### PR TITLE
Update lucky parking project page

### LINKED ISSUE #2990: Update Lucky Parking project page
### Overview
We need to ensure that links and info on the Lucky Parking project page resolve properly and are up to date.

### Action Items
- [x] Update the test site url for the [lucky parking project page](http://www.luckyparking.org/) to http://www.luckyparking.org/
- [x] Update the project page info for current dev team lead

## Note
Bonnie asked for me to update the link with a pull request. I'm creating this issue as a way to track it, but I will immediately open a related PR to resolve it.

### Resources/Instructions

- [Lucky Parking Project page](https://www.hackforla.org/projects/lucky-parking)

### PR DESCRIPTION
**Pull request by macho-catt**
Fixes #2990 

### What changes did you make and why did you make them ?

  - Update the test site url to the correct one
  - Update dev lead

## Note
As mentioned in the issue I opened, Bonnie asked me to just create a pull request to resolve this. Thanks.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Full page before</summary>
  
full-page-after

</details>

<details>
<summary>Full page after</summary>

full-page-before

</details>

### CODE REVIEW

**Comment by answebdev** [comment]
Review ETA: Tuesday, 3/22/2022
Availability: 3 hours

**Comment by blulady** [comment]
ETA: Monday 3.21.22
Availability: Monday 3.22.22 1-6pm

**Review by blulady — APPROVED** [review]
Looks good! There's a linked issue that matches.  The pull request is done with the correct branch.  When I viewed the branch locally the test site url for the [lucky parking project page](http://www.luckyparking.org/) to http://www.luckyparking.org/ and the lead developer had been changed from Matthew Ginther to Matthew Cacho. The links work as intended both to the updated developer slack/github and the http://www.luckyparking.org/. The source code looks succinct and clean.
Great Job!!

**Review by answebdev — APPROVED** [review]
@macho-catt Thank you for submitting your PR for this issue. I can see that you have updated the test site url for the lucky parking project page to http://www.luckyparking.org/, and have also updated the project page info for current dev team lead to Matthew Cacho, and I can see these changes in the browser as well (and the link directs to the correct page). Great job!

**Pull request merged**
