### PR TITLE
Add github handle for Joshua Fishman in tech-work-experience

### LINKED ISSUE #7240: Add github-handle for Joshua Fishman in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Joshua Fishman
```
with
```
- name: Joshua Fishman
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by vorleakyek**
Fixes #7240
### What changes did you make?
  
  - adding "github-handle:" under "- name: Joshua Fishman" in the tech-work-experience.md 

### Why did you make the changes (we will use this info to test)?
  
  - to create a single variable github-handle to hold the github handle
  - github-handle will replace the github and picture variables

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

### CODE REVIEW

**Comment by k-cardon** [comment]
Looks good @vorleakyek! The pull request is written correctly, I verified that you made the correct changes to the site, and it did not change the appearance. Thanks for working on this!

**Review by k-cardon — APPROVED** [review]
Looks correct!

**Review by bexux — APPROVED** [review]
Great job! PR description is well written, issue is linked, branches are correct, and the changes are made correctly in the correct file.

**Review by codyyjxn — APPROVED** [review]
Nice work! I wanted to mention that it might be helpful to simplify the branch names for future reference. It could make it easier for everyone to identify and work with them quickly.

Just a small suggestion to consider—thanks for all your hard work!

**Comment by codyyjxn** [comment]
Review ETA: 8/26/24, 11:59pm PT
Availability: 9am-5pm M > F

**Review by kgold2018 — APPROVED** [review]
Hi @vorleakyek ! You followed all the steps - approved. 
I can see that you added the GitHub handle line in the right place and that the webpage's appearance has remained unchanged. Thank you!

**Comment by t-will-gillis** [comment]
Hey @vorleakyek For future reference- please do not request a review from anyone unless you have already contacted that person, or if you need a re-review from that person. 

I am mentioning this because one of the reviewers you requested is no longer active, so you would be waiting a very long time for them to review your PR.

**Comment by vorleakyek** [comment]
Thanks @t-will-gillis, but I don't think I requested a review from anyone. I thought it was automated after I opened the PR.

**Comment by t-will-gillis** [comment]
Hi @vorleakyek 

My mistake! One of the other reviewers requested that person, not you.

**Pull request merged**
