### PR TITLE
Update 311-data.md

### LINKED ISSUE #5921: Correction on 311-data.md page: Sanju Venugopal
### Overview
While reviewing an unrelated PR, I noticed that the entry for "Sanju Venugopal" misspelled their name. 

### Action Items

- [x] Change "Saju Venugopal" to "Sanju Venugopal"

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #5921 
### What changes did you make?
  - In leadership section, changed "Saju Venugopal" to "Sanju Venugopal"

### Why did you make the changes (we will use this info to test)?
  - To correct Sanju's name
  - Referencing ER #5786 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-11-19 134922

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-19 135212

</details>

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: Evenings
ETA: By EoD 11/21

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: By EoD 11/20

**Review by freaky4wrld — APPROVED** [review]
Hey @t-will-gillis, amazing presence of mind, like hats off to you for noticing these tiny things, and how quickly you made those changes. The issue is approved by me
- the to/from branch looks good
- the changes are correctly made
- the visual changes are clearly seen in the local environment

Good to go....... great work again

**Review by MattChau01 — COMMENTED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5921 was properly referenced. ✅ 
- As mentioned on the original issue, the line of code was properly updated. ✅

**Pull request merged**
