### PR TITLE
Change-linter-version-2479

### LINKED ISSUE #2479: GitHub Actions: Change Linter version to @v4 when source code bug is fixed
### Dependency
~Source code fix on https://github.com/github/super-linter/issues/2128~

### Overview
We have to update the version for our linter when the source code bug is fixed to ensure that everything is up to date.

### Details
There is a bug with super linter v4.8.3 (the latest version) where the image for the release is missing. Because of this, all GitHub actions related to linting will fail. There is an open issue in the repository of the source code:
https://github.com/github/super-linter/issues/2128

I temporarily updated the version number to v4.8.1 where everything is still working

### Action Items
- [x] Once the bug is fixed in the linked issue above, revert the version number back in line 22 to:
```
        uses: github/super-linter@v4
```
- [x] Confirm the linter works after the change

### Resources/Instructions
Issue opened on the source code of the repo: https://github.com/github/super-linter/issues/2128
[lint-scss.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/lint-scss.yml)

### PR DESCRIPTION
**Pull request by esantiano**
Fixes #2479

### What changes did you make and why did you make them ?

  - checked @v4.8.3 to make sure that bug had been fixed.
  - changed line 22 "@v4.8.1 to @v4" after confirming the bug had been fixed.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by tunglinn** [comment]
ETA: tonight
Availability: 1hr

**Comment by tunglinn** [comment]
For other reviewers:
`git checkout -b esantiano-change-linter-version-2479 gh-pages`
`git pull https://github.com/esantiano/website.git change-linter-version-2479`

**Comment by tunglinn** [comment]
The checks didn't run for this PR. Is there a way to get it to run?
This is important because part of this PR is to make sure the linter works with the changes.

**Comment by arpitapandya** [comment]
@esantiano Can we close this PR, and open a new one, please?
canyouclosetheprpleaseandcreatenew

**Pull request closed without merging**
