### PR TITLE
Update labels: Issue Template: alt-text-audit--dev

### LINKED ISSUE #4477: Update labels: Issue Template: alt-text-audit--dev
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/alt-text-audit--dev.md`
- [x] Replace the following line
   ```
   labels: 'Feature: Accessibility, good first issue, ready for dev lead, role: back end/devOps, role: front end, size: 1pt
   ```
   with
   ```
   labels: ['Feature: Accessibility', 'good first issue', 'ready for dev lead', 'role: back end/devOps', 'role: front end', 'size: 1pt', 'Complexity: Missing']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL]

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/alt-text-audit--dev.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by Sk-223**
Fixes #4477

### What changes did you make and why did you make them ?

  - Updated labels string
    - From:
    ```labels: 'Feature: Accessibility, good first issue, ready for dev lead, role: back end/devOps, role: front end, size: 1pt```

    - To:  
     ```labels: ['Feature: Accessibility', 'good first issue', 'ready for dev lead', 'role: back end/devOps', 'role: front end', 'size: 1pt', 'Complexity: Missing']```
  - Updated labels to show added "Complexity: Missing"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes to the website.

### Resources/Instructions
- [Link to Issue Template](https://github.com/Sk-223/website/issues/new?assignees=&labels=Feature%3A+Accessibility%2Cgood+first+issue%2Cready+for+dev+lead%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2Csize%3A+1pt%2CComplexity%3A+Missing&projects=&template=alt-text-audit--dev.md&title=%5BINSERT+PAGE+HERE%5D%3A+Update+alt+text+for+%5BINSERT+IMAGE+NAME+HERE%5D+image+to+adhere+to+WCAG)

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Comment by kiwookim** [comment]
Availability: W - F 9-5PM
ETA: 6/22 EOD

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @Sk-223 thank you for a great job on this PR.  Your code change was clean and correct, you followed an involved test procedure and you created a PR with correctly formed branches.  My only request is that in the PR, for the convenience of the other reviewers, could you add a bullet point with the updated labels string, and another bullet point explaining that the changes were made so the GitHub bot would not remove any labels.  Also under "Screenshots of Proposed Changes of the website", you can write "No visual changes to the website".  Thank you

**Review by Sebster3 — APPROVED** [review]
Hey @Sk-223, great job on this PR! The branches are set correctly, the changes were done neatly, and the issue template in your fork of the repo displays the correct default labels. Approved 👍🏽

**Review by roslynwythe — APPROVED** [review]
Thank you @Sk-223 for your work on this issue and being responsive to requests for changes.

**Pull request merged**
