### PR TITLE
Img tag refactor citizen engagement 4446

### LINKED ISSUE #4446: img Tag Refactor: Citizen Engagement page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/citizen-engagement.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="org-img org-img-large" src="{{ partner.image }}" alt="{{ partner.name }}"/>
```
to
```
<img class="org-img org-img-large" src="{{ partner.image }}" alt="{{ partner.name }}">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html
2. Webpage: https://www.hackforla.org/citizen-engagement
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by ghost**
Fixes #4446 

### What changes did you make and why did you make them ?

  -   Removed ending '/ ' in img HTML tag with class 'org-img org-img-large' to make codebase to be consistent with how HackForLA uses img HTML tags.
  
  - Did not remove ending '/' for HTML tag with class of 'header-hero-image' as ticket did not call for this to be fixed.

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: EOD 04/09
Availability: 3-5pm PST, 04/09

**Review by arcan9 — DISMISSED** [review]
Good job @DeitchDustin!

- You made the changes that were outlined in the issue
- Made in the correct branch
- Linked issue
- Stated reason for the change

**Comment by steven-positive-tran** [comment]
Review ETA: EOD 04/09
Availability: 10-12pm PST, 04/09

**Review by steven-positive-tran — CHANGES_REQUESTED** [review]
Good job the issue has been done and you have commited to the right branch.

I do see that 2 lines have been changed that wasn't in the scope where you removed a space in header-hero alt for the citizen-engagement.html and added a space for the join-us.html alt and I don't see to do that in the linked issue. 

I think the merge team could just merge this pull request but they might ask to fix that issue.

image
image

**Review by steven-positive-tran — APPROVED** [review]
Thanks for fixing that issue.

**Pull request merged**
