### PR TITLE
Sort events by project name after by time

### LINKED ISSUE #2751: Add condition to event sorting to group by project.
### Overview
Would like to update display of events so that team meetings from the same team appear together if they are at the same time.

### Details
Currently Home Unite Us has two meetings at the same time that alternate from week to week. The display order is separating them, so someone might not think to look for the second meeting. After sorting events by time, we need to add a sort by team to make sure that the two meetings are together so someone is more likely to see both.

### Action Items
- [x] Review [Right column content](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html) file
- [x] Analyze how the events are currently being sorted using [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js) and [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) files
- [x] Make changes to [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js) or/and [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) files to ensure meetings from same team appear together or any other way we can achieve the same
- [x] Please ensure the look and functionality of the events page is still the same.

### Resources/Instructions
<details>
<summary>Screenshot from the events page</summary>

image

</details>

- [Events page](https://www.hackforla.org/events/)
- [Right column content html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html) 
- [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js)  
- [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js)

### PR DESCRIPTION
**Pull request by luke-karis**
Fixes #2751

### What changes did you make and why did you make them ?

  - Changed events to be sorted by project name after the time so that meetings with the same name will appear next to each other.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

2751_before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
2751_after

</details>

### CODE REVIEW

**Review by usaboo — APPROVED** [review]
Hi Luke,

So far so good. Your change makes sense and I can see the difference when I docker-compose up your branch, however is this change only for issue #2751 or anytime such a situation might arise in the future?

**Comment by luke-karis** [comment]
Hey @usaboo, thanks for the review. I believe that this change will only affect the list for this issue and I'm not sure what you mean by "anytime such a situation might arise in the future".

**Comment by usaboo** [comment]
Hi Luke, what I mean by that is that right now, the 2 events for Home Unite Us that are at 7PM PST on Tuesday are below each other, which is what we want. 

However in the future, lets say there are 2 events for Expunge Assist(a different project) that are at 10PM on Wednesday, would they also be next to each other?

I checked your code and I think they would be, however I just wanted to make it sure with you too!

Hope it makes sense now.

**Comment by tamara-snyder** [comment]
Availability: 2 hours
Review ETA: Monday, March 14, 2022

**Review by tamara-snyder — APPROVED** [review]
What an elegant solution! The changes look correct to me — I can see that the events are sorted by time first and then alphabetically if they start at the same time. This ensures that events from the same team are grouped together. Great job working on this.

**Pull request merged**
