### PR TITLE
Added GitHub handle for Bryan Wu

### LINKED ISSUE #6735: Add github-handle for Bryan Wu in food-oasis.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: Bryan Wu
```
with
```
- name: Bryan Wu
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by andyphancode**
Fixes #6735

### What changes did you make?
  - replaced `- name: Bryan Wu` with ```- name: Bryan Wu  github-handle: ```

### Why did you make the changes (we will use this info to test)?
  - Use single github-handle variable to replace the github and picture variables

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
No visual changes were made
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
None detected
</details>

### CODE REVIEW

**Comment by ino-iosdev** [comment]
Review ETA: 10PM 5/29/24 
Availability: Flexible except for Wed. after till late June

**Comment by ino-iosdev** [comment]
Hi @andyphancode For the naming of the title

 - You could remove "6735" from the title, it would be a cleaner format so that it doesn't get stacked with the PR number right behind it:)
 - I would suggest something like "Added Github-handle for Bryan Wu" for accuracy instead of "Updated"since the handle did not exist before, cheers!

**Review by ino-iosdev — CHANGES_REQUESTED** [review]
Hey @andyphancode ,

The changes look good, once you have updated the title format mentioned in the comments, I will be able to approve the change, thank you for your patience:)

**Comment by andyphancode** [comment]
> Hey @andyphancode ,
> 
> The changes look good, once you have updated the title format mentioned in the comments, I will be able to approve the change, thank you for your patience:)

@ino-iosdev Went ahead and changed the title! Thanks.

**Comment by jphamtv** [comment]
Hey @andyphancode, make sure to re-request reviews from the original reviewer after you have made the requested changes by clicking on the circular arrows icon next to their names. I have done this for you so this is just for future reference. Thanks!
Screenshot 2024-05-30 at 12 00 19

**Comment by DrAcula27** [comment]
ETA: 1 June 2024
Availability: weekdays 5pm - 8pm Pacific time

**Review by ino-iosdev — APPROVED** [review]
Hi @andyphancode , thank you so much for updating the title, looking great!
 
- Naming was appropriate
- Direction between branches "from" and "to" are clear
- The changes and why were clear
- PR issue link was clear
- No visual changes to the website
 
Great job, thank you for contributing!

**Comment by del9ra** [comment]
Review ETA: 9PM 5/31/24
Availability: 1-5 PM Friday

**Review by del9ra — APPROVED** [review]
Hey @andyphancode,
* The branching was done correctly
* You can delete everything under "Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)" and leave only the following: “No visual changes to the website”.
* The issue is properly linked
* Your explanation of changes is clear 
* The look of the project webpage hasn't changed
Great job and thanks for your contribution to the website!

**Pull request merged**
