### PR TITLE
Updates Project Profile: Lucky Parking (Removed Yuting Chu)

### LINKED ISSUE #5796: Update Project Profile: Lucky Parking (Remove Yuting Chu)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Yuting Chu
    role: Product Manager Lead
    links:
      slack: 'https://hackforla.slack.com/team/U03J4E55KCH'
      github: 'https://github.com/ychu196'
    picture: https://avatars.githubusercontent.com/ychu196
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #5796 

### What changes did you make?
  - Removed Yuting Chu from Lucky Parking profile page

### Why did you make the changes (we will use this info to test)?
  - To update the Lucky Parking profile page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-11-22 at 12 54 00 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-22 at 12 56 24 PM

</details>

### CODE REVIEW

**Comment by jphamtv** [comment]
Availability for this week: Monday-Friday 12–2 PM, 8–10 PM (PST) 
My estimated ETA for completing this issue: 10 PM 11/22/23

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 11/23

**Review by freaky4wrld — APPROVED** [review]
Hi there @sornekian , great work there all the work assigned to you in the issue is done correctly
- the to/from branch looks good
- the visual changes are completely applied in the local environment
- the changes specified is done correctly and are apt
- the issue linked is correct too

Great work there, I approve this PR.......

**Review by jphamtv — APPROVED** [review]
The pull request was done with the correct branch, and the issue is linked correctly. Changes in the source code are applicable and clean. The update looks good in the browser. Awesome job!

**Pull request merged**
