### PR TITLE
Update engineering leadership #4025

### LINKED ISSUE #4025: Communities of Practice information updates: Engineering
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Communities of Practice - Engineering project card needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `internal/communities/engineering.yml` file and find the `leadership` variable.
- [x] Remove the following member's info
  - [x] Ava Li
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Micah Elm
Role: Co -Lead
GitHub Handle: MicahBear
Slack Member ID: U04N8H0V72R
  - [x] Name: AJ Price
Role: Co-Lead
GitHub Handle: mxajprice
Slack Member ID: U02UZ5BK8UB
  - [x] Name: Fang Yi Liu
Role: Co-Lead
GitHub Handle: fyliu
Slack Member ID: UCE01B4AX
  - [x] Name: Alejandro Gomez
Role: Co-Lead
Github: agosmou
Slack Member ID: U04HFRQ5Y12
  - [x] Name: Harrison Katz
Role: Co-Lead
GitHub Handle: hkatzdev
Slack Member ID: U04PFCPK6EP
- [x] Verify the changes by viewing the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [engineering.yml](https://github.com/hackforla/website/blame/gh-pages/_data/internal/communities/engineering.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jch1013**
Fixes #4025

### What changes did you make and why did you make them ?

  - Updated personal information for engineering community of practice leads

### Screenshots of Proposed Changes Of The Website

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
Availability: Flexible
ETA: 03/01 EOD

**Comment by KazushiR** [comment]
@jch1013 Hello Jackson. I see that you have compeleted everything and it all looks good. Once you have checked off the action items in the original issue, I will go ahead and approve of the issue. If you have anymore questions, feel free to reach out to me.

**Comment by mademarc** [comment]
Review ETA:  7:45PM 2/28/23
Availability: 1Hr

**Review by mademarc — COMMENTED** [review]
@jch1013 This is code is very readable  also great job on this :)

**Comment by jch1013** [comment]
@KazushiR I have finished checking off the tasks on the original issue, thanks!

**Review by KazushiR — APPROVED** [review]
There didn't seem to be any issues when implimenting the changes. Good job!

**Comment by roslynwythe** [comment]
Availability: 3/1 11 pm - 11:30 pm
ETA: noon 3/2

**Review by roslynwythe — APPROVED** [review]
@jch1013 Thank you for a job well done.  The branches are correct, code looks clean and correct, and it looks great in the browser.

**Comment by roslynwythe** [comment]
Hi @mademarc thank you for reviewing this issue.  From your comment above I'm assuming that you approve this PR, but in the future, to clarify your intention, please submit the "Review Changes" form found that can be found on the "Files Changed" page.   Thank you!

**Pull request merged**
