### PR TITLE
added Ida Valenzuela as leadership for Civic Tech Jobs

### LINKED ISSUE #7555: Update Project Profile: Civic Tech Jobs Add Ida Valenzuela
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Ida Valenzuela
    github-handle: irais-valenzuela
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U062NBBNFA7
      github: https://github.com/irais-valenzuela
    picture: https://avatars.githubusercontent.com/irais-valenzuela
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
[^3]: initiating ER:  #7521

### PR DESCRIPTION
**Pull request by siyunfeng**
Fixes #7555

### What changes did you make?
  
  - updated leadership info for Civic Tech Jobs (added Ida Valenzuela)

### Why did you make the changes (we will use this info to test)?
  
  - to ensure the leadership info for project Civic Tech Jobs is up-to-date

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>

</details>

### CODE REVIEW

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: Thurs Oct 10

**Review by ramitaarora — APPROVED** [review]
Looks great!
- You made the pull request from the correct branch
- I see the changes in the IDE
- The changes are correctly reflected on the civic tech jobs projects page
- One improvement is that you can have a better branch name, such as added-ida-valenzuela-leadership-profile-7555

Nice work, and thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
Great job @siyunfeng on your first issue! The changes look good, the branch is named correctly, and the title is clear. I also appreciate the before-and-after screenshots, as they effectively illustrate what has been changed.

For the section `Why did you make the changes (we will use this info to test)?`, I recommend providing an explanation of why this change was necessary. Usually, the original issue should give some context for this. Additionally, it would be helpful if you could address the question posed by the bot in the comments section of the original issue.

Other than that, excellent work, and thank you for your contributions! Keep it up!

**Comment by siyunfeng** [comment]
> Looks great!
> 
> * You made the pull request from the correct branch
> * I see the changes in the IDE
> * The changes are correctly reflected on the civic tech jobs projects page
> * One improvement is that you can have a better branch name, such as added-ida-valenzuela-leadership-profile-7555
> 
> Nice work, and thank you for your contribution!

Thank you, Ramita! I'll name the branch with more specific details next time.

**Comment by siyunfeng** [comment]
> Great job @siyunfeng on your first issue! The changes look good, the branch is named correctly, and the title is clear. I also appreciate the before-and-after screenshots, as they effectively illustrate what has been changed.
> 
> For the section `Why did you make the changes (we will use this info to test)?`, I recommend providing an explanation of why this change was necessary. Usually, the original issue should give some context for this. Additionally, it would be helpful if you could address the question posed by the bot in the comments section of the original issue.
> 
> Other than that, excellent work, and thank you for your contributions! Keep it up!

Thank you, @codyyjxn! I updated the answer to `Why did you make the changes (we will use this info to test)?` and left a comment for `Availability` and `ETA` in the original issue according to your advice.

**Pull request merged**
