### PR TITLE
Update navbar

### LINKED ISSUE #1257: Add Join page to the nav bar
### Dependencies

These issues must be completed before the page can be added to the nav bar:

~~#1251~~   ,  ~~#1252~~  , ~~#1253~~  , ~~#1254~~ , ~~#1255~~ , #1256

### Overview
We need to add the Join page to the top nav bar of the Hack for LA website when the page is ready, so that users can access it

### Action Items
- [x] Research how to update the nav bar with a new link
- [x] Add Join page to the nav bar

### Resources/Instructions
[Join page](https://www.hackforla.org/join-us)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### PR DESCRIPTION
**Pull request by akibrhast**
Closes #1257 

- [x]  Remove `Connect` and replace with  `Join` in the navbar

 You can see the changes here https://akibrhast.github.io/website/join

### CODE REVIEW

**Comment by erikaBell** [comment]
### "Connect" returns after you click on "Join"

<details>
<summary>Example</summary>
mainPg
joinPg
</details>

<details>
<summary>What's shown when inspecting the return of "Connect"</summary>
Screen Shot 2021-04-06 at 11 06 32 PM
</details>

**Comment by erikaBell** [comment]
Looks good (-: !

**Review by erikaBell — APPROVED** [review]

**Review by daniellex0 — CHANGES_REQUESTED** [review]
Please change to "Join Us" instead of Join (this is following coversation with @ExperimentsInHonesty ). Also please finish and merge #1392 before merging this issue)

**Review by jbubar — APPROVED** [review]
Ready to merge :))

**Comment by daniellex0** [comment]
Great! (but only after finishing and merging #1392 please)

**Pull request merged**
