### PR TITLE
DO NOT MERGE: Fix meeting name display on Events Page and Project Details Pages

### LINKED ISSUE #4054: Fix the meeting names for project details page
### Overview
On the events and project details pages, we are currently showing the meetings `details` as the name of the meetings. For this issue, we will change it to show the meeting `name` instead.

### Action Items
- [x] Change the `project.js` file to show meeting names instead of meeting descriptions on the individual project details pages ( i.e. https://www.hackforla.org/projects/vrms )
- [x] Change the `api-events.js` file to show the meeting `name` instead of `description` on the [events](https://www.hackforla.org/events/) page
- [x] Check that the VRMS meeting on "Sun 7:00 pm - 8:00 pm" displays the name `VRMS All Team` and NOT `Only this part will show website` on both the [VRMS details page](https://www.hackforla.org/projects/vrms) and the [Events Page](https://www.hackforla.org/events/)

### Instructions
- Do not merge the PR associated with this issue until VRMS and Bonnie are ready sometime on Sunday March 5th

### Resources

<details><summary>The Event Object coming from VRMS API for the VRMS Sun 7 - 8PM meeting </summary>

image

</details>

<details><summary>Events Page</summary>

image

</details>

<details><summary>VMRS details page</summary>

image

</details>

### PR DESCRIPTION
**Pull request by MattPereira**
Fixes #4054

### Merge Team Instructions
- Do not merge this pull request yet because we are waiting on VRMS to update the meeting name fields in their database before making this change

### What changes did you make and why did you make them ?
  - Changed `api-events.js` so that meeting names will show instead of meeting descriptions on the Events Page 
  - Changed `project.js` so that meeting names will show instead of meeting descriptions on all Project Details pages
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<h2>Events page</h2>

image

<h2>VRMS project details page</h2>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

<h2>Events page</h2>

image

<h2>VRMS project details page</h2>

image

</details>

### CODE REVIEW

**Comment by ExperimentsInHonesty** [comment]
@MattPereira FYI, I have made a meeting update in VRMS to what is currently our wed meeting 
see on website https://www.hackforla.org/projects/website
image

to move it to sunday 9am pst 
image


and I tried to take out the description, but it seems like it requires it, so I added a dash instead, which we can plan to ignore when we later revise the display on website to be
`Meeting name` - Meeting Description`

This will require you to put back in the event.description when we are ready to make that change.  Examples of how I think this will be used
When a team meets weekly, it only needs to be the `Meeting name`
When a team meets 2x a month (1st and 3rd wed), then it would be `Meeting name` - Meeting Description`

Ideally, VRMS would make the description field optional.  But given how long it takes things to happen at VRMS, hackforla.org website will be able to ignore any comments whose value is equal to the dash symbol `-`

**Comment by MattPereira** [comment]
@ExperimentsInHonesty 

I started to draft an issue to allow for empty meeting descriptions
- https://github.com/hackforla/VRMS/issues/1310

But I noticed that the requested functionality does seem to be possible on the current development branch. 

The commit we have deployed to production is pretty old and needs to be updated.

I will investigate further and let you know what I figure out.

**Comment by MattPereira** [comment]
@ExperimentsInHonesty 

I deployed what we have on the development branch right now to production last night incase prod was running on an old commit. 

I've had no trouble creating and updating recurring events with no `description` at [dev.vrms.io](https://dev.vrms.io/)

But I don't have access to an account on the production version of the site to verify for sure

image



image

**Comment by Jaretzbalba** [comment]
Availability: 2 hour
ETA: EOD 3/14/23

**Comment by Jaretzbalba** [comment]
@MattPereira I just want to double-check that the pages you have shown as examples won't show up the same on my computer because the VRMS database hasn't been updated, correct? Because the current website for me shows this for the vrms project page meeting section.

<details><summary>VRMS details page before changes applied</summary>

Screenshot 2023-03-14 at 2 28 49 PM

</details>

<details><summary>VRMS details page after changes applied</summary>

Screenshot 2023-03-14 at 2 28 38 PM

</details>

**Comment by MattPereira** [comment]
@Jaretzbalba the vrms database has had changes since this PR and associated issue were created. 

You wont be able to use the screenshots or last action item for reference when reviewing

You may approve if you think I made the appropriate changes to show meeting names instead of descriptions, but you can also walk away from this review if you prefer situations with more clarity

I still havent heard from Bonnie about when she wants this change to go live yet

**Comment by Jaretzbalba** [comment]
@MattPereira All good! Based on what was requested in the issue, I'd say that everything looks good. I see that the code was updated to show the name property instead of the description, and it does show the correct data from VRMS even if it seems to be a work in progress still.

**Review by jdingeman — APPROVED** [review]
Approving for merge.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I'm not sure if this pr was given the green light to be merged or not from VRMS since I know they needed to get some things sorted out on their end. The merging of this pr has caused problems with how the meeting names are displayed for some teams on [Events page](https://www.hackforla.org/events/) and the project detailed pages, including but not limited to:
-  https://www.hackforla.org/projects/access-the-data
- https://www.hackforla.org/projects/brigade-organizers-playbook
- https://www.hackforla.org/projects/design-systems
- https://www.hackforla.org/projects/expunge-assist
- https://www.hackforla.org/projects/lucky-parking

**Comment by MattPereira** [comment]
@JessicaLucindaCheng Bonnie requested this PR be merged during the VRMS meeting last night. 

The meeting names look wrong because the names of the recurring events still haven't been updated in the VRMS database, but I believe the PR is successfully displaying the correct property from the reccuring events object

<details><summary>See screenshots</summary>

vrms

image

</details>

**Comment by ExperimentsInHonesty** [comment]
I approved it.  We were stuck in a limbo and the site is going to have bad data for a week while I get the project leads to update.

**Pull request merged**
