### PR TITLE
add github handle to name: Hannah Zulueta in projects file

### LINKED ISSUE #6734: Add github-handle for Hannah Zulueta in food-oasis.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: Hannah Zulueta
```
with
```
- name: Hannah Zulueta
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by curbeammonae**
Fixes #6734

### What changes did you make?
  -I added "github-handle" to name: Hannah Zulueta in projects file

### Why did you make the changes (we will use this info to test)?
-To create a single variable to hold the github handle for each member of the leadership team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by curbeammonae** [comment]
Provide Update
1. Progress - I have completed the task by adding github handle to name Hannah Zulueta in the food oasis project file
2. Blockers - Initially one of my checks failed, however after I corrected my pull request instructions it passed
3. Availability - 20 hours
4. ETA - Completed

**Review by dcotelessa — APPROVED** [review]

**Comment by LRenDO** [comment]
Hi @mrodz! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.

**Comment by mrodz** [comment]
ETA: 12PM 5/29
Availability: 4PM-9PM MTWThF

**Review by mrodz — APPROVED** [review]
Hey @curbeammonae! Congrats on the PR.

- Branches `from` and `to` are correct.
- You linked to the correct issue.
- Nice and brief description of what was changed/why.
- Correctly stated `No visual changes`.
- Followed the checklist of items in the issue.

Good stuff! Keep up the good work.

**Pull request merged**
