### PR TITLE
Added github-handle for Brian #7249

### LINKED ISSUE #7249: Add github-handle for Brian Dick in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Brian Dick
```
with
```
- name: Brian Dick
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by maadeshsivakumar**
Fixes #7249

### What changes did you make?
  - Added `github-handle` variable for Brian
  

### Why did you make the changes (we will use this info to test)?
  - This variable is to replace the `github` and `picture` in the future

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- (N/A)

### CODE REVIEW

**Comment by alabador** [comment]
Review ETA: 6 PM 8/12/24
Availability: 5-7 PM Monday

**Review by alabador — APPROVED** [review]
Hi @maadeshsivakumar, good work.

- Branches are set up correctly
- Correct issue is linked
- Reason for changes is clear
- No visual changes needed

Thanks for working on this!

**Comment by roslynwythe** [comment]
@hussainmudassir Please add a comment with your availability and ETA for reviewing this PR.  Thank you!

**Review by pluto-bell — APPROVED** [review]
Looks great!

- Your comments are clear
- The issue is linked
- All items have been setup properly

Good work.

**Comment by hussainmudassir** [comment]
Looks good.

**Review by hussainmudassir — COMMENTED** [review]
Looks good

**Pull request merged**
