### PR TITLE
Remove CfA from brigade orgranizer's playbook

### LINKED ISSUE #5411: remove mention of CfA from Brigade Organizer's Playbook project info
### Overview
We need to remove mention of CfA from the Brigade Organizer's Playbook list of partners and description.

### Action Items
- [x] In your local IDE, navigate to `_projects/brigade-organizers-playbook.md` 
- [x] replace
```
partner: Code for America (CfA), CfA National Advisory Council, Code for Boston, Code for Charlottesville
```
with
```
partner: Code for Boston, Code for Charlottesville 
```
- [x] replace
```
description: Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.  The original project was started as part of the Code for America National Advisory Council with Hack for LA as the volunteer staffing partner.
```
with
```
description: Civic tech volunteer organizations often start building from scratch, which uses up valuable resources (time, labor and momentum).  This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each other's work, improving outcomes for the civic tech ecosystem.
```
- [x] Using Docker, confirm that the changes are reflected on the Brigade Organizer's Playbook project webpage, and the surrounding elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md
2. Brigade Organizer's Playbook project webpage(s): https://www.hackforla.org/projects/brigade-organizers-playbook

### PR DESCRIPTION
**Pull request by agutiernc**
Fixes #5411

### What changes did you make?
  - Updated the partner and description variables with the requested information

### Why did you make the changes (we will use this info to test)?
  - To remove mention of CfA from the Brigade Organizer's Playbook list of partners and description

### Screenshots of Proposed Changes Of The Website
<details>
<summary>Visuals before changes are applied</summary>

brigade-old
</details>

<details>
<summary>Visuals after changes are applied</summary>
 
brigade-new

</details>

### CODE REVIEW

**Comment by allison-truhlar** [comment]
ETA: Friday 9/8 noon ET
Availability: Thursday afternoon, Friday morning (ET)

**Comment by antho-zng** [comment]
ETA: Sept 7, 5pm PT
Availability: 9-5pm ET

**Review by antho-zng — APPROVED** [review]
Hi @agutiernc! This looks good to me. The revised text is showing up as it should locally, and the surrounding elements are unchanged in desktop, mobile, and tablet views. Good job!

**Review by allison-truhlar — APPROVED** [review]
Hi @agutiernc! I agree with the other reviewer - this pull request looks good! You made the requested changes to the markdown file and the visual changes are showing up correctly locally. Good work on this issue and pull request!

**Pull request merged**
