### PR TITLE
Fix bug in add update label weekly gha 3341

### LINKED ISSUE #3341: GitHub Actions: Bot adding and removing "Status: Updated" and "To Update!" label
### Overview
There is a bug with the Github bot in which it both adds and removes the "Status: Updated" label. This should be fixed to avoid confusion and to make sure that the proper labels are being applied.

### Action Items
- [x] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [x] Review the [add-label.js](https://github.com/hackforla/website/blob/2fe355b396ed7f785d382505b8c2ecafe09cb486/github-actions/add-update-label-weekly/add-label.js#L226) file, to understand how the bot adds and removes labels from the issue.
- [x] Understand why the Github action bot adds and removes the "Status: Updated" and the "To Update!" label.
- [x] Change the code logic to fix this error

### Checks
- [x] Test in your local environment that it works

### Resources/Instructions
Relevant files:
- https://github.com/hackforla/website/blob/2fe355b396ed7f785d382505b8c2ecafe09cb486/github-actions/add-update-label-weekly/add-label.js
- https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml

Relevant Issues:
Status: Updated Bug:
- #2497 
- #2561 
- #2397 
- #3059 

To Update! Bug:
- #2462 
- #2317

Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by bzzz-coding**
Fixes #3341 

### What changes did you make and why did you make them ?

- Refactored the isTimelineOutdated function as the logic was buggy and the function exits too early for certain cases. 
- Refactored part of the main function so the bot adds and removes labels correctly.
- Added comments and console logging to help understand, debug, and revise the code in the future.

### CODE REVIEW

**Comment by bzzz-coding** [comment]
I'll start testing GHA using another branch in my own repo. I'll also try testing following @tunglinn 's instructions (Thank you! ❤️), but I want to submit this PR now so I don't further delay this issue/discussion.

**Comment by t-will-gillis** [comment]
availability: Sat-Sun, 3/4-3/5, 12-5
eta: Sun

**Comment by MattPereira** [comment]
availability: Sat-Sun, 3/4-3/5, 12-5
eta: Sun

**Comment by bzzz-coding** [comment]
Update 3/4/23:
I've set up my forked repo for GHA testing (testing both the current code and code in my PR). Here's my testing branch: https://github.com/bzzz-coding/HfLA-website
I'll share more findings after running more tests.

- Design question: 
  - my current understanding is that if an issue has been cross-referenced in a PR by an assignee, the issue is considered updated regardless of when this event happened--even if the cross-reference happened 2 weeks ago, we want the issue to have a `Status: Updated` label--is this correct?
  - If an assignee was recently assigned (say, 5 days ago) but has not commented/fixed the issue in a PR, should we add an update-related label to the issue? It's not quite "updated" but it's also not outdated. 

- I noticed in the GHA running log there are errors when running remove/add labels because the label does not exist. I think this is because in the main function, when removeLabels and addLabels are called, labels are passed in regardless of whether the issue currently has them. These error requests are out of the scope of this issue, but may be addressed in a future issue?

**Comment by t-will-gillis** [comment]
In conversations with @bzzz-coding during testing we would like to confirm the intent with the two labels `Status: Updated` and `To Update !`. The current code is a bit convoluted and it is difficult to determine what needs to be changed since we aren’t entirely certain of original intent. There are also discrepancies between how the GHA actually operates and the descriptions in the wikis.  

The open questions are to confirm the intent when:
- Issue first assigned, but assignee **does not add** a comment prior to the weekly GHA running. 
  - Applies to two types of issues: 
    - The prework checklists. 
    - When someone self-assigns and moves issue to ‘New Issue Approval’. 
  - Currently- Prework only
    - Bot sometimes adds & deletes `Status: Updated`, then adds `To Update !`
    - Or Bot adds `Status: Updated` 
  - Proposed- Prework we would want no labels applied until the GHA runs twice, then `To Update !` <if possible
  - Issue newly assigned but no comment- want the `To Update !` label applied immediately? Unclear how to do this. Maybe label applied when assigned?
- Existing issue, and the assignee’s last comment was within the last week.  
  - Proposed- `Status: Updated`
- Existing issue, and the assignee’s last comment was within the last two weeks.
  - Proposed- `To Update !`
- Existing issue, and the assignee’s last comment was over two weeks old.
  - Proposed- `2 weeks inactive`
- Issue has a linked PR
  - Proposed- all labels removed from issue 
- Additional:
  - Comment by anyone other than assignee(s) doesn’t count

**Comment by t-will-gillis** [comment]
Hi @bzzz-coding - here are some notes that hopefully clarify this issue. This confirms what we have been discussing for the `2 weeks inactive` and `To Update !` label timing. The main thing here is that the `Status: Updated` label will be applied manually or by a future issue's action but not by this action (which would only check if the label exists and remove it if needed. )

From the conversation with Bonnie during the Sunday meeting, 12 March 23:
-	The `Status: Updated` label should be applied immediately and automatically/ manually to the issue after the assignee makes a comment. 
  - Since the `add-update-label-weekly.yml` file as currently written runs weekly: this action would not be adding the `Status: Updated` label.
  - This action would still be checking for the existence of the label and removing it when appropriate.

- When `add-update-label-weekly.yml` runs, it will still be checking for:
  - Whether there is a comment by the current assignee(s): 
    - If not, the ‘last update date’ is whenever the issue was assigned to the current assignee(s).
    - If yes, the ‘last update date’ is whenever the last comment was by the current assignee(s).
  - If ‘last update date’ < 3 days ago:
    - Retain `Status: Updated` if exists
    - Check for and remove any of the other two labels, if they exist
  - If 3 days <= ‘last update date’ < 7 days ago: 
    - Check for and remove any of the three labels
  - If 7 days <= ‘last update date’ < 14 days ago:
    - Check and remove any of the three labels
    - Apply `To Update !` label
  - If 14 days <= ‘last update date’:
    - Check and remove any of the three labels:
    - Apply `2 weeks inactive` label
  - If issue has gone to a PR: remove all status labels since we would not need to know comment status anymore


- We would need a **new issue** to describe which action will add the `Status: Updated` label, besides applying it manually: 
  - Logically- this might be included with the `issue-trigger.yml` file (???), 
  - pseudo-code: if issue commented on && comment made by assignee  (and issue open and no PR)  then remove any status labels and apply `Status: Updated`. 
- Likely: We will need new issues to correct/ revise our wiki articles about labels
- Likely: We will need new issues to correct/ revise our wiki articles about specific GHAs
- Definitely @t-will-gillis to create a Figjam diagram explaining all of this…

**Comment by bzzz-coding** [comment]
@t-will-gillis Thanks so much for your clarification! I will revise my code in the next couple of days and will post an updated comment when it's ready for review/testing.

**Review by t-will-gillis — APPROVED** [review]
Hey @bzzz-coding  Fantastic work on this issue!!! 

Thank you for your care and determination working through this. Your refactoring makes the code more readable and obvious in its intent, and the added comments will make for easier debugging and revisions in the future. 

The problem with the `To Update !` appears to be resolved. The action functioned as intended during testing for several different conditions such as comments and issue assignments at various intervals, having no comments on the issue, opening a PR, etc.  

Awesome job again!

**Review by MattPereira — APPROVED** [review]
@bzzz-coding superbly well done! :+1: 

You displayed outstanding degree of grit and determination on this issue. Refactoring and bug fixing GitHub actions is no easy task. I really admire your perseverance sticking with this issue for so long. Getting the chance to hear some of your thought process as you problem solved during zoom meetings was also a delight.

And big thanks to @t-will-gillis for his continued reign as the king of GHA testing :crown: 

Proud of you both and so glad to have y'all on the team! :tada:

**Pull request merged**
