### PR TITLE
Add icon no sql 2669

### LINKED ISSUE #2669: Add svg icon for NoSQL to the website repo and delete non svg icons from Google Drive folder
### Overview
We need .svg file of the icon for NoSQL, so that users exploring our projects by technology can get a quick sense of the technologies we use.

### Action Items
- [x] Locate .svg file for the icon of NoSQL. 
  - [x] This can often be found by googling "logo [technology]", for example "logo NoSQL"
- [x] Have a copy of the downloaded .svg inside the directory named "technologies-icons" within [this folder](https://github.com/hackforla/website/tree/gh-pages/assets/images)
  - [x] When choosing an .svg to place in the folder, choose the one that appears on the main page of its website.
- [x] Delete all non svg icons from this [Google Drive folder](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)

### Resources/Instructions
[Hack for LA - Projects Page](https://www.hackforla.org/projects/)
[Google Drive folder - Technology icon .svg files](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)
[assets/images](https://github.com/hackforla/website/tree/gh-pages/assets/images)
[Related issue](https://github.com/hackforla/website/issues/2130)

### PR DESCRIPTION
**Pull request by Pauljsyi**
Fixes #2669

### What changes did you make and why did you make them ?

  -added a NoSQL svg file inside the directory name technologies-icons

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

N/A

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
N/A

</details>

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
Review ETA: EOD 2/5/22
Availability: 3-6 PM Pacific Saturday

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@Pauljsyi Hi Paul, Thanks for working on this issue. Request to make the following changes:
- [x] Please add your PR to the project board.
- [x] Please edit the description of what changes you made such that it mentions that you removed non svg icons from google drive
- [x] Please remove the react icon with png extension in the google drive folder
- [ ] Please make sure the changes in expunge-assist.md file and onesheet.pdf file are not visible in the files changed tab.

Once you are done with the changes, please request a re-review. Thank you.

**Comment by Pauljsyi** [comment]
ETA: 1 hour
Availability: Tues 3pm

**Comment by SAUMILDHANKAR** [comment]
@Pauljsyi Thanks for making the changes. I see some of the items are still pending and wanted to follow up on your progress. In regard to the last item on the above checklist, you can try updating your forked gh-pages and merging the updated forked gh-pages into your topic branch. Also, if you have any questions or need help, please add help wanted label or you can reach out on our hfla-site slack channel. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Pauljsyi Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@Pauljsyi Just wanted to follow up regarding your progress on this issue. Please let us know if you have any questions or need help. Sent a slack message and email as well about the same. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@Pauljsyi Planning to close this PR due to inactivity. Please feel free to pick up this or any other issue once your availability changes. Will let you know on slack as well. Thanks.

**Pull request closed without merging**
