### PR TITLE
Updated Virginia Wu's section by adding "github-handle"

### LINKED ISSUE #6737: Add github-handle for Virginia Wu in food-oasis.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: Virginia Wu
```
with
```
- name: Virginia Wu
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by cchrizzle**
Fixes #6737 

### What changes did you make?
  - Added "github-handle" to Virginia's Wu's section below her name.

### Why did you make the changes (we will use this info to test)?
  - Reduce redundancy in project file by eventually combining the "github" and "picture" variables into "github-handle".

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updated markdown file - no visual changes to the website.

### CODE REVIEW

**Comment by cchrizzle** [comment]
My mistake, I just realized I have the "Prettier" extension and it automatically formatted some other parts of the code (removed extraneous spaces and changed double quotes to single quotes).

Let me know if this needs to be fixed, I'll be sure to disable it for future issues.

**Comment by Anahisv23** [comment]
Review ETA: EOD 6/12/24
Availability: M - F 11am - 5pm

**Comment by Anahisv23** [comment]
Hi @cchrizzle, nice job working on this issue! Everything looks good on my end. Regarding the Prettier automatic formatting that occurred, I think it's alright, but we should confirm with the tech leads. @roslynwythe, I would love to get your opinion on this. I'll hold off on approving the pull request until we get the green light from the tech leads about whether the Prettier formatting is acceptable. Other than that, nice job!

Here’s what you did well:
* Linked issue is correct, into branch, and from branch are correct.
* Added github-handle variable under Virginia Wu in the correct file and in the correct place in the file without indenting that variable, following the issue instructions correctly.

**Comment by andyphancode** [comment]
Review ETA: EOD 6/12/24
Availability: Throughout week

**Review by andyphancode — COMMENTED** [review]
Went ahead and took a look at all the changes and they are consistent with the explanation. 

- Correct branch usage
- Correct addition of `github-handle:`
- PR comment is complete


I agree with @Anahisv23 's take on the situation but it is out of my scope to say if it is wrong or right. I can give the PR my approval when someone with more authority comments on the situation or you can take the safer, quicker route of re-doing the pull request with the extension off or making another commit fixing all the changes that are not necessary. 

For future reference I recommend checking what lines have changed either by looking at your Git GUI you have installed or using `git show` in your terminal. @cchrizzle

**Comment by cchrizzle** [comment]
I just resubmitted with the original formatting intact, so the only change from the original file is the addition of "github-handle" for Virginia Wu's section as originally requested.

(Also I just realized I put "Victoria" instead of "Virginia" in the pull request title and just fixed that as well!)

@Anahisv23 I appreciate your time and input, thank you!

@andyphancode Followed your advice with the resubmission, thanks for letting me know about `git show`! For future reference, how would I get out of the command afterward? I kind of got stuck and had to reopen my Git to proceed.

**Review by Anahisv23 — APPROVED** [review]
Hi @cchrizzle thanks for fixing the prettier formatting issue and for updating the name from "Victoria" to "Virginia" on the PR title. @andyphancode this was a great suggestion. These new code changes look great. Approved!

**Review by ajb176 — APPROVED** [review]
Hey @cchrizzle, nice work. 

Yes, you should avoid using Prettier when working on issues, VSCode + Spell checker is the standard, you should be able to disable Prettier in your VSCode workspace. 

Your PR looks good, one thing to keep in mind for next time is that the 'why did you make the changes' section should be a brief, high level description of what the PR is meant to address. The overview section of the linked issue mentions this, which would be a decent answer: 

> We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

Just something like 'To reduce redundancy in the project file' or however you want to phrase it would be good enough.

**Comment by cchrizzle** [comment]
@Anahisv23 thanks again, much appreciated!

@ajb176 got it, disabled Prettier and will continue like this from now on. Thank you so much for the suggestion on how to have better descriptions, it was really helpful to help me get a better idea of what is expected and I've updated my pull request accordingly.

**Review by andyphancode — APPROVED** [review]

**Review by del9ra — APPROVED** [review]
Hi @cchrizzle,
1. The pull request is done with the correct branch
2. The issue is properly linked
3. Your summary of changes is clear
4. Your code change correctly uses spaces instead of tabs to indent
5. The appearance of the project webpage is unchanged
Well done!
Thanks for your contribution

**Pull request merged**
