### PR TITLE
Add github handle for Angela Darosh on tech-work-experience.md

### LINKED ISSUE #7247: Add github-handle for Angela Darosh in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Angela Darosh
```
with
```
- name: Angela Darosh
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by bexux**
Fixes #7247

### What changes did you make?
  - Using spaces, added the variable `github-handle` under Angela Darosh

### Why did you make the changes (we will use this info to test)?
  - We need to create a single variable github-handle to hold the github handle for each member of the leadership team. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by mmcclanahan** [comment]
Review ETA: 10 PM 8/17/24
Availability: 8am-pm Sunday, available throughout work week

**Review by mmcclanahan — APPROVED** [review]
Looks Good!

Checklist:
To and from branches are correct
Link to the issue included
Clear and concise description of what was done and why
No visual changes made

Nice Work!

**Comment by jennisung** [comment]
Review ETA: 10 PM 8/19/24
Availability: Friday - Monday 6 pm to 12pm EST

**Review by jennisung — APPROVED** [review]
Hey, this looks good. I see the added "github handle" under the intended user. The branches are correct.The documentation is also written and formatted correctly. Great job.

**Pull request merged**
