### PR TITLE
Richard Kwang added to Website: Current Project Team

### LINKED ISSUE #5038: Update Project Profile: Add Richard Kwang to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the end of the `leadership` variable
```
  - name: Richard Kwang
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U04U531MS5P
      github: 'https://github.com/kwangric'
    picture: https://avatars.githubusercontent.com/kwangric
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by k-rewd**
Fixes #5038 

### What changes did you make?
  - Updated `leadership` variable by adding Richard Kwang's name, role, slack&github link and picture.

### Why did you make the changes (we will use this info to test)?
  - To add Richard Kwang as a **Current Project Team** member: https://www.hackforla.org/projects/website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

rkwang-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
rkwang-after

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 7/25 noon - 2 pm
ETA: EOD 7/25

**Comment by nnr-nnr** [comment]
Availability: 7/26 5:30-7PM PT
ETA: EOD 7/26

**Comment by roslynwythe** [comment]
Note to reviewers:
Want to review this pull request? Take a look at this [this documentation](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) for a step by step guide!
From your project repository, check out a new branch and test the changes.

git checkout -b update-add-rkwang-website-5038 gh-pages
git pull https://github.com/k-rewd/website.git update-add-rkwang-website-5038

**Review by roslynwythe — DISMISSED** [review]
Great job @k-rewd on your first good issue.  Your setup the branches correctly, your code change is correct and clean and you have described your change and the purpose behind the change.  Thank you for contributing to Hack for LA.

**Review by nnr-nnr — DISMISSED** [review]
Nice job keeping the website updated, @k-rewd ! This looks good!

**Comment by LRenDO** [comment]
Hi @mademarc! If you still would like to review this request, please add your ETA and Availability when you get a minute.  If not, please remove yourself as a reviewer.  Thanks!

**Comment by mademarc** [comment]
Review ETA: 7/27/2023
Availability: 7:13PM

**Review by mademarc — DISMISSED** [review]
Hey @k-rewd  Good job on adding the correct code for lines 75-80  and @LRenDO the ETA and Review is done.

**Comment by adrianang** [comment]
Hi @k-rewd! I was going through pull requests to merge and noticed that there's a merge conflict on this issue now, as a result of #5052 (adding Ronald to the leadership list) being merged while this issue was getting reviewed. Can you pull the latest version of the Website project page and push the change with Richard added to the list back onto this branch?

Everything else seems good (branching, issue, requested change made), so this merge conflict just needs to be resolved before I can merge your issue into the production branch! 😄

**Comment by k-rewd** [comment]
Hello @adrianang ! Thank you for bringing this to my attention. Please confirm if the merge conflict with pr #5052 has be resolved correctly. I'll also send you a message on Slack in case I missed something. Thank you!

**Review by adrianang — CHANGES_REQUESTED** [review]
@k-rewd I just sent you a message on Slack, but there is an extra space at the start of line 81 that is giving me a YAML Exception reading error on Docker. When that extra space gets deleted, everything is working perfectly; can you delete that extra space and push another commit?

**Comment by k-rewd** [comment]
hi @adrianang! Sorry I missed that! Should be good to go now. I'll be more careful next time.

**Review by adrianang — APPROVED** [review]
@k-rewd No worries! I just tested your branch for this issue on my local machine after you merged the updates to the website and everything on the Website project page is looking great and working great, with Richard added to the project team roster. Per my previous review, the branching is still set up well, the corresponding issue is linked, and the documentation is descriptive with provided screenshots. I'll merge this as the other aspects of your PR have been reviewed by others and only the merge conflict had to be resolved.

Thank you for taking up this issue and for also being patient and responsive with regards to the merge conflicts! 🙏🏼

**Pull request merged**
