### PR TITLE
Notify multiple issues 4505

### LINKED ISSUE #4505: GitHub Actions: Notify developers if they are working on multiple issues at once
### Overview
We need a GitHub Action that notifies a developer when they have assigned themselves to multiple open issues, so that they don't "camp on issues".  

### Details
Camp on issues = when a person assigns themselves to multiple issues, planning on working on them in the future.  You cannot work on two things simultaneously, so you are basically keeping other people who are looking for an issue from being able to start on them.

As a developer on the website team, you are expected to follow the chain of complexity when you assign yourself an issue; that is, two good first issues, one small issue, one medium issue, and at least one large issue while only working on one issue at a time. 

Currently, when a developer assigns themselves an issue, a GitHub Action runs that posts this comment on the issue:  
<details><summary>Message</summary>
 
  ```
  Hi @developer, thank you for taking up this issue! Hfla appreciates you :)
  
  Do let fellow developers know about your:-
  i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
  ii. ETA: (When do you expect this issue to be completed?)
   
  You're awesome!
  
  P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)  
  ```
</p>
</details>  

When a developer assigns themselves to more than one issue, we want to post an alternate message instead. 

### Action Items
- [x] Become familiar with [HfLA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
  - [x] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Be sure to read up on using Personal Access Tokens to test the project board in your own repo ([Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))  
- [x] Review the [.github/workflows/issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) workflow and note the job "Ask-For-Preliminary-update", which is triggered when an issue is assigned (`event_name` and `event.action`). The workflow first checks labels, and then runs `preliminary-update-comment.js` to post a comment on the issue.
- [x] In [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js), add to the existing script with code that checks whether the developer is assigned to multiple issues and if so posts the alternate message.
- [x] Your script should check the following:
   - [x] Whether the dev is assigned to multiple open issues at once
   - [x] Since closed issues stay assigned to the dev that completed them, it should not look at any of the dev's closed issues
      - [x] This should exclude any issues with label `Complexity: Prework`
      - [x] This should exclude any devs who are members of either the ['website-merge'](https://github.com/orgs/hackforla/teams/website-merge) or ['website-admins'](https://github.com/orgs/hackforla/teams/website-admins) teams
     - [x] This should exclude any Agenda issues (2010, 2027, 2212, 2607) 
     - [x] This should exclude any issues in the following columns:
        - [x] "Emergent Requests"
        - [x] "New Issue Approval"
- [x] Navigate to the [add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment) collection
   - [x] Add a new .md file named `multiple-issue-reminder.md`
   - [x] Copy the following text into the .md file
      ```
      <!-- Template for a notification to the assignee that they're already assigned to an open issue and that they will be unassigned -->
      Hello @${issueAssignee}, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

      We are going to unassign you from this issue so you can focus on your current issue.

      Hfla appreciates you! :)
      ```
  - [x] If the dev already has an open issue, the new comment `multiple-issue-reminder.md` should post **_instead_** of the comment that asks the dev for their availability
- [x] The script should also perform the following:
   - [x] Unassign the dev from the issue
   - [x] Add a `ready for dev lead` label
   - [x] Move the issue to the "New Issue Approval" column for dev leads to reprioritize 
- [x] Demonstrate your new GHA to the merge team

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4230
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/.github/workflows) workflows
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/github-actions) JavaScript files
- HfLA's [GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

### PR DESCRIPTION
**Pull request by moazDev1**
Fixes #4505

### What changes did you make?
  - All Project Board related functions have been updated to align with ProjectV2
  - Added `multiple-issue-reminder.md` file
  - Modified `preliminary-update-comment.js`:
    - Added functionality to check if the developer is assigned to another open issue. If so, the script will:
      - Post a comment using the template message in `multiple-issue-reminder.md`
      - Unassign the dev from the issue
      - Add a "ready for dev lead" label
      - Update issue's status to "New Issue Approval"
    - The code exempt any developer who is part of Admin or Merge teams
    - The code exempt any other issue that applies the following conditions:
      - Any issues with label "Complexity: Prework"
      - Any Agenda issues
      - Any issues in the "Emergent Requests" or "New Issue Approval" status
    - Refactored existing code:
      - Split the code into distinct functions to improve readability and maintainability.

### Why did you make the changes (we will use this info to test)?
  - Ensuring developers are not assigned to multiple issues simultaneously helps maintain focus on a single task and allows other developers to find available issues to work on.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by t-will-gillis** [comment]
availability: upcoming week, 6/10-16
eta: 6/16 e.o.d.

**Comment by t-will-gillis** [comment]
Hi @moazDev1 - I know you are working on this currently. Take your time! 

This is a summary of what is going on with the migration, etc. and is from our previous conversation on Slack 6/17/24:
You might have seen the [Sunset Notice](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/) on the Project Board. GitHub is discontinuing Projects (classic) and before August Hack for LA needs to migrate to the Projects Beta. After talking with Bonnie and the team, doing some testing, and checking the calendar, we have decided that the Website is going to migrate to the new Projects Beta on Monday, June 24th.  

Sorry for the short notice- this is happening very quickly. Each of you have currently submitted a PR that involves GitHub Actions and wanted to let you know that we will need to hold off merging any new GHAs until after the migration. To make this interesting, also need to let you know that after migration, any of the existing API calls using a ‘column’ reference will no longer work because Projects Beta is not structured the same- the new term is ‘status’ and it is not interchangeable. Some other REST API endpoints that will be deprecated soon are [here.](https://docs.github.com/en/rest/projects?apiVersion=2022-11-28)  

So for all of you, after migration your workflows will need to be tested using Projects Beta. If you already installed Projects (classic) on your repo you can migrate to Projects Beta for early testing. (FYI after migrating you can reopen Projects (classic)- but do that immediately if you want to keep it because that option disappeared for me after a day.)  

For any workflows that currently involve moving an issue to or from a ‘column’, this should be doable using GraphQL, ProjectV2, and Status. (I have not done this yet- still learning!) And/or we can discuss other options.  

Finally, one last thing I notice is that for all of you there are parts of your issue that overlap with the other two’s issues. As one example, all three of your issues include posting messages to a member’s “Pre-work Checklist”. Unfortunately, this should have been caught earlier so that each issue was worked on after the other was completed, so that you would not each have a different solution to the same problem. (I could also be wrong and maybe there will not be any conflicts.)

**Comment by t-will-gillis** [comment]
From 6/24 Slack
Hey everyone- we have migrated to Projects Beta. As I mentioned before we made revisions to all workflows that previously involved 'columns' including removing all workflow jobs that used the alex-page automation since these no longer work. "Issue Trigger", "Pull Request Trigger", and "Schedule-Friday" plus related js files had the biggest changes.

**Comment by moazDev1** [comment]
Hey @t-will-gillis, I just updated my code to align with ProjectV2. I tested it using [nektos/act](https://github.com/nektos/act) and worked just fine. I tried to merge it to my forked repo to run it but not sure why it didn't run my workflow their. No errors appear.

**Comment by t-will-gillis** [comment]
Hey @moazDev1 Sounds good- I'll start looking at this over the next couple of days

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @moaz great job so far on this issue. As you know, there is a lot going on with this issue so this is taking a while to get through. I am posting some initial comments here, but I will have more as I continue. 

I tested this in my repo substituting my Project’s GraphQL ids. Here are the things that I am noticing:
-	Thank you for reactivating the previous functionality to check `Draft` and `Complexity: Prework` in the “New Issue Approval” column
-	This was not running for me initially due to a permissions problem. I believe that we need a new token with “project” and “repo” scopes- let me know if you agree. We can create the token and then it could be inserted around Line 66 of `issue-trigger.yml`:
`github-token: ${{ HACKFORLA_GRAPHQL_TOKEN }}`  
-	`multiple-issue-reminder.md` needs to be attached to PR
-	Around Line 218: the substituted string needs to be “issueAssignee” to match the .md files, so the comments show the assignee's name, eg:
`placeholderString: '${issueAssignee}',`

Thanks for all of your work, especially for refactoring due to Projects Beta. I will try to wrap up my comments over the next few days.

**Comment by moazDev1** [comment]
Hey @t-will-gillis, thanks for your notices. I just fixed them.
- > This was not running for me initially due to a permissions problem. I believe that we need a new token with “project” and “repo” scopes- let me know if you agree. We can create the token and then it could be inserted around Line 66 of issue-trigger.yml:
github-token: ${{ HACKFORLA_GRAPHQL_TOKEN }}

  Yes, just added it and fixed the permission issue. I  had to add it also in line 55. It seems we have to provide the token every time we use `actions/github-script@v7`.

- > multiple-issue-reminder.md needs to be attached to PR

  Done, I didn't notice it was removed from the PR. My bad.
  
- >Around Line 218: the substituted string needs to be “issueAssignee” to match the .md files, so the comments show the assignee's name, eg:
placeholderString: '${issueAssignee}',

  Done

- I also refactored the `memberOfAdminOrMergeTeam` function. Seemed there was already a function with same job in `utils` directory.

The code is now working perfectly in my forked repo. Thanks for your clarifications, they really helped me a lot.

**Review by t-will-gillis — COMMENTED** [review]
Hey @moazDev1 Thanks for making the latest batch of changes.

- Thanks for refactoring `memberOfAdminOrMergeTeam()` - just need to add the import statement at top ;-)
- I believe that existing lines 21-24 should be kept as is- I am a fan of using **_many, many_** `console.log()`  statements. My main argument is that each of these log snippets are very helpful when troubleshooting GHAs. 
- Also, I think this conditional should occur before `assignee = await getLatestAssignee();` (no reason to check for latest assignee if `shouldPost === false`)
- Regarding the "try - catch" statements: I know that this is what we are supposed to do as developers, the argument being that catching the errors and letting the program run is preferable to having the program crash. What I am noticing however is that when the runtime errors are caught, the workflow continues and finishes, and then the workflow logs show a green checkmark even though something failed in the workflow- I can see that we could go for months with something not working correctly and we would completely miss it because all of the logs would show that everything is working correctly. I feel strongly that we want the workflow to crash with a red X when something goes wrong so that the error is obvious and does not get buried. 
- There might be times when using try/catch is appropriate-however, at this time please remove all try-catch statements. As I said, I keep seeing errors in the workflows, and every time the logs show a successful run even though the run should be failing.

I am testing this in my repo using my account and a dummy account:
- The workflow seems to change the status to "In progress (actively working)" in many instances when it definitely should not: For example, when I assign myself from "New Issue Approval" with or without `Draft`, the status is changing and it should not. Same from the dummy account, prework label from "New Issue Approval", it changes status and it should not. 
- I notice that there is a lot of repeated code in the `main()` and `makeComment()` functions- these should be integrated. 

Thank you for the time you are putting into this. I am thinking that we may need to scale back this PR so that it is only addressing the items from 4505. What are your thoughts?

**Comment by moazDev1** [comment]
Hey @t-will-gillis, thanks for notices.

- >Thanks for refactoring memberOfAdminOrMergeTeam() - just need to add the import statement at top ;-)

  Sorry for this oversight, I usually work on a separate branch to test changes on my forked repo before integrating them here. I'll make sure to be more careful next time.

- >Also, I think this conditional should occur before assignee = await getLatestAssignee(); (no reason to check for latest assignee if shouldPost === false)
  
  Done

- > Regarding the "try - catch" statements: I know that this is what we are supposed to do as developers, the argument being ...

  I removed all the try/catch blocks, but I believe using `throw error` instead of `console.log` will trigger the error in the GitHub Actions console as you wanted. I made a `throw error` version in this [branch](https://github.com/moazDev1/website/tree/notify-multiple-issues-4505-test). Please let me know if this works for you, so I can apply the changes to this branch as well. I believe using try/catch will make it much easier to track the exact location of errors as our codebase grows.

- > The workflow seems to change the status to "In progress (actively working)" in many instances when it definitely should not: ...

  My bad, I tried to automate the process of changing status to "In progress" as many developers forgot to do it. I think I can fix this by adding another condition but I'll revert everything to the original state and remove it for now.

- > I notice that there is a lot of repeated code in the main() and makeComment() functions- these should be integrated.

  I just removed `makeComment()` and combined its functionality into `createComment()`. I also refactored the `main()` function so I don't use redundant code. The `makeComment()` function was meant to make comment but it was holding the whole old code making it really ambiguous and hard to refactor.

**Review by t-will-gillis — COMMENTED** [review]
Hey @moazDev1 so close! Thanks for the latest round of changes. 
- Thank you for your reasoning and explanation regarding `throw error`- I appreciate it. I tested your branch and created a purposeful error: The error was logged and the workflow halted- perfect. 
- Thanks for consolidating the main functions. I think this is much cleaner now. 
- I tested this for multiple combos of team member/non-team member, statuses, special labels, etc. and everything appears to be working as intended. 
- I ran the tests without the token on line 55- I believe this token is not needed and can be removed. 

Please go ahead with the `throw error`, and I'll mark as "Comment" in the meantime. 

Changing this to `Complexity: Extra Large` also.

**Comment by moazDev1** [comment]
Hey @t-will-gillis I just added back try/catch blocks and removed the unnecessary token.

Thanks for upgrading my PR complexity, I appreciate it :)

**Review by t-will-gillis — APPROVED** [review]
Hey @moazDev1 Fantastic-I did a final test and it appears that everything is functioning as intended. As we discussed, there is a new token added to HfLA `HACKFORLA_GRAPHQL_TOKEN` with `project` and `repo` permissions, because based on the testing, these seem to be the permissions needed. 

Thank you again for all of your work on this. 




<details>

  | workflow     number | assignee | post | initial     status | final     status | initial     label(s) | final     label(s) | message
-- | -- | -- | -- | -- | -- | -- | -- | --
OK | 1112 | self | same | New Issue Approval | same | none | n/a | draft-label-reminder.md
OK | 1114 | self | same | New Issue Approval | same | Draft | same | prelim-update-comment.md
OK | 1116 | dummy | unassigned | New Issue Approval | same | none | n/a | unassign-from-nia.md
OK | 1117 | dummy | unassigned | Prioritized Backlog | New Issue Approval | none | ready for dev lead | multi-issue-reminder.md
OK | 1121 | dummy | same | In Progress | same | Feature: Agenda | same | prelim-update-comment.md
OK | 1124 | dummy | same | In Progress | same | Complex: Pre-work | same | prelim-update-comment.md
OK | 1135 | dummy | same | Emergent Requests | same | none | n/a | prelim-update-comment.md


</details>

**Pull request merged**
