### PR TITLE
Updating github handle for Bonnie W

### LINKED ISSUE #6759: Add github-handle for Bonnie Wolfe in civic-tech-structure.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-structure.md` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-structure

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by nssensalo**
Fixes #6759

### What changes did you make?
  -Added github handle variable below name
  
### Why did you make the changes (we will use this info to test)?
  The greater plan is to replace name and github link with a variable.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by Chrisklangley** [comment]
ETA: 05/06/24
Availability : Monday-Friday 6pm-9pm

**Review by Chrisklangley — APPROVED** [review]
Hey @nssensalo
Great work on your Pull request !
you linked your issue and made clear documentation of the changes you made on line 14 of _projects/civic-tech-structure.md file

Great work!

**Comment by pdimaano** [comment]
ETA: 5/9/24
Availability: Weekday evenings

**Review by pdimaano — CHANGES_REQUESTED** [review]
@nssensalo Thank you for creating this pull request, I just have a few suggestions for changes to be made before final approval:

For the linked issue, make sure you select the appropriate checkboxes that you have completed prior to creating the pull request. This makes it easier for you and the reviewers to keep track of what steps have already been completed.

The linked issue also states that the webpage appearance should be unchanged after updating the code. According to the Hack for LA website contributing documentation, you do not need to include screenshots if this is the case. You can remove the pre-placed text in the "Screenshots" section and write a statement like "No visual changes to the website."

Please make the appropriate changes and I will continue the review process, thanks!

**Comment by nssensalo** [comment]
Phillip,

Thank you for verifying the webpage would be unchanged after my updates. I
could not find that information but I'm going to go back and try to track
it down for future issues.

And yes, I forgot to check those boxes this time around, will be sure to
stick to my cheat sheet until the process is memorized/more second nature.

Thanks,
Nansamba

**Comment by del9ra** [comment]
Review ETA: EST 11 PM 5/7/24
Availability: 5-8 PM Wednesday

**Review by del9ra — CHANGES_REQUESTED** [review]
HI @nssensalo, 
- the pull request is done with the correct branch
- the Issue is linked properly
- since no changes were implemented, you can omit screenshots. You are not supposed to see any changes
- the checkboxes in the issue were not marked off
Nice job overall! Please make the necessary changes to the code and I will approve your PR.

**Comment by nssensalo** [comment]
Hi @del9ra,

I've checked off the boxes and removed the images.

Let me know if there are any issues. It's now in the pull request "changes
requested" mode.

Thanks,
Nansamba

**Review by pdimaano — APPROVED** [review]
@nssensalo Thank you for making the requested changes. The branches are correct and the issue is linked. The webpage appearance is unchanged on my system on desktop, mobile and tablet. The correct file was updated with the requested information. Well done!

**Review by del9ra — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
