### PR TITLE
added '_site/' to ignorePaths array

### LINKED ISSUE #5843: Add "_site/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "_site/" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by aidanwsimmons**
Fixes #5843

### What changes did you make?
  - added "_site/" to the ignorePaths array in cspell.json

### Why did you make the changes (we will use this info to test)?
  - to populate the spell check configuration file with file paths that should be excluded from spell checking

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by Jung-GunSong** [comment]
Review ETA: 6 PM 3/6/24
Availability: 11 AM - 12:30PM Tuesday, 5-8 PM Wednesday

**Review by Jung-GunSong — APPROVED** [review]
Website works well, the changes to cspell.json look good, and the _/site/ files don't seem to be spell checked anymore. Nice job aidanwsimmons!

**Comment by w1ld-r** [comment]
Availability: Weekdays 9AM to 8PM CST
Review ETA: EOD Wednesday March 6th

**Review by w1ld-r — APPROVED** [review]
Hi @aidanwsimmons — great work on this issue!

* You linked the issue correctly in your PR description
* Your branch is correct
* You clearly described the changes and stated the reason for making them
* No changes were made to the site and no bugs were introduced
* I'm not seeing any cspell errors in files contained in the _site folder

Nicely done -- Approved! 👍

**Pull request merged**
