### PR TITLE
Removed Danny Do

### LINKED ISSUE #6113: Update Project Profile: Remove Danny Do from Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Danny Do
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U048G8S2YAK'
      github: 'https://github.com/Adastros'
    picture: https://avatars.githubusercontent.com/Adastros
```
- [ ] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by zkamenov**
Fixes #6113

### What changes did you make?
  - Removed the "Danny Do" widget from the hfla site project.

### Why did you make the changes (we will use this info to test)?
  - To update information about leads

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<a href="https://ibb.co/4VRry39">wgqgbfsbfbe</a>

</details>

<details>
<summary>Visuals after changes are applied</summary>
<a href="https://ibb.co/84BxF5c">wertyfhdsgsdgfd</a>

</details>

### CODE REVIEW

**Comment by angela-lee1** [comment]
Review ETA: EOD 2/26
Availability: 2/26 2/28

**Comment by aconstas** [comment]
**Review ETA**: 2/26/24 EOD
**Availability**: 2/26/24 all day

**Comment by aconstas** [comment]
Hi @zkamenov! Excellent work with this! 

- The pull request is done on the correct branch
- The issue is properly linked within this PR
- The PR clearly states the changes made and why
- I have confirmed that visual changes are as expected--Danny Do's profile is no longer displayed under **Current Project Team**

Thank you for your time and contributions. :)

**Review by aconstas — APPROVED** [review]
Hi @zkamenov! Excellent work with this! 

- The pull request is done on the correct branch
- The issue is properly linked within this PR
- The PR clearly states the changes made and why
- I have confirmed that visual changes are as expected--Danny Do's profile is no longer displayed under **Current Project Team**

Thank you for your time and contributions. :)

**Comment by angela-lee1** [comment]
Hi @zkamenov, 

Awesome job! The branch is correct and the issue is linked. The Changes are visible on my system. The correct file was changed. Well done!

**Review by angela-lee1 — APPROVED** [review]

**Pull request merged**
