### PR TITLE
Mark civic opporunity project on hold

### LINKED ISSUE #3893: Mark Civic Opportunity Project as On Hold
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the Civic Opportunity project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [x] In `_projects/civic-opportunity-project.md`, change the status for Civic Opportunity Project from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [x] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [Civic Opportunity Project page](https://www.hackforla.org/projects/civic-opportunity-project)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/civic-opportunity-project.md`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, Civic Opportunity project page](https://www.hackforla.org/projects/civic-opportunity-project)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-opportunity-project.md?plain=1
- This issue is part of an epic: https://github.com/hackforla/website/issues/3891

### PR DESCRIPTION
**Pull request by mjh-projects**
Fixes #3893 

### What changes did you make and why did you make them ?

  - changed  word Active to On Hold for civic Opportunity Project 
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

image

</details>

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Availability: Thursday 2-4pm, Tuesday evenings.
ETA: 2/2/23 by 4pm.

**Review by bzzz-coding — APPROVED** [review]
@mjh-projects Thanks for working on this issue!
I see that you have changed the status from Active to On Hold in _projects/civic-opportunity-project.md file. I have also tested in docker and can see the pages showing the On Hold status. 
Great job! Also, thanks for including screenshots of the changes on the web pages!

**Comment by MattPereira** [comment]
**ETA:** 20 minutes
**Availability:** 8 - 10 PM Sunday - Thursday

**Review by MattPereira — APPROVED** [review]
Nice work @mjh-projects ! :+1: 

Your change works as intended and your screenshots are magnificent

**Pull request merged**
