### PR TITLE
removed Bitian Zhang & Arpita Pandya

### LINKED ISSUE #4473: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
  - [x] Remove Bitian Zhang
  - [x] Remove Arpita Pandya
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by 93Belen**
Fixes #4473

### What changes did you make and why did you make them ?

I removed  Bitian Zhang and Arpita Pandya from the leadership in Hackforla.org Website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
first isssue

</details>

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Avail: Tue, Thurs 7pm-12
ETA: Tue 11pm

**Comment by bphan002** [comment]
Avail: Wed 
ETA: Wed  3 PM PST

**Review by bphan002 — COMMENTED** [review]
Hi Belen it looks like you made the correct changes needed, but didn't do it on a new branch.  This is my first PR review, so I'll wait for the second reviewer to chime in on if this should be done.  Or you can go ahead and make a new branch for the changes.

**Review by steven-positive-tran — CHANGES_REQUESTED** [review]
I think its best practice for it to be on a seperate branch. We want to keep the gh-pages in the form to be exactly like the branch from main.

**Comment by 93Belen** [comment]
Ok! I had to do a different pull request in order to change the Head branch the pull request was done from. Here is the new one: https://github.com/hackforla/website/pull/4646.
Thank you!

**Comment by Adastros** [comment]
Closing this pull request since a new one was made. See #4646.

**Pull request closed without merging**
