### PR TITLE
Update alt text for BallotNav-3874

### LINKED ISSUE #3874: BallotNav: Update alt text for the BallotNav image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `BallotNav` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [ ] Change the image alt property value within `_projects/ballot-nav.md`:

**From:**
```
alt: "Two hands holding a mobile device with BallotNav's web application on display."
```

**To:**
```
alt: "Ballot Nav"
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move the epic issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/ballot-nav

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/ballot-nav.md`
- https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by adevlinb**
Fixes #3874 

### What changes did you make and why did you make them ?

  - Update image alt property to -> "Ballot Nav"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by janice87** [comment]
Review ETA: EOD 3/20/22
Availability: 5-8 PM EST Monday

**Review by janice87 — APPROVED** [review]
Good job on your first issue! The branches look perfect, the issue was addressed and I can see the changes made in docker. This is approved!

**Comment by perlaroyerc** [comment]
Review ETA: 10 PM 3/20/23
Availability: 11-7 PM ET M-F

**Comment by Thinking-Panda** [comment]
Availability: M-F 10AM - 3PM
ETA: 3/20/23

**Review by Thinking-Panda — APPROVED** [review]
Hello @adevlinb , nice work on your first issue. Merge branches are correct, code changes are as mentioned in the issue and clean (Thank you for removing the trailing spaces), and website runs perfect locally. Thank you!

**Review by perlaroyerc — APPROVED** [review]
Good job @adevlinb! The changes were made in the correct document, the issue is linked, and the branches are set up properly. 

I suggest adding the PR to the project board, see [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board) for reference. Also, the Pull Request should include a brief description of "why" the changes were made in the codebase. Keep up the good work!

**Comment by adevlinb** [comment]
Hi! Quick question if anyone sees this... 

Do I need to wait until this has been merged to take on a second issue? Am I responsible for any other steps before it is merged? (I'm not seeing anything else to my knowledge).. So this issue has been approved, but just hasn't been merged yet? (Assuming a senior dev has to approve the merge).

Thank you!!

**Comment by Thinking-Panda** [comment]
Hi @adevlinb , after the PR is approved, the merge team will merge the changes. You should wait until this issue is merged before working on another issue. While waiting, you can review a couple of PRs. Hope this helps :)

**Review by jefflueck — APPROVED** [review]
Looks good. I see the code changes, branches are correct for merge. Nice work!!

**Pull request merged**
