### PR TITLE
img-tag-refactor-getting-started-page

### LINKED ISSUE #4394: img Tag Refactor: Getting Started page - `step-img-icon-git join-2.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="" />
```
to
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by garrettallen0**
Fixes #4394 

### What changes did you make and why did you make them ?

  - Got rid of the trailing slash and extra space. 
  - So that the codebase is consistent in how we use HTML tags. 
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Refactoring img tag. No visual changes.

### CODE REVIEW

**Comment by StephenTheDev1001** [comment]
Availability: 10am-12pm M-F
Review ETA: EoD

**Review by StephenTheDev1001 — CHANGES_REQUESTED** [review]
Good job making the changes to the HTML. Edit your pull request comment, under `Screenshots of Proposed Changes Of The Website` to make it more explicit. I would remove all the boilerplate under `Screenshots of Proposed Changes Of The Website` and replace it with "Refactoring img tag. No visual Changes"

There's something strange about the branch. It should be from `garrettallen0:img-tag-refactor-4394`

**Comment by garrettallen0** [comment]
I made the requested edits under `Screenshots of Proposed Changes Of The Website`. Thanks!

I see what you mean about the branch name. Good observation. In fact, I did have challenges pushing my changes to my issue branch. At the dev meeting Tuesday we looked at it as a group, and eventually made it work although with a slight glitch. The first time we pushed my changes, we pushed it to UPSTREAM rather than ORIGIN, and it showed up on the HfLA site but wasn't yet connected to my account. Since we noticed this, we found the error and then ran `git push origin img-tag-refactor-4394`. At that point, it also showed up in my own repository. Is this possibly responsible for the unusual branch name?

**Comment by mjshelton12** [comment]
Availability: 9am-1pm M-F
Review ETA: EoD 4/20

**Review by mjshelton12 — CHANGES_REQUESTED** [review]
Interesting, it didn't even trigger the bot that shows how to pull this down.

I think what happened was you made this commit straight to the HfLA repo instead of pushing it through your repo to HfLA's. If the change showed up in your repo, I'm guessing it has to do with the way you pushed your changes. (If it hadn't, I'd wondered if you accidentally cloned HfLA's repo rather than your own).

[In the guide to how to work on issues, it requests a different push command than you used]( https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md#i-if-there-are-no-changes-in-the-upstream-repository). Rather than `git push origin img-tag-refactor-4394`, it suggests `git push --set-upstream origin update-give-link-2093`. This makes a branch on your repo then pushes that branch to HfLA. Was that the command you were struggling with on Tuesday?

I wonder if you need to [verify your origin remote URL](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#14b-clone-repo-2-verify-origin-remote-url). For sure do `git remote -v` to see what your origins and upstreams are (while checking against the documentation that it's correct). Because your origin should be your own repo, not HfLA's, which would mean only pushing to origin shouldn't hit HfLA at all, only your forked repo. Perhaps walk through the set-up guide one more time and repeat as many steps as are possible to be sure you are hooked up correctly.

If you have tonight free, heading to office hours may help. I'm also willing to help via slack if you'd like it.

**Comment by blulady** [comment]
> I made the requested edits under `Screenshots of Proposed Changes Of The Website`. Thanks!
> 
> I see what you mean about the branch name. Good observation. In fact, I did have challenges pushing my changes to my issue branch. At the dev meeting Tuesday we looked at it as a group, and eventually made it work although with a slight glitch. The first time we pushed my changes, we pushed it to UPSTREAM rather than ORIGIN, and it showed up on the HfLA site but wasn't yet connected to my account. Since we noticed this, we found the error and then ran `git push origin img-tag-refactor-4394`. At that point, it also showed up in my own repository. Is this possibly responsible for the unusual branch name?

Most likely. Feel free to delete this PR and local branch and push to your repo using origin. Otherwise, see you at office hours.

**Pull request closed without merging**
