### PR TITLE
Add paragraph classes 1-3 to codebase

### LINKED ISSUE #2690: Add paragraph classes 1-3 to codebase
### Overview
As developers, we use reusable SCSS classes for styling Hack for LA webpages. For this issue, we will add the paragraph classes 1-3 defined in the [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144) to our codebase.

**Note:** We will not be writing classes for paragraph classes 4-5 because the font size is illegible and should not be used on the website.

<details>
  <summary>Paragraph Classes under Typography in the Design System in Figma</summary>
paragraph-classes-in-design-system

</details>

### Action Items
- [x] Locate the Paragraphs section under Typography in the [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144) in Figma to see how the paragraph classes are defined.
- [x] Look at the following SCSS files to see how title classes were implemented; paragraph classes should be implemented similarly.
  - [x] [_sass/variables/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/variables/_typography.scss)
  - [x] [_sass/elements/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/elements/_typography.scss)
- [x] Based on how each paragraph class is defined in Figma, add SCSS paragraph classes 1-3 to [_sass/elements/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/elements/_typography.scss)
  - [x] You may also need to define some variables in [_sass/variables/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/variables/_typography.scss)
- [x] Update paragraph definitions in Figma (if needed) to match code

#### Merge Team or Technical Leads
Once the pull request associated with this issue is approved and merged, please update the following: 
- [x] Edit issue #2656 by
  - [x] Checking off the dependency for this issue
  - [x] Moving issue #2656 into the New Issue Approval column and removing the Dependency label
- [x] Edit issue #2555 by
  - [x] Checking off the dependency for this issue
  - [x] Moving issue #2555 into the In Progress column, removing the Dependency label, and assigning JessicaLucindaCheng to the issue. (Note: I, Jessica, was working on issue #2555 prior to this one and needed the classes from this issue in order to continue work on issue #2555. So, I had to stop work on issue #2555 and complete this issue first. Once this issue is merged, I want to finish working on #2555 since I have 65% of it done already.) 
  

### Resources/Instructions
- [Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144)
- [_sass/variables/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/variables/_typography.scss)
- [_sass/elements/_typography.scss](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/elements/_typography.scss)
- [SASS/SCSS Basics](https://sass-lang.com/guide)
- [SASS/SCSS Documentation](https://sass-lang.com/documentation)

### PR DESCRIPTION
**Pull request by JessicaLucindaCheng**
Fixes #2690

### What changes did you make and why did you make them?
- In _sass/variables/_typography.scss, I added variables for font size and line height, so that they can be used in the paragraph classes.
- In _sass/elements/_typography.scss, I added .paragraph1, .paragraph2, and .paragraph3 classes to the codebase because they are a part of the Design System in Figma and should have been in the codebase already.
  - I used extend/inheritance for the paragraph classes. For more information, see the "Extend/Inheritance" section in [Sass Basics](https://sass-lang.com/guide).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
There are no visual changes because the classes I added have not been applied to any HTML, so the classes are not used anywhere currently. However, they are necessary for future issues.

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 3 hours
Review ETA: Friday, Feb 25, 2022

**Review by tamara-snyder — COMMENTED** [review]
Looks great! Your code was super straightforward to read and I appreciated the rem to px translations in [_sass/variables/_typography.scss](https://github.com/hackforla/website/pull/2880/files#diff-444d690d95950f2215870c62d903ce1fd6a3bdea417ddd2e9661e2138bb08999). The website does indeed remain untouched and the added variables and paragraph classes match the [Figma specifications](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144).

My only feedback is that there's a small typo in line 121 of [_sass/variables/_typography.scss](https://github.com/hackforla/website/pull/2880/files#diff-444d690d95950f2215870c62d903ce1fd6a3bdea417ddd2e9661e2138bb08999): in the comment, you wrote "Equivant" instead of "Equivalent". I'll leave it up to you whether you want to change it, but I thought it was worth noting. 

Otherwise, really well done!

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Thanks for reviewing my pr! I fixed the typo.

Also, when you do pr reviews, feel free to use the Request Changes and Approval options as you deem appropriate.

**Review by tamara-snyder — APPROVED** [review]
Looks great! Thanks for fixing the comment typo.

**Comment by SAUMILDHANKAR** [comment]
Review ETA: End of day 3/2/22
Availability: Wednesday 7-8 PM Pacific Time

**Review by SAUMILDHANKAR — APPROVED** [review]
@JessicaLucindaCheng Thank you for working on this issue. All looks good to me. Impressive work!

**Pull request merged**
