### PR TITLE
Update the GitHub resource name for the Access the data project

### LINKED ISSUE #4685: Update the GitHub resource name for the Access the Data Project
### Overview
As developers we must correct the GitHub resource name in the Access the Data project file, so that the GitHub icon and heading are displayed correctly.  

### Action Items
- [x] Open the Access the Data project markdown file at `_projects/access-the-data.md` and  locate the `links` array and the line `- name: Github` which assigns the value `Github` to the liquid variable `name`   
- [x] Change 
`- name: Github` 
to 
`- name: GitHub`
- [x] To test the change locally, view the Resources section of the [Access the Data Project Page](https://www.hackforla.org/projects/access-the-data).  The GitHub resource should appear as depicted in the screenshot labelled "GitHub resource card on the Access the Data project page - correct"

### Resources/Instructions
<details><summary>GitHub resource card on the Access the Data project page - incorrect</summary>

image

</details> 
<details><summary>GitHub resource card on the Access the Data project page - correct</summary>

image

</details>

- [Access the Data project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Access the Data project webpage](https://www.hackforla.org/projects/access-the-data)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- This is the code which reads the `links` array and renders the resource cards: [resource-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/resource-card.html)
- This issue was created as a result of #4660

### PR DESCRIPTION
**Pull request by AHP15**
Fixes #4685 

### What changes did you make and why did you make them ?

  - inside `_projects/access-the-data.md` file in `links array`, I changed the liquid variable `name` from `- name: Github` to - name: GitHub

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by one2code** [comment]
**Review ETA:** 5/23/23
**Availability:** 4-5PM EST, and 8-10PM EST on 5/23/23. All day 5/24/23 if further review is necessary.

**Comment by nnr-nnr** [comment]
**Review ETA**: 5/24/23
**Availability**: M-F 12–2PM PST

**Review by one2code — CHANGES_REQUESTED** [review]
I've reviewed the code for issue #4708 and tested the changes inside of Docker. I can verify that the changes have successfully resolved the issue with the Github icon displaying incorrectly on the /access-the-data page. I've attached an image of the display change in Docker.

ghtestimg

@Abdessittir, I just need you to check off the last box here https://github.com/hackforla/website/issues/4685
and I can approve the pull request.

Great job on resolving the bug!

**Comment by AHP15** [comment]
@one2code, Thanks for the review I just checked the box

**Comment by nnr-nnr** [comment]
Hi @Abdessittir , I'm having issues with my Docker that are preventing me from completing the review. It's taking me some time to resolve this, and I don't want to hold you up. So, I'm going to remove myself as a reviewer. Apologies!

**Review by one2code — APPROVED** [review]
@Abdessittir Thank you for taking the time to check the last box off on the issue. I look forward to your next pull request.  Approved!

**Review by t-will-gillis — APPROVED** [review]
Hey @Abdessittir - great job! Your branches are correct, you are linking the issue, and your code changes are concise. Thank you for picking up the comment from @one2code and for displaying the visuals in the description. I checked on Docker and the icon is rendering correctly now.

The only comment is that on the next issue, you could explain **_why_** you made the change, for example: 
```
inside _projects/access-the-data.md file in links array, I changed the liquid variable name from - name: Github to - name: GitHub so that the icon and heading display correctly
```
Great job again and thank you!

**Pull request merged**
