### PR TITLE
Update schedule-daily-1100.yml

### LINKED ISSUE #5494: Confirm dependabot version update to schedule-daily-1100.yml
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) periodically checks the packages/dependencies used in our codebase to see whether a more recent version is available. When it finds an updated version, the dependabot creates a PR specifying which files will be affected if the package/dependency is updated. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 
### Action Items
Refer to the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) file and review the version update(s) recommended by the dependabot.
   
- [ ] Make sure that you have configured your private repo for testing GHAs. See "Details" above.
- [ ] Review the expected activity of the GHA, then create a test branch in your local repo to trigger and record the results of the current action.
- [ ] Create another test branch to trigger and record the results of the action using the updated package version(s). Change all instances of:
```
- uses: actions/checkout@v3
```
to:
```
- uses: actions/checkout@v4
```
- [ ] Compare results to determine whether the update causes breaking changes, or whether the update causes no apparent change in the expected functioning of the action, and "Approve" or "Request changes" as appropriate. 

### Resources/Instructions
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)  
- This issue was initiated by #5443

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #5494

### What changes did you make?
  - Updated `actions/checkout@v3` --> `actions/checkout@v4` in `schedule-daily-1100.yml`
  - Tested to confirm the GHA functions as expected with update
  - Testing was successful, see below: OK to update

### Why did you make the changes (we will use this info to test)?
  - Change made for testing the Dependabot recommended version updates for compatibility with existing automation

### Supporting file

- [Action log](https://github.com/t-will-gillis/website/actions/runs/6167920735/job/16739633677) showing successful run.
##
### Note to PR Reviewers
 - The process for testing GHAs is different from procedures described in the `CONTRIBUTING.md` document. You will want to have an environment set up in your local repo and test the GHAs on the desktop. 
 - First, review the following wiki pages [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and follow the "Mini Guide".
   - Pay close attention especially to Steps 6 & 7. 
   - Note in Step 7: It is best practice to give your secret an expiration date. 
   - Note in Step 7 also: when you are creating your own token, do not give your token the same name that you see in the yaml file. In other words, do not give your token the same name as HfLA's token, otherwise unexpected behavior may result. Any other name is OK (for example, TEST_TOKEN).
 - To continue creating your testing environment, go to your local repo on the desktop and create a new branch for testing: 
   - From your "gh-pages" branch, make sure you are synced to HfLA.
   - Select the "gh-pages" button, enter a name for your test branch (such as "test-ghas-for-pr-review"), then select "Create branch". You will make edits and test from here.
   - Next, go to "Settings" on the upper right, scroll down to "Default branch", and select the button with the arrows to switch you default branch to another branch.
   - Find your newly created branch and select it, then "Update", then "I understand, update the default branch".
   - Important- when you are done testing you will want to repeat these steps to reselect "gh-pages" as your default branch.
   - Now, when you make edits to the "website" on your repo you will only affect the new branch.
 - For testing this specific action you will need to make these changes to `.github/workflows/schedule-daily-1100.yml`:
   - Line 7: Add `workflow_dispatch:` inline with Line 5's  `schedule: `
   - Line 11: change to reference your GitHub repo, e.g. `if: github.repository == 'your-repo-name/website'`
   - Line 15: change to '@v4', e.g. `uses: actions/checkout@v4`
   - Lines 17, 26: change to reference your token, e.g.  `token: ${{ secrets.TEST_TOKEN }}`
  - When all edits are made, commit changes directly to your branch, then select "Actions" from the top menu on your repo. Find "Schedule Daily 1100", then on the right, select "Run workflow". A successful test will generate an error-free log and write an update to `_data/external/github-data.json`

### CODE REVIEW

**Comment by davidwiese** [comment]
ETA/Availability: Thurs 9/14/23 1pm-4pm PST

**Comment by JanineSooThow** [comment]
ETA: By next Monday
Available: weekends

**Comment by sheehanrobb** [comment]
ETA: By next Monday
Availability: Weekends

**Comment by JanineSooThow** [comment]
unable to do this PR, removed name off assignee list.

**Comment by sheehanrobb** [comment]
Sorry I am unable to complete this PR. I have removed my name from reviewers list

**Comment by allison-truhlar** [comment]
ETA: Tuesday 10/10, EOD
Availability: Mon/Tues 9-5pm ET

**Comment by allison-truhlar** [comment]
I still plan to review this - my family has been sick over the long weekend so I'm behind. My new, very cautious, ETA is Friday 10/13 EOD. I am typically available via Slack during the day, 9-5pm.

**Comment by dineshsk98** [comment]
ETA: By Monday 10/16
Availability: 11-2 PM Monday to Friday

**Comment by brianf4** [comment]
Availability: Sunday - Saturday 2pm - 7pm PST
ETA: Before or by Saturday EOD

**Review by allison-truhlar — COMMENTED** [review]
@t-will-gillis This PR looks good - the only code changed was actions/checkout@v3 to actions/checkout@v4 in schedule-daily-1100.yml, as requested in the issue. I tested the change locally and the schedule-daily-1100 workflow ran successfully with the change to actions/checkout@v4. Nice work!

Link to successful run WITH the v4 change: https://github.com/allison-truhlar/website/actions/runs/6512541496/job/17690398322

Link to successful run prior to the v4 change (for comparison): https://github.com/allison-truhlar/website/actions/runs/6512518673/job/17690321198

**Review by allison-truhlar — APPROVED** [review]
Sorry - I hit comment instead of approve! Copying my comment below for reference

@t-will-gillis This PR looks good - the only code changed was actions/checkout@v3 to actions/checkout@v4 in schedule-daily-1100.yml, as requested in the issue. I tested the change locally and the schedule-daily-1100 workflow ran successfully with the change to actions/checkout@v4. Nice work!

Link to successful run WITH the v4 change: https://github.com/allison-truhlar/website/actions/runs/6512541496/job/17690398322

Link to successful run prior to the v4 change (for comparison): https://github.com/allison-truhlar/website/actions/runs/6512518673/job/17690321198

**Comment by t-will-gillis** [comment]
Hey @brianf4 @k-rewd @dineshsk98 just checking in to see whether you have had a chance to get started on your reviews yet, and if so your timeframes for finishing? If you have already started reviewing this, please let me know if you have questions or how I can help you. I would like to wrap this PR up in the next day or two because there are currently 3 additional PRs that are waiting on this one to be completed. 

If you have not started reviewing this yet, I would like to ask if you would consider un-assigning yourself from this one. There will be **_many more_** PRs involving GHAs coming up. (This includes #5637 which is over two weeks old and needs a review. )

**Comment by dineshsk98** [comment]
> Hey @brianf4 @k-rewd @dineshsk98 just checking in to see whether you have had a chance to get started on your reviews yet, and if so your timeframes for finishing? If you have already started reviewing this, please let me know if you have questions or how I can help you. I would like to wrap this PR up in the next day or two because there are currently 3 additional PRs that are waiting on this one to be completed.
> 
> If you have not started reviewing this yet, I would like to ask if you would consider un-assigning yourself from this one. There will be **_many more_** PRs involving GHAs coming up. (This includes #5637 which is over two weeks old and needs a review. )

Sorry, for the delay. I started the review, but got stuck with other work. I will unassign myself off of this one.

**Comment by brianf4** [comment]
@t-will-gillis Sorry got caught up with work as well but currently working on it. Will try to have it reviewed by tonight or by tomorrow.

**Comment by t-will-gillis** [comment]
Hey @dineshsk98 and @brianf4 - thanks for the notes and updates

**Review by brianf4 — APPROVED** [review]
Hey @t-will-gillis, I just ran the workflow changes locally for the schedule-daily-1100.yml file and everything checks out. The workflow ran successfully with no errors on my end.

**Pull request merged**
