### PR TITLE
changed size to complexity

### LINKED ISSUE #3110: Edit label info for the HFLA wiki and contributing.md file
### Dependency
- [x] #3109  

### Overview
We are in the process of renaming the "Size" labels to "Complexity" to better clarify the purpose of the label. For this issue, we will edit the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file and the [How to read and interpret labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) wiki so that it has up-to-date information on our label names.

### Details
We are changing the following "Size" labels to instead be named "Complexity":
- ```Size: Good second issue``` to ```Complexity: Good second issue```
- ```Size: Small``` to ```Complexity: Small```
- ```Size: Medium``` to ```Complexity: Medium```
- ```Size: Large``` to ```Complexity: Large```

### Action Items
- [x] Review  [section 2.1](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) , [section 2.2](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#22-how-hack-for-la-organizes-issues) and [section 2.3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) in the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file
- [x] Appropriately update all references to the "size" label to instead be "complexity" for sections 2.1 through 2.3 of the  [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) by matching the casing as you swap the words
- [x] Appropriately update the [How to read and interpret labels wiki](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) now that we are using "complexity" instead of "size" by matching the casing as you swap the words
- [x] Create a pull request for these changes to be merged
#### For Merge Team Only
- [ ] Once the pull request associated with this issue is merged, go to https://github.com/hackforla/website/labels and  update the following labels:
  - [ ] from `Size: Good second issue` to `Complexity: Good second issue`
  - [ ] from `Size: Small` to `Complexity: Small`
  - [ ] from `Size: Medium` to `Complexity: Medium`
  - [ ] from `Size: Large` to `Complexity: Large`
- [ ] Verify that all the project board and wiki links work properly after the changes have been merged. If they do not, create a `time-sensitive` issue to fix the links

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file
    - [section 2.1](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations)
    - [section 2.2](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#22-how-hack-for-la-organizes-issues) 
    - [section 2.3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on)

- [How to read and interpret labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) wiki
    - [Size Series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#the-size-series)

### PR DESCRIPTION
**Pull request by vmaineng**
Fixes #3110

### What changes did you make and why did you make them ?

  - Updated references to "size" label to be "complexity" for sections 2.1 through 2.3 of the Contributing.md
  -Updated Size Series on How to read and interpret labels wiki to 'complexity'
  -

<details>
<summary>Visuals before changes are applied</summary>

image
2 1 Size Before

2 2 Size Before

2 3 Size Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
2 1 Size After

2 2 Size After

2 3 Size After

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 2/14 11-midnight;  2/15 10 - 11 am
ETA 2/15

**Comment by MattPereira** [comment]
**Availability:** 7 - 9 PM Sunday - Thursday
**ETA:** End of Day 2/16

**Comment by roslynwythe** [comment]
Hi @MattPereira thank you for reviewing this PR.  The issue https://github.com/hackforla/website/issues/3110 was not consistent in its use of case.  The Action Items section specifies lower case 'complexity', but the Details section specifies upper case 'Complexity'.  Viewing the updated CONTRIBUTING file, I see both upper and lower case used.  In links to the Project Board the lower case is used.  Please advise.

**Comment by MattPereira** [comment]
@roslynwythe I updated the action items to address the confusion

**Comment by roslynwythe** [comment]
Hi @vmaineng Did you make any changes to the wiki "How to read and interpret labels"?  If so, what file was modified?

**Comment by roslynwythe** [comment]
> @roslynwythe I updated the action items to address the confusion

Thanks Matt.  I didn't mean to imply there was anything wrong with the Action Items; I just wanted to clarify the intent.

**Comment by roslynwythe** [comment]
Hi @vmaineng it would be desirable to have screenshots to display in the "visuals before" and "visuals after" section of the PR.  You can take the screenshots by viewing the contributing doc at https://github.com/vmaineng/website/blob/edit-label-info-3110/CONTRIBUTING.md.  Please message me on Slack if you need assistance with this.

**Comment by vmaineng** [comment]
Hey @roslynwythe , I attached some before and after visuals. I hope this helps :)  Please let me know if you have any questions.

**Review by roslynwythe — APPROVED** [review]
Thank you @vmaineng for making all the required changes and creating this PR to document your work.

**Review by MattPereira — APPROVED** [review]
Well done @vmaineng !!!

Great job communicating with the team and nice attention to detail with this tedious task of swapping size to complexity throughout the contributing.md and wiki :+1:

**Pull request merged**
