### PR TITLE
add-sdg-background-4233

### LINKED ISSUE #4233: Add SDG color variables: 2-5, 8-11, 13, 16, 17
### Overview
We need to add the SDG (Sustainable Development Goal) colors to our repo so we can use these colors with their corresponding, matching SDG icons.

### Action Items
- [x] In the `_sass/variables`, create a new file: `_colors-sdg.scss`
- [x] In the file you just created, add the following:
```
/**
 * Sustainable Development Goal (SDG) Colors
 *
 * The hex color values for these variables match the SDG color icons provided by the United Nations (UN).
 * These hex values are from the last the page in the SDG Guidelines provided by the UN:
 * https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf
 */

$color-sdg2: #DDA63A;
$color-sdg3: #4C9F38;
$color-sdg4: #C5192D;
$color-sdg5: #FF3A21;
$color-sdg8: #A21942;
$color-sdg9: #FD6925;
$color-sdg10: #DD1367;
$color-sdg11: #FD9D24;
$color-sdg13: #3F7E44;
$color-sdg16: #00689D;
$color-sdg17: #19486A;
``` 
- [x] In the `_sass/main.scss`, under the `General Settings and Utilities` section, add this:
```
@import 'variables/colors-sdg';
```

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues/dependencies listed under the `Dependency` section are closed or checked off. If the dependencies are all closed or checked, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4344 

### Resources/Instructions
- [_sass/variables](https://github.com/hackforla/website/tree/gh-pages/_sass/variables)
- [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss)
- [SDGs_HEX_Colors tab in HfLA: Projects: SDG and Targets Google Sheet](https://docs.google.com/spreadsheets/d/1lV8d8AMSJ5HOiTWlFE7lzbqiKxqMmh8pHADcJMdp7JE/edit#gid=741671421)
- This issue is tracked in #4153

### LINKED ISSUE #4344: Add SDG background color classes: 2-5, 8-11, 13, 16, 17
### Dependency
- #4233 

### Overview
We need to add background color classes using the SDG (Sustainable Development Goal) color variables to our repo so we can use these classes with their corresponding, matching SDG icons.

### Action Items
- [x] In the `_sass/elements`, create a new file: `_background-sdg-colors.scss`
- [x] In the file you just created, add the following:
```
/**
 * Sustainable Development Goal (SDG) Background Colors
 *
 * These background color classes match the colors of the SDG icons provided by the United Nations (UN):
 * https://www.un.org/sustainabledevelopment/news/communications-material/
 */

.background-color-sdg2 { background-color: $color-sdg2; }
.background-color-sdg3 { background-color: $color-sdg3; }
.background-color-sdg4 { background-color: $color-sdg4; }
.background-color-sdg5 { background-color: $color-sdg5; }
.background-color-sdg8 { background-color: $color-sdg8; }
.background-color-sdg9 { background-color: $color-sdg9; }
.background-color-sdg10 { background-color: $color-sdg10; }
.background-color-sdg11 { background-color: $color-sdg11; }
.background-color-sdg13 { background-color: $color-sdg13; }
.background-color-sdg16 { background-color: $color-sdg16; }
.background-color-sdg17 { background-color: $color-sdg17; }
``` 
- [x] In the `_sass/main.scss`, under the `Elements` section, add this:
```
@import 'elements/background-sdg-colors';
```

#### Merge Team, Technical Lead, or Product Manager
- [x] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues/dependencies listed under the `Dependency` section are closed or checked off. If the dependencies are all closed or checked, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4187 

### Resources/Instructions
- [_sass/elements](https://github.com/hackforla/website/tree/gh-pages/_sass/elements)
- [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss)
- [SDGs_HEX_Colors tab in HfLA: Projects: SDG and Targets Google Sheet](https://docs.google.com/spreadsheets/d/1lV8d8AMSJ5HOiTWlFE7lzbqiKxqMmh8pHADcJMdp7JE/edit#gid=741671421)
- This issue is tracked in #4153

### PR DESCRIPTION
**Pull request by wKategianes**
Fixes #4344 

### What changes did you make and why did you make them ?

  - created `_background-sdg-colors.scss` file inside the `_sass/elements` folder
  - added the following code to `_background-sdg-colors.scss` 
```
/**
 * Sustainable Development Goal (SDG) Background Colors
 *
 * These background color classes match the colors of the SDG icons provided by the United Nations (UN):
 * https://www.un.org/sustainabledevelopment/news/communications-material/
 */

.background-color-sdg2 { background-color: $color-sdg2; }
.background-color-sdg3 { background-color: $color-sdg3; }
.background-color-sdg4 { background-color: $color-sdg4; }
.background-color-sdg5 { background-color: $color-sdg5; }
.background-color-sdg8 { background-color: $color-sdg8; }
.background-color-sdg9 { background-color: $color-sdg9; }
.background-color-sdg10 { background-color: $color-sdg10; }
.background-color-sdg11 { background-color: $color-sdg11; }
.background-color-sdg13 { background-color: $color-sdg13; }
.background-color-sdg16 { background-color: $color-sdg16; }
.background-color-sdg17 { background-color: $color-sdg17; }
``` 
  - Inside `_scass/main.scss` I went ahead and added the following import statement
```
@import 'elements/background-sdg-colors';
``` 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes made as of this moment as all the changes were code changes.

### CODE REVIEW

**Comment by StephenTheDev1001** [comment]
ETA: EoD Apr 28
Availability: M-F 10am - 12pm

**Review by StephenTheDev1001 — CHANGES_REQUESTED** [review]
This is linked to a merged issue #4233 . I see @wKategianes is assigned to a similar issue #4344 . Which of those two issues did @wKategianes intend to address?

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@wKategianes Did you intend this PR to fix #4344 ?  If so, please change the first line of the PR where it says "Fixes: #4233"

**Comment by wKategianes** [comment]
@StephenTheDev1001 My apologies these changes were intended for #4344. @roslynwythe You are correct I intended that this PR to fix #4344. The requested changes have been made. Let me know if anything else needs to be done.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Review by StephenTheDev1001 — CHANGES_REQUESTED** [review]
Is there a way you can rename the branch to include to correct issue number?

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @wKategianes I agree with @StephenTheDev1001, please rename the PR with the correct issue number "4344".  Thank you!

**Comment by blulady** [comment]
How to rename a PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by t-will-gillis** [comment]
The dev for this PR was unassigned from the original issue #4344 therefore closing this PR without merging.

**Pull request closed without merging**
