### PR TITLE
update toolkit page subheading

### LINKED ISSUE #1459: Adjust size of Credits page header illustration
### Overview
We need to adjust the size of the Credits page header illustration so that it is consistent with the Figma and other headers on the site

### Action Items
- [x] In desktop view of the Credits page, make the header illustration max-height 240px
- [x] In tablet and below, make the max-height 170px

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits/)
[Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### LINKED ISSUE #1479: Update Toolkit Page subheadings
### Overview
We need to update the 'Guides' and 'Resources' subheading sections (and their buttons) in the Toolkit page to better align the page, and accommodate upcoming changes to the mobile version of the filter banner.

### Action Items
- [x] Review images below (under arrows) to see how the updated page should look (or see the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)
- [x] Remove "(We made these!)" text after 'Guides' subheading
- [x] Evenly align both the buttons and subheadings ("Guides" and "External Resources") with the edges of the guide cards in all screen sizes, desktop through mobile, as seen in the screenshots below and Figma

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit/)
[Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)

<details>
<summary>How it looks now:</summary>
<br>
Screen Shot 2021-04-27 at 6 45 45 PM
</details>

<details>
<summary>How it should look:</summary>
<br>
Screen Shot 2021-04-27 at 6 45 23 PM
</details>

### PR DESCRIPTION
**Pull request by qaz6209031**
1479 
- [x] Remove "(We made these!)" text after 'Guides' subheading
- [x] Evenly align both the buttons and subheadings ("Guides" and "External Resources") with the edges of the guide cards in all screen sizes, desktop through mobile, as seen in the screenshots below and Figma

Before 

Screen Shot 2021-04-28 at 6 29 41 PM
Screen Shot 2021-04-28 at 6 29 10 PM

After 
Screen Shot 2021-04-28 at 6 33 03 PM
Screen Shot 2021-04-28 at 6 33 21 PM

### CODE REVIEW

**Comment by qaz6209031** [comment]
Besides, the font size of 'Guildes' in the Figma design is 35px in webpage, but the version we have now is 28px. Should we also need to change that to match our design system?

**Comment by daniellex0** [comment]
> Besides, the font size of 'Guildes' in the Figma design is 35px in webpage, but the version we have now is 28px. Should we also need to change that to match our design system?

Good catch- actually the Figma design font size was out of date, so I just updated it there. Thanks for the head's up!

**Review by daniellex0 — CHANGES_REQUESTED** [review]
This is looking good, thanks for taking this one on @qaz6209031 ! 

So the only issue is that in some viewport sizes (most importantly desktop screen sizes like mine), the alignment still looks off-

Screen Shot 2021-04-30 at 1 02 10 AM

Screen Shot 2021-04-30 at 1 01 55 AM

But I'm realizing this issue is more complicated than I originally thought... is it even possible to keep the button and 'Guides' subheading always aligned with the first and last guide cards, without having to insert a million media queries? If not, I might have to rethink the design/ let go of this request... (sorry, honestly this goes beyond my CSS knowledge, so let me know if you have any thoughts on this)

**Comment by erikaBell** [comment]
> So the only issue is that in some viewport sizes (most importantly desktop screen sizes like mine), the alignment still looks off-


@qaz6209031 @daniellex0 The same thing happens for my desktop view. After taking a look at this in my browser, the quick and easy suggestion I have, would be for Kai-Chin to try changing the `padding-left` and `padding-right` on `.suggest-guide-group` for desktop view.

Currently `.suggest-guide-group` has a padding left&right of `10rem` where as `.toolkit-flex-container` has a padding left&right of `2rem`. I found that playing around with lower numbers on the padding of `.suggest-guide-group` helps things look cleaner.

However! I think we could achieve much more consistency if we took the `.suggest-guide-group` div + all it's child elements and placed it at the top of the `.toolkit-flex-container` div. If that makes sense? 

Anyway, @qaz6209031 I'll let you take a look at it and do what feels comfortable to you.

**Comment by qaz6209031** [comment]
Thanks for all the advises @daniellex0 @erikaBell , let me see what I can do to make it consistent on all view port size.

**Comment by qiqicodes** [comment]
@qaz6209031 Can you let us know your progress in regards to the change request? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by qaz6209031** [comment]
Hello, it seems like there were some update on the toolkit page so now the toolkit page look like this

<details>
<summary>How it looks now:</summary>
<br>

</details>

But according to the original issue #1479, I need to evenly align both the buttons and subheadings ("Guides" and "External Resources") with the edges of the guide cards in all screen sizes, desktop through mobile. so I am not sure what to do next.

P.S. The current toolkit page design is different from Figma design
[Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)

**Comment by daniellex0** [comment]
Hi @qaz6209031 sorry we're trying to have someone fix the issue asap with #1510 , as soon as it's ready you should be able to work on this

**Review by daniellex0 — APPROVED** [review]

**Comment by akibrhast** [comment]
@qaz6209031 The toolkit page issue has been resolved. I believe you should now be able to apply the changes requested if any. Also, please resolve the merge conflicts

**Comment by qaz6209031** [comment]
Sounds good, let me work on it !

**Comment by qaz6209031** [comment]
I changed the padding and it doesn't seem to be working, and then I tried @erikaBell method to put all the `.suggest-guide-group` div into `.toolkit-flex-container` div but the grid system will consider it part of the grid. I am not sure how to fix this issue, so I will join tomorrow's meething to discuss with you guys.

**Comment by qaz6209031** [comment]
It works now, thanks for the guildance from @akibrhast .

**Review by erikaBell — CHANGES_REQUESTED** [review]
Hi @qaz6209031 sorry if this issue is starting to become cumbersome or annoying, but with the newly implemented code, the following is occurring at the bottom of the page under "External Resources"  

<details>
<summary>Kai's Branch</summary>

Screen Shot 2021-05-11 at 8 36 46 PM

</details>

<details>
<summary>Hack4LA Livesite</summary>

Screen Shot 2021-05-11 at 8 36 52 PM

</details>


I believe the way to fix this is to add a second class on the external resources card container.

So, right now the cards in this div are receiving all the styling that falls under `.toolkit-flex-container`

By adding a second class, i.e `.external-resources-card-container` or whatever you think is best, I found that simply changing the display from grid, which it is currently receiving, to flex takes care of this issue! While keeping everything else exactly the same (-: !

Reach out if you need anymore clarification. 

Great job overall @qaz6209031 ~

**Comment by erikaBell** [comment]
@qaz6209031 Hey kai, just wanted to check in with you on this issue, if you could provide us an update! Thanks (-:

**Pull request closed without merging**
