### PR TITLE
Removed / in img tag

### LINKED ISSUE #5029: img Tag Refactor: Join Us page - advice-us-icon.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/join-us.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="join-us-card-img" src="/assets/images/join-us/advice-us-icon.svg" alt="" />
```
to
```
<img class="join-us-card-img" src="/assets/images/join-us/advice-us-icon.svg" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: [INSERT LINK TO FILE]
2. Webpage(s): https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by Vinny02**
Fixes #5029 

### What changes did you make?
  - Removed a '/' from an img tag

### Why did you make the changes (we will use this info to test)?
  - requested by issue to maintain code consistency

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to to the website.

### CODE REVIEW

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Great job @Vinny02 on this Pull Request.  The branches are setup correctly, the code change is clean and correct., and it checks out fine in the browser.  I do have a minor request, to clean up the PR by removing the blank bullets, and by cleaning up the "Visual Changes" section by removing the `<details>` and `<summary>` tags (up to and including the closing tags) and adding a comment so that it appears like this:
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

**Comment by Vinny02** [comment]
> Great job @Vinny02 on this Pull Request. The branches are setup correctly and the code change is clean and correct. I do have a minor request, to clean up the PR by removing the blank bullets, and by cleaning up the "Visual Changes" section by removing the `<details>` and `<summary>` tags (up to and including the closing tags) and adding a comment so that it appears like this:
> 
> ### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
> No visual changes to the website.

Fixed! Thanks for reviewing my PR Roslyn

**Review by roslynwythe — APPROVED** [review]
Thank you @Vinny02 for your quick response!

**Comment by kwangric** [comment]
ETA: EOD 7/31
Availability: After 3pm PDT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The code was changed exactly as needed, and everything looks good in Docker. Thanks for making the changes to your PR and great job with your issue!

**Pull request merged**
