### PR TITLE
Remove no-labels-template.md and edit post-labels-comment.js file 2898

### LINKED ISSUE #2898: Remove no-labels-template.md file
### Overview
We need to remove [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md) file so that the total number of bot comments are reduced, and developers would have less notifications

### Action Items
- [x] Remove  [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md) file
- [x] Edit the following lines in [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js) file such that if no label i.e., (role, size and feature) is missing, no bot comment should be posted: https://github.com/hackforla/website/blob/dc04be749651270020eb965c428c2a36431d9c5e/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js#L47-L55

### Checks
- [x] For testing in your own repo (after making the necessary code changes)
    - [x] Create a project board in your own repo
    - [x] Create a new issue with all the required labels, i.e., (role, size and feature) and submit the issue
    - [x] Confirm that no comment is posted by the bot

### Resources/Instructions
Directory where files are located `website/github-actions/trigger-issue/add-missing-labels-to-issues/`
File that needs to be removed [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md)
File where changes need to be made: [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js)
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

### PR DESCRIPTION
**Pull request by raswani2023**
Fixes #2898 

### What changes did you make and why did you make them ?

  - Removed the no-labels-template.md file
  - edited lines 47-55 in post-labels-comment.js so that no comment object was created when all the correct labels were added, and therefore no comment is posted

### CODE REVIEW

**Comment by Zak234** [comment]
ETA: 1 day 
Availability: All day

**Comment by lilyarj** [comment]
ETA: 7/11
Availability: 3 hrs

**Comment by lilyarj** [comment]
@kathrynsilvaconway is it okay if there is another file committed, if that commit has already been merged and approved because other than that this pull request is great!

**Comment by Zak234** [comment]
I would think so but it would probably be better to ask.

**Review by lilyarj — DISMISSED** [review]

**Review by Zak234 — DISMISSED** [review]
It looks like the unwanted commit was reverted. I tested it in my repo and it looks like everything is working as intended. Good work!

**Review by blulady — APPROVED** [review]
The code looks clean, we only have intended changes and everything runs. Good Job!!

**Pull request merged**
