### PR TITLE
Update website.md(Change alt text to enable proper screen reader pronunciation of "Hack for LA")

### LINKED ISSUE #4669: Change alt text to enable proper screen reader pronunciation of "Hack for LA"
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  In this issue, we will replace the value of the alt text for the website project image so that it will be pronounced correctly by screen readers.    

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `alt` variable.  
- [x] Change the value of the `alt` variable from
`Hackforla.org Website` 
to
`Hack for LA Site`
- [x] Do not modify any other instances of `hackforla.org`
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) 

### Resources/Instructions
 
<details><summary>The Website Project Image on the Current Projects page (circled)</summary>

image

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)

### PR DESCRIPTION
**Pull request by Mayank2808sharma**
Fixes #4669 

### What changes did you make and why did you make them ?

  - Change the value of the ```alt``` variable in ```website.md```
  - Changed it from ```Hackforla.org Website``` to  ```Hack for LA Site```
  - ScreenShots of changes are below

### Before
before

Check out the value of alt tag. it was ```Hackforla.org Website```

### After
Screenshot 2023-05-29 073421

Changed value of alt tag to ```Hack for LA Site```

### CODE REVIEW

**Comment by LRenDO** [comment]
Availability: 5/29/23 1:45pm-3:45pm
ETA: 5/29/23 2pm

**Review by LRenDO — APPROVED** [review]
Hi @Mayank2808sharma!
Updates look great!

- Branching was done correctly
- Great specific description of "what" in pull request comment
- Visuals included made it easy to see previews of change
- Updates were accurate and worked with screen reader on the site

Even though this is a pretty straight forward issue. The only minor request is a quick edit to the pull request comment to add the "why".  Something like "to correct screen reader pronunciation of the website project image to improve accessibility."

Nice work! Thanks for taking the time to contribute!

**Comment by graycodesnu** [comment]
Availability: Afternoon of 6/1
ETA: EOD 6/1

**Review by graycodesnu — APPROVED** [review]
Hi @Mayank2808sharma, great job working this issue. You committed to and from the correct branches, added the correct changes to the alt attribute, and checked each step off as you completed it. Changes approved. Thank you for your contribution!

**Comment by drakenguyen4000** [comment]
Good job!

**Pull request merged**
