### PR TITLE
Add github-handle for Eli Marietta in design-systems.md

### LINKED ISSUE #7288: Add github-handle for Eli Marietta in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Eli Marietta
```
with
```
- name: Eli Marietta
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md?plain=1
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by codyyjxn**
Fixes #7288 

### What changes did you make?
  - I updated the `_projects/design-systems.md` file by inserting a new key, 'github-handle,' directly beneath the `name: Eli Marietta`

### Why did you make the changes (we will use this info to test)?
  - I made this change to streamline the project file by introducing a 'github-handle' key, which replaces the need for separate  'github' and 'picture' entries.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

-  No screenshots since adding a variable did not create any new visual change

### CODE REVIEW

**Comment by codyyjxn** [comment]
@kgold2018 @MicahBear Hi. Would you please review my pr ?

**Review by kgold2018 — CHANGES_REQUESTED** [review]
Hi @codyyjxn, the changes look good, but please check off all the relevant action items on the original issue.  Thank you!

**Review by kgold2018 — APPROVED** [review]

**Comment by codyyjxn** [comment]
@MicahBear  Hi please review my pr.

**Review by bexux — APPROVED** [review]
Changes look good. PR description is accurate and concise. Great job!

**Comment by t-will-gillis** [comment]
Hey @codyyjxn For future reference, you do not need to assign yourself to your own PRs

**Pull request merged**
