### PR TITLE
Changed Alt Text for EMS Triage Tracker Logo

### LINKED ISSUE #3987: EMS Triage Tracker: Update alt text for EMS Triage Tracker image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `EMS Triage Tracker` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/ems-triage-tracker.md`:

**From:**
```
EMS Triage Tracker Logo
```

**To:**
```
EMS Triage Tracker
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866.
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/ems-triage-tracker

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/ems-triage-tracker.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/ems-triage-tracker.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by agosmou**
Fixes #3987 

### What changes did you make and why did you make them ?

  - Changed the image alt property value within _projects/ems-triage-tracker.md:
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changed alt text. No visual changes to the website.

### CODE REVIEW

**Comment by richardmundyiii** [comment]
Availability: M-F 6am - 8 am
RP ETA : EOD 3/15/2023

**Review by mademarc — COMMENTED** [review]
Hey @agosmou  looks like the logo tracker text was removed correctly so good job over here.

**Comment by mademarc** [comment]
Review ETA: 3/15/23
Availability: 6:45 PM

**Review by t-will-gillis — APPROVED** [review]
Hey @agosmou - Good job on your first issue! You made the changes in the correct branch, and your commit from/to is also correct. Your code change is clean and addresses the requirements of the original issue. One thing to consider for next time is to include the 'why did you make the change' part in the description, eg. "Changed the image alt property value within _projects/ems-triage-tracker.md to adhere to WCAG guidelines." 

Great job!

**Pull request merged**
