### PR TITLE
Added redirections to ignorepath in cspell.json

### LINKED ISSUE #5846: Add "redirections/" to "ignorePaths" array in cspell.json
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to `cspell.json`
- [x] Add the path `redirections/`to the end of the array `ignorePaths`
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by patelbansi3009**
Fixes #5846 

### What changes did you make?
  - Added `redirections/` to the end of the array `ignorePaths` in the `cspell.json` file

### Why did you make the changes (we will use this info to test)?
  - To make sure the redirections/ folder is not spell-checked.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

- Adding a line of code. No visual changes to the website.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @jenjenkayi, @patelbansi3009, @taylorbeee, @nssensalo, @ShamaaTabassum as a reminder, while you are waiting for your PRs to be reviewed, please consider reviewing each other’s `good first issue` PRs and any other PRs you feel comfortable with. Instructions are here for [How to Review Pull Requests]( https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) . You should aim to review two PRs for every PR you submit, and each PR ideally should have two or more reviewers. Thanks!
#6746, #6767, #6768, #6770, #6772

**Comment by luisitocanlas** [comment]
Review ETA: EOD 29 April 2024
Availability: 29 April 2024

**Review by luisitocanlas — APPROVED** [review]
Hi @patelbansi3009,

- Pull request is done with the correct branch.
- The issue is linked properly.
- Pull request changes and reasoning were provided.
- Everything looks good!

Thank you for working on this issue!

**Comment by Thinking-Panda** [comment]
Hi @Maarimar , @awlFCCamp Please add your availability and ETA for this PR. Thanks!

**Comment by angela-lee1** [comment]
Review ETA: eod 4/29
Availability: 4/29, 4/30

**Review by angela-lee1 — APPROVED** [review]
@patelbansi3009, great work! 
- You've linked the correct issue and your branch is correct.
- You've provided a clear description for making the change.
- You've also given the reason for not providing screenshots.
- The correct changes were made. 
Thank you.

**Comment by t-will-gillis** [comment]
Hey @patelbansi3009 Thanks for helping out with the PR reviews

**Comment by Maarimar** [comment]
Agree with @awlFCCamp and @luisitocanlas, great work! @patelbansi3009 :)

**Pull request merged**
