### PR TITLE
Add Samuel kowitch GitHub handle #7189

### LINKED ISSUE #7189: Add github-handle for Samuel Kowitch in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Samuel Kowitch
```
with
```
- name: Samuel Kowitch
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by FamousHero**
Fixes #7189

### What changes did you make?
  
  - Add "github-handle:" below "   - name: Samuel Kowitch" in home-unite-us.md

### Why did you make the changes (we will use this info to test)?
  
  - Future plans to remove github & picture fields to reduce redundancy

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
<!-- Notes: 
  -No visual changes to the website

### CODE REVIEW

**Review by kgold2018 — CHANGES_REQUESTED** [review]
hi @FamousHero , thanks for taking this issue!

**What looks good:** 
- Your branches are set up correctly 

- The original issue number is linked in the pull request 

**Things you should change:** 

- There are changes to multiple other lines in home-unite-us.md not called for in the issue. 
Just a note, in your pull request below, changes you made are not per requirement
- name: Samuel Kowitch 
 github: KowDesign
 
 Once you've fixed the extra changes to the file, let me know in a comment or re-request a review.

**Comment by FamousHero** [comment]
@kgold2018 Thanks for the feedback! I removed the changes that we not a part of the original requirement.

**Comment by terrencejihoonjung** [comment]
Review ETA: 8/24/24, 11:59pm PT
Availability: 9am-5pm everyday

**Review by terrencejihoonjung — DISMISSED** [review]
Hi @FamousHero,

- "from and to" branching is correct

Changes Requested:
- as of now, it seems the change requirements have still not been met. I recommend re-reading the issue instructions to see the small change needed.

Note: For your next PR, I recommend using hyphens rather than underscores when naming your branches to follow the common convention among hack-for-la issues. 

Thank you for your contribution!

**Review by kgold2018 — APPROVED** [review]
Hi @FamousHero,
I reviewed your last changes after @[terrencejihoonjung comments - it  looks good now.
Thank you!

**Comment by t-will-gillis** [comment]
Hey @FamousHero please don't forget to re-request a review after you have made changes by selecting the chasing arrows next to the reviewer's handle:
Screenshot 2024-08-25 083539

**Review by codyyjxn — APPROVED** [review]
Nice work! Everything looks great !

**Comment by codyyjxn** [comment]
Review ETA: 8/26/24, 11:59pm PT
Availability: 9am-5pm M > F

**Review by vorleakyek — APPROVED** [review]
Looks good! Approved.

**Pull request merged**
