### PR TITLE
refactored img tag

### PR DESCRIPTION
**Pull request by aidanwsimmons**
Fixes #6283

### What changes did you make?
  - removed ending slash from img html tag

### Why did you make the changes (we will use this info to test)?
  - refctored so that the codebase is consistent with how we use img HTML tags.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by njackman-2344** [comment]
@aidanwsimmons Everything looks ok except for missing issue # linked above -  Fixes #replace_this_text_with_the_issue_number

branches look correct. Code looks more consistent. 

Comment format looks great and much improved over last PR. Now you can review more good first issues.

After you fix issue number, I will approve.

**Comment by aidanwsimmons** [comment]
fixed issue number

**Review by njackman-2344 — APPROVED** [review]
Issue Linked

branches look good. Code consistent and refactored.

Approved! Thanks @aidanwsimmons! Nice Job.

**Review by Chrisklangley — APPROVED** [review]
Hey @aidanwsimmons 

NIce work on your Pull Request!
you correctly linked your issue and made all the necessary changes.

Everything looks great, keep up the good work

**Pull request merged**
