### PR TITLE
Update alt text for Railstats LA image

### LINKED ISSUE #4045: Railstats LA: Update alt text for Railstats LA image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Railstats LA` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/metro-ontime.md`:

**From:**
```
LA Metro Rail logo
```

**To:**
```
Railstats LA
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/metro-ontime

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/metro-ontime.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/metro-ontime.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by jlu9d2**
Fixes #4045

### What changes did you make and why did you make them ?

  - Updated alt text for Railstats LA image to adhere to WCAG.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-03-02 at 8 38 38 PM
</details>

<details>
<summary>Visuals after changes are applied</summary>
Screenshot 2023-03-02 at 8 46 08 PM
</details>

### CODE REVIEW

**Comment by jlu9d2** [comment]
do i manually move the card on the kanban board or will someone move it?

**Comment by jeristella** [comment]
Review ETA: 6 PM 3/5/23
Availability: Friday 8 - 10pm

**Review by jefflueck — APPROVED** [review]

**Comment by MattPereira** [comment]
@jefflueck please review the [How to review a pull request documentation](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)

You skipped [Step -1](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step--1-where-do-i-find-these-pull-requests-you-speak-of) which instructs you leave a comment with your ETA & Availability and you also failed to leave an approval comment.

**Comment by MattPereira** [comment]
Review ETA: 5 minutes
Availability: 8-10 PM Monday - Thursday

**Review by MattPereira — APPROVED** [review]
Well done @jlu9d2 

Keep up the great work! :+1:

**Pull request merged**
