### PR TITLE
Removed ending slash in img HTML tag in Abouts page

### LINKED ISSUE #5175: img Tag Refactor: _includes/about-page/about-card-sustainability.html - sdg11.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sustainability.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/sdg/sdg11.svg" alt="11 Sustainable Cities and Communities" />
```
to
```
<img src="/assets/images/sdg/sdg11.svg" alt="11 Sustainable Cities and Communities">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by bluechocolate2019**
Fixes #5175

### What changes did you make?
  -  removed ending slash in one instance of img HTML tag
  -  removed blank spaces before the closing bracket

### Why did you make the changes (we will use this info to test)?
  -  to make the codebase consistent with other img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by meru-a** [comment]
Availability: In the evening & on weekends
Review ETA: EOD 09/01

**Review by StephenTheDev1001 — DISMISSED** [review]
You have provided a clear and concise summary of your changes and the rationale behind them. I tested your code on the browser and it works as expected. Congratulations on your first pull request, you did a great job!

**Review by meru-a — CHANGES_REQUESTED** [review]
Hi @lateral-neck-stretch! Great work on your pull request!

- The new branch is properly going into the correct branch gh-pages. ✅
- Original issue was properly linked and referenced. ✅
- Pull request description is clear and correct. ✅
- The specified ending slash is removed from the website is not broken. ✅

However, I do have a small note about the pull request itself - please add all the [labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) from the linked issue to this pull request. It seems that the bot should've added those automatically when linking the issue, but since it did not happened this can be done manually. After this small change, I'll be glad to approve it!

**Comment by bluechocolate2019** [comment]
Hi, I added the labels as requested.

**Review by meru-a — DISMISSED** [review]
Approving after requested changes were applied. Great work on your pull request!

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @bluechocolate2019, thank you for taking on this issue! 

- The branches are correct
- The requested changes from issue #5175 are correct
- The pull request comment is clear and concise

I won't be able to merge this pull request due to a merge conflict. Some changes were made to the `about-card-sustainability.html` file that your branch of the file does not contain. To fix this, could you update your fork and branch of the HFLA website repository? Once updated, you can re-implement the changes that issue #5175 is requesting. Reference [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) on how to update your fork and branch. 

Let me know if you have any questions!

**Comment by bluechocolate2019** [comment]
Hi, I updated my fork and redid the changes required by issue #5175

**Comment by LRenDO** [comment]
Hi @bluechocolate2019!

Just happened to be going through to do merges and I noticed that there's still a merge conflict.  It looks to me like you may have updated your branch to your forked gh-pages. However, your forked gh-pages is still behind the HFLA repo.  You will need to sync your fork first before pulling it locally. Feel free to reach out to me here or Slack if you need clarification or have any questions!

 [Instructions for syncing fork to original repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

**Comment by bluechocolate2019** [comment]
sorry, I’ll try again!  If it doesn’t work out, I’ll definitely reach out.

thanks,
Mary Ann

**Comment by bluechocolate2019** [comment]
Hi @Adastros, I synced my fork and dealt with merge conflict and need to have PR reviewed. Thank you!

**Review by Adastros — APPROVED** [review]
Hi @bluechocolate2019, thanks for updating your branch and fixing the merge conflict! This pull request is good to merge

**Pull request merged**
