### PR TITLE
changed image alt text to blank. - #3860

### LINKED ISSUE #3860: Communities Of Practice Page: Update alt text for CoP page card images to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Community of Practice` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [ ] Change the image alt property value within `/pages/communities-of-practice.html`:

**From:**
```
alt="{{ community[1].alt }}"
```

**To:**
```
alt=""
```

- [ ] Ensure that the corresponding `Community of Practice` webpage stays the same after the change
- [ ] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

### Resources/Instructions
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `/pages/communities-of-practice.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/910e145af61f4072aa8ebb24da385197729af942/pages/communities-of-practice.html#L31

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by EllenKellyb**
Fixes #3860 

### What changes did you make and why did you make them ?

  - Edited Line 31 on communities-of-practice.html alt text to blank
  - no other changes
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by bootcamp-brian** [comment]
Review ETA: 1:15pm
Availability: Today before 5pm

**Review by bootcamp-brian — CHANGES_REQUESTED** [review]
Good job on linking the issue and getting your branches setup. Looks like you also made the change requested in the issue, but it looks like you might have accidentally created an additional file before your commit. The requested changes to the site are working but you'll need to remove that extra "communities-of-practice.html~" file before this pull request can be merged. And thanks for working on this issue!

**Comment by mjshelton12** [comment]
Review ETA: Today by 6pm
Availability: Today all afternoon

**Review by mjshelton12 — CHANGES_REQUESTED** [review]
Nice work, EllenKellyb! Your branches are all correct and your changes were clean and solved the requests of the issue. I can see them correctly reflected in the code and in docker.

I do see that an extra file was created of the page that shouldn't have. It comes in as a general text file as it ends in ".html~". If you could just delete that file so that only the changes to the alt are reflected, this will be good to go.

**Comment by EllenKellyb** [comment]
ETA for completion: 48-72 hours
To Do: Look up deleting a file from a pull request

**Comment by EllenKellyb** [comment]
Deleted the extra file: communities-of-practice.html~ 
Selected and clicked: commit to the same branch

**Review by mjshelton12 — APPROVED** [review]
Great work! Your fix took away the extra file as requested and nothing else has changed.

Nice work on the original issue and nice work making the change!

**Review by bootcamp-brian — APPROVED** [review]
Thanks for making the changes and getting rid of the extra file. Now everything looks good to go. Great work!

**Pull request merged**
