### PR TITLE
Created the donate page

### LINKED ISSUE #1739: Create a Donate page
### Overview
We need to create a dedicated Donate page so that users clearly know how to donate directly to Hack for LA before they visit the Code for America donate page.

### Action Items

Design
- [x] Review the donate gif and instructions in the bottom of the [Join Us page](https://www.hackforla.org/join)
- [x] Create a new page on Figma for the donate page
- [x] Design a donate page with the same gif and instructions as the About page (the design on the page can look similar to the layout in About Us)
   - [x] When users click the 'Donate' button in the header or footer of any page, they will be led to the donate page (currently they are led directly to Code for America, which means they miss the instructions about how to donate directly to HfLA)

Development
- [x] Develop the Donate page based on the design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022) in the pink rectangle
   - [x] Duplicate the body from the last card in the Join Us page
   - [x] Follow the lead of the header in the Join Us page too
- [x] Do not link the page to the website yet- this should remain an unlinked page for now, until the header copy is finished
- [x] Add header image to [Credits](https://www.hackforla.org/credits/) page

### Resources/Instructions
[Join Us page](https://www.hackforla.org/join) (donate instructions on bottom)
Donate page design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022) (in the pink rectangle)
[How to Create a new HfLA website page](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website)
[HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)

Screen Shot 2021-06-28 at 11 55 58 AM

### PR DESCRIPTION
**Pull request by mgodoy2023**
Fixes #1739 

### What changes did you make and why did you make them?

  - Created a donate page for the website (involving the following new files/folders: donate.html, _donate.scss, donate.yml, and a new  donate folder in /assets/images containing the images used for the page) 
  - Modified the file _main.scss to include _donate.scss
  - The "Donate" button on the website is still not linked to the new Donate page, as requested  
  - The header size needs to be adjusted in another issue, I talked with @daniellex0 about this problem and we agreed that it should be fixed in a smaller issue after the Design team looks at it 

### Screenshots of Proposed Changes Of The Website 

<details>
<summary>Images of Figma design, the new Donate page, and the change to the Credit page</summary>

Screen Shot 2021-07-15 at 11 38 09 AM 
Screen Shot 2021-07-15 at 11 36 52 AM
Screen Shot 2021-07-15 at 11 37 13 AM
Screen Shot 2021-07-15 at 11 37 22 AM
Screen Shot 2021-07-15 at 11 37 44 AM

</details>

### CODE REVIEW

**Review by daniellex0 — DISMISSED** [review]
Looks good! I met with @mgodoy2020 to review this page 1:1 because there are minor issues with the header margins, and I said this can just go live because it's not connected to the website at all yet. Then when it's live it'll be easier to create issues for anyone to take on and fix those details. 

But there should still definitely be at least one developer reviewer on this too just to make sure the code for the new page looks good :)

**Comment by erikaBell** [comment]
Hi @mgodoy2020 ~ should I be able to put in `http://localhost:4000/donate` while on your branch? It is still directing me over to "Code for America", disallowing me to review the page locally.

**Comment by mgodoy2023** [comment]
Hi @erikaBell, because the page is meant to be unlinked it is supposed to still direct you to Code for America when you put in http://localhost:4000/donate. In order to see my page you have to put in http://localhost:4000/donate.html. Hope that helps!

**Review by erikaBell — CHANGES_REQUESTED** [review]
Everything looks good @mgodoy2023! Great Work (-: 

I'm just going to be a bit nit-picky and ask for the indentations in your HTML to be cleaned up.

Indentation issues I found were: 

- items inside the `div` at line 9
- items inside the `div` at line 26
- items inside the `div` at line 45
- list items inside of the `ol` at line 53

**Comment by mgodoy2023** [comment]
Hi @erikaBell, I made the indentation fixes you requested. Hopefully it's all set to be merged now. Thanks for the feedback!

**Review by erikaBell — APPROVED** [review]
Lgtm ~*

**Pull request merged**
