### PR TITLE
Added Product manager Info on guides page for Sarah Levine.

### LINKED ISSUE #5624: Update Project Profile: Guides Team (Add Sarah Levine)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and make the following change:
  - [x] Add the following as a new entry
    ```
      - name: Sarah Levine
        role: Product Manager
        links:
          slack: 'https://hackforla.slack.com/team/U05RWQJ8YKU'
          github: 'https://github.com/levines2017'
        picture: https://avatars.githubusercontent.com/levines2017
    ```
  - [x] Place this profile with the other Product Manager profile(s)
- [x] Verify the changes by viewing the Guides Team page [^2] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by #5407
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by dineshsk98**
Fixes #5624

### What changes did you make?
  -added info at line 23 in _projects/guides-team.md
 

### Why did you make the changes (we will use this info to test)?
  -update website information
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  10/03/2023
Availability: 10am - 2pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @dineshsk98! Thanks for taking up this issue!
A few edits are required so as to follow the correct format for creating a new issue branch.
Choose a branch name that:
- relates to the issue (No spaces!)
- includes the issue number
An example would look like this:
git checkout -b update-give-link-2093
For more reference refer to part 2.7.b of CONTRIBUTING.md
Other than that,
You linked the issue.
Comments are filled out properly.
Changes were made correctly in the code.
Images were included to show visual changes.
Changes appear correctly on the browser.
Nice work!

**Comment by dineshsk98** [comment]
I had 

> Hi @dineshsk98! Thanks for taking up this issue! A few edits are required so as to follow the correct format for creating a new issue branch. Choose a branch name that:
> 
> * relates to the issue (No spaces!)
> * includes the issue number
>   An example would look like this:
>   git checkout -b update-give-link-2093
>   For more reference refer to part 2.7.b of CONTRIBUTING.md
>   Other than that,
>   You linked the issue.
>   Comments are filled out properly.
>   Changes were made correctly in the code.
>   Images were included to show visual changes.
>   Changes appear correctly on the browser.
>   Nice work!

Do I create a new PR? I had also committed code for another issue in the same branch.

**Comment by robertnjenga** [comment]
Hi @dineshsk98 So you have to create a new branch for each issue you work on.

**Comment by dineshsk98** [comment]
> Hi @dineshsk98 So you have to create a new branch for each issue you work on.

I understand that, but in this case, commits have already been made to the primary branch. Should I delete the fork and re-fork the repository? In that case, would the existing PR get deleted?

**Comment by robertnjenga** [comment]
Hi @dineshsk98 No you don't have to delete your fork, you can create a new branch for this issue and make a PR.

**Comment by LRenDO** [comment]
Hi @dineshsk98! Thanks for working on this issue. In general, you should not assign yourself or begin work an issue until your previous issue's PR is merged. 

I took a look at your forked repo branches and it looks like you've got it pretty close to ready. Each feature branch should only have changes related to that specific issue.  It looks like you'll need to do the following:
- Make sure your branch names are for only one issue
- Go to each single issue branch and undo the change that is not required for that specific issue 
- Add and commit the changes on those branches
- Push both branches to your forked repo
- Create a PR for each of the branches

Feel free to ping me if you need any clarification or help!

**Comment by dineshsk98** [comment]
> Hi @dineshsk98! Thanks for working on this issue. In general, you should not assign yourself or begin work an issue until your previous issue's PR is merged.
> 
> I took a look at your forked repo branches and it looks like you've got it pretty close to ready. Each feature branch should only have changes related to that specific issue. It looks like you'll need to do the following:
> 
> * Make sure your branch names are for only one issue
> * Go to each single issue branch and undo the change that is not required for that specific issue
> * Add and commit the changes on those branches
> * Push both branches to your forked repo
> * Create a PR for each of the branches
> 
> Feel free to ping me if you need any clarification or help!

Got it. Have reverted the changes on this first issue and created a PR. Will create a PR for the second after the first is merged.

**Comment by dineshsk98** [comment]
> Hi @dineshsk98 No you don't have to delete your fork, you can create a new branch for this issue and make a PR.

Created a new PR. https://github.com/hackforla/website/pull/5672

**Comment by t-will-gillis** [comment]
New PR #5672 replaces this one; closing

**Pull request closed without merging**
