### PR TITLE
Update add adrian ang to the website team 5036

### LINKED ISSUE #5036: Update Project Profile: Add Adrian Ang to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the end of the `leadership` variable
```
  - name: Adrian Ang
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U0596J2AZEE
      github: 'https://github.com/adrianang'
    picture: https://avatars.githubusercontent.com/adrianang
```

- [ ] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by sisi-in-tech**
Fixes #5036 

### What changes did you make?
  -Added name as Adrian Ang.
  -Added role as Merge Team.
  -Added links to Slack, GitHub, and pictures.

### Why did you make the changes (we will use this info to test)?
  -To add Adrian Ang as a new team member: https://www.hackforla.org/projects/website
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
Before-update-screenshot

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
After-update-screenshot

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: EOD 7/31
Availability: After 3pm PDT

**Comment by Ris345** [comment]
Hi @sisi-in-tech  On the top where it says fixes you can add the issue number after the hash  #1111 something like this. On the Screen shots area you can remove the extra images links. Hope that helps!

**Comment by sisi-in-tech** [comment]
Thank you for your support @Ris345

**Review by kwangric — CHANGES_REQUESTED** [review]
Branches are set up correctly and you made the requested changes to the code. Everything looks good in Docker.

I noticed that in the file you changed, all the single quotes were changed into double quotes. Looks like that was probably done automatically by your code editor. We would like to keep the formatting consistent throughout all the files; if you could revert those changes that would be very helpful.

**Comment by kwangric** [comment]
Hey @sisi-in-tech! Any update on when the requested changes above will be made? I only ask since this is a time sensitive issue. Let me know if you have any questions!

**Comment by sisi-in-tech** [comment]
@kwangric Thank you for your friendly reminder. I have some technical issues with my laptop. I try to update end of this Sunday (Aug 6th) if it's possible.

**Comment by sisi-in-tech** [comment]
Hey, @kwangric, please kindly view the change request; thank you.

**Review by kwangric — APPROVED** [review]
@sisi-in-tech thanks for making the changes! Everything still looks good on Docker. Great work!

**Review by t-will-gillis — APPROVED** [review]
Hi @sisi-in-tech Great job- Thanks for working with @kwangric and @Ris345. The to/from branches are good, you are linked to the original issue, you included appropriate whats/whys in the description, and you included screenshots. The changes look good in Docker.

Thanks for taking up this issue!

**Pull request merged**
