### PR TITLE
Updated Error Log Statements to make them more descriptive

### LINKED ISSUE #2438: GitHub Actions: Improvements to error logs in add-label.js
### Overview
As a developer, we need to ensure that the GHA to add labels produces a more descriptive error log when failing because currently it produces a generic error statement which might not be too helpful while debugging.

### Action Items
- [x] Become familiar with how the [GitHub action](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml) "Add Update Label to Issues Weekly" works
- [x] [JS Edits](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)
    - [x] Under the function removeLabels (line 141), update the catch so it logs the exact error when it fails
    - [x] Under the function addLabels (line 163), update the catch so it takes in err as a parameter, and log the exact error if it fails
    - [x] Under the function postComment (line 190), update the catch so it logs the exact error when it fails
    - [x] Under the function getAssignees (line 227), update the catch so it logs the exact error when it fails

### Details
It is always better to have more info on what the specific error is, rather than outputting a generic statement that a developer won't be able to debug. At the least, the error code should be added. At most, just include the body of the error statement so a developer can have an idea of why something failed.
<details>
<summary>Click for an example for a good error logging</summary>

```
console.err(`Function failed to <insert specific action here>. Please refer to the error below: \n ${err}`)
```

</details>

### Resources/Instructions
[add-update-label-weekly](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)

### PR DESCRIPTION
**Pull request by AsherEngelberg**
Fixes #2438 

### What changes did you make and why did you make them ?

  - I Updated 5 Error log statements and 1 catch statement to improve the quality of the error messages for the GHA
  - I made these changes so that developers will have an easier time debugging code given a more helpful error message.
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

no visual changes to the site.

### CODE REVIEW

**Comment by lilyarj** [comment]
ETA: 7/8/22
Availability: 4 hrs

**Comment by lilyarj** [comment]
@AsherEngelberg, I'm a little confused, I don't see any edits on the file till like line 214 but the issue seems to ask you to edit after line 141

**Comment by AsherEngelberg** [comment]
@lilyarj so on the issue the lines they gave didn't correlate at all to the actual methods that were listed. I think what probably happened was that this issue was created with those lines a while ago and since then the file had been edited and added onto so the methods didn't line up anymore. Hope that helps!

**Comment by tunglinn** [comment]
ETA: today
Availability: 1hr

**Comment by tunglinn** [comment]
@AsherEngelberg were you able to test this in your own repo? if so, what steps did you take?

**Comment by AsherEngelberg** [comment]
@tunglinn sorry, I'm not exactly sure how to test the changes that I made in my own repo. is there a specific section of the contributing guide that I could reference or a tutorial to learn how to?

**Comment by tunglinn** [comment]
> @tunglinn sorry, I'm not exactly sure how to test the changes that I made in my own repo. is there a specific section of the contributing guide that I could reference or a tutorial to learn how to?

I don't see anything on the contributing guide. It's a bit odd to test because how do you force an error...? I would bring it up during standup or office hours. Otherwise, the code looks like it should work.

**Comment by AsherEngelberg** [comment]
@tunglinn I'll make sure to bring this up during the office hours tomorrow and then get back on what happened. Thanks so much for taking time to review my issue!

**Comment by Zak234** [comment]
ETA: N/A (trying to figure out how to test)
Availability: Anytime

**Comment by blulady** [comment]
Hey Asher, I am so sorry but we are having a bit of an issue testing your code. I still have questions for Bonnie about what exactly to do about it but in the meantime I have gotten clearance for you to take on another issue, if you like, while we wait to hear what the decision is.

**Review by blulady — CHANGES_REQUESTED** [review]
Hey @AsherEngelberg I was able to get the code to start throwing errors but they looked exactly as they did before you made the changes.

**Comment by blulady** [comment]
Asher informed me by slack he is unable at this time to continue working on this pr

**Pull request closed without merging**
