### PR TITLE
Img Tag Refactor - removed ending slash for sdg8.svg

### LINKED ISSUE #5176: img Tag Refactor: _includes/about-page/about-card-sustainability.html - sdg8.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `[INSERT PATH TO FILE HERE]`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth" />
```
to
```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by meru-a**
Fixes #5176 

### What changes did you make?
  - Change an img HTML tag ending with a slash () to an img tag without an ending slash ().

### Why did you make the changes (we will use this info to test)?
  - Need a consistent codebase with how we use img HTML tags.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Comment by allison-truhlar** [comment]
ETA: EOD Friday Aug 25
Availability 9-5pm ET Friday Aug 25

**Review by allison-truhlar — CHANGES_REQUESTED** [review]
@pearlescence-m Great work with this pull request! The "to" and "from" branches are correct, there is a correctly formatted linked issue, your changes to the code are clean (only the slash in one ending img tag is removed) and they resulted in no visual changes (as expected). 

I have one small change request for the opening comment in the pull request - can you please edit the comment to remove all the details  and summary tags under the screenshots heading, and instead just put a statement that there were no visual changes? https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available 

After this, click the circular arrows by my icon under "reviewers" in the top right of the screen, and I'll approve the pull request.

**Review by njackman-2344 — APPROVED** [review]
fixes #5299 
I am echoing @allison-truhlar 's comments above: The "to" and "from" branches are correct, there is a correctly formatted linked issue, your changes to the code are clean (only the slash in one ending img tag is removed). 

 I see her requested change underneath the snapshots to "No visual changes." Great Job @pearlescence-m

**Review by allison-truhlar — APPROVED** [review]
Thanks for removing the display/summary tags for the visual changes in the opening comment! As I noted before, the changes to the code and the rest of the pull request format look great!

**Pull request merged**
