### PR TITLE
Add github-handle for Gigi Patel to food-oasis.md

### LINKED ISSUE #6736: Add github-handle for Gigi Patel in food-oasis.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: Gigi Patel
```
with
```
- name: Gigi Patel
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by mrodz**
Fixes #6736 

### What changes did you make?
  - Added `github-handle` property to Gigi Patel in configuration object.

### Why did you make the changes (we will use this info to test)?
  - The `github-handle` property will enable a more streamlined approach to consolidate profile pictures and github variables.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- Added variable to `food-oasis.md`. No visual changes to the website.

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA: EOD 5/26/24
Availability: 9-5 PM Monday-Friday

**Review by dcotelessa — APPROVED** [review]
Tested locally.

**Review by aadilahmed — APPROVED** [review]
Great job, @mrodz , you correctly added the github-handle tag!

**Review by t-will-gillis — APPROVED** [review]
Hey @mrodz Great job and congrats on your first HfLA issue-
- Branches 'from' and 'to' are correct
- Linked to the original issue
- There is a brief description of what was changed and why
- No visual changes
- Code edits are clean

Thanks for working on this!

**Pull request merged**
