### PR TITLE
Edit Content Field and Remove Type Field

### LINKED ISSUE #2836: Edit content field and remove type field from hands.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/hands.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/hands.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/hands.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/hands.yml#L11

### PR DESCRIPTION
**Pull request by jbialkin98**
Fixes #2836 

### What changes did you make and why did you make them ?

  - Changed content field in line for to content-type
  - Removed line 11 (previously type: icon)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by kathrynsilvaconway — DISMISSED** [review]
@jbialkin98 Nice work submitting your first pull request. The word "image" in line 4 should have a lower case "i." Please ccorrect this and request a re-review after you push your changes, then I will approve them

**Comment by plang-psm** [comment]
Availability: 6hrs
ETA: 10/3/22

**Comment by giroz** [comment]
ETA: 10-1-22
Availability: 3 hours

**Comment by plang-psm** [comment]
Nice work! Besides changing the 'I' to 'i' in image, I was curious if you placed images in your description above. The 'Visual changes' before and after dropdown are not loading images just in case you did add anything there.

**Review by plang-psm — COMMENTED** [review]
Nice work! Besides changing the 'I' to 'i' in image, I was curious if you placed images in your description above. The 'Visual changes' before and after dropdown are not loading images just in case you did add anything there.

**Review by giroz — DISMISSED** [review]
Good job.  You just have to adjust line 4 to have 'I' in 'Image' to look like 'i' in 'image'.

**Review by arpitapandya — APPROVED** [review]
All the changes are correct and doesn't break anything. Great job! @jbialkin98

**Comment by arpitapandya** [comment]
> Nice work! Besides changing the 'I' to 'i' in image, I was curious if you placed images in your description above. The 'Visual changes' before and after dropdown are not loading images just in case you did add anything there.

@plang-psm Considered as there weren't any visual changes and reviewed the new changes. Thanks

**Pull request merged**
