### PR TITLE
Implemented new mobile footer design 2554

### LINKED ISSUE #2554: Implement the new design for the footer: mobile
~### Dependency~
-  ~#2393~

### Overview
We need to update the mobile view of the footer on the website to reflect the new design in Figma.

### Details
We are changing the way the mobile footer looks. We will be adding sections to the footer that include: "Our Work", "Get in Touch", "Join Us", and "Toolkit.

<details>
<summary>Current Mobile Footer</summary>
Screen Shot 2021-12-06 at 10 46 42 PM
</details>

<details>
<summary>Desired Mobile Footer</summary>
Screen Shot 2021-12-06 at 10 36 11 PM
</details>

Note, the figma design in the desired mobile footer shows the last link on the bottom as "Privacy Policy". However, the current link on the website is "Join Us". The last link should remain as "Join Us".

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be pushed into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] Navigate to footer.html  -> [/_includes/footer.html](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss)
- [x] Create new section under the Donate button, and above the link section
- [x] Include four sections of Our Work, Join Us, Get in Touch, Toolkit
- [x] Under each section add desired links according to figma design
- [x] If scss is necessary, add to the _footer.scss file -> [/_sass/components/_footer.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_footer.scss)

### Resources/Instructions
#2393 - issue for updating the footer design for desktop view
Figma - [Mobile Footer Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3)

Issue Creator - Tomas Gonzalez
Designer of Feature - Stephen Parent

### PR DESCRIPTION
**Pull request by Wny-Duong**
Fixes #2554 

### What changes did you make and why did you make them ?

  - Added four new text sections to the footer (under the donate button and above the link section), all of which are grouped into columns and contain links to various different parts of the website. 
    - Some of these links are not functional since the anchors they're meant to link to haven't been made yet.
  - In the mobile footer, these columns will rearrange themselves to stack on top of each other in order to match the design shown in [Figma ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3)on the original issue. 
    - The design matches best only for 280 to 479 px in width. I think this was because the media rule used to distinguish between mobile and non-mobile in the rest of the _footer.scss file only encompasses width up to 479px. The pictures shown in visual changes are based on 425px width, smaller widths lead to longer links being separated in two lines if they use spaces.
  - Made adjustments to the main footer's css. The positioning of the footer now uses sticky positioning with a top margin that's also dependent on mobile versus non-mobile formatting.
    - Adding columns in the way I did caused the footer to cover content on the main body of the page when using absolute positioning with a 0 bottom margin. I think this is because the footer now has a dynamic height based on the sizes of the columns.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 6/08
Availability: 2 hours

**Comment by Carlos-A-P** [comment]
Availability: 2 hours
ETA: 6/06/2022

**Review by Carlos-A-P — APPROVED** [review]
Hey @Wny-Duong. Great job working on this issue! I can see that all of the currently live anchors work well, and all of the required links are shown. The mobile view looks just like the Figma mobile design. I also haven't spotted any issues so far, so I'll approve the pr. Awesome work!

**Comment by usaboo** [comment]
Hi @Wny-Duong , sorry for the delay, I will have it reviewed by today (26th June)

ETA : Sunday, June 26th
Availability : 1 hour

**Review by usaboo — APPROVED** [review]
Everything looks good! The footer has been added  correctly to the "About Us", "Joins Us", "Toolkit" and "Get in Touch"! 
I do not understand much about your change on sticky positioning but the original issue looks to be resolved.

**Pull request merged**
