### PR TITLE
Add Missing Closing Tags in About Page

### LINKED ISSUE #5370: Refactor HTML: _includes/about-page/about-card-platform.html - Agility
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/agility.svg" alt=""></span><span class="sub-head-text color-deeppink">Agility</div>
```
to
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/agility.svg" alt=""></span><span class="sub-head-text color-deeppink">Agility</span></div>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by fahimicodes**
Fixes #5370 

### What changes did you make?
  - Added the missing </span> closing tags in three sections on the About page.

### Why did you make the changes (we will use this info to test)?
  - To remove linter errors caused by span tags that were not paired with closing tags. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

Refactoring HTML codes. No visual changes to the website.

### CODE REVIEW

**Comment by Tomomi-K1** [comment]
Availability: weekday
ETA: 10/18

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
Hi @Sediqa-Fahimi, great job taking on this good first issue!🎇
 I see that you used correct branches and have a linked issue and create the nicely formatted pull request.😊

One thing I need to point out is that you had fixed more than what was asked in the linked issue. I believe you were only supposed to update one line of code:  `<span>` that wraps "Agility"
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/agility.svg" alt=""></span><span class="sub-head-text color-deeppink">Agility</div>
```
I saw this spreadsheet on the linked issue : [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0). From this, I see that the team is making one  issue for one `</span>`  tag needed to be added (not per page).

Please edit your code to undo changes you have made on line 7: 
```
 <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/workforce-development.svg" alt=""></span><span class="sub-head-text color-dodgerblue">Workforce Development</span></div>
```
and line 17:
```
 <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/impact.svg" alt=""></span><span class="sub-head-text color-lightseagreen">Impact</span></div>
```

**Comment by fahimicodes** [comment]
Hi @Tomomi-K1 , 
Thank you for your comment. I made the suggested changes above for your review. Thanks!

**Review by Tomomi-K1 — APPROVED** [review]
@Sediqa-Fahimi Thank you for undoing some of the changes you made to meet with the issue requirement. Great job!

**Comment by roslynwythe** [comment]
@mademarc please provide an ETA for reviewing this PR.  Thank you

**Comment by mademarc** [comment]
Review ETA: 10/19/2023
Availability: 7:50PM

**Review by mademarc — APPROVED** [review]
Hey @Sediqa-Fahimi well done on the adding for line 52 on this issue and @roslynwythe the ETa is done already.

**Comment by kwangric** [comment]
ETA: EOD 10/20
Availability: 7am-10am PDT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The requested changes are made and the PR includes a description of the changes made and why. Great work @Sediqa-Fahimi!

**Pull request merged**
