### PR TITLE
Updated project-meetings.html & _project-meetings.scss

### LINKED ISSUE #4699: Website Element Removal: Project Team Meetings Page
### Prerequisite

1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Remove the COVID Notification banner as seen on https://www.hackforla.org/project-meetings
The element will be removed by removing the HTML and SCSS associated with it

#### Remove HTML
- [x] Navigate to /website/pages/project-meetings.html and delete lines 20-22
```
<div class='covid-notification-banner'>
    <p class='meetings-message'>All meetings are currently online due to COVID19.</p>
</div>
```

#### Remove SCSS
- [x] Navigate to /website/_sass/components/_project-meetings.scss and delete lines 1-15
```
.covid-notification-banner {
    background-color: $color-gold;
    width: 100%;
    display: flex;
    justify-content: center;
    align-content: center;

    p {
        text-align: center;
        font-weight: bold;
        margin: 0;
        padding: 15px 0;
    }
}
```

- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 3 in the Resources/Instructions section below)

### Resources/Instructions

1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/project-meetings.html
2. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-meetings.scss
3. Webpage: https://www.hackforla.org/project-meetings

### PR DESCRIPTION
**Pull request by DevRishiJain**
Fixes #4699
1. Navigated to /website/pages/project-meetings.html and delete lines 20-22

2. Navigate to /website/_sass/components/_project-meetings.scss and delete lines 1-15

Also, 

  3. Using Docker, checked the page remains the same in mobile, tablet, and desktop views as on the current website. (See 
   3 in the Resources/Instructions section below),  And it is working pretty well.

### CODE REVIEW

**Comment by bphan002** [comment]
ETA: May 24th Wednesday EOD

**Comment by bphan002** [comment]
@DevRishiJain generally they like for you to have the issue# also on your branch name, and to follow the template with the preview image and final image.  I believe that is the standard procedure they like for you to do. 

As far as the pull request, you have followed the instructions and deleted the lines like the instructions mentioned and the p tag "All meetings are currently online due to COVID19." does not show up after running docker.  Great job and thank you for taking care of this issue.

**Review by bphan002 — APPROVED** [review]
@DevRishiJain generally they like for you to have the issue# also on your branch name, and to follow the template with the preview image and final image. I believe that is the standard procedure they like for you to do.

As far as the pull request, you have followed the instructions and deleted the lines like the instructions mentioned and the p tag "All meetings are currently online due to COVID19." does not show up after running docker. Great job and thank you for taking care of this issue.

**Comment by roslynwythe** [comment]
Hi @DevRishiJain please follow the instructions in [CONTRIBUTING](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31b-complete-pull-request-on-hack-for-la-website-repo) for completing the PR.  In order to ensure proper linkage between the PR and the issue, the first line of the PR should read "Fixes: #4699".  Also please provide a more descriptive name for the PR.

**Comment by roslynwythe** [comment]
Hi @mademarc please provide your Availability and ETA for your review.  To submit your review, go to the "Files Changed" page, then click "Review Changes" and describe the specific steps you have taken in your review.  Thank you.

**Review by blulady — APPROVED** [review]
Looks really good!! It is going to the correct the branch from the correct branch. The PR correctly addresses the issue by deleting lines 1-15 in _project-meetings.scss and deleting lines10-22 in project-meetings.html. I would just recommend deleting the extra line at 19 for conformity with the rest of the page in the future.

**Pull request merged**
