### PR TITLE
updated-alt-text-two

### LINKED ISSUE #4042: Spare: Update alt text for the Spare image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Spare image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/spare.md`:

**From:**
```
alt: 'Spare logo. Different article of clothing icons surrounds "What can you spare?"'
```
**To:**
```
alt: 'Spare'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Spare Page: https://www.hackforla.org/projects/spare

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/spare.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/spare.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by mademarc**
Fixes #4042

### What changes did you make and why did you make them ?

-I had to update the branch to make a new pull request and replace the number #4137 

  -as part of the Web Content Accessibility Guidelines (WCAG i made  these changes Change the alt value within _projects/spare.md:
From:

alt: 'Spare logo. Different article of clothing icons surrounds "What can you spare?"'

To:

alt: 'Spare'

### CODE REVIEW

**Comment by karengcecena** [comment]
Review ETA: 4 PM 3/11/23
Availability: 1:30-4 PM Saturday

**Comment by karengcecena** [comment]
Nice work @mademarc ! Merge branches are correct and code changes are as mentioned in the issue. Thank you!

However, I had issues viewing this on my local machine, so I will have to pass this on to someone else to check it instead of checking off the review while I figure out my local browser issues. Thank you for understanding!

**Comment by plang-psm** [comment]
Review ETA: 3/11/23
Availability: 6 hrs

**Review by plang-psm — APPROVED** [review]
Great job @mademarc ! The requested changes were made and the site runs smoothly. I'll leave this PR up for a couple more days to let others review and then merge.

**Comment by mademarc** [comment]
Thanks  @plang-psm , @karengcecena  & @t-will-gillis for the feedback and also @roslynwythe  for being lovely & professional on this matter as well  :)

**Review by t-will-gillis — APPROVED** [review]
Hey @mademarc - You made the change shown in the issue to conform to WCAG, it is from the correct branch, and this commit is clean without any merge conflicts. 

Great job!

**Pull request merged**
