### PR TITLE
Added GitHub-handle for Brett Beekley in hellogov.md

### LINKED ISSUE #7403: Add github-handle for Brett Beekley in hellogov.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/hellogov.md` in the IDE
- [x] Replace:
```
- name: Brett Beekley
```
with
```
- name: Brett Beekley
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md?plain=1
Project Webpage: https://www.hackforla.org/projects/hellogov

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Sujay-Anantha**
Fixes #7403 

### What changes did you make?
  
  - Added github-handle for Brett Beekley in hellogov.md 

### Why did you make the changes (we will use this info to test)?
  
  - Added to eventually replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

  - No visual changes to the website.

### CODE REVIEW

**Comment by codyyjxn** [comment]
Availability: Mon > Fri 
ETA: EOD

**Review by codyyjxn — CHANGES_REQUESTED** [review]
**Here are the things that are correct:**

-The branch name is accurate.
-The title clearly states the change made.
-The description is concise and explains what was changed and why.

### However, a few adjustments are needed:

- [x]  The change you made is almost correct, but you need to remove the name added to the `github-handle`. The original issue only requires the `github-handle:` variable, not the name "Beekley."

- [x]  In the section asking for a screenshot, you don’t need to add a comment. That section is meant only for screenshots, so you can simply note "No visual changes.""

**Comment by Sujay-Anantha** [comment]
I have updated it as requested. Please let me know if any other changes/updates have to be made.
Thank you

**Comment by codyyjxn** [comment]
Hi @Sujay-Anantha great job! The changes are good. Please re-request a review.

**Review by FamousHero — APPROVED** [review]
Hi @Sujay-Anantha, thanks for taking on this issue!

Things you did well:
- descriptive branch name with issue number included
- Issue # properly linked in PR
- PR title gives a good overview of what PR does
- Changes made is short & descriptive
- Why you made the changes is clear 

No reviews needed, good job!

**Review by codyyjxn — APPROVED** [review]
Great Job! @Sujay-Anantha

**Review by t-will-gillis — APPROVED** [review]
Hey @Sujay-Anantha Great job on your first HfLA PR- branches are good, you are linked to the issue, and your description for what was done and why is clear and concise. Thanks for working with the other reviewers on changes

**Pull request merged**
