### PR TITLE
Add Mario Antonini to Merge Team

### LINKED ISSUE #6864: Update Project Profile: Add Mario Antonini to Merge Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hackforla.org Website project page](https://www.hackforla.org/projects/website

### PR DESCRIPTION
**Pull request by dcotelessa**
Fixes #6864

### What changes did you make?
  - Added Mario Antonini name, github-handle (blank), role, slack link, github link, and picture to the end of the leadership variable
  ```
- name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
```
  - Verified the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on  local environment
  - include a screenshot with pull request

### Why did you make the changes (we will use this info to test)?
  - Mario Antonini is being added to Merge Team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

https://github.com/hackforla/website/assets/5404705/5885e29a-29f3-4096-a835-467bf66b0029

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
https://github.com/hackforla/website/assets/5404705/4537a02c-913b-4ac0-9e82-28db8de71c50

</details>

### CODE REVIEW

**Comment by iancooperman** [comment]
ETA: EoD

**Comment by ino-iosdev** [comment]
ETA: also EoD

**Comment by ino-iosdev** [comment]
@dcotelessa 

David, I think we need to include the issue # at the end of branch name? @iancooperman lmk your thoughts on this one, also updating branch name after the `from` and `to` has been linked is not very fix-friendly right? How would you fix that? I came across the same issue before and ended up having to recreate a new PR.

**Comment by iancooperman** [comment]
> @dcotelessa
> 
> David, I think we need to include the issue # at the end of branch name? @iancooperman lmk your thoughts on this one, also updating branch name after the `from` and `to` has been linked is not very fix-friendly right? How would you fix that? I came across the same issue before and ended up having to recreate a new PR.

@dcotelessa Not totally sure this'll work, but maybe try renaming the branch on your end?
image
image

**Comment by dcotelessa** [comment]
Good catch, I did that last time, and missed it.  Thanks.

**Pull request closed without merging**
