### PR TITLE
remove alt-hero from tdm-calculator.md

### LINKED ISSUE #3212: Remove unused `alt-hero` field from tdm-calculator.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/tdm-calculator.md`, remove line 8 for the alt-hero
```
alt-hero: 'Los Angeles skyline at dusk, complete with cranes on top of buildings and golden smog.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/tdm-calculator.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a2c97475e2d1ab5956bf5cbe95c7e251ce8a1033/_projects/tdm-calculator.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by SZwerling**
Fixes #3212

### What changes did you make and why did you make them ?

  - I removed line 8 of tdm-calculator.md because this alt text was not being used anywhere.

  - No visual change.

### CODE REVIEW

**Comment by giroz** [comment]
ETA: 11-21-22
Availability: 2 hours

**Comment by roslynwythe** [comment]
Availability: 1-3 pm today 11/20

**Comment by roslynwythe** [comment]
@SZwerling - Your update to the code change as well as your documentation look great.  Thank you.

**Review by roslynwythe — COMMENTED** [review]
The code update and documentation look great.

**Comment by roslynwythe** [comment]
I approve this PR but perhaps I should not have closed it, so reopened.

**Comment by patrickohh** [comment]
Review ETA: 11/20/22
Availability: 3 - 4 PM PST

**Comment by patrickohh** [comment]
@SZwerling Great work! The required changes to the file have been made and documentation through the pull request has been completed correctly.

**Review by patrickohh — APPROVED** [review]
@SZwerling Great work! The required changes to the file have been made and documentation through the pull request has been completed correctly.

**Review by roslynwythe — APPROVED** [review]
Great work, approved

**Comment by MattPereira** [comment]
> I approve this PR but perhaps I should not have closed it, so reopened.

@roslynwythe You are correct that you are not supposed to close the pull request after submitting your review. 

I recommend reviewing the hfla wiki for [how to review pull requests](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) for reference as you conduct your future PR reviews.

**Review by giroz — COMMENTED** [review]
Good job! On removing the text.

**Pull request merged**
