### PR TITLE
Typo fixed

### LINKED ISSUE #2553: TYPO - change GitHub hand to GitHub handle
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.

### Action Items
- [x] Correct the spelling mistake in the Issue Template "[Project Profile Card review and update](https://github.com/hackforla/website/blob/ced4d6e9a900c02f55f3fc0449057b830783d4bb/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md?plain=1#L26)" markdown file by changing "GitHub hand" to "GitHub handle" in line 26:

From
```
         - [ ] GitHub hand
```
To
```
         - [ ] GitHub handle
```
- [x] Ensure that creating a new issue using [this](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D) form reflects the spelling fix.

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/ced4d6e9a900c02f55f3fc0449057b830783d4bb/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md#L26

### PR DESCRIPTION
**Pull request by npkeerthi**
Fixes #2553
### What changes did you make and why did you make them ?

  - Fixed Typo GitHub Hand to GitHub Handle

<details>
<summary>Visuals before changes are applied</summary>

image

</details>
<details>
<summary>Visuals  After  Changes are applied</summary>

image

</details>

@jbubar  have a review   
@hackforla-onboarding   Its updated

### CODE REVIEW

**Comment by Georgema20** [comment]
This is almost ready to be approved, but can you just put in the correct before and after photos, please! Right now, your before photo is the end result, and you currently have no photos in visuals after changes are applied. 

Thanks so much! and great job! Once you make the changes, I can approve this PR @npkeerthi!

**Comment by Georgema20** [comment]
Also, on the right side, where it says projects, please select project board!

**Comment by SAUMILDHANKAR** [comment]
@npkeerthi You are welcome to work on our projects, however, I don't see that you have joined the hackforla website team. Have you been to our onboarding? In order to join the organization, please see this webpage https://www.hackforla.org/getting-started, then once you have attended one of our onboarding sessions we can help you work on this issue. Thank you.

**Comment by npkeerthi** [comment]
@jbubar have a review
@hackforla-onboarding
@Georgema20  Its updated

**Review by Georgema20 — APPROVED** [review]

**Comment by Georgema20** [comment]
Nice!

**Comment by npkeerthi** [comment]
@Georgema20 so is it ready to be merged?

**Comment by ExperimentsInHonesty** [comment]
@npkeerthi There is more to coding than just changing text, as your pr shows.  If you [join our organization](https://www.hackforla.org/getting-started) (free)  and the website team, we would be happy to spend time with you, helping you to understand the problems with your pr.  But right now, since you are not onboarded properly, it will take more time to explain it to you then the value of what have changed.  If you want to self teach please read our [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file, and feel free to revise or delete and resubmit.

**Comment by JessicaLucindaCheng** [comment]
I'm closing this pr because another person has been assigned to fix the issue associated with this pr.

**Pull request closed without merging**
