### PR TITLE
Apply New Gradient for Project Pages

### LINKED ISSUE #2600: Apply new gradient overlay for Projects pages
### Overview
We need to use a new gradient for the hero-image overlay on Project pages so that it looks smooth, visually pleasing and is applied consistently to Project page hero images.

### Action Items
- [x] Identify where the [gradient image file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891) must be placed in the code repository. 
- [x] Make the code changes so that the gradient is applied on all the Project pages.
- [x] Check if the gradient looks good on each of the Project page and provide screenshots of all of them. 
  - [x] If it does not look good on all of them, identify the ones it does not look good on, and bring them to the team meeting to discuss, or address it directly with design.

### Resources/Instructions
- [Project Page Example: 100 Automations](https://www.hackforla.org/projects/100-automations)
- [HfLA figma, design system page, gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24996%3A285234&t=VH2yEoPVb8SMTAOs-0)
- Related issue #2312
- How to export the image from figma
  - Click on Export on the right side and download from there. 
image

<details>
<summary>Depreciated links - please ingore</summary>

- [Figma - Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11346%3A42)
- Here is the gradient image file: [Final Gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891)
- Location of the gradient in the [Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=7891%3A0) in a box underneath the 'final version' outlined in pink.

</details>

### PR DESCRIPTION
**Pull request by jyaymie**
Fixes #2600

### What changes did you make and why did you make them ?

Currently, the hero image on each project page has a gradient overlay. The following changes to `_sass/components/_project-page.scss` were made to make this gradient look smoother and more visually pleasing and apply consistently across all project pages and screen sizes. (Please see the issue's comments to get the full scope of the issue.)
  - I changed the gradient's start and end points as well as the start point's opacity.
  - I lowered the position of each project page's title. This **did not** affect the position of the home page's title, which shares the same class name `.hero-inner`.

### Screenshots of Proposed Changes Of The Website

<details>
<summary>Visual of one project page on desktop, tablet, and mobile before changes are applied</summary>

Screen Shot 2022-10-26 at 12 48 51 AM

</details>

<details>
<summary>Visuals of all 34 project pages on desktop, tablet, and mobile after changes are applied</summary>

Screen Shot 2022-10-26 at 12 05 54 AM
Screen Shot 2022-10-26 at 12 06 43 AM
Screen Shot 2022-10-26 at 12 06 44 AM
Screen Shot 2022-10-26 at 12 06 46 AM
Screen Shot 2022-10-26 at 12 06 48 AM
Screen Shot 2022-10-26 at 12 06 49 AM
Screen Shot 2022-10-26 at 12 06 51 AM
Screen Shot 2022-10-26 at 12 06 25 AM
Screen Shot 2022-10-26 at 12 06 27 AM
Screen Shot 2022-10-26 at 12 06 30 AM
Screen Shot 2022-10-26 at 12 06 32 AM
Screen Shot 2022-10-26 at 12 06 33 AM
Screen Shot 2022-10-26 at 12 06 35 AM
Screen Shot 2022-10-26 at 12 06 37 AM
Screen Shot 2022-10-26 at 12 06 38 AM
Screen Shot 2022-10-26 at 12 06 40 AM
Screen Shot 2022-10-26 at 12 06 41 AM
Screen Shot 2022-10-26 at 12 06 07 AM
Screen Shot 2022-10-26 at 12 06 09 AM
Screen Shot 2022-10-26 at 12 06 11 AM
Screen Shot 2022-10-26 at 12 06 13 AM
Screen Shot 2022-10-26 at 12 06 15 AM
Screen Shot 2022-10-26 at 12 06 17 AM
Screen Shot 2022-10-26 at 12 06 19 AM
Screen Shot 2022-10-26 at 12 06 20 AM
Screen Shot 2022-10-26 at 12 06 22 AM
Screen Shot 2022-10-26 at 12 06 24 AM
Screen Shot 2022-10-26 at 12 05 32 AM
Screen Shot 2022-10-26 at 12 05 47 AM
Screen Shot 2022-10-26 at 12 05 52 AM
Screen Shot 2022-10-26 at 12 05 57 AM
Screen Shot 2022-10-26 at 12 06 00 AM
Screen Shot 2022-10-26 at 12 06 02 AM
Screen Shot 2022-10-26 at 12 06 05 AM

</details>

### CODE REVIEW

**Comment by arpitapandya** [comment]
ETA: EOD 2022-10-27
Availability: 2hrs

**Comment by arpitapandya** [comment]
Hey, @jyaymie I see the `Help-wanted` label is on. Do you still need help or the PR is ready for review? We can take the label off if no help is needed.

**Comment by jyaymie** [comment]
> Hey, @jyaymie I see the `Help-wanted` label is on. Do you still need help or the PR is ready for review? We can take the label off if no help is needed.

Thanks for catching this, @arpitapandya! I'll remove the label now.

**Comment by jyaymie** [comment]
I'm heading out! ✈️ The earliest I can get to any requested changes is 11/1/22. Thanks in advance to anyone reviewing this PR!

**Comment by MattPereira** [comment]
ETA: EOD 2022-10-28
Availability: 3hrs

**Review by MattPereira — APPROVED** [review]
Amazing work on this one @jyaymie ! :+1: 

The new linear gradient background and page title position styles you are suggesting definitely make the text easier to read by creating more contrast between the text color and its background, especially for projects with light backgrounds like BallotNav and Railstats LA. Nice job fine tuning the linear-gradient for tablet and mobile screen sizes as well!

Also, please allow me to commend your tremendous efforts in putting together all of those screen shots with three different view ports for each project! :fire: :fire: :fire:

**Comment by esantiano** [comment]
ETA: 10/29/2022
Availability: 3 - 5PM

**Review by esantiano — APPROVED** [review]
Hey @jyaymie 

Looked at the changes you made to the code, everything looks clean and nice change to the formatting on line 41. The gradient change and the decision to lower the title on each page definitely make it look more readable on lighter project backgrounds. Great job!

**Review by jdingeman — APPROVED** [review]
Nice job @jyaymie

**Pull request merged**
