### PR TITLE
Create new credits file for use of artists image

### LINKED ISSUE #4269: Create a new credit file for use of artist's image
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Currently, the alt text for the [Not Today logo](https://github.com/hackforla/website/blob/gh-pages/assets/images/projects/not-today.png) does not contain the credit to the artist. We need to create a new credit file for the artist so that we are in legal compliance for use of his image.

### Action Items
- [x] Create a new credit in [/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) called "cwmoss.yml"
- [x] Paste the content below into the file

```
---
# The title from the source provider
title: unknown
# The url where you can get direct access to the image on the provider site
title-link: 
# The type of content - image, audio, or video 
content-type: image 
# The page it's used on
used-in: Not Today Project Logo
# Name of the artist
artist: C.W. Moss
# Name of the image database you found it on
provider: The Grey Rainbow
# Please give the general site URL, not the link to the image
provider-link: http://greyrainbow.com/
# Location in our GitHub repo
image-url: assets/images/projects/not-today.png
---
```

- [x] For consistency across credit files, remove the comments in the new file you created

### Resources/Instructions
- Emergent Request associated with this issue: https://github.com/hackforla/website/issues/4240
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)

### PR DESCRIPTION
**Pull request by janice87**
Fixes #4269 

### What changes did you make and why did you make them ?

  - Added new file cwmoss.yml under _data/internal/credits
  - Included the credits and removed comments for consistency
  - Change was made because the alt text logo does not contain the credit to the artist

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

There were no visual changes made

### CODE REVIEW

**Comment by mjshelton12** [comment]
Availability: 9am-1pm Mon-Fri
Review ETA: By end of day 3/30

**Comment by chrismenke45** [comment]
Availability: 8am-12pm Mon-Fri
Review ETA: By end of day 3/29

**Review by chrismenke45 — APPROVED** [review]
Looks good! I like how thorough you were in you PR comment. It made it very easy to see what you did and why you did it.

**Review by mjshelton12 — APPROVED** [review]
Great work! Your PR is properly set up a link to the issue, branches are perfect, and your comments are very clear and informative.

The code looks exactly as requested when it's pulled down. Wonderful job!

**Comment by roslynwythe** [comment]
Hi @mademarc please advise if you are able to review this PR, and if so, your availability.  If you don't have time, please remove your name from the reviewer list.  Thank you.

**Pull request merged**
