### PR TITLE
Edited content field and removed type field from brochure.yml credits file

### LINKED ISSUE #2796: Edit content field and remove type field from brochure.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/brochure.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/brochure.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/brochure.yml#L4
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/brochure.yml#L11

### PR DESCRIPTION
**Pull request by geedtd**
Fixes #2796

### What changes did you make and why did you make them ?

  - I edited line 4 changed the content field to content-type 
  - deleted line 11 which was 'type: icon'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changed iml file, no visual changes to website

### CODE REVIEW

**Comment by harshitasao** [comment]
Availability: 10pm-11pm IST
Review ETA: 19/05/2022 (End of the day)

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/20
Availability: 1 hours

**Review by Jaretzbalba — CHANGES_REQUESTED** [review]
@geedtd The code change in the brochure.yml looks good; however, I see that the docker-compose.yml file was changed which shouldn't have been. Based on the issue, it doesn't look like that file should be modified, so please undo that change, and everything should be good. 

Thank you again for working on this and feel free to re-request a review when you're ready.

**Comment by geedtd** [comment]
Hi @Jaretzbalba I reverted the docker file to it's original state, let me know if everything looks good. Thank you

**Review by harshitasao — APPROVED** [review]
Hi @geedtd. Good job working on your first issue. The changes look good to me.

**Review by Jaretzbalba — APPROVED** [review]
@geedtd The changes look good and thank you for fixing the file!

**Pull request merged**
