### PR TITLE
Added github-handle for Khanh Cao in design-systems.md

### LINKED ISSUE #6701: Add github-handle for Khanh Cao in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Khanh Cao
```
with
```
- name: Khanh Cao
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by patelbansi3009**
Fixes #6701 

### What changes did you make?
  - Added github-handle for Khanh Cao in design-systems.md.

### Why did you make the changes (we will use this info to test)?
  - To Reduce redundancy in the project data.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- Adding a line of code. No visual changes to the website.

### CODE REVIEW

**Review by jenjenkayi — APPROVED** [review]
Great job @patelbansi3009!

- Used the correct branch for pull request
- Linked the issue correctly
- Made the changes as requested in the issue
- Made no visual changes on the website

**Comment by jchue** [comment]
**Availability:** May 1, after 5 PM PDT
**ETA:** May 1

**Review by ramitaarora — APPROVED** [review]
This looks good!
- The issue is linked correctly
- The PR is made from your fork
- You used spaces to indent and made the correct changes

Thank you for contributing! Approved. :)

**Review by jchue — APPROVED** [review]
I don't think it's necessary anymore, but approved. :)

- Branch looks good
- Linked issue is correct
- Code change is correct

**Pull request merged**
