### PR TITLE
Updated resource cards on project page 

### LINKED ISSUE #3449: Update Resource Cards On Projects Pages
### Overview
As a developer, I need our site to align with our current design standards to give our users a more consistent experience. For this issue, we will update the resource cards on the individual projects pages to accommodate multiple lines of text.

### Action Items

 - [x] Implement OPTION 3 in this [updated Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490) to create the new resource cards
     - [x] Note there is an example of what it is supposed to look like when there are longer and shorter lines and there are details for dev off to the left side of the Figma design.
     - [x] Locate the html tag that impacts `resource-card` list item in each project page
     - [x] Find the scss file and add the inline-size and overflow wrap to implement the wanted effect
     - [x] Note: implement `inline-size: min-content;` and not a particular pixel size
- [ ] When this issue is closed, release the dependency on #3118 and transfer the recommendations for mobile view

### Resources/Instructions
<details>
<summary>Current styling</summary>
Screen Shot 2021-12-18 at 9 49 12 PM
</details>
<details>

<summary>Option 3</summary>
Screen Shot 2021-12-18 at 9 49 45 PM
</details>

- [Mozilla CSS Resource](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text)
- [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [Material Design-cards](https://material.io/components/cards#behavior)
- This issue solves issue #2606

### PR DESCRIPTION
**Pull request by jdingeman**
Fixes #3449 
### What changes did you make and why did you make them ?

- Changed `margin-left` in `.resource-list` from 21px to 20px
- Added `margin-right: 20px` to `.resource-list`
- Added `justify-content: flex-start` so cards are left aligned
- Changed `margin-left` in the mobile `.resource-list` from 0px to auto
- Added the following properties to `.resource-link`
  - `display: flex` to align individual cards in their space
  - `flex-basis: 16%` so a max of 6 cards are displayed within the block
  - `margin-right: 5px` to space out cards
  - `justify-content: center` to center cards within individual space
- Removed `margin` dimensions in `.resource-card` and replaced with
  - `inline-size: min-content`
  - `margin-bottom: 21px` to space the top line from the bottom
- Changed dimensions of images
  - Width from 128px to 111px
  - Height from 128px to 112px
- Added `padding: 5px` to `.resource-img` to put space between svg and box
- Added `padding: 5px` to `.resource-img-provided` to put space between image and box
- Added the following to `.resource-body` to align text
  - `display: flex`
  - `height: 71px`
  - `justify-content: center`
  - `align-items: center`
   
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

7 cards
image

6 cards
image

5 cards
image

4 cards
image

3 cards
image

</details>

<details>
<summary>Visuals after changes are applied</summary>

7 cards
image

6 cards
image

5 cards
image

4 cards
image

3 cards
image

</details>

### CODE REVIEW

**Comment by plang-psm** [comment]
ETA: EOD 10/9/22
Availability: 4hrs

**Comment by AzaniaBG** [comment]
Review ETA: 10/8/2022 by 8 AM
Availability: 10/7/2022 8 - 10 AM; 10/8/2022: 7 - 8 AM

**Review by AzaniaBG — CHANGES_REQUESTED** [review]
Nice work fixing the inline-size and right margin @jdingeman. A few issues to address:
1. The cards are not matching the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490). This screenshot shows that the cards are not the same height (specifically the last card):
<details>
<summary>Screenshot of projects/civic-tech-index on localhost site</summary>

localhost_projects_civic-tech-index

</details>

2. It looks like only the scss file was changed, but I believe the actual resource-card on the project page needs to be updated so that changes will take affect across all resource-card list items
3. Your comment indicates you changed the image size to 95 x 95, but the Figma design shows the image is 87 x 77 (unless I am missing something)
4. It looks like each card should be 97 x 169, per the Figma design

**Comment by plang-psm** [comment]
ETA: EOD 10/13/22
Availability: 6hrs

**Comment by jdingeman** [comment]
Current status: Haven't had the chance to revisit this yet but no blockers as of right now. Hoping to get it done by Wednesday 10/13 EOD.

@AzaniaBG - could you please clarify what you mean in your second comment? The resource-card element only exists in the scss file as the html that the project pages use is written entirely in Liquid, so the individual cards are generated from that. Thank you! :smile:

**Review by plang-psm — CHANGES_REQUESTED** [review]
Hey @jdingeman , good work with the resources section! I know you've been working on trying to get it centered and I think I may have found the issue.

If the centering does not matter, then disregard change request.

 The margin to the actual resource card is only on the right side which could be causing it to offset from one end. See the picture below.

<details>
<summary>Margin offset</summary>

image

</details>


I played with the code and found that there is also another method that can be done using flex but it goes away from the Figma design request. Simple changes but it will not be a fixed pixels in between and will rely on flex to size. See below.

<details>
<summary>Changes not aligned with Figma design</summary>

image

</details>



Feel free to message me if you need any help, but overall good work!

**Comment by AzaniaBG** [comment]
> Current status: Haven't had the chance to revisit this yet but no blockers as of right now. Hoping to get it done by Wednesday 10/13 EOD.
> 
> @AzaniaBG - could you please clarify what you mean in your second comment? The resource-card element only exists in the scss file as the html that the project pages use is written entirely in Liquid, so the individual cards are generated from that. Thank you! 😄

@jdingeman ~ sorry for the confusion. I'm not familiar with Liquid and just assumed that was the reason the styles weren't taking effect across all cards. You can disregard that comment. My understanding is that all cards should be the same height and width per the Figma design, but please let me know if i'm missing something, or if you have additional insights to share :).

**Comment by jdingeman** [comment]
> > Current status: Haven't had the chance to revisit this yet but no blockers as of right now. Hoping to get it done by Wednesday 10/13 EOD.
> > @AzaniaBG - could you please clarify what you mean in your second comment? The resource-card element only exists in the scss file as the html that the project pages use is written entirely in Liquid, so the individual cards are generated from that. Thank you! 😄
> 
> @jdingeman ~ sorry for the confusion. I'm not familiar with Liquid and just assumed that was the reason the styles weren't taking effect across all cards. You can disregard that comment. My understanding is that all cards should be the same height and width per the Figma design, but please let me know if i'm missing something, or if you have additional insights to share :).

I'm definitely revamping the cards because I realized what you said about the Figma design. So hopefully this next PR will align with it more! :smiley:

**Comment by jdingeman** [comment]
Hello @AzaniaBG and @plang-psm, I have changed quite a few things (thank you Phillip for walking me through!!) and hopefully now it aligns more to the Figma design. See below for example taken from /projects/vrms 
image

**Comment by AzaniaBG** [comment]
> Hello @AzaniaBG and @plang-psm, I have changed quite a few things (thank you Phillip for walking me through!!) and hopefully now it aligns more to the Figma design. See below for example taken from /projects/vrms image

Awesome @jdingeman ! I should be able to take a look tomorrow.

**Comment by AzaniaBG** [comment]
ETA for review: 10/14/2022 by 3 PM
Availability: 10/14/2022 2 - 3 PM

**Review by AzaniaBG — DISMISSED** [review]
@jdingeman ~ nice work implementing the Figma design and getting everything to display properly using flexbox!

**Comment by blulady** [comment]
Hey @jdingeman @AzaniaBG,
So I talked to Bonnie about this issue. We need to present the issue to her. We need to have a picture of what cards look like in the dev environment and a picture of what the figma wants, along with an explanation of what we (Justin) did and why. Specifically she wants to know what happens to the pixels when we change the padding (because if the padding isn't working it might need to go back to design). So Justin if you can put that together by tomorrow I'll send you an invite to come to the meeting at 2:00. Otherwise, let's plan on bringing it back to her next Sunday.

**Comment by jdingeman** [comment]
> Hey @jdingeman @AzaniaBG, So I talked to Bonnie about this issue. We need to present the issue to her. We need to have a picture of what cards look like in the dev environment and a picture of what the figma wants, along with an explanation of what we (Justin) did and why. Specifically she wants to know what happens to the pixels when we change the padding (because if the padding isn't working it might need to go back to design). So Justin if you can put that together by tomorrow I'll send you an invite to come to the meeting at 2:00. Otherwise, let's plan on bringing it back to her next Sunday.

When you say padding, which padding are you referring to? The padding between the cards or the padding of the image inside the top part of the card?

**Review by plang-psm — DISMISSED** [review]
Looks good on my end Justin! Good work!

**Comment by jdingeman** [comment]
Hi @plang-psm and @AzaniaBG, after consulting with Bonnie last week, I don't think I'll need to strictly follow the figma design pixel by pixel after hearing her feedback. I am going to bring it up to her tomorrow to see what she thinks and hopefully we'll be able to merge. :smile:

**Comment by AzaniaBG** [comment]
> Hi @plang-psm and @AzaniaBG, after consulting with Bonnie last week, I don't think I'll need to strictly follow the figma design pixel by pixel after hearing her feedback. I am going to bring it up to her tomorrow to see what she thinks and hopefully we'll be able to merge. 😄

Thanks for the update @jdingeman

**Comment by jdingeman** [comment]
Hello @plang-psm and @AzaniaBG (only if available), I have made some adjustments to the code so that it more reflects Bonnie's vision of the pages. I am not entirely sure what the Linter failure is but it seems it may have to do with the fact that I am editing a scss file.

**Comment by arpitapandya** [comment]
> Hello @plang-psm and @AzaniaBG (only if available), I have made some adjustments to the code so that it more reflects Bonnie's vision of the pages. I am not entirely sure what the Linter failure is but it seems it may have to do with the fact that I am editing a scss file.

@jdingeman looks like you have got other commits if you scroll

**Comment by jdingeman** [comment]
> > Hello @plang-psm and @AzaniaBG (only if available), I have made some adjustments to the code so that it more reflects Bonnie's vision of the pages. I am not entirely sure what the Linter failure is but it seems it may have to do with the fact that I am editing a scss file.
> 
> @jdingeman looks like you have got other commits if you scroll

@arpitapandya The last clean commit was when we were still using linter v4.8.1, after we updated to v4.9.7, it seems it started to fail. Do you think there may be something in my code that is breaking it?

**Comment by arpitapandya** [comment]
ETA: EOD 2022-11-06
Availability: 6 hrs

**Comment by plang-psm** [comment]
ETA: EOD 11-7-22
Availability: 4 hrs

**Comment by plang-psm** [comment]
ETA: EOD 11-9-22
Availability: 6 hrs

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct

**Review by arpitapandya — CHANGES_REQUESTED** [review]
We will be merging v2, so this can be closed.

**Comment by arpitapandya** [comment]
We will be merging v2, so this can be closed. I am closing this.

**Pull request closed without merging**
