### PR TITLE
Updated Project Profile in website.md (removed two team members)

### LINKED ISSUE #4883: Update Project Profile: Hack for LA Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Remove these team members `name`s, `role`s, `slack` links, `github` links, and `picture` from the `leadership` variable. 
  - [x] Justin Dingeman
  - [x] Matt Pereira
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by Abrosss**
Fixes #4883 

### What changes did you make?
  - Removed the following team members: Justin Dingeman and Matt Pereira from the _leadership_ variable in website.md
  - Verified the changes (screenshots below)
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by ldietz08** [comment]
Availability: M-F 4pm-6pm
ETA: 6/30

**Comment by adrianang** [comment]
- Availability: ThFSS, 6 PM - 10 PM (PST) (Weeks of 6/26, 7/3)
- ETA: I plan on reviewing this pull request by Saturday, 7/1 at 10 PM.

**Review by LOSjr4 — APPROVED** [review]
PR done with the correct branch and issue is linked. Correct lines of code were removed associated with two persons listed on the issue. Docker preview correctly shows two persons and info are removed from the page. Assignee provided images of changes and wrote a good description of changes that were made.
Thank you for handling this change @Abrosss.

**Review by ldietz08 — APPROVED** [review]
The pull request was done in the correct branch and you linked to the issue. As requested, two team members were removed from the website markdown file. The visual changes reflect what I see in my local environment. Well done!

**Comment by chrismenke45** [comment]
@mademarc Please add your ETA and availability

**Comment by mademarc** [comment]
Review ETA:  6/29/2023
Availability: 7:12PM

**Review by mademarc — APPROVED** [review]
Hey @Abrosss the removal of the team members is done correctly so good job on this.

**Review by adrianang — APPROVED** [review]
This looks good! Branching is set up correctly, the correct issue is linked, the visual changes matches the screenshots and my browser view according to the action items in the linked issue, and source code successfully accomplishes the task of removing two team members without affecting other parts of the codebase.

Thank you for resolving this issue!

**Comment by drakenguyen4000** [comment]
Nicely done @Abrosss, members removed as requested.

**Pull request merged**
