### PR TITLE
Moved wins.html script into own JS file 2116

### LINKED ISSUE #2116: Refactor JS: Move script from wins page into js directory
### Overview
We need to separate `<script>` code from `wins.html` into a separate folder so we can better maintain and reuse our JavaScript code.

### Action Items

- [x] Review the notes below to understand recent changes to our architecture
- [x] Move line 25-280 from the `/pages/wins/wins.html` into a new js file in the assets/js main directory. it should be something like `/assets/js/wins.js`. Omit the opening and closing `<script>` tag.
- [x] once `/assets/js/wins.js` has the code from `<script>` tag in `wins.html`, delete line 24-281 (opening and closing `<script>`.
- [x] replace line 24 with a script element tied to the newly created file like `<script src="/assets/js/wins.js" type="module"></script>`
- [x] Ensure that the website still appears the same. No visual changes should be made as this is a refactor.

### Resources/Instructions

https://github.com/hackforla/website/blob/8a6df1dcd270c17403fa75c5842be9aa07ab3fa9/pages/wins/wins.html#L24-L481
[wins page](https://www.hackforla.org/wins/)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by linds-fonnes**
Fixes #2116 

### What changes did you make and why did you make them ?

  - Removed lines 24 - 481 from website/pages/wins/wins.html
  - Created /assets/js/wins.js file with the  code from lines 24-481
  - Added wins.js script tag to wins.html 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes made

### CODE REVIEW

**Review by SAUMILDHANKAR — DISMISSED** [review]
@linds-fonnes: Thanks Lindsey for working on this issue. I can see the new files in my environment. The Wins page also looks the same. Thank you.

**Review by adam-abundis — CHANGES_REQUESTED** [review]
@linds-fonnes Thank you for taking this issue on. We seem to have lost the see more/see less functionality of the wins page. The function call is hardcoded into the HTML. I have created a fix to resolve the console errors from the file change.

Please complete the following:
- [x] create a new line between 84-85 and add the following code:
```js
document.addEventListener('click', event => {
  // if the .see-more-div element is clicked
  if (event.target.closest('.see-more-div')) {
    // open the seeMore with the id of the selected target 
    seeMore(event.target.id)
  }
  if (event.target.matches('.overlay') || event.target.closest('.overlay-close-icon') || event.target.closest('.top-buffer') || event.target.closest('.bottom-buffer')) {
    hideOverlay();
  }
  // else, do nothing
  return false;
}, false);

document.addEventListener('keydown', function(event) {
  // if its the enter key and the .see-more-div element is currently tabbed on
  if (event.key === "Enter" && document.activeElement.classList.contains('see-more-div')) {
    // run seeMore with the active tab element id
    seeMore(document.activeElement.id);
  }
  // else, do nothing
  return false;
}, false);
```
- [x] After you make the changes go to line 172 (under the window.addEventListener)
```
widthOutput = window.innerWidth;
```
add a variable declaration so it looks like:
```
let widthOutput = window.innerWidth;
```
- [x] Go to the `function hideOverlay` declaration and remove line 515:

```
if (e.target !== e.currentTarget) return;
```
- [x] Remove line 25-26 from pages/wins/wins-card-template.html (`onclick` and `keypress` attribute
https://github.com/hackforla/website/blob/bd7219c143f18936accba60fd1e831f50fa38fea/pages/wins/wins-card-template.html#L25-L26

- [x] Remove `onclick="hideOverlay()"` attribute from line 1, 3, 5, 27
https://github.com/hackforla/website/blob/bd7219c143f18936accba60fd1e831f50fa38fea/pages/wins/wins-overlay.html#L1
https://github.com/hackforla/website/blob/bd7219c143f18936accba60fd1e831f50fa38fea/pages/wins/wins-overlay.html#L3
https://github.com/hackforla/website/blob/bd7219c143f18936accba60fd1e831f50fa38fea/pages/wins/wins-overlay.html#L5
https://github.com/hackforla/website/blob/bd7219c143f18936accba60fd1e831f50fa38fea/pages/wins/wins-overlay.html#L27

**Note:** it's not a good practice to use the onclick an keypress HTML attribute and drop a JavaScript function into it. The changes above will allow us to move the logic back to the JS file and remove the attributes since we don't need them anymore.

Complete these changes and verify the see more/see less functionality works and you receive no errors in the console. Thank you again for helping with this issue. If you have any questions, feel free to reach out to me.

**Comment by linds-fonnes** [comment]
@abuna1985 Good catch, thank you! I made the requested changes and the see more/less functionality is now functioning correctly on my end.

**Review by adam-abundis — APPROVED** [review]
@linds-fonnes Thank you for making the changes! Everything looks good. I am approving this PR and merging it. Keep up the good work! 🌠 🌠 🌠

**Pull request merged**
