### PR TITLE
Added Kevin Yu's profile to Civic Tech Job section of Projects Page

### LINKED ISSUE #7556: Update Project Profile: Civic Tech Jobs Add Kevin Yu
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Kevin Yu
    github-handle: kevin31yu
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U061GQQ56Q4
      github: https://github.com/kevin31yu
    picture: https://avatars.githubusercontent.com/kevin31yu
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
[^3]: initiating ER:  #7521

### PR DESCRIPTION
**Pull request by srinipandiyan**
Fixes #7556

### What changes did you make?
  
  - Added a profile card with Kevin Yu's data to the Civic Tech Jobs section of the Projects page.
  -  Updated `civic-tech-jobs.md` file to include Kevin Yu's profile info:
  ```
- name: Kevin Yu
    github-handle: kevin31yu
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U061GQQ56Q4
      github: https://github.com/kevin31yu
    picture: https://avatars.githubusercontent.com/kevin31yu

```
 
### Why did you make the changes (we will use this info to test)?
  
  - To update the fronted interface for end-clients to reflect the latest profile data within the Civic Tech Jobs section.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before Kevin Yu's Profile Card

</details>

<details>
<summary>Visuals after changes are applied</summary>

After Kevin Yu's Profile Card

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
Review ETA: 8 PM 10/16/24 (EDT)
Availability: 6-10 PM Weekdays (EDT)

**Comment by siyunfeng** [comment]
Hi, @srinipandiyan ! 

I appreciate the clear details in `What changes did you make?` to clarify the corresponding changes to this issue. You also did a good job providing your availability and ETA in the original issue.

I'm not able to pull the date from your branch due to the branch conflicts. You might forget to pull/sync from the `gh-pages` branch before making the changes or submitting your PR. I recommend you resolve the conflicts so I will be able to review the changes you made. 

### Branch conflicts: 
7556-pull-conflict

**Comment by srinipandiyan** [comment]
Hi @siyunfeng,

I've synced the PR. Please try again at your convenience. Thank you!

Best,

Srini

**Comment by codyyjxn** [comment]
Review ETA: EOD
Availability: M > F

**Review by siyunfeng — APPROVED** [review]
Nice job, @srinipandiyan !

The changes you made are applicable to the issue. The before-and-after screenshots you provided are helpful to show the changes. 

Improvements: 
- Run `git pull` from `gh-pages` before working on the issue and submitting the PR to prevent branch conflicts in the future
- Update the before-and-after screenshots after updating your PR if the view changed
- Name the branch with more specific details, such as `add-kevin-yu-to-civic-tech-job-7556`

Thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
Hey @srinipandiyan great job on taking on this issue. 
The issue is linked correctly and the branch name is clear. Thank you for also providing the screenshots which help anyone see what changes were made. 
Great Job! Keep it up.

**Pull request merged**
