### PR TITLE
Refactor no results message component 4903

### LINKED ISSUE #4903: Refactor "No Results" Message from the Toolkit Filter and Reuse it for the Projects Filter
### Overview

The Projects Filter shifts to the center when no results are found by the filter. We need to add a "No Results" message so this shift does not occur.

### Details

The Toolkit page filter displays a "no results" message when no results are found by the filter. The code from `toolkit.js` will need to be 

- extracted into a new component/ element file
- refactored so that it can be reused on the projects and toolkit filters (or any future filter) 

Once the above is performed, the code can then be imported into the projects filter file (or any future filter file).

<details>
<summary>Current Functionality</summary>

Screen Shot 2023-07-01 at 7 23 48 AM
</details>

<details>
<summary>Desired Functionality</summary>

Screen Shot 2023-07-01 at 7 25 15 AM
</details>

### Action Items
- [x] Extract the HTML code from `toolkit.js` into a new file. Create the new file in the `_includes` directory. 
  - [x] Style the HTML as needed to match the design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?type=design&node-id=24097-286538). The "no results" message should look the same on any page. 
- [x] Extract the "no results" JS code from `toolkit.js` into a new file. Create the new file in the `elements` directory (path: `/assets/js/elements`).
- [x] Refactor the "no results" code so that it 
   - [x] functions similarly to the filter on the toolkit page when no results are found
   - [x] can be reused on the home, projects, and toolkit pages
- [x] Refactor the filter code on the home, projects, and toolkit pages as needed to get the "no results" code to work
- [x] Import/ include the code in the relevant filter files for the home, projects, and toolkit pages. 

### Resources/Instructions
- This issue was created for ER #4769. Reference the ER for more background and information. 
- [Write up of how to implement the 'no results" message on another page](https://github.com/hackforla/website/issues/4769#issuecomment-1592092127)
- [Write up of how to implement the projects filter on another page](https://github.com/hackforla/website/issues/3744#issuecomment-1496291746)
- Files to reference:
  - [Toolkit Page Filter JS Code](https://github.com/hackforla/website/blob/c536e346051b60957d46c3bcd62eef9118314645/assets/js/toolkit.js)
  - [Projects Page Filter JS Code](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
  - [Home Page HTML Code](https://github.com/hackforla/website/blob/gh-pages/pages/index.html)
  - [Projects Page HTML Code](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html)
  - [Toolkits Page HTML](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html)
- [Figma Design of "No Results" Message](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?type=design&node-id=24097-286538)

### PR DESCRIPTION
**Pull request by bphan002**
Fixes #4903 

### What changes did you make?
  - The initial action was to extract the HTML code from toolkit.js, but that was already done and moved to current-guides.html. No style was needed.
  -  A noResultsMessageComponent function was created and placed under /assets/js/elements/noResultsMessageFilter.js as a reusable function for any pages that have a left-column filter. The first parameter takes the filterParams, and the second is the text color of the results since the various pages have different background colors.
  

### Why did you make the changes (we will use this info to test)?
  - A no-result message message does not display currently on the home or project page if the filter finds no results.
  - Changes to the current message displayed used switch statements and were manually set depending on filterParams arguments passed.  I temporarily removed this since I do not think this is a good way of doing it if we want a reusable function.  Currently, the display is just the parameters argument passed in, which isn't ideal. 
  - The home page and project page use the same _includes file.  Since this is the case I only showed the visual for the Project Page, but the functionality is the same for the Home Page.

<details>

<summary> Visuals before changes are applied to Projects Page</summary>

Screenshot 2023-08-24 at 1 14 58 AM

</details>

<details>

<summary>Visuals before changes are applied to Toolkit Page</summary>

Screenshot 2023-08-24 at 1 12 03 AM

</details>

<details>
<summary>Visuals after changes are applied to Projects Page(Notice the title before colon are dependent on the parameters passed into the function)</summary>
  
Screenshot 2023-08-24 at 1 27 57 AM

</details>

</details>

<details>
<summary>Visuals after changes are applied to toolkit Page(Notice the title before colon are dependent on the parameters passed into the function)</summary>
  
Screenshot 2023-08-24 at 1 25 40 AM

</details>

Revision may be needed if we want the parameters to be named differently.  I'm opened to suggestions on how to tackle this.

#### NOTE TO REVIEWERS: The automated "Lint SCSS / Lint SCSS (pull_request)" check below should be ignored for your review. The linter itself is causing the scss error. - Will G.

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: 9/6
Availability: All day 9/4 through 9/6

**Comment by Adastros** [comment]
Availability (PST): 10 - 11 PM 07SEP2023, 2 - 3 PM 09SEP2023, 10 - 11 PM 11-12SEP2023
Review ETA (PST):  End of day 12SEP2023

**Review by kwangric — COMMENTED** [review]
Hey @bphan002, thanks for taking on this extra large issue! I've had some time to briefly look at your pull request, but my week has been busier than anticipated and I probably won't finish a full review until this week.

One of the first things I noticed was that the search function on the Projects and Home page don't seem to be working anymore. Performing the search does add the parameter to the URL, but doesn't actually change the results of the projects or add the tags. Additionally, after attempting a search, the filters don't work correctly until the page is refreshed.

I'll take a closer look at the code to see what is causing this later this weekend, just wanted to let you know my findings in case you have a better idea of the cause.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @bphan002, thanks for taking the time to work on this issue! 

I agree with @kwangric's findings. Based on my investigation, the issue stems from how the "Search" key from filterParams is handled. Functions such as `updateCategoryCounter` and `updateProjectCardDisplayState` will throw an undefined error trying to use the 'Search' key. 

Looking at what has changed in `current-projects.js`, it seems that a lot of the code involving the search bar were removed. The best way to fix this would be to bring back some or all of the code used for the search bar. This includes bringing back the use of "AND", "OR", and "-" to refine the search (if this is currently handled somewhere else in your code let me know!). 

You can also implement a different approach to handle the errors/ search functionality if you like. 

See issue #4136 for the search bar requirements.

**Comment by Adastros** [comment]
Also, could you update your fork/ branch to include the latest updates from the website repository? It looks like there is a merge conflict with the 'current-projects.js' file. Code involving the tools category of the filter was updated while this pull request was pending review.

**Comment by bphan002** [comment]
Thank you for the feedback. I'll look over this again.

Updated timeline
9/16

**Comment by bphan002** [comment]
I have re-added the original search function that was removed.  I'm not sure why I removed it in the first place, but I think it is working now.  The original comments with my first pull request are still an issue I would like guidance on.

Thank you

**Comment by Adastros** [comment]
Availability (PST): 10 - 11 PM 21SEP23, 3 - 4 PM 23SEP23, 10 - 11:30 PM 25SEP23
Review ETA (PST): End of day 25SEP23

**Review by kwangric — APPROVED** [review]
Thanks for making the changes!

- The code for the message was modified to be reusable for each page with filters.
- The no results message displays correctly on the home, projects, and tooltip page when no cards are displayed.
- The message shows all the filters and searches used.

I think that the parameters names are fine. For the tooltip message, we will want to either add an additional step before passing in the filter params to fix the text. Or change how the page handles the filters so it will work similar to the projects page. This can be done with a future issue I believe.

Overall great work with completing the issue!

**Review by Adastros — APPROVED** [review]
Hi @bphan002, thank you for fixing the searchbar functionality! 

- The searchbar functions as expected
- The no results message appears and correctly displays the search terms/ keywords used that led to the no results message
- No issues were found with the no results message at different viewport widths
- works on Firefox and Chrome

One thing that I want to mention is that the original intention of the first task in the issue I created was to move lines 13 - 24 in `noResultsMessageFilter.js` into a new HTML file in the `_includes` directory. From there, the the new HTML file would be included in the projects and toolkit page HTML files using Liquid (see [lines 48 - 53](https://github.com/hackforla/website/blob/e2c3169490ce8a053ef46f087a88b7cbabb97ad0/_includes/current-guides.html#L48) in [current-guides.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-guides.html) for an example). Reading the issue I created, I should have made that more clear. 

That being said, the current implementation does make the no results message a reusable component. Instead of implementing it as mentioned above, it is implemented through JavaScript through `noResultsMessageFilter.js`, which is included in the relevant HTML page files as an extra script tag.

Since this issue is time sensitive and does make the no results message into a working reusable component, I'm okay with the changes in this pull request.

 In regards to parameter names in the no results message on the toolkit page, I agree with @kwangric. That can be addressed in a new, separate issue. 

Good job and thank you for working on the issue!

**Pull request merged**
