### PR TITLE
Replace GitHub with GitHub in ui-ux.yml

### LINKED ISSUE #7113: Replace `Github` with `GitHub` in _data/internal/communities/ui-ux.yml
### Overview
We need to replace instances of `Github` with `GitHub` so that we display the company name correctly, and we need to test the changes to ensure the behavior and appearance of any and all related webpages are unchanged.    

### Action Items
- [x] Open `_data/internal/communities/ui-ux.yml` in your IDE
- [x] Change
```
 - name: Github
```
to
```
 - name: GitHub
```
- [x] Find all the files that are connected to this change.  (e.g., if its a yml or md file, what files or scripts use the data stored in that file).  And document briefly how they work together.
- [x] Define where you expect the change to show up on the website (e.g., the footer of the website).  Can be on multiple pages
- [x] Write a test procedure, in a comment, and then use it to test the change.  Include a link to this comment in your PR.
- [x] Add/commit changes then create a PR as usual.  Document the test procedure in the Pull Request.  

### Resources
- This issue resulted from #6161

### Merge Team
- [_data/internal/communities/ui-ux.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml)
- [x] After closing this issue, check off the dependency in #6161.  If all dependecies have been completed, close #6161

### PR DESCRIPTION
**Pull request by taylorbeee**
Fixes #7113 

 - The elements edited in this pull request are from the data stored in .yml file that is referenced when the page: www.hackforla.org/communities-of-practice is launched. This page then fetches each .yml and loads them as separate cards indicating the different communities and leaders' contact information. 

Link to test procedure comment: https://github.com/hackforla/website/issues/7113#issuecomment-2253631350

### What changes did you make?
  - Change links.name from Github to GitHub
  

### Why did you make the changes (we will use this info to test)?
  - This change was made to have all the code spell the brand 'GitHub's name correctly and be uniform throughout the project.
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - N/A

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA:  EOD 7/27/24
Availability: 9-5 PM Monday - Friday

**Review by aadilahmed — DISMISSED** [review]
I've checked the ui-ux.yml file and made visual confirmation that the name attribute for the GitHub link was changed to the correct text of "GitHub", with no visual changes to the website. Good job!

**Comment by t-will-gillis** [comment]
Hi @daras-cu, @buneeisSlo, @Kle012, and @taylorbeee Just a friendly reminder- Since each of your open PRs are similar, you can help the review process move along by reviewing each other’s PRs. Thanks!

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @taylorbeee, when I try to run the website to test I get an error connected to the `ui-ux.yml` file, it looks like you also changed the indent of line 49 when editing. The error:

Screenshot 2024-07-29 153544

**Comment by taylorbeee** [comment]
> Hi @taylorbeee, when I try to run the website to test I get an error connected to the `ui-ux.yml` file, it looks like you also changed the indent of line 49 when editing. The error:
> 
> Screenshot 2024-07-29 153544

Thank you for this heads up @daras-cu !! I believe I fixed the issue.

**Comment by t-will-gillis** [comment]
Hey @taylorbeee please don't forget to "Re-request review" from 'daras-cu' by selecting the chasing arrows next to their name, eg:  

Screenshot 2024-07-31 143413

**Review by daras-cu — APPROVED** [review]
@taylorbeee looks great, I'm no longer getting the error and the page is displaying without any visual changes. Everything else looks correct with the pull request, good job.

**Pull request merged**
