### PR TITLE
Add github-handle to Richa Srivastava

### LINKED ISSUE #6724: Add github-handle for Richa Srivastava in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Richa Srivastava
```
with
```
- name: Richa Srivastava
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by DrAcula27**
Fixes #6724 

### What changes did you make?
  - Opened the file _projects/ems-triage-tracker.md in my IDE
  - Replaced:
     `- name: Richa Srivastava`
  - With:
     `- name: Richa Srivastava`
     `   github-handle: `
  - Ensured no other changes were made (a.k.a. no Prettier automatic reformatting)
  - Used spaces to indent, not tabs.

### Why did you make the changes (we will use this info to test)?
  - to create a single variable `github-handle` to hold the GitHub handle for each member of the leadership team eventually reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No visual changes to the website.

### CODE REVIEW

**Comment by iancooperman** [comment]
ETA: 5/15 EoD
Availability: 5/15 6pm-9pm

**Comment by Jperparas** [comment]
**ETA:** 5/15 EoD
**Availability:** 5/15

**Review by iancooperman — APPROVED** [review]
@DrAcula27 Great job! You correctly linked your issue and titled your development branch appropriately, though it could benefit from being a bit more descriptive. Plus, you avoided making any out-of-scope changes. Thanks for your contribution!

**Review by Jperparas — APPROVED** [review]
Hi @DrAcula27 Good Job on this issue!
- Issue linked
- PR going into correct branch
- code changes are consistent with issue
- changes are outlined clearly with a reason
- No Visual Changes

Good luck on the next one!

**Pull request merged**
