### PR TITLE
Update Public Tree Map Slack Link #6514

### LINKED ISSUE #6514: Project Slack links: Public Tree Map
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to edit the Slack link for the project so that we have continuity between project Slack links.

### Action Items
- [x] In `_projects/public-tree-map.md`, for the Slack `url` under the `links` section, change 

From:
```
url: 'https://hackforla.slack.com/messages/C9UU5KKAA/'
```
To:
```
url: 'https://hackforla.slack.com/archives/C9UU5KKAA/'
```
- [x] Ensure that clicking the Slack link resolves to the new address at the following places:
  - [x] On the [Projects page](https://www.hackforla.org/projects/), the Slack link under the `Links` field for the project's card
  - [x] On the [Public Tree Map page](https://www.hackforla.org/projects/public-tree-map),
    - [x] the Slack link under the `Links` field in the Project Overview section
    - [x] the Slack link in the Resources/Instructions section 
- [x] Once your pull request is merged, go to #4564 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4564 to **Questions / In Review** column and add a **ready for dev lead** label to it

### Resources/Instructions
- Directory to find the page once you have it in your IDE: `_projects/public-tree-map.md`
- [Projects page](https://www.hackforla.org/projects/)
- Project page URL: https://www.hackforla.org/projects/public-tree-map
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/public-tree-map.md?plain=1
- This issue is tracked in #4564

### PR DESCRIPTION
**Pull request by elisetvy**
Fixes [#6514](https://github.com/hackforla/website/issues/6514)

### What changes did you make?
  - Update the Slack link for the Public Tree Maps project 

### Why did you make the changes (we will use this info to test)?
  -  So that we have continuity between project Slack links

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updating Slack link. No visual changes to the website.

### CODE REVIEW

**Comment by w1ld-r** [comment]
Hey @elisetvy Can you add the labels from the issue (#6514) onto this PR? It looks like the workflow that adds those automatically failed. Either something went wrong, or maybe you created the PR in a different way than the workflow expects. Thanks!

**Comment by elisetvy** [comment]
@gaylem just added the labels. Thanks for the feedback!

**Comment by tony1ee** [comment]
**Review ETA**: EOD 04/13/2024
**Availability**: 12-8 PM SAT

**Review by tony1ee — CHANGES_REQUESTED** [review]
Hi @elisetvy, thank you for submitting this pull request.

You did great on:
1. choosing the correct branch for pull request
2. linking the issue
3. making the slack url change as needed for the issue
4. making no visible changes on website for this link change

However, I did find an issue with your request:
- unnecessary changes at line **9** and line **50** for file `public-tree-map.md`

[Review guideline](https://github.com/hackforla/website/wiki/How-to-review-pull-requests#step-4-take-a-look-at-the-source-code) requires changes to be **applicable and clean**, and unfortunately this does not seem to be met.

Please revert the changes at line 9 and line 50 in the file `public-tree-map.md` to their original state. Once you've made these adjustments, please push the updated changes to your branch, and I will be happy to review it again. 

Thank you for your efforts and cooperation in keeping our project's changes clean and efficient!

**Comment by elisetvy** [comment]
@tony1ee hi Tony! Thank you for the feedback. Is using 'git revert [id]' the best way to revert a change? I made two changes/commits for this issue. The second change was because I accidentally mistyped something the first time. Should I revert both of these commits and then make the necessary changes? Also curious what would have caused those unnecessary changes in the first place because I didn't touch those lines, but I did notice them get "changed" in the commit history.

**Comment by tony1ee** [comment]
Hi @elisetvy, you can choose to add another commit that fixes line 9 and line 50 so they appear not changed compared to `hackofla:gh-pages` (essentially, adding new commits that negate the unnecessary changes)

After you push it to `elisetvy:update-project-slack-links-6514`, this pull request should automatically update to reflect any new commit, at which point we can move forward with further review.

Thank you for your efforts, looking forward to your updates!

**Comment by tony1ee** [comment]
To answer your question, one potential reason for these changes made without your explicit actions might be you enabled "format on save" feature on your code editor.
If you mean to keep this feature on but want to avoid unnecessary changes to be committed, you can choose to only add the lines of change you want to make via `git add -i` (or `git add --interactive`), instead of adding the whole file to staging, after which you can safely drop the unintended changes.

**Comment by elisetvy** [comment]
@tony1ee hi Tony, I just made a new commit to negate the unnecessary changes. I think they were caused by me having format on save on, as you said - thanks for the explanation + advice!

**Comment by elisetvy** [comment]
I made a few commits while still wrestling with my formatter. I think all unnecessary changes have been reverted now.

**Comment by LRenDO** [comment]
Hi @Beatriz-G! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Comment by Beatriz-G** [comment]
ETA: EOD 04/17/2024
Availability: 11am-7pm Mon-Th

**Review by Beatriz-G — APPROVED** [review]
Line 34 matches requested changes. Updated public link tree map from messages to archives.

**Review by tony1ee — APPROVED** [review]
Thanks @elisetvy for the effort of making the requested changes, everything looks good now and I am happy to approve this pull request!

**Pull request merged**
