### PR TITLE
Updated section 2.7f i SSH for mac in CONTRIBUTING.md

### LINKED ISSUE #5693: Update CONTRIBUTING.md Section 2.7.f i SSH for Mac
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac) we need to clarify the instructions used for setting up an SSH key for Mac in Section 2.7.f i in order to avoid confusion. 

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to Section 2.7.f i "Setting up SSH Keys for Mac"
- [x] Replace
```
4. Next you need to add your ssh key to your ssh agent.
```
with
```
4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by ChrisKildunne**
Fixes #5693 

### What changes did you make?
  - Updated 4. Next you need to add your ssh key to your ssh agent. to  4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step. in CONTRIBUTING.MD

### Why did you make the changes (we will use this info to test)?
  - To provide more clear instructions to newcomers.

### CODE REVIEW

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hey @ChrisKildunne 

There two issues with this PR. Firstly, there are some commits in your PR that aren't relevant to the issue. Your local repository doesn't seem to be synced to the HFLA repository, so it seems like your commits are undoing changes that have happened in the meantime. You can sync a branch in your local repository to the HFLA repository by typing: `git pull upstream gh-pages`. Generally you should type that command while in your gh-pages branch before working on an issue, and then create an issue branch. You can either create a new branch and a new PR, or sync your issue branch and re-do the changes. 

Secondly, the PR isn't fully finished. There's one more checkbox in the linked issue in which you're meant to push your changes to your local fork and add the link to the CONTRIBUTING.md of the relevant page so the changes can be reviewed.

If anything here is confusing, feel free to reach out.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @ChrisKildunne I share the concerns of @ajb176 regarding the extraneous changes in CONTRIBUTING.md and the unfinished Action Item in this issue.  The extraneous changes seem to be largely removal of blank spaces and replacement of characters, for instance `*` characters have been replaced by `-`.  Is it possible that these have resulted from a markdown linter or prettifier?  It would be worthwhile disabling VS Code extensions so that only the required changes are made.

**Comment by ChrisKildunne** [comment]
Copy, I do use those extensions in vs code. I can disable them and redo it.
As far as the extra commits that are not related to the issue, I had that
problem with my last pull request. I have been running git pull upstream
gh-pages to sync my branch, I am not sure what the root of the issue is but
regardless I will go back and redo it. I appreciate the feedback and I
might be reaching out soon if I cant figure out the extra commits.

**Comment by ChrisKildunne** [comment]
Hi, So Ive been trying to resolve the issues stated prior but am running
into some blockers. I have disabled said extensions and toggled off format
on save in vs code but I still am running into *** changing to ---. I think
this is why I am running into so many merge conflicts. Any thoughts or
advice would be greatly appreciated.
Thanks,
Chris

**Comment by ExperimentsInHonesty** [comment]
Hi @ChrisKildunne that sounds like a real bummer.  Here is what I would do.  I would turn off all extensions.  And then try saving it the way you want it.  If it is still changing *** to ---, then I would go to slack channel for Engineering and explain what you are experiencing and put screen shots.  Then, I would also go to the next Engineering community of practice meeting on Thursday and show them, in real time, what you are experiencing.

**Comment by ChrisKildunne** [comment]
For whatever reason, I believe I got it to work but I am still not 100%
confident. Thanks for all the help.

**Pull request closed without merging**
