### PR TITLE
Update overview link 2240

### LINKED ISSUE #2240: Update how 'Overview' link opens for Expunge Assist
### Overview
As a user, clicking on the 'Overview' link for the Expunge Assist project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Expunge Assist's pdf file currently opens](https://docs.google.com/document/d/1JFZGKxeEBWVak_GATgIt0Knyr9_gJ15CBirynebb4tg/preview)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Expunge Assist's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/expunge-assist) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md)
[Project Page](https://www.hackforla.org/projects/expunge-assist)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

### PR DESCRIPTION
**Pull request by Pauljsyi**
Fixes #2240

### What changes did you make and why did you make them ?

  -Instead of the Overview link redirecting to a google docs page it opens the same file in pdf format stored locally.
  -Updated markdown file regarding Expunge Assist overview url to point to a pdf file stored locally.
  -Setting a standard on how pdf files should be opened.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Update-Overview-Link-2240-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Update-Overview-Link-2240-after

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1 hour
- Review ETA: Thu, Feb 3

**Review by BrianCodes33 — APPROVED** [review]
I reviewed the files and everything looks good. Nicely done!

**Review by JessicaLucindaCheng — CHANGES_REQUESTED** [review]
@Pauljsyi Good job on this issue! Could you please do the following?

1) Please add your pull request to the project board.
Add-to-project-board

2) In the changes you made section, you wrote, "Updated markdown, html and js files regarding Expunge Assist overview url to point to a local directory containing the pdf file." However, in the Files changed tab, I only see the pdf being added and line 37 of the markdown file with changes. Could you edit and clarify in your post on what you meant in terms of updating html and js files?

**Review by JessicaLucindaCheng — APPROVED** [review]
@Pauljsyi Looks good to me! Thanks for making those changes!

**Pull request merged**
