### PR TITLE
Deleted line 12: unused alt-hero field

### LINKED ISSUE #2927: Remove unused `alt-hero` field from design-systems.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/design-systems.md`, remove line 12 for the alt-hero
```
alt-hero: 'Design Systems hero background'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/design-systems.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/design-systems.md?plain=1#L12

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by poorvi4**
Fixes #2927

### What changes did you make and why did you make them ?

  - Deleted line 12 from design-systems.md, removing unused alt-hero field to improve readability and reduce loading time

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
NA

### CODE REVIEW

**Comment by blulady** [comment]
Review ETA: 6 PM 3.22.22
Availability: 4-6 Tuesday 3.22.22

**Comment by Jaretzbalba** [comment]
Review ETA: 2 PM 3.22.22
Availability: 12-2 PM Tuesday 3.22.22

**Comment by Jaretzbalba** [comment]
@poorvi4 Everything looks good to me! Thank you for working on this issue!

**Review by Jaretzbalba — APPROVED** [review]
@poorvi4 Everything looks good to me! Thank you for working on this issue!

**Review by blulady — APPROVED** [review]
Looks Good. There is a linked issue and  it is correct. Source code looks clean and the changes are relevant. There aren't any changes to view in the browser so no images are needed.
Great Job!!

**Pull request merged**
