### PR TITLE
Resolved CodeQL Alerts 6 and 8

### LINKED ISSUE #6227: Resolve CodeQL alert 6 and 8 "Potentially unsafe external link"
### Dependency
- [x] `_layouts/guides.html` is in production (specified in _config.yml)

Note: when the above dependency is satisfied, before prioritizing this issue we must reopen the CodeQL alert on this page: https://github.com/hackforla/website/security/code-scanning/6 and https://github.com/hackforla/website/security/code-scanning/8

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 6](https://github.com/hackforla/website/security/code-scanning/6) and [alert 8](https://github.com/hackforla/website/security/code-scanning/8) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/6
- [x] Open the file `_layouts/guides.html` in your IDE
- [x] Replace BOTH instances of:
```
<a href="{{ item.links.linked-in }}" target="_blank" title="Linkedin Profile" class="fa fa-linkedin fa-xl" style="margin-right: 13px;
text-decoration: none;"></a>
```
with
```
<a href="{{ item.links.linked-in }}" target="_blank" title="Linkedin Profile" class="fa fa-linkedin fa-xl" style="margin-right: 13px; 
text-decoration: none;" rel="noopener noreferrer"></a>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Sample webpage using this template: https://www.hackforla.org/guide-pages/2FA
3. This issue is part of #5129

### PR DESCRIPTION
**Pull request by SteeRevo**
Fixes #6227 

### What changes did you make?
  -added the attribute rel="noopener noreferrer" to both instances of `<a href="{{ item.links.linked-in }}" target="_blank" title="Linkedin Profile" class="fa fa-linkedin fa-xl" style="margin-right: 13px; text-decoration: none;"></a>`

### Why did you make the changes (we will use this info to test)?
  - To prevent the alert "Potentially unsafe external link" from appearing in CodeQL

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Changed lines in `_/layouts/guides.html` file. No visual changes to website

### CODE REVIEW

**Comment by w1ld-r** [comment]
Sorry @abenipa3, I accidentally removed you from the reviewers when I tried to add myself. Managed to get you back on here, though! Let me know if this caused any issues for you.

**Review by w1ld-r — APPROVED** [review]
Thanks for working on this, @SteeRevo!

- Your branch is correct
- The issue is correctly linked from your PR
- You made the appropriate changes to the correct lines
- Your PR clearly states the changes you made

Approved! Great work and thanks again :)

**Comment by w1ld-r** [comment]
Availability: Weekdays 10AM - 8PM CST
ETA for review: 2024-02-20

**Comment by Thinking-Panda** [comment]
@abenipa3 Whenever possible, Please update your availability and review ETA for this PR.

**Comment by abenipa3** [comment]
@Thinking-Panda @gaylem Hi there, sorry I just read the notifications of this PR - I took a quick glance at this PR and read that this is for the guide-pages based on the description and the code change?

I haven't been active in HfLA for almost two years as I've been working full-time so I'm not sure if I'm suited to review this as I've been out of the loop since summer 2022 🙇 

If you have any questions relating to what I've done re: guide pages in the past  or if I should be informed of something related that requires my review, please let me know (as I was not aware of this PR and the issue linked in the description till now).

P.S. Looks good/makes sense to me (from reading the changes only though) 👍 I'm happy to see further improvements are being made on the guide pages, too 😄

**Review by t-will-gillis — APPROVED** [review]
Hey @SteeRevo - Great work! Your branches are correct, you are linked back to the issue, you have provided a concise description of what you did and why, and you note that there are no visual changes.

Your code changes address both CodeQL alerts 6 and 8. 

Thanks for addressing these two "Potentially unsafe external link" alerts!

**Comment by t-will-gillis** [comment]
Hey @abenipa3 welcome back! Please message me on Slack when convenient. Thanks!

**Comment by abenipa3** [comment]
Hi @t-will-gillis, I think there's a misunderstanding here.

I apologize if I wasn't clear earlier and for continuing the conversation here as I no longer have a Slack account in HfLA's space. 

I'm not sure if I was tagged to review this PR by mistake; I had mentioned earlier I was not aware of this PR and the issue tied to it. 

I also had mentioned that I haven't been able to contribute to HfLA since 2022 and won't be able to continue to do. 

If there's any further comments or questions, I am reachable via email at abenipa3@gmail.com. Thanks

**Comment by w1ld-r** [comment]
Hey @abenipa3 that was probably my mistake. As I said in my previous comment, I accidentally removed a reviewer, and when I went to try to add them back your name was the first to come up as a suggestion from Github. I went ahead and removed you. Thanks for clarifying!

**Pull request merged**
