### PR TITLE
Added Member Nooria Ali To Civic Tech Jobs

### LINKED ISSUE #7730: Update Project Profile: Civic Tech Jobs Add Nooria Ali
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile under the other PMs (the PMs should be at the top). 
```
  - name: Nooria Ali
    github-handle: nooriaali9
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U078JUY57GW
      github: https://github.com/nooriaali9
    picture: https://avatars.githubusercontent.com/nooriaali9
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: (https://www.hackforla.org/projects/civic-tech-jobs)
- initiating ER:  #7490

### PR DESCRIPTION
**Pull request by dvernon5**
Fixes #7730

### What changes did you make?
  - Added the name Nooria Ali to `_project/civic-tech-jobs.md`

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before_Webpage_Changes
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After_Webpage_Changes

</details>

### CODE REVIEW

**Comment by mchait18** [comment]
Review ETA: 12 PM 11/27/24
Availability: 10-3 PM EST M-F

**Comment by mugdhchauhan** [comment]
Review ETA: 27 Nov @ 6 PM (GMT)
Availability: Daily @ 6 PM - 8 PM (GMT)

**Review by mugdhchauhan — APPROVED** [review]
## PR Review

@dvernon5 Thank you for your PR. 

### Things that went well

- Providing Availability & ETA in the issue.
- Good PR title, issue number is added, what changes you made and why are clear, good screenshots, and CodeQL alerts have been checked.
- Branch name is ok but can be better.
- I can see the changes in my local environment.
- All links are working fine e.g. GitHub and Slack.

### Things to change

I have approved this PR because the code is fine but please make the following changes:

- [x]  In the comments on the changes in the Pull Request for your particular file path use backticks ``(`)`` to enclose the file path such as `_projects/expunge-assist.md`.
- [x] For the PR title: it is 'Civic Tech Jobs' not 'Civic Tech Job'. Please rename PR title.

Suggestion (for your next task): the branch name could be better by using a more descriptive branch name such as `Civic-Tech-Jobs-add-Nooria-Ali-7730`.

Thank you. I appreciate your work. Feel free to ask if you have any questions.

**Review by mchait18 — APPROVED** [review]
Hello @dvernon5 
- The code changes look good.
- The issue is linked correctly
- CodeQL alerts are checked
- The original issue items are checked
- The content added is correct
- Before and After photos are accurate

Great job

**Comment by dvernon5** [comment]
@mugdhchauhan 

Thank you for your feedback. I took your advice and made the following changes. Also, I will be more descriptive of my branch name for the next issue.

Once again thank you for all of your suggestions.

**Comment by dvernon5** [comment]
@mchait18 

Thank you for your time and feedback. I truly appreciate it.

**Comment by belunatic** [comment]
Review ETA: 12 PM 11/27/24
Availability: 2-4 PM PST M,W,F

**Review by belunatic — APPROVED** [review]
@dvernon5 

**Amazing job!**
- Issue number present
- Images are perfect
- Code added is clear and concise

Thank you for taking care of the issues stated by @mugdhchauhan 

Great Job and Happy Thanksgiving!

**Comment by rachelcorawood** [comment]
Review ETA: noon 11/27/24
Availability: Available W & F Before 3pm

**Comment by rachelcorawood** [comment]
This looks great! 

-You completed it in the right branch
-You linked the issue
-You understand the issue and executed well
-Included visuals
-Made the recently requested updates from other reviews! 

Thank you!

**Review by rachelcorawood — APPROVED** [review]
This looks great!

-You completed it in the right branch
-You linked the issue
-You understand the issue and executed well
-Included visuals
-Made the recently requested updates from other reviews!

Thank you!

**Pull request merged**
