### PR TITLE
Add Mario Antonini to Merge Team

### LINKED ISSUE #6864: Update Project Profile: Add Mario Antonini to Merge Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hackforla.org Website project page](https://www.hackforla.org/projects/website

### PR DESCRIPTION
**Pull request by dcotelessa**
Fixes #6864

### What changes did you make?
  - Added Mario Antonini name, github-handle (blank), role, slack link, github link, and picture to the end of the leadership variable
  ```
- name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
```
  - Verified the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on  local environment
  - include a screenshot with pull request

### Why did you make the changes (we will use this info to test)?
  - Mario Antonini is being added to Merge Team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

https://github.com/hackforla/website/assets/5404705/5885e29a-29f3-4096-a835-467bf66b0029

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
https://github.com/hackforla/website/assets/5404705/4537a02c-913b-4ac0-9e82-28db8de71c50

</details>

### CODE REVIEW

**Comment by dcotelessa** [comment]
This ticket is an update of this PR:
https://github.com/hackforla/website/pull/6921
to rename the branch to include the ticket #.

**Comment by ino-iosdev** [comment]
ETA: End of 6/5

**Comment by robertnjenga** [comment]
Review ETA:  06/03/2024
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hi @dcotelessa!
The branching was done correctly, you linked the issue, you gave a description of what you did and why the changes were made, and also provided the appropriate before and after screenshots.
I'm able to verify in docker that the changes appear correctly on the website project page.
Thank you for taking up and completing this issue!

**Review by ino-iosdev — APPROVED** [review]
Hi @dcotelessa  , It's such a blessing to have you as part of the team here!
 
- Naming was appropriate
- Direction between branches `from` and `to` are clear
- The changes and why were clear
- PR issue link was clear
- visual changes to the website look good, screenshots are very helpful
 
Great job, thank you for contributing!

**Comment by ino-iosdev** [comment]
> Hi @dcotelessa! The branching was done correctly, you linked the issue, you gave a description of what you did and why the changes were made, and also provided the appropriate before and after screenshots. I'm able to verify in docker that the changes appear correctly on the website project page. Thank you for taking up and completing this issue!

@robertnjenga for some reason your approval checkmark wasn't showing up.

Screenshot 2024-06-05 at 1 10 55 AM

I wonder if it's because you didn't review in the yellow warning pop-up on the top, or can also do it in the `Files changed` tab to sync the approval to have the checkmark appear. I'm not sure whether missing this checkmark affects the merging team's progress to move forward.

[
Screenshot 2024-06-05 at 1 15 27 AM
](url)

**Review by robertnjenga — APPROVED** [review]
PR approved in previous comment.

**Comment by Thinking-Panda** [comment]
@dcotelessa Thank you for working on this issue.

**Pull request merged**
