### PR TITLE
Refactor current-project.html

### PR DESCRIPTION
**Pull request by akibrhast**
Major refactor of current-project.html javascript functionality to ensure that

- Code is more maintainable over time
- Code is easily modifiable over time to add or remove features
- Code is well documented

### CODE REVIEW

**Comment by erikaBell** [comment]
😭🥲😭🥲😭🥲😭 = my heart. 



Only two things to note @akibrhast 
<details>
<summary>Missing elements from design</summary>

### **Live Site**
Screen Shot 2021-04-15 at 12 30 04 PM

### **Akib's Branch**
Screen Shot 2021-04-15 at 12 33 05 PM

</details>

**Review by erikaBell — DISMISSED** [review]
Requesting change on design elements, mentioned in comment above.

**Comment by akibrhast** [comment]
@erikaBell  Requested edits will be in at some point tonight or tomorrow.

**Review by erikaBell — CHANGES_REQUESTED** [review]
<details>
<summary>Make Following Change: add number of filter tags currently in use</summary>

Screen Shot 2021-04-16 at 12 38 48 PM
</details>

One bug I found on mobile view, at `width < 660`, `clear all` disappears.
<details>
<summary>Example of Bug</summary>

Screen Shot 2021-04-16 at 12 36 49 PM

Screen Shot 2021-04-16 at 12 36 26 PM

</details>

On top of that, if we are to keep the filter tags during mobile view, at `width < 461`, we will need to create a styling change on filter tags, re-aligning them on the page.

Honestly though, I don't know if the filter tags need to be there once width hits 659. My opinion is that it starts to get too cluttered. In any case, you can ask @daniellex0 about her thoughts on that. Once we have an answer on the `mobile-view` question, we'll know what changes need to be made for it.

**Comment by akibrhast** [comment]
> Make Following Change: add number of filter tags currently in use - @erikaBell 

Done

> On top of that, if we are to keep the filter tags during mobile view, at width < 461, we will need to create a styling change on filter tags, re-aligning them on the page.
> 
> Honestly though, I don't know if the filter tags need to be there once width hits 659. My opinion is that it starts to get too cluttered. In any case, you can ask @daniellex0 about her thoughts on that. Once we have an answer on the mobile-view question, we'll know what changes need to be made for it. - @erikaBell 

Please open a new/separate issue in regards to the comments you made above

**Review by erikaBell — APPROVED** [review]

**Pull request merged**
