### PR TITLE
Fixes #7046  Added github handle to _projects/heart.md for Jason LaManque.

### LINKED ISSUE #7046: Add github-handle for Jason LaManque in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Jason LaManque
```
with
```
- name: Jason LaManque
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by DakuwoN**
Fixes #7046 Added github handle to _projects/heart.md for Jason LaManque.

### What changes did you make?
  - Add Github handle to markdown file

### Why did you make the changes (we will use this info to test)?
  - Reduce redundancy 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by Anahisv23** [comment]
ETA: EOD 
Availability:  M - F 11am - 5pm

**Review by Anahisv23 — APPROVED** [review]
Hi @DakuwoN thanks for working on this issue. The only feedback I have is making the title of the PR more descriptive to summarize what the goal of the issue is. Other than that nice job! 

Here's what you did well. 
- Into and from branch are correct 
- The issue linked is correct
- Appropriate files were changed, no indentation was applied, and github-handle variable was added

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @DakuwoN! Overall looks great!

- The branching was done correctly
- Issue number was listed
- Changes were made correctly in the code
- Changes do not impact the site
- A note was included that there were no visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I have one non-functional request. Please change the title to something descriptive of the changes. For example, "Added github handle to `_projects/heart.md` for Jason LaManque". You can click the circle with the arrows next to my handle in the reviewers section to re-request a review once it's updated. Thanks!

**Review by LRenDO — APPROVED** [review]
Updated title looks great! Thanks for contributing and making the change!

**Review by mSharifHub — COMMENTED** [review]
correct format

**Pull request merged**
