### PR TITLE
added a new entry for Nga Do in the civic tech jobs page

### LINKED ISSUE #5388: Update Project Profile: Civic Tech Jobs (add Nga Do)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] Add a new entry for Nga Do:
```
  - name: Nga Do
    role: UX Researcher
    links:
      slack: https://hackforla.slack.com/team/U05JS3BS9FD
      github: https://github.com/ngadoq
    picture: https://avatars.githubusercontent.com/ngadoq
```
 - [x] Place Nga's profile with the other Researcher profiles
 - [x] Confirm on your local that links for the member appear to be correct (i.e. for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by blaycoder**
Fixes #5388 

### What changes did you make?
  - Added a new entry for Nga Do profile below Sarah Sanger profile in the civic-tech-jobs page

### Why did you make the changes (we will use this info to test)?
  - To keep the Civic Tech Jobs webpage up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before-updating-profile-civic-tech-jobs</a>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after-updating-profile-civic-tech-jobs</a>

</details>

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  9/26/2023
Availability: 10am - 2pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @blaycoder! Thanks for taking up this issue.
The pull request is done with the correct branch.
You linked the issue.
Code changes were made correctly.
Screenshots were included to show the changes, and the changes appear correctly on the browser. Great Job!
If possible just to clean up the PR comments, please remove the unused bullet points.

**Comment by blaycoder** [comment]
Remove unused bullet points

**Review by robertnjenga — APPROVED** [review]
@blaycoder Thank you for making the changes. Looks good!

**Review by kabszac — APPROVED** [review]
@blaycoder  the changes look good! Great work!

**Pull request merged**
