### PR TITLE
Add Github Handle for Yingjie Ou #7241

### LINKED ISSUE #7241: Add github-handle for Yingjie Ou in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Yingjie Ou
```
with
```
- name: Yingjie Ou
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by mimiwrp**
Fixes #7241 

### What changes did you make?
  - Add "github-handle:" to Yingjie Ou in the file _projects/tech-work-experience.md

### Why did you make these changes

- Adding "github-handle" to store github handle for contributor

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
  - No visual changes to the website

### CODE REVIEW

**Review by vorleakyek — APPROVED** [review]
The code looks good! Approved! 

Two small comments: 

1. Please edit your comment and add the "Why did you make the changes (we will use this info to test)?" in the PR comment as suggested in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31-how-to-make-a-pull-request.). 
2. Something to consider in the future: maybe include the person's name in the branch name for clarity 

Thanks for contributing!

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @mimiwrp, thanks for working on this issue. Everything looks good except as mentioned you are missing the "Why did you make these changes" section in your PR.
- Branches are set up correctly (I agree your branch names could be a little more specific in the future)
- Original issue is linked in the PR
- Changes to the file were made according to original issue
- Testing confirms the website is not changed visually

Once you add the missing section to your PR it will be ready to approve. Nice work!

**Comment by Thinking-Panda** [comment]
@mimiwrp - Please make the requested changes and request  a re-review.
screenshotPR

**Comment by mimiwrp** [comment]
Why did you make these changes
- Adding "github-handle" to store github handle for contributor

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@mimiwrp 
Thank you for taking on this issue. Everything looks good you are missing the: `Why did you make the changes (we will use this info to test)?`
This needs to be added in the comment underneath the 
`What changes did you make?`

**Comment by mimiwrp** [comment]
@vorleakyek @daras-cu @Thinking-Panda @codyyjxn Thank you so much for taking your time to review my pull request. I just edit the comment and I'm so sorry for the delay.

**Review by codyyjxn — APPROVED** [review]

**Review by daras-cu — APPROVED** [review]
Thanks for adding that section @mimiwrp, everything looks good!

**Pull request merged**
