### PR TITLE
Carlos 1510 fix css on toolkit page

### LINKED ISSUE #1510: Fix CSS on Toolkit page
### Overview
There's a CSS bug on the toolkit page and it doesn't look right. Stuck in mobile view -- check out toolkit-flex-container as possible culprit?

### Action Items
- [ ] compare the page and the Figma
- [ ] find bug (it's stuck in mobile view for some reason)
- [ ] fix bug :)

### Resources/Instructions
Page: https://www.hackforla.org/toolkit/
Figma (see pink rectangle): https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967

### PR DESCRIPTION
**Pull request by sanchece**
Fixed #1510

### CODE REVIEW

**Review by qiqicodes — DISMISSED** [review]
lgtm.

https://user-images.githubusercontent.com/68657634/117592237-af9cee80-b0ec-11eb-8ffd-e774319b5bbc.mov

**Review by daniellex0 — CHANGES_REQUESTED** [review]
Thank you so much for the quick turnaround! 

There is only one thing but it should be a quick fix now that you fixed the rest- the title and 'Suggest..' button are not supposed to be stacked in desktop (only in mobile) - they are supposed to look like this in desktop:

Screen Shot 2021-05-09 at 8 49 55 PM

I think this should be able to be fixed by making the "flex-direction: column" property only in mobile size  (in .suggest-guide-group) 

Thank you!!

**Review by akibrhast — CHANGES_REQUESTED** [review]
It looks like you deleted the file `assets/images/about/hfla-donate.gif` . Could you please ensure that your pull request does not delete that file ?

**Comment by erikaBell** [comment]
> It looks like you deleted the file `assets/images/about/hfla-donate.gif` . Could you please ensure that your pull request does not delete that file ?

@akibrhast I've been noticing that any time I pull from upstream, that gif gets removed.. and i have to manually ask for the change to be discarded. Not sure why, or when, it started happening, but it's been a week or two for sure.

**Comment by qiqicodes** [comment]
@akibrhast @erikaBell that happens when I update my branches as well.

**Comment by erikaBell** [comment]
@sanchece you can find the gif here: https://github.com/hackforla/website/blob/71a9798cc937592d98fe63133c6ad9db5f737898/assets/images/about/hfla-donate.gif 

and place it back into your branch

**Comment by sanchece** [comment]
Thanks for linking the gif @erikaBell. Fixed stacked button in toolkit page and added back the hfla-donate.gif


image
image

**Review by erikaBell — CHANGES_REQUESTED** [review]
I'm seeing that the file paths are there, but I'm not seeing the actual gif in the assets and receive the following error in my terminal when going to the "join-us" page

`hfla_site    | [2021-05-10 17:15:28] ERROR '/assets/images/about/hfla-donate.gif' not found.`

Is this happening for anyone else? @qiqicodes @akibrhast 

<details>
<summary>donation gif not found</summary>

Screen Shot 2021-05-10 at 3 18 31 PM

</details>

**Review by daniellex0 — APPROVED** [review]
Design looks good, thanks for making the edit @sanchece ! Approved pending the above discussion about the gif^

(FYI, the gif isn't showing up for me either)

**Comment by qiqicodes** [comment]
@sanchece @erikaBell @daniellex0 The gif is not showing up on my end.

I also have the same error
```
hfla_site  | [2021-05-10 18:36:26] ERROR `/assets/images/about/hfla-donate.gif' not found.
```

I've checked the directory, it is missing the gif. This could be the cause of gif not found error.

Also, with the mobile display:
<details>
<summary>Current Mobile View</summary>
<br>

</details>

<details>
<summary>Figma Shows Accordion for Mobile View</summary>
<br>

</details>

**Comment by daniellex0** [comment]
@qiqicodes Yes, the dropdown mobile display is actually for an [upcoming issue](https://github.com/hackforla/website/issues/1329) (this issue is a dependency for that one)

**Pull request merged**
