### PR TITLE
Renamed hack-nights page and added timezone info to meeting times section

### PR DESCRIPTION
**Pull request by cnk**
Addresses some of the issues on #403

### CODE REVIEW

**Comment by cnk** [comment]
This is how the meetings section currently looks:

MeetingTimesWorking

**Comment by ExperimentsInHonesty** [comment]
@cnk visual review of your changes (will fix meeting times not loading and add timezone lang) looks good.  @drubgrubby is going to do the code review.

**Review by drubgrubby — APPROVED** [review]
Reviewed code (and discussed the things I didn't understand with @cnk).  Everything looks tidy and in its place, and seems to function as it should. In my opinion, this PR is ready to merge.

**Review by ruben1s — COMMENTED** [review]
Looks good. Ready to merge

**Pull request merged**
