### PR TITLE
Updated project profile for Access the Data

### LINKED ISSUE #6064: Update Project Profile: Access the Data (Change Status to On Hold, Remove AJ Price & Jason Yung)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/access-the-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: AJ Price
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U02UZ5BK8UB'
      github: 'https://github.com/mxajPrice'
    picture: https://avatars.githubusercontent.com/mxajPrice
  - name: Jason Yung
    role: Project Manager
    links:
      slack: 'https://hackforla.slack.com/team/U059W9P96C8'
      github: 'https://github.com/merlinsmagic'
    picture: https://avatars.githubusercontent.com/merlinsmagic
```
- [x] Find the `status` variable and change the status
**From**
```
status: Active
```
**To**
```
status: On Hold
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Access the Data page [^2]
  - [x] the project's card on the Projects' page [^3]
- [x] Once your pull request is merged, go to #6018 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6018 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6018
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/access-the-data
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by iancooperman**
Fixes #6064

### What changes did you make?
  - Removed AJ Price and Jason Yung from leadership variable
  - Changed status variable from 'Active' to 'On Hold'

### Why did you make the changes (we will use this info to test)?
  - To keep information about the "Access the Data" project up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image
image

</details>

### CODE REVIEW

**Comment by agutiernc** [comment]
ETA: EoD 1/21
Availability: 1/21 - After 5pm

**Review by agutiernc — APPROVED** [review]
The following check out:
- correct linked issue and branch
- leadership entries removed from page
- status variable is updated
- Changes are reflected in the browser and in different viewports

Great job @iancooperman! Thanks for contributing.

**Comment by kwangric** [comment]
Hey @sornekian! When you get the chance, please leave a comment with your availability and ETA for your review. Thanks!

**Comment by sornekian** [comment]
ETA: 01/23/23 EoD
Availability: T-Su 7-11pm

**Comment by LRenDO** [comment]
Hi @sornekian! Thanks for volunteering to review this issue! When you have a minute, please update your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Comment by sornekian** [comment]
Sorry for the delay...
 - The correct issue number was stated
 - Two names were removed from the page
 - Active to On Hold was updated
 - Both of these changes look good on chrome and safari
Looks good to me, I approve this PR

**Review by sornekian — APPROVED** [review]
Sorry for the delay...
 - The correct issue number was stated
 - Two names were removed from the page
 - Active to On Hold was updated
 - Both of these changes look good on chrome and safari
Looks good to me, I approve this PR

**Pull request merged**
