### PR TITLE
Removed Yujin Chang from Project Profile: Lucky Parking

### LINKED ISSUE #5801: Update Project Profile: Lucky Parking (Remove Yujin Chang)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Yujin Chang
    role: UX/UI Designer
    links:
      slack: 'https://hackforla.slack.com/team/U0270QURQCD'
      github: 'https://github.com/eugenecha'
    picture: https://avatars.githubusercontent.com/eugenecha
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by jleung7158**
Fixes #5801

### What changes did you make?
  - Found the leadership variable in the _projects/lucky-parking.md file and removed Yujin Chang's information.

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

issue 5801 before changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
issue 5801 after changes

</details>

### CODE REVIEW

**Comment by jleung7158** [comment]
For availability and ETA for this issue:
i. Availability: Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ii. ETA: 1- 1.5 weeks

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @jleung7158!
Great job overall with this pull request!

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site. Yujin Chang has been removed.
- Relevant images were included to show visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I do have one request to remove changes that are not included in the issue. Line 65 of [_projects/expunge-assist.md](https://github.com/hackforla/website/pull/5901/files#diff-8adbe09f7ce64f808992f4dcc03399dd7a2da1d2eca4e5008d7f3717824f30dd) has two backticks added that shouldn't appear.  It should read `Slack` instead of  `Slack''`. I believe this is likely due to not pulling the most current changes into your local gh-pages before branching. If I remember correctly, you were working in that file for your last issue. 
- [x] Please pull the hackforla/website gh-pages into your feature branch and then push it back to your fork. The PR should automatically include those changes once they are pushed. You can verify the changes in the `Files changed` tab of the pull request to make sure only the intended changes are included.

Once it's updated, remember to click the circle with the arrows next to my user name in the reviewers section. Thanks for taking the time to contribute to the website!

**Comment by jleung7158** [comment]
Thank you @LRenDO ! I have tried doing what you suggested, and I hope it was done correctly. It's strange because I did do a git pull upstream and push onto my local branch before making the new feature branch, but I guess it is out of sync. I will double check the CONTRIBUTING.md to see what I can do, though I am also open to any suggestions you may have!
For availability and ETA for this issue:
i. Availability: Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ii. ETA: 1- 1.5 weeks

**Comment by LRenDO** [comment]
Thanks @jleung7158! It looks like it fixed the Slack issue in expunge-assist.md, but looking at the `Files changed` tab, Sam Sengupta is added back.  It looks like the PR for removing Sam was merged yesterday (#5902) so it could have been removed after you pulled the changes yesterday.  If you could pull and push one more time hopefully that will take care of it!

I'm also not sure then how the expunge-assist.md change remained in there. I am happy to jump on Slack with you and look at what you've got and your process and see if we can figure out what happened and/or prevent similar hiccups in the future.

**Comment by jleung7158** [comment]
Alright @LRenDO I did another push/pull as late as I could, hopefully it will be good this time!
For availability and ETA for this issue:
i. Availability: Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ii. ETA: 1- 1.5 weeks

**Comment by LRenDO** [comment]
Hi @jleung7158! Thanks for updating again. Unfortunately, it looks like that didn't work. Removing Sam's info manually is probably the fastest way to fix the issue and the easiest to explain.

Please delete the following lines (64-69) and push it back to your fork.
```
 - name: Sam Sengupta
    role: UX/UI Designer
    links:
      slack:
      github:
    picture: https://avatars.githubusercontent.com/u/41702879
```

Again, you can verify only your intended changes have been made by clicking the `Files changed` tab on this pull request.  Thanks!

**Comment by JanineSooThow** [comment]
availability: Sunday, Monday, Tuesday NZ time
ETA: By Tuesday 18th november NZT

**Comment by JanineSooThow** [comment]
Hello @jleung7158 thank you for taking up this issue! From my review, I can see the PR was correctly done with the correct branch and you have successfully removed Yujin's information as requested in the issue. Code after removal of Yujin's information looks clean and tidy. Well done! Good job on showing the before and after changes visually. I will wait until you delete lines 64-69 as requested by @LRenDO and then I will review it again so I can approve your PR.

**Comment by jleung7158** [comment]
I have removed the info manually as suggested! Ready for review @LRenDO @JanineSooThow 
i. Availability: (PST) Monday-Tuesday after 2PM, Wednesday-Friday after 7PM
ii. ETA: 1- 1.5 weeks

**Review by LRenDO — APPROVED** [review]
@jleung7158, thanks for making the updates! Looks like it's all set on my end!

**Comment by JanineSooThow** [comment]
Hello @jleung7158 thank you for the changes! Just had a check and it looks all good! :D Awesome job! Will approve this PR

**Review by JanineSooThow — APPROVED** [review]

**Pull request merged**
