### PR TITLE
leadership info change

### LINKED ISSUE #4566: Update Project Profile: Access the Data
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Access the Data project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/access-the-data.md` file and find the `leadership` variable.
- [x] Remove the following members
  - [x] Lucy Chang
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Cathy Cai
GitHub Handle: @Cathyyyyyyyy
Role: Product Manager
Slack Member ID: U04TUV2FQCU
  - [x] Name: Aparna Gopal
GitHub Handle: @Aparna1Gopal
Role: UX Researcher
Slack Member ID: U0245UJP868
  - [x] Name: Deepa Mohan
GitHub Handle: @deepamohan22
Role: UX Designer
Slack Member ID: U033H9HT0P2
  - [x] Name: Leslie Luk
GitHub Handle: @lesUXW
Role: UX Writer
Slack Member ID: U04960088CV
  - [x] Name: Tony Delgado
GitHub Handle: @TonyDelgadoWillis
Role: Developer
Slack Member ID: U05422GPUQ2
- [x] Make the following changes
  - [x] Change Judson Lester's role from "Developer Lead" to "Developer"
- [x] Verify the changes by viewing the [Access the Data project page](https://www.hackforla.org/projects/access-the-data) on your local environment and include a screenshot with your pull request

### Resources
- [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by bphan002**
Fixes  #4566

### What changes did you make and why did you make them ?

  - Removed old leadership team
  - Updated list with new members

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-04-30 at 5 42 41 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2023-05-01 at 9 10 41 PM

</details>

### CODE REVIEW

**Comment by drakenguyen4000** [comment]
ETA: 5/1/23
Availability: M-F 6pm-8pm

**Review by drakenguyen4000 — CHANGES_REQUESTED** [review]
Hi @bphan002, it looks like your code is missing the github picture link.  All you need to do is copy and add their github handle to the end and their picture should display.  

image

**Review by bphan002 — COMMENTED** [review]
Thanks Drake.  That did the trick. Let me know if anything else needs to be changed.

**Comment by steven-positive-tran** [comment]
ETA: 5/1/23
Availability: M-F 10pm-12pm

**Review by steven-positive-tran — APPROVED** [review]

**Review by drakenguyen4000 — APPROVED** [review]
Great job @bphan002, the code met all action items required.  Everything is displaying properly in Docker.  

Also, please fix the your issue tag.  For some reason it's not linking and displaying the issue in the development area.  

It should look like this.  I'm not sure why your Fixes is hyperlinked. 
image

image

**Comment by bphan002** [comment]
@drakenguyen4000 thanks Drake.  Fixes has been unhyperlinked

**Pull request merged**
