### PR TITLE
Add title1 class to h1 header in wins hero file

### LINKED ISSUE #2082: Apply design system heading classes to Wins page
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Wins page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading class “.title1” to the [Wins page](https://www.hackforla.org/wins/) header’s heading text (“Let’s celebrate together!“)
- [x] Make sure the heading still looks the same as it did before in mobile and desktop, and that nothing gets messed up due to these changes
### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Guide to working on a feature branch (wins-feature-1)](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
Screen Shot 2021-08-08 at 1 11 22 AM

### PR DESCRIPTION
**Pull request by adrian-zaragoza**
Fixes #2082

### What changes did you make and why did you make them ?

  - Added title1 class to the h1 tag in the wins hero file.
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Aveline-art** [comment]
@adrian-zaragoza It looks like you might have been accidentally assigned multiple second issues. If you have been assigned more than one, please be sure to unassign yourself so that one issue is assigned to you at all times and to not have another one assigned until your related PR has been merged.

**Comment by adrian-zaragoza** [comment]
@Aveline-art Woops I forgot to check if my last issue was merged yet. I'll make sure to do that going forward.

**Review by blakes24 — DISMISSED** [review]
Nice job. The header looked good when I ran it on my computer.

**Comment by macho-catt** [comment]
Hi @adrian-zaragoza. This looks good, and would be ready for merge; however, the issue missed the important detail that this was supposed to be worked on the wins-feature-1 branch. I apologize for this, but could you close this PR and create a new PR on the wins-feature-1 branch?
Here are the instructions for working on a feature branch: https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
All you have to do is create a new branch based off the feature branch, copy your code from here to that new branch, then open a new PR. Let me know if you need help on this, and I can assist you on slack / via zoom.
Thank you.

**Comment by adrian-zaragoza** [comment]
Per the suggestions, I'm closing this PR and creating new branch off of the wins-feature-1 branch and opening a new PR. Apologies for the mess this has caused.

**Comment by adam-abundis** [comment]
@adrian-zaragoza No worries. It's our fault for not catching this. Your doing great. Keep up the good work!

**Pull request closed without merging**
