### PR TITLE
Team meetings time zone

### LINKED ISSUE #690: Team Meetings Page Time Zone Update
### Overview
We need to display the time and time zone in a format that is understandable to the user so that they can easily understand what time a team meeting occurs and if that time suits their schedule. 

### Action Items

Development 
- [x] Identify & resolve the bug causing midnight (or 12:00 am) to show as 0:00 am (screenshot below)
- [x] Add in the time zone next to the time (be sure this is responsive to where the user's browser is reflecting)

### Resources/Instructions
[Project Team Meetings page](https://www.hackforla.org/project-meetings)

Screen Shot 2020-08-18 at 1 27 44 PM

### PR DESCRIPTION
**Pull request by drubgrubby**
FIxes #690 

1) Text showing the user's time zone has been added above the calendar listings.
2) The bug that showed midnight at 0:00 has been fixed. 

We discussed last Sunday adding the time zone to the top of the page, rather than adding PDT (or whatever) to each time.  Because there was not specific language for this in the issue, please confirm that the language I wrote is what we want to use. 

Screen Shot 2020-09-11 at 1 02 32 AM

### CODE REVIEW

**Comment by drubgrubby** [comment]
While not sleeping last night it occurred to me that there should be a default response in case, for some reason, the browser couldn't detect the time zone. (My assumption is that it's still displaying the correct time zone, but the code I used to determine the time zone can't tell what the time zone is, which as I understand it can happen with old browsers.)

I added that and pushed the changes. 

Here's the default language:
Screen Shot 2020-09-11 at 5 11 26 AM

**Review by ExperimentsInHonesty — COMMENTED** [review]
It looks good to me visually.   I will wait for a technical review from Ruben or others.

**Comment by ruben1s** [comment]
screencapture-0-0-0-0-4000-project-meetings-2020-09-12-16_45_32
screencapture-0-0-0-0-4000-project-meetings-2020-09-12-16_45_32 (1)

**Comment by ruben1s** [comment]
They seem to be working:
screencapture-0-0-0-0-4000-project-meetings-2020-09-12-16_46_04
screencapture-0-0-0-0-4000-project-meetings-2020-09-12-16_45_32 (1)

**Review by ruben1s — COMMENTED** [review]
Code looks good and you even left good comments. This branch is ready to merge.

**Comment by alexandrastubbs** [comment]
@drubgrubby Can we add a space between the time zone note and 'Monday'?

**Comment by drubgrubby** [comment]
@alexandrastubbs - There was previously 10px bottom margin between the time zone and "Monday".  It looked okay on my machine (you can see that at the top of the PR), but I agree that on the screen shots from Ruben it looks too close.  I've added 10px of margin (20px now).  Let me know if that looks okay. 

Screen Shot 2020-09-17 at 7 56 20 PM

**Comment by alexandrastubbs** [comment]
@drubgrubby this looks better! All good on my end. Thank you.

**Review by ExperimentsInHonesty — APPROVED** [review]

**Pull request merged**
