### PR TITLE
Update Github Actions for Issue Creators not on the Website-Write Team

### LINKED ISSUE #3111: Update GitHub actions for issue creators not part of website-write team
### Overview
We need to make sure that the GHA that adds a reminder to all new issues about adding missing labels is only activated by people who have write access to the repo, so that people don't get a reminder message that they can't comply with. 

Example:  product mangers from other hack for LA teams open issues to ask for updates to their project card.  But they don't have write access to our repo.

### Action Items
- [x] Review [add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues) workflow and [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) file.
- [x] Notice in the following comments: [comment1](https://github.com/hackforla/website/issues/2758#issuecomment-1033403336), [comment2](https://github.com/hackforla/website/issues/2758#issuecomment-1034008129); users who are not part of website-write team are prompted to add labels to the issue even though they can't.
- [x] Make code changes in your repo such that no bot comment related to missing labels such as [comment1](https://github.com/hackforla/website/issues/2758#issuecomment-1033403336) gets posted on the issue for issue creators who are not part of website-write team
- [x] Test if it works in your own repo first.
- [x] Create a PR for the changes to be merged.

### Checks
- [x] For testing in your own repo (after making the necessary code changes)
    - [x] Create a project board in your own repo
    - [x] Create a new issue (using a dummy profile not part of website-write team) and add it to one of the newly created columns (do not add labels to your issue so that [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file gets triggered)
    - [x] Make sure nothing gets posted on your issue
- [x] Make sure all the functionalities in [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file still work fine

### Resources/Instructions
[Add-missing-labels-to-issues](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues) workflow 
[Issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) file
[Add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes
Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by Zak234**
Fixes #3111 

### What changes did you make and why did you make them ?

  -Edited issue-trigger.yml to check which teams the user is a part of in HackforLA and then to check if one of those teams is the website-write team. If they are on the website write team, then the comment is posted. If not then the comment is not posted.

### Comments

  -Requires a action repository secret of a Github access token with read:org and read:user permissions and the name TEAMS.

### CODE REVIEW

**Comment by blulady** [comment]
Availability: 2 hours
ETA: 6/26/22

**Comment by blulady** [comment]
Ok so far I have pulled Zak's branch into my local repo and then pushed it to my github repository.
I didn't merge it into my gh-pages, hoping I could test it from the branch. This is the results from trying to do it from that branch
So testing it in my repo on the zak branch
<details>
    <summary>Step 2: Create a new issue</summary>

Was able to leave an issue with the dummy account, github left a comment and sent and email in response  
Screenshot (182)
</details>

<details>
 <summary>Add issue to  newly created columns </summary>
Dummy account has no access to items in the columns
Screenshot (180)


Dummy account has no access to columns
Screenshot (181)
</details>


<details>
 <summary>Made an issue with my account, github response matched the dummies</summary>

Made an issue with my account, github response matched the dummies
Screenshot (183)


</details> 

<details>
 <summary>was unable to add the issue to the column board</summary>


Screenshot (184)


</details> 

Is the problem that I am unable to add the issue to the project columns or do I need to make the changes in gh-pages and not the feature branch I pushed up.

**Comment by Zak234** [comment]
There may be several issues. First, I made the changes in the update-add-missing-labels branch not the gh-pages branch. It could also be that the secret which has the github access token was not generated when you pulled the branch. It should be in settings and called TEAMS. I'm not going to be available for the next five days but if there are any other issues, please let me know.

**Comment by blulady** [comment]
> There may be several issues. First, I made the changes in the update-add-missing-labels branch not the gh-pages branch. It could also be that the secret which has the github access token was not generated when you pulled the branch. It should be in settings and called TEAMS. I'm not going to be available for the next five days but if there are any other issues, please let me know.

Ok so now I have merged your branch into my gh-pages and pushed it. Then I created a TEAMS token and put it in my repository secrets. Good news and bad. Good news is I am not getting notifications for the dummy account. Not getting an email either. Bad news is, I am not getting it for my account either. 


<details>
 <summary>Here I have a picture of a comment I left with the dummy account and my account to demonstrating how it's not working for either</summary>

Screenshot (193)

</details>

**Review by blulady — CHANGES_REQUESTED** [review]
The good news is that there is no notification for the dummy account. The bad news is that there is no notification for my regular account either. So we aren't quite there yet.

**Comment by blulady** [comment]
Ok so update. I did get an email for my real account and you can see in the picture a small comment by github actions after the issue is created but neither gets a big comment like we were getting prior to the changes.

**Comment by Zak234** [comment]
That's weird. Can you try adding an issue on my branch to see if its a problem with the code?
https://github.com/Zak234/website.git

**Comment by blulady** [comment]
> That's weird. Can you try adding an issue on my branch to see if its a problem with the code? https://github.com/Zak234/website.git

Ok. It looks different in your repo then mine.

**Comment by blulady** [comment]
update on update. My dummy account got an email too. Womp Womp.

**Comment by blulady** [comment]
> > That's weird. Can you try adding an issue on my branch to see if its a problem with the code? https://github.com/Zak234/website.git
> 
> I left an issue in your repo. Which I shouldn't be able to do, because I am not a contributor but I will try from my dummy account as well

<details>
<summary> Yet another picture, not my repo but Zaks </summary>

Screenshot (195)

</details>

**Comment by Zak234** [comment]
It seems like it worked. The issue by blu-lady got a comment and the one from s-sanger didn't.

**Comment by blulady** [comment]
> It seems like it worked. The issue by blu-lady got a comment and the one from s-sanger didn't.

Yeah, but we need clear instructions on how to make it work in another repository before we merge it. So I will ask on Sunday.

**Comment by Zak234** [comment]
Alright

**Review by blulady — APPROVED** [review]
Sakari walked me through adding the token with the correct permissions and it worked. Good Job!!

**Pull request merged**
