### PR TITLE
removed one entry #5393

### LINKED ISSUE #5393: Update Project Profile: LA TDM Calculator (remove Moji Momoh)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The LA TDM Calculator project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/tdm-calculator.md` file and find the `leadership` variable.
 - [x] **_Remove_** the entry:
```
  - name: Moji Momoh
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/D04HDM7DM18'
      github: 'https://github.com/mojimoh'
    picture: https://avatars.githubusercontent.com/mojimoh
```
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the LA TDM Calculator project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [LA TDM Calculator](https://www.hackforla.org/projects/tdm-calculator) project page
  - [tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)  
  - This issue was initiated by #5381

### PR DESCRIPTION
**Pull request by kiran98118**
Fixes #5393

### What changes did you make?
  - Removed one of the entry as mentioned in the description

### CODE REVIEW

**Comment by antho-zng** [comment]
Availability: 9–5pm ET
ETA: Sept 8, by 5pm ET

**Review by antho-zng — CHANGES_REQUESTED** [review]
Hi @kiran98118! The changes look good to me. I think for the purpose of documentation, we'd want more details on: 
- The specific changes made (e.g. specifying which entry was removed from where) 
- Why these changes were made
- Visuals of the before/after on the page via screenshots

Going off the contributing guide, it'd probably also help our teammates track your changes too if you added the same details on changes made in your commit message as well! 

Thanks for submitting the pull request! Happy to add my approval after you've had a chance to add details on the request comment.

**Comment by t-will-gillis** [comment]
Hello @kiran98118 It appears that the last reviewer requested changes two weeks ago. Could you please give us an update on your progress on addressing the requested changes on this PR? Thank you.

**Comment by t-will-gillis** [comment]
Dev unassigned themselves from the PR and the issue.

**Pull request closed without merging**
