### PR TITLE
Edit content field and remove type 2846

### LINKED ISSUE #2846: Edit content field and remove type field from locations.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/locations.yml`, do the following:
- [ ] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [ ] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/locations.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/locations.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/locations.yml#L11

### PR DESCRIPTION
**Pull request by gstemmann**
Fixes #2846

### What changes did you make and why did you make them ?

  - Changed content field key: value pair in _data/internal/credits/locations.yml
  - Removed type field from _data/internal/credits/locations.yml
Changes were made to reduce redundancy

### Screenshots of Proposed Changes Of The Website  
No visual changes to the website or photos to attach

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: 4PM 10/13/22
Availability: 6 hours

**Review by MattPereira — APPROVED** [review]
Phenomenal work George! I love how you improved the code by removing redundancy. 😎

**Comment by jyaymie** [comment]
Review ETA: 5pm PST 10/13/22
Availability: 1 hour

**Comment by jyaymie** [comment]
Great work! I see all the changes that needed to be made. I did notice that in your PR, the listed file path is different from that in the issue. I believe the end of the path should be `locations.yml` instead of `meetup.yml`.

**Review by jyaymie — APPROVED** [review]

**Comment by gstemmann** [comment]
> Great work! I see all the changes that needed to be made. I did notice that in your PR, the listed file path is different from that in the issue. I believe the end of the path should be `locations.yml` instead of `meetup.yml`.

Thank you so much for catching this! I will change this now.

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing line four to `content-type: image` and deleting line 11. The code looks clean and there is only one file changed (even though there are multiple commits).
Good job!!

**Pull request merged**
