### PR TITLE
Added Program area to Green Earth OS

### LINKED ISSUE #2271: Add Program Area: Green Earth OS
### Overview
We need to add program area information to the Green Earth OS project so that it will show up when we add the program areas filter.

### Action Items
- [ ] Review the project.md file model in the Resources section
- [ ] Add the following text to the file indicated in the Resources section
- [ ] See visual changes on the [Projects page's](https://www.hackforla.org/projects/) Green Earth OS card.
  <details>
    <summary>Here is where you will see changes:</summary>
    Green-Earth-OS
  </details>
```
program-area:  
    - Environment
```

### Resources/Instructions
- File location to make the change: _projects/green-earth-os.md

- URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md

- [Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

- Link to [Projects page](https://www.hackforla.org/projects/)

### PR DESCRIPTION
**Pull request by jnmrles**
Fixes #2271 

### What changes did you make and why did you make them ?

  - added program area to green-earth-os.md

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
Review ETA: Thursday, December 30, 2021

**Comment by JessicaLucindaCheng** [comment]
@jnmrles 
- On the right, under Projects , please add your pull request to the Project Board.

- Also, please add the following section in your original post/comment and edit it with your before and after changes are applied images:

``` 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<!-- Note, if your images are too big, use the <img src="" width="" length="" />  syntax instead of ![image](link) to format the images -->
<!-- If images are not loading properly, you might need to double check the syntax or add a newline after the closing </summary> tag -->

<details>
  <summary>Visuals before changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  ![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>
```

See [Complete pull request (4): Include images (if available)](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available) in CONTRIBUTING.md for more details.

**Comment by anthonysim** [comment]
Review ETA: Thursday, Jan 1, 2022

**Review by anthonysim — COMMENTED** [review]
@jnmrles, LGTM! But waiting for the requests from @JessicaLucindaCheng to be made before I give an approval. Good job!

**Comment by lopezpedres** [comment]
Review ETA: Jan 7, 2022

**Review by lopezpedres — CHANGES_REQUESTED** [review]
Great job! @jnmrles thanks for pointing out the missing part in the PR comment @JessicaLucindaCheng. Looks ready to be merged once the corrections are done :)

**Comment by JessicaLucindaCheng** [comment]
> @jnmrles
> 
> * On the right, under Projects , please add your pull request to the Project Board.
> * Also, please add the following section in your original post/comment and edit it with your before and after changes are applied images:
> 
> ```
> ### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
> 
> 
> 
> <details>
>   <summary>Visuals before changes are applied</summary>
> 
>   image
> 
> </details>
> 
> <details>
>   <summary>Visuals after changes are applied</summary>
> 
>   image
> 
> </details>
> ```
> 
> See [Complete pull request (4): Include images (if available)](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available) in CONTRIBUTING.md for more details.

@jnmrles Just following up to see if you had questions or need help with making the above requested changes.

The visual changes will be on the [Projects page's](https://www.hackforla.org/projects/) Green Earth OS card.

<details>
  <summary>Here is where you will see changes:</summary>
  Green-Earth-OS
</details>

**Comment by JessicaLucindaCheng** [comment]
@jnmrles Are you still interested in working on this issue? If yes, please let me know by Monday, January 31, 2022. If I do not hear back from you by that date, I will close this pull request and unassign you from this issue.

**Comment by anthonysim** [comment]
I removed myself as reviewer since this is still in-progress.

**Comment by JessicaLucindaCheng** [comment]
Closing this pr because I have not heard back from Jovanni.

**Pull request closed without merging**
