### PR TITLE
Removed Michael and added Ryan & Anna to 311 data team on UI

### LINKED ISSUE #5860: Update Project Profile: 311 Data (Remove Michael Criste, Add Ryan Chase & Anna Kim)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Michael Criste
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U048U430FQV'
      github: 'https://github.com/mc759'
    picture: https://avatars.githubusercontent.com/mc759
```
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Ryan Chase
    github-handle: ryanfchase
    role: Project Manager, Developer
    links:
      slack: https://hackforla.slack.com/team/U052L9R6ETD
      github: https://github.com/ryanfchase
    picture: https://avatars.githubusercontent.com/ryanfchase
```
- [x] If there are other Project Managers, place Ryan Chase's profile after the other Project Managers' profiles
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Anna Kim
    github-handle: annaseulgi
    role: UX Design Lead, Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05JKGV3F4N
      github: https://github.com/annaseulgi
    picture: https://avatars.githubusercontent.com/annaseulgi
```
- [x] If there are other Product Managers, place Anna Kim's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
- [x] Once your pull request is merged, go to #5786 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #5786 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #5786
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data

### PR DESCRIPTION
**Pull request by irais-valenzuela**
Fixes #5860 

### What changes did you make?
  - Removed Michael Criste from the 311 Data UI page.
  - Added Ryan Chase to the 311 Data UI page.
  - Added Anna Kim to the 311 Data UI page.

### Why did you make the changes (we will use this info to test)?
  - To keep 311 Data UI Page up to date with new leadership.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
mage_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
_Image_Link_Here_After_Attaching_Files)

</details>

### CODE REVIEW

**Comment by Anahisv23** [comment]
Review ETA: 4PM 11/16
Availability: 1-6 PM 11/16

**Review by Anahisv23 — DISMISSED** [review]
Nice work Irais! Keep it up!

**Review by KyleA99 — DISMISSED** [review]
- Your PR is done with the correct branch.
- Your code is correctly changed.
- Changes look great in the browser.

Reviewed and approved!

Great work @irais-valenzuela

**Comment by t-will-gillis** [comment]
Hi @irais-valenzuela! 
FYI There have been some changes to the 311-data.md page since you worked on it, and so there is a merge conflict to fix. 
Thanks!

Also, please send me a Slack message afterwards...

**Review by t-will-gillis — APPROVED** [review]
Hey @irais-valenzuela - Thank you for addressing the merge conflict and picking up the name change!

**Pull request merged**
