### PR TITLE
Update Project Profile: Remove Ronald Paek from HfLA Website #6257

### LINKED ISSUE #6257: Update Project Profile: remove Ronald Paek from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Ronald Paek
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U04RS2BCESX'
      github: 'https://github.com/ronaldpaek'
    picture: https://avatars.githubusercontent.com/ronaldpaek
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by MarcosG119**
Fixes #6257

### What changes did you make?

 - Removed Ronald Paek's card from the leadership section in _projects/website.md. 

### Why did you make the changes (we will use this info to test)?

 - To update the project profiles and remove Ronald Paek's card.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-02-27 at 2 57 50 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-02-27 at 2 59 15 PM

</details>

### CODE REVIEW

**Comment by danvgar** [comment]
Thanks, @drakenguyen4000 . I will jump on this review by tomorrow (EOD Wed Feb 28).

**Comment by ramitaarora** [comment]
Review ETA: EoD Feb 28
Availability: 9am-12pm Weekdays

**Review by ramitaarora — APPROVED** [review]
This looks good! The user was removed from the code and resulting changes showed on the website.

**Review by danvgar — APPROVED** [review]
Fixes Issue #6257 

Branch is correct. Code looks good and in Docker. Visual changes look clean.

Great work, @MarcosG119  !!

**Pull request merged**
