### PR TITLE
Removed ending slash from img tag

### LINKED ISSUE #4448: img Tag Refactor: Citizen Engagement page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/program-area-pages-cards.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="card-image" src="{{ item.image }}" alt=""/>
```
to
```
<img class="card-image" src="{{ item.image }}" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/program-area-pages-cards.html
2. Webpage: https://www.hackforla.org/citizen-engagement
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by pdimaano**
Fixes #4448

### What changes did you make and why did you make them ?

  - Removed ending slash from img tag to keep syntax consistent throughout codebase

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by vanessavun** [comment]
Availability: weekday evenings
ETA: 04/14/2023

**Review by vanessavun — CHANGES_REQUESTED** [review]
Strange. Based on #4448 it asks specifically for 
``
to be changed to
``

but the file you have looks different with it as
`{{ item.card-image-alt }}`

To double check, can you ensure that you updated the gh-pages branch?

I hope a second reviewer can check this as well.

**Comment by cmedina-dev** [comment]
Availability - All day today
ETA - 4/15/2023

**Review by cmedina-dev — CHANGES_REQUESTED** [review]
Hi @pdimaano! Looks like your PR has a merge conflict that you'll need to resolve before the PR can be merged. You did modify the correct line, but if you take a look here, that same line was updated: https://github.com/hackforla/website/blob/gh-pages/_includes/program-area-pages-cards.html 

My only other suggestion is making sure your PR is added to the project board on the right-hand side of your PR. You can add it really easily by just clicking the little cog wheel and selecting the HfLA Project Board option.

Everything else looks good! You linked the proper issue, created the PR from your feature branch, and explained why the change was made. Good work!

**Review by vanessavun — APPROVED** [review]
Thanks for fixing the merge issue. Now the changes you made in _includes/program-area-pages-cards.html reflects the changes needed mentioned in the issue you're working on.

This looks good, and you linked the proper issue, updated the PR from your feature branch, and explained why the change was made. Thanks!

**Review by cmedina-dev — APPROVED** [review]
Looks good to me, good job fixing the merge conflict! 👍

**Pull request merged**
