### PR TITLE
Updated alt text on Donate page images to adhere to WCAG

### LINKED ISSUE #2886: Update Donate page images' alt text to adhere to WCAG
### Overview
As a developer, we need to provide clear and descriptive alt text on the Donate web page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity. For this issue, we will change the alt texts on the Donate web page to adhere to WCAG.

### Action Items
The following alt text changes are for the [Donate web page](https://www.hackforla.org/donate/)
- [x] Change the image's alt property value within [donate.html](https://github.com/hackforla/website/blob/557ff50b2f426a7c481a22ac5ce5dd72020f6c10/pages/donate.html) for the following lines of code only:
  - [x] The following alt text is on the `Header-container Header-container--donate` area on the web page
    - [x] On line 18, change the `alt="donate banner icon"` text  to `alt=""`
  - [x] The following alt text is on the `Content-section Donate-card-container` area on the web page
    - [x] On line 24, change the `alt="donate card image"` text  to `alt=""`
    - [x] On line 34, change the `alt="donation chart"` text  to `alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"`
    - [x] On line 45, change the `alt="donation form image"` text  to `alt="Gif showing how to select Hack for LA from donation list"`
    - [ ] Review with product referencing the parent issue https://github.com/hackforla/website/issues/2568 

- [x] Check that the Donate web page looks the same
- [x] Check that the new alt texts got incorporated after the change by inspecting the web page using developer tools

#### File and Code links you will need to review this issue
- Link to web page: https://www.hackforla.org/donate/

- Directory to find the source file code once you have it in your IDE: `pages/donate.html`

- Click on this link to see the source file code: https://github.com/hackforla/website/blob/557ff50b2f426a7c481a22ac5ce5dd72020f6c10/pages/donate.html

- Related design issue: https://github.com/hackforla/website/issues/2568

- Link to the tab on Google Sheets: https://docs.google.com/spreadsheets/d/1abMlPOX88zHTV29E4BFxAYwahCxgJN28Mn95cXr8jak/edit#gid=14599403

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #2886

### What changes did you make and why did you make them ?

  -Updated alt text on Donate page images' to adhere to WCAG and to be more inclusive.  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  -No visual changes

### CODE REVIEW

**Comment by luke-karis** [comment]
Review ETA: 9 PM 3/14/22
Availability: 7-9 PM Monday

**Review by luke-karis — APPROVED** [review]
@Jaretzbalba Great job making this change! Everything here looks good to me.

**Comment by usaboo** [comment]
Review ETA: 11 AM 3/16/22
Availability: 9 - 11AM EST Wednesday

**Review by usaboo — APPROVED** [review]
Everything looks good to me too! Good job :)

PS - Sorry for the delay.

**Pull request merged**
