### PR TITLE
add github-handle variable for Gian Reyes Dionisio

### LINKED ISSUE #6937: Add github-handle for Gian Reyes Dionisio in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] #6977
- [x] #6978
```
- name: Gian Reyes Dionisio
```
with
```
- name: Gian Reyes Dionisio
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by williamzhang73**
Fixes #6937 

### What changes did you make?
  -add `github-handle:` for Gian Reyes Dionisio

### Why did you make the changes (we will use this info to test)?
  -add Github handle variable for Gian Reyes Dinnisio to reduce redundancy in the project file.
 
### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)

  -No visual change on the website.

### CODE REVIEW

**Comment by dcotelessa** [comment]
Hi williamzhang,

Thanks for the PR. We need a few updates:
- In the PR description, we need to replace "Fixes #replace_this_text_with_the_issue_number" with the number of the ticket, linking  the task to the ticket. This is described [here](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md#31-how-to-make-a-pull-request)
- Also, we can remove the "Screenshots" portion of the PR description as there are no visual changes.
- The github-handle is applied and left blank , as the task is described.

Look forward to the update, thanks!

**Comment by williamzhang73** [comment]
Thanks @dcotelessa, 
1. The issue number was updated.
2. The "screenshots" part of the PR description was removed.
please review it again.

**Review by dcotelessa — APPROVED** [review]
Thanks for the updates.
The description looks good and the passing all tests.
Great job!

**Comment by andyphancode** [comment]
Review ETA: 6/11/2024 EOD 
Availability: Throughout week

**Review by andyphancode — APPROVED** [review]
Looks good!

- Correctly merging from collaborator's branch into hackforla:gh-pages
- Issue is correctly fixed (github-handle: added)

Approved.

**Review by ino-iosdev — DISMISSED** [review]
@williamzhang73 

- Issue number was properly linked
- Branch naming is good (just a side note for future reference, no need to make change on this one: branch naming is more clear if you could include the name of the person, e.g. `add-github-handle-for-bryon-heart-6730`)

### Changes required:

1. Remove `6937` from the title (notice how it becomes unclear since it stacks with your PR number)

2. Use syntax highlight when referencing changes made so that it's clear to read, e.g. below:

Screenshot 2024-06-11 at 6 57 44 PM

3. Revise the `Why did you make the changes` answer: In general, it's a good practice to write details in your own words based on the request from the issue, e.g. #6917

4. Please include this at the end if no visual change is made to the website:

```
Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)

-  No visual change on the website. 

```
After making all these changes, don't forget to click on something like this on the top right of your page (see below) to request a review of your changes:

Screenshot 2024-06-06 at 8 45 27 PM

**Comment by ino-iosdev** [comment]
> Looks good!
> 
> 
> 
> - Correctly merging from collaborator's branch into hackforla:gh-pages
> 
> - Issue is correctly fixed (github-handle: added)
> 
> 
> 
> Approved.

@andyphancode Just noticed that your view mentioned `merging`, since this is a `pushing` only, and the merge team will be handling merging once it's approved overall, I would kindly suggest to say `correctly pushing` instead to avoid confusing. Hope this make sense, cheers!

**Comment by del9ra** [comment]
ETA: 06/13/24
Availability: 1-5 PM monday-friday

**Review by del9ra — CHANGES_REQUESTED** [review]
HI @williamzhang73 Well done! Good job!
* The branching was done correctly
* No need to mention issue number in the PR title. Refer to this guide https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md 
* Issue number was listed
* Not all pull requests will have significant changes to our website. Please just add the following explanation for no images like:
		### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
		No visual changes to the website.
	Please refer to the Contributing Guide: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md 
* Changes were made correctly in the code
* Please provide a more detailed explanation of why the changes are being made
Thank you! Just make these changes, and I'll be happy to approve it.

**Review by del9ra — APPROVED** [review]

**Comment by jphamtv** [comment]
Hi @williamzhang73 - Please update the "What changes did you make?" summary according to @ino-iosdev's feedback: 

>2. Use syntax highlight when referencing changes made so that it's clear to read, e.g. below:

Screenshot 2024-06-11 at 6 57 44 PM


Tip: Remove the underscores (_), and use backticks (`) instead 

Once updated, ping @ino-iosdev to review and approve the changes. This PR is ready to be merged and is only waiting for this final update. Thanks!

**Review by ino-iosdev — COMMENTED** [review]
Thank you for the changes!

**Pull request merged**
