### PR TITLE
add github handle for kevin nguyen

### LINKED ISSUE #6725: Add github-handle for Kelvin Nguyen in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Kelvin Nguyen
```
with
```
- name: Kelvin Nguyen
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by curbeammonae**
Fixes #6725 

### What changes did you make?
  - I completed the main task which is to add the github handle for Kevin Nguyen 
 

### Why did you make the changes (we will use this info to test)?
  -To create a single variable to hold the github handle for each member of the leadership team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by curbeammonae** [comment]
Provide Update
Progress - I have completed the task by adding github handle to name Kevun Nguyen
Blockers - no blockers this time!
Availability - 13 hours
ETA - Completed

**Comment by robertnjenga** [comment]
Review ETA:  06/03/2024
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hi @curbeammonae! Thank you for taking up this issue.
- The branching was done correctly, you used correct branch to commit from and into.
- You linked the issue.
- Code changes were made correctly as stated.
- I'm able to confirm in docker that the appearance of the project webpage is unchanged.
Great Job!

**Comment by DeniseLewis1** [comment]
Review ETA: 6/4 end of day
Availability: 11am - 3pm

**Review by DeniseLewis1 — APPROVED** [review]
Hello @curbeammonae, thank you for contribution!

- The correct branch was used for the pull request
- The issue is linked correctly
- Changes were made correctly
- Confirmed no visual changes to the website

Great work!

**Comment by Thinking-Panda** [comment]
@curbeammonae Thank you for working on this issue. Nice work. FYI remember to add the issue number at the end of the name of your issue branch.

**Pull request merged**
