### PR TITLE
Updated redirect_to in codeforamerica.md

### LINKED ISSUE #5968: update "/codeforamerica" redirect to point to Hfla donate page
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to update the redirect so that requests for https://www.hackforla.org/codeforamerica/ are redirected to https://www.hackforla.org/donate

### Action Items
- [x] In your local IDE, navigate to `redirections/codeforamerica.md`
- [x] Replace:
 ```
# https://www.hackforla.org/codeforamerica/ redirects to -> https://www.codeforamerica.org/donate
layout: redirect
title: CodeForAmerica
permalink: /codeforamerica/
redirect_to: https://www.codeforamerica.org/donate
``` 
with
```
# https://www.hackforla.org/codeforamerica/ redirects to -> https://www.hackforla.org/donate
layout: redirect
title: CodeForAmerica
permalink: /codeforamerica/
redirect_to: https://www.hackforla.org/donate
```
- [x] Using Docker, confirm that `/codeforamerica`  redirects to https://www.hackforla.org/donate

### Resources/Instructions
- This issue was created from #5953

### PR DESCRIPTION
**Pull request by Jung-GunSong**
Fixes #5968

### What changes did you make?
  - Changed the value of redirect_to: in codeforamerica.md to https://www.hackforla.org/donate

### Why did you make the changes (we will use this info to test)?
  - To allow redirect of the https://www.hackforla.org/codeforamerica/ url to https://www.hackforla.org/donate

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by heejung-hong — APPROVED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, iPad, and iPhone view), Firefox, and Safari browser.

**Comment by robertnjenga** [comment]
Review ETA:  01/07/2024
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hello @Jung-GunSong! Great job with this pull request.
The branching is done correctly, you linked the original issue, you gave concise descriptions of what you did i.e updated redirect_to in codeforamerica.md, and why the changes were needed, and also provided the screenshots.
I'm able to confirm in Docker that the redirect works correctly. Nice work!

**Comment by t-will-gillis** [comment]
Hey @Jung-GunSong - Great job on your first PR! As an FYI, you can go ahead and remove the empty bullet points in the description for what you did and why. Otherwise, looks great- thanks for your work.

**Comment by Jung-GunSong** [comment]
Good to hear and thanks for the feedback everyone!

**Pull request merged**
