### PR TITLE
Updated Hands Photo to Correct Orientation

### LINKED ISSUE #6296: Replace Team Hands Middle image in Credits page on Feature Homepage Launch branch
### Overview
We need to replace the "Team Hands Middle" graphic on the Credits page, within the feature homepage branch.  The new graphic file should simply replace the existing file, so the filename and references to the image will be unchanged.  

### Action Items
- [x] Work on this issue will be merged into hackforla/feature-homepage-launch.  For information about working on a feature branch, see https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
- [x] Download the "New image" from the Resources section below, then rename it `/team-hands-middle.jpg` and save it in the folder `/assets/images/credits`
- [x] Using Docker, view the Credits page (/credits) and confirm that the appearance of the credit for the "Team Middle Hands" image (text and image) matches the "Current appearance of the Credit for the Team Middle Hands image" screenshot below, except for the rotation of the image

### Resources/Instructions
<details><summary>New Image</summary>

team-hands-middle

</details> 

<details><summary>Current appearance of the Credit for the Team Middle Hands photo</summary>

image

</details> 

Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

### PR DESCRIPTION
**Pull request by evan-ishibashi**
Fixes #6296

### What changes did you make?
  -  Downloaded provided asset and replaced the current one with the newly rotated image.

### Why did you make the changes (we will use this info to test)?
  - Photo should be displayed properly for when the page goes live.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
 

image

</details>

### CODE REVIEW

**Comment by vincendp** [comment]
Availability: 3/22/24
ETA: End of 3/22/24

**Comment by angela-lee1** [comment]
Availability: 3/22 3/23
ETA: End of 3/23

**Comment by vincendp** [comment]
Hi Evan - Nice work with this PR! Your PR properly links the issue and includes good descriptions for the what and why for the changes. You successfully saved the .jpg in the correct place. I tested on different viewport sizes and everything looks OK.

Just a minor thing for next time, be sure to include the issue number on your branch name!

Aside: (maybe @awlFCCamp can chime in)

On my end, /credits, looks like this:

Screen Shot 2024-03-22 at 6 52 50 PM

The middle hands photo for Team Middle Hands looks good! However, there is a discrepancy between my page and Evan's screenshots. Not sure if I'm supposed to point this out or if it's just a mistake on my end (my first review for HFLA).

**Comment by angela-lee1** [comment]
Hi,  @evan-ishibashi Awesome job! Your PR links to the correct issue. You clearly described the changes and stated the reason for making them. You provided before and after screenshots. I agree that you should include your issue number on the branch name. Thank you!
@vincendp I attached the screenshot on my local
Screenshot 2024-03-22 at 10 17 05 PM

**Comment by vincendp** [comment]
@awlFCCamp Thanks for the attached screenshot.

I don't understand why our local /credits look different. When I go to the tip of the branch `feature-homepage-launch` at commit `92758d23401bd27b6c0d9825aae77001c4a5453f`, looks different compared to the screenshots posted. Maybe mergers can help here

**Comment by awlFCCamp** [comment]
@vincendp I noticed the minor difference. I am mainly unsure about the branch name. Could anyone on the merge team advise?

**Review by angela-lee1 — DISMISSED** [review]

**Comment by angela-lee1** [comment]
Hi @vincendp at website directory, git branch, do you see both gh-pages and feature-homepage-launch?

**Comment by vincendp** [comment]
@awlFCCamp In terms of viewing the changes, I do 

``
git fetch --all
``

``
git checkout -b evan-ishibashi-update-hands-photo upstream/feature-homepage-launch
``

``
git pull https://github.com/evan-ishibashi/website.git update-hands-photo
``

I've also tried directly cloning the fork and going to `update-hands-photo`

**Comment by angela-lee1** [comment]
@vincendp Thank you. I just used the instructions here and started the docker. 

```
git checkout -b evan-ishibashi-update-hands-photo feature-homepage-launch
git pull https://github.com/evan-ishibashi/website.git update-hands-photo
```

**Comment by vincendp** [comment]
@awlFCCamp Thanks for helping me out with this. I was wondering if you could run the commands and screenshot for me
```
git checkout evan-ishibashi-update-hands-photo
git log --graph
```

**Comment by evan-ishibashi** [comment]
Great thanks, updated the branch name to include the issue #

**Comment by evan-ishibashi** [comment]
Also, it looks like updating the branch name deleted the old one, thus closing out this PR. Here's the link to the new one @vincendp @awlFCCamp 
https://github.com/hackforla/website/pull/6522

**Pull request closed without merging**
