### PR TITLE
Add github-handle: to Isaiah Ozadhe

### LINKED ISSUE #6179: Add github-handle for Isaiah Ozadhe in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/[PROJECT FILE]` in the IDE
- [x] Replace:
```
- name:  Isaiah Ozadhe
```
with
```
- name: Isaiah Ozadhe
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by DrAcula27**
Fixes #6179

### What changes did you make?
  - Replaced: 
     `name:  Isaiah Ozadhe`
  - With: 
     `name:  Isaiah Ozadhe`
      `github-handle:`
  - Did not use the tab key to indent github-handle, but used spaces, as YAML does not accept tabs.
  - Using docker, confirmed that the appearance of the project webpage is unchanged at all screen sizes.

### Why did you make the changes (we will use this info to test)?
  - To create a single variable `github-handle` to hold the GitHub handle for each member of the leadership team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

Update to a markdown file. No visual changes to the website.

### CODE REVIEW

**Review by partapparam — APPROVED** [review]
@DrAcula27 good job!
- Correctly added `github-handle`
- Did not use the tab key to indent, but used spaces, as YAML does not accept tabs.
- Appearance is unchanged.

**Comment by elisetvy** [comment]
Review ETA: EOD 4/17
Availability: working on it right now!

**Review by elisetvy — CHANGES_REQUESTED** [review]
Hi @DrAcula27, thank you for submitting this pull request!

You did great on: 

1. Choosing the correct branch for pull request
2. Linking the issue
3. Creating a single variable "github-handle"
4. Using spaces instead of a tab to indent
5. Making no changes to the project webpage appearance

However, I did find an issue with your request:

* Unnecessary changes at lines 22, 41, 48, 62, 69, 83, and 150 for file civic-tech-index.md

[Review guideline](https://github.com/hackforla/website/wiki/How-to-review-pull-requests#step-4-take-a-look-at-the-source-code) requires changes to be applicable and clean, and unfortunately this does not seem to be met.

Please revert the changes at lines 22, 41, 48, 62, 69, 83, and 150 (please ensure there is a space after each colon including the one after the newly created github-handle variable - I also had this issue caused by my text editor making unnecessary formatting changes on save) in the file civic-tech-index.md to their original state. Once you've made these adjustments, please push the updated changes to your branch, and I will be happy to review it again.

Thank you for your efforts and cooperation in keeping our project's changes clean and efficient!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @DrAcula27 As the other reviewers noted, the bulk of this PR looks good. However, please see [CONTRIBUTING.md 2.7.b](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue). The `gh-pages` branch should be kept clean of changes and up to date with HfLA, and anytime an issue is worked on a new branch should be created using HfLA's naming convention. To fix, it may be easiest to close this PR and open a new one with the correct branch. You can add @partapparam and @elisetvy as reviewers again.

Thanks for working on this issue!

**Pull request closed without merging**
