### PR TITLE
Removed unused alt-hero from _projects/access-the-data.md

### LINKED ISSUE #2920: Remove unused `alt-hero` field from access-the-data.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/access-the-data.md`, remove line 11 for the alt-hero
```
alt-hero: 'description of the hero image'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/access-the-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/access-the-data.md?plain=1#L11

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by scorbz9**
Fixes #2920 

### What changes did you make and why did you make them ?

  - Removed the unused alt-hero field from _projects/access-the-data.md (line 11)
  - This will make the website load faster, as well as make the code easier to understand and take less time to review

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes made to website.

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA: End of day 5/23
Availability: One Hour

**Comment by Jaretzbalba** [comment]
ETA: End of day 5/23
Availability: One Hour

**Review by Jaretzbalba — APPROVED** [review]
@scorbz9 Great work on this issue! I see that the the alt-hero property was deleted and everything looks good.

**Review by kathrynsilvaconway — APPROVED** [review]
@scorbz9  Nice work on this issue. I see you have deleted line 11 from the access-the-data md file. Everything looks good!

**Pull request merged**
