### PR TITLE
Update Heading Element Color Citizen-Engagement

### LINKED ISSUE #2464: Update Citizen Engagement page's h4 titles to match Figma design
### Overview
We need to adjust ~the SDG card padding and~ the font color of the H4 titles so that they match the Figma design and the design system color usage guidelines. 

Jessica removed the action item of updating the SDG card padding from this issue. (See https://github.com/hackforla/website/issues/2464#issuecomment-1014110882 for more information.)

### Action Items
- [x] **Adjust color of H4 titles so that they match the Figma design and the design system. They are currently #464646, rather than #333333 as the design system stipulates for our dark font.** 
   Screen Shot 2021-11-08 at 5 45 21 PM

<details>
  <summary>No longer adjusting bottom padding of SDG card</summary>
  - [ ] **Adjust bottom padding of SDG card so that it matches the Figma design.**
  - Current version on site to be changed:
    Screen Shot 2021-11-08 at 5 51 46 PM
  - Figma design:
    Screen Shot 2021-11-08 at 5 51 55 PM
</details>

### Resources/Instructions
[HfLA - Citizen Engagement Page](https://www.hackforla.org/citizen-engagement)
[Figma - Citizen Engagement](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15901%3A100458)
[Citizen Engagement SCSS](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_citizen_engagement.scss)
[citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html)

### PR DESCRIPTION
**Pull request by lindseyindev**
Fixes #2464 

### What changes did you make and why did you make them ?

  - Updated all h4 elements that had a color property other than #333333 to #333333
  - Updated an h3 element that also needed to have #333333 color value per checking figma design
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
before design

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after design

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
@lindseyindev Thanks for working on this issue. Instead of the hex value `#333333` , could you use `$color-black` from the Color System in the Design System?
For your reference, the colors are defined here: https://github.com/hackforla/website/blob/508dc989cf45a8b339fb430e87e22f751bc17db1/_sass/variables/_colors.scss
(Note: `$color-black` is defined as `#333` in our codebase which is the 3 digit shorthand for `#333333`.)

**Comment by anthonysim** [comment]
@lindseyindev, LGTM, can you make the changes @JessicaLucindaCheng requested above? I will approve shortly after.

**Comment by lindseyindev** [comment]
Updated to the $color-black design system tag!

**Review by Georgema20 — APPROVED** [review]
Looks great to me! Nice job!

**Review by anthonysim — APPROVED** [review]
@lindseyindev, LGTM! Excellent!

**Pull request merged**
