### PR TITLE
SDG 8: Rename and replace image with correct color one

### LINKED ISSUE #4256: SDG 8: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `decent-work.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-08.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg8.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the SVG you just added by changing
```
<img src="/assets/images/sdg/decent-work.svg" alt="8 Decent Work and Economic Growth" />
```
to
```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth" />
```
- [x] Using Docker, check the About page's Sustainability section (https://www.hackforla.org/about/#sustainability) to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by aaronweixiangli**
Fixes #4256

### What changes did you make and why did you make them ?

 - In the assets/images/sdg directory, delete decent-work.svg
 - From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: E-WEB-Goal-08.svg
 - Add the svg you just downloaded into the assets/images/sdg directory
 - Rename that svg so that it becomes sdg8.svg
- In _includes/about-page/about-card-sustainability.html, update the path to the SVG you just added by changing
 ```
<img src="/assets/images/sdg/decent-work.svg" alt="8 Decent Work and Economic Growth" />
```
to 
 ```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth" />
```
  - Reason: We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

After replacing 'decent-work.svg' with 'sdg8.svg', I'm not seeing any visible changes. Please let me know if this is the expected outcome.

Note: I noticed that the path to the SDG image in the code was
```
<img src="/assets/images/about/sdg-elements/decent-work.svg" alt="8 Decent Work and Economic Growth" />
```
 instead of  
 ```
 <img src="/assets/images/sdg/decent-work.svg" alt="8 Decent Work and Economic Growth" />
 ```
I made sure to follow the instructions by pulling from upstream before pushing the changes, but it seems like there is a new merge that is causing conflicts with my pull request.

### CODE REVIEW

**Comment by chrismenke45** [comment]
Review ETA: 4/12 EOD
Availability: 4/12 8am-12pm

**Comment by KazushiR** [comment]
Review ETA: 4/12 EOD
Availability:Weekdays

**Review by chrismenke45 — CHANGES_REQUESTED** [review]
Hi Aaron,
You changes look good but there is a merge conflict. This will need to be resolved in order to complete the PR.  See [how to resolve merge conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts) in our wiki for instructions on how to resolve them. Let me know if you have any questions

**Comment by aaronweixiangli** [comment]
Hi @chrismenke45 , would it be easier if I delete this pull request and do it again? I think it's because it has conflict with the folder name. It won't take too much time if I do it again. What do you think?

**Comment by chrismenke45** [comment]
Hi @aaronweixiangli ,
Yes it looks like sdg8.svg should be saved in the **/assets/images/sdg/sdg8.svg**, not **/assets/images/about/sdg-elements/sdg8.svg**.I believe there is also an issue is with [about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html). Lines 49-56 appear to have been updated since you created your branch. You could still try to make the changes and then resolve conflicts(it would be good practice), but I think it would definitely be easier to just redo it. Make sure to pull from upstream gh-pages before starting over. Please feel free to request my review on your new PR and let me know if you have any questions.

**Review by KazushiR — DISMISSED** [review]
Hello, I reviewed the PR and everything looks good on my end. I see no issues when looking at the update.

**Comment by aaronweixiangli** [comment]
@chrismenke45 Got it. I will just close this pull request tonight and redo it. Thanks!

**Comment by chrismenke45** [comment]
@aaronweixiangli I'm going to close this PR. Is that okay?

**Pull request closed without merging**
