### PR TITLE
5167: Updated Project Profile

### LINKED ISSUE #5167: Update Project Profile: Brigade Organizers Playbook
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Brigade Organizers Playbook project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observing the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/brigade-organizers-playbook.md` file: 
- [x] Find the `title:` variable and replace:
```
title: Brigade Organizers Playbook
```
with:
```
title: BOP
```
- [x] Find the `description:` variable and replace:
```
description: Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.
```
with:
```
description: Each of the 80+ Code for America Brigades (chapters) was an experiment which generated valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each other's work, improving outcomes for the whole network.
``` 
- [x] Fnd the `leadership:` values and replace:
```
  - name: Bonnie Wolfe
    role: Agile Mentor & CfA National Advisory Council BOP project Co-Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/UGREE50MT'
      github: 'https://github.com/experimentsinhonesty'
    picture: https://avatars.githubusercontent.com/experimentsinhonesty
  - name: Thad K.
    role: CfA National Advisory Council BOP project Co-Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/UAU40G31A'
      github: 'https://github.com/thadk'
    picture: https://avatars.githubusercontent.com/thadk
  - name: Will Pfeffer
    role: CfA Brigade Network team representative
    links:
      slack: 'https://codeforamerica.slack.com/team/U014MEJV6KT'
      github: 'https://github.com/willpfeffer'
    picture: https://avatars.githubusercontent.com/willpfeffer
  - name: Sam H.
    role: Product Manager
    links:
      slack: 'https://codeforamerica.slack.com/team/U019C4LERSM'
      github: 'https://github.com/thesamwong'
    picture: https://avatars.githubusercontent.com/thesamwong
  - name: Serena Baleja
    role: Product Owner
    links:
      slack: 'https://codeforamerica.slack.com/team/U01FUJ7124S'
      github: 'https://github.com/Baleja'
    picture: https://avatars.githubusercontent.com/Baleja
  - name: Marianne Miranda
    role: UX Research Team Lead
    links:
      slack: 'https://codeforamerica.slack.com/team/U01ASEG8HK5'
      github: 'https://github.com/MarianneAnthonette'
    picture: https://avatars.githubusercontent.com/MarianneAnthonette
  - name: Raquel Nishijima
    role: Communication Designer & UX Researcher
    links:
      slack: 'https://codeforamerica.slack.com/team/U01EJ7KMLCV'
      github: 'https://github.com/raquelnish'
    picture: https://avatars.githubusercontent.com/raquelnish
  - name: Jon Kropko
    role: Data Scientist
    links:
      slack: 'https://codeforamerica.slack.com/team/UL9U380TH'
      github: 'https://github.com/jkropko'
    picture: https://avatars.githubusercontent.com/jkropko
  - name: Tan Zhou
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/UPMSC27G8'
      github: 'https://github.com/tan-zhou'
    picture: https://avatars.githubusercontent.com/tan-zhou
  - name: Helen Lin
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01B79J9V9B'
      github: 'https://github.com/osnickersnee'
    picture: https://avatars.githubusercontent.com/osnickersnee
  - name: Myranda Pierce
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01E521NT2L'
      github: 'https://github.com/myrandi'
    picture: https://avatars.githubusercontent.com/myrandi
  - name: Reem Mehdoui
    role: Research Analysis Contributors
    links:
      slack: 'https://codeforamerica.slack.com/team/U01DF6AE5TL'
      github: 'https://github.com/reemux'
    picture: https://avatars.githubusercontent.com/reemux
```
with:
```
  - name: Bonnie Wolfe
    role: BOP Project Lead
    links:
      slack: 'https://hackforla.slack.com/archives/C01Q24YF56J'
      github: 'https://github.com/experimentsinhonesty'
    picture: https://avatars.githubusercontent.com/experimentsinhonesty
  - name: Aleiya Gafar
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U01K7QMQ4TC'
      github: 'https://github.com/ag2463'
    picture: https://avatars.githubusercontent.com/ag2463
  - name: Evan Stalker
    role: Lead Designer
    links:
      slack: 'https://hackforla.slack.com/team/U04M979AY3G'
      github: 'https://github.com/ejstalker'
    picture: https://avatars.githubusercontent.com/ejstalker
  - name: Liz Brown
    role: UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U052DR4HVJS'
      github: 'https://github.com/ermbrown'
    picture: https://avatars.githubusercontent.com/ermbrown
  - name: Katrina Bonoan 
    role: UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U052LER0010'
      github: 'https://github.com/kit-katrina20'
    picture: https://avatars.githubusercontent.com/kit-katrina20
```
- [x] Replace the GitHub Link:

```
    url: 'https://github.com/codeforamerica/brigade-playbook'
```
with
```
    url: 'https://github.com/hackforla/BOP'
```
- [x] Replace the Slack Link:
```
    url: 'https://cfa.slack.com/archives/G0196272BBN'
```
with
```
    url: 'https://hackforla.slack.com/archives/C051M4JU562'
```
- [x] Verify the changes by viewing the [BOP](https://www.hackforla.org/projects/brigade-organizers-playbook) project page on your local environment in Docker and include a screenshot with your pull request

### Resources
- [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by GRK1998**
Fixes #5167

### What changes did you make?
  -I have made changes to the title, description, leadership, GitHub Link, and Slack Link

### Why did you make the changes (we will use this info to test)?
  -The Brigade Organizers Playbook project page needs to be updated so that the project information is up to date.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-09-01 at 9 27 39 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-09-01 at 9 31 32 PM

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/5/23
Availability: 1-3 PM everyday

**Comment by ronaldpaek** [comment]
I plan to review this by Sept 7th.

**Comment by ortegaa32** [comment]
- Pull request has correct branch and is linked to the correct issue. 
- Changes don't appear to break the website and screenshots accurately reflect the changes. 
- Changes were made to correct file and source code looks clean

Good job @GRK1998. Approving pull request.

**Review by ortegaa32 — DISMISSED** [review]

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @GRK1998 - Great job on this issue! Your branches are good, you have linked the issue, you are giving a short description of what you did and why, and you have provided before and after screenshots. Since there are changes, please provide before and after screenshots of the [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook) as well.

Also- _**only**_ in the `description: ` you -correctly!- made the changes requested by the issue. Unfortunately, a separate PR 5454 fixes #5411 changed the same entry, so your PR has a merge conflict that needs to be addressed. 

Therefore, for _**only**_ the line `description: ` please keep what is in the code currently and do not make the change shown on your issue. Here is a link from the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31d-dealing-with-merge-conflicts) on what to do. If you would like help please ask. 

Thank you for your work!

**Comment by t-will-gillis** [comment]
Hi @GRK1998 - Could you please give an update on your progress on this PR? Again, if you have questions or need help please message myself or anyone else. Thank you

**Comment by t-will-gillis** [comment]
@GRK1998 Please provide an update on this PR before Sunday or it will be closed. Thank you.

**Comment by GRK1998** [comment]
I have resolved the issue  please let me know if there are any changes to be made

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @GRK1998  Thanks for making the changes and updating the `description: ` Please update the `title: `  as noted on #5167. Also, please provide visuals showing the 'before' and 'after' changes on the project page as well as on the [Brigade Organizers Playbook](https://www.hackforla.org/projects/brigade-organizers-playbook) page.

**Comment by GRK1998** [comment]
Hi @t-will-gillis I have made the changes as requested.

### Screenshots of Proposed Changes Of The Website



<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-09-01 at 9 27 39 PM



</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-09-30 at 9 37 51 PM


</details>

### Screenshots of Proposed Changes Of The [Brigade Organizers Playbook](https://www.hackforla.org/projects/brigade-organizers-playbook) page



<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-09-30 at 9 42 00 PM



</details>

<details>
<summary>Visuals after changes are applied</summary>
  

Screenshot 2023-09-30 at 9 42 32 PM


</details>

**Review by t-will-gillis — APPROVED** [review]
@GRK1998 - Looks perfect, thank you

**Pull request merged**
