### PR TITLE
Updated the alt text for the Public Tree Map image

### LINKED ISSUE #4044: Public Tree Map: Update alt text for the Public Tree Map image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Public Tree Map image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/public-tree-map.md`:

**From:**
```
alt: 'Zoomed-in map showing ten streets of the neighborhood. Each dot on the map displaying a tree from the urban forest'
```
**To:**
```
alt: 'Public Tree Map'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Public Tree Map Page: https://www.hackforla.org/projects/public-tree-map

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/public-tree-map.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/public-tree-map.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by mattmalane**
Fixes #4044

### What changes did you make and why did you make them ?

  - Updated alt value to `Public Tree Map`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changed the the alt value for the `Public Tree Map` image. No visual changes to the website.

### CODE REVIEW

**Comment by nicolettedmabeza** [comment]
Review ETA: 6pm 3/5/23
Availability: 3-5pm PST Friday and 3-5pm Saturday

**Review by nicolettedmabeza — APPROVED** [review]
This branch is coming from the correct branch and committing into gh-pages. Linked issue is stated within the pull request. The code looks clean and applicable. Changes in code are reflected in browser and does not break website. No visual changes due to nature of issue. Great job!

**Comment by bootcamp-brian** [comment]
Review ETA: 6:30pm Today
Availability: Before 5pm Friday-Sun this weekend

**Review by bootcamp-brian — APPROVED** [review]
Your pull request and branches have been set up correctly and you completed the issue's tasks. I confirmed that the changes are reflected on the site's projects page and your pull request looks nice and clean. Everything should be good to go. Good job!

**Pull request merged**
