### PR TITLE
img Tag Refactor - removed ending slash for meetup.svg - #5184

### LINKED ISSUE #5184: img Tag Refactor: _includes/events-page/left-col-content.html - meetup.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/left-col-content.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="vector-img" src="../assets/images/hack-nights/meetup.svg" alt="meetup logo" />
```
to
```
<img class="vector-img" src="../assets/images/hack-nights/meetup.svg" alt="meetup logo">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/left-col-content.html
2. Webpage(s): https://www.hackforla.org/events
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by meru-a**
Fixes #5184 

### What changes did you make?
  - Removed ending slash for img tag of meetup.svg

### Why did you make the changes (we will use this info to test)?
  - Needed a consistent codebase with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

No visual changes.

</details>

<details>
<summary>Visuals after changes are applied</summary>

No visual changes.

</details>

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: In the evening & most of the day on weekends
ETA: Expected to finish review by EOD Friday

**Comment by LRenDO** [comment]
Hi @yujioshiro, @ronaldpaek, and @Jfong1218! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.  Thanks!

**Comment by Jfong1218** [comment]
PR Review:
Availability: weekdays afternoon starting 8/24
ETA: EOD 8/26

**Review by MattChau01 — APPROVED** [review]
- The new branch is properly going into the correct branch `gh-pages`. ✅ 
- Original issue #5184 was properly linked and referenced. ✅ 
- The specified instance of an `` tag on line 2 was properly adjusted to match the consistency of code. ✅ 

Great work! I think the only room for adjustment would be to edit your comment and remove the `Screenshots` section since there were no visual images attached. Other than that, good on my side!

**Review by ronaldpaek — APPROVED** [review]
Great job, all changes to the file look correct to me. :)

**Comment by Jfong1218** [comment]
Great job!
I can confirm that the ending slash for img tag for meetup.svg has been deleted, and none of the other lines of code were affected. 
The website behaved the same before and after the change.
- Issue # was properly linked
- The merge is commit into hackforla: gh-pages
- The code is clean

**Review by Jfong1218 — APPROVED** [review]
Great job!
I can confirm that the ending slash for img tag for meetup.svg has been deleted, and none of the other lines of code were affected.
The website behaved the same before and after the change.

Issue # was properly linked
The merge is commit into hackforla: gh-pages
The code is clean

**Review by adrianang — APPROVED** [review]
Hi @pearlescence-m — the branching is set up correctly, the corresponding issue is linked, the requested change of removing the ending slash in line 2 was made exactly as asked, and it doesn't seem to affect anything on my local environment (as expected).

The What and Why of your PR are clearly written, but I would agree with @MattChau01's suggestion of deleting the Screenshot section, or at least removing the `<summary>` and `<details>` tags from those sections (and saying there aren't visual changes, as you did above).

Also, I notice that you had made another pull request (#5299) while this one was in the process of being reviewed; per the [Github Actions bot message for this issue](https://github.com/hackforla/website/issues/5184#issuecomment-1681568197) posted upon your self-assignment, developers may not assign themselves to more than one open issue at a time (the PR of the issue must also be closed, not only submitted).

Thanks for taking up this issue! 🙌🏼

**Pull request merged**
