### PR TITLE
Delete solidarity-pana.svg

### LINKED ISSUE #4579: Delete unused solidarity svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Currently, the website credits have an item for the [solidarity-pana.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/solidarity-pana.svg), however this image is no longer used anywhere in the site. We need to delete this image so that we don't have extraneous assets in our codebase.

### Action Items
- [x] In your local IDE, navigate to `assets/images/donate`
- [x] Delete `solidarity-pana.svg`

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4531
- [Credits page](https://www.hackforla.org/credits/)

### PR DESCRIPTION
**Pull request by Mayank2808sharma**
Fixes #4579

### What changes did I make and why did I make them:-
- Solidarity-pana.svg is not being used in the website
- Deleted solidarity-pana.svg from assets/images/donate to reduce repository size and to keep it maintainable
-  There is no visual difference in the website as the current website is not using that partcular image

Here is Some more Detail to it

###Before Deletion
before
### After Deletion
after

### CODE REVIEW

**Review by DevRishiJain — APPROVED** [review]
I have seen the code and working properly and the commit is legit

**Comment by 93Belen** [comment]
Availability: Monday, Tuesday, Thursday and Sunday all day.
ETA: Tuesday by 6pm.

**Review by 93Belen — APPROVED** [review]
Looks good :)

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @Mayank2808sharma - Well done. You are using the correct branches, you are linked back to the correct issue, and you have made the changes per the issue. 

Some notes: it would be better to leave the original wording in the description, that is "What changes did you make and why did you make them?" Along with this, when you describe the changes you made you should also note why you made the changes.

Also, in this issue you are deleting something visible from the website so you need to include before and after screenshots showing the change. Please add back the section "Screenshots of Proposed Changes Of The Website" with the before and after.

@DevRishiJain and @93Belen - thank you for reviewing this and other issues. Please keep in mind that part of the reason that we are reviewing each other's work is so that we can help each other. When reviewing PRs, we want to be explaining what we are checking: are the branches correct? is the issue linked correctly? did the dev make the changes they were supposed to make? does everything appear correct in various screen sizes when you view the changes on Docker? and so on. The wiki doc for [reviewing PRs](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) gives a great explanation of the whats, hows, and whys for reviewing PRs. . .

**Comment by t-will-gillis** [comment]
Hi @Mayank2808sharma - Thank you for sticking with this- especially on a ‘good first issue’- and thanks for making the changes to the description- this part looks great. Regarding the visuals- my apologies because I was wrong!- when I opened the [Credits]( https://www.hackforla.org/credits/) in Docker with your code it looked like the Solidarity icon was gone and I had mistakenly believed this was a visual change to the website. 

Note: I know that you added the visuals / screenshots of the code because I incorrectly said there was a visual change. >> **You were right the first time**, and in similar cases in the future you should do what you did and only say  “There are no visual changes to the website” without the code screenshots. <<

So great job: thanks for the changes to the description, apologies again about the visuals, and I am merging this.

**Review by t-will-gillis — APPROVED** [review]
See comment above

**Pull request merged**
