### PR TITLE
Change alt text

### LINKED ISSUE #1583: Change Alt Text for Review Icon on Credit page
### Overview
Alt text for Review Icon on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Review Icon'

```diff
- alt: 'Image of Review'
+ alt: 'Review Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/review.yml#L10

### PR DESCRIPTION
**Pull request by jpandh**
Fixes #1583

### 
In website/_data/internal/credits/review.yml
- alt: 'Image of Review'
+ alt: 'Review Icon'

Screen Shot 2021-07-17 at 11 29 07 PM

### CODE REVIEW

**Review by macho-catt — CHANGES_REQUESTED** [review]
For the most part, the code change itself is good. Good job on that! One thing I noticed though, is that on lines 8 and 10 you replaced the single quotes to double quotes. It doesn't really change anything in how the page looks overall, but for styling purposes (and to keep consistency across the styles of the other yml files) could you revert them back to single quotes? Other than this requested change, this should be good.

**Review by macho-catt — APPROVED** [review]

**Comment by macho-catt** [comment]
After the change, it looks good. Good job!

**Comment by Zak234** [comment]
Everything looks good!

**Review by Zak234 — APPROVED** [review]
Everything looks good!

**Comment by Aveline-art** [comment]
Great work on your first issue, @jpandh . With two reviews, I have merged this. Feel free to pick up your good second issue from the prioritized backlog. Let me know if you have any questions!

**Pull request merged**
