### PR TITLE
Updated Project Profile with New Member

### LINKED ISSUE #4585: Update Project Profile: Hackforla.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project leadership team is up to date. 

### Action Items
- [ ] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [ ] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [ ] Name: MJ Shelton
  GitHub Handle: mjshelton12
  Role: Merge Team
  Slack Member ID: U04UG4UQE8G
- [ ] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by vanyanv**
Fixes #4585

### What changes did you make and why did you make them ?

  - Added new team member 
  - Added Role
  - Added GitHub handle
  - Added Slack ID
  - Added User Image

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: M-F 10AM - 3PM
ETA 5/10/23

**Comment by matthewmpan** [comment]
Availability: M-F 12PM - 8PM
ETA: EOD 5/9/23

**Review by matthewmpan — DISMISSED** [review]
@vanyanv - Your branches are set up correctly, the issue is linked, and you completed all of the action items. Your changes look good in the browser and your code looks clean and concise. 

Congrats on your first issue, and thanks!

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
Hi @vanyanv , Merge branches look good, code changes are as mentioned in the issue. Needs a little clean up- delete line 87 and line 126

**Review by Thinking-Panda — APPROVED** [review]
Thankyou @vanyanv for a clean code.

**Review by matthewmpan — APPROVED** [review]
@vanyanv - Your changes cleaned up the code even more. Good work.

**Pull request merged**
