### PR TITLE
Update project details for lucky parking

### LINKED ISSUE #3056: Update Project Profile: Lucky Parking
### Overview
As a product manager of Lucky Parking I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md

### Action Items
- [ ] In [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md), update the [Lucky Parking](https://www.hackforla.org/projects/lucky-parking) Team Leadership as follows. If an item is already checked off, double check the information matches the info in [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md).  
  - [x] name: Greg Pawin
    - [ ] role: Data Scientist Lead
    - [X] slack: 'https://hackforla.slack.com/team/UUEQF3AJG'
    - [X] github: 'https://github.com/gregpawin'
    - [X] picture: https://avatars.githubusercontent.com/gregpawin
  - [ ] name: Yuting Chu
    - [ ] role: Product Manager Lead
    - [ ] slack: 'https://hackforla.slack.com/team/U03J4E55KCH'
    - [ ] github: 'https://github.com/ychu196'
    - [ ] picture: https://avatars.githubusercontent.com/ychu196
  - [ ] name: Glen Florendo
    - [ ] role: Full-Stack Developer Lead
    - [ ] slack: https://hackforla.slack.com/team/UFQGH8JH0
    - [ ] github: https://github.com/glenflorendo
    - [ ] picture: https://avatars.githubusercontent.com/u/9373317
    - [ ] name: Michael Morgan
    - [ ] role: UX/UI Design Lead
    - [ ] slack: 'https://hackforla.slack.com/team/U01SPJCC26A'
    - [ ] github: 'https://github.com/mklmrgn'
    - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
  - [ ] name: Yen Phan
    - [ ] role: User Research
    - [ ] slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
    - [ ] github: 'https://github.com/ymphan'
    - [ ] picture: https://avatars.githubusercontent.com/ymphan
  - [ ] name: Yujin Chang
    - [ ] role: UI Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U0270QURQCD'
    - [ ] github: 'https://github.com/eugenecha'
    - [ ] picture: https://avatars.githubusercontent.com/eugenecha
  - [ ] name: Jodie Chen
    - [ ] role: UI/UX Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U03RFGLLAQG'
    - [ ] github: 'https://github.com/jojochen25'
    - [ ] picture: https://avatars.githubusercontent.com/u/103106753
  - [ ] name: Sijia Pitts
    - [ ] role: UI/UX Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U03CBK89KUY'
    - [ ] github: 'https://github.com/sijiapitts'
    - [ ] picture: https://avatars.githubusercontent.com/u/103976231
  - [ ] name: Pratibha Shivanand
    - [ ] role: Data Scientist
    - [ ] slack: 'https://hackforla.slack.com/team/U03SM1LF9HD'
    - [ ] github: https://github.com/pratibhanagesh
    - [ ] picture: https://avatars.githubusercontent.com/u/8139348
  - [ ] name: Aletia Trepte
    - [ ] role: Data Scientist/Engineer
    - [ ] slack: 'https://hackforla.slack.com/team/U03KAPRML9Y'
    - [ ] github: https://github.com/parcheesime
    - [ ] picture: https://avatars.githubusercontent.com/u/38143160
  - [ ] name: Yao Guan
    - [ ] role: Quant UXR
    - [ ] slack: 'https://hackforla.slack.com/team/U03F35T4PND'
    - [ ] github: https://github.com/yaoguan
    - [ ] picture: https://avatars.githubusercontent.com/u/41702875
   - [ ] name: Diedrich Chavarria
     - [ ] role: Full Stack Developer
     - [ ] slack: 'https://hackforla.slack.com/team/U031VEUS0CW'
     - [ ] github: 'https://github.com/DCH-CH'
     - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
   - [ ] name: Seymour Liao
     - [ ] role: Data Scientist
     - [ ] slack: 'https://hackforla.slack.com/team/U018XPTSTC6'
     - [ ] github: 'https://github.com/Seymour100'
     - [ ] picture: https://avatars.githubusercontent.com/Seymour100
   - [ ] name: David Lam
     - [ ] role: Data Scientist
     - [ ] slack: 'https://hackforla.slack.com/team/U02D8CDURF0'
     - [ ] github: 'https://github.com/davidlamcanada'
     - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
- [x] Also, add the Overview PDF by
  - [x] Downloading the PDF from https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf
  - [x] Adding the PDF to the `assets/pdfs` directory
  - [x] In the `links` section [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md), add an `Overview` with a url that points to the PDF you added to `assets/pdfs` directory. (For an example of an Overview link in code, see [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1).)

### Resources
- File to make edits: https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md
- [Lucky Parking page](https://www.hackforla.org/projects/lucky-parking)
- https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf
- For an example of an Overview link in code, see [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1).

<details>
  <summary>Click here to see the original request for reference</summary>

  - [ ] Lucky Parking Team Leadership
     - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
        - [X] title
        - [X] description
        - [X] image
        - [ ] leadership
        - [x] name: Greg Pawin
           - [ ] role: Product Owner
           - [X] slack: 'https://hackforla.slack.com/team/UUEQF3AJG'
           - [X] github: 'https://github.com/gregpawin'
           - [X] picture: https://avatars.githubusercontent.com/gregpawin
        - [ ] name: Gordon Ruby
           - [ ] role: Product Manager Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U02AJ61CSQP'
           - [ ] github: 'https://github.com/gordonruby'
           - [ ] picture: https://avatars.githubusercontent.com/gordonruby
        - [X] name: Matthew Cacho
           - [X] role: Full-Stack Developer Lead
           - [X] slack: 'https://hackforla.slack.com/team/U0262GA4DD2'
           - [X] github: 'https://github.com/macho-catt'
           - [X] picture: https://avatars.githubusercontent.com/macho-catt
        - [ ] name: Yen Phan
           - [ ] role: Lead User Research
           - [ ] slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
           - [ ] github: 'https://github.com/ymphan'
           - [ ] picture: https://avatars.githubusercontent.com/ymphan
        - [ ] name: Yujin Chang
           - [ ] role: UX/UI Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U0270QURQCD'
           - [ ] github: 'https://github.com/eugenecha'
           - [ ] picture: https://avatars.githubusercontent.com/eugenecha
        - [ ] name: Marie Li
           - [ ] role: Data Science Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U01S72NLGAC'
           - [ ] github: 'https://github.com/zhao-li-github'
           - [ ] picture: https://avatars.githubusercontent.com/zhao-li-github
        - [ ] name: Michael Morgan
           - [ ] role: UX/UI Design
           - [ ] slack: 'https://hackforla.slack.com/team/U01SPJCC26A'
           - [ ] github: 'https://github.com/mklmrgn'
           - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
        - [ ] name: Glen Florendo
           - [ ] role: Full Stack Developer
           - [ ] slack: 'https://hackforla.slack.com/team/UFQGH8JH0'
           - [ ] github: 'https://github.com/glenflorendo'
           - [ ] picture: https://avatars.githubusercontent.com/glenflorendo
        - [ ] name: Diedrich Chavarria
           - [ ] role: Full Stack Developer
           - [ ] slack: 'https://hackforla.slack.com/team/U031VEUS0CW'
           - [ ] github: 'https://github.com/DCH-CH'
           - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
        - [ ] name: Seymour Liao
           - [ ] role: Data Scientist
           - [ ] slack: 'https://hackforla.slack.com/team/U018XPTSTC6'
           - [ ] github: 'https://github.com/Seymour100'
           - [ ] picture: https://avatars.githubusercontent.com/Seymour100
        - [ ] name: David Lam
           - [ ] role: Data Scientist
           - [ ] slack: 'https://hackforla.slack.com/team/U02D8CDURF0'
           - [ ] github: 'https://github.com/davidlamcanada'
           - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
        - [X] links
           - [X] Github
           - [X] Slack
           - [X] Test Site
           - [X] Demo Site
           - [X] Site
        - [X] technologies
        - [X] partner
        - [X] tools
        - [X] status
   - [x] Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below
   
  ### Resources
  [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

</details>

### PR DESCRIPTION
**Pull request by macho-catt**
Fixes #3056 

### What changes did you make and why did you make them ?

  - Updates team project details so they are up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

full-page-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
full-page-after

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/17
Availability: 2 hours

**Review by Jaretzbalba — APPROVED** [review]
@macho-catt The new code you added shows up locally on my end and the project team looks like it was updated cleanly. Great job on this!

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Tuesday, May 17

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Hi @macho-catt, great work on this! All the new names, titles, and links are there. I notice two things that may need some attention:

1. You use "Full-Stack" (with a hyphen) under your name, but "Full Stack" (no hyphen) under both Glen Florendo and Diedrich Chavarria's names. For consistency, could you please pick your preferred spelling and update those three names accordingly?
2. There was a section at the end of the issue that requested to add the Lucky Parking one-sheet PDF to assets/pdfs. Could you please add that as well?

Great job again and feel free to re-request a review when you're ready.

**Comment by Jaretzbalba** [comment]
@tamara-snyder Thank you for catching this! I see that it's missing that step as well now along with the consistency issue.

**Review by Jaretzbalba — CHANGES_REQUESTED** [review]
@macho-catt Please make the necessary changes as stated in the comments above. Thanks again for working on this!

**Comment by macho-catt** [comment]
I will work on it this week.
Status: Will do the changes requested
ETA: by next Sun
Availability: 2 hours
Progress: need to update PR
Blockers: None

**Comment by macho-catt** [comment]
Status: Updated PR
ETA: n/a
Availability: 2 hours
Progress: updated PR
Blockers: None

**Review by Jaretzbalba — CHANGES_REQUESTED** [review]
@macho-catt Thank you for fixing the roles to keep our code consistent and for adding the pdf link. However, I can't actually find the pdf in the `assets/pdfs` directory so please double-check that you downloaded the pdf and put it in the correct location. Other than that everything looks good!

**Comment by macho-catt** [comment]
Sorry, it was untracked. Added! @Jaretzbalba

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Hi @macho-catt, thank you for making those changes and my apologies for the delayed review. This all looks good, but I noticed that the Overview link doesn't show up on the main project page — it's only shown once you click on the Lucky Parking project card. Can you please look into why this is?
Screen Shot 2022-06-24 at 9 11 24 AM
Screen Shot 2022-06-24 at 9 11 34 AM

**Comment by kathrynsilvaconway** [comment]
@macho-catt Hi, are you still planning to complete this issue? Please leave a comment with your availability. If you are feeling stuck, please reach out to us on the slack channel or come by office hours at 7pm PST on Thursday.

**Pull request closed without merging**
