### PR TITLE
Fix alignment#1498

### LINKED ISSUE #1498: Fix alignment of News section in About page
### Overview
We need to fix the News section of the About page so that it is properly aligned and closer to how it looks in the original Figma design

### Action Items
- [x] Review the original [Figma design of the About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) with the correct News section alignment (in pink rectangle all the way on bottom of page)
- [x] Fix the alignment of the News section in the [About page](https://www.hackforla.org/about/#news) so that it is closer to the original Figma design

### Resources/Instructions
- [Original Figma design of About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) (all the way on bottom in pink rectangle)
- [About page](https://www.hackforla.org/about/#news)
- [HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Click arrows:

<details>
<summary>How About page News section looks now:</summary>
<br>
Screen Shot 2021-04-30 at 6 18 22 PM
</details>

<details>
<summary>How About page News section looks on Figma:</summary>
<br>
Screen Shot 2021-04-30 at 6 21 08 PM
</details>

### PR DESCRIPTION
**Pull request by 1anya1**
Fixes #1498

### What changes did you make and why did you make them ?

  - Refactored news container, added new styles according to figma spect both for mobile and web views.
  - Added new class to news container/ wrapped images. to prevent overrides  of repeating components
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screen Shot 2022-03-10 at 1 51 42 PM
Screen Shot 2022-03-10 at 1 53 29 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2022-03-10 at 1 54 57 PM

Screen Shot 2022-03-10 at 2 06 08 PM

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 2 hours
Review ETA: Thursday, March 10, 2022

Update: I'm going to delay my review until tomorrow, March 11, 2022.

**Comment by tamara-snyder** [comment]
Hi @1anya1, apologies for my confusion — I'm still going through your code, but I'm wondering if the changes in [pages/getting-started.html](https://github.com/hackforla/website/pull/2959/files#diff-f75aac8ebcbb9718e73bf3990061a0f98feb49a25c664338ea6a123afb299d24) have anything to do with this issue.

If they're not relevant, can you please remove the changes in that file and re-request a review?

**Comment by 1anya1** [comment]
Resubmitting pull request

**Comment by 1anya1** [comment]
@tamara-snyder I am not sure what the issue was here. I see there are only files that were changed are the once I made for the existing issue. Can you please specify what  you are referring to?

**Pull request closed without merging**
