### PR TITLE
Refactor Tools Data for hellogov.md

### LINKED ISSUE #4807: Refactor Tools data for hellogov.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [hellogov.md](https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Mongo, Angular, Node, JS
```
to
```
tools:
  - Mongo
  - Angular
  - Node
```
Do not include JS even though it is in the current tools list, because it is actually categorized under languages, which is delivered by pulling the language for a repo from the GitHub API.
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by evanhesketh**
Fixes #4807 

### What changes did you make?
  - Changed tools data in hellogov.md from a string to a list

### Why did you make the changes (we will use this info to test)?
 - Tools data in .md needs to be changed from a string to a list so that the projects-check page can be refactored to include a dropdown for tools in the future

### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)

<details>
  <summary>Visuals before changes are applied</summary>
Project list:
<br>
<br>
4807-projects-list-before
<br>
Project detail:
<br>
<br>
4807-project-details-before
</details>

<details>
  <summary>Visuals after changes are applied</summary>
Project list:
<br>
<br>
4807-project-list-after
<br>
Project detail:
<br>
<br>
 4807-project-details-after

</details>

### CODE REVIEW

**Comment by jch1013** [comment]
ETA: 7/27, EOD
Availability: Any

**Review by jch1013 — APPROVED** [review]
Changes are being merged from personal fork to gh-pages, and the changes match the changes outlined by the issue. Website looks as it should, with "JS" being removed from the tools section. A few additional spaces seem to have been removed for consistency, but there appears to be no visual impact and I think it should be fine as long as the merge team is ok with it.
Also, I didn't see any screenshots of the visual changes in the pull request, please try to include these when you are able to so the merge team can easily review the pull request. 
Nice work overall!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @evanhesketh - Great job! Your branches are good, you linked the issue, and you provided visuals before and after. (Thanks for working with @jch1013 on the screenshots!) 

One minor note: please provide the "Why did you make the changes (we will use this info to test)?" This does not need to be elaborate and you can use the original issue i.e. "We need to refactor the `tools` data in the .md file so that in the future we will be able to add a dropdown filter to the "Projects Check" page."

Thanks for working on this!

**Comment by kwangric** [comment]
Hey @evanhesketh! If you've made the requested changes, you can re-request reviews from the assigned reviewers so they know when to take a look at your PR again.

Review

**Review by t-will-gillis — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Thanks for adding the reason for the change to the description!

**Pull request merged**
