### PR TITLE
Update yellow variables

### LINKED ISSUE #2199: Design System Audit: Swap colors with color variables: Yellows
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the yellow colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (yellow)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [ ] First, check for all of the color types listed in the Resource section below to make sure it isn't used in our codebase.
  - [ ] Then, if it isn't used,
    - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
    - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [ ] Release dependency on #2114 , if conditions are met
- [ ] See additional Action Items in this comment: https://github.com/hackforla/website/issues/2199#issuecomment-1334702332

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L19-L22

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  
</details>

 #### Hard-coded colors can be one of the following color types:
- HTML color codes
- Hex color codes
- RGB 
- HSL values
- HTML color names

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #2199

### What changes did you make and why did you make them ?

  - Checked for unused yellow color variables, but all were in use.
  - Changed the hex color in `_about.scss` to its variable name for readability

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visible changes to the website.

### CODE REVIEW

**Comment by ericvennemeyer** [comment]
`Availability`: Today, 8/29 -- 1 hr
`ETA`: EOD 8/29

**Review by ericvennemeyer — APPROVED** [review]
Branch is correct, changes requested in original issue have been made, and doesn't break the site. Nice work!

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-29

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct! Great job!! @d-perez-8

**Pull request merged**
