### PR TITLE
updated mayor quote

### LINKED ISSUE #936: Add mayor quote portion to bottom of About Us page
### Overview
We need to replace the screenshot of the mayor's quote on the bottom of the [About Us page](https://www.hackforla.org/about-us) with code so that it can be visible to search engines, etc. 

Note: The About Us page is in progress and being worked on by @drubgrubby who is on a break right now so please don't edit any of the other code on this page, but this quote portion should definitely save him some extra work.  

### Action Items

Font-End Development
- [x] Read about the [Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture) (if you haven't already)
- [x] Review the About Us [Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) (final design in green rectangle) 
- [x] Write code to replace the mayor quote screenshot that is currently on the bottom of the [About Us page](https://www.hackforla.org/about-us) 

### Resources/Instructions
- [Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
- About Us page - this is not accessible from the main site nav yet- only through the url https://www.hackforla.org/about-us
- [About Us Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) - Final design is in a green rectangle on the bottom. Zoom in with + on keyboard. View the CSS details on the right panel when you select specific elements of the page
- [Hack for LA homepage](https://www.hackforla.org/#) - The About Us mayor quote section is modified from the one in the bottom of the Home page, so you can pull the image and text from here (files: eric_garcetti.md, img url: /assets/images/testimonials/quote-garcetti.jpg, & press.html)

This is the mayor's quote that needs to be developed:

Screen Shot 2021-01-12 at 9 02 18 PM

### PR DESCRIPTION
**Pull request by thatguyish**
fixed #936

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
The quote itself looks good to me.  Perhaps @daniellex0 has a second to do a visual review. 

Two things: 
1) I think that the styles should not go on /elements/_typography.scss unless they're also going to be used on other pages.  

@daniellex0 - would we use these same classes on the quote on the main page?  Would we use them somewhere else?  Do you have an opinion on where these classes should live? (They can always just live on about-us.scss)

2) Your changes seem to have impacted the sticky navigation somehow.  See the image below, when the page is all the way at the top, before it gets sticky, it has just disappeared. That needs to be corrected...obviously. 

Screen Shot 2021-02-09 at 1 25 57 PM

**Comment by daniellex0** [comment]
Just did a visual review, looks great @thatguyish ! 👍 My only minor edit is that the _"- Mayor Eric Garcetti"_ line  shouldn't be in itallics- instead if you'll notice in the Figma and in David's screenshot that's on the current page, it's regular straight text but a slightly lighter color (#767676)

Screen Shot 2021-02-09 at 3 34 06 PM

And @drubgrubby I agree I don't think it should live on the typography scss file quite yet- at least not until we consolidate with the quote on the homepage when the redesign happens.. so I think let's keep it on about_us.scss for now if possible and I'll think about its reusability

**Comment by thatguyish** [comment]
Made the changes necessary for the cite and card.
Screen Shot 2021-02-13 at 8 45 28 PM
Screen Shot 2021-02-13 at 8 45 36 PM

**Comment by daniellex0** [comment]
@thatguyish Great, looks good! 👍

**Comment by thatguyish** [comment]
@daniellex0 thank god cuz if the designer aint happy no one is lol.

**Comment by drubgrubby** [comment]
@thatguyish @daniellex0  - I guess everyone's happy, then.  Nice work!  Ready to merge.

**Pull request merged**
