### PR TITLE
Found the superfluous empty class attribute in _guide-pages/2FA.html …

### LINKED ISSUE #5712: attribute appears to be superfluous in `_guidepages/2FA.html`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Determine whether or not an empy class attribute in `_guidepages/2FA.html` is superflous, and if so, remove it.    

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 50, and note the line of code
```
<div class=''>

```
- [x] Determine whether the class attribute is superflous (unnecessary).  
  - [x] If so, remove it, then perform local testing using docker to ensure that the behavior and appearance of the page is unchanged, and then proceed to create a Pull Request
  - [ ] If the HTML should remain as-is, explain in a comment in the issue, then move the issue to Questions/In Review and apply the 'ready for dev lead' label.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA

### PR DESCRIPTION
**Pull request by LukeLowrey2**
Fixes #5712

### What changes did you make?
  - Found the superfluous empty class attribute in _guide-pages/2FA.html at line 50
  - Deleted the empty class attribute
  -

### Why did you make the changes (we will use this info to test)?
  - The empty class attribute at line 50 of _guide-pages/2FA.html was not needed
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
There were no visual changes to the website

### CODE REVIEW

**Comment by Chrisklangley** [comment]
Availability: Weekdays 6-9pm
ETA: 11/15/23 EOD

**Review by Chrisklangley — APPROVED** [review]
Hey Luke!

Great work on your PR
• you created a branch with the correct syntax and committed to gh-pages
•  Going over your linked issue I am able to understand the the changes you made  to _guide-pages/2FA.html 
• I see you removed the unused class attribute from the div tag on line 50

Visually everything looks good. the only tip I would give you is to remove any unused bullet points  from the pull request template

**Comment by KyleA99** [comment]
Availability: M-F, 5-8 PM
ETA: 11/15/23 EOD

**Review by KyleA99 — APPROVED** [review]
- Your PR is done with the correct branch.
- Your code is correctly changed.
Reviewed and approved!

Great work @LukeLowrey2

**Pull request merged**
