### PR TITLE
Fixed misspelled words on home-unite-us.md file

### LINKED ISSUE #2912: Fix misspelled words on home-unite-us.md file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_projects/home-unite-us.md`,  on line 4, change the spelling from "non-profits" to "nonprofits" and the spelling from "scaleable" to "scalable", so

  ```
  description: We're working with community non-profits who have a Host Home initiative to develop a workflow 
  management tool to make the process scaleable
  ```
  becomes
  ```
  description: We're working with community nonprofits who have a Host Home initiative to develop a workflow 
  management tool to make the process scalable
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website pages with the issue:
- https://www.hackforla.org/projects
- https://www.hackforla.org/projects/home-unite-us

File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_projects/home-unite-us.md?plain=1#L4

### PR DESCRIPTION
**Pull request by Wny-Duong**
Fixes #2912 

### What changes did you make and why did you make them ?

  - Corrected a typo in the home-unite-us.md file on line 4 from "non-profits" to "nonprofits."

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by harshitasao** [comment]
Availability : Flexible
ETA : 18/04/2022

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: EOD 4/18

**Review by Sparky-code — APPROVED** [review]
Hi @Wny-Duong, everything looks good, text reads well and I couldn't find any additional undocumented errors in need of update. Great job!

Noted that part of your action items weren't done because they had become not applicable due to [issue 3001](https://github.com/hackforla/website/pull/3001) changing some of the text since this issue was written.

**Review by harshitasao — APPROVED** [review]
Hi, @Wny-Duong Great job! The changes look good to me.

**Pull request merged**
