### PR TITLE
Updated pre-work-template---design.md labels

### LINKED ISSUE #4480: Update labels: Issue Template: pre-work-template---design
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/pre-work-template---design.md`
- [x] Replace the following line
   ```
   labels: 'Feature: Onboarding/Contributing.md, prework, role: design, size: 1pt'
   ```
   with
   ```
   labels: ['Feature: Onboarding/Contributing.md', 'prework', 'role: design', 'size: 1pt', 'Complexity: Missing']
   ```
- [ ] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: [Updated Pre-work Design Template](https://github.com/LRenDO/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Crole%3A+design%2Csize%3A+1pt%2CComplexity%3A+Missing&projects=&template=pre-work-template---design.md&title=Pre-work+Checklist%3A+Designer%3A+%5Breplace+brackets+with+your+name%5D)

**For PM, Merge Team, or Tech Lead**
- [ ] See test [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931)
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/pre-work-template---design.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by LRenDO**
Fixes #4480 

### What changes did you make and why did you make them ?

  - Updated labels in    `.github/ISSUE_TEMPLATE/pre-work-template---design.md`
   from
   ```labels: 'Feature: Onboarding/Contributing.md, prework, role: design, size: 1pt'```
   to
   ```labels: ['Feature: Onboarding/Contributing.md', 'prework', 'role: design', 'size: 1pt', 'Complexity: Missing']```
  - Verified labels appeared correctly in the pre-work design template
  - Per the issue, this was done to avoid the GitHub bot taking off the labels when devs add them to issues.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>

  

</details>

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: [Updated Pre-work Design Template](https://github.com/LRenDO/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Crole%3A+design%2Csize%3A+1pt%2CComplexity%3A+Missing&projects=&template=pre-work-template---design.md&title=Pre-work+Checklist%3A+Designer%3A+%5Breplace+brackets+with+your+name%5D)

**For PM, Merge Team, or Tech Lead**
- [ ] See test [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931)
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Comment by one2code** [comment]
**ETA:** 6/2/23
**Availability** 8-10PM EST, 6/2/23

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @LRenDO thank you for working on this issue.  It looks good so far.  For the convenience of reviewers, please go to the issue and copy the section "Link for Reviewers" (along with the text/link) into this PR.  Thank you !

**Comment by blulady** [comment]
### Instructions for testing updated issue templates:
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [x] The response from the push command will include the URL for creating a pull request.  Copy/Paste the URL below for use after testing:  
[REPLACE THIS TEXT WITH URL FOR CREATING PR]
- [x] Browse to your fork of the website repository and click Settings 
<details><summary>Screenshot of Repository Settings</summary>

image

</details> 

- [x] Change the default branch to the new issue branch

<details><summary>Screenshot of Default Branch Setting</summary>

image

</details> 

- [x] Further down on the settings page under Features, check the Issues checkbox

<details><summary>Screenshot of Issues Checkbox</summary>

image

</details> 

- [x] Browse to the Issues page, then click Labels

<details><summary>Screenshot - creating labels in the test Repo</summary>

image

</details> 

- [x] Create labels corresponding to each label that was listed in the updated issue template.  The color of the labels don't have to match those on the `hackforla/website` repository, but the text of the labels must match exactly.  
- [x] From the Issues page, click `New Issue` then locate the template updated by your issue, and click `Get Started` to open the issue template. 
- [ ] Copy/Paste the URL of the issue template into the Resources section of the issue, replacing the text: [REPLACE THIS TEXT WITH URL OF THE ISSUE TEMPLATE ON THE TEST REPO]
 This will enable others to check the template.  
- [x] Verify that the labels listed in the issue all appear on the issue template.  If there is a discrepancy between the labels listed in the issue and the labels that appear on the issue template, ask a dev lead or merge team member for help.  
- [ ] If the labels listed in the issue match those listed on the issue template, complete the PR process by visiting the URL saved from the push command
- [ ] Copy these sections from the Issue into the PR 
  - [ ] "For PR Reviewers and Merge Team"
  - [ ] "Link for Reviewers"
  - [ ] "For PM, Merge Team, or Tech Lead"

**Comment by LRenDO** [comment]
> Hi @LRenDO thank you for working on this issue. It looks good so far. For the convenience of reviewers, please go to the issue and copy the section "Link for Reviewers" (along with the text/link) into this PR. Thank you !

Hi @roslynwythe! Whoops, looks like I was moving too quickly and didn't get the whole section when I copied. Should be fixed now. Thanks for catching that!

**Review by one2code — APPROVED** [review]
I've verified that the changes requested in issue #4767 have been correctly implemented in the `.github/ISSUE_TEMPLATE/pre-work-template---design.md` file. After following the testing instructions provided by @roslynwythe and @blulady, I was able to successfully add and implement the labels on the pre-work template --design when creating a new issue. 

I'm very impressed by the your attention to detail in your PR report. You took the time and effort to clearly state where file changes where taking place, and what file changes were being made. Furthermore, you quickly made requested changes to make the testing process easier. Excellent work!

**Review by roslynwythe — APPROVED** [review]
Thank you @LRenDO for great work on this issue.  Your code change is correct and clean, you completed the test procedure and displayed the test template URL, and created a well-formed Pull Request which describes your work.

**Pull request merged**
