### PR TITLE
Added github handle for Bonnie Wolfe in tdm-calculator.md

### LINKED ISSUE #7171: Add github-handle for Bonnie Wolfe in tdm-calculator.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tdm-calculator.md` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tdm-calculator

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by hkhaung**
Fixes #7171 

### What changes did you make?
  - added `github-handle` in `/_projects/tdm-calculator.md` for Bonnie Wolfe

### Why did you make the changes (we will use this info to test)?
  -  to hold the github handle which will eventually replace the github and picture variables, reducing redundancy in the project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No screenshots since adding a variable did not create any new visual change

### CODE REVIEW

**Comment by cchrizzle** [comment]
Hi @hkhaung, thank you for working on this!

The changes you've made look good:

1. You linked to the original issue.
2. You added the section of "github-handle" as requested.
3. You used spaces to indent as requested as well.
4. You specified that there are no screenshots.


Just a couple requests:
1. Specify who you made the changes for in both the title and the description of changes you made section (Bonnie Wolfe in this case).
2. Tie the reasoning for your changes into a bigger picture, higher level description of what the changes are meant to address. You can get this from the overview in the original issue, such as "reducing redundancy in the project file".
3. Specify the reasoning that you don't have any screenshots (no visual changes).

Once you have those everything should be good to go!

**Comment by Anahisv23** [comment]
Availability: M - F 12pm - 5pm
ETA: EOD

**Comment by hkhaung** [comment]
Hi @cchrizzle, I've updated the title and description as per your feedback. Let me know if there is anything else needed. Thanks.

**Review by Anahisv23 — APPROVED** [review]
Hi @hkhaung, thank you for working on this issue. Here's what you did well. Overall nice work!

What went well 
- Into and from branch are set up correctly 
- The linked issue links to the correct issue 
- Modified the appropriate lines of code to add the `github-variable`
- Did not indent with tab
- Fixed the PR itself to be more descriptive of the overall goal of the ticket

**Review by cchrizzle — APPROVED** [review]
Perfect, approved!

**Pull request merged**
