### PR TITLE
removed sdg-img-item class

### LINKED ISSUE #4422: Remove .sdg-img-item class from _project-page.scss
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The `.sdg-img-item` class in `_sass/components/_project-page.scss` is not used anywhere in the codebase. We need to remove this so that we don't have extraneous SCSS class that aren't being used to style any HTML.

### Action Items
- [x] Navigate to [ _sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)
- [x] Delete the lines 290 - 296

```
.sdg-img-item {
  text-align: center;
  padding: 30px 60px 10px;
  border-radius: 10px 10px 0px 0px;
  background: #02548B;
}
```

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4343
- [ _sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)
- [How to search across files in VS Code](https://code.visualstudio.com/docs/editor/codebasics#:~:text=VS%20Code%20allows%20you%20to%20quickly%20search%20over%20all%20files,each%20file%20and%20its%20location.)

### PR DESCRIPTION
**Pull request by kurikurichan**
Fixes #4422 

### What changes did you make and why did you make them ?

  - Removed lines 263-268 in the _project-page.scss file
  - That particular SCSS class is not being used anywhere in the site, which is why we removed it
  - My "good first issue"

### CODE REVIEW

**Comment by cmedina-dev** [comment]
Review ETA: 9:00 PM CST 4/15/23
Availability: Weekdays after 6:00 PM CST, Weekends flexible

**Review by cmedina-dev — APPROVED** [review]
Hi Krista! I read over your PR. Everything looks good! You made sure to link the issue and that the change originates from the feature branch, removed the requested lines of code, and stated the reason for the change. Only thing I might suggest in the future is avoiding the extra white space changes as they tend to clutter the PR. Other than that small suggestion, great job!

**Comment by drakenguyen4000** [comment]
ETA 4/14/23
Availability: M-F 3:30pm-8pm PST

**Review by drakenguyen4000 — APPROVED** [review]
Hi @kurikurichan, great job listing the changes you made and why you did them.  The PR is linked to its issue; however, please don't forget to move your PR to the Project Board.

Commit change approved!  Nicely done!

**Comment by roslynwythe** [comment]
Hi @kurikurichan please move the PR to the Project Board, and we will get it merged.  Thank you !

**Comment by kurikurichan** [comment]
Thank you!! I will do that now

**Comment by Adastros** [comment]
Hi @kurikurichan, one last thing! Could you add the same labels in issue #4422 on this pull request? The labels are usually automatically added by the github actions bot. It wasn't added this time since this pull request wasn't added to the project board on creation.

**Comment by kurikurichan** [comment]
Thanks @Adastros, I did that just now. For future reference, is there a way I should add the pull request to the project board on creation?

**Comment by Adastros** [comment]
Hi @kurikurichan, thanks for adding the labels! You can add the pull request before submitting it by clicking the gear icon as shown below.

image

Previously I mentioned adding the pull request to the project board before submitting but you can do it after or before. Thinking about it more, the labels probably weren't added automatically due to some changes to the project board that occurred around the time you submitted the pull request. Those changes caused some issues with the bots. You can check the details for this merge and see one of the errors for this pull request.

It also helps to double check the labels just in case the bots didn't add them.

Reference [this section](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board) of contributing.md for adding the pull request to the project board.

**Pull request merged**
