### PR TITLE
added github-handle to Kristelle Gumaru

### LINKED ISSUE #7180: Add github-handle for Kristelle Gumaru in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Kristelle Gumaru
```
with
```
- name: Kristelle Gumaru
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by purna-madala**
Fixes #7180

### What changes did you make?
  
  - added github-handle to Kristelle Gumaru in `_projects/home-unite-us.md` file

### Why did you make the changes (we will use this info to test)?
  
  - change made to streamline the project file by introducing a 'github-handle' key, which replaces the need for separate 'github' and 'picture' entries

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
- No visual changes to the website

### CODE REVIEW

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@purna-madala Thank you for taking on your first issue. The branch name looks good. The change looks good as well. The title is concise and clean. 
 
### Things that you need to change/check is: 

- [x] You need to check the "Checks section" and see why its not passing the "checked for link issue." 
- [x] You need to change the `Why did you make the changes (we will use this info to test)?` 
 you need to be specific on why you needed to make the change. The labels on the right side already indicate that this is your first issue. 
- Here is a reference on an issue if you are having any problems. https://github.com/hackforla/website/issues/7288

- [x] You also need to answer on the original issue. 
"Do let fellow developers know about your:-
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. ETA: (When do you expect this issue to be completed?)"

**Comment by DrAcula27** [comment]
**ETA**: Friday, September 13, 2024
**Availability**: weekdays after 2pm Pacific Time

**Comment by purna-madala** [comment]
Hi @codyyjxn I made the changes, could you review this again?

**Review by codyyjxn — APPROVED** [review]

**Review by DrAcula27 — APPROVED** [review]
@purna-madala Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7180 
- The correct file _projects/home-unite-us.md was edited
- No extra edits were made
- Spaces were used instead of tabs for indenting
- Appearance of the website is unchanged (Chrome and Firefox)
👍 Approved!

**Pull request merged**
