### PR TITLE
Refactored the donate.html page and deleted donate-card.html page

### LINKED ISSUE #4454: Refactor/Remove donate-card component
### Dependency

- [x] #4263 
- [x] #4439

### Overview

The large component `_includes/donate-card.html` has been replaced by smaller components so its elements will be moved into `pages/donate.html`, and the component ("include") file will be deleted. 

### Action Items

- [x] Open `_includes/donate-card.html` and `pages/donate.html`
- [x] In `pages/donate.html`, replace the line
```
{% include donate-card.html %}
```
with the contents of `pages/donate.html`
- [x] Delete the file `_includes/donate-card.html`
- [x] Use git to add and commit the change (deletion)
- [x] Using docker, confirm that the following website pages match the live web pages: 
   - [x] Donate Page: [docker](http://localhost:4000/donate) matches [live web page](https://hackforla.org/donate)
   - [x] Join Us Page: [docker](http://localhost:4000/join) matches [live web page](https://hackforla.org/join)
   - [x] About Us Page: (click to open the "Make a Donation" card) [docker](http://localhost:4000/about) matches [live web page](https://hackforla.org/about)

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
<details><summary>Donate</summary>
<p>
https://www.hackforla.org/donate/

https://github.com/hackforla/website/blob/gh-pages/pages/donate.html

screencapture-hackforla-org-donate-2024-01-22-18_09_16
</p>
</details> 

<details><summary>Join</summary>
<p>
https://hackforla.org/join

image

</p>
</details> 

<details><summary>About</summary>
<p>
https://hackforla.org/about

image

</p>
</details> 

- This issue is part of Epic #4492

### PR DESCRIPTION
**Pull request by heejung-hong**
Fixes #4454

### What changes did you make?
  - Replaced the {% include donate-card.html %} with the contents of donate-card.html.
  - Deleted donate-card.html page.

### Why did you make the changes (we will use this info to test)?
  - donation element is created to be reused across the site.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No applicable visual changes to website.

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: Evenings
ETA: EoD 2/9

**Comment by ajb176** [comment]
ETA: 24 hours

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #4454 was properly referenced. ✅ 
- Per the instructions on the original issue, the file `donate-card.html` was deleted and transferred to `donate.html` . ✅

**Review by ajb176 — APPROVED** [review]
Instructions were followed exactly as requested in the linked issue and there are no visual changes to the website, nice work @heejung-hong

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @heejung-hong Great job! 

Quick comment: I am comparing https://www.hackforla.org/donate/ with Docker in my repo http://localhost:4000/donate/ and it appears that some css/sass styling plus the emoticon are screwy- I only am seeing this on the Donate page; the other pages match live and Docker



donate
Thanks

**Comment by ajb176** [comment]
@t-will-gillis 

I'm not seeing any difference on Firefox/Safari. I do recall seeing that exact quirk when I was reviewing the PR initially on Firefox (can't remember which specific page), but after restarting Docker it looked the same and I couldn't replicate the issue.

**Review by t-will-gillis — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Hey @ajb176 thank you for the message, and @heejung-hong my bad! I deleted the cookies on my localhost and now everything looks correct. Confirmed in Docker on Chrome, Firefox, and Brave.

(Weird that only the 'Donate' page was affected in my localhost... )

**Comment by heejung-hong** [comment]
Thank you @ajb176 and @t-will-gillis for your review and communication!

**Pull request merged**
