### PR TITLE
Refactor `tools` data from string to list

### LINKED ISSUE #4813: Refactor Tools data for website.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Google Drive, Zoom, Google Analytics, 1Password
```
to:
```
  - Figma
  - Google Drive
  - Zoom
  - Google Analytics
  - 1Password
```
  - [x] Confirm that the tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by julialuongw**
Fixes #4813

### What changes did you make?
  - Changed the data for `tools` from a string to a list. More specifically, I changed it from comma-separated strings to a bulleted list with hypthens. 

### Why did you make the changes (we will use this info to test)?
  - This change is to contribute to the ongoing effort "to revise the filter menu in the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for 'Tools', so that we can see where we might need to move project values from tools to technologies, and vice versa." (quoted from the original issues page)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
</details>

<details>
<summary>Visuals after changes are applied</summary>
 image
</details>

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: EOD 7/26
Availability: After 5pm PDT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly, the requested changes were made to the code and the project card still looks good in Docker. You also gave a detailed description of the changes made in your pull request.

One note is that you don't have to include screenshots if there are no visual changes to the site. And also for future PRs, you do not need to manually move your PR to the 'PR Needs Review" column since it *should* be automated.

Other than that, great work with your first issue!

**Comment by LRenDO** [comment]
Hi @mademarc! Please add your ETA and Availability when you get a minute. Thanks!

**Comment by mademarc** [comment]
Review ETA: 7/27/2023
Availability: 7:22PM

**Review by mademarc — APPROVED** [review]
Hey @julialuongw mshirk2 Good work on the strings and @LRenDO  the ETA and Review is done.

**Review by adrianang — APPROVED** [review]
Hi @julialuongw — the branching is set up correctly, the corresponding issue is linked, and the requested change of making the tools for the Website project from a string into a list was made. When testing your branch on my local machine via Docker, the Website project page still looks the same as expected.

In addition to Richard's feedback with regards to screenshots and moving issues into columns, I would also say that it might be useful to indicate somewhere in your next PR onwards where/what file you had made a change(s) to, to make it easier for reviewers to understand where and what they should review.

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
