### PR TITLE
Update Sitemap Spelling 2465

### LINKED ISSUE #2465: Ensure consistent spelling of "Site Map" across the site
### Overview
We need to ensure "Site Map" is written consistently across the site as two words, vs one word so that we optimize our site for SEO and maintain professionalism across the site by sticking to consistent wording/spelling of terms.

### Action Items

- [x] Change spelling in footer to "Site Map". 
   - [x] Note: new footer design has correct spelling, but if it will be some time until that is developed and goes live, then the current footer should be updated to reflect the correct spelling. 
- [x] Change spelling of subheading on Site Map page so that both instances of this written on the page are consistent (as 2 words vs. 1)
  
Screen Shot 2021-11-08 at 6 28 35 PM

  

### Resources/Instructions
[Figma - Footer](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261)
[HfLA - Site Map page](https://www.hackforla.org/sitemap/)
[sitemap.html](https://github.com/hackforla/website/blob/gh-pages/pages/sitemap.html)
[footer.html](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html)

### PR DESCRIPTION
**Pull request by lindseyindev**
Fixes #2465

### What changes did you make and why did you make them?

  - updated site map spelling on /footer.html to "Site Map" for consistency
  - updated site map spelling on /sitemap.html to "Site Map" for consistency
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Footer: my update is on the left, current website on the right</summary>

image

</details>

<details>
<summary>Site map: my update is on the left, current website on the right</summary>
  
image

</details>

### CODE REVIEW

**Comment by lindseyindev** [comment]
FYI @ reviewers 
In the commit items, it's showing this:

lindseyindev and others added 3 commits 5 days ago
@lindseyindev
deleted .github/workflows/update-comment-on-update-label.yml
b011d1d

which is from this past issue I completed and was approved for merge before I started this issue.
https://github.com/hackforla/website/issues/2194
I'm not sure why it's showing on this pull request that I began after other than my local and remote fetches and merges were out of order.

If you have any questions reach out to me on slack @ Lindsey Dinkel

**Comment by JessicaLucindaCheng** [comment]
Review ETA: Monday, December 20, 2021

**Comment by JessicaLucindaCheng** [comment]
@lindseyindev I'm seeing two commits of "deleted .github/workflows/update-comment-on-update-label.yml". I think this could be a problem. 


<details>

<summary>Commit (id 1b023400064eb805668b3fa5f19ed94b071a486e) with pull request #2587</summary>

Associated with PR

</details>


<details>

<summary>Commit (id b011d1d8f62da7df1c09aa57af495648f3f608f1) without pull request number</summary>

No PR Number

</details>

**Comment by JessicaLucindaCheng** [comment]
> @lindseyindev I'm seeing two commits of "deleted .github/workflows/update-comment-on-update-label.yml". I think this could be a problem.
>
> Commit (id [1b02340](https://github.com/hackforla/website/commit/1b023400064eb805668b3fa5f19ed94b071a486e)) with pull request #2587
> Commit (id [b011d1d](https://github.com/hackforla/website/commit/b011d1d8f62da7df1c09aa57af495648f3f608f1)) without pull request number


@SAUMILDHANKAR and @R-Tomas-Gonzalez said it's okay at the Sunday, December 19, 2021 meeting when I asked. So, it's not a problem.

Explanation: Commit (id [1b02340](https://github.com/hackforla/website/commit/1b023400064eb805668b3fa5f19ed94b071a486e)) with pull request #2587 was merged into the Hack for LA repo by @macho-catt. Commit (id [b011d1d](https://github.com/hackforla/website/commit/b011d1d8f62da7df1c09aa57af495648f3f608f1)) without pull request number, I think, was from @lindseyindev merging the changes from delete-unused-GHA-2194 branch into lindseyindev's forked gh-pages and then the branch sitemap-spelling-2465 being based off of lindseyindev's forked gh-pages.

**Review by JessicaLucindaCheng — APPROVED** [review]
@lindseyindev Good job updating the spelling for site map in the subheading and footer!

@mergers I know there is commit id b011d1d8f62da7df1c09aa57af495648f3f608f1 and @SAUMILDHANKAR and @R-Tomas-Gonzalez said it is okay. (See previous comments for details.) Thus, I'm approving it as is.

**Comment by R-Tomas-Gonzalez** [comment]
> @lindseyindev Good job updating the spelling for site map in the subheading and footer!
> 
> @mergers I know there is commit id [b011d1d](https://github.com/hackforla/website/commit/b011d1d8f62da7df1c09aa57af495648f3f608f1) and @SAUMILDHANKAR and @R-Tomas-Gonzalez said it is okay. (See previous comments for details.) Thus, I'm approving it as is.

Thanks Jessica! Will wait on Miguel to finalize the merge.

**Review by lopezpedres — APPROVED** [review]
Hi @lindseyindev ! You did a great job here! Thank you @JessicaLucindaCheng for helping clarify that extra commit.

**Pull request merged**
