### PR TITLE
Renamed to blank-issue-form-with-dependency.yml

### LINKED ISSUE #3720: Update blank-issue-form.yml file name to blank-issue-form-with-dependency.yml
### Overview

We want to change the file name of `blank-issue-form.yml` to `blank-issue-form-with-dependency.yml` to clarify the purpose of the file. This will also make locating the file easier for future developers.

### Action Items

- [x] In the `.github/ISSUE_TEMPLATE/` folder, change the file name of `blank-issue-form.yml` to `blank-issue-form-with-dependency.yml`

### Testing Instructions
Check if the form works and displays correctly by
1. Pushing the changes to your remote forked repo's topic branch on GitHub
2. In your remote forked repo on GitHub, temporarily change the default branch from `gh-pages` to your topic branch. (See link in the Resources section for official documentation)
3. Check you have issues enabled in your forked repo by going to the `Settings` tab and then select `General` in the left menu. On the right side of your screen, scroll until you see the `Issues` checkbox under the `Features` section. Make sure the checkbox is checked. <details><summary>Click here to see what it looks like when issues are enabled in a repo</summary>
                image</details>
4. Open an issue within your repo to test out the form you just edited by going to the `Issues` tab and clicking the `New issue` button.
5. Select the `Getting Started` button for `Blank Issue Form with Dependency`<details><summary>Click here to see where the Getting Started button is for the Blank Issue with Dependency Form</summary>
Blank Form with Dependency Issue Selection View </details>
6. Test out the form and make sure everything functions as expected.
7. Remember to change your default branch back to `gh-pages` in your remote forked repo on GitHub.

### Resources
- [blank-issue-form.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml)
- [Github's documentation on how to change the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch)

### PR DESCRIPTION
**Pull request by angieyan**
Fixes #3720 

### What changes did you make and why did you make them ?

  - I changed the file name of blank-issue-form.yml to blank-issue-form-with-dependency.yml
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
no visual changes

### CODE REVIEW

**Comment by Adastros** [comment]
Availability (PST): 9 PM - 11:59 AM 06MAR23, 9 - 11PM 07MAR23
Review ETA (PST): 11:59AM 06MAR23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @angieyan thank you for working on the issue! A branch was accidentally created on the hack for la repository instead of on your local repository. Please create a branch on your repository with the updates and create a pull request from it. 

Once you create your branch and commit your changes, you can try seeing if you can edit this pull request to set the branches to look similar to the screenshot below. If that doesn't work, you create a new pull request and close this one. 

<details>
<summary>Pull Request Branch Screenshot</summary> 

image

</details>

[Link to creating a branch on your fork of the repository if needed](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue)

If you need any help, feel free to message anyone on the merge team.

**Comment by angieyan** [comment]
The reason that we have this issue, because of the fact I couldn't see .github folder through my terminal.
I changed the file name through visual studio. I would appreciate if you could help me to solve this issue. 
I will be available at 9-9:30 PM Mar 7, 23.

**Comment by Adastros** [comment]
@angieyan No worries, do you want to hop on a Slack call to troubleshoot right now?

**Comment by Adastros** [comment]
Closing this pull request because a new one was created. See pull request #4131. 

The branch was accidentally created on the hack for la repository and this pull request was trying to merge it.

**Pull request closed without merging**
