### PR TITLE
Edit note text in CONTRIBUTING.md at Sec 3.1.b.iv

### LINKED ISSUE #7139: Edits to `CONTRIBUTING.md` at Sec 3.1.b.iv part 3 of 3
### Overview
We want the instructions in the `CONTRIBUTING.md` file to read clearly and cover all relevant points so that there is no unnecessary ambiguity.

### Action Items
- [x] Open [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md). 
- [x] Go to Section 3.1.b.iv, which has the title `##### **iv. Complete pull request (4): Include images (if available)**`. Find the following line and replace: 
  
  ```
  **Note:** Not all pull requests will have significant changes to our website. **Please do not any screenshots of VSCode** If you do not have the ability to notate changes, please remove the `<details>/<summary` and replace it with an explanation for no images like:
  ```
 
  with:  
 
  ```
  **Note:** Not all pull requests will make visual changes to our website. **Please do not include screenshots from VSCode / other IDE**.  If your pull request does not make visual changes to our website, please remove the entire`<details>/<summary` section and replace it with a brief summary stating that there are no visual changes, for example:
  ```
  

- [x] Changes to `CONTRIBUTING.md` cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository. Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL, replacing "your github", "your repo", and "your branch" accordingly.
  ```
  https://github.com/{your github}/{your repo}/blob/{your branch}/CONTRIBUTING.md
  ```
   for example: 
  ```
  https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md
  ```
- [x] Create a pull request with your changes. In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
  ```
  For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
  ```

### Resources/Instructions
- This issue was initiated by #6929

### PR DESCRIPTION
**Pull request by mmcclanahan**
Fixes #7139 

### What changes did you make?
  - Edited the Note text located in Section 3.1.b.iv with the new text from this issue.

### Why did you make the changes (we will use this info to test)?
  - To reduce ambiguity and give simpler instructions on how to handle a PR that makes no visual changes to the website.
 
For Reviewers: Do not test changes locally, rather test changes at [test url](https://github.com/mmcclanahan/website/blob/update-Sec3.1.b.iv-7139/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to website. Changes to contributing.md.

### CODE REVIEW

**Review by Anahisv23 — COMMENTED** [review]
Hi @mmcclanahan, thanks for working on this issue! Here's what you did well and some feedback.

What went well 
- Into and from branch are correctly set up 
- Linked issue correctly links to the issue
- Good description of what you changed and why you changed it 
- Modified the old note to reflect the new note 

Feedback 
- I see you changed the old note to reflect the new note but I noticed you also removed some spaces from other lines of the CONTRIBUTING.md. Go ahead and remove those changes from your commit since they are not within the scope of this issue. After that your PR should be good to go. Let me know if you have questions.

**Comment by mmcclanahan** [comment]
@Anahisv23 Thank you for the review and catching the deletion of trailing white spaces! Disabled the setting in my vscode so it should't happen again. Just committed/pushed the fix. Thanks again!

**Review by Anahisv23 — APPROVED** [review]
Hey @mmcclanahan, yeah no problem! Thanks for fixing the trailing spaces issue. Approved!

**Review by jphamtv — APPROVED** [review]
Hi @mmcclanahan,
- You created the pull request using the correct branch
- The issue is properly linked 
- Your summary of changes is clear 
- You provided a test URL for reviewers
- Your code change is clean and accurate

Thanks for your contribution to resolving this issue!

**Pull request merged**
