### PR TITLE
Updated value for alt text for the voices neighborhood img

### LINKED ISSUE #3105: Change alt text for voices neighborhood council image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the voices neighborhood council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 54](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L54) for the alt text:

from
```
<img class="org-img" src="/assets/images/citizen-engagement/voices_neighborhood_council.svg" alt="voices of neighborhood council logo">
```
to
```
<img class="org-img" src="/assets/images/citizen-engagement/voices_neighborhood_council.svg" alt="Voices Neighborhood Council">
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L54

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by geedtd**
Fixes #3105

### What changes did you make and why did you make them ?

  -changed line #54 on the assets/pages/citizen engagement to reflect requested format that adheres to WCAG

### CODE REVIEW

**Comment by answebdev** [comment]
ETA: 5/20/2022 (end of day)
Availability: 2 hours

**Review by answebdev — APPROVED** [review]
Thank you for submitting your PR. @geedtd For this issue, the alt text in `pages/citizen-engagement.html` (line 54) needed to be changed, which I can see that you did. I was also able to see this change locally in the dev tools. Great job with that!

Also, please be sure to add this PR to the Project Board. Thank you.

**Comment by geedtd** [comment]
@answebdev sorry about that, I added it to the Project Board. Thanks for the review!

**Comment by answebdev** [comment]
@geedtd No problem. Thank you for adding it to the Project Board.

**Comment by harshitasao** [comment]
Availability: 1 hour 
Review ETA: 21/05/2022

**Review by harshitasao — APPROVED** [review]
Excellent work @geedtd. Changes look good to me.

**Pull request merged**
