### PR TITLE
changed p- tags to h4-tags

### LINKED ISSUE #2953: Add h tags to Getting Started page (Steps 4-5)
### Overview
As a developer, I need to replace p tags with h tags on the headings of [Getting Started page](https://www.hackforla.org/getting-started) (Steps 4-5) so it becomes WCAG compliant

### Action Items
- [x] Review [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [x] In line 166, change the p tag to an appropriate h tag: https://github.com/hackforla/website/blob/96f02c4a8446f615741c881d823b94619738a708/pages/getting-started.html#L166
- [x] In line 201, change the p tag to an appropriate h tag:
https://github.com/hackforla/website/blob/96f02c4a8446f615741c881d823b94619738a708/pages/getting-started.html#L201
- [x] Ensure h tags (h1, h2, h3 etc.) reflect the correct hierarchy of the page for screen readers
- [x] Make sure the [Getting started page](https://www.hackforla.org/getting-started) still looks the same.

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)
- [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [Headings in Page Structure Tutorial](https://www.w3.org/WAI/tutorials/page-structure/headings/)
- [WCAG guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)
- Related issue #2952

### PR DESCRIPTION
**Pull request by Olanrewaju-Ak**
Fixes #2953 

### What changes did you make and why did you make them ?

  - changed p tag to h4 tags for correct hierarchy of the page
  -
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
@Olanrewaju-Ak Just wanted to let you know that I have removed the reviewers from your PR. Please do not add reviewers to your PR as we don't know if they are available. Generally, we assign reviewers during team meetings, or if someone is available, they can add themselves. Thank you.

**Comment by JessicaLucindaCheng** [comment]
Not sure why labels aren't added but I will add them now so it is easy to see info about the pr quickly by looking at the labels.

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/12
Availability: 1 hours

**Comment by usaboo** [comment]
ETA: EoD Thursday, 12th May, 22
Availability: Wednesday 11PM EST - 12AM EST

**Comment by Jaretzbalba** [comment]
@Olanrewaju-Ak I noticed that this PR is being merged into the hackforla:2953-add-h-tags-to-getting-started-page-steps-4-5 branch. The correct branch is the hackforla:gh-pages branch.  I would double check with the contributing.md to make sure you set up your local repository and remote upstream correctly.

**Comment by SAUMILDHANKAR** [comment]
@Olanrewaju-Ak I noticed that you haven't followed the progression in which the issues should be worked on, i.e., good first issue, good second issue, small, medium, large. Also, as Jaret mentioned above the branches aren't correct. Therefore, would request you to close this PR, unassign from the corresponding issue and move it back to new issue approval column so it can be reprioritized. Then, please pick up your good first issue from the top of prioritized backlog column, you can use the following link which has filters applied to it: https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22+label%3A%22good+first+issue%22. Thanks.

**Comment by Olanrewaju-Ak** [comment]
@SAUMILDHANKAR @Jaretzbalba  thank you for the feedback. I’ll pick another first issue and be careful to follow the instructions. My Apologies

**Pull request closed without merging**
