### PR TITLE
Remove Richard Kwang from HFLA website leadership

### LINKED ISSUE #6259: Update Project Profile: remove Richard Kwang from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Richard Kwang
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U04U531MS5P
      github: https://github.com/kwangric
    picture: https://avatars.githubusercontent.com/kwangric
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by vincendp**
Fixes #6259 

### What changes did you make?
  - I removed Richard Kwang from the HFLA website leadership

### Why did you make the changes (we will use this info to test)?
  - The Hackforla.org Website project page needs to be updated to remove Richard Kwang from the leadership section.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2024-03-01 at 12 06 35 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2024-03-01 at 12 07 27 PM

</details>

### CODE REVIEW

**Review by heejung-hong — DISMISSED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, tablet, and mobile view), Firefox, and Safari browser.

Going forward for the "Why did you make the changes" section, instead of referring to the original issue number, please indicate in writing why the changes were made.  The reason for the change is indicated in the overview section of the original issue.

Thank you

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @vincendp - it looks like your branch has a conflict that needs to be resolved. After you update your branch, please re-request reviews by clicking on the circular arrows icon next to reviewers name. Thanks! 

[Dealing with merge conflicts](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31d-dealing-with-merge-conflicts)

**Comment by vincendp** [comment]
I updated the _**Why did you make the changes**_ section to be more descriptive. I also dealt with the merge conflict and updated the _**Screenshots of Proposed Changes Of The Website**_ section accordingly

**Review by jphamtv — DISMISSED** [review]
Great work on this @vincendp. Thanks for resolving the conflict and making updates to the summary of changes for clarity. Your code change is clean and accurate. PR approved

**Review by t-will-gillis — APPROVED** [review]
Hey @vincendp Thanks for working with @heejung-hong and @jphamtv to pick up their comments and resolve the previous merge conflict.

A new merge conflict popped up, but I made the changes for that one so you can move on to a new issue. Thanks for your work!

I will go ahead and merge this since the Heejung and J previously approved it.

**Pull request merged**
