### PR TITLE
Remove trailing slash from <img> tag in Getting Started page

### LINKED ISSUE #4396: img Tag Refactor: Getting Started page - `CoP lead... info-icon information.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
and Gmail address to a CoP lead. <img class="info-icon" src="assets/images/getting-started/information.png" alt="" />
```
to
```
and Gmail address to a CoP lead. <img class="info-icon" src="assets/images/getting-started/information.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by cmedina-dev**
Fixes #4396 

### What changes did you make and why did you make them ?

  - Removed the trailing slash from the first information HTML \ tag to ensure consistency of \ tags across the website.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
(No visual changes)

### CODE REVIEW

**Comment by mademarc** [comment]
Review ETA: 4/13/2023
Availability: 7PM Monday

**Review by mademarc — APPROVED** [review]
Hey @cjmedina95  you have remove that / on that alt to make the code better so well done.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @cjmedina95, good job on completing the issue! Could you check off the boxes in issue #4396? This is so reviewers know what has been completed and what needs to be completed for an issue. Some issues require that we revisit them in the future so having the check boxes marked off lets us know where to resume working on the issue.

**Comment by cmedina-dev** [comment]
Should be done, thanks @Adastros!

**Comment by angieyan** [comment]
Review ETA: 4/18/2023
Availability: 1-3 PM

**Review by angieyan — APPROVED** [review]
Good job, @cjmedina95. Everything looks good.

**Review by Adastros — APPROVED** [review]
Hi @cjmedina95, thanks for checking the boxes on the issue! Everything looks good

**Pull request merged**
