### PR TITLE
 Update alt text for the Shared Housing Project image

### LINKED ISSUE #4043: Shared Housing Project: Update alt text for the Shared Housing Project image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Shared Housing Project image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/shared-housing-project.md`:

**From:**
```
alt: 'Linked arms'
```
**To:**
```
alt: 'Shared Housing Project'
```
**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Project is not currently visible on the live site so you will not be able to see it

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/shared-housing-project.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/shared-housing-project.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by jeristella**
Fixes #4043

### What changes did you make and why did you make them ?

  - Updated alt text to "Shared Housing Project" 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Suman2795** [comment]
ETA: 5 mar 2023
Availability : 2 hours

**Comment by blulady** [comment]
@jeristella I see that you have multiple PR's in the queue, I appreciate your enthusiasm but I wanted to gently remind you that you should only have on PR up at a time. While you are waiting,  you can help speed the PR process by review other people's pull requests.

**Comment by vmaineng** [comment]
Availability: 3/6/2023 3-6pm PST
ETA: 2 hours

**Review by vmaineng — APPROVED** [review]
Hey @jeristella! Great job on updating the alt tag! The code is DRY and it is correctly merging into the right branch. Everything looks great!

**Comment by jeristella** [comment]
> Hey @jeristella! Great job on updating the alt tag! The code is DRY and it is correctly merging into the right branch. Everything looks great!

Thank you Mai!

**Pull request merged**
