### PR TITLE
Added a meeting description to projects page

### LINKED ISSUE #6930: Update Project Info Page to show Meeting Description
### Overview
We need to add meeting description to the Project Info pages to keep users informed of the meeting frequency.

### Action Items
- [x] Analyze and understand the data in `_data/external/vrms_data.json`
- [x] Make changes to `project.js` to show the meeting description on the Project Info page.
- [x] Using Docker, check the website on your local machine.

### Resources/Instructions
- [Project Info Page for LA TDM Calculator](https://www.hackforla.org/projects/tdm-calculator)
- [JSON Data File](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
- [Js File](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
- Refer to the [Project Meetings Page](https://www.hackforla.org/project-meetings ) that shows all the meeting data
- Note: The data for Project Info pages should be coming from the above mentioned JSON data file and not from the VRMS API.

### PR DESCRIPTION
**Pull request by lukewangm**
Fixes #6930

### What changes did you make?
  - Added const meetingDescription = event.description;
  - Added meetingDescription to the meetings list
 
 

### Why did you make the changes (we will use this info to test)?
  - The meeting frequency is not detailed enough without the meeting description
 
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

old

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
new

</details>

### CODE REVIEW

**Comment by aidanwsimmons** [comment]
Availability: weekday evenings
ETA: Thursday EOD

**Review by aidanwsimmons — DISMISSED** [review]
Hey Luke, 

- issue linked
- branches look good
- clear and concise descriptions for changes and reason for implementing
- changes look good, and added description text appears on my end as well

Great job! approved

**Comment by jphamtv** [comment]
Hey @lukewangm, it looks like the labels from the automation for transferring labels didn't transfer when you created this PR. Can you please add those labels manually? 

Also, your branch has conflicts that need to be resolved before it can be merged. Here's the wiki guide for guidance on how to resolve conflicts: [How to Resolve Merge Conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts)

Thanks!

**Comment by terrencejihoonjung** [comment]
Review ETA: 6/17/24, 11:59pm PST
Availability: 7pm - 12am PST, everyday

**Review by terrencejihoonjung — APPROVED** [review]
Hey @lukewangm,

- meeting description is correctly added to each meeting
- visual changes look good
- changes made and why they were made are clearly stated 
- comment describing the changes are a plus! 
- branches are correctly specified

Good work! Thanks :)

**Comment by ha-bach** [comment]
Review ETA: in 2 days
Availability: Wednesday, Thursday evening

**Review by ha-bach — APPROVED** [review]
Hi @lukewangm 
- Branching looks good
- Appropriate linked issue
- Brief description of what and why changes are provided
- Code edit is clean
- Changes displayed correctly on my browser for both mobile and desktop views 

Overall great contribution! Thank you for your work. I am approving the PR.

**Pull request merged**
