### PR TITLE
Updated tools section of metro-ontime.md by removing Docker, and changed format from string to list.

### LINKED ISSUE #4810: Refactor Tools data for metro-ontime.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [metro-ontime.md](https://github.com/hackforla/website/blob/gh-pages/_projects/metro-ontime.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Docker, AWS, Observable
```
to:
```
tools:
  - AWS
  - Observable
```
Do not include docker even though it is in the current tools list, because it is actually categorized under languages, which is delivered by pulling the language for a repo from the GitHub API.
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by joelfuelling**
Fixes #4810

Reviewers: I'm assigning all 3 of you since you've been helping with this since my initial push attempt.

After talking to Ren (thanks again!)  I just reforked and following the correct procedure, this is the corrected push with ONLY the changes to the metro-ontime.md file per the instructions. My VScode no longer auto formats, or alters .vscode/settings.json files like it did with my initial attempt. I've included a screen shot at the bottom of this comment of the closed pull attempts from the project board.

### What changes did you make?
  - Updated tools section of metro-ontime.md from...
  "tools: Docker, AWS, Observable", to...
  "tools: 
     - AWS 
     - Observable"

### Why did you make the changes (we will use this info to test)?
  - The filter menu on the projects-check page needs a dropdown so we can check what project categories need moved from tools to technologies (This is just some context for why this assignment is needed)
    - The "tools" data in the metro-ontime.md must be formatted as a list, as it is now, rather than strings so it will work with the new projects-check page dropdown.
  - Docker is in the technologies category pulled from a separate Github API and is no longer needed in tools.

### Screenshots of Proposed Changes Of The Website  
<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-08-09 at 12 49 45 PM

Screenshot 2023-08-09 at 12 36 38 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-08-09 at 12 43 02 PM

Screenshot 2023-07-31 at 4 24 05 PM

</details>

### Screenshot of closed branches from project pages.
Screenshot 2023-08-10 at 4 04 26 PM

### CODE REVIEW

**Review by LRenDO — APPROVED** [review]
Hi @joelfuelling! 

Thanks for sticking with it to get the formatting and missing directory sorted out!

You did a great job with 
- Branching correctly
- Linking the issue
- Making the correct changes
- Looping the original reviewers into the new PR
- Showing the closed PRs

I have a few non-functional requests
- The `![image]` before the images and the `)` after images can be deleted. This is unnecessary because when you drag and drop or copy into the comment field GitHub automatically format the markdown text with the file name as the alt text. It's also good idea to make sure the alt description between the brackets to be descriptive of the image itself.
- For the why changes were made section, I would also add something that includes the reasoning for changing the tools from a string to a list which is included in the issue's Overview section. 
- In the future, it's a good idea to separate out the PR info related to the fix for the issue from any explanation about the PR process itself.  In other words, only the information to fill out the PR template would be in the initial opening PR comment.  Other comments about the other PRs can be placed in a separate comment after the PR is created, so that it is easy and clear for the reviewers to understand the issue and it's solution.

Thanks again for your time, persistence, and contribution!

**Comment by one2code** [comment]
**ETA:** 8/12/23

**Review by one2code — APPROVED** [review]
@joelfuelling Good job on addressing the requested changes in the `projects/metro-ontime.md` file. For future pull request's, I advise taking the time to click the preview tab at the top, to the right of the write tab, to see what the submitted pull request will look like. That way, if there are any tags that are not closed/utilized, you will see it right away. This will help with readability.

**Comment by joelfuelling** [comment]
> @joelfuelling Good job on addressing the requested changes in the `projects/metro-ontime.md` file. For future pull request's, I advise taking the time to click the preview tab at the top, to the right of the write tab, to see what the submitted pull request will look like. That way, if there are any tags that are not closed/utilized, you will see it right away. This will help with readability.

Hi, Travis. That is a wonderful piece of advice, thank you!

**Pull request merged**
