### PR TITLE
Update project description pages

### LINKED ISSUE #1794: Update Project Description pages
### Overview
We need to remove the "Getting Started" page card from the Project Description pages, and instead move the "Getting Started" resource card to the end of the Resources page card, because the Getting Started card is currently redundant and unnecessary. PM's agreed about this at their Community of Practice meeting.

### Action Items
- [ ] Remove 'Getting Started' page card from the project description pages
- [ ] Add the 'Getting Started' resource card to the end of the Resources page card section
   - [ ] The 'Getting Started' resource card should always automatically be there on project description pages
- [ ] Make sure that the markdown that automatically adds these resource cards doesn't get negatively affected by these changes

### Resources/Instructions
[Example of a project description page](https://www.hackforla.org/projects/100-automations)

Screen Shot 2021-06-20 at 1 04 13 AM

### PR DESCRIPTION
**Pull request by aalieu**
Fixes #1794

### What changes did you make and why did you make them ?

  -Removed 'Getting Started' section and all the cards and buttons associated with it since there was a lot of redundancy.
  -Moved 'Getting Started' card into the 'Resources' section to keep everything in one section.
  -Removed 'Getting Started' link from the 'Open Community Survey' project file since it was creating a duplicate 'Getting Started' card.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Desktop View Before
Mobile View Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Desktop View
Mobile View

</details>

### CODE REVIEW

**Review by arghmatey — CHANGES_REQUESTED** [review]
Looks good so far! You did a great job reaching out for clarification and more information. Before merging - I've requested a change for the open-community-survey.md file, and there is currently a conflict on the PR that needs to be resolved.

**Comment by aalieu** [comment]
@arghmatey 

Thanks for the review! I've resolved the conflict in the open-community-survey.md file and updated my pull request. Please let me know if there are any other problems!

**Review by erikaBell — APPROVED** [review]
great, thanks for resolving that @aalieu.

lgtm ~

**Review by arghmatey — APPROVED** [review]
Nicely done, @aalieu! Thanks for resolving those so quickly!

**Pull request merged**
