### PR TITLE
Added Marlena Mellody Khim Sai to the LA TDM Calculator leadership page

### LINKED ISSUE #7649: Update Project Profile: LA TDM Calculator Add Marlena Mellody Khim-Sai
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Marlena Mellody Khim-Sai
    github-handle: marlenamellody
    role: UX Design Lead
    links:
      slack: https://hackforla.slack.com/team/U06DSRCSXRD
      github: https://github.com/marlenamellody
    picture: https://avatars.githubusercontent.com/marlenamellody
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by mchait18**
Fixes #7649

### What changes did you make?
  
  - I added Marlena Mellody Khim Sai to the leadership page on LA TDM Calculator
  
### Why did you make the changes (we will use this info to test)?
  
  - The leadership page for the LA TDM Calculator project was outdated and needs to be up-to-date.
  
<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

before 7649
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after 7649

</details>

### CODE REVIEW

**Comment by theogguu** [comment]
Review ETA: EOD Sunday(11/10)
Availability: M > F

**Review by theogguu — APPROVED** [review]
Hi @mchait18, thanks for taking this issue!

- the PR contains the correct branch
- issue is correctly linked
- changes are verified across browsers (firefox, edge, chrome)
- code changes are accurate and concise
- no other notable issues

Great job!

**Review by codyyjxn — APPROVED** [review]
@mchait18  , thank you for taking this issue. 

## What went well: 
- The branch name is correct 
- The before and after screenshots are great! 
- The description is really clear and concise makes it easy for anyone to understand what was done. 

## Some suggestions 
- On the original issue you need to respond to the Bot in the comments below
- You also need to change the original issue label from `Prioritized backlog` to `In progress`


Great Job , Keep it up!

**Comment by mchait18** [comment]
Thanks. What do you mean by the "original issue" in terms of responding to the bot and changing the label?

**Comment by siyunfeng** [comment]
> Thanks. What do you mean by the "original issue" in terms of responding to the bot and changing the label?

Hi @mchait18 , the original issue is the one you mentioned in your PR (**Fix #issue number**). 

- In your case, it is #7649 
- Follow the steps in section [2.4 Claiming an Issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#24-claiming-an-issue) to assign yourself issues

**Comment by mchait18** [comment]
Got it. Thanks. Do you know when this will be merged so that I can start my next issue?

**Comment by jphamtv** [comment]
Hi @mchait18 - Thanks for your contribution. Reminder to finish the remaining action items listed in the issue now that this PR is merged.

**Pull request merged**
