### PR TITLE
Update Image Tag in Events Page

### LINKED ISSUE #5267: img Tag Refactor: _includes/events-page/our-locations-content.html - DTLA.png
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/our-locations-content.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="location-image" src="../assets/images/hack-nights/DTLA.png" alt="Downtown L.A." />
```
to
```
<img class="location-image" src="../assets/images/hack-nights/DTLA.png" alt="Downtown L.A.">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/our-locations-content.html
2. Webpage(s): https://www.hackforla.org/events/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by DomenicScozz**
Fixes #5267

### What changes did you make?
  - The change involves using a self-closing img tag without a trailing slash.

### Why did you make the changes (we will use this info to test)?
  - I implemented this alteration to enhance the uniformity of the codebase.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
I removed the ending slash from the image tag, but there were no visual changes as a result.

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 8/23/23
Availability: Weekday evenings

**Comment by ha-bach** [comment]
Review ETA: in 3 days.
Availability: anytime.

**Comment by homeroochoa47** [comment]
ETA: 8/24/23
Availability: Weekdays after 5

**Comment by LRenDO** [comment]
Hi @k-rewd! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availablity.  Thanks!

**Review by pdimaano — APPROVED** [review]
@DomenicScozz Good job: The branches are correct and the issue is linked. The website appearance remains the same on my system with desktop, mobile and tablet. The correct file was modified and the appropriate ending slash was removed. Well done!

**Review by homeroochoa47 — APPROVED** [review]
What's up, @DomenicScozz ! Everything looks great to me.
- The branches were set up correctly. 
- The ending slash was removed without any visual changes locally as expected.
Nice work!

**Comment by k-rewd** [comment]
Looks good! Slash has been removed per instructions. Branches are set up correctly. Page still running as it should. Well done!

**Review by k-rewd — APPROVED** [review]
Looks good! Slash has been removed per instructions. Branches are set up correctly. Page still running as it should. Well done!

**Review by ha-bach — APPROVED** [review]
The changes look good!

The correct branches are used. There is a linked issue. The page looks good on my location machine on desktop and mobile mode. The code changed looks good as well!

Good work!

**Review by adrianang — APPROVED** [review]
Hi @DomenicScozz — the branching was set up correctly, the corresponding issue was linked. the requested change of removing the ending slash on the image tag in line 7 was made, and it doesn't affect the Events Page when I test your branch on my local environment.

One thing I did notice was that a whitespace character was removed on line 15; this is a cosmetic change that I'll let slide, but you may want to check your linter (if you're using one) that its rules don't make unknowing changes to files. Ideally, the only change should have been on line 7. It isn't so much an issue now for simple issues like this one, but could be troublesome to work with on later issues that touch on more files.

I appreciate the bit of time you took to write out the What and Why of your PR, as well as noting the detail of removing the `<summary>` and `<details>` tags from the Screenshots section!

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
