### PR TITLE
update-alt-text-100-automations-3868

### LINKED ISSUE #3868: 100 Automations: Update alt text for 100 Automations image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text for the `100 Automations` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the alt value within `_projects/100-automations.md`:

**From:**
```
alt: '100 Automations logo depicted as a 1 and two intermeshed gears surrounded by a open left bracket, forward slash and closing right bracket to indicate the 100 automations are in code, followed by the word Automations.'
```

**To:**
```
alt: '100 Automations'
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  100 Automations Page: https://www.hackforla.org/projects/100-automations

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/100-automations.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by adevlinb**
Fixes #3868

### What changes did you make and why did you make them ?
In: ./_project/100automations.md

  **Why:** Image alt property not in proper format to be WCAG compliance.
  **Previously:** alt="alt: '100 Automations logo depicted as a 1 and two intermeshed gears surrounded by a open left bracket, forward slash and closing right bracket to indicate the 100 automations are in code, followed by the word Automations.'"
  **Updated:** alt="100 Automations"

**NOTE**... not sure if this is an issue... I checked localhost:4000 && the hackforla website.. did not see the alt property in either location. This specific .png is referenced in the head of the page in a meta element. I did not see the alt property for this png used anywhere. While the .md file did have the information requesting change for this issue, it is not reflected (to my knowledge) on the actual website / in the browser / UI. I have included two screen shots below. One from localhost:4000 and one from the hack4la website.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by RyanGehris — APPROVED** [review]
Good job completing this issue. Your update of the alt text to comply with WCAG standards was successfully shown when inspecting the website on my local computer. I have attached before and after photos for you to see. 

<details>
<summary>Before</summary>
Screenshot 2023-03-28 at 4 38 49 PM

</details>

<details>
<summary>After</summary>
Screenshot 2023-03-28 at 4 38 18 PM

</details>

**Comment by RyanGehris** [comment]
@adevlinb I am commenting the images again because I was not able to view them in my last comment. Let me know if you can see the screenshots. You can see this when inspecting the 100 Automations project card at the following addresses:

https://www.hackforla.org/#
https://www.hackforla.org/projects/

<details>
<summary>Before</summary>

Screenshot 2023-03-28 at 4 38 49 PM

</details>

<details>
<summary>After</summary>

Screenshot 2023-03-28 at 4 38 18 PM


</details>

I also examined the image within the header on the [100 Automations Project Page](https://www.hackforla.org/projects/100-automations) and found that the 100-automations-hero.png is added as a background property to the header element, which would imply that it is decorative. Decorative images do not require alt text because they do not add meaning to the page. Based on that, my understanding is that you would not see the alt attribute in the header. If the hero image within the header does add meaning to the page, there should be an img element nested inside the header element and the img element should contain an alt attribute. 

It could be a good idea to ask the leadership team if there should be an alt attribute for the header. In the file assets/js/project.js between lines 31-38, you could potentially add a child element to the header with the image and alt text instead of adding a background. I haven't tried, but would seem like a reasonable alternative in the future.

<details>

<summary>Screenshot of inspected header</summary>

Screenshot 2023-03-28 at 5 23 24 PM


</details>

The 100-Automations image is also used for the Readme and Overview links under resources. I determined that the alt text '100 Automations' is not used here because in resource-card.html on line 14, the alt text is specified as 'project' when the projects image is used. 

<details>
<summary>Screenshot of inspected links in resources</summary>

Screenshot 2023-03-28 at 5 38 49 PM


</details>

**Comment by janice87** [comment]
Review ETA: 9PM 3/31/22
Availability: 6-9 PM Wed - Fri

**Comment by adevlinb** [comment]
Thank you @RyanGehris !! Exactly the explanation I needed!! Thank you, thank you!! And, YES -> I was able to see your images in the last comment!

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. I can also confirm that I see the alt text was updated under projects showing "100 Automations".  
@adevlinb Great job on being so detailed and thorough with this issue!

Screenshot of change on my local computer:
pr-1



@RyanGehris thank you for the explanation, screenshots and the info on decorative images vs backgrounds!

**Pull request merged**
