### PR TITLE
Update Project Profile: Hackforla.org Website to correct leadership order

### LINKED ISSUE #4358: Update Project Profile: Hackforla.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that leadership is in the correct order. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
  - [x] Move the information for Justin Dingeman so that it is between Bonnie Wolfe and Sarah Sanger
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- ER associated with this issue: https://github.com/hackforla/website/issues/4285
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by cng008**
Fixes #4358

### What changes did you make and why did you make them ?

  - Move the information for Justin Dingeman so that it is between Bonnie Wolfe and Sarah Sanger so that leadership is in the correct order

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by mjh-projects** [comment]
Review ETA: 10 PM 4/6/23
Availability: After 5:30  PM Thursday - Saturday

**Comment by mjshelton12** [comment]
Review ETA: End of day 4/5
Availability: 4/5 10-11pm

**Review by mjshelton12 — APPROVED** [review]
Great work, cng008! You did a great job creating this PR - The branches are correctly done, your explanation of what you did is clear and easy to understand the what and why, and your code is clean and effective.

In terms of testing the website - The visuals are correct in desktop, tablet, and phone views and all links still work as expected.

Nice, clean work!

**Review by jdingeman — APPROVED** [review]
Hi @cng008, looks good! Nice job.

**Pull request merged**
