### PR TITLE
Updated element tag on the Events webpage

### LINKED ISSUE #6633: Change paragraph from <h2> to <p> on header-container-content.html
### Overview

In `_includes/events-page/header-container-content.html`, the paragraph in the header section is an `<h2>` header but should be a `<p>` HTML element. Using the correct element helps browsers and assistive technologies understand the structure of the content, which is important for accessibility according to the W3C accessibility guidelines.

### Details

https://github.com/hackforla/website/blob/3a5c1479d7a51730fa39a2aeab2e5c2435f7b42d/_includes/events-page/header-container-content.html#L5-L9

### Action Items

- [x] Change the `<h2>` tag to a `<p>` tag on the Events webpage
- [x] Review the changes in the browser to confirm no bugs were introduced (see [instructions](https://github.com/hackforla/website/wiki/How-to-review-Pull-Requests#Step3))
- [x] Push your changes to your private branch and submit a pull request

### Resources/Instructions

- [Events page](https://www.hackforla.org/events/)
  - [pages/events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html) 
    - [_includes/events-page/header-container-content.html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html)
- [W3C Web Accessibility Initiative: Page Structure](https://www.w3.org/WAI/tutorials/page-structure/)

### PR DESCRIPTION
**Pull request by luisitocanlas**
Fixes #6633 

### What changes did you make?
  - Updated the element tag from `<h2>` to `<p>` for lines 5 to 9.

### Why did you make the changes (we will use this info to test)?
  - Using the correct element helps browsers and assistive technologies understand the structure of the content, which is important for accessibility according to the W3C accessibility guidelines.

### CODE REVIEW

**Comment by urvishp13** [comment]
Review ETA: 3pm 5/2/24
Availability: 12pm - 3pm 5/2/24

**Comment by ramitaarora** [comment]
Review ETA: April 30 EOD
Availability: 9am-12pm Weekdays

**Review by ramitaarora — APPROVED** [review]
Hey! This looks good:
- issue is linked correctly and merging from proper branch
- changes are made correctly from h2 tag to p tag

Thank you! :)

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 4/30/24

**Review by Thinking-Panda — APPROVED** [review]
@luisitocanlas Thank you for working on this issue. Merge branch is setup correct, code changes are as mentioned in the issue and clean. Well done. Approved!

**Comment by Thinking-Panda** [comment]
@urvishp13, thank you for assigning yourself to review this PR. As it is time sensitive, I am going ahead and merging it. Thanks for understanding.

**Pull request merged**
