### PR TITLE
Add GitHub handle for Charlotte Soestini

### LINKED ISSUE #6938: Add github-handle for Charlotte Soestini in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Charlotte Soestini
```
with
```
- name: Charlotte Soestini
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by handshek**
Fixes #6938

### What changes did you make?
  -	Added  `github-handle:` for Charlotte Soestini:

### Why did you make the changes (we will use this info to test)?
  - Create a single variable `github-handle` for each member of the leadership team to reduce redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes.

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 6/13/24
Availability: Weekday evenings

**Review by mSharifHub — DISMISSED** [review]
you should add the name next to the github-handle like a key:value  with no "" for example github-handle: msharifHub

**Comment by handshek** [comment]
> you should add the name next to the github-handle like a key:value with no "" for example github-handle: msharifHub

Sorry, but I don't think that's correct. According to [this comment](https://github.com/hackforla/website/pull/6916#pullrequestreview-2106538074) the intent is to add a new line with the variable `github-handle` and that's it.

Kindly read the instructions on the [issue](https://github.com/hackforla/website/issues/6938) before reviewing.

**Comment by ino-iosdev** [comment]
> you should add the name next to the github-handle like a key:value  with no "" for example github-handle: msharifHub

@mSharifHub This is incorrect information, we had you revise yours to NOT include the name after `github-handle:` see example #6917, and please note that you are not supposed to do any PR review until your first PR has been approved and eventually merged. I dismissed your change request, could you please unassign yourself from your end? Thank you!

@buneeIsSlo You are good, no need to make changes on that. Thank you.

**Comment by ino-iosdev** [comment]
ETA: EoD

**Comment by ino-iosdev** [comment]
> you should add the name next to the github-handle like a key:value with no "" for example github-handle: msharifHub

**Comment by t-will-gillis** [comment]
Hey @buneeIsSlo You are correct.  

So there is no ambiguity: The issue specifies that **_only_** the text `github-handle:` should be added, and your code edits are correct.

**Review by ino-iosdev — APPROVED** [review]
Hi @buneeIsSlo  , It's such a blessing to have you as part of the team here!
 
- Branch naming was appropriate
- Direction between branches `from` and `to` are clear
- The changes and why were clear
- PR issue ticket was properly linked
- No visual changes to the website
 
Great job, thank you for contributing!

**Review by ino-iosdev — DISMISSED** [review]
@buneeIsSlo 

Just noticed one minor thing to change, please mark the actions in the original issue ticket, after that it's all good! Thank you so much! Please see reference below:
[
Screenshot 2024-06-12 at 2 47 54 PM
](url)

**Comment by handshek** [comment]
@t-will-gillis Thank you for the clarification and the review :)

@ino-iosdev I Truly appreciate the kind words, and I'll be sure to mark the actions on the issue.

I look forward to contributing more!

**Comment by del9ra** [comment]
Review ETA: 6 PM 6/13/24
Availability: 1-5 PM Monday - Friday

**Review by del9ra — APPROVED** [review]
Hey @buneeIsSlo,
Great job with this pull request!
* The branching was done correctly
* Issue number was listed
* The PR title is descriptive of the changes
* Changes were made correctly in the code
* Note was left that there were no visual changes
Again, nice work and thanks for taking the time to contribute to the website!

**Review by pdimaano — APPROVED** [review]
@buneeIsSlo Good job: The branches are correct and the issue is linked. The webpage still works on my system on desktop, mobile and tablet. The correct file was changed with the requested information. Well done!

**Pull request merged**
