### PR TITLE
added github-handle for Katrina Bonoan

### LINKED ISSUE #6157: Add github-handle for Katrina Bonoan in brigade-organizers-playbook.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/brigade-organizers-playbook.md` in the IDE
- [x] Replace:
```
- name: Katrina Bonoan
```
with
```
- name: Katrina Bonoan
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/brigade-organizers-playbook

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Jperparas**
Fixes #6157

### What changes did you make?
  - added github-handle variable to Katrina Bonoan in brigade-organizers-playbook.md

### Why did you make the changes (we will use this info to test)?
  - reduce redundancy
  - prioritized backlog good first issue 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
no visible changes

### CODE REVIEW

**Review by partapparam — APPROVED** [review]
@Jperparas great job.

- The branch is going into the correct branch gh-pages. 
- The original issue [issue with #number] was properly referenced. 
- Per the instructions on the original issue, the specified lines of code were properly updated.

**Comment by partapparam** [comment]
availability - 7-8pm, -3/19
ETA - Done

**Comment by jonnyoe** [comment]
Availability: 10-11pm 3/19
ETA: 11pm 3/19

**Comment by jonnyoe** [comment]
@Jperparas Looks good to me!
- Comment is clean and thorough
- Code is correctly replaced
- Branch is named well and is merging to the correct place

**Review by jonnyoe — APPROVED** [review]
html code is replaced and merged correctly per issue #6157

**Pull request merged**
