### PR TITLE
Edited and removed content from care.yml #2810

### LINKED ISSUE #2810: Edit content field and remove type field from care.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/care.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/care.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/care.yml#L4
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/care.yml#L11

### PR DESCRIPTION
**Pull request by lilyarj**
Fixes #2810 

### What changes did you make and why did you make them ?

  -Changed line 4 from: content: icon --> to content-type: image 
  - Deleted line 11
  - I made these changes because this issue required these changes to be made in order for it to be resolved. I also made these changes to reduce content that was not needed in the code to make it easier to read.
 
 Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No screenshot, does not change website visuals

### CODE REVIEW

**Comment by Sparky-code** [comment]
@lilyarj Glad to see your environment is working! 
Please update your comment to follow this format when opening a new PR:
- Note the fixes:_____ number that links the PR to the original issue and the explicit note when the issue does not deal with visual changes.
- The why you did something is a great time to build the habit of teaching yourself something or potentially teaching something to those that will review your code. It will also be super useful later when you are building your resume or interviewing and you have ready made notes to refer to when they ask 'what did you do/learn at X'. In this case a one sentence summary of the details section would be perfect.
image

**Comment by blulady** [comment]
ETA:  6/23
Availability: 1 hours

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: 6/23

**Review by Sparky-code — DISMISSED** [review]
Thank you for updating the linked issue. Please see the rest of my initial comment so that I can approve your PR.

**Review by blulady — APPROVED** [review]
The branch is correct and goes to [hackforla:gh-pages](https://github.com/hackforla/website) from [lilyarj:edit-remove-content-care-yml-2810](https://github.com/lilyarj/website/tree/edit-remove-content-care-yml-2810).
There is a  linked issue and it is the correct issue. The requested change of line 4 from `content: icon` to `content-type: image` and deleted line 11. It looks good when I throw it up in my local repo, although there were no visual changes so no pictures were needed.
Good job!!!

**Review by kathrynsilvaconway — APPROVED** [review]

**Pull request merged**
