### PR TITLE
update content field and remove type field

### LINKED ISSUE #2859: Edit content field and remove type field from shield.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/shield.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/shield.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/shield.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/shield.yml#L11

### PR DESCRIPTION
**Pull request by SZwerling**
Fixes #2859

### What changes did you make and why did you make them ?
Updated line 4 to "content-type: image"
Eliminated line 11

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by aricforrest** [comment]
Review ETA: 8 PM 11/8/22
Availability: 5-8 PM Tuesday, Thursday

**Review by aricforrest — APPROVED** [review]
Great job @SZwerling! One note regarding the PR comment, you should remove the empty bullets and screenshot section.

**Comment by jyaymie** [comment]
Review ETA: 11/8/22 7pm
Availability: 11/8/22 Now til 7pm

**Review by jyaymie — APPROVED** [review]
Awesome work, @SZwerling! You've linked the issue and nicely completed its action items. Like @aricforrest mentioned, I'd remove any unused characters/text and even make a brief note that there were no resulting visual changes.

**Comment by Adastros** [comment]
Review ETA: 11PM 09NOV2022
Availability: 9 - 11:30 PM weekdays, Sunday 10AM - 10PM

**Review by Adastros — APPROVED** [review]
Nice job completing the issue @SZwerling! Don't forget to remove any unused bullet points from the PR commit message! If there aren't any visual changes to the website after completing an issue, you can briefly state that and remove any parts of the PR commit message that involve showing the visual changes.

**Pull request merged**
