### PR TITLE
Fixed mispelled words on join-us.html file #2914

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hey @answebdev I have fixed this. I have changed the spelling from "non-profit" to "nonprofit" and Line 77. 
Please Review this.

### CODE REVIEW

**Comment by Sparky-code** [comment]
Hi @NaincyKumariKnoldus it looks as though this issue is still undergoing approval from team leads- please [see here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) for reference on finding a good first issue to work on. I'd also take another look at the [contributions ](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) doc overall and [issues ](https://github.com/hackforla/website/issues)tab for proper checkout and documentation practices.

**Comment by JessicaLucindaCheng** [comment]
@NaincyKumariKnoldus  In order to work on issues in this repo, you must be a member of Hack for LA. (There are no fees to join.) To join, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).

In addition, this issue is not ready to be worked on, so I will be closing your pr.

**Comment by NaincyKumariKnoldus** [comment]
> @NaincyKumariKnoldus In order to work on issues in this repo, you must be a member of Hack for LA. (There are no fees to join.) To join, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
> 
> In addition, this issue is not ready to be worked on, so I will be closing your pr.

i was the member of Hack for LA. I had registered to it.

**Comment by JessicaLucindaCheng** [comment]
@NaincyKumariKnoldus Did you already attend an onboarding session with Bonnie?

**Comment by NaincyKumariKnoldus** [comment]
> @NaincyKumariKnoldus Did you already attend an onboarding session with Bonnie?

no

**Comment by JessicaLucindaCheng** [comment]
@NaincyKumariKnoldus After you attend an onboarding session with Bonnie, then you will be able to start working on issues in this repo.

**Comment by NaincyKumariKnoldus** [comment]
okay no problem @JessicaLucindaCheng

**Pull request closed without merging**
