### PR TITLE
Remove trailing slash from <img> tag in Citizen Engagement page

### LINKED ISSUE #4447: img Tag Refactor: Citizen Engagement page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/citizen-engagement.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
    <img class="header-hero-image" src="/assets/images/citizen-engagement/citizen-engagement-header.svg"
        alt="" />
```
to
```
    <img class="header-hero-image" src="/assets/images/citizen-engagement/citizen-engagement-header.svg"
        alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html
2. Webpage: https://www.hackforla.org/citizen-engagement
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by cmedina-dev**
Fixes #4447 

### What changes did you make and why did you make them ?

- Removed the trailing slash from the hero \ tag.
- The tag was removed to ensure consistency with other HTML \ tags across the site.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

(No visual changes)

### CODE REVIEW

**Comment by cmedina-dev** [comment]
Wasn't sure if I should remove the other \ tag's trailing slash per the issue's instructions since it only mentioned the hero image's tag, but since this is for consistency across the code base, if I need to do add that one to the PR as well just let me know! :smile:

**Comment by arcan9** [comment]
Review ETA: 04/11
Availability: after 5pm pst, M-F

**Review by RyanGehris — CHANGES_REQUESTED** [review]
Great job working on this issue. The changes you made were correct, and you are right in that you only needed to update the img element for the hero image. I am requesting changes because in your pull request you should provide an explanation of why the changes were made. You can do this by adding another bullet point under the header "What changes did you make and why did you make them ?"

**Comment by cmedina-dev** [comment]
> Great job working on this issue. The changes you made were correct, and you are right in that you only needed to update the img element for the hero image. I am requesting changes because in your pull request you should provide an explanation of why the changes were made. You can do this by adding another bullet point under the header "What changes did you make and why did you make them ?"

Thanks Ryan, the PR has been updated to include the reasoning from the original issue.

**Review by arcan9 — APPROVED** [review]
Nice work @cjmedina95!

- You made the changes that were outlined in the issue
- Made in the correct branch
- Linked issue
- Stated reason for the change

**Review by RyanGehris — APPROVED** [review]
Great work! Thank you for adding an explanation for the changes you made.

**Comment by cng008** [comment]
The pull request is done in the correct branch and the issue is linked correctly. In the source code, I see the change was made to the image tag to remove the slash at the end. There are no visual changes made. Good job on your first issue!

**Review by cng008 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. In the source code, I see the change was made to the image tag to remove the slash at the end. There are no visual changes made. Good job on your first issue!

**Pull request merged**
