### PR TITLE
Updated emergent-request.md labels -- #4502

### LINKED ISSUE #4502: Update labels: Issue Template: emergent-request
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/emergent-request.md`
- [x] Replace the following line
   ```
   labels: 'size: 0.25pt'
   ```
   with
   ```
  labels: 'size: 0.25pt', 'role missing', 'Feature Missing', 'Complexity: Missing'
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [Updated Emergent Issue Template](https://github.com/LRenDO/hfla-site/issues/new?assignees=&labels=size%3A+0.25pt%2Crole+missing%2CFeature+Missing%2CComplexity%3A+Missing&projects=&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/emergent-request.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by LRenDO**
Fixes #4502

### What changes did you make and why did you make them ?

  - Updated ```labels: 'size: 0.25pt'```  to ```labels: ['size: 0.25pt', 'role missing', 'Feature Missing', 'Complexity: Missing']``` 
in ```.github/ISSUE_TEMPLATE/emergent-request.md```
  - Added brackets to list that were not in the code in the original issue to fix linting issue.
  - Verified updates per testing instructions

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

 

</details>

<details>
<summary>Visuals after changes are applied</summary>
 

</details>

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [Updated Emergent Issue Template](https://github.com/LRenDO/hfla-site/issues/new?assignees=&labels=size%3A+0.25pt%2Crole+missing%2CFeature+Missing%2CComplexity%3A+Missing&projects=&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Review by LOSjr4 — APPROVED** [review]
Good job following the steps of this issue @LRenDO! Even I wasn't sure how to verify the changes   at first, and I've been here a few months.
I checked the link Ren left and verified the correct additions were made. Ren also wrote up a nice description of what was done including screenshots. I also noticed the additional checklist Ren followed in the comment section of the original issue as instructed.
Thank you for the good work Ren!

**Comment by ldietz08** [comment]
Availability: 5/26-5/27 1pm-4pm
ETA: 5/27

**Comment by ldietz08** [comment]
The pull request is done in the correct branch and you linked to the issue. The emergent request markdown file has been updated correctly. Great job!

**Review by ldietz08 — APPROVED** [review]

**Review by t-will-gillis — APPROVED** [review]
Hey @LRenDO - Great job! everything looks good: your branches, you linked the issue, your description tells the whats and whys, you included visuals, and your code changes are clean and concise, and when I test the code it adds the correct labels to the new issue. 

Thanks!

**Comment by LRenDO** [comment]
@LOSjr4 @ldietz08 @t-will-gillis  Thanks for the specific feedback y'all!

**Pull request merged**
