### PR TITLE
Swapped Color with Color Variables: Black, White, and Grey

### LINKED ISSUE #2113: Design System Audit: Swap colors with color variables: black, grey, and white
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the black, grey, and white colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (black, grey and white colors)
  - [x] Also, make sure to check the equivalent hex values
    - [x] For `$color-black`, `#333` is the same as `#333333`
    - [x] For `$color-mediumgrey`, `#ccc` is the same as `#cccccc`
    - [x] For `$color-white`, `#fff` is the same as `#ffffff`
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
  - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L49-L58

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  
</details>

### PR DESCRIPTION
**Pull request by ldaws003**
Fixes #2113

### What changes did you make and why did you make them ?

  - replaced the hard coded colors with their variable counter part for the black, white, and grey colors so that changes to these variables would reflect throughout the website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Just replacing hard-coded color with the appropriate color variable in the scss files so there should be no visible changes.

### CODE REVIEW

**Comment by DmitriiTsy** [comment]
ETA: 2022/11/12
Availability: 3 hours

**Review by DmitriiTsy — APPROVED** [review]
Hi. You did great work! I checked that all that [7kram](https://github.com/7kram) mentioned about this issue was resolved. It's awesome.

**Comment by esantiano** [comment]
ETA: 11/12/2022
Availability: 6 hours

**Comment by plang-psm** [comment]
ETA: 11/12/2022
Availability: 6 hours

**Review by plang-psm — APPROVED** [review]
Everything looks good and the site runs smoothly. Good job!!

**Review by esantiano — COMMENTED** [review]
Hey @ldaws003, 

Great job on addressing the original issue! I checked a docker composed site, clicked through a few of the pages, and found that the changes you made work seamlessly with the site, nice work. Also sharp eyes on catching the two instances one on line 225 and 242. The color codes being used on those lines are #000000 and #efefef which are described as black and a very light shade of gray that aren't mentioned in the issue resources. @JessicaLucindaCheng I'm also curious about whether these should be included in the changes as well.

**Comment by JessicaLucindaCheng** [comment]
@esantiano 
> The color codes being used on those lines are #000000 and #efefef which are described as black and a very light shade of gray that aren't mentioned in the issue resources. @JessicaLucindaCheng I'm also curious about whether these should be included in the changes as well.

Good catch noticing those colors as well! I think it's fine not to include the changes for this pr because those colors currently don't have variable names in our codebase. I have added a comment in issue #2114 about the colors you found, since that issues addresses colors without associated variables.

**Pull request merged**
