### PR TITLE
Fix Styling of Header of Projects 'Info Pages'.

### LINKED ISSUE #3377: feature-homepage-launch branch: Fix projects' info pages' styling of the header
### Overview
As developers, we need to fix the styling of the first header in the projects' info pages in the feature-homepage-launch branch so that it matches the styling of those pages on the live website. 

### Details
<details>
  <summary>Click here to see examples of what the header should look like on the current projects' info pages</summary>
  100Automations

  Home Unite Us

  Spare
</details>

<details>
  <summary>Click here to see examples of what the header looks like on the feature-homepage-launch projects' info pages</summary>
  100 Automations

  Home Unite Us

  Spare

</details>

On the feature-homepage-launch branch, the problem crept in on the project info pages when the SCSS class `hero-inner` was removed from home.scss as part of pr #2373, which was the initial pr on the feature-homepage-launch branch. I think the problem happened because a lot of the code originally in home.scss was removed/changed in order to style the redesigned homepage, including the removal of class `hero-inner`.

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] Familiarize yourself with how the headers look on the projects' info pages on the current website. See the Details section above for screenshots of examples; in addition, here are links to those example pages:
  - [x] https://www.hackforla.org/projects/100-automations
  - [x] https://www.hackforla.org/projects/home-unite-us
  - [x] https://www.hackforla.org/projects/spare
- [x] Fix the SCSS for the header on the projects' info pages on the feature-homepage-launch branch to match how it currently looks on the website by doing the following:
  - [x] In VS Code or your local IDE on your computer, navigate to `_sass/components/_project-page.scss`
  - [x] Then, add the following SCSS code:
    ```
    .hero-inner {
      color: $color-white;
      margin: 60px auto 0px;
      max-width: $max-content-width;
      position: relative;
      z-index: 2;
    
      @media #{$bp-tablet-up} {
        margin-bottom: 0;
        margin-top: 150px;
      }
    
      h1 {
        font-weight: bold;
        margin-bottom: .65rem;
      }
      
      p {
        margin-bottom: .65rem;
      }
      
      span {
        border-bottom: 3px solid $color-red;
      }
    }
    ```
- [x] Using Docker, make sure any changes you make to the code doesn't break anything on the website in mobile, tablet, and desktop views. 
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
  
### Resources/Instructions
- Tracked in https://github.com/hackforla/website/issues/2481
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [_sass/components/_project-page.scss](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_project-page.scss)

### PR DESCRIPTION
**Pull request by GRISONRF**
Fixes #3377

### What changes did you make and why did you make them ?

  - Added styling components in lines 387 to 411.
  - File path: _sass/components/_project-page.scss
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Capture

</details>

### CODE REVIEW

**Comment by tunglinn** [comment]
ETA: by end of 9/27
Availability: 1hr

**Comment by arpitapandya** [comment]
ETA: EOD 2022-09-27
Availability: 1hr

**Review by arpitapandya — APPROVED** [review]
All the changes are correct and visible. It doesn't break anything in the mobile, desktop, and tablet views. Great job!! @GRISONRF

**Review by tunglinn — APPROVED** [review]
Merge branches are correct. Changes follow linked issue. Site does not break and visual changes are seen. Good work!

**Pull request merged**
