### PR TITLE
Replaced ready for dev lead label with ready for merge team label in add-github-handle.md

### LINKED ISSUE #7600: Replace label in add-github-handle.md
### Overview
We need to change the ready for label on the add-github-handle.md issue template so that the merge team can handle more of the issue reviews.

### Action Items
- [x] Open the files  /.github/ISSUE_TEMPLATE/add-github-handle.md
- [x] In the following text, replace `ready for dev lead` label with `ready for merge team` label 
```
labels: 'Complexity: Small, feature: spelling, good first issue, P-Feature: Project
  Info and Page, ready for dev lead, role: back end/devOps, role: front end, size:
  0.5pt, size: 0.25pt'
```
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [x] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [x] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  image

  </details> 
- [x] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  image

  </details> 
- [x] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  image

  </details> 

- [x] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [x] Copy the URL of the issue creation page and save for later use.  
- [x] Verify the appearance of the issue template.
- [x] Complete the Pull Request process by visiting the URL saved from the push command.
- [x] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
```
 ### For Reviewers
- Use this URL to check the updated issue template: [INSERT URL of issue creation page]
```
- [x] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template in your fork of the repository
- [x] Submit your pull request with your changes for review
- [x] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/add-github-handle.md?plain=1

- This issue is part of Issue Making Issue #7602

### PR DESCRIPTION
**Pull request by siyunfeng**
Fixes #7600

### What changes did you make?
  
  - replaced `ready for dev lead` label with `ready for merge team` label in the file `/.github/ISSUE_TEMPLATE/add-github-handle.md`

### Why did you make the changes (we will use this info to test)?
  
  - to update the label so the merge team can handle more of the issue reviews

 ### For Reviewers
- Use this URL to check the updated issue template: https://github.com/siyunfeng/hackforla-website/issues/new?assignees=&labels=Complexity%3A+Small%2C+feature%3A+spelling%2C+good+first+issue%2C+P-Feature%3A+Project+Info+and+Page%2C+ready+for+merge+team%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt%2C+size%3A+0.25pt&projects=&template=add-github-handle.md&title=Add+github-handle+for+%5BINSERT+NAME%5D+in+%5BINSERT+PROJECT+FILE%5D

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
No visual changes to the website

### CODE REVIEW

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: Oct 30 EOD

**Comment by dcotelessa** [comment]
ETA: 1 hour
Availability: 4-6 W Th F

**Review by ramitaarora — CHANGES_REQUESTED** [review]
Hello!
- The changes look good on your branch.
- When I follow the link for reviewers, I don't see the correct labels showing up. I believe you asked a question about this as well.
- Since the issue template involves changing the labels specifically, I think we should make sure all the correct labels show up in the test issue on your branch.

**Comment by siyunfeng** [comment]
> Hello!
> 
> * The changes look good on your branch.
> * When I follow the link for reviewers, I don't see the correct labels showing up. I believe you asked a question about this as well.
> * Since the issue template involves changing the labels specifically, I think we should make sure all the correct labels show up in the test issue on your branch.

Hi @ramitaarora , thank you for reviewing this PR. 

I think the instruction is missing one of the actions to create new labels on my GitHub account so the labels wouldn't show. I created the corresponding labels on GitHub, which are automatically added to the templates. 

Please re-review my PR and the template when you are available, thanks!

**Review by ramitaarora — APPROVED** [review]
I checked the issue and now all the labels are showing up properly. The label 'ready for dev lead' is now 'ready for merge team'.

Great work and thank you for your contribution :)

**Review by dcotelessa — APPROVED** [review]
Good job!
- change on add-github-handle shows

Thank you for your contribution!

**Comment by jphamtv** [comment]
Thanks for working on this issue @siyunfeng. Just a reminder to complete the remaining action step listed in the issue now that the PR is merged.

**Comment by siyunfeng** [comment]
> Thanks for working on this issue @siyunfeng. Just a reminder to complete the remaining action step listed in the issue now that the PR is merged.

Thanks for your reminder!

**Pull request merged**
