### PR TITLE
update project profile remove Kristelle

### LINKED ISSUE #7474: Update Project Profile: Home Unite US Remove Kristelle Gumaru
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/home-unite-us.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
  - name: Kristelle Gumaru
    github-handle:
    role: Product Manager
    links:
      slack: "https://hackforla.slack.com/team/U031VJ99ATU"
      github: "https://github.com/K-Gumarama"
    picture: https://avatars.githubusercontent.com/K-Gumarama
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Home Unite Us page [^2]
- [ ] Once your pull request is merged, go to #7362  and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #7362 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #7362 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/home-unite-us

### PR DESCRIPTION
**Pull request by BlakePeters99**
Fixes #7474

### What changes did you make?
  
  - Removed Kristelle from the leadership variable
  - File changed:  _projects/home-unite-us.md 

### Why did you make the changes (we will use this info to test)?
  
  - Updated so that Unite Us current team members is most up to date.  

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

UpdateProjectProfileHomeUnitedUSRemoveKristelleGumaruBEFORE

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
UpdateProjectProfileHomeUnitedUSRemoveKristelleGumaruAfter

</details>

### CODE REVIEW

**Review by codyyjxn — APPROVED** [review]
@BlakePeters99 Thank you for taking on this issue. 
- The branch name is correct 
- The description is great as well. 
- The issue is linked correctly 
- before and after screenshots are great!

### Some Suggestions
- You can remove the extra bullet points 
- You can also edit the title to be a bit more clear of what files you changed.

Thank you for your contribution!

**Comment by mamypoco** [comment]
Review ETA: 6 PM 11/15/2024
Availability: 9-3 PM M-F

**Comment by BlakePeters99** [comment]
> @BlakePeters99 Thank you for taking on this issue.
> 
> * The branch name is correct
> * The description is great as well.
> * The issue is linked correctly
> * before and after screenshots are great!
> 
> ### Some Suggestions
> * You can remove the extra bullet points
> * You can also edit the title to be a bit more clear of what files you changed.
> 
> Thank you for your contribution!

**Comment by BlakePeters99** [comment]
Removed unnecessary bullet points and changed description to highlight which file was changed.

**Comment by trimakichan** [comment]
Review ETA: 6 PM 11/17/2024
Availability: 9-5 PM M-F

**Review by mamypoco — APPROVED** [review]
Good job removing the requested person, @BlakePeters99! 
 
 @BlakePeters99 Thank you for helping this issue.

The branch name is correct
The description is great as well.
The issue is linked correctly
before and after screenshots are great!

### Suggestions
I don't see CodeQL alert, so please check the section "I have checked this PR for CodeQL alerts and none were found."

Thank you for your contribution!

**Comment by BlakePeters99** [comment]
Thanks @mamypoco and @codyyjxn for the review and suggestion! Updated my pr accordingly.

**Pull request merged**
