### PR TITLE
Commented out test site for engage project

### LINKED ISSUE #4924: Comment out broken Test Site link for Engage project
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to comment out the non-functional "Test Site" for the Engage project to prevent users from encountering dead links on our site.

### Details
The Engage project has links that are currently leading to non-existent pages. This includes the "Test Site" link. This issue aims to temporarily hide this link from the website's visitors until we have the correct and functioning links in place.

### Action Items
- [x] Go to the [engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) file in the GitHub repository.
- [x] Identify the lines containing (_**only**_) the "Test Site" link.
- [x] Comment out both the line beginning with ` - name: ...` as well as the line with `   url: ...` so the "Test Site" link will not be rendered on the live website. In Markdown, this can be done by placing a '#' at the start of each line. If you are using VSCode, you can highlight the line(s) to be commented out, then select 'Ctrl/Cmd' + '/' to automatically insert the '#'s.
- [x] Confirm that both links are no longer visible on the live site by running the site locally on Docker and provide before and after screenshots.

### Resources/Instructions
[Engage](https://www.hackforla.org/projects/engage) project page
Associated ER: https://github.com/hackforla/website/issues/4594

### PR DESCRIPTION
**Pull request by brianf4**
Fixes #4924 

### What changes did you make?
  - Updated by commenting out name for "test site"
  - Updated by commenting out URL for "test site"

### Why did you make the changes (we will use this info to test)?
  - To temporarily hide this link from the website's visitors until we have the correct and functioning link in place.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before-screenshot

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after-screenshot

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability- Weekdays 10AM- 3PM
ETA- 8/30

**Review by Thinking-Panda — APPROVED** [review]
@brianf4 , Nice work with the issue. Merge branches are correct, code changes are as mentioned in the issue and website works perfect on my local machine. Well done. Thanks!

**Review by ronaldpaek — APPROVED** [review]
Great work All file changes and visual changes look correct to me.

**Review by t-will-gillis — APPROVED** [review]
Hey @brianf4 - great job on your first issue! Branches are correct, issue is linked, description explains what was done and why, screenshots are included, and code is clean. Changes are reflected in Docker with nothing unexpected. 
Thanks for working on this!

**Pull request merged**
