### PR TITLE
Update youth justive nav overview to open pdf

### LINKED ISSUE #2243: Update how 'Overview' link opens for Youth Justice Nav
### Overview
As a user, clicking on the 'Overview' link for the Youth Justice Nav project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Youth Justice Nav's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Youth-Justice-Nav-Product-One-Sheet.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Youth Justice Nav's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/youthjusticenav.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/youthjusticenav) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/youthjusticenav.md)
[Project Page](https://www.hackforla.org/projects/youthjusticenav)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

### PR DESCRIPTION
**Pull request by luke-karis**
Fixes #2243

### What changes did you make and why did you make them ?

  - Added pdf for youth justice nav to assets/pdfs
  - Changed the url for the youth justice nav Overview so that the pdf is opened instead of GitHub

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Added a file and changed where the user is taken to when clicking on a link. No visual changes to the website.

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
Review ETA: EOD 2/16
Availability: 4-6 PM Wednesday

**Comment by Carlos-A-P** [comment]
Review ETA: EOD 2/17
Availability: 2 hours

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1 hour
- Review ETA: Thursday, February 17, 2022

**Review by JessicaLucindaCheng — CHANGES_REQUESTED** [review]
@luke-karis Thanks for working on this issue! The code changes look good to me and I can see the pdf opens when clicked on the overview link. However, please add the pr to the Project Board and then re-request me to review your pr. (If needed, more detailed instructions are below.)

- [x] Please add your pr to the Project Board.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
    how-to-add-to-the-project-board1
    
    2) Click on the gear icon
    Add-to-project-board
    
    3) Then click on Project Board to add your pull request to the project board.
    how-to-add-to-the-project-board3
  
  </details>
  
- [x] When you are ready for me to re-review your pull request, please click the following in the Reviewers section on the right:
image

**Review by Carlos-A-P — DISMISSED** [review]
@luke-karis Great job. I can see the changes and the Overview links opened as a separate tab to the file in the project page and the project's dedicated page. As Jessica mentioned, you need to add the pr to the project board.

**Review by JessicaLucindaCheng — APPROVED** [review]
@luke-karis Looks good to me! Thanks for adding the pr to the Project Board.

**Pull request merged**
