### PR TITLE
removed two profiles (Bitian Zhang and Arpita Pandya)

### LINKED ISSUE #4473: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
  - [x] Remove Bitian Zhang
  - [x] Remove Arpita Pandya
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by 93Belen**
Fixes #4473

### What changes did you make and why did you make them ?

  - I removed Bitian Zhang and Arpita Pandya from the leadership in Hackforla.org Website to reflect accurate team information

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by 93Belen** [comment]
i. Availability: Monday, Tuesday, Thursday and Sunday all day

**Review by rdhmdhl — APPROVED** [review]
Great job following instructions! I ran this on my machine and no longer see Bitian or Arpita on the leadership section. Approved. 

Screen Shot 2023-05-14 at 12 42 03 PM

**Comment by matthewmpan** [comment]
Availability: M-F 12PM - 8PM
ETA: EOD 5/14/23

**Review by matthewmpan — APPROVED** [review]
@93Belen - Your branch is set up correctly, the issue is linked, you checked off all of the action items, and your changes look good in the browser. Nice work!

**Comment by angieyan** [comment]
Availability: M-F 9AM - 11AM
ETA: EOD 5/15/23

**Review by angieyan — APPROVED** [review]
@93Belen Thank you for taking up this issue. The changes look good to me, and the branch is set up correctly.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @93Belen, good job on completing the issue! The correct team members were removed on the website. 

Could you update the following before I merge this pull request:

- Update the title of this pull request to clarify what two profiles are being changed
- Add a brief statement on why the changes were made
- Update the "Visuals before changes are applied" image to reflect the current status of the [website project page](http://localhost:4000/projects/website). A new member was added while this pull request was in review.

These are all mainly to follow documentation practices at Hack for LA.

**Comment by 93Belen** [comment]
Hi @Adastros! I just made those changes, let me know if I need to update anything else. Thank you!

**Review by Adastros — APPROVED** [review]
Hi @93Belen, thanks for updating the pull request! Everything looks good

**Pull request merged**
