### PR TITLE
Update the profile guides team (Removed Shawn Wong profile)

### LINKED ISSUE #5584: Update Project Profile: Guides Team (Remove Shawn Wong)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the project information for Guides Team so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the `_projects/guides-team.md` file and make the following change:
  - [x] Under the `leadership` section, 
    - [x] Remove 
      ```
        - name: Shawn Wong
          role: Product Manager
          links:
            slack: 'https://hackforla.slack.com/team/U04MXRWPQ64'
            github: 'https://github.com/seannwvong'
          picture: https://avatars.githubusercontent.com/seannwvong
      ```
- [x] Verify the changes by viewing the Guides Team page [^1] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by #5407
[^1]: Project page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by blaycoder**
Fixes #5584 

### What changes did you make?
  - I removed the profile of Shawn Wong from the file ./_projects/guides-team.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before-updating-guides-team

</details>

<details>
<summary>Visuals after changes are applied</summary>

after-updating-guides-team

</details>

### CODE REVIEW

**Comment by kezzaam** [comment]
Review ETA: By EOD 10/5
Availability: 10/3 and 10/5

**Review by kezzaam — APPROVED** [review]
Hi @blaycoder! 
Fantastic job on this issue, I see that the changes have been made as specified without breaking or adding anything, and they are showing up as expected. Thanks for such an easy review :)

**Comment by kwangric** [comment]
ETA: EOD 10/4
Availability: All day

**Review by kwangric — CHANGES_REQUESTED** [review]
Branches are set up correctly and the requested changes are made. I just have two requests:

1. Please include the `Why did you make the changes (we will use this info to test)?` section of the PR. You don't have to be too detailed when explaining why the changes are made, referencing the original issue can help.
2. The empty line on `line 23` can be removed to keep the code consistent with the other projects.

Thanks @blaycoder!

**Comment by blaycoder** [comment]
Why did you make the changes (we will use this info to test)?  To update the project information for Guides Team so that visitors to the website can find accurate and up-to-date information.

The empty line on line 23 has been removed

Thanks @kwangric

**Pull request closed without merging**
