### PR TITLE
Issue # 1498

### LINKED ISSUE #1498: Fix alignment of News section in About page
### Overview
We need to fix the News section of the About page so that it is properly aligned and closer to how it looks in the original Figma design

### Action Items
- [x] Review the original [Figma design of the About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) with the correct News section alignment (in pink rectangle all the way on bottom of page)
- [x] Fix the alignment of the News section in the [About page](https://www.hackforla.org/about/#news) so that it is closer to the original Figma design

### Resources/Instructions
- [Original Figma design of About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) (all the way on bottom in pink rectangle)
- [About page](https://www.hackforla.org/about/#news)
- [HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Click arrows:

<details>
<summary>How About page News section looks now:</summary>
<br>
Screen Shot 2021-04-30 at 6 18 22 PM
</details>

<details>
<summary>How About page News section looks on Figma:</summary>
<br>
Screen Shot 2021-04-30 at 6 21 08 PM
</details>

### PR DESCRIPTION
**Pull request by 1anya1**
Fixes #1498
  
### What changes did you make and why did you make them ?

  - Refactored news container, added new styles according to figma spect both for mobile and web views.
  - Added new class to news container/ wrapped images. to prevent overrides  of repeating components
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screen Shot 2022-03-10 at 1 51 42 PM
Screen Shot 2022-03-10 at 1 53 29 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2022-03-10 at 1 54 57 PM

Screen Shot 2022-03-10 at 2 06 08 PM

</details>

### CODE REVIEW

**Comment by 1anya1** [comment]
@tamara-snyder sorry for the confusion I hope this PR will work. I made sure to remove all the previous commits that I have made. Please let me know if this works. I know there was initial commit to contributor( im not sure how it got there maybe from rebasing) but I ended up reverting it back so the code should work. Thanks again!

**Comment by JessicaLucindaCheng** [comment]
- github-actions didn't add labels but I'm going to go ahead and add them manually now so that people looking to review prs know the complexity and other information about this issue by looking at the labels.
- Note to reviewers: There is something wrong with the GitHub Actions automating the comment for the commands to pull the changes into your environment locally. To review the changes in your local environment, see "Commandline instructions for Development Team" for instructions and the commands: https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-3-view-the-changes-in-the-browser

**Comment by tamara-snyder** [comment]
Hi @1anya1, thank you for fixing this!

Availability: 2 hours
Review ETA: Monday, March 14, 2022

**Comment by JessicaLucindaCheng** [comment]
- Availability: 3 hours
- Review ETA: Wed, Mar 16, 2022 or Thu, Mar 17, 2022

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Hi @1anya1, thank you again for reverting back to the old commit. You've implemented the design really well in most cases. However, when I resize my screen to ~1000px in width and scroll, the nav-bar on the right covers the content of the page, as shown below:

### This branch
Screen Shot 2022-03-14 at 11 50 47 PM


It should look more like on the current version of the site:
### Current site
Screen Shot 2022-03-14 at 11 50 20 PM


### To fix:
- [x] Remove line 567 of `_sass/components/_about.css` where you set the width of `.news-cells` to `55.733vw`. I think this is the culprit and it also affects all of the other sections on the page.
- [x] Adjust the other elements as needed so that they align with the Figma design

Please re-request a review from me when you're ready. You can use this same PR. Thanks!

P.S. Sorry for the massive comment. I couldn't get the images to display when embedded in details tags.

**Comment by 1anya1** [comment]
@tamara-snyder great catch! I made the adjustment so there is no more overlap.
Screen Shot 2022-03-14 at 9 59 08 PM

**Review by tamara-snyder — APPROVED** [review]
Hi Anya, thank you for the super quick fix! All the breakpoints are covered now and you've done a wonderful job of matching the Figma design. Great work on this issue!

**Pull request merged**
