### PR TITLE
added image-hero-credit field and create public-tree-map.yml file

### LINKED ISSUE #3922: Add `image-hero-credit` to public-tree-map.md and create a new credit
### Overview
The `public-tree-map.md` file needs a new `image-credit` field and a new credit in [`data/internal/credits`](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits) since it is a credit to the photographer. 

### Action Items
- [x] Add a new field to [public-tree-map.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/public-tree-map.md) under `image-hero` called `image-hero-credit` 
```
image-hero-credit: 'Coral tree from City of Santa Monica. Photo by Dave Baiocchi www.studiobaiocchi.net'
```
- [x] Create a new credit yaml file in [`data/internal/credits`](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits)
  - [x] Use this [template](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)

### Resources/Instructions
- [public-tree-map.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/public-tree-map.md)
- Public Tree Map [project page](https://www.hackforla.org/projects/public-tree-map)
- Coral tree [image hero](https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/assets/images/projects/public-tree-map-hero.jpeg)
- Coral tree [source](https://www.davebaiocchi.net/santa-monica-urban-forest/r5drejeht8obbydv2c14krzuglraql)

### PR DESCRIPTION
**Pull request by ftblmagician**
Fixes #3922 

### What changes did you make and why did you make them ?
- A new image-hero-credit field was added to the public-tree-map.md file. The field was added in order to give the photographer credit for the image.

- A public-tree-map.yml file was created and added into data/internal/credits. The file adds the image to the credits page which gives credit to the photographer.

### CODE REVIEW

**Comment by bootcamp-brian** [comment]
Review ETA: By end of day tomorrow
Availability: Weekdays this week before 5pm

**Review by bootcamp-brian — CHANGES_REQUESTED** [review]
Thanks for working on this issue @ftblmagician, it appears that the issue this pull request is for wasn't successfully linked. Looks like it's just missing the # sign in front of the number is all.

**Comment by KazushiR** [comment]
Review ETA: In the next few minutes.
Availability: Weekdays

**Review by KazushiR — COMMENTED** [review]
@ftblmagician Once the issue is correctly linked, I will go ahead and approve the changes. I do not see any other problems with this PR.

**Comment by ftblmagician** [comment]
> Fixes #3922 
> 
> ### What changes did you make and why did you make them ?
> * A new image-hero-credit field was added to the public-tree-map.md file. The field was added in order to give the photographer credit for the image.
> * A public-tree-map.yml file was created and added into data/internal/credits. The file adds the image to the credits page which gives credit to the photographer.

**Comment by ftblmagician** [comment]
Okay... I believe I made the change now

**Comment by bootcamp-brian** [comment]
> Okay... I believe I made the change now

The issue still doesn't appear to be linked for me. I think you should be able to edit your original comment from when you first made this pull request by clicking the three dots at the top right of that specific comment. The first line "Fixes 3922" just needs to be changed to "Fixes #3922" I believe.

**Comment by KazushiR** [comment]
@ftblmagician I see that the issue is still persisting. You will need to hyperlink the issue to the issue number. Once it has been hyperlinked, I will be able to approve of the commit.

**Comment by ftblmagician** [comment]
ok now I think I got it! thank you for the help!

**Review by KazushiR — APPROVED** [review]
Looks like it is fixed! Nice job!

**Review by bootcamp-brian — APPROVED** [review]
Thanks for getting the issue linked. All the requests from the issue have been done and it looks like the changes show up on the credits page like they're supposed to, so this should be good to merge. Good job on completing the issue.

**Pull request merged**
