### PR TITLE
Created a yml file for SDG2

### LINKED ISSUE #4450: Creating a yml file for SDG 2
### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [x] In `_data/internal/sdg`, add a file called `sdg2.yml`
- [x] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 2
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg2
# The path to the SDG image
image: /assets/images/sdg/sdg2.svg
# The alt text for the SDG image
image-alt: 2 Zero Hunger
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 1
    # The SDG target statement 
    statement: By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153

### PR DESCRIPTION
**Pull request by agosmou**
Fixes #4450

### What changes did you make and why did you make them ?

  - Added a yml file for a Sustainable Development Goal no. 2 (SDG2) so that information is not repeated in multiple files
  
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM - 3PM
ETA: 4/20/23

**Comment by mjshelton12** [comment]
Review Availability: Wed 7pm-10pm, Thur 9am-1pm
ETA: EOD 4/19/23

**Review by mjshelton12 — APPROVED** [review]
Great work, agosomou! The basics are done perfectly: Your branches are correct, you linked to your issue, and your explanation of what you did and why you did it is clear.

Your code is clean and effectively meets the needs of the issue. Though it doesn't affect the look of the site, I brought it up in docker just incase and the site is indeed unchanged in all views. Excellent work!

**Comment by StephenTheDev1001** [comment]
Availability: M-F 10am - 12pm 
ETA: EOD 4/19/23

**Review by StephenTheDev1001 — APPROVED** [review]
Great pull request. You created the correct file and added the code correctly. I appreciate your clear and concise description of the changes made and why they were necessary. Thank you for your contribution.

**Review by Thinking-Panda — APPROVED** [review]
Hi @agosmou , Thank you for working on this issue. Merge branches look perfect, code added is clean and website works perfect on the local machine. Well done!

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by creating file sdg2.yml in the correct directory. The code is identical to the code in the linked issue. The code looks clean, only one commit and only one file changed.
Good job!!

**Pull request merged**
