### PR TITLE
edited credit for accounting image from revenue

### LINKED ISSUE #3337: Edit credit for Accounting image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Accounting credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/revenue.yml`,
  - [x] Change the file name from `revenue.yml` to `accounting.yml` 
  - [x] Change `title: Revenue` to `title: Accounting`
  - [x] Change `title-link: https://thenounproject.com/madadesign/collection/finance-and-currency/?i=3669009` to `title-link: https://thenounproject.com/search/?q=accounting&i=3669009`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'Revenue Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #3337
### What changes did you make and why did you make them ?

  - Renamed `_data/internal/credits/revenue.yml,` to `accounting.yml`
  - Updated changes to the file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 4 Hours
ETA: EOD 7/20/22

**Review by BeckettOBrien — CHANGES_REQUESTED** [review]
Everything else looks good but the issue said to remove `type: icon`.

**Review by BeckettOBrien — APPROVED** [review]
Perfect. The changes are good and the result on the website is correct. Good job!

**Review by blulady — APPROVED** [review]
This pr comes from the correct branch [arpitapandya:accounting-image-redesign-3337](https://github.com/arpitapandya/website/tree/accounting-image-redesign-3337) and goes to the correct branch, in this case [hackforla:feature-homepage-launch](https://github.com/hackforla/website/tree/feature-homepage-launch).
There is a linked issue and it is the correct issue. The issues requested changes have been made. There are no visible changes in the browser and the site works like it should. Good Job. 
You still have open issues so please remember to review pull requests until it is approved. Each pr review is practice using github and working with code.

**Comment by poorvi4** [comment]
Availability: 2-3 hours
ETA: Friday July 22th, 2022 8 pm

**Comment by poorvi4** [comment]
The changes look good to me and are appropriately reflected. Good job!

**Pull request merged**
