### PR TITLE
Edit Content Field and Remove Type Field From yml Credit Files - #2863

### LINKED ISSUE #2863: Edit content field and remove type field from star.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/star.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/star.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/star.yml#L4 
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/star.yml#L11

### PR DESCRIPTION
**Pull request by Adaakal**
Fixes #2863

### What changes did you make and why did you make them?

For the file _data/internal/credits/star.yml:
   - Changed line 4 for the content field from content: icon to content-type: 
      image 
  -  Removed line 11 for the type field
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
Edited a .yml file. No visual changes to the website.

</details>

### CODE REVIEW

**Comment by gstemmann** [comment]
Review ETA: 6 PM 1/12/23
Availability: 5-8 PM Monday

**Comment by jdingeman** [comment]
Review ETA: EOD January 8, 2023
Availability: 4 hrs

**Review by jdingeman — CHANGES_REQUESTED** [review]
Hi Adaugo, nice job. I would go ahead and remove the space from line 11 all together so it's uniform with the other files like this one.

**Comment by gstemmann** [comment]
> Hi Adaugo, nice job. I would go ahead and remove the space from line 11 all together so it's uniform with the other files like this one.

Yes, awesome job with your first good issue. When you take out line 11 we can approve the PR :)

**Comment by Adaakal** [comment]
@gstemmann @jdingeman thank you for the reviews. I've removed the spaces.

**Review by jdingeman — APPROVED** [review]
Nice job!

**Comment by Adaakal** [comment]
Thank you!

**Pull request merged**
