### PR TITLE
Added github-handle for Farah Khan in home-unite-us.md 

### LINKED ISSUE #7185: Add github-handle for Farah Khan in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Farah Khan
```
with
```
- name: Farah Khan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us.md

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by codyyjxn**
Fixes #7185

### What changes did you make?
  -  The github-handle for  Farah Khan  has been successfully added to the  projects/home-unite-us.md file.

### Why did you make the changes (we will use this info to test)?
  - Update related logic and documentation to reflect the use of the github handle variable, thereby ensuring consistent references throughout the project.

### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
- No screenshots since adding a variable did not create any new visual change

### CODE REVIEW

**Comment by mrodz** [comment]
**Availability**: Weekdays 8am-8pm, Weekends 9am-5pm
**ETA**: EOD 8/11/24

**Comment by daras-cu** [comment]
Availability: Sun/Mon all day, Tues-Fri evenings
ETA: 8/11 EOD

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @codyyjxn, thanks for working on this issue! A couple things to address:
- You added `github-handle` correctly in `home-unite-us.md`, but two additional files have changes that were not called for- `CNAME` and `README.md`. Please take a look at these and revert the changes.
- In your PR explanation, you should be more specific about the changes you made by including where or who you added the new variable for. This could be copied directly from the original issue or just note that it was for Farah Khan.
- Instead of deleting the whole screenshot section in the PR, I would keep it there and just note that there are no visual changes to the website to make it more clear for reviewers.
- It looks like you may have cut off part of the "Why did you make the changes" answer.

Otherwise your branches are set up correctly for merging and when I test the changes locally the Home Unite Us page displays as it should. 

A good idea may be to review successfully merged PRs for similar issues to see what they should look like, for example [#7325](https://github.com/hackforla/website/pull/7235).

Once you've made the adjustments let me know in a comment or re-request a review and I'll come back to take a look.

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @codyyjxn, thanks for making the adjustments! Everything looks good except CNAME is still showing up under the changed files, I know both versions look the same but I think the difference may be a newline after `www.hackforla.org`. You can manually adjust this again or to be sure everything is the same you can do a git checkout of just the CNAME file from a branch where it is unchanged.

**Review by mrodz — CHANGES_REQUESTED** [review]
> Hi @codyyjxn, thanks for making the adjustments! Everything looks good except CNAME is still showing up under the changed files, I know both versions look the same but I think the difference may be a newline after `www.hackforla.org`. You can manually adjust this again or to be sure everything is the same you can do a git checkout of just the CNAME file from a branch where it is unchanged.

Hi @codyyjxn, [this article](https://about.gitlab.com/blog/2020/11/23/keep-git-history-clean-with-interactive-rebase/) explains what a rebase is. I might try to rebase and remove the touches you made to the extra files if I were you.

If you get stuck, add the `ready for dev lead` label and move this **issue** from `In progress (actively working)` to `Questions / In Review` and explain your issue.

If rebasing is too complicated, I suggest you start over again as this issue is small and not worth a headache trying to learn some of git's complicated features if you're new to version control. For now, I am marking this as incomplete. Leave a comment and tag us when you have a fix :)

**Comment by codyyjxn** [comment]
Yea I am going to just start over with a new issue. 
When can I start  a new issue ?

**Comment by daras-cu** [comment]
@codyyjxn I don't think you have to start over with a whole new issue, what I would do is just delete the branch you have been working on (locally and on GitHub) and start over with the same issue on a new branch. You can close this pull request and once you have your changes done on the new branch just open a new PR.

If you do prefer to start over with a new issue you can follow the steps [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue) to unassign yourself from the current issue, and then you will be able to pick up a new one.

Either way I would suggest that after you've made changes, only stage the specific file(s) included in the issue before you commit (you can `git add` a single file by specifying the file path, see [here](https://github.com/git-guides/git-add)). This should avoid any unintentional changes to other files.

**Comment by codyyjxn** [comment]
Okay I will be working on it. Thanks ! @daras-cu

**Pull request closed without merging**
