### PR TITLE
Img tag refactor in Getting Started Page

### LINKED ISSUE #4394: img Tag Refactor: Getting Started page - `step-img-icon-git join-2.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="" />
```
to
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by garrettallen0**
Fixes #4394 

What changes did you make and why did you make them ?

- Got rid of the trailing slash and extra space.
- So that the codebase is consistent in how we use HTML tags.

Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- Refactoring img tag. No visual changes.

### CODE REVIEW

**Comment by se7en-illa** [comment]
Availability: M-F 12:00PM - 8:00PM EST
ETA: EOD 04/25/2023

**Comment by ghost** [comment]
Availability: M-F 1:30PM - 2:30PM PST
ETA: EOD 4/23/2023

**Comment by angieyan** [comment]
Availability: M-F 1:50PM - 2:30PM PST
ETA: EOD 4/23/2023

**Review by angieyan — APPROVED** [review]
Great job! I love what you have done, @garrettallen0 . You have made the change precisely. The pull request is done with the correct branch.

**Review by ghost — APPROVED** [review]
Great job! code does what was asked for in ticket, has a descriptive title, and contains the ticket number within the title.

**Comment by garrettallen0** [comment]
Thank you @angieyan and @DeitchDustin for your reviews and comments. This is on track to become my first successful PR and I am pumped!

**Comment by adevlinb** [comment]
Availability: M-F 12:00PM - 1:00PM, 5:00PM-6:00PM PST
ETA: EOD 4/23/2023

**Review by adevlinb — APPROVED** [review]
Excellent Job @garrettallen0!

a) The issue is accurately linked. 
b) The pull request is descriptive. 
 c) The branches are setup correctly. 
d) The changes are **Applicable**, do not **Break** the website, and are **Clean** .
e) The changes can be seen in the browser and are as requested. 
f) The changes in the source code are as clean and concise as possible.

**Review by se7en-illa — APPROVED** [review]
- Issue is linked correctly
- PR was created from the correct branch
- Code changes are clean, function correctly, and do not break the website

Great work!

**Pull request merged**
