### PR TITLE
Make about page dynamic

### LINKED ISSUE #1417: Fix Donate Image on About Page
### Overview
The donate image is not currently showing up on the about page. 

### Action Items

- [ ] Rename image from capital HFLA-Donate.gif to hfla-donate.gif.
- [ ] Change the image reference that appears on the Join Us and About page. 

### Resources/Instructions
https://github.com/hackforla/website/tree/gh-pages/assets/images/about

### LINKED ISSUE #1418: How to grab images in liquid jekyll
### Overview
How to grab images from a folder, and iterate through them
How to take the image names and use it for alt text

### Action Items

- [ ] research how to do this in Liquid Jekyll
- [ ] implement this
 
### Resources/Instructions
[Jekyll Docs](https://jekyllrb.com/docs/)

Good points of contact for help: @akibrhast @erikaBell @jbubar 

_If you need to reach out_: sharing any useful documents you've come across while researching would be helpful for us. So please add them in a comment.

### PR DESCRIPTION
**Pull request by akibrhast**
- This pr adds two new files under `data\internals`
   - about.yml
   - partners.yml

- The files allow for a more dynamic content on the site, such that new partners can be added or removed by adding
content to the partners.yml file

- It also allows for easy addition/update/delete of new accomplishments and executive letter changes via the
  about.yml page

<details>
<summary>About Page With Example Lorem Ipsum Markdown</summary>

image

</details>

Closes  #1418 
Closes https://github.com/hackforla/website/issues/1417

### CODE REVIEW

**Review by erikaBell — APPROVED** [review]
Looking good to me,  👁!

**Review by jbubar — APPROVED** [review]
Great job akib. I pulled it to my local branch and it all checked out!

**Comment by jbubar** [comment]
@akibrhast will you let bonnie know that we made the about page dynamic, and we are ready for her mark down letter?

**Comment by akibrhast** [comment]
@jbubar I believe so. Just give her this link as a demo  -> https://www.hackforla.org/about/

**Pull request merged**
