### PR TITLE
update project profile: expunge assist

### LINKED ISSUE #5756: Update Project Profile: Expunge Assist (Add Analicia Mejia Mesinas)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Analicia Mejia Mesinas
    github-handle: amejiamesinas
    role: Product Manager, UX Research
    links:
      slack: https://hackforla.slack.com/team/U04J34E73CG
      github: https://github.com/amejiamesinas
    picture: https://avatars.githubusercontent.com/amejiamesinas
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by jackyuan1**
Fixes #5756 

### What changes did you make?
  - Added a profile to the expunge assist team members
  
### Why did you make the changes (we will use this info to test)?
  - Keep current team members on the project up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

image

  

</details>

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: weekday evenings
ETA: EoD Thursday

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5756 was properly referenced. ✅ 
- Per the instructions on the original issue, specified data entry was properly added as a new entry. ✅ 
- Per your attached screenshots, the visual changes look great ✅ 

@jackyuan1 there are trailing bullet points on your pull requests that can be removed. When you get the chance, would you mind editing your PR without the unused bullet points? Aside from that, great work on the code!

**Comment by Chrisklangley** [comment]
Availability: weekday 6-10pm
ETA: 10-27-23 EOD

**Review by Chrisklangley — APPROVED** [review]
Hey @jackyuan1 


• you created a  new branch for your issue with the correct syntax
• your branch was committed to gh-pages
• you  linked your issue in your  PR 
• the changes you made were easy to follow 

Taking a look at your source code I saw you implemented the correct changes  the leadership variable in  the _projects/expunge-assist.md file. Visually everything looks really good, nice work

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @jackyuan1 Great job! 

- Your from/to branches are good,
- you are linked to the original issue,
- you are providing a short description of what you did and why,
- you are providing relevant before and after screenshots, 
- your code edits are clean, and
- when opened in Docker, the profile appears correctly with no unexpected changes.

As @MattChau01 noted, please remove the trailing bullets on the description. 

Everything looks great, thanks for your work!

**Review by t-will-gillis — APPROVED** [review]
@jackyuan1 Looks great! Thanks

**Pull request merged**
