### PR TITLE
 Add github-handle for Erik Guntner in home-unite-us.md

### LINKED ISSUE #7179: Add github-handle for Erik Guntner in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Erik Guntner
```
with
```
- name: Erik Guntner
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by ihop-56**
Fixes #7179

### What changes did you make?
  - Added github-handle: field under name: Erik Guntner in the _projects/home-unite-us.md file.

### Why did you make the changes (we will use this info to test)?
  - The change was made to prepare the project file for future enhancements by standardizing the GitHub handle field.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

### CODE REVIEW

**Review by vorleakyek — APPROVED** [review]
The code looks good. Thanks for contributing.

**Comment by 8alpreet** [comment]
**Review ETA:** EOD Sep 4, 2024
**Availability:** 3pm to 7pm weekdays

**Review by 8alpreet — APPROVED** [review]
Hi @ihop-56,

What went well:
* PR title is descriptive and concise.
* Branch is named correctly.
* Correct lines of code were changed.
* All sections of PR comment are well done.
* Issue is linked.

Wow, you did an amazing job on this one. Great job on learning from your last GFI. Keep up the good work!

**Review by k-cardon — APPROVED** [review]
Looks good--branched correctly, added the code w/ spaces instead of tab, and I confirmed the site is unchanged visually. Good work!

**Pull request merged**
