### PR TITLE
Update VRMS Profile

### LINKED ISSUE #2552: Update Project Profile: VRMS
### Overview
As a product manager of VRMS I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md

### Action Items

- [x] VRMS Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [x] Name
         - [x] GitHub hand
         - [x] Role
         - [x] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

### PR DESCRIPTION
**Pull request by sydneywalcoff**
Fixes #2552

### What changes did you make and why did you make them ?

  - Updated Description
  - Removed Khushboo Shah and Olga Bilogurova
  - Added Katiuska Alicea de Leon, Glen Paul Florendo, Walter (JunJie) Tang, Josh Bubar, and David Rubinstein
  - Added VRMS one sheet pdf to assets, linked as Overview
  - Added MongoDB Atlas, Postman, and Insomnia to tools.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

screenshot of current site

</details>

<details>
<summary>Visuals after changes are applied</summary>

screenshot after changes

</details>

### CODE REVIEW

**Comment by sydneywalcoff** [comment]
@ExperimentsInHonesty 
Hi Bonnie!
The slack ID for Glen Paul Florendo and the github for Josh Bubar were incorrect. I found the correct handle and ID, but they should probably be double checked by their respective owners. 

Josh's github: `https://github.com/jbubar`
Glen Paul Florendo's Slack ID: `UFQGH8JH0`

**Comment by JessicaLucindaCheng** [comment]
Review ETA: Friday, December 17, 2021

**Review by lopezpedres — APPROVED** [review]
Hi @sydneywalcoff The updates look great and all the new links work. Great job!

**Review by JessicaLucindaCheng — DISMISSED** [review]
@sydneywalcoff Everything looks good to me!

**Comment by SAUMILDHANKAR** [comment]
@sydneywalcoff: Thanks for working on the issue. Just a quick note, in your screenshot of visuals after changes are applied, there are only 2 links (Github and site) visible while (Readme, slack, overview and wiki) are not visible. Is this updated?

**Comment by JessicaLucindaCheng** [comment]
**Further clarification on my review dismissal**
When I used the git commands (shown in the comment by the github-actions bot) to review the pull request, it looked fine and all the links were there. However, when using GitHub Desktop just now, the links were not all there.


<details>

<summary>When using the git commands, I see</summary>

git commands pr 2593

</details>


<details>

<summary>When using GitHub Desktop, I see</summary>

pr2593

</details>

**Comment by sydneywalcoff** [comment]
@SAUMILDHANKAR looks like I have the screen shots switched in the initial pr. I'll update it.

**Comment by JessicaLucindaCheng** [comment]
Re-review ETA: Sunday, December 19, 2021 or Monday, December 20, 2021

**Comment by JessicaLucindaCheng** [comment]
@sydneywalcoff @SAUMILDHANKAR I think it was correct before but the after image did not include the updates merged into it. That's why the ReadMe, Slack, and Wiki links were missing.
@sydneywalcoff Could you please update those images again? Thank you.

**Comment by sydneywalcoff** [comment]
@JessicaLucindaCheng Great catch. I fully understand what happened. I uploaded the correct screenshots

**Review by JessicaLucindaCheng — APPROVED** [review]
@sydneywalcoff Thanks for updating the images and incorporatinging the most recent changes from the Hack for LA repo into your pull request! I see the same thing when I use the git commands and when using GitHub Desktop now in terms of what the changes look like on the VRMS page and the card on the project page. Good job!

**Comment by SAUMILDHANKAR** [comment]
@JessicaLucindaCheng: Thanks a lot for your detailed review.
@sydneywalcoff: Thanks for updating the screenshot. Great work.

**Pull request merged**
