### PR TITLE
Add github-handle for Natalie Aguilar in tech-work-experience.md 

### LINKED ISSUE #7252: Add github-handle for Natalie Aguilar in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Natalie Aguilar
```
with
```
- name: Natalie Aguilar
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by rachelcorawood**
Fixes #7252 

What changes did you make?
  -added "github-handle:" under Natalie Aguilar name in Tech Work Experience Project (tech-work-experience.md)

Why did you make the changes (we will use this info to test)?
-We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
No visual changes to the website.

### CODE REVIEW

**Review by codyyjxn — DISMISSED** [review]
Hi, @rachelcorawood 
Everything looks good! Thank you for taking this issue on. 
###  For future reference
- the removal of some whitespace, which I don't believe should affect the functionality. However, it's always a good precaution to double-check where the whitespace was removed to ensure it doesn't impact the code in any way.

- In the pr you can also add the name you changed.

**Comment by rachelcorawood** [comment]
Hi @codyyjxn Thank you! I'm all set right? I don't need to personal take any further actions for this issue or pull request correct?

**Comment by t-will-gillis** [comment]
@rachelcorawood 
- Since this is a duplicate PR, the PR that is being replaced needs to be closed with a comment linking to this new PR. 
- Please do not assign reviewers***, even if GitHub suggests someone. The person that you assigned is no longer active on the Website team, so you will be waiting a long time for a review from that person. ***The only exceptions are if you already arranged for a review from that person, or if that person previously reviewed the same PR: in other words, you should request reviews from @8alpreet, @daras-cu, and @minkang3

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @rachelcorawood, it looks like you are still having the same issue with additional lines being edited to remove whitespace. While it doesn't affect the code itself, if it's something your code editor is doing automatically it will keep coming up in future contributions you make so it is best to resolve it now. You can see where the additional edits are in the "Files changed" tab at the top of your PR. You may need to adjust your editor settings or check what extensions you have enabled.

Everything else looks good, your PR is set up correctly and you added the `github-handle` variable as required.

**Comment by DrAcula27** [comment]
@rachelcorawood It looks like changes were requested before this PR can be approved.
- If you have made these changes, please scroll up to the top of this page, and in the right-hand column, where it shows the reviewers, click on the `Re-request review` button next to the red icon.
- If you have not made the requested changes yet and need help figuring out the settings to prevent your editor from automatically making these whitespace changes, feel free to shoot me a message on Slack. As mentioned by the previous reviewers, this whitespace change here doesn't meaningfully change the code, however, in future issues this could pose a problem, especially with file types where whitespace matters.

**Comment by t-will-gillis** [comment]
Hi @rachelcorawood Please leave an update on when you will be able to complete this PR. Thank you

**Comment by rachelcorawood** [comment]
Hi @t-will-gillis I should have this done by late this evening. I will be attending the meeting from 7:30-8pm. I hit a block with updating my branch. At this point I may create a third branch to complete this task because I've hit some unexpected challenges. I'm gonna attend tonight's meeting to see if I can remedy the problem before I do so.

**Comment by rachelcorawood** [comment]
#7557

**Pull request closed without merging**
