### PR TITLE
updated leadership info

### LINKED ISSUE #3697: Update Project Profile: Lucky Parking
### Overview
As a product manager of Lucky Parking I want my project's details to be up to date on the HackforLA website

### Action Items
 In the [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md) file, update the `leadership` variable as follows (the order is important):
 - [ ] name: Yuting Chu
    - [ ] role: Product Manager Lead
    - [ ] slack: ‘https://hackforla.slack.com/team/U03J4E55KCH’
    - [ ] github: ‘https://github.com/ychu196’
    - [ ] picture: https://avatars.githubusercontent.com/ychu196
- [x] name: Greg Pawin
    - [ ] role: Data Scientist Lead (currently it says Product Owner / Data Science, and he is dropping the Product Owner)
    - [X] slack: ‘https://hackforla.slack.com/team/UUEQF3AJG’
    - [X] github: ‘https://github.com/gregpawin’
    - [X] picture: https://avatars.githubusercontent.com/gregpawin
 - [ ] name: Glen Paul Florendo
    - [ ] role: Full-Stack Developer Lead
    - [ ] slack: https://hackforla.slack.com/team/UFQGH8JH0
    - [ ] github: https://github.com/glenflorendo
    - [ ] picture: https://avatars.githubusercontent.com/u/9373317
  - [ ] name: Michael Morgan
    - [ ] role: UX/UI Design Lead
    - [ ] slack: ‘https://hackforla.slack.com/team/U01SPJCC26A’
    - [ ] github: ‘https://github.com/mklmrgn’
    - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
  - [ ] name: Yen Phan
    - [ ] role: User Research
    - [ ] slack: ‘https://hackforla.slack.com/team/U025M9VRDJR’
    - [ ] github: ‘https://github.com/ymphan’
    - [ ] picture: https://avatars.githubusercontent.com/ymphan
  - [ ] name: Yujin Chang
    - [ ] role: UI Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U0270QURQCD’
    - [ ] github: ‘https://github.com/eugenecha’
    - [ ] picture: https://avatars.githubusercontent.com/eugenecha
- [ ] name: Jodie Chen
    - [ ] role: UI/UX Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03RFGLLAQG’
    - [ ] github: ‘https://github.com/jojochen25’
    - [ ] picture: https://avatars.githubusercontent.com/u/103106753
- [ ] name: Sijia Pitts
    - [ ] role: UI/UX Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03CBK89KUY’
    - [ ] github: ‘https://github.com/sijiapitts’
    - [ ] picture: https://avatars.githubusercontent.com/u/103976231
- [ ] name: Pratibha Shivanand
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U03SM1LF9HD’
    - [ ] github: https://github.com/pratibhanagesh
    - [ ] picture: https://avatars.githubusercontent.com/u/8139348
- [ ] name: Aletia Trepte
    - [ ] role: Data Scientist/Engineer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03KAPRML9Y’
    - [ ] github: https://github.com/parcheesime
    - [ ] picture: https://avatars.githubusercontent.com/u/38143160
- [ ] name: Yao Guan
    - [ ] role: Quant UXR
    - [ ] slack: ‘https://hackforla.slack.com/team/U03F35T4PND’
    - [ ] github: https://github.com/yaoguan
    - [ ] picture: https://avatars.githubusercontent.com/u/41702875
- [ ] name: Diedrich Chavarria
    - [ ] role: Full Stack Developer
    - [ ] slack: ‘https://hackforla.slack.com/team/U031VEUS0CW’
    - [ ] github: ‘https://github.com/DCH-CH’
    - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
 - [ ] name: Arpita Pandya
    - [ ] role: Full Stack Developer
    - [ ] slack: ‘https://hackforla.slack.com/team/U02LQ20MEDU'
    - [ ] github: ‘https://github.com/arpitapandya’
    - [ ] picture: https://avatars.githubusercontent.com/arpitapandya
- [ ] name: Seymour Liao
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U018XPTSTC6’
    - [ ] github: ‘https://github.com/Seymour100’
    - [ ] picture: https://avatars.githubusercontent.com/Seymour100
- [ ] name: David Lam
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U02D8CDURF0’
    - [ ] github: ‘https://github.com/davidlamcanada’
    - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
- [ ] name: Carlos Olivas
    - [ ] role: Data Scientist
    - [ ] slack:
    - [ ] github: 
    - [ ] picture: https://avatars.githubusercontent.com/u/41702877
 - [ ] name: Sam Sengupta
    - [ ] role: UX/UI
    - [ ] slack:
    - [ ] github: 
    - [ ] picture: https://avatars.githubusercontent.com/u/41702879

### Instructions
- If an item is already checked off, double check the information matches the info in [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- Unchecked items are new info which needs to be updated or added.
- Make sure to use valid YAML syntax. You must match the existing structure of [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- Verify the changes by checking the "Current Project Team" section of the [Lucky Parking project page](https://www.hackforla.org/projects/vrms) on your local development environment

### Resources
- [Lucky Parking markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Slack: Find a slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #3697

### What changes did you make and why did you make them ?

  - updated leadership variable to make sure info was up-to-date.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

screencapture-hackforla-org-projects-lucky-parking-2022-12-12-11_55_48

</details>

<details>
<summary>Visuals after changes are applied</summary>

screencapture-localhost-4000-projects-lucky-parking-2022-12-12-11_55_16

</details>

### CODE REVIEW

**Review by arpitapandya — CHANGES_REQUESTED** [review]
Hey @Jaretzbalba It would be helpful if we add some roles in sequence. For eg. Devs and Designers, and Data-scientist.

**Comment by Jaretzbalba** [comment]
@arpitapandya I saw some other discrepancies in the roles. Some roles say UI/UX, UI/UX Designer, UI Designer. Should I consolidate these all to UI/UX Designer? Thanks!

**Comment by arpitapandya** [comment]
> @arpitapandya I saw some other discrepancies in the roles. Some roles say UI/UX, UI/UX Designer, UI Designer. Should I consolidate these all to UI/UX Designer? Thanks!

I am not sure, what's the difference between those two. But, we can keep the Data Science, and Devs in sequence except leads.

**Comment by arpitapandya** [comment]
ETA: EOD 2022-12-13
Availability: 10 minutes

**Review by arpitapandya — CHANGES_REQUESTED** [review]
@Jaretzbalba Please use placeholder image where picture's are missing.

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct! Great job!! @Jaretzbalba

**Pull request merged**
