### PR TITLE
SDG 8: Rename and replace image with correct color one

### LINKED ISSUE #4256: SDG 8: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `decent-work.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-08.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg8.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the SVG you just added by changing
```
<img src="/assets/images/sdg/decent-work.svg" alt="8 Decent Work and Economic Growth" />
```
to
```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth" />
```
- [x] Using Docker, check the About page's Sustainability section (https://www.hackforla.org/about/#sustainability) to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by aaronweixiangli**
Fixes #4256

### What changes did you make and why did you make them ?

 - In the assets/images/sdg directory, delete decent-work.svg
 - From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: E-WEB-Goal-08.svg
 - Add the svg you just downloaded into the assets/images/sdg directory
 - Rename that svg so that it becomes sdg8.svg
- In _includes/about-page/about-card-sustainability.html, update the path to the SVG you just added by changing
 ```
<img src="/assets/images/sdg/decent-work.svg" alt="8 Decent Work and Economic Growth" />
```
to 
 ```
<img src="/assets/images/sdg/sdg8.svg" alt="8 Decent Work and Economic Growth" />
```
  - Reason: We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

After replacing 'decent-work.svg' with 'sdg8.svg', I'm not seeing any visible changes. Please let me know if this is the expected outcome.

### CODE REVIEW

**Comment by chrismenke45** [comment]
Review ETA:
4/23 EOD

**Comment by mjshelton12** [comment]
Availability: M-F 9am-1pm
ETA: EOD 4/21/23

**Review by mjshelton12 — APPROVED** [review]
Excellent work! Your issue is set up perfectly with the link to the issue, correct branches, clear explanation of what you did/why, and effective photos. By the way, there is a change in the image it's just very subtle. The color is slightly different, the font is smaller, and the arrow chart thing is a slightly different size. I only noticed when I brought it up in docker and compared to the live site by clicking back and forth.

Anyway, excellent work! Very clean and effective code!

**Comment by chrismenke45** [comment]
My apologies, I will need to update my review ETA to tomorrow: 4/24 EOD

**Review by KazushiR — APPROVED** [review]
@aaronweixiangli Hello, I don't remember assignee myself this particular PR so I apologize for the delay. I have looked over the PR and everything seems to be good!

**Review by chrismenke45 — APPROVED** [review]
Nice work @aaronweixiangli! All the required changes have been made and it looks great. Thank you for making the changes from your previous PR.

**Comment by Adastros** [comment]
Hi @aaronweixiangli, good job on completing the issue! As @mjshelton12 mentioned, the visual changes are subtle and may not be apparent. 

The following are things I noticed when reviewing the issue prior to merging, do not affect the status of this merge, and may need an emergent request:

- It seems that `sdg-la.svg` and the sdg link below it are not positioned closely together. Per the Figma wire frame, they should be. Looking at the project board, it doesn't seem like we have an issue to address this. 

<details>

<summary>Current State</summary>

image

</details>

<details>

<summary>Figma Design</summary>

image

</details>

- On Firefox, the images are out of order. See the image below. Microsoft Edge and Chrome do not exhibit the issue. This may be a result of the SDG icon sizes which is addressed in issue #4229. If completing #4229 doesn't fix the issue, a separate issue will be needed to fix it. 

<details>

<summary>Current State - Firefox</summary>

image

</details>

**Pull request merged**
