### PR TITLE
remove Emma Thrash from Expunge Assist #7705

### LINKED ISSUE #7705: Update Project Profile: Expunge Assist Remove Emma Thrash
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
  - name: Emma Thrash
    github-handle: emmathrash
    role:  UX Content, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U05JUM3881J
      github: https://github.com/emmathrash
    picture: https://avatars.githubusercontent.com/emmathrash 

```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL:  https://www.hackforla.org/projects/expunge-assist
[^3]: initiating ER:  https://github.com/hackforla/website/issues/7580#issue-2579554525

### PR DESCRIPTION
**Pull request by codyjohnsontx**
Fixes #7705

### What changes did you make?
  
  - Remove Emma Thrash from Expunge Assist Current Team

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of Current Project Team up to date

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

emma_thrash_before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
emma_thrash_after
</details>

### CODE REVIEW

**Comment by mchait18** [comment]
Review ETA: 12 PM 11/20/24
Availability: 9-3 EST M-F

**Review by mchait18 — APPROVED** [review]
- The PR contains the correct branch
- issue is correctly linked
- changes are verified across browsers (firefox, edge, chrome)
- code changes are accurate and concise
- no other notable issues
Great job!

**Comment by belunatic** [comment]
Review ETA: 12 PM 11/22/24
Availability: 4-5 M

**Review by belunatic — APPROVED** [review]
@codyjohnsontx great job! All looks good 

**few suggestion**
- it will be helpful for the branch name to be more descriptive, maybe added a project emma is in, ex: ``remove-emma-thrash-expung-assist-7705``
- What has changed section can be more descriptive to, let us know what file changed, will help us going back and forth between the issue and PR to see what file need to be changed

Besides that , thank you very much @codyjohnsontx!

**Review by santiseccovidal — APPROVED** [review]
Hi @codyjohnsontx everything looks great. Branches, screenshots and code changes are correct. Also the What and Why sections. Though for next time, as a tip to help other developers, please add the files you changed in the What section. For example:
"Modified the `_projects/expunge-assist.md` file" or something of your choice of course.
Thanks for working on this, great job.

**Comment by codyjohnsontx** [comment]
Update
1. All finished, made notes in my own documentation about what to do better according to the reviews above. Only awaiting merge pull request to delete branch and continue on
2. None
3. M-F 3-7pm, 9pm-10pm
4. ETA: EOD 11/21/24

**Pull request merged**
