### PR TITLE
Update project card 3447

### LINKED ISSUE #3447: Update Project Card for Access the Data
### Overview
As a deleloper, I need the details of all Hack for LA projects to be up to date on the website. For this issue, we will update the Access the Data project card.

### Action Items

 - [x] Go to the file _projects/access-the-data.md
 - [x] Update the image to the  [current logo](https://drive.google.com/file/d/1GVGG8ie6eRbQUjUj2aM9tyPGhhUTs91W/view?usp=sharing)
  - [x] Replace the project description with the following:
  ```
         With government policies increasingly relying on data and data analysis, it becomes imperative to increase citizens' 
         access and understanding of local government data in order to be effective advocates for their communities.

         We are currently working on an MVP, which is a website that will serve as a foundation for the continued Access the Data 
         project. The MVP will consist of a website that hosts a catalog of sources of open government data. This project will 
         focus on Los Angeles County as its backdrop to test the hypothesis that this is a tool the community of community 
         activists and data experts needs and wants.
```
 - [x]  In the technologies section, add CKAN
 - [x] Remove the Partners section, as there is no current partner.
 - [x] In the tools section remove Sketch and phonecalls. Add [Google Drive](https://drive.google.com/drive/u/0/my-drive)
 - [x] In the links section, replace the Overview link with a link to the new [one sheet](https://drive.google.com/file/d/1uWSqc5jU6feY3XSi9g178qnoOkan6enH/view) (You 'll need to download the one sheet PDF first.)
 - [x] In the Resources section, replace the Overview link with a link to the new [one sheet](https://drive.google.com/file/d/1uWSqc5jU6feY3XSi9g178qnoOkan6enH/view)
 - [x] In the Current Project Team Section: 
     - [x] Remove: Sarah Nabelsi, Alyssa Bryant, Assel Abilova, Jeremy DeCarvalho, and Malak Hmimy
     - [x] Add:
     - name: AJ Price
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/D02USE0EPSS
      github: 'https://github.com/mxajPrice'
    picture: https://avatars.githubusercontent.com/mxajPrice
     - name: Mariana Melo-Vega
    role: UX/UI Research Lead
    links:
      slack: 'https://hackforla.slack.com/team/U038BPUMFB7
      github: 'https://github.com/mmelovega'
    picture: https://avatars.githubusercontent.com/mmelovega
     - name: Kevin Chu
    role: UX/UI Design Lead
    links:
      slack: 'https://hackforla.slack.com/team/U037TKS7U9G
      github: 'https://github.com/KC243
    picture: https://avatars.githubusercontent.com/KC243
     - name: Judson Lester
    role: Developer Lead
    links:
      slack: 'https://hackforla.slack.com/team/U9NFW84QK
      github: 'https://github.com/nyarly
    picture: https://avatars.githubusercontent.com/nyarly
 - [x] Once every action item has been checked off, write to the stakeholder on issue #3153 asking them if they sign off on User Acceptance.

### Resources
- [PDF overview of Access the Data Project](https://drive.google.com/file/d/1uWSqc5jU6feY3XSi9g178qnoOkan6enH/view?usp=sharing) 
- [_projects/access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Access the Data webpage](https://www.hackforla.org/projects/access-the-data)

### Associated Issue
 - #3153

### PR DESCRIPTION
**Pull request by mariareeves**
Fixes #3447

### What changes did you make and why did you make them ?

 - Updated image to the current logo
- Updated project description
- Added “CKAN” to the technology section
- Removed Partners section
- Removed Sketch and phonically from tools section and added google drive 
- Updated the leadership section
- Updated the Overview link in Resources section to the new One Sheet

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

description-before-changes
leadership-before-changes
overview-before-changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
updated-resources
updated-description)

</details>

### CODE REVIEW

**Comment by aricforrest** [comment]
Review ETA: 6 PM 9/27/22
Availability: 5-8 PM Tuesday

**Comment by carolemlago** [comment]
Review ETA: 8 PM 9/27/22
Availability: 5-8 PM Tuesday

**Review by carolemlago — DISMISSED** [review]
All looks good. Great job, Maria!

**Review by aricforrest — CHANGES_REQUESTED** [review]
Nice job on tackling this Maria. I found a few issues which you should address before this gets merged. In the future you may want to think more about the context of the surrounding files and code.

Update the image to the current logo
• The existing photo was not replaced and instead the new photo was added with its original name of "horizontal-version.png". If you look at other images within this directory they all follow a naming standard matching their project name.
• I suggest instead replacing the existing "access-the-data.png" image or naming this new logo something along the lines of "access-the-data-horizonal.png". 

Replace the project description
• There is no separation of the paragraphs when rendered.

Updated the tools section
• Google Drive and the other tool names are not capitalized.
• I suggest capitalizing the first letter of each tool if it is a product as most of the other projects are structured.

Update the one sheet
• The project's "one sheet" is not being replaced.

**Comment by mariareeves** [comment]
@aricforrest Thank you for your feedback! 

I have a question about the new "OneSheet" pdf. What is the correct way to replace it ?  I was having some issue with that and apparently the solution I tried didn't work out. 
Thank you!

**Comment by aricforrest** [comment]
@mariareeves replacing the pdf should be pretty straight forward but feel free to ping me on slack if you have additional questions. If you aren't seeing updates reflected in the website after you make changes to the `access-the-data.md`, it could be related to jekyll not updating the files in the _site directory.

Replace the "one sheet":
- checkout your issue branch 
- copy the old Access the Data project's "one sheet" filename
- delete the project's old "one sheet" file
- rename the new file to the old filename
- update the url in the Overview section to match the filename
- git add, commit, and push your local changes to your remote repository

**Comment by plang-psm** [comment]
Availability: 6hrs
ETA: 10/3/22

**Review by aricforrest — CHANGES_REQUESTED** [review]
@mariareeves you are going to hate me, I identified two issues. One you should be able to resolve and the other we will likely need @kathrynsilvaconway or @blulady to chime in.

Replace the project description
The newline characters you added are not doing the job of separating the two paragraphs when it's rendered in a web browser. You will need to use HTML to do this. Take a look at how a few of the other projects are doing it.

Update the image to the current logo
The updated logo linked in the issue does not meet either of the dimensions for the card image (600px x 400px) or hero image (1500px x 700px) specified in the comments on `access-the-data.md`. This is resulting in this projects image being much shorter than all the other projects.

**Comment by arpitapandya** [comment]
ETA: EOD 2022-10-01
Availability: 2hrs

**Review by aricforrest — APPROVED** [review]
Changes look good. Great job @mariareeves !

**Review by arpitapandya — APPROVED** [review]
All the changes are correct! Thank you for putting in the hard-work. Great job @mariareeves! I am approving all the changes. Also, This file `_projects/access-the-data.md` has lots of old comments and commented out code which shall be removed in future.

- @mariareeves I just noticed [comment](https://github.com/hackforla/website/issues/3153#issuecomment-1255477800). Let me know, if you can remove before I will merge this PR tonight. If not, I will write a new issue since you already put all the hard work and changes.

**Comment by arpitapandya** [comment]
> All the changes are correct! Thank you for putting in the hard-work. Great job @mariareeves! I am approving all the changes. Also, This file `_projects/access-the-data.md` has lots of old comments and commented out code which shall be removed in future.
> 
> * @mariareeves I just noticed [comment](https://github.com/hackforla/website/issues/3153#issuecomment-1255477800). Let me know, if you can remove before I will merge this PR tonight. If not, I will write a new issue since you already put all the hard work and changes.

Merging this PR. And will write new issue for [comment](https://github.com/hackforla/website/issues/3153#issuecomment-1255477800). Thank you @mariareeves You're free to work on the next medium issue.

**Pull request merged**
