### PR TITLE
resolve linter error in about-card-platform.html

### LINKED ISSUE #5318: Refactor HTML to resolve linter error: _includes/about-page/about-card-platform.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about page-card--platform' >
```
to
```
<div class="card-primary page-card-lg page-card--about page-card--platform">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-partners.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by jaasonw**
Fixes #5318

### What changes did you make?
  - Replaced single quotes with double quotes in about-card-platform.html

### Why did you make the changes (we will use this info to test)?
  - To resolve the linter error in https://github.com/hackforla/website/issues/5318

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by freaky4wrld** [comment]
Review ETA: 6 PM 12/10/22
Availability: Weekend mostly at noon

**Comment by freaky4wrld** [comment]
Hey there your collaborating branch (king-of-tiktok: fix-5318)[https://github.com/king-of-tiktok/website/tree/fix-5318] isn't descriptive enough as mentioned in the (contributing.md)[https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue], I would suggest to make it relevant like `jasonw: update-html-resolve-linter-error-5318 ` , I can't review it as it's clearly mentioned that the (names must match)[https://github.com/hackforla/website/wiki/images/how-to-review-pull-requests/step0-branches.png]

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
Hey there your collaborating branch [king-of-tiktok: fix-5318](https://github.com/king-of-tiktok/website/tree/fix-5318) isn't descriptive enough as mentioned in the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue).
I would suggest to make it relevant like ` jasonw: update-html-resolve-linter-error-5318 ` , I can't review it as it's clearly mentioned that the [names must match](https://github.com/hackforla/website/wiki/images/how-to-review-pull-requests/step0-branches.png)

**Comment by LukeLowrey2** [comment]
Availability: Tuesday 10/10/23 10am - 12pm
ETA: Tuesday 10/10/23 EOD

**Comment by jaasonw** [comment]
not renaming it because it cannot be renamed without deleting the branch and closing the pull request which has already been sitting around for a week but noted for next time

**Comment by jaasonw** [comment]
not renaming it because it cannot be renamed without deleting the branch and closing the pull request which has already been sitting around for a week but noted for next time

**Review by LukeLowrey2 — APPROVED** [review]
Hello @jaasonw!

- The issue is linked to the pull request
- You are committing into the proper branch
- The quotation marks have been update from single to double in about-card-platform.html

Thank you for for working on this issue. Great job!

**Pull request closed without merging**
