### PR TITLE
Updating github handle for Dennis Chatkhan

### LINKED ISSUE #6181: Add github-handle for Dennis Chatkhan in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-index.md` in the IDE
- [x] Replace:
```
- name: Dennis Chatkhan 
```
with
```
- name: Dennis Chatkhan 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by vanessasinam**
Fixes #6181

### What changes did you make?
  - Replaced "- name: Dennis Chatkhan" with "- name: Dennis Chatkhan github-handle: "

### Why did you make the changes (we will use this info to test)?
  - The plan is to create a single variable github-handle to hold the github handle for each member of the leadership team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-04-29 at 3 09 26 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
Screenshot 2024-04-29 at 3 13 51 PM

</details>

### CODE REVIEW

**Review by elisetvy — CHANGES_REQUESTED** [review]
Hi @vanessasinam,

1. The pull request is done with the correct branch
2. The issue is properly linked
3. Your summary of changes is clear
4. Your code change correctly uses spaces instead of tabs to indent
5. The appearance of the project webpage is unchanged 

Please check off the Action Items when working on issues to indicate you have completed them, then I will be happy to approve!

Thanks for your contribution!

**Review by del9ra — COMMENTED** [review]
Hey @vanessasinam! 
Review ETA: 2 PM 4/30/24
Availability: 5-8 PM Friday

**Review by del9ra — COMMENTED** [review]
1. The PR is done with the correct branch
2. The issue is linked correctly
3. spaces were used rather than tabs
4. The summary is clear
5. The code change is clean 
6. The visual aspect of the project webpage hasn't changed
Nice job!

**Review by del9ra — APPROVED** [review]

**Comment by vanessasinam** [comment]
> Hi @vanessasinam,
> 
> 1. The pull request is done with the correct branch
> 2. The issue is properly linked
> 3. Your summary of changes is clear
> 4. Your code change correctly uses spaces instead of tabs to indent
> 5. The appearance of the project webpage is unchanged
> 
> Please check off the Action Items when working on issues to indicate you have completed them, then I will be happy to approve!
> 
> Thanks for your contribution!

Hi @elisetvy I have updated the Action items!

**Review by elisetvy — APPROVED** [review]

**Comment by jphamtv** [comment]
Nice work on this @vanessasinam. For future issues, if there are no visual changes to the website, you can replace the "Visual changes before/after changes are applied" sections with a comment like "No visual changes to website".

**Pull request merged**
