### PR TITLE
Update civic tech infrastructure card 5428

### LINKED ISSUE #5428: Remove mention of CfA from the Civic Tech Infrastructure program area description
### Overview
We need to remove mention of CfA from the Civic Tech Infrastructure program area description.

### Action Items
- [x] In your local IDE, navigate to `_data/internal/program-areas/civic-tech-infrastructure-card.yml`
- [x] Replace:
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be 
  shared across Code for America brigades and support other similar organizations 
  around the world.
``` 
with:
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be shared with other similar organizations around the world
```
- [x] Using Docker, confirm that on the Program Areas webpage, the description under "Civic Tech Infrastructure" has been updated, but other elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/civic-tech-infrastructure-card.yml
2. Program Areas webpage: https://www.hackforla.org/program-areas

### PR DESCRIPTION
**Pull request by robertnjenga**
Fixes #5428

### What changes did you make?
  - Modified Civic Tech Infrastructure program area description.

### Why did you make the changes (we will use this info to test)?
  - Remove mention of CfA from the Civic Tech Infrastructure program area description.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

civic tech 1

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
civic tech 2

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 9/19

**Review by Thinking-Panda — APPROVED** [review]
@robertnjenga , thank you for working on this issue. Merge branches are correct, codes changes are as mentioned in the issue, and website works good on local machine. Well done.

**Comment by LRenDO** [comment]
Hi @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @robertnjenga!
Great job with this pull request!

- The branching was done correctly
- Issue number was listed
- Changes were made correctly in the code
- Changes appear correctly on the site - the edited text has been changed to remove the Code for America reference
- Relevant images were included to show visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I have only one minor non-functional change to request.
- [x] Please remove the unused bullet points in the PR comment 

When you're done with the changes you can click the circle with the arrows next to my name in the reviewers section. Thanks for taking the time to contribute to the website!

**Review by LRenDO — APPROVED** [review]
Hi @robertnjenga! Looks great! Thanks for making the changes!

**Review by t-will-gillis — APPROVED** [review]
Hey @robertnjenga - Great job! I don't have anything to add from the other reviewers- everything looks good. Thanks for working with @LRenDO and thanks for working on this issue!

**Pull request merged**
