### PR TITLE
Update Zero Hunger image alt text for About Us page

### LINKED ISSUE #3382: Update alt text for Zero Hunger image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-sustainability.html`, change the following alt text

From:
```
Zero Hunger goal logo
```

To:
```
2 Zero Hunger
```

- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by kyrakwak**
Fixes #3382

### What changes did you make and why did you make them ?
  - Changed Zero Hunger logo image alt text from `Zero Hunger goal logo` to `2 Zero Hunger`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to site.

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 1/17/23 11:40am
Availability: 1/17/23 Flexible

**Review by jyaymie — APPROVED** [review]
You successfully updated the alt text with the site continuing to run as normal. You're on a roll, @kyrakwak. Keep it up!

**Comment by maryjng** [comment]
Review ETA: 1/18 11:30 PM EST
Availability: 1/19 5-7 PM EST

**Comment by maryjng** [comment]
Code changes and site look good.

**Review by maryjng — APPROVED** [review]
Code changes and site look good.

**Pull request merged**
