### PR TITLE
Remove duplicate alt field in youthjusticenav.md

### LINKED ISSUE #3746: Remove duplicate `alt` field in youthjusticenav.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
There is a duplicate alt field for [youth justice nav](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/youthjusticenav.md). This breaks some yaml interpreters, and is non-standard for yaml.

### Action Items
- [ ] For the file `_projects/youthjusticenac.md`, delete line 6
```
alt: "All capital letters spelling out title of project - YOUTH JUSTICE NAV"
```

### Resources/Instructions
**File and code links you will need to work on this issue**

- Directory to find the page once you have it in your IDE: `_projects/youthjusticenav.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/e5361f8ab2a6537ee941e90f1d4e38ea83015276/_projects/youthjusticenav.md?plain=1#L6

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by annierm18**
Fixes #3746

### What changes did you make and why did you make them ?

  - Removed the duplicate alt field in the youthjusticenav.md file because having duplicate alt fields breaks some yaml interpreters and is non-standard for yaml

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: EOD 04/06
Availability: after 6pm, M-F

**Comment by bootcamp-brian** [comment]
Review ETA: 12:45pm
Availability: Today until 6pm

**Review by bootcamp-brian — COMMENTED** [review]
The issue is linked properly, the branches are set up right and you made the requested changes from the issue. Everything looks good to me. Nice work.

**Review by arcan9 — APPROVED** [review]
Nice work @annierm18!

- Correct PR branch
- Correctly linked the original issue
- Made the necessary changes to the code and documented it, including the reason for the change

**Pull request merged**
