### PR TITLE
Develop 404

### LINKED ISSUE #1482: Develop page for 404 Error Invalid URL page
### Overview 
It's a good idea to create a page for invalid url, so instead of seeing 404, user could have more clue to see what's going on. 

### 
<details>
<summary>Details </summary>

Screen Shot 2021-04-27 at 8 09 45 PM
</details>

RIght now if the invalid url is provided, out page will look like this 

<details>
<summary>We could improve it to something like youtube did:</summary>

Screen Shot 2021-04-27 at 8 11 31 PM
</details>

or 
<details>
<summary>Netflix</summary>

Screen Shot 2021-04-27 at 8 12 49 PM
</details>

### Action Items  

 Design
- [x] Finalise the web version
- [x] Finalise the mobile version 

Development 
- [x] Develop the new 404 Error page for the HfLA site matching final Figma design specifications (in the pink rectangle https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9616%3A0)
- [x]  Add illustration credit info (credit details listed below Figma design) to [Credits page ](https://www.hackforla.org/credits/)

### Resources  
[404 Error page in Figma (final design in pink rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9616%3A0)
[Template of a credit.yml file](https://github.com/hackforla/website/wiki/Template-of-a-credit.yml-file-(for-Credits-page))
[Credits page](https://www.hackforla.org/credits/)
Sample invalid url (Hack for LA): https://www.hackforla.org/hahaha
Sample invalid url (Youtube): https://www.youtube.com/asd
Sample invalid url (Netflix): https://www.netflix.com/hahaha

### PR DESCRIPTION
**Pull request by sena-ji**
Fixes #1482 

### What changes did you make and why did you make them ?

  - Developed the 404 page according to Figma
  - Shout out to @macho-catt for helping me so much. Helped me figure out new ways to rearrange divs on the page and some placement/sizing issues on the page. Great mentor and learned a lot of new techniques with him.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
image
image
image

### CODE REVIEW

**Review by erikaBell — CHANGES_REQUESTED** [review]
Looks great @sena-ji ! (-: 

The one change request I have is related to the "Join Us" link. The re-direct does not currently work. Our url param to the Join Us page is `/join` so all you should need to do is take out "us" from `/joinus`

**Comment by sena-ji** [comment]
@erikaBell Thank you for reviewing my PR! I made the changes requested and pushed them again :). Please let me know if you need anything else!

**Review by erikaBell — DISMISSED** [review]
One last thing! Can you add a bit of space around the "Uh Oh!" header in mobile view, per the figma design

<details>
<summary>Figma, mobile view</summary>

Screen Shot 2021-07-20 at 12 28 39 PM

</details>

<details>
<summary>Sena's Branch, mobilve view</summary>

Screen Shot 2021-07-20 at 12 30 10 PM

</details>



Thanks (-:

**Review by daniellex0 — COMMENTED** [review]
Yes agreed with @erikaBell , for both mobile and desktop! Otherwise looks good :) 

Tagging @kristine-eudey to loop her in on pull request reviews

**Comment by sena-ji** [comment]
Fixed the lineup issue with the "Uh-Oh" message

**Review by adam-abundis — DISMISSED** [review]
There seems to be a lack of spacing in the mobile view. I provided a visual example of the Figma design and your current changes. It seems like you need:
- You need to add more left/right margin for the 404 section.
- More top/bottom space between the title.
- You may need to drop the font size for `Looks like something went wrong...` in mobile view.

<details>
<br>
  <summary>Click here to see <strong>figma design (iPhone X view)</strong> with visual lines</summary

Screenshot 2021-07-26 095953
<br>
</details>

<details>
<br>
  <summary>Click here to see <strong>your current 404 page (iPhone X view)</strong> with visual lines</summary>
  
  Screenshot 2021-07-26 101301
<br>  
</details>

**Comment by adam-abundis** [comment]
Created #2097 to move my request for styling updates for the mobile view of the 404 page. @hackforla/website-merge I am going to approve the pull request and merge so we have a working 404 page.

**Review by adam-abundis — APPROVED** [review]
@sena-ji Thank you for your patience. You did a great job on the 404 page. I created a separate issue (#2097) to correct the styling for the mobile view. Thank you for your understanding and your work.

**Comment by adam-abundis** [comment]
@Aveline-art Does the branch need to be updated to make sure there are no merge conflicts?

**Pull request merged**
