### PR TITLE
Removed unused component  `_includes/calendar.html`

### LINKED ISSUE #7282: Remove unused component `_includes/calendar.html`
### Dependency
- [x] #7281

### Overview
We need to remove the file `_includes/calendar.html` because the component is no longer used.

### Action Items
- [x] Delete the file `_includes/calendar.html`
- [x] Using Docker, confirm that the HfLA home page is unchanged
- [x] Add and commit the change then create a PR in the usual manner

### Resources/Instructions
[Liquid - include statement documentation](https://shopify.dev/docs/api/liquid/tags/include)
[HfLA homepage - webpage](https://www.hackforla.org)

### PR DESCRIPTION
**Pull request by codyyjxn**
Fixes #7282

### What changes did you make?
  
  - Removed the file `_includes/calendar.html` 
  - The file I removed was in the `pages/index.html`

### Why did you make the changes (we will use this info to test)?
  
  - The changes I made were necessary due to the deprecation of the previous approach. 
  - The original method of handling variables negatively impacted performance and made the code more challenging to read and maintain. The updated approach enhances both efficiency and code clarity.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

  - No screenshots.

### CODE REVIEW

**Review by handshek — APPROVED** [review]
Hey @codyyjxn, Nicely done!

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a detailed description of what was done and why
- `No screenshots` is mentioned

Thanks for working on this issue!

**Review by daras-cu — APPROVED** [review]
Hi @codyyjxn, great job working on this issue!
- Branches are set up correctly
- Original issue is linked in your PR
- Clear explanation of changes and why they were necessary
- File deleted does not affect the website

Just a reminder, when you assign yourself to an issue don't forget to move it from "Prioritized Backlog" to "In Progress" on the Project Board.

**Comment by codyyjxn** [comment]
> Hi @codyyjxn, great job working on this issue!
> 
> * Branches are set up correctly
> * Original issue is linked in your PR
> * Clear explanation of changes and why they were necessary
> * File deleted does not affect the website
> 
> Just a reminder, when you assign yourself to an issue don't forget to move it from "Prioritized Backlog" to "In Progress" on the Project Board.

Thanks totally forgot to do that. Can I now move it to "test-approved-by-reviewer" ? @daras-cu

**Comment by daras-cu** [comment]
> > Hi @codyyjxn, great job working on this issue!
> > 
> > * Branches are set up correctly
> > * Original issue is linked in your PR
> > * Clear explanation of changes and why they were necessary
> > * File deleted does not affect the website
> > 
> > Just a reminder, when you assign yourself to an issue don't forget to move it from "Prioritized Backlog" to "In Progress" on the Project Board.
> 
> Thanks totally forgot to do that. Can I now move it to "test-approved-by-reviewer" ? @daras-cu

@codyyjxn I think you can just move it to In Progress, the "test-approved-by-reviewer" is an automated category for PRs.

**Pull request merged**
