### PR TITLE
 Fix alignment and scaling of resource links

### LINKED ISSUE #3118: Fix alignment and scaling of resource links
### Overview

As developers, we want to ensure that the behavior of the page is consistent between content types and across all platforms. For this issue, we will fix the mobile alignment of the Resources cards on the  project details pages.

### Action Items
- [x] Explore an individual project page in mobile view to see the alignment issues.
- [x] Edit the [_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss) file to center the Resources cards for mobile view 

### Instructions
-  On mobile, view the "Resources" section of the [100 Automations Project Page](https://www.hackforla.org/projects/100-automations). (Since all individual project pages draw from the same styling, you may choose any individual project page to use as a template for addressing this issue.) <details><summary>See Screenshot of Resources section on mobile</summary>Screenshot from 2022-11-30 13-38-15</details>

### Resources
- [_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss) 
- [Media Query Variables File](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss)

### PR DESCRIPTION
**Pull request by Adaakal**
Fixes #3118

### What changes did you make and why did you make them?

  - Edited the [_project-page.scss] file to center the Resources cards for mobile view

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-02-20 at 3 00 30 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

Screen Shot 2023-02-20 at 3 00 43 PM

</details>

### CODE REVIEW

**Comment by vmaineng** [comment]
Review ETA: 6 PM 2/23/23
Availability: 5-8 PM Weeknights

**Comment by vmaineng** [comment]
Hey Adaakal! Great job on this! I only have one question - do you know why there are changes to vscode/settings.json file? I don't anticipate any changes to this file since it was not mentioned in the linked issue. Please let me know what your thoughts are. Thanks!

**Comment by Adaakal** [comment]
> 

Hi @vmaineng,
Thank you! My only prediction is that change happening due to git? I didn't manually add that line to the vscode/settings.json file so I'm not quite sure. I notice that no value was added though. How do you think I should proceed?

**Comment by vmaineng** [comment]
Hey @Adaakal, I'd recommend to delete line 11 from the vscode/settings.json file and push your changes again. Please let me know if you have any questions. Thanks!

**Comment by bzzz-coding** [comment]
Review ETA: 7 PM 2/24/23
Availability: Tuesday and Thursday evenings

**Review by bzzz-coding — CHANGES_REQUESTED** [review]
@Adaakal Thanks for working on this issue! I like your approach of adding `justify-content: space-evenly;` to center the cards on small screens. 

I agree with @vmaineng and think that the settings.json file could be changed back to what it was, and then we can test and make sure everything works as expected. Thank you!

**Comment by Adaakal** [comment]
Hi! Thank you both. I hope this fixed it.

**Review by bzzz-coding — COMMENTED** [review]
@Adaakal Thank you so much for your hard work! I love your approach of using `justify-content: space-evenly;` to evenly display the cards. However, I noticed that because of the `margin-left: auto;` rule and the fact that the .resource-link class has a margin-right of 5px, the cards appear slightly shifted to the left rather than being perfectly centered. I'm attaching three screening shots below:

Currently, the cards look slightly shifted to the left:
Screenshot 2023-02-24 at 3 10 31 PM

After I turned off the `margin-left: auto;` rule, the cards look centered:
Screenshot 2023-02-24 at 3 09 00 PM

If we highlight the .resource-link, we can see there is a 5px margin-right:
Screenshot 2023-02-24 at 2 55 14 PM

Personally, I don't see the reason for setting the 5px margin-right, instead of using auto to set both margin-left and margin-right. Maybe we can refer to the design guide in Figma?  What are your thoughts? @vmaineng what do you think?

**Comment by Adaakal** [comment]
> @Adaakal Thank you so much for your hard work! I love your approach of using `justify-content: space-evenly;` to evenly display the cards. However, I noticed that because of the `margin-left: auto;` rule and the fact that the .resource-link class has a margin-right of 5px, the cards appear slightly shifted to the left rather than being perfectly centered. I'm attaching three screening shots below:
> 
> Currently, the cards look slightly shifted to the left: Screenshot 2023-02-24 at 3 10 31 PM
> 
> After I turned off the `margin-left: auto;` rule, the cards look centered: Screenshot 2023-02-24 at 3 09 00 PM
> 
> If we highlight the .resource-link, we can see there is a 5px margin-right: Screenshot 2023-02-24 at 2 55 14 PM
> 
> Personally, I don't see the reason for setting the 5px margin-right, instead of using auto to set both margin-left and margin-right. Maybe we can refer to the design guide in Figma? What are your thoughts? @vmaineng what do you think?

Oh, I think you're right. It would be simple get the cards centered if we were to just turn off the `margin-left: auto;` rule. You're suggesting heading to Figma then?

**Comment by mademarc** [comment]
Review ETA:  7:30PM 2/28/23
Availability: 1Hr

**Review by mademarc — COMMENTED** [review]
@Adaakal It looks well done the code and the image is well styled :)

**Comment by bzzz-coding** [comment]
@Adaakal I think removing the `margin-left: auto;` is the most straightforward and fastest way to fix this current issue. However, I haven't looked into the design style guide in depth so I don't know if the 5px margin-right was there for a reason, or if removing the `margin-left: auto;` would result in other elements being displayed in an undesired way. We can definitely give it a try and see if everything looks good. :)

**Comment by jdingeman** [comment]
Hi @Adaakal, wanted to check in regarding the progress on the changes requested. Did you see @bzzz-coding's comment?

**Comment by Adaakal** [comment]
> Hi @Adaakal, wanted to check in regarding the progress on the changes requested. Did you see @bzzz-coding's comment?

Hi @jdingeman, testing that suggestion now.

**Comment by Adaakal** [comment]
Removed margin-left:auto from the branch fix-alignment-and-scaling-3118

**Review by bzzz-coding — APPROVED** [review]
@Adaakal Thanks for working on this issue and testing the changes! You made the pull request from and to the correct branches, and the change you made in the code was clean and precise. The cards are centered on a mobile screen (width <= 479px)! 🌟🙌

Screenshot 2023-03-07 at 1 14 19 PM
Screenshot 2023-03-07 at 1 13 58 PM

**Comment by blulady** [comment]
@vmaineng just wondering if you wanted to throw an ETA for a review or ...

**Pull request merged**
