### PR TITLE
record-clearance added

### PR DESCRIPTION
**Pull request by leonelRos**
@ExperimentsInHonesty, Project record-clearance has been added!

### CODE REVIEW

**Comment by ExperimentsInHonesty** [comment]
@leonelRos It looks like you made a change to another file, please remove that from your pull request.

**Comment by KianBadie** [comment]
Also, another friendly heads up. Please make sure the "h" in "Github" is lowercase. Currently the code that I'm working on with the project page expects it to be lowercase. The consistency across all the cards makes it easier to code :) @leonelRos

**Comment by leonelRos** [comment]
@KianBadie No problem!

**Comment by ExperimentsInHonesty** [comment]
Fixes #280

**Pull request closed without merging**
