### PR TITLE
changing typo issue 2348

### LINKED ISSUE #2348: Fix typo for Undebate under Accomplishments: from thorughout to throughout
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.  

### Action Items
- [x] Correct the spelling mistake in the Accomplishments section of the About page by changing "thorughout" to "throughout" in line 37:
From
```
    thorughout the country from the San Francisco City Attorney race, to Student Association Elections on College Campuses.
```
To
```
    throughout the country from the San Francisco City Attorney race, to Student Association Elections on College Campuses.
```
- [ ] Ensure that the [corresponding webpage](https://www.hackforla.org/about/#accomplishments) reflects the spelling fix

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/_data/internal/accomplishments.yml```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/f015a891265d56372f87e1adb1e1b6088dcfac06/_data/internal/accomplishments.yml#L37

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

https://www.hackforla.org/about/#accomplishments

### PR DESCRIPTION
**Pull request by Georgema20**
Fixes #2348

### What changes did you make and why did you make them ?

  - Changed"thoroughout" typo to "throughout"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screen Shot 2021-12-13 at 11 16 04 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2021-12-12 at 7 36 25 PM

</details>

### CODE REVIEW

**Comment by macho-catt** [comment]
Hi @Georgema20, please update the content of your post with the following info:

- Issue number that the PR fixes
- What changes you made to the code
- Visual changes on the website, if any

Afterwards, we can review. Thanks!

**Comment by JessicaLucindaCheng** [comment]
@Georgema20 Thanks for making the changes that @macho-catt requested! Please also do the following:

- Add an image for the "Visuals before changes are applied" in your post
- Add this pull request to the Project Board

**Comment by Georgema20** [comment]
How do I add this to the project board? Sorry new to github and figuring a lot of this out now @JessicaLucindaCheng 

Nvm I think I figured it out. Please confirm.

**Review by JessicaLucindaCheng — APPROVED** [review]
@Georgema20 The pull request was put correctly on the Project Board. Thanks for updating your pull request again!
The changes made to the code look good. Awesome job on your first issue!

**Review by macho-catt — APPROVED** [review]
LGTM. Good job on your first issue

**Pull request merged**
