### PR TITLE
Updated Expunge Assist project team with Rick Peng

### LINKED ISSUE #7701: Update Project Profile: Expunge Assist Add Rick Peng
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Rick Peng
    github-handle: rcpeng34
    role: Product Manager, Development
    links:
      slack: https://hackforla.slack.com/team/U07QU3C45MY
      github: https://github.com/rcpeng34
    picture: https://avatars.githubusercontent.com/rcpeng34
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: (https://www.hackforla.org/projects/expunge-assist)
[^3]: initiating ER:  #(https://github.com/hackforla/website/issues/7580#issue-2579554525)

### PR DESCRIPTION
**Pull request by jakejjoyner**
Fixes #7701

### What changes did you make?
Added Rick Peng to Expunge Assist team

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of active expunge-assist project team up to date

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-11-19 201546

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-11-19 201537

</details>

### CODE REVIEW

**Comment by codyjohnsontx** [comment]
Review ETA: 3:15 PM 11/20/24
Availability: On Call Today: 10am-6 PM CST, 9pm-12midnight CST 11/20

**Review by codyjohnsontx — APPROVED** [review]
Very nice work @jakejjoyner 
Proper into and from branches
Clear and simple what and why
Correctly added the team member Rick Peng’s info

Thanks for the PR!

**Comment by siyunfeng** [comment]
Review ETA: 11/20/2024 Wed
Availability: 6-10 PM Weekdays (EDT)

**Review by siyunfeng — APPROVED** [review]
Great job working on this issue, @jakejjoyner !

- The branch you made the change on is correct
- The linked issue number is included
- Availability and ETA are provided in the original issue
- The CodeQL Alerts are checked
- The change you made is accurate
- The before-and-after screenshots help display the changes

Things to improve: 
- Name the branch with more specific details, for example, `expunge-assist-add-rick-peng-7701`
- Provide your availability for the week instead of the day in the original issue
- Check the boxes of all the `Action Items` you completed in the original issue

You did an awesome job on your good first issue. Thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
@jakejjoyner Good job on your first good issue. 
- The branch is correct and the issue is linked as well. 
- The file changed is correct 
- The before and after screenshots are great !
Keep it up !

**Comment by belunatic** [comment]
Review ETA: 10 AM 11/22/24
Availability: 4-5 PM Monday

**Review by belunatic — APPROVED** [review]
- the naming convention of the issue is great
- before and after picture look good
- code added is clean and understandable

Suggestions:
- as one of out college explain, you will need to be more descriptive on the issue naming, ex: ``update-expunge-project-profile-add-rick-peng`` 
- in the What section try to include what file you changed

Amazing job!! Goodluck on your next one

**Pull request merged**
