### PR TITLE
Updated project profile: Civic Tech Index

### LINKED ISSUE #3236: Update Project Profile: Civic Tech Index
### Overview

As a product manager of Civic Tech Index I want my project's details to be up to date on the HackforLA website

### Action Items

- [ ] Civic Tech Index Team Leadership
    - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
        - [x] title
        - [x] description
        - [x] image
        - [ ] leadership
            - [ ] Name
            - [ ] GitHub hand
            - [ ] Role
            - [ ] SLACK ID
        - [x] links
            - [x] Github
            - [x] Wiki
            - [x] Slack
            - [x] Test Site
            - [x] Demo Site
            - [x] Site
        - [x] technologies
        - [x] partner
        - [x] tools
        - [x] status
 
[Comment with the necessary changes](https://github.com/civictechindex/CTI-website-frontend/issues/1062#issuecomment-1151508065)

### Resources/Instructions
- File where changes need to be made [_projects/civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)
- Link to the CTI project page on our website: [CTI project](https://www.hackforla.org/projects/civic-tech-index)
- Related issue link to be followed: https://github.com/civictechindex/CTI-website-frontend/issues/1062

### PR DESCRIPTION
**Pull request by alan-zambrano**
Fixes #3236

### What changes did you make and why did you make them ?
Updated the website by removing devs no longer working on the project, adding new devs, and updating existing devs so that it is up to date with the project.
* Removed:
    * Joyce Kim
    * Vance Dubberly
    * Adaeze Nwaezeigwe
* Added:
    * Iffath Sultana
* Updated:
    * Bhaggyalakshmi
    * Maxwell Countryman Skewes

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 1 hr
ETA: EOD 6/28

**Comment by lilyarj** [comment]
ETA: 6/29
Availability: 3 hrs tmr

**Review by BeckettOBrien — APPROVED** [review]
The changes look correct and the site works perfectly. Good job!

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Pull request merged**
