### PR TITLE
Fix cop redirection 5622

### LINKED ISSUE #5622: Fix broken CoP redirect
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to change https://www.hackforla.org/cop to redirect to the _Communities of Practice_ (CoP) page [^1] so that it redirects to the expected page on the website.

### Action Items
- [x] In your IDE, open the `redirections/cop.md` [^2], and make the following change:
  - [x] Change
    ```
    redirect_to: /communities-of-practice/
    ```
    to
    ```
    redirect_to: /communities-of-practice
    ```
- [x] Using Docker, check https://www.hackforla.org/cop will redirect to _Communities of Practice_ (CoP) page [^1]

### Resources/Instructions
- This issue is a result of https://github.com/hackforla/website/issues/5329#issuecomment-1738852984 
[^1]: [_Communities of Practice_ (CoP) page](https://www.hackforla.org/communities-of-practice)
[^2]: File to open in your IDE: `redirections/cop.md`

### PR DESCRIPTION
**Pull request by dineshsk98**
Fixes #5622  

### What changes did you make?
 -changed path on line 7 in redirections/cop.md

### Why did you make the changes (we will use this info to test)?
  -fix broken path
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

272727955-20ab00b4-6ea2-426a-9bec-17165035440a

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
272727950-112b04f0-8437-437c-9e88-6193c982c79c

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 10/13/23
Availability: Weekday evenings

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 10/11

**Review by pdimaano — APPROVED** [review]
@dineshsk98 Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed and the appropriate ending slash was removed.  The included screenshots also reflect the redirect to the correct webpage. Well done!

**Review by Thinking-Panda — APPROVED** [review]
@dineshsk98 , Well done. Branches are setup correctly, code changes are clean and as mentioned in the issue, website works well on my machine. Thank you !

**Comment by mademarc** [comment]
Review ETA: 10/12/2023
Availability: 7:22PM

**Review by mademarc — APPROVED** [review]
Hey @dineshsk98 well done in fixing the issue on line 7.

**Pull request merged**
