### PR TITLE
refactored tools data for access-the-data.md

### LINKED ISSUE #4798: Refactor Tools data for access-the-data.md
### Dependencies
- [x] #4860
- [x] #4861 

### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Photoshop, Google Drive
```
to
```
tools:
  - Figma
  - Photoshop
  - Google Drive
```
ADDED NOTE 8/6/23: Refer also to issue #4818 for additional edits.

  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by Tomomi-K1**
Fixes #4798

### What changes did you make?
  - on `access-the-data.md` file under `_project` file, I changed `tools`  data from string to a list as it is described on issue action item.

### Why did you make the changes (we will use this info to test)?
  -We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from tools to technologies, and vice versa. In order for the filter to work properly, we need to refactor the tools data in the .md file from a string to a list.
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>
  
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @Tomomi-K1! This looks great! Nice work!

- The branching was done correctly with the issue number
- The title is descriptive
- The changes were made correctly and display correctly on the site
- Nothing additional was changed
- The "what" was very descriptive
- Appropriate screenshots were included with helpful highlighting

I have one minor request.  Please add a section about why the changes were made.  Often times you can find the reason why the change is being made in the original issue.

Once you've made the change, you can click the circle with the arrows next to my username in the `Reviewers` section of this page.  This will re-request a review.

Thank you for taking the time to contribute to the site!

**Comment by Tomomi-K1** [comment]
@LRenDO Thank you so much for checking my first pull request! I have added `why changes were made` section. Let me know if I need to change anything! I'm happy to contribute and get more experiences!

**Comment by kwangric** [comment]
ETA: EOD 7/27

**Review by LRenDO — APPROVED** [review]
Update looks great @Tomomi-K1! Thanks again and great job!

**Review by kwangric — APPROVED** [review]
Looks like branches are set up correctly and the requested changes to the code were made. Everything look good in Docker as well. Great work!

**Review by adrianang — APPROVED** [review]
Hi @Tomomi-K1 — the branching is set up correctly, the corresponding issue is linked, and the requested change was made to exactly what was asked of (making the tools for Access the Data into a list from a string). When I tested your branch on my local machine via Docker, the Access the Data project page looked the same, as expected.

I would also say that since this issue didn't really have a visual change, the screenshots aren't really needed and could be either deleted or noted that there weren't visual changes, but this is just something minor to keep in mind for your next issues if they also don't have visual changes.

Thank you for taking up this issue! 🙌🏼

**Comment by Tomomi-K1** [comment]
Hi @adrianang ,

Thank you for checking and approving my issue! I will keep in mind that I don't need to add images if there is no visual change.
This time, there was actually minor visual change, but the difference is only quotation mark. :)

Thank you again for your time!

**Pull request merged**
