### PR TITLE
Design System Audit: Audit for hardcoded colors

### LINKED ISSUE #2114: Design System Audit: Audit for hardcoded colors
### Dependency
- [x] #4138 
- [x] #2112
- [x] #2113 
- [x] #2198
- [x] #2199
- [x] #2200
- [x] #2204
- [x] #2205

### Overview
We want to stop using hard-coded colors, and instead, use variables so future changes to colors in our color palette will be easier to implement on our website.

### Action Items
- [x] Check our entire code base for hard-coded colors (as opposed to a color variable).
  - [x] Check for all of the color types listed in the Resource section below.
  - [x] If a color is hard-coded*, and is not currently a variable (see files below), add a comment on this issue noting:
    - [x] its location, including
      - [x] file
      - [x] code snippets 
    - [x] the type of color (reds, oranges, blacks, etc)
    - [x] suggested color variable name
  - [x] Else:
    - [x] change the hard-coded color to a variable instead  

### Resources/Instructions
- HTML colors: https://htmlcolorcodes.com/
- Color variables and classes in our codebase
  - Color variables: https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss
  - Color classes: https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss
- If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
  - [Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)
  
 #### *Hard-coded colors can be one of the following color types:
- HTML color codes
- Hex color codes
- RGB 
- HSL values
- HTML color names

### PR DESCRIPTION
**Pull request by AHP15**
Fixes #2114 

### What changes did you make and why did you make them ?
- I find all the hardcoded color value and put a note for them in the issue associated with this PR
- I changed the following color values:
     -  `background: #F6F6F6;` to `background: $color-whitesmoke;` in file: `_sass/components/_project-page.scss`
     - `color: #030D2D;` to `color: $color-darkblue;` in file `_sass/components/_donate-components.scss`
     - Also I change colors from hard-coded values to variable in the following files: `_sass/components/_home.scss`, `_sass/components/_privacy-policy.scss`, `_sass/components/_projects-page.scss`

### CODE REVIEW

**Comment by 93Belen** [comment]
Availability: Tuesday and Thursday morning. Sunday all day
ETA: Thursday by 11am

**Review by 93Belen — CHANGES_REQUESTED** [review]
Hey really nice job! This Issue is labelled as a small issue but it looks medium to me. Well done!
I found a few things that need changes and a suggestion.

- [x] Just a suggestion: This color https://github.com/hackforla/website/issues/2114#issuecomment-1576482002 you said that is a type of white. It looks more like a green than a white. If you want, a little trick to name variables (since this is a tedious job) you can ask chat GPT. I asked for a name for that color and it suggested "Pale mint" which is pretty accurate haha. This would be an easy way to find more descriptive names for the variable names that contain numbers, like `color-darkblue-2`
- [x] This one: https://github.com/hackforla/website/issues/2114#issuecomment-1576485332 already has a variable called `color-darkblue`
- [x] In this one https://github.com/hackforla/website/issues/2114#issuecomment-1576499182 this color : `rgb(187, 255, 187)` in HEX is #BBFFBB which is hold by the variable called `color-lightgreen`
- [x] In this one https://github.com/hackforla/website/issues/2114#issuecomment-1576505443 that shorthand represents the HEX color #333333 that is hold by the variable called `color-black`
- [x] This one https://github.com/hackforla/website/issues/2114#issuecomment-1576524246 has a typo in the location. There is a score where there should be an underscore `_sass/components/-credit-items.scss` should be `_sass/components/_credit-items.scss`
- [x] In this one https://github.com/hackforla/website/issues/2114#issuecomment-1576551611 the color in line 257 is hold by the variable `color-pink`
- [x] In this one https://github.com/hackforla/website/issues/2114#issuecomment-1576551611 you mention line 265 but you don't need to since you changed it for a variable.
- [x] I didn't see any comment mentioning `_saas/components/_guides.scss` lines 52 and 225

**Comment by AHP15** [comment]
Hi @93Belen, Thanks for the review!
I made the required changes

**Review by LOSjr4 — COMMENTED** [review]
@Abdessittir The color names you labeled are all correct according to previous names that were used for the hardcodes referenced in the dependency documentations. So I approve what what done so far.
After browsing the keyword "color" in VScode, I was wondering if some of these other hardcodes should also be changed? Correct me if I'm wrong. I'm not actually sure.
image
image

image
image

image

image
image

**Review by 93Belen — CHANGES_REQUESTED** [review]
Nice job! You addressed all my charges requests! Now you just need to update the PR description to match the changes you did. ☺️

**Comment by AHP15** [comment]
Hi @93Belen thanks, I just updated my pull request description

**Comment by AHP15** [comment]
@LOSjr4 Thanks for the review if you take a look at the #4783 issue you will see that I mentioned all of those colors in comments and suggested names for them as the issue requires

**Review by 93Belen — APPROVED** [review]
Thank you for the update!

**Review by LOSjr4 — APPROVED** [review]
Thank you @Abdessittir for clarifying my question and adding more details in your description.

**Pull request merged**
