### PR TITLE
Remove unused alt-hero field from shared housing project file

### LINKED ISSUE #3210: Remove unused `alt-hero` field from shared-housing-project.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/shared-housing-project.md`, remove line 8 for the alt-hero
```
alt-hero: 'Light-gray background'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/shared-housing-project.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/_projects/shared-housing-project.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by ldaws003**
Fixes #3210

### What changes did you make and why did you make them ?

  - removed line 8: "alt-hero: 'Light-gray background'" from the file _projects/shared-housing-project.md due to it being unused

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No screenshots, since the alt text wasn't used.

### CODE REVIEW

**Comment by giroz** [comment]
ETA: 10-31-22
Availability: 2 hours

**Comment by gstemmann** [comment]
ETA: 10-31-22
Availability: 6 hours

**Review by gstemmann — APPROVED** [review]
Looks like you appropriately removed the line 8 for the alt hero that was requested.
Awesome Job!

**Review by arpitapandya — CHANGES_REQUESTED** [review]
Hey @ldaws003 I see that you haven't created a topic branch. Please follow the [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue). 
For each issue create a topic branch and then create a pull request to merge the changes.


- You may close the PR and create new.

donotpushchangestoghpagescreateanewbranch

**Review by giroz — CHANGES_REQUESTED** [review]
Hey ldaws003.  I see you haven't put this in your own branch.  
ldaws003 wants to merge 3 commits into hackforla:gh-pages from ldaws003:gh-pages
I don't know if your changes would effect hackforla: gh-pages or not.

**Pull request closed without merging**
