### PR TITLE
Refactor CONTRIBUTING.md: Removes slash at closure of Image Tag  in Section 2.4

### LINKED ISSUE #7097: img tag refactor in CONTRIBUTING.md Sec 2.4.b
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open the file `CONTRIBUTING.md`
- [x] In Section 2.4.b change
```
<img src="https://user-images.githubusercontent.com/21162229/137693338-97fe5f6c-820d-41c9-8e93-57b70827e0cf.gif" />

```
to
```
<img src="https://user-images.githubusercontent.com/21162229/137693338-97fe5f6c-820d-41c9-8e93-57b70827e0cf.gif">

```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.** 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL (also store the test URL for use in a later step)
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```

### Merge Team
- [x] After closing this issue, check off the dependency in #6453.  If all dependecies have been completed, close #6453 and check off its dependency in #4362.  If all dependencies have been completed in #4362, close it.  

### Resources/Instructions
1. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. This issue is part of #6453

### PR DESCRIPTION
**Pull request by mSharifHub**
Fixes #7097

### What changes did you make?
-Root Directory CONTRIBUTING.md file refactored  by removing slash at end of closure image tag on Section 2.4
make it better

For Reviewers: Do not test changes locally, rather test changes at https://github.com/mSharifHub/website/tree/img-tag-refactor-contributing.md-sec.2.4.b-%237097/CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
-As requested in the Issue to meet the same syntax format of other tags

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
-No visual changes to the website

### CODE REVIEW

**Review by k-cardon — CHANGES_REQUESTED** [review]
Code and branch look correct, and the PR is clear. One change needed--the link to the correct page to confirm no visual changes is broken--when I click the link you provided, it returns 404 not found.

**Review by codyyjxn — CHANGES_REQUESTED** [review]
Thank you for taking on this issue @mSharifHub 
Things that went well:
-You made the correct branch name. 
- The change on the file is correct. 

Somethings you need to complete is:
- You need to check the boxes from the original issue. 
- You also need to provide the link as the issue prompted you to do. 
- I don't see a URL where I can go to see what changes you made.

**Comment by mSharifHub** [comment]
Hey, I just noticed the feedback. I will do the above, however, there is no visual changes. The original issue is asking to remove the slash at ending index. This is not visible to the end user rather just a syntax style change.

**Review by k-cardon — DISMISSED** [review]
The issue persists--this link is broken:

https://github.com/mSharifHub/website/tree/img-tag-refactor-contributing.md-sec.2.4.b-#7097/CONTRIBUTING.md

correct link is needed to the contributing page so we can verify no visual changes. Maybe a reread of the issue would help? Or just a working link to the relevant section of the contributing page? (I was a bit confused by the issue directions as well)

**Comment by mSharifHub** [comment]
interesting. i did the above https://github.com/mSharifHub/website/blob/img-tag-refactor-contributing.md-sec.2.4.b-#709/CONTRIBUTING.md and shows a 404

**Comment by mSharifHub** [comment]
Yah, I dont know why the link is broken,

**Comment by mSharifHub** [comment]
I sent a message on slack. I followed all instructions yet I dont know why the link is broken. Im sorry, I only have been with Hack For LA for a short period. I will be waiting for someone to help resolve the broken link.

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hi @mSharifHub 

It looks like you've tried to guess the URL based on the example URL Roslyn provided, that isn't working because your branch URL has the character '#' that needs to be escaped. 

You just need to manually navigate to the branch in your local repo where you've made the changes, click on the contributing.md file in that branch, and link the URL you get.

**Comment by mSharifHub** [comment]
You totaly right, the "#" needs to be escaped. I should had named differently . I updated with %23

**Review by codyyjxn — APPROVED** [review]
Well Done ! @mSharifHub

**Review by ajb176 — APPROVED** [review]
Looks good, nice work. A few notes for next time:

- You can easily just get the link by clicking on `mSharifHub:img-tag-refactor-contributing.md-sec.2.4.b-#7097` above the PR, then scrolling down and clicking on the contributing.md file. Although just escaping the '#' works, it's easy to just navigate to where the file is located on your fork and copy/paste the URL there. 
- Unless you have a reason to, it's best not to request review from specific reviewers. They may be busy or may not be active, which could delay the PR from being reviewed. 
- Your branch name is very detailed which is great, but something like
`img-tag-refactor-contributing-7097` is also good enough if you'd rather keep it simpler. It doesn't matter too much but as you've seen, using some characters like '#' can make things a little more complicated. 

Anyway, nice work on the issue.

**Comment by mSharifHub** [comment]
Hello,

Yes the branch should be kept detail but simple. Thanks for the feedback and approving it.

**Comment by terrencejihoonjung** [comment]
eta: today, 11:59pm PST
availability: 5pm - 9pm PST, Mon-Fri

**Review by terrencejihoonjung — APPROVED** [review]
Hi @mSharifHub,

- changes made and why they were made stated clearly
- concise, clear PR title
- branching is correct
- changes are correct in preview link

Well done! Thank you for your contribution :)

**Pull request merged**
