### PR TITLE
edit content field, removed type field from yml credits

### LINKED ISSUE #2775: Edit content field and remove type field from yml credit files
### Dependency
- [x] #2806
- [x] #2830 
- [x] #2833 
- [x] #2874
- [x] #2863 
- [x] #2864 
- [x] #2865 
- [x] #2861 
- [x] #2866 
- [x] #2867 
- [x] #2868 
- [x] #2869   
- [x] #2870 
- [x] #2871 
- [x] #2633
- [x] #2791
- [x] #2792
- [x] #2793
- [x] #2794
- [x] #2795
- [x] #2796
- [x] #2797
- [x] #2798
- [x] #2799
- [x] #2800 
- [x] #2804
- [x] #2810
- [x] #2805 
- [x] #2811
- [x] #2808
- [x] #2807
- [x] #2816
- [x] #2812
- [x] #2820 
- [x] #2813
- [x] #2815
- [x] #2809 
- [x] #2817
- [x] #2818 
- [x] #2814 
- [x] #2821 
- [x] #2822 
- [x] #2823 
- [x] #2824 
- [x] #2825 
- [x] #2831 
- [x] #2826 
- [x] #2827 
- [x] #2829 
- [x] #2828 
- [x] #2832 
- [x] #2834 
- [x] #2836
- [x] #2842 
- [x] #2843
- [x] #2844 
- [x] #2845 
- [x] #2846 
- [x] #2847 
- [x] #2848 
- [x] #2849 
- [x] #2850
- [x] #2851 
- [x] #2852 
- [x] #2853
- [x] #2855 
- [x] #2856
- [x] #2876 
- [x] #2877 
- [x] #2860
- [x] #2873
- [x] #2875 
- [x] #2857 
- [x] #2858 
- [x] #2859
- [x] #2878 

### Overview
As a developer, I want to edit the content field and remove the type field from all the credits' yml files so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

To incorporate this, the following will be implemented: the content field will be edited to content-type and the type field will be removed from each of the issues mentioned in the action items below. The issues will be created using the [Credits file template: Edit content field and remove type field](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Credit%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&template=credits-file-template--edit-content-field-and-remove-type-field.md&title=Edit+content+field+and+remove+type+field+from+%5BINSERT+FILE+NAME+HERE%5D.yml+credits+file). Once the issue is created the information will be updated in the following [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=0). Tech Leads will take a look at the issue before adding the ready for milestone label on each issue and the issue numbers to the Dependency section above.

The process for a developer to follow when writing an issue for this epic:
- Locate the yml file in the credits directory `website/_data/internal/credits`
- Change the content and type fields in the respective yml files

### Action Items
- [x] Write issues and add to the Dependency section above. See instructions in [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=456708813).
- [ ] Once all the issues in the Dependency section are checked off and closed, use the search function in your IDE to check the following for the .yml files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits):
  - [x] There is _**no**_ `content:` field in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits). (If you are using VSCode as your IDE, you can search for `content:` and restrict the search by filling in the "files to include" field with `_data\internal\credits`. Other IDEs may have similar search capabilities.)
    - [x] If you find any `content:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), list the .yml file(s) you found them in in a new comment below.
  - [x] There is _**no**_ `type:` field in any of the `.yml` files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits). If you see any `content-type: image` in your search, that is okay.
    - [x] If you find _**any**_ `type:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), list the .yml file(s) you found them in in a new comment below.
- [x] After you do the searches above,    
  - [x] If you find _**no**_ `content:` nor `type:` fields in any of the `.yml` files  in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits), then close this issue.
  - [x] If you find _**any**_ `content:` or `type:` fields in any of the `.yml` files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits),
    - [x] Then reach out to the [merge team and technical leads](https://github.com/hackforla/website/wiki/Meet-the-Team) with the list of .yml files that had `content:` or `type:` fields and ask them to help you write issues to fix what you found.

### Resources/Instructions
[Credits Page](https://www.hackforla.org/credits/)
[Credits file template: Edit content field and remove type field](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+P-Feature%3A+Credit%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&template=credits-file-template--edit-content-field-and-remove-type-field.md&title=Edit+content+field+and+remove+type+field+from+%5BINSERT+FILE+NAME+HERE%5D.yml+credits+file)
[Google spreadsheet for tracking issue creation progress](https://docs.google.com/spreadsheets/d/1yHo08dVVxI-Bvf_4MXJwMB9jSTr23pk_pydirWkgDgs/edit#gid=0)
Location of yml files in the credits directory `website/_data/internal/credits`

### LINKED ISSUE #2856: Edit content field and remove type field from process.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/process.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/process.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/process.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/process.yml#L11

### PR DESCRIPTION
**Pull request by luiderek**
Fixes #2856

### What changes did you make and why did you make them
for the file: `_data/internal/credits/process.yml`
  - replaced the `content` field with `content-type`
  - removed the `type` field

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 11/1/22 7:30pm
Availability: 2 hours

**Review by jyaymie — APPROVED** [review]
Fantastic job, @luiderek! You took care of all the action items without making any visible changes to the website. One thing I've been doing when coming up with a branch name is choosing the number of the dependency (in this case, #2856) rather than the issue it's being tracked by (#2775) so it's clear to reviewers that I am only managing the dependency.

**Comment by luiderek** [comment]
Yeah, I realized I put in the wrong issue # for my commit / branchname after making the pull request (i had a lot of different tabs open), but wasn't sure if undoing the pull request was the right move in this situation. Just gotta be more careful.

**Comment by jyaymie** [comment]
> Yeah, I realized I put in the wrong issue # for my commit / branchname after making the pull request (i had a lot of different tabs open), but wasn't sure if undoing the pull request was the right move in this situation. Just gotta be more careful.

Gotcha. I would've also committed to this PR and maybe included a small note for my oopsie. I'd be curious to know what the leads would do!

**Review by arpitapandya — CHANGES_REQUESTED** [review]
@luiderek to resolve that, can you check [here](https://github.com/luiderek/hfla-website/branches/active) and see if you can rename it. I see the automation got confused between labels.
I can merge PR, not a big issue but I don't want the number which is irrelevant as it's being tracked and may create other problems.

**Comment by luiderek** [comment]
Ah, it looks like renaming the branch kills it. Should I restore it or just open a new pull request?

**Comment by arpitapandya** [comment]
> Ah, it looks like renaming the branch kills it. Should I restore it or just open a new pull request?

Whatever is easy for you, I think its a small issue if you can create a new branch

**Comment by luiderek** [comment]
https://github.com/hackforla/website/pull/3689

**Pull request closed without merging**
