### PR TITLE
Standardize Slack channels using ID and archives: CONTRIBUTING.md Section 1.5

### LINKED ISSUE #6848: Standardize Slack channels using ID and archives: CONTRIBUTING.md Section 1.5
### Overview

We need to fix our reference to the hfla-site Slack channel in Section 1.5 of the CONTRIBUTING.md file to use the channel ID instead of the channel name, so that if the name gets changed, the link will still work. We are also changing the link to use archives instead of messages

### Action Items

- [x] In your IDE open the file `CONTRIBUTING.md`
- [x] In Section 1.5, look for the line that references the slack channel `hfla-site` by name `https://hackforla.slack.com/messages/hfla-site`
  - [x] This needs to be changed ONLY in Section 1.5, do not change other lines with the same references.
  - [x] Change the following:
  **From:**
  ```
  ...<strong><em>Feel free to reach out in the [Hack for LA Slack channel](https://hackforla.slack.com/messages/hfla-site/) if you have trouble installing ...
  ```
  **To:**
  ```
  ...<strong><em>Feel free to reach out in the [Hack for LA Slack channel](https://hackforla.slack.com/archives/C4UM52W93/) if you have trouble installing ...
  ```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository. 
  - [x] Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.
  - [x] Verify that the link still opens the `hfla-site` channel in Slack
  - [x] Also store the test URL for use in a later step:
  ```
  https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
  ```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions

- https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
- On the Slack desktop app, you can right click on a channel name, select `View channel details` and find the Channel ID in the bottom of the details pane. The `hfla-site` channel ID is: `C4UM52W93`
- This issue resulted from #6224 and aligns with #4535

### PR DESCRIPTION
**Pull request by dcotelessa**
Fixes #6848

### What changes did you make?
  - Change https://hackforla.slack.com/messages/hfla-site/ to https://hackforla.slack.com/archives/C4UM52W93/
  - Only in Section 1.5 on CONTRIBUTING.md
  - Tested on branch link

### Why did you make the changes (we will use this info to test)?
  - Change ONLY in Section 1.5 to link to Slack channel correctly
  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/dcotelessa/website-hackforla/blob/slack-channel-contributing-section-1.5-6848/CONTRIBUTING.md

### CODE REVIEW

**Review by freaky4wrld — APPROVED** [review]
@dcotelessa thanks for working on the issue
- branches looks good
- link to issue is correct
- changes made are correct and the link provided has the desired changes

PR approved!!

**Comment by moazDev1** [comment]
Availability: 6/12 5PM - 10PM
ETA: 6/12 EOD

**Review by ino-iosdev — APPROVED** [review]
Hi @dcotelessa , It's such a blessing to have you as part of the team here!
 
- Branch naming was appropriate
- Direction between branches `from` and `to` are clear
- The changes and why were clear
- PR issue ticket was properly linked
- Changes were only made in section 1.5
- Tested and the change was reflected in [https://github.com/dcotelessa/website/blob/slack-channel-contributing-section-1.5-6848/CONTRIBUTING.md ](url)
 
Great job, thank you for contributing!

**Review by moazDev1 — APPROVED** [review]
Hey @dcotelessa, Great job working in this issue and accomplish the following:
1. Using the correct branch
2. Making changes as requested in the issue
3. Clean and readable code
4. Changes appeared on the website without any issues

Keep going!

**Pull request merged**
