### PR TITLE
added _includes/svg/ to ignorePaths array in cspell.json

### LINKED ISSUE #5840: Add "_includes/svg/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "_includes/svg/" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by Limeload**
Fixes #5840 

### What changes did you make?
  - Add the path "_includes/svg/" to the end of the array "ignorePaths"
 

### Why did you make the changes (we will use this info to test)?
 - Good first issue - https://github.com/hackforla/website/issues/5840

### CODE REVIEW

**Comment by jphamtv** [comment]
Hi @Limeload, some items need to be addressed before this PR is ready to be reviewed.
- Link the issue number and transfer the labels from the issue to this PR
- Resolve the merge conflict ([How to Resolve Merge Conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts))
- If no changes to the website, comment 'No visual changes to the website' in your summary above.

Please follow the [How to make a pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31-how-to-make-a-pull-request) steps outlined in the contribution guide to ensure a complete pull request.

Also, don't request initial reviews from specific developers. They may not be available to review the PR immediately, and leaving the reviewers unassigned allows other team members to pick it up more quickly, increasing the chance of getting it merged sooner. 

Let me know if you have any questions. Thanks!

**Comment by ramitaarora** [comment]
i. Availability: Weekdays 9am-12pm
ii. ETA: Mar 28 EoD

**Review by ramitaarora — CHANGES_REQUESTED** [review]
Hey there! It looks like there are a couple of errors:

- please link the related issue in your pull request
- there is a merge conflict that needs to be resolved

Thanks! :)

**Comment by jphamtv** [comment]
Hi @Limeload,
Please provide an update if you're still working on this issue or leave a comment to let us know if you're not able to continue working on it. Please reach out if you need assistance. Thanks!

**Comment by Limeload** [comment]
No visual changes to the website

**Comment by ramitaarora** [comment]
Hey @Limeload, can you link the related issue in the first line of your pull request? :)

**Comment by Limeload** [comment]
> Hey @Limeload, can you link the related issue in the first line of your pull request? :)

Done.

**Review by jphamtv — APPROVED** [review]
Hey @Limeload - Great work resolving the merge conflict and thanks for working on this issue!

Positives:

- Pull request done with the correct branch
- Issue properly linked
- Code change is clean and accurate

Minor suggestions for future PRs:

- Provide a clear description in the "Why did you make the changes…" section, similar to the issue's overview (e.g., "To exclude the "_includes/svg/" file path from spell checking")
- Place comments like "No visual changes to website" in the summary of changes section

Check out [this PR](https://github.com/hackforla/website/pull/6561) for a good example. I'm approving this PR since it's non-functional changes that need to be made. Keep up the great work and keep these tips in mind for future PRs. Thanks

**Review by ramitaarora — APPROVED** [review]
Looks great!
- cspell.json now has "_includes/svg/" on line 26
- there are no merge conflicts

Great job! :)

**Pull request merged**
