### PR TITLE
Update CONTRIBUTING.md Section 2.7.f ii SSH for Windows

### LINKED ISSUE #5694: Update CONTRIBUTING.md Section 2.7.f ii SSH for Windows
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) we need to clarify the instructions in order to avoid confusion. 

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` Section 2.7.f i "Setting up SSH Keys for Windows"
- [x] Replace
```
4. Next you need to add your ssh key to your ssh agent.
```
with
```
4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) 
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by jleung7158**
Fixes #5694 

### What changes did you make?
  -  Replaced "4. Next you need to add your ssh key to your ssh agent." with "4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step."

### Why did you make the changes (we will use this info to test)?
  - In [CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"] we need to clarify the instructions in order to avoid confusion.
  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/jleung7158/website/blob/update-contributing-section-2.7/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
issue 5694 before changes
</details>

<details>
<summary>Visuals after changes are applied</summary>
issue 5694 after changes
</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Hi @jleung7158 Please correct the second bullet point under "Why did you make the changes (we will use this info to test)?" by replacing the text "[REPLACE WITH TEST URL]" with the test URL.  In the 3rd bullet point you indicate the format of the test URL but you need to replace the text "[REPLACE WITH GITHUB HANDLE]" and "[REPLACE WITH NAME OF ISSUE BRANCH]" as directed.

**Comment by jleung7158** [comment]
Thank you Roslyn @roslynwythe! I have made the changes to this pull request as requested by you.

**Review by Tomomi-K1 — DISMISSED** [review]
@jleung7158 Great job 🙌🏻 updating the contribution documents. You have used correct branches, linked the correct issue and fixed as it is instructed in the issue.

Thank you!😊

**Comment by Tomomi-K1** [comment]
Availability: weekday 12-5pm

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: 12/13

**Review by freaky4wrld — APPROVED** [review]
this approval is done by mistake while reviewing the issue, sorry for that. Changes are requested below

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
@jleung7158 I see you have also made extra changes in the file `expunge-assist.md` and in the `CONTRIBUTING.md` you have repeated the content of `line 32` at `line 33`, made some changes at `line 44 and 47` can I know the reason why?

**Comment by jleung7158** [comment]
@freaky4wrld Sorry about that, they must have come in when I was updating the branch upstream. I will fix that asap!

**Review by freaky4wrld — DISMISSED** [review]
@jleung7158 the recent commits looks good and as per the issue, good work with resolving the error...... I approve this !!!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @jleung7158 - I am looking at the current changes and I am still seeing the duplicate line 33 and the extra changes at lines 44 and 47 that @freaky4wrld referenced- please remove the duplicate line 33 and the added '\' characters on lines 43 and 47. Thanks!  

<details>
Screenshot 2023-12-17 201643</details>

**Review by t-will-gillis — APPROVED** [review]
Hi @jleung7158 Thanks for making the changes! Issue is good to go

**Pull request merged**
