### PR TITLE
Added github-handle for Ron Fu in Civic Tech Index

### LINKED ISSUE #6178: Add github-handle for Ron Fu in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-index.md` in the IDE
- [x] Replace:
```
- name: Ron Fu
```
with
```
- name: Ron Fu
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by urvishp13**
Fixes #6178 

### What changes did you make?
  - added `github-handle:` variable under Ron Fu's `name` variable. Used spaces to indent.

### Why did you make the changes (we will use this info to test)?
  - To use a single variable `github-handle` to hold the github handle, eventually replacing the github and picture variables, to reduce redundancy in the project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Added a variable to the file. No visual changes were made to the website.

### CODE REVIEW

**Comment by tony1ee** [comment]
**Review ETA**: EOD 04/13/2024
**Availability**: 12-8 PM SAT

**Review by tony1ee — APPROVED** [review]
Good job @urvishp13 !
1. correct branch for pull request and name checks out
2. issue is linked
3. verified no visible changes in developer mode on Chrome (Desktop, tablet, and mobile view), Firefox, and Safari.
4. source code changes appear to be applicable and clean

Note that I've edited the your comment for a clearer explanation for the changes made.

**Comment by robertnjenga** [comment]
Review ETA:  04/13/2024
Availability: 12pm - 4pm

**Review by robertnjenga — APPROVED** [review]
Hi @urvishp13 
- The branching was done correctly, you used correct branch to commit from and into.
- You linked the issue.
- Code changes were made correctly as stated in the issue.
- I'm able to confirm in Docker that the appearance of the project webpage is unchanged. 
Nice Work!

**Pull request merged**
