### PR TITLE
Refactored HTML on the about page sponsors card

### LINKED ISSUE #5288: Refactor HTML to resolve linter error: _includes/about-page/about-card-sponsors.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sponsors.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about'>
```
to
```
<div class="card-primary page-card-lg page-card--about">
```
- [x] Using Docker, check the `About Us` page (permalink `/about/`) remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sponsors.html
2. 'About Us` webpage: https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by allison-truhlar**
Fixes #5288

### What changes did you make?
  - Updated HTML tag to change single quotes around class names to double quotes

### Why did you make the changes (we will use this info to test)?
  - To resolve a linter error: "Value of attribute [class] must be in double quotes"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes caused by refactoring HTML for class attribute.

### CODE REVIEW

**Comment by Jmmcclo2023** [comment]
Availability: 4-6pm EDT Daily
ETA: 8/30

**Comment by evanhesketh** [comment]
Availability: 9-10am EDT Tuesday, Wednesday
ETA: EOD 08/28

**Review by evanhesketh — APPROVED** [review]
Branching is done correctly, the issue is linked, and changes made address the issue. There were no visual changes to the website.

One minor detail that was momentarily confusing: your comment on the PR regarding what changes were made suggests you changed double quotes to single quotes, when what you did was the opposite (correctly). 

Otherwise, looks great!

**Comment by Jmmcclo2023** [comment]
Great job completing the issue! 
As Evan stated above, you might need to edit the pull request to correctly state the changes of your issue to match what you actually did.
Otherwise, everything looks good!
This post contains the correct branch and the correctly linked issue, no screenshots since there are no visual changes, all changes are done in the correct file, all applicable action items are completed, and the source code looks good!

**Review by Jmmcclo2023 — APPROVED** [review]
Great job completing the issue!

As Evan stated above, you might need to edit the pull request to correctly state the changes of your issue to match what you actually did.
Otherwise, everything looks good! This post contains the correct branch and the correctly linked issue, no screenshots since there are no visual changes, all changes are done in the correct file, all applicable action items are completed, and the source code looks good!

**Comment by allison-truhlar** [comment]
Thanks, @evanhesketh and @Jmmcclo2023 for catching the error in my opening comment! I have edited it to correctly reflect the change from single quotes to double quotes.

**Pull request merged**
