### PR TITLE
Add Unique iDs for each wins entry

### LINKED ISSUE #2385: Google Apps Script: Add unique IDs as object keys for each wins entry
### Dependency 
- [x] #3722
- [x] #3641
- [x] #4134
- [x] #2147

### Overview
To expedite the process of locating a specific wins entry, each wins entry (which is also a javascript object) should have a unique ID as a key.

### Action Items
- [x] Follow sections 1-3 in the Wins Apps Script Development Process[^3].  Note that in this issue you will be modifying both Apps Scripts `wins-form-responses` and `gh-requests` so setup will be required in both `/google-apps-script/wins-form-responses` and `/google-apps-script/gh-requests` 
- [x] As described in section 3a and 3b, you will provide a dev lead with the google account you wish to use for testing, and request the dev lead to:
   - do not modify folder level access
   -  share the Wins Form Admin Guide[^1] as VIEWER 
   -  share the Wins-form (Response)[^2] sheet as VIEWER
   -  share the gh-requests doc as VIEWER
- [x] Continue following instructions in 3c and d.  As described in 3d, you will have to make modifications to certain documents in the test folder. 
   - [x] It will not be necessary to restore any triggers, because you can execute `main()` in debug mode. 
   - [x] Since you will be running `main()` for testing, you must follow instructions in [Testing WINS in a test repository](https://github.com/hackforla/website/issues/5746#issuecomment-1846549069)
- [x] Continue following instructions through section 6 "Editing".  As described in this section, editing can be done locally in an IDE or in the Google Drive cloud editor, and the `clasp` utility can be used to transfer code back and forth between the local worksation and the Google Drive as needed. 
    - [x] Modify wins so that on the creation of the javascript object for each entry, a unique ID is generated as well
    - [x] This ID can be the row number of the wins entry
- [x] Ensure that even with the addition of the unique IDs as keys, the current wins page should functionally look and work the same way in your own repo. 
- [ ] Demo your changes to the website leads so they can approve and add it to the production script

### Resources/Instructions
[Google Apps Script](https://developers.google.com/apps-script/overview)
[_wins-data file](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json)
[wins page JS](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
[^1]:[Wins Form Admin Guide](https://docs.google.com/document/d/1j1JTX5XzotgVCVZ91ImvenedPN5-IVjdSKDukq1B9iE/edit?usp=drive_link)
[^2]:[Wins-form (Response) Sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit?usp=drive_link)
[^3]:[Wins Apps Script Development Process](https://github.com/hackforla/website/issues/4134#issuecomment-1741851926)

### PR DESCRIPTION
**Pull request by lopezpedres**
Fixes #2385

### What changes did you make and why did you make them?

  - Added Unique IDs for each object
  - Refactored App Script Code 
  - Tested in my Personal GitHub Repo

<details>
<summary>Video of applied changes</summary>

The main goal of the video is to show how the unique IDs are added to the wins object

https://user-images.githubusercontent.com/63615112/147504648-bf8f1243-e2ce-4a27-a8fc-5cdc03f581da.mp4

</details>

### CODE REVIEW

**Comment by lopezpedres** [comment]
Once this PR gets approved, the actual App Script is going to be modified :)

**Comment by SAUMILDHANKAR** [comment]
@lopezpedres Hi Miguel, thanks for working on the issue and adding the video. It looks good. Is line 44 the only change that you made in the App script? Let me know when you are available to go over the changes. We can test if all the sections are still working fine. I don't think we need to merge this. Once done we can just close the issue.

**Review by SAUMILDHANKAR — COMMENTED** [review]
Please share the code changes that you made in your App Scrip.

**Comment by lopezpedres** [comment]
> @lopezpedres Hi Miguel, thanks for working on the issue and adding the video. It looks good. Is line 44 the only change that you made in the App script? Let me know when you are available to go over the changes. We can test if all the sections are still working fine. I don't think we need to merge this. Once done we can just close the issue.

Hi @SAUMILDHANKAR, yes It's only one line! It was a pretty easy issue. The hard part was to get familiar with App Script and to find the reason why my code wasn't working.  We can go over the changes this Tuesday if you are free, maybe in-office hours?

**Comment by SAUMILDHANKAR** [comment]
@lopezpedres Thanks Miguel. Lets go over it during the office hours. I wanted to discuss the case where if one of the rows' display value is changed to false, the unique IDs will change. If we can use timestamp as the unique ID instead, this could be resolved since they are more unique.

**Comment by lopezpedres** [comment]
> @lopezpedres Thanks Miguel. Lets go over it during the office hours. I wanted to discuss the case where if one of the rows' display value is changed to false, the unique IDs will change. If we can use timestamp as the unique ID instead, this could be resolved since they are more unique.

@SAUMILDHANKAR That sounds like a good idea! I can start working on it 👍

**Comment by SAUMILDHANKAR** [comment]
Review ETA: 2/15/22
Availability: Friday 3-6 PM

**Comment by SAUMILDHANKAR** [comment]
I am closing this PR as there is no need to merge _wins-data.json file. For this issue, data should get merged through the bot account. The code changes suggested by Miguel are in a comment in the issue. Also, adding ignore label as there is no need of QA on this and all the information is available in the linked issue. Thanks Miguel for working on this. Great job!

**Pull request closed without merging**
