### PR TITLE
Add github-handle for Aleiya Gafar in brigade-organizers-playbook.md

### LINKED ISSUE #6154: Add github-handle for Aleiya Gafar in brigade-organizers-playbook.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/brigade-organizers-playbook.md` in the IDE
- [x] Replace:
```
- name: Aleiya Gafar
```
with
```
- name: Aleiya Gafar
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/brigade-organizers-playbook

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Jperparas**
Fixes #6154

### What changes did you make?
  - added github-handle: under name: Aleiya Gafar in _projects/brigade-organizers-playbook.md

### Why did you make the changes (we will use this info to test)?
  - Reduce redundancy

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
-No visual changes to website

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by agutiernc** [comment]
Availability: 3/12
ETA: EoD 3/12

**Comment by colin-macrae** [comment]
Availability: 3/12-14
ETA:  3/14

**Comment by agutiernc** [comment]
Thanks your contribution, @Jperparas ! I have one request for a change regarding the branch name:

- Please name your branch to follow the guidelines in [section 2.7.b, of the Contributing doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue). The branch name should relate to the issue being addressed and include the issue number.

Other than that, the addition of the `github-handle` variable looks good. Once you've updated the branch name, I'll be happy to approve.

**Comment by Jperparas** [comment]
> Thanks your contribution, @Jperparas ! I have one request for a change regarding the branch name:
> 
>     * Please name your branch to follow the guidelines in [section 2.7.b, of the Contributing doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue). The branch name should relate to the issue being addressed and include the issue number.
> 
> 
> Other than that, the addition of the `github-handle` variable looks good. Once you've updated the branch name, I'll be happy to approve.

had to close this to rename branch new pull request at #6457

**Pull request closed without merging**
