### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by 5HAD0W-P1R4T3**

### CODE REVIEW

**Review by ExperimentsInHonesty — CHANGES_REQUESTED** [review]
Hi Rahul ( @5HAD0W-P1R4T3). Thanks for catching the missing colons on the steps.  It looks like there are a few more you missed (step 1, 2 and 3).  Can you do those and update your PR?

**Review by 5HAD0W-P1R4T3 — COMMENTED** [review]
Done! Can you pls recheck

**Comment by KianBadie** [comment]
@ExperimentsInHonesty @5HAD0W-P1R4T3 It looks like the readme file was renamed to "Improved Docs". I think it would be a good idea to keep the file name the same as it originally was. Thoughts @ExperimentsInHonesty?

**Comment by 5HAD0W-P1R4T3** [comment]
@KianBadie Yup i didn't noticed , it was changed by a mistake

**Comment by 5HAD0W-P1R4T3** [comment]
@KianBadie I have changed the title to README.md 3 days ago.

**Comment by KianBadie** [comment]
@5HAD0W-P1R4T3 Are those changes pushed to your remote branch? The "Files changed" section of this pull request still looks like the file is named "Improved Docs" (screenshot below). Also, sorry for the delay in response to your request for review 4 days ago! 
 
Screenshot from 2020-10-07 16-43-58

**Review by 5HAD0W-P1R4T3 — COMMENTED** [review]
@KianBadie Sorry, my bad, now changed the readme file to README.md

**Comment by KianBadie** [comment]
@5HAD0W-P1R4T3 no worries, thank you for contributing!

**Pull request merged**
