### PR TITLE
1413 add comm of practice icon and text to get start page

### PR DESCRIPTION
**Pull request by RobertaFricker**
This one took a lot of time and when I finally got it right, I forgot to add the commit message.
Fixes Issue #1413 
See screenshots below:

image

image

The details on who the artist is for the icon will have to be added later.  I have to move on from this issue.

### CODE REVIEW

**Comment by RobertaFricker** [comment]
@daniellex0   Hello Danielle, would you please provide the artist and provider information for the Comm of Practice icon so that I can add it to the Credits page, thanks.
image

**Comment by daniellex0** [comment]
@RobertaFricker Sute, FYI the source link is to the right of the mockup-

https://thenounproject.com/term/meeting/28970/

But here are the details:

Name: Meeting

Used in: Getting Started

Artist: froz

Provider: Freepik

**Comment by RobertaFricker** [comment]
@daniellex0. Gracias...🐸

**Review by erikaBell — APPROVED** [review]
Looks good!

**Pull request merged**
