### PR TITLE
img tag refactor in CONTRIBUTING.md Sec 2.3 

### PR DESCRIPTION
**Pull request by codyyjxn**
Issue #7095

### What changes did you make?
 - Changed an img HTML tag ending with a slash () to an img tag without an ending slash () 
 

### Why did you make the changes (we will use this info to test)?
  -  The over all goal was to change img tag so that the codebase is consistent with how we use img HTML tags.
  
  - https://github.com/codyyjxn/website/blob/update-codyyjxn-7219/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Anahisv23** [comment]
Availability: M - F 12pm - 5pm
ETA: Friday

**Comment by codyyjxn** [comment]
Yes, I am available.

**Comment by Anahisv23** [comment]
Hi @codyyjxn, thanks for working on this issue. Nice job mentioning what you changed! There are a few things you need to fix to ensure this PR can be reviewed. 

1. You need to replace this text `replace_this_text_with_the_issue_number` with the number of your issue. This can be found in the title of the issue you worked on. 
2. On the section of this PR where it says 'Why did you make the changes?' if you could be a bit more specific on why you changed what you did. Perhaps mentioning what the overall goal of the ticket was, would be very helpful. 
3. I believe you also have some merge conflicts. Go ahead and fix those. I'll link the documentation here to aid you with that https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31d-dealing-with-merge-conflicts

Let me know if you need help. Goodluck!

**Comment by codyyjxn** [comment]
Hi. Thanks for the reply. I actually fixed the first two but I can't seem
to fix the third step. I read through the documentation and did the same
steps but I can't seem to fix it.
Thanks in advance.

**Comment by Anahisv23** [comment]
Hey @codyyjxn, nice work fixing the first two issues! I think you just need to click on the resolve conflicts button on this PR and remove line 390, line 398, and line 399. I'm also seeing you modified a README.md file. I'm not sure if that was within the scope of this issue, if not remove it from the commit. Also I believe you forgot to add this section "https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md"  to your PR for reviewers to test. Let me know if you have questions. Happy to help :)

**Comment by Anahisv23** [comment]
Hey @codyyjxn, I think you still need to remove the README.md file from your commit.

**Comment by Anahisv23** [comment]
Hi @codyyjxn thanks for removing the other files from your commit. Everything looks good on my end! Nice job approved!

**Review by Anahisv23 — DISMISSED** [review]
Hi @codyyjxn thanks for removing the other files from your commit. Everything looks good on my end! Nice job approved!

**Comment by codyyjxn** [comment]
Thank you so much, **@Anahisv23**, for your patience and the time you dedicated to helping me. Your detailed explanations on how to fix my commits were incredibly helpful and greatly appreciated.

**Comment by Anahisv23** [comment]
@codyyjxn Of course! Nice work implementing the feedback. Keep up the good work!

**Comment by t-will-gillis** [comment]
Hi @codyyjxn Please see the comments on #7095. You need to complete the requirements in the "Skills Issue" before taking on a `Complexity: Small` issue. 
Thanks!

**Pull request closed without merging**
