### PR TITLE
Fixes Add github-handle for Adrian Inchauste in heart.md #6934

### LINKED ISSUE #6934: Add github-handle for Adrian Inchauste in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [ ] Open the file `_projects/heart.md` in the IDE
- [ ] Replace:
```
- name: Adrian Inchauste
```
with
```
- name: Adrian Inchauste
  github-handle: 
```
- [ ] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by mSharifHub**
Fixes #6934

### What changes did you make?
- Added `github-handle:  ` to `heart.md`.

### Why did you make the changes (we will use this info to test)?
-  added github handle on heart.md file

### Screenshots of Proposed Changes Of The Website (if any, please do not screenshot code changes)
No visual changes

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>

</details>

### CODE REVIEW

**Comment by dcotelessa** [comment]
Hi Mohamed!
Thanks for the PR.
A couple things:
- on the link in the PR description (Fixes #6982), can we set the link to:
https://github.com/hackforla/website/issues/6934 and change the number to the ticket number (Fixes #6934). We don't have to link to the PR, since we are already here.
- Also, the github-handle should be blank as the task on the ticket describes. We will be adding the handle later.

Thank you.

**Review by dcotelessa — CHANGES_REQUESTED** [review]
Check my comment.

Available: 9-5 T-F

**Review by dcotelessa — CHANGES_REQUESTED** [review]
More feedback:
- Thank you for updating the file. Looks good.
- The description still isn't updated with ticket number. 
- The screenshot information is still there.
If you look at this latest PR, it might help you with the description:
https://github.com/hackforla/website/pull/6984#pullrequestreview-2111474105
Once we update that, I'll recheck.

Thanks for your contribution!

**Comment by ino-iosdev** [comment]
ETA: Eod

**Review by ino-iosdev — CHANGES_REQUESTED** [review]
@mSharifHub 

- Branch naming is good

### Changes required:

1. Remove `6934` from the title (note how it becomes unclear since it stacks with your PR number `6982`), replace`Fixed Add` to something like `Added` in title, this is to make is clear and readable as possible.

2. Properly link the issue following the auto-generated template guide, seems like you removed that line, it would look something like this:
Screenshot 2024-06-11 at 6 28 26 PM

3. Update your description on the changes made, I can see that you made changes in the file, but your description still has his name attached to `github-handle:`

Screenshot 2024-06-11 at 6 40 20 PM
](url)
 
4. Revise the `Why did you make the changes` answer: In general, it's a good practice to write details in your own words based on the request from the issue, see below from the original issue page

**_Check out this example of a similar issue for your reference #6917_** 

5. No need to include screenshots unless your change will have any visual change to the website. Simply write "No visual change to the website" under the template guideline should suffice.

After making all these changes, don't forget to click on something like this on the top right of your page (see below) to request a review of your changes:

Screenshot 2024-06-06 at 8 45 27 PM

**Review by dcotelessa — APPROVED** [review]
We went through code during Tuesday zoom:
- PR Number is updated
- github-handle is added correctly.

Good work!

**Review by ino-iosdev — CHANGES_REQUESTED** [review]
Thanks for making those changes @mSharifHub 

Please address 1 and 4 in the previous change request, we are almost there!
Thank you!

**Comment by del9ra** [comment]
ETA: 06/13/2024
Availability: 1-5 PM monday-friday

**Review by del9ra — CHANGES_REQUESTED** [review]
Hi @mSharifHub, 
Nice job!
* The branching was done correctly
* No need to mention issue number in the PR title. Follow the example from the Contributing Guide: “Update Care Link in Credits Page”. Refer to this guide https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md 
* Issue number was listed
* Not all pull requests will have significant changes to our website. Please do not do any screenshots of VSCode If you do not have the ability to notate changes, please remove this part "details>/<summary" and replace it with an explanation for no images like:
		### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
		No visual changes to the website. 
	Please refer to the Contributing Guide: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md 
* Changes were made correctly in the code
* The PR request clearly states what was updated
* Please mark up “Action items” on the issue page https://github.com/hackforla/website/issues/6934
* Please provide a more detailed explanation of why the changes are being made
Thank you for contributing to the website!

**Review by ino-iosdev — CHANGES_REQUESTED** [review]
@mSharifHub 

- Change 1 out of 5 hasn't been addressed, please reference the requested 5 changes in my previous comment.

- Change 4 out of 5 still needs revision, it's not about repeating the change you made, but rather why the change needs to be made, again, please reference the good example linked in my previous comment. 

Thank you so much!

**Comment by Thinking-Panda** [comment]
@mSharifHub Please post an update on your progress in regards to the changes requested. If you need any help, please reach out  on slack hfla-site channel.

**Comment by t-will-gillis** [comment]
@mSharifHub Please post an update on this PR and let us know when you plan to complete it. Thanks.

**Comment by t-will-gillis** [comment]
Hi @mSharifHub Unfortunately, there is a duplicate issue for this issue, so this PR and the original issue need to be closed. Sorry for the mixup.

Closing this because there was a duplicate issue for this ( #7045 )

**Pull request closed without merging**
