### PR TITLE
Wins page: desktop and mobile view

### LINKED ISSUE #1425: Add badges to the wins overlay
### Dependency
#1313

### Overview
Redesign the win's page overlay to include the badges

### Action Items
- [ ] redesign the wins page overlay to match the figma (in blue rectangle)
- [ ] get the icons from the win icon object
- [ ] include the text of the win
- [ ] style it to look like the figma (in blue rectnagle)

### Resources/Instructions
[figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle)

### LINKED ISSUE #1432: Wins badge mobile view
### Dependency
#1313

### Overview
Mobile view for wins badges

### Action Items
- [ ] make sure the cards are styled like they are in the figma
- [ ] when see more is clicked, and the card drops down.... make that part look like the figma too
- [ ] give yourself a high five

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Figma file for the Wins page badges](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in **blue rectangle**)

### PR DESCRIPTION
**Pull request by erikaBell**
Fixes #1432 
Fixes #1425 

Have added badge elements and functionality to wins page. Please refer to the [Figma Design, blue rectangle](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) for a full overview of what I have done. 

Edit, my personal changes are found on the following files: 
- `_sass/components/_wins-page.scss`
- `pages/wins/wins-overlay.html`
-  `pages/wins/wins.html`  

The star badges are currently bugged and a separate issue has been made for those: Issue #1439 

Due to the complexity of how things are hooked up, I did not make the "best" choices at all times...this is written for Akib lol.

### CODE REVIEW

**Review by akibrhast — CHANGES_REQUESTED** [review]
There seems to be an excess amount of files in this pull request that has nothing to do with the files worked on. Could you please clean up your PR. 

Also from looking at this PR it seems to me that it is requesting a review for merging into hackforla:wins-feature-1 from erikaBell:wins-feature-1.. Since that is a development merge that is not even live is the PR review necessary at this stage yet ?

@jbubar Please advise. Since I am not sure what should be done in this situation.

**Comment by daniellex0** [comment]
Oh wow.. @erikaBell .. this is looking AMAZING!! So exciting to see it come to life, I'm truly in awe!! I mean, the text bubble functionality alone! And the overlay!! I know this was probably crazyyyy difficult to bring to this point with the million different icons and all, so thank you!! We're not worthy!! 🥇 

Ok so my notes so far are:

- Can the badges all be hex# AEAEAE ? (Sorry there is probably no variable yet for this color. Also I couldn't figure out which class this property could go into..)
- Can the badge that is being hovered over turn into dark gray color (# 333333) ?
- Can the hover bubble text (".wins-text-bubble") have the property font-family: arial removed (I think this should automatically make it roboto instead)
- Can ".wins-icon-container" margin be turned into **1.5em** 0 0 6.5rem (so that there is a little less margin below the paragraph)
- Can ".wins-badge-icon" max-width be changed to **1.7em** (so that the icons are a little smaller)?
- Can ".overlay-badge-icon" max-width be changed to **1.5rem** (so that the icons are a little bigger)?
- I'll leave mobile comments out because that's probably not ready yet. I won't blame you if you pass that part off to someone else lol.

Thank you!!! 🙏

**Comment by erikaBell** [comment]
@daniellex0 Would love your mobile view critique as well! I will also be taking that on ~ ~ (-:

**Comment by erikaBell** [comment]
@daniellex0 have made the above design changes

**Comment by jbubar** [comment]
Hey @erikaBell hit me up about this. I think that you may have merged upstream-gh-pages into your branch?? I think that is why there are all these files. We can figure this out

**Pull request closed without merging**
