### PR TITLE
Added Github-handle for Rachel Newcomb

### LINKED ISSUE #6705: Add github-handle for Rachel Newcomb in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Rachel Newcomb
```
with
```
- name: Rachel Newcomb
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jenjenkayi**
Fixes #6705 

### What changes did you make?
  - Added github-handle for Rachel Newcomb in design-systems.md.

### Why did you make the changes (we will use this info to test)?
  - Reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - Adding github-handle to the file. No visual changes to the website.

### CODE REVIEW

**Comment by moazDev1** [comment]
Availability: 5/3 6PM - 9PM
ETA: EOD 5/3

**Review by moazDev1 — APPROVED** [review]
Hey @jenjenkayi, Great job on:

1. Using the correct branch for your pull request.
2. Accurately linking the issue.
3. Making code changes as requested in the issue
4. Ensuring no visual changes across multiple browsers (Safari, Firefox, Chrome) in both desktop and mobile views.
5. Applicable and clean code changes.

Keep going!!

**Comment by DeniseLewis1** [comment]
Availability: 5/3 11AM - 3PM
Review ETA: End of day 5/3

**Review by DeniseLewis1 — APPROVED** [review]
Thank you for your contribution @jenjenkayi great work!

- Used correct branch for pull request
- Correctly linked the issue
- Used spaces instead of tab in the right file
- Confirmed no visual changes across Firefox and Chrome in desktop, mobile, and tablet views

**Pull request merged**
