### PR TITLE
Update Team Meeting Data on Events Page to show Meeting Frequency

### LINKED ISSUE #6920: Update Team Meeting data on the Events page to show meeting frequency
### Overview
Currently the Online Project Team Meeting section of Events page has Day, Start Time, End Time, Name of Project, and Name of Meeting. As some of the meetings do not happen weekly (like Onboarding), we need to mark those meetings and add a message to visit project page for more information.

### Action Items
- [x] Analyze and understand the data in `_data/external/vrms_data.json`
- [x] Update Team Meeting data on the Events page to add asterisk to the end of "Name of Meeting" if it's not weekly.
- [x] Add the following text to the end of the "Online Project Team Meetings" section.
     ```
     *This meeting is not weekly, check project link for more details.
     ```
- [x] Using Docker, check the changes on your local machine 

### Resources/Instructions
- [Event Page](https://www.hackforla.org/events/)
- [JSON Data File](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
- [Js File](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js)
- [HTML File](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html)
- This issue was created from #6320

### PR DESCRIPTION
**Pull request by terrencejihoonjung**
Fixes #6920 

### What changes did you make?
  - added `*This meeting is not weekly, check project link for more details.` at the bottom of the `right-col-content.html`
  - conditionally rendered an asterisk if the event's description was not empty within `right-col-content.js`

### Why did you make the changes (we will use this info to test)?
  - to indicate that an asterisk means that the meeting is not necessarily weekly
  - when the event description is not empty, it contains information about an alternative meeting schedule. By rendering an asterisk when the event description is not empty, we indicate that the meeting is not weekly. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by ha-bach** [comment]
Review ETA: end of day.
Availability: Sunday, Monday, Wednesday.

**Review by ha-bach — CHANGES_REQUESTED** [review]
Hi @terrencejihoonjung,

- branching looks good
- relevant linked issue
- code edit is clean
- correct changes showed up on my test page

Issues to address:

- merge conflict with current version of website at _data/external/github-data.json

Overall great work! Just one file is outdated from the current website. Once you've fixed the merge conflict, feel free to @ me and I will review the PR again.

**Comment by terrencejihoonjung** [comment]
Hi @muninnhugin,

Thank you for your feedback! I've handled the merge conflict and updated my branch. 

Thank you!

**Review by ha-bach — APPROVED** [review]
Of course, thank you for your contribution!

**Comment by jphamtv** [comment]
Hi @Thinking-Panda - Please add your ETA and availability for this review when you get a chance. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hi @terrencejihoonjung I am able to load this in Docker and cross check with `vrms-data.json` to see that whenever a meeting lists a `description`, an `*` is rendered on the "Events" page. 

Great job, and thanks for taking care of this.

**Pull request merged**
