### PR TITLE
Added Leader

### LINKED ISSUE #5757: Update Project Profile: Expunge Assist (Add Lane Mitchell)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Lane Mitchell
    github-handle: lmitch10
    role: Product Manager, Development
    links:
      slack: https://hackforla.slack.com/team/U052LEP0BSN
      github: https://github.com/lmitch10
    picture: https://avatars.githubusercontent.com/lmitch10
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      
    </details>

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by zip-dazie**
Fixes #5757 

### What changes did you make?
Added Lane Mitchel to Project Profile: Expunge Assist

### Why did you make the changes (we will use this info to test)?
To keep project team info up to date.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

Before

<details>
<summary>Visuals after changes are applied</summary>

After

### CODE REVIEW

**Comment by freaky4wrld** [comment]
ETA: EOD 11/22
Availability: Evenings

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
Hey there @zip-dazie , this PR that you generated doesn't look usual, it is missing the labels, also no GHA(Github Actions) done on this one, plus the issue that you are originally assigned for doesn't seem to have `action items` checked.
Also the screenshot in the PR description is also not shown

I think the best would be close this particular PR and create a new one.........

**Comment by heejung-hong** [comment]
Review ETA: 6 PM 11/22/23
Availability: 5-8 PM Weekdays

**Review by heejung-hong — DISMISSED** [review]
The labels have been added, the before and after pictures are now visible.  This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by adding Lane's info line 25-31. The code looks clean, only one commit and only one file changed.  
The changes were verified in www.hackforla.org/projects/expunge-assist and localhost:4000/projects/expunge-assist
Good job!!

The command below was used to check in my project repository. 
git checkout -b zip-dazie-add-leader-5823 gh-pages
git pull https://github.com/zip-dazie/website.git add-leader-5823

**Comment by mademarc** [comment]
Review ETA: 11/22/2023
Availability: 7:43PM

**Review by mademarc — DISMISSED** [review]
Hey @zip-dazie  great job to the added changes requested for this page.

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
Hey there @zip-dazie can you please remove the extra-spaces (new lines) you added on line `24, 32, 61`. Great effort in making your code highlighted for the reviewers but I guess it disrupts the `code consistency/code style` of the file. Rest of the issue is cool.....
- the to and from branch is good
- the visuals are perfect now and are similar to the one in the local environment
- the labels are added manually and correctly
- the changes are as specified and are apt

Jus do the one thing and I'll approve it!!

**Comment by ExperimentsInHonesty** [comment]
@freaky4wrld good job catching the extra spaces.  @zip-dazie please remove those extra spaces so we can merge this.

**Review by freaky4wrld — APPROVED** [review]
Hi there , great work there all the work assigned to you in the issue is done correctly
- the to/from branch looks good
- the visual changes are completely applied in the local environment
- the changes specified is done correctly and are apt
- the issue linked is correct too

Great work there, I approve this PR.......

**Pull request merged**
