### PR TITLE
added credits for all badge icons on the wins page

### LINKED ISSUE #2078: Add all Wins page badge icon credits to Credits page
### Overview
We need to add all of the Wins page badge icons’ credit information to the [Credits page](https://www.hackforla.org/credits/) to follow image use compliance standards

### Action Items
- [x] Locate all icon credit information in [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9246%3A80729) (in green rectangle on bottom right)
- [x] Add all of the icon credit information to the [Credits page](https://www.hackforla.org/credits/)
### Resources/Instructions
Icon credit information in [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9246%3A80729) (in green rectangle on bottom right)
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Wins page](https://www.hackforla.org/wins/)

### PR DESCRIPTION
**Pull request by aalieu**
Fixes #2078
### What changes did you make and why did you make them ?

  -Added credits for all the Wins page badge icons
  -Did not add first mentor and avatar credits because they are not used in the Wins page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by Aveline-art — CHANGES_REQUESTED** [review]
Great work @aalieu ! I think the avatar is actually used; not as a badge, but as a placeholder. Can you add this into the credits?

<details>
<summary>Avatar icon</summary>
<br>

<br>
</details>

Besides that, the GitHub and Linkedin icons are deliberately left out in Figma. @hackforla/website-design, are we going to add the GitHub and Linkedin icons?

**Comment by aalieu** [comment]
Thanks @Aveline-art for the review! Also, sorry for mistake – I don't know how I missed the big avatar icon on the Wins page. I will wait for an update from @hackforla/website-design about the GitHub and LinkedIn icons before I update this PR.

**Comment by Aveline-art** [comment]
> 
> 
> Thanks @Aveline-art for the review! Also, sorry for mistake – I don't know how I missed the big avatar icon on the Wins page. I will wait for an update from @hackforla/website-design about the GitHub and LinkedIn icons before I update this PR.

@aalieu To prevent needless waiting, if website-design or admin does not jump in with an answer by tomorrow morning, feel free to just add the avatar credits, and we can close out the issue. The question about the GH and LI icons will be resolved under UAT, so there is no need to wait for other teams for answers.

**Comment by aalieu** [comment]
Updated PR to include the avatar credit. Should be ready to merge pending a final review.

**Review by Aveline-art — APPROVED** [review]
Good work on this! @aalieu I've noticed that all the errors in the Figma was also checked and corrected. Very detail-oriented!

**Pull request merged**
