### PR TITLE
Oliviazhai update project information 4211

### LINKED ISSUE #4211: Update Project Information: Access the Data
### Overview
The Access the Data page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Download a copy of the Access the Data [One Sheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/AtD-one-sheet.pdf) from the product management repo
  - [x] Replace the current Access the Data One Sheet in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs) 
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/access-the-data.md` file and find the `leadership` variable.
- [x] Remove Mariana Melo-Vega and their information
- [x] Verify the changes by viewing the [Access the Data project page](https://www.hackforla.org/projects/access-the-data) on your local environment and include a screenshot with your pull request
  - [x] Ensure that the "Overview" hyperlink links to the new One Sheet
- [x] Remove the following variables (and their text content) from the access-the-data.md file
  - [x]  `problem` 
  - [x] `solution`
  - [x]  `impact`

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by oliviazhai**
Fixes #4211 

### The changes I made

  - Replace the old Access the Data one sheet with the updated one
  - Remove Mariana Melo-Vega from the leadership 
  - remove variables: project, solution, and impact from the access-the-data.md file

### Screenshots of Proposed Changes Of The Website 
Screenshot 2023-03-23 at 9 09 43 PM

Screenshot 2023-03-23 at 9 12 54 PM

<details>
<summary>The leadership section and value section change </summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by mjshelton12** [comment]
ETA: 3/24 by end of day
Availability: 3/24 after 1pm

**Comment by mademarc** [comment]
Review ETA: 3/23/2023
Availability: 7:55 PM

**Review by mademarc — APPROVED** [review]
hey @oliviazhai  the texts was removed correctly in order to make the page look well so good job.

**Comment by arcan9** [comment]
ETA: EOD 03/24/23
Availability: 3-8PM 03/24/23

**Review by mjshelton12 — APPROVED** [review]
Nice work, Oliviazhai! The basics are handled wonderfully: Good branches, nice job linking issue, and nice work explaining what you did. The images didn't quite make it into the drop-downs, but I'm sure that's just something to watch for next time.

I was able to view the updated one-sheet (I made sure the version date was correct compared to what was linked in the issue), note that the team member had been removed, and saw that the problem, solution, and impact values were taken out as the issue outlined. I was able to see this all in docker in computer, tablet, and phone views without any unexpected problems. Excellent work!

I did want to note that I was a little confused when the value card was completely removed as the image/caption for "Sustainable Development Goal" had not been removed. However, I went into layouts/project.html and saw that this card would only be rendered if there was a "problem" variable (which was removed as the issue requested). This can be seen on line 91 of the project.html code. I wanted to note that here so if any other devs reviewing are confused by this - it's expected behavior though the issue didn't expressly outline it.

**Comment by arcan9** [comment]
hi @oliviazhai ! I moved your issue to the project board in the "Projects" section (gear icon, right side of this page). Looks like according to the [contributing instructions](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board), this isn't an automatic action yet, so the PR needs to be moved there manually. Hopefully this'll be automated soon! 

Just giving a heads up for future PRs.

**Review by arcan9 — CHANGES_REQUESTED** [review]
Nice job @oliviazhai! PR is correctly set up and the changes are reflected in the browser. One change though --  it seems you added a new empty `temp.txt` file that wasn't there before. Please remove it if it's unneeded.

**Comment by oliviazhai** [comment]
> Nice job @oliviazhai! PR is correctly set up and the changes are reflected in the browser. One change though -- it seems you added a new empty `temp.txt` file that wasn't there before. Please remove it if it's unneeded.

Hi @arcan9, for some reason I could not remove the file and push to this branch since the branch is now protected. I opened a new PR #4288 that we can merge into this branch to remove the file instead.

**Comment by arcan9** [comment]
> > Nice job @oliviazhai! PR is correctly set up and the changes are reflected in the browser. One change though -- it seems you added a new empty `temp.txt` file that wasn't there before. Please remove it if it's unneeded.
> 
> Hi @arcan9, for some reason I could not remove the file and push to this branch since the branch is now protected. I opened a new PR #4288 that we can merge into this branch to remove the file instead.

That is strange. I'll tag some of our merge team leads to clarify why that is. (In the meantime, I'll approve your PR.)

@roslynwythe @t-will-gillis @bzzz-coding Could you take look at why @oliviazhai is unable to push new changes to this branch?

**Review by arcan9 — APPROVED** [review]

**Comment by oliviazhai** [comment]
Hi everyone, I incorrectly created the branch directly off of hackforla/website instead of my own fork. This PR fixes it. I've copied and pasted the original PR description below. https://github.com/hackforla/website/pull/4289

**Comment by t-will-gillis** [comment]
Dev had created the branch directly off of the hackforla/website branch instead of off their own repo. In DMs with the dev I indicated that I did not know of an easier way of transferring the work that was already done other than closing this PR and restarting from the correct branch.

Also, I indicated that all are expected to begin with a `Good first issue` and then work on progressively more difficult issues. The dev will need to pick up a[ `Good first issue` ](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22good+first+issue%22)from 'Prioritized backlog' as their next issue.

Finally, I recommend deleting the two branches off of the hackforla/website that the dev mistakenly made.
[oliviazhai-patch-1](https://github.com/hackforla/website/tree/oliviazhai-patch-1)
[oliviazhai-update-project-information-4211](https://github.com/hackforla/website/tree/oliviazhai-update-project-information-4211)


This PR is closed, as is #4288.
Replaced by #4289, which is also to be closed.

**Comment by JessicaLucindaCheng** [comment]
I deleted the branches:
- [oliviazhai-patch-1](https://github.com/hackforla/website/tree/oliviazhai-patch-1)
- [oliviazhai-update-project-information-4211](https://github.com/hackforla/website/tree/oliviazhai-update-project-information-4211)

**Pull request closed without merging**
