### PR TITLE
changing bold to strong

### LINKED ISSUE #2431: Accessibility: Change bold to strong in join-us.html
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [x] Change all the b tags to strong tags within `pages/join-us.html`
- [x] **Line 20**

From:
```
Hack for LA is a project of <b>Code for America</b> and is its official
```
To:
```
Hack for LA is a project of <strong>Code for America</strong> and is its official
```
- [x] **Line 43**

From:
```
Connect with our leadership team on the <b>#admin</b> <a href="https://hackforla.slack.com/messages/admin"
```
To:
```
Connect with our leadership team on the <strong>#admin</strong> <a href="https://hackforla.slack.com/messages/admin"
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected webpage](https://www.hackforla.org/join)
- Directory to find the page in once you have it in your IDE: `pages/join-us.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/pages/join-us.html#L20
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/pages/join-us.html#L43

### PR DESCRIPTION
**Pull request by blulady**
Fixes #2431 
### What changes did you make and why did you make them ?

  -changed b tags to strong tags
  -to be compliant with Accessibility 
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changed bold to strong. No visual changes to the website. </summary> tag -->

<details>
Images look the same with code change. Not Applied.

</details>

### CODE REVIEW

**Comment by lindseyindev** [comment]
Availability: 1 hour
ETA: midnight 1/26

**Review by lindseyindev — APPROVED** [review]
Looks good! You found that third <b> tag not mentioned in the issue, great work!

**Comment by Georgema20** [comment]
Availability: 1 hour
ETA: midnight 1/26

**Comment by Georgema20** [comment]
Everything looks great except your screenshot of the website before and after do not work for me? Does it work for you? Can you put in a new after and a new before? Once I see that I can approve. Everything else looks great.

**Comment by JessicaLucindaCheng** [comment]
@blulady Under the screenshots section, if there are no visual changes, you can just write no visual changes and then an explanation why there are no visual changes. (For more info, see this: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

**Comment by blulady** [comment]
> Everything looks great except your screenshot of the website before and after do not work for me? Does it work for you? Can you put in a new after and a new before? Once I see that I can approve. Everything else looks great.

Hey George,
Because there were no visual changes, there were no images. I made the corrections suggested by Jessica in the comments.
Thank You!!

**Review by JessicaLucindaCheng — APPROVED** [review]
@blulady  Looks good to me!

**Pull request merged**
