### PR TITLE
Replace github with GitHub in CONTRIBUTING.md

### LINKED ISSUE #7442: Replace `github` with `GitHub` in CONTRIBUTING.md Section 2.7.f ii
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join). If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to replace instances of `Github` and `github` with `GitHub` so that we display the company name correctly.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
In section 2.7.f ii:
- [x] Replace
```
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already. Open Git Bash and run:
```
with
```
1. You have to set up SSH keys in order to contribute to GitHub remotely. First check if you have any keys set up already. Open Git Bash and run:
```
- [x] Replace
```
2. Then enter the text below into your terminal using your github account email address.
```
with
```
2. Then enter the text below into your terminal using your GitHub account email address.
```
- [x] Replace
```
5. Finally copy the ssh key to add it to your github account by entering the following command. This copies the contents of the id_ed25519.pub file to your clipboard __Don't copy anything else until after you finish the last step, or else you will have to repeat this step.__
```
with
```
5. Finally copy the ssh key to add it to your GitHub account by entering the following command. This copies the contents of the id_ed25519.pub file to your clipboard __Don't copy anything else until after you finish the last step, or else you will have to repeat this step.__
```
- [x] Replace
```
6. Go to your github accounts ssh key settings, and click on the button that says _New SSH key_. In the "Title" field, add a descriptive label for the new key. Paste the key into the form that pops up. Click Add SSH Key

```
with
```
6. Go to your GitHub account's ssh key settings, and click on the button that says _New SSH key_. In the "Title" field, add a descriptive label for the new key. Paste the key into the form that pops up. Click Add SSH Key

```
- [x] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #6161

### Merge Team
- [ ] After closing this issue, check off the dependency in #6161.  If all dependencies have been completed, close #6161

### PR DESCRIPTION
**Pull request by jenjenkayi**
Fixes #7442 

### What changes did you make?
  
  - Replace github with GitHub in CONTRIBUTING.md Section 2.7.f ii

### Why did you make the changes (we will use this info to test)?
  
  - So that we display the company name correctly

For Reviewers: Do not review changes locally, rather, review changes at https://github.com/jenjenkayi/website/blob/replace-github-with-Github-7442/CONTRIBUTING.md

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

  - No visual changes to the website.

### CODE REVIEW

**Comment by codyyjxn** [comment]
Availability: M  > F 
ETA: EOD

**Review by codyyjxn — APPROVED** [review]
Hi @jenjenkayi,
Thank you for taking on this issue!

### Things that went well: 
- The branch is named correctly
- The issue is linked.
- The title and description are concise and clear.

### The only change: 
- The only suggestion I have is to remove the brackets around the link in the section where you provided the changes. Everything else looks great!

**Comment by FamousHero** [comment]
Availability: 5pm-9pm M -F
ETA: EOD 10/5

**Review by FamousHero — CHANGES_REQUESTED** [review]
Hi @jenjenkayi, thanks for taking on this issue!

Things you did well:
- Branch name contains issue number
- PR title, description, & reason are informative & concise
- Issues action items properly followed

Things to Work on:
- Small oversight but branch name has Github instead of GitHub
- Visual changes not included. The CONTRIBUTING.md on the main repo is different.
- review link is not done correctly. I recommend you re-read the last action item as to how you can fix it!

Once you fix these issues, please request a re-review and I'll gladly approve the PR. Thanks!

**Comment by jenjenkayi** [comment]
> Hi @jenjenkayi, thanks for taking on this issue!
> 
> Things you did well:
> 
> * Branch name contains issue number
> * PR title, description, & reason are informative & concise
> * Issues action items properly followed
> 
> Things to Work on:
> 
> * Small oversight but branch name has Github instead of GitHub
> * Visual changes not included. The CONTRIBUTING.md on the main repo is different.
> * review link is not done correctly. I recommend you re-read the last action item as to how you can fix it!
> 
> Once you fix these issues, please request a re-review and I'll gladly approve the PR. Thanks!

**Comment by jenjenkayi** [comment]
@FamousHero 

Thank you for your comments.  

1. The branch name is fixed.
2. Since there are no visual changes to the website, I did not include the screenshots of the code changes. 
The changes are on the "replace-github-with-Github-7442" branch. I am not sure what you meant by saying the main repo is different.
3. I have removed the brackets per the instructions.

**Comment by FamousHero** [comment]
> 2\. The changes are on the "replace-github-with-Github-7442" branch. I am not sure what you meant by saying the main repo is different.

Correct, before we push the changes to the main branch it's best to see what is different visually between the current site at "https://www.hackforla.org/" and the one on your branch. In this case, compare https://github.com/jenjenkayi/website/blob/replace-github-with-Github-7442/CONTRIBUTING.md to https://github.com/jenjenkayi/website/blob/gh-pages/CONTRIBUTING.md.

**Comment by FamousHero** [comment]
> > 2. The changes are on the "replace-github-with-Github-7442" branch. I am not sure what you meant by saying the main repo is different.
> 
> ~~Correct, before we push the changes to the main branch it's best to see what is different visually between the current site at "https://www.hackforla.org/" and the one on your branch. In this case, compare https://github.com/jenjenkayi/website/blob/replace-github-with-Github-7442/CONTRIBUTING.md to https://github.com/jenjenkayi/website/blob/gh-pages/CONTRIBUTING.md.~~

Sorry about that, you are correct! It is not on the main website so it does not need to be included. Thank you for making all the required changes!

**Review by FamousHero — APPROVED** [review]

**Pull request merged**
