### PR TITLE
Change description text for CoP URL on Getting Started PAge #2268

### LINKED ISSUE #2268: Change description text for CoP URL on Getting Started PAge
### Overview
We need to change the description text for a URL on the Getting Started Page. 

Currently the text on the page is as follows:
[Join your Community of Practice's Slack channel](https://www.hackforla.org/communities-of-practice) for access to announcements, meeting zoom links, and helpful resources.

We need to update it to:
[Join your Community of Practice ](https://www.hackforla.org/communities-of-practice) for access to announcements, meeting zoom links, and helpful resources.

### Action Items

- [ ] Replace text for the URL
- [ ] Test and verify the Getting Started page shows the updated link text

### Resources/Instructions
https://www.hackforla.org/getting-started
https://github.com/hackforla/website/blob/a159ab43e798007daa61f334d2c4a810560e8c26/pages/getting-started.html#L103-L104

### PR DESCRIPTION
**Pull request by robertestrada**
Fixes #2268

### What changes did you make and why did you make them ?

I changed the text for the getting started page for "Step 2: Join your community of Practice" section regarding the line "Join your Community of Practice's Slack channel" to "Join your Community of Practice" since it was flagged as an open good 1st issue for new on boarders like myself.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

![image]
Screen Shot 2021-09-24 at 10 23 55 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]
Screen Shot 2021-09-24 at 10 22 10 PM
</details>

### CODE REVIEW

**Review by mdhailwood1 — APPROVED** [review]
@robertestrada Looks great! Fully approved

One thing I noticed was you made three commits where the second one you un-did the change then in the third you re-added it back.  If your intention was to start-over after you've already committed, another option could be to delete the branch you were working on and create a new one off of "gh-pages".  Multiple commits works perfectly too though!

**Comment by robertestrada** [comment]
Thank you!

Sincerely,



Robert M. Estrada
***@***.*** ***@***.***>
6267553454
Portfolio <https://robertmestrada.com/>
GitHub <https://github.com/robertestrada>
LinkedIn <http://www.linkedin.com/in/robertmestrada/>

**Review by macho-catt — APPROVED** [review]
Good job on your first issue!

**Review by SAUMILDHANKAR — COMMENTED** [review]
Thanks Robert.

**Pull request merged**
