### PR TITLE
Update styling 404 page 2097

### LINKED ISSUE #2097: Update styling for 404 page (Mobile View)
### Overview
Making styling changes for the mobile view of the 404 page so it matches the Figma design.

<details>
<br>
  <summary>Click here to see <strong>figma design (iPhone X view)</strong> with visual lines - black lines for margin, red lines for spacing</summary

Screenshot 2021-07-26 095953
<br>
</details>

<details>
<br>
  <summary>Click here to see <strong>your current 404 page (iPhone X view)</strong> with visual lines- black lines for margin, red lines for spacing</summary>
  
  Screenshot 2021-07-26 101301
<br>  
</details>

### Action Items
- [x] Add left/right margin for the 404 page so it matched the Figma design.
- [x] Adding top/bottom space between the 404 page title.
- [x] `Looks like something went wrong...` text needs to drop the font size for mobile view.

### Resources/Instructions
[404 Error page in Figma (final design in the pink rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9616%3A0)
[PR 1972 - My original comment that notated the styling reccomendations](https://github.com/hackforla/website/pull/1972#pullrequestreview-715114095)

### PR DESCRIPTION
**Pull request by scorbz9**
Fixes #2097 

### What changes did you make and why did you make them ?

  - Added left/right margin to 404 page to match figma design
  - Added top/bottom margin to main-message-404 element
  - Lowered font size for main-message-404 element

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Wednesday, June 8th

**Review by Wny-Duong — DISMISSED** [review]
Horizontal margins look good and the text on mobile layouts is aligned with the top-right corner of the Hack for LA logo. The resized text on "Looks like something went wrong" is smaller proportionally than the header, which it should be. Spacing between the lines between the nav bar, header, and subtitle look correct as well. Nice work!

**Comment by Carlos-A-P** [comment]
Availability: 1hr
ETA: 6/15 EOD

**Comment by usaboo** [comment]
Availability: 1 hour
Deadline: EOD Tuesday 6/14

**Review by Carlos-A-P — DISMISSED** [review]
Hey @scorbz9, the changes look just like the Figma design and I can see that the elements have the correct spacing. I did notice that the "looks like something went wrong" text looks to have a smaller font size on the Figma design with a font size of 16px. It looks like it currently has a font size of 18px.

**Comment by usaboo** [comment]
Hi @scorbz9, great work on this issue.
- I see that left and right margins have been added.
- The "looks like something went wrong" message has been resized which is good.
- Also some margin has been added between the between the top left "Hack for LA" logo and the "Uh oh..." message.

That said, the only slight issue I have with your implementation is that at the mentioned screen setting of 375 x 875 in Figma the message that says "Here are some other pages that can help get you back on track" has the second line starting with "can..." in your implementation whereas in figma it starts with "help"

Here is an annotated screenshot of what I mean.

Figma -> 
Screen Shot 2022-06-15 at 6 18 09 PM

Local ->
Screen Shot 2022-06-15 at 6 15 28 PM

I suspect increasing the left and right margin a little bit might solve the problem by helping fit "can" into the first line.

Maybe @Wny-Duong and @Carlos-A-P can confirm this as well.

**Review by usaboo — CHANGES_REQUESTED** [review]
Hi @scorbz9, great work on this issue.
- I see that left and right margins have been added.
- The "looks like something went wrong" message has been resized which is good.
- Also some margin has been added between the between the top left "Hack for LA" logo and the "Uh oh..." message.

That said, the only slight issue I have with your implementation is that at the mentioned screen setting of 375 x 875 in Figma the message that says "Here are some other pages that can help get you back on track" has the second line starting with "can..." in your implementation whereas in figma it starts with "help"

Here is an annotated screenshot of what I mean.

Figma -> 
Screen Shot 2022-06-15 at 6 18 09 PM

Local ->
Screen Shot 2022-06-15 at 6 15 28 PM

I suspect increasing the left and right margin a little bit might solve the problem by helping fit "can" into the first line.

Maybe @Wny-Duong and @Carlos-A-P can confirm this as well.

**Comment by Carlos-A-P** [comment]
@usaboo Yes, it looks like if you were to decrease the inline margin for .grid-container--404 by a little bit it would match the Figma design.

**Comment by scorbz9** [comment]
I made changes on this PR to match the requests. I decreased the inline margin for grid-container--404 (below tablet) so that the second line begins with 'help' instead of 'can,' like the figma design. I also decreased the font size for main-message-404 to 16px and added a margin-right of 5px so that it also matches the figma design.

**Comment by Wny-Duong** [comment]
Availability: 1 hour
ETA: 6/27

**Comment by usaboo** [comment]
Availability : 1 hour
Review ETA : Sunday June 26th

**Review by Wny-Duong — CHANGES_REQUESTED** [review]
You forgot to revert the change from the 4.2.0 version of jekyll in docker-compose.yml to pages on line 4.

Besides that, and I'm checking based on the changes needed from the comments left earlier.

- The text for "Looks like something went wrong..." was resized to 16px as per Carlos's change request.
- As per Utkarsh's change request, the design now matches between the site and the 375 x 875 layout on Figma, with "can" now being on the first line as opposed to the second.

Good work on those, just the one tiny change left.

**Comment by usaboo** [comment]
Hi @scorbz9, good job on fixing the 404 page to look like the Figma design. I can see that the second line starts with **help** now.

**Review by usaboo — CHANGES_REQUESTED** [review]
Hi @scorbz9, good job on fixing the 404 page to look like the Figma design. I can see that the second line starts with help now. Only tiny bits of work on Wilny's comment is left :)

**Comment by scorbz9** [comment]
Hi @usaboo and @Wny-Duong,

I've gone ahead and reverted the accidental changes to the docker-compose.yml file.

**Review by Wny-Duong — APPROVED** [review]
Thanks for fixing the docker-compose file. Approved!

**Comment by usaboo** [comment]
Looks good to me too! Can be merged!

**Review by usaboo — APPROVED** [review]

**Pull request merged**
