### PR TITLE
removed 'workflow_dispatch' used for testing

### LINKED ISSUE #2934: BOP project page not connected to its GitHub repo properly
### Overview
As a developer, I want the data on all our project pages to be up to date. For this issue, we will fix an error on the [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook) where all-time contributors are not getting displayed.

### Action Items
- [x] Review the [project.md file template](https://github.com/hackforla/website/wiki/project.md-file-template) for tips on how data for the 'contributors' section is pulled from the project's GitHub main repository using the GitHub API
- [ ] Review [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md?plain=1) file and [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) file
- [ ] Fix the error and ensure that the data is getting pulled on the BOP project page in your own repo
- [ ] Make sure existing functionalities are not impacted by the change

### Resources/Instructions

<details>
<summary>Screenshot of error</summary>

BOP project page error

</details>

- [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook)
- [project.md file template](https://github.com/hackforla/website/wiki/project.md-file-template)
- [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md?plain=1) file
- [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) file
- Related comments: https://github.com/hackforla/website/issues/2605#issuecomment-1013941235 and https://github.com/hackforla/website/issues/2605#issuecomment-997477244

### PR DESCRIPTION
**Pull request by RyanCahela**
Fixes #2934

### What changes did you make and why did you make them ?

  - removed all changes I made to config files while testing
  - changed "cfa" to "codeforamerica"
  - hopefully will fix bug where brigade organizer playbook contributors are not displayed.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
NA - changes only made to github-actions file.

<details>
<summary>Visuals before changes are applied</summary>
NA - changes only made to github-actions file.

</details>

<details>
<summary>Visuals after changes are applied</summary>
NA - changes only made to github-actions file.

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/16
Availability: 2 hours

**Comment by answebdev** [comment]
ETA: 5/13/2022 (end of day)
Availability: 2 hours

**Review by answebdev — COMMENTED** [review]
@RyanCahela Thank you for submitting your PR. I can see that you have changed "cfa" to "codeforamerica" in `github-actions/github-data/get-project-data.js`, but this is the only change that I can see you made under the "Files changed" tab - you wrote in your PR that you also removed all changes you made to config files while testing, but I do not see any other changes made (unless you are referring to code that you added on your own for testing, and then removed). Also, were you able to see the contributors on the Brigade Organizers Playbook page, as referred to in the original issue? I was not able to see them locally:

<details>
  <summary>Brigade Organizers Playbook - (local)</summary>

bop

</details>

**Comment by Jaretzbalba** [comment]
@RyanCahela As @answebdev mentioned above, I was also unable to see the All-Time Contributor cards on my end either. I think there should be a visual change from fixing this issue since right now the live site claims that there isn't a GitHub repository linked.

**Comment by RyanCahela** [comment]
Hey @Jaretzbalba @answebdev thanks for taking a look at the PR, the only thing that has changed is the string from "cfa" to "codeforamerica". Any other reference to config file changes was me removing things that I needed for local testing. I'm still getting the hang of keeping my remote and local repos synced up, that's why there are so many commits.

I've been trying to work out different testing solutions with @SAUMILDHANKAR and due to the way the contributor data is pulled using github actions on GitHub servers, it was hard to test this script on my machine without sharing certain security tokens.

Because this script is already throwing an error every time we try to access Code For America contributor data we figured it wouldn't hurt just making the change and seeing if it pulled the data correctly. 

Once the data gets pulled completely and the contributor Json file composed correctly by GitHub actions my hope is that the page will render as expected. 

I should have included a more detailed explanation in my initial PR. Sorry about the confusion.

**Comment by answebdev** [comment]
@RyanCahela Thank you for clarifying that. I understand what you're saying, and it makes sense now. And I figured as much about the references to the config file, but thanks for clearing that up. Hopefully, once you get to that point, the page will indeed render as expected.

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Sorry for the delay. I am planning to merge this now so we can see if it works fine for a few days. If something breaks, we might need to revert it.
@answebdev @Jaretzbalba Thanks for your review. As Ryan already mentioned we couldn't test this in local as that would require sharing the token and we are trying to avoid that since there aren't a lot of code changes. I will merge this PR but keep the corresponding issue open.

**Comment by answebdev** [comment]
ETA: 5/18/2022 (end of day)
Availability: 2 hours

**Comment by answebdev** [comment]
@RyanCahela Thank you for letting us know on Slack that the bug has been fixed and that the All-Time Contributors are now displayed as expected. Since this has already been merged, I am now able to see the contributors on the live site:

<details>
  <summary>All-Time Contributors on live Hack for LA site</summary>

live

</details>


However, I still am not able to see the contributors locally:

<details>
  <summary>All-Time Contributors locally</summary>

local

</details>

I don't know if this is an issue on my end. I went through the steps of deleting the `_site` folder and building everything back up from scratch, etc. in the case where I cannot see the changes locally, but as you can see, I still cannot see the changes locally. I'm not sure why. Perhaps this is because this has already been merged? Obviously, it seems to be okay now, since the Contributors are now displayed as expected on the live site. @SAUMILDHANKAR Saumil, can you confirm that this issue is okay to close now, or if the fact that I cannot see this locally is something that needs to be taken care of first before closing?

**Comment by SAUMILDHANKAR** [comment]
@answebdev Hi Adolf, you should be able to see the changes locally as well but since the changes are already in the production website, no need to worry about that. More importantly, wanted to check if the code change might have unintended consequences while pulling contributor data on project pages. Notice the difference between `Generate github-data.json` in Update GitHub data [WR#706](https://github.com/hackforla/website/runs/6440563399?check_suite_focus=true) and [WR#705](https://github.com/hackforla/website/runs/6434197947?check_suite_focus=true) where in 706 the error has disappeared. You can also look for potential vulnerabilities in [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/get-project-data.js) file. Some of the points I could think of:

- `function constructContributorParams` pulls data for comments, do we need to verify if other contributions such as commits, PRs etc are getting added to all-time contributors?
- Since the error occurred because value was hard-coded, should we explore ways to avoid that?

Once your review is done, we can decide on how to incorporate the changes (if any) and whether it should be fixed with this issue or maybe a new issue should be created. Please let me know your comments. Thank you.

**Comment by answebdev** [comment]
@SAUMILDHANKAR and I discussed and verified that the `constructContributorParams` function was actually just for the parameters, and verified that the contributors are in fact getting added to the all-time contributors list. We can explore hard-coding “codeforamerica” (line 166) in the future, but for this issue, it’s okay to hard-code it for now. It looks like there are no other potential errors or vulnerabilities that could be a problem for this issue.

**Pull request merged**
