### PR TITLE
Operations image redesign 3296

### LINKED ISSUE #3296: Edit credit for Operations image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Operations credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/operations.yml`,
  - [x] Change 
    `title-link: https://thenounproject.com/made.somewhere/collection/work/?i=1819014`
     to
     `title-link: https://thenounproject.com/search/?q=operations&i=1819014`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'Operations Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #3296

### What changes did you make and why did you make them ?

  - Edited _data/internal/credits/operations.yml,
  - Fixed typo by renaming branch name of my last pull request for this issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by lilyarj** [comment]
@arpitapandya,I can't see the before image, can you re input it?

**Comment by arpitapandya** [comment]
> @arpitapandya,I can't see the before image, can you re input it?

I have updated it now. Thanks

**Comment by lilyarj** [comment]
@arpitapandya Everything looks good for this issue, and I see the change on your website but for some reason your website doesn't have a press tab, did you change anything else on this branch?

**Comment by arpitapandya** [comment]
> @arpitapandya Everything looks good for this issue, and I see the change on your website but for some reason your website doesn't have a press tab, did you change anything else on this branch?

These are the changes '_data/internal/credits/operations.yml', I haven't made any other changes but what is "press tab"???

**Comment by arpitapandya** [comment]
> > @arpitapandya Everything looks good for this issue, and I see the change on your website but for some reason your website doesn't have a press tab, did you change anything else on this branch?
> 
> These are the changes '_data/internal/credits/operations.yml', I haven't made any other changes but what is "press tab"???

It should show in review changes, the changes I have made, are you seeing any other changes in code that are not related to this issue/PR?

**Comment by lilyarj** [comment]
> > > @arpitapandya Everything looks good for this issue, and I see the change on your website but for some reason your website doesn't have a press tab, did you change anything else on this branch?
> > 
> > 
> > These are the changes '_data/internal/credits/operations.yml', I haven't made any other changes but what is "press tab"???
> 
> It should show in review changes, the changes I have made, are you seeing any other changes in code that are not related to this issue/PR?

not in your code but on the website it looks different

normal hfla website : 
Screen Shot 2022-07-20 at 5 41 41 PM

yours:
Screen Shot 2022-07-20 at 5 43 38 PM

**Comment by BeckettOBrien** [comment]
@lilyarj This issue is working off of the feature branch `feature-homepage-launch`, so you can't compare it to the currently hosted hackforla.org. You should be able to checkout the `feature-homepage-launch` branch and run the site locally to compare the changes.

**Comment by lilyarj** [comment]
> 

Oh okay, thank you so much!

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Review by AsherEngelberg — APPROVED** [review]
Great job! These changes look great @arpitapandya

**Pull request merged**
