### PR TITLE
Create New Code of Conduct Page

### LINKED ISSUE #4249: Create a new Code of Conduct Page
### Overview
Since HfLA is no longer bound by Code for America's Code of Conduct, we need to update HfLA's Code of Conduct. For this issue, you will need to create a new Code of Conduct page so that developers will read the Code that pertains to HfLA specifically.

### Action Items
- [x] In [website/pages](https://github.com/hackforla/website/tree/gh-pages/pages), create a new html file named code-of-conduct.html
  - [x] Add the Jekyll [front matter](https://jekyllrb.com/docs/front-matter/) block for this new page
  - [x] Use `layout: default`
  - [x] Make the permalink to the page with `permalink: code-of-conduct` so Jekyll can build the page
  - [ ] ~~Include the file in index.html~~
- [x] Using the [GitHub REST API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28), use the [hackforla/codeofconduct](https://github.com/hackforla/codeofconduct/blob/master/README.md) README.md file to populate the website's current [CODEOFCONDUCT.md](https://github.com/hackforla/website/blob/gh-pages/CODEOFCONDUCT.md) dynamically
  - [x] The idea here is that the content of the Code of Conduct only gets edited in one place and can be applied across all projects
  - [x] This will then be rendered onto the new code-of-conduct.html file using Liquid
  - [x] Be sure to separate the content as appropriate into 
    - Header
    - Content Body
    - Footer

### For PM/Tech Lead/Merge Team
- [x] When this PR associated with this issue is merged, add a "ready for design lead" label on this issue #4249, and place it into the New Issue Approval Column so that design can review the layout and redesign as necessary. 
  

### Resources/Instructions
- Associated ER for this issue: https://github.com/hackforla/website/issues/4243
- Using [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll
- [GitHub REST API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28)
- REST API [Media Types](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28)

### PR DESCRIPTION
**Pull request by bootcamp-brian**
Fixes #4249

### What changes did you make and why did you make them ?

  - As part of the solution for this issue, a GitHub action was created in the `hackforla/codeofconduct` repo that will run whenever the README.md file in that repo containing the code of conduct is updated and will then update the `_includes/code-of-conduct-page/CODEOFCONDUCT.md` file in the website repo. You can find the merged PR for this [here](https://github.com/hackforla/codeofconduct/pull/3). This solves the automation of updating the code of conduct so that it is only required to edit a single file.
  - Created a new layout file at `_layouts/default-markdown.html` and made an addition to `_sass/components/layouts/_main.scss`. The new layout file uses the `default.html` layout as a template and makes it so that the content on this page will maintain markdown formatting. I added padding to the `main` element in `default-markdown.html` in order to make the page's content readable. This was accomplished by giving it a unique id of "content-markdown" and adding the CSS for that id to the `_main.scss` file.
  - Created a new `pages/code-of-conduct.html` file to add a new page to the site at `hackforla.org/code-of-conduct/`. This file just uses an include to paste onto the page the markdown formatted content taken from `hackforla/codeofconduct` repo that has been copied into `_includes/code-of-conduct-page/CODEOFCONDUCT.md`.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Visuals before changes are applied:

- Since this is creating a brand new page for the website, there are no previous visuals to compare to.

<details>
<summary>Visuals after changes are applied</summary>

Top half of page:
 image

Bottom half of page:
image

</details>

### CODE REVIEW

**Comment by LOSjr4** [comment]
Availability: weekdays 9AM-1PM
ETA: Thursday 5/11

**Comment by blulady** [comment]
@mjshelton12 & @mademarc when you guys get a chance can you put your eta and availability? Thank you.

**Review by LOSjr4 — CHANGES_REQUESTED** [review]
@bootcamp-brian I think you did a great job and I appreciate the thorough explanation in the "What changes were made" section, so as a reviewer, I can fully understand the issue.
One minor detail I'm noticing on certain narrower preview formats is that the last line of the Code of Conduct email template gets cut off.
For example: This is scrolled down as far as I can go. Sometimes it cuts off half or the entire last line off.
image
Add more bottom padding or maybe add some space at the bottom of the ReadMe file.

**Comment by bootcamp-brian** [comment]
> @bootcamp-brian I think you did a great job and I appreciate the thorough explanation in the "What changes were made" section, so as a reviewer, I can fully understand the issue. One minor detail I'm noticing on certain narrower preview formats is that the last line of the Code of Conduct email template gets cut off. For example: This is scrolled down as far as I can go. Sometimes it cuts off half or the entire last line off. image Add more bottom padding or maybe add some space at the bottom of the ReadMe file.

Thanks, I made some padding adjustments to address the issue. It shouldn't get cut off now at that size.

**Comment by mademarc** [comment]
Review ETA: 4/11/2023
Availability: 7:05PM

**Review by mademarc — COMMENTED** [review]
Hey @bootcamp-brian   good call in adding the content-markdown properties along with the padding selectors for giving the page style on it and @mjshelton12  feel free to take a look at this also thanks @blulady  for the heads up as well

**Review by LOSjr4 — APPROVED** [review]
Thank you @bootcamp-brian. There is plenty of padding now. You've done well implementing these changes and noting the steps of your progress.

**Comment by mjshelton12** [comment]
Availability: Tue-Wed 9am-1pm, Fri 9am-4pm
ETA: Wed by end of day

**Review by mjshelton12 — APPROVED** [review]
First off, great work on the basics. Your branches are correct, you linked to an issue, you provided a thorough explanation of what you did/why you did it, and included appropriate visuals. Your code is clean and effective, plus it shows perfectly in chrome desktop, tablet, and iphone as well as safari desktop. Excellent work!

I will note that I did not attempt to test/thoroughly look at the GHA as it was already merged, but I did give it an overview to understand it and you did great work there too.

I really think you did a very thorough and clean job here. Developers will be appreciating your clear and concise comments for years to come. Thanks for all this work, I would say it's ready for design!

**Comment by roslynwythe** [comment]
Hi @mademarc your comments are appreciated, however to work efficiently, our developer and merge team need to be able to clearly and quickly assess the status of each PR, and that is not always clear from your comments.   Therefore we need to request that instead of writing a comment in a PR, you submit the "Review Changes" form that can be found on the "Files Changed" page (see screenshot below).  Using this form, you will make the status of the review explicit by selecting from the options: "Comment", "Approve", or "Request Changes".   Please be specific about what elements of the PR review have been completed;  in particular, describe the local testing that you have completed.  It is especially useful when reviewers mention the browser(s) they have used for local testing.  Thank you!

image

**Review by blulady — APPROVED** [review]
Outstanding @bootcamp-brian. As @mjshelton12 pointed out all of the basics are covered and like @LOSjr4 mentioned the explanation is complete. The file structure looks good in my local, no conflicts and while my old lady eyes struggle with the fine print, it's completely adjustable on my end. I would say you could probably use https://github.com/hackforla/codeofconduct as an image but not worth holding up merging this clean and succinct code.

**Comment by mademarc** [comment]
Greatly noted @roslynwythe and thanks as well :)

**Pull request merged**
