### PR TITLE
 Update added Johnny Wu to the website team #4917

### LINKED ISSUE #4917: Update Project Profile: Add Johnny Wu to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the end of the `leadership` variable
```
 - name: Johnny Wu
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U043KH4FQ1M'
      github: 'https://github.com/Skydodle'
    picture: https://avatars.githubusercontent.com/Skydodle
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by Ris345**
Fixes #4917 

### What changes did you make?
  - added name as  Johnny Wu
  - added role as merge team
  - added links to slack, GitHub and pictures

### Why did you make the changes (we will use this info to test)?
  - To add Johnny Wu as a Current Project Team member: https://www.hackforla.org/projects/website
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-07-30 at 9 24 57 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-07-30 at 9 23 22 PM

</details>

### CODE REVIEW

**Comment by whitneywind** [comment]
Review ETA: 7/26 EOD
Availability: 7/26 12-3

**Review by whitneywind — DISMISSED** [review]
Changes are being merged correctly from your personal branch to gh-pages, changes match the those requested in the original issue, and the visual change matches your screenshot and is consistent in mobile and desktop views. Nicely done!

**Comment by steven-positive-tran** [comment]
Review ETA: 7/26 EOD
Availability: 7/26 6-12

**Review by steven-positive-tran — CHANGES_REQUESTED** [review]
Hi I see theres a merge conflict and I believe the issue stems from Ronald Paek infomation is not there. I saw from previous pull requests that he recently got into the merge team and from the code I see that if we approved and merge this branch we would remove him. 

 I'm unfamilar with how to solve this but try pulling from hackforla, fixing the merge conflict and making a new PR?

**Comment by Ris345** [comment]
@steven-positive-tran Thanks for the  comments, I pulled from gh-pages branch as that was suggested in the documentation. I can make another PR if that is required

**Comment by LRenDO** [comment]
> @steven-positive-tran Thanks for the comments, I pulled from gh-pages branch as that was suggested in the documentation. I can make another PR if that is required

Hi @Ris345! If you have pulled the changes into your `update-add-Johnny-Wu-to-website-team-4917` branch locally and resolved any conflicts, you can go ahead and push the branch to your forked repository the same way you did before. This pull request should automatically update once you do that.

**Review by steven-positive-tran — DISMISSED** [review]
Thanks for doing that Riv. Branches look good, code changes seem in line with the issue needed to be addressed and works on my machine.

**Comment by adrianang** [comment]
Hi @Ris345 — this issue now has a merge conflict since there was another merge to the Website Project Team that had been submitted for PR before this one. Would you be able to resolve and merge that update into this branch, and push another commit? Apologies for having you resolve another merge conflict, but your PR should be the next update to the Website project page once the merge conflict is resolved 🙏🏼

**Comment by Ris345** [comment]
@adrianang Just made the new changes and pushed it up. Thanks

**Review by adrianang — APPROVED** [review]
Hi @Ris345 — this PR looks good to me! The branching is set up correctly and is descriptive of the feature/change, the corresponding issue is linked for easy reference, the what/why/screenshots are well-documented and succinct, and the requested change (adding Johnny to the Website team) was made exactly without altering any other part of the codebase. When testing your branch on my local environment via Docker, it shows Johnny on the team without affecting the rest of the page, and also reflects earlier merges on the Website project page that were made while this issue was awaiting merge.

Thank you for taking up this issue and being patient, responsive, and communicative with the Website team as we worked through the merge conflicts. 🙌🏼 Feel free to work on another issue now!

**Comment by Ris345** [comment]
@adrianang Thanks, learnt a lot on this first issue and especially merge conflicts.

**Pull request merged**
