### PR TITLE
add labels for the blank-issue-form-with-no-dependancy issue template

### LINKED ISSUE #4485: Update labels: Issue Template: blank-issue-form-with-no-dependency
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/blank-issue-form-with-no-dependency.yml`
- [x] Add the following line under the description field
   ```
   labels: ['role missing', 'Complexity: Missing', 'Feature Missing', 'size: missing','Draft']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template
URL of the issue branch on the test Repository:  https://github.com/vincentdang/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-no-dependency.yml

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/blank-issue-form-with-no-dependency.yml`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by rdhmdhl**
Fixes #4485

### What changes did you make and why did you make them ?

- Replace the following line
labels: ['role: design']
with
label: ['role: design','Feature Missing','Complexity: Missing','size: missing']
- add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.

### CODE REVIEW

**Review by jenny-alexander — APPROVED** [review]
Well done @rdhmdhl! I reviewed the .yml file and see you added the new 'labels' line.

**Comment by roslynwythe** [comment]
Hi @carolemlago Please provide your Availability and ETA to review this PR.  Thank you

**Comment by roslynwythe** [comment]
Closing this PR because the linked issue was not in the Prioritized Backlog column and the Action Items were not complete.

**Comment by vincentdang** [comment]
Whoops. I just noticed I made a mistake.

**Pull request closed without merging**
