### PR TITLE
Kiran98118 span update

### LINKED ISSUE #5368: Refactor HTML: _includes/about-page/about-card-platform.html - Diversity
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
                    <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/diversity.svg" alt=""></span><span class="sub-head-text color-chocolate">Diversity, Equity & Inclusion</div>
```
to
```
                    <div class=""sub-card-head""><span class=""sub-head-image""><img src=""/assets/images/about/platform-header-elements/diversity.svg"" alt=""""></span><span class=""sub-head-text color-chocolate"">Diversity, Equity & Inclusion</span></div>

```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
4. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by kiran98118**
Fixes #5368 

### What changes did you make?
  -I have added the missing span tag
  
  

### Why did you make the changes (we will use this info to test)?
  -To solve the linter error
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- no visual change

### CODE REVIEW

**Comment by antho-zng** [comment]
Review ETA: 9pm 8/31/23
Availability: 12-9pm Thursday 8/31/23

**Review by antho-zng — CHANGES_REQUESTED** [review]
Nice formatting catch on the unnecessary closing / on the img tag, but our pull requests should only address the changes specified in the original issue (in case the other fixes we catch show up in other existing issues). 

Please resubmit with just the span update—otherwise looks great!

**Comment by LRenDO** [comment]
Hi @kiran98118! 

Thanks for working on this issue! I saw you moved the related issue #5368 back to the backlog. If you still plan to complete the changes, please move the original issue back to the `In Progress (actively working)` and reassign yourself.  Either way, please leave a comment to let us know whether or not you plan to complete the changes. Also, feel free to ping me if you need any help or clarification! Thanks!

**Comment by LukeLowrey2** [comment]
Working on this review Monday 9/11
Availably: Monday 9/11 930a - 1030a, Tuesday 9/12 10a - 11a
ETA: Tuesday 9/12 EOD

**Review by LukeLowrey2 — CHANGES_REQUESTED** [review]
Hello @kiran98118 

Thank you for working on this issue!
-You attached the issue number to the PR
-You are committing into the correct branch
-You navigate to _includes/about-page/about-card-platform.html and added the closing </span> correctly

Awesome job!

When reviewing the changed files attached to this PR I'm also seeing changes to _includes/about-page/about-card-donations.html which were not in the instructions of issue #5368. 

Please clarify why changes were made to _includes/about-page/about-card-donations.html or revert changes to the file. Once changes are made or clarification is given use the re-request review icon next to my name at the top right of this PR, in the conversation tab.

**Comment by t-will-gillis** [comment]
Dev opened a second PR for this issue #5457 that replaces this PR.

**Pull request closed without merging**
