### PR TITLE
About-us: change donation image

### LINKED ISSUE #846: About page: Replace static image with animated.gif in donations section
### Description
The image used is a static image and needs to be replaced with the intended animated gif

### Resources
https://github.com/civictechindex/CTI-website-frontend/issues/60#issuecomment-673788199

http://localhost:4000/about-us#donations

### Steps

- [x] Add image to directory
- [x] Change resource to use new image
- [x] Delete old image
- [x] Mark as complete on master issue #835

### PR DESCRIPTION
**Pull request by drubgrubby**
Fixes #846 

I replaced the static image with the animated gif, changed the image source, and deleted the old image. 

Do I get a gold star?

Note: The image looks a little off-center in mobile view at some sizes.  This seems to be because the image itself is cropped in what is (to me) an odd way.  I'm not sure how to fix this other than to redo the image.

### CODE REVIEW

**Review by jbubar — APPROVED** [review]
Code looks great! I like these quick issues. makes it easy to review,

And we looked over it together and decided that we should crop the gif.. 
here is this great online resource for cropping the gif: https://www.flexclip.com/editor/app

**Review by jbubar — CHANGES_REQUESTED** [review]
See comment above

**Comment by drubgrubby** [comment]
@daniellex0 - Can you have a look at this and let us know what you think.  The animated gif looks a bit off-kilter, I think because of the way it's cropped.   Do you think it's okay as it is?  Is there an easy way to re-crop it?  Do you have some other clever idea?

**Comment by daniellex0** [comment]
@drubgrubby Do you mean in mobile view? For some reason I can't expand the collapsed sections in my mobile view to see that (clicking doesn't work in Firefox or Chrome for me). However in desktop version it looks fine to me! 

Do you mean the way it's cropped with part of the text on the right still visible looks off-kilter? If that's what you're talking about, I personally think it's not too bad because it can make it clear to viewers that it's a screen grab from another site and meant to show them what to do on that site, so I think it's fine..

**Comment by daniellex0** [comment]
@drubgrubby And P.S. while we're on this section, can you please remove the hyperlink from "Code for America" in this donation page card, leaving it just plain black text? I also originally had that as a link, but Bonnie asked me to remove it because she doesn't want to lose people that click that link instead of reading the rest of the instructions

Screen Shot 2020-12-16 at 9 40 45 PM

**Comment by drubgrubby** [comment]
@daniellex0 - I removed the Code for America link as you requested.  

As far as the sections not opening in mobile: I sometimes have that issue when I switch from desktop to mobile.  Usually if I reload the page it fixes it.  

If the image looks okay to you, then either you or @jbubar can feel free to squash and merge.  If you think we should do something to change the image, let me know how you think that might best be accomplished.

**Comment by drubgrubby** [comment]
@daniellex0 - I added the drop shadow.  I believe this is ready to go.

**Review by jbubar — APPROVED** [review]

**Pull request merged**
