### PR TITLE
Feature homepage launch

### LINKED ISSUE #4111: Fix artist's name for Coding credit for redesigned homepage
**Note:** Numbers in brackets (example: [1]) refers to the numbered item in the Resources/Instructions section.

### Overview
We need to fix a misspelled name on a credit for an image used in the redesigned version of the homepage so that the Credits page [1] is accurate.

### Details
From the Homepage Redesign Credits in Figma [2], here is a screenshot of the credit's information for reference and how the artist's name should be spelled:
  <details>
    <summary>Click here to see the screenshot of the Coding credit in Figma</summary>
    
  </details>

Here is a screenshot of the current credit on the Credits page on the feature-homepage-launch branch:
  <details>
    <summary>Click here to see the screenshot of the Coding credit on the feature-homepage-launch branch</summary>
    

  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/coding.yml`, switch the `t` and `z` in the last name so that
  ```
  artist: Ralf Schmizter
  ```
  becomes
  ```
  artist: Ralf Schmitzer
  ```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
  
### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
3. [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
4. [_data/internal/credits/coding.yml on feature-homepage-launch branch](https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/coding.yml)
5. [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
6. This is a follow-up issue to #3130

### PR DESCRIPTION
**Pull request by jefflueck**
Fixes #4111

### What changes did you make and why did you make them ?

  - Updated last name in _data/internal/credits/coding.yml
  - Was: Ralf Schmizter
  - Now: Ralf Schmitzer

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
Availability: Weekdays
ETA: EOD 03/15/2023

**Comment by christinaor** [comment]
Availability: 3/15, 1PM-5PM EST
ETA: 3/15, 5PM EST

**Review by christinaor — APPROVED** [review]
Good job on the change, Jeff! I was able to confirm the change to "Ralf Schmitzer" on the Credits page via Docker. I realize the GitHub Actions bot didn't comment the git commands here, so I had to do a bit of investigating because the usual commands for the gh-pages branch was throwing an error. I noticed your repo's link was a bit different as "website-1", presumably because you might have had a "website" repo before joining Hack for LA's website team.

For reference for other reviewers, these were the git commands I needed to use to successfully pull your feature branch:

```
git checkout -b jefflueck-feature-homepage-launch feature-homepage-launch
git pull https://github.com/jefflueck/website-1.git feature-homepage-launch
```

Just one suggestion to include screenshots next time for pages that have visual changes - the change can be found after running Docker and going to the credits page through the local host of choice. Happy to run through it if you're unsure about this!

**Comment by jefflueck** [comment]
Thank you. 
If you had some time I would like to run through the proper process of using git on a feature branch.
I did follow the wiki but had some issues in getting it set up initially right on my end to have this push to the proper upstream.
I also had a hard time finding the proper page to include a screenshot for this issue.
If you want to DM me I could find some time if you are free to show me the proper process for what I missed.

**Comment by mademarc** [comment]
Review ETA: 3/15/23
Availability: 7:35PM Monday

**Review by mademarc — COMMENTED** [review]
Hey @jefflueck The format looks updated and it looks good.

**Review by KazushiR — APPROVED** [review]
Everything looks good on my end!

**Pull request merged**
