### PR TITLE
Fix Bug on Code of Conduct Page

### LINKED ISSUE #2632: Bug on code of conduct
### Overview
This is a bug that I have found.

When I was searching through Google for our code of conduct, it gave me a link to an incomplete page. Please look at the resources for more information.

Note: Might overlap with #110. I'm not sure 😔 

### Action Items
- [ ] Explore ways to keep [Broken code of conduct page](https://www.hackforla.org/CODEOFCONDUCT.html) from displaying when the site is googled.
    - [x] Try the following possible approach: Jekyll's [configuration ](http://jekyllrb.com/docs/configuration/options/)accepts file exclusions, which prevents the file from being considered when site is built.
- [ ] Make sure the fix/changes do not affect other parts of the website.

### Resources/Instructions
<details>
<summary>Google search</summary>
<br>

<br>
</details>

[Broken code of conduct page](https://www.hackforla.org/CODEOFCONDUCT.html)
- Please read through the commens for additional information and links

### PR DESCRIPTION
**Pull request by michaelmagen**
Fixes #2632 

### What changes did you make and why did you make them ?

  - Created robots.txt file
  - Added User-agent to robots.txt
  - Added disallow of "/CODEOFCONDUCT.html" to robots.txt
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to website.

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: End of Day 10/25/22
Availability: 6 - 8 PM Tuesday

**Review by jdingeman — APPROVED** [review]
Testing changes

**Comment by blulady** [comment]
So this is what I am currently getting when I google the Hack For LA Code of Conduct. @Aveline-art is this what you had in mind when you wrote issue #2632?

Screenshot (274)

**Comment by Aveline-art** [comment]
@blulady I don't quite remember, but if the team says it looks good, then it's good? Maybe ping your product team?

**Comment by blulady** [comment]
@hackforla/product-managment Hi Guys, we have resolved this issue and the screenshot above is what currently comes back as opposed to the page below turning up on internet searches. 
Screenshot (275)

**Comment by marthaalterhines** [comment]
Please remove me from this email list.  Thank you!

**Pull request merged**
