### PR TITLE
Update Alt Text for Food Oasis Image

### LINKED ISSUE #3999: Food Oasis: Update alt text for Food Oasis image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Food Oasis` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/food-oasis.md`:

**From:**
```
Stacks of freshly harvested beets
```

**To:**
```
Food Oasis
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/food-oasis

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/food-oasis.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by Alsuang**
Fixes #3999 

### What changes did you make and why did you make them ?

  -Updated alt text to 'Food Oasis'
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Alt text will display if image is not shown. Otherwise, no visual change to website.

### CODE REVIEW

**Comment by jch1013** [comment]
Review ETA: 3pm
Availability: Any

**Review by jch1013 — APPROVED** [review]
Everything looks good, no visual changes. Nice job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hello @Alsuang  Thanks for taking up this issue! 

I notice that you are attempting to merge directly from your ‘gh-pages’ branch. When you will be working on an issue, you will always want to [create a new branch in your repo](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) where you will make the changes- instead of making changes in your ‘gh-pages’ branch. Then you will be committing / pushing changes and creating pull requests off this new branch. 

If you would like any help with setup or if you have any other questions, please send a Slack to anyone on the merge team and we will be happy to help you!
Thanks again-

**Comment by jch1013** [comment]
@t-will-gillis Didn't catch that, sorry. Thanks for the correction!

**Comment by t-will-gillis** [comment]
@jch1013 - No problem! We're all helping each other

**Comment by Alsuang** [comment]
Hi, thanks for the clarification. I just attempted another pull request and (hopefully) from my created branch. Should I just close this request and just follow the issue on my other request? Thanks for your help.

**Comment by t-will-gillis** [comment]
Hi @Alsuang - yes, you could close with a comment referencing the new PR. If this were a larger issue, it also would be good to assign any of the original Reviewers (@jch1013 and me) to the new PR so they are flagged, but this is fine. Thanks!
- Replaced by #4125

**Pull request closed without merging**
