### PR TITLE
changed chip label for programs and languages to be singular words

### LINKED ISSUE #6298: Continuation: Update chips labels from plural to singular
### Overview
Currently, chip label prefixes for the "Program Areas" and "Languages" filter groups are shown as "Programs" and "Languages" even though singular filter items are listed for either label. This can be confusing to users, so we want to update the chip label prefixes to "Program" on and "Language" respectively. (See related issue #4647.)

### Action Items

- [x] Check the current state of search chip labels under Applied Filters on the [Projects](https://www.hackforla.org/projects/) and [Projects-Check](https://www.hackforla.org/projects-check/) pages.
  - [x] Apply some of the filters to see how the current chips appear under Applied Filters.
- [x] Explore `assets/js/current-projects.js` and understand how the programming of the filters and chips work.  
  - [x] Change the chip label prefix "Programs" to "Program" (on Projects page).
  - [x] Change the chip label prefix "Languages" to "Language" (on Projects-Check page).
  - [x] Using Docker, confirm that both pages display correctly when applying various selections.  
  
Merge team: when complete
- [x] Release dependency on #4648 

### Resources/Instructions

- Chip labels can be found on the [Projects page](http://hackforla.org/projects)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)
- See associated ER for this issue: #4563 
- and #6297

### PR DESCRIPTION
**Pull request by jtw007**
Fixes #6298

### What changes did you make?
  - Changed the chip label prefix "Programs" to "Program" (on Projects page).

### Why did you make the changes (we will use this info to test)?
  - to keep website up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
 
Screen Shot 2024-02-20 at 18 13 35

Screen Shot 2024-02-20 at 18 13 46

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
Screen Shot 2024-02-20 at 18 15 16

Screen Shot 2024-02-20 at 18 15 25

</details>

### CODE REVIEW

**Comment by irais-valenzuela** [comment]
Review ETA: 2/21/24
Availability: 10:00 AM - 2 PM Wednesday

**Review by irais-valenzuela — COMMENTED** [review]
Hi @jtw007, nice job on the issue! The branches are correct, you linked the issue, and successfully changed the chip labels "programs" to "program" and "languages" to "Language". The only reason I haven't approved the PR yet is because I think we can remove the comment above since "languages" has now been addressed. Once you delete that comment you'll be good to go.

**Review by irais-valenzuela — APPROVED** [review]
@jtw007 Nice job on the issue and removing the comment!

**Review by heejung-hong — APPROVED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, tablet, and mobile view), Firefox, and Safari browser.
Programs and Languages have been changed to the singular form.

**Pull request merged**
