### PR TITLE
Update alt text wcag 3875

### LINKED ISSUE #3875: Program Areas: Update alt text for .page-card-image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Program Areas` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `pages/program-areas.html`:

**From:**
```
<img class="page-card-image" src="{{ program_areas[1].image }}" alt="{{ program_areas[1].image_alt }}" />
```

**To:**
```
<img class="page-card-image" src="{{ program_areas[1].image }}" alt="" />
```

- [x] Ensure that the corresponding `Program Areas` page stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

### Resources/Instructions
- https://www.hackforla.org/program-areas

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `pages/program-areas.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/075ce5f7d67c7732e258148b0f4a1a9342095e26/pages/program-areas.html#L24

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by mademarc**
Fixes #3875 

### What changes did you make and why did you make them ?

  -  changed the program areas from `{{ program_areas[1].image_alt }}
`
  - changed to ` `

  - As a developer, we need to provide clear and descriptive alt text on the Program Areas page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

-no visual changes were made

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by RyanGehris** [comment]
Review ETA: 6 PM PT 02/11/2023 Sat
Availability: 6pm-8 PM PT Monday - Friday

**Review by RyanGehris — DISMISSED** [review]
Your changes are clean and effective in creating a more inclusive HackForLA website! Thanks Marco.

**Comment by Jaretzbalba** [comment]
Review ETA: EOD 2/13
Availability: 1 hr

**Review by Jaretzbalba — CHANGES_REQUESTED** [review]
@mademarc Thank you for working on this issue and I see that you were able to remove the alt text as requested in the issue! However, the format of the page was changed in your PR. Please ensure that the rest of the code isn't changed to keep the code readable and clean. i.e. the only change in the file should be on line 24 from the original code with the alt tag.

**Comment by mademarc** [comment]
Hey @RyanGehris No problem as i am glad to contribute for this great organization :)

**Comment by RyanGehris** [comment]
@mademarc I am glad you enjoy contributing to HackForLA so much! It looks like Jaret requested changes to your pull request. If you have any questions, I recommend reaching out to him directly. Once your changes are made, please let myself and Jaret know. I'd be happy to review it again.

**Comment by mademarc** [comment]
hey @RyanGehris Thanks for the feedback and will reach out to @Jaretzbalba on this matter :)

**Comment by plang-psm** [comment]
@Jaretzbalba @RyanGehris Hey everyone, I worked with @mademarc on this. Seems like we can't kink out the extra spaces so we may just accept it the way it is. We were able to fix the formatting, theres just a few extra spaces we can't seem to get rid of. Please review the changes once more and test in docker to ensure site runs smoothly. Thanks for all your help!

**Review by RyanGehris — APPROVED** [review]
The site runs smoothly, and after adding the necessary code changes to comply with WCAG the webpage formatting is unaffected. Great work @mademarc and thank you for helping out @plang-psm

**Comment by mademarc** [comment]
Thanks @RyanGehris and respect @plang-psm for being cool/professional as well :)

**Review by Jaretzbalba — APPROVED** [review]
@mademarc Thank you for making the necessary changes! Everything looks good now and great job on this first issue!

**Review by t-will-gillis — APPROVED** [review]
Hey @mademarc - congrats on your first issue! In Docker the Program Areas page appears to be loading correctly with no issues. Thanks!

**Pull request merged**
