### PR TITLE
Deleted wins-data.json since we are no longer using AF

### LINKED ISSUE #2148: Google Apps Script: Migrate Wins Data - Delete AF file
### Dependency

- #2147
- #4134 
- #3641

### Overview
As a developer, to turn the wins card into a reusable component, we must first be able to generate a wins-data.json file of a more specific format. This issue is part of a series that aims to migrate us to the more specific format.

### Action Items

- [ ] Read the resources/instructions below to understand your task.
- [ ] Delete the AF version of our file from our codebase.
- [ ] Check and make sure that all pages in the website still appears as before this change.

### Resources/Instructions
[wins-page](https://www.hackforla.org/wins/)

Currently we have two json files for wins: [_wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json) and [wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/wins-data.json). The former will henceforth be called KVF (for key-value file) and AF (for array file). AF is generated daily from a script on google while KVF appears to be an older, dysfunc version. The format in the KVF version, however, is much friendlier to formatting in liquid syntax. Therefore, we need to incrementally port our codebase to use the KVF version of the data and remove the AF version we currently use. This will be done in multiple steps:

1. Have the apps script generate both AF and KVF version.
2. Migrate all uses of AF to KVF.
3. Have the apps script stop generating the AF version.
4. Delete the AF version from our repo since it is now unused.

For this issue, we are doing step 4.

### PR DESCRIPTION
**Pull request by steven-positive-tran**
Fixes #2148

### What changes did you make and why did you make them ?

- Deleted [wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/wins-data.json) as this issue is doing step 4 and we are no longer using AF file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visibile changes

### CODE REVIEW

**Review by t-will-gillis — APPROVED** [review]
Hi @steven-positive-tran - The commit 'from' and 'into' branches are correct and there is the relevant linked issue. The 'Wins' page appears to function as expected on Docker, no unexpected issues with the file deletion. The correct file has been deleted `wins-data.json` and the file to remain is untouched `_wins-data.json`. Looks good! Great job.

**Comment by d-perez-8** [comment]
ETA: 1 hour
Availability: 2-4pm PST weekdays

**Review by d-perez-8 — APPROVED** [review]
Great, this looks good, @steven-positive-tran! The issue is completed as instructed and there are no issues with the web page.

**Comment by jdingeman** [comment]
Hi @steven-positive-tran, we appreciate you taking up the issue to remove the AF file, however this issue was not supposed to be in the prioritized backlog and its [dependency](https://github.com/hackforla/website/issues/2147) has not been satisfied. It also seems that the dependency's [dependency](https://github.com/hackforla/website/issues/2147#issuecomment-1303890743) has not been satisfied. Sorry for the confusion. We are going to close this as not planned.

**Pull request closed without merging**
