### PR TITLE
Update alt text for Youth Justice Nav image

### LINKED ISSUE #4023: Youth Justice Nav: Update alt text for the Youth Justice Nav image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Youth Justice Nav image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/youth-justice-nav.md`:

**From:**
```
alt: ''
```
**To:**
```
alt: 'Youth Justice Nav'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Youth Justice Nav Page: https://www.hackforla.org/projects/youthjusticenav

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/youth-justice-nav.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/youth-justice-nav.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by vraer**
Fixes #4023 

### What changes did you make and why did you make them?

  - Changed the alt value within `_projects/youthjusticenav.md` 
  from `alt: ''` to `alt: 'Youth Justice Nav'`
  - Update adheres to the Web Content Accessibility Guidelines (WCAG) and furthers HFLA mission of inclusivity
  - Part of epic https://github.com/hackforla/website/issues/3866

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visible changes to website.

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 3/9 1 am - 1:30 am
ETA 3/9 1:30 am

**Review by roslynwythe — APPROVED** [review]
Great work, @vraer.  The branches are setup correctly, the code change is clean and correct, and the PR does a good job of describing your changes and why you made them.  The Projects page displays perfectly in the browser.

**Comment by perlaroyerc** [comment]
Review ETA: 10 AM 3/10/23
Availability: 11-6 ET PM M-F

**Comment by bootcamp-brian** [comment]
Review ETA: 12:45pm
Availability: Today before 5pm

**Review by bootcamp-brian — APPROVED** [review]
Changes made in the correct file, branches setup correctly, issue linked, and the site is updated in local environment. Great job on your good first issue!

**Review by perlaroyerc — APPROVED** [review]
All the changes are correct, the PR comment is accurate and descriptive, and the branches are properly configured. Keep up the good work!

**Pull request merged**
