### PR TITLE
Update HelloGOV image alt property value

### LINKED ISSUE #4008: HelloGOV: Update alt text for HelloGOV image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `HelloGOV` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/hellogov.md`:

**From:**
```
helloGOV log on top, three mobile devices displaying different areas of the helloGOV application
```

**To:**
```
HelloGOV
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/hellogov

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/hellogov.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by srandolph2**
Fixes #4008

### What changes did you make and why did you make them ?

  - Fixed the image alt property value within _projects/hellogov.md to HelloGOV
  - Changed to make the alt easier to read

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website

### CODE REVIEW

**Comment by chrismenke45** [comment]
Review ETA: 6 PM 2/20 Monday
Availability: Now-6 PM 2/20 Monday

**Review by chrismenke45 — APPROVED** [review]
Looks good! The change can be seen when I run the site in my local environment.

**Comment by Adastros** [comment]
Review ETA (PST): 9:15 PM 20FEB23
Availability (PST): 9 - 10 PM 20FEB23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @srandolph2, good job on completing your first issue! The changes to the alt text for the `hellogov.jpg` matches the changes in the issue and reflects on the website. 

Could you reformat your pull request comment? Looks like the description of the change was formatted as a header instead of a bullet point. 

This is optional, but I find adding a brief explanation of why we're making the changes helps with the review process (why update the alt text?).

**Comment by srandolph2** [comment]
> Hi @srandolph2, good job on completing your first issue! The changes to the alt text for the `hellogov.jpg` matches the changes in the issue and reflects on the website.
> 
> Could you reformat your pull request comment? Looks like the description of the change was formatted as a header instead of a bullet point.
> 
> This is optional, but I find adding a brief explanation of why we're making the changes helps with the review process (why update the alt text?).

Hello! I fixed the bullet point

**Review by Adastros — APPROVED** [review]
@srandolph2 Thanks for updating it! Good job on completing the issue

**Pull request merged**
