### PR TITLE
modified projects/civic-tech-jobs.md-removed Beth Williford

### LINKED ISSUE #5378: Update Project Profile: Civic Tech Jobs (remove Beth Williford)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] **_REMOVE_** the entirety of the entry:
```
  - name: Beth Williford
    role: UX Researcher
    links:
      slack: https://hackforla.slack.com/team/U0312CTAZS4
      github: https://github.com/BethBethBeth
    picture: https://avatars.githubusercontent.com/BethBethBeth
```
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by robertnjenga**
Fixes #5378

### What changes did you make?
  - Update Project Profile: Civic Tech Jobs (remove Beth Williford)
  -
  -

### Why did you make the changes (we will use this info to test)?
  - Update Project Profile
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot hfla-1

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot hfla-2

</details>

### CODE REVIEW

**Comment by Tomomi-K1** [comment]
Review ETA: 6 PM 9/12/2023
Availability: 12-8pm PM M-F

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
Hi @robertnjenga, Thank you for taking up this issue. You used correct branch to commit from and into. You have linked issue and check off all requirements on the issue! Great Job!

Just couple of edits if possible:

- Pull request format looks a bit off since 2 bullet point items are bigger than section titles. You can  put a space after "-" like below example.
    
    from:
    `-Update Project Profile: Civic Tech Jobs (remove Beth Williford)`
    to :
    `- Update Project Profile: Civic Tech Jobs (remove Beth Williford)`

- you added an empty line at line 63 on `_projects/civic-tech-jobs.md` (above `-name: Matt Pereira`)  but that was not instructed in the issue so please remove.
-  your screenshot of after changes are applied has a card with empty name and empty role. 
   but that should not show. Please double check.

**Review by homeroochoa47 — CHANGES_REQUESTED** [review]
What's up, @robertnjenga! Thanks for taking up the issue. I see you've made updates to the formatting for the pull request markdown, and you also removed the empty card that was left in the 'after changes' image prior to your PR edit. Everything looks as expected when running locally as well. 

The one thing to update (which I believe is normally requested in other reviews as well) is to make sure that there are no empty lines in the code after removing the item. It looks like there's an empty line (line 63) where the removed item previously was in this case. Other than that, the branch setup looks great!

Thanks!

**Review by Tomomi-K1 — DISMISSED** [review]
@robertnjenga thank you for updating your pull request and deleting the empty line 63.
Great job!

**Review by homeroochoa47 — DISMISSED** [review]
Hi @robertnjenga, the updates look great, nice work!

**Review by t-will-gillis — APPROVED** [review]
Hey @robertnjenga Great job with the issue and thanks for working with @Tomomi-K1 and @homeroochoa47 to address their comments-  looks good! Congrats on your first issue.

**Pull request merged**
