### PR TITLE
Updated donation gif on Join Us page

### LINKED ISSUE #1254: Update donation gif on Join Us page
### Overview
We need to replace the current donation gif on the [Join Us page](https://www.hackforla.org/join-us) with the new version so that it looks cleaner / there isn't extra cut-off text on its right

### Action Items
- [ ] Replace current donation gif on [Join Us page](https://www.hackforla.org/join-us) with the new version (the new one is used on the bottom of the [About page](https://www.hackforla.org/about))
- [ ] Make sure the layout still looks good with the new gif

### Resources/Instructions
[Join Us page ](https://www.hackforla.org/join-us)
[About Us page](https://www.hackforla.org/about) (scroll to bottom for new gif)
[Hack for LA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Old version:

Screen Shot 2021-03-17 at 11 46 17 PM

New version:

Screen Shot 2021-03-17 at 11 47 38 PM

### PR DESCRIPTION
**Pull request by kevinreber**
Fixes #1254 

Removed `/assets/images/join-us/HfLA-Donate.gif` and replaced it with `/assets/images/about/HFLA-Donate.gif`

<details>

<summary>Before</summary>

image

</details>

<details>

<summary>After</summary>

image

</details>

### CODE REVIEW

**Review by akibrhast — APPROVED** [review]
@kevinreber 
Please fix merge conflicts

**Comment by kevinreber** [comment]
@akibrhast 
Conflicts fixed, waiting for review

**Review by akibrhast — CHANGES_REQUESTED** [review]
Hey @kevinreber , Do you think you could possibly close this PR and make a brand new PR. The change requested is like changing two lines of code.. But due to i think some merge conflict issues it looks like you changed 41 files in this PR. Which is not the case.

**Comment by kevinreber** [comment]
@akibrhast Will do, closing this PR and creating a new one

**Pull request closed without merging**
