### PR TITLE
CONTRIBUTING.md: stopping mid issue text update

### LINKED ISSUE #2768: Contributing.md:  stopping mid issue text update
### Overview
As a developer, I want the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to have accurate instructions. In this issue, we will update a line in section [2.6.b What to do if you have to stop working mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26b-what-to-do-if-you-have-to-stop-working-mid-issue).

### Action Items
- [x] Change [line 457 in the CONTRIBUTING.md](https://github.com/hackforla/website/blob/ca3b53c3d4a5bdd0a4e0e413fe839e7862aef530/CONTRIBUTING.md?plain=1#L457)
  ```
  - Remove the progress in the checkboxes (all checkboxes should be empty)
  ```
  to 
  ```
  - For your issue, uncheck the checkboxes for any action items that have to be redone by the next developer picking up the issue.
  ```
- [x] To see the visual changes for the CONTRIBUTING.md
  - [x] Push the changes to your remote forked repo's topic branch
  - [x] Go to your remote forked repo on GitHub
  - [x] Switch to your topic branch
  - [x] Click on CONTRIBUTING.md file
  - [x] On the upper right, click on "Display the rendered blob" to see what your changes look like. Here is an image of what the "Display the rendered blob" button looks like:   
    image
  
### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `CONTRIBUTING.md`
- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/ca3b53c3d4a5bdd0a4e0e413fe839e7862aef530/CONTRIBUTING.md?plain=1#L457

### PR DESCRIPTION
**Pull request by Garcia1416**
Fixes #2768

### What changes did you make and why did you make them?

  - Changed line 457 in CONTRIBUTING.md from:
  - "Remove the progress in the checkboxes (all checkboxes should be empty)" to 
  - "For your issue, uncheck the checkboxes for any action items that have to be redone by the next developer picking up the issue."
  - Purpose is to give accurate instructions in CONTRIBUTING.md under section 2.6.b

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

2768-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
2768-after

</details>

### CODE REVIEW

**Comment by harshitasao** [comment]
Review ETA : 22/03/2022
Availability : Flexible

**Comment by blulady** [comment]
Review ETA : 3.22.22 1:00pm
Availability : 3.22.22 4-6:00pm

**Review by blulady — APPROVED** [review]
Looks Good. There is a linked issue and it is the correct issue. The images accurately reflect the changes. The source code looks succinct and changes are relevant to the issue.
Great Job!!

**Review by harshitasao — APPROVED** [review]
@Gorck1416 Hi! To me, the changes that you have made appear to be positive. Well done!

**Pull request merged**
