### PR TITLE
Fixes #2220

### LINKED ISSUE #2220: GitHub Actions: Rename "Add Update Label to Issues Weekly" to "Schedule Friday 0700"
### Overview
As a member of the backend team, github actions are much more maintainable and easier to understand if they are structured based on triggers and functionality. For this issue, we want to update [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml) and rename the action to 'Schedule Friday 0700' so all scheduled actions that occur on 7am every Friday can live in this file.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Rename the file from 'add-update-label-weekly.yml' to 'schedule-fri-0700.yml'
- [x] Rename the name of the action from 'Add Update Label to Issues Weekly' to 'Schedule Friday 0700'
    - [x] The name of the job should still stay the same (line 8)
- [x] Update the location of the [accompanying files](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
    - [x] If not created yet, create a new directory under /[github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)/ called trigger-schedule
    - [x] Move the [add-update-label-weekly directory](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly) under /github-actions/trigger-schedule
    - [x] Update the github action's js requirement to reflect the change in directory
- [x] If possible, do a test on your local environment and make sure it still works

### Resources/Instructions

- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Accompanying JS](https://github.com/hackforla/website/tree/gh-pages/github-actions)
- See previous work done on this issue: https://github.com/hackforla/website/pull/3426
- [How to test GitHub Actions](https://docs.google.com/document/d/1A2sj5KROv_AD3qTUrPO-YI730hKj2-o1FnE8GE1PUVY/edit#heading=h.t6xbafvaf6mp)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

### PR DESCRIPTION
**Pull request by poorvi4**
Fixes #2220

### What changes did you make and why did you make them ?
Implemented solutions as suggested in https://github.com/hackforla/website/issues/2220:

- Renamed 'add-update-label-weekly.yml'' to 'schedule-fri-0700.yml'' and updated 'name' env variable to Schedule Friday 0700
- Moved add-update-label-weekly directory to already existing /github-actions/trigger-schedule/ directory
- Updated path to respective add-label.js to reflect current directory structure

Much of the changes are purely for organizational purposes to better maintain the workflows/actions created

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No changes since the directories were reorganized and minor changes were made to accompanying files to better maintain code. Function remains same.

NOTE: One thing to mention is that I'm not entirely sure how to locally test a github action/workflow. If anyone knows, please let me know! I've found this tool [neko](https://github.com/nektos/act) which but I haven't used/tested it myself yet.

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-26

**Comment by BeckettOBrien** [comment]
Availability: 5 Hours
ETA: EOD 2022-07-25

**Review by BeckettOBrien — DISMISSED** [review]
All the changes look correct, so good job! And thanks for letting me know about that tool to test actions, it looks really helpful!

**Comment by arpitapandya** [comment]
Where do we test it? Any specific tool? @BeckettOBrien @poorvi4

**Comment by blulady** [comment]
The [Act from Nektos](https://github.com/nektos/act) tool does look really helpful. Did you try it @BeckettOBrien?

**Comment by BeckettOBrien** [comment]
I did, but so far I only tested it on a different action because I'm still figuring out how to trigger specific scheduled actions or if I have to temporarily add a workflow_dispatch first.

**Comment by blulady** [comment]
I'd love to see a demo on Tuesday @BeckettOBrien. @arpitapandya I will have to test this before I merge it, so if you want we can do that, DM me and we'll can schedule a time.

**Comment by arpitapandya** [comment]
Hey @poorvi4 sorry, I am working on it, I am actually waiting on the GitHub action testing demo as discussed during our last team meeting as I am also having issues in testing. Once we figure that out I will review it. You may ask the team lead if you have to work on next issue since I holding this off for a while.

**Review by Zak234 — CHANGES_REQUESTED** [review]
I checked the changes and it look like you created a new file named "schedule-fri-0700.yml" instead of renaming "add-update-label-weekly.yml" as both files still show up in workflows.

**Comment by poorvi4** [comment]
Oh good catch! I updated the pull request so the add-update-label file should be correctly renamed to schedule-fri-0700

**Review by Zak234 — CHANGES_REQUESTED** [review]
When I run the action, I keep getting this error: 

```
Unhandled error: Error: Cannot find module '../utils/find-linked-issue'
Require stack:
- /home/runner/work/website/website/github-actions/trigger-schedule/add-update-label-weekly/add-label.js
- /home/runner/work/_actions/actions/github-script/v4/dist/index.js
```

Have you experienced this error while running the action?

**Comment by Zak234** [comment]
I think the problem is that line 302 is 
```const path = './github-actions/add-update-label-weekly/update-instructions-template.md'```
and it should be 
```const path = './github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md'```

**Comment by blulady** [comment]
Hey @poorvi4, just wondering if you are still going to be able to finish this pull request. Please post an update or let us know if you won't be able to continue working on the PR.

**Comment by poorvi4** [comment]
Hi sorry for the delay I’ll finish it up in the coming days

**Comment by poorvi4** [comment]
@Zak234 @blulady Hi all, I updated the path as per Sakari's suggestion so everything should be good to go!

**Comment by blulady** [comment]
Hey @poorvi4,
Sorry it has taken me so long to get back to you, I've been wrestling with getting the project board locally. So I am currently running this test in my repo and I keep getting the error
`
Add-Update-Label-to-Issues-Weekly
Unhandled error: Error: Cannot find module '../utils/find-linked-issue'
Require stack:
- /home/runner/work/website/website/github-actions/trigger-schedule/add-update-label-weekly/add-label.js
- /home/runner/work/_actions/actions/github-script/v4/dist/index.js`
Which is odd because [utils](https://github.com/blulady/website/tree/poorvi4-add-update-label-restructure-2220/github-actions/utils) is in the same place it was relative to where the new file is.

Did you want to keep working on this or should we hand it off to someone else?

**Review by blulady — CHANGES_REQUESTED** [review]
Hey @poorvi4,
Sorry it has taken me so long to get back to you, I've been wrestling with getting the project board locally. So I am currently running this test in my repo and I keep getting the error
`
Add-Update-Label-to-Issues-Weekly
Unhandled error: Error: Cannot find module '../utils/find-linked-issue'
Require stack:
- /home/runner/work/website/website/github-actions/trigger-schedule/add-update-label-weekly/add-label.js
- /home/runner/work/_actions/actions/github-script/v4/dist/index.js`
Which is odd because [utils](https://github.com/blulady/website/tree/poorvi4-add-update-label-restructure-2220/github-actions/utils) is in the same place it was relative to where the new file is.

Did you want to keep working on this or should we hand it off to someone else?

**Comment by blulady** [comment]
Reached out to Poorvi on slack as well. No response. Putting this back into the new issue approval.

**Pull request closed without merging**
