### PR TITLE
Update the meeting times on the CoP page

### LINKED ISSUE #7072: Use VRMS data to update the meeting times on the CoP page
### Overview
We need to automate the update of meeting times on the Communities of Practice page [^1] in a similar way as we do on the Events [^2] and individual project pages using VRMS data. Currently each CoP project is manually updated in the yml files under `_data/internal/communities` [^3].

### Action Items
- [x] Create `communities-of-practice.js` file in `assets/js/` directory
- [x] Remove the meeting-times key from `_data/internal/communities` [^3]
- [x] Pull the meeting times from the VRMS data similar to how the project's pages [^4] using the VRMS data from `_data/external/vrms_data.json` [^5].
- [x] Take a look at `assets/js/project.js`[^6] and see how it utilizes `assets/js/utility/vrms-events.js`. Pay special attention to the following code:  ```{% assign vrmsData = site.data.external.vrms_data %}
const vrmsData = JSON.parse(decodeURIComponent("{{ vrmsData | jsonify | uri_escape }}"))```
- [x] Modify the HTML structure of `communities-of-practice.html` to accommodate the display of meeting times fetched from VRMS data.
- [x] Include `communities-of-practice.js` into the `communities-of-practice.html` file

### Resources/Instructions
[^1]: [Communities of Practice (CoP) page](https://www.hackforla.org/communities-of-practice)
[^2]: [Events page](https://www.hackforla.org/events/)
[^3]: [_data/internal/communities](https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities)
[^4]: https://www.hackforla.org/projects/311-data
[^5]: https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json
[^6]: https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js
- #5328

### PR DESCRIPTION
**Pull request by del9ra**
Fixes #7072

### What changes did you make?
- Created `communities-of-practice.js` as there was no JavaScript file for the CoP page to handle dynamic content.
- Modified `communities-of-practice.html` to include a placeholder `<span id="meeting-times-..."></span>` for meeting times. This allows meeting times to be fetched from JSON data and displayed automatically, ensuring they are always up-to-date without manual updates. Included `communities-of-practice.js` at the end of the HTML file.
- Removed the meeting times key from `_data/internal/communities`.
- Pulled meeting times from the VRMS data similar to how project pages use VRMS data from `_data/external/vrms_data.json`.
- Created `getMeetingTimes` function to retrieve and format meeting times in Pacific Time (PT) using a 12-hour clock. It includes a formatter to get the full name of the day of the week and make it plural.
- Created `setMeetingTimes` function to set the meeting times for each community and update the HTML with the meeting times. It maps community names to their corresponding project names and formats the community name from the element ID.

### Why did you make the changes (we will use this info to test)?
- To move from using static YAML data to dynamic JSON data, making it easier to update and manage meeting times.
- To automate the process of displaying meeting times in a consistent and user-friendly format on the webpage.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-08-02 at 21 41 32

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-08-08 at 11 53 13

</details>

### CODE REVIEW

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@del9ra  This PR looks great.  My only request is a minor change to the formatting of the meeting times, based on https://github.com/hackforla/website/issues/7072#issuecomment-2201593251.  It looks as if we want spaces surrounding the dash that separates the start and end times.

**Comment by del9ra** [comment]
> @del9ra This PR looks great. My only request is a minor change to the formatting of the meeting times, based on [#7072 (comment)](https://github.com/hackforla/website/issues/7072#issuecomment-2201593251). It looks as if we want spaces surrounding the dash that separates the start and end times.

Done! Please review my changes.

**Review by roslynwythe — APPROVED** [review]
Great job @del9ra 
- code changes are clean and correct
- PR has well-formed branches, description of changes and screenshots
- changes check out in the browser
- you updated the cop data files to clean out the old meeting time data

**Review by t-will-gillis — APPROVED** [review]
Hey @del9ra Awesome work-
- branches are good
- good description of what was done and why
- relevant screen shots included
- good changes are clean and appropriate

Formatting appears good in Docker.  

Great job again and thanks for working on this!

**Pull request merged**
