### PR TITLE
Removed Thomas Demoner from _projects/expunge-assist.md

### LINKED ISSUE #5752: Update Project Profile: Expunge Assist (Remove Thomas Demoner)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, remove
```
  - name: Thomas Demoner
    role: Product Manager, Development
    links:
      slack: 'https://hackforla.slack.com/team/U02DFJ72V8Q'
      github: 'https://github.com/thomasdemoner'
    picture: 'https://avatars.githubusercontent.com/thomasdemoner'
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [ ] Once your pull request is merged, go to #5627 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      
    </details>

### Resources/Instructions
- This issue was initiated by #5627

[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by ChrisKildunne**
Fixes #5752

### What changes did you make?
  - Deleted Thomas Demoner from leadership in projects/expunge-assist.md file

### Why did you make the changes (we will use this info to test)?
  - To keep an up to date list of the current project team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by freaky4wrld — COMMENTED** [review]
Hey there @ChrisKildunne , well the issue you did is done completely and correctly, but here are some changes in your [comment](https://github.com/hackforla/website/pull/5884#issue-1982632952l), you can see `three dots` , and then edit it.

In your `What you changed` and `Why did you make changes` column
- Give a space between the `-` and the content, so it would be converted into bullets.
- Also remove the empty `-` so that they look nice and I can approve it.
- Just tag me here when you are done, I'll approve it ASAP

**Comment by ChrisKildunne** [comment]
Hey @freaky4wrld I just made the changes. I am pretty new to this I appreciate your patience!

**Review by freaky4wrld — DISMISSED** [review]
Great work there @ChrisKildunne ,

- The merging branch is correct
- The changes made are correctly mentioned, also the reason is clearly specified
- The changes made are visually shown and works similarly on the local branch

I appreciate your work done, since you are new to this and approve this !!

**Review by kwangric — CHANGES_REQUESTED** [review]
Hi @ChrisKildunne! Your branches are set up correctly and the requested changes were made. Your PR also includes details about the changes made and why. Great work!

Looking at the files changed, it looks like two additional files were added that aren't related to the issue (`eval "$(ssh-agent -s)"` & `eval "$(ssh-agent -s)".pub`). Can you remove these files from your branch?

**Comment by ChrisKildunne** [comment]
I just removed the files from the branch and pushed the changes. It should be reflected in the pull request.

**Comment by kwangric** [comment]
Hey @ChrisKildunne, it doesn't look like the changes were pushed to the PR. The files are still there in your latest commit.

**Comment by ChrisKildunne** [comment]
Copy, I just tried to do it again. I am struggling a bit with GitFlow. Please let me know if the changes were made.

**Pull request closed without merging**
