### PR TITLE
removed Brian Mui from Site Project Team

### LINKED ISSUE #4954: Update Project Profile:  Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Remove the following lines:
 ```
 - name: Brian Mui
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U04MFMMNJRH
      github: https://github.com/bootcamp-brian
    picture: https://avatars.githubusercontent.com/bootcamp-brian
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jnomad21**
Fixes #4954

### What changes did you make?
I removed the profile of Brian Mui from the Website Leadership page, as directed in the issue

### Why did you make the changes (we will use this info to test)?
There was a 'Good First Issue' requesting to remove this profile

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by ronaldpaek — APPROVED** [review]
Nice work

**Comment by roslynwythe** [comment]
Hi @one2code please leave an Availability and ETA for the review.  Thank you!

**Comment by one2code** [comment]
**ETA:** 7/19/23
**Availability:** 11:30 - 12:00 am

**Review by one2code — CHANGES_REQUESTED** [review]
@jnomad21 The changes look good, and your merge is into the correct branch. The only thing I would ask, is for you to take the time and check off the task lists on the issue for completeness.

**Comment by jnomad21** [comment]
@one2code done.  Thanks for the heads up, I didn't realize those were clickable.

**Comment by blulady** [comment]
there is also a way to request a re-review after you make changes

request review

**Comment by jnomad21** [comment]
@blulady thank you very much.  I just did that.  I appreciate the help.

**Review by blulady — APPROVED** [review]
You are going from the correct branch to the correct branch. There is a linked issue and the issues is addressed correctly by getting rid of lines 51-56. There is only one commit and no other files changed. Good job!!

**Review by one2code — APPROVED** [review]
@jnomad21 Thank you for taking the time to close off the tasks on the issue. Excellent job on the PR.

**Comment by mademarc** [comment]
Review ETA: 7/20/2023
Availability: 7:18PM

**Review by mademarc — APPROVED** [review]
Hey @jnomad21 the removal of the name and info in the code was done very well.

**Review by adrianang — APPROVED** [review]
As everyone noted, the branching is set up correctly, the corresponding issue is linked, and changes are exactly what was requested. It looks as I expect it to when I check on my machine.

Nice work @jnomad21 — thanks for taking up this issue!

**Pull request merged**
