### PR TITLE
Updated Labels From Missing Series in Suggest a Guide Template Page

### LINKED ISSUE #4487: Update labels: Issue Template: suggest-a-guide
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/suggest-a-guide.md`
- [x] Replace the following line
   ```
   labels: documentation, enhancement
   ```
   with
   ```
   labels: ['documentation', 'enhancement', 'role missing', 'Feature Missing', 'Complexity: Missing', 'size: missing']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL]

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/suggest-a-guide.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by imvan2**
Fixes #4487

### What changes did you make and why did you make them ?

  - Added `labels: ['documentation', 'enhancement', 'role missing', 'Feature Missing', 'Complexity: Missing', 'size: missing']` per instructions to `.github/ISSUE_TEMPLATE/suggest-a-guide.md` per instructions
  - Made the changes so we can avoid Github bot taking off the labels when devs add them to issues

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visuals before changes are applied.

<details>
No visual changes to the website.
<summary>Visuals after changes are applied</summary>

update-suggest-a-guide-4487-screenshot

</details>

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: (https://github.com/imvan2/website/issues/new?assignees=&labels=documentation%2Cenhancement%2Crole+missing%2CFeature+Missing%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=suggest-a-guide.md&title=)

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Comment by 93Belen** [comment]
Availability: Sunday, Monday, Tuesday and Sunday from 6am to 6pm
ETA: Monday by 6pm

**Review by 93Belen — CHANGES_REQUESTED** [review]
Hi! Great job with this PR!
- The PR is done from the correct branch.
- You linked the Issues correctly
- and made the correct changes in the code
- You did great adding the link for reviewers
- and making a descriptive title and adding the visual to your description, 
- but I am requesting changes so you can explain in the description why you made these changes. Right now you just say "per instruction" but that doesn't explain much. The reason to make this changes is so that we can avoid the GitHub bot taking off the labels when devs add them to issues.

**Comment by imvan2** [comment]
Hi @93Belen! Thanks for catching that. I've added the reasoning to my PR.

**Review by 93Belen — APPROVED** [review]
That was quick! thanks!
Next time when you make some requested changes you can request another review by clicking here
Screenshot 2023-05-26 at 5 32 00 PM
You don't need to do it now because I did it :)

**Review by t-will-gillis — APPROVED** [review]
Hey @imvan2 - Great job! Your branches are correct, you link to the original issue, your description says what changes you made and why (thank you @93Belen for your review comments and thank you Van for picking those up), and you added a link to the new issue in your repo showing the correct labels.

Thanks!

**Comment by rdhmdhl** [comment]
availability: weekdays 5-9pm; weekends 9-5pm
ETA: 5/31

**Comment by rdhmdhl** [comment]
Hey @imvan2 ! Great job linking the issue, and understanding the testing procedure. The changes you've made to the file look correct. I've used the link you provided to see the labels added -- looks good. Approved.

**Pull request merged**
