### PR TITLE
Change alt text 3401

### LINKED ISSUE #3401: Update alt text for Climate Action goal logo on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-sustainability.html`, change the following alt text

From
```
Climate Action goal logo
```

To
```
13 Climate Action
```

- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/about-page/about-card-platform.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a83dd650b664618ff2352b2fb93e8ae4acfb402b/_includes/about-page/about-card-platform.html#L77

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by maryjng**
Fixes #3401

### What changes did you make and why did you make them ?
- Per issue instructions, updated alt text on file Line 53 from "Climate Action goal logo" to "13 Climate Action"

### Screenshots of Proposed Changes Of The Website
- No visual changes were made to the website.

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 1/10/23 6:30pm
Availability: 1/10/23 til 9pm

**Review by jyaymie — CHANGES_REQUESTED** [review]
Great work, @maryjng! You made the changes discussed in the linked issue and used the correct branches in your PR. However, additional changes in `_data/internal/credits/website.yml` appear to be beyond the scope of the issue. Were these changes part of your good first issue? Maybe your local repo was not up-to-date with the main site before you worked on this second issue? In any case, I would restore the code as it was in that file and make another commit. Let me know what you think!

**Comment by jyaymie** [comment]
Oh! I see that your [good first issue](https://github.com/hackforla/website/pull/3804#issue-1527644073) has not yet been merged. We typically wait until our PR is merged before we move on to another issue, but I think keeping this PR will be ok once those changes are removed.

**Review by jyaymie — APPROVED** [review]
You've fulfilled the issue's requirements. Approved!

**Review by arpitapandya — CHANGES_REQUESTED** [review]
@maryjng Code changes are correct, but before I merge could you assign yourself to add issue, move it from `prioritized-backlog` to `in progress- actively working` column and add your ETA and Availability to the issue. #3401.

**Review by arpitapandya — APPROVED** [review]
All the changes are correct! Great job!! @maryjng

**Pull request merged**
