### PR TITLE
Created site.imgdir as an image asset reference

### LINKED ISSUE #1139: Create Jekyll image path structure
### Overview
Research how to src image urls using liquid syntax instead of hardcoding the path to avoid incorrect paths with future restructuring of site.

### Action Items

- [ ] Research how to src image urls using liquid syntax instead of hardcoding the path to avoid incorrect paths with future restructuring of site.
- [ ] Make sure nothing breaks
- [ ] please include a comment on issue #1027 and how you did it
- [ ] create new issues to rewrite image paths using liquid syntax if its possible

### Resources/Instructions
https://jekyllrb.com/docs/
https://yaml.org/
@alyssabenipayo

### PR DESCRIPTION
**Pull request by csseu**
Responsive to #1139.

- Added imgdir as a site-wide variable in _config.yml. It's a URL fragment relative to the root directory so that it should work whether live on github, or in your local instance. 
- Changed all instances of assets/images/ (and variations thereof) to refer to this new site variable. 
- Projects and Credit collections, and event data referred to images using different keys. I made this consistently image-url. Then updated the liquid templating so that collections can be referred to using the site.imgdir variable in conjunction with the image-url.
- Confirmed that this works with Akib's new Event page structure and Martha's About-Us page. Quick run-through of the site on my machine seems to show all images present.

Sorry this is an update with multiple types of changes, but I thought it would be better to submit a full working site without any broken images...

We would want to inform developers that they should refer to images using the liquid tag {{ site.imgdir }}. I can document this somewhere if/when we decide we want to finalize this merge.

For the collections, I left the subdirectory (e.g., testimonials/) in the YAML front-matter.

<details>
<summary>Screenshot showing that there is now only one reference to assets/images, in the _config. yml:</summary>
<br>

</details>

Screenshots of key pages in the site from my local server:
<details>
<summary>About Us pg</summary>
<br>

</details>

<details>
<summary>pg 2</summary>
<br>

</details>

<details>
<summary>Wins pg</summary>
<br>

</details>

<details>
<summary>Sample project page (100 automations)</summary>
<br>

</details>

<details>
<summary>Events page</summary>
<br>

</details>

Big thanks to Akib for helpful discussions and getting me unstuck at one point!

### CODE REVIEW

**Comment by jbubar** [comment]
Wow! This looks really great! tomorrow, I will have time to pull this to my machine and do a proper review.. but for now, I have an uninformed question (lol).. 
If we have an html file that is embedded within two folders. such as 
`/pages/wins/wins.html`

would we have to write

> `src="../{{ site.imgdir }}/wins-page/avatar-default.svg"`
>or
>` src="{{ site.imgdir }}/wins-page/avatar-default.svg"`

thanks for sharing your jekyll knowledge

**Comment by csseu** [comment]
@jbubar Great question/point, made me realize that I had a brain fart about structure and that I intended imgdir to be with respect to the root no matter what directory we're in. Updated _config.yml in a new commit and we would use the latter, I believe.

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@ruqpyL2 - This is a really impressive undertaking.  There are a lot of moving pieces here and you're doing a good job of herding them all together. 

I downloaded this to my machine and noticed a couple of things: 

1) I got a Liquid Warning:

<details>
<summary>Liquid  warning</summary>
Screen Shot 2021-03-01 at 9 05 25 AM
</details>

I'm guessing this is where it's tripping up. On quick glance it looks like that should be okay, but it's the same syntax on all of the pages that are throwing an error when it loads in docker.  
<details>
<summary>getting-started.html</summary>
Screen Shot 2021-03-01 at 9 06 56 AM
</details>

2) Lots of images aren't showing up for me. I don't think this is a cache on my end; I've tried it in all of the browsers I have and cleared the cache and I'm still getting this.  (Anyone, Please let me know if this is just me). 

<details>
<summary>Missing project images</summary>
Screen Shot 2021-03-01 at 9 24 28 AM
</details>

<details>
<summary>Missing getting started images</summary>
Screen Shot 2021-03-01 at 9 29 54 AM

</details>

I'm just going to leave the review here for the moment until we get this sorted out.  (@jbubar - When you pull this down to your machine let me know if you are seeing the same thing, or if this is just me).

**Comment by drubgrubby** [comment]
@cnk - This change is intended to avoid incorrect image paths in some of the planned, and not-yet-planned restructuring.  Since the change is fairly wide-ranging, I'd love it if you could weigh in.  Is there any reason NOT to do this? Future issues we might not have thought of?   Thanks.

**Comment by jbubar** [comment]
Many photos are missing on my end too
<details>
<summary> home page </summary>


</details>


And I got the same liquid syntax errors.. @ruqpyL2 I wonder why it looked good on your server and not on ours.. could you look it over again and make sure that all the photos are showing up?

**Comment by csseu** [comment]
Ooh. Yeah, that liquid code is an oversight on my part from the
find/replace. In addition to deleting the extra `"{{` , I would take out
the absolute_url filter (unless there is a compelling reason to use it...in
which case we can def put into proper syntax)

Newbie question, it seems like my machine/setup is hiding the error
messages that you got. How do you get the verbose output? What other
tips do you suggest that would enable me to do a more stringent review next
time?

Re: images, I wonder if that's a cache issue hiding mistakes from me.
Otherwise, I did initially have an issue yesterday with .svg images not
rendering on something someone else correctly wrote, and this resolved when
I upgraded ruby and jekyll.

I may not be able to get to this until Wednesday night so if someone else
wants to step in, I'm totally cool with that.

**Comment by jbubar** [comment]
<details>
<summary>I see the errors in my terminal where I typed the docker-compose up command</summary>

</details>

We recommend folks use docker to run the site locally if they can get docker running. here is that part of the contributing.md file
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-4-setting-up-docker

I am not sure where you would see those errors if you were running jekyll locally

@ruqpyL2 if you would like to hop on the Communities of practice page #1137 that you assigned yourself too on sunday. That is probably more important. 
This is a good start. I am going to make this pr a draft and we can talk about it in the next meeting (tuesday at 7pm pst).

let me know what you think.. you can always reach me on slack. My display name is just [Josh Bubar](https://hackforla.slack.com/team/UMNNMHXV2)

**Comment by akibrhast** [comment]
@ruqpyL2  @jbubar @cnk @drubgrubby ,

We might also want to somehow integrate this in whatever we are linking?
https://jekyllrb.com/docs/liquid/tags/#links -> `{% link _collection/name-of-document.md %}`

> One major benefit of using the **link** or post_url tag is link validation. If the link doesn’t exist, Jekyll won’t build your site. This is a good thing, as it will alert you to a broken link so you can fix it (rather than allowing you to build and deploy a site with broken links).

**Review by akibrhast — CHANGES_REQUESTED** [review]
I receive the following log error when navigating to the events page, and none of the images are loading. Could you please look into what's going on?

<details>
<summary>Broken Event Page Render</summary>

image

</details>

<details>
<summary>Log Text</summary>

```bash
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/meetup.svg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/happy-hour.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/meetings.svg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/org-projects.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/locations.svg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/building.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/westside1.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/engage.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/lucky-parking.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/hellogov.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/new-schools-today.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/public-tree-map.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/not-today.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/vrms.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/website.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/undebate.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/record-clearance.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/DTLA.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/311.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/civic-tech-index.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/tdm-calculator.jpg' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/home-unite-us.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/hack-nights/southla.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/writeforall.png' not found.
hfla_site    | [2021-03-01 21:53:44] ERROR `/projects/food-oasis.jpg' not found.
```

</details>

**Comment by csseu** [comment]
Welp...I fixed the liquid tags on the getting started pages (d5dbcfb), installed and set up Docker in hopes that having the same environment might get me in sync with y'all... *

All of the images load whether I run the server from Docker or my native Windows environment, they load even when I cleared my cache, they load when I use browsers I don't usually use. I don't know what's going on that makes the relative URLs render for me but not for the rest of you. Something something Windows vs. Linux? Time to for me fire up the old Fedora laptop?

@jbubar Agreed, I'll switch gears to the other project. I won't be at tomorrow's meeting but will update for Sunday and likely join next week. Thanks all for patience and help!

**Comment by jbubar** [comment]
Thanks for you contributions @ruqpyL2! See you when we see you. And I would love to figure out why the images show up for you but not us. That's a real head scratcher. Later tonight I'll pull your changes and clear cache again to check.

**Pull request closed without merging**
