### PR TITLE
Refactored image tag in section 1.3 in CONTRIBUTING.md

### LINKED ISSUE #7093: img tag refactor in CONTRIBUTING.md Sec 1.3 - first
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open the file `CONTRIBUTING.md`
- [x] In Section 1.3 change
```
  <img src="https://user-images.githubusercontent.com/21162229/137044762-c80f18e8-b785-48fb-a286-81c1117c0178.jpg" />        

```
to
```
  <img src="https://user-images.githubusercontent.com/21162229/137044762-c80f18e8-b785-48fb-a286-81c1117c0178.jpg">      

```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.** 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL (also store the test URL for use in a later step)
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```

### Merge Team
- [ ] After closing this issue, check off the dependency in #6453.  If all dependecies have been completed, close #6453 and check off its dependency in #4362.  If all dependencies have been completed in #4362, close it.  

### Resources/Instructions
1. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. This issue is part of #6453

### PR DESCRIPTION
**Pull request by maadeshsivakumar**
Fixes #7093 

### What changes did you make?
- Refactored img tag ending with a slash () to an img tag without an ending slash 

### Why did you make the changes (we will use this info to test)?
To make the codebase consistent with how we use img HTML tags

- For Reviewers: Do not test changes locally, rather test changes at [[TEST URL]](https://github.com/maadeshsivakumar/website/blob/refactor-img-tag-7093/CONTRIBUTING.md)
  
### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

### CODE REVIEW

**Comment by FamousHero** [comment]
availability: 5-6pm Mon-Fri
eta: EOD 9/20

**Review by FamousHero — CHANGES_REQUESTED** [review]
Hi @maadeshsivakumar, Thanks for taking on this issue! 
Things you did well:

- Code looks good
- Branch name is descriptive & has issue number
- Testing instructions work

Things to Fix:

- add file changed to PR title to make it easier to see what this is changing (in `CONTRIBUTING.md`)
- Link the issue number in the PR after `Fixes #` . This will add all the proper labels on the side.
- Say HOW you refactored the image tag so that we know what changed
- Say why you made these changes under **Why did you make the changes (we will use this info to test)?** (if you need help, read the issue carefully to see why)
- Assign yourself the issue. While you wrote it in your branch, you never assigned it to yourself so it's hard to keep track of who's working on it

Please ask for a re-review once these changes are made. Thanks!!

**Comment by terrencejihoonjung** [comment]
availability: everyday, 5pm - 9pm PST
eta: 9/21/24, 11:59pm PST

**Review by codyyjxn — APPROVED** [review]
@maadeshsivakumar Good job on taking this issue!
Thank you for addressing those changes. Just a small note—there’s no need to assign your own PR. Other than that, the changes look great, and the branch name is appropriate as well. I appreciate your attention to detail..

**Review by terrencejihoonjung — APPROVED** [review]
Hi @maadeshsivakumar,

Looks great! You did the following correctly:
- state changes clearly and why they were made
- branch naming 
- wrote a clear PR title
- correctly modified the `img` element

Thanks for your contribution!

**Comment by daras-cu** [comment]
@maadeshsivakumar please see my comment on the original issue [7093](https://github.com/hackforla/website/issues/7093#issuecomment-2369319533)

**Review by FamousHero — APPROVED** [review]
Changes look good! Thanks for your hard work!

**Review by k-cardon — APPROVED** [review]
Looks good! PR is clear, branch name is descriptive, changes are correct--thanks for doing this!

**Pull request merged**
