### PR TITLE
Remove font type and font weight

### LINKED ISSUE #2961: Remove font-size and font-weight from .getting-started-step-title-faq class
### Overview
As a developer, I want to remove font-size and font-weight from [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class because it is redundant code 

### Details
We want to remove font-size and font-weight from [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class because these should now be dependent on title4 class. Note: If we have two classes with same specificity, the class that is later in the aggregated [main.scss](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/main.scss) file will be used, which may not be the title4 class.

### Action Items
- [x] Review [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class  in the [Getting Started page](https://www.hackforla.org/getting-started)
- [x] Remove lines 372-373 from [Getting Started page scss file](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss):https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L372-L373
- [x] Please search our codebase (using VS code or GitHub search functionalities) to ensure  [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class isn't being reused at other places in our website
- [x] If [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class is being used at multiple places, make sure existing functionalities are not impacted by this change 
- [x] Make sure [Getting Started page](https://www.hackforla.org/getting-started) looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)
- [Getting Started html file](https://github.com/hackforla/website/blob/b8d2700a5f95538b9ddbc83b9ecd6e010b307fc1/pages/getting-started.html)
- [Getting Started page scss file](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss)
- [.getting-started-step-title-faq](https://github.com/hackforla/website/blob/5e3c221a51919423c6d3073b9c334b7e3ad3093a/_sass/components/_getting-started-page.scss#L371-L374) class

### PR DESCRIPTION
**Pull request by clayton1111**
Fixes #2961 

### What changes did you make and why did you make them ?

  - removed font size and font weight from getting-started-step-title-faq class
  - made sure existing functionalities are not impacted by this change

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by clayton1111** [comment]
I haven't been able to get rid of these other commits. The majortiy of them are merges to update my repository, or previous commits from when I first joined that cancel each other out (when I was still figuring out how to work git). Any advice on how to get rid of them?

**Comment by BeckettOBrien** [comment]
Availability: 2 Hours
ETA: EOD 7/15/22

**Review by BeckettOBrien — COMMENTED** [review]
The changes are correct, the site looks good, and I searched the codebase for all elements that use the `getting-started-step-title-faq` class to make sure it only gets used on the getting started page. I don't know that the branch name is correct though, it has the right issue number but the description doesn't seem relevant. Also, I'm not quite sure what to do about the old commits. Are you sure you created the new branch from `gh-pages` and not from an old issue branch you were working on?

**Review by Zak234 — APPROVED** [review]
I looked at the code and tested it and everything seems to work fine. I do agree with Beckett that it looks like you either used a branch from a previous issue or forked from one instead of gh-pages. It shouldn't be a problem for this pull request but should be fixed in future pull requests.

**Review by BeckettOBrien — APPROVED** [review]
It looks like the previous commits haven't been too big of a concern on other PRs so, given that the changes are good, I'll approve it and let the merge team decide if it's an issue or not.

**Pull request merged**
