### PR TITLE
Add Github Handle for Nino Dzotsenidze in tech-work-experience.md

### LINKED ISSUE #7253: Add github-handle for Nino Dzotsenidze in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Nino Dzotsenidze
```
with
```
- name: Nino Dzotsenidze
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by izma-mujeeb**
Fixes #7253 

### What changes did you make?
  - Using spaces, I added a variable to hold the github-handle for Nino Dzotsenidze 

### Why did you make the changes (we will use this info to test)?
  - The reason why I need to add a single variable holding the github-handle is because eventually this variable will replace the github and picture variables. This is being done for every member of the leadership team to ensure that we are writing efficient code and reducing redundancy. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website

### CODE REVIEW

**Comment by mrodz** [comment]
**Availability**: Weekdays 5pm-9pm, Weekends 10am-5pm
**ETA**: EOD 8/18

**Comment by 8alpreet** [comment]
Review ETA: EOD
Availability: Mon to Fri; 3 p.m. to 7 p.m.

**Review by mrodz — APPROVED** [review]
Hi @izma-mujeeb! Good work on this issue.
- Correctly linked issue number
- Correct to/from branches
- Correctly modified Nino Dzotsenidze's yaml object, added `github-handle`
- Correctly used spaces
- Good description of the issue (for future issues, if you don't have enough items in the bullet point list, you can remove the extra `-`)

Keep it up :)

**Comment by 8alpreet** [comment]
Hi @izma-mujeeb,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- Branch is named correctly
- Only relevant lines of code were changed.

### Changes needed:
1. In the "why did you make these changes" section
    - You're correct in stating the purpose of the "github-handle" key; however, the full reason for the change is not being communicated. It would be great to have the true "why" of the change. This section should allow the reader/reviewer to get the gist of the related issue without having to open the issue itself.

**Review by mmcclanahan — CHANGES_REQUESTED** [review]
Hey @izma-mujeeb! 

Great job adding the github-handle. 
One quick thing that could be changed for clarity is the PR name. Adding whose github handle variable was added would be helpful for readers. Such as: Added Github Handle Variable for Nino Dzotsenidze

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @izma-mujeeb,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- Branch is named correctly
- Only relevant lines of code were changed.

### Changes needed:
- In the "why did you make these changes" section
- You're correct in stating the purpose of the "github-handle" key; however, the full reason for the change is not being communicated. It would be great to have the true "why" of the change. This section should allow the reader/reviewer to get the gist of the related issue without having to open the issue itself.

**Comment by minkang3** [comment]
ETA: EOD
Availability: 11-5 Weekdays

**Review by minkang3 — CHANGES_REQUESTED** [review]
Everything looks good except the "Why did you make the changes" section in your PR.

The language "We needed..." doesn't show a clear understanding of the issue and why it needed to be fixed. Rather than saying you did the changes because you needed to, look for the underlying problem that is being fixed.

**Review by minkang3 — APPROVED** [review]
Looks good!

**Review by 8alpreet — APPROVED** [review]
Thank you for applying the feedback!

**Review by mmcclanahan — APPROVED** [review]
Awesome!

**Pull request merged**
