### PR TITLE
updated photo

### LINKED ISSUE #6296: Replace Team Hands Middle image in Credits page on Feature Homepage Launch branch
### Overview
We need to replace the "Team Hands Middle" graphic on the Credits page, within the feature homepage branch.  The new graphic file should simply replace the existing file, so the filename and references to the image will be unchanged.  

### Action Items
- [x] Work on this issue will be merged into hackforla/feature-homepage-launch.  For information about working on a feature branch, see https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
- [x] Download the "New image" from the Resources section below, then rename it `/team-hands-middle.jpg` and save it in the folder `/assets/images/credits`
- [x] Using Docker, view the Credits page (/credits) and confirm that the appearance of the credit for the "Team Middle Hands" image (text and image) matches the "Current appearance of the Credit for the Team Middle Hands image" screenshot below, except for the rotation of the image

### Resources/Instructions
<details><summary>New Image</summary>

team-hands-middle

</details> 

<details><summary>Current appearance of the Credit for the Team Middle Hands photo</summary>

image

</details> 

Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

### PR DESCRIPTION
**Pull request by evan-ishibashi**
Fixes #6296

reference to https://github.com/hackforla/website/pull/6504

Original branch got deleted after updating name to include the issue number

### What changes did you make?
  -  Downloaded provided asset and replaced the current one with the newly rotated image.

### Why did you make the changes (we will use this info to test)?
  - Photo should be displayed properly for when the page goes live.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
 

image

</details>

### CODE REVIEW

**Comment by Jperparas** [comment]
**Availability:** 3/27
**ETA:** EOD 3/27

**Comment by JackCasica** [comment]
Hi Evan ~ I'll be reviewing this PR today.
Availability: 3/27
ETA: EOD 3/27

**Review by JackCasica — APPROVED** [review]
Hi Evan,

Awesome ~ In this PR you...
- [x] Added the issue number to the branch name ✅
- [x] The PR is going to the correct feature branch (`feature-homepage-launch`) ✅
- [x] kept original file naming so as to not affect any references ✅
- [x] Fixed the rotation of the image so that it displays correctly on the page ✅. Here's what I see locally:
image

PR approved!

**Review by Jperparas — APPROVED** [review]
Hi Evan,
looks good to me!
- [x] PR done in correct branch
- [x] Fixes linked issue
- [x] only one file changed
- [x] file name is correct
What I see locally:
team-hands-local-environment

**Pull request merged**
