### PR TITLE
Fix linting error on about page

### LINKED ISSUE #5366: Refactor HTML: _includes/about-page/about-card-platform.html - Sustainability
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/sustainability.svg" alt=""></span><span class="sub-head-text color-darkorchid">Sustainability</div>
```
to
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/sustainability.svg" alt=""></span><span class="sub-head-text color-darkorchid">Sustainability</span></div>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by romainyvernes**
Fixes #5366

### What changes did you make?
  - Added a span closing tag 

### Why did you make the changes (we will use this info to test)?
  - To resolve the linter error "Tag must be paired; missing </span>"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No visual changes

### CODE REVIEW

**Comment by kristinstockley** [comment]
Review ETA: By EOD 10/3
Availability: 10/2 and 10/3

**Comment by kezzaam** [comment]
Review ETA: By EOD 10/5
Availability: 10/3 and 10/5

**Review by kezzaam — APPROVED** [review]
Hi @romainyvernes! Great job on this issue. I can confirm you have handled the changes as specified and not broken or added anything. Awesome! Thanks for an easy review :)

**Review by jaasonw — APPROVED** [review]
Looks good 🚀

**Review by kristinstockley — APPROVED** [review]
Great job, @romainyvernes!

**Pull request merged**
