### PR TITLE
Add additional GitHub field and TWE to Project Profile Card Issue Template

### LINKED ISSUE #7363: Add additional GitHub field and TWE to Project Profile Card issue template
### Overview
In the "Project Profile Card review and update" issue template, we need to add options for Tech Work Experience and a field to submit additional GitHub repositories used by project volunteers. This will ensure issues can be submitted for the TWE project card and enable us to more accurately track a project's resources.

### Action Items
 - [x] Open `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml` in your IDE.
 - [x] In the `Project Name` dropdown section, add `- "Tech Work Experience"` to the options list after `- "Open Community Survey"`, making sure the indentation matches the other list items.
 - [x] In the 'Project Card URL' dropdown section, add `- "tech-work-experience.md"` to the options list after `- "tdm-calculator.md"`, making sure the indentation matches the other list items.
 
Under the `Update GitHub Link` field ending with the lines:
 ```
attributes:
  label: GitHub Link 
```
- [x] Add the following code:
```
  - type: dropdown
    id: additional-github-repos-yes-no
    attributes:
      label: "Do you have any additional (other than your primary) GitHub repositories that your volunteers make issues or PRs against?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: additional-github-repos
    attributes:
      label: "If yes, list the repo URLs here"
```
- [x] Make sure to verify the indentation of each line uses spaces, not tabs, and matches the indentation pattern of the other fields in the file.
- [x] Ensure you have Issues enabled in your fork of the website repo on GitHub, and test opening a new issue with the Project Profile Card template to ensure the additional GitHub field shows up correctly.
- [x] Have Bonnie (@ExperimentsInHonesty) test the template changes by using it to submit the following changes for Tech Work Experience:
    - add another repo to pull contributors from

### Resources/Instructions
- New issue template [Project Profile Card review and update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml
- This issue initiated by #6863

### PR DESCRIPTION
**Pull request by jazxbx**
fixes #7363 

### What changes did you make?

When creating an issue using the Project Profile Card review and update template:

-Project Name: Added the option "Tech Work Experience" to the Project Name dropdown

-Project Card URL: Included the "tech-work-experience.md" option in the Project Card URL dropdown.

-Update Github Link section: Added a dropdown menu asking “Do you have any additional (other than your primary) GitHub repositories that your volunteers make issues or PRs against?” with "YES" and "NO" options.
Included a textbox for entering additional repository URLs if the answer is "YES."

### Why did you make the changes (we will use this info to test)?
This will allow issues to be submitted for the TWE project card and help us better track a project's resources more accurately

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 No visual changes to the website

Changes to the template seen in my repo: 
https://github.com/jazxbx/website/blob/add-github-field-twe-project-card-7363/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml

### CODE REVIEW

**Review by codyyjxn — CHANGES_REQUESTED** [review]
Hi @jazxbx  thank you for taking on this issue. 
### Things that you did correctly: 
- The branch name is correct 
- The changes are good and the indentation is good as well
- The title and the descriptions is clear. 

### Things that need to be changed: 

- You need to add the labels that are on the original issue.

**Comment by jazxbx** [comment]
> Hi @jazxbx thank you for taking on this issue.
> 
> ### Things that you did correctly:
> * The branch name is correct
> * The changes are good and the indentation is good as well
> * The title and the descriptions is clear.
> 
> ### Things that need to be changed:
> * You need to add the labels that are on the original issue.

Thank you! Just added the missing labels.

**Comment by daras-cu** [comment]
@jazxbx the first line of your PR always needs to be in the format "Fixes #XXXX" for the original issue to be linked correctly. That is the reason the labels were not added to this PR and it is currently failing two of the automated checks. Replace that line and it should resolve the check issues.

**Comment by jazxbx** [comment]
> @jazxbx the first line of your PR always needs to be in the format "Fixes #XXXX" for the original issue to be linked correctly. That is the reason the labels were not added to this PR and it is currently failing two of the automated checks. Replace that line and it should resolve the check issues.

Ahh my bad! I thought by doing that, it would close the issue when merged and I didnt want that to happen since there were still some checks I didn't do.

**Comment by daras-cu** [comment]
@jazxbx I see, you actually should be able to complete the action items now in your own repo before the PR is merged. If you  switch your default branch to the one you made the changes on, the issue template should then reflect the changes. For reference: [Changing the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch). I apologize for not including that step in the initial issue instructions. Once the default branch is updated you can test the template yourself by opening an issue and then let Bonnie know so she can make sure it works as she intended.

I'm going to mark this PR as a draft so you can finish those last two items, then you can go ahead and remove the label.

**Comment by jazxbx** [comment]
> @jazxbx I see, you actually should be able to complete the action items now in your own repo before the PR is merged. If you switch your default branch to the one you made the changes on, the issue template should then reflect the changes. For reference: [Changing the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch). I apologize for not including that step in the initial issue instructions. Once the default branch is updated you can test the template yourself by opening an issue and then let Bonnie know so she can make sure it works as she intended.
> 
> I'm going to mark this PR as a draft so you can finish those last two items, then you can go ahead and remove the label.

Ohh will do this! Thank you!

**Comment by terrencejihoonjung** [comment]
availability: everyday, 5pm - 9pm PST
eta: today, 11:59pm PST

**Review by terrencejihoonjung — COMMENTED** [review]
(ignore this comment)

**Review by terrencejihoonjung — CHANGES_REQUESTED** [review]
Hi @jazxbx,

Here's what you did correctly:
- changes made and why they were made are clearly stated
- PR title is clear and concise
- branch naming is correct
- changes made to `project-profile-card-review-and-update.yml` are correct
- issue on your fork has been successfully created with GitHub fields showing correctly

Requested Changes:
- Seems like you just have the last check remaining (Bonnie testing), so once that is finished feel free to address this request thereafter! 

Thanks for your contribution!

**Comment by t-will-gillis** [comment]
Hi @codyyjxn @terrencejihoonjung @k-cardon Bonnie has [approved](https://github.com/hackforla/website/issues/7363) 

Please re review and let us know. Thanks!

**Review by terrencejihoonjung — APPROVED** [review]
Thanks for your contribution @jazxbx!

**Review by k-cardon — APPROVED** [review]
All these changes look correct, PR is clear, display on test is correct, and Bonnie said the functionality was also working properly. Thanks!

**Review by codyyjxn — APPROVED** [review]
Great Job! @jazxbx  Thank you for taking on this issue!

**Pull request merged**
