### PR TITLE
Refactor engage.md tools data from string to list

### LINKED ISSUE #4804: Refactor Tools data for engage.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Hotjar, Google Analytics
```
to
```
tools:
  - Hotjar
  - Google Analytics
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by a-t-klein**
Fixes #4804 

### What changes did you make?
  - Changed tools data in engage.md from string to list

### Why did you make the changes (we will use this info to test)?
  - There is a plan to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from tools to technologies, and vice versa
  - To complete issue #4804

### CODE REVIEW

**Comment by ldietz08** [comment]
Availability: Mon-Fri 4pm-7pm
ETA: 08/02 EOD

**Review by ldietz08 — APPROVED** [review]
The pull request was done in the correct branch and you linked to the issue. As requested, the tools data was refactored from a string to a list. Well done!

**Comment by kwangric** [comment]
ETA: EOD 8/4
Availability: Most days after 3pm PT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The requested changes were made to the code and everything still looks good in Docker. The pull request also contains a description of what changes were made and why. Well done!

**Review by adrianang — APPROVED** [review]
Hi @a-t-klein — the branching is set up correctly, the corresponding issue is linked, the requested change has been made exactly as asked (refactor Tools into a list for Engage), and the change didn't visually or functionally affect the Engage project views for its page and card layouts when testing your branch on my local environment through Docker. The What/Why sections in your PR were also well-written.

Thanks for taking up this issue! 🙌🏼

**Pull request merged**
