### PR TITLE
Update environmental-impact.yml

### LINKED ISSUE #2830: Edit content field and remove type field from environmental-impact.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/environmental-impact.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/environmental-impact.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/environmental-impact.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/environmental-impact.yml#L11

### PR DESCRIPTION
**Pull request by RobenusW**
Fixes #2830

### What changes did you make and why did you make them ?

  -Changed "content" to "content-type"
  -Removed "type: icon"
  -I did this because I followed what the issue said to change

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>
 

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Hi @RobenusW, please add the issue number this PR relates to in the description so that the bot can add appropriate labels and reviewers can view the issue.

**Comment by lilyarj** [comment]
@RobenusW please add the issue number at the top so we can review this pr :)

> Hi @RobenusW, please add the issue number this PR relates to in the description so that the bot can add appropriate labels and reviewers can view the issue.

**Comment by RobenusW** [comment]
> Hi @RobenusW, please add the issue number this PR relates to in the description so that the bot can add appropriate labels and reviewers can view the issue.

Sorry about that, I didn't read the instructions properly, I also just added the image after I realized I didn't follow the correct steps. Please tell me if there is anything getting in the way of merging.

**Comment by RobenusW** [comment]
> @RobenusW please add the issue number at the top so we can review this pr :)
> 
> > Hi @RobenusW, please add the issue number this PR relates to in the description so that the bot can add appropriate labels and reviewers can view the issue.


Sorry about that, I didn't read the instructions properly, I also just added the image after I realized I didn't follow the correct steps. Please tell me if there is anything getting in the way of merging.

**Comment by blulady** [comment]
The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)

**Comment by lilyarj** [comment]
@RobenusW Also just as a note please only screenshot changes if changed have been made to the website, so no pictures of code are needed

**Comment by RobenusW** [comment]
> The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)

I see. Should I create a new merge request using the correct branch or what should I do? Detailed instructions are much needed.

**Comment by RobenusW** [comment]
> The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)

Ok I realized I am a little confused. I thought a created a new branch for this issue

> The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)



> @RobenusW Also just as a note please only screenshot changes if changed have been made to the website, so no pictures of code are needed

Took them out, thanks for the feedback.

**Comment by blulady** [comment]
> > The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)
> 
> I see. Should I create a new merge request using the correct branch or what should I do? Detailed instructions are much needed.
@RobenusW 
Ok so we have 2 options. You can rename the branch in GitHub or you can rename the branch in your local repo [(online guide](https://careerkarma.com/blog/git-rename-branch/#:~:text=To%20rename%20a%20Git%20branch%2C%20run%20the%20following%20command%3A%20git,the%20branch%20you%20are%20viewing.)) To rename your branch locally you would 
 - get on the branch you are trying to rename (in this case hackforla-RobenusW-patch-1) 
 - then type git branch -m update-env-impact-yml-3362 
 - then you can push it up to git, start with git push, git will then provide the appropriate command for you to use
 - it will then give you an option of commands, use this one "git push origin HEAD"
 - this will create a new pr which I will then approve and merge
 or ([directions here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch))
 - go to the main page of the repo (the one that says website)
 - click on branches
 - then click on the pencil (on the right side)
 
Personally I would probably change it in github

**Comment by RobenusW** [comment]
> > > The changes look great but the branch name doesn't follow our typical scheme. You can read about standard scheme [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)
> > 
> > 
> > I see. Should I create a new merge request using the correct branch or what should I do? Detailed instructions are much needed.
> 
> Ok so we have 2 options. You can rename the branch in GitHub or you can rename the branch in your local repo [(online guide](https://careerkarma.com/blog/git-rename-branch/#:~:text=To%20rename%20a%20Git%20branch%2C%20run%20the%20following%20command%3A%20git,the%20branch%20you%20are%20viewing.)) To rename your branch locally you would
> 
> * get on the branch you are trying to rename (in this case hackforla-RobenusW-patch-1)
> * then type git branch -m update-env-impact-yml-3362
> * then you can push it up to git, start with git push, git will then provide the appropriate command for you to use
> * it will then give you an option of commands, use this one "git push origin HEAD"
> * this will create a new pr which I will then approve and merge
>   or ([directions here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch))
> * go to the main page of the repo (the one that says website)
> * click on branches
> * then click on the pencil (on the right side)
> 
> Personally I would probably change it in github

Thanks for your feedback and time. I came across a problem when I was following your steps, it says I can't rename my patch branch because only admins can rename protected branches. What should I do to solve that? Thanks for your detailed steps above.

**Comment by BeckettOBrien** [comment]
I think that error is happening because the branch you are renaming is on the official hackforla github and not your own fork. This can happen if you accidentally have the hackforla github set as the origin. Can you send the output of `git remote -v`?

**Comment by blulady** [comment]
> I think that error is happening because the branch you are renaming is on the official hackforla github and not your own fork. This can happen if you accidentally have the hackforla github set as the origin. Can you send the output of `git remote -v`?

@RobenusW This is probably the issue. If you can't get it working, let me know and we can do a screen share later.

**Comment by RobenusW** [comment]
> * update-env-impact-yml-3362

I see. Thanks for the feedback beyond your duty. I'm going to work through this as much as possible and will update you if I need additional help.

**Comment by blulady** [comment]
> > * update-env-impact-yml-3362
> 
> I see. Thanks for the feedback beyond your duty. I'm going to work through this as much as possible and will update you if I need additional help.

Totally, but if you spend more than 45 minutes on it, reach out.

**Comment by RobenusW** [comment]
> > > * update-env-impact-yml-3362
> > 
> > 
> > I see. Thanks for the feedback beyond your duty. I'm going to work through this as much as possible and will update you if I need additional help.
> 
> Totally, but if you spend more than 45 minutes on it, reach out.

Hey, I tried to fix this issue, but I kinda afraid I am going to mess some things up. Can we schedule a meeting to fix this? Thanks for your patience and help

**Comment by blulady** [comment]
> > > > * update-env-impact-yml-3362
> > > 
> > > 
> > > I see. Thanks for the feedback beyond your duty. I'm going to work through this as much as possible and will update you if I need additional help.
> > 
> > 
> > Totally, but if you spend more than 45 minutes on it, reach out.
> 
> Hey, I tried to fix this issue, but I kinda afraid I am going to mess some things up. Can we schedule a meeting to fix this? Thanks for your patience and help

Absolutely. I have obligations today. You are welcome to attend the Sunday meeting or we can set up a meeting after.

**Comment by RobenusW** [comment]
I am not able to come to most Sunday meetings, so I am free all week after 4:30, except Friday.

**Comment by blulady** [comment]
> I am not able to come to most Sunday meetings, so I am free all week after 4:30, except Friday.

Hey is that PST or.... 
I could do Monday at 4:30 PST. Let me know if that works for you.

**Comment by RobenusW** [comment]
Yes, 4:30 pst works, hope its not too late to respond. Tell me if you can't make it anymore.

**Comment by blulady** [comment]
It's good. Chat with you tomorrow at 4:30.

**Comment by blulady** [comment]
> Yes, 4:30 pst works, hope its not too late to respond. Tell me if you can't make it anymore.

I sent a zoom link to (what I think is) you on slack.

**Comment by blulady** [comment]
accidently made this pr from website repo

**Pull request closed without merging**
