### PR TITLE
Added github-handle for D.Nyasetia

### LINKED ISSUE #6702: Add github-handle for Debbie Nyasetia in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Debbie Nyasetia
```
with
```
- name: Debbie Nyasetia
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by del9ra**
Fixes #6702

### What changes did you make?
  - Added "github-handle:" under "- name: Debbie Nyasetia"

### Why did you make the changes (we will use this info to test)?
  - To replace two variables "github" and "picture" variables with one
  - To reduce redundancy
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by DrAcula27** [comment]
#### ETA for review:
March 2, 2024

#### Availability:
Weekdays 2pm - 5pm

**Comment by ramitaarora** [comment]
ETA: May 1
Availability: Weekdays 9am-12pm

**Review by taylorbeee — APPROVED** [review]
@del9ra - branch looks good, issue is linked correctly and spaces were used rather than tabs. Great work.

Approved!

**Review by ramitaarora — APPROVED** [review]
This looks good!
- PR was made from your fork
- Issue was linked correctly
- Changes were made correctly

Thank you! Approved. :)

**Review by DrAcula27 — APPROVED** [review]
@del9ra 
Great work on your good first issue!
- PR was initiated from the correct branch
- It fixes the linked issue
- No extra changes were made
- You used spaces instead of tabs to indent

Approved 😄

**Pull request merged**
