### PR TITLE
Added Rhoda Michael's profile to guides team

### LINKED ISSUE #5623: Update Project Profile: Guides Team (Add Rhoda Michael)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

#### Developer
- [ ] In your IDE, open the `_projects/guides-team.md` file
- [ ] Observe the existing syntax of the front matter block [^1] in the file
- [ ] Find the `leadership` variable and make the following change:
  - [ ] Add the following as a new entry
    ```
      - name: Rhoda Michael
        github-handle: the-techgurl
        role: UX Research Lead
        links:
          slack: 'https://hackforla.slack.com/team/U05JS9NLNQJ'
          github: 'https://github.com/the-techgurl'
        picture: https://avatars.githubusercontent.com/the-techgurl
    ```
- [ ] Verify the changes by viewing the Guides Team page [^2] in your local environment and include before and after screenshots with your pull request
- [ ] Once your pull request is merged, go to #5407 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5407 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5407
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by sakibian**
Fixes #5623 

### What changes did you make?
  - Added Rhoda Michael's profile on the guides team board

### Why did you make the changes (we will use this info to test)?
  - Information was not there, added a new name to the board

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @sakibian I was reading through the comments on your previous PR, and notice that this still has a merge conflict. The confusion is happening because three PRs are updating the same file at the same time. The two before yours are: #5672 fixes #5624 adds "Sarah Levine", so their name should stay. #5671 fixes #5584 removes "Shawn Wong", so this person's name should be removed.

To fix this:
- First, as you note- please close your previous PR #5692
- Next, to resolve the conflict scroll down this page and select "Resolve conflicts"
- On the next page, you want to keep the profile you added: "Rhoda Michael", and delete the profile that has already been deleted from the Hack for LA website: "Shawn Wong".
  - Edit this page by deleting lines 42-43 first, then delete lines 29-35. The remaining info is six lines for "Rhoda Michael".
  - "Sarah Levine"s info is on lines 23-28. This does not change.
- When done, scroll up and select "Mark as resolved". This should clear up the conflict.

**Comment by sakibian** [comment]
@t-will-gillis Instruction followed according to your guide, thanks. Cheers.

**Comment by Thinking-Panda** [comment]
Availability: weekdays
Review ETA: EOD 10/18

**Review by Thinking-Panda — DISMISSED** [review]
@sakibian , Thank you for your patience in working wit this issue. The code changes show the expected results on my machine. Minor change: Could you please update the  visuals of the before and after change to reflect the current status.

**Comment by sakibian** [comment]
@Thinking-Panda I have updated them, before was not change in this situation  because it is from live server screenshot, I did update the after changes screenshot.

**Comment by KyleA99** [comment]
Availability: 10/18/23
Review ETA: EOD 10/18/23

**Comment by KyleA99** [comment]
Just looked over PR, the webpage does appear as desired.  However, I believe your code is missing the github-handle from the issue action items (see below).  Add that last info in and I think this PR can be merged

  - name: Rhoda Michael
    github-handle: the-techgurl
    role: UX Research Lead
    links:
      slack: 'https://hackforla.slack.com/team/U05JS9NLNQJ'
      github: 'https://github.com/the-techgurl'
    picture: https://avatars.githubusercontent.com/the-techgurl

**Review by KyleA99 — CHANGES_REQUESTED** [review]
Missing github info for Rhoda Michael.  Check issue action item

**Comment by sakibian** [comment]
> Missing github info for Rhoda Michael. Check issue action item

@KyleA99 updated missing phrase.

**Comment by KyleA99** [comment]
Availability: 10/22/23
Review ETA: EOD 10/22/23

**Review by KyleA99 — CHANGES_REQUESTED** [review]
@sakibian I believe Sarah Levine's info was omitted (possibly due to merge conflict again?), but I do see the github-handle correctly added for Rhoda. I think it will be approved once Sarah's info is added back in.

**Comment by roslynwythe** [comment]
@sakibian I believe @KyleA99 is correct and you may have removed Sarah Levine's information while resolving the merge conflict. 
 You have several choices: (1) You can add back Sarah Levine's information.  You can find that information in #5624 or from the diff in files changed.  (2) You can close this Pull Request and start over again.   If you do start over please start with an updated gh-pages branch and create an issue branch with a name that is distinct from the original one.  Feel free to contact me on Slack for assistance.  
 
 Thank you @KyleA99 and @Thinking-Panda for your careful reviews.

**Review by roslynwythe — DISMISSED** [review]
@sakibian I believe @KyleA99 is correct and you may have removed Sarah Levine's information while resolving the merge conflict. 
 You have several choices: (1) You can add back Sarah Levine's information.  You can find that information in #5624 or from the diff in files changed.  (2) You can close this Pull Request and start over again.   If you do start over please start with an updated gh-pages branch and create an issue branch with a name that is distinct from the original one.  Feel free to contact me on Slack for assistance.  
 
 Thank you @KyleA99 and @Thinking-Panda for your careful reviews.

**Comment by sakibian** [comment]
@roslynwythe, @KyleA99 @Thinking-Panda added back to Sarah Levine's information.

**Review by KyleA99 — CHANGES_REQUESTED** [review]
Missing Shawn Wong's info

**Comment by t-will-gillis** [comment]
@sakibian @KyleA99 

Shawn Wong's info should not be added back in- Shawn's info was removed by #5671 fixes #5584

**Comment by KyleA99** [comment]
@t-will-gillis thank you.  In that case, this PR is approved from what I saw.  Thank you for the hard work and excellent communication on this @sakibian

**Review by KyleA99 — APPROVED** [review]
Approved, please ignore review-request I submitted earlier today.  Looks great, thank you @sakibian

**Review by t-will-gillis — APPROVED** [review]
Hey @sakibian - Great job! Thank you for working with everyone to address the merge conflicts- and thank you for your persistence!

**Pull request merged**
