### PR TITLE
Replaced previous website.png with image in issue 1152

### LINKED ISSUE #1152: Increase resolution and ratio of image on project page for Hackforla.org Website
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels. 

Current Resolution: 411 x 325 pixels
Current Ratio: 2.5:2

### Action Items

UX/UI
- [x] Increase ratio of project image for Hackforla.org Website to 3:2
- [x] Increase resolution of project image for Hackforla.org to 600 x 400 pixels 

Front-End development
- [x] Add the new resized image (scroll to bottom of this issue) to the HackforLA.org Website project card on the homepage
- [x] Update Status on #1105 
- [x] release dependency on #1219 and put the image in that issue.

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)

### PR DESCRIPTION
**Pull request by RobertaFricker**
Fixes #1152 
Replaced website.png image on hackforla website project card with image provided in issue #1152

### CODE REVIEW

**Review by averdin2 — APPROVED** [review]
Everything looks good!

**Review by GLRJr — COMMENTED** [review]
Nice, I like this image way better

**Comment by erikaBell** [comment]
@GLRJr just a future heads up (-:, as I know "how to review" isn't that clear when you're just starting. 

When reviewing, in order to either: approve, request changes, or just make a comment on the pull request, click on the `Files Changed` tab at the top of the pull request — see image below. 
<details>
<summary>Files Changed Tab</summary>

Screen Shot 2021-04-14 at 2 41 57 PM
</details>

Clicking `Files Changed` allows you to click the `Review Changes` dropdown button on the far right side. This is where you'll find the options to: `Approve, Comment, Request Changes`

This then indicates to everyone that you have reviewed it, and what your thoughts are on it. Just making this point because I only noticed you reviewed it due to coming in to check on the pull request and finding you had left a comment.

Lmk if that needs any more clarification. 

~ ~ <3

**Comment by GLRJr** [comment]
ok cool, I did that because I wasn't sure what I was allowed to do lol I
know someone else in charge of merging so I didn't want to step on any toes
lol Thank you for the feedback.

**Comment by erikaBell** [comment]
@GLRJr oh yeah that makes total sense lol. The Merge button is separate, so choosing "review changes" is all good.

**Pull request merged**
