### PR TITLE
Added GitHub handle option for Eva Kwock in design-systems.md

### LINKED ISSUE #6706: Add github-handle for Eva Kwock in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Eva Kwock
```
with
```
- name: Eva Kwock
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by taylorbeee**
Fixes #6706

### What changes did you make?

  - Added empty github-handle variable under Eva Kwock's name variable.

### Why did you make the changes (we will use this info to test)?

  - Eventually the added github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

 - Added an empty variable. No visual changes to the website.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @jenjenkayi, @patelbansi3009, @taylorbeee, @nssensalo, @ShamaaTabassum as a reminder, while you are waiting for your PRs to be reviewed, please consider reviewing each other’s `good first issue` PRs and any other PRs you feel comfortable with. Instructions are here for [How to Review Pull Requests]( https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) . You should aim to review two PRs for every PR you submit, and each PR ideally should have two or more reviewers. Thanks!
#6746, #6767, #6768, #6770, #6772

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hey @taylorbeee

In the first line of your PR, there are two spaces instead of one between 'fixes' and '#6706', and it seems like that confuses the github action that adds labels to pull requests. Make sure to keep an eye on the checks when making a PR, if some of them fail there might be an issue with the way the PR was formatted. 

Everything else looks good:
- md file is edited correctly 
- Branch is descriptive 
- PR other than the typo in the first line is well-written
- There are no visual changes to the website  

Just quickly fix that first line in the PR and I'll approve.

**Comment by taylorbeee** [comment]
@ajb176 I fixed the typo in the PR. Good eye, and thanks for pointing that out!

**Comment by del9ra** [comment]
Review ETA: EST 11 PM 5/1/24
Availability: 5-8 PM Thursday

**Review by ajb176 — APPROVED** [review]
Looks good to me, nice work.

**Review by LRenDO — APPROVED** [review]
Hi @taylorbeee !
Great job with this pull request!

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site. 
- Note was left that there were no visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

Again, nice work and thanks for taking the time to contribute to the website!

**Review by del9ra — COMMENTED** [review]
Hey @taylorbeee,
1. The PR is done with the correct branch
2. The issue is properly linked
3. Changes were summarized and implemented correctly
4. No visual changes were made to the website
Great job! Thanks for your contribution!

**Pull request merged**
