### PR TITLE
Update Project Profile: Expunge Assist (Add Mireya V. Aviles)

### LINKED ISSUE #5919: Update Project Profile: Expunge Assist (Add Mireya V. Aviles)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Mireya V. Aviles
    github-handle: vanessaavviles
    role: Product Manager, Design
    links:
      slack: https://hackforla.slack.com/team/U0429M52LTY
      github: https://github.com/vanessaavviles
    picture: https://avatars.githubusercontent.com/vanessaavviles
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by talking directly with the stakeholder
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by jphamtv**
Fixes #5919

### What changes did you make?
  - Added Mireya V. Aviles' information to the `leadership` variable in the `_projects/expunge-assist.md` file.

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-20 at 21 53 24

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2023-11-20 at 21 57 33

</details>

### CODE REVIEW

**Comment by JanineSooThow** [comment]
Availability: Tuesday 21st November - Wednesdsay 22nd November NZ Time
ETA: Wednesday 22nd November

**Comment by JanineSooThow** [comment]
Hello @jphamtv thank you for taking up this issue. 
- The PR matches the correct branch
- Mireya V. Aviles' information has been correctly added in the _projects/expunge-assist.md file. Code appears clean
- Changes with Mireya V. Aviles' information have successfully shown up on the H4LA website 
- Links work well
Well done! It all looks good to me! I will approve this PR.

**Review by JanineSooThow — APPROVED** [review]

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 22nd November

**Review by freaky4wrld — APPROVED** [review]
Hey there @jphamtv the changes required are done rightly, the to/from branch looks good, the linked issue is also correctly mentioned. The added profile is also visually added in the local environment.
Great work there.......

**Pull request merged**
