### PR TITLE
Added a new Project Profile to  the Expunge Assist team 

### LINKED ISSUE #5759: Update Project Profile: Expunge Assist (Add Curtis Barber)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Curtis Barber
    github-handle: CBx3000
    role: Product Manager, Content
    links:
      slack: https://hackforla.slack.com/team/U05RZAETCQ4
      github: https://github.com/CBx3000
    picture: https://avatars.githubusercontent.com/CBx3000
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by Chrisklangley**
Fixes #5759  

### What changes did you make?
  -  In  the _projects/expunge-assist.md file from line 41-47 I added a new profile to the leadership Variable 

### Why did you make the changes (we will use this info to test)?
  -  Expunge Assist needed an update to their project team on the Hack For LA website  
  
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-10-27 at 1 25 19 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-10-27 at 1 37 18 PM

</details>

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: EOD 10/28/23
Availability: 12-8 PM 10/23/23

**Comment by kezzaam** [comment]
Review ETA: EOD 10/28/23
Availability: 27th and 28th October 7-9pm

**Review by kezzaam — APPROVED** [review]
Hi @Chrisklangley! 
Nice work on this issue! I can see that it has been handled as expected and everything looks as it should without breaking anything.

**Review by KyleA99 — APPROVED** [review]
PR approved.  Code and visuals look great.  Nice work @Chrisklangley

**Review by t-will-gillis — APPROVED** [review]
Hey @Chrisklangley Great job!

- Your branches from/to look good,
- you are linked back to the original issue,
- you are giving a concise description of what you did and why,
- you are providing relevant before and after screenshots,
- your code changes only what needs to be changed, and
- the new profile appears when opened in Docker with no unexpected changes.

Thanks for your work!

**Pull request merged**
