### PR TITLE
Changed alt value for HFLA website image

### LINKED ISSUE #4036: Hackforla.org Website: Update alt text for the Hackforla.org Website image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Hackforla.org Website image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/website.md`:

**From:**
```
alt: 'Wireframe sample from new website.'
```
**To:**
```
alt: 'Hackforla.org Website'
```
**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Hackforla.org Website Page: https://www.hackforla.org/projects/website

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/website.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by vraer**
Fixes #4036 

### What changes did you make and why did you make them ?

- Changed the alt value within `_projects/website.md` from `alt: 'Wireframe sample from new website.'` to `alt: 'Hackforla.org Website'` 
- Update adheres to the Web Content Accessibility Guidelines (WCAG) and furthers HFLA's mission of inclusivity 
- Issue is part of epic https://github.com/hackforla/website/issues/3866

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by d-perez-8** [comment]
Availability: 4-6 pm on weekdays
ETA: 1 hour

**Review by d-perez-8 — CHANGES_REQUESTED** [review]
Hi @vraer, thank you for working on this issue! The code meets the requirements of the issue, and the branches are correctly labeled. 

One this to change is to keep the pull request format by leaving the bullet points on what you have changed. Also, include why you have made those changes. I know it's a much more minor issue, but it helps create good habits for documenting your changes.

Keep up the great work!

**Comment by vraer** [comment]
Hey @d-perez-8 thanks for reviewing. I updated the pull request format to include bullet points summarizing what the changes were and why they were made.

**Review by d-perez-8 — APPROVED** [review]
Great, looks good!

**Comment by RyanGehris** [comment]
Availability: 6-8pm
ETA: EOD 03/08/2023

**Review by RyanGehris — APPROVED** [review]
Great job working on this issue! It was also awesome the way you took feedback and made appropriate changes. Thank you.

**Pull request merged**
