### PR TITLE
Added github-handle for Amanda Glover on VRMS Project Page

### LINKED ISSUE #7355: Add github-handle for Amanda Glover in vrms.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/vrms.md` in the IDE
- [x] Replace:
```
- name: Amanda Glover
```
with
```
- name: Amanda Glover
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md?plain=1
Project Webpage: https://www.hackforla.org/projects/vrms

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by floydferrer**
Fixes #7355 

### What changes did you make?
  
  - Added github-handle for Amanda Glover within leadership variable on VRMS Project Page

### Why did you make the changes (we will use this info to test)?
  
  - github-handle will eventually replace the github and picture variables, reducing the redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

- No visual changes to the website

### CODE REVIEW

**Comment by codyyjxn** [comment]
Availability: M>F 
ETA: EOD

**Review by codyyjxn — APPROVED** [review]
@floydferrer Good Job on your first good issue.
- The branch name is correct with the issue as well. 
- The issue is linked correctly 
- The title is clear and concise. 


Thank you for your contribution !

**Comment by patelbansi3009** [comment]
Availability: Monday - Friday (9 am - 6 pm)(EST)
ETA: EOD

**Review by patelbansi3009 — APPROVED** [review]
Great Job @floydferrer !

- Used the correct branch for the pull request
- Linked the issue correctly
- Made the changes as requested in the issue
- Made no visual changes on the website
- Spaces were used instead of tabs

Keep up the good work! Thank you for your contribution. 👍

**Pull request merged**
