### PR TITLE
Updated Home Unit Us project leadership profiles

### LINKED ISSUE #3773: Update Project Profile: Home Unite Us
### Overview
As a developer, we must ensure our project's details are up to date on the HackforLA website. We need to update the [Home Unite Us](https://www.hackforla.org/projects/home-unite-us) page's leadership.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md) and find the `leadership` variable. 
- [x] Remove the following persons from the `leadership` variable
    - [x] Tracy Michelle
    - [x] Regan Hutson
    - [x] Kristy Points
    - [x] Ben Ross
- [x] Add the following persons `name`, `role`, `links`, and `picture` to the `leadership` variable
    - [x] Name: Jed Stewart
GitHub Handle: jed-stewart
Role: Developer
Slack Member ID: U04A3J6V0HY
    - [x] Name: Mira Kinebuchi
GitHub Handle: mira-kine
Role: Developer
Slack Member ID: U0411CAL13N
    - [x] Name: Stephen Barkley-Yeung
GitHub Handle: stevbark
Role: Developer
Slack Member ID: U041403GHEC
    - [x] Name: Kristelle Gumaru
GitHub Handle: K-Gumarama
Role: Product Manager
Slack Member ID: U031VJ99ATU
    - [x] Name: Sanya Nijhawan
GitHub Handle: sanya301
Role: Product Manager
Slack Member ID: U031FLYS561
    - [x] Name: Raji Pradheap
GitHub Handle: rpradheap
Role: Product Manager
Slack Member ID: U02R9MKA6KH
    - [x] Name: Bryce Lednar
GitHub Handle: brycelednar
Role: Product Manager
Slack Member ID: U049TSDG2SX
    - [x] Name: Farah Khan
GitHub Handle: fourmatte
Role: UX/UI Designer
Slack Member ID: U01JC8VEKMH
    - [x] Name: Eduardo De La Rosa
GitHub Handle: edela0015
Role: UX/UI Designer
Slack Member ID: U0430G2T4AC
    - [x] Name: Flora Osmond
GitHub Handle: itzflowa
Role: UX/UI Designer
Slack Member ID: U047ZT4GP5E

- [x] Test the Home Unite Us Project Page at [http://localhost:4000/projects/home-unite-us](http://localhost:4000/projects/home-unite-us) on your local development environment to ensure the changes are being properly displayed

### Instructions
- Be sure to use valid YAML syntax and match the existing structure of [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/
- For the github link, append the team member's github handle to https://github.com/
- For the picture URL, append the team member's github handle to https://avatars.githubusercontent.com/

### Resources
- [Home Unite Us project page](https://www.hackforla.org/projects/home-unite-us)
- [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by Satenik-Ba**
Fixes #3773

### What changes did you make and why did you make them ?

  - Updated Home Unite Us (https://www.hackforla.org/projects/home-unite-us) page's leadership team info.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-01-11 at 2 43 48 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-01-16 at 11 03 01 AM
</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Review availability: Weekdays 10-12pm
ETA: 01/16 5pm

**Comment by Adastros** [comment]
Availability (PST): 4 - 6PM 14JAN23
ECD: 6PM 14JAN23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @Satenik-Ba, good job on updating the team members for the Home Unite Us project! 

I noticed a couple of things that need to be updated:

- the roles for Kristelle, Sanya, Raji, and Bryce state "Manager" instead of "Product Manager" as stated in the issue.  
- it's very minor, but could you update the pull request title to change "Unit" to "Unite"? The commit message has the same spelling error but it's fine as is. You can look into and try to fix it using something like `git commit --amend -m` but that may cause more issues than it's worth.

**Comment by Satenik-Ba** [comment]
> 
Hi @Adastros! thank you for the reviewing the pull request. Just fixed the issue. Was unable to fix the spelling error in the pull request title. 
Thank you

**Comment by Adastros** [comment]
Hi @Satenik-Ba, thanks for updating the roles! 

The last thing that needs to be updated is the image under the "visual after changes are applied" `details` element on the pull request comment. It currently shows the old role descriptions on the webpage.

**Comment by Satenik-Ba** [comment]
Hi @Adastros, Updated the details for visual changes. Thank you!

**Review by Jaretzbalba — APPROVED** [review]
@Satenik-Ba I see that you've made all of the necessary changes requested by @Adastros and everything looks good on my end too. Good job working on this issue!

**Review by Adastros — APPROVED** [review]
Everything looks good on my end! Thanks for implementing the updates @Satenik-Ba.

**Pull request merged**
