### PR TITLE
update to pr-template example in 3.1b of CONTRIBUTING.md

### LINKED ISSUE #4870: Update CONTRIBUTING.md to reflect updated Pull Request Template
### Overview
We need to update CONTRIBUTING.md to reflect the changes in the Pull Request template.  

### Action Items
- [x] Navigate to CONTRIBUTING.md
- [x] Edit section 3.1.b to reflect the changes in the [Pull Request template](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)
- [x] Check your changes in your remote repository

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Pull Request template](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)

### PR DESCRIPTION
**Pull request by whitneywind**
Fixes #4870 

### What changes did you make?
  - split the pr template question into two questions
  -  added three dashes underneath each of them
  -

### Why did you make the changes (we will use this info to test)?
  - updated so that the example in CONTRIBUTING.md 3.1b matches the new Pull Request Template
  -
  -

### CODE REVIEW

**Comment by LOSjr4** [comment]
Availability: M-W 10AM-12PM
ETA: 7/11 12PM (edit: delaying to see response to adrianang question)

**Comment by adrianang** [comment]
- Availability: MTThFSS, 6 PM - 10 PM (PST) (Week of 7/10)
- ETA: I plan on finishing this PR review by Tuesday, 7/11 at 10 PM.

**Comment by adrianang** [comment]
@roslynwythe Hi Roslyn -- in reviewing this PR, I noticed that merging the change that @whitneywind made would create an ER that would cause the example in 3.1b(iii) of `CONTRIBUTING.md` to be outdated. The selected example would follow the old PR template and could create some confusion for new volunteers.

Did you intend #4870 to only update the markdown template example in 3.1b (old lines 821-825), or should 3.1b(iii) be updated to reflect the updated PR template as well? I would either approve or request changes depending on what you had intended the linked issue to encompass.

**Comment by blulady** [comment]
@LOSjr4 When you get a chance, can you update your eta/aval?

**Review by LOSjr4 — APPROVED** [review]
As far as the PR markdown template being updated on CONTRIBUTING.md to the new format, that is done correctly. I see the changes on Whitney's branch and it matches what was provided on the issue. So I approve.
I was curious to see a response to Adrian's question, but I will be unavailable for a week starting tomorrow.

**Review by t-will-gillis — APPROVED** [review]
Hey @whitneywind - great job!  Your branches look great, your description is accurate, and you have changed what was required of the issue without additions. I was able to preview the changes in Visual Studio and it looks great.

@adrianang has a great point about changing additional areas in `CONTRIBUTING.md`. This was not part of the original scope, so I feel this PR should be approved as is since you satisfied the original requirements. I created a new issue #4961 to continue with the changes. Adrian and Whitney please feel free to review and comment on this issue.

Thanks so much for your work!

**Review by adrianang — APPROVED** [review]
This looks good to me! The branching is set up correctly, the corresponding issue is linked, and the requested edits to the Markdown file have been made. The template example looks exactly how I expect it to when I view it on Github.

Thank you @whitneywind for taking up this issue and @t-will-gillis for making that follow-up issue!

**Pull request merged**
