### PR TITLE
Img tag refactored 

### LINKED ISSUE #5185: img Tag Refactor: _includes/events-page/left-col-content.html - event links
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/left-col-content.html `
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-1" src="{{event.link}}" alt="" />
```
to
```
<img class="step-img-1" src="{{event.link}}" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/left-col-content.html
2. Webpage(s): https://www.hackforla.org/events
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by GRK1998**
Fixes #5185

### What changes did you make?
  - Changed an img HTML tag ending with a slash () to img tag without an ending slash ()

### Why did you make the changes (we will use this info to test)?
  - To make the code base consistent

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No visual changes

### CODE REVIEW

**Review by roslynwythe — DISMISSED** [review]
Good job @GRK1998 on this good first issue.  You made the correct code change and created a well-formed pull request.  The code change checks out fine in the browser.  I just have a tiny request: please remove the broken images from the PR, by deleting the `<details>` and `<summary>` tags as well as the closing tags and everything in-between.  Thanks

**Comment by LRenDO** [comment]
Hi @agutiernc and @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.  Thanks!

**Comment by agutiernc** [comment]
Availability and ETA to do pull request review:
Availability: Today
ETA: End of day

**Review by agutiernc — APPROVED** [review]
Awesome job @GRK1998! I verified that  the ending slash in the img HTML tag was removed. The page remains the same in different views too. Committed to the correct branch and pull request done well.

**Comment by mademarc** [comment]
Review ETA: 8/24/2023
Availability: 7:11PM

**Review by mademarc — APPROVED** [review]
Hey @GRK1998 the changes on the img tag was done very well and @LRenDO  the  ETA and Availability is done.

**Review by adrianang — APPROVED** [review]
Hi @GRK1998 — the branching is set up correctly, the corresponding issue is linked, the requested change of removing the ending slash on line 9 was made exactly as asked, and making the change didn't seem to affect the left column of the Events page at all when I tested this branch on my local environment.

The PR states the What and Why for the change, and I appreciate you taking the time to edit the Screenshots section based on reviewer feedback. I think that edit made your PR a bit easier to read; good job!

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
