### PR TITLE
Updated existing profile of Sanya Nijhawan in Home Unite Us Leadership Section

### LINKED ISSUE #7489: Update Project Profile: Home Unite Us Add Sanya Nijhawan
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/home-unite-us.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Sanya Nijhawan
    github-handle: sanya301
    role: Advisory
    links:
      slack: https://hackforla.slack.com/team/U031FLYS561
      github: https://github.com/sanya301
    picture: https://avatars.githubusercontent.com/sanya301
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Home Unite Us page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/home-unite-us
[^3]: initiating ER:  #7362

### PR DESCRIPTION
**Pull request by srinipandiyan**
Fixes #7489

### What changes did you make?
  
  - Task was to add profile card of Sanya Nijhawan's data to Home Unite Us Leadership Section; however, a profile card with outdated data was already present in the`home-unite-us.md` file.
  - I modified the existing profile card to reflect the updated contact info and leadership role as follows:
  ```
- name: Sanya Nijhawan
    github-handle: sanya301
    role: Advisory
    links:
      slack: https://hackforla.slack.com/team/U031FLYS561
      github: https://github.com/sanya301
    picture: https://avatars.githubusercontent.com/sanya301
```

### Why did you make the changes (we will use this info to test)?
  
  - These changes were made to provide end-clients with up-to-date information regarding our partnering organizations through the Hack For LA website.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before screenshot of Home Unite Us page with updated profile card of Santa Nijhawan

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After screenshot of Home Unite Us page with updated profile card of Santa Nijhawan

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
**Review ETA**: 10/23/24 Wednesday
**Availability**: 6-10 PM Weekdays (EDT)

**Comment by floydferrer** [comment]
Review ETA: 10/23/24 Thursday
Availability: 4-10 PM Weekdays (PST)

**Review by siyunfeng — APPROVED** [review]
Great job on your second good first issue, @srinipandiyan ! You have been improving your skills and following the guidelines. 

- Availability and ETA are included in the original issue
- PR is done with the correct branch
- The linked issue is included and accurate
- Changes are correct
- Before-and-after screenshots are provided and you put extra effort into highlighting the difference

Improvement: 
- Name the branch with more specific details, such as `update-sanya-nijhawan-profile-home-unite-us-7489`

Thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
@srinipandiyan Great Job on this issue. 
- The title is good and the description as well. 
-  Ran the code on my end and it seems to display the correct changes needed for this page. 

Only thing needs to be removed from your pr is `…ip section.` this is right on top of the `fixes` maybe just a type-o. Please remove this and the pr will be done.

Keep it up! Thank you for your contribution.

**Comment by floydferrer** [comment]
Great job on your second good first issue, @srinipandiyan !

- PR is done with the correct branch
- The linked issue is included and accurate
- Changes are correct
- Before-and-after screenshots are clear of the requested changes
- As @codyyjxn mentioned, need to remove "…ip section" from the top of your PR above "Fixes..."

Thanks for your contribution!

**Review by floydferrer — APPROVED** [review]

**Pull request merged**
