### PR TITLE
remove-languages-2487

### LINKED ISSUE #2487: Remove languages from the technologies field for each project
### Overview
We need to remove the languages from the technologies field for each project so we can properly implement languages as its own filter field.

### Action Items
- [x] Go through each .md file under the [_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects) directory and remove any instances of a language under the 'technologies' property
    - [x] Click [this](https://www.hackforla.org/projects/?technologies=Python,SASS,SCSS,TypeScript) link for all the projects that currently have a language under the 'technologies' property
    - [x] Remove TypeScript, Python, SCSS, and SASS wherever possible
- [x] Ensure that both the [projects page](https://www.hackforla.org/projects/) and each individual project's landing page no longer has any of the mentioned languages under 'Technologies'
- [x] Ensure that the filter under the [projects page](https://www.hackforla.org/projects/) no longer lists any of the mentioned languages as a possible filter option
- [x] Once approved and merged, release dependency on #2488

### Resources/Instructions
[projects page](https://www.hackforla.org/projects/)
[_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects)
[Projects with languages](https://www.hackforla.org/projects/?technologies=Python,SASS,SCSS,TypeScript)

### PR DESCRIPTION
**Pull request by anthonysim**
Fixes #2487 

### What changes did you make and why did you make them ?

- went through each .md file under the _projects collection directory and remove any instances of a language under the 'technologies' property
 - Removed TypeScript, Python, SCSS, and SASS wherever possible
 - Ensured that both the projects page and each individual project's landing page no longer has any of the mentioned languages under 'Technologies'
 - Ensure that the filter under the projects page no longer lists any of the mentioned languages as a possible filter option

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
 

 

 
</details>

<details>
<summary>Visuals after changes are applied</summary>
   
   
   
   
</details>

</details>

### CODE REVIEW

**Review by lopezpedres — APPROVED** [review]
Great job @anthonysim! It all looks good.

**Comment by JessicaLucindaCheng** [comment]
@anthonysim Could you add your pull request to the Project Board? Thank you.

**Comment by anthonysim** [comment]
> @anthonysim Could you add your pull request to the Project Board? Thank you.

@JessicaLucindaCheng, sure I'll do that right now.

**Review by JessicaLucindaCheng — APPROVED** [review]
@anthonysim Changes look good to me! Fantastic job!

**Review by macho-catt — APPROVED** [review]
LGTM

**Pull request merged**
