### PR TITLE
Remove unused scripts.

### LINKED ISSUE #6200: removed unused file current-projects.js
### Overview
As developers we need to remove the unused file `assets/js/current-projects-check.js` in order to keep the codebase clear and avoid confusion.  

### Action Items
- [x] Open your IDE to `assets/js` and delete the file `current-projects-check.js`

### Resources/Instructions
- The need for the file https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js was obviated by #5978

### PR DESCRIPTION
**Pull request by JackCasica**
Fixes #6200

### What changes did you make?
- Deleted `current-projects-check.js` file from `assets/js`

### Why did you make the changes (we will use this info to test)?
- Removed this file as its scripts were obviated by a previous PR: #5978 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- Deleted unused script only. No visual changes to the website.

### CODE REVIEW

**Comment by tesiahwang** [comment]
Review ETA: 2/7/2024
Availability: flexible

**Review by tesiahwang — APPROVED** [review]
Great job, @JackCasica - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable! Just a couple of small things to note:
- Include the issue number in your branch name.
- When no visual changes are made, please explain e.g. "Deleted unused script only. No visual changes to the website."

**Review by freaky4wrld — APPROVED** [review]
Hi there , great work there all the work assigned to you in the issue is done correctly
- the to/from branch looks good
- the deletion specified is done correctly
- the issue linked is correct too
PR approved.......

**Comment by LRenDO** [comment]
Hi @JackCasica and @tesiahwang!

@tesiahwang, great non-functional requests! @JackCasica, I am going to go ahead and merge the code this time as it is correct and working, but if you could please update the original comment to include the reasoning why the screenshots were not included. In addition, please update the title to include the file names of the files that were removed. In the future, please do include the issue number in the branch name.

Please don't hesitate to reach out if you need any help or clarifications.

Great work and thank you for taking the time to contribute!

**Pull request merged**
