### PR TITLE
Update project information accessthedata 4211

### LINKED ISSUE #4211: Update Project Information: Access the Data
### Overview
The Access the Data page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Download a copy of the Access the Data [One Sheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/AtD-one-sheet.pdf) from the product management repo
  - [x] Replace the current Access the Data One Sheet in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs) 
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/access-the-data.md` file and find the `leadership` variable.
- [x] Remove Mariana Melo-Vega and their information
- [x] Verify the changes by viewing the [Access the Data project page](https://www.hackforla.org/projects/access-the-data) on your local environment and include a screenshot with your pull request
  - [x] Ensure that the "Overview" hyperlink links to the new One Sheet
- [x] Remove the following variables (and their text content) from the access-the-data.md file
  - [x]  `problem` 
  - [x] `solution`
  - [x]  `impact`

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by mjh-projects**
Fixes #4211
### What changes did you make and why did you make them ?

  -  Replaced Access-The-Data-OneSheet.pdf  with new sheet updated 1/27/2023
  - Removed Mariana Melo-Vega and their information  to keep access the data updated
  - Removed Problem/Solution/Impact variables to keep access the data updated

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot from 2023-03-29 01-36-27

Screenshot from 2023-03-29 01-38-02

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot from 2023-03-29 01-38-43

Screenshot from 2023-03-29 00-08-29

</details>

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: EOD 03/30
Availability: after 5pm, M-F

**Comment by RyanGehris** [comment]
ETA: EOD 03/29
Availability: M-Th 6pm-10pm

**Review by RyanGehris — APPROVED** [review]
Great work on this issue. You made the appropriate changes to the leadership variable and removed the problem, solution, and impact variables. I was able to view and confirm the changes on my local machine. Thank you for working on this issue, to help keep project information up to date!

**Review by arcan9 — APPROVED** [review]
Nice job @mjh-projects. PR is in the correct branch, issue is linked, and you documented the changes effectively. The docker version reflects the changes you made.

**Review by t-will-gillis — APPROVED** [review]
Hey @mjh-projects - Great job- branches are correct, changes were made as detailed in the referenced issue. I checked in Docker and see the revised One Sheet, the edits to the leadership, and the removal of the three variables. 

Thanks for your work!

**Pull request merged**
