### PR TITLE
 Add github-handle for Ebi Imafidon in tdm-calculator.md  7173

### LINKED ISSUE #7173: Add github-handle for Ebi Imafidon in tdm-calculator.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tdm-calculator.md` in the IDE
- [x] Replace:
```
- name: Ebi Imafidon
```
with
```
- name: Ebi Imafidon
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tdm-calculator

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by kgold2018**
Fixes #7173

### What changes did you make?
  - Add  github-handle for Ebi Imafidon
 
### Why did you make the changes (we will use this info to test)?
  - To hold the github handle for each member of the leadership team

### CODE REVIEW

**Comment by iancooperman** [comment]
Review ETA: EoD

**Review by iancooperman — CHANGES_REQUESTED** [review]
Changes look good, but please check off all the relevant action items on the original issue.

**Comment by kgold2018** [comment]
@iancooperman  I reviewed an original issue and addressed all relevant action items you requested. Thank you!

**Review by iancooperman — APPROVED** [review]
@kgold2018 Thank you.

**Comment by LRenDO** [comment]
Hi @ihop-56! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hey @kgold2018 - Everything looks good! 
- branches are correct
- pr is linked to orig issue
- description of what was changed and why is concise
- code changes are clean
Thanks for working on this!

**Review by ihop-56 — COMMENTED** [review]
Hi @kgold2018, I reviewed the changes, and everything looks great. The `github-handle` was correctly added for Ebi Imafidon as per the issue instructions. There are no visual changes to the website, and the code is clean and well-formatted. Nice job!

**Pull request merged**
