### PR TITLE
Removed alt-hero field from metro-ontime.md file

### LINKED ISSUE #3205: Remove unused `alt-hero` field from metro-ontime.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/metro-ontime.md`, remove line 8 for the alt-hero
```
alt-hero: 'Line graph of arrival times versus schedule for the Green Line train.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/metro-ontime.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/_projects/metro-ontime.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by patrickohh**
Fixes #3205 

### What changes did you make and why did you make them ?
  - Removed alt-hero field to reduce time to load for website
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to website.

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Unity7** [comment]
Availability: 2 Hours
ETA: EOD 10/25/22

**Comment by AzaniaBG** [comment]
@patrickohh ~ can you please add this issue to the project board? You can use the "Projects" section on the right pane of this issue to do so.

**Comment by patrickohh** [comment]
just added this issue to the project board!

**Comment by jyaymie** [comment]
Review ETA: 4:00pm 10/25/22
Availability: 1 hour

**Comment by jyaymie** [comment]
Hey @patrickohh! It looks like you linked the number of this PR. Could you instead link the number of the original issue?

**Comment by patrickohh** [comment]
whoops just fixed it!

**Review by jyaymie — APPROVED** [review]
Well done, @patrickohh! We've got a linked issue and correct implementation. Thanks for your quick responses in the Comments!

**Pull request merged**
