### PR TITLE
Update Project Profile: Remove Gayle Martin from HackforLA.org Website

### LINKED ISSUE #6981: Update Project Profile: remove Gayle Martin from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Gayle Martin
    github-handle: gaylem
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06HC3A0DM0'
      github: 'https://github.com/gaylem'
    picture: https://avatars.githubusercontent.com/gaylem
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by katiejnete**
Fixes #6981 

### What changes did you make?
  
  - Removed Gayle Martin lines from leadership variable in website markdown file (_projects/website.md)

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of current HfLA project team members on the website up-to-date

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Review by codyyjxn — DISMISSED** [review]
@katiejnete great job on this issue. 
- The branch name is correct with the issue number 
- The before and after screenshots are good as well. 
- Title and description is very clear and concise 


### Things you need to fix 
- You need to fix the merge conflict 

Thank you for taking on this issue.

**Review by FamousHero — DISMISSED** [review]
Hi @katiejnete, Thanks for taking on this issue!

Things you did well:
- branch name contains issue # 
- PR title and description sections are descriptive and succinct.
- Visual Changes are included
- Great job resolving the merge conflict!!!!

No changes needed, great job! Keep it up!

**Review by t-will-gillis — DISMISSED** [review]
Hi @katiejnete It looks like you previously resolved a merge conflict, and after you did that you re-requested a review from @codyyjxn - thanks! This is exactly the process to follow. 

- Unfortunately, there is an additional merge conflict that just popped up due to merging 7718. Please resolve this one as well.
- Also, please check the appropriate box under "CodeQL Alerts"
- Then re-request a review from me and I will merge this

**Review by santiseccovidal — APPROVED** [review]
Hi @katiejnete. Thanks for working on this. Branches, code changes and the what and why sections are correct. I couldn't observe the merge conflict that was commented before. It was probably fixed by your last changes removing Mario.
The changes look good in the local version of the website.
Well done!

**Review by t-will-gillis — APPROVED** [review]
Hey @katiejnete Thank you for taking care of the merge conflict- a second time- and thanks for working on this. Looks great! 

FYI For the "CodeQL Alerts", you can check the box that ends with "...and none were found." I changed it since you did not have one of those alerts. If you want to see what the CodeQL alert looks like, you can open the dropdown:

 "> Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown"

@FamousHero and @codyyjxn Since you previously Approved this PR, I will go ahead and merge it.

**Pull request merged**
