### PR TITLE
I edited the update comment github action

### LINKED ISSUE #1978: Github actions: edit update comment action
### Overview
As a Product Manager, I need the [Update Comment GitHub action ](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-comment-on-update-label.yml)to say "Please add update using this template" 

### Action Items
- [ ] Edit the automation such that it say "Please add update using this template"  instead of "Please add update"

### Resources/Instructions
Don't know how to do GitHub actions? Start [here](https://docs.github.com/en/actions)!

Other considerations: The current GitHub action uses ```peter-evans/create-or-update-comment@v1``` as a third-party action, which may or may not prove ideal. If you would like to make further edits to the GHA to remove the third-party action, you are more than welcome to as long as its final functionality remains the same.

### PR DESCRIPTION
**Pull request by JackRichman**
Fixes #1978

### What changes did you make and why did you make them ?

  -I changed the automation to say "Please add update using this template"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Aveline-art** [comment]
@JackRichman Please resolve the merge conflict so our team can review your pull request! Thank you!

**Comment by JackRichman** [comment]
I'm confused, what did I do wrong? It says I have conflicting files. @Aveline-art

**Comment by Aveline-art** [comment]
git checkout -b JackRichman-editupdatecommentJR gh-pages
git pull https://github.com/JackRichman/website.git editupdatecommentJR

**Comment by Aveline-art** [comment]
[This ](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts)should explain what is going on.

And [this ](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)should explain the steps you would need to take.

Feel free to post in the slack channel if you need more help! It's a common problem that the team deals with, especially since our team has gotten a lot more efficient.

**Comment by JackRichman** [comment]
I resolved the merge conflict

**Review by Aveline-art — APPROVED** [review]
Great work @JackRichman . Everything looks good!

**Review by Zak234 — COMMENTED** [review]
LGTM

**Pull request merged**
