### PR TITLE
removed unused alt-hero field

### LINKED ISSUE #2922: Remove unused `alt-hero` field from brigade-organizers-playbook.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/brigade-organizers-playbook.md`, remove line 8 for the alt-hero
```
alt-hero: ''
```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/brigade-organizers-playbook.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/brigade-organizers-playbook.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by Olanrewaju-Ak**
Fixes #2922

### What changes did you make and why did you make them ?

  -Removed line 8 for alt-hero

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Edited text fields. No visual changes to the website.

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA: End of Day on 5/30
Availability: 1 hour

**Comment by juliansmith0** [comment]
Availability for this week: 6 hours
My estimated ETA for completing this issue: Wednesday, June 1, 2022 EOD

**Comment by juliansmith0** [comment]
The pull request is done with the correct branch, the issue is linked properly, and all changes made are relevant to the original issue.

Excellent work! The only suggestion I have is to add a bit to the "What changes did you make and why did you make them?" section about why the change was made. As someone else once mentioned to me, it helps serve as another check on your process and reinforces documentation over time. I'm going to go ahead and approve however—just a good thing to keep in mind for the future!

**Review by juliansmith0 — APPROVED** [review]
The pull request is done with the correct branch, the issue is linked properly, and all changes made are relevant to the original issue.

Excellent work! The only suggestion I have is to add a bit to the "What changes did you make and why did you make them?" section about why the change was made. As someone else once mentioned to me, it helps serve as another check on your process and reinforces documentation over time. I'm going to go ahead and approve however—just a good thing to keep in mind for the future!

**Comment by trishajjohnson** [comment]
Availability: 1hr
ETA: EOD 6/2/22

**Review by trishajjohnson — APPROVED** [review]
Reviewed PR and see that its from/to the correct branches, there is an issue number provided that this PR fixes and, after looking at the file changes, I observe that the appropriate tasks had been accomplished.  You removed line 8 alt-hero: '' from file _projects/brigade-organizers-playbook.md and checked off box in original issue.  You also provided an explanation for no screenshots being provided.

I agree with @juliansmith0, for the future, I'd also recommend providing a little bit more of a description in your PR as to what you did and why.  Other than that, though, you've completed the issue and you should be good to go!

**Review by kathrynsilvaconway — APPROVED** [review]
@Olanrewaju-Ak Nice work on this issue. I see you have removed line 8 from the brigade-organizers-playbook.md file. Everything looks good.

**Pull request merged**
