### PR TITLE
Changed alt text for wins card images

### LINKED ISSUE #3402: Update alt text for Wins-Card Mobile image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-accomplishments.html`, change the following alt text

From
```
The wins card displays the contributer's name, their teams and roles, and testimonials of their accomplishments.
```

To
```
Wins card: contributors' names, teams and roles, and testimonials of their accomplishments.
```

- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/about-page/about-card-accomplishments.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/about-page/about-card-accomplishments.html#L29

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by kotynskm**
Fixes #3402

### What changes did you make and why did you make them ?

  - Updated alt text for wins card images for mobile and desktop images
  
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changed alt text for wins card images, no visual changes to the website.

### CODE REVIEW

**Comment by kotynskm** [comment]
Availability for this week: Weekdays flexible
ETA: 1/17 1122AM

**Comment by jyaymie** [comment]
Review ETA: 1/17/23 11:50am
Availability: 1/17/23 Flexible

**Review by jyaymie — APPROVED** [review]
You found both occurrences where the alt text needed to be updated, and you used a descriptive yet concise branch name. Great work, @kotynskm!

**Comment by vincentdang** [comment]
Hey I noticed you moved this issue from the prioritized backlog section into the new issue approval column. 
It should be moved into the in-progress column.

**Comment by kotynskm** [comment]
Hi Vincent

For some reason I could not find “in progress” as an option and then I
could not move it back out of new issue. Sorry about that I’m not sure why
I couldn’t find in progress I was following along the instructions but it
wasn’t an option.

**Comment by vincentdang** [comment]
> Hi Vincent For some reason I could not find “in progress” as an option and then I could not move it back out of new issue. Sorry about that I’m not sure why I couldn’t find in progress I was following along the instructions but it wasn’t an option.
> […](#)

Go to Projects tab above next to Actions and Wiki > Click Project (Classic) > Project Board > In Progress tab should be next to Prioritize Backlog

**Comment by vincentdang** [comment]
The alt text looks fine. It is 91 characters with space included.  However, if you want shorten it again for readers that might have trouble with reading to begin with that'd be cool.  Otherwise, I think it passes all the rules and guidelines that I've seen.

**Review by vincentdang — COMMENTED** [review]
It looks fine.  Just make sure it is in the right bin.

**Pull request merged**
