### PR TITLE
Remove Cathy Cai from leadership variable - Access The Data

### LINKED ISSUE #4605: Update Project Profile: Access the Data
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Access The Data project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/access-the-data.md` file and find the `leadership` variable.
- [x] Remove `Cathy Cai`'s `name`, `role`, `slack` link, `github` link, and `picture` from the `leadership` variable
- [x] Verify the changes by viewing the [Hackforla.org Access The Data project page](https://www.hackforla.org/projects/access-the-data) on your local environment and include a screenshot with your pull request

### Instructions
- Delete the lines of code containing the information for the old team member, `Cathy Cai`

### Resources
- [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by rdhmdhl**
Fixes #4605

### What changes did you make and why did you make them ?

- Removed Cathy Cai from the access-the-database.md file. Removed name, role, links and photo. 
- Change made to resolve issue #4605

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Avail: sunday, monday 6pm-11
ETA: sunday 11pm.

**Comment by matthewmpan** [comment]
Availability: M-F 12PM - 8PM
ETA: EOD 5/14/23

**Review by matthewmpan — APPROVED** [review]
@rdhmdhl - Your branch is set up correctly, the issue is linked, you checked off all of the action items, and your changes look good. Great work!

**Review by steven-positive-tran — APPROVED** [review]
Branches are correct, changes work on my machine both firefox and edge and the code changes seems in line with the issue.

**Pull request merged**
