### PR TITLE
changed complexity label  missing to prework

### LINKED ISSUE #5336: Adjust the labels on Pre-work Template - UX issue template
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide]

### Overview
We use various templates to help team members produce consistent results in an efficient manner. We need to edit the Pre-work--UX Issue Template so that team members start with the correct labels during issue-making.

### Action Items

- [x] Navigate to the .github/ISSUE_TEMPLATE/ folder and find the template for `pre-work-template--ux.md.`
- [x] Find the line:
```
labels: 'Complexity: Missing, Feature: Onboarding/Contributing.md, prework, role:
  user research, size: 1pt'
```
and replace with:
```
labels: ['Complexity: Prework, Feature: Onboarding/Contributing.md, prework, role: user research, size: 1pt']
```
- [x] Submit screenshots of the 'before' and 'after' of the template from your own repository. 

Note: if you have not done so already you will need to set up your repo with the correct labels. Do this before making the code changes:
  - [x] First, create a new branch on the desktop. This is where you will make your edits, and you will push changes from here to create the Pull Request. See the animation here.
  - [x] Next, from the desktop select "Issues" then "New Issue" on the right. Scroll down to find the "Pre-work Template - UX" template and then select "Get Started". 
  - [x] On the right side of the template there is a section called "Labels" with a gear icon. If you have not set up the Labels, you will not see any here yet. To set up the labels, click on the gear, then on "Edit Labels" at the bottom. 
  - [x] On the next window, click on "New Label". 
  - [x] Now, enter each of the labels above in the "Label name" box. Enter each separately, and exactly as written without quotes. The description and the color are not important. Then select "Create label". You should have six labels: Complexity: Missing, Complexity: Prework, Feature: Onboarding/Contributing.md, prework, role: user research, size: 1pt
  - [x] Now repeat the process of selecting "Issues", then "New Issues", then "Pre-work Template- UX" and "Get Started". If you entered the labels correctly, you should see the original labels including `Complexity: Missing` already applied. Take your 'before' screenshot, proceed with making the edits, and then take the 'after' screenshot including the `Complexity: Prework` label.
- [x] Now switch you default branch back to "gh-pages" (review the animation). Click on "website" next to your name in the upper left. A new, highlighted box will appear with the option to "Compare & pull request". Select this. 
- [x] Follow the `CONTRIBUTING.md` docs section to complete the PR.

### Resources/Instructions
[pre-work template--ux.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template---ux.md)
This issue was initiated by ER #5273

### PR DESCRIPTION
**Pull request by raviteja4117**
Fixes #5336 

### What changes did you make?
  - Made changes to the pre-work-UX template Complexity: Missing to Complexity: Prework
  
### Why did you make the changes (we will use this info to test)?
  - Edited the Pre-work--UX Issue Template so that team members start with the correct labels during issue-making.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

after

</details>

### CODE REVIEW

**Comment by romainyvernes** [comment]
Availability: M-F all day
ETA: 10/11 EOD

**Comment by ajb176** [comment]
ETA: 10/11 EOD
Availability: 6-7:30 mornings

**Review by ajb176 — APPROVED** [review]
- Branch is named descriptively and merges into gh-pages as required
- Change of labels section is implemented as requested in issue #5336 
- Edited .md file looks properly formatted and corresponds with 'after' screenshot

Looks good to me, nice work @raviteja4117!

**Review by romainyvernes — APPROVED** [review]
Hi @raviteja4117. It looks good to me!

The issue is properly referenced; the changes are limited to the scope of the issue and correctly fix it; and the PR merges the changes into the correct branch.

Good job!

**Pull request merged**
