### PR TITLE
Moved nginx from tools to technologies section

### LINKED ISSUE #5342: Move Nginx from Tools to Technologies in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For each Hack for LA project listed on our webpages, we need to ensure that the data entries for Tools, Technologies, etc. are appropriate for each category. On the Home Unit Us project page, there is an entry under Tools that should move to Technologies.

### Action Items

- [ ] Locate the Home Unite US markdown file in the website/_projects/ folder.
- [ ] Locate the section `tools: ...` 
- [ ] From `tools: ` select the following entry:
```
  - Nginx
```
- [ ] MOVE only this entry to `technologies: `
- [ ] Provide before and after screenshots of the relevant web pages showing that the change was made successfully with no unintended effects. Also, confirm that the side filter displays the correct information.

### Resources/Instructions
[home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
[Home Unite Us](https://www.hackforla.org/projects/home-unite-us) project page
[Hack for LA](https://www.hackforla.org/) homepage
[Projects](https://www.hackforla.org/projects/) page
This issue is initiated by ER #5192

### PR DESCRIPTION
**Pull request by sakibian**
Fixes #5342

### What changes did you make?
  - Word changes from one section to another section.

### Why did you make the changes (we will use this info to test)?
  - It's an issue which needed fixes
  - Appropriate section chosen

### Screenshots of Proposed Changes to the Website.

<details>
<summary>Before -[Project page](https://www.hackforla.org/projects/home-unite-us)</summary>

before_home_unite-us2

</details>

<details>
<summary>Before - [HackforLA Landing Page](https://www.hackforla.org/)</summary>
  
before_home_unite-us3_website

</details>

<details>
<summary>Before - [Projects](https://www.hackforla.org/projects/)</summary>
  
before_home_unite-us4_project

</details>

<details>
<summary>After - HackforLA Landing Page</summary>
  
after_home_unite-us3_website

</details>

<details>
<summary>After - Project page</summary>
  
after_home_unite-us2

</details>

<details>
<summary>After - Projects</summary>

after_home_unite-us4_project

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
Hi @sakibian, thanks for making the changes to the branches of your PR, I've reassigned the reviewers of your previous PR. When you get the chance, please close #5548 to avoid any confusion. Thanks!

**Comment by kwangric** [comment]
Also, it looks like the issue wasn't linked correctly. When putting in the issue number after `Fixes ` you only need to put in the issue number, adding a link will not trigger the automation. If you make the edit to the PR, it should automatically link the issue.

**Comment by klei0229** [comment]
Review ETA: 10 PM PST 9/19/23
Availability: 6-10 PM PST Weekdays

**Comment by klei0229** [comment]
Hi @sakibian @kwangric , I'm trying to pull in the code onto my local machine and I'm not getting the same results as in the pictures you posted. 

This is my first PR review so I tried to take some more time in making sure I did the steps to get code onto my local machine. Here are the steps I followed: 

1) On branch gh-pages, I pulled changes from upstream to make sure I have the latest version
2) Made a new branch and switched to it
3) Pulled in the changes from the remote repository
4) Accepted incoming changes during merge
```
   git pull upstream gh-pages
   git checkout -b sakibian-5342
   git pull https://github.com/sakibian/website.git move-ngnx-word-tools-to-technologies-5342
   docker-compose up
```
Navigating to [http://localhost:4000/projects/](http://localhost:4000/projects/) I do not see the project Home Unite Us or any of the projects after that on that page. Could this be due to the change in the formatting under tools in the file 'home-unite-us.md'? 

In particular there is a format difference between main branch line(134-143) vs incoming branch line 79
 
[Main Branch Code](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1)
[Incoming Branch Code](https://github.com/sakibian/website/blob/gh-pages/_projects/home-unite-us.md?plain=1)

**Comment by kezzaam** [comment]
Hi again @sakibian! I've just looked through the changes and I can see that you've done everything correctly, and only made the changes that were specified in the issue, so excellent job on that and also fixing up the branches from earlier. For some reason, I'm not seeing the Home Unite Us project coming up on either the home page or project page on my local repo. I have attached a screenshot of what I'm talking about. The individual project at http://localhost:4000/projects/home-unite-us is as expected.  I can see on the live site, there are 25 more projects after the ones I'm seeing on my local site:

Screenshot 2023-09-21 at 9 27 21 AM

I'm not sure why this is. I have checked my repo is synced with origin and checked on multiple browsers. 
Could you double check that you are seeing these missing projects on your local repo?
I don't want to approve something that might break the site.
I hope this makes sense!

**Review by kezzaam — DISMISSED** [review]
Hello @sakibian! Great job fixing up branches and making the changes on this issue! I can confirm that the changes are made with the correct branches and are as expected, and you've only changed what was specified. Thanks for your work!

**Comment by kezzaam** [comment]
Hi @klei0229, I just reviewed this PR and I had problems seeing the projects on the home page and projects page according to the pictures @sakibian included, too. I ended up deleting the branch I'd made and running git pull upstream gh-pages, then creating the branch to check again: 

git checkout -b sakibian-move-ngnx-word-tools-to-technologies-5342 gh-pages
git pull https://github.com/sakibian/website.git move-ngnx-word-tools-to-technologies-5342

I had to do the last command with a git pull --rebase, accepted current changes and everything was as expected.
I think my repo, although it was synced, was not fully up to date.
Sorry if this is different to what happened for you, I thought I would share what I did in case it helps. 
Happy coding!

**Comment by klei0229** [comment]
@kezzaam I took another look and tried to pull in the PR the way you did it via rebasing. If you choose accept 'current changes' instead of 'incoming changes' I'm noticing that we're reverting back to the old format for tools.  I'm noticing that this 
change in format was done in this previous [commit](https://github.com/hackforla/website/commit/9b68452619b29b121e0d0df0a17a637fe43ace6a) which addresses an issue  such that 'The new format is required for the filter menu on the projects-check to work properly' 

@sakibian when you first started working on the code did the code base look more like codeblock 1 or 2? If it looked like codeblock 1, I think that there might have been a chance that the updated code wasn't pulled in via ```git pull upstream gh-pages```

codeblock 1: current changes(old): 
```
tools: Figma, AWS, Nginx, Docker, Style Components, Zoom, GitHub, Google Drive, Docs, Sheets, Slides
``` 
or
codeblock 2: incoming changes(new): 
```
tools: 
  - Figma
  - AWS
  - Nginx
  - Style Components
  - Zoom
  - GitHub
  - Google Drive
  - Docs
  - Sheets
  - Slides
```

**Comment by kezzaam** [comment]
@klei0229 Great work spotting the formatting change! I thought I was pretty good with details but I missed that one. And I see that the branch has conflicts, so perhaps it needs to be redone. 

@sakibian If you sync up your branch and push it to your forked repo, it might resolve the problem.

**Comment by sakibian** [comment]
@kezzaam @klei0229 it was code block 1 format, now I should `git pull upstream gh-pages` than `push` changes?

**Comment by klei0229** [comment]
@sakibian I think that's correct, ```git pull upstream gh-pages``` will pull the current most up to date version of the codebase,. 
From there I believe you should see that there are merge conflicts that you have to address namely you want to accept the changes that will keep the code that looks like code block 2. From there you can make your code changes (apply the removal of nginx from tools from code block 2). After that, you can follow the steps needed to push up to remote.

**Review by klei0229 — CHANGES_REQUESTED** [review]
Line 78 is referring to the old way of formatting tools. Pulling in the latest code will update line the tools section to be the new format (bullets). From there the nginx bullet can be removed as requested from the issue.

**Review by kezzaam — APPROVED** [review]
Hi @sakibian, this one took a bit longer so well done sticking with it. I have reviewed it and can see that the changes have been made as expected, there are no conflicts, and it behaves as expected on the site. Nice work!

**Comment by klei0229** [comment]
Hi @sakibian , well done! Thanks for taking the time to solve this issue.

I also reviewed it and I can confirm that: 
1) The pull request is done from the correct branch
2) There is a linked issue (#5342)
3) I can observe the changes in the browser & everything looks good!

Thanks @sakibian & @kezzaam

**Review by klei0229 — APPROVED** [review]
I also reviewed it and I can confirm that:

The pull request is done from the correct branch
There is a linked issue (https://github.com/hackforla/website/issues/5342)
I can observe the changes in the browser & everything looks good!

**Comment by kwangric** [comment]
Thank you @klei0229 and @kezzaam for the thorough review!

**Pull request merged**
