### PR TITLE
Update Project Profile: Food Oasis (Fix Hannah Zulueta's Slack link)

### LINKED ISSUE #6317: Update Project Profile: Food Oasis (Fix Hannah Zulueta's Slack link)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to fix the link to Hannah Zulueta's Slack profile so that it resolves to Hannah's active account.

### Action Items
- [x] In your IDE, open the `_projects/food-oasis.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, find Hannah Zulueta's profile information.
- [x] Then, change Hannah Zulueta's Slack link
  **From**
  ```
        slack: "https://hackforla.slack.com/team/U01G7AH18J3"
  ```
  **To**
  ```
        slack: "https://hackforla.slack.com/team/U9SCMTNK0"
  ```
- [x] Verify the changes by viewing the following in your local environment:
  - [x] Food Oasis page [^2]
- [x] Once your pull request is merged, go to #6313  and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6313 to the **New Issue Approval** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/food-oasis

### PR DESCRIPTION
**Pull request by luisitocanlas**
Fixes #6317 

### What changes did you make?
  - Updated Hannah Zulueta's Slack link at line 42.

### Why did you make the changes (we will use this info to test)?
  - So that the link resolves to Hannah's active account.

### CODE REVIEW

**Comment by Anahisv23** [comment]
Hey @luisitocanlas thanks for taking up the issue! 

Here's what you did well: 
• Commit into branch and from branch are correct 
• There is a linked issue number
• Appropriate files and lines of code were changed 
• Slack link was correctly updated and clicking the new slack link directs user to Hannah's active account 

Overall great work! Keep it up :)

**Review by Anahisv23 — APPROVED** [review]
Hey @luisitocanlas thanks for taking up the issue!

Here's what you did well:
• Commit into branch and from branch are correct
• There is a linked issue number
• Appropriate files and lines of code were changed
• Slack link was correctly updated and clicking the new slack link directs user to Hannah's active account

Overall great work! Keep it up :)

**Comment by irais-valenzuela** [comment]
Review ETA: 6:30 PM 2/20/24
Availability: 6-8 PM Monday

**Review by irais-valenzuela — APPROVED** [review]
Hey @luisitocanlas, good job on the issue! The branches are correct, you linked the issue, and successfully updated the slack link. Nice job!

**Pull request merged**
