### PR TITLE
Fix Slack links in CoP: Ops: leadership variables 

### LINKED ISSUE #7566: Update CoP: Ops: Fix Slack links in leadership variables
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/ops.yml` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and replace. 
```
leadership-type: Community Led
leadership:
  - name: Chelsey Beck
    github-handle: chelseybeck
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
  - name: Alex English
    github-handle: ale210
    role: Co-lead
    links:
      slack: U078B1S0XDM
      github: https://github.com/ale210
    picture: https://avatars.githubusercontent.com/ale210
  - name: Ryan Sakuma
    github-handle: RSkuma
    role: Co-lead
    links:
      slack: U078U294XB6
      github: https://github.com/RSkuma
    picture: https://avatars.githubusercontent.com/RSkuma
  - name: Sudha Raamakrishnan
    github-handle: sudhara
    role: Ops PM
    links:
      slack: https://hackforla.slack.com/team/U07FJRNN9MK
      github: https://github.com/sudhara
    picture: https://avatars.githubusercontent.com/sudhara
  - name: Dean Church
    github-handle: Rankazze
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJR0UKBN1
      github: https://github.com/Rankazze
    picture: https://avatars.githubusercontent.com/Rankazze
```
with this
```
leadership-type: Community Led
leadership:
  - name: Chelsey Beck
    github-handle: chelseybeck
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
  - name: Alex English
    github-handle: ale210
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U078B1S0XDM
      github: https://github.com/ale210
    picture: https://avatars.githubusercontent.com/ale210
  - name: Ryan Sakuma
    github-handle: RSkuma
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U078U294XB6
      github: https://github.com/RSkuma
    picture: https://avatars.githubusercontent.com/RSkuma
  - name: Sudha Raamakrishnan
    github-handle: sudhara
    role: Ops PM
    links:
      slack: https://hackforla.slack.com/team/U07FJRNN9MK
      github: https://github.com/sudhara
    picture: https://avatars.githubusercontent.com/sudhara
  - name: Dean Church
    github-handle: Rankazze
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJR0UKBN1
      github: https://github.com/Rankazze
    picture: https://avatars.githubusercontent.com/Rankazze
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [ ] [Insert name of project] page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label** and add the `ready for stakeholder` label
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/communities-of-practice
[^3]: initiating ER:  #7294

### PR DESCRIPTION
**Pull request by theogguu**
Fixes #7566

### What changes did you make?
  - Updated links under 'leadership' variable. Replaced
 ```leadership-type: Community Led
leadership:
  - name: Chelsey Beck
    github-handle: chelseybeck
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
  - name: Alex English
    github-handle: ale210
    role: Co-lead
    links:
      slack: U078B1S0XDM
      github: https://github.com/ale210
    picture: https://avatars.githubusercontent.com/ale210
  - name: Ryan Sakuma
    github-handle: RSkuma
    role: Co-lead
    links:
      slack: U078U294XB6
      github: https://github.com/RSkuma
    picture: https://avatars.githubusercontent.com/RSkuma
  - name: Sudha Raamakrishnan
    github-handle: sudhara
    role: Ops PM
    links:
      slack: https://hackforla.slack.com/team/U07FJRNN9MK
      github: https://github.com/sudhara
    picture: https://avatars.githubusercontent.com/sudhara
  - name: Dean Church
    github-handle: Rankazze
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJR0UKBN1
      github: https://github.com/Rankazze
    picture: https://avatars.githubusercontent.com/Rankazze
```
with
```
leadership-type: Community Led
leadership:
  - name: Chelsey Beck
    github-handle: chelseybeck
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
  - name: Alex English
    github-handle: ale210
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U078B1S0XDM
      github: https://github.com/ale210
    picture: https://avatars.githubusercontent.com/ale210
  - name: Ryan Sakuma
    github-handle: RSkuma
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U078U294XB6
      github: https://github.com/RSkuma
    picture: https://avatars.githubusercontent.com/RSkuma
  - name: Sudha Raamakrishnan
    github-handle: sudhara
    role: Ops PM
    links:
      slack: https://hackforla.slack.com/team/U07FJRNN9MK
      github: https://github.com/sudhara
    picture: https://avatars.githubusercontent.com/sudhara
  - name: Dean Church
    github-handle: Rankazze
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJR0UKBN1
      github: https://github.com/Rankazze
    picture: https://avatars.githubusercontent.com/Rankazze
```

### Why did you make the changes (we will use this info to test)?
  - To keep project information up to date so that visitors to the website can find accurate information

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
Bottom left corner of the screenshots reveal the link changes.
<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by 8alpreet** [comment]
ETA: EOD Oct 8
Availability: 3-7 pm Mon-Fri

**Review by DrAcula27 — APPROVED** [review]
@theogguu Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7566 
- The correct file `_data/internal/communities/ops.yml` was edited
- No extra edits were made
- Appearance of the website is unchanged (Chrome and Firefox)
Approved! 👍

**Comment by codyyjxn** [comment]
ETA: EOD 
Availability: M > F

**Review by codyyjxn — APPROVED** [review]
Hey @theogguu  Thank you for taking on this issue. 

- The branch is correct also provides the issue. 
- The title and description is clear and also you provided screenshots before and after which are great for a first good issue. 
- The attention to detail is great you changed what was needed. 

Keep it up !

**Review by 8alpreet — APPROVED** [review]
Hi @theogguu,

The changes look good!
* the issue is linked
* branch is named well
* PR comment is informative
* Only relative lines of code are changed

**Comment by Thinking-Panda** [comment]
@theogguu Thank you for working on this issue and nice work. The screenshots of "Before " and "After" changes are very helpful. Also, you do not have to paste the code change in the "What changes did you make?" section. Well done overall.

**Pull request merged**
