### PR TITLE
Updated Alt Text

### LINKED ISSUE #3873: Adopt Civic Art: Update alt text for Adopt Civic Art image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text for the `Adopt Civic Art` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/adopt-civic-art.md`:

**From:**
```
alt: 'Adopt civic arts.'
```

**To:**
```
alt: 'Adopt Civic Art'
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #`[INSERT EPIC NUMBER HERE]` to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/adopt-civic-art.md`
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/adopt-civic-art.md?plain=1
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by nicolettedmabeza**
Fixes #3873 

### What changes did you make and why did you make them ?

  - update alt text for the Adopt Civic Art image so that we adhere to the Web Content Accessibility Guidelines (WCAG)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- no visual changes made to website, only code base

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays 10 AM -3 PM
ETA: 9:00 PM 2/17/23

**Comment by vanessavun** [comment]
Availability: Weekday evenings
ETA: 10PM 2/16/23

**Review by vanessavun — APPROVED** [review]
Great job with working on this issue. Commit into gh-pages from your matching username and branch looks correct. You followed directions and made the exact changes. I also agree with removing the extra spaces. Running the website locally, I don't see anything broken. LGTM. Thanks!

**Comment by Thinking-Panda** [comment]
Pull request is done with the correct branches. Changes requested in issue has been done. Changes are applicable and clean. Changes did not break the website. Nice work!

**Review by Thinking-Panda — APPROVED** [review]
Nice work @nicolettedmabeza !

**Pull request merged**
