### PR TITLE
Edit content field and remove type field from job.yml

### LINKED ISSUE #2845: Edit content field and remove type field from job.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/job.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/job.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/job.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/job.yml#L11

### PR DESCRIPTION
**Pull request by MattPereira**
Fixes #2845

### What changes did you make and why did you make them ?
  - Changed content field `key: value` pair in `_data/internal/credits/job.yml`
  - Removed type field from `_data/internal/credits/job.yml`
 
These changes were made to reduce redundancy in the code.

### Screenshots of Proposed Changes Of The Website

Updating content field and type field of job.yml file. No visual changes to the website.

### CODE REVIEW

**Comment by blulady** [comment]
Hey Matt,
So again I appreciate your voracity but volunteers assign themselves to review PR's. Since this is a good first PR, it would be better if other new devs got a chance to review it. Normally I would recommend reviewing other dev's pr. Right now we don't have much but as other folks make their first pr, you'll have a ton to review.

**Comment by GRISONRF** [comment]
ETA: 10/12/2022
Availability: 35min

**Review by GRISONRF — APPROVED** [review]
The changes were made in the correct branch and everything looks good. 

Edit: I just noticed it some checks were not successful and I'm not sure why.  
It got an error parsing the pull request body for all the linked issues, but I don't know if it's related to Matt's code, since everything looks right.

**Comment by giroz** [comment]
ETA: 10/13/22
Availability: 2 hours

**Comment by arpitapandya** [comment]
> The changes were made in the correct branch and everything looks good.
> 
> Edit: I just noticed it some checks were not successful and I'm not sure why. It got an error parsing the pull request body for all the linked issues, but I don't know if it's related to Matt's code, since everything looks right.

Answer on why some checks fail: We have GitHub actions that check for linked issue when we create a pull request. I see that @MattPereira mistakenly typed `Fixes #3615` while creating a pull request to link the issue so checks didn't pass and that failed to generate PR labels automatically. but, later on, the correct issue is linked.

**Comment by gstemmann** [comment]
Review ETA: 6 PM 10/15/22
Availability: 6 hours

**Review by gstemmann — APPROVED** [review]
Everything looks good to me. And the correct repositories were chosen.

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing line four to content-type: image and deleting line 11. The code looks clean and there is only one file changed.
Good job!!

**Review by giroz — COMMENTED** [review]
Good job. line 4 added text, and line 11 deleted text

**Pull request merged**
