### PR TITLE
Update Project Profile - Anjola Jaiyeola

### LINKED ISSUE #5852: Update Project Profile: Anjola Jaiyeola PM (Urgent)
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the following as a new entry:
```
  - name: Anjola Jaiyeola
    role: Product Team
    links:
      slack: https://hackforla.slack.com/team/U052HJ1NMEZ
      github: https://github.com/anjolaaoluwa
    picture: https://avatars.githubusercontent.com/u/122532788?v=4
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by tesiahwang**
Fixes #5852

### What changes did you make?
  - Added Anjola Jaiyeola to current project team leadership

### Why did you make the changes (we will use this info to test)?
  - Keep project information up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-11-05 at 2 15 23 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
Screen Shot 2023-11-05 at 2 15 33 PM

</details>

### CODE REVIEW

**Comment by ajb176** [comment]
ETA: 16 hours

**Review by ajb176 — APPROVED** [review]
- PR is well-formatted and follows all guidelines
- Project profile is properly added and aligned with other product team member(s)
- No unwanted visual changes to webpage

Looks good to me, nice work @tesiahwang

**Comment by freaky4wrld** [comment]
Availability: 7PM 06/11/23
ETA: EOD 06/11/23

**Review by freaky4wrld — APPROVED** [review]
Hey @tesiahwang great work there......
- the branch is merging correctly
- the changes and the reason to make changes are done correctly
- the visual changes are clearly shown before and after the changes are made

Kudos to the progress you made

**Pull request merged**
