### PR TITLE
Edit content field and remove type field from giving.yml credits file issue 2828

### LINKED ISSUE #2828: Edit content field and remove type field from giving.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/giving.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/giving.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/giving.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/giving.yml#L11

### PR DESCRIPTION
**Pull request by Unity7**
Fixes #2828

### What changes did you make and why did you make them ?

Made changes to _data/internal/credits/giving.yml

  - Change line 4 for the content field from content: icon to content-type: image
  -  Remove line 11 for the type field type: icon
  - changes were made because fields were redundant

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website

### CODE REVIEW

**Comment by AzaniaBG** [comment]
Availability: afternoon of 09/16/2022 
ETA: 09/16/2022 by 6 PM

**Comment by plang-psm** [comment]
Review ETA: 11 PM 5/15/22
Availability: 2hrs Thursday

**Review by plang-psm — APPROVED** [review]
Great documentation, no extra changes and runs fine. Solid work!

**Review by AzaniaBG — APPROVED** [review]
Nice job, @Unity7 ~ it was easy to understand which changes you made.

**Comment by arpitapandya** [comment]
ETA: 2022-09-16
Availability: 30 minutes

**Review by arpitapandya — APPROVED** [review]
All the changes are correct and doesn't break anything!! Great job! @Unity7

**Pull request merged**
