### PR TITLE
remove-non-existent-classes-2721

### LINKED ISSUE #2721: Remove non-existent classes from citizen-engagement.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers, we should make sure our code does not use SCSS classes that do not exist. For this issue, we will remove the non-existent classes `card-body` and `card-width` from a line of code.

### Action Items
- [x] On [line 41 in pages/citizen-engagement.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/pages/citizen-engagement.html#L41), remove the classes `card-body` and `card-width` from
```
            <div class="page-card card-primary page-card-lg card-body card-width organizations">
```
so the result is
```
            <div class="page-card card-primary page-card-lg organizations">
```
- [x] Using Docker locally on your computer, check [Citizen Engagement page](https://www.hackforla.org/citizen-engagement) looks the same as the page on the current site in various desktop, tablet, and mobile views using developer tools

### Resources/Instructions
- [line 41 in pages/citizen-engagement.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/pages/citizen-engagement.html#L41)
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)

### PR DESCRIPTION
**Pull request by A-BMT02**
Fixes #2721
### What changes did you make and why did you make them ?

  -  Removed non-existent classes from citizen-engagement.html as requested
  - Used Docker locally on my computer to check if  [Citizen Engagement page](https://www.hackforla.org/citizen-engagement) looks the same as the page on the current site in my local computer using developer tools as requested
  - No screenshots

### CODE REVIEW

**Comment by A-BMT02** [comment]
Availability for this week: Available
My estimated ETA for completing this issue:30 minutes

**Comment by A-BMT02** [comment]
Providing Update
1. Progress - Done
2. Blockers - None
3. Availability - Available
4. ETA - Done

**Review by JessicaLucindaCheng — APPROVED** [review]
@A-BMT02 Good job on making the changes in the code!

- I have gone ahead and added this pull request (pr) to the Project Board this time. However, for your future prs, please add your pr to the Project Board yourself. If you need more detailed instructions on how to do so, I have provided them below.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
      how-to-add-to-the-project-board1
    
    2) Click on the gear icon
      Add-to-project-board
    
    3) Then click on Project Board to add your pull request to the project board.
      how-to-add-to-the-project-board3
  
  </details>
  
- Your initial availability and ETA and the progress update (progress, blockers, availability, ETA) should not be in this pr. Instead, they should be comments in your issue.

**Comment by A-BMT02** [comment]
Noted @JessicaLucindaCheng 
I will make sure to add my future pull requests to the Project Board 
Thanks for the review

**Pull request merged**
