### PR TITLE
Delete unused Slack svg file

### LINKED ISSUE #6648: Delete unused Slack svg file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We have refactored HTML/CSS throughout the site to use a single version of the Slack icon and in this issue we will remove the unused svg file from the codebase.  

### Action Items
- [x] In your IDE, delete the file `https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack-color.svg`
- [x] Don't forget to use `git add` to stage the deletion and `git commit` to commit the change
- [x] Proceed with a pull request in the usual manner

### Resources/Instructions
- This issue resulted from #5758

### PR DESCRIPTION
**Pull request by Beatriz-G**
Fixes #6648

### What changes did you make?
  - Deleted unused Slack svg file

### Why did you make the changes (we will use this info to test)?
  - Deleted the unused svg file from the codebase to use a single version of the Slack icon.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Deleted a file no visual changes to the website.

### CODE REVIEW

**Comment by Jperparas** [comment]
**availability:** 04/17
**ETA:** EoD 04/17

**Comment by Beatriz-G** [comment]
@irais-valenzuela @Jperparas    I had put the wrong issue number, fixed it and should link to issue #6648 . Labels are now showing so it should be good to go. Let me know if anything else needs to be worked on.

**Comment by irais-valenzuela** [comment]
Availability: 4/17
ETA: 4/17

**Review by irais-valenzuela — APPROVED** [review]
Hey @Beatriz-G, nice job on the issue! You linked the issue, the branches are correct, and successfully deleted the icon-slack-color.svg file. Nice work!

**Review by Jperparas — APPROVED** [review]
Hi @Beatriz-G thanks for contributing, here's what you did right:

1. pull request contains the correct branch
2. Correct Issue is linked
3. No visual changes 
4. Correct file deleted

Good Job!

**Pull request merged**
