### PR TITLE
Update Home Unite Us technology array - Amazon Cognito / OIDC / OAuth2 - 4782

### LINKED ISSUE #4782: Update Home Unite Us Project File to split up long technology name
### Overview
We need to split the technology item `Amazon Cognito / OIDC / OAuth2` from the "Home Unite Us" project page into three separate items, so that the name will not be truncated on the filter tag when the filter is activated the Projects page.  

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/home-unite-us.md` file and find the `technology` array
- [x] Replace the line 
```
  - Amazon Cognito / OIDC / OAuth2
```
with these three lines:
```
- Amazon Cognito
- OIDC
- OAuth2
```
- [x] Using Docker, view the Projects Page and confirm that the appearance and functionality of the new technology items is correct on the project card for Home Unite Us

### Resources/Instructions
<details><summary>Screenshot showing truncation of the current technology item</summary>

image

</details> 

- [home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- [HfLA Projects Page](https://hackforla.org/projects)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- This issue is a result of #4770

### PR DESCRIPTION
**Pull request by matthewmpan**
Fixes #4782

### What changes did you make and why did you make them ?

  - Removed the line ` - Amazon Cognito / OIDC / OAuth2`
  - Split the technologies into three separate lines 
  ` - Amazon Cognito`
  ` - OIDC`
  ` - OAuth2`
  - The technologies are no longer truncated on the filter tag and can be filtered independently

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-06-15 at 4 34 21 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2023-06-15 at 4 56 52 PM

</details>

### CODE REVIEW

**Comment by LOSjr4** [comment]
Availability: weekdays 8AM-10AM
ETA: 6/16 10AM

**Review by LOSjr4 — APPROVED** [review]
The changes on home-unite-us.md look clean. I see the three technologies separated with commas instead of slashes on docker. I see the three technologies show up individually on the filter selections, and they each point to Home Unite Us when toggled.
Good work @matthewmpan ! Thank you for taking this issue.

**Comment by Sebster3** [comment]
Availability: 9AM-1PM
ETA: 6/18 10AM

**Comment by Sebster3** [comment]
Good work here, @matthewmpan! The branches are correct, the edits were made neatly, and the page renders properly in my local environment, and the filter functionality is consistent with what is expected. Approved 👍🏽

**Review by Sebster3 — APPROVED** [review]
Good work here, @matthewmpan! The branches are correct, the edits were made neatly, and the page renders properly in my local environment, and the filter functionality is consistent with what is expected. Approved 👍🏽

**Comment by matthewmpan** [comment]
@LOSjr4 & @Sebster3 Thanks for the reviews! @t-will-gillis Thanks for the merge!

**Pull request merged**
