### PR TITLE
Update alt text ctjobsimage 3950

### LINKED ISSUE #3950: Civic Tech Jobs: Update alt text for Civic Tech Jobs image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Civic Tech Jobs` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/civic-tech-jobs.md`:

**From:**
```
Hack for LA logo and the title of the project, Civic Tech Jobs
```

**To:**
```
Civic Tech Jobs
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- Civic Tech Jobs: https://www.hackforla.org/projects/civic-tech-jobs

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/civic-tech-jobs.md`
- Click on the filename below to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md

- This issue is part of epic #3866 

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by mjh-projects**
Fixes #3950
### What changes did you make and why did you make them ?

  -Change the image alt property value To:
Civic Tech Jobs
  -
  -

### CODE REVIEW

**Comment by richardmundyiii** [comment]
Availability: M-F 6am - 8am, 8pm - 11pm
ETA: EOD 03/16/2023

**Review by richardmundyiii — APPROVED** [review]
@mjh-projects Congrats on your first PR. Glad you were able to get your permissions working. Now it's smooth sailing. The requested changes were made in the correct document, the branch is set up correctly, and the issue is properly linked.

In terms of the PR documentation itself, I would suggest to:

* Indicate the "why" of your changes. Something as simple as "Changed img alt text to adhere to the Web Content Accessibility Guidelines (WCAG)" is okay.
* Explain why screenshots are not needed. It's straightforward why it's not needed here, but to follow the [Contributing instructions](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available), then include something like:

`### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

Only alt text is changed. No visual changes to the website.`

Overall, congrats on your good first issue!

**Comment by perlaroyerc** [comment]
Review ETA: 5 PM 3/17/23
Availability: 11-6 PM ET M-F

**Review by perlaroyerc — APPROVED** [review]
Thank you for taking this issue @mjh-projects! The changes look good in the local environment, the issue is linked, and the branches are set up correctly. 

Some minor details to work on:
-Edit the description under `What changes did you make and why did you make them?` to a smaller font and remove the bold format. 
-Create the habit of adding a brief explanation of "why" you made the changes, this will help to keep your documentation super impressive!

Keep up the good work!

**Pull request merged**
