### PR TITLE
worked on adding githandle for Dr. Stephen M. Hubbard

### PR DESCRIPTION
**Pull request by deepak-getpu**
Fixes #6856

### What changes did you make?
  - Added GitHub handle for Dr. Stephen M. Hubbard
  -
  -

### Why did you make the changes (we will use this info to test)?
  - Changed as instructed in the issue
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
@deepak-getpu Please link this PR to an issue by replacing "replace_this_text_with_the_issue_number" with the issue number, and complete the remaining fields.  Thank you

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hey @deepak-getpu 

- #6856 is the issue number of the pull request itself. What you need to link is the actual number of the issue you were assigned to. 

- You should remove the placeholder image links and the details tabs if you're not using them, and just write 'No visual changes to the website' if after testing in docker you don't see any changes. 

- In the 'Why did you make these changes' section, you should write what the issue means to solve. You can generally find this information in the linked issue.

**Comment by LRenDO** [comment]
Hi @deepak-getpu! Thanks for working on this issue! In addition to the changes @ajb176 requested, also make sure you add the same labels on this pull request as on the original issue. (This usually this happens automatically, but sometimes it doesn't work. It generally fails when the issue number isn't added at the time the PR was created.) Please also remove any unused bullet points from the original PR comment.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @deepak-getpu Great job on your first issue! Some notes:
- As @ajb176 notes: for "Fixes" use the number of the issue you have worked on, in your case replace the 6856 with 6718.
- For the next time (not now)- when you name your branch, use the number of the original issue (that is, title it `update-givelink-6718` instead)
- On issue 6718, remember to check the "Action Items" that you completed
- Also as Ajay notes, for "Why did you make the changes..." this is meant to be the reason from the original issue, in this case the reason could be something like "To reduce redundancy in the project files"
- As @LRenDO notes: you can delete the empty lines under "What changes'' and "Why did you make ..."
- And as Ajay notes, you can delete everything under "Screenshots of Proposed Changes..." and replace with "No visual changes"
- You don't need to assign yourself to the PR...
- Otherwise, your code edits are clean and correct.

This is looking good and you are almost there! Thanks for working on this issue

**Comment by deepak-getpu** [comment]
I was trying to do corrections by 1) re-adding in git, 2) commit 3)push in the new branch 4)running docker. However, I could not pull the request as indicated or demonstrated in the pre-boarding checklist documents. I am struggling to find a page similar to the one shown in the document for git pull. Any help and guidance on this would be appreciated.

**Comment by t-will-gillis** [comment]
Hi @deepak-getpu:

> I was trying to do corrections by 10 re-adding in git, 2) commit 3)push in the new branch 4)running docker. However, I could not pull the request as indicated or demonstrated in the pre-boarding checklist documents. I am struggling to find a page similar to the one shown in the document for git pull. Any help and guidance on this would be appreciated.

It seems like there was a miscommunication. The changes that the reviewers were asking for did not involve Git or Docker. 

Any of us will be happy to help you- I am happy to help you with this if we can set up a specific time. You can also bring your questions to one of the meetings. Let us know.

**Comment by deepak-getpu** [comment]
Hi Will,

Thank you for reaching out to me. I am desperately stuck completing my
first issues as these steps involved here were completely new and i never
had opportunity to learn these steps during my study of backend software
development.

Help in completing my first issue would be really helpful. I am available
almost all days this week from (9 am to 2.30 pm). For evening i would be
available Monday, Wednesday, Thursday, and Friday from (6 pm to 9 pm
Central time).

Thanking you,
Deepak Acharya

**Comment by deepak-getpu** [comment]
Closing this pull request, replaced by #6886.

**Pull request closed without merging**
