### PR TITLE
Updated Project Profile in Civic Tech Jobs - Jenn Wu #5385

### LINKED ISSUE #5385: Update Project Profile: Civic Tech Jobs (add Jenn Wu)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] Add a new entry for Jenn Wu:
```
  - name: Jenn Wu
    role: UX Researcher Lead
    links:
      slack: https://hackforla.slack.com/team/U05JS3V38TV
      github: https://github.com/jayywu
    picture: https://avatars.githubusercontent.com/ jayywu
```
 - [x] Place Jenn's profile after any other Lead's profiles
 - [x] Confirm on your local that links for the member appear to be correct (i.e. for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by siddhanthiyer-99**
Fixes #5385 

### What changes did you make?
  - Added Jenn Wu as a UX Researcher Lead to Civic Tech Jobs.

### Why did you make the changes (we will use this info to test)?
  - New Profile to be added
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
before

</details>

<details>
<summary>Visuals after changes are applied</summary>
after

</details>

### CODE REVIEW

**Review by roslynwythe — DISMISSED** [review]
Great job @siddhanthiyer-99 on your first good issue.  The branches are setup correctly, the code change is correct, the PR is descriptive, and the code checks out in the browser, including the GitHub and Slack links.  Thank you!

**Comment by siddhanthiyer-99** [comment]
Thank you @roslynwythe! Just getting started, happy to contribute! :)

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @siddhanthiyer-99 Great job- Your branches from and into are good, you are linked back to the original issue, you give clear reasons what and why you made the changes, and you provide before and after visuals.

I have one request for a change- since Jenn Wu is a UX Researcher Lead, their name needs to be with the other Leads, that is higher on the list. Would you please move Jenn Wu's entry so that it appears immediately _**after**_ the entry for the other UX/UI Design Lead:
```
  - name: Jen Chung
    role: UX/UI Design Lead
    links:
      slack: https://hackforla.slack.com/team/U02A6H5PVAA
      github: https://github.com/jenchuu
    picture: https://avatars.githubusercontent.com/jenchuu
```
Otherwise, everything looks great- thanks for contributing!

**Comment by siddhanthiyer-99** [comment]
Hi @t-will-gillis,
I have made the necessary changes and added Jenn right next to another UX Research Lead. Please let me know if it looks alright.
Happy to contribute!

**Comment by t-will-gillis** [comment]
Hi @siddhanthiyer-99 Thanks for moving the entry for "Jenn Wu"-

However, as I noted in my comment above: 
- please move the entry for "Jenn Wu" directly after the entry for "Jen Chung".

(The placement you chose won't work because _**that**_ person's entry is also being reordered (by a separate issue), which is why "Jenn Wu" needs to come after "Jen Chung".)

Apologies for the confusion. The CTJ team has many simultaneous changes happening.

**Comment by siddhanthiyer-99** [comment]
Hi @t-will-gillis,
Thank you for the feedback. I have made the appropriate changes and added "Jenn Wu" right after "Jen Chung" as per your instructions. Apologies for the confusion from my end too. Hope this change completes the issue at hand. However, please do let me know if anything else needs to be done. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hey @siddhanthiyer-99 Congratulations on your first PR- looks perfect! Thanks so much for re-locating "Jenn Wu", and thank you for your help working through this issue!

**Pull request merged**
