### PR TITLE
Check dependabot version updates to schedule-daily-1100.yml 4826

### LINKED ISSUE #4826: Verify dependabot version updates to GHAs for schedule-daily-1100.yml
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.
### Overview
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) has been identifying the packages/dependencies for which a more recent version is available, and for each it has created a PR detailing which files in our codebase use that package/dependency. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 
### Action Items
Refer to the [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) file and review with the version updates recommended by the dependabot.
Select:
  - [x] PASSES TEST #4735 \`uses: actions/checkout@v2\` with \`uses: actions/checkout@v3\`
Or:
  - [ ] FAILS: #4735. Do not update.

Merge team:
- [x] Transfer results to #4815
### Resources/Instructions
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #4826 
### What changes did you make and why did you make them ?

  - Tested updating the package version in the file `schedule-daily-1100.yml` per the dependabot suggestions:
    - Tested changing `uses: actions/checkout@v2` with `uses: actions/checkout@v3` per 4735
    - It appears that updating to  `uses: actions/checkout@v3` does not effect the GHA- after the update the action still creates the `github-data.json` as intended.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Changes effect GHAs only

### CODE REVIEW

**Comment by LOSjr4** [comment]
Availability: weekdays 12PM-2PM
ETA: 6/23 2PM

**Review by blulady — DISMISSED** [review]
I reviewed this pr by pulling the branch into my local. I changed .github/workflows/schedule-daily-1100.yml by commenting out lines 5/6 and using on: workflow_dispatch to be able to trigger the workflow manually. I then use my github handle in line 12 with my gi I also made sure I set up HACKFORLA_BOT_PA_TOKEN in my local repo as described in the [docs](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board). If you are reviewing this you will also need the project board set up like it suggests in the [wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board). Once I modify the file to run the action in my repo, make sure that I have the project board and token properly set up, I push the branch up to *My* GitHub repo. I make that branch my main/default branch in my GItHub repo. Then I can go to actions, then Schedule Daily 1100 and click run workflow. Once I did that the action successfully ran.

**Review by LOSjr4 — DISMISSED** [review]
I followed @blulady 's instructions after watching her test this PR during Thursday's meeting. 
I had previously copied the project board to my repository. On github/workflows/schedule-daily-1100.yml, I commented out the scheduled section and added "workflow_dispatch" to enable a manual run. I wrote in my repository name instead of hackforla on line 11. I set up a token in GitHub and replaced the secrets name on line 17. I pushed the branch to my repo. I changed the default repo to this branch in my general GitHub settings. I manually ran the workflow for Schedule Daily 1100 under Actions. After the run was successful, I checked _data/external/github-data.json to verify the date and time of my manual run was shown on line 2.
The v3 update seems to work as intended.
Thank you @t-will-gillis for taking on these multiple dependabot issues.
Thank you @blulady for helping with the review.

**Comment by t-will-gillis** [comment]
Having issues resolving the merge conflict with `github-data.json`. Closing with PR, opening a new one.

**Pull request closed without merging**
