### PR TITLE
Remove alt hero field 3215

### LINKED ISSUE #3215: Remove unused `alt-hero` field from website.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/website.md`, remove line 8 for the alt-hero
```
alt-hero: 'Five women in tech collaborating, engaging in a joyful conversation.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/website.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a2c97475e2d1ab5956bf5cbe95c7e251ce8a1033/_projects/website.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by matt-arofin**
Fixes #3215

### What changes did you make and why did you make them?

  - Deleted deprecated `alt-hero` field on line 8 of the file `_projects/website.md`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
N/A: Code changes only

### CODE REVIEW

**Comment by matt-arofin** [comment]
PR made to the wrong issue

**Comment by matt-arofin** [comment]
Older commits are from a different branch - unsure why they were included in this PR.
Only the most recent commit applies to the file changed here

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Thursday, June 9th

**Review by Wny-Duong — APPROVED** [review]
The alt-hero's line been deleted as it should. Nice work.

**Comment by answebdev** [comment]
Availability: 1 hour
Review ETA: 6/8/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@matt-arofin Thank you for submitting your PR. For this issue, you needed to remove line 8 for the alt-hero for the file `_projects/website.md`, which I can see that you did. Great job!

On a minor note, please add this PR to the Project Board. Thank you.

**Comment by matt-arofin** [comment]
> @matt-arofin Thank you for submitting your PR. For this issue, you needed to remove line 8 for the alt-hero for the file `_projects/website.md`, which I can see that you did. Great job!
> 
> On a minor note, please add this PR to the Project Board. Thank you.

Thanks for the heads up @answebdev, hadn't realised it wasn't on the board!

**Comment by answebdev** [comment]
@matt-arofin You're welcome. Thanks for adding it to the Project Board.

**Pull request merged**
