### PR TITLE
Changed Image Alt Value within _projects/new-schools-today.md

### LINKED ISSUE #4046: New Schools Today: Update alt text for New Schools Today image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `New Schools Today` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/new-schools-today.md`:

**From:**
```
Team of students each with a laptop sitting around the conference table, attentively engege in a video conference call meeting.
```

**To:**
```
New Schools Today
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/new-schools-today

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/new-schools-today.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/new-schools-today.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by kimberlytanyh**
Fixes #4046 

### What changes did you make and why did you make them ?

  - As requested, I changed the original image alt value to "New Schools Today"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Changed text value in image alt section of a .md file. No visual changes to website.

### CODE REVIEW

**Comment by RyanGehris** [comment]
Availability: 6-8pm
ETA: EOD 03/08/2023

**Review by RyanGehris — APPROVED** [review]
Thank you for working on this issue! The alt text changes were correctly applied, and I was able to see them when inspecting the image on my local computer. 

One thing that I would advise in the future is to check off the bullets/boxes under Action items when completing you [issue](https://github.com/hackforla/website/issues/4046). It can help you and your reviewers when completing an issue/PR. 

Great Job Kimberly!

**Comment by kimberlytanyh** [comment]
Thank you for the feedback and advice, Ryan! I will make sure to check off action items completed in future issues!

**Review by Skydodle — APPROVED** [review]
Great work! I see the image alt property value within `_projects/new-schools-today.md` is changed correctly to `New Schools Today`. Thank you.

**Comment by Skydodle** [comment]
Availability: 7-9pm PST
ETA: EOD 03/08/2023

**Pull request merged**
