### PR TITLE
Change alt tag for Public Tree Map Project image on events page to adhere to WCAG issue #3284

### LINKED ISSUE #3284: Change alt tag for Public Tree Map Project image on events page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the westside location on [Events page](https://www.hackforla.org/events/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_includes/events-page/our-locations-content.html`, change [line 46](https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L46) for the alt text:

from
```
<img id="mini-img" src="../assets/images/projects/public-tree-map.png" alt="Public Tree Map Project" />
```
to
```
<img id="mini-img" src="../assets/images/projects/public-tree-map.png" alt="" />
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3132 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3132 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3132 
- [Events page](https://www.hackforla.org/events/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/events-page/our-locations-content.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L46

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by MatthewBozin**
Fixes #3284 

### What changes did you make and why did you make them ?

  -Removed alt text from Public Tree Map div in our-locations-content.html

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
This PR causes no visual changes to the website.

### CODE REVIEW

**Comment by michaelmagen** [comment]
Review ETA: 3 PM 10/25/22
Availability: 3-4 PM Tuesday

**Comment by jyaymie** [comment]
Review ETA: 10/25/22 4:00pm
Availability: 1 hour

**Review by michaelmagen — APPROVED** [review]
Great job! Everything looks good to me.

**Review by jyaymie — APPROVED** [review]
Awesome job, @MatthewBozin! The PR was done with the correct branch and all requested changes in the linked issues were made. One minor thing I would do for the next PR is, in the body of the PR, include a brief reason for the change(s) you made.

**Pull request merged**
