### PR TITLE
Updated content field and removed type field in internal/rocket.yml

### LINKED ISSUE #2873: Edit content field and remove type field from rocket.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/rocket.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_data/internal/credits/rocket.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/8ba65e1fc269bf94a737a9892d56e541d79b8302/_data/internal/credits/rocket.yml#L4
https://github.com/hackforla/website/blob/8ba65e1fc269bf94a737a9892d56e541d79b8302/_data/internal/credits/rocket.yml#L11

### PR DESCRIPTION
**Pull request by wendybarrios**
Fixes #2873

### What changes did you make and why did you make them ?

- Updated "content: icon" field to "content-type: image"
- Removed type field

### Screenshots of Proposed Changes Of The Website  
No visual changes to the website.

### CODE REVIEW

**Comment by angelenelm** [comment]
Review ETA: 7PM PST 11/16/2022
Availability: 10AM - 5PM PST M-F

**Review by angelenelm — DISMISSED** [review]
The requested changes to rocket.yml in the issue are addressed correctly, and are done on the correct branch. Good job @wendybarrios :)

**Comment by Adastros** [comment]
Review ETA: 11PM 16NOV22
Availability: 9 - 11 PM

**Review by Adastros — COMMENTED** [review]
Good job @wendybarrios! You completed the action items successfully! 

One thing I would like to note is that line 11 is empty. I don't believe this affects anything on the site but to keep it consistent with the structure of the other credit files, I think it would be best to remove the empty line. 

What are your thoughts @angelenelm?

**Comment by angelenelm** [comment]
@Adastros I think that's a fair change to request :)

**Review by arpitapandya — CHANGES_REQUESTED** [review]
- Hey @wendybarrios could you remove space from line no. 11.
- Also in your comment on the top of the Pull request, I would suggest keeping it short. for e.g. 'removed type field and update content filed' in bullet points. Instead of copying the checkboxes from the original issue.
- You can look at other PR's for the format

**Review by arpitapandya — APPROVED** [review]
Thank you for making the changes. It's correct. Good job! @wendybarrios

**Pull request merged**
