### PR TITLE
Add program area to adopt-civic-art.md file

### LINKED ISSUE #2275: Add Program Area: Adopt Civic Art
### Overview
We need to add program area information to the Adopt Civic Art project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Citizen Engagement
```

### Resources/Instructions
File location to make the change: _projects/adopt-civic-art.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/adopt-civic-art.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

### PR DESCRIPTION
**Pull request by Zhu-Joseph**
Fixes #2275

### What changes did you make and why did you make them ?

  - Add program area to  _projects/adopt-civic-art.md
  - No proposed changes to the website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by macho-catt — CHANGES_REQUESTED** [review]
Hi @Zhu-Joseph. @abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.

Could you update your PR to reflect these changes? Basically it should look like this now:
```
programs:  
    - Citizen Engagement
```

Thanks!

**Comment by Zhu-Joseph** [comment]
> Hi @Zhu-Joseph. @abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
> 
> Could you update your PR to reflect these changes? Basically it should look like this now:
> 
> ```
> programs:  
>     - Citizen Engagement
> ```
> 
> Thanks!

Hi Matt, 

I updated program area to programs. 

Thanks

**Review by SAUMILDHANKAR — APPROVED** [review]
Thanks Joseph. I can see the change in my environment, looks good.

**Review by R-Tomas-Gonzalez — APPROVED** [review]
Thank you! Looks good to me!

**Review by macho-catt — APPROVED** [review]

**Pull request merged**
