### PR TITLE
create yml data file for former-sponsors-partners

### LINKED ISSUE #6199: Create yml data file for former-sponsors-partners
### Overview
We require a means of storing data relating to former sponsors and partners.  In this issue we will create the file and populate it with data pertaining to Code for America.  

### Action Items
- [x] Open your IDE to `_data/internal` then create a new file `former-sponsors-partners.yml`
- [x] Paste this content:
```
- name: Code for America
  image: /assets/images/former-sponsors-partners/code-for-america.svg
  link: https://www.codeforamerica.org/
```

### Resources/Instructions
- This issue resulted from #5953

### PR DESCRIPTION
**Pull request by aconstas**
Fixes #6199 

### What changes did you make?
  - Create new YAML file in `_data/internal` titled `former-sponsors-partners.yaml`
  - Add `name` `image` `link` text

### Why did you make the changes (we will use this info to test)?
  - Per issue: "We require a means of storing data relating to former sponsors and partners."

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Visual changes are not related to this PR or Issue.

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 2/29/24
Availability: Weekday evenings

**Comment by ajb176** [comment]
ETA: 20 minutes

**Review by ajb176 — APPROVED** [review]
PR is formatted properly and YML file was added exactly as requested

Nice work @aconstas

**Review by pdimaano — APPROVED** [review]
@aconstas Good job: The branches are correct and the issue is linked. The correct file was added with the requested information. The website still works properly on my system on desktop, mobile and tablet. Well done!

**Pull request merged**
