### PR TITLE
updated the access the data profile section

### LINKED ISSUE #2007: Update Project Profile: Access the Data
### Overview
As a product manager of Access the Data I want my project's details to be up to date on the HackforLA website

### Project card
_https://www.hackforla.org/projects/access-the-data 

### Action Items

- [x] Assess the Data Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking- remove UX Lead to build surveys
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status
     
### Resources
[Markdown file where Access the Data is stored](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
File path: `_projects/access-the-data.md`

### PR DESCRIPTION
**Pull request by mehmehmehlol**
Fixes #2007 

### What changes did you make and why did you make them ?

  - updated the profile/ current project team section for the Access the Data project according to profiles provided in the issue comment
  - Removed looking - UX Lead to build surveys (on line 47 and 48 in the original file)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Access the Data Profile Before Pic

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Access the Data Profile After Pic

</details>

### CODE REVIEW

**Comment by mehmehmehlol** [comment]
I forgot to remove the "looking - UX Lead..." line, I will commit again

**Comment by mehmehmehlol** [comment]
sorry, I accidentally reopened the pull request when commenting

**Comment by mehmehmehlol** [comment]
I apologized for closing and reopening the pull request multiple times. I thought I needed to close the pull request if I wanted to commit again -- now everything's been updated based on the changes mentioned in the issue.

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
Hi @mehmehmehlol Thanks for sharing your image for the visuals after changes are applied. I just realized that the role of Sarah Nabelsi should be changed to Project Manager instead of Product Manager in line number 20 in your branch.

**Comment by mehmehmehlol** [comment]
@SAUMILDHANKAR hey Saumil! thanks for bringing this to my attention -- I didn't notice the changes in title. Just fixed it, and please let me know if there's anything else I am missing/need to be fixed. Thanks!

**Review by adrian-zaragoza — CHANGES_REQUESTED** [review]
Hi @mehmehmehlol Thank you for working on this issue! I found a small problem with the github links. It looks like the github links are missing for each member in the current project team. Right now, the only member who has the github link is Sarah Nabelsi. 

Other than that, everything else looks good! 

image

**Comment by mehmehmehlol** [comment]
@adrian-zaragoza hey Adrian, thanks for giving me a heads up! I must have overlooked the github links when making the updates. All members have the github links now. I tested the links and they all direct to the respective github profiles. Please let me know what else is missing/needs to be fixed. thanks!

**Review by adrian-zaragoza — APPROVED** [review]
Thank you @mehmehmehlol This looks good!!

**Review by SAUMILDHANKAR — APPROVED** [review]
@mehmehmehlol Thank you Megan. Looks good in my environment.

**Pull request merged**
