### PR TITLE
Update Project Profile: Hackforla.org Website Add Samhitha Kamma

### LINKED ISSUE #7619: Update Project Profile: Hackforla.org Website Add Samhitha Kamma
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/website.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Samhitha Kamma
    github-handle: Samhitha444
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U07FF529MU6
      github: https://github.com/Samhitha444
    picture: https://avatars.githubusercontent.com/Samhitha444
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Hackforla.org Website page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/website
[^3]: initiating ER:  #7317

### PR DESCRIPTION
**Pull request by mamypoco**
Fixes #7619

### What changes did you make?
  
  URL: https://www.hackforla.org/projects/website
  File: _projects/website.md
  Section: leadership
  Add: 
    - name: Samhitha Kamma
    github-handle: Samhitha444
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U07FF529MU6
      github: https://github.com/Samhitha444
    picture: https://avatars.githubusercontent.com/Samhitha444
 

### Why did you make the changes (we will use this info to test)?
  
  -  To add new leader so our website is fully synced

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
Review ETA: 11/5/2024 Tuesday
Availability: 6-9 PM Weekdays (EDT)

**Comment by ajb176** [comment]
ETA: 2 hours

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hi @mamypoco, thanks for working on this issue. Nice work, the project profile entry looks like it's been added as requested. But it looks like there are a few more changes than necessary. 

- Do you have any idea why there's an SSH key in your commit? Make sure to take that out, exposing keys can be dangerous. If this is the same key value you're using to verify your github credentials from your computer, it would be a good idea to delete this key and follow the directions [here](https://github.com/hackforla/website/blob/gh-pages/]CONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors) to create a new one. 
- The commit to the website.md file seems to swap all occurrences of single quotes to double quotes, which isn't necessary. Are you using some kind of formatting tool in your environment that did that automatically?

Lines 82-88 look great and that's all that's necessary in this PR, there shouldn't be any other changes.

If you need help with anything, feel free to reach out.

**Comment by mamypoco** [comment]
> Hi @mamypoco, thanks for working on this issue. Nice work, the project profile entry looks like it's been added as requested. But it looks like there are a few more changes than necessary.
> 
> * Do you have any idea why there's an SSH key in your commit? Make sure to take that out, exposing keys can be dangerous. If this is the same key value you're using to verify your github credentials from your computer, it would be a good idea to delete this key and follow the directions [here](https://github.com/hackforla/website/blob/gh-pages/%5DCONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors) to create a new one.

Sorry, I have no idea: I followed SSH AFTER my good first issue and it was copied in the website directory for some reason. I immediately deleted it as well as the one in the c: drive and from my github SSH setting.

> * The commit to the website.md file seems to swap all occurrences of single quotes to double quotes, which isn't necessary. Are you using some kind of formatting tool in your environment that did that automatically?
> 
> Lines 82-88 look great and that's all that's necessary in this PR, there shouldn't be any other changes.
> 
I did git reset and currently working from as brand new branch. I only added the section for Samhitha Kamma. When I saved it, all the section that has single quotes changed double quotes. I was not aware this on [my good first issue](https://github.com/hackforla/website/pull/7665), which apparently does not have double quotes. Though, do I need to configure VS Code to use single quotes for this project only?

**Comment by siyunfeng** [comment]
> > Hi @mamypoco, thanks for working on this issue. Nice work, the project profile entry looks like it's been added as requested. But it looks like there are a few more changes than necessary.
> > 
> > * Do you have any idea why there's an SSH key in your commit? Make sure to take that out, exposing keys can be dangerous. If this is the same key value you're using to verify your github credentials from your computer, it would be a good idea to delete this key and follow the directions [here](https://github.com/hackforla/website/blob/gh-pages/%5DCONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors) to create a new one.
> 
> Sorry, I have no idea: I followed SSH AFTER my good first issue and it was copied in the website directory for some reason. I immediately deleted it as well as the one in the c: drive and from my github SSH setting.
> 
> > * The commit to the website.md file seems to swap all occurrences of single quotes to double quotes, which isn't necessary. Are you using some kind of formatting tool in your environment that did that automatically?
> > 
> > Lines 82-88 look great and that's all that's necessary in this PR, there shouldn't be any other changes.
> 
> I did git reset and currently working from as brand new branch. I only added the section for Samhitha Kamma. When I saved it, all the section that has single quotes changed double quotes. I was not aware this on [my good first issue](https://github.com/hackforla/website/pull/7665), which apparently does not have double quotes. Though, do I need to configure VS Code to use single quotes for this project only?

Hi @mamypoco, if you have any formatting tool extensions in your VS Code editor, such as Prettier, they could be automatically applied when you save the file. You can go to VS Code settings, type 'format' in the search bar, and click 'Formatting' under 'Text Editor' to check if any settings format your code. 

Pushing extra files not unrelated to the PR could be because you use `git add .`, because `git add .` will add **all** the files you modified to the stage. If that's the case, you can use `git status` to check which files are modified first, and use `git add <the file you want to commit>` to add the specific file you want to commit to the stage.

**Comment by mamypoco** [comment]
Thank you for your advice. 

- I successfully removed the key from my computer and from my github ssh setting. 
- I changed vscode format to use single quote, and updated the section again.
- I did git add "_project/website.md", commit then pushed to remote repo.

Can you review this again?

**Comment by siyunfeng** [comment]
> Thank you for your advice.
> 
> * I successfully removed the key from my computer and from my github ssh setting.
> * I changed vscode format to use single quote, and updated the section again.
> * I did git add "_project/website.md", commit then pushed to remote repo.
> 
> Can you review this again?

You closed this PR earlier and I don't see your new pull request. You may need to reopen this pull request before pushing the change you made. You can follow [3.1 How to make a pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31-how-to-make-a-pull-request) to submit your PR and ensure you push to the right branch.

If it doesn't work, you can create a new branch and submit your PR again. I'll follow up on the original issue to review the new PR. 

Let us know if you need help.

**Comment by mamypoco** [comment]
Hi, I didn't close this PR. Not sure why. I just reopened. Though, will you let me know if I should open new PR?

**Review by siyunfeng — APPROVED** [review]
Great job fixing your PR, @mamypoco !

- The branch you work on is correct, the branch name is clear
- The linked issue number is included
- Availability and ETA are provided
- The change you made is correct
- Before-and-after screenshots match the frontend view

Improvements: 
- Lines 69 and 76 shouldn't have any changes, double-check the modified parts before adding to the stage by running `git add <file name>`. 
- Run `git status` to check which files are modified before adding any files to the stage before committing and pushing, avoid using `git add .`
- Use this format to create a copy board if you need to: 
   ```
   (```) remove the parentheses before submitting
   copy board content
   (```) remove the parentheses before submitting
   ```

Thank you for working on this issue!

**Comment by siyunfeng** [comment]
> Hi, I didn't close this PR. Not sure why. I just reopened. Though, will you let me know if I should open new PR?

Hi @mamypoco , I can see the latest PR you submitted so you don't need to open a new PR. I also reviewed and approved this PR. In order to merge this PR, you will need to re-request @ajb176 to review and approve your latest PR. 

Let me know if you have any questions.

**Comment by mamypoco** [comment]
Really appreciate it. It's so odd that I didn't even touch the line 69 and 76. How do I know there is a space before pushing to the repo? 

Regarding the copy board, why you are suggesting this?

**Comment by siyunfeng** [comment]
> Really appreciate it. It's so odd that I didn't even touch the line 69 and 76. How do I know there is a space before pushing to the repo?
> 
> Regarding the copy board, why you are suggesting this?

### How do I know there is a space before pushing to the repo?
If you open a folder that is a Git repository and begin making changes, VS Code will add useful annotations to the gutter and to the overview ruler.

- A red triangle indicates where lines have been deleted
- A green bar indicates new added lines
- A blue bar indicates modified lines

### Regarding the copy board, why you are suggesting this?
That's a formatting syntax to create a copyboard so it's easier to read or for the reviewer to copy the content and compare the change you made. It's a recommendation but not a must. 

You can check [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for further info if you're interested.

**Review by ajb176 — APPROVED** [review]
Looks good to me now!

It looks like there are a couple spaces that were removed in different locations, but those shouldn't be there anyway. 

Nice work

**Pull request merged**
