### PR TITLE
get in touch anchor tag added in contact-us.html

### LINKED ISSUE #3023: Homepage redesign: Add anchor to Get In Touch section
### Overview
As a developer, I want to be able to go directly to the Get In Touch section on the redesigned homepage so that I can quickly and easily go to that section without scrolling. For this issue, we will add an anchor to the Get In Touch section.  

### Details
<details>
  <summary><h4>Screenshot of Get in Touch Section on the Redesigned Homepage</h4></summary>
  get-in-touch
</details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be pushed into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] Before line 1 in _includes/forms/contact-us.html, add `<a class="anchor" id="get-in-touch"></a>` so that
  ```
  <section class="home--contact home--section">
  ``` 
  becomes
  ```
  <a class="anchor" id="get-in-touch"></a>
  <section class="home--contact home--section">
  ```
- [x] Using Docker, check that going to `localhost:4000/#get-in-touch` jumps to the Get In Touch section on the homepage
- [ ] Once the pull request associated with this issue is approved and merged, 
  - [x] Please update and edit issue https://github.com/hackforla/website/issues/2393 by
    - [x] Checking off the dependency for this issue
    - [x] If all dependencies are checked off, please move issue https://github.com/hackforla/website/issues/2393 to the New Issue Approval column and remove the Dependency label
  - [x] Please update and edit issue #2455 by
    - [x] Checking off the dependency for this issue
    - [x] If all dependencies are checked off, please move issue #2455 to the New Issue Approval column and remove the Dependency label 

### Resources/Instructions
- https://github.com/hackforla/website/blob/467a797f7c9518fcb466b6bdd034de27050b838e/_includes/forms/contact-us.html#L1
- Example page that has anchors: https://www.hackforla.org/about
- Tracked in https://github.com/hackforla/website/issues/2481#issuecomment-968349924
- Related to issues
  - https://github.com/hackforla/website/issues/2393
  - https://github.com/hackforla/website/issues/2455

### PR DESCRIPTION
**Pull request by CalvinTan607**
Fixes #3023 

### What changes did you make and why did you make them ?

  -added anchor tag which links to Get in Touch section of homepage
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to website

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-08-09

**Review by arpitapandya — APPROVED** [review]
The changes looks correct! Great job! @CalvinTan607 

Though, There are dependency labels missing to this PR

**Comment by lilyarj** [comment]
ETA: 8/10
Availability: 2hrs

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Pull request merged**
