### PR TITLE
Include github-handle variable for Sarah Sanger

### LINKED ISSUE #6125: Add github-handle for Sarah Sanger in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Sarah Sanger
```
with
```
- name: Sarah Sanger
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by vincendp**
Fixes #6125

### What changes did you make?
  - I included the variable named `github-handle` for Sarah Sanger

### Why did you make the changes (we will use this info to test)?
  - I added `github-handle` to hold the github handle for Sarah Sanger of the leadership team (Civic Tech Jobs). Eventually, this variable will be used to replace the `github` and `picture` variables

### Screenshots of Proposed Changes Of The Website

- **Screenshots included to show that the appearance of the project webpage is unchanged**

<details>
<summary>Visuals before changes are applied</summary>

civic_tech_jobs_before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
civic_tech_jobs_after

</details>

### CODE REVIEW

**Comment by angela-lee1** [comment]
Review ETA: EOD 3/6
Availability: 6:00pm -10:00pm 3/6

**Review by angela-lee1 — APPROVED** [review]
@vincendp Awesome job! Branches and naming are correct. The issue is linked, and your code is clean. Confirmed that the appearance of the project webpage is unchanged at all screen sizes on my system. For future reference, you could opt not to include screenshots since no visible change was made. Well done! Thank you!

**Comment by w1ld-r** [comment]
Availability: Weekdays 9AM to 8PM CST
Review ETA: EOD Wednesday March 6th

**Review by w1ld-r — APPROVED** [review]
Hi @vincendp — great work on this issue!

* You linked the issue correctly in your PR description
* Your branch is correct
* You clearly described the changes and stated the reason for making them.
* In the future, you can probably forgo the before and after screenshots and just leave a comment saying "No visible changes made to the website." How you did it is totally fine, too, but a comment is a bit easier. 
* Everything looks good across mobile and desktop. No bugs were introduced.

Nicely done -- Approved! 👍

**Pull request merged**
