### PR TITLE
Update alt text 1564

### LINKED ISSUE #1564: Change Alt Text for Check Icon on Credit page
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We want to provide updated alt text for the  `Check` icon so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the alt property value to 'Check Icon' within `_data/internal/credits/check.yml`

**From**
`alt: 'Image of Check'`
**To:**
`alt: 'Check Icon'`

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/check.yml`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/check.yml#L10

### PR DESCRIPTION
**Pull request by riddle015**
Fixes #1564

### What changes did you make and why did you make them ?

  - Updated alt text in 'check.yml from 'Image of Check'  to 'Check Icon'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>
Fixes #1564

### CODE REVIEW

**Review by BrianCodes33 — APPROVED** [review]
Nice job @riddle015 ! I reviewed your code and it all looks good with changing the alt text on the check icon. Keep it up!

**Comment by JessicaLucindaCheng** [comment]
Thanks for working on this issue!

1. Please add your pull request to the project board.
Add-to-project-board

2. Under the screenshots section, if there are no visual changes, you can just write no visual changes and then an explanation why there are no visual changes. (For more info, see this: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

**Comment by JessicaLucindaCheng** [comment]
@riddle015 Thanks for working on this issue!

1. Please add your pull request to the project board.
Add-to-project-board

2. Under the screenshots section, if there are no visual changes, you can just write no visual changes and then an explanation why there are no visual changes. (For more info, see this: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

**Review by blulady — APPROVED** [review]
Looks Good!!

**Comment by JessicaLucindaCheng** [comment]
I merged this pr with the changes asked for in this issue because I didn't want to confuse the developer on their good first issue by telling them to do something different than what is requested in the issue for the alt text. However, I am aware that the audit of the credits page alt text in issue #2572 has determined that the check icon alt text should stay the same and I will make another issue to change the alt text again back to what it was. However, I will await PMs QA review and approval of issue #2572 before writing the issue to change the alt text back.

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng Remember to do this: https://github.com/hackforla/website/pull/2714#issuecomment-1027656125

Edit: Bonnie said it actually should be `alt=""` for all credit image icons.

**Pull request merged**
