### PR TITLE
Deleted Carlos Olivas from Lucky Parking

### LINKED ISSUE #5804: Update Project Profile: Lucky Parking (Remove Carlos Olivas)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Carlos Olivas
    role: Data Scientist
    links:
      slack:
      github:
    picture: https://avatars.githubusercontent.com/u/41702877
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by heejung-hong**
Fixes #5804

### What changes did you make?
  - Removed Carlos Olivas from Lucky Parking

### Why did you make the changes (we will use this info to test)?
  - Keep leadership information up to date.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-20 at 3 21 30 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2023-11-20 at 3 22 20 PM

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 11/22/23
Availability: Weekday evenings

**Comment by freaky4wrld** [comment]
ETA: 11/21/23
Availability: Weekday evenings

**Review by freaky4wrld — APPROVED** [review]
hey @heejung-hong , nice work done by you all the mentioned.
- the to/from branch are correct
- the deletion is done correctly
- visual effects of the changes made are also visible

Approved and good to go......

**Review by pdimaano — APPROVED** [review]
@heejung-hong Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed and the requested information was removed. Well done!

**Pull request merged**
