### PR TITLE
change program area text #4287

### LINKED ISSUE #4287: Make Program Area Consistent on Join Us Page
### Overview
We want our website to be use terms consistently when referring to program areas. On the [Join Us](https://www.hackforla.org/join) page, in the 'Advise Us' section, we need to change the text `Diversity Equity and Inclusion` to `Diversity, Equity & Inclusion`.

### Action Items
- [x] Change the text in the 'Advise Us' section of the [join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html) file from `Diversity Equity and Inclusion` to `Diversity, Equity & Inclusion`.

### Resources/Instructions
- [Join Us page ](https://www.hackforla.org/join)
- [/pages/join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)

### PR DESCRIPTION
**Pull request by janice87**
Fixes #4287 

### What changes did you make and why did you make them ?

  - Updated the Advise Us section under join-us.html to make program area consistent
  - Changed text from Diversity Equity and Inclusion to Diversity, Equity & Inclusion.
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

4287-b4

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
4287-after

</details>

### CODE REVIEW

**Comment by adevlinb** [comment]
Review ETA: Today by 1:00PMPT
Availability: Today before 1:00PMPT

**Review by adevlinb — APPROVED** [review]
Excellent work @janice87!! 

a) The issue is accurately linked.
b) The pull request is descriptive.
c) The pull request includes images to show accurate changes in the browser.
d) The branches are setup correctly. 
e) The changes are Applicable, do not Break the website, and are Clean
f) The changes can be seen in the browser and are as requested.
g) The changes in the source code are as clean and concise as possible.

Thank you for an excellent contribution!

**Comment by mjshelton12** [comment]
Review ETA: Done by noon tomorrow if not tonight
Availability: Tonight until 11pm, tomorrow 9am-12pm

**Review by mjshelton12 — APPROVED** [review]
Great work janice87!

The PR is perfect - correct branches, issue linked, explanation is clear, and screen-shots are helpful.

The code is clean and effective. It can be seen on desktop, tablet, and phone views as expected. You tackled this perfectly, excellent job!

**Comment by Skydodle** [comment]
Review ETA: EOD 3/27
Availability: M-F 6-9pm PST

**Review by Skydodle — APPROVED** [review]
The text was changed correctly, branch naming looks compliant, screen shots were provided, issue was linked correctly, and pull request was added to Project Board.

Great job @janice87 ! Thank you so much !

**Review by plang-psm — APPROVED** [review]
Great job! I will be merging your PR into production.

**Pull request merged**
