### PR TITLE
Corrected a spelling on line 6 of .yml file

### PR DESCRIPTION
**Pull request by eodero**
Fixes # 2916

### What changes did you make and why did you make them ?

  - changed spelling from susainability to sustainability on line 6

### CODE REVIEW

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: 4/18 EOD

@eodero please remove the space between '#' and your issue reference number so that all checks complete properly.

**Comment by harshitasao** [comment]
Availability : Flexible
ETA : 18/04/2022

**Review by Sparky-code — CHANGES_REQUESTED** [review]
@eodero please see my first comment about PR formatting and automated checks. This also ensures documentation is properly linked, can you also  update your title to clearly reflect which .yml file you are making changes to.

**Review by harshitasao — CHANGES_REQUESTED** [review]
Hi, @eodero I can see the changes that you have made in `_data/internal/program-areas/environment-card.yml`, but I think that is not mentioned in the original issue. As per the original issue #2916 you need to make changes in `_projects/lucky-parking.md` Can you please explain that?
And after you make all the changes as per the original issue, please check the action items.

**Comment by Sparky-code** [comment]
Please refer to the comment @harshitasao made. It looks like you may have mixed up a couple things, I do see a [different issue](https://github.com/hackforla/website/issues/2910) that relates to the environment card here that you commented an availability for but did not assign yourself, please only work on one issue at a time.

**Comment by eodero** [comment]
@harshitasao I see. Thanks for the observation will work on the issue again.

**Comment by eodero** [comment]
@Sparky-code Thanks for the observation. Will rectify.

**Pull request closed without merging**
