### PR TITLE
Update Img Alt Text

### LINKED ISSUE #4014: Light The Way: Update alt text for Light The Way image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Light The Way` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/light-the-way.md`:

**From:**
```
Veteran returned from service to civilian life.
```

**To:**
```
Light The Way
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/light-the-way

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/light-the-way.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/light-the-way.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by richardmundyiii**
Fixes #4014 

### What changes did you make and why did you make them ?

  - Changed img alt text
  - Alt before: 'Veteran returned from service to civilian life.'
  - Alt after: 'Light The Way'

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA (PST): 1:30 AM, Tues 3/14/23
Availability (PST): 12:30AM - 2AM, Tues 3/14/23

**Review by arcan9 — APPROVED** [review]
@richardmundyiii Great work! The requested changes were made in the correct document, branch is setup correctly, and the issue is properly linked. 

In terms of the PR documentation itself, I would suggest to:
- Indicate the "why" of your changes. Something as simple as "Changed img alt text to adhere to the Web Content Accessibility Guidelines (WCAG)" is okay.
- Explain why screenshots are not needed. It's straightforward why it's not needed here, but to follow the [Contributing instructions](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available), then include something like:
```
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Only alt text is changed. No visual changes to the website.
```

Overall, congrats on your good first issue!

**Comment by arcan9** [comment]
@richardmundyiii Forgot to note: I've added your PR to the Project Board (right hand side of this page). Please make sure to do so with future PRs!

**Review by t-will-gillis — APPROVED** [review]
Hey @richardmundyiii - Thanks for taking up this issue! @arcan9 made some great observations about the PR documentation that will be good to keep in mind for when you submit PRs in the future. For this issue, the from/to branches are correct, the change addresses the issue and the code is clean and correct. Great job!

**Pull request merged**
