### PR TITLE
Updated Hack for LA alt text on events page

### LINKED ISSUE #3306: Update Hack for LA Alt Text on Events Page: our-locations-content.html
### Overview

As developers we want to ensure that we ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). This issue addresses the alt text for the Hack for LA Website Project.

### Action Items

- [x] In the file `_includes/events-page/our-locations-content.html`, change [line 60](https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L60) of the alt text:

from
```
 <img id="mini-img" src="../assets/images/projects/website.png" alt="Hack for LA Website Project" /> 
```
to
```
 <img id="mini-img" src="../assets/images/projects/website.png" alt="" /> 
```

- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3132 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3132 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3132 
- [Events page](https://www.hackforla.org/events/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)
- Working on an Issue: 
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#24-claiming-an-issue

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/events-page/our-locations-content.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L60

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by angietechcafe**
Fixes #3306

### What changes did you make and why did you make them ?

  - Changed line 60 of alt text
  - Edited this change on a text editor
  - Filename is the same.

### CODE REVIEW

**Comment by lilyarj** [comment]
Availability: 2hrs
ETA: 7/15

**Review by lilyarj — APPROVED** [review]
All looks well, site runs as normal and the changes that were made follow what the issue asks! :)

**Comment by Wny-Duong** [comment]
Availability: 1 hr
ETA: Friday, 7/15

**Review by Wny-Duong — APPROVED** [review]
Changes match the request in the original issue. Good job!

**Pull request merged**
