### PR TITLE
update-engineering-information-4239

### LINKED ISSUE #4239: Update Engineering Community of Practice information to peer led
### Overview

The Communities of Practice - Engineering project card needs to be updated to reflect accurate team information.

### Action Items

- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `internal/communities/engineering.yml` file and find the `leadership-type` variable.
- [x] Update the description 
     - ***From***
     ```leadership-type: Mentor Led```
     - ***To***
     ```leadership-type: Peer Led```

### Resources/Instructions

- [engineering.yml](https://github.com/hackforla/website/blame/gh-pages/_data/internal/communities/engineering.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jeristella**
Fixes #4239 

### What changes did you make and why did you make them ?

  - Updated leadership-type from "Mentor Led" to "Peer Led" to reflect accurate team information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by mjh-projects** [comment]
Review ETA: 8 PM 3/30/23
Availability: After 6 PM Mon, Tues, Thur. - Sat.

**Comment by mjh-projects** [comment]
@jeristella 
Good job on this pull request
Pull request was done with the correct branch,
There is a linked issue.
Changes can be seen in the browser
File changes look good

In regards to the comments for your pull request it is a good idea not only to note the change but also why your making it.

**Review by mjh-projects — APPROVED** [review]
Changes look good.

**Comment by perlaroyerc** [comment]
Review ETA: EOD 3/29/23
Availability: 11-7 ET M-F

**Review by perlaroyerc — APPROVED** [review]
Good job working on this issue @jeristella! The issue is linked, the changes were made in the correct document, and the branches are set up properly.

I suggest a few minor edits:
- Add a brief description explaining "why" you made the changes, as it helps ensure the changes align with the project's goals and the HFLA guidelines.
- Include the Project Board to "Projects" you can reference this [wiki](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) if you need more clarity on how to do it.
- Remove the `<details>/<summary` and replace it with an explanation for no images like: `No visual changes made.`

Keep up the good work! :)

**Review by blulady — DISMISSED** [review]
Hey this looks almost perfect. I would just be particular and ask that you add a why to the initial comment on the PR (under Updated leadership-type to "Peer Led" in the next bullet point). I'll merge it after that's completed.

**Comment by jeristella** [comment]
Thanks for the feedback everyone! I have updated my comment above.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @jeristella It may not have been clear in the issue, but there are visual changes resulting from this PR, on https://www.hackforla.org/communities-of-practice.  Please update the PR "Visual Changes" section with "before" and "after" screenshots.  Also please clean up the blank bullet points.  When those are complete, click the re-review icon next to Sarah's and my name, or if you have trouble modifying the issue, message me.  

Thank you for your great work on this issue and I apologize for the confusion!

**Comment by adevlinb** [comment]
Review ETA: 5pm/pt - 6/6/23
Availability: M-F 4-5pm/pt

**Review by adevlinb — APPROVED** [review]
Excellent work @jeristella

a) The issue is accurately linked.
 b) The pull request is descriptive. 
c) The branches are setup correctly. 
d) The changes are Applicable, do not Break the website, and are Clean .
e) The changes can be seen in the browser and are as requested.
 f) The changes in the source code are as clean and concise as possible.

**Review by roslynwythe — APPROVED** [review]
Hi @jeristella since this is an urgent issue and the code change is correct, I've been advised to go ahead and approve/merge it.  Thank you for your work on this issue.

**Pull request merged**
