### PR TITLE
labels are added below description

### PR DESCRIPTION
**Pull request by vincentdang**
#4485

### What changes did you make?

I added labels to Issue Template: blank-issue-form-with-no-dependency

### Why did you make the changes (we will use this info to test)?
  
This what they requested.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]image

</details>

### CODE REVIEW

**Comment by JpadillaCoding** [comment]
eta: 7/19
availability: 7/16-7/20 8am- 5pm

**Comment by JpadillaCoding** [comment]
Hey Vincent, 

Thanks for taking up this issue. It looks like you added the labels correctly to the YML file and are merging the correct branches- from your local repo with the issue number to the gh pages branch.

Some changes that need to be made: 
- Please add the issue number to the pull request where it says "Fixes #replace_this_text_with_the_issue_number"
- Please copy/paste the following sections from the issue to this pull request "For PR Reviewers and Merge Team"(make sure to add the URL of the issue template ), "Link for Reviewers", and "For PM, Merge Team, or Tech Lead".

Thanks!

**Comment by one2code** [comment]
**ETA: 7/18/23**
**Availability:** 11PM EST

**Comment by roslynwythe** [comment]
Hi @JpadillaCoding thank you for your review comments, which are perfect.  However I think you may have added yourself as an assignee instead of a reviewer.

**Review by one2code — CHANGES_REQUESTED** [review]
In addition to @JpadillaCoding 's suggestion, I'd also suggest updating this part with the changes that you have made.

> Why did you make the changes (we will use this info to test)?
This what they requested.

I know it seems pedantic to be detailed about the changes, even if they're minor, but it's important to develop good PR etiquette early-on. Not just for HFLA projects, but for any potential future employers and OSS projects as well. By submitting well-documented & detailed PR's, it sets you up for success.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @vincentdang I believe that you pushed your issue branch to the hackforla/website repository, which is incorrect.  Please follow the instructions in [CONTRIBUTING.md Part 3 Pull Requests](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests) to push your issue branch to your fork of the website repository, and then remove update-addLabels#4485 from the hackforla repository.

**Review by JpadillaCoding — CHANGES_REQUESTED** [review]
Hey Vincent,

Thanks for taking up this issue. It looks like you added the labels correctly to the YML file and are merging the correct branches- from your local repo with the issue number to the gh pages branch.

Some changes that need to be made:

Please add the issue number to the pull request where it says "Fixes #replace_this_text_with_the_issue_number"
Please copy/paste the following sections from the issue to this pull request "For PR Reviewers and Merge Team"(make sure to add the URL of the issue template ), "Link for Reviewers", and "For PM, Merge Team, or Tech Lead".
Thanks!

**Review had to be remade since I didn't assign myself as a reviewer before commenting. Sorry!

**Comment by vincentdang** [comment]
@JpadillaCoding 


**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template
URL of the issue branch on the test Repository:  https://github.com/vincentdang/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-no-dependency.yml

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/blank-issue-form-with-no-dependency.yml`
- This issue is part of epic #4307

**Comment by JpadillaCoding** [comment]
Thanks for the update! The issue is linked and you have copied the requested sections along with the URL to view the labels. 
Also note that the forked repo on the URL that you linked is the branch you would request the PR from. 😃 

I will approve my review as you've changed what was requested, but the branch issue should still be addressed. Once done, please press the request re-review button for @roslynwythe

**Review by JpadillaCoding — APPROVED** [review]

**Review by one2code — APPROVED** [review]
All requested changes have been made to the PR, including the merge path and issue # in the PR form, and the file resolves issue #4485. Thank you for making all requested changes.

**Comment by LRenDO** [comment]
Hi @vincentdang! Popping over here to finish answering your question from #4485 about whether the issue is complete. I am still seeing the [branching issue](https://github.com/hackforla/website/pull/4953#pullrequestreview-1538204095) mentioned by Roslyn. I didn't see another pull request from your branch in your forked repository in the pull requests. Please let me know if I missed it and link it here so I can take a look.  Otherwise, a new pull request needs to be created for the `updateLabels#4485` branch on your forked repository. Again, feel free to ping me if you have questions!

**Comment by vincentdang** [comment]
> Hi @vincentdang! Popping over here to finish answering your question from #4485 about whether the issue is complete. I am still seeing the [branching issue](https://github.com/hackforla/website/pull/4953#pullrequestreview-1538204095) mentioned by Roslyn. I didn't see another pull request from your branch in your forked repository in the pull requests. Please let me know if I missed it and link it here so I can take a look. Otherwise, a new pull request needs to be created for the `updateLabels#4485` branch on your forked repository. Again, feel free to ping me if you have questions!

@LRenDO @roslynwythe 

I created a new pull request
https://github.com/hackforla/website/pull/5162

**Comment by LRenDO** [comment]
Closing this PR as branching was fixed and issue #4485 was resolved by PR #5162.

**Pull request closed without merging**
