### PR TITLE
Refactored join-us with contents of join-donate-card

### LINKED ISSUE #4455: Refactor/Remove join-donate-card component
### Dependency

- [x] #4565

### Overview

The large component `_includes/join-donate-card.html` has been replaced by smaller components, so its elements will be moved into `pages/join-us.html`, and the include file will be deleted. 

### Action Items

- [x] Open `_includes/join-donate-card.html` and `pages/join-us.html`
- [x] In `pages/join-us.html`, replace the line
```
{% include join-donate-card.html %}
```
with the contents of `_includes/join-donate-card.html`
- [x] Remove the file `_includes/join-donate-card.html`
- [x] Use git to add and commit the change (including the deletion)
- [x] Using docker, confirm that the local Join Us page matches the [Join Us webpage](https://hackforla.org/join)

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- Join Us [webpage](https://hackforla.org/join)
- This issue is part of Epic #4492

### PR DESCRIPTION
**Pull request by k-rewd**
Fixes #4455

### What changes did you make?
  - Replaced line '{% include join-donate-card.html %}' on pages/join-us.html with contents from _includes/join-donate-card.html

### Why did you make the changes (we will use this info to test)?
  - To refactor the donate-card component

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

no applicable visual changes to website

### CODE REVIEW

**Comment by freaky4wrld** [comment]
ETA: EOD 11/25
Availability: Evenings

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
Hey there @k-rewd in #4455, there's a specific instruction to delete the file `_includes/join-donate-card.html`. But your branch has that file, kindly delete the file and then **stage the changes with** `git add .` , then commit those changes.

After you've made the changes re-request me for reviewing, or ping me here.

**Comment by robertnjenga** [comment]
Review ETA:  11/25/2023
Availability: 10am - 5pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @k-rewd! Thanks for taking up the issue.
The branching was done correctly, you used correct branch to commit from and into.
You linked the issue.
As stated in the issue, you replaced the line {% include join-donate-card.html %} with the elements in _includes/join-donate-card.html. However, from the action items and as stated by @freaky4wrld, the _includes/join-donate-card.html file has to be removed.
After the changes are made you can re-request the review.

**Comment by k-rewd** [comment]
Hello @robertnjenga, @freaky4wrld. Kindly re-review changes. I pulled/merged the main branch before committing the changes to avoid any merge conflicts but I'm not sure if it worked out. Let me know what I can do. thank you!

**Review by robertnjenga — APPROVED** [review]
Hi @k-rewd 
Thanks for making the requested changes. The file _includes/join-donate-card.html has been deleted, and the Join Us page on my local machine matches the Join Us webpage.
Great job!

**Review by freaky4wrld — APPROVED** [review]
Great work there all the work assigned to you in the issue is done correctly
- the to/from branch looks good
- the changes specified are done correctly and are apt
- the issue linked is correct too
- no changes were find in the `join us` page
- the `file is correctly deleted` as well

Great work there, I approve this PR....... and amazing work by @k-rewd with the requested changes

**Review by t-will-gillis — APPROVED** [review]
Hey @k-rewd Great job on the issue, and great communication among you, @freaky4wrld , and @robertnjenga!

**Pull request merged**
