### PR TITLE
Added Mira Kinebuchi's github handle variable in home-unite-us.md

### LINKED ISSUE #7177: Add github-handle for Mira Kinebuchi in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Mira Kinebuchi
```
with
```
- name: Mira Kinebuchi
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by mSharifHub**
Fixes #7177 

### What changes did you make?
  -    Added github-handle for Mira Kinebuchi
  

### Why did you make the changes (we will use this info to test)?
  -    The change was made to prepare the project file for the future inclusion of GitHub handles in a standardized way, reducing redundancy.
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 -    No visual changes to the website

### CODE REVIEW

**Comment by 8alpreet** [comment]
Review ETA: EOD Tue Aug 20
Availability: Mon to Fri; 3 p.m. to 7 p.m.

- [x] Step 0: Is the pull request done with the correct branch?
- [x] Step 1: Is there a linked issue?
- [x] Step 2: Understand the linked issue.
- [x] Step 3: View the changes in the browser.
- [x] Step 4: Take a look at files changed tab.
- [x] Step 5: Check for anything else.
- [ ] Step 6: Approve the pull request.
- [ ] Step 7: Clean up your working repo.

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @mSharifHub,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- Branch is named correctly
- Only relevant lines of code were changed.
- You answered the "What.." and "Why.." sections well!

### Changes needed:
1. PR title
    - The current PR title does not accurately represent the changes. While the file mentioned was updated, I think the title could be more precise.
2. PR Comment
    - The first line in the comment is redundant, as the "What.." section has that information.

**Review by mmcclanahan — CHANGES_REQUESTED** [review]
Hey @mSharifHub!
Great job correctly linking the issue and explaining your what and why.

Like Balpreet mentioned, the first line in your PR comment can be removed and the PR name can be a bit more descriptive of what was updated. For instance "Added Mira Kinebuchi's github handle variable in home-unite-us.md".

Everything else looks great!

**Comment by minkang3** [comment]
ETA: EOD
Availability: 11-5 Weekdays

**Review by minkang3 — CHANGES_REQUESTED** [review]
Hi @mSharifHub,

I'll just touch on things that other reviewers have not mentioned.

- I think your branch name could be slightly more descriptive, you don't have to add that change for this PR but keep it in mind for your next one.
- In your PR, some of the bullet points are not formatted properly. Simply edit the PR to add spaces after every "-".

Just make the simple formatting change and rerequest the review.

**Comment by mSharifHub** [comment]
I do not know how descriptive more can I be ? Do i need to explain what is github handle for ? I dont get it. It has been over a week i have submitted. Over one line of code with a description from my git submission did no stop anyone from finding the issuse since I already have it under fixes. I do not see how productive this is but very counter productive

**Comment by 8alpreet** [comment]
@mSharifHub, @mmcclanahan gave you can example you could use; you could just copy paste that. Your changes resulted in an update to the file you mentioned but that was not your change nor the goal of the PR. Your change was adding the github-handle key. At minimum, the title should mention that. It seems you're having trouble with this, so I'll give you what my answer would be: Added github-handle for Mira Kinebuchi.

I understand it can be frustrating to wait. You're almost there, please update the title and I will approve.

**Comment by codyyjxn** [comment]
Review ETA: 8/26/24, 11:59pm PT
Availability: 9am-5pm M > F

**Review by codyyjxn — APPROVED** [review]
Great job on the branch name—it looks good! Just a quick note: for future reference, it would be helpful to include the specific change you made in the title. This can make it easier for everyone to quickly understand what the branch is about.

**Review by vorleakyek — APPROVED** [review]
It seems good now. Approved!

**Comment by t-will-gillis** [comment]
Hi @mSharifHub Just to make sure everyone is on the same page: there are changes requested above that have not been addressed yet, and the PR can not be merged until those requested changes have been addressed. 

Here are the two main items that appear to be outstanding:
- @mmcclanahan, @minkang3, and @8alpreet and mentioned editing the title of the PR and gave examples of what the title could be changed to, for example @mmcclanahan suggested: "Added Mira Kinebuchi's github handle variable in home-unite-us.md". Please make the change to the title. Select "edit" as shown below to make the edits
- @minkang3 requested that you add spaces between the hyphen and text in the description. Please add the space between the hyphen and the text in the two locations shown below.
- After you have made the changes above, please e-request reviews from the reviewers.

Screenshot 2024-09-01 151840

**Comment by mSharifHub** [comment]
sounds good. will fix now

**Comment by mSharifHub** [comment]
I have made changes. I added a tab to each as space

**Review by minkang3 — APPROVED** [review]
Looks good.

**Comment by mSharifHub** [comment]
🙏

**Review by codyyjxn — APPROVED** [review]
Great Work!

**Review by mmcclanahan — APPROVED** [review]

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @mSharifHub,

You missed the first of @t-will-gillis's bullet points; the PR title still needs to be changed.

**Review by 8alpreet — APPROVED** [review]

**Review by codyyjxn — APPROVED** [review]

**Pull request merged**
