### PR TITLE
Check dependabot version updates to move-closed-issue.yml 4824

### LINKED ISSUE #4824: Verify dependabot version updates to GHAs for move-closed-issues.yaml
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.
### Overview
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) has been identifying the packages/dependencies for which a more recent version is available, and for each it has created a PR detailing which files in our codebase use that package/dependency. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 
### Action Items
Refer to the [move-closed-issues.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/move-closed-issues.yaml) file and review with the version updates recommended by the dependabot.
Select:
  - [x] PASSES TEST #4734 \`uses: actions/github-script@v4\` with \`uses: actions/github-script@v6\`
  - [x] PASSES TEST #4735 \`uses: actions/checkout@v2\` with \`uses: actions/checkout@v3\`
Or:
  - [ ] FAILS: #4734. Do not update.
  - [ ] FAILS: #4735. Do not update.

Merge team:
- [x] Transfer results to #4815
### Resources/Instructions
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #4824 
### What changes did you make and why did you make them ?

  - Tested updating the package versions In the file `moved-closed-issues.yml` per the dependabot suggestions: 
    - Tested changing `uses: actions/github-script@v4` with `uses: actions/github-script@v6` per 4734
    - Tested changing `uses: actions/checkout@v2` with `uses: actions/checkout@v3`
    - Both changes passed successfully, issues are moved to either 'Done' or 'QA' columns upon closing as they are supposed to.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Changes effect GHAs only

### CODE REVIEW

**Comment by one2code** [comment]
**ETA:** 6/15/23

**Comment by mademarc** [comment]
Review ETA: 6/15/2023
Availability: 7:10PM

**Comment by one2code** [comment]
@t-will-gillis Can you further expound on the testing protocol? I pushed your branch up to my origin, switched my default branch to your branch, but I was not able to access or link to any project board to test which column a closed issue would be moved to, after being placed on the project board. I can see all of the script updates are correct, but I want to be able to test the issue correctly before approving.

**Comment by t-will-gillis** [comment]
Hi @one2code yes definitely, thanks for the message. 

If you haven’t already done this, you will want to set up a Project Board on your own repo- please see this [document](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit) and the [HfLA wiki pages](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions), especially starting at Tip 6 towards the bottom of the page. (FYI for future GHA testing you also might be able to use [Nektos](https://docs.google.com/document/d/1Ya-Al4k9i1Nu7pq2pc_0J2xxEfQ6mO8-kw0nxqeRMIc/edit) from your CLI. I don’t feel like Nektos is helpful for this particular action but it is good to know about.) 

Let me know if you run into any issues or would like to discuss further...

**Comment by one2code** [comment]
@t-will-gillis Thank you Will. @blulady shared some documentation links with me. I'll give it another go tomorrow, and if I run into any problems, I will reach out to you.

**Review by one2code — DISMISSED** [review]
After reading the documentation, I was able to successfully clone the project board and implement a secret token for testing. I can verify that new issues are correctly placed on the new issue approval column, and then when closed, they are moved to the QA column as intended. These changes brought forth by Dependabot had no breaking effects when tested, Therefore, I'm going to approve this pull request.

**Review by mademarc — DISMISSED** [review]
Hey @t-will-gillis  all the line from 10, 12 & 24 changes are done correctly.

**Review by ronaldpaek — DISMISSED** [review]
Everything looks good on my end, was able to fork it and simulate the GHA with Sarah today.

**Review by one2code — APPROVED** [review]

**Pull request merged**
