### PR TITLE
Homepage redesign

### LINKED ISSUE #2317: Develop Homepage Redesign
### Overview
We need to develop the new Homepage Redesign based on Figma file provided by design.

### Action Items

- [x] Develop the redesigned Home page
     - [x] Ensure applicable design system classes are applied throughout
     - [x] Add new icons on [credits page](https://www.hackforla.org/credits/)
     - [x] Move or create 'includes' files into home-page folder nested in the _includes folder
     - [x] Update program areas images
- [x] Develop mobile version of Home page

### Resources/Instructions
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15570%3A99833) (in pink rectangle)
[index.html](https://github.com/hackforla/website/blob/gh-pages/pages/index.html) - for home page architecture
[Credit folder](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) & [credit.yml template](https://github.com/hackforla/website/wiki/Credits-yml-file-template)
Homepage Redesign - #2057
Design mobile version of new homepage - #2213

### PR DESCRIPTION
**Pull request by arghmatey**
Fixes #2317

### What changes did you make and why did you make them ?
Developed the plans for our Homepage redesign based on the given Figma designs. At the time this draft was created, not all home page wins have been selected. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Screenshots will be updated ASAP.

<details>
<summary>Visuals before changes are applied</summary>

[Desktop](https://user-images.githubusercontent.com/40401149/144154168-e518bf8a-8e51-4b8a-b0bb-999ddbb96887.png)
[Mobile](https://user-images.githubusercontent.com/40401149/144154146-53eab06d-6788-495e-aada-939ea162197e.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

[Desktop](https://user-images.githubusercontent.com/40401149/144154190-da9bdca7-11bb-4960-9da3-7b132678ea08.png)
[Mobile](https://user-images.githubusercontent.com/40401149/144154195-867292e4-e034-4631-8d3f-f1bfb05dae14.png)

</details>

### CODE REVIEW

**Comment by arghmatey** [comment]
In order to display wins on the home page, best solution found is to add a "Homepage" column to the Wins-form (Responses) Google sheet. If that win has been selected to be featured, the value in said column should be changed to "TRUE".

Adding column to Wins-form (Responses), updating Google script to accommodate the added column, and running script for creation of PR updating _wins-data.

**Comment by arghmatey** [comment]
Development finished.

Need feature branch created, and new wins response edits pushed and this will be ready for review.

**Comment by macho-catt** [comment]
@arghmatey feature-homepage-launch branch has been created and the wins responses are in the github. Thanks!

**Comment by arghmatey** [comment]
Base branch updated to feature-homepage-launch.

**Comment by ExperimentsInHonesty** [comment]
@arghmatey Can you provide a screenshot of the new homepage.  If you don't already have the full page [screen shot chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en), please install to make it easier.

**Comment by arghmatey** [comment]
I've added before and after pictures of homepage. I've included both desktop and mobile.

**Comment by R-Tomas-Gonzalez** [comment]
Hi @arghmatey / Sarah!

First off, great job building out such a big task. @macho-catt and I had the chance to look over your code today and I really enjoyed getting to do that with him. The new homepage redesign looks great!

Here are notes and things for you to fix:
Files: 
   - **_sass/components/_home.scss** - Please use the $absolute_url variable on **line 30** in the background property for the .hero--header class similar to **line 49**
   - **assets/js/home.js** - Please utilize the _wins-data.json file and not the wins-data.json file for pulling in data. [Here](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json) is the file that should be used for any js utilized. wins-data.json will soon be deprecated.

Questions, notes, design fixes:
Sections:
   - **Program Areas** - This may be a question for design, but each program has a hover effect, and a pointer cursor as if to convey a link to its page. Is this the intention? If not, please remove any effect upon hover.
   - **Technology Section** - There is an underline under the word "technology" that cuts off at the "gy". In the design, the line goes underneath the entire word. Might be worth checking with design on...
   - **Ready to Join Us?** - Please make sure "Join Us?" is under "Ready to". Also, please leave the "?" without an underline - per the design.

Please let us know if you have any questions at all. Matt has also pinged you on slack concerning some merge conflicts. 

Thanks for your time! 

Cheers, 

- Tomas Gonzalez - [Slack DM](https://hackforla.slack.com/app_redirect?channel=U02DF1PPQUA)

**Comment by arghmatey** [comment]
@R-Tomas-Gonzalez - Thanks for the review and feedback! 

@macho-catt and I were able to resolve the merge conflicts. 

> * **_sass/components/_home.scss** - Please use the $absolute_url variable on **line 30** in the background property for the .hero--header class similar to **line 49**

^ Done! Thanks for catching this.

> * **assets/js/home.js** - Please utilize the _wins-data.json file and not the wins-data.json file for pulling in data. [Here](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json) is the file that should be used for any js utilized. wins-data.json will soon be deprecated.

^ I've updated the js file to utilize _wins-data.json and have refactored the js to display the chosen homepage wins at random.

> * **Program Areas** - This may be a question for design, but each program has a hover effect, and a pointer cursor as if to convey a link to its page. Is this the intention? If not, please remove any effect upon hover.

^ This hover effect is intentional as noted on the Figma design [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9477%3A88938). They should now link to the program area page with the corresponding area at the top.

> * **Technology Section** - There is an underline under the word "technology" that cuts off at the "gy". In the design, the line goes underneath the entire word. Might be worth checking with design on...

^ Since the last two letters have descenders, this seems unavoidable. I'll let Kristine know through slack. 

> * **Ready to Join Us?** - Please make sure "Join Us?" is under "Ready to". Also, please leave the "?" without an underline - per the design.

^ Condensed header, removed the "?" from link, and added inline styling to keep it red. 



Please let me know if you find any other changes or questions!

**Review by R-Tomas-Gonzalez — CHANGES_REQUESTED** [review]
Hi @arghmatey,

Thanks so much for all your hard work! Would you please mind changing these issues @macho-catt and I caught?

_Desktop View_
**Hero**: Hide the "Learn More" hyperlink until the about page is fixed. Commenting it out should be sufficient. (We'll make another issue once that page is done)

**Wins**: The hyperlink is linked incorrectly. It should link to hackforla.org/wins

_Mobile View_
**Header Nav**: Something strange is happening on the dev view for the nav bar. There is a weird grayish color on the hamburger button. And, when the dropdown menu is activated there is a tiny space between the header nav and the dropdown. There are two things to create a quick fix for them.
1. Change the main-header-content to be 40px. This will close the gap between the header and dropdown.
2. Please utilize the `$color-white` variable in the background color for the component utilizing the `burger-image` id. 

Thanks again,

- Tomas

**Comment by arghmatey** [comment]
Hey @R-Tomas-Gonzalez - 

I've removed the link leading to the About page, and the nav link leading there as well. I've also fixed the wins page link. 

For the hamburger nav: I did a deep dive and found I removed code from the _home.scss file that ```#burgerImage``` was using. I've applied the missing background color and margin to ```#burgerImage``` to resolve the issue. Photos of live site and localhost attached. 

[Live](https://user-images.githubusercontent.com/40401149/145562302-6400a3e4-d208-4e6e-addd-80766ab57620.png)

[Local](https://user-images.githubusercontent.com/40401149/145562148-53e2c4bc-265b-499c-9849-d20fd5c83f7e.png)

Please let me know if there's anything else that could be improved! Though just a heads up - I will be out of town next week. Thank you!

Sarah

**Review by R-Tomas-Gonzalez — APPROVED** [review]

**Comment by R-Tomas-Gonzalez** [comment]
> Hey @R-Tomas-Gonzalez -
> 
> I've removed the link leading to the About page, and the nav link leading there as well. I've also fixed the wins page link.
> 
> For the hamburger nav: I did a deep dive and found I removed code from the _home.scss file that `#burgerImage` was using. I've applied the missing background color and margin to `#burgerImage` to resolve the issue. Photos of live site and localhost attached.
> 
> [Live](https://user-images.githubusercontent.com/40401149/145562302-6400a3e4-d208-4e6e-addd-80766ab57620.png)
> 
> [Local](https://user-images.githubusercontent.com/40401149/145562148-53e2c4bc-265b-499c-9849-d20fd5c83f7e.png)
> 
> Please let me know if there's anything else that could be improved! Though just a heads up - I will be out of town next week. Thank you!
> 
> Sarah

This is great! Thanks again. Changes look good and I have nothing else at the moment. @macho-catt may you take a second look when you get the chance?

Cheers,

- Tomas

**Review by macho-catt — APPROVED** [review]
LGTM. Thanks for all your hard work on this!

**Pull request merged**
