### PR TITLE
Change alt text for building image on credit page

### LINKED ISSUE #1560: Change Alt Text for Building Image on Credit page
### Overview
Alt text for Building Image on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Team discussion concept illustration'

```diff
- alt: 'Image of Building'
+ alt: 'Team discussion concept illustration'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/building.yml#L10

### PR DESCRIPTION
**Pull request by lorenzejay**
Fixes #1560

### What changes did you make and why did you make them ?

  - Updated _data/credits/building.yml alt text as instructed on
 [issue 1560](https://github.com/hackforla/website/issues/1560)
  
Screen Shot 2021-07-14 at 6 24 49 AM
  - No visual Changes applied. Only 

### Screenshots of Proposed Changes Of The Website

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2021-07-14 at 6 31 07 AM

</details>

<details>
<summary>Visuals after changes are applied

</summary>
  
Screen Shot 2021-07-14 at 6 32 52 AM

</details>

### CODE REVIEW

**Comment by Aveline-art** [comment]
Hi @lorenzejay I noticed the PR is failing the checks. When you get to it, can you please reformat the top post using a [linking keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)? Thank you!

**Comment by lorenzejay** [comment]
Thank you,

Linking keyword has been added.

**Review by macho-catt — APPROVED** [review]
This looks good to me. Just a quick note, generally you don't have to post screenshots of code changes (it is actually not advised to do so), so for changes that don't affect how the frontend looks you should be fine just detailing what you did.
Otherwise, good job!

**Review by averdin2 — APPROVED** [review]
@lorenzejay Good job on this issue! One note I want to make is that I saw you requested a review from Martha. I don't believe she is on the team anymore. If you would like someone to review your issue, the best way is to reach out in the hfla-site Slack channel asking if someone can review your issue. The recommended reviewers on GitHub sometimes recommends members that are no longer active.

**Comment by lorenzejay** [comment]
> @lorenzejay Good job on this issue! One note I want to make is that I saw you requested a review from Martha. I don't believe she is on the team anymore. If you would like someone to review your issue, the best way is to reach out in the hfla-site Slack channel asking if someone can review your issue. The recommended reviewers on GitHub sometimes recommends members that are no longer active.

Thank you for the feedback and thank you for letting me know.

**Pull request merged**
