### PR TITLE
Remove unused alt-hero field from civic-tech-jobs.md project file #2925

### LINKED ISSUE #2925: Remove unused `alt-hero` field from civic-tech-jobs.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/civic-tech-jobs.md`, remove line 8 for the alt-hero
```
alt-hero: "Civic tech jobs hero image, for HfLA website projects page"
```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/civic-tech-jobs.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/civic-tech-jobs.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by palomasoltys**
Fixes #2925 

### What changes did you make and why did you make them ?

  - Removed unused alt-hero field from civic-tech-jobs.md project file (line 8)

### CODE REVIEW

**Comment by d-perez-8** [comment]
Review ETA: 6:30 PM 9/26/22
Availability: Tuesday-Thursday 9-11 am

**Review by d-perez-8 — APPROVED** [review]
This looks good, @palomasoltys! Thank you for your work. The issue was handled correctly, and the website does not break.
When issues become more difficult, please provide an explanation as to why the changes were made.

**Comment by tunglinn** [comment]
ETA: end of today
Availability: 1hr

**Review by tunglinn — APPROVED** [review]
Merge branches are correct. Only the changes in the issue are made. No visual change to the website and site does not break. Good work!

**Pull request merged**
