### PR TITLE
Removed img Closing Tag in Getting Started Page

### LINKED ISSUE #4397: img Tag Refactor: Getting Started page - `<p...><img... info-icon information.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<p class="github-sign-up-text"><img class="info-icon" src="assets/images/getting-started/information.png" alt="" />
```
to
```
<p class="github-sign-up-text"><img class="info-icon" src="assets/images/getting-started/information.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by eulloa10**
Fixes #4397

### What changes did you make and why did you make them ?

  - Changed img HTML tag ending with a slash () to an img tag without an ending slash () 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

image
</details>

### CODE REVIEW

**Comment by eulloa10** [comment]
Availability for this week: ~8hrs Tu-Fr
My estimated ETA for completing this issue: <30min

**Comment by Jaretzbalba** [comment]
Review ETA: EOD 04/05
Availability: 1 hour

**Review by Jaretzbalba — APPROVED** [review]
@eulloa10 I see that you were able to remove the img closing tag and everything looks to be good! Good job working on this issue!

**Review by RyanGehris — APPROVED** [review]
Great job working on your first issue! The changes you made are correct, and the page remained the same. Thank you for your work!

**Pull request merged**
