### PR TITLE
Edit hex orange colors to orange variables

### LINKED ISSUE #2198: Design System Audit: Swap colors with color variables: Oranges
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the orange colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (oranges)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, delete it from the files noted above.
- [ ] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L13-L17

<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  Search: hex color<br>
  Replace: color variable<br>
  files to include: ./<br>
  files to exclude: *.svg, _site, _colors.scss<br>
  Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  Click `Ok` to confirm replace
  
</details>

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similiar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #2198

### What changes did you make and why did you make them ?

  - Changed hex values for orange to their orange variables. This was to make the code more readable instead of deciphering hexadecimal. 
  - No need to delete color variables because they are all being used.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by Zak234** [comment]
ETA: Aug.17
Availability: Anytime

**Review by Zak234 — CHANGES_REQUESTED** [review]
I checked the repository and it looks like $color-chocolate is used in file color_styles.scss along with _about.scss and $color-orange is used in both color-styles.scss and _about.scss.

**Comment by d-perez-8** [comment]
@zak234 You're right. I only checked the colors using their hexadecimal, and not their variable name. Fixing it now.

**Review by luke-karis — APPROVED** [review]
LGTM! Thanks for working on this ticket

**Review by Zak234 — CHANGES_REQUESTED** [review]
Nvm

**Review by Zak234 — APPROVED** [review]
Everything looks good now. Great work!

**Pull request merged**
