### PR TITLE
Update Project Profile: LA TDM Calculator Add Parisa Jannatifard #7643

### LINKED ISSUE #7643: Update Project Profile: LA TDM Calculator Add Parisa Jannatifard
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Parisa Jannatifard
    github-handle: Parisajf
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05Q5D34ARZ
      github: https://github.com/Parisajf
    picture: https://avatars.githubusercontent.com/Parisajf
```
`(edit: slack ID U05PG72SL56 was changed to U05Q5D34ARZ)`
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM calculator page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by Sk-223**
Fixes #7643 

### What changes did you make?
- Find the leadership variable and add the following profile.
```
  -name: Parisa Jannatifard
    github-handle: Parisajf
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05Q5D34ARZ
      github: https://github.com/Parisajf
    picture: https://avatars.githubusercontent.com/Parisajf
```

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
Review ETA: 11/6/2024 Wednesday
Availability: 5-9 PM Weekdays (EDT)

**Review by siyunfeng — CHANGES_REQUESTED** [review]
Thank you for working on this issue, @Sk-223 !

- The branch you made the pull request from is correct
- The linked issue number is included
- The changes are correctly reflected on the LA TDM Calculator projects page

Improvements: 
- Name the branch with more specific details, such as `LA-TDM-calculator-add-parisa-jannatifard-7643`
- Provide more details to `What changes did you make?` and `Why did you make the changes (we will use this info to test)?`. Usually, the original issue should give some context for this.

Changes you need to make:
- [x] Address the questions posted by `HackforLABot` in the comments section of the original issue
- [x] Complete the `CodeQL Alerts` section
- [x] Provide the before-and-after screenshots of the website view instead of the code

Please re-request me to review and approve this PR once you make the changes. Feel free to reach out if you have any questions.

**Comment by Sk-223** [comment]
Hi @siyunfeng! Thank you for taking the time to review my request!
I'm having issues getting the screenshots of the before and after since I don't have permission with Docker. But I've renamed the branch, edited my response for the WHY of the issue, and answered the bot questions. What is the CodeQL Alerts?

**Comment by siyunfeng** [comment]
> Hi @siyunfeng! Thank you for taking the time to review my request! I'm having issues getting the screenshots of the before and after since I don't have permission with Docker. But I've renamed the branch, edited my response for the WHY of the issue, and answered the bot questions. What is the CodeQL Alerts?

Thanks for updating your availability and ETA in the original issue, @Sk-223 . 

Please fix your Docker issue so you can verify the changes you made by viewing the LA TDM calculator page in your local environment and the Hack for LA website. It's required from the original issue. 

I don't see the changes to the branch name or the response to `Why did you make the changes (we will use this info to test)?`, but these are suggestions and you don't need to rename your branch this time. 

The `CodeQL Alerts` section is below the `Why did you make the changes (we will use this info to test)?`. You'll need to follow the instructions and provide corresponding responses. 

Please check the boxes in `Changes you need to make:` from my request change comment and re-request me to review once you make the changes.

**Review by siyunfeng — DISMISSED** [review]
Nice job making the changes, @Sk-223 !

- Availability and ETA are posted in the original issue 
- `CodeQL Alerts` check is completed
- Before-and-after screenshots are modified and match the change

Thank you for your contribution! Keep it up!

**Comment by floydferrer** [comment]
Review ETA: 11/7/2024 Wednesday
Availability: 12-5 PM Weekdays (PST)

**Review by floydferrer — CHANGES_REQUESTED** [review]
Thank you for working on this issue, @Sk-223 !

• The branch you made the pull request from is correct
• The linked issue number is included

Improvements: The changes match the requested changes from the Issue #7643 , however, the member ID for Parisa that was provided on the issue is incorrect. Upon searching for Parisa Jannatifard on Slack, their member ID is actually U05Q5D34ARZ and therefore, the slack link should be: https://hackforla.slack.com/team/U05Q5D34ARZ

This will need to be adjusted on not only your PR, but possibly on the Issue itself. @t-will-gillis , can you advise if Issue #7643 needs to be corrected to provide the correct slack link?

**Review by A-Wu5 — COMMENTED** [review]
@Sk-223 Great job on this issue! I agree with the comment above. It does seem like the incorrect link was listed in the issue. Everything else looks good to me.

**Comment by Sk-223** [comment]
Hi @floydferrer! Thank you for taking the time to review this PR for me. Great catch on the ID. I've edited my PR to reflect the correct slack ID to U05Q5D34ARZ.
This was the path before:
Screenshot 2024-11-08 140704
And now after, the correct path to Parisa's slack:
Screenshot 2024-11-08 141313

**Comment by Sk-223** [comment]
Thank you @A-Wu5!

**Review by siyunfeng — APPROVED** [review]
Thank you for updating the correct Slack member ID, @Sk-223 !

The URLs work and everything looks good.

**Review by codyyjxn — APPROVED** [review]
@Sk-223 Thank you for taking on this issue. 
- The screenshots are helpful. 
- The branch name is correct. 
- The description is good.

Great job. Keep it up !

**Review by floydferrer — APPROVED** [review]
Thanks @Sk-223 for making these revisions!

Slack URL is now correct. PR #7706 is approved, but please flag in the issue request #7643 that the Github link provided is a broken link and you updated it accordingly.

**Comment by Sk-223** [comment]
Thank you for your help @floydferrer! I've flagged the discrepancy in the issue request. 

I do have one more question. Would you also be able to help me understand this next step?

- Once your pull request is merged, go to the initiating ER [3](https://github.com/hackforla/website/issues/7643#user-content-fn-3-9ff49d8d381f4deec22cf08eae376ac6)
  - Check off this issue under the _Dependency_ section
  - If all the issues in the _Dependency_ section are checked off, move initiating ER [3](https://github.com/hackforla/website/issues/7643#user-content-fn-3-9ff49d8d381f4deec22cf08eae376ac6) to **Questions / In Review** column and uncheck the **Dependency label**. 
  
Where is the _Dependency_ section in this issue to check off after adding Parisa to the leadership section? It also looks like the initiating ER is already in the **Questions / In Review** column, but the **Dependency label** has been re-added to the issue.

**Comment by t-will-gillis** [comment]
Hey @Sk-223 Great job! I want to note that you placed Parisa's Product Manager profile exactly where it should be: after the other Product Manager Ebi. I don't think the issue indicated this specifically so thank you for choosing the appropriate placement. 

Also kudos to @floydferrer for noticing that the Slack link needed to be corrected and @siyunfeng for the thorough comments!

**Comment by t-will-gillis** [comment]
@Sk-223 

> I do have one more question. Would you also be able to help me understand this next step?
> 
> - Once your pull request is merged, go to the initiating ER https://github.com/hackforla/website/issues/7643#user-content-fn-3-9ff49d8d381f4deec22cf08eae376ac6
>   - Check off this issue under the Dependency section
>   - If all the issues in the Dependency section are checked off, move initiating ER https://github.com/hackforla/website/issues/7643#user-content-fn-3-9ff49d8d381f4deec22cf08eae376ac6 to Questions / In Review column and uncheck the Dependency label.  

> Where is the Dependency section in this issue to check off after adding Parisa to the leadership section? It also looks like the initiating ER is already in the Questions / In Review column, but the Dependency label has been re-added to the issue.

The note about checking off the Dependency does not apply on this issue, so you can ignore this. The reference really means that if all of the issues[ shown here](https://github.com/hackforla/website/issues/7305#issuecomment-2442488145) are completed, then remove the `Dependency` label on 7305 and move it to "Questions/ In Review". But this is not the case on your issue...

**Pull request merged**
