### PR TITLE
Updating Lucky Parking project overview and leadership

### LINKED ISSUE #693: Lucky Parking Project Overview and Leadership Update
### Overview
The Lucky Parking Project Leadership was recently updated but several major changes have happened and need updating. Also, the project overview information needs to be updated.

- [ ] Project Overview info needs to be updated
- [ ] Project Leadership info needs to be updated

### Resources/Instructions
**Project Overview**
```
Project Description: Visualization of parking data to assist in understanding of the effects of parking policies on a neighborhood by neighborhood basis in the City of Los Angeles.

Open roles:
Data Analyst/Data Scientist (data cleaning)
Early UI/UX product development
Experienced Frontend Software Engineer (Mapbox experience)
Experienced Backend Software Engineer

Partner: Department of Neighborhood Empowerment 

Tools: Jupyter Notebooks, Google Colab, AWS, React-JS, Node-JS

Languages: Python, JavaScript, SQL
```
This includes all of the current team so previous info can be discarded (Title:Name \n Slack \n Git):
**Project Leadership**
``` 
Product Owner / Data Science Lead: Greg Pawin
https://app.slack.com/team/UUEQF3AJG
gregpawin

Full-Stack Developer Lead: Matthew Ginther
https://app.slack.com/team/U013GNM93U1
mg78856

Full-Stack Developer: David Kim
https://app.slack.com/team/U3MNUEQJ3
hyomiTheTech

Full-Stack Developer: Sam Guan
https://app.slack.com/team/U0173AHJ004
samreality4

```

### PR DESCRIPTION
**Pull request by daniellex0**
Fixes #693

### CODE REVIEW

**Comment by drubgrubby** [comment]
@daniellex0  - Good job.  All of the changes are in the right place, and clearly the process worked 'cause here I am looking at it. 

A couple of notes and questions from https://github.com/hackforla/website/issues/693#issue-683192758: 

1) According to the issue, the tools should be "Tools: Jupyter Notebooks, Google Colab, AWS, React-JS, Node-JS".  It looks like React-JS, and Node-JS didn't make the list. 

Screen Shot 2020-12-04 at 1 52 55 PM

2) Under "open roles" it says, "Experienced Frontend Software Engineer (Mapbox experience)".  Your change says just "Mapbox".  I think that your way reads better, but I want to make sure that that change was intentional, and that their original text didn't have a reason for being the way it was. 

3) I notice that "Languages: Python, JavaScript, SQL" isn't showing up on the card.  It seems not to be showing up on any cards, and not actually be a line on most on the .md cards.  When I ad the line it doesn't show up.  Do you know anything about why this is so?  I don't think this is part of your issue, but I'm just wondering if we need to make another issue about it, or at least see why it is the way it is.

**Comment by daniellex0** [comment]
@drubgrubby  Hi David, yes I'm realizing I should have explained these changes from the original issue in this PR so that people understand my reasoning, I will make sure to next time (thanks for catching them!)- 

Generally these changes were made based on the standards I saw in the other project cards, but more specifically:

1. I removed React-JS and Node-JS from "Tools" because I noticed in the other cards that these are always listed under "Technologies" as ReactJS and Node.js (so that's where I moved them). I also understand these are not generally considered tools (the typical "tools" listed are Hotjar, Google Analytics, AWS, etc).

2. Yes I intentionally changed "(Mapbox experience)" to just "(Mapbox)" because I was checking how other page cards showed this, and I followed Public Tree Map's example. However I'm realizing all of the page cards phrase their needs slightly differently so I'm now realizing maybe I shouldn't have changed this... also because perhaps just "Mapbox" might sound more intense than "Mapbox experience," which implies you don't have to be a total Mapbox expert but just have 'experience'... What do you think? Maybe I'll bring back 'experience'?

3. Yes I left out the "language" portion because in [this wiki page](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) about project md files, on the bottom, it says "Data for the **'languages'** and 'contributors' sections is pulled from the project's GitHub main repository using the GitHub API. In order to merge the GitHub API data into the finished card, you need to put the project's GitHub id in the 'identification field'. To find the id, go to the GitHub homepage for the project's main repository and search the page source for <meta name="name="octolytics-dimension-repository_id" content="#####">; the number in the 'content' field is the id you want."

But you're right, I just noticed that no language info is showing up for any of the projects... I wonder if something isn't working with the Github API..?

**Comment by drubgrubby** [comment]
@daniellex0 - Thanks for your response.  

For the record, I really appreciate you making the correct fix for this by putting those things under "Tools", not just the easy, literal fix of doing what the issue said.  Your work is very detailed and thoughtful, and it's really appreciated. 

As you suggested, it's a good idea to put your thinking in the PR so the person reviewing knows what they are looking at. 

on "1" you are exactly right.

on "2"  - I don't know the source of the original text. I usually assume that the text was intentional and specific, and if I think it should be something else, I tend to check with whomever wrote it in the first place to see if there's something I'm missing.  In this case, I'd suggest you do the same, either change it back to "mapbox experience", or, if you fee strongly about it being just "Mapbox", to find out where the original text came from. 

on "3" - I'm going to leave this open until Sunday just so we can remember to discuss the fact that the languages aren't showing up anywhere and see if it's something we need to make a new issue on.  But again, really good work on researching this and finding out where the languages data is supposed to be pulled from.  I don't think that the language thing is a reason not to merge this, however. 

Summary: Do something about #2, either change it back or find out if it's okay to keep it the way you have it.  We'll merge it on Sunday after we discuss the language thing.

**Comment by drubgrubby** [comment]
This PR was replaced by PR #841

**Pull request closed without merging**
