### PR TITLE
Adjust mobile alignment 4084

### LINKED ISSUE #4084: Adjust Alignment on Getting Started in Mobile View
### Overview
The Getting Started Page shows a step-by-step graphic that changes alignment when a user views it in a responsive viewport, so we need to adjust the alignment so that it looks clean and professional.

<details>
<summary>Getting Started page in desktop view</summary>

image

 </details>

<details>
<summary>Getting Started page in mobile view (1027px x 842px)</summary>

image

</details>

<details>
<summary>Getting Started page in mobile view (1010px x 842px)</summary>

image

</details>

### Action Items
- [x] View the [Getting Started](https://www.hackforla.org/getting-started) page in various viewport sizes to see how the text and graphics respond
- [x] Adjust the spacing between the text and the graphics in mobile view so the graphics remain in line with each other
  - [x] Consider bottom aligning the graphics so they do not move independently

OR
  - [ ] Find alternative ways to display the text and graphics in mobile views without changing the general look of it

### Resources/Instructions
- [_getting-started.scss](https://github.com/hackforla/website/blob/a8d86b813c914f75fffd0f649907c01fe57e5f4b/_sass/components/_getting-started-page.scss)
- [Working with Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

### PR DESCRIPTION
**Pull request by jch1013**
Fixes #4084

### What changes did you make and why did you make them ?

  - Aligns images to bottom of parent container for consistency

### Screenshots of Proposed Changes Of The Website

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
availability: Flexible
eta: EOD Wednesday 03/08/2023

**Comment by KazushiR** [comment]
@jch1013 I was reviewing your PR and noticed that no images are applied. Please provide an image of the changes you have made before and after the change. Also, in the original issue, the checkboxes aren't marked off. Please check off all items you have completed before going further.

**Comment by jch1013** [comment]
@KazushiR Forgot to delete the parentheses around the image link in the pull request, sorry! Everything should be working now. Sorry for the inconvenience

**Review by roslynwythe — APPROVED** [review]
Great work @jch1013 !  The branches are setup correctly, the PR is descriptive, the code change is clean and correct and works perfectly in the browser for all screen sizes.  I like your solution of making the step-links div a flex container.

**Review by KazushiR — APPROVED** [review]
@jch1013 I have inspected the different windows and it looks good!

**Pull request merged**
