### PR TITLE
Updated engage project's hero profile

### LINKED ISSUE #1923: Update Project Profile: Engage
### Overview
We need to update the Engage project's hero so that it will render properly.

### file locations
location of their project card: /gh-pages/_projects/engage.md
location of their current hero: image-hero: /gh-pages/assets/images/projects/engage-hero-2.jpeg

### Action Items
- [ ] replace their hero image with the one provided by
   - [ ]  downloading it, renaming it engage-hero.png and putting in the /gh-pages/assets/images/projects/ folder
   - [ ] change the reference to it in the engage.md file to be /assets/images/projects/engage-hero.png
   - [ ] delete the file /gh-pages/assets/images/projects/engage-hero-2.jpeg

### Resources
Link to the new image [here](https://drive.google.com/file/d/1P0m4tOu40c3hUfH6rNzoUsM6ubddYKzu/view?usp=sharing).

### PR DESCRIPTION
**Pull request by JasonUranta**
Fixes #1923

### What changes did you make and why did you make them?

  - Updated profile picture of hero to engage-hero.png
  - Deleted file: /gh-pages/assets/images/projects/engage-hero-2.jpeg
  - Changed the reference to it in the engage.md file to be /assets/images/projects/engage-hero.png

### Screenshots of Proposed Changes Of The Website  (if any, please 

<summary>Visuals before changes are applied</summary>

Screen Shot 2021-07-15 at 9 46 15 AM

<summary>Visuals after changes are applied</summary>
  
Screen Shot 2021-07-15 at 3 03 59 PM

</details>

### CODE REVIEW

**Review by macho-catt — APPROVED** [review]
I downloaded the branch into my environment, and it looks good to me. Good job!

**Review by mgodoy2023 — COMMENTED** [review]
Hi @JasonUranta, your changes to engage.md look good. I'm just wondering if you by any chance deleted the file engage-hero.jpg and why you did that. I see a direction in the issue to delete the file engage-hero-2.jpeg but not for the file engage-hero.jpg. Thanks!

**Comment by JasonUranta** [comment]
@mgodoy2023 I deleted the file at Bonnie's direction because there were multiple copies of the same file so I cleaned up the folder a bit.

**Review by mgodoy2023 — APPROVED** [review]
All changes look good to me. Nice job!

**Review by erikaBell — APPROVED** [review]
lgtm

**Pull request merged**
