### PR TITLE
Updates wr pr instructions 4934

### LINKED ISSUE #4934: Correction to verify dependabot suggested version update to GHA wr-pr-instructions
### Overview
Refer to #4830.  This issue concluded that `wr-pr-instructions.yml` fails when updating the version for #4734. After additional research it was noted that when `actions/github-script@` was updated to v5, one of the [api requests](https://github.com/actions/github-script#breaking-changes-in-v5) needed to change. Thus this change also needs to be made in v6. 

### Action Items

- [x] Confirm that the GHA will run as expected when updating `actions/github-script@v4` to `actions/github-script@v6` if the api request changes from:
```
github.issues.xxxxx
```
to:
```
github.rest.issues.xxxxx
```
- [x] This changes affects 1 file:
  - [x] [post-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/post-comment.js) at line 32.
  
Post merge:
- [ ] Transfer findings to #4815 and #4830

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #4934 
### What changes did you make?
  - Updated `actions/github-script@v4` to `actions/github-script@v6`
  - When updating the above, github REST methods requests needed to change from `github.issues` to `github.rest.issues`

### Why did you make the changes (we will use this info to test)?
  - Changes were made so that  `actions/github-script` version can be updated to latest

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visuals

### CODE REVIEW

**Comment by blulady** [comment]
eta: Saturday
avaialbility: Saturday

**Comment by ronaldpaek** [comment]
I can't get it to work on my project board. I think it's set up right, though.

CleanShot 2023-07-12 at 19 45 02@2x

**Comment by ronaldpaek** [comment]
I don't know weather to approve or not I will wait till I get feedback on what to do.

**Comment by t-will-gillis** [comment]
Thank you @ronaldpaek - I am closing this PR because I can't duplicate a successful run, there may be a glitch in the code. Apologies everyone.

**Comment by LRenDO** [comment]
@mademarc when you get a minute please add your availability and ETA for reviewing this PR. Thanks! 
EDIT: Apologies @mademarc . I just posted this right as @t-will-gillis closed this PR.
EDIT to the EDIT: @mademarc looks like Will sorted it out. Please do post your availability and ETA when you get a chance. Thanks!

**Comment by LRenDO** [comment]
@t-will-gillis I took a quick glance at this and was wondering if it was line 18 needing to be updated to `const artifacts = await github.rest.actions.listWorkflowRunArtifacts({` because of the version change updates as well. Also looks like potentially a similar issue for line 27 `var download = await github.rest.actions.downloadArtifact({`

**Comment by t-will-gillis** [comment]
@LRenDO - You are awesome! Yes, that is what was sinking it and it definitely is working now. Thanks so much. This is probably the fastest close-and-reopen a PR.

Did I mention you are awesome? ;-)

**Comment by LRenDO** [comment]
> @LRenDO - You are awesome! Yes, that is what was sinking it and it definitely is working now. Thanks so much. This is probably the fastest close-and-reopen a PR.
> 
> Did I mention you are awesome? ;-)

Lol. You're very kind. Just happened to be really excellent timing. Happy to help and Woohoo for fast fixes!

**Comment by ronaldpaek** [comment]
> @t-will-gillis I took a quick glance at this and was wondering if it was line 18 needing to be updated to `const artifacts = await github.rest.actions.listWorkflowRunArtifacts({` because of the version change updates as well. Also looks like potentially a similar issue for line 27 `var download = await github.rest.actions.downloadArtifact({`

awesome stuff

**Comment by ronaldpaek** [comment]
CleanShot 2023-07-12 at 23 39 53@2x

**Review by ronaldpaek — CHANGES_REQUESTED** [review]
Getting errors possibly need to make changes; not sure what changes are though.

**Comment by mademarc** [comment]
Review ETA: 7/13/2023
Availability: 7:13PM

**Review by mademarc — APPROVED** [review]
Hey @t-will-gillis the lines 13, 18, 27, 37, 50 on the yml file are done well as they should be and the same goes for the line 32 changes on the JS file was done as well  also @LRenDO  the availability and Reviewing on this PR is done.

**Review by ronaldpaek — APPROVED** [review]
I approve of the changes made 👍

**Pull request merged**
