### PR TITLE
Updating food oasis profile #3232

### LINKED ISSUE #3232: Update Project Profile: Food Oasis
### Overview
We'd like to update our current team members on this page: https://www.hackforla.org/projects/food-oasis

### Action Items
- [x] Please remove the people currently listed under Current Project Team on https://www.hackforla.org/projects/food-oasis
- [x] In [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1), please update the leadership with the following people:  

Name: John
GitHub handle: @entrotech
Role: Architect and Technology Lead
Slack ID: UFLDX9V19

Name: Bryan Wu
GitHub handle: @fancyham
Role: Design Lead
Slack ID: U01PG6RD0T1

Name: Jieun Ryu
GitHub handle: @ryu-jieun
Role: UX Researcher 
Slack ID: U02LL2DF4HL

Name: Gigi Patel
GitHub handle: @LIlinit
Role: UX Researcher
Slack ID: U02KZ8WSHHV

Name: Virginia Wu
GitHub handle: VirginiaWu11
Role: Full Stack Engineer
Slack ID: U02G7SBKSV7

Name: Seiko Igi
GitHub handle: @sei1122
Role: Product Designer
Slack ID: U02U55MQEQ7

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID: U9SCMTNK0

### Resources/Instructions
- [Food Oasis webpage](https://www.hackforla.org/projects/food-oasis)
- [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1)

### PR DESCRIPTION
**Pull request by lilyarj**
Fixes #3232

### What changes did you make and why did you make them ?

  - I updated the food oasis profile
  - deleted the leadership people and changed it to :
 Name: John
GitHub handle: @entrotech
Role: Architect and Technology Lead
Slack ID: UFLDX9V19

Name: Bryan Wu
GitHub handle: @fancyham
Role: Design Lead
Slack ID: U01PG6RD0T1

Name: Jieun Ryu
GitHub handle: @ryu-jieun
Role: UX Researcher
Slack ID: U02LL2DF4HL

Name: Gigi Patel
GitHub handle: @LIlinit
Role: UX Researcher
Slack ID: U02KZ8WSHHV

Name: Virginia Wu
GitHub handle: VirginiaWu11
Role: Full Stack Engineer
Slack ID: U02G7SBKSV7

Name: Seiko Igi
GitHub handle: @sei1122
Role: Product Designer
Slack ID: U02U55MQEQ7

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID: U9SCMTNK0 ( I actually used a different slack id, one that I got off slack for Hannah Zulueta because this one did not connect to an account) - This was the one I used (U01G7AH18J3)
- I made these changes so the Food Oasis could have an updated profile with the people who are currently on the leadership team and all of their roles were described accurately.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-06-26 at 10 51 39 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-06-26 at 10 50 44 AM

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 1 hour
ETA: 7/2, End of Day

**Comment by Wny-Duong** [comment]
Everything looks good! But, it seems like there might be problems with what the original issue was asking that could be addressed beyond Hannah's slack ID though. I'm not too sure if those are outside the scope of what you're meant to do though. It would be worth messaging Seiko (the original issue opener) over Slack in case those changes might be needed.

Namely:
1. John doesn't have a last name even though he was listed as John Darragh previously.
2. @GigiUxR looks like Gigi Patel's proper Github handle since @LIlinit doesn't lead to an actual account.

**Comment by sei1122** [comment]
Hi @Wny-Duong,
 I will check Namely, 1, and 2 and get back to you. 
 Thank you

**Comment by sei1122** [comment]
I checked in with John and Gigi.

1. Please use his full name. John Darragh
2. Please use  @GigiUxR   (she changed her handle name recently)

**Review by Wny-Duong — CHANGES_REQUESTED** [review]
Just needs a few changes before it's good to go.

Line 10:  
`- name: John Darragh`
Line 32:  
`github: "https://github.com/GigiUxR"`

**Review by Wny-Duong — APPROVED** [review]
Thank you for making the changes! Good work!

**Comment by tunglinn** [comment]
Availability: 1hr
ETA: end of 7/4

**Review by tunglinn — APPROVED** [review]
Merging to and from the right branch. All changes made from original issue. Also, added John's last name, updated Gigi's github, and corrected Hannah's slack. Site does not break. Looks good!

**Comment by yiminng** [comment]
Hi! We need help with updating some information 
### https://github.com/hackforla/food-oasis/issues/1269, who should I contact to work with to make changes?

**Pull request merged**
