### PR TITLE
removed alt-hero from line 8 in _projects/311-data.md file

### LINKED ISSUE #2892: Remove unused `alt-hero` field from 311-data.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/311-data.md`, remove line 8 for the alt-hero
```
alt-hero: 'Macbook Pro showing the 311 data app display. On the left of the screen shows input options and selections for dates, neighborhood council and various requests. On the right of the screen shows a map of LA county and its corresponding checked neighborhood council and requests.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/311-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/311-data.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by trishajjohnson**
Fixes #2892

### What changes did you make and why did you make them ?

  - Removed alt-hero on line 8 from _projects/311-data.md file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No changes to code made that reflect noticeable changes on the website; no images to show.

### CODE REVIEW

**Comment by answebdev** [comment]
Availability: 2 hours
Review ETA: 5/6/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@trishajjohnson Thank you for submitting your PR. For this issue, line 8 for the alt-hero needed to be removed for the file `_projects/311-data.md`, which I can see that you did. Also, there are no changes to the code that reflect noticeable changes on the website, so no images needed to be shown. I can see a linked issue, and you have also added this to the Project Board. Great job!

**Comment by harshitasao** [comment]
Availability: 2pm to 3pm (IST)
Review ETA: 07/05/2022

**Review by harshitasao — APPROVED** [review]
Hi @trishajjohnson, great job! The changes that you have made looks good to me.

**Pull request merged**
