### PR TITLE
Update project information for Access the Data

### LINKED ISSUE #4939: Update Project Profile: ACCESS THE DATA
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the project information for Access the Data so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find _projects/access-the-data.md file [^1] and make the following changes:
  - [x] Under the `leadership` section, 
    - [x] Remove
      ```
        - name: Bonnie Wolfe
          role: Agile Coach
          links:
            slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
            github: 'https://github.com/experimentsinhonesty'
          picture: https://avatars.githubusercontent.com/experimentsinhonesty
      ```
    - [x] Remove
      ```
        - name: Leslie Luk
          role: UX Writer
          links:
            slack: 'https://hackforla.slack.com/team/U04960088CV'
            github: 'https://github.com/lesUXW'
          picture: https://avatars.githubusercontent.com/lesUXW
      ```
    - [x] Add 
      ```
        - name: Jason Yung
          role: Project Manager
          links:
            slack: 'https://hackforla.slack.com/team/U059W9P96C8'
            github: 'https://github.com/merlinsmagic'
          picture: https://avatars.githubusercontent.com/merlinsmagic
      ```
- [x] Using Docker, verify the changes by checking the Access the Data page [^2] in mobile, tablet, and desktop views

### Resources/Instructions
- Original request copied into this comment for future reference: https://github.com/hackforla/website/issues/4939#issuecomment-1639105125
[^1]: Directory to find the page once you have it in your IDE: `_projects/access-the-data.md`
[^2]: Project page URL: https://www.hackforla.org/projects/access-the-data

### PR DESCRIPTION
**Pull request by aadilahmed**
Fixes #4939

### What changes did you make?
  - Removed Bonnie Wolf from the leadership section
  - Removed Leslie Luk from the leadership section
  - Added Jason Yung to the leadership section

### Why did you make the changes (we will use this info to test)?
  - To update the project information for Access the Data so that visitors to the website can find accurate and up-to-date information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

project-access-the-data-before-update

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
project-access-the-data-after-update

</details>

### CODE REVIEW

**Comment by kiwookim** [comment]
eta 7/24 EOD
availability 9-6pm everyday

**Review by kiwookim — APPROVED** [review]
@aadilahmed Great job! The branch is set up correctly and I can see in my local server that Current Project Team for Access The Data has been updated correctly. Thank you for taking this issue aadil!

**Comment by mshirk2** [comment]
ETA: 7/26 EOD
Availability: 7/26 10-5pm

**Review by mshirk2 — APPROVED** [review]
Nice work, Aadil

**Comment by LRenDO** [comment]
Hi @mademarc! If you still would like to review this request, please add your ETA and Availability when you get a minute.  If not, please remove yourself as a reviewer.  Thanks!

**Comment by mademarc** [comment]
Review ETA: 7/27/2023
Availability: 7:07PM

**Review by mademarc — APPROVED** [review]
Hey @aadilahmed the removal of code the lines 19-24 and lines 49-54  was done correctly and so was the adding of the code added on lines 49-54 as well and @LRenDO  the ETA and Review is done.

**Review by adrianang — APPROVED** [review]
Hi @aadilahmed! The branching is set up correctly, the corresponding issue is linked, the requested changes were made perfectly (removing Bonnie and Leslie, adding Jason), and the screenshots you had provided match up with my view of the Access the Data project page on Docker and looks as expected.

Thank you for taking up this issue! 🙌🏼

**Comment by mxajPrice** [comment]
Thanks, all!

**Pull request merged**
