### PR TITLE
Updating github handle for Eli Selkin in engage.md

### LINKED ISSUE #6731: Add github-handle for Eli Selkin in engage.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/engage.md` in the IDE
- [x] Replace:
```
- name: Eli Selkin
```
with
```
- name: Eli Selkin
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/engage

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by vanessasinam**
Fixes #6731 

### What changes did you make?
  - Replaced "- name: Eli Selkin" with "- name: Eli Selkin github-handle: "

### Why did you make the changes (we will use this info to test)?
  - The plan is to create a single variable github-handle to hold the github handle for each member of the leadership team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to website.

### CODE REVIEW

**Review by ha-bach — DISMISSED** [review]
Edit since I found the template for PR review and reviewing accordingly.

What works:
- branching was done correctly
- the issue number was listed
- code edit looks correct and only necessary code is added
- what and why in PR description are well-stated 

To review:
- PR title is not descriptive. I would describe what you changed rather than listing the issue being fixed
- Good work on listing "No visual changes to website." under "Visuals before/after changes are applied", but the collapsible bullet points could be removed as well, leaving just "No visual changes to website." under "Screenshots of Proposed Changes..."

Overall great work! Thank you for contributing.

**Comment by LRenDO** [comment]
Hi @del9ra! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.

**Comment by del9ra** [comment]
Review ETA: 10 PM 5/30/24
Availability: 1-3 PM Friday

**Review by del9ra — APPROVED** [review]
Hey @vanessasinam,
- The branching looks good.
- The issue is linked properly.
- I would make the title more descriptive
- Your explanation of the changes is clear.
- The project's webpage looks the same.
Nice work, and thanks for contributing to the website!

**Comment by jphamtv** [comment]
Hey @vanessasinam, @muninnhugin provided feedback that needs to be addressed. Please make those changes and re-request a review from them by clicking on the circular arrows icon next to their name. Thanks!
Screenshot 2024-05-30 at 11 30 51

**Comment by ha-bach** [comment]
@vanessasinam I previously reviewed this PR and edited it according to my understanding of how it should look: https://github.com/hackforla/website/pull/6900#pullrequestreview-2081512690.
When you make the changes just let me know and I can approve the PR!

**Comment by vanessasinam** [comment]
> @vanessasinam I previously reviewed this PR and edited it according to my understanding of how it should look: [#6900 (review)](https://github.com/hackforla/website/pull/6900#pullrequestreview-2081512690). When you make the changes just let me know and I can approve the PR!

I've just made the changes!

**Review by ha-bach — APPROVED** [review]
The PR title is descriptive and the visual changes description is clean!

Thank you for adding the changes, and for contributing!!

**Pull request merged**
