### PR TITLE
Removed unused GitHub icon

### LINKED ISSUE #6908: Remove unused GitHub icon
### Overview
We need to remove the unused file `assets/images/technologies-icons/github-icon-1.svg` in order to maintain clean file folders.  

### Action Items
- [x] Remove the file `assets/images/technologies-icons/github-icon-1.svg`
- [x] Add/Commit the change and proceed with a PR in the usual manner. 

### Resources/Instructions
- This issue resulted from #6903

### PR DESCRIPTION
**Pull request by ino-iosdev**
Fixes #6908 

### What changes did you make?
  - Removed the file `assets/images/technologies-icons/github-icon-1.svg`

### Why did you make the changes (we will use this info to test)?
  - Redundancy in code
  - Hard to change out the icon for any new icon
  - We need to maintain clean file folders

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
  - No visual change to the website
  
### Resources/Instructions
- This issue resulted from #6903

### CODE REVIEW

**Review by dcotelessa — APPROVED** [review]
Observed:
- Removed the file assets/images/technologies-icons/github-icon-1.svg
- Like the reasoning "Redundancy in code, Hard to change out the icon for any new icon"
- Ongoing maintenence of clean file folders
- Number in branch name

Great job!

**Comment by dcotelessa** [comment]
ETA: 10 min
Availability: 6/5-6/7 10-5pm

**Comment by mrodz** [comment]
ETA: 10 min
Availability: 6/5-6/8 9AM-7PM

**Comment by mrodz** [comment]
- Correct branch name and issue number included
- Good overview of the fix
- Deletion done correctly; there are no visual changes

Good stuff!

**Review by mrodz — APPROVED** [review]

**Pull request merged**
