### PR TITLE
Update Project Profile: Civic Tech Jobs (remove Ava Li)

### LINKED ISSUE #5376: Update Project Profile: Civic Tech Jobs (remove Ava Li)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] **_REMOVE_** the entirety of the entry:
```
  - name: Ava Li
    role: Development Lead
    links:
      slack: https://hackforla.slack.com/team/U01B73XGCKV
      github: https://github.com/Aveline-art
    picture: https://avatars.githubusercontent.com/Aveline-art
```
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by innith**
Fixes #5376 

### What changes did you make?
  - removed Ava Li from `_projects/civic-tech-jobs.md`

### Why did you make the changes (we will use this info to test)?
  - to update the project profiles of Civic Tech Jobs project page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by one2code** [comment]
**ETA:** 8/31/23

**Review by one2code — APPROVED** [review]
Excellent job on making the required changes to the _projects/civic-tech-jobs.md file. I've pulled down your branch and verified that the correct changes were successfully made without any side effects. Likewise, your issue branch is well-named with the correct issue, and you are merging into the correct branch. Good job on your first pull request!

**Comment by tesiahwang** [comment]
Review ETA: 9/1/2023
Availability: flexible

**Review by tesiahwang — APPROVED** [review]
Great job, @innith - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable & clean!

**Review by t-will-gillis — APPROVED** [review]
Hey @innith Great job- your branches are correct, you linked the issue, you describe the what and the why of your changes, your supply before and after screenshots, and your code is clean and edits only what is needed. I can confirm the results on Docker. Thanks for your work!

**Pull request merged**
