### PR TITLE
Add credit for Social Safety Net image for redesigned homepage #3416

### LINKED ISSUE #3416: Add credit for Social Safety Net image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the Credits webpage is up to date.

### Details
From the Homepage Redesign Credits in Figma, here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Social Safety Net credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `social-safety-net.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Social Safety Net
# The url where you can get direct access to the image on the provider site
title-link: https://unsplash.com/photos/lyiKExA4zQA
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Austin Kehmeier
# Name of the image database you found it on
provider: Unsplash
# Please give the general site URL, not the link to the image
provider-link: https://unsplash.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/social-safety-net.png
# Alt text for the image on the Credits page
alt: ''
# If an image was altered, please give the name of the HfLA designer that altered the image
altered-by: Kristine Eudey
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please do the following in issue #3130:
    - [ ] Move it to the New Issue Approval column
    - [ ] Remove the "Dependency" label from it
    - [ ] Add a "ready for dev lead" label to it    

### Resources/Instructions
- [Credits webpage](https://www.hackforla.org/credits/)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- This issue is tracked in the epic #3130.

### PR DESCRIPTION
**Pull request by SZwerling**
Fixes #3416 

### What changes did you make and why did you make them ?

  - Added a credit for a new image used in the redesigned version of the homepage so that the Credits webpage is up to date.
  - Added file social-safety-net.yml in _data/internal/credits
  - No screenshot taken.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
review ETA: sun 12/4
availability: sun 10-12

**Comment by esantiano** [comment]
ETA: 12/04
Availability: 3 Hours.

**Comment by Suman2795** [comment]
ETA: 5/12/2022
Availability: 3 hours

**Review by esantiano — APPROVED** [review]
Hi @SZwerling 

Good job adding the credit to the redesigned credits page. It looks good and is working on the responsive design mode options. Nicely done.

**Review by t-will-gillis — APPROVED** [review]
Hi @SZwerling - You added the `social-safety-net.yml` file to the correct folder. The new credit appears to load as intended om the `/credits` page in Docker. Great job!

**Review by Suman2795 — APPROVED** [review]
Hi @SZwerling ,
The PR goes into the correct branch and is created at the correct location. You made correct changes to the file.Good Job in handling this issue.

**Pull request merged**
