### PR TITLE
added link to privacy policy in the footer, line 7 of footer.html issue #3129

### LINKED ISSUE #3129: Footer menu: Add link to the Privacy Policy page
### Overview
As a stakeholder, I want a link to the [Privacy Policy page](https://www.hackforla.org/privacy-policy) in the footer menu so that visitors to the website can navigate to our Privacy Policy. 

### Action Items
- [ ] Add the link to the Privacy Policy page to the footer at the bottom of the website.
  - [ ] Currently, the footer shows:
      ```
      Credits | Site Map | Join Us
      ```
    Please add the privacy policy link in the following display order
      ```
      Credits | Site Map | Privacy Policy | Join Us
      ```
  - [ ] For "Privacy Policy" that you just added to the footer, it should link to `/privacy-policy`
- [ ] Check the change in the footer is seen throughout the website

### Resources/Instructions
- Related issue (comment): https://github.com/hackforla/website/issues/2555#issuecomment-1120350513
- Page you are changing is located here: _includes/footer.html

### PR DESCRIPTION
**Pull request by Unity7**
Fixes #3129

### What changes did you make and why did you make them ?

  -added the privacy policy link in the following display order Credits | Site Map | Privacy Policy | Join Us
  - Privacy Policy in footer, links to /privacy-policy
  - changes made for more accessibility to the privacy policy

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by giroz** [comment]
ETA: 9-25-22
Availability: 3 hours

**Comment by jdingeman** [comment]
Availability: Today all day
ETA: EOD 9/25/22

**Comment by neevliberman** [comment]
Availability: Next 2 hours
ETA: 9/25/22

**Review by neevliberman — APPROVED** [review]
The code looks great! I took a look through docker and it doesn't seem to break the website and the link seems to work as intended. Nice work!

**Review by giroz — APPROVED** [review]
Looks good! Added line 7 to the file

**Pull request merged**
