### PR TITLE
Refactored HTML to remove space slash for shield.png img element alt

### LINKED ISSUE #4399: img Tag Refactor: Getting Started page - `step-img-icon shield.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/shield.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/shield.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by Dprosser4**
Fixes #4399

### What changes did you make and why did you make them ?

-Changed an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

-Specific Tag Changed: ``

-File: pages/getting-started.html

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website. (Confirmed with Docker)

### CODE REVIEW

**Comment by kiwookim** [comment]
Review ETA: 5/30 2pm
Availability: 3-6 pm PST on weekdays

**Comment by one2code** [comment]
**ETA:** 5/27/23
**Availability:** 11PM -12am on 5/26/23, & 7-9PM 5/27/23

**Review by one2code — CHANGES_REQUESTED** [review]
I've reviewed the code in your pull request, and the code looks good. The requested change identified in issue #4399 was successfully made. However, I'm going to request that you edit your pull request report to include the specific  that was changed , e.g.  ``. This makes it easier for the reviewers to understand where and why the change was made.

**Comment by Dprosser4** [comment]
Thank You for your review. Changes to the pull request have been made.

**Review by one2code — APPROVED** [review]
Thank you @Dprosser4 for making the requested changes. Everything looks great. Congratulations on your first good issue!

**Review by kiwookim — APPROVED** [review]
Thanks, Dylan, for working on this issue and adding a link. I see that PR is done with the correct branch and see the changes to the image tag in getting-started.html. Everything looks great! Thank you.

**Pull request merged**
