### PR TITLE
Replace png with jpg image

### LINKED ISSUE #1341: Project Card Update - BallotNav
### Overview
We need to replace the current project card image with the image provided in the comment below

### Action Items

- [x] Replace the current image in the project file with the new image
- [x] Let BallotNav know that their issue can be closed: https://github.com/hackforla/ballotnav/issues/389

### Resources/Instructions
Current text in the project file: /assets/images/projects/ballot-nav.png
Replace with: /assets/images/projects/ballotnav.jpg
Where to find the project file: _projects/ballot-nav.md

### PR DESCRIPTION
**Pull request by RobertaFricker**
Fixes #1341 
Fixes #389 

Deleted ballot-nav.png and added ballotnav.jpg for issue 1341.
Added comment to ballotnav page, Issue 389 advising them change was completed, pull request added, and provided screenshot below:

image

### CODE REVIEW

**Review by averdin2 — CHANGES_REQUESTED** [review]
@RobertaFricker You forgot to make changes in the ballot-nav.md file. You need to replace the image path with the correct image. I'll add a screenshot of the image path so you know where. Just change the underlined part to ballotnav.jpg. You can find the file you need to change in _projects/ballot-nav.md. After you make the changes, just commit and push, and it should update the pull request.

image

**Review by averdin2 — APPROVED** [review]
Looks good!

**Comment by ExperimentsInHonesty** [comment]
@jbubar @RobertaFricker This is not working.  Here is how it looks on the site now.  Please revert and then figure out why
Screen Shot 2021-04-13 at 4 13 09 PM

**Comment by RobertaFricker** [comment]
It should be correct now per the following screenshot of the localhost:

image

**Pull request merged**
