### PR TITLE
Changed alt text for Westside Expunge Assist image 

### LINKED ISSUE #3316: Change alt text for Westside Expunge Assist image on events page
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Westside Expunge Assist location on [Events page](https://www.hackforla.org/events/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_includes/events-page/our-locations-content.html`, change the alt text so that
```
<img id="mini-img" src="../assets/images/projects/expunge-assist.png" alt="Expunge Assist" />
```
becomes
```
<img id="mini-img" src="../assets/images/projects/expunge-assist.png" alt="" />
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3132 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3132 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3132 
- [Events page](https://www.hackforla.org/events/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/events-page/our-locations-content.html`
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/our-locations-content.html

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by wendybarrios**
Fixes #3316

### What changes did you make and why did you make them ?

  - Changed alt text "Expunge Assist" to adhere to WCAG
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by Adastros** [comment]
Review ETA: 11PM 29NOV22
Availability: 9 - 11 PM 29NOV22

**Comment by jyaymie** [comment]
Review ETA: 11/29/22 2pm
Availability: 11/29/22 Flexible

**Review by jyaymie — APPROVED** [review]
Awesome job, @wendybarrios! You removed the alt text for the decorative image as described in the linked issue.

**Review by Adastros — APPROVED** [review]
Good job @wendybarrios! You removed the alt text successfully!

Don't forget to click the check-box(es) under the action items section for the issue as you complete them!

**Comment by blulady** [comment]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing alt text "Expunge Assist" to "". The code looks clean, only one commit and only one file changed.
Good job!!

**Pull request merged**
