### PR TITLE
Create dependabot.yml #3843

### LINKED ISSUE #3843: Create dependabot.yml file for dependabot to create pull requests
### Overview

GH Dependabot has been enabled to issue alerts for vulnerabilities and security. Therefore we need a configuration file, dependabot.yml, to create pull requests so that we maintain up to date security in our repo.

### Action Items

- [x] Read [configure dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [x] Read #3598 to understand HfLA's decision for implementing dependabot
  - [x] See associated [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- [x] Create a dependabot.yml file in the [.github](https://github.com/hackforla/website/tree/gh-pages/.github) and configure the file as per the instructions given in 1st link

### Resources/Instructions

- [Enabling Dependabot Version Updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [Configuration Options for Dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- ER for Decision Record: https://github.com/hackforla/website/issues/3598
- [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- See previous work done here: #4102

### PR DESCRIPTION
**Pull request by one2code**
Fixes #3843 

### What changes did you make and why did you make them ?

Created a dependabot configuration file to handle version and security updates for HackForLA's NPM packages and Github Actions on the website repository.

### CODE REVIEW

**Review by blulady — APPROVED** [review]

**Review by blulady — CHANGES_REQUESTED** [review]
Not actually requesting changes just revoking approval after using this pr for testing unrelated to this pr

**Comment by LOSjr4** [comment]
Availability: weekdays 9AM-1PM
ETA: 5/22 1PM

**Review by LOSjr4 — APPROVED** [review]
After reading the three references listed in issue #3843 , I do believe @one2code has used the proper format for a dependabot yaml file.
I unsuccessfully attempted to test this addition in GitHub through the Insights>Dependecy Graph>Dependabot section of GitHub. I also tried switching branches on GitHub from gh-pages to create-dependabot.yml-#3843, however clicking the Insights tab automatically switches me back to the gh-pages default branch, so I wasn't able to test further. I assume until it is fully merged.
Again, the format looks good and I saw a comment that @blulady saw the dependabot create PR's in her repo and I trust her, so I approve.
I was curious about one thing @one2code. In the documentation, dependabot appears to be compatible with Docker, but I saw you add then delete the docker section in the YAML file. What the reason for that outcome?

**Comment by one2code** [comment]
@LOSjr4 The initial reason for adding Docker to the config file, was to make the file 1:1 with a previous config file, for troubleshooting purposes related to the Dependabot not firing correctly during testing on my fork. After this issue was resolved, Docker was removed from the config because it is not needed to resolve the actions outlined in this issue. In order for Docker to be added to this config file and operate correctly in the future, there would have to be two separate issues created, or one larger complexity issue.

Here's a reference to what is required to config Docker, and what is updated. It operates quite a bit differently than npm or Github Actions.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#docker

**Review by blulady — APPROVED** [review]

**Pull request merged**
