### PR TITLE
Refactor div to resolve linter error –– about-card-partners.html

### LINKED ISSUE #5287: Refactor HTML to resolve linter error: _includes/about-page/about-card-partners.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-partners.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about'>
```
to
```
<div class="card-primary page-card-lg page-card--about">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-partners.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by homeroochoa47**
Fixes #5287

### What changes did you make?
  - Refactored the outer-most div to include double quotes instead of single quotes

### Why did you make the changes (we will use this info to test)?
  -Resolves the linter error "Value of attribute [class] must be in double quotes"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes were made

### CODE REVIEW

**Comment by homeroochoa47** [comment]
Thanks @Vinny02 and @adrianang for the feedback on my previous PR!

**Comment by wongstephen** [comment]
Availability 8/29 3p-5p PST
ETA EOD 8/29

**Comment by mshirk2** [comment]
Review ETA: 5pm 8/30
Availability: Weekdays 10-5pm

**Comment by MattChau01** [comment]
Availability: weekday evening
ETA: by end of day Friday

**Comment by wongstephen** [comment]
@homeroochoa47 great job on your 'good first issue'. You made the correct code change, which checks out fine in the browser, and you setup the branches correctly and described your work in the PR. Thank you!

**Review by wongstephen — APPROVED** [review]
@homeroochoa47 great job on your 'good first issue'. You made the correct code change, which checks out fine in the browser, and you setup the branches correctly and described your work in the PR. Thank you!

**Review by mshirk2 — APPROVED** [review]
Branching is set up correctly, the issue is linked, PR describes the solution well, and the changes to the quotes have been made. Great work @homeroochoa47!

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5287 was properly referenced. ✅ 
- The specified class on line 1 was correctly adjusted to double quotes as specified. ✅ 

Good fix @homeroochoa47 !

**Review by t-will-gillis — APPROVED** [review]
Hey @homeroochoa47 Great job on your first issue- Branches are correct, the orig. issue is linked, the description covers the what and why, and your code is clean and changes only what needs to be changed. 
Thanks for your work!

**Pull request merged**
