### PR TITLE
Update Project Profile - MJ Shelton

### LINKED ISSUE #5181: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: MJ Shelton
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U04UG4UQE8G
      github: https://github.com/mjshelton12
    picture: https://avatars.githubusercontent.com/mjshelton12
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by tesiahwang**
Fixes #5181

### What changes did you make?
  - Removed MJ Shelton from current project team leadership

### Why did you make the changes (we will use this info to test)?
  -  Keep project information up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-08-29 at 11 25 30 PM

</details> 
<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2023-08-29 at 11 24 36 PM

</details>

### CODE REVIEW

**Comment by Jmmcclo2023** [comment]
Availability: 4pm-6pm Daily 
ETA: 8/31

**Review by Jmmcclo2023 — APPROVED** [review]
Good job with the pull request Tesia! Everything looks good! 
- The pull request contains the correct branch
- The correct issue is linked in the post.
- The post contains before & after screenshots are applicable to the issue 
- The screenshots correctly show the issue's changes.
- All changes are in the correct file.
- The source code looks good.
- All applicable action items are completed for the issue.
- The comments in your pull request post are written well.

Well Done!

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 8/31/23
Availability: 1-3 PM everyday

**Comment by ortegaa32** [comment]
- Pull request contains correct branch
- Correct issue linked in post
- Changes don't appear to break the website
- Screenshots correctly show website before and after changes
- Changes made in correct file and source code looks good

Everything looks good @tesiahwang. Great job!

**Review by ortegaa32 — APPROVED** [review]

**Pull request merged**
