### PR TITLE
Update civic-tech-index.md

### LINKED ISSUE #684: Update to Civic Tech Index Page
### Overview
Please replace Arun as Product Manager with myself.

### Action Items
Please change **from**:
  - name: Arun Prakash
    role: Product Manager
    links:
      slack: 'https://app.slack.com/team/U015GPCKUFK'
      github: 'https://github.com/arunprakash87'
    picture: https://avatars.githubusercontent.com/arunprakash87

**To**:
  - name: Jonathan Sachsman
    role: Product Manager
    links:
      slack: 'https://app.slack.com/team/U018CSDL5FZ'
      github: 'https://github.com/jsachsman'
    picture: https://avatars.githubusercontent.com/jsachsman

### Resources/Instructions
https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/civic-tech-index.md

### PR DESCRIPTION
**Pull request by ghost**
Fixes: #684

Replace Arun Prakash with Jonathan Sachsman as Product Manager for Civic Tech Index, including his Slack, GitHub, and GitHub picture links.

The change in quotes for the rest of the document was automatic from a VS Code extension.

### CODE REVIEW

**Comment by jbubar** [comment]
The pull request looks great. I ran it on my machine and here is what it looks like. Great job Ethan. One thing I would like to mention, to echo Kian's point on the credits page issue (https://github.com/hackforla/website/pull/685#issuecomment-680407426), I think that you did this on the hack4la repo rather than your own fork of the repo. Hit me up if you would like me to clarify
screencapture-0-0-0-0-4000-projects-civic-tech-index-2020-09-02-15_21_04

**Comment by jbubar** [comment]
@KianBadie would you like to look this over and merge the pull request?

**Review by KianBadie — COMMENTED** [review]
So everything looks good and works, nice job Ethan :+1: . Just curious, was there a reason for the single to double quote change? It looks like it was intentional so I'm guessing there was some motivation.

Also, like @jbubar pointed out, I think it is very important that after this issue to start working on tasks on your own fork. I think it can reduce the amount of possibilities of things messing up on the main site. Like accidentally pushing to the wrong branch is a simple mistake. However, if that simple mistake happens on the fork it can cause a little bit of a scramble.

**Edit**: Also, I feel like just to have a consistent standard, would you mind changing it back to single quotes? I did a quick search and all files except food-oasis use single quotes. It doesn't make a difference in terms of results, but I think it would be a good practice to keep to a standard of sorts, even though this isn't a official standard but more so a standard by majority.

**Comment by KianBadie** [comment]
@ethanh256 @ExperimentsInHonesty since the update that @ethanh256 added last night, does it need another visual confirmation or can it be merged?

**Comment by KianBadie** [comment]
Going to merge. I'm assuming since it was a small addition that was made (@ExperimentsInHonesty 's role changing from Acting PM (Project looking for a new PM) -> Technical Product Manager) it does not need another visual confirmation. Everything looks good and links go to the right place. Nice job @ethanh256

**Pull request merged**
