### PR TITLE
Changed Project Title in website.md

### LINKED ISSUE #4514: Change "HackforLA.org" project title to enable proper screen reader pronunciation
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  Screen readers do not prounounce "Hackforla" properly, therefore in this issue we will rename the project "Hack for LA website"

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `title` variable. 
- [x] Change the value of the `title` variable from 
`hackforla.org` 
to 
`Hack for LA Site`
- [x] Do not change any other instances of `hackforla.org`.  
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) and on the [Website Project Page](https://www.hackforla.org/projects/website).  The location of the modified text is shown the screenshots in the Resources section below.  

### Resources/Instructions
<details><summary>Display of the project title on the Current Projects page (circled)</summary>

image

</details> 
<details><summary>Display of the project title on the Website Project page (circled)</summary>

image

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Website Project Page](https://www.hackforla.org/projects/website)
- [Hack for LA Current Projects Page](https://www.hackforla.org/projects)

### PR DESCRIPTION
**Pull request by Abrosss**
Fixes #4514 

### What changes did you make and why did you make them ?

  - Changed 'Hackforla.org Website' Project Title to 'Hack for LA Site' in website.md 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals on the Current Projects and Website Project pages before changes are applied</summary>

image

image

</details>

<details>
<summary>Visuals on the Current Projects and Website Project pages after changes are applied</summary>

image
image
  

</details>

### CODE REVIEW

**Comment by one2code** [comment]
**ETA:** 6/12/23

**Review by one2code — CHANGES_REQUESTED** [review]
@Abrosss I've reviewed the changes that you have made for issue #4514, and can verify that the requested merge is into the correct branch, and that the changes you have made to the value in 'title' are correct. I've also verified that the correct title value is displayed during testing in Docker when visiting `https://www.hackforla.org/projects`  & `https://www.hackforla.org/projects/website ' I'm going to request that you check off all of the boxes in issue #4514 before I submit my approval on the pull request, to ensure completeness.

**Comment by Abrosss** [comment]
Alright! Just did it, thank you @one2code

**Review by one2code — APPROVED** [review]
Excellent job on your first pull request @Abrosss, and thank you for taking the time to check off all of the boxes in the issue.

**Comment by steven-positive-tran** [comment]
ETA: 6/14/23

**Review by steven-positive-tran — APPROVED** [review]
Changes look good on my machine. Branches are directed correctly and the code change are in line with the issue that was presented.

Thank you for taking up this issue for hack for la and good job.

**Comment by graycodesnu** [comment]
ETA: Evening of 6/14
Availability: 6/14-6/15

**Review by graycodesnu — APPROVED** [review]
Hi, @Abrosss! Great job working this issue. You committed changes to and from the correct branches, made the necessary changes to the codebase (which runs on my local machine with no issues), and your pull request looks good. Changes approved. Thank you!

**Comment by drakenguyen4000** [comment]
Hi @Abrosss, good work!  Code was changed properly.

**Pull request merged**
