### PR TITLE
Edit alt text for Engage image

### LINKED ISSUE #3278: Update alt text for Engage project image on the Events page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Engage project image on the [Events page](https://www.hackforla.org/events/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/events-page/our-locations-content.html`, change the alt text on [line 11](https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L11):

from
```
<img id="mini-img" src="../assets/images/projects/engage-logo.png" alt="Engage Project" />
```
to
```
<img id="mini-img" src="../assets/images/projects/engage-logo.png" alt="" />
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3132 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3132 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3132 
- [Events page](https://www.hackforla.org/events/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/events-page/our-locations-content.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/events-page/our-locations-content.html#L11

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by str-xjua24**
Fixes #3278

### What changes did you make and why did you make them ?

  -Edit alt text for engage image on events page to adhere to WCAG

### CODE REVIEW

**Comment by giroz** [comment]
ETA: 10-31-22
Availability: 2 hours

**Comment by gstemmann** [comment]
ETA: 10-31-22
Availability: 6 hours

**Review by gstemmann — APPROVED** [review]
Looks like you properly changed the alt text on line 11 of _includes/events-page/our-locations-content.html and you removed the "Engage Project"
You also properly pushed your branch to the correct repo to be ready to be merged!
Awesome Job.

**Review by giroz — APPROVED** [review]
Good job. Deletion of Engage Project

**Comment by arpitapandya** [comment]
ETA: EOD 2022-10-31
Availability: 15 minutes

**Review by arpitapandya — APPROVED** [review]
Changes are correct! Great job! @str-xjua24

**Pull request merged**
