### PR TITLE
Changed the status of 100-automation

### LINKED ISSUE #3892: Mark 100 Automations project as On Hold
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the 100 Automations project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [x] In `_projects/100-automations.md`, change the status for 100 Automations from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [x] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [100 Automations page](https://www.hackforla.org/projects/100-automations)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/100-automations.md`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, 100 Automations project page](https://www.hackforla.org/projects/100-automations)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md?plain=1
- This issue is part of an epic: #3891

### PR DESCRIPTION
**Pull request by KazushiR**
Fixes #3892

### What changes did you make and why did you make them ?

  - On the project 100-automations, the status was set to active.
  - Changed the project from hactive to on hold.
  - The displayed item now shows as on hold on the status in the project itself and the project card.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image

</details>

### CODE REVIEW

**Comment by Adastros** [comment]
Review Availability (PST): 9-11 PM Monday - Thursday
Review ETA: 10:30 PM 30JAN23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @KazushiR, good job on changing the status of the 100-automations project from "active" to "On Hold". The changes are reflected on the website, and the 100-automation project filters properly by status on the home and project pages of the website.

Could you update the following before I approve it?

1. In issue #3892, don't forget to check the task list (check boxes) as you complete the issue. This helps indicate which parts of the issue were completed or needs to be completed.
2. In addition to the images you added, could you add one more before and after image of the 100-automations card from either the home or project page of the website? It can be found under the "Current Projects" section of either page. 
3. Could you clarify what changes were made and why? It's a little confusing but understandable. Could you also remove the empty bullet from the pull request comment? This helps keep the comment organized and clean.

**Comment by KazushiR** [comment]
> Hi @KazushiR, good job on changing the status of the 100-automations project from "active" to "On Hold". The changes are reflected on the website, and the 100-automation project filters properly by status on the home and project pages of the website.
> 
> Could you update the following before I approve it?
> 
> 1. In issue #3892, don't forget to check the task list (check boxes) as you complete the issue. This helps indicate which parts of the issue were completed or needs to be completed.
> 2. In addition to the images you added, could you add one more before and after image of the 100-automations card from either the home or project page of the website? It can be found under the "Current Projects" section of either page.
> 3. Could you clarify what changes were made and why? It's a little confusing but understandable. Could you also remove the empty bullet from the pull request comment? This helps keep the comment organized and clean.

Hello @Adastros ,

I have completed the requested changes. Hopefully the bullet points are a bit more descriptive. I have updated the picture as well. Please let me know if there are anymore issues with this pull request.

**Comment by MattPereira** [comment]
Review Availability (PST): during live meeting
Review ETA: during live meeting

**Review by MattPereira — APPROVED** [review]
Awesome job on this one @KazushiR ! :+1: 

I appreciate your speedy response to the changes requested by Danny!

**Comment by KazushiR** [comment]
> Awesome job on this PR @KazushiR ! 👍

Thank you. You mentioned a live review. Just to clarify, is the live review for me to attend?

**Comment by KazushiR** [comment]
> Awesome job on this PR @Kazushi

**Review by Adastros — APPROVED** [review]
Thanks for implementing the updates @KazushiR! Everything looks good on my end.

**Pull request merged**
