### PR TITLE
Refactor img tag 

### LINKED ISSUE #5703: Refactor img tag in CONTRIBUTING.md Section 3.1.b
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE,  open `CONTRIBUTING.md` and navigate to Section 3.1.b
- [x] Replace
```
<img src="https://user-images.githubusercontent.com/21162229/137709888-77ccfd63-3921-4978-9fc0-6fbd703683b8.jpg" />
```
with
```
<img src="https://user-images.githubusercontent.com/21162229/137709888-77ccfd63-3921-4978-9fc0-6fbd703683b8.jpg">
```
- [x] With CONTRIBUTING.md still open, make a note of the location of the replaced content, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Make sure that the appearance of the refactored image is unchanged.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

### PR DESCRIPTION
**Pull request by kezzaam**
Fixes #5703

### What changes did you make?
  - changed an img HTML tag ending with a slash () to an img tag without an ending slash () - line 812, CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
  - so that the codebase is consistent with how we use img HTML tags

  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/kezzaam/website/blob/refactor-img-tag-5703/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website 
- no visual changes
<details>
<summary>The section with the image is 3.1.b</summary>
Screenshot 2023-10-14 at 10 35 27 AM
</details>

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: 6 PM 10/14/23
Availability: 12-6 PM Sunday

**Comment by meru-a** [comment]
Review ETA: 10/15 EOD
Availability: 12-6 PM weekends

**Review by KyleA99 — APPROVED** [review]
Changes correctly implemented.  Looks good @kezzaam

**Comment by meru-a** [comment]
Good job, @kezzaam! Everything looks as expected, approved.

**Review by meru-a — APPROVED** [review]

**Pull request merged**
