### PR TITLE
Update env impact yml 3362

### PR DESCRIPTION
**Pull request by RobenusW**
Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  - changed "content: Image" to "content-type: image"
  -deleted "type: icon"
  - we changed for clarity reasons and to get rid of redundancy

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Zak234** [comment]
@RobenusW You need to link the issue where it says, "Fixes #replace_this_text_with_the_issue_number"

**Comment by blulady** [comment]
> @RobenusW You need to link the issue where it says, "Fixes #replace_this_text_with_the_issue_number"

Sorry. I should have been following the [contributor's](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) guide when we were walking through[ this](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests).

**Comment by Zak234** [comment]
ETA: July 26th
Availability: Anytime

**Comment by BeckettOBrien** [comment]
Availability: 5 Hours
ETA: EOD 2022-07-26

**Review by Zak234 — CHANGES_REQUESTED** [review]
The I in Image is supposed to be under-case.

**Comment by blulady** [comment]
@RobenusW Please reach out to us if you are still working on this issue. If we don't hear back from you by August 18th, we will assume you are no longer working on it.

**Comment by blulady** [comment]
> @RobenusW Please reach out to us if you are still working on this issue. If we don't hear back from you by August 18th, we will assume you are no longer working on it.

@RobenusW today's the day, I'll give you until the end of the day and then I'll close this request.

**Comment by blulady** [comment]
Robenus informed me that he will be taking a break for the semester.

**Pull request closed without merging**
