### PR TITLE
Added GitHub handle for Shawn Duenas

### LINKED ISSUE #6719: Add github-handle for Shawn Duenas in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Shawn Duenas
```
with
```
- name: Shawn Duenas
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by cflemmonds**
Fixes #6719 

### What changes did you make?
  - Added a single variable of `github-handle` after team member's name

### Why did you make the changes (we will use this info to test)?
  - This variable will be used in the future to reduce redundancy in the project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
No visual changes to the website

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
@cflemmonds Please complete this PR, following instructions in the [CONTRIBUTING section 3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests). In particular, in the first line of the PR, please replace the string "replace_this_text_with_the_issue_number" with the issue number.  As it is, we have no issue linked to this PR so we cannot review it.  

When that is done, please complete the other sections of the PR:
- What changes did you make?
- Why did you make the changes (we will use this info to test)?
- Screenshots of Proposed Changes Of The Website 
   - If there are no visual changes to the website as a result of the PR, follow the instructions in [CONTRIBUTING Sect 3.1.b](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31b-complete-pull-request-on-hack-for-la-website-repo)



Thank you!

**Comment by ino-iosdev** [comment]
> @cflemmonds Please complete this PR, following instructions in the [CONTRIBUTING section 3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests). In particular, in the first line of the PR, please replace the string "replace_this_text_with_the_issue_number" with the issue number. As it is, we have no issue linked to this PR so we cannot review it.
> 
> When that is done, please complete the other sections of the PR:
> 
> * What changes did you make?
> * Why did you make the changes (we will use this info to test)?
> * Screenshots of Proposed Changes Of The Website
>   
>   * If there are no visual changes to the website as a result of the PR, follow the instructions in [CONTRIBUTING Sect 3.1.b](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31b-complete-pull-request-on-hack-for-la-website-repo)
> 
> Thank you!

@cflemmonds Once you completed the steps mentioned from @roslynwythe , please mention me in the comment so that I could go ahead and start the review process, thank you! Please feel free to reach out if you need any help along the process!

**Comment by jphamtv** [comment]
Hi @ino-iosdev, I think you intended to add yourself as a reviewer instead of self-assigning as an Assignee. I've unassigned you and added you as a reviewer instead. Thanks!

**Comment by jphamtv** [comment]
Hi @cflemmonds, please address the comments from @roslynwythe and @ino-iosdev. If you are unable to continue working on this issue, let us know and we'll unassign you. Thanks!

**Comment by cflemmonds** [comment]
Thank you for all of your help! I have made the edits to the initial comment. If there is anything else I need to update, please let me know. Thanks again.

**Review by ino-iosdev — CHANGES_REQUESTED** [review]
@cflemmonds thank you for the revision!

- Issue number was properly linked
- branch naming is good

### Changes required:

1. Remove 6719 from the title (we don't need to add it there, note how it becomes unclear since it stacks with your PR number 6916)

2.  Revise the actual change made in the file: DO NOT delete the original github link, the issue did NOT request you to add a link, it just needs you to add `github-handle: ` under `- name: Shawn Duenas`, please read the instruction again in the issue #6719

 
3. Use syntax highlight when referencing syntax so that it's clear to read, in the `What changes did you make?` section, quote from the original issue change request when laying out the changes you made, this is good to double check whether you followed the exact change instruction. To make syntax highlight, add a backtick at the beginning and end of the words you wish to highlight. Then click `Preview` to check how it turns out when people read it, see below:

### What you type in `Write` section

Screenshot 2024-06-06 at 8 23 33 PM

### What you see in `Preview` section

Screenshot 2024-06-06 at 8 25 30 PM



4. Revise the `Why did you make the changes` answer: In general, it's a good practice to write details in your own words based on the request from the issue, see below from the original issue page:

Screenshot 2024-06-06 at 8 23 10 PM

**_Check out this example of a similar issue for your reference #6917_** 

After making all these changes, don't forget to click on something like this on the top right of your page (see below) to request a review of your changes:

Screenshot 2024-06-06 at 8 45 27 PM

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @cflemmonds Good job so far with this issue, and thanks for working with everyone to address their comments. 
- Regarding the issue title- I tend to leave the issue number in the title myself (I have an open PR right now where I do this). In other words, I am OK either with or without the issue number. Since this is not a stated requirement from Hack for LA, I am not going to ask you to make this change.
- Regarding the code edits: it seems there was some confusion with issues like this one. 
  - As @ino-iosdev referenced, line 27 was not part of the issue so please change this back to `github: 'https://github.com/McRawly'`. 
  - The intent of the issue is that a new line should be inserted  after line 23 `-name: Shawn Duenas`. This new line should say `github-handle:` and be inline as shwon.
  - Note: the intended result is shown on Lines 10 and 17 of the same file.
- Regarding  "What changes did you make..." and "Why...", as mentioned typically you will want to give a brief summary of the "Overview" of the original issue. For the "What.." section, you could say something to the effect of "Add a single variable `github-handle` after team member's name", and for "Why..", you could say something like "This variable will be used in the future to reduce redundancy in the project file." 

Thanks for sticking with this- you are almost there!
One last note: @ino-iosdev  please remember, these are 'requested changes', not 'required changes'.

**Comment by cflemmonds** [comment]
@t-will-gillis 
@ino-iosdev 

I want to begin with thanking you both for your feedback and clarifying the issue. I have taken your feedback and made the necessary changes. If I missed anything, please to hesitate to remind me!

**Review by t-will-gillis — APPROVED** [review]
@cflemmonds Perfect- thanks for making the changes.

(Don't forget to click on the chasing arrows to re-request a review from @ino-iosdev )
<details>  

Screenshot 2024-06-10 181100 

</details>

**Review by ino-iosdev — DISMISSED** [review]
@cflemmonds Thank you for all the update, great job!

Since there are a few of these PRs re adding github handle, to make the title visually clear, it would be good to add the name of the person, e.g. `Added github-handle for Shawn Duenas`, hope this makes sense to you. I'm good to approve after this last bit of change, thank you.

**Comment by cflemmonds** [comment]
@ino-iosdev thanks so much for that suggestion, I've made the requested change to the title! Thanks again

**Review by jphamtv — APPROVED** [review]
Hey @cflemmonds, thanks for making the requested title change and addressing all the feedback. Great work!

**Pull request merged**
