### PR TITLE
Remove good second issue from CONTRIBUTING section 2.2

### LINKED ISSUE #5590: Remove "good second issue" from CONTRIBUTING.md Section 2.2
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove references to "good second issue" from CONTRIBUTING.md in order to avoid confusion, since we are no longer creating issues with the label `Complexity: good second issue'.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` and locate Section 2.2
- [x] Remove
```
* `complexity: good second issue`
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/C- ONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review locally, rather review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [x] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4506

### PR DESCRIPTION
**Pull request by romainyvernes**
Fixes #5590

### What changes did you make?
  - Deleted ``* `complexity: good second issue` `` within section 2.2 of CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
  - Because we are no longer creating issues with the label `Complexity: good second issue'.

For Reviewers: Do not review locally, rather review changes at https://github.com/romainyvernes/hackforlawebsite/blob/remove-good-second-issue-5590/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No visual changes on website.

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: Evening, but may contact via Slack on the weekends throughout the day
ETA: By EOD Saturday

**Comment by freaky4wrld** [comment]
ETA: 9th October
Availability: Evenings mainly

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5590 was properly referenced. ✅ 
- The specified line of code was properly removed per the instructions on the original issue. ✅ 
- You also provided a direct URL to the updated md file for review, which was excellent!

Great work @romainyvernes !

**Review by freaky4wrld — APPROVED** [review]
- The merging branch is correct i.e. ` gh-pages ` 
- The line ` good second issue ` is removed from CONTRIBUTING.md
- Changes are visible on the forked repo of  @romainyvernes 
- The reason to make change is clearly mentioned and the original issue https://github.com/hackforla/website/issues/5590 was referenced correctly. 

The  PR is good to merge, thanks @romainyvernes  for providing the direct URL of your forked repo.

**Pull request merged**
