### PR TITLE
update 311 info page 2987

### LINKED ISSUE #2987: Update Project Profile: 311data
### Overview
As a product manager of 311 Data I want my project's details to be up-to-date on the HackforLA website

### Project card
https://github.com/hackforla/website/tree/gh-pages/_projects/311-data.md

### Action Items

- [x] 311 Data Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [ ] Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

### PR DESCRIPTION
**Pull request by maybleMyers**
Fixes #2987 
### What changes did you make and why did you make them ?

  -Removed people no longer on the project
  -Added New Product Managers
  -Changed the Partner
  -Made changes to bring the information up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by maybleMyers** [comment]
I did not open an issue on VRMS to update the meeting times because they appear to be correct. If they are not correct then what are the new times?

**Comment by blulady** [comment]
Review ETA: 7 PM 3.20.22
Availability: 2-6 PM Tuesday 3.22.20

**Review by blulady — APPROVED** [review]
Looks Good!
The pull request is done with the correct branch. The linked issue is correct and has been addressed. The changes in the Browser look good.  The source code is clean and succinct.  The  prior volunteers have been removed and the current ones updated.

**Comment by SAUMILDHANKAR** [comment]
Review ETA: End of day 3/21/22
Availability: Monday 6-7 PM Pacific Time

**Comment by SAUMILDHANKAR** [comment]
> I did not open an issue on VRMS to update the meeting times because they appear to be correct. If they are not correct then what are the new times?

@Benji-Montgomery You are right, looks like no update is required for the meeting times. Thanks.

**Review by SAUMILDHANKAR — APPROVED** [review]
@Benji-Montgomery All changes look good in my environment. Nicely done! Thank you.

**Pull request merged**
