### PR TITLE
merging content and type to content-type in building.yml

### LINKED ISSUE #2797: Edit content field and remove type field from building.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/building.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/building.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/building.yml#L4
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/building.yml#L11

- Availability for this week: Good
- My estimated ETA for completing this issue: Sun, May 22

### PR DESCRIPTION
**Pull request by mmogri**
Fixes #2797

### What changes did you make and why did you make them ?

  - Changed line 4 for the content field from content: icon to content-type: image
  - Removed line 11 for the type field type: icon

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/23
Availability: 2 hours

**Review by Jaretzbalba — APPROVED** [review]
@mmogri The changes on the building.yml file look great! Thank you for working on this issue!

**Comment by kathrynsilvaconway** [comment]
ETA: End of the day on 5/23
Availability: 1 hours

**Review by kathrynsilvaconway — APPROVED** [review]
@mmogri Congrats on completing your first issue with Hack for LA. I see that you have changed the content field in line 4 to read 'content-type: image' and you have deleted line 11 from the building yml file. Nice work.

**Comment by KBWells77** [comment]
ETA: End of day on 5/23
Availability: 1 hour

**Review by KBWells77 — COMMENTED** [review]
Looks great @mmogri , great job fixing the error.

**Pull request merged**
