### PR TITLE
Removed alt-hero field from _projects/spare.md file

### LINKED ISSUE #3211: Remove unused `alt-hero` field from spare.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/spare.md`, remove line 8 for the alt-hero
```
alt-hero: ''
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/spare.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/_projects/spare.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by angelenelm**
Fixes #3211

### What changes did you make and why did you make them?
- Per the action items, for the file ```_projects/spare.md```, removed line 8 for the alt-hero
<strike>

```
alt-hero: ''
```
</strike>

### Screenshots of proposed changes of the website (if any; please do not screenshot code changes)
- No visual changes to the website.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Availability: Friday, 11/18, 12-5
Review ETA: Friday 5pm

**Comment by giroz** [comment]
ETA: 11/18/22
Availability: 2 hours

**Comment by Suman2795** [comment]
ETA:18/11/2022
Availability: 2 hours

**Review by Suman2795 — APPROVED** [review]
This looks good. Changes are made into the correct branch and are done as asked in the issue.

**Review by t-will-gillis — APPROVED** [review]
Hi @angelenelm - good job!  You followed the linked issue, deleted the correct line, left the code cleaner!

**Review by MattPereira — APPROVED** [review]
Well done and great job explaining your changes @angelenelm ! :+1:

**Review by giroz — COMMENTED** [review]
Good Job! Well done deleting text.

**Pull request merged**
