### PR TITLE
refrac: updated small label to avoid github bot removing the label

### LINKED ISSUE #4479: Update labels: Issue Template: creating-a-yml-file-for-a-sdg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/creating-a-yml-file-for-a-sdg.md`
- [x] Replace the following line
   ```
   labels: 'Complexity: Small, p-feature: SDGs, role: front end, size: 0.25pt'
   ```
   with
   ```
   labels: ['Complexity: Small','p-feature: SDGs','role: front end','size: 0.25pt']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL]

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/creating-a-yml-file-for-a-sdg.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by JpadillaCoding**
Fixes #4479

### What changes did you make and why did you make them ?

- labels: ['Complexity: Small','p-feature: SDGs','role: front end','size: 0.25pt']
- Modified the labels on the Creating a yml file for a SDG issue templete

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

-No visual changes

###For PR Reviewers and Merge Team
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

###Link for Reviewers
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: https://github.com/JpadillaCoding/Website/issues/new?assignees=&labels=Complexity%3A+Small%2Cp-feature%3A+SDGs%2Crole%3A+front+end%2Csize%3A+0.25pt&projects=&template=creating-a-yml-file-for-a-sdg.md&title=Creating+a+yml+file+for+SDG+%5BINSERT+SDG+NUMBER+HERE%5D

###For PM, Merge Team, or Tech Lead

- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Comment by kiwookim** [comment]
ETA: 6/4/23 by 3pm

**Review by kiwookim — CHANGES_REQUESTED** [review]
Hi, Jose.
Thanks for taking this issue,
Great job setting up the branch correctly, adding correct labels in the 'creating-a-yml-file-for-a-sdg.md.
I do see all the labels you added on the create issue page.

Just a minor fix:
Please remove the bracket when adding links in the few sections where the reviewers need the URL so it redirects us to the URL right when we click on it. (Link for Reviewers, and in the comments section here: https://github.com/hackforla/website/issues/4479#issuecomment-1574489714)
Thank you.

**Comment by roslynwythe** [comment]
Availability: 6/4 6 -8 pm
ETA: EOD 6/4

**Comment by JpadillaCoding** [comment]
@kiwookim  
Nice Catch! The comments have been edited with the removal of the brackets.

**Review by kiwookim — APPROVED** [review]
Could you also add the url here? https://github.com/hackforla/website/issues/4479#issue-1663620661 (Link for Reviewers section)

Thank you for the update!

**Comment by JpadillaCoding** [comment]
@kiwookim It's been added as a comment as requested.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Great job @JpadillaCoding!  You made the correct code change, followed the test procedure, and created a Pull Request with the correct branches.  We do need to ask that you write something under "What changes did you make and why did you make them ?".  I suggest two bullet points, one with the updated value of the "labels" array, and another that mentions that you modified the labels on the "Creating a yml file for a SDG" issue template, so that the GitHub bot won't remove the label.  

The sentence  "No visual changes" should go under "Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)".  

Thank you !

**Comment by JpadillaCoding** [comment]
@roslynwythe I've made the changes requested. One thing I am curious about- How does commenting the label modification stop the bot from removing the label?

**Comment by JpadillaCoding** [comment]
Provide Update
1. Progress: Issue complete, making adjustments to PR comment to meet PR request standards.
2. Blockers: N/A
3. Availability: Sunday 7am-9pm
4. ETA: Done

**Review by roslynwythe — APPROVED** [review]
Hi @JpadillaCoding I agree that in this particular issue, it is unclear how the change specified in the Action Item would make a difference in the GitHub bot behavior, since all of the labels in the "Missing Series" were already assigned.  The change may have been made to be consistent with the syntax in other issue templates.  

Thank you for your work on this issue.  You made the correct code change, completed a rather complex test process, and created a well-formed PR.  We really appreciate your time and effort!

**Pull request merged**
