### PR TITLE
Created issue template for updates to CONTRIBUTING.md

### LINKED ISSUE #5547: Create Issue Template for Updates to CONTRIBUTING.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a GitHub issue template for updates to CONTRIBUTING.md so that issues can be created efficiently and so that we can provide developers with special instructions for previewing changes to CONTRIBUTING.md.  

### Action Items
- [x] Create a new file `.github/ISSUE_TEMPLATE/update-CONTRIBUTING.md` with YAML frontmatter:
```
---
name: update CONTRIBUTING.md
about: 'For making updates to CONTRIBUTING.md'
title: 'Update CONTRIBUTING.md Section [INSERT SECTION #]'
labels: 'Feature: Wiki, Complexity: Small, role: back
  end/devOps, role: front end, size: 0.5pt'
assignees: ''

---
```
- [x] The body of the issues should come from this [template](https://github.com/hackforla/website/issues/5547#issuecomment-1722424996)
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by erinzz**
Fixes #5547 

### What changes did you make?
  - created file for the new GitHub issue template for making updates to CONTRIBUTING.md
  - included in body provided template format and description
  - created new labels for issue template on GitHub following standardized labels from HackforLA repo 

### Why did you make the changes (we will use this info to test)?
  - increase efficiency in creating issues for the team
  - allows for specific instructions to preview changes made to CONTRIBUTING.md for the developer working on issue

### For Reviewers
- Use this URL to check the updated issue template: (https://github.com/erinzz/website/issues/new?assignees=&labels=Feature%3A+Wiki%2C+Complexity%3A+Small%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=update-CONTRIBUTING.md&title=Update+%5BDESCRIBE+CHANGE%5D+in+CONTRIBUTING.md)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

None 

</details>

<details>
<summary>Visuals after changes are applied</summary>

**Form when creating new issue:**
Screenshot 2023-09-21 at 6 06 12 PM

**Labels added after issue created:** 
Screenshot 2023-09-21 at 6 06 43 PM

</details>

### CODE REVIEW

**Comment by ha-bach** [comment]
Reviewing this PR
ETA: end of week
Availability: weekends

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @erinzz Your work on this issue was perfect, but I discovered that there was an error in the front matter as well as in body of the template; I have edited the issue to correct the error and I need to ask you to update the md file as well as the test URL.  I apologize for the error.  Please contact me in Slack if you have any questions.

**Comment by erinzz** [comment]
Hey @roslynwythe, no problem! I've updated the template with the corrected front matter and body. Let me know if there's anything else that's wrong.

**Comment by roslynwythe** [comment]
I apologize @erinzz but I had to make another change in both frontmatter and the template.  I updated the issue and template and I promise this is the last change.

**Comment by erinzz** [comment]
Hey @roslynwythe, no worries, I've updated the front matter and templated again!

**Review by christinaor — APPROVED** [review]
Hey @erinzz , great job on this issue, and thanks for being patient with us! The branch was created correctly, the issue itself is very descriptive, and you made the correct changes based on Roslyn's latest changes to the template.

**Review by roslynwythe — APPROVED** [review]
Thank you you @erinzz for your excellent work and your patience with the changes to this issue.  You correctly created the .md file to implement a new GitHub issue template, tested the template in your repository, provided a link to the test template for the convenience of reviewers.  You created a descriptive and well-formed PR with correct branches and updated the PR to reflect a change in the issue.   Thank you for your contribution!

**Pull request merged**
