### PR TITLE
Remove alt text fields 2931

### LINKED ISSUE #2931: Remove unused alt-text field in toolkit guides html files: linkedin, dashboard, and using-kanban (file names abbreviated)
### Overview
As a developer, I want to make sure unused code is removed from the codebase in the guide pages' HTML files, so that 
- time to load the website is as low as possible, 
- it's easier to understand the code, and 
- time to review the code is reduced. 

For this issue, we will remove the unused alt-text fields from the guide pages' HTML files.

### Details
At the top of each guide pages' HTML file, there is a section containing YAML front matter, which contains variables that can be accessed using Liquid tags. (See the links in the Resources/Instructions section for more information about front matter and Liquid tags.) 

In the front matter of each guide pages' HTML file, there are the variables: `svg` and `alt-text`. `svg` field contains the location of a decorative image and `alt-text` is the alt text associated with the `svg` image.  Currently, `alt-text` is not used anywhere in our codebase since the images are not used within an `img` HTML tag and the images are displayed through svg HTML tags. 

Moreover, the alt text for all the images should be `alt=""` and will be programmatically set for all the alt properties associated with each image in issue #2929. 

### Action Items
- [x] Remove the line of code with the `alt-text` field in the following files only:
  - [x] showing-civictech-experience-on-llinkedin.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/showing-civictech-experience-on-linkedin.html#L10
  - [x] survey-reporting-dashboard-guide.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/survey-reporting-dashboard-guide.html#L19
  - [x] using-kanban-project.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/using-kanban-project.html#L10
- [x] The guide pages' HTML files are used on the website in the Toolkit page and the guides linking from the Toolkit page.
  - [x] Check the Toolkit page and make sure it looks the same as the current [Toolkit page](https://www.hackforla.org/toolkit/)
  - [x] Check each guide page by clicking on its link in the Toolkit and making sure it looks the same as guides on the current website

### Resources/Instructions
- [Information about Front Matter as used by Jekyll](https://jekyllrb.com/docs/front-matter/) 
- [Introduction to Liquid, including information on tags](https://shopify.github.io/liquid/basics/introduction/)
- [Toolkit page](https://www.hackforla.org/toolkit/)
- Directory to find the files once you have it in your IDE: _guide-pages
- Click on the links below to see the code for each file: 
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/showing-civictech-experience-on-linkedin.html#L10
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/survey-reporting-dashboard-guide.html#L19
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/using-kanban-project.html#L10

### PR DESCRIPTION
**Pull request by matt-arofin**
Fixes #2931

### What changes did you make and why did you make them ?

  - Deleted deprecated 'alt-text' tags from YAML front matter in 3 `/_guide-pages` files

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Removed alt-text tags only - no visual changes observed on site

### CODE REVIEW

**Review by Zak234 — COMMENTED** [review]
The edits to the guide page look good but I'm not sure from the issue whether your supposed to delete the alt-hero line in the website.md page.

**Comment by matt-arofin** [comment]
> The edits to the guide page look good but I'm not sure from the issue whether your supposed to delete the alt-hero line in the website.md page.

@Zak234 I'm also not sure why that's there, it's a commit from an unrelated issue that's still showing up in my pull requests. 

Let me take a look and see whether I can't get it to stop being added.

**Comment by kathrynsilvaconway** [comment]
@tamara-snyder @Sparky-code @JessicaLucindaCheng It looks like this PR is running into the issue where unrelated changes are showing up in the commits. Do any of you know what the fix was for this? I know we had this problem with another PR in the last couple of weeks, but I don't know which one it was.

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway 
1) They can try reverting the commit that brought in that change [alt-hero field deleted](https://github.com/hackforla/website/pull/3301/commits/cb5953920bfdb951ce10c5fa76adf2ed09f4f709)
2) Also, I think the topic branch hasn't been updated with the latest changes from hackforla/website's gh-pages for over month. So, the pr creator should probably update their topic branch too.

**Comment by riddle015** [comment]
Availability: 2 hours
Review ETA: June 26, 2022

**Review by kathrynsilvaconway — APPROVED** [review]
@matt-arofin Thanks so much for working on this issue. I see that you have removed the alt text fields. All of the unwanted files have been reverted. Everything looks good.!

**Pull request merged**
