### PR TITLE
Modify GitHub actions for label change 3109

### LINKED ISSUE #3109: Modifying GitHub actions for label change from size to level
### Dependency
- [x] #2777 

### Overview
As a developer, I would like to track the size of an issue in terms of number of hours. In order to achieve that, we need to modify GitHub action automations or other files before changing size labels to level.

### Details
We are planning to edit the following labels:
- ```Size: Good second issue``` to ```level: Good second issue```
- ```Size: Small``` to ```level: Small```
- ```Size: Medium``` to ```level: Medium```
- ```Size: Large``` to ```level: Large```

However, before doing that we need to edit all the automations that might be dependent on these existing labels, so that no workflows are affected by this change. Refer to issue #2777 for details on which automations might be impacted.

### Action Items
- [x] Use the search string in the resources below to confirm that the list of files that use the size labels identified, is complete.
- [x] Refer to Resources section for which files will be impacted
- [x] Test the changes in your own repo and make sure other functionalities are not impacted
- [ ] Create a pull request if all looks good in your own repo
    - [ ] Note: Discuss a timeline with the merge team and leads to change the actual labels in our repo as this might be needed for the GitHub action to work properly.
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit #3110 by
  - [x] Checking off the dependency for this issue in issue #3110
  - [x] Editing any action items if required
  - [x] If all dependencies are checked off, please move issue #3110  to the New Issue Approval column, remove the Dependency label and add ready for milestone label.

### Resources/Instructions
- [GHA architecture spreadsheet](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions
- https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions
- https://github.com/hackforla/website/wiki/GHA:-issue-trigger

#### Code that Reference Size Labels
- [Search GitHub Actions Workflow directory for files that contain the string `size:`](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+size%3A+path%3A%2F%5Egithub-actions%5C%2F%2F&type=code&l=github-actions%2Ftrigger-issue%2Fadd-missing-labels-to-issues%2F)
- [GitHub actions folder](https://github.com/hackforla/website/tree/gh-pages/github-actions)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
1. [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js) --> contains many actions that utilize labels using the 'size' attribute one time in the declaration
2. [check-labels.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js) ---> also contains processes that utilize labels using the 'size' attribute one time in the declaration

I will also note that the following phrases were not used throughout the 2 directories listed above. Just the use of "Size:" and labels.
- ```Size: Good second issue``` 
- ```Size: Small``` 
- ```Size: Medium``` 
- ```Size: Large``` 

#### Wiki pages that reference size labels
- [Search the wiki for "size: medium"](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+size%3A+path%3A%2F%5Egithub-actions%5C%2F%2F&type=code&l=github-actions%2Ftrigger-issue%2Fadd-missing-labels-to-issues%2F)
1. https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels
2. https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests
3. https://github.com/hackforla/website/wiki/How-to-create-issues

### PR DESCRIPTION
**Pull request by bzzz-coding**
Fixes #3109

### What changes did you make and why did you make them ?

  - Changed 'Size' to 'Complexity' in these two files in GitHub actions that referenced Size:
     - github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js
     - github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Linked below are two updates I provided in the comments for issue #3109:
- ## In this update, I identified all files in the repo and wiki that referenced 'Size' and potentially need updating for consistency:
    - https://github.com/hackforla/website/issues/3109#issuecomment-1381208287

- ## I identified the "next steps" in the comment below, but I'm unsure if I should work on those for this issue.
    - https://github.com/hackforla/website/issues/3109#issuecomment-1382321028

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @bzzz-coding – I am reviewing the changes you made, and it appears your edits match what the original issue was looking for. This is primarily the two files in `post-labels-comment.js` and `check-labels.js` Great job!

My one observation is about the text case for the labels. You matched what the original issue requested- i.e. to change `Size: ` to `level: ` so this isn’t a critique of your work. However, I am marking my review as ‘Request changes’ because I think that while we are already making the changes this is a great time to review the HfLA documents and code and make sure they are stylistically consistent. For example, our labels are sometimes all lowercase (`role: back end/devOps` and `size: 1pt`), all title case (`Status: Updated`), or mixed (as `Size: Medium` changes to `level: Medium`) without there seeming to be a reason why the style should be one way and not another. (At least from what I can see. Maybe there is pattern here that I am not seeing…) What do others think?

As you mention, there are other places that reference the `Size: Large` etc. For example, the original issue notes that the `CONTRIBUTING.md` document also needs to be edited via #3110. 

**A big warning here is that #3110 is talking about changing `Size: ` to `Complexity: ` and not `level: ` (or `Level: `)** Probably needs to be edited?

This also leaves the wikis. I am not sure if the intent was for the wikis to be part of this issue or if they are a separate issue… merge team?

Thanks for your work! Looking good so far.

**Comment by bzzz-coding** [comment]
Hi @t-will-gillis, thanks for reviewing my PR and leaving the comment! I agree--it would be a good time to review the label styles and address the comment about changing Size to Complexity under the issue. 

I was also wondering if there is a general style guide regarding GHA and all the HfLA code regarding indentation, quotation marks, line breaks, naming variables, etc.

**Comment by t-will-gillis** [comment]
Hi @bzzz-coding I do not know if HfLA has a style guide. It is possible that there is something in the wikis [https://github.com/hackforla/website/wiki](url) but I have not found that myself. I would like to know for myself also. This may be something to bring up in a meeting or by slacking the merge team. I also don't want to hold up this PR if we do not want to address the styling now.

**Comment by blulady** [comment]
@bzzz-coding and @t-will-gillis,
This is a great discussion and I am glad you are having it!! For future reference you can always @hackforla/website-merge to get our eyes on an issue (someone is bound to check their GitHub notifications). These are great points about the inconsistency with the capitalization and the level being changed to complexity in #3110. Apparently there is a style guide coming soon (according to the bottom of the [wiki page](https://github.com/hackforla/website/wiki) but I'll have to double check to see where we are on that). But I think we need to check before we merge the PR to see if we want to go with level or complexity. The issue #3110 will put these changes into the wiki, we know this because issue #3110 has a dependency on the completion of #3109 and is currently in the ice box waiting for this issue to be completed so we can release it (which I always think is fun, like releasing the Kraken and is described [here](https://github.com/hackforla/website/wiki/How-to-create-issues#when-do-issues-with-dependencies-get-approved)) But I'll dig around to see what "coming soon" actually means for the HFLA style guide.

**Comment by bzzz-coding** [comment]
@blulady @t-will-gillis @hackforla/website-merge Thank you! I'll wait for further clarification/revision to this issue regarding the change from Size to level or Complexity and then make changes if needed.

**Comment by bzzz-coding** [comment]
@hackforla/website-merge
As discussed in the 1-24-23 meeting, I changed label 'size' to 'Complexity'.
Please note that there is a ':' between 'size' (now 'Complexity') and 'missing' but I don't see it with other labels, for example, 
in github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js:
`const LABEL_MISSING = ['Complexity: missing', 'role missing', 'Feature Missing']`

and in github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js: 
`const LABELS_OBJ = {
  'Complexity: missing': 'Complexity',
  'role missing': 'Role',
  'Feature Missing': 'Feature'
}`

- Is the ':' there for a reason, or is it a typo that should be removed?
- Should 'missing' be capitalized as in 'Feature Missing', or should it be all lowercase as in 'role missing'?

I only updated 'size' to 'Complexity' in this PR, and left ':' and 'missing' as they are.

**Review by t-will-gillis — COMMENTED** [review]
Good catch with the ':' in 'Complexity: missing'! Although I can see one side of an argument for keeping it, my opinion would be to ditch the colon and capitalize Missing to match: 
`const LABELS_OBJ = { 'Complexity Missing': 'Complexity', 'role missing': 'Role', 'Feature Missing': 'Feature' }` 

How do you feel about it? 
I notice that Matt added this issue to the meeting agenda for January 29th. I am submitting this as a comment for now and will test this tomorrow to see whether removing the colon has any unexpected affects. 

>> I tested with `'Complexity Missing' : 'Complexity'` - the test was OK/ no issues.

**Comment by MattPereira** [comment]
Hey @bzzz-coding 

We brought up your question about letter casing and the usage of `:` with the product manager. She said casing does not matter for labels but to definitely keep the `:` for the `complexity: missing` label because the github actions may fail if you remove it.

**Review by t-will-gillis — APPROVED** [review]
Hey @bzzz-coding - Awesome work and thanks for following through with it!

**Comment by MattPereira** [comment]
ETA: End of day Feb 1st
Availability: 8-10 PM Sunday thru Thursday

**Review by MattPereira — APPROVED** [review]
Amazing work on this one @bzzz-coding ! :+1: 

I appreciate your attention to detail noticing the label naming inconsistencies and would also like to commend the outstanding display of teamwork between you and @t-will-gillis on this PR

**Pull request merged**
