### PR TITLE
Program Areas: Update alt text for the join us footer desktop image

### LINKED ISSUE #3877: Program Areas: Update alt text for the join us footer desktop image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Program Areas` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `/pages/program-areas.html`:

**From:**
```
alt="join us card image"
```

**To:**
```
alt=""
```

- [x] Ensure that the corresponding `Program Areas` page stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

### Resources/Instructions
- https://www.hackforla.org/program-areas

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `/pages/program-areas.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/075ce5f7d67c7732e258148b0f4a1a9342095e26/pages/program-areas.html#L72

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by phuongv8**
Fixes #3877 

### What changes did you make and why did you make them ?

  - Change the image alt property value on the Program Areas page from "join us card image" to ""
  - The change was made to adhere to the Web Content Accessibility Guidelines (WCAG) and achieve mission of inclusivity.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updated image alt text. No visual changes to the website.

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
Labels were not automatically added (probably because there is a merge conflict), so I manually added them to this pr.

**Comment by mariorecinos** [comment]
Hi Phoungv8 awesome work on this pull request!  Although you have done awesome work to add the alt text There is currently a merge conflict with your pull request.  Make sure to go to vs code and resolve the conflicts.  When resolving a conflict you want to indicate what is the work you want to push.  In this case you want to push your awesome work were you have the alt text. When you go to review the merge conflict you will be presented with two version of your code one without your changes and one with your changes you definitely want to choose to keep your changes.  Fix the merge conflict and send over the pull request with the fix and you should be good to go.  If any questions below is a link to the hackforLA on solving merge request a from the github documentation.

[Resolving Merge Conflict](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line)

[](url)

```
=======
        class="join-us-footer-img mobile-img"
        src="/assets/images/join-us/volunteer-with-us-icon.svg"
        alt="join us card image"
      />
      <div class="join-us-footer-paragraphs">
        <p class="first-paragraph">
          To join any of the projects click through their project pages for
          details on getting started.
        </p>
        <p class="second-paragraph">
          The projects that are in formation are not yet on our website. To
          connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack</a> and browse for their
          channel name.
        </p>
      </div>
        <a href="/join" class="btn btn-primary btn-md btn--default">Join Us</a>
      </div>
  </div>
</section>
>>>>>>> gh-pages

**Review by mariorecinos — CHANGES_REQUESTED** [review]
Hi Phoungv8 awesome work on this pull request! Although you have done awesome work to add the alt text There is currently a merge conflict with your pull request. Make sure to go to vs code and resolve the conflicts. When resolving a conflict you want to indicate what is the work you want to push. In this case you want to push your awesome work were you have the alt text. When you go to review the merge conflict you will be presented with two version of your code one without your changes and one with your changes you definitely want to choose to keep your changes. Fix the merge conflict and send over the pull request with the fix and you should be good to go. If any questions below is a link to the hackforLA on solving merge request a from the github documentation.  Currently your push is doing the opposite and [removing the alt text](https://github.com/hackforla/website/pull/4208/files)

[Resolving Merge Conflict](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line)


=======
        class="join-us-footer-img mobile-img"
        src="/assets/images/join-us/volunteer-with-us-icon.svg"
        alt="join us card image"
      />
      <div class="join-us-footer-paragraphs">
        <p class="first-paragraph">
          To join any of the projects click through their project pages for
          details on getting started.
        </p>
        <p class="second-paragraph">
          The projects that are in formation are not yet on our website. To
          connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack</a> and browse for their
          channel name.
        </p>
      </div>
        <a href="/join" class="btn btn-primary btn-md btn--default">Join Us</a>
      </div>
  </div>
</section>
>>>>>>> gh-pages

```

**Comment by phuongv8** [comment]
Hi @mariorecinos, I have resolved the merge conflict on github. I'm not sure why after I did git pull, it does not show the conflict on vs code. It said file is up to date.

**Comment by mademarc** [comment]
Review ETA:  3/21/2023
Availability: 7PM

**Comment by mariorecinos** [comment]
Review ETA: 9 PM 3/21/23
Availability: 7-9 PM 3/21

**Review by mademarc — APPROVED** [review]
Hey @phuongv8  The changes on this code were done very well.

**Review by mariorecinos — APPROVED** [review]

**Comment by mariorecinos** [comment]
> Hi @mariorecinos, I have resolved the merge conflict on github. I'm not sure why after I did git pull, it does not show the conflict on vs code. It said file is up to date.

@phuongv8 excellent work on fixing the merge conflict.  One small slight note 

One note: it looks like your fork of the hackforla/website repo is named hfla-website instead of website. The instructions for reviewing pull requests assume that your repo is named website (see [Commandline instructions for Development Team](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-3-view-the-changes-in-the-browser)), so you may want to make a note of this for future reviewers or re-fork/rename the repo if possible.

Credit this feedback to [from this review](https://github.com/hackforla/website/pull/4222#pullrequestreview-1351580167)

Keep up the awesome work and thank you for maintaining amazing communication during this whole pull request.

**Review by vraer — APPROVED** [review]
@phuongv8, please excuse my tardiness, as your exceptional code had the power to make time stand still during my review. Kudos!

**Comment by mjh-projects** [comment]
@phuongv8  good job with the pull request. All the changes look good. It looks like the merge conflict is resolved..

**Review by mjh-projects — APPROVED** [review]
Changes look good.

**Pull request merged**
