### PR TITLE
Add github-handle for Sara Brady in tech-work-experience.md

### LINKED ISSUE #7245: Add github-handle for Sara Brady in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Sara Brady
```
with
```
- name: Sara Brady
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by joooseph2**
Fixes #7245 

### What changes did you make?
 Changed variable `name:` in /website/_projects/tech-work-experience.md to include variable
`github-handle:` 
- `name: Sara Brady`

- `name: Sara Brady
   github-handle:`

### Why did you make the changes (we will use this info to test)?
  - to submit the second pull request. The issue was created to replace the github: and picture: variables with github-handle: to reduce redundancy. 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No Visual changes made as only a variable name was added.

### CODE REVIEW

**Review by santiseccovidal — APPROVED** [review]
Hi @joooseph2 everything looks great.
Branches are correct, there's a linked issue and you correctly stated that there are no visual changes done to the website. No changes in my docker version also.

When it comes to the code, `github-handle:` was correctly added underneath `- name: Sara Brady` without using tab indent.

Great job! Thanks for working on this

**Comment by santiseccovidal** [comment]
Review ETA: 6 AM 8/19/24
Availability: 8-2 PM Monday

**Comment by mmcclanahan** [comment]
Review ETA: 8/20/24 3PM
Available: Monday & Tuesday 8am-7pm

**Review by mmcclanahan — APPROVED** [review]
Hey @joooseph2 Good Work!

What was completed correctly:
To and from branches 
linked issue
what and why are clear and thorough
No visual changes made / correctly indented without tab

Thanks for completing this issue!

**Review by santiseccovidal — CHANGES_REQUESTED** [review]
Hi @joooseph2 looking in more detail to your descriptions.
I'm a bit confused by the answer to **Why did you make the changes**.

I think that the issue states a different reason as to **Why** adding the `github-handle` variable is done.

Moreover, in the **What** section we are not changing a variable but rather adding a new one.

Would you like to try answering the questions one more time?

**Comment by joooseph2** [comment]
@santisecco 
**Here's the original issue**
Overview

We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

**Here's my summary as to why**

to submit the second pull request. The issue was created to replace the github: and picture: variables with github-handle: to reduce redundancy.

Personally, I think it's fine. The issue says to replace `name:` with `name: github-handle:` . I see what you're saying but that's more a commentary on the linked issue not what I wrote out. I'm just following the format and description of the issue itself. I get that technically you're only adding a variable but that's not what the issue says. I could add in the why to say *eventually replaces* instead of just *replaces*. If the issue says add variable `github-handle:` under `name:` then I would make changes to my PR.

**Review by santiseccovidal — APPROVED** [review]
Agree @joooseph2 I meant that, we are "adding the variable to hold the github-handle of the member". It's a simple explanation, perhaps redundant, but we understand "what" the github-handle is, and the fact that one day an automation might be created to add them all up.
That would be my personal answer, but what you are saying is also true.

Thanks for clarifying and explaining that you also saw that it's "eventual"

**Comment by ihop-56** [comment]
Hi @joooseph2, I reviewed the changes, and everything looks great. The `github-handle:` was correctly added under `name: Sara Brady` without using tab indentations. There are no visual changes to the website, which aligns with the expectations for this change. Nice work!

**Review by ihop-56 — COMMENTED** [review]
Hi @joooseph2, I reviewed the changes, and everything looks great. The `github-handle:` was correctly added under `name: Sara Brady` without using tab indentations. There are no visual changes to the website, which aligns with the expectations for this change. Nice work!

**Pull request merged**
