### PR TITLE
Update Overview Links 2239

### LINKED ISSUE #2239: Update how 'Overview' link opens for Engage
### Overview
As a user, clicking on the 'Overview' link for the Engage project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Engage's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Engage-Product-One-Sheet.pdf.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Engage's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/engage) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md)
[Project Page](https://www.hackforla.org/projects/engage)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

### PR DESCRIPTION
**Pull request by BrianCodes33**
Fixes #2239

### What changes did you make and why did you make them ?

  - Placed new PDF file in folder  `assets/pdfs/Engage-Product-One-Sheet.pdf`
  - Updated `_projects/engage.md` on line 46 that points to `url: '../assets/pdfs/Engage-Product-One-Sheet.pdf'`
  - Tested links on home page and projects page and they are both opening correctly

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-02-02 at 2 42 26 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-02-02 at 2 41 52 PM

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1 hour
- Review ETA: Thu, Feb 3, 2022

**Comment by JessicaLucindaCheng** [comment]
@BrianCodes33 Before I review your pr, could you link the pr to the issue you are assigned to by changing the number for the field `Fixes #` in your post? I think the current linked issue is the wrong issue.

**Comment by BrianCodes33** [comment]
@JessicaLucindaCheng - yes I made an error with the issue # . Thanks for pointing that out.

**Review by JessicaLucindaCheng — CHANGES_REQUESTED** [review]
@BrianCodes33 Good job on this issue!

Could you edit and clarify your original post where you wrote, "Updated assets/pdfs with correct file assets/pdfs/Civic-Tech-Jobs-One-Sheet.pdf"? I'm a little confused because I thought you were adding `Engage-Product-One-Sheet.pdf` to the `assets/pdfs` directory. Thank you.

**Review by JessicaLucindaCheng — APPROVED** [review]

**Comment by JessicaLucindaCheng** [comment]
@BrianCodes33 Thanks for making the changes in the comment! Good job! I went ahead and merged your pr.

**Pull request merged**
