### PR TITLE
Change Alt Text for SDG Image

### LINKED ISSUE #3091: Change alt text for sdg image in 311 data md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the 311 data project's sustainability development goal image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/311-data.md`, change [line 74](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/311-data.md?plain=1#L74) for the alt text:

from
```
sdg-image-alt: peace justice bottom sustainable dev goal
```
to
```
sdg-image-alt: '16: peace, justice and strong institutions'
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/311-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/311-data.md?plain=1#L74

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by rdpfeifle**
Fixes #3091

### What changes did you make and why did you make them?

- I changed sdg-image-alt to '16: peace, justice and strong institutions' to ensure that alt texts adhere to Web Content Accessibility Guidelines (WCAG).

### CODE REVIEW

**Comment by rdpfeifle** [comment]
Question: I don't know why my last issue's commit is showing on this pull request. How can I fix this problem? Thank you!

**Comment by rdpfeifle** [comment]
Please, ignore commit [5702051]. It's already merged. I apologize in advance!

**Comment by Jaretzbalba** [comment]
Review availability: Sunday 2-3pm
ETA: 01/15 3pm

**Review by Jaretzbalba — APPROVED** [review]
@rdpfeifle I see that the alt tag description has been changed correctly and everything looks good. Thank you for working on this issue!

**Comment by rdpfeifle** [comment]
Progress: done since Sunday (01/15)
Availability: next week
ETA: took me about 30 minutes to complete

**Pull request merged**
