### PR TITLE
Add Christina Or to website.md leadership variable

### LINKED ISSUE #4236: Update Project Profile: Hackforla.org Website- Christina
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Christina Or
  GitHub Handle: christinaor
  Role: Merge Team
  Slack Member ID: U04J1GBA6QP
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by vraer**
Closes #4236 

### What changes did you make and why did you make them?

Added new member to `_projects/website.md` under `leadership`
  - name: Christina Or
  - role: Merge Team
  - slack: https://hackforla.slack.com/team/U04J1GBA6QP
  - github: https://github.com/christinaor
  - picture: https://avatars.githubusercontent.com/christinaor

  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before_projects-website
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after_projects-website
</details>

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: EOD 03/24
Availability: 3-8pm 03/24

**Comment by mjshelton12** [comment]
Review ETA: EOD 03/24
Availability: 6-10pm 03/24

**Review by arcan9 — CHANGES_REQUESTED** [review]
Hi @vraer! The member info you added is correct, but you are having a merge conflict (see "Resolve Conflicts" right below this page). This is because there are two different versions of this code block that currently exists which is 1) the version that exists in the remote repo and 2) your version with Christina Or. So Github can't merge this automatically. This usually occurs if you forgot to do `git pull` to update your code in your local machine before making changes.

To resolve the conflict, you'll need to fix it manually in your vscode. Here's a helpful guide: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line. Let me know if you have questions.

**Comment by vraer** [comment]
Hey @arcan9, thanks for the review. Looks like new changes were merged into the file after I submitted my pull request.  Everything should be up to date now :)

**Review by mjshelton12 — APPROVED** [review]
Excellent work vraer! The basics are done perfectly (branches are pristine, issue is linked, before/after pics are where they want to be).

You added Christina Or's info in perfectly - I can click on their picture to jump to their github and click on their name to jump to their slack. It renders as expected without changing anything in computer, tablet, or phone views. Wonderful work and nice job fixing that merge conflict too!

**Review by arcan9 — APPROVED** [review]
Great work @vraer! Merge conflict resolved and everything was set up correctly.

**Pull request merged**
