### PR TITLE
Refactor img tag in Getting Started page

### LINKED ISSUE #4415: img Tag Refactor: Getting Started page - `step-img-icon schedule.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/schedule.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/schedule.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by yujioshiro**
Fixes #4415

### What changes did you make?
  - Refactored the img tag in the Getting Started page

### Why did you make the changes (we will use this info to test)?
  - to maintain the consistency of img tags with the rest of the codebase
  
  ### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Refactored code, no visual changes to website.

### CODE REVIEW

**Comment by whitneywind** [comment]
Review ETA: 7/22
Availability: 1-3pm 7/22

**Review by whitneywind — APPROVED** [review]
Hey there, I see that the changes are being correctly merged from your personal branch into hackforla:gh-pages and that you linked to the issue. The trailing slash in the image tag was removed as specified in the original issue and there are no visual changes to the site. Nicely done!

**Review by ronaldpaek — APPROVED** [review]
Perfect, everything looks good on my end!

**Comment by ronaldpaek** [comment]
@roslynwythe done

**Review by adrianang — APPROVED** [review]
Hi @yujioshiro! Everything's looking good — the branching is set up correctly, the corresponding linked issue is linked, the requested change was made perfectly (removing the ending slash in the `img` tag on line 172), and this change didn't affect the appearance of the Getting Started page on all views in Docker.

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
