### PR TITLE
Joelfuelling update 4810 refactor tools data for metro ontime.md

### LINKED ISSUE #4810: Refactor Tools data for metro-ontime.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [metro-ontime.md](https://github.com/hackforla/website/blob/gh-pages/_projects/metro-ontime.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Docker, AWS, Observable
```
to:
```
tools:
  - AWS
  - Observable
```
Do not include docker even though it is in the current tools list, because it is actually categorized under languages, which is delivered by pulling the language for a repo from the GitHub API.
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by joelfuelling**
Fixes #4810-refactor-tools-data-for-metro-ontime.md

### What changes did you make?
- Updated meto-ontime.md 'tools' section requested changing it from a string format to list format. 
- Removed my personal formatting changes and folders that I added previously. 

### Why did you make the changes (we will use this info to test)?
Docker was removed because it is actually categorized under languages, which is delivered by pulling the language separately from the GitHub API.

<details>
<summary>Visuals before changes are applied</summary>

image)
image
)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
)
image
)

</details>

### CODE REVIEW

**Comment by LRenDO** [comment]
Availability: 7/31
ETA: 7/31

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @joelfuelling! Great work fixing the formatting and removing the additional files mentioned in #5103.  Some highlights from this PR were
- Branching was done correctly
- Pull request includes a description of what was changed
- Formatting was saved correctly
- Additional files were removed
- Code changes were made correctly

I do have a few requests for changes. 
- It looks like `.vscode` folder was deleted along with `settings.json`. Please add those back. We only want to make changes necessary for the specific issue being addressed.
- There was a visual change on the website (though small) because `Docker` was removed per the issue. Screenshots could be applicable here.  You can see the changes under the tools section for Railstats LA on the [the projects page](https://www.hackforla.org/projects/).
- For the "why" in the pull request, generally we want to put something about the reasoning behind the changes in the issue.  Often times, the reasoning can be found in the issue itself. In this case, it can be found in the `Overview` section.

Thanks again for taking the time to contribute to the website! We really appreciate all your effort in making the requested changes and dealing with the formatting issue!

**Review by jnomad21 — DISMISSED** [review]
@joelfuelling This looks good.  The requested changes were made and there is no additional formatting from the code formatted.  Branching is correct.

**Comment by joelfuelling** [comment]
Additionally,

Here are screenshots showing the corrected formatting.

As to the "why?", Docker was removed because it is actually categorized under languages, which is delivered by pulling the language separately from the GitHub API.

Screenshot 2023-07-31 at 4 24 39 PM
Screenshot 2023-07-31 at 4 24 05 PM

**Comment by t-will-gillis** [comment]
Hi @joelfuelling - Thanks for providing the description and the 'after' screenshots. Would you please add this info to the original issue description box itself? You will need to select the '. . . ' in the upper right, then edit as shown below.  

Also- please include both 'before' and 'after' screenshots. The code for the screenshots is on the PR when originally created, but here it is again:  

```
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<!-- Note, if your images are too big, use the <img src="" width="" length="" />  syntax instead of ![image](link) to format the images -->
<!-- If images are not loading properly, you might need to double check the syntax or add a newline after the closing </summary> tag -->

<details>
<summary>Visuals before changes are applied</summary>

![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image](Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

```

Screenshot 2023-08-06 091504

**Comment by LRenDO** [comment]
Hi @joelfuelling! I noticed you added screenshots. However, it looks like the `settings.json` file is still deleted, but that you had tried to restore it.  Please feel free to ping me if you need any help sorting out how to do it without your vscode settings interfering.

**Comment by joelfuelling** [comment]
@t-will-gillis Sure. I've edited the original comment box above to include the requested screenshots and information.

@LRenDO Yes, let's please connect. I've fancied up my VScode a bit, which is great when I'm working in a solo environment, but since collaborating more it's been the occasional nuisance.

**Comment by LRenDO** [comment]
@joelfuelling sounds good. I will reach out on Slack and we can sort it out.

**Pull request closed without merging**
