### PR TITLE
refactor-tag-img-find-4414

### LINKED ISSUE #4414: img Tag Refactor: Getting Started page - `step-img-icon find.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/find.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/find.png" alt="">
```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by Maia-Cochran**
Fixes #4414

### What changes did you make and why did you make them ?

  - removed slash at line 166 in HTML "getting started" file
  - changes made to be cohesive with codebase standards
  - changed ```.../>``` to ```...>``` at line 166

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- N/A

### CODE REVIEW

**Comment by vanessavun** [comment]
Availability: weekday evenings
ETA: 04/24/2023

**Review by vanessavun — APPROVED** [review]
Your pull request is coming from your username and is going into gh-pages.
You connected the associated issue and corrected the issue.
LGTM. Good job.

FYI: you don't have to tag for reviewers. People can self-assign to review the PRs since everyone needs to review 2 for every 1 pull request made.

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM - 3 PM
ETA: 4/25/23

**Review by Thinking-Panda — APPROVED** [review]
Hi @Maia-Cochran , Thank you for working on this issue. Merge branches look good. Code changes are clean and as mentioned in the issue. Website works perfect on my local machine. Well done!

**Review by chrismenke45 — APPROVED** [review]
Great work @Maia-Cochran! The changes look good in mobile, tablet and desktop views of the site.

**Pull request merged**
