### PR TITLE
added the missing span tag #5368

### LINKED ISSUE #5368: Refactor HTML: _includes/about-page/about-card-platform.html - Diversity
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
                    <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/diversity.svg" alt=""></span><span class="sub-head-text color-chocolate">Diversity, Equity & Inclusion</div>
```
to
```
                    <div class=""sub-card-head""><span class=""sub-head-image""><img src=""/assets/images/about/platform-header-elements/diversity.svg"" alt=""""></span><span class=""sub-head-text color-chocolate"">Diversity, Equity & Inclusion</span></div>

```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
4. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by kiran98118**
Fixes #5368 

### What changes did you make?
  - added the missing span tag
  
 

### Why did you make the changes (we will use this info to test)?
  - the span tag is missing in one section which makes code inconsistent

### CODE REVIEW

**Comment by Vinny02** [comment]
ETA: Sep 8 Noon
Availability: 6-12PM

**Review by Vinny02 — APPROVED** [review]
Well done @kiran98118 ! I can confirm you have merged to and from the correct branches, that the changes are correct, and the issue is successfully linked. Thank you for contributing!

**Comment by t-will-gillis** [comment]
Hello @kiran98118 - please add a note to PR #5396 stating that this PR is a replacement, then close 5396. Also, I will add @lateral-neck-stretch to the reviewers since they reviewed the first iteration.

**Comment by antho-zng** [comment]
Availability: 9–5pm ET
ETA: Sept 13 EOD (by 5pm ET)

**Review by antho-zng — APPROVED** [review]
Thanks @kiran98118! The changes address the original issue, and the page looks good on my locally hosted version!

**Pull request merged**
