### PR TITLE
Updated Labels project-profile-card-review-and-update-4489

### LINKED ISSUE #4489: Update labels: Issue Template: project-profile-card-review-and-update
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] #4749
- [x] Replace the following line
   ```
   labels: ["P-Feature: Project Info and Page, role: back end/devOps, role: front end, Size: Small, size: 0.5pt, time sensitive"]
   ```
   with
   ```
   labels: ['P-Feature: Project Info and Page', 'role: back end/devOps', 'role: front end', ': Complexity: Small', 'size: 0.5pt', 'time sensitive']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL]  

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by mlkara**
Fixes #4489

### What changes did you make and why did you make them ?

  - labels: ['P-Feature: Project Info and Page', 'role: back end/devOps', 'role: front end', ': Complexity: Small', 'size: 0.5pt', 'time sensitive']
  - Modified the project profile card review and updated template. 
  
**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository: 
https://github.com/mlkara/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml`
- This issue is part of epic #4307

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
- The Appearance of the website has not changed.

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 6/4 6-8 pm
ETA: EOD 6/4

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @mlkara thank you for working on this issue.  You may have noticed that above, some GitHub checks were not successful.  Our GitHub automation looks at the first line of the PR in order to find the linked issue.  Please change the first line to "Fixes #4489".  

Please see my Slack DM

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Thank you @mlkara for linking your issue and PR.  

Please delete the 3 lines of text surrounded by double quotes (starting with "For Reviewers and Merge Team" from the PR.  Then go to the issue and copy the URL of the test template from this [comment](https://github.com/hackforla/website/issues/4489#issuecomment-1565664486) into the section of the issue titled "Link for Reviewers", replacing the text:  `[REPLACE THIS TEXT AND BRACKETS WITH THE URL]`.  
Then go to the issue and copy these entire sections (the headings and the text underneath) of the issue from the issue into the PR:  

- For PR Reviewers and Merge Team
- Link for Reviewers
- For PM, Merge Team, or Tech Lead

Thank you!

**Review by roslynwythe — APPROVED** [review]
Thank you @mlkara for your work on this issue.  You setup the branches correctly, made the correct code change, tested the branch, and created a well-formed PR including a link to the original issue and a description of your work.

**Comment by JpadillaCoding** [comment]
Review ETA: 2 AM 6/8/23
Availability: 12am-5am 6/8/23 
(Night Owl)

**Comment by JpadillaCoding** [comment]
Hey @mlkara ,
- Your pull request is coming from the correct branch and is also being requested into the correct branch.
- The Correct issue is linked
- The change requested on the issue matches what you've changed on your branch
- Labels match the updated labels string in the issue when using the reviewer link. 
Good job!

**Pull request merged**
