### PR TITLE
Added github-handle for Conor McKiernan

### LINKED ISSUE #6722: Add github-handle for Conor McKiernan in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Conor McKiernan
```
with
```
- name: Conor McKiernan
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by terrencejihoonjung**
Fixes #6722 

### What changes did you make?
  - created a single variable "github-handle" under "name" variable" for Conor McKiernan

### Why did you make the changes (we will use this info to test)?
  - in the future github-handle will replace the github and picture variables, reducing redundancy in the project file

### Screenshots of Proposed Changes Of The Website
- Added variable to ems-triage-tracker.md file. No visual changes to the website.

### CODE REVIEW

**Review by dcotelessa — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Hi @dcotelessa 
There is not a specific format that needs to be followed when leaving a [PR review](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Comm), but there are specific items that a good PR review checks for, and it is helpful for everyone when the reviewer leaves specific (and encouraging) reasons for why the PR is being approved or why changes are being requested.  

Here is an example of a well-done review: https://github.com/hackforla/website/pull/6887#pullrequestreview-2075530707 When we look at this, we can see both that the reviewer has done a thorough job checking the PR, and the reviewee has done their job in creating the PR.

**Comment by pdimaano** [comment]
ETA: 5/31/24
Availability: Weekday evenings

**Comment by dcotelessa** [comment]
Hi @terrencejihoonjung,

- a single variable was created "github-handle" under "name" variable" for Conor McKiernan
- the description contains the issue number and the change, "github-handle" added

Thank you! Great job!

**Review by pdimaano — APPROVED** [review]
@terrencejihoonjung Good job: The branches are correct and the issue is linked. The webpage is visually unchanged on desktop, mobile and tablet. The correct file was updated with the requested information. Well done!

**Review by del9ra — APPROVED** [review]
HI @terrencejihoonjung,
* The pull request is done with the correct branch
* The issue is properly linked
* The PR clearly tells us what changes were made and why
* No visual changes were performed
Excellent work! Good job!

**Comment by del9ra** [comment]
ETA: 5/30/2024
Availability: 1-4 PM Friday

**Pull request merged**
