### PR TITLE
Update alt text for VRMS image

### LINKED ISSUE #4037: VRMS: Update alt text for the VRMS image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the VRMS image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/vrms.md`:

**From:**
```
alt: 'VRMS logo. VRMS homepage.'
```
**To:**
```
alt: 'Volunteer Relationship Management System (VRMS)`
```
**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  VRMS Page: https://www.hackforla.org/projects/vrms

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/vrms.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by ronaldpaek**
Fixes #4037 

### What changes did you make and why did you make them ?

  - Updated alt text for the VRMS image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### CODE REVIEW

**Comment by d-perez-8** [comment]
Availability: 3-6pm PST
ETA: 2 hours

**Review by d-perez-8 — CHANGES_REQUESTED** [review]
Welcome, @ronaldpaek! Thank you for completing this issue. The changes were made accordingly to the issue. The only thing to change is to remove the pictures of code from the pull request. We have that space to show any visual changes on the website. Instead, you can add "no visual changes to the website" since the code you have changed doesn't affect how the website looks.

**Review by d-perez-8 — APPROVED** [review]
Looks good!

**Comment by ronaldpaek** [comment]
> Looks good!

thank you

**Pull request merged**
