### PR TITLE
Add github-handle for Muyin Zheng in home-unite-us.md

### LINKED ISSUE #7190: Add github-handle for Muyin Zheng in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Muyin Zheng
```
with
```
- name: Muyin Zheng
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by izma-mujeeb**
Fixes #7190 

### What changes did you make?
  
  - Using spaces, I added a variable named github-handle to hold Muyin Zheng's github handle 

### Why did you make the changes (we will use this info to test)?
  
  - The reason why I had to add a github-handle variable was because eventually this variable is going to replace the github and picture variables for each member in the leadership team. By adding this variable, I am reducing redundancy and ensuring the code in the project file is efficient. 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
- No visual changes to the website

### CODE REVIEW

**Comment by FamousHero** [comment]
i. Availability: Mon-Fri: 5pm-6pm
ii. ETA: EOD 9/11/24

**Comment by tamara-snyder** [comment]
**Review ETA:** End of day 9/10/2024
**Availability:** Evenings

**Review by tamara-snyder — APPROVED** [review]
This looks great! I see you added the github-handle line using spaces and the appearance of the website hasn't changed. Well done :)

**Review by FamousHero — APPROVED** [review]
Hi @izma-mujeeb, every looks great! 
branch name is descriptive and has issue # in it. Clear and concise change description and reason.
Keep up the good work!

**Comment by Thinking-Panda** [comment]
@izma-mujeeb Nice work on this issue!

**Pull request merged**
