### PR TITLE
Add Heejung Hong to CoP Engineering on HfLA website

### LINKED ISSUE #6189: Update Communities of Practice: Engineering (Add Heejung Hong)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Heejung Hong
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U064M7X48SY
      github: https://github.com/heejung-hong
    picture: https://avatars.githubusercontent.com/heejung-hong
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #6183 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6183 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6183 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by elliot-d-kim**
Fixes #6189 

### What changes did you make?
* Added Heejung Hong's details to _data/internal/communities/engineering.yml as specified in issue

### Why did you make the changes (we will use this info to test)?
* To keep list of Engineering CoP leadership team on HfLA website up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

image

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 1/30/24

**Review by Thinking-Panda — APPROVED** [review]
@elliot-d-kim , Thank you for working on this issue. PR has a linked issue, and visuals of before and after code change. Merge branches look good. Code changes are clean and as mentioned in the issue description. Website works well in my local machine. Well done! Approved!

**Comment by Chrisklangley** [comment]
Availability: Weekdays 6:30pm-9pm
ETA: 2/02/24 EOD

**Comment by roslynwythe** [comment]
@elliot-d-kim I just wanted to mention that #6204 updates the same file so if a merge arises please be sure to note that there were two changes (removal of Chelsea Beck and addition of new Co-lead Adam Abundis).  Contact me if you need assistance.

**Review by jphamtv — APPROVED** [review]
Hey @elliot-d-kim  - Your pull request looks good:

- You branched off the correct base branch
- The issue is properly linked
- Your summary of changes is clear
- The before/after screenshots are very helpful
- I was able to verify the changes look good locally through Docker

Great work! Thanks for following PR best practices.

**Review by Chrisklangley — COMMENTED** [review]
Hey @elliot-d-kim 

Great work on your Pull Request!

you correctly linked your issue, the documentation you wrote is detailed. I am able to understand the changes you made and why they needed to be made.

in the _data/internal/communities/engineering.yml file I see that you added a new contributor  to leadership variable.

Keep up the great work!

**Pull request merged**
