### PR TITLE
Updated instructions for creating ~/.ssh prior to using ssh-keygen

### LINKED ISSUE #5695: Update CONTRIBUTING.md Section 2.7.f ii SSH for Windows - creating folder
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) we need to provide instructions for creating the folder `~/.ssh` prior to using `ssh-keygen` in order to avoid confusion for developers creating their initial SSH key.

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to "Section 2.7.f ii. Setting up SSH Keys for Windows"
- [x] Replace 
<pre><code>
##### **ii. Setting up SSH Keys for Windows**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
``` 
</code></pre>
with 
<pre><code>
##### **ii. Setting up SSH Keys for Windows**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
```
If the folder ~/.ssh does not exist, create it using
```bash
mkdir ~/.ssh
```
</code></pre>
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) 
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by rankdjr**
Fixes #5695

### What changes did you make?
Updated section [2.7.f ii of CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows)

FROM:

> ##### **ii. Setting up SSH Keys for Windows**
> 1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
> ```bash
> ls -al ~/.ssh
> ``` 

TO:

> ##### **ii. Setting up SSH Keys for Windows**
> 1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
> ```bash
> ls -al ~/.ssh
> ```
> If the folder ~/.ssh does not exist, create it using
> ```bash
> mkdir ~/.ssh
> ```

### Why did you make the changes (we will use this info to test)?
To provide instructions for creating the folder ~/.ssh prior to using ssh-keygen in order to avoid confusion for developers creating their initial SSH key.

For Reviewers: Do not review changes locally, rather, review changes at (https://github.com/rankdjr/website/blob/update-contributingmd-5695/CONTRIBUTING.md)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Hi @rankdjr please update the first line of the PR, with issue number.  Until that is done, our automation cannot link the PR with the issue, and so it is not ready for review.

**Comment by rankdjr** [comment]
> Hi @rankdjr please update the first line of the PR, with issue number. Until that is done, our automation cannot link the PR with the issue, and so it is not ready for review.

Updated

**Comment by roslynwythe** [comment]
Hi @rankdjr the first line of the PR should link to the associated issue, which is this case is 5695.  So the first line should read:
```
Fixes: #5695 
```

**Comment by rankdjr** [comment]
> Hi @rankdjr the first line of the PR should link to the associated issue, which is this case is 5695.  So the first line should read:
> ```
> Fixes: #5695 
> ```

Apologies. Updated.

**Comment by jphamtv** [comment]
Availability: Monday-Friday 12–2 PM, 8–10 PM (PST) 
Estimated ETA: 12/11/23

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hi @rankdjr thanks for updating the issue number, and for providing the review URL. I have two requests:

1. Could you clarify with @roslynwythe whether the instructions are for Windows or Mac? It looks like you updated it for Mac, but we may need Section 2.7.f ii updated for Windows. Easy mix-up since both the "replace" and "with" code in the action items mention "Mac".
2. This might be a bit extra, but for the sake of consistency, could we add blank lines between the instructional text and code snippets? Similar to how the other steps in the section are formatted. It won’t change how it appears to readers, but it'll help keep things neat for us in the backend.

When PR is ready for review, please click on the re-request review icon next to my username in the Reviewers section. 

Thanks!

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @rankdjr there was an error in the issue.  I just updated the original Action Item and I apologize for the error.  

@jphamtv thank you for your careful review.  It is appreciated!

**Comment by rankdjr** [comment]
@jphamtv 

1. Confirmed changes with @roslynwythe 
2. Spacing updated in CONTRIBUTING.md file to match consistency with document.

**Review by jphamtv — APPROVED** [review]
Thanks for the clarification, @roslynwythe. 

@rankdjr, your updates look great - nicely done!

**Review by roslynwythe — APPROVED** [review]
Great job @rankdjr for your work on this issue.  You updated the file as directed, setup the pull request correctly, and described your work.   Thank you

**Pull request merged**
