### PR TITLE
Added github-handle for Olivia Chiong

### LINKED ISSUE #6760: Add github-handle for Olivia Chiong in civic-tech-structure.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-structure.md` in the IDE
- [x] Replace:
```
- name: Olivia Chiong
```
with
```
- name: Olivia Chiong
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-structure

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by terrencejihoonjung**
Fixes #6760 

### What changes did you make?
  - created a single variable "github-handle" under "name" variable" for Olivia Chiong

### Why did you make the changes (we will use this info to test)?
  - in the future github-handle will replace the github and picture variables, reducing redundancy in the project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- Added variable to civic-tech-structure.md file. No visual changes to the website.

### CODE REVIEW

**Review by taylorbeee — APPROVED** [review]
Hey @terrencejihoonjung good work!

- The issue is properly linked
- Changes were summarized and implemented correctly
- No visual changes were made to the website
- 
Great job! Thanks for your contribution!

**Comment by vanessasinam** [comment]
Review ETA: 5/30/24 EST
Availability: 1PM-5PM (Mon-Fri)

**Comment by LRenDO** [comment]
Hi @vanessasinam! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.

**Review by vanessasinam — APPROVED** [review]
Hi @terrencejihoonjung 

The PR is done with the correct branch
The issue is linked properly
The code change is clean
The visual aspect of the webpage hasn't changed

Good work, thanks for your contribution!

**Pull request merged**
