### PR TITLE
added rel attribute to anchor tag

### LINKED ISSUE #6054: Resolve CodeQL alert 20 "Potentially unsafe external link"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 20](https://github.com/hackforla/website/security/code-scanning/20) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/20
- [x] Open the file `pages/communities-of-practice.html` in your IDE
- [x] Replace
```
<a href='{{ leader.links.github }}' target='_blank' title='GitHub Profile'><img class='leader-img--communities' src='{{ leader.picture }}'/></a>
```
with
```
<a href='{{ leader.links.github }}' target='_blank' title='GitHub Profile'><img class='leader-img--communities' src='{{ leader.picture }}' rel="noopener noreferrer"/></a>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/communities-of-practice
3. This issue is part of #5129

### PR DESCRIPTION
**Pull request by aidanwsimmons**
Fixes #6054

### What changes did you make?
- added rel attribute to anchor tag
- changed "" to ''
- Resolve CodeQL alert

### Why did you make the changes (we will use this info to test)?
  - sole action item 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

N/A

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
N/A

</details>

### CODE REVIEW

**Comment by njackman-2344** [comment]
Hey @aidanwsimmons, I see there's a security issue with the code. Try using ' ' instead of "" for rel and see if the security github action goes away. I believe that should clear that up.

So far branches look fine. Issue #6054 is linked (great) but also to leave merge checkbox clear for merge team to check that when they look at issue.

Also if you could please delete the 404 links underneath for consistency: Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes) and if there's no website screenshots associated with the PR, you can put n/a or something similar. 

Thanks :)

**Comment by w1ld-r** [comment]
Hey @aidanwsimmons, great job deducing the scope of the ticket and implementing the tag!

I second the feedback provided by @njackman-2344 and would only add the following:

**1. Be mindful of how you're using markdown in the pull request description.** I think you'll need a space between the hyphen (-) and the text to ensure it becomes a bullet point instead of a title. Not a big deal here, but it could cause confusion on larger issues.

**2. Under "Why did you make the changes (we will use this info to test)?"** it would be helpful to provide more information. Even though it's provided in the story, having a summary of the "why" on the PR makes it easier for the reviewer to understand the purpose. In this case, it's not a big deal because the issue is so small, but it'll be helpful to provide more info for larger stories.

Way to go! I'll take a look again once your changes have been made.

**Review by w1ld-r — CHANGES_REQUESTED** [review]
See comments above

**Comment by aidanwsimmons** [comment]
Fixes #6054

What changes did you make?
- added rel tag to anchor link + changed "" to ''
Why did you make the changes (we will use this info to test)?
- Resolve CodeQL alert
Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
Visuals before changes are applied n/a
Visuals after changes are applied n/a

**Comment by aidanwsimmons** [comment]
Fixes #6054

### What changes did you make and why did you make them ?

- added rel attribute to anchor tag
- changes "" to ''
- To resolve CodeQL alert

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)



<details>
  <summary>Visuals before changes are applied</summary>

  n/a

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  n/a

</details>

**Review by w1ld-r — DISMISSED** [review]
Looks good! The error appears to be gone and the markdown is much improved. Great work! :D

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @aidanwsimmons Good job on your first issue. Thanks for working with @gaylem and @njackman-2344 and addressing their comments. Everything is looking good, but I have a couple of additional comments. 
- The more minor one is regarding the response to "Why did you make the changes...?" This should be the reason for the original issue. For this issue the third bullet point is a great answer and you could respond with: "To resolve the CodeQL alert." (Note that this section can be edited by selecting the three dots in the upper right of the box.)
- The other comment is regarding your branch. Your `gh-pages` should be kept free of changes and updated with `hackforla:gh-pages`, and a new branch should be created whenever you work on a new issue. Please see the following section of [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) and other sections for the flow.

You may want or need to start over with a new PR and close this one. When/if you open the new PR, add us as reviewers. 

If you have questions, dm me on Slack. Thanks for working on this! It takes a little while to get the hang of GitHub...

**Pull request closed without merging**
