### PR TITLE
Img tag refactor events page

### LINKED ISSUE #5265: img Tag Refactor: _includes/events-page/our-locations-content.html - southla.png
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] #5270
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="location-image" src="../assets/images/hack-nights/southla.png" alt="South L.A."  />
```
to
```
<img class="location-image" src="../assets/images/hack-nights/southla.png" alt="South L.A.">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/our-locations-content.html
2. Webpage(s): https://www.hackforla.org/events/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by tkozek**
Fixes #5265 

### What changes did you make?
  -Removed the ending slash in the img HTML tag 
 
### Why did you make the changes (we will use this info to test)?
  -To keep the code base consistent with how we use HTML tags

### CODE REVIEW

**Comment by allison-truhlar** [comment]
ETA: Tuesday EOD
Availability: Tues 9-5pm ET

**Comment by DorianDeptuch** [comment]
ETA: Tuesday EOD
Availability: Tuesday Afternoon & Evening

**Review by DorianDeptuch — APPROVED** [review]
Hello @tkozek,

The ending slash in the img tag was correctly removed. You answered the 'What' and the 'Why' portions of your issue appropriately and since there were no visual changes, it was correct not to include that section. I ran this in my local environment and everything seems to be working fine.

One suggestion that I might add is when you are creating your branch names, please try to follow the convention outlined in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) by appending your issue number to the end of your branch name. I believe this helps with the automated GitHub Actions.

Otherwise, everything looks good to me. Great job!

**Review by allison-truhlar — APPROVED** [review]
Hi @tkozek! I'm echoing the previous reviewer - the changes in the code look good and there are no visual changes to the website, as expected. Like the other reviewer said, it would be good to append the issue number to the end of your branch name in the future.

I would also suggest keeping in the visual changes header in your opening comment of the pull request, and adding a line underneath that says "no visual changes" (as suggested here: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available). This way, it's easy to tell that the creator of the issue (you in this case) expected no visual changes, rather than accidentally left out this section.

Otherwise, great job on this issue!

**Comment by tkozek** [comment]
@DorianDeptuch @allison-truhlar 
Thank you for taking the time to review my pull request! I really appreciate the feedback from you guys and I will make sure to incorporate it in my next time!

**Pull request merged**
