### PR TITLE
removed issaac from website project

### LINKED ISSUE #2895: Update Current Project Team section for the Website Team
### Overview
As a member of the Hack for LA Website team, I want the information on the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website) to be up to date. For this issue, we will be updating the Current Project Team section of the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website).

### Action Items
- [ ] Remove Isaac Cruz from the leadership section in [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1)

### Resources/Instructions
- [Hackforla.org Website project information page](https://www.hackforla.org/projects/website)
- [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1)

### PR DESCRIPTION
**Pull request by maybleMyers**
Fixes #2895 

### What changes did you make and why did you make them ?

  -Removed Isaac Cruz from current project team section of the Hackforla.org website project information page
  -Removed lines 34-39 from _projects/website.md
  -Made changes to bring the information up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

### CODE REVIEW

**Comment by blulady** [comment]
ETA: Monday 3.21.22
Availability: Monday 3.21.22 1-6pm

**Comment by Sparky-code** [comment]
ETA: 3.20.22
Avail: M/W/F 7-9p

**Review by Sparky-code — COMMENTED** [review]
@Benji-Montgomery looks like you deleted the appropriate area to update the website project cards. Nice going!

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: today, March 20, 2022

**Review by tamara-snyder — APPROVED** [review]
Hi Ben, great work on this issue! I can see that you've successfully removed Isaac from the leadership section in website.md and the changes appear as expected when running the site locally. 

I'm going to merge this now so that you can pick up one of the important small issues as discussed in the meeting.

**Pull request merged**
