### PR TITLE
Removed Yua Guan from lucky parking page#5808

### LINKED ISSUE #5808: Update Project Profile: Lucky Parking (Remove Yao Guan)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Yao Guan
    role: Quant UXR
    links:
      slack: 'https://hackforla.slack.com/team/U03F35T4PND'
      github: 'https://github.com/yaoguan'
    picture: https://avatars.githubusercontent.com/u/41702875
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by james-aguirre**
Fixes #5808

### What changes did you make?
  - Removed Yao Guan from lucky parking page

### Why did you make the changes (we will use this info to test)?
  - User is inactive

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-08 at 4 46 08 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-08 at 4 47 29 PM

</details>

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  11/12/2023
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hi @james-aguirre,
Great work! Everything looks good: branching done correctly, link to issue, concise descriptions of what you did, i.e remove Yao Guan from _projects/lucky-parking.md,
 and why the changes were needed, and you included  screenshots of before and after.
I was able to verify the changes made on the Lucky Parking page.
Thanks for working on this issue!

**Comment by tonyvang** [comment]
Avail: This evening, after 7pm
ETA: Tonight 11/13/2023

**Review by tonyvang — APPROVED** [review]
Hello @james-aguirre,

Your pull request appears correctly branched, with the correct linked issue. Your changes to remove the inactive member from the page are appropriate and worked as intended upon testing, just as in your included B&A screenshots. Thanks for your work! I am approving this pull request.

**Comment by drakenguyen4000** [comment]
Nicely done james-aguirre.  Yao Guan has been removed from lucky parking page and the page is displayed with him.

**Pull request merged**
