### PR TITLE
Add github-handle variable for Yasaman Roostaeian in design-systems.md

### LINKED ISSUE #6696: Add github-handle for Yasaman Roostaeian in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Yasaman Roostaeian
```
with
```
- name: Yasaman Roostaeian
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Dartis4**
Fixes #6696 

### What changes did you make?
  - Added the github-handle variable to _project/design-systems.md

### Why did you make the changes (we will use this info to test)?
  - It serves as a placeholder for when future changes are made to utilize this variable

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No Visual Change

### CODE REVIEW

**Comment by Jperparas** [comment]
**Availability:** 4/20-4/21
**ETA:** eod 4/21

**Comment by moazDev1** [comment]
Review ETA: 4/22
Availability: 6-10 PM Sat - Mon

**Review by moazDev1 — APPROVED** [review]
Great job @Dartis4  on:

1. Using the correct branch for your pull request.
2. Accurately linking the issue.
3. Making code changes as requested in the issue
4. Ensuring no visual changes across multiple browsers (Safari, Firefox, Chrome) in both desktop and mobile views.
5. Applicable and clean code changes.

**Keep going!!**

**Review by Jperparas — APPROVED** [review]
Good job on this good first issue!

1.  Branch is labeled correctly and going into the correct branch
2.  appropriate issue is linked
3.   code updated as directed by issue
4.  no visual changes.

Get back out there!

**Pull request merged**
