### PR TITLE
Updated alt text for join us footer mobile image for WCAG adherence

### LINKED ISSUE #3878: Program Areas: Update alt text for join us footer mobile image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Program Areas` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `/pages/program-areas.html`:

**From:**
```
alt="join us card image"
```

**To:**
```
alt=""
```

- [x] Ensure that the corresponding `Program Areas` page stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

### Resources/Instructions
- https://www.hackforla.org/program-areas

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `/pages/program-areas.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/075ce5f7d67c7732e258148b0f4a1a9342095e26/pages/program-areas.html#L79

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by nnr-nnr**
Fixes #3878 

### What changes did you make and why did you make them ?

  - Updated the alt text of the image in the join us footer (mobile version) on the Program Areas page to make the HfLA site more inclusive and accessible (ie, adhere to Web Content Accessibility Guidelines, or WCAG)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updating alt text; no visual changes to the website.

### CODE REVIEW

**Comment by janice87** [comment]
Review ETA: EOD 3/22/22
Availability: 5-8 PM EST Wednesday

**Comment by RyanGehris** [comment]
Review ETA: EOD 3/22/23
Availability: 5-8 PM PST M-F

**Review by janice87 — APPROVED** [review]
Good job on this issue! The pull request is done in the correct branch and the issue is linked correctly. The issue is addressed and only the mobile image alt text is updated. The change does not affect the physical appearance of the website. This looks good and is approved.

**Review by RyanGehris — APPROVED** [review]
Great job reviewing the issue, and making the correct changes. It is awesome to see the Website become more inclusive everyday! Thank you for working on this.

**Comment by mademarc** [comment]
Review  3/22/2023
Availability: 4:30 PM

**Review by mademarc — APPROVED** [review]
Hey @nnr-nnr  the variable removal on the alt was well done so good job.

**Pull request merged**
