### PR TITLE
Add GitHub Link to the Community Of Practice

### LINKED ISSUE #2489: Add GitHub link to community of practice: Project/Product Management
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to update the community of practice GitHub links so we can provide the end-user with more information about our communities.

### Action Items
- [x] Add the following lines on line 32 of the file `_data/internal/communities/project-management.yml`:
```
  - name: Github
    url: https://github.com/hackforla/product-management
```
So that the end result looks like this:
```
links:
  - name: Slack
    url: https://app.slack.com/client/T04502KQX/C010LNXH2JY/details/
  - name: Github
    url: https://github.com/hackforla/product-management
```
- [x] Ensure that the Communities of Practice page on your local environment reflects your changes
    - [x] The local environment url will be localhost:4000/communities-of-practice
    - [x] A "View GitHub" button should appear on the Project/Product Management page card after the change
    - [x] Clicking the button should resolve to the Product Management GitHub repository

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_data/internal/communities/project-management.yml`
- [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/6c445b6d092b73ec6457a989fce587e20bc133e2/_data/internal/communities/project-management.yml#L29-L32

### PR DESCRIPTION
**Pull request by lrobinson823**
Fixes #2489

### What changes did you make and why did you make them?

  - Added GitHub Link to the Community Of Practice
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>

<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>

</details>

### CODE REVIEW

**Comment by lindseyindev** [comment]
@lrobinson823 this issue solution looks good and works as expected, good work! 

One thing before I can approve - will you please edit the pull request details to add the before and after images to show the visual change since a new button is added to the website
like this:

<details>
<summary>Visuals before changes are applied</summary>
  
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
(Github button added)
</details>

**Review by lindseyindev — CHANGES_REQUESTED** [review]
[resubmitting feedback under Review - Request Changes]

@lrobinson823 this issue solution looks good and works as expected, good work! 

One thing before I can approve - will you please edit the pull request details to add the before and after images to show the visual change since a new button is added to the website
like this:

<details>
<summary>Visuals before changes are applied</summary>
  
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
(Github button added)
</details>

**Comment by anthonysim** [comment]
@lrobinson823 LGTM! Just waiting for the edits that @lindseyindev requested above and I'm good to approve! Good job!

**Comment by lrobinson823** [comment]
@anthonysim 

Updated.

**Review by lindseyindev — APPROVED** [review]
Looks good to me!

**Comment by anthonysim** [comment]
> @anthonysim
> 
> Updated.

Thanks! LGTM!

**Review by anthonysim — APPROVED** [review]

**Pull request merged**
