### PR TITLE
Updated alt text for LA TDM calculator image to adhere to WCAG

### LINKED ISSUE #4041: LA TDM Calculator: Update alt text for LA TDM Calculator image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the LA TDM Calculator image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/tdm-calculator.md`:

**From:**
```
alt: 'LA TDM Calculator Landing Page (Mock Up)'
```
**To:**
```
alt: 'LA TDM Calculator'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  LA TDM Calculator Page: https://www.hackforla.org/projects/tdm-calculator

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/tdm-calculator.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by MicahBear**
Fixes #4041 

### What changes did you make, and why did you make them?

  -Changed the image alt property value within _projects/tdm-calculator.md to adhere to WCAG
 **From:**
```
alt: 'LA TDM Calculator Landing Page (Mock Up)'
```
**To:**
```
alt: 'LA TDM Calculator'
```

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- no visual changes

### CODE REVIEW

**Review by jefflueck — APPROVED** [review]
Looks great. Nice work!

**Comment by MarkWiltberger** [comment]
**Availability:** Daily 10am-6pm ET (7am - 3pm PT)

**ETA:** 03/09/2023 Thu 6pm ET (3pm PT)

**Comment by bootcamp-brian** [comment]
Review ETA: 12:45pm
Availability: Today before 5pm

**Review by bootcamp-brian — APPROVED** [review]
Updated the correct file, branches are setup right, the issue is properly linked and the changes are reflected in local environment. Great job!

**Review by MarkWiltberger — APPROVED** [review]
Great job! I love what you have done, @MicahBear ! You have made the change precisely. The pull request is done with the correct branch. There is a linked issue. The issue is to change the `alt text` for the image in the `_projects/criminal-sentencing.md`  file.  The change did not result in visible changes in the local dev environment, as expected. The code was inspected on the **Files changed** tab and the html elements were inspected in the local dev environment and appear to be correct. The changes fulfill the ABC’s: they are _applicable_, they do not _break_ the main website, and they are _clean_. The changes are approved.

**Pull request merged**
