### PR TITLE
Update toolkit page subheadings

### LINKED ISSUE #1479: Update Toolkit Page subheadings
### Overview
We need to update the 'Guides' and 'Resources' subheading sections (and their buttons) in the Toolkit page to better align the page, and accommodate upcoming changes to the mobile version of the filter banner.

### Action Items
- [x] Review images below (under arrows) to see how the updated page should look (or see the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)
- [x] Remove "(We made these!)" text after 'Guides' subheading
- [x] Evenly align both the buttons and subheadings ("Guides" and "External Resources") with the edges of the guide cards in all screen sizes, desktop through mobile, as seen in the screenshots below and Figma

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit/)
[Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)

<details>
<summary>How it looks now:</summary>
<br>
Screen Shot 2021-04-27 at 6 45 45 PM
</details>

<details>
<summary>How it should look:</summary>
<br>
Screen Shot 2021-04-27 at 6 45 23 PM
</details>

### PR DESCRIPTION
**Pull request by macho-catt**
Fixes #1479 

### What changes did you make and why did you make them ?

  - Placed suggest-guide-group div as a child of toolkit-flex-container for both the guides and external resources so that it becomes part of the grid, along with the guides
  - Set suggest-guide-group to span the entire column, which fixes the heading and button alignments so they align with the edges of the first and last guides
  - Removed "We made these" from subheading
  - Removed commented code and fixed some tab alignments
  - For external resources, wrapped the resources under a new div: external-resource-container. Without this div, the external resources sit to the left (instead of centered like in the figma) because of how grid works. To fix this, added media queries so that at certain breakpoints, this div is either a flex (above 1632px), a grid (below 1632px until above mobile) and back to flex (below mobile). 
  - Added comment under _toolkit.scss to explain the above in the code:
  _Refer to issue #1999. This part, the accompanying divs in toolkit.html (lines 89 and 109),
  and $screen-desktop-large under layout.scss were added to take into account how the external
  resources look at a certain breakpoint ($bp-desktop-large-up). As of 7/22/2021, there are only three resources in the list.
  Since suggest-site-group div was added to the grid and takes up the entire first row, the rows that
  follow does not go to the center and instead aligns to the left. The media queries here fixes that.
  When there are four or more resources added in the future, this part (and the divs in toolkit.html)
  can be removed._

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Full page before</summary>

toolkit-full-before

</details>

<details>
<summary>Full page after</summary>
  
toolkit-full-after

</details>

<details>
<summary>Guides responsiveness</summary>
  
guides

</details>

<details>
<summary>External Resources responsiveness</summary>
  
external

</details>

### CODE REVIEW

**Review by adam-abundis — DISMISSED** [review]
@macho-catt I was able to pull the changes and verify locally. It looks awesome. Thank you for your detailed pull request and comment to notate the addition of the `$screen-desktop-large` and implementation for the `Toolkit` page. Great work.

**Review by Abel-Zambrano — CHANGES_REQUESTED** [review]
Hey, @macho-catt it's looking good, but there's still unalignment happening below 960px width. If you could please make changes so it's aligned with cards before it gets centered in mobile-screen.

**Comment by Abel-Zambrano** [comment]
https://user-images.githubusercontent.com/67209686/127588929-9013771c-adab-4edd-ba7a-d58b86d1ecc7.mov

**Comment by macho-catt** [comment]
@Abel-Zambrano good catch! I'll work on that, thanks!

**Comment by macho-catt** [comment]
New commits for @Abel-Zambrano's change request

### What changes did you make and why did you make them ?

- Under _toolkit.scss, fixed grid-template-column for below desktop view so that the header and the guides are still aligned on both edges
- Made a new media query for below tablet view, and placed anything that uses below tablet view under that new media query
- Added new class, external-resources-text for the external resources header because at a certain width below tablet view, it wraps the text and centers it, which makes it not aligned to the front edge. The new class aligns it to the left below tablet view.
- Fixed scss indents

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)



<details>
<summary>New full page (still looks the same)</summary>

full-page


</details>

<details>
<summary>Guides header responsiveness</summary>
  
first-header


</details>

<details>
<summary>External Resources header responsiveness</summary>
  
second-header


</details>

**Review by Abel-Zambrano — CHANGES_REQUESTED** [review]
@macho-catt Wow! That looks great! Sorry, one more thing, I must've missed it. On file _toolkit.scss, can you move line 308's code for h2's margin-bottom into media query bp-below-mobile (line 314) so it can be aligned with the button on the right? 

### How it looks now
Screen Shot 2021-07-29 at 22 36 31

### How it should look
Screen Shot 2021-07-29 at 22 37 12

**Comment by Abel-Zambrano** [comment]
This change will also give the h2 and button some breathing room when viewed on mobile-screens

**Comment by macho-catt** [comment]
Thanks @Abel-Zambrano 

### Changes

- Fixed alignment so Guides and External Resources are aligned with the button

</details>

<details>
<summary>Fixed Header Alignment</summary>
  
header-alignment


</details>

**Review by Abel-Zambrano — APPROVED** [review]
Awesome work! @macho-catt

**Review by adam-abundis — APPROVED** [review]
Great job @macho-catt. Thank you for your edits.

**Pull request merged**
