### PR TITLE
update on issue 5878

### LINKED ISSUE #5878: Add new variable github-handle to member Sabrina Heasley in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
  - name: Sabrina Heasley 
```
with
```
  - name: Sabrina Heasley 
    github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [x] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md 
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by Shikha0428**
fixes #5878 

### What changes did you make?
  - Replace  name: Sabrina Heasley with - name: Sabrina Heasley 
                                                                       github-handle: 
 

### Why did you make the changes (we will use this info to test)?
  - We need to create a single variable github-handle to hold the github handle for each member of the leadership 
     team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project 
     file.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Review by roslynwythe — APPROVED** [review]
Hi @Shikha0428 great job on this issue.  The branches are formed correctly, the code change is clean and correct, you have described your work, and it checks out in the browser.  Thank you!

**Comment by roslynwythe** [comment]
Hi @kezzaam please let us know your availability and ETA to review this issue.  Thanks!

**Review by freaky4wrld — APPROVED** [review]
@Shikha0428 thanks for taking the issue, the branches are good, issue linked is great, description provided is great as well. Docker testing is successful too.

Please check off the action items in the issue, thanks

PR approved!!

**Comment by Shikha0428** [comment]
@roslynwythe and @freaky4wrld Thank you.

**Pull request merged**
