### PR TITLE
Create inactive-members json for GHA

### LINKED ISSUE #6460: Create new file `inactive-members.json`
### Overview
We are adding a new functionality to the `schedule-monthly.yml` GHA: before we remove inactive members from the 'website-write' team, we want to be sure that the bot sent a notification in the previous month. Otherwise, there are some members that could be removed from the 'website-write' team without receiving the  30 day warning. Note: this issue **_does not_** require testing of the `schedule-monthly.yml` GHA.  

### Action Items
- [x] Locate the directory `github-actions/utils/`
- [x] Create a new directory/file under the `utils` directory and name it: `_data/inactive-members.json`
- [x] Copy the contents of [this file](https://github.com/t-will-gillis/website/blob/edits-6193-consolidate-3-13/github-actions/utils/_data/inactive-members.json) into `inactive-members.json`.

### Resources/Instructions
This issue is a dependent for #6193

### PR DESCRIPTION
**Pull request by vincendp**
Fixes #6460

### What changes did you make?
  - Created `_data/inactive-members.json` 
  - Copied contents from [here](https://github.com/t-will-gillis/website/blob/edits-6193-consolidate-3-13/github-actions/utils/_data/inactive-members.json) into `_data/inactive-members.json` 

### Why did you make the changes (we will use this info to test)?
  - Create `_data/inactive-members.json` for use by GitHub Actions to handle inactive members

### Screenshots of Proposed Changes Of The Website
- No visible changes

### CODE REVIEW

**Comment by freaky4wrld** [comment]
@vincendp in the PR description, make sure you have the Screenshot section, and just mention `No visual changes` , do this and I'll approve the PR

**Comment by vincendp** [comment]
> @vincendp in the PR description, make sure you have the Screenshot section, and just mention `No visual changes` , do this and I'll approve the PR

Edited. Thank you

**Review by freaky4wrld — APPROVED** [review]
@vincendp thanks for taking up the issue, branches looks good, the issue is linked correctly, new file is added as specified.

PR approved

**Review by t-will-gillis — APPROVED** [review]
Hey @vincendp Branches are good, linked back to the original issue, description of what was changed and why is concise, and code changes are clean.

Great job, thanks for contributing!

**Pull request merged**
