### PR TITLE
Update CONTRIBUTING.md Section 2.7.f i SSH for Mac - creating folder

### LINKED ISSUE #6240: Update CONTRIBUTING.md Section 2.7.f i SSH for Mac - creating folder
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING - 2.7.f i "Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac) we need to provide instructions for creating the folder `~/.ssh` prior to using `ssh-keygen` in order to avoid confusion for developers creating their initial SSH key.

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to "Section 2.7.f i. Setting up SSH Keys for Mac"
- [x] Replace 
<pre><code>
##### **i. Setting up SSH Keys for Mac**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
``` 
</code></pre>
with 
<pre><code>
##### **i. Setting up SSH Keys for Mac**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
```
If the folder ~/.ssh does not exist, create it using
```bash
mkdir ~/.ssh
```
</code></pre>
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING - 2.7.f i "Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac) 
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by elisetvy**
Fixes #6240 

### What changes did you make?
  - Update instructions for creating ~/.ssh folder

### Why did you make the changes (we will use this info to test)?
  - To avoid confusion for developers creating their initial SSH key
  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/elisetvy/hfla-site/blob/update-contributing-ssh-6240/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-05-08 at 09 11 58

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-05-08 at 09 12 15

</details>

### CODE REVIEW

**Comment by marioantonini** [comment]
Review ETA: EOD 5/8/24

**Review by marioantonini — APPROVED** [review]
PR done on the correct branch.
Issue linked properly.
Code looks good!

@elisetvy thanks for working on the issue.

**Comment by Jperparas** [comment]
**review ETA:** EoD 5/9

**Review by Jperparas — APPROVED** [review]
Good Job on this issue @elisetvy!
- Branch is correct
- Relevant issue is linked
- Code Changes are appropriate
- Visual changes properly documented

**Pull request merged**
