### PR TITLE
Update HfLA team roster and add tool 3520

### LINKED ISSUE #3520: Update Project Profile: HackforLA website team
### Overview
As a product manager of the hackforla.org website team I want my project's details to be up to date on the HackforLA website

### Project card
URL of my project card: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md

### Action Items

- [X] hackforla.org website Team Leadership
   - [X] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [X] leadership
         - [X] Name
         - [X] GitHub handle
         - [X] Role
         - [X] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] WIKI
         - [x] Site
      - [x] technologies
      - [x] partner
      - [X] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

### PR DESCRIPTION
**Pull request by plang-psm**
Fixes #3520

### What changes did you make and why did you make them ?

Changes to the Hack for LA Team page: **Project Team and Tools section.**

*** Please note, I had an auto format upon save setting in my editor that changed single quotes to double quotes. This doesn't seem to have any impact on the page. The setting I changed prior to my PR was incorrect so it formatted itself to the file but I have since solved the setting for future issues that I work on. 

#### Project Team
 Remove
  - Simone Campbell
  - Providence Onyenekwe
  
Insert (including name, role, slack, github and picture) 
 - Akram Nour
 - Bishr Aboobaker
 - Vaisali Krishna Kumar

#### Tools
Add to tools
 - 1Password

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

pm-team-before-3520

tools-before-3520

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
pm-team-update-3520
tools-update-3520

</details>

### CODE REVIEW

**Comment by lilyarj** [comment]
ETA: 9/8
Availability: 2hrs

**Comment by lilyarj** [comment]
@plang-psm Everything looks good! But was 1password supposed to be added to the tools section?

**Review by lilyarj — DISMISSED** [review]
Everything looks good, site doesn't break!

**Comment by giroz** [comment]
ETA: 9/8/22
Availability:  3 hours

**Review by giroz — DISMISSED** [review]
Looks great!  Nice job.

**Review by blulady — CHANGES_REQUESTED** [review]
This comes from the right branch and goes into [hackforla:gh-pages](https://github.com/hackforla/website). It has a linked issue and the PR directly addresses the request to add and remove folks from the current project team on the project page. The changes look great in the browser, all the links work correctly. The source code is all uniform except for the issue with the double quotation marks vs the single. 
Great Job!!! I am going to ask that you change the double quotes to single in the interest in maintaining uniformity on the website but as soon as you do that I want to merge this PR.

**Comment by plang-psm** [comment]
Thanks everyone! @lilyarj @giroz @blulady I just finished revising the double quotes to single quotes. Website ran fine on my end. Let me know if any other changes are needed.

**Review by blulady — APPROVED** [review]
Looks good. Not a " in sight. It looks great when I throw it up locally  and all the links work. Good Job!!!

**Pull request merged**
