### PR TITLE
img Tag Refactor in Contributing.md page 

### LINKED ISSUE #5146: img Tag Refactor: CONTRIBUTING.md  giphy-downsized-large.gif
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open 'CONTRIBUTING.md' and navigate to Section 3.1.b
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="https://media.giphy.com/media/WT7SDqqKLWnjC1ppHV/giphy-downsized-large.gif" />
```
to
```
<img src="https://media.giphy.com/media/WT7SDqqKLWnjC1ppHV/giphy-downsized-large.gif">
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket. 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
3. This issue is part of #6453

### PR DESCRIPTION
**Pull request by Kle012**
Fixes #5146

### What changes did you make?
  - Change an img HTML tag ending with a slash () to an img tag without an ending slash () 

### Why did you make the changes (we will use this info to test)?
  - Ensure the codebase is consistent with how img HTML tags is being used

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- Changing the img closing tag. No visual changes to the website.

### CODE REVIEW

**Comment by Anahisv23** [comment]
ETA: EOD 
Availability: M - F 11am - 5pm

**Review by Anahisv23 — CHANGES_REQUESTED** [review]
Hi @Kle012 thanks for working on this issue. You correctly changed the  tag on CONTRIBUTING.md on line 881 and left no space before the closing bracket. The linked issue is correct and into and from branch look correct. 

However I see that you added some \ on line 43 and 46 on CONTRIBUTING.md. I'm sure you probably added them by mistake but once you remove these \ you should be good to go!

**Comment by Kle012** [comment]
Hi @Anahisv23,
I've been trying to remove these backslashes, but for some reason, they keep getting added back in automatically whenever I click save. I've checked the documents on the website, and it seems there are no changes; the backslashes are not visible on the site. But otherwise, I'm not sure how to resolve this issue.

**Comment by Anahisv23** [comment]
Hi @Kle012, hmm thats strange. Have you tried removing these backslashes on your Github PR on the files changed tab? You could try that and see if that removes the backslashes. Let me know if that works.

**Comment by Kle012** [comment]
Hi @Anahisv23, I was able to remove the backslashes. Thank you so much for your advice. Please let me know if there is any issue.

**Review by Anahisv23 — APPROVED** [review]
Hi @Kle012 thanks for addressing the backslash issue and no problem I'm glad that solved the problem. Everything looks good on my end. Approved!

**Review by jphamtv — APPROVED** [review]
Hi @Kle012 - Great work on this pull request!
- You created the pull request using the correct branch.
- The issue is properly linked to the pull request.
- Your summary of changes is clear and concise.
- Your code change is clean and accurate. 

Thanks for your contribution!

**Pull request merged**
