### PR TITLE
Complete refactor/standardization of all buttons within Home Page 

### LINKED ISSUE #2104: Complete refactor/standardization of all buttons within Home Page
### Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

### Action Items
- [x]  Make the 8 recommended edits for the buttons from the spreadsheet below (4 files will be updated)
  

1.  - [x] Update **line 4** of `website/_includes/donate-button.html` with HTML from the `Reccomendation` column
2.  - [x] Update **line 5** of `website/_includes/footer.html` with HTML from the `Reccomendation` column
3.  - [x] Update **line 2** of `website/_includes/_includes/home-getting-started.html` with HTML from the `Reccomendation` column
4.  - [x] Update **line 10** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
5.  - [x] Update **line 14** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
6.  - [x] Update **line 25** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
7.  - [x] Update **line 30** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
8.  - [x] Update **line 35** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Home page
- [x] Update CSS to ensure the buttons remain the same as before
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

### PR DESCRIPTION
**Pull request by Zak234**
Fixes #2104 

### What changes did you make and why did you make them ?
  -Made the 8 changes detailed in the issue which removed the button tag from donate-button.html, footer.html and contact-us.html. This was to help standardize the code.
  -Changed the display for class btn--donate-footer from block to table so the donate button in the footer showed up correctly.
  -Changed the display for class column from flex to block so that the Getting Started and Transport buttons were correctly formatted under their text.
  -Added a new class in _cards.css called page-card-md-VWU and applied it to the Volunteer With Us card along with editing the volunteerWithUs class to give the card proper formatting and spacing.
  -Edited the margin for btn--donate-header so that the donate button has proper spacing in the header
  -Added padding for btn--donate-header when on smaller screens so that the text is properly displayed in the donate button.
  -Commented code out in header-links as it was messing with the location of the donate button on smaller screens and the code was not observably affecting the other classes the class was applied to

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
None, the website should look the same.

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 5 Hours
ETA: EOD 7/23/22

**Review by BeckettOBrien — APPROVED** [review]
I don't have access to the google sheet linked in the issue but the changes are to the right lines of the right files and the site looks the same. Good job!

**Comment by blulady** [comment]
ETA: 7.24.22
Availability: 7.24.22, 7.25.22

**Comment by blulady** [comment]
Hey, was this the issue that you were showing us those slight visual variations on? If it is, could you grab some screenshots of the differences for documentation?

**Comment by Zak234** [comment]
I fixed those, it should look the same now.

**Review by blulady — COMMENTED** [review]
The branches are correct. The linked issue is correct. The pr addresses the issues from the issue. There are a few lines that don't match the recommendation code, if you had to make these changes in order to get the code to look the same, I'll merge it but if it was an error let's update it. In line 4 of _includes/donate-button.html "btn--default" is left out from the recommendation code.  There is a change on _includes/forms/contact-us.html that is not included in the recommended file <div class="page-card card-secondary page-card-md-VWU page-card--home page-card--home-volunteer">.

**Review by blulady — APPROVED** [review]
Apparently you did need to make those changes.

**Pull request merged**
