### PR TITLE
Edited agile.yml issue 2792 

### LINKED ISSUE #2792: Edit content field and remove type field from agile.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/agile.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/agile.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/agile.yml#L4
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/agile.yml#L11

### PR DESCRIPTION
**Pull request by maybleMyers**
Fixes #2792

### What changes did you make and why did you make them ?

  -changed line 4 from content to content-type to make purpose clearer
  -removed line 11 because it is redundant
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to website.

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
Review ETA: End of day 3/11/22
Availability: Friday 8-10 PM Pacific Time

**Comment by answebdev** [comment]
Review ETA: 3/11/2022 (end of day)
Availability: 3 hours

**Review by answebdev — DISMISSED** [review]
@Benji-Montgomery Thank you for submitting your PR. For this issue, you were supposed to change line 4 from `content: Image` to `content-type: image`, as well as remove line 11 for the type field in the file, `_data/internal/credits/agile.yml`, which I can see that you did. Great job with that!

In the original issue, the word `image` is lowercase, while you used uppercase in your change (`Image`). I don't know if this needs to be lowercase as in the original issue, since all of the values in the file use uppercase. Perhaps @SAUMILDHANKAR can chime in when he does his review.

Also, one final thing: Please add this PR to the Project Board. Thank you.

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@Benji-Montgomery Thanks for working on this issue. As mentioned by @answebdev, request you to make `Image` to lowercase `image` in line4 so it is consistent with the issue requirements. Also, please add your PR to the project board. Once you have made changes, please request a re-review. Thank you.

**Pull request closed without merging**
