### PR TITLE
Updated credit for Dicussion Teamwork image

### LINKED ISSUE #3131: Edit credit for Discussion Teamwork image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Discussion Teamwork credit in Figma</summary>
     
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be merged into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] For `_data/internal/credits/product-management.yml`,
  - [x] Change the file name from `product-management.yml` to `discussion-teamwork.yml`
  - [x] Change `title: Product Management` to `title: Discussion Teamwork`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'Product Management Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #3131 

### What changes did you make and why did you make them ?

For `_data/internal/credits/product-management.yml`,
  - Changed the file name from `product-management.yml` to `discussion-teamwork.yml`
  - Changed `title: Product Management` to `title: Discussion Teamwork`
  - Changed `content: icon` to `content-type: image`
  - Changed `used-in: Home` to `used-in: Homepage`
  - Changed `alt: 'Product Management Icon'` to `alt: ''`
  - Removed `type: icon`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by trishajjohnson** [comment]
Availability: 1hr
ETA: EOD today, 7/7/22

**Review by trishajjohnson — APPROVED** [review]
Took a look at your PR.  It was done on the correct branch, you provided a linked issue and a detailed description of the changes you made.  After reviewing your changes both in the source code and on the frontend, everything looks to be in order.  You also provided clear screenshots of the changes reflected on the frontend. Good job and thanks for your hard work!!

**Comment by Wny-Duong** [comment]
ETA: 7/9/22, Saturday
Availability: 2 hours

**Review by Wny-Duong — APPROVED** [review]
Changes match with what was requested in the original issue, the hyperlinks work, and the changes in the after image match what I'm seeing when I host locally. Good work!

**Comment by JessicaLucindaCheng** [comment]
Not sure why the automations isn't automatically linking the issue to this pr even though it has `Fixes #3131` in the first post above.

I went ahead and manually connected the issue to this pr.

**Pull request merged**
