### PR TITLE
Removed alt text fields from 2FA.html, creating-kanban-project.html, and figma-for-opensource-projects.html - #2928

### LINKED ISSUE #2928: Remove unused alt-text field in toolkit guides html files: 2FA, creating-kanban, figma (file names abbreviated)
### Overview
As a developer, I want to make sure unused code is removed from the codebase in the guide pages' HTML files, so that 
- time to load the website is as low as possible, 
- it's easier to understand the code, and 
- time to review the code is reduced. 

For this issue, we will remove the unused alt-text fields from the guide pages' HTML files.

### Details
At the top of each guide pages' HTML file, there is a section containing YAML front matter, which contains variables that can be accessed using Liquid tags. (See the links in the Resources/Instructions section for more information about front matter and Liquid tags.) 

In the front matter of each guide pages' HTML file, there are the variables: `svg` and `alt-text`. `svg` field contains the location of a decorative image and `alt-text` is the alt text associated with the `svg` image.  Currently, `alt-text` is not used anywhere in our codebase since the images are not used within an `img` HTML tag and the images are displayed through svg HTML tags. 

Moreover, the alt text for all the images should be `alt=""` and will be programmatically set for all the alt properties associated with each image in issue #2929. 

### Action Items
- [x] Remove the line of code with the `alt-text` field in the following files only:
  - [x] 2FA.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/2FA.html#L15
  - [x] creating-kanban-project.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/creating-kanban-project.html#L10
  - [x] figma-for-opensource-projects.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/figma-for-opensource-projects.html#L10
- [x] The guide pages' HTML files are used on the website in the Toolkit page and the guides linking from the Toolkit page.
  - [x] Check the Toolkit page and make sure it looks the same as the current [Toolkit page](https://www.hackforla.org/toolkit/)
  - [x] Check each guide page by clicking on its link in the Toolkit and making sure it looks the same as guides on the current website

### Resources/Instructions
- [Information about Front Matter as used by Jekyll](https://jekyllrb.com/docs/front-matter/) 
- [Introduction to Liquid, including information on tags](https://shopify.github.io/liquid/basics/introduction/)
- [Toolkit page](https://www.hackforla.org/toolkit/)
- Directory to find the files once you have it in your IDE: _guide-pages
- Click on the links below to see the code for each file:
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/2FA.html#L15
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/creating-kanban-project.html#L10
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/figma-for-opensource-projects.html#L10

### PR DESCRIPTION
**Pull request by scorbz9**
Fixes #2928  

### What changes did you make and why did you make them ?

  -Removed alt text fields from 2FA.html, creating-kanban-project.html, and figma-for-opensource-projects.html.
  -This makes the website load faster, as well as making it easier for other developers to understand and review.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes made to website.

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA:  endof day on 5/25
availability: 1 hour

**Review by kathrynsilvaconway — APPROVED** [review]
@scorbz9 Nice work on this issue. I see that you have removed alt text fields from 2FA.html, creating-kanban-project.html, and the figma-for-opensource-projects.html, as instructed in the original issue. Everything looks good.

**Comment by trishajjohnson** [comment]
ETA: EOD 5/26/22
Availability: 1 hr

**Review by trishajjohnson — APPROVED** [review]
Reviewed PR, it is from the correct branch, you have provided an issue number and have provided a list of tasks you completed and why.  I reviewed the file changes and everything lines up.  You removed the alt-text from line 15 in file 2FA.html, line 10 in file creating-kanban-project.html and line 10 in file figma-for-opensource-projects.html.  I also took a look at the toolkits pages and clicked on links and compared them to current live pages and everything matches.

Thanks for the good work!  You're good to go.

**Comment by tamara-snyder** [comment]
Hi @scorbz9, thanks for removing the unused code as mentioned in the issue. Great work on this!

**Pull request merged**
