### PR TITLE
added environment credit file

### LINKED ISSUE #3358: Add credit for Environment image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Environment credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `environment.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Environment
# The url where you can get direct access to the image on the provider site
title-link: https://unsplash.com/photos/kbTp7dBzHyY
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Matt Palmer
# Name of the image database you found it on
provider: Unsplash
# Please give the general site URL, not the link to the image
provider-link: https://unsplash.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/environment.png
# Alt text for the image on the Credits page
alt: ''
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please do the following in issue #3130:
    - [ ] Move it to the New Issue Approval column
    - [ ] Remove the "Dependency" label from it
    - [ ] Add a "ready for dev lead" label to it  
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by Mattre7**
Fixes #3358 

### What changes did you make and why did you make them ?

  - added a credit file, environment.yml, to _data/internal/credits for a new image in a redesigned version of the home page
  - This branch is feature-homepage-launch
  -

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-31

**Review by arpitapandya — APPROVED** [review]
The changes looks correct! Great job! @Mattre7 
- Can you add the screenshots of before and after changes by removing the comment `no visual changes to the website` under `Screenshots of Proposed Changes Of The Website (if any, please do not screenshot code changes)`
- You can run `docker-compose up` command in terminal under your branch and you will be able to run the site locally on `http://localhost:4000/credits/` as per the [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

**Comment by ericvennemeyer** [comment]
Availability: 2 hrs
ETA: EOD Saturday, 7/30

**Comment by Mattre7** [comment]
> The changes looks correct! Great job! @Mattre7
> 
> * Can you add the screenshots of before and after changes by removing the comment `no visual changes to the website` under `Screenshots of Proposed Changes Of The Website (if any, please do not screenshot code changes)`
> * You can run `docker-compose up` command in terminal under your branch and you will be able to run the site locally on `http://localhost:4000/credits/` as per the [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

Thanks Arpita! 

I ran docker for both my personal branch with my changes and the feature-homepage-launch branch before my changes and didn't see any visual changes. Only changes I could see were in the code which I thought we weren't supposed to take pictures of. Am I missing somewhere on the site where a visual change was made per this issue/the environment.yml file being added?

**Review by ericvennemeyer — APPROVED** [review]
Nice work @Mattre7! I see that you added the new environment credit file as specified, the website does not break, and the Environment photo credit does appear on the Credits page.

> I ran docker for both my personal branch with my changes and the feature-homepage-launch branch before my changes and didn't see any visual changes.

Re: the above, there *should* be a change. In the original `feature-homepage-launch` branch, there is no file for `environment.yml`, so that card shouldn't appear on the Credits page. I followed this process:

- When I first launched the site from the `feature-homepage-launch` branch on my computer, I didn't see the environment card. 
- I launched it again from your issue branch, and I did see it. 
- But when I switched back to `feature-homepage-launch` and launched again, the environment card was still there. 

I don't know why the environment card seemed to persist, even when the `environment.yml` file was clearly not present in the `feature-homepage-launch` branch. Might be something to look into...

**Comment by arpitapandya** [comment]
> > The changes looks correct! Great job! @Mattre7
> > 
> > * Can you add the screenshots of before and after changes by removing the comment `no visual changes to the website` under `Screenshots of Proposed Changes Of The Website (if any, please do not screenshot code changes)`
> > * You can run `docker-compose up` command in terminal under your branch and you will be able to run the site locally on `http://localhost:4000/credits/` as per the [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)
> 
> Thanks Arpita!
> 
> I ran docker for both my personal branch with my changes and the feature-homepage-launch branch before my changes and didn't see any visual changes. Only changes I could see were in the code which I thought we weren't supposed to take pictures of. Am I missing somewhere on the site where a visual change was made per this issue/the environment.yml file being added?

@Mattre7 You aren't missing anything. Everything is correct. When you started working on issue you weren't able to see the image because the file didn't exist, So we created one and that adds Environment image under the credit 

Note: These changes don't appear in `gh-pages`, They're visible to your branch(now) and `feature-homepage-launch`(after merge). Adding a screenshot here.
environmentCredit

**Comment by Mattre7** [comment]
> 

Yes! That is what was confusing me, that card persisting. Anyway thanks to Arpita I posted that screenshot anyway, appreciate both of your guys' help!

**Comment by Mattre7** [comment]
> @ericvennemeyer

Yes exactly! That card persisting was confusing me. But I posted the screenshot anyway thanks to @arpitapandya, appreciate both of your guys' help!

**Pull request merged**
