### PR TITLE
Moved items from Tools to Technologies in hellogov.md #5340

### LINKED ISSUE #5340: Move items from Tools to Technologies in hellogov.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For each Hack for LA project listed on our webpages, we need to ensure that the data entries for Tools, Technologies, etc. are appropriate for each category. On the HelloGOV project, there are some entries under Tools that should move to Technologies.

### Action Items

- [x] Locate the HelloGOV markdown file in the website/_projects/ folder.
- [x] Locate the section `tools: ...` For this particular project, we want all of the "Tools" listed to be categorized as "Technologies" instead. Also, some of the entries need minor revisions as shown.
- [x] Therefore, replace:
```
tools:
  - Mongo
  - Angular
  - Node
```
with:
```
technologies:
  - MongoDB
  - Angular
  - Node.js
```
- [x] Provide before and after screenshots of the relevant web pages showing that the change was made successfully with no unintended effects. Also, confirm that the side filter displays the correct information.

### Resources/Instructions
[hellogov.md](https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md)
[Hello GOV](https://www.hackforla.org/projects/hellogov) project page
[Hack for LA](https://www.hackforla.org/) homepage
[Projects](https://www.hackforla.org/projects/) page
This issue is initiated by ER #5268

### PR DESCRIPTION
**Pull request by segbuniwe**
Fixes #5340 

### What changes did you make?
  - Updated Tools to Technologies in hellogov.md
  - Updated Mongo to MongoDB
  - Updated Node to Node.js

### Why did you make the changes (we will use this info to test)?
  - The Hack For LA projects needed revisions to better showcase technologies used for project.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-09-21 at 1 35 20 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-09-21 at 1 38 16 PM

</details>

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA: EOD 9/22/2023
Availability: 9am - 5pm Monday-Friday

**Comment by robertnjenga** [comment]
Review ETA:  9/22/2023
Availability: 8am - 12pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @segbuniwe! Thanks for taking up the issue.
The branching was done correctly, you used correct branch to commit from and into.
You linked the issue.
Code changes were made correctly in the code as stated in the issue.
Images were included to show visual changes.
Changes appear correctly on the browser. Great Job!

Just one edit if possible:
Please remove the unused bullet points in the PR comment.

**Review by aadilahmed — APPROVED** [review]
Great job! I can see in my local server that you have correctly changed the "Tools" category to "Technologies", and you have also updated the names of the technologies used. Thank you for taking this issue!

**Review by robertnjenga — APPROVED** [review]
Hi @segbuniwe. Thanks for making the changes, looks great!

**Pull request merged**
