### PR TITLE
Add GitHub handle roland 6940

### LINKED ISSUE #6940: Add github-handle for Roland Abregorivas in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Roland Abregorivas
```
with
```
- name: Roland Abregorivas
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jennisung**
Fixes #6940

### What changes did you make?
- I added 'github handle' for Roland Abregorivas in heart.md

### Why did you make the changes (we will use this info to test)?
  - The site wants to eventually add github handle for all members, so this task wants me to add one for Roland.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>No visual changes to the site.</summary>

image

</details>

<details>
<summary>No visual changes to the site.</summary>
  
image

</details>

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hi @jennisung Please add a comment to your previous PR that says that it is being replaced by this PR (include the #7009) and then close the previous PR- Thanks!

**Comment by daras-cu** [comment]
Review ETA: 1 pm 6/17/24
Availability: All day Monday, Tues-Fri after 6 pm Pacific Time

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @jennisung, nice job with the changes! There are just a couple small things I think you need to change in the pull request, see below.

Correctly done:
- Pull request was done with the correct branch
- Understood and described the reason for the changes
- File was changed correctly and website was not visually affected

Need to fix:
- Link the pull request to the issue number (in the first line of the pull request, put the issue number where "replace_this_text_with_the_issue_number" is currently)
- In the screenshot section, you can get rid of the before and after image sections and just note that there were no visual changes to the site

**Comment by mSharifHub** [comment]
Hello @jennisung . So, the issue you having is same as the issue I Had. on the pull request form where it says Fixes, replace what you have with  -> " Fixes #6940 ". The reason so the issue number serves as a direct link to the issue for other developers to look at. Also, certain task does not require screenshots. So, you can just say, No visual needed.

**Review by mSharifHub — DISMISSED** [review]
Refer to the comment I left in conversations for the Request Change

**Comment by jennisung** [comment]
Thank you for the suggestions! I close the previous pull request #7008 and made the comment after closing it. And updated the description for this pull request. All checks have passed.

**Review by daras-cu — APPROVED** [review]
Your updates look good, well done!

**Comment by zkamenov** [comment]
Review ETA: 1 PM 6/20/2024
Availability: 9AM - 6 PM Thursday

**Review by zkamenov — APPROVED** [review]
This change in the file is relevant, accurate, and robust. Keep up the good work!

**Pull request merged**
