### PR TITLE
Updated message when no results from filter selection - issue 6299

### LINKED ISSUE #6299: Update message when no results from filter selections, Projects and Projects-Check page
### Overview
We need the 0 results search message on the Projects and Project-check pages to deliver a message that makes sense
#### Details
On the Projects and Projects-Check pages, when no results are found after filters have been selected, the message displayed is:
<details><summary>Screenshot</summary>
<p>
Screenshot 2024-02-14 205443
</details> 

Each category in the message should be shown in a singular forms and not the plural.

### Action Items
- [x] Explore both [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) and
 [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js) to understand how the search filter feature works and what triggers the "We couldn't find results for: " message.
- [x] Change "Technologies", "Languages", "Tools", and "Programs" so that "Technology", "Language", "Tool", and "Program" are displayed as appropriate when the filter selection return no results.
- [x] Using Docker, confirm that the [Projects](https://www.hackforla.org/projects/) and [Projects-Check](https://www.hackforla.org/projects-check/) pages display the updated message.
- [x] Note that this issue is only for messages under the search bar, and not for the filter tags shown under "Applied Filters".

### Resources/Instructions
- Related issues for the filter tags
  - #4647 
  - #6298 
- This issue initiated by #6297

### PR DESCRIPTION
**Pull request by raviteja4117**
Fixes #6299

### What changes did you make?
  - Updated message when no results from filter selections for Projects page made it singular forms from plural forms.
  - Updated message when no results from filter selections for Projects-Check page it singular forms from plural forms.

### Why did you make the changes (we will use this info to test)?
  -  Changed Projects and Project-check pages filter messages to deliver a message that makes sense
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-03-03 at 2 18 20 PM

Screenshot 2024-03-03 at 2 18 36 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-03-03 at 2 18 57 PM

Screenshot 2024-03-03 at 2 19 15 PM

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 3/5/24

**Review by elliot-d-kim — CHANGES_REQUESTED** [review]
Hey @raviteja4117,

- Branches and naming was done properly
- Issue is linked
- Summary is concise and descriptive with appropriate visualizations.

I like your hashmap solution: it's simple and easy to understand. My only suggestion is to change the variable name to something more descriptive, like `filterNameSingular`. A [similar PR](https://github.com/hackforla/website/pull/6271/files) used the variable name `singularFormOfFilterName`.

Not related to the actual issue, but I also appreciate you changing the indentation to single tab :) While you edit the variable name, could you also Shift+Tab this section (lines 3-12) to make the indentation consistent with the rest of the file?

Thanks for these contributions!

**Comment by raviteja4117** [comment]
Hi @elliot-d-kim 

Thank you for your feedback and suggestions.

I've made the requested changes, including renaming the variable to "filterNameSingular" for clarity and adjusting the indentation to be consistent with the rest of the file.

I'm glad you found the hashmap solution easy to understand and appreciate your feedback on the variable naming.


Thank you

**Review by elliot-d-kim — DISMISSED** [review]
@raviteja4117 Perfect, the changes look good to me and I'm approving this PR.

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @raviteja4117 - Thanks for working on this issue and nice work so far.
- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear

A couple of things to address: 
- [x] The category labeled "Status" displays as "Undefined"  
- [x] Please remove the spaces before the colons in the key-value pairs of the `filterNameSingular` object for consistency and standard formatting. 

Screenshot 2024-03-08 at 00 05 33


Please re-request reviews (circular arrows icon next to reviewers' username) after you make the changes. Thanks!

**Comment by raviteja4117** [comment]
Hi @jphamtv 

Thanks for pointing out those issues. I'm not sure how I missed them. I've fixed them now. Let me know if everything looks good.

Thank you

**Review by jphamtv — CHANGES_REQUESTED** [review]
@raviteja4117 - Thanks for making those updates. As I was reviewing the changes, I noticed another issue that needs to be addressed. 

When searching for a term, the category displays 'Undefined' as shown in the below image.

Screenshot 2024-03-09 at 16 49 52

**Comment by raviteja4117** [comment]
Hi @jphamtv 

Thanks for Pointing out the search Display. I have fixed it Now. Please have a look at it. Thank you

**Review by elliot-d-kim — COMMENTED** [review]
Good catches from @jphamtv. The new changes seem to fix the aforementioned bugs so they looks good to me.

I want to float the suggestion of adding a fallback value of `key` for `filterNameSingular[key]` to more robustly cover for undefined cases that may escape our attention now or in the future. This can be achieved with the expression `filterNameSingular[key] ?? key`.

@jphamtv @Thinking-Panda A second opinion would be appreciated.

**Comment by jphamtv** [comment]
Thanks @elliot-d-kim for the great suggestion to use `filterNameSingular[key] ?? key` as a fallback to make the function more robust and handle undefined cases nicely.

@raviteja4117, would you like to try implementing this change? If you get stuck or need any help, feel free to loop in @elliot-d-kim or myself, and we'll be happy to assist you.

**Comment by Thinking-Panda** [comment]
Thank you @elliot-d-kim and @jphamtv for the suggestions. @raviteja4117 Nice work. Looking forward to the requested code changes for a robust programming.

**Review by jphamtv — APPROVED** [review]
Hey @raviteja4117, great work on the issue, and thanks for addressing the feedback. Your changes satisfy the requirements outlined in the issue, so I'm approving this PR.

@elliot-d-kim provided a suggestion to make the code more robust. Implementing those changes is totally optional - if you'd like to do so, feel free to update the code and re-request a review. But if you prefer to move forward with the current version, that's fine too since it meets the core requirements and is functioning properly on the site.

Thanks for your contribution!

**Review by Thinking-Panda — APPROVED** [review]
Agree with @jphamtv . I approve this PR.

**Review by elliot-d-kim — APPROVED** [review]
Also agree with @jphamtv. Approving this PR!

Thanks for your contributions :)

**Pull request merged**
