### PR TITLE
Update codeql.yml to automatically create new CodeQL issues

### LINKED ISSUE #5059: Create GHA to create issues when new CodeQL alerts are detected
### Overview
Create a new GitHub action workflow to create GitHub issues when new CodeQL alerts are detected so that we may respond in a prompt manner and ensure the security and quality of our codebase  

### Details
- The workflow `.github/workflows/codeql.yml` implements CodeQL scanning of the gh-pages branch weekly, as well as scanning of pushed commits and pull requests, using the "security and code quality" suite.  
- Alerts are displayed in the repository "Security" tab on the code scanning page[^1]
- It is also posible to use the REST API to retrieve and update code scanning alerts from a repository. 
- To ensure that each CodeQL alert is managed, our goal will be to track each alert with an issue.  There are several means to link a tracking issue with a CodeQL alert.  
- The suggested strategy for this issue is to check every CodeQL alert for a tracking issue, and create new tracking issues as needed.  If a different strategy is proposed, explain the strategy in a comment, move the issue to "Questions/In Review" and apply the `ready for dev lead` label 

### Action Items
- [x] In the workflow file `.github/workflows/codeql.yml`, add a new job following `analyze` OR add a new step to `analyze`, to perform the following steps following the execution of the existing `analyze` job:
  - [x] Examine each open CodeQL alert for a tracking issue.  If a CodeQL does is not linked to a tracking issue, create an issue with template shown below.  Each instance of `[ALERT #]` in the template must be replaced by the CodeQL alert #.  
     - [x] The new issue should have the title "Resolve CodeQL query `[ALERT #]` - generated by GHA"
     - [x] apply the label `ready for dev lead`

### Resources/Instructions
- This issue resulted from #5007

### Issue Template ###
```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the new `[ALERT #]` and either recommend dismissal of the alert or update the code files to resolve the alert.    

### Action Items
- [ ] The following action item serves to "link" this issue as the "tracking issue" for the CodeQL alert and to provide more details regarding the alert. 
- [ ] https://github.com/hackforla/website/security/code-scanning/`[ALERT #]`
- [ ] In a comment in this issue, add your analysis and recommendations.  The recommendation can be one of the following: `dismiss as test`, `dismiss as false positive`, `dismiss as won't fix`, or `update code`.  An example of a `false positive` is a report of a JavaScript syntax error that is caused by markdown or liquid symbols such as `---` or `{%`  
- [ ] If the recommendation is to dismiss the alert, apply the label `ready for dev lead` then move the issue to `Questions/In Review`
- [ ] If the recommendation is to update code:
   - [ ] create an issue branch and proceed with the code update
   - [ ] test using docker to ensure that there are no changes to any affected webpage(s)
   - [ ] proceed with pull request in the usual manner 
  
### Resources/Instructions
[^1]: [HfLA website: CodeQL scan alert audits - issue 5005](https://docs.google.com/spreadsheets/d/1B3R-fI8OW0LcYuwZICQZ2fB8sjlE3VsfyGIXoReNBIs/edit#gid=193401043)
[^2]:[Code scanning results page](https://github.com/hackforla/website/security/code-scanning)
[^3]: [CodeQL query help for JavaScript](https://codeql.github.com/codeql-query-help/javascript/)

- This issue was automatically generated from the codeql.yml workflow
 ```

[^1]:[code scanning results page](https://github.com/hackforla/website/security/code-scanning)
[^2]:[code scanning - in the GitHub REST API
[^3]:[Storing workflow data as artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts)
[^4]:[template for issue to manage new alerts]

### PR DESCRIPTION
**Pull request by w1ld-r**
Fixes #5059

### What changes did you make?
  - Added the following steps to `.github/workflows/codeql.yml`:
    - Setup Node.js (needed to use @actions/core)
    - Install @actions/core (needed to use @actions/core)
    - Fetch Alerts
    - Check Existing Issues
    - Create New Issues
  - Created a folder `github-actions/trigger-issue/create-codeql-issues`
  - Created the following files inside the above folder:
    - issue-body.md
    - fetch-alerts.js
    - check-existing-issues.js
    - create-new-issues.js

### Why did you make the changes (we will use this info to test)?
  - We need to automatically to create GitHub issues when new CodeQL alerts are detected so that we may respond in a prompt manner and ensure the security and quality of our codebase.
  - The new updates will (1) query the GitHub API to find any open CodeQL alerts, (2) check if there are existing tracking issues for the alerts, and (3) if any issues are missing, it creates them automatically.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>CodeQL workflow completed</summary>
<br />
Screenshot 2024-03-30 at 3 42 20 PM
Screenshot 2024-03-30 at 3 36 46 PM
</details>

<details>
<summary>Issue Trigger workflow completed</summary>
<br />
Screenshot 2024-03-30 at 3 37 20 PM
</details>

<details>
<summary>38 issues created automatically by codeql.yml</summary>
<br />
Screenshot 2024-03-30 at 3 36 59 PM
Screenshot 2024-03-30 at 3 50 42 PM
</details>

<details>
<summary>38 issues added to project board</summary>
<br />
Screenshot 2024-03-30 at 3 38 08 PM
</details>

### Testing Notes

- [x] Test your solution by running the `codeql.yml` workflow. You will need to do the following: 
  - [x] Enable Issues your private repo so that you see an Issues tab at the top ([instructions](https://stackoverflow.com/questions/29692626/why-is-issues-tab-not-present-in-my-repos-github-page))
  - [x] Enable CodeQL alerts Security tab ([GitHub CodeQL Documentation](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/configuring-advanced-setup-for-code-scanning))
  - [x] Copy the Hack for LA Project Board in your private repo and make sure the title says `Project Board` ([instructions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Create the following tokens in your GitHub account and add them to your private repo: 
    - [x] `HACKFORLA_ADMIN_TOKEN` for the `codeql.yml` file. Choose these scopes:
           - public_repo (under 'repo')
           - admin:org_hook 
           - write:org (under 'admin:org')
    - [x] `TEAMS` for the `issue-trigger.yml` file.  Choose these scopes:
           - 'read:org' (under 'admin:org')
           - 'read:user' (under 'user')
    - [x] `HACKFORLA_BOT_PA_TOKEN` for the `issue-trigger.yml` file. Choose these scopes:
           - public_repo (under 'repo')
           - admin:org_hook 
  - [x] Push to your branch on your own repo to test.
  - [x] You should see code scanning alerts in your **Security tab** for your branch after you push to your repo (it'll take a minute). You will need to switch branches inside your Security tab to see them (there is a search bar above the alerts): `is:open branch:YOUR-BRANCH`
  - [x] Once the security alerts are created, you should see the **CodeQL workflow** running under your last commit message in the **Actions tab**. 
  - [x] This will also trigger the **Issues Trigger** workflow in your Actions tab, and you will see workflows with the titles of each new issue.
  - [x] When it's all done, you should also see the issues appear in your **Issues tab** and on the **Project Board** in the **New Issue Approval** column.

### CODE REVIEW

**Comment by marioantonini** [comment]
@gaylem quick question, is there a reason to not use a [separate .js file?](https://github.com/actions/github-script?tab=readme-ov-file#run-a-separate-file)
I ask because I recently worked on a GHA issue and that is how it was setup, which actually seemed cleaner.

**Comment by w1ld-r** [comment]
Hey @marioantonini, I noticed that, too. I felt like my code was much shorter and therefore didn't warrant a separate doc. I also tried to set it up that way but couldn't get it to work. I can try again, though, if that is the preferred format.

**Comment by marioantonini** [comment]
@gaylem oh, I have no idea if it is preferred or not, I just thought it felt cleaner. Can I ask, why couldn't you get it to work?
If it helps at all, #4821 is the issue where I worked on a GHA

**Comment by w1ld-r** [comment]
@marioantonini I was getting a strange error in VS Code, I can't remember exactly what it was (some kind of linting error, I think). I suppose it might have worked anyway but I reverted the changes because it was working before I tried to move the code into a new file. I also did that because testing this repeatedly is a bit tedious (you have to delete all the existing issues otherwise it won't generate them). Happy to move it all to a new file if you prefer, let me know what you decide. Thanks!

UPDATE: The strange error was a random typescript error because for some reason my VS code was set to check my JS like it was TS. 🤷

**Comment by marioantonini** [comment]
@gaylem I'll review it as is!

**Comment by marioantonini** [comment]
@gaylem I'm sorry I could not set this up properly to test, so I can't truly review this. Hopefully someone else can chime in and review this soon.

**Comment by t-will-gillis** [comment]
eta: 3/27 eod

**Comment by aidanwsimmons** [comment]
ETA: EOD Thursday
Availability: Weekday afternoons

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @gaylem -  

Sincere kudos for working on this GHA and getting the code to this point, especially for your first time! GHAs can be tricky, and I know you have reworked this once already.  
  
I see the convo with Mario above regarding the setup/ architecture of the of GHA. It is not my decision to make, but I feel that this likely needs to be rewritten using the same architecture that we use on our other GHAs- ie., what is described in [Hack for LA’s GitHub Actions]( https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions). I think there is a benefit to having consistency and interchangeability in the codebase. For example, since most of our GHAs use the `actions/github-script` workflow context, it is fairly simple to modularize repetitive functions (in the [/utils/](https://github.com/hackforla/website/tree/gh-pages/github-actions/utils)) to use in multiple workflows. I also believe it would be helpful to break the step “Check for CodeQL Alerts” down into 2 or more discrete steps.  

I am able to get this GHA running and generating new issues, but I am seeing the same problem with the `issue-trigger.yml` workflow failing due to missing or bad credentials. I have not spent much time trying to figure out why the credentials are not being passed - but I can say that handling credentials using the `actions/github-script` context is straightforward and I think reformatting the code would clear up these errors because the context includes the credentials.

I believe that your workflow’s structure is sound. I think that refactoring this using the HfLA wiki guide (hopefully) shouldn’t be too painful- of course keep asking questions.

PS- the [Wiki guide, Tip 7.5]( https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board) is wrong regarding the token scopes and needs to be fixed (I am writing an issue for it). HfLA’s `HACKFORLA_BOT_PA_TOKEN` only has “public_repo” and “admin:org_hook” scopes, so I would recommend creating another token with these scopes. Keep using your other token and when everything is working, substitute the new token at the end to make sure that the GHA doesn’t need a token with additional scopes. If so there is also a `HACKFORLA_ADMIN_TOKEN` that has the admin “write:org” scope.

**Comment by w1ld-r** [comment]
Thanks @t-will-gillis, I appreciate your help! I'll dig into your feedback in the morning.

**Comment by w1ld-r** [comment]
Hey @t-will-gillis and @aidanwsimmons, I think I got it (mostly)! I'll update the PR description with the changes, but here's proof:

<details>
<summary>Images of Issue Trigger workflow running for each issue on a test branch</summary>
<br />
Screenshot 2024-03-28 at 1 21 09 PM
Screenshot 2024-03-28 at 1 49 49 PM
</details>

<details>
<summary>Issues created automatically by codeql.yml</summary>
Screenshot 2024-03-28 at 1 21 17 PM
Screenshot 2024-03-28 at 1 24 12 PM
</details>

<details>
<summary>Issue added to project board</summary>
<br />
Screenshot 2024-03-28 at 1 20 55 PM
</details>

### Lingering Issues:
- I only got one issue to generate for one of the security alerts, but I'm wondering if that's because I already ran it previously. I deleted all of the created issues from those previous runs, though. Let me know if you have any thoughts on this. 
- Looks like `Add-Missing-Labels-To-Issues` in `issue-trigger.yml` completed successfully but they all say "missing." Is this the expected behavior?
- I'm seeing the following warning even though I updated the `Setup Node.js` in `codeql.yml` to version 20: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.` Not sure how to handle this or if it can be safely ignored for now?
- Let me know what you think about the error handling I commented out on `create-new-issues.js`. Curious what your thoughts are about removing it, modifying it, or keeping it in and just letting some of the checks fail.

### More Testing Notes:
I created 3 tokens in my repo and gave them all the permissions (not sure if this is correct but I wanted to get it to run):
- `H4LA_TOKEN`: This is the replacement for `GITHUB_TOKEN`  on the `codeql.yml` file
- `HACKFORLA_BOT_PA_TOKEN` for the `issue-trigger.yml` file
- `TEAMS` for the `issue-trigger.yml` file


Let me know if you have any additional feedback, and thanks!! 😄

**Comment by t-will-gillis** [comment]
HI @gaylem I ran your code mostly 'as is', only changing branch names. The workflow is running through successfully, there are 42 security alerts found, but there are no issues being generated for me. 

If you are able to get this to generate more than one issue, definitely let me know. 

Some things I am noticing that I believe should be addressed:
- in `codeql.yml`, lines 80-87: `actions/github-script` is running node and core already so they don't need to be loaded and these lines should be deleted.  
- lines 89-98: the token does not need to be passed in script because it is included in the github argument
- also, you'll need to `return fetchAlerts` after line 98 since you are using the output in the next job
- altogether, should look something like this, maybe:
```
    - name: Fetch Alerts
      id: fetch-alerts
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/trigger-issue/create-codeql-issues/fetch-alerts.js')
          const fetchAlerts = script({ g: github, c: context })
          return fetchAlerts
```  
- similar for the next two jobs 
- line 109 (and sim 120), the existing syntax should be changed to  `const alerts = ${{ steps.fetch-alerts.outputs.result }}`
- sim to above, since the output is used in the next job, need to `return checkIssues`   
- in `fetch-alerts.js`: line 2 (`core`) should be deleted- it is running already
- lines 18-22: not saying that this would not work as written, but the typical way we have formatted the API in our other js files especially using `github/actions-script` has been:
```
   const response = await github.request('GET /repos/{owner}/{repo}/code-scanning/alerts', {
    owner: context.repo.owner,
    repo: context.repo.repo,
    state: 'open',                    // note not active
    per_page: 100,
    page: 1
  });
```
- Or alternate `github.rest.codeScanning.listAlertsForRepo({......})`
- Note: no authorization token here
- Note: I believe that `state: 'open'` and not 'active'
- Note the `per_page` and `page`- I believe you will need this because the default number of objects returned is 30. Also, if at some point there are more than 100 alerts, this will need pagination. There are examples of using pagination in our repo- for example in [contributors-data.js](https://github.com/t-will-gillis/website/blob/codeql-test-edits/github-actions/trigger-schedule/github-data/contributors-data.js) lines 162-188
- I don't believe the error check is correct. I ran this, and the `response.status` was `200`- In other words the response was OK but the error was tripped. Probably needs to be `if(response.status != 200) { throw new Error...}` or some such.

Getting late so I will stop here. 
Thanks!

**Comment by w1ld-r** [comment]
Hey @t-will-gillis, thank you so much for your detailed feedback, it was incredibly helpful. I was able to refactor, run the workflow, and create all of the issues.

<details>
<summary>CodeQL workflow completed</summary>
<br />
Screenshot 2024-03-30 at 3 42 20 PM
Screenshot 2024-03-30 at 3 36 46 PM
</details>

<details>
<summary>Issue Trigger workflow completed</summary>
<br />
Screenshot 2024-03-30 at 3 37 20 PM
</details>

<details>
<summary>38 issues created automatically by codeql.yml</summary>
<br />
Screenshot 2024-03-30 at 3 36 59 PM
Screenshot 2024-03-30 at 3 50 42 PM
</details>

<details>
<summary>38 issues added to project board</summary>
<br />
Screenshot 2024-03-30 at 3 38 08 PM
</details>

**One caveat:** I had to run the workflow twice because I hit the GitHub API rate limit, which is 30 requests in an hour for the `/issues` endpoint. This was good in a sense, because it allowed me to validate that running the workflow multiple times won't create duplicate issues.

Do you know of a way to automate a retry? I don't think it's really essential since it's not to hard to manually re-run, but if there's a way to do this I'm happy to give it a shot.

Thanks again! I will await more of your sage advice 😄 

PS - Just noticed one of the checks is failing due to the following error: `Input required and not supplied: github-token` I believe this is referring to the following lines on my codeql.yml file: `github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}` Should I change the secret to something else?

**Comment by t-will-gillis** [comment]
Hey @gaylem Sorry for the delay looking at this- I plan to look at this later today. ETA: eod 4/1

**Comment by aidanwsimmons** [comment]
@gaylem Ill also give this a look this afternoon/evening- hope to finish tomorrow at the latest

**Comment by roslynwythe** [comment]
Hi @gaylem I just realized that CodeQL creates alerts from code in unmerged pull requests, and we don't want to create issues to manage those alerts.  Here is an example of such an alert:  https://github.com/hackforla/website/security/code-scanning/90.  Those alerts do not appear in the list of code scanning alerts https://github.com/hackforla/website/security/code-scanning

We can create an ER for this new requirement, but your advice would be appreciate regarding how best to prevent the GHA from creating issues against alerts for code in PRs.

**Comment by w1ld-r** [comment]
Hey @roslynwythe if I'm understanding you correctly we might be good as is. You said that alerts created for code in unmerged pull requests don't show up in the [code-scanning alerts list](https://github.com/hackforla/website/security/code-scanning). If that's the case then they may not be in our query result at all. We'll want to test that to see if I'm right, though.

Can you tell me how I can identify these issues? Are you able to find them because their status is `In pull request`, or is there some other indicator?

**Review by t-will-gillis — DISMISSED** [review]
Hey @gaylem  Fantastic work! Great job and thank you for sticking with this through all of the iterations. 

I was able to run this in a new branch on my repo, with 35 security issues found and 20 issues generated, then the action exited with a "rate limit exceeded" message. It sounds like you had something similar going on. I don’t think it changes anything necessarily- just something for us to watch. 

I ran CodeQL again, and this time it was much faster and finished creating the issues it was unable to the first time, which is good of course. I would think that once this workflow is running, it will only be updating so maybe the rate limiting will only be an infrequent problem, if that.  

About the manual retry, you could adjust the cron to trigger up to every five minutes (I think). I added the line `workflow_dispatch:` on line 22 so that I could trigger the workflow on demand in my repo.

Some other comments:
-	For the title of the issue, should this be “Resolve CodeQL Alert # 33 – generated by GHA”  instead of “Code QL query”?
-	I very much like that you are using `console.log()` for monitoring in the workflow logs. I think these are very useful for troubleshooting.
-	There are two CodeQL alerts that could be addressed with the PR, both to remove `const fs = require(‘fs’);` one at `fetch-alerts.js` and one at `check-existing-issues.js`. 
-	The “Code scanning alerts” in my repo are not tracked to the issue that was created BUT most likely this is a disconnect due to the issue residing in my repo and the alert linking to HFLA’s repo. Only mentioning this as something to watch for when this is live.
-	For a future issue: the file  `github-actions/utils/issue-template-parser` could be used to parse the `issue-body.md` template. Then the “name”, “title”, “labels”, and “milestone” data could be saved to the .md file similar to [inactive-members.md]( https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/inactive-members.md) Again, this could be a future issue for refactoring, and consolidating the similar actions in [list-inactive-members/create-new-issue.js]( github-actions/trigger-schedule/list-inactive-members/create-new-issue.js) and your `create-new-issue.js`
- For another future issue, I am curious what happens if the CodeQL alert is resolved through a change made by an unrelated PR. I know that CodeQL closes the alert next time it runs. It would be ideal if the issue to address the alert also automatically closed. Not for this issue...

Again, fantastic job and thanks!

(And apologies for not reviewing this sooner)

**Review by aidanwsimmons — DISMISSED** [review]
Great job with this issue Gayle! Appreciate the timely and thorough communication. I was able to generate the issues on my repo- with them also appearing on my copy of the project board. Thanks for the help getting everything properly set up to run on my end

**Comment by t-will-gillis** [comment]
Hi @gaylem prior to merging, if you would like to take care of the two bot alerts and the question about "For the title of the issue, should this be “Resolve CodeQL Alert # 33 – generated by GHA” instead of “Code QL query”? please let me know...Thanks!

**Comment by w1ld-r** [comment]
@t-will-gillis yup, I'm going to take a look at all of this today and make those changes. I'll tag you here when it's ready. Thanks!

**Comment by w1ld-r** [comment]
@t-will-gillis I made the following changes per your request:

1. Updated title to `Resolve CodeQL Alert #${alertId} - Generated by GHA`
2. Removed `const fs = require(‘fs’)` from fetch-alerts.js and check-existing-issues.js

**Questions:** 
- I'm seeing a check fail with the following error: `Error: Input required and not supplied: github-token`. Does this need to be addressed? Am I using the wrong secret?
- Re: [Roslyn's question above ](https://github.com/hackforla/website/pull/6503#issuecomment-2030796014)- I think this would be challenging to test out locally, so I think it would be ok to just deploy what we have and see what happens. If we are creating issues for alerts on PRs, I can raise an ER to address it. Let me know what you think.

I'll raise an ER or two for the future issues you mentioned [here](https://github.com/hackforla/website/pull/6503#pullrequestreview-1975447622).

**Comment by t-will-gillis** [comment]
@gaylem - Great thanks!

- I saw the same message: the one I saw was in reference to the `issue-trigger.yml`, "Add-Missing-Labels-To-Issues", "Run tspascoal/get-uer-teams-membership". I did not create a `secret.TEAMS` token so I figured this was why I got the message. Which log did you see this message?
- If I understand Roslyn's comment, I agree with what you say about deploying it and then reacting if needed. It seems like the worst thing that will happen will be some nuisance issues created, and if so I think we could address it then. 
- Yes! sometimes it is difficult to test these GHAs locally and know for sure how the automation might run differently when deployed. I think it just seems that we need to monitor the logs to make sure that automations are running as anticipated.

FYI- I will be out shortly and not back till next Weds. Just letting you know in case we don't merge this soon- if I don't merge it, I think it is perfectly fine for you to merge this once you have access.

**Comment by w1ld-r** [comment]
Thanks @t-will-gillis!

The error I'm seeing is in the checks above, see images below. 

Screenshot 2024-04-03 at 1 24 19 PM
Screenshot 2024-04-03 at 1 24 31 PM


Looks like it's also saying review required, so I re-requested from you and @aidanwsimmons

**Comment by t-will-gillis** [comment]
Hmmm I don't see what is causing this error since "Fetch Alerts" is given the "HACKFORLA_BOT_PA_TOKEN". It does not get flagged on my repo for what that is worth. ~Any chance your "HACKFORLA_BOT_PA_TOKEN" is expired?~ it should be getting HFLA's token, which definitely is not expired.

**Comment by t-will-gillis** [comment]
@gaylem Can we try something? Can you substitute `secrets.HACKFORLA_ADMIN_TOKEN` at "Fetch Alerts"? If this works, maybe the others also.

**Comment by w1ld-r** [comment]
@t-will-gillis I added the secret to my repo and pushed the changes, but I'm getting the same error. 

Screenshot 2024-04-03 at 2 59 02 PM

**Comment by t-will-gillis** [comment]
ugh the only two other things I can think of are:
- try to run it without any token?
- hope the error is something that goes away when this is live and if not revert it.

**Comment by w1ld-r** [comment]
Thanks @t-will-gillis, I'll keep noodling on it and maybe post the issue on slack to see if anyone else has an idea what's going on. Enjoy your time off!

**Comment by t-will-gillis** [comment]
Thank you! Good luck and let me know what happens...

**Comment by w1ld-r** [comment]
I tried replacing `HACKFORLA_BOT_PA_TOKEN` with `GITHUB_TOKEN` on all three of the new steps in codeq.yml. It worked for `fetch-alerts` and `check-existing-alerts`.  However, I'm getting a different error on `create-new-issues` depending on which token I use. In either case this is looking like a permissions issue. I don't think I can merge until I figure this out so I'll keep digging. I'm a little stumped though, because I would think GITHUB_TOKEN should work.

### `HACKFORLA_BOT_PA_TOKEN`
Screenshot 2024-04-04 at 5 18 08 PM

### `GITHUB_TOKEN` - 403 error
Screenshot 2024-04-04 at 5 11 53 PM

**Comment by roslynwythe** [comment]
@gaylem we have a draft of a wiki page in a comment [How to resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270) and if possible, I would like to include a link to that information in the issue created by this PR.

**Comment by w1ld-r** [comment]
Hey @t-will-gillis @roslynwythe @aidanwsimmons:

Here's my theory about why the `Create New Issues` step is failing in the PR checks:

1. **Updated Problem:** I updated my tokens to match the scopes listed in [this issue](https://github.com/hackforla/website/issues/6537). I used `HACKFORLA_ADMIN_TOKEN` for the `Create New Issues` step and it worked perfectly in my personal repo (`GITHUB_TOKEN` did not). So that token _should_ work in production as well. But the `Create New Issues` step is still failing when this PR runs it as part of the standard checks. 
2. **Hypothesis:** I'm pushing from a forked repo, so if I were GitHub, I wouldn't want to run a POST request as part of the PR checks because that feels like a security issue. What if someone knew that and submitted a billion PRs because hackers be hackin? Too many reads is expensive, but unintended writes could be more problematic. And in this specific case, if the check didn't fail, the CodeQL workflow would have created all of the issues before the PR was approved. If I were GitHub, I'd be smart enough to prevent that sort of thing. For whatever reason, I'm thinking either the workflow or token only has read access on the main repo in this instance, regardless of its scope/permissions. 
3. **Tentative Conclusion:** If that is correct, and these changes are deployed, then the `codeql.yml` workflow will _always_ fail anytime someone submits a PR (big if true). That would be annoying and unhelpful.
5. **Question for Product:** Do we actually want to check for existing CodeQL issues and possibly create new issues every single time the `codeql.yml` file runs? That seems cumbersome/expensive and it makes the checks take longer. It may also result in false negatives because either (a) the check will fail at the `create new issues` stage because of the reasons stated above, or (b) it may hit a rate limit and confuse the developer. 
6. **My Recommendation:** I think we should: (1) stick with the original `codeql.yml` file as it currently is on the `gh-pages` branch, and (2) turn the updated workflow that I created into a separate workflow that we can run manually or on a schedule to generate more CodeQL issues. Even if it doesn't work, this would allow us to maintain our business-as-usual PR review process while validating the change in production. It's also not the cleanest approach, so if we agree on this, I can raise an ER to refactor.

If we go with the recommendations above, then the only way to really confirm this will work in production is to run it there. It _should_ work, because I tested it locally with the same token/scope and it worked there (famous last words). I can also try testing again locally one more time just to be safe.

I'll add this to Monday's agenda for discussion. In the meantime, thoughts and prayers are welcome!! 🙏

**Comment by w1ld-r** [comment]
Hey @t-will-gillis and @aidanwsimmons,

This should be my final update. If you could both take one last look and give your approval, that would be awesome. Here's a summary of how we resolved the issues:

1. **Updated Problem:** I updated my tokens to match the scopes listed in [this issue](https://github.com/hackforla/website/issues/6537). I used `HACKFORLA_ADMIN_TOKEN` for the `Create New Issues` step and it worked perfectly in my personal repo (`GITHUB_TOKEN` did not). So that token _should_ work in production as well. But the `Create New Issues` step was still failing when this PR ran it as part of the standard checks. 
2. **Explanation:** After much digging and theorizing, @t-will-gillis and I came up with [the answer](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/): workflows triggered by Dependabot PRs will run with read-only permissions. So that's why the `Create New Issues` step was failing. Which means if I deployed the original changes I made, then the `codeql.yml` workflow would have _always_ failed on _every_ PR. 
5. **Solution:** I added the following code to all three of the new steps I built on the `codeql.yml` fileso they don't run on PRs: `if: github.event_name != 'pull_request'`. I tested it locally and it creates the issues as expected. And as you can see in the workflow logs on this PR, those steps are being skipped as expected. 
6. **Request** @t-will-gillis and @aidanwsimmons Could you review this (and test with the updated instructions in the PR description) one last time and give your approval (or request more changes if you notice something is wrong)? The only change I made other than adding the `if` condition to the `codeql.yml` file was refactoring the post requests on `create-new-issues.yml`. 

Thanks everyone for your help and patience with this!

**Review by t-will-gillis — DISMISSED** [review]
Hey @gaylem Fantastic job! I ran this one more time and everything appears to be working as expected. Thanks for all of your work on this!

**Comment by w1ld-r** [comment]
FYI, I did some regression testing because I wanted to confirm that the workflow still picks up errors and throws alerts on PR requests. It does! I added an unused variable to the `fetch-alerts.js` file and it threw an alert. (I also reverted the changes I made to test this.)
Screenshot 2024-04-15 at 5 57 53 PM


2. Also, I double checked and the `fetch-alerts` step should not pick up on alerts created by PR checks because the state is set to `open`:
Screenshot 2024-04-15 at 6 08 52 PM


3. Lastly, I updated my `TEAMS` test token with the correct scope and it still added labels correctly.

**Review by aidanwsimmons — APPROVED** [review]
Great job Gayle! pulled your most recent changes and configured tokens per your instructions. Successfully generated issues and they appeared on my project board. Approved!

**Pull request merged**
