### PR TITLE
added github-actions/ to the ignorePaths array in cspell.json file

### LINKED ISSUE #5844: Add "github-actions/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "github-actions/"to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by Maarimar**
Fixes #5844

### What changes did you make?
  - Added "github-actions/" to the ignorePaths array in cspell.json file

### Why did you make the changes (we will use this info to test)?
  - To populate the spell check configuration file with file paths that should be excluded from spell checking
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes made to site.

### CODE REVIEW

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @Maarimar,

Thanks for working on this issue! You used the correct branch and properly linked the issue. Your code change looks accurate.

Could you address the following:

1. Clean up the summary of changes section by fixing the text formatting and removing extra bullet points.
2. Replace the 'Visuals' placeholders with a comment stating there are no visual changes to the website.

For future issues, remember to:

- Work on one issue at a time, waiting for your pull request to be merged before starting another.
- Leave issues with actions for the Merge Team unchecked, as they'll handle these items after merging the pull request. 

If you have any questions or need assistance, don't hesitate to reach out. 

Thanks!

**Comment by w1ld-r** [comment]
Review ETA: April 5th 2024, 5pm CT
Availability: Weekdays 12pm - 8pm CT

**Review by w1ld-r — CHANGES_REQUESTED** [review]
Hi @Maarimar,

Thanks for your help with this issue! It's looking really good.

- You linked the issue correctly in your PR description
- Your branch is correct
- You clearly described the changes ad stated the reason for making them

I agree with @jphamtv's feedback about your PR description and would add a couple of things:
 - Make sure to add a space between the hyphen `-` and "And" in your first bullet. Right now, it's reading as a title because that's how the markdown is interpreting the line without the space. 
 - Since your changes didn't have any visual impact on the site, you can remove the dropdowns completely from under the "Screenshots" section and just leave a comment that says something like "No visual changes made to site."
 - Remove the unnecessary bullets

Once you've made those changes, I'll approve. Thanks again!!

**Comment by Maarimar** [comment]
Working on it! Thanks for the feedback :)

**Comment by w1ld-r** [comment]
Hey @Maarimar thanks for making the updates!

Just a tip for the future, if you click the "refresh" icon under reviewers, it notifies the reviewers that they need to take a look at your changes. It's easy to forget. I went ahead and did it for you and approved. 

Screenshot 2024-04-05 at 3 13 35 PM

Thanks again for your help, nicely done!

**Review by w1ld-r — APPROVED** [review]

**Review by jphamtv — APPROVED** [review]
Great work on the updates @Maarimar! Thanks for your contribution.

**Pull request merged**
