### PR TITLE
Updated the banner img tag, header-hero-image, by removing the slash …

### LINKED ISSUE #5030: img Tag Refactor: Join Us page - banner-icon.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/join-us.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="" />
```
to
```
<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: [INSERT LINK TO FILE]
2. Webpage(s): https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by LukeLowrey2**
Fixes #5030

### What changes did you make and why did you make them ?

-Removed the “/” from the “header-hero-image” img tag
-This was done to create consistency with HTML tags in the codebase

There are no visual changes to the site so I have not uploaded images.

### CODE REVIEW

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing line 24 to not have a slash. The code looks clean, only one commit and only one file changed.
Good job!!

**Review by k-rewd — APPROVED** [review]
Branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed properly. Line 24 has been revised correctly where the ending slash has been removed.

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5030 was properly referenced. ✅ 
- The specified instance of an `` tag was adjusted accordingly with the ending forward slash being removed. ✅

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @LukeLowrey2 as the other reviewers have noted, you did a great job with this good first issue, but I would like to request that you clean up the PR by removing the broken images.  You can edit the markup of the PR by clicking on the menu icon circled below, then delete the `<details>` and `<summary>` tags along with their closing tags and everything in between.  

image


When you have done this, please click the circular icon next to my name; then I will re-review the issue and get it merged.  Thank you for your contributions so far to Hack for LA!

**Comment by mademarc** [comment]
Review ETA: 8/18/2023
Availability: 7:06PM

**Review by mademarc — APPROVED** [review]
Hey @LukeLowrey2 Well done those html code changes.

**Comment by LukeLowrey2** [comment]
Hi @roslynwythe! The broken images have been removed and the PR is cleaned up.

Sadly not seeing the re-request review icon next to your name in the reviewers section.

**Review by roslynwythe — APPROVED** [review]
Thank you @LukeLowrey2 for completing this issue with correct branches, correct code change and a well-formed descriptive pull request.

**Pull request merged**
