### PR TITLE
Changes content to content-type, removes type field.

### LINKED ISSUE #2855: Edit content field and remove type field from photo-roster.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/photo-roster.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/photo-roster.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/photo-roster.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/photo-roster.yml#L11

### PR DESCRIPTION
**Pull request by PeterSYoo**
Fixes #2855

### What changes did you make and why did you make them ?

  - Updated `content: icon` to `content-type: image` in `photo-roster.yml`
  - Removed `type: icon` in `photo-roster.yml`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: 10/25/22 @ 6:30pm
Availability: 6 - 7 pm

**Comment by t-will-gillis** [comment]
Review ETA: 6 pm, 10/26/22
Availability: 2-6 10/26/22

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @PeterSYoo - I see that the -data/internal/credits is changed. This part looks good! 

From reading the conversation attached to the issue, it looks like you were having some issue with the `.vscode/settings.json` file and therefore deleted the file and folder. I believe this will cause an issue with a clean merge since this file needs to remain. 

Regarding the changes at `provider-link:  'https://thenounproject.com'` and at  `alt:  'Photo Roster Icon'`, from single quotes to double quotes: although this change should not effect the functionality, it is not needed and would make this file inconsistent with the other files in the `credits` folder. I recommend switching back to single quotes for consistency. 

Thanks, Peter

**Comment by PeterSYoo** [comment]
Thank you @t-will-gillis , I hope this fixes it now! Sorry about the inconvenience guys.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Thanks for making the changes at `photo-roster.yml` , and for adding the `.vscode/settings.json` file back in. 

I apologize if it seems that I am fixated too much on this, but the `settings.json` file has an extra indent from the original code. This likely would not effect anything, but I believe it would be best to copy the `settings.json` file exactly- i.e. no changes at all- to be certain that no unexpected behavior results. (Following the rule of "If it ain't broke, don't fix it") 

Thanks for looking at these comments right away!

**Comment by PeterSYoo** [comment]
@t-will-gillis Removed the extra line at the bottom in `settings.json`, I'll make sure to keep an eye out for those things in the future! Thanks again!

**Comment by gstemmann** [comment]
Review ETA: 6 pm, 10/31/22
Availability: 7-10pm Thursday

**Review by gstemmann — APPROVED** [review]
it looks like the .yml file has all the proper changes from the original issue. 
I also see you brought back the settings.json file exactly as it was before. Great job!

**Review by t-will-gillis — APPROVED** [review]
Hi Peter- looks great! Thanks so much

**Pull request merged**
