### PR TITLE
Update EXPUNGE ASSIST project information

### LINKED ISSUE #3135: Update Project Profile: EXPUNGE ASSIST
### Overview
As a product manager of EXPUNGE ASSIST I want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending: https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md

### Action Items

- [ ] EXPUNGE ASSIST Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [ ] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

### PR DESCRIPTION
**Pull request by tunglinn**
Fixes #3135

### What changes did you make and why did you make them ?

  - updated team leadership and added product website to keep information accurate and up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 2 hours
ETA: 6/30, end of day.

**Comment by lilyarj** [comment]
ETA: 6/29
Availability: 2hrs

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Review by Wny-Duong — APPROVED** [review]
Everything looks as it should. Good work!

**Pull request merged**
