### PR TITLE
Resolve codeql alert 51 6622

### LINKED ISSUE #6622: Resolve CodeQL Alert 51
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers. we need to analyze [CodeQL query alert 51](https://github.com/hackforla/website/security/code-scanning/51) and to either recommend dismissal of the alert or update the code to resolve the alert.    

### Action Items
- [x] DO NOT DISMISS ANY ALERTS.  Dismissal of alerts should be done by dev leads only after review of the recommendation
- [x] Browse to the link in the next Action Item and read the contents.  Click "See More" to view Recommendations, Examples and References.  
- [x] https://github.com/hackforla/website/security/code-scanning/51
- [x] Note these resources: 
   - [x] See the wiki page "How to manage CodeQL alerts" (see under Resources)
   - [x] To look at the resolution of similar alerts, visit the [code scanning page](https://github.com/hackforla/website/security/code-scanning) and query closed alerts for similar alert type.  To see the resolution of a closed alert, view the alert details and open the tracking issue (outlined in red in the screenshot under Resources)
- [x] In a comment in this issue, provide your recommendation.  The recommendation can be one of the following: `dismiss as test`, `dismiss as false positive`, `dismiss as won't fix`, or `update code`.  An example of a 'false positive' is a report of a JavaScript syntax error that is caused by markdown or liquid symbols such as `---` or `{%`.  
- [x] If the recommendation is to update code:
   - [x] create an issue branch and proceed with the code update
   - [x] Use docker to test locally
      - [x] If `assets/js/utility/api-events.js` is imported from `assets/js/project-meetings.js`, test by verifying that meeting data on  `/project-meetings` is consistent with the live website.  
      - [x] If `assets/js/utility/api-events.js` is imported from `assets/js/right-col-content.js`, test by verifying that meeting data on  `/events is consistent with the live website.  
      - [x] If `assets/js/utility/api-events.js` is imported from `assets/js/right-col-content-check.js`, test by verifying that meeting data on  `/events-check is consistent with the live website.  
   - [x] proceed with pull request in the usual manner 
- [ ] If the recommendation is to dismiss, describe your reason for dismissal in the comment, then move the issue to `Questions/In Review` and apply the label `ready for dev lead`.  

### For merge team/dev lead
- [ ] If recommendation to dismiss is approved, dismiss the alert with a comment, then close the issue as completed.
- [x] When this issue is closed please check off the dependency (under "Issues") in #5159.  If all issues are closed, close #5159 as completed.  
  
### Resources/Instructions

- [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
- [code scanning page](https://github.com/hackforla/website/security/code-scanning)
- Wiki page "How to resolve CodeQL alerts" (if this page has not been published yet, see the draft at https://github.com/hackforla/website/issues/6463#issuecomment-2002573270)
- This issue is part of #5159

### PR DESCRIPTION
**Pull request by aidanwsimmons**
Fixes #6622

### What changes did you make?
  - I changed the sortData function to iterate over Object.values(filteredData) instead of Object.entries(filteredData)

### Why did you make the changes (we will use this info to test)?
  - the previous version required the destructuring of each entry into [key, value], but the 'key' variable was not being used
  - these changes should achieve the same result with out the unused variable

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by LRenDO** [comment]
Hi @elliot-d-kim! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Comment by A-Wu5** [comment]
Availability: 4/19/24
ETA: Eod of 4/19/24

**Comment by elliot-d-kim** [comment]
Availability: 4/19/24
ETA: EOD 4/19/24

@LRenDO Sorry about that, appreciate the reminder!

**Review by elliot-d-kim — APPROVED** [review]
Hey @aidanwsimmons,

- Branches and naming was done properly
- Issue is linked
- Summary describes changes and motivation clearly and concisely.
- Website retains functionality
- Code changes are clean and intuitive, and they resolved the CodeQL alert on my test branch (had to jump through some hoops to definitively test this, so @A-Wu5 if you'd like me to share my documentation on how I did so, feel free to let me know!)

<details>
<summary>Screenshot of resolved CodeQL alert</summary>

image

</details>

Great work and thanks for these contributions!

---

PS I did find some oddities while I was testing the website (they're in production as well, so nothing to do with this PR, really). I mentioned these findings in #6369.
- The last event under Wednesday on the [Project Meetings page](https://www.hackforla.org/project-meetings) looks like dummy data that got shipped
- All the 'Admin team' links are https://www.hackforla.org/undefined

**Review by A-Wu5 — APPROVED** [review]
Hi aidanwsimmons, great work on this issue! The code changes you've made make sense and follows through your recommendation for the codeql alert. The changes have not altered the data.

**Pull request merged**
