### PR TITLE
Update Project Profile: 311 Data (Update Technologies, Add Ahmed Awadalla & Edwin Jue to project team)

### LINKED ISSUE #5854: Update Project Profile: 311 Data (Update Technologies, Add Ahmed Awadalla & Edwin Jue)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `technologies` variable and change the following:

**From:**
```
technologies:
  - React
  - Redux
  - Material-UI
  - Mapbox
  - AWS
  - FastAPI
  - Redis
  - PostgreSQL
  - Prefect
  - Docker
  - Figma
  - Adobe CC
  - Miro
```
**To:**
```
technologies:
  - React
  - Redux
  - Material-UI
  - DuckDb
  - HuggingFace
  - GitHub Pages
  - Mapbox
```
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Ahmed Awadalla
    github-handle: ahmedsalah0130
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05Q80JEGG4
      github: https://github.com/ahmedsalah0130
    picture: https://avatars.githubusercontent.com/ahmedsalah0130
```
- [x] If there are other Product Managers, place Ahmed's profile after the other Product Managers' profiles
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Edwin Jue
    github-handle: edwinjue
    role: Engineering Lead
    links:
      slack: https://hackforla.slack.com/team/U03SUUZMFEV
      github: https://github.com/edwinjue
    picture: https://avatars.githubusercontent.com/edwinjue
```
- [x] If there are other Engineering Leads, place Edwin's profile after the other Engineering Leads' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
  - [x] the project's card on the Projects' page [^3]
- [x] Once your pull request is merged, go to #5786 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5786 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #5786 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by Chrisklangley**
Fixes #5854 

### What changes did you make?
  - In _projects/311-data.md file I updated technologies variable  on line 67 to display a updated list of technologies 
  - In the same  in _projects/311-data.md file I added two new team members to the  leadership variable on line 8
  

### Why did you make the changes (we will use this info to test)?
  - I updated the technologies variable to properly show the current technologies being used on the project
  - I updated the leadership variable with two new team members to show that the current list of team members 
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Technologies Before Screen Shot 2023-11-09 at 11 12 17 AM

Project Team Screen Shot 2023-11-09 at 11 21 57 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Technologies After Screen Shot 2023-11-09 at 11 15 38 AM
Project team after Screen Shot 2023-11-09 at 11 38 40 AM

</details>

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA: EOD 11/9
Availability: 9-5 pm Monday-Friday

**Review by aadilahmed — DISMISSED** [review]
Great job Chris! All of the changes to the 311 Data page and project card were correctly implemented.

**Comment by A-Wu5** [comment]
Review ETA: Nov 11 EOD
Availability: Weekday afternoons 2-5 PM

**Review by A-Wu5 — CHANGES_REQUESTED** [review]
@Chrisklangley Great work! The requested changes were done correctly. This is minor, but I think one of the empty lines at 43 and 44 can be removed to make the code cleaner.

**Review by A-Wu5 — DISMISSED** [review]
Great work! Everything looks good to me. Changes were implemented as requested.

**Comment by roslynwythe** [comment]
@aadilahmed Please re-review this pull request.

**Comment by roslynwythe** [comment]
@A-Wu5 Please re-review this pull request.  Thank you!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @Chrisklangley Thank you for working on this issue! 
- Your from/to branches are correct
- The PR is linked back to the original issue
- Your description briefly explains what changes you made and why you made them
- You provided clear and relevant 'before' and 'after' screenshots (thanks for highlighting the changes!)

Regarding the code edits:
- Thank you for addressing a potential merge conflict. I can see that you are accounting for "Bethlehem Berhane" and "Holly Worthen".
- Since the codebase now includes these two members: as noted on #5854, the entry for "Edwin Jue" needs to be grouped with "Holly Worthen" since both are Leads .
- Also, the empty lines at 59, 44, and 29 need to be deleted to keep the code clean.

When you have made the changes please select the 're-request review'- thanks!

**Comment by Chrisklangley** [comment]
Hey @t-will-gillis  I'll fix that right now give me a few minutes, Thank you!

**Review by t-will-gillis — APPROVED** [review]
Hey @Chrisklangley - Fantastic

Thanks for making the edits!

**Pull request merged**
