### PR TITLE
Added the vertical to work-for-la

### PR DESCRIPTION
**Pull request by y20s**
Added the vertical to work-for-la
There is no project file for hack-for-la

### CODE REVIEW

**Comment by y20s** [comment]
Issue #907

**Comment by y20s** [comment]
@tarang100 Can you clarify for the hack-for-la. That file doesn't seem to exist.

**Comment by y20s** [comment]
Making the change to website.md as it seems to be the appropriate file.

**Comment by y20s** [comment]
I made the change to website.md

**Review by drubgrubby — APPROVED** [review]
That looks just right.  Nice work!  Ready to merge.

**Comment by tarang100** [comment]
Thanks @y20s I believe that website.md is the correct file. However, I am not the expert so requesting @drubgrubby to confirm. If required, I can check this with Bonnie during Sunday's meeting.

**Pull request merged**
