### PR TITLE
removed alt-hero from _projects/expunge-assist.md issue 3196

### LINKED ISSUE #3196: Remove unused `alt-hero` field from expunge-assist.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/expunge-assist.md`, remove line 9 for the alt-hero
```
alt-hero: 'Expunge Assist project logo'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/expunge-assist.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/fdecdb49ef86a3cc3bf4617effe055e39efecc13/_projects/expunge-assist.md?plain=1#L9

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by roslynwythe**
Fixes #3196

### What changes did you make and why did you make them ?

  - removed alt-hero by deleting line 9 from _projects/expunge-assist.md, because alt-hero was not being used. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
There were no visual changes to the site

### CODE REVIEW

**Review by gstemmann — APPROVED** [review]
Looks like you added your branch to the proper repo in hfla website: hackforla:gh-pages. great job. And it looks like you deleted the correct line from the expunge-assist.md for the alt-hero.

**Comment by MattPereira** [comment]
Review ETA: 11:30 PM 10/31/22
Availability: 1 hour

**Review by MattPereira — APPROVED** [review]
Great job @roslynwythe ! :+1: 

You removed the alt-hero line and executed the pull request beautifully by linking the issue number, listing your changes, and providing the reason for the changes.

**Comment by arpitapandya** [comment]
ETA: EOD 2022-10-31
Availability: 15 minutes

**Review by arpitapandya — APPROVED** [review]
Changes looks correct! Great job! @roslynwythe

**Pull request merged**
