### PR TITLE
added new team member to hfla site project profile

### LINKED ISSUE #4758: Update Project Profile: Hackforla.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Drake Nguyen
  GitHub Handle: drakenguyen4000
  Role: Merge Team
  Slack Member ID: U04TSESVB4J
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by Dprosser4**
Fixes #4758

### What changes did you make and why did you make them ?

  - added new team members information within the leadership variable 
  - specific file changed `_projects/website.md`
  - confirmed all links working for new team member

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-06-06 at 12 34 25 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-06-06 at 12 34 07 PM

</details>

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Availability: W-F
ETA: Friday 11pm

**Review by LOSjr4 — APPROVED** [review]
I see formatting for addition to leadership in _projects/website.md were done correctly. I verified all links worked and went to the correct profiles. Docker preview looks good. @Dprosser4 left a good description of what was done and why. They also correctly included before and after pictures.
Nice clean work @Dprosser4 !

**Comment by ldietz08** [comment]
ETA: 6/11 EOD
Availability: M-F 4pm-6pm

**Review by steven-positive-tran — COMMENTED** [review]
Sorry for the delay.

The changes of adding the new team member shows up docker in both firefox and in edge. Code changes seem in line with the issues that were addressed. Branches look good.

Looks good and thank you for taking up this issue.

**Review by steven-positive-tran — APPROVED** [review]

**Review by ldietz08 — APPROVED** [review]
Hi Dylan! It looks like the pull request was done in the correct branch and you linked to the issue. As requested, a new merge team member was added to the website markdown file. The visual changes reflect what I see in my local environment. 

Nice job!

**Pull request merged**
