### PR TITLE
Fix Punctuation and Capitalization in Access the Data & Food Oasis

### LINKED ISSUE #3354: Fix Punctuation and Capitalization in Access the Data  & food Oasis
### Overview
We need to fix the capitalization and punctuation in food-oasis.md and access-the-data.md so we can keep everything understandable and up to standard on the website.

### Details
Below are screenshots of the tools currently on the Food Oasis and Access the Data webpages from the Hack for LA website as of 2022-09-04 (these tools are subject to change via another issue, so don't worry if they are different):
<details>
  <summary>Click here to see a screenshot of the Tools on the Food Oasis webpage</summary>
  
</details>

<details>
  <summary>Click here to see a screenshot of the Tools on the Access the Data webpage</summary>
  
</details>

### Action Items
- [x] Open _projects/food-oasis.md in VS Code or your IDE, then capitalize each tool in food-oasis.md and remove the period at the end (don't capitalize: pen, paper, phone calls)
- [x]  Open _projects/access-the-data.md in VS Code or your IDE, then capitalize each tool in access-the-data.md and remove the period at the end (don't capitalize: pen, paper, phone calls)

### Resources/Instructions
access-the-data.md
https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md
food-oasis.md
https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md

Website:
access-the-data page
https://www.hackforla.org/projects/access-the-data
food-oasis page
https://www.hackforla.org/projects/food-oasis

### PR DESCRIPTION
**Pull request by michaelmagen**
Fixes #3354

### What changes did you make and why did you make them ?

  - Capitalized the words Figma, Photoshop, and Sketch in tools section of Access the Data
  - Removed period from tools in Access the Data
  - Removed period from tools in Food Oasis

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image

</details>

### CODE REVIEW

**Comment by d-perez-8** [comment]
Availability: 4-6 pm 10/04/22 - 10/05/22
ETA: EOD 10/04/22

**Review by d-perez-8 — APPROVED** [review]
This looks good! The website does not break, and you have completed the issue correctly. Thank you for your work!

**Comment by Unity7** [comment]
Availability: 2 Hours 
ETA: EOD 10/5/22

**Review by Unity7 — APPROVED** [review]
Looks good. I was able to clear see the changes you made to punctuations per the issue. Great work!

**Comment by plang-psm** [comment]
Availability: 6 Hours
ETA: 10/9/22

**Comment by plang-psm** [comment]
Good work! Everything checks out just fine.

**Review by plang-psm — COMMENTED** [review]
Good work! Everything checks out just fine.

**Review by plang-psm — APPROVED** [review]

**Pull request merged**
