### PR TITLE
moved SDG folder and refactored SDG paths in multiple files

### LINKED ISSUE #4183: Move and rename `sdg-elements` directory and refactor associated code
### Overview
We want to move the `sdg-elements` folder up a level from the `assets/images/about` to the `assets/images` directory so that it accurately reflects that we use those images on multiple pages on our website.

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] Move the file directory `assets/images/about/sdg-elements` up one level so it becomes `assets/images/sdg-elements`
- [x] Rename the directory `sdg-elements` to `sdg`
- [x] As a result of the above changes, change the paths of the SDG images in the following files:
  - [x] _includes/about-page/about-card-sustainability.html
  - [x] _projects/311-data.md
  - [x] _projects/access-the-data.md
  - [x] _projects/engage.md
  - [x] _projects/lucky-parking.md
  - [x] _projects/open-community-survey.md
- [x] Using the search function in VS Code or IDE, search for `assets/images/about/sdg-elements`. If you find any files with that, update the code in those files to the new path.
- [x] Check the following pages look the same as the pages on the live website
  - [x] About page: https://www.hackforla.org/about/#sustainability
  - [x] Citizen Engagement page: https://www.hackforla.org/citizen-engagement
  - [x] 311 Data: https://www.hackforla.org/projects/311-data
  - [x] Access the Data: https://www.hackforla.org/projects/access-the-data
  - [x] Engage: https://www.hackforla.org/projects/engage
  - [x] Lucky Parking: https://www.hackforla.org/projects/lucky-parking
  - [x] Open Community Survey: https://www.hackforla.org/projects/open-community-survey

#### Merge Team, Technical Lead, or Product Manager
- [x] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4254
  - [x] #4255
  - [x] #4256
  - [x] #4225
  - [x] #4257
  - [x] #4253
  - [x] #4258  

#### Files that need the paths of the SDG images to be updated
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- [_projects/311-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md?plain=1)
- [_projects/access-the-data.md](https://github.com/hackforla/website/blob/7770fdeaa68f44c6ceb32866a24b903ad52c2019/_projects/access-the-data.md?plain=1)
- [_projects/engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md?plain=1)
- [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md?plain=1)
- [_projects/open-community-survey.md](https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md?plain=1)

#### Pages to check to make sure pages stay the same
- About page: https://www.hackforla.org/about/#sustainability
- Citizen Engagement page: https://www.hackforla.org/citizen-engagement
- 311 Data: https://www.hackforla.org/projects/311-data
- Access the Data: https://www.hackforla.org/projects/access-the-data
- Engage: https://www.hackforla.org/projects/engage
- Lucky Parking: https://www.hackforla.org/projects/lucky-parking
- Open Community Survey: https://www.hackforla.org/projects/open-community-survey
- This issue is tracked in #4153

### PR DESCRIPTION
**Pull request by arcan9**
Fixes #4183 
### What changes did you make and why did you make them ?

  - `sdg-elements` directory is renamed to `sdg` and moved up one level.
     - Old path: `assets/images/about/sdg-elements`
     - New path: `assets/images/sdg`
  - Due to the change, various files had to be refactored to point to the new path (listed in the issue).
  - Reason: to accurately reflect that we use these SDG images on multiples pages of the HfLA website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<br>

> Small card images in the "sustainable" sections in mulitple project pages:

hfla-4183-current

</details>

<details>
<summary>Visuals after changes are applied</summary>
<br>

> After the change, the images are still rendered correctly:

  
hfla-4183-localhost

hfla-4183-localhost-2

</details>

### CODE REVIEW

**Comment by nnr-nnr** [comment]
Review ETA: EOD Mon. 3/27/23
Availability: 12-4 PM 3/26, 3-8 PM 3/27–328/

**Comment by richardmundyiii** [comment]
Availability: 3/26/23 12pm - 3pm
ETA: EOD 3/26/23

**Review by nnr-nnr — DISMISSED** [review]
Wonderful work, @arcan9 ! You've cleanly moved and renamed all the SDG image assets, and you've updated all mentions of these files in the repo to reflect these changes. This PR passes the ABCs 👍.

**Comment by arcan9** [comment]
> Availability: 3/26/23 12pm - 3pm ETA: EOD 3/26/23

Hi @richardmundyiii are you still available to review this?

**Review by blulady — DISMISSED** [review]
@arcan9 All the changes you have done look great!!! However when I pull your branch into my local and search for "assets/images/about/sdg-elements", I find 18 mentions of it in 7 files. I see it in citzen-engagement.html, about\index.html, 311-data.html, access-the-data.html, engage.html, lucky-parking.html and open-community-survey.html. Please update the branch with changes to `assets/images/sdg-elements` from `assets/images/about/sdg-elements`.

**Comment by nnr-nnr** [comment]
Hi @blulady, just curious how you found the mentions of `assets/images/about/sdg-elements`? In VS Code, I use the Cmd + Shift + F (on mac) sequence to search for "assets/images/about/sdg-elements", but this doesn't turn up any mentions. I'm also not seeing the mentions of this file path in the files you listed, though I do see the updated file path that Issue #4183 says to use (ie `assets/images/sdg`).  I think I might be missing something here... Thank you!

**Comment by arcan9** [comment]
@blulady: Like @nnr-nnr, I can't seem to find any mentions of `assets/images/about/sdg-elements` in the files you mentioned. And interestingly, I couldn't find those html files. Could you clarify please? Thank you.

**Comment by arcan9** [comment]
@t-will-gillis @bzzz-coding @roslynwythe Would love feedback on this!

**Review by t-will-gillis — DISMISSED** [review]
Hey @arcan9 - Great job! Your branches are correct, as is your linked issue, and your description is super with the clips. I checked the changes on Docker and did not see any unexpected changes. Also did a final check and it appears that all `assets/images/about/sdg-elements` paths are changed. 

Thanks for your efforts and great job again

**Comment by blulady** [comment]
> Hey @arcan9 - Great job! Your branches are correct, as is your linked issue, and your description is super with the clips. I checked the changes on Docker and did not see any unexpected changes. Also did a final check and it appears that all `assets/images/about/sdg-elements` paths are changed.
> 
> Thanks for your efforts and great job again

Hey @t-will-gillis feel free to merge this pr.

**Review by t-will-gillis — APPROVED** [review]
Merge conflicts have been resolved.

**Pull request merged**
