### PR TITLE
Update Program Areas "Join a Project" Section

### LINKED ISSUE #4142: Update Slack Link on Program Areas Page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
At the bottom of the Program Areas page, there is section called 'Join a Project' that refers new volunteers to `join our slack` via an embedded link. We want this to change so that new volunteers are referred to our onboarding process in 'Getting Started'. 

### Action Items
On the [Program Areas](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html) page:

- [x] Change the text in the join-us-footer first paragraph from:
```
To join any of the projects click through their project pages for details on getting started.
```
to
```
We are looking for volunteers of all different skill types, levels, and civic interests. If you have not joined yet, please see the <a href="/join" target="_blank">Join Us</a> page. 
```
- [x] Delete the entirety of the join-us-footer second paragraph as shown here:
```
<p class="second-paragraph">
          The projects that are in formation are not yet on our website. To 
          connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack</a> and 
          browse for their channel name.
</p>
```

### Resources/Instructions
[Program Areas webpage](https://www.hackforla.org/program-areas)
[program-areas.html](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html)

### PR DESCRIPTION
**Pull request by Sebster3**
Fixes #4142 

### What changes did you make and why did you make them ?

  - Updated the text and link within the "Join a Project" section of the Program Areas page to direct prospective volunteers to the onboarding process.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Program Areas Footer Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Program Areas Footer After

</details>

### CODE REVIEW

**Review by mariorecinos — APPROVED** [review]
Hi Sebster3 Excellent work on this pull request.  Your pull request came from the correct branch and your branch was named correctly and linked with the issue.  Amazing work you have done all the changes and I can see them on docker.  The only thing to take note of that when describing the changes you made make sure to[ include all of the changes](https://github.com/hackforla/website/pull/4222/files) you made to the file including deleting the second paragraph in the footer and updating the text.
```
Delete the entirety of the join-us-footer second paragraph as shown here:
<p class="second-paragraph">
          The projects that are in formation are not yet on our website. To 
          connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack</a> and 
          browse for their channel name.
</p>
```
Excellent work on making these two very important changes and doing excellent work.

**Comment by steven-positive-tran** [comment]
Review ETA: 8 PM 3/21/23
Availability: 7pm-12pm

**Comment by nnr-nnr** [comment]
Review ETA: 8 PM 3/21/23
Availability: 5pm-9pm

**Review by nnr-nnr — APPROVED** [review]
Nice job, @Sebster3! This PR passes the ABCs. I was confused by the broken Slack links on the HfLA website when I was looking to join the org a few weeks ago, so I'm glad this is being fixed. 

One note: it looks like your fork of the hackforla/website repo is named `hfla-website` instead of `website`. The instructions for reviewing pull requests assume that your repo is named `website`  (see [Commandline instructions for Development Team](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-3-view-the-changes-in-the-browser)), so you may want to make a note of this for future reviewers or re-fork/rename the repo if possible.

Overall, nice work.

**Review by steven-positive-tran — APPROVED** [review]
Branches pulled for hackforla/gh-pages to your own fork and I've pulled and confirmed that the changes are in my development server

**Comment by Sebster3** [comment]
> One note: it looks like your fork of the hackforla/website repo is named `hfla-website` instead of `website`. The instructions for reviewing pull requests assume that your repo is named `website` (see [Commandline instructions for Development Team](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-3-view-the-changes-in-the-browser)), so you may want to make a note of this for future reviewers or re-fork/rename the repo if possible.

I can see how that might be a problem, so I'll make a note on future PRs, thanks @nnr-nnr!

**Pull request merged**
