### PR TITLE
updates leadership variable in engineering.yml under communities of practice

### LINKED ISSUE #6184: Update Communities of Practice: Engineering (Remove Chelsey Beck, Add Adam Abundis)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Chelsey Beck
    role: Co-Lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
```
- [x] Then, add the following person to the `leadership` variable as a new entry :
```
  - name: Adam Abundis
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJML6CY49
      github: https://github.com/abuna1985
    picture: https://avatars.githubusercontent.com/abuna1985
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #6160 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6160 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6160
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #6184

### What changes did you make?
  - Removed Chelsea Beck from the leadership variable under community of practice page
  - Added Adam Abundis to the leadership variable under community of practice page

### Why did you make the changes (we will use this info to test)?
  - To update community of practice page with new Co-lead Adam Abundis
  - Ensured site works in desktop and mobile mode

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before_desktop
before_mobile

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after_desktop
after_mobile

</details>

### CODE REVIEW

**Review by roslynwythe — APPROVED** [review]
Great job @sornekian 
- Your branches are correctly formed
- Your code change is clean and correct
- You have described your work 
- You tested the page in the browser at all screen sizes

Approved and thank you for your contribution!

Also please note that #6197 modifies the same file so a merge conflict may arise.  For this reason, we need to be very clear about the changes in this PR so under "What changes did you make?", please add a bullet item mentioning Adam Abundis.

**Review by heejung-hong — APPROVED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, iPad, and iPhone view), Firefox, and Safari browser.

**Comment by jphamtv** [comment]
Hey @sornekian, it looks like there’s a merge conflict that needs to be resolved before we can move forward, as @roslynwythe pointed out. 

Also, Roslyn asked to add a bullet item mentioning Adam Abundis in the "What changes did you make?" section. I see you mentioned him in the "Why" section instead. Once the conflict is resolved, could you move his name to the correct section and re-request reviews? Let me know if you need help or have any questions. Thanks!

**Comment by t-will-gillis** [comment]
Hey @sornekian - Not sure if you saw @jphamtv 's comment above regarding the merge conflict and other items- if you need help please feel free to contact one of us. Thanks!

**Comment by jphamtv** [comment]
Replaced by #6262

**Pull request closed without merging**
