### PR TITLE
Added Github-handle for Sandra Berjan in design-systems.md

### LINKED ISSUE #6700: Add github-handle for Sandra Berjan in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems` in the IDE
- [x] Replace:
```
- name: Sandra Berjan
```
with
```
- name: Sandra Berjan
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jenjenkayi**
Fixes #6700 

### What changes did you make?
  - Added github-handle for Sandra Berjan in design-systems.md.

### Why did you make the changes (we will use this info to test)?
  - Reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Adding github-handle to the file. No visual changes to the website.

### CODE REVIEW

**Review by jphamtv — APPROVED** [review]
Hi @jenjenkayi, 
- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- Your code change is clean and accurate, correctly using spaces instead of tabs to indent 

Thanks for your contribution to this issue!

**Comment by t-will-gillis** [comment]
Hey @jenjenkayi, @patelbansi3009, @taylorbeee, @nssensalo, @ShamaaTabassum as a reminder, while you are waiting for your PRs to be reviewed, please consider reviewing each other’s `good first issue` PRs and any other PRs you feel comfortable with. Instructions are here for [How to Review Pull Requests]( https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) . You should aim to review two PRs for every PR you submit, and each PR ideally should have two or more reviewers. Thanks!
#6746, #6767, #6768, #6770, #6772

**Comment by angela-lee1** [comment]
Review ETA: eod 4/29
Availability: from 1:00pm EST 4/29

**Review by angela-lee1 — COMMENTED** [review]
@jenjenkayi Awesome job! 
- you have linked the correct issue, your branch is correct
- a clear description is provided  for making the change
- you gave the reason for not providing screenshots

Thank you!

**Review by angela-lee1 — APPROVED** [review]

**Comment by Thinking-Panda** [comment]
@jenjenkayi Thank you for working on this issue!

**Pull request merged**
