### PR TITLE
Update Communities of Practice: Engineering - removed Alejandro Gomez 

### LINKED ISSUE #6074: Update Communities of Practice: Engineering (Remove Alejandro Gomez)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Alejandro Gomez
    role: Co-Lead
    links:
      slack: https://hackforla.slack.com/team/U04HFRQ5Y12
      github: https://github.com/agosmou
    picture: https://avatars.githubusercontent.com/agosmou
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #6060 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6060 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6060
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by jtw007**
Fixes #6074 

### What changes did you make?
  -removed Alejandro Gomez from yml file 
  -
  -

### Why did you make the changes (we will use this info to test)?
  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screen Shot 2024-01-08 at 19 13 16

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2024-01-08 at 19 13 34

</details>

### CODE REVIEW

**Comment by tonyvang** [comment]
Availability: tomorrow evening, Saturday evening, Sunday afternoon
ETA: EOD Sunday

**Comment by LRenDO** [comment]
Hi @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Review by jlevot — CHANGES_REQUESTED** [review]
@jtw007 Branches aren't correctly set. You need to create a specific branch on your fork.
You can see the necessary documentation just [here](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue).

Just an advice for you next PR, you can improve the clarity of the body:
- Say why you did this change, in you case: To keep project information up to date
- Add screenshots before/after of the website view, not of the code. The goal is to have a visual rendering of your work.

Feel free to contact me on slack if you have any questions 👍

**Comment by mademarc** [comment]
Review ETA: 01/12/2024
Availability: 1:43PM

**Review by mademarc — APPROVED** [review]
Hey @jtw007  good call on posting the screenshot of what you have done showcasing the changes that needed to be done and @LRenDO  the ETA is there

**Comment by jtw007** [comment]
closing this PR, created new branch on my fork and created a new pull request here: https://github.com/hackforla/website/pull/6103

**Pull request closed without merging**
