### PR TITLE
Added Heejung Hong to the LA TDM Calculator Leadership Page

### LINKED ISSUE #7646: Update Project Profile: LA TDM Calculator Add Heejung Hong
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Heejung Hong
    github-handle: heejung-hong
    role: Front End Development Lead
    links:
      slack: https://hackforla.slack.com/team/U064M7X48SY
      github: https://github.com/heejung-hong
    picture: https://avatars.githubusercontent.com/heejung-hong
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by mchait18**
Fixes #7646

### What changes did you make?
  
  - I added Heejung Hong to the leadership page for LA TDM Calculator.
   

### Why did you make the changes (we will use this info to test)?
  
   To keep the leadership for LA TDM Calculator on the website up-to-date
 

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

![image]before 7646

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]after 7646

</details>

### CODE REVIEW

**Comment by floydferrer** [comment]
Review ETA: 11/8/2024 Friday
Availability: 12-5 PM Weekdays (PST)

**Review by floydferrer — APPROVED** [review]
Thank you for working on this issue, @mchait18  !

- PR is done with the correct branch
- The linked issue is included and accurate
- Changes are correct
- Slack and Github links direct to the correct destinations
- Before-and-after screenshots are clear of the requested changes

Thanks for your contribution!

**Comment by TheManTheMythTheGameDev** [comment]
Review ETA: 2 PM 11/9/24
Availability: Weekends

**Review by TheManTheMythTheGameDev — APPROVED** [review]
- Branches are correct
- Issue is linked correctly
- Changes look good on the website
- Changes are simple and clean
Great job! This PR looks perfect. Thank you for your work!

**Comment by t-will-gillis** [comment]
Hi @mchait18 Great job on your issue. Quick note: for the checkbox under "CodeQL Alerts" above, you can either check the box after all changes have been saved, or you can add an 'X' to the raw markdown- it will display correctly as long as you remove any spaces. 

It looks like you added the 'X', so just remember to remove the extra space and only show "- [x]" not "-[x ]" For example:

- [x ] button with the extra space
- [x] button with only the 'x'

**Comment by mchait18** [comment]
### 6 - PULL REQUESTS update
>What is the number of your first merged pull request?
- #7711 
>Did you receive any reviews that required you to change anything on your PR? 
- [ ] no
- [x] yes (if yes, describe what you learned)

Comments: 
I learned how to check a checkbox in raw markup, by putting an x without any whitespace.
[return to section 6](#section-6)

**Pull request merged**
