### PR TITLE
Add new variable github-handle to member Karen Coronel in civic-tech

### LINKED ISSUE #5714: Add new variable github-handle to member Karen Coronel in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in your IDE
- [x] Replace:
```
- name: Karen Coronel 
```
with
```
- name: Karen Coronel 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [x] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by KuanHsienYEH**
Fixes #5714 

### What changes did you make?
 Replace 
```html
- name: Karen Coronel 
```
with
```html
 - name: Karen Coronel 
  github-handle: 
```
  

### Why did you make the changes (we will use this info to test)?
 To resolve #5714 reducing redundancy in the project file
 

 ### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by tonyvang** [comment]
Review inbound.

Availability: Monday evening, Wednesday evening, Thursday evening.

ETA: EOD Thursday

**Review by kevin-421 — APPROVED** [review]
Hello @KuanHsienYEH, thank you for taking this issue. I really liked how you included the code blocks in your pull request. Overall good job and thank you for volunteering.

**Review by jphamtv — APPROVED** [review]
Hey @KuanHsienYEH,
The pull request is done with the correct branch, your summary of changes is clear, and the code change is clean and accurate. I verified the change didn't alter the appearance of the page. Great job!

**Comment by tonyvang** [comment]
I'm sorry for missing my eta on reviewing this pull request. My availability this week got taken up dealing with a car emergency. Congratulations on the merge!

**Pull request merged**
