### PR TITLE
Update program-area.md Text

### LINKED ISSUE #2273: Add Program Area: New Schools Today
### Overview
We need to add program area information to the New Schools Today project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Diversity, Equity & Inclusion
```

### Resources/Instructions
File location to make the change: _projects/new-schools-today.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/new-schools-today.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

### PR DESCRIPTION
**Pull request by Sparky-code**
Fixes #2273

### What changes did you make and why did you make them ?

  - updated semantics for 'program-area:' on line 54

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
  <summary>Program Area Card Before Text Update</summary>

 image

</details>

<details>
  <summary>Program Area Card Before Text Update</summary>

image

</details>
</summary>

### CODE REVIEW

**Comment by Sparky-code** [comment]
Potential Blocker: asking for clarification that updates to .md would not reflect beyond the file (i.e in the projects page html).

Branch:  Sparky-code:update-program-area-text-2273

**Review by JessicaLucindaCheng — COMMENTED** [review]
@Sparky-code As far as I know, the change is reflected only on the card for [New Schools Today on the Projects page](https://www.hackforla.org/projects/).

- [x] Thus, please edit your post above under the section "Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)" with before and after screenshots. If you need it, here is a link to more detailed instructions: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available

- [x] Also, please add your pr to the Project Board.

  <details>
  
    <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
    
    1) On the right, under the "Projects" section
      how-to-add-to-the-project-board1
    
    2) Click on the gear icon
      Add-to-project-board
    
    3) Then click on Project Board to add your pull request to the project board.
      how-to-add-to-the-project-board3
  
  </details>

**Comment by Sparky-code** [comment]
Progress: Completed pending a re-review. cleared and updated docker/browser to reflect visual changes in screenshots
Blockers: An error with the docker cache led me to believe this issue didn't have visual changes. 
Availability: ~3hrs avail this weekend, monitoring this issue for review
ETA: Friday EOD, pending review

**Review by JessicaLucindaCheng — APPROVED** [review]
@Sparky-code Changes look good to me! Feel free to pick up a small issue.

Before you start on your next issue, please update your forked gh-pages. If needed, here are detailed instructions for how to do so: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream

**Pull request merged**
