### PR TITLE
removed thomas demoner from _projects/epunge-assist

### LINKED ISSUE #5752: Update Project Profile: Expunge Assist (Remove Thomas Demoner)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, remove
```
  - name: Thomas Demoner
    role: Product Manager, Development
    links:
      slack: 'https://hackforla.slack.com/team/U02DFJ72V8Q'
      github: 'https://github.com/thomasdemoner'
    picture: 'https://avatars.githubusercontent.com/thomasdemoner'
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [ ] Once your pull request is merged, go to #5627 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      
    </details>

### Resources/Instructions
- This issue was initiated by #5627

[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by ChrisKildunne**
Fixes #5752

### What changes did you make?
  - Deleted Thomas Demoner from leadership in projects/expunge-assist.md file

### Why did you make the changes (we will use this info to test)?
  - To keep an up to date list of the current project team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 11/16/23
Availability: Weekday evenings

**Comment by kwangric** [comment]
ETA: EOD 11/14
Availability: All day 11/14

**Comment by freaky4wrld** [comment]
Availability : Evenings
ETA : EOD 11/14

**Review by freaky4wrld — APPROVED** [review]
Finally you resolved the previous merging conflicts, this looks fine to me
- the to/from branches are accurate
- the changes specified are done correctly
- the visual changes are clearly scene

Nice work there @ChrisKildunne , thanks @kwangric for highlighting the merging conflicts, I would be more careful from now on

**Review by pdimaano — APPROVED** [review]
@ChrisKildunne Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed and the requested information was removed. Well done!

**Pull request merged**
