### PR TITLE
Change bold to strong in step 5

### LINKED ISSUE #2429: Accessibility: Change bold to strong in step 5 of getting-started.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [x] Change the b tag to strong tag within `pages/getting-started.html` in line 201 only (step 5)
- [x] **Line 201**

From:
```
<p class="getting-started-step-title-header">STEP 5: <b>Join a Project</b></p>
```
To:
```
<p class="getting-started-step-title-header">STEP 5: <strong>Join a Project</strong></p>
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected webpage](https://www.hackforla.org/getting-started)
- Directory to find the page in once you have it in your IDE: `pages/getting-started.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/pages/getting-started.html#L201

### PR DESCRIPTION
**Pull request by answebdev**
Fixes #2429

### What changes did you make and why did you make them ?

  - Changed the b tag to strong tag within pages/getting-started.html in line 201 only (step 5) to be WCAG compliant and ensure the same experience to all users.

### Screenshots of Proposed Changes Of The Website

- b tag changed to strong tag, so no visual changes to the website.

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
Review ETA: End of day 2/17/22
Availability: Thursday 6-7 pm Pacific

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@answebdev Thank you for making your first PR. For this issue, changes need to be made to line 201 which I can see, however, I also see a lot of changes mostly related to indentation and spacing. Just wanted to confirm with you, I have noticed VS code plug in might be the cause. Except line 201, other changes should not be part of this PR. 
- Also, request you to please add this PR to the project board. Thank you.

**Comment by answebdev** [comment]
@SAUMILDHANKAR 
Thank you for reviewing my PR. And yes, you are right. When I saved the file, the indentation and spacing changed in my VS Code editor. And just to confirm, so are you saying that I need to put the indentation and spacing back to how it was originally, and then do another pull request?

Also, as you requested, I have added this PR to the Project Board, under "PR Needs Review". Have I done this correctly?

UPDATE: I have fixed the indentation and spacing, and then at the end, I pushed up my changes using this:

```
git push --set-upstream origin update-change-bold-to-strong-2429
```

After doing this, I got the following message, so I'm not sure if it means my changes were pushed or not:

```
Everything up-to-date
Branch 'update-change-bold-to-strong-2429' set up to track remote branch 'update-change-bold-to-strong-2429' from 
'origin'.
```

Thank you.

**Review by SAUMILDHANKAR — APPROVED** [review]
@answebdev Thanks a lot for making all the changes. Looks good in my environment. Great job!
Feel free to pick up a good second issue next.

**Comment by answebdev** [comment]
@SAUMILDHANKAR Thank you, and thank you for all your help!

**Pull request merged**
