### PR TITLE
Added _sass/ to cspell.json ignorePaths array

### LINKED ISSUE #5841: Add "_sass/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "_sass/" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [ ] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by SteeRevo**
Fixes #5841

### What changes did you make?
  - Added "_sass/" to the cspell.json ignorePaths array 

### Why did you make the changes (we will use this info to test)?
  - To prevent files under the "_sass/" folder from being spell checked

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Added "_sass/" to the cspell.json ignorePaths array. No visual changes to website

### CODE REVIEW

**Comment by w1ld-r** [comment]
Availability: M-F 1pm-8pm CST
ETA: 2023-02-12 8pm CST

**Review by w1ld-r — APPROVED** [review]
Great work @SteeRevo!

- Your branch was created correctly
- You linked out to the original issue
- Your PR description was thorough
- You made the change to cspell.json correctly

Thanks for your efforts! Approved :)

**Comment by aidanwsimmons** [comment]
Availability: M-F before 6pm
ETA: 6pm Wednesday

**Review by aidanwsimmons — APPROVED** [review]
Looks great to me!
Issue linked correctly
branches look good
good descriptions of changes what/why
NIce Job!

**Pull request merged**
