### PR TITLE
Add github-handle to Zeynep Aslan in _projects/design-systems.md

### LINKED ISSUE #7286: Add github-handle for Zeynep Aslan in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Zeynep Aslan
```
with
```
- name: Zeynep Aslan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md?plain=1
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by FamousHero**
Fixes #7286

### What changes did you make?
  - Add "github-handle:" for Zeynep Aslan in design-systems.md

### Why did you make the changes (we will use this info to test)?
  - Future plans to remove github & picture fields to reduce redundancy

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
  - No visual changes were made to the website

### CODE REVIEW

**Comment by handshek** [comment]
Review ETA: by e.o.d 3-Sep-24
Availability: 7AM to 10AM weekdays

**Comment by 8alpreet** [comment]
**Review ETA:** EOD Sep 4, 2024
**Availability:** 3pm to 7pm weekdays

**Review by handshek — CHANGES_REQUESTED** [review]
Hi @FamousHero , in your writeup, please include a `Screenshots of the changes made` section and mention `No visual changes were made to the website` under it. Ping me once you're done, and I'll go ahead and approve the changes.

**Review by handshek — APPROVED** [review]
Perfect! @FamousHero 

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a clean description of what was done and why
- No visual changes were made to the website

Thanks for woking on this issue!

**Review by 8alpreet — APPROVED** [review]
Hi @FamousHero,

What went well:
* PR title is descriptive.
* Branch is named correctly.
* Related issue is linked.
* Why and What sections are answered well.
* Correct line of code is changed.

Great job on this, everything looks good. Keep up the good work!

**Pull request merged**
