### PR TITLE
Refactored project page to fix formatting issues

### LINKED ISSUE #4859: Refactor project page to fix any formatting issues with new tools data format
### Dependency

- [x] #4427 

### Overview

This task involves refactoring the code referencing page.tools to align with the newly implemented data format for tools. The modifications aim to ensure correct display, accommodating spaces in the new data structure.

### Action Items

- [x] Refer to [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) and locate where tools is being referenced
- [x] Refactor this code since tools till now be an Array so we need to map over every value
```
{% if page.tools %}<p><strong>Tools: </strong>{{ page.tools }}</p>{% endif %}
```
to
```
{% if page.tools %}
<p id='tools'>
    <strong>Tools: </strong>
    {% for tool in page.tools %}
    {{ tool }}{% if forloop.last == false %},{% endif %}
    {% endfor %}
</p>
{% endif %}
```
Making this change will ensure tools section renders correctly with the new data format of tools
- [x] Once the change is made, confirm that Tools data is rendering correctly/ as before on individual project pages.

<details>
<summary>Click here to see pictures of the tools list</summary>
<br>

<br>

</details>

### Resources/Instructions

- [Projects](https://www.hackforla.org/projects/) page
- [Liquid template language](https://shopify.github.io/liquid/)
- This issue is part of an epic: #4427

### PR DESCRIPTION
**Pull request by ldietz08**
Fixes #4859 

### What changes did you make?
  - Added a code snippet to the project page to align with the newly implemented data format for tools.
  - The main change involves adding a for loop to iterate over each item in page.tools. 

### Why did you make the changes (we will use this info to test)?
  - To provide a more flexible approach for rendering the page.tools data as a formatted list. 

No visual changes made to the site.

### CODE REVIEW

**Review by LOSjr4 — APPROVED** [review]
The pull request was done with the correct branch and the issue is linked. The tools section of the project pages appear to display correctly using Docker. The code matches the proposed code provided on the issue.
@ldietz08 , images in the PR description are to show visual changes. I figured you provided the image because the issue asked you to verify the code displayed correctly, but adding the image was not needed. I do appreciate a thorough description though.
Thank you for picking up this issue.

**Comment by chrismenke45** [comment]
Review ETA: Noon today
Availability: Now-Noon today

**Review by chrismenke45 — APPROVED** [review]
Looks good! The site doesn't have any changes and the code is correct!

**Comment by drakenguyen4000** [comment]
Code changes were made correctly as requested.  Good work @ldietz08.

**Pull request merged**
