### PR TITLE
Updated leadership info on Youth Justice Nav page

### LINKED ISSUE #3958: Update Project Profile: Youth Justice Nav
### Overview
The Youth Justice Nav page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/youthjusticenav.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Rabia Shaikh
GitHub Handle: Rabia2219
Role: Project Manager
Slack Member ID: U01QSJ10XRA
  - [x] Name: Hyun Joo Sandy Oh
GitHub Handle: doctorsandy
Role: UX Researcher
Slack Member ID: U03RZE7TTKP
- [x] Remove the following members and their information from the file:
  - [x] Nielsen (Product Manager)
  - [x] Daniel Lee (Product Designer)
- [x] Verify the changes by viewing the [Youth Justice Nav project page](https://www.hackforla.org/projects/youthjusticenav) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [youthjusticenav.md](https://github.com/hackforla/website/blob/gh-pages/_projects/youthjusticenav.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by bootcamp-brian**
Fixes #3958 

### What changes did you make and why did you make them ?

  - Updated the file "_projects/youthjusticenav.md
  - Removed info for Nielsen and Daniel Lee from leadership variable
  - Added info for Rabia Shaikh and Hyun Joo Sandy Oh to leadership variable

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

youthjusticenav-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
youthjusticenav-after

</details>

### CODE REVIEW

**Review by chrismenke45 — APPROVED** [review]
Looks good! All the necessary members have been added and the correct ones were removed. Looks good on the site.

**Comment by MarkWiltberger** [comment]
I inadvertently requested review from Chris again, then removed the request. Apologies.

**Comment by RyanGehris** [comment]
Availability: 4pm-7pm 12/15/2023, 9am-5pm 12/16/2023
ETA: by 7pm on 12/15/2023

**Review by RyanGehris — APPROVED** [review]
The file changes show that you correctly removed two members from leadership and added two new members. The changes are correctly displayed on the website.

Great work!

**Pull request merged**
