### PR TITLE
Updated typo in food_oasis.md

### LINKED ISSUE #5324: Edits to Tools data for Food Oasis
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want our website to demonstrate professionalism and attention to detail to our visitors. On the Food Oasis project, we need to make edits so that we are displaying text in a consistent manner.

### Action Items
- [x] Go to the [Food Oasis](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) markdown page and find the entry under `tools:`
- [x] Replace the line:
```
 - Google forms
```
with:
```
- Google Forms
```
- [x] Replace the line:
```
  - Usabilityhub.com surveys
```
with:
```
  - UsabilityHub
```
- [x] Confirm with Docker on your local repo that the Tools data has been changed and is shown correctly, and that no other changes have occurred, including the Food Oasis page, homepage, and Projects pages.

### Resources/Instructions
[Food Oasis](https://www.hackforla.org/projects/food-oasis) project page
[Hompage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
[Projects Check](https://www.hackforla.org/projects-check/) page
This issue was initiated by #5193

### PR DESCRIPTION
**Pull request by sayeedkhannabil**
Fixes #5324

### What changes did you make?
- Changed 2 typos in food_oasis.md documentation.

### Why did you make the changes (we will use this info to test)?
  - To maintain the uniformity between relative tool's names.

  ### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
  <summary>Visuals before changes are applied</summary>

  image

 image

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  image

 image

</details>

### CODE REVIEW

**Comment by njackman-2344** [comment]
To Review:
Availability: Sunday 3pm - 7pm Monday 10am-12pm PST

ETA: Monday 12pm PST

**Comment by sayeedkhannabil** [comment]
@njackman-2344 I have a testcase failing for `Set PR Labels/ generate-labels-artifact(pull_request)`. I have tried to figure out the cause of failing. [set-pr-labels.js](https://github.com/hackforla/website/blob/c14aca9ad2154366792df14d246d4889c3fa927b/github-actions/trigger-pr/set-pr-labels.js), in this code, its mentioned the pull request is checked to see if the pull request have a linked issue or not based on certain keywords. However, I have used `Fixes` which is a valid keyword to link an issue and the issue is also showing on development area. I am not sure if the problem is on my side or the something internal happend. If you can help me investigate that, please do so. Thanks.

**Comment by tesiahwang** [comment]
Review ETA: 9/18/2023
Availability: flexible

**Review by tesiahwang — CHANGES_REQUESTED** [review]
Great job, @sayeedkhannabil - you are attempting to merge your commit into the correct base branch and your change is applicable! Just a couple of things to note:
- When taking screenshots, ensure that all changes are visible. Your current screenshot for visuals before changes are applied does not show "Google forms".
- For linking the corresponding issue, the problem may be that you have two spaces after "Fixes" instead of one.

**Comment by njackman-2344** [comment]
@sayeedkhannabil, Nice job attempting this PR.

 I pulled the code and it seems to be ok unless I missed something or a couple spaces after like @tesiahwang suggested. I will continue to investigate.

**Comment by sayeedkhannabil** [comment]
>     * When taking screenshots, ensure that all changes are visible. Your current screenshot for visuals before changes are applied does not show "Google forms".
> 
>     * For linking the corresponding issue, the problem may be that you have two spaces after "Fixes" instead of one.

I have fixed these two. Thanks for the help.

**Review by tesiahwang — APPROVED** [review]
Thank you for making the changes, @sayeedkhannabil! Everything looks good now!

**Review by njackman-2344 — APPROVED** [review]
I see it has been approved through github action and I see the PR comment template has been improved as well. 

I see the uniformity in code as desired.

 Great Job @sayeedkhannabil for #5546

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @sayeedkhannabil, thank you for taking on the issue! The branches are correct and the Tools data was implemented correctly per issue #5324.

It looks like screenshots of `food-oasis.md` were attached to the top pull request comment. Could you replace the screenshots to show the before and after changes to the Tools list on the Food Oasis [project page](https://www.hackforla.org/projects/food-oasis) and [card](https://www.hackforla.org/#) instead?

**Comment by sayeedkhannabil** [comment]
> It looks like screenshots of `food-oasis.md` were attached to the top pull request comment. Could you replace the screenshots to show the before and after changes to the Tools list on the Food Oasis [project page](https://www.hackforla.org/projects/food-oasis) and [card](https://www.hackforla.org/#) instead?

@Adastros Sorry for the confusion. I have updated it.

**Comment by LRenDO** [comment]
Hi @sayeedkhannabil! 

Thanks for working on this issue! The changes to the images look great! When you've made changes requested by a reviewer, go ahead and re-request a review by clicking the arrow circle next to the reviewers user name in the user section.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @sayeedkhannabil, thanks for updating the screenshots! Could you also add the before and after screenshots of the Food Oasis project cards too? It should look like this

image

**Review by tesiahwang — APPROVED** [review]
Awesome - thanks for catching that, @Adastros!

**Review by Adastros — APPROVED** [review]
Hi @sayeedkhannabil, thanks for updating the screenshots!

**Pull request merged**
