### PR TITLE
removed Carlos Olivas from Lucky Parking

### LINKED ISSUE #5804: Update Project Profile: Lucky Parking (Remove Carlos Olivas)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Carlos Olivas
    role: Data Scientist
    links:
      slack:
      github:
    picture: https://avatars.githubusercontent.com/u/41702877
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by heejung-hong**
Fixes #5804 

### What changes did you make?
  - Updated Project Profile by removing Carlos Olivas from Lucky Parking 
  -
  -

### Why did you make the changes (we will use this info to test)?
  - Ticket was created for removal.
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-10 at 8 23 41 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-10 at 8 25 15 PM

</details>

### CODE REVIEW

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @heejung-hong I see that you removed the information for Carlos Olivas as requested, but it appears that information for Aletia Trepte was added in its place.  Information for Aletia Trepte was recently removed as part of https://github.com/hackforla/website/pull/5890.  You may have added those lines back into the file while resolving a merge conflict; in that case, I need to ask you to remove them.  You might want to try pushing your branch again, and if there is a merge conflict, resolve it by removing the YAML lines for both Carlos Olivas and Aletia Trepte

**Comment by mademarc** [comment]
Review ETA: 11/16/2023
Availability: 7PM

**Review by mademarc — DISMISSED** [review]
Hey @heejung-hong Great job in removing the lines 88-93 on the md file in order to make things changes effective for the page.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@heejung-hong Commits on Nov. 16th introduced changes from other issues (#5902, #5874) including changes to _data/internal/communities/ui-ux.yml.  I'm not sure how that happened.  If you reviewed pull requests associated with those issues, perhaps you pulled their commits into your issue branch by mistake.  To remove those commits you could do 
`git reset --hard cab9859`

and then use the "-force" option when you push that branch to GitHub.  

Feel free to contact me on Slack for help

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @heejung-hong this is a minor issue, but under "Why did you make the changes", please indicate the reason for the issue.  For example, in this issue, it is to keep the leadership information on the Hack for LA "Lucky Parkign" project up to date.

**Comment by roslynwythe** [comment]
Closing, will push issue branch to create a new PR

**Pull request closed without merging**
