### PR TITLE
Update civic tech jobs roster

### LINKED ISSUE #3339: Update Project Profile: [Civic Tech Jobs]
### Overview
As a product manager of Civic Tech Jobs I want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending; your card(s) can be found in this folder: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md

### Action Items

- [ ] Civic Tech Jobs Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [ ] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #3339

### What changes did you make and why did you make them ?

  - Updated the roster in the civic-tech-jobs.md file
  - Changes were made to keep up to date with current contributors

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

old_roster

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
updated_roster

</details>

### CODE REVIEW

**Comment by ericvennemeyer** [comment]
Review ETA: 6 PM 8/9/22
Availability: 3-6 PM 8/9/22

**Review by ericvennemeyer — APPROVED** [review]
Changes meet the criteria of the original issue, and do not break the site. Good work!

**Comment by d-perez-8** [comment]
@ericvennemeyer thank you!

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-08-09

**Review by arpitapandya — APPROVED** [review]
The changes looks correct! Great job!! @d-perez-8

**Comment by d-perez-8** [comment]
@arpitapandya Thank you, Arpita!

**Pull request merged**
