### PR TITLE
Update image tag (About us - sustainability) 

### LINKED ISSUE #5177: img Tag Refactor: _includes/about-page/about-card-sustainability.html - sdg5.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sustainability.html - sdg5.svg`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/sdg/sdg5.svg" alt="5 Gender Equality" />
```
to
```
<img src="/assets/images/sdg/sdg5.svg" alt="5 Gender Equality">
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by anh628**
Fixes #5177

### What changes did you make?
  - Remove ending slash for image tag with alt gender equality
 

### Why did you make the changes (we will use this info to test)?
  - Refactor so that it is consistent with how image tags are used in codebase

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Refactoring, no visual changes to the website.

### CODE REVIEW

**Comment by kabszac** [comment]
Review ETA:  02/10/23
Availability:  Monday - Saturday

**Comment by kabszac** [comment]
@anh628 On the issue #5177 check the action items as completed. Also on the projects side bar move the issue from prioritized backlog to In progress

**Comment by robertnjenga** [comment]
Review ETA:  10/03/2023
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hi @anh628! Thanks for taking up the issue.
The pull request is done with the correct branch.
You linked the issue.
Comments are filled out properly.
Code changes were made correctly in the code as stated in the issue.
Page remains the same on the browser. Great Job!

**Comment by LRenDO** [comment]
Hi @kabszac! Thanks for reviewing this PR! Great job catching that the issue was still in the backlog. If you're requesting changes, please add the requested changes to a review.  You can do that by going to the `Files Changed` tab on this page. Then clicking `Review Changes` button.  Add your requests in the comment text box and click the `Request Changes` option before clicking `Submit Review`.  You can also approve reviews from that same place. Thanks again!

**Comment by kabszac** [comment]
Hi @LRenDO. Thank you so much. Let me do that.

**Review by kabszac — CHANGES_REQUESTED** [review]
-  on the Issue page check the action items as completed. 
- Also on the projects side bar move the issue from prioritized backlog to In progress

**Comment by nikunjgupta609** [comment]
Please sir, 
assign me with this issue, please

**Comment by LRenDO** [comment]
@kabszac review looks great! Thanks for updating it!

**Comment by anh628** [comment]
@kabszac thanks for catching, just updated things.

**Review by kabszac — APPROVED** [review]
Hi @anh628  the update looks great. Great job with this pull request!

**Comment by adrianang** [comment]
Hi @anh628 — good job with this issue! The branching is set up correctly,

**Review by adrianang — APPROVED** [review]
Hi @anh628 — good job with this issue! Your branching is set up correctly, the corresponding issue is linked, the ending slash in the image tag on line 50 was deleted exactly as requested, and doing so didn't seem to affect the image on the About page when testing your branch. Your PR was also written well, providing enough description while taking care to remove the section and detail tags for the Screenshots section (as no visual changes were made).

Thank you for taking up and completing this issue! 🙌🏼

**Pull request merged**
