### PR TITLE
Remove unused alt-hero from file

### LINKED ISSUE #3203: Remove unused `alt-hero` field from jobs-for-hope.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/jobs-for-hope.md`, remove line 8 for the alt-hero
```
alt-hero: ''
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/jobs-for-hope.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/fdecdb49ef86a3cc3bf4617effe055e39efecc13/_projects/jobs-for-hope.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by jbialkin98**
Fixes #3203 

### What changes did you make and why did you make them ?

  - Removed line 8 from code, which was the alt-hero field

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by AzaniaBG** [comment]
PR review availability: 10/17/2022 1:15 pm - 2:15 pm
review ETA: 10/17/2022

**Review by AzaniaBG — APPROVED** [review]
Nice work making changes that address this issue @jbialkin98. I'm not sure which images you uploaded because they are not showing up. If those are just screenshots of the code, no need to include them in your PR :)

**Comment by richardmundyiii** [comment]
Availability: 3/18 4pm - 6pm
ETA: EOD 3/18/23

**Review by richardmundyiii — COMMENTED** [review]
@jbialkin98 Great job on your 2nd PR! The requested changes were made in the correct document, the branch is setup correctly, and the issue is properly linked. 

As mentioned before, if your PR does not include any visual changes there is no need to send a screenshot of the code. However, leave a note as to why you didn't leave a screenshot as to follow the [Contributing instructions](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available) guidelines. It should include something like this: 
```
### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

Only removed alt-text code. No visual changes to the website.
```

Overall, great work, and thank you for your time and effort.

**Pull request merged**
