### PR TITLE
Check Developer's Complexity Allowance for Issue Assignments

### LINKED ISSUE #4442: GitHub Actions: Notify developers if they are working on issues of the same complexity
### Overview
As a developer for the website team, you are expected to follow the chain of complexity when you assign yourself an issue; that is, two good first issues, one small issue, one medium issue, and at least one large issue, although we make an exception to this progression for developers who apply both `role: front end` and `role: back end/devOps` labels on their prework issues.  We want to create a GitHub Action that notifies a developer when they have assigned themselves to too many issues of a specified complexity.

### Action Items
Currently, when a developer assigns themselves an issue, a GitHub Action runs that posts a comment on the issue:
> Hi @developer, thank you for taking up this issue! Hfla appreciates you :)
> 
> Do let fellow developers know about your:-
> i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
> ii. ETA: (When do you expect this issue to be completed?)
> 
> You're awesome!
> 
> P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)
- [x] Become familiar with [HfLA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
  - [x] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Be sure to read up on using Personal Access Tokens to test the project board in your own repo ([Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))
- [x] Navigate to the [add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment) collection
- [x] Add a new .md file named `developer-complexity-reminder.md`
- [x] Copy the following text into the .md file
````
<!-- Template for a notification to the assignee that they've already worked on issue(s) of a certain complexity and they will be unassigned -->
Hello @${issueAssignee}, we appreciate you taking on issue ${issueNum}, however it looks like you've already worked on enough issues of this complexity. Try checking out some of the issues of the next complexity from the Prioritized Backlog :)

We are going to unassign you from this issue so you can take on another issue.

Hfla appreciates you! :)


P.S. There is one exception to this rule/automation, and that is if you were away for a long time, and need to do the issue ladder again.  If that is the case, please post the following note on the issue and on your prework.  A Merge team member will reassign you to this issue, and will help you get assigned to subsequent issues up to medium size.
```
I am returning after a significant time away, and need to do the issue ladder again. Please assign me back to this issue.
```
````
- [x] Create the script that checks the developer's assigned issues in [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js)
- [x] Your script should check the following:
  - [x] If the dev has assigned themself to a third `good first issue`
  - [x] If the dev has assigned themself to a second `Complexity: Small` issue, except in the case where:
     - [x]  the developer's prework issue contains both `role: front end` and `role: back end/devOps`
     - [x] AND the first `Complexity: Small` issue was either front end or backend/devOps (but not both) 
     - [x] AND the second `Complexity: Small` issue is either has both labels or the label that was not on the first `Complexity: Small` issue
  - [x] If the dev has assigned themself to a second `Complexity: Medium` issue, except in the case where:
     - [x]  the developer's prework issue contains both `role: front end` and `role: back end/devOps`
     - [x] AND the first `Complexity: Medium` issue was either front end or backend/devOps (but not both) 
     - [x] AND the second `Complexity: Medium` issue is either has both labels or the label that was not on the first `Complexity: Medium` issue
  - [x] If any of the above checks have a true outcome, the template contained in `developer-complexity-reminder.md` should be used to post a comment in the issue, **instead** of the comment that asks the dev for their availabity
  - [x] The script should also perform the following:
  - [x] Post the same comment in the developer's prework issue
     - [x] If the developer's prework issue is closed, reopen it
  - [x] Unassign the dev from the issue
  - [x] Add a `ready for prioritization` label
  - [x] Move the issue to the New Issue Approval column
- [x] Testing the new GHA in a copy of the Project Board in your repository
- [ ] Demonstrate your new GHA to the merge team

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4193
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/.github/workflows) workflows
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/github-actions) JavaScript files
- HfLA's [GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

### PR DESCRIPTION
**Pull request by jphamtv**
Fixes #4442

### What changes did you make?
  - Added new file `github-actions/trigger-issue/add-preliminary-comment/developer-complexity-reminder.md`
  - Added new file `github-actions/trigger-issue/add-preliminary-comment/check-complexity-eligibility.js` and created script that checks for complexity allowance and handles actions if issue exceeds complexity allowance
  - In the file `github-actions/trigger-issue/preliminary-update-comment.js` file:
    - Imported `checkComplexityEligibility` function module
    - Added condition logic to skip posting the preliminary update comment if the issue is not within complexity allowance (check-complexity-eligibility.js script will handle posting a comment)

### Why did you make the changes (we will use this info to test)?
  - We want to create a GitHub action script to check and notify when developers assign themselves to too many issues of specified complexity (up to medium sized issue).
  - New developers for the website team are expected to follow the chain of complexity progression when assigning themselves to an issue: two good first issues, one small issue, one medium issue, and at least one large issue. We make an exception to this progression for developers who apply both front end and back end roles on their prework issues.
  
### Information For Testing
1. Create a copy of the Project Board by following the directions outlined in [Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board).
2. Create a personal access token that will allow the automation to work on your duplicated project board by following the directions outlined in [Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board).
3. Copy Hack for LA's website repo labels into your repo using [GH CLI](https://github.com/cli/cli#installation). This command will clone the labels from the source repository to your own repository. Install the tool, login, then use this command (replace "your-username/your-repo" with your repo's information):
    ```
    gh label clone hackforla/website --repo your-username/your-repo
    ```
4. To quickly create test issues on your repository's project board, use the GitHub CLI and run the script provided in this repository: [https://github.com/jphamtv/create-issues-script](https://github.com/jphamtv/create-issues-script)

    Follow the instructions in the script's README file to set it up and execute it.
5. Please note that the script skips checking for complexity when the creator of an issue assigns themselves to that issue. To properly test the complexity eligibility checks, you'll need to create a separate GitHub test account.
6. Use the test account to self-assign the Pre-work Checklist (Skills Issue) and other issues created by the script. This will ensure that the complexity eligibility checks are triggered correctly.
7. Update the secret token in `Ask-For-Preliminary-update` job in the `github/workflows/issue-trigger.yml` file
8. In `github-actions/utils/mutate-issue-status.js` file, change the ID numbers in `WEBSITE_PROJECT_ID` and `STATUS_FIELD_ID` constants to match your repo Project Board's IDs. In `github-action/utils/_data/status-field-ids.js` file, change the ID values in `statusValues` for `New_Issue_Approval` and `In_Progress` to match your repo Project Board's IDs. You can get your Project Board's info from the [GitHub GraphQL Explorer](https://docs.github.com/en/graphql/overview/explorer) using the following query:
    ```
    query {
      viewer {
        projectV2(number: 1) {
          id
          fields(first:20) {
            nodes {
              ... on ProjectV2Field {
                id
                name
              }
              ... on ProjectV2SingleSelectField {
                id
                name
                options {
                  id
                  name
                }
              }
            }
          }
        }
      }
    }
    ```
9. In `github-actions/trigger-issue/preliminary-update-comment.js` file, add the following to the top of `memberOfAdminOrMergeTeam` function to mock the member status. Replace your_username and your_repository_name with your own information:
    ```
    if (context.repo.owner === 'your_username' && context.repo.repo === 'your_repository_name') {
      console.log('Testing environment detected. Mocking not a member of Admin or Merge team.');
      return false;
    }
    ```
  
10. In your fork of the website repository, go to "Settings" and change the default branch from gh-pages to this PR's branch. 
11. Self-assign the Pre-work Checklist (Skills Issue) with your test account and then close the issue. It should automatically move to the QA column. This is to make sure it gets moved to the In Progress column after the script re-opens it. 
12. Move issues to the Prioritized Backlog and self-assign issues to test the criteria described in the ["Your script should check the following" Action Item](https://github.com/hackforla/website/issues/4442).

### CODE REVIEW

**Comment by LRenDO** [comment]
Hi @t-will-gillis! Thanks for reviewing this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Comment by t-will-gillis** [comment]
Availability: Thurs & Fri
eta: 5/17 e.o.d.

**Comment by t-will-gillis** [comment]
need to push back my timeframe
eta now: 5/19 e.o.d.

**Review by t-will-gillis — COMMENTED** [review]
Hey @jphamtv Awesome work on this! There is a lot to review- I am still in the middle of testing and going through the workflow but these are some questions, comments, conversations to start with. I likely will add to this, and some of the questions / comments might turn out to be irrelevant, which is why this is only a review comment for now. 

- First, thanks for enforcing some styling as well as adding semi-colons in `preliminary-update-column.js`! (and prevent future CodeQL alerts)
- ~These are out of scope, but line 52...`var i...`, `i -= 1`, `eventdescriptions`~
- Nice find with the "GH CLI"! I had already copied the labels using the API, but this is faster and easier. This should be added to Tip 6 on the [Latest edits to Hack for LA's GitHub Actions](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335).
- Bravo with your `create-issues-script`! Disclosure: I have not actually used it yet. However, it makes perfect sense to just automatically spit out 6-8 issues. We (or I) should have done this already, so this is great. 
- In `check-complexity-eligibility.js`:
  - Lines 373 and 374, conversation: how are you planning to handle the column id's?
  - ~Also, should "Prioritized Backlog" be included since often the dev forgets to move the issue?~ (   Tested this: I assigned myself from "Prioritized Backlog" and still was unassigned.  )
  - Line 162: conversation only: does this need page turning? Or maybe the assumption is that if the dev has over 100 self-assigned issues we don't need to worry...
  - This is something to look at: Line 176-182, the workflow was initially crashing for me and returning ` Error: Assignee's Pre-Work Checklist not found in assigned issues.  ` but since the Pre-Work Checklist exists, it looks like the search found an issue where at least one of the elements had a null value, causing the mistaken error message.  
   
  
  <details>
  
  Screenshot 2024-05-19 215121

   </details> 
  
  - Conversation: in general, are Merge Team, Leads, devs who have 'completed the ladder' going to be excluded from this functionality? 
  - I can see that 4442 requests it, but why is the "Pre-work Checklist" reopening, and why to "New Issue Approval"?
  - (This might be part of the plan where eventually everyone's Prework becomes a record for everything that they have worked on)  

To be continued...

So again, still want to keep looking through this and might post more and/or answer my own questions, but great work!

**Comment by jphamtv** [comment]
Hey @t-will-gillis, thanks for the review and feedback so far. 

> * In `check-complexity-eligibility.js`:
>   
>   * Lines 373 and 374, conversation: how are you planning to handle the column id's?

I'm not sure I fully understand your question. Could you please clarify what you mean by "handle the column id's"? The variables declared lines 373 and 374 are used on line 397 and line 414 to handle moving the issue back to the New Issue Approval column and the Pre-work Checklist to the In Progress column. 

>   * Line 162: conversation only: does this need page turning? Or maybe the assumption is that if the dev has over 100 self-assigned issues we don't need to worry...

You're right, this is a great catch. My assumption is also that if a developer has over 100 self-assigned issues, we don't need to worry about page turning. But `direction: 'asc',` property needs to be included in the query to return the issues sorted in ascending order, as the default is descending order. This way the oldest issues are returned first.

>   * This is something to look at: Line 176-182, the workflow was initially crashing for me and returning `Error: Assignee's Pre-Work Checklist not found in assigned issues. ` but since the Pre-Work Checklist exists, it looks like the search found an issue where at least one of the elements had a null value, causing the mistaken error message.
>   
>   
>   Screenshot 2024-05-19 215121
>     
>   

Is this a persistent error or did it occur before the Prework Checklist was self-assigned? I think this error may happen when a Pre-work Checklist is first opened but not yet assigned, which could be the case during the onboarding process for new members. 

To prevent this, I can add a fallback to handle null value on the assignee ID specifically for the onboarding scenario. So the error won't happen when a new member's Pre-work Checklist is opened but not yet assigned. 

After the onboarding process is complete, this shouldn't be an issue because developers who are ready to start working on issues will have the Pre-work Checklist issue assigned to them. Let me know your thoughts on this approach, and if you have any further suggestions.

>   * Conversation: in general, are Merge Team, Leads, devs who have 'completed the ladder' going to be excluded from this functionality?

Currently, the script doesn't exclude Merge Team members, Leads, or developers who have completed the ladder from the complexity check. I could add functionality to check if the assignee is a member of the website-admin or website-merge teams and skip the complexity eligibility check if this is the case.

Regarding developers who have completed the ladder, we currently don't track this information anywhere and would need to explore a way to identify developers to exclude them from the complexity eligibility check.

>   * I can see that 4442 requests it, but why is the "Pre-work Checklist" reopening, and why to "New Issue Approval"?
>   * (This might be part of the plan where eventually everyone's Prework becomes a record for everything that they have worked on)
> 

The moving of the "Pre-work Checklist" issue to the "New Issue Approval" column when it is reopened is handled by a GitHub Action outside of this script. This GitHub Action moves all opened or reopened issues to the "New Issue Approval" column. The `check-complexity-eligibility.js` script is responsible for moving the Pre-work Checklist to the "In Progress" column after it's reopened. 

That's my understanding as well of being part of the plan to have the Pre-work Checklist become a record for everything. When I brought it up at the Dev/PM meeting, the decision was to move it to the "In Progress" column.

Thanks again for your valuable feedback and questions so far. Please let me know if you have any further questions or if there's anything else I can clarify.

**Comment by t-will-gillis** [comment]
Hey @jphamtv Sheez I lost track of this issue, sorry.

- About the column ids: What I was thinking about is [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml) and how we are using a secret to hide the `IN_PROGRESS_COLUMN_ID`. But... I am not sure why this workflow would be using this secret here, since it is very easy to find the column id without even having access to HfLA. 
  - My only thought is that maybe(?) we use a secret id so that if someone clones the repo and is careless, they won't mistakenly refer to a column in our Project Board. But that person would not have a valid access token so I am not sure why we would care. 
  - So when I asked about lines 373-374 I was wondering if you were going to use secrets to hide the column ids, but unless someone knows a good reason it probably is not needed.
- About the page turning: Agreed, we don't need more than 100 results. But great call about `direction: 'asc'`! 
- About lines 176-182: In my tests, I have had an assigned "Prework Checklist". I found that if I changed the `per_page: 20` on Line 162, everything works fine, but when `per_page: 100` there is an error> HOWEVER this could be that somewhere in my repo, one of my test issues has something weird going. This likely is not worth worrying about unless the same error pops up somewhere else.   
  
  <details>  
  
  Screenshot 2024-05-31 141103

  </details>  

- About excluding Merge Team, Leads, devs who have completed the ladder, etc.: ugh- Since it is checking for the dev's "Pre-work Checklist" anyway, maybe your workflow can check whether the dev's prework has a label that says to the effect that "this person completed the ladder and should excluded from these checks".

**Comment by t-will-gillis** [comment]
Hi @jphamtv  - 

Bonnie asked that I include our conversations from Slack- This is a summary of what is going on with the migration, etc. and is from our previous conversation 6/17/24:
You might have seen the [Sunset Notice](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/) on the Project Board. GitHub is discontinuing Projects (classic) and before August Hack for LA needs to migrate to the Projects Beta. After talking with Bonnie and the team, doing some testing, and checking the calendar, we have decided that the Website is going to migrate to the new Projects Beta on Monday, June 24th.

Sorry for the short notice- this is happening very quickly. Each of you have currently submitted a PR that involves GitHub Actions and wanted to let you know that we will need to hold off merging any new GHAs until after the migration. To make this interesting, also need to let you know that after migration, any of the existing API calls using a ‘column’ reference will no longer work because Projects Beta is not structured the same- the new term is ‘status’ and it is not interchangeable. Some other REST API endpoints that will be deprecated soon are [here.](https://docs.github.com/en/rest/projects?apiVersion=2022-11-28)

So for all of you, after migration your workflows will need to be tested using Projects Beta. If you already installed Projects (classic) on your repo you can migrate to Projects Beta for early testing. (FYI after migrating you can reopen Projects (classic)- but do that immediately if you want to keep it because that option disappeared for me after a day.)

For any workflows that currently involve moving an issue to or from a ‘column’, this should be doable using GraphQL, ProjectV2, and Status. (I have not done this yet- still learning!) And/or we can discuss other options.

Finally, one last thing I notice is that for all of you there are parts of your issue that overlap with the other two’s issues. As one example, all three of your issues include posting messages to a member’s “Pre-work Checklist”. Unfortunately, this should have been caught earlier so that each issue was worked on after the other was completed, so that you would not each have a different solution to the same problem. (I could also be wrong and maybe there will not be any conflicts.)

**Comment by t-will-gillis** [comment]
From 6/24 Slack
Hey everyone- we have migrated to Projects Beta. As I mentioned before we made revisions to all workflows that previously involved 'columns' including removing all workflow jobs that used the alex-page automation since these no longer work. "Issue Trigger", "Pull Request Trigger", and "Schedule-Friday" plus related js files had the biggest changes.

**Comment by t-will-gillis** [comment]
Hey @jphamtv You had put a ton of work into this before the projects migration fracked up everything... Were you planning to give this another go?

**Comment by jphamtv** [comment]
> Hey @jphamtv You had put a ton of work into this before the projects migration fracked up everything... Were you planning to give this another go?

Hi @t-will-gillis, thanks for checking in. Yes, I'll update and test later this week. I'll message you when it's ready for your review.

**Comment by jphamtv** [comment]
Hey @t-will-gillis, I've updated and tested the code on my repo. It's now compatible with the new Projects V2 board and includes updates such as skipping the eligibility check for Admin or Merge team members. I've also revised the testing instructions, with specific changes to Step 8. Please let me know if you need clarification or have questions.

**Comment by t-will-gillis** [comment]
Hey @jphamtv - whew, just like before this is a ton of work and the project migration did not help so thanks once again for tackling this. I am still reviewing but here are prelim comments. I have it running in my repo but still need to try a couple different scenarios to trigger the comments. 

This is going to be very annoying so I will apologize in advance. We have had a string of PRs that have similar functions, for example retrieving issue data and changing the issue’s status. These are pulled out into `/utils/query-issue-info.js`, `/utils/mutate-issue-status.js`, and `/utils/data/status-field-ids.js`, and I am writing issues to refactor “Schedule Friday” and “Issue Trigger” to use these modules and simplify files.  
-	We might need to discuss over Slack about how to approach this. I have a branch [here if you are curious](https://github.com/t-will-gillis/website/tree/refactor-issue-trigger) that I have not submitted yet for refactoring `preliminary-update-comment.js` which I am thinking should be held off until your PR is done, but hoping that you won’t mind to refactor `check-complexity-elegibility.js` to use `/utils/query-issue-info.js`, `/utils/mutate-issue-status.js`, and `/utils/data/status-field-ids.js`. Let me know what you think.
-	Regarding changes to `format-comment.js`: These look good; however this file is used by four other workflows so we can’t make changes without editing the other files also.
-	I imagine this will be OK, but will need to check that the new “Skills Issue” works now that it is replacing the “Pre-work Checklist”

To let you know, that is good info in your description and I edited the [Hack for LA’s GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335) document to include your code for copying all of HfLA’s labels at once to one’s repo and for generating issues- new Tip 8.

**Comment by jphamtv** [comment]
Hey @t-will-gillis,

>This is going to be very annoying so I will apologize in advance. We have had a string of PRs that have similar functions, for example retrieving issue data and changing the issue’s status. These are pulled out into /utils/query-issue-info.js, /utils/mutate-issue-status.js, and /utils/data/status-field-ids.js, and I am writing issues to refactor “Schedule Friday” and “Issue Trigger” to use these modules and simplify files.
> * We might need to discuss over Slack about how to approach this. I have a branch [here if you are curious](https://github.com/t-will-gillis/website/tree/refactor-issue-trigger) that I have not submitted yet for refactoring `preliminary-update-comment.js` which I am thinking should be held off until your PR is done, but hoping that you won’t mind to refactor `check-complexity-elegibility.js` to use `/utils/query-issue-info.js`, `/utils/mutate-issue-status.js`, and `/utils/data/status-field-ids.js`. Let me know what you think.

Thanks for pointing out the new utils. I somehow missed them when updating the code after the migration. I've refactored `check-complexity-eligibility.js` to use the utils and tested it on my repo. It should be good to go now.

> * Regarding changes to `format-comment.js`: These look good; however this file is used by four other workflows so we can’t make changes without editing the other files also.

I appreciate you letting me know that `format-comment.js` is used by other workflows. I should have caught this myself. I've reverted the code and included the `formatComment` function for multiple replacement objects in the `check-complexity-eligibility.js` file.

> * I imagine this will be OK, but will need to check that the new “Skills Issue” works now that it is replacing the “Pre-work Checklist”

The Skills Issue will also work if it continues using the `Complexity: Prework` label. 
 
> To let you know, that is good info in your description and I edited the [Hack for LA’s GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335) document to include your code for copying all of HfLA’s labels at once to one’s repo and for generating issues- new Tip 8.

Thank you for the feedback on my description, including my code in the wiki, and the recognition!

I updated step 8 in the testing instructions above. Please let me know if you need anything else for this PR or if we need to discuss how to handle the `preliminary-update-comment.js` file with your recent updates in #7373.

**Comment by t-will-gillis** [comment]
Hey @jphamtv  I have been testing this and wanted to give you an update. It took a lot of tweaking to get the conditions set up where the other conditions were not triggered first, but now have it so that the `check-complexity-eligibility.js` is running. Unfortunately an error keeps popping up for me that appears to be in the `fetchIssuesByAssignee()` function (starting on line 127):

```  
Error fetching issues for assignee t-will-gillis TypeError: Cannot read properties of null (reading 'id')
```  
So one or more of the issues in my repo (or possibly a PR?) is returning null values. [Link here](https://github.com/t-will-gillis/website/actions/runs/10836927499/job/30071753691) But I have not been able to track it down yet. 

I don’t know if this is a problem with the issues in my repo alone, or if something similar would occur in the live repo. If you have any good ideas, please let me know. Otherwise, it will take me a while to track down.

**Comment by jphamtv** [comment]
@t-will-gillis - You might be getting the error because you have [three Prework checklists](https://github.com/t-will-gillis/website/issues?q=is%3Aissue+assignee%3At-will-gillis+label%3A%22Complexity%3A+Prework%22+is%3Aclosed) assigned to yourself on your repo. Try assigning only one and see if you still get the error.

**Comment by t-will-gillis** [comment]
@jphamtv Closed two of the three preworks (thank you), still had the issue. Did a little more digging and found that three of my very early issues were returning "null" on "assignee.id" even though of course I was assigned (under "assignees"). Whatefs I removed those three issues and the previous error is no longer happening. will continue...

**Review by t-will-gillis — APPROVED** [review]
Hey @jphamtv I was able to run a successful demo in my repo for the situation a.) not checking if admin or merge, b.) previously assigned closed issue `Complexity: Small` with `role: back end/devOps`, c.) attempting to open a second issue matching the same size and role of closed issue. Result was that the issue was unassigned, moved to “New Issue Approval”, labeled `Ready for Prioritization`, and commented on with the specified comment. Furthermore, the “Skills Issue” was reopened and the same comment applied.  

I also tried opening a `good first issue` with two closed  `good first issue`s and got the same result. (I did not check the condition for `role: back end/devOps` and `role: front end` at the same time.)   

Fantastic work on this- especially with all of the moving parts. Thanks for incorporating the modules, providing the code snippets, and for addressing the Projects migration and previous comments.

**Pull request merged**
