### PR TITLE
Update Expunge assist project profile card

### LINKED ISSUE #1943: Update Expunge assist project profile card
### Overview
As a product manager I need to have my project profile card up to standards

### Action Items

- [x] Replace image in the card by the new one 
<details>
<summary> put this image </summary>

https://user-images.githubusercontent.com/27507664/121819463-0cd31500-cc42-11eb-8f21-afb65b0d0873.png
</details>

- [x] Change alt description to this "Image of a criminal record"
- [x] Create a pull request from the md file 
- [ ] Automatically close this issue once your PR is reviewed and merge

### Resources/Instructions
[Expunge assist md](https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md)
[Check this template md for reference](https://github.com/hackforla/website/wiki/project.md-file-template)

### PR DESCRIPTION
**Pull request by blakes24**
Fixes #1943

### What changes did you make and why did you make them ?

  - Replaced the Expunge Assist project card image
  - Changed image alt text to "Image of a criminal record"
  - Renamed duplicate alt key in `expunge-assist.md` to "alt-hero" so the correct alt text was associated with the card image

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Expunge Assist card before</summary>

Screen Shot 2021-07-22 at 9 16 58 PM

</details>

<details>
<summary>Expunge Assist card after</summary>

Screen Shot 2021-07-22 at 9 16 07 PM

</details>

### CODE REVIEW

**Review by lorenzejay — COMMENTED** [review]
I can verify that the expunge assist project image has been updated. However, upon inspecting the image alt tag from google chrome dev tools, the alt text seems to still say `Expunge Assist project logo` rather than reflecting the new alt text `Image of a criminal record`. How does the alt text look on your end when inspecting it?

**Comment by blakes24** [comment]
The alt text is correct when I inspect it now.

Screen Shot 2021-07-23 at 10 26 39 PM

When I first changed it, the old alt text was still showing for me as well. I had to stop and restart the container a couple of times before it showed the updated alt text. I'm not sure why.

**Review by lorenzejay — APPROVED** [review]
I just double checked and I see it now. Great job 👍🏼

**Comment by celinevalentine** [comment]
It looks good to me, good job!

**Comment by Aveline-art** [comment]
@celinevalentine Just want to verify that you approve of this pull request? If so, can you confirm it though approving through a review (see [this guide ](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews)on how). Thanks!

**Pull request merged**
