### PR TITLE
add github handle #7254

### LINKED ISSUE #7254: Add github-handle for Eric Vennemeyer in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Eric Vennemeyer
```
with
```
- name: Eric Vennemeyer
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by pluto-bell**
Fixes #7254

### What changes did you make?
  - added 'github-handle' under Eric  Vennemeyer's name, located under the "Tech Work Expereince" project.

### Why did you make the changes (we will use this info to test)?
  - To reduce redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

 No visual changes were made.

### CODE REVIEW

**Comment by Anahisv23** [comment]
ETA: EOD

**Comment by pluto-bell** [comment]
@t-will-gillis I hope you don't mind that I've requested you again — just looking to move into meatier issues as soon as possible and I notice you as one of the more active members/mergers. Let me know if you'd like me to pause on sending you requests!

Cheers *~

**Review by Anahisv23 — APPROVED** [review]
Hi @pluto-bell, thanks for working on this issue. Everything looks good on my end. Nice work!

What went well
- Into and from branch are set up correctly
- PR description is detailed and explains why the changes are needed and what you changed
- Appropriate lines of code were changed to add the `github-handle` variable

**Review by LRenDO — APPROVED** [review]
Hi @pluto-bell!
Great job with this pull request!

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- A note was included that there were no visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I have one non-functional request for the future. Please be more specific with the title. For example,  "added github handle for Eric Vennemeyer in tech-work-experience.md". We often have many very similar issues and it's helpful to have some specificity in the title.

Again, nice work and thanks for taking the time to contribute to the website!

**Pull request merged**
