### PR TITLE
fix Remove "good second issue"

### LINKED ISSUE #5617: Remove "good second issue" from CONTRIBUTING.md Section 2.3.c
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove mention of  the "Compleity: Good second issue" label in order to eliminate confusion, since we are no longer ceating issues with the "Complexity: Good second issue" label.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` Section 2.3.c
- [x] Remove this line:
```
* `Prioritized Backlog` column in the [filtered Project Board - **complexity: Good second issues** label](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22complexity%3A+good+second+issue%22+label%3A%22role%3A+back+end%2Fdevops%22)
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4506

### PR DESCRIPTION
**Pull request by Utkarsh3128**
Fixes #5617 & #5591 

### What changes did you make?
  - Remove "good second issue" from CONTRIBUTING.md Section 2.3.b and 2.3.c

### Why did you make the changes (we will use this info to test)?
- To eliminate confusion, since good second issues no longer exist.

### Screenshots of Proposed Changes Of The Website (if any, please do not screenshot code changes)
- No visual changes
- For Reviewers: Do not review changes locally, rather, review changes at https://github.com/Utkarsh3128/website/blob/issue-%235617/CONTRIBUTING.md

### CODE REVIEW

**Comment by romainyvernes** [comment]
Availability: 8h
ETA: 9/28

**Review by romainyvernes — CHANGES_REQUESTED** [review]
1. The issue states that the line to remove is under section 2.3.c, but the one you removed is under 2.3.b. It would make sense to have both removed since "good second issues" no longer exist anywhere, but you want to make sure to remove the correct line as stated in the issue. Then, you can see if there isn't another issue that would have been specifically created to remove the same line under section 2.3.b. If that isn't the case, you can inquire with the issue's author to suggest that the line be removed from section 2.3.b as well.
2. You updated the cspell.json file in this PR, but it is outside the scope of the issue that needs fixing. You should revert that file back to the way it was.
3. You didn't provide the test link for reviewers to ensure the changes were correctly applied as stated next to the 4th checkbox within the issue's description. I would suggest you do the following to improve the description of your PR:
    - Add back the section "Why did you make the changes"
    - Answer the question within that section (e.g., good second issues no longer exist)
    - Below that, add this statement: "For Reviewers: Do not review changes locally, rather, review changes at https://github.com/Utkarsh3128/website/blob/issue-%235617/CONTRIBUTING.md"

Lastly, it is usually good practice to name your branches with a short description that gives some insight into the issue that will be resolved within a branch. The contributing guidelines provide more details on this here: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue

I realize this may look like a lot of issues, but don't let it discourage you. I'm trying to provide as many details as possible for you to have everything you need to resolve this successfully on your own. Let me know if you have any questions and I'll be happy to help you out.

**Comment by Utkarsh3128** [comment]
@romainyvernes Sir, I have made changes as per your request. If still there is any mistake, please guide me.

**Comment by ajb176** [comment]
Hi @Utkarsh3128, 

As said in your other PR, you have to be a member of Hack for LA to work on an issue. You can find details on the [Getting Started](https://www.hackforla.org/getting-started) page. You will have to attend an on-boarding session, the next will be held on October 17th. If you have any questions about the procedure to join, feel free to reach out. Thank you for your interest.

**Pull request closed without merging**
