### PR TITLE
Add github-handle for Bonnie Wolfe in heart.md

### LINKED ISSUE #6939: Add github-handle for Bonnie Wolfe in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by daras-cu**
Fixes #6939

### What changes did you make?
  - Replaced 
``` 
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle:
```
in _projects/heart.md

### Why did you make the changes (we will use this info to test)?
  - The github-handle variable will later replace the github and picture variables in heart.md to streamline the file
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes

### CODE REVIEW

**Comment by cchrizzle** [comment]
Hi @daras-cu, looks good to me!

1. You have the correct branch linking, branch naming, and linked issue
2. You correctly added `github-handle` while also using spaces to indent as the instructions requested
3. You have an accurate and detailed description of your changes

Great job!

**Review by cchrizzle — APPROVED** [review]
Everything looks good, great job Danielle!

**Comment by ha-bach** [comment]
Review ETA: in 2 days
Availability: Wednesday, Thursday evening

**Review by ha-bach — APPROVED** [review]
Hi @daras-cu, 
- branching looks good
- relevant issue is linked
- great description of what changes and why, and visual changes
- code edit is correct and clean
approving the PR. great work and thanks for contributing!

**Pull request merged**
