### PR TITLE
redundant code in _toolkit.scss consolidated

### LINKED ISSUE #3489: Clean up selectors in _toolkit.scss
### Overview
As a developer on the website team, SCSS code is easier to understand and maintain when it does not contain duplicate selectors. This issue is to consolidate duplicate selectors within `_toolkit.scss`.

### Action Items

- [x] Duplicate selectors are present in three places within [_toolkit.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_toolkit.scss). For each instance, remove overwritten properties and combine the remaining active properties under one selector:
  - [x] `.resource-svg-icons` appears on line 120, and again on line 225. 
  - [x] `.toolkit-info-container` appears on line 126, and again on line 230.
  - [x] `.toolkit-info-container h3` appears on line 130, and again on line 231. 
- [x] Note that properties in the second selector that match properties in the first will take precedence and overwrite the previous properties. See [CSS specificity rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) for reference.

### Acceptance Criteria
- [x] Compare the toolkit page at [localhost:4000](http://localhost:4000/) with the [toolkit page on the Hack for LA website](https://www.hackforla.org/toolkit/) to ensure your code modifications don't result in any visible change.

### Resources/Instructions
The duplicate selectors were highlighted when they failed to pass a `Lint SCSS` test for PR #3483. 
[_toolkit.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_toolkit.scss)
[toolkit page](https://www.hackforla.org/toolkit/)
[CSS Specificity Rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) --> "When two selectors in the same cascade layer and origin have the same specificity, proximity is important; the last selector wins."

### PR DESCRIPTION
**Pull request by Mattre7**
Fixes #3489

### What changes did you make and why did you make them ?

  - Consolidated redundant and defunct code in _toolkit.scss:
  -  Did this for the class .toolkit-info-container, a child class it had for h3, and for the class .resource-svg-icons
  
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals side by side of live website and branch ran locally</summary>

</details>

### CODE REVIEW

**Comment by AzaniaBG** [comment]
ETA: 09/28/2022 by 5 PM
Availability: 09/26/2022 7 - 8 AM, 4 - 5 PM; 09/27/2022 7 - 8 AM, 3 - 5 PM;  09/28/2022 7 - 8 AM, 3 - 5 PM;

**Review by arpitapandya — CHANGES_REQUESTED** [review]
Hey @Mattre7 before we review or merge this PR

- which issue you worked on? Missing linked issue
- I see there's a merge conflict. Reason: Did you forget to update the website repo from your GitHub before creating the branch and started making changes? 
- Adding a link to the [Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by Mattre7** [comment]
Oops, added issue number to branch but forgot to add to the body of the post. Done now. 

Merge conflicts only look to be related to the changes that were made.

> Hey @Mattre7 before we review or merge this PR
> 
> 
> 
> - which issue you worked on? Missing linked issue
> 
> - I see there's a merge conflict. Reason: Did you forget to update the website repo from your GitHub before creating the branch and started making changes? 
> 
> - Adding a link to the [Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Review by arpitapandya — APPROVED** [review]
All the changes look correct! The website is running and doesn't break anything. Great job! @Mattre7

**Review by AzaniaBG — APPROVED** [review]
Nice work @Mattre7 ~ it looks like all changes address the issue!

**Comment by Mattre7** [comment]
Thank you both @AzaniaBG @arpitapandya !!!

**Pull request merged**
