### PR TITLE
Refactored the tools data from a string to a list - #4814 

### LINKED ISSUE #4814: Refactor Tools data for youthjusticenav.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [youthjusticenav.md](https://github.com/hackforla/website/blob/gh-pages/_projects/youthjusticenav.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Google Docs, Google Sheets
```
to:
```
tools:
  - Google Docs
  - Google Sheets
```
  - [x] Confirm that the tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by DorianDeptuch**
Fixes #4814 

### What changes did you make?
  - Replaced the tools string to a list

### Why did you make the changes (we will use this info to test)?
  - To make the necessary revisions for the filter menu on the [projects-check] page to include a dropdown for "Tools"

### CODE REVIEW

**Comment by jch1013** [comment]
ETA: 7/30, EOD
Availability: Any

**Review by jch1013 — APPROVED** [review]
Changes are being merged into gh-pages from personal branch, the changes match the changes requested in the original issue, and there is no visual change to the website. Nice work!

**Comment by yffu** [comment]
ETA: 7/30, EOD
Availability: Any

**Review by yffu — APPROVED** [review]
@DorianDeptuch the PR is into and from the correct branch, there is a linked issue, tools data displays correctly on project-check page after branch is installed, website is run and viewed in browser. Changes in source code are applicable and clean. Well done!

**Pull request merged**
