### PR TITLE
Update website's project team members

### LINKED ISSUE #3177: Update Current Project Team section for the Website Team
### Overview
As a member of the Hack for LA Website team, I want the information on the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website) to be up to date. For this issue, we will be updating the Current Project Team section of the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website).

### Action Items
 In the leadership section in [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1):
- [x] Add Phu
   - [x] Name: Phuong Van
   - [x] Title: Design Lead
   - [x] GitHub: phuonguvan
   - [x] Slack: https://hackforla.slack.com/team/U031MRNSLNS

- [x] Add Tamara Snyder
   - [x] Name: Tamara Snyder
   - [x] Title: Technical lead
   - [x] GitHub: tamara-snyder
   - [x] Slack: https://hackforla.slack.com/team/U02SQV06ARZ
       
- [x] Remove Jessica Cheng
- [x] Remove Saumil Dhankar

### Resources/Instructions
- [Hackforla.org Website project information page](https://www.hackforla.org/projects/website)
- [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #3177 

### What changes did you make and why did you make them ?

  - Added Phuong Van to the website project's team section
  - Added Tamara Snyder to the website project's team section
  - Removed Jessica Cheng from the website project's team section
  - Removed Saumil Dhankar from the website project's team section

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: EOD 6/24

**Comment by answebdev** [comment]
Availability: 1 hour
ETA: 6/24/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@BeckettOBrien Thank you for submitting you PR. For this issue, Phuong Van and Tamara Snyder needed to be added to the leadership section in `_projects/website.md`, while Jessica Cheng and Saumil Dhankar needed to be removed. I can see that you did that, and I was able to see these changes in the browser. Great job!

**Review by Sparky-code — APPROVED** [review]
I can see that you've made the appropriate changes to the website leadership in `../website.md` and that those changes are reflected in the browser. Nice work!

**Pull request merged**
