### PR TITLE
Refactored img tag events page right col #5186

### LINKED ISSUE #5186: img Tag Refactor: _includes/events-page/right-col-content.html - meetings.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/right-col-content.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="vector-img" src="../assets/images/hack-nights/meetings.svg" alt="" />
```
to
```
<img class="vector-img" src="../assets/images/hack-nights/meetings.svg" alt="">
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/left-col-content.html
2. Webpage(s): https://www.hackforla.org/events
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by erinzz**
Fixes #5186

### What changes did you make?
  - removed "/" from img tag on events page for mobile dropdown 

### Why did you make the changes (we will use this info to test)?
  - for img tag notation to be consistent with codebase 
   
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

There are no visual changes made to the website.

### CODE REVIEW

**Comment by DorianDeptuch** [comment]
Availability: Afternoons
ETA: 8/17 EOD

**Review by DorianDeptuch — APPROVED** [review]
Hello Erin,

The ending slash was removed correctly. You correctly documented the changes, and since there were no visual changes, you stated that correctly. I ran the site locally to confirm everything works as it should. Everything looks good in that regard. One suggestion that I might make is that under the "Why did you make the changes (we will use this info to test)?" section of the documentation, there is usually a reason for these changes to be made. In this case, the answer can be found within the issue itself: 

> ### Overview
> We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

Other than that, everything else looks good, great job!

**Comment by erinzz** [comment]
Hey Dorian, thank you for your feedback! Great tip that I will note for future issues!

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @erinzz — the branching is set up correctly, the corresponding issue is linked, and the change of removing the ending slash from the image tag on line 2 has been made (without any other changes) as requested. When testing your branch on my local environment, the Events page seems to be visually and functionally unaffected by this change (as expected). Good job!

Before this gets merged, there's a couple of changes that I think should be edited in the PR itself:
- In the Why section, I would say that @DorianDeptuch's suggestion would be more meaningful to add and take note of for documentation purposes, instead of explaining that ending slashes in image tags are optional.
- It would be easier to see that no visual changes have been made if they weren't inside the `<details>` tag — deleting the `<details>` and `<summary>` tags and just noting 'No visual changes to the website.` underneath the header would be better.

Once you make these changes, let me know and I'll merge this PR.

_Edit: There's also no need to assign yourself to your own pull request - I unassigned you already, but just a light FYI._

**Comment by erinzz** [comment]
Hey @adrianang, thank you for feedback and the clear instructions! I've updated the pull request documentation.

**Review by adrianang — APPROVED** [review]
@erinzz Thank you for making those changes! It looks good to me, and everything else is still set up correctly and unchanged from my last review.

Thanks for taking up this issue! 🙌🏼

**Pull request merged**
