### PR TITLE
Added title to suggest-a-feature-or-new-content-for-hackforla-org.md issue template

### PR DESCRIPTION
**Pull request by mmcclanahan**
Partial work for #2293

### What changes did you make?
  
  - Replaced `title: ''` with `title: suggest a feature or new content for the hackforla.org website`

### Why did you make the changes (we will use this info to test)?
  
  - make the form more user-friendly by having directing place holder text in the title
  - gives direction to the user to update the title 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
<!-- Notes: 
  -  No visual changes to the website

### CODE REVIEW

**Comment by FamousHero** [comment]
Availability: 5pm-9pm M-F
ETA: EOD 10/8

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @mmcclanahan Thanks for working on this atypical issue. I can see that the original issue said to submit the PR with "Partial work for # 2293", most likely so the issue does not close when your PR is merged. This is why two workflows did not run correctly- but this is OK for this issue. Some notes:
- Because the description does not say "Fixes #..." the workflow to transfer labels is not going to run. Please add the same labels from 2293 to this issue
- You did substitute the correct text as shown on the issue. However, when we were writing the issue we should have caught that the text format is not consistent. I changed the formatting on the issue- would you please replace the text from the original with the new text?
- Per 2293, please add the `### Dependency ...waiting to see...` text at the top of 2293. (If you received different instructions from someone, please note that on the PR)

Besides these items, it appears that you satisfied the first steps of the original issue. Your branches are good, you reference the orig. issue, you explain what you did and why.  Great job

**Review by FamousHero — CHANGES_REQUESTED** [review]
Hi @mmcclanahan, thanks for taking on this issue!

Things you did well:
- branch name & pr reference issue being addressed
- Description and reason for changes are clear
- Title give a good idea of what the PR does

Things to change:
- PR does not contain labels. This makes it difficult to find the PR in the future.
- Issue calls for an edit to the Issue text. Add the dependency so we know the issue has per-requisites before we can move forward.

Once the changes are made ask for a re-review and I'd be happy to approve it. Keep up the good work!

**Review by codyyjxn — CHANGES_REQUESTED** [review]
The changes look good but the checks wont pass unless you change the `Partial work` to `fixes`
Also you should provide the labels so we know if this is related to the back end or front end. 
Keep it up! Please let us know if you need any help. @mmcclanahan

**Comment by mmcclanahan** [comment]
Thank you @t-will-gillis @FamousHero and @codyyjxn for the review and help! 
I have:
-updated the title variable with the proper text format  
-added the labels from issue #2293
-moved the dependency checkbox to the top of issue #2293

Please let me know if you catch anything else.

**Review by FamousHero — APPROVED** [review]
Looks good, thank you for making the changes!

**Review by t-will-gillis — APPROVED** [review]
Hey @mmcclanahan Thanks for making the requested changes/additions - looks great!

**Review by codyyjxn — APPROVED** [review]
Great Job! @mmcclanahan Thank you for taking on this issue.

**Pull request merged**
