### PR TITLE
Fix dropdown list on the wins page

### LINKED ISSUE #4706: Fix width of dropdown list on Wins page
### Overview
We need to adjust the width of the dropdown lists in the [Wins Page](https://www.hackforla.org/wins) so that it is aligned with the width of the input on desktop and mobile.

### Action Items

- [x] Locate the `_sass/elements/_old_dropdown_filters.scss` file
- [x] Change the width to `100%` for `ul.old-filter-list li ul`
- [x] Change the width to `100%` for `@media #{$bp-below-tablet}`
- [x] To test the change locally, open the drop-downs in the [Wins Page](https://www.hackforla.org/wins)

### Resources/Instructions
<details>
<summary>Wins page - desktop view BEFORE</summary>

desktop-before

</details>

<details>
<summary>Wins page - desktop view AFTER</summary>

desktop-after

</details>

<details>

<summary>Wins page - mobile view BEFORE</summary>

mobile-before

</details>

<details>

<summary>Wins page - mobile view AFTER</summary>

mobile-after

</details>

- [Currently deployed Wins page](https://www.hackforla.org/wins)
- This issue was created as a result of #4705 
- #4608

### PR DESCRIPTION
**Pull request by rdhmdhl**
Fixes #4706

### What changes did you make and why did you make them ?

  - Adjust the width of the dropdown menu on the wins page, for both desktop and tablet/mobile
  - Made this change so the with of the dropdown menu matches the width of the unordered list, list item elements. 

<details>
<summary>Visuals before changes are applied - desktop </summary>

image

</details>

<details>
<summary>Visuals after changes are applied - desktop</summary>
  
image

</details>

<details>
<summary>Visuals before changes are applied - mobile </summary>

image

</details>

<details>
<summary>Visuals after changes are applied - mobile </summary>
  
image

</details>

### CODE REVIEW

**Comment by 93Belen** [comment]
Availability: Thursday and Sunday from 6am to 6pm
ETA: Friday by 6pm

**Comment by rdhmdhl** [comment]
something odd seems to be going on with the image file, assets/images/projects/.311data-beta.png

tried pulling upstream and it did not update the file name. last commit attempted to correct the file name

**Comment by rdhmdhl** [comment]
added the file back manually to gh-pages, and merged the changes into fix-dropdown-list-4706

**Review by 93Belen — APPROVED** [review]
Hi @rdhmdhl!
You made the PR from the correct branch, linked the issue in your description, explained your changes, and added the visuals
I know you had some trouble but you seem to have fixed them because everything looks right on my end. My guess is that you got some unmerged changes into this branch, although I would have to look more into it to say it for sure. Nevertheless you fixed it and it looks great. Good job!

**Review by blulady — APPROVED** [review]
This issue is coming from the correct branch and going to the correct branch. There is a linked issue and it is addressed by the pr. The ul.old-filter-list lis ul width is changed to 100% and @media #{$bp-below-tablet} is changed too 100%. It looks good when I run it in Docker locally.

**Pull request merged**
