### PR TITLE
added github-handle under Kevin Phan line27

### LINKED ISSUE #6169: Add github-handle for Kevin Phan in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-index.md ` in the IDE
- [x] Replace:
```
- name: Kevin Phan
```
with
```
- name: Kevin Phan
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by aswutmaxcy**
Fixes #6169 

### What changes did you make?
  - added "github-handle:" under Kevin Phan on ln 27 in _projects/civic-tech-index.md

### Why did you make the changes (we will use this info to test)?
  - make changes per instruction on issue 6169

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes were made, added code to ln 27 of file referenced.

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by colin-macrae** [comment]
Availability: 3/15, 18 (updated dates)
ETA: 3/18

**Comment by irais-valenzuela** [comment]
Review ETA: 4:15 PM 3/15/24
Availability: 3-4 PM Friday

**Review by irais-valenzuela — APPROVED** [review]
Hi @aswutmaxcy, great job on the issue! You're branches are correct, there is a linked issue, and you successfully added the github handle variable for Kevin Phan. Awesome job!

**Review by colin-macrae — APPROVED** [review]
@aswutmaxcy, great job. 

- The branch is going into the correct branch gh-pages. ✅
- The original issue [issue with #number] was properly referenced. ✅
- Per the instructions on the original issue, the specified lines of code were properly updated. ✅

**Pull request merged**
