### PR TITLE
Update alt text 3851

### LINKED ISSUE #3851: Join Us: Update alt text for Join Us - Header image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Join Us` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `pages/join-us.html`:

**From:**
```
alt="join us banner icon"
```

**To:**
```
alt=""
```

- [x] Ensure that the corresponding `Join Us webpage` stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3858 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- Join Us webpage: https://www.hackforla.org/join

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `pages/join-us.html`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
- This issue is part of epic #3858

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by angieyan**
Fixes #3851 

### What changes did you make and why did you make them ?

  - Deleted alt text of header-hero-image
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Availability: 1 hour.
ETA: By the end of the day on 2/13.

**Review by Jaretzbalba — DISMISSED** [review]
@angieyan I see that the alt has been changed accordingly to the WCAG and everything looks good. Good job on this first issue!

**Comment by bootcamp-brian** [comment]
Review ETA: 1pm 2/13/23
Availability: 1 hour

**Review by bootcamp-brian — COMMENTED** [review]
@angieyan You did a good job changing the requested alt property value, however, it looks like you've added an extra file to your repo named ".bash_profile.swp" in one of your commits. If my understanding of the issue is correct there should be no need for any file additions. Could you clarify why it was added?

**Comment by angieyan** [comment]
Bonnie, when I did fetch, it came by itself, that was my first issue and I
didn’t know what to do with it :) I hope I will not have such a problem
during my next issues )

**Comment by angieyan** [comment]
Sorry Brian, I mentioned Bonnie instead of you.

**Comment by bootcamp-brian** [comment]
I checked the main website repo and the file doesn't appear to be there so
I'm not sure why the file would show up when you did a fetch. Then again I
don't know what the file actually is either. Maybe someone will know on
Slack.

**Review by bootcamp-brian — COMMENTED** [review]
@angieyan So I asked for advice on Slack and someone confirmed that the file should be removed and gave me some instructions on how to go about it: 

"Just check out the branch, do git rm .bash_profile.swp, and git commit -m "remove swap file" and git push to hackforla"

**Comment by angieyan** [comment]
@bootcamp-brian I also asked and received the same response ) but I have
already deleted my remote repo. Should I create a new one?

**Review by bootcamp-brian — COMMENTED** [review]
@angieyan Yeah, you should be able to just checkout the branch you created for this pull request, do the deletion, then commit the change I believe.

**Comment by angieyan** [comment]
I am having trouble to delete that as I have already deleted my created branch through the terminal. Any advice?

**Comment by bootcamp-brian** [comment]
I'm not sure if it'll work the same for you since you're the one that made the branch but you can try:

git checkout -b angieyan-update-alt-text-3851
git pull https://github.com/angieyan/website.git

That should hopefully get you the local copy to change so you can delete it.

**Comment by angieyan** [comment]
Changed image alt and deleted .bash_profile.swp.

**Review by bootcamp-brian — APPROVED** [review]
Everything looks good to me now. Thanks for working with me to get that fix done. Appreciate your willingness to work together to get things figured out and your responsiveness to feedback. Great job!

**Comment by angieyan** [comment]
Thank you too Brian.

**Review by MattPereira — APPROVED** [review]
Well done @angieyan ! 

The change to remove the alt text from the header hero image looks great

Also, good job responding to changes requested and communicating with @bootcamp-brian on this PR :+1:

**Comment by angieyan** [comment]
Thank you @MattPereira ☺️

**Pull request merged**
