### PR TITLE
Update made to change bold to strong for line 91

### LINKED ISSUE #2426: Accessibility: Change bold to strong in step 2 of getting-started.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [x] Change the b tags to strong tags within `pages/getting-started.html` for line 91 (step 2) only
- [x] **Line 91**

From:
```
<p class="getting-started-step-title-header">STEP 2: <b>Join Your Community of Practice</b></p>
```
To:
```
<p class="getting-started-step-title-header">STEP 2: <strong>Join Your Community of Practice</strong></p>
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected webpage](https://www.hackforla.org/getting-started)
- Directory to find the page in once you have it in your IDE: `pages/getting-started.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/pages/getting-started.html#L91

### PR DESCRIPTION
**Pull request by 1anya1**
Fixes #2426
### What changes did you make and why did you make them ?

  - Change bold to strong in step 2 of getting-started

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visible changes made, semantic change from bold to strong.

### CODE REVIEW

**Comment by usaboo** [comment]
ETA - Saturday, Feb 26th
Availability - Thursday, Feb 24th 3PM EST - 6PM EST
                      Friday, Feb 25th 3PM EST - 6PM EST

**Comment by 1anya1** [comment]
@JasonY188 @usaboo  Can you take a look at this please and review? I am looking forward to working on my next issue. Thanks so much!

**Comment by usaboo** [comment]
> @JasonY188 @usaboo Can you take a look at this please and review? I am looking forward to working on my next issue. Thanks so much!

**Comment by usaboo** [comment]
I have an interview tomorrow morning actually, will check your PR after that!

**Comment by JessicaLucindaCheng** [comment]
@usaboo @JasonY188 I'm going to go ahead and review this now, since it has been over 24 hours and we are trying to get first and second issues reviewed within 24 hours.

**Review by JessicaLucindaCheng — APPROVED** [review]
@1anya1 Good job! Feel free to pick up a good second issue!

**Pull request merged**
