### PR TITLE
img tag refactor issue 5042, works

### LINKED ISSUE #5042: img Tag Refactor: wins page - wins-card-big-quote
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/wins-page/wins-card-template.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="wins-card-big-quote" alt=""/>
```
to
```
<img class="wins-card-big-quote" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: _includes/wins-page/wins-card-template.html
2. Webpage(s): https://www.hackforla.org/wins
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by SeyiAkinwale**
Fixes #5042

### What changes did you make?
  -removed slash in img self closing tag

### Why did you make the changes (we will use this info to test)?
  -to make the use of the img tag consistent with others on site

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  -no visual changes to website

### CODE REVIEW

**Comment by njackman-2344** [comment]
The html slash was removed in code. Great Job @SeyiAkinwale!

**Comment by mademarc** [comment]
Review ETA: 8/24/2023
Availability: 7:20PM

**Review by mademarc — APPROVED** [review]
Hey @SeyiAkinwale  Well done  removing the slash on the html img tag on the line 18 for this issue.

**Review by StephenTheDev1001 — APPROVED** [review]
Thank you for your contribution to this project. You have successfully submitted your first pull request. You have followed the best practices of linking the pull request to the relevant issue, naming the branch appropriately, and providing clear and concise descriptions of your changes and their rationale. I have tested your code in the browser and it works as expected.

**Comment by StephenTheDev1001** [comment]
@njackman-2344 
https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-6-approve-the-pull-request
image

**Pull request merged**
