### PR TITLE
update wins.js to add alt text for linkedIn icon

### LINKED ISSUE #4010: Enhance wins JavaScript to assign alt text to LinkedIn icon
### Overview
To comply with Web Content Accessibility Guidelines (WCAG), we need to ensure that image alt text on the Wins page is meaningful and appropriate for each icon.  This issue addresses the need for alt text on the LinkedIn icon in the Wins cards, which are generated using JavaScript. 

### Action Items

- [x] Understand the role of these components of the wins page: 
  - [x] The main Wins web page: [wins.html](/hackforla/website/blob/gh-pages/pages/wins/wins.html), which uses Liquid to include the template for each win card:  [wins-card-template.html](/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html)
  - [x] The JavaScript code [wins.js](hackforla/website/blob/gh-pages/assets/js/wins.js) running in the Wins web page. 
- [x] In  [wins-card-template.html](/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html), find the img element with class 'linkedin-icon', and add an empty alt attribute (`alt=''`). 
- [x] In [wins js](/hackforla/website/blob/gh-pages/assets/js/wins.js), search for the text '.linkedin-icon' in order to locate the line of code which sets the "src" attribute for the GitHub icon.  Add code to set the "alt" attribute of the icon equal to "GitHub profile for `name`" where `name` is the name of the contributor.  For example, the alt text for the image representing the link to Mary Smith's LinkedIn page should be "GitHub profile for Mary Smith".  
- [x] A change will also be required in wins.js in the function updateOverlay to set the alt text in the Overlay (when the user clicks "See More" for wide screens).  
- [x] View the wins page to test the code at mobile, tablet and full-screen widths. Also also follow the "See More" page to check the alt tag on the modal overlay.   

### Resources/Instructions

- [Wins webpage](https://hackforla.org/wins/)
- [wins.html](/hackforla/website/blob/gh-pages/pages/wins/wins.html)
- [wins js](/hackforla/website/blob/gh-pages/assets/js/wins.js)
- [wins-card-template.html](/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html)
- This issue was created as a follow-up to #2569.  See that issue for accessibility resources.

### PR DESCRIPTION
**Pull request by roslynwythe**
Fixes #4010

### What changes did you make and why did you make them ?

  - added empty alt tag to LinkedIn icon in wins-card-template.html
  - assigned alt text dynamically on page load and on overlay ("See More" in for wide-screens)
  - the change was made to conform to WCAG guidelines for providing meaningful alt text

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website

### CODE REVIEW

**Review by mariorecinos — DISMISSED** [review]
Hi @roslynwythe  Excellent work on this pull request. Your pull request came from the correct branch and your branch was named correctly and linked with the issue. Amazing work you have done all the changes and I can see them on docker.  I used the devtools in chrome to inspect your alt text for the linkedin-icon img class and all of them are dynamically rendering 
```
<img class="linkedin-icon" alt="LinkedIn profile for [different name that matches each person]" src="/assets/images/wins-page/icon-linkedin-small.svg">

```

which is the intended result amazing work.

**Comment by nnr-nnr** [comment]
Review ETA: 9 PM 3/21/23
Availability: 6-9 PM 3/21

**Review by nnr-nnr — CHANGES_REQUESTED** [review]
Hi @roslynwythe, nice work navigating this multi-part issue! It looks like you've gotten the alt text for the LinkedIn icon in both the default win card view and the "see more" win card view, which is awesome (love that detail + accessibility :)). However, the alt text attribute for the GitHub icon in the “see more” view is `alt="undefined”`. There is also no alt text attribute for the GitHub icons in the default card views, though I think the issue instructions are a bit confusing about whether this should be addressed in your PR... 

The issue attached to this PR includes the instruction:

> In [wins-overlay.html](https://github.com/hackforla/website/blob/gh-pages/_includes/wins-page/wins-overlay.html), find the img element with class 'github-icon', and add an empty alt attribute (alt='').

I don't see any such img element with class 'github-icon' is in this file. It doesn’t look like you edited the [wins-overlay.html](https://github.com/hackforla/website/blob/gh-pages/_includes/wins-page/wins-overlay.html) file either in this PR. Is this why? 

Aside: it also seems like the instruction for editing [wins js](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js) has some typos in describing LinkedIn vs GitHub icon alt text issues (?):

> In [wins js](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js), search for the text '.linkedin-icon' in order to locate the line of code which sets the "src" attribute for the GitHub icon. Add code to set the "alt" attribute of the icon equal to "GitHub profile for name" where name is the name of the contributor. For example, the alt text for the image representing the link to Mary Smith's LinkedIn page should be "GitHub profile for Mary Smith".

If you want to discuss this over a call/zoom or asynchronously through chat, let me know! My schedule’s fairly flexible: 
- tomorrow 3/22 between 12–9 PM PST
- 3/23 between 12–6 PM PST
- 3/24–26 between 12–7 PM PST

Also, if I’ve misunderstood anything, definitely please lmk — I’m very new to this :). Looks like you're making great progress with this!!

Edit: Maybe you can check off the specific instruction in the Issue #4010 that you've addressed in this PR.

**Comment by roslynwythe** [comment]
@nnr-nnr Thank you for a very detailed and thoughtful review.  I owe you an apology.  I created this issue, which addresses only the LinkedIn icon,  along with an almost identical one which addresses the GitHub icon.  I must have copied/pasted from the Github icon issue to this issue, but I missed several references to 'Github icon' that should have been changed to 'LinkedIn icon'.  The instruction to edit wins-overlay.html was also an error.  I've edited the issue with corrections and checked the Action item checkboxes.

**Review by nnr-nnr — CHANGES_REQUESTED** [review]
Hi @roslynwythe , thanks for the clarification, that's really helpful! I think there's still the same issue as before; your changes are also affecting the alt text for the GitHub icon in the "see more" view. I've taken screenshots of what my web inspector shows of the live website vs the version with your changes below. This discrepancy seems to be coming from your addition to the `makeIcon` function (lines 438 and 445 of [assets/js/wins.js](https://github.com/hackforla/website/pull/4223/files#diff-c8b2affa0d69218d0e5ecf8afc5fafb986cb1ecd98c01c99c008d68fb265095a)) since this function is also used to create the GitHub icon  (line 481), for which the `alt` attribute has not been defined in this version of code.  That is, `makeIcon` now requires an `alt` attribute, which the code for the LinkedIn icon supplies but the not the code for the GitHub icon. Maybe you can add a check in `makeIcon` to see if the `alt` parameter is defined, or give it a default value so that it doesn't show up as "undefined". 

Live Site:
Screenshot 2023-03-22 at 7 05 20 PM

vs

Your Version of the Site (notice the `alt="undefined"` attribute for the element with class `github-icon`):
Screenshot 2023-03-22 at 7 06 38 PM

**Comment by roslynwythe** [comment]
- Hi @nnr-nnr I should have mentioned that the issue to add alt text to the GitHub icon (#4088) is still in progress, so currently there is no alt text.  But in the meantime, you are absolutely correct in recommending the use of a test in makeIcon to test if the alt parameter is defined.  I've added the test in the recent commit.  Thank you for your patience and insight re-reviewing this issue and your spot-on recommendation.

**Review by mariorecinos — APPROVED** [review]

**Review by nnr-nnr — APPROVED** [review]
Great work improving the accessibility and detail of the HfLA site, @roslynwythe ! Thank you for sharing the considerations of all the changes in the PR and fixing the bug with the GitHub icon. This PR passes the ABCs 👍!

**Pull request merged**
