### PR TITLE
changed tools items format

### LINKED ISSUE #4801: Refactor Tools data for civic-tech-structure.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [ ] Refer to the [civic-tech-structure.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-structure.md) file and find the entry for `tools:`
  - [ ] Change the `tools` data from:
```
tools: Google Docs, HackforLA.org guides
```
to
```
tools:
  - Google Docs
  - HackforLA.org guides
```
  - [ ] Confirm that the Tools data on all project pages is rendered correctly
 
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by Vinny02**
Fixes #4801 

### What changes did you make?
  - The filter menu on the projects-check page requires modification to incorporate a "Tools" dropdown

### Why did you make the changes (we will use this info to test)?
  - Changed the format for better visual clarity and to be consistent with the rest of the page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No changes to site

### CODE REVIEW

**Comment by wongstephen** [comment]
Availability 8/2 12pm - 5pm
ETA 8/2 EOD

**Review by wongstephen — APPROVED** [review]
Hi @Vinny02 

Great job on the first issue. You documented the changes correctly. 

For the pull request comments, I recommend paraphrasing the description from the issue for clarity. Such as 'The filter menu on the projects-check page requires modification to incorporate a "Tools" dropdown.' 

In addition, I do not believe it is necessary to add a screenshot as there are no visual changes to the website. 

I can confirm the changes are correct and visually accurate when ran in my local environment. The card is hidden (maybe because the project is marked complete) but can be found at https://www.hackforla.org/projects/civic-tech-structure.

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @Vinny02 — going through PRs and I noticed a couple things that should be addressed and edited before this gets merged and closed:

- The 'Why' section of your PR should be a bit more descriptive, more within the context of the issue itself. The Overview in the linked issue contextualizes the reason for this change, so I would edit this section with a quick blurb about why this needs to be in a list format. @wongstephen also provided a great example above!
- I also agree with @wongstephen that this issue doesn't quite need a screenshot, but if you do provide a screenshot (for this issue and future ones), please screenshot the corresponding page on the website and not the Markdown file; the screenshot of what the user sees would be more useful to document.

Everything else is looking good so far (branching, linked issue, change itself) — just the documentation on the PR itself needs changes.

**Comment by Vinny02** [comment]
Fixed! I used your suggestion for this one @wongstephen, and I'll follow your recommended strategy to paraphrase the issue in my future PRs. Thank you for the assistance as well @adrianang.

**Review by adrianang — APPROVED** [review]
Hi @Vinny02 — the PR looks good to me! The branching is  set up correctly, the corresponding issue is linked, and the requested change was made correctly. Your branch is also showing up on my local environment through Docker and the Civic Tech Structure project visually and functionally remains unchanged.

Thank you for editing the message in your PR and for taking up this issue! 🙌🏼

**Pull request merged**
