### PR TITLE
Update wins-data.json via Google Apps Script

### PR DESCRIPTION
**Pull request by elizabethhonest**
### Dependency Before Reviewing
  - [x] #3417 - There are errors within the JSON files in this pr and this linked ticket is supposed to fix it.
### Merge Team Tasks
- [ ] This is a PR to update the wins data and is to be reviewed by the merge team.
  - [ ] The commit [Merge branch 'update-wins-data' into update-wins-data](https://github.com/hackforla/website/pull/3024/commits/4d52e3a37dbd828be528ed2fa06a381557d77eb0) with `UniqueId` for each entry should not be a part of this pr and should be removed before merging this pr.

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
Do not merge this for now. This still needs to be checked to see if the errors from before were fixed, which I think has not happened yet.

**Comment by JessicaLucindaCheng** [comment]
@SAUMILDHANKAR I know there are issue(s) that address fixing the problems with the wins json. Which issue(s) need to be closed/done before we start merging these again?

**Review by JessicaLucindaCheng — DISMISSED** [review]
I'm trying to get a screenshot of what to click on for re-review on a light theme background, so this request for change is just to capture that.

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR I know there are issue(s) that address fixing the problems with the wins json. Which issue(s) need to be closed/done before we start merging these again?

@JessicaLucindaCheng We should review this once #2901 is done. Thanks for the follow-up.

**Comment by SAUMILDHANKAR** [comment]
Hello team,
I have been looking for ways to remove an unwanted commit [4d52e3a](https://github.com/hackforla/website/pull/3024/commits/4d52e3a37dbd828be528ed2fa06a381557d77eb0), part of this PR. I tried a few options in my own repo and wanted to share my observations before making any changes.

1. First, I tried git revert, but since the commit we are trying to remove is a merge commit and we would need to resolve merge conflicts before we can revert and it can get more complicated as well, so I am not in favor of doing this at this moment.

2. Next, I tried git reset and my recommendation is to go with that. Even though we would be losing some of the latest commits which are part of the update-wins-data branch of elizabethhonest bot account, in my opinion it should be fine, based on the way this workflow is set up. We would still have the time stamped data in the Google spreadsheet which can be used to replicate those commits if required.

3. Third option would be to merge the PR as it is and ignore the unwanted commit. I am not in favor of this as this might have unintended consequences at a later stage because we would be adding an unwanted commit to the branch. 

In addition to these, I will be trying out 2 more options as suggested by fellow team members which are a) trying to cherry pick commits to a new branch b) creating a new branch based of gh-pages with same name i.e., update-wins-data and changing the existing branch name by adding archive prefix to it.

**Review by aricforrest — DISMISSED** [review]

**Comment by JessicaLucindaCheng** [comment]
@arpitapandya This pr is for a Merge Team member to review and merge. I saw you assigned me as a reviewer. Since I'm no longer part of Merge Team, did you want me to explain or show you how to review this pr? (Note: I haven't actually ever reviewed one of these prs before either because of issues with it.)

**Comment by arpitapandya** [comment]
> @arpitapandya This pr is for a Merge Team member to review and merge. I saw you assigned me as a reviewer. Since I'm no longer part of Merge Team, did you want me to explain or show you how to review this pr? (Note: I haven't actually ever reviewed one of these prs before either because of issues with it.)

Hey, @JessicaLucindaCheng I think you have self requested about 7 months ago, So I thought you have more idea about what this PR is about since @SAUMILDHANKAR isn't active anymore. But yes, If you can't then I will be happy to look at it and will ask you if something I don't understand that you might know.

**Comment by JessicaLucindaCheng** [comment]
@arpitapandya I self-requested to review it because I was testing something with prs and using this pr as an example to take a screenshot. However, I think it best if you or another Merge Team member review it, and let me know if you have questions.

I'm going to un-assign myself from reviewing this pull request for now. If you run into difficulties or want me to take a second look after reviewing it yourself, let me know.

**Review by jdingeman — APPROVED** [review]
Approving for PR to be merged. The issue linked to it describes the empty key-value pairs as not being an issue any longer. Merging this to continue investigating the Google Apps Script issues and get them fixed.

**Comment by roslynwythe** [comment]
> Approving for PR to be merged. The issue linked to it describes the empty key-value pairs as not being an issue any longer. Merging this to continue investigating the Google Apps Script issues and get them fixed.

@jdingeman OK if I do an end to end test on wins display column, with another merge?  Or has that been done already?  Also should I investigate the possibility of automating the merge ?

**Comment by jdingeman** [comment]
> > Approving for PR to be merged. The issue linked to it describes the empty key-value pairs as not being an issue any longer. Merging this to continue investigating the Google Apps Script issues and get them fixed.
> 
> @jdingeman OK if I do an end to end test on wins display column, with another merge? Or has that been done already? Also should I investigate the possibility of automating the merge ?

Sure, you can do the end test. If you'd like to investigate the possibility of automating the merge then go ahead, though I would talk with Bonnie just to make sure that we want it to be updating automatically with no intervention

**Pull request merged**
