### PR TITLE
Dropdown fix

### LINKED ISSUE #3256: Create filter_dropdown.scss File in Elements Folder
### Overview

Currently, the dropdown filters menus on the projects page and the toolkit page use different SCSS classes, which creates visual inconsistency for the user and also makes it hard for future developers to apply changes correctly. We need to create an SCSS file the will contain all the classes necessary to build our filter menus and store it in the [elements folder](https://github.com/hackforla/website/tree/gh-pages/_sass/elements) for future use.

### Action Items

- [x] create a new SCSS file in the [elements folder](https://github.com/hackforla/website/tree/gh-pages/_sass/elements) called _dropdown_filters.SCSS.
- [x] Copy the entire contents of the  [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) file into the new _dropdown_filters.scss file.
- [x] Import the new scss file you created into main.scss and delete the import for the original [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) 
- [x] After you verify that the contents has been copied correctly, delete the original [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) file in your local repo and test the site to make sure nothing is broken.
- [x] Push your code to your feature branch.
- [ ] Demo your code with the merge team/tech leads. Which has not been made at this time.  Check the bottom of this issue to see if an issue has been made yet.  if not, leave a comment with this issue being done https://github.com/hackforla/website/issues/3277, if yes, then release dependency on the new issue that related this one.

### Note to Merge Team/Tech Leads:
- [ ] If moving this file does not break any code on the site, have the assignee open a pull request and the changes can be merged. If something does break, create an issue to investigate why and correct it.

### Resources/Instructions

Here is the _project-filter.scss file:
https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss

### PR DESCRIPTION
**Pull request by DmitriiTsy**
Fixes #3256

### What changes did you make and why did you make them?
- Created dropdown_filters.SCSS in this _path: /hackforla/website/_sass/elements_
- Copied all styles from  _project-filter.scss _(Path: hackforla/website/_sass/components)_ to dropdown_filters.SCSS

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 10/25/22 @ 11pm
Availability: 9pm - 11pm

**Comment by giroz** [comment]
ETA: 10/26/22 
Availability: 2 hours

**Review by jyaymie — COMMENTED** [review]
Great work, @DmitriiTsy! The functionality of the dropdown filters menus seems to be preserved after your changes were made. I did want to mention a few things:

- On my code editor, I see the new file name with the file extension in lowercase (i.e., `dropdown_filters.scss` instead of `dropdown_filters.SCSS`). I don't know if that's what you're seeing on your end. @kathrynsilvaconway, does casing matter in this case?
- I was wondering if the last action item in the issue was taken care of. I wasn't sure as I didn't see anything related to it in the comments.
- In the future, I would include the issue number in your branch name so we can identify the issue number at a glance.
- In the future, if there are no visual changes to the website, I would make a brief note that that's the case in the body of the PR.

I'm happy to approve once there's confirmation about that last action item!

**Review by giroz — CHANGES_REQUESTED** [review]
Good job, Dmitrii.  I see you copied the file over to file to the new location but you didn't change the name of file to the dropdown_filters.scss.  At least this is what I saw in my vs code editor.

**Comment by MattPereira** [comment]
ETA: End of Day 10/28/22
Availability: 2 hours

**Review by MattPereira — DISMISSED** [review]
Good work @DmitriiTsy ! :+1: 

It looks like you renamed `_project-filter.scss` and moved its location rather than creating a new file and deleting the old one as instructed in issue #3256. I agree with your approach as it removes the possibility of incorrectly copying the contents of `_project-filter.scss` into `dropdown_filters.scss`.

**Comment by DmitriiTsy** [comment]
@giroz 
I just double-checked it in VS code and commit history (file changed section)
Screen Shot 2022-10-28 at 13 15 30
Look's like everything is okay.

**Review by giroz — DISMISSED** [review]
I see the change now.  Stupid me.

**Comment by esantiano** [comment]
ETA: 10/29/22
Availability: 3-5PM

**Review by esantiano — DISMISSED** [review]
Hey @DmitriiTsy

Found the changes you made to the original file name - great and simple approach to this issue, it also passes the ABC's good job!

**Comment by arpitapandya** [comment]
ETA: EOD 2022-10-30
Availability: 2 hrs

**Review by arpitapandya — CHANGES_REQUESTED** [review]
Hey @DmitriiTsy Thank you for working on this.

- Could you provide screenshot by running it locally? It is a requirement to test the site locally, and since this PR is related to CSS, I would look for if something isn't breaking the site.
- Could you provide demo to the merge team? It can be me for this as I am reviewing.

Let me know if you need help.

**Review by jdingeman — CHANGES_REQUESTED** [review]
Hi all,
When testing in your local environment, it is a good idea to `docker-compose down` and then `docker-compose up` after your changes are finished. Docker has a tendency to run an old image if it runs into an error if it's already running, and won't shut down. 
For this issue, running on my local environment, running `docker-compose up` after switching into the branch caused it to exit because it cannot find the `_project-filter.scss` file, causing `main.scss` to import a nonexistent file. 
image

In order for this to not break the page, you will need to import the newly created dropdown_filters scss file into `main.scss`.

Also, please note that, for naming conventions, the name of the filer should actually be `_dropdown_filters.scss` with the underscore in front.

**Comment by DmitriiTsy** [comment]
Thank you so much @jdingeman. Now it works fine.

**Comment by DmitriiTsy** [comment]
ETA:  2022-11-12
Availability: 2 hrs

**Comment by DmitriiTsy** [comment]
@arpitapandya

Hi, sure. 

Here is Docker container 
Screen Shot 2022-11-12 at 10 20 07

Here is the website: 
Screen Shot 2022-11-12 at 10 20 42

Everything works fine for now. I can do a real-time demo with Zoom or send you a record - please let me know which is better

**Pull request closed without merging**
