### PR TITLE
Update alt text for the Civic Opportunity Project

### LINKED ISSUE #3933: Civic Opportunity Project: Update alt text for the Civic Opportunity Project image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Civic Opportunity Project image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/civic-opportunity-project.md`:
**From:**
```
alt: 'Wireframing and designing process for Civic Opportunity Project, there are hands pointing to a tablet and papers of the low fidelity prototyping.'
```
**To:**
```
alt: 'Civic Opportunity Project'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Civic Opportunity Project Page: https://www.hackforla.org/projects/civic-opportunity-project 

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/civic-opportunity-project.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-opportunity-project.md

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by aaronweixiangli**
Fixes #3933

### What changes did you make and why did you make them ?

  -Change the alt value within _projects/civic-opportunity-project.md:
  -From: `alt: 'Wireframing and designing process for Civic Opportunity Project, there are hands pointing to a tablet and papers of the low fidelity prototyping.'`
  -To: `alt: 'Civic Opportunity Project'`
  -Reason for the changes:
As a developer, we need to provide clear and descriptive alt text for the Civic Opportunity Project image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Only alt text is changed. No visual changes to the website.

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 3/16 10 - noon
ETA: EOD 3/16

**Comment by roslynwythe** [comment]
Hi @aaronweixiangli thank you for taking up this issue.  So far it looks great but I wanted to ask if you would edit the PR text.  I like your description of what you did, but we like developers to add a note describing why the change was made.  I think the original issue has some explanation that you could copy.  Thank you!

**Comment by Thinking-Panda** [comment]
Availability: 10 AM - 3 PM
ETA: 3/17/23

**Comment by aaronweixiangli** [comment]
Hi @roslynwythe, thanks for reviewing my first good issue. I just added the note why the change was made to the PR text. Thank you!

**Review by RyanGehris — APPROVED** [review]
Your changes correctly reflect what were required from this issue. Thank you for working on this! This will help the website be more inclusive for everyone.

I am approving the changes to the code, but please read the comments above and make the necessary changes.

**Review by Thinking-Panda — APPROVED** [review]
Nice work @aaronweixiangli ! Merge branches are correct, code change is as mentioned in the issue and website runs fine in the local machine. Also, thank you for updating the PR. Thanks!

**Pull request merged**
