### PR TITLE
Update link name from Github to GitHub  in `_projects/ems-triage-tracker.md`

### LINKED ISSUE #7413: Replace `Github` with `GitHub` in _projects/ems-triage-tracker.md
### Overview
We need to replace instances of `Github` and `github` with `GitHub` so that we display the company name correctly, and test the changes to ensure the behavior and appearance of any and all related webpages are unchanged.    

### Details
The instance of "Github" that you are changing seems to relate to the creation of this button on the https://www.hackforla.org/communities-of-practice page 
 
that is created by https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html.

### Action Items
- [x] Open `_projects/ems-triage-tracker.md` in your IDE
- [x] Change
```
  - name: Github
```
to
```
  - name: GitHub
```
- [x] Find all the files that are connected to this change.  (e.g., if its a yml or md file, what files or scripts use the data stored in that file).  And document briefly how they work together.
- [x] Define where you expect the change to show up on the website (e.g., the footer of the website).  Can be on multiple pages
- [x] Write a test procedure, in a comment, and then use it to test the change.  Include a link to this comment in your PR.
- [x] Add/commit changes then create a PR as usual.  Document the test procedure in the Pull Request.  

### Resources
- This issue resulted from #6161

### Merge Team
- [x] After closing this issue, check off the dependency in #6161.  If all dependencies have been completed, close #6161

### PR DESCRIPTION
**Pull request by FamousHero**
Fixes #7413

### What changes did you make?
  
  - Updated `name: Github` to `name: GitHub` in `_projects/ems-triage-tracker.md`

### Why did you make the changes (we will use this info to test)?
  
  - To fix display issues stemming from `name: ` variable

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Project_Card_Before
Project_Overview_Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Project_Card_After
Project_Overview_After

</details>

### Connected Files
  - This file is referenced by `_layouts/project.html` to create the links for each project in the `_projects` folder.
  - This file is reference by `current-projects.js` when creating a display card for each project.

### Test Procedure
  - Follow [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) in order to clone the feature branch
  - Compare http://localhost:4000/projects to https://www.hackforla.org/projects/. Look for the **EMS-Triage-Tracker** project card and compare the `Links:` element
  -  Compare http://localhost:4000/projects/ems-triage-tracker to https://www.hackforla.org/projects/ems-triage-tracker. Look for the **Project Overview** card and compare the `Links:` element
  -  Compare http://localhost:4000/ to https://www.hackforla.org/. Look for the **EMS-Triage-Tracker** project card and compare the `Links:` element
  - Compare http://localhost:4000/projects-check to https://www.hackforla.org/projects-check. Look for the **EMS-Triage-Tracker** project card and compare the `Links:` element

### CODE REVIEW

**Comment by handshek** [comment]
ETA: e.o.d 16-Sept-2024
Availability: 7AM to 11AM weekdays

**Review by handshek — CHANGES_REQUESTED** [review]
Hi @FamousHero,

Everything looks great! However, the title of the PR is a bit vague. I suggest updating it to something like: "Update 'Github' to 'GitHub' in `_projects/ems-triage-tracker.md`"

Ping me once you've made the changes, and I'll be happy to approve it.

Thanks!

**Review by handshek — APPROVED** [review]
@FamousHero  Perfect!

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a clear and concise description of what was done and why
- Bonus points for providing a detailed test procedure
- Screenshots of before and after the changes are included

Thanks for woking on this issue!

**Comment by vorleakyek** [comment]
Review ETA: by Friday (9/20) 
Availability: M-F evening

**Review by codyyjxn — APPROVED** [review]
@FamousHero  Thank you for taking on this issue. Everything looks good and also deployed on the local server. Everything seemed to be the same. Good job!

**Comment by Thinking-Panda** [comment]
@FamousHero , Thank you for working on this issue.

**Pull request merged**
