### PR TITLE
 Tools in _projects .md files refactored

### LINKED ISSUE #4805: Refactor Tools data for food-oasis.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Photoshop, Sketch, whiteboard / paper & pencil, phone calls, paper prototyping, Google forms, Google Sheets, Google Analytics, FigJam, SPSS, Mplus, AtlasTI, Usabilityhub.com surveys

```
to
```
tools:
  - Figma
  - Photoshop
  - Sketch
  - whiteboard / paper & pencil
  - phone calls
  - paper prototyping
  - Google forms
  - Google Sheets
  - Google Analytics
  - FigJam
  - SPSS
  - Mplus
  - AtlasTI
  - Usabilityhub.com surveys
```
  - [ ] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by awellsbiz**
Fixes #4805

### What changes did you make?
  - Tools data in the _projects .md files has been refactored from a string to list.  
  

### Why did you make the changes (we will use this info to test)?
  - I made the changes to prep for the revision for the filter menu on the projects-check page to include a dropdown for "Tools"
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @awellsbiz! In reviewing your PR, I noticed that you had refactored the Tools section for every project, but the issue you assigned yourself to stated to only refactor the Tools section for the Food Oasis project (`_projects/food-oasis.md`). Please discard the changes for the 17 other projects and push a new commit.

Also, generally, if you make a PR, you don't need to assign reviewers to your PR unless there's a specific reason you need them (specifically) to review the changes (you were in prior contact with them already, they wrote the issue, etc.). This way, other developers can know which PRs need reviewing.

**Comment by awellsbiz** [comment]
Hi @adrianang

I noticed that a checkable box inside of the action items read:

   -  Confirm that the Tools data on all project pages is rendered correctly

So I completed that task, too. My apologies, I got confused.

When you say: " Please discard the changes for the 17 other projects and
push a new commit. "

Do you want me to change them back and then push a new commit, or just
disregard them?

**Comment by adrianang** [comment]
@awellsbiz No worries! I can see how you could interpret that action item in that way.

Yes, please change the Markdown files back for all of the projects, except for Food Oasis. You could look into/use `git revert` to do so pretty quickly. Then after you've reverted all the files, you could refactor the tools for Food Oasis and push that commit. For this PR to be approved, the `Files changed` at the top of your PR should have a count of 1 (for `_projects/food-oasis.md`), and lines 85–99 should be the only changes within that file.

**Comment by awellsbiz** [comment]
Hey @adrianang 

I have reverted all of the other files. Please let me know if i have done it correctly.

**Comment by adrianang** [comment]
@awellsbiz It's showing up that 22 files have been changed, likely because of the way that the commits from other PRs have been merged into your branch. Only `_projects/food-oasis.md` should be changed; all other files must remain untouched.

The way that the commits have been merged into this branch have made the commit log quite messy and has also pulled the developers of those commits into this PR's discussion; I'd suggest making a new PR on a new branch that refactors the Tools section of `_projects/food-oasis.md` only. I'll close this PR so that the other devs won't get additional messages beyond this one, and so possible merge conflicts will be reduced.

There are also some PRs that have recently been merged that are similar to your issue where it involves a refactor of the Tools data for a project; I would look at that as a reference example to see how your PR should look for your issue of refactoring the Tools data for `_projects/food-oasis.md`.

**Pull request closed without merging**
