### PR TITLE
Logo cutoff citizen page - #4226

### LINKED ISSUE #4226: Logo getting cutoff on smaller screens on Citizen Engagement page
### Overview
On the Citizen Engagement page's Organizations We Work With section, we need to fix the logo so it doesn't get cutoff in tablet and mobile views.

### Details
- Screenshot of problem:
  <details>
    <summary>Click here to see a gif of the logo being cutoff as it the view becomes smaller</summary>
    
  </details> 

- Here are screenshots of the Figma Design of the Organizations We Work With section of the Citizen Engagement page. For dimensions and other specifications, please inspect the Figma Design for the [Citizen Engagement design in the red box titled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625-0&t=xpc1QvW41BRJ0jNW-0) to see how it should look for desktop and mobile views. 

  <details>
    <summary>Click here to see screenshots of the Organizations We Work With section of the Citizen Engagement page in mobile and desktop views</summary>
  
    <b>Desktop</b>
    
  
    <b>Mobile</b>
    
  
  </details>

### Action Items
- [ ] On the Citizen Engagement page's Organizations We Work With section, fix the logo so it resizes as the screen width gets smaller and smaller. (See the Resources/Instructions' Files section for some files to get you started.) 
- [x] Make sure nothing on the website is broken in mobile, tablet, and desktop views

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to issue #3328 and check if all the issues listed under the `Dependency` section are closed. If they are all closed, move that issue (#3328) into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it. 

### Resources/Instructions
- Citizen Engagement page: https://www.hackforla.org/citizen-engagement

#### Files to get you started
- [pages/citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html)
- [_sass/components/_citizen_engagement.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_citizen_engagement.scss)

#### Additional resources
- [Liquid template language](https://shopify.github.io/liquid/)
- [SCSS](https://sass-lang.com/documentation/)
- See the Figma Design [Citizen Engagement design in the red box titled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625-0&t=xpc1QvW41BRJ0jNW-0)

### PR DESCRIPTION
**Pull request by Adaakal**
Fixes #4226

### What changes did you make and why did you make them ?

  - In In .organizations .organizations-images, changed grid-template-columns from 1fr 1fr to 1fr
  - In .organizations .organizations-images .org-img-large, changed height from 65px to auto and width from 185px to auto
  - For bp-tablet-up:
       - In .organizations .organizations-images .org-img, removed previous styling and replaced it with display: grid, place-items: center, and width: 100%
       - In .organizations .organizations-images .org-img-large, changed height from 75px to auto and max-width from 100% to width: max-content

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

(Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>

<details>

<summary>Visuals after changes are applied</summary>
  
(Paste_Your_Image_Link_Here_After_Attaching_Files)
Screen Shot 2023-03-27 at 4 15 39 PM
Screen Shot 2023-03-27 at 4 20 51 PM
Screen Shot 2023-03-27 at 4 21 08 PM

Screen Shot 2023-03-27 at 4 21 42 PM

</details>

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: EOD 03/27
Availability: after 6pm, M-F

**Comment by RyanGehris** [comment]
Review ETA: EOD 03/29
Availability: after 6pm, M-Th

**Review by RyanGehris — CHANGES_REQUESTED** [review]
You did a great job fixing the issue for when HackForLA is working with one organization. Unfortunately, the current [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17601-123536&t=ANtxFQCbATEpTer2-0) which I believe is up to date shows that the css should be able to handle displaying multiple organizations. 

Based on the figma, the image sizes should be max 200x70 for desktop and 142.86x50 for mobile/tablet. I believe that the [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property could be something to look into. 

I also wanted to note that I was able to add organizations and test the page by changing the file _data/internal/partners.yml and changing the program-area for a few partners to be 'Citizen Engagement'. Be sure to revert the changes in that file when pushing your code.

Let me know if you have any questions. Great first attempt!

**Comment by RyanGehris** [comment]
@Adaakal here are some examples of what I was pointing out regarding the multiple organizations
<details>
<summary>Gif of Organizations We Work With section  showing multiple orgs</summary>
Sorry, I had to compress the gif files so that they would be under 10mb

[citizen-engagement-desktop.gif.zip](https://github.com/hackforla/website/files/11106666/citizen-engagement-desktop.gif.zip)

[citizen-engagement-desktop.mov.zip](https://github.com/hackforla/website/files/11106690/citizen-engagement-desktop.mov.zip)


</details>

**Comment by Adaakal** [comment]
> 

Hi Ryan, thank you for your feedback. I suppose my questions are because I'm still new, but:
- I've checked the _data/internal/partners.yml file that you referenced and I only see the one partner with the program-area of 'Citizen Engagement'.

Also, I appreciated those gifs very much. I'll diving in more this weekend.

**Comment by RyanGehris** [comment]
@Adaakal you are right, there is only one partner with the program-area "Citizen Engagement". However, at any time HackForLA could have more partners for "Citizen Engagement" which is apparent in the Figma design. In my GIF, I added other fake partners just to test how your css changes would work if there were multiple "Citizen Engagement" partners. 

I am happy to help explain more if you need.

**Comment by JessicaLucindaCheng** [comment]
@Adaakal Sorry, I wasn't clear about what the result should be when it is fixed. However, I agree with what @RyanGehris has suggested and commented above.

Also, please add a before image where it says, "Visuals before changes are applied" in your pull request post. Thanks.

Here are screenshots of the Figma Design of the Organizations We Work With section of the Citizen Engagement page. For dimensions and other specifications, please inspect the Figma Design for the [Citizen Engagement design in the red box titled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625-0&t=xpc1QvW41BRJ0jNW-0). 

<details>
  <summary>Click here to see screenshots of the Organizations We Work With section of the Citizen Engagement page in mobile and desktop views</summary>

  <b>Desktop</b>
  

  <b>Mobile</b>
  

</details>

**Comment by jdingeman** [comment]
@Adaakal - are you still working on this issue? Please provide us with an update.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman 
- Adaugo unassigned themselves. See the history in the issue: #4226

**Pull request closed without merging**
