### PR TITLE
removed unused filed

### LINKED ISSUE #3216: Remove unused `alt-hero` field from writeforall.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/writeforall.md`, remove line 10 for the alt-hero
```
alt-hero: 'A large rainbow-colored background with a rainbow document searcher icon in the middle.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/writeforall.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a2c97475e2d1ab5956bf5cbe95c7e251ce8a1033/_projects/writeforall.md?plain=1#L10

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #3216

### What changes did you make and why did you make them ?

  - Removed unused field

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by alan-zambrano — APPROVED** [review]
This looks great! I see you've removed the correct line as dictated by the original issue. There are no visual changes, so screenshots are not necessary. Well done!

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Tuesday, June 7th

**Review by Wny-Duong — APPROVED** [review]
Line 10 of writeforall.md containing the alt-hero is removed as it should be. Good work.

**Review by kathrynsilvaconway — APPROVED** [review]
@arpitapandya Looks good. Thanks for taking care of this issue. For your future reference, when issuing a pull request with no visual changes, be sure to note that there are no visual changes to the site in the 'What changes did you make and why' section. Nice work overall.

**Pull request merged**
