### PR TITLE
Changed Website Markdown File to Improve Accessibility 

### LINKED ISSUE #4354: Change website project description to enable proper screen reader pronunciation of "Hack for LA"
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  In the project description of the website project, we will replace the text "hackforla.org" with "Hack for LA Site (hackforla.org)".  

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `description` variable.  
- [x] In the starting text of the `description` variable, replace the string
`The hackforla.org website` 
with
`The Hack for LA Site (hackforla.org)`
- [x] Do not modify any other instances of `hackforla.org`
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) and on the [Website Project Page](https://www.hackforla.org/projects/website).  The location of the modified text is shown the screenshots in the Resources section below. 

### Resources/Instructions
 
<details><summary>Display of the Project Description on the Hack for LA Current Projects page (circled)</summary>

image

</details> 

<details><summary>Display of the Project Description on the Hack for LA Website Project page (circled)</summary>

image

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)

### PR DESCRIPTION
**Pull request by ldietz08**
Fixes #4354

### What changes did you make and why did you make them ?

  - Updated project description by replacing 'The hackforla.org website' with 'The Hack for LA Site (hackforla.org)' to enable proper screen reader pronunciation. 
  - Improved accessibility of the website.

### Screenshots of Proposed Changes Of The Website 
<details>
<summary>Visuals before changes are applied</summary>

Display of the Project Description on the Hack for LA Current Projects page:
image

Display of the Project Description on the Hack for LA Website Project page:
image

</details>

<details>
<summary>Visuals after changes are applied</summary>

Display of the Project Description on the Hack for LA Current Projects page:
HFLA-current-projects

Display of the Project Description on the Hack for LA Website Project page:
HFLA-website-project

</details>

### CODE REVIEW

**Comment by jenny-alexander** [comment]
Availability: 05/25-05/26 11am-2pm
ETA: 05/26 5pm

**Review by one2code — APPROVED** [review]
I've pulled the code into my repository and verified that the changes to the markdown and display are as shown in the pull request. Good job on your pull request.

**Review by jenny-alexander — APPROVED** [review]
Hi @ldietz08 - really good job on making this change! All of the following was done accordingly:

- commit going into gh-pages from your branch (ldietz08:improve-accessibility-4354)
- linked fix in PR
- I reviewed the changes locally and see that that 'Hack for LA' appears in both Hack for LA Current Projects Page and the website project page.
- File changed is only website.md as requested.

Thanks for making the change @ldietz08 .

**Review by t-will-gillis — APPROVED** [review]
Hi @ldietz08 - awesome job! Your branches are correct, you correctly linked the issue, your description explains what and why you made the changes, you included the visuals, and your code is clean and changes only what needs to be changed.

Thank you

**Pull request merged**
