### PR TITLE
edit content-field from sustainability.yml credits

### LINKED ISSUE #2864: Edit content field and remove type field from sustainability.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/sustainability.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/sustainability.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/sustainability.yml#L4 
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/sustainability.yml#L11

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2864 

### What changes did you make and why did you make them ?

  - change content to content-type
  - remove type from line 11
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No images to provide

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Availability: Thursday 6-7pm PT
ETA: 6:30pm 1/12/23

**Review by bzzz-coding — CHANGES_REQUESTED** [review]
@Hector-Torres000 Thanks for working on your first issue! 

I see that you updated the content field and deleted the type field on line 11. Well done!

However, I noticed that on line 10, you changed the single quotes to double quotes. This change was not mentioned in issue #3811, and the other yml files have single quotes, so to keep it consistent, I suggest that you change the double quotes back to single quotes for line 10.

**Review by bzzz-coding — APPROVED** [review]

**Comment by bzzz-coding** [comment]
@Hector-Torres000 Thank you for submitting this pull request! Everything looks good!

**Comment by Adaakal** [comment]
Availability: 1/20 3-4pm

**Comment by Adaakal** [comment]
Review ETA: 3 PM 1/21/22

**Review by Adaakal — APPROVED** [review]
Hi Hector, great job and thank you for working on your first issue!

I see that you updated the content field and deleted the type field on line 11. Well done!
You've also addressed the double quotes on line 10 and you've changed them back to single quotes. Thank you!

**Pull request merged**
