### PR TITLE
Issue #6258: Remove Sarah Sanger from the page projects/website

### LINKED ISSUE #6258: Update Project Profile: remove Sarah Sanger from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Sarah Sanger
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U02M686LYET'
      github: 'https://github.com/blulady'
    picture: https://avatars.githubusercontent.com/blulady
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jonnyoe**
Fixes #6258

### What changes did you make?
  - Removed Sarah Sanger from the website team

### Why did you make the changes (we will use this info to test)?
  - Keeps the list of people on the website team current
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]Screenshot 2024-03-01 at 11 26 47 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]Screenshot 2024-03-01 at 11 27 06 PM

</details>

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  03/02/2024
Availability: 10am - 2pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @jono4727! Thank you for taking up this issue.
The basics are good, you linked the issue, gave descriptions of what changes you made and why you made the changes, and appropriate screenshots of before and after.
I'm able to confirm on Docker that the changes appear correctly.
Just a few edits needed:
- Rename your branch to a format that relates to the issue and includes the issue number e.g update-project-profile-6258
- In your pull request, right above where you linked the issue, the pull request title overflows into the section, shorten it so that "...ebsite" doesn't appear.
- Lastly delete the unused bullet points under "What changes did you make?" and "Why did you make the changes (we will use this info to test)?"
Thanks!

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Also if you can , check off the last action item in the tasks for the issue.

**Comment by jonnyoe** [comment]
I may need help with this.

I feel that I need to create a new pull request in order to have it with a different branch. 
  
I made it so that it has a different branch on my local repository but it doesn't show that change on this github pull request

**Comment by robertnjenga** [comment]
@jono4727 Yes you will need to create a PR when you rename it, and also delete the branch with the old name.

**Comment by freaky4wrld** [comment]
@jono4727 @robertnjenga closing this PR as a new PR for the same issue is created as discussed above

**Pull request closed without merging**
