### PR TITLE
Img Tag Refactor #4401

### LINKED ISSUE #4401: img Tag Refactor: Getting Started page - `step-img-icon ada.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/ada.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/ada.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by graycodesnu**
Fixes #4401 

### What changes did you make and why did you make them ?

  -Changed an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Review by agosmou — APPROVED** [review]
LGTM!

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM - 3PM
ETA: 4/27/23

**Review by Thinking-Panda — DISMISSED** [review]
Hi @graycodesnu, code changes look good and clean. But, while checking website on my local machine, the donate page is the older version and looks different from the published website. May be there is an issue with the branch you are working on.

**Comment by graycodesnu** [comment]
Hi @Thinking-Panda, can you provide more detail in terms of the changes you see and what adjustments need to be made on my end? 
I synced my forked repo + pulled before creating a new branch, and then pulled the upstream changes before submitting my pull request. I also double-checked for any changes via Docker on my end before pushing and creating this request. Additionally, I did not work on a donate page, as these changes were only made to the getting-started.html file.

**Comment by Thinking-Panda** [comment]
> Hi @Thinking-Panda, can you provide more detail in terms of the changes you see and what adjustments need to be made on my end? I synced my forked repo + pulled before creating a new branch, and then pulled the upstream changes before submitting my pull request. I also double-checked for any changes via Docker on my end before pushing and creating this request. Additionally, I did not work on a donate page, as these changes were only made to the getting-started.html file.

@graycodesnu , looks like you have followed the necessary steps before submitting a pull request. I also understand that you did not work on the donate page. I still see the older version of the donate page on my local machine. Did you try pulling from upstream again?

**Comment by graycodesnu** [comment]
@agosmou, you've already approved this request, but are you seeing the same issues @Thinking-Panda is? I understand version control differently and don't think this will be an issue, but if I need to take time to brush up, I'd rather have a second set of eyes.

**Comment by jdingeman** [comment]
@Thinking-Panda - you may be seeing the page before the cache was emptied and reloaded/the page was rebuilt in Docker. The file he changed doesn't affect the Donate page.

**Pull request merged**
