### PR TITLE
Change Alt Text For Sdg Image

### LINKED ISSUE #3099: Change alt text for sdg image in open community survey md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the open community survey project's sustainability development goal image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/open-community-survey.md`, change line 79 for the alt text:

from
```
sdg-image-alt: peace justice bottom sustainable dev goal
```
to
```
sdg-image-alt: '16: peace, justice and strong institutions'
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/open-community-survey.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/open-community-survey.md?plain=1#L101

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by GRISONRF**
Fixes #3099
### What changes did you make and why did you make them ?

  - Changed line 79 because it was inaccurate and not descriptive.
  - Changed it to: '16: peace, justice and strong institutions'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No visual changes to the website.

### CODE REVIEW

**Comment by lilyarj** [comment]
Eta: 9/23/22
Availability: 2hrs

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Comment by Unity7** [comment]
This looks good.  I was able to identify the changes you made to the alt text.

**Review by Unity7 — COMMENTED** [review]
This looks good. I was able to identify the changes you made to the alt text.

**Comment by arpitapandya** [comment]
ETA: EOD 2022-09-23
Availability: 30 minutes

**Review by arpitapandya — APPROVED** [review]
All the changes are correct and doesn't break anything. Great job!! @GRISONRF

**Pull request merged**
