### PR TITLE
added Melissa Perry to the Current Project Team section

### LINKED ISSUE #7647: Update Project Profile: LA TDM Calculator Add Melissa Perry
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Melissa Perry
    github-handle: melissaperry09
    role: UX Research Lead
    links:
      slack: https://hackforla.slack.com/team/U05MCJTTPN3
      github: https://github.com/melissaperry09
    picture: https://avatars.githubusercontent.com/melissaperry09
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by belunatic**
Fixes #7647

### What changes did you make?
  
  - I added Melissa Perry to the Current Project Team section

### Why did you make the changes (we will use this info to test)?
  
  - to updated the team roster as requested

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

FireShot Capture 073 - LA TDM Calculator - Hack for LA - localhost

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
FireShot Capture 074 - LA TDM Calculator - Hack for LA - localhost

</details>

### CODE REVIEW

**Comment by maadeshsivakumar** [comment]
Review ETA: 10 AM 11/17/24
Availability: 5-8 PM Everyday

**Review by maadeshsivakumar — APPROVED** [review]
@belunatic  Great job on your Pull Request! Thank you for your contribution keep it up !

**Comment by trimakichan** [comment]
Review ETA: 11/18/24
Availability: 10 AM to 5 PM Weekdays

**Comment by t-will-gillis** [comment]
Hi @maadeshsivakumar You have selected to assign yourself to this PR as shown here:

<details>

Screenshot 2024-11-17 093504

</details>

Reviewers do not assign themselves to PRs that they are reviewing. Please go to "Assignees", select the gear, and then un-assign yourself. Thank you!

**Review by trimakichan — APPROVED** [review]
Great job on working on this issue, @belunatic !

- The branch name includes the issue number and is appropriately named.
- The issue is linked correctly.
- Before and after screenshots are provided to show the changes.
- The code changes are correct.
- CodeQL Alerts was checked. 

**_Suggestions:_**

- Consider revising the title to make it more specific about the files you changed.

- In the What changes did you make? section, please specify the file(s) you edited. This would be very helpful.
Example: File changed: projects/tdm-calculator.md

- Check the box on the linked issue (original issue) that says:
"Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request."

Thank you for your contribution!  Keep up the great work!

**Comment by NolaDodd** [comment]
Review ETA: 6 PM 11/17/24
Availability: 2-8 PM Sunday

**Comment by santiseccovidal** [comment]
Review ETA: 16 PM 11/17/24
Availability: 2-8 PM Sun-Monday

**Review by NolaDodd — APPROVED** [review]
Great job @belunatic !

Everything is done correctly; the branch name is correct, the issue is linked, and changes are reflected in the new branch and screenshots.

Notes:

- The title is a little unclear. "I added Melissa Perry to the Current Project Team section" doesn't specify which one, since there are MANY different teams across Hack for LA. It would be good to specify that it's for the _**LA TDM Calculator**_ team. A link to the section would be nice as well. (The original issue has a link in it's subnotes:  https://www.hackforla.org/projects/tdm-calculator ) 

- Specifying which file you changed would be nice as well, so we don't have to search for it. 

Otherwise, great job!

**Review by santiseccovidal — APPROVED** [review]
Hi @belunatic everything looks great. Code changes are correct and branches are correct. For next time, please be a bit more descriptive in the **Why** and **What** sections as these are very important as issues progress in difficulty and for the rest of the devs to further understand your code.
For example, you could include the path of the file you are editing in the **What** section. 
For completeness also please check all the boxes in the issue #7647 and/or ask if you need help resolving some of them. I understand some may remain unchecked but I see one like "Find the leadership variable and add the following profile." that could be checked.

Besides that, the changes look awesome in my local version of the website. Thanks for working on this!

**Comment by t-will-gillis** [comment]
Hi @belunatic Looks good! Before your next PR, please make sure to read through the comments above - there are many good observations here to keep in mind. Thanks!

**Comment by belunatic** [comment]
@NolaDodd, @trimakichan, and @santisecco, I want to thank you all for the feedback you left for me. I will integrate it in my next PR.

**Pull request merged**
