### PR TITLE
Removed type field 2878

### LINKED ISSUE #2878: Edit content field and remove type field from solidarity.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/solidarity.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: image
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/solidarity.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/8ba65e1fc269bf94a737a9892d56e541d79b8302/_data/internal/credits/solidarity.yml#L4
https://github.com/hackforla/website/blob/8ba65e1fc269bf94a737a9892d56e541d79b8302/_data/internal/credits/solidarity.yml#L11

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #2878

### What changes did you make and why did you make them ?

  - Changed content field
  - Removed type field
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Tuesday, May 31

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Wednesday, June 1st

**Comment by Wny-Duong** [comment]
Almost everything looks good, the changes match what was requested from the original issue. 

However, Line 4 of the docker-compose.yml file should be reverted from:
`image: jekyll/jekyll:4.2.0`

back to:
`image: jekyll/jekyll:pages`

The temporary fix was meant only for resolving the "Hash into Integer" error to let people build the website locally to continue working, if I remember right. It should be set back to pages when you actually push and merge.

**Review by Wny-Duong — CHANGES_REQUESTED** [review]
Almost everything looks good, the changes match what was requested from the original issue.

However, Line 4 of the docker-compose.yml file should be reverted from:
image: jekyll/jekyll:4.2.0

back to:
image: jekyll/jekyll:pages

The temporary fix was meant only for resolving the "Hash into Integer" error to let people build the website locally to continue working, if I remember right. It should be set back to pages when you actually push and merge.

**Review by tamara-snyder — DISMISSED** [review]
Hi @arpitapandya, the changes in solidarity.yml look good. As Wilny said, please revert line 4 of docker-compose.yml and then you should be good to go! Feel free to re-request a review when you're ready.

**Review by Wny-Duong — APPROVED** [review]
Looks good now. Thanks for making the changes!

**Review by kathrynsilvaconway — APPROVED** [review]
@arpitapandya I see you have removed the type field from the solidarity.yml file and that you have also reverted line 4  in docker-compose.yml file. Nice work!

**Pull request merged**
