### PR TITLE
Add alt image tag

### LINKED ISSUE #3398: Update alt text for wins-cup image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [ ] In the file `_includes/about-page/about-card-accomplishments.html`, add the specified alt code to the following line (the code is intentionally `alt=""` (the tag is supposed to be empty):

```
<img src="/assets/images/about/wins-cup.svg">
```

New Text
```
alt=""
```

- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/about-page/about-card-accomplishments.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c88d715eeaca83a1665cfce48be1bead3f203fde/_includes/about-page/about-card-accomplishments.html#L24

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by jch1013**
Fixes #3398

### What changes did you make and why did you make them ?

  - added alt tag to ensure that alt text for images adhere to Web Content Accessibility Guidelines

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 1/17/23 11:45am
Availability: 1/17/23 Flexible

**Review by jyaymie — APPROVED** [review]
You linked the associated issue, made the appropriate change, and used the correct branches in your PR. Nicely done, @jch1013!

**Comment by chrismenke45** [comment]
Review ETA: 1/18/23 12pm
Availability: 1/18/23 Flexible

**Comment by jch1013** [comment]
Review ETA: 1/19/23 12pm
Availability: Any time 1/19 before 5pm PST

**Review by chrismenke45 — APPROVED** [review]
Great job! I love what you have done, Jackson!

**Pull request merged**
