### PR TITLE
Updated title-link for error in the credits pages

### LINKED ISSUE #3823: `Error` Credit: Fix name link
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to update an incorrect link on our Credits webpage so that proper credit is given for each image we use on the website.

### Action Items
- [x] In `_data/internal/credits/404.yml`, change the title-link from 
```
title-link: https://www.freepik.com/
```
to
```
title-link: https://www.freepik.com/free-vector/no-data-concept-illustration_5928292.htm#query=error&position=6&from_view=author
```
- [x] For the Error credit on the Credits webpage, ensure that when you click on **Error** it goes to https://www.freepik.com/free-vector/no-data-concept-illustration_5928292.htm#query=error&position=6&from_view=author.

### Resources/Instructions
- Credits webpage: https://www.hackforla.org/credits/
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/404.yml`
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/404.yml

### PR DESCRIPTION
**Pull request by steven-positive-tran**
Fixes #3823 

### What changes did you make and why did you make them ?

  - Updated title-link in credit/404.yml

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual change in the website

</details>

### CODE REVIEW

**Comment by Adastros** [comment]
Availability (PST): 9:30 - 11PM 23JAN23
Review Estimate: 10:30PM 23JAN23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @steven-positive-tran, good job on completing the issue! The correct link was added and works when clicked on the credits page. 

I noticed two things that should be fixed. 

1. In issue #3823 the task list (check boxes) are not checked off. They should be checked as you're completing the issue to help indicate what has been completed for a issue. 
2. The issue was moved to the `Questions / In Review` column. I believe this should be moved back to the `In progress` column of the project board. The `Questions / In Review` column is mainly for situations where you may have a question regarding the issue and/or require a dev lead to help review the issue/ question you had. 

An optional thing I would like to bring up is to add an explanation for why we are making the change. It can be brief and can explain why an issue was completed a particular way and/or why we are working on the issue (why fix the broken link?). Not every pull request has the why and it's not always required but I find it helpful when reviewing a pull request. In this case, it's pretty clear why we are doing this in the issue so I'm okay with it as-is.

**Comment by Adastros** [comment]
This isn't related to the issue for the pull request but I noticed that some of the link values for the `provider-link` keys use single quotes or no quotes at all. For the `title-link` keys, all the link values are consistent and do not wrap the links in quotes. Wanted to bring this up as there are a few discussions regarding styling and consistency going around (such as in pull request #3839). There are some other things such as extra spaces or comments (see [trophy.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/trophy.yml)). Hopefully this will be covered in the upcoming style guide soon.

**Comment by steven-positive-tran** [comment]
Thank you the task list has been checked and I have moved the issue to the In progress column

**Review by Adastros — APPROVED** [review]
Perfect! Thanks for implementing the updates! Everything looks good to me

**Review by roslynwythe — APPROVED** [review]
Branches are correct, code change is perfect, and in the browser, the text "Error" is correctly linked to the new URL.  Great job !

**Pull request merged**
