### PR TITLE
changed line 4 for the content field from content:icon to content-typ…

### LINKED ISSUE #2804: Edit content field and remove type field from candidates.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/candidates.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label
  

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/candidates.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/candidates.yml#L4 
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/candidates.yml#L11

### PR DESCRIPTION
**Pull request by eodero**
Fixes #2804 

### What changes did you make and why did you make them ?

-  I changed line 4 for the content field from content-icon to content-type: image

  -I removed line 11 for the type field type: icon

####Screenshots of the proposed changes of the website

-  No visual changes

### CODE REVIEW

**Comment by Sparky-code** [comment]
@eodero 
- Please update your initial comment to follow the format below. You should be reviewing your markdown using the 'preview' tab to check formatting before submitting. 
- Try to keep your title as concise as possible, leaving details for the 'what did you do and why?' header.
- Your title should be written in the infinitive tense

Title Example: Change content field variable description

image

**Comment by answebdev** [comment]
Availability: 1 hour
ETA: 6/22/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@eodero Thank you for submitting your PR. For this issue, for the file `_data/internal/credits/candidates.yml`, you needed to change line 4 for the content field from `content: icon` to `content-type: image`, as well as remove line 11 for the type field, which I can see that you did. Great job!

**Comment by answebdev** [comment]
@eodero You did a great job with this issue, but now, please be sure to add this PR to the Project Board. Also, be sure to address to comments made above by @Sparky-code . Thank you!

**Comment by eodero** [comment]
@Sparky-code Thank you for the observation

**Comment by eodero** [comment]
@answebdev Thank you

**Review by blulady — COMMENTED** [review]
Looks like there is a linked issue and it is the correct linked issue. You correctly replaced line 4 `content: icon` with `content-type: image` and deleted line 11 `alt: 'Icon of Candidates'` in your code. The changes work when I through them up locally. Good job!! Github Markdown is a bit of a challenge but easy to hit edit on other formatted comments (like the one from @Sparky-code or checkout the [docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)) and copy-pasta.

**Pull request merged**
