### PR TITLE
Add 2 weeks inactive comment 2625

### LINKED ISSUE #2625: GitHub Actions: Add a comment to be posted with 2 weeks inactive label
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want a comment to be posted whenever 2 weeks inactive label is added to an issue.

### Details
Currently, we are posting the same comment with both the `To update !` label and `2 weeks inactive` label even though there should be separate comments for each. For this issue, we want a separate comment to be posted whenever a `2 weeks inactive` label is added to an issue. You can use the format similar to this [comment](https://github.com/hackforla/website/issues/2625#issuecomment-1092536660):
<details>
  <summary>Click here to see the screenshot of the comment</summary>
  Screenshot 2023-02-06 173227
</details>

  However, it should be customized for the `2 weeks inactive` label, such as changing where it says `To Update !` to `2 weeks inactive` in the line: "Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label."

### Action Items
- [x] Review add-label.js file as well as update-instructions-template.md file located at (https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
- [x]  Add a condition which checks for the type of label being added (to update or 2 weeks inactive) and post the comment accordingly.

### Pseudo-code
- When a 2 weeks inactive label is added to an issue
    - [x] A comment should be posted similar to the one for to update label, except it should mention 2 weeks inactive label.

### Checks
- [x] Test in your local environment that it works
- [x] If a to update label is added to an issue, it should be accompanied with a comment for `to update label!`
- [x] If a 2 weeks inactive label is added to an issue, it should be accompanied with a comment for `2 weeks inactive label!`

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

### PR DESCRIPTION
**Pull request by chrismenke45**
Fixes #2625 

### What changes did you make and why did you make them ?
- In [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)
       - I modified the postComment function to take a "labelString" parameter and then pass that parameter to formatComment
       - I modified the formatComment function to take a "labelString" parameter and use that to replace ${label} in [update-instructions-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/update-instructions-template.md)
 - In [update-instructions-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/update-instructions-template.md)
       - I modified "' 'To Update !'" to "'${label}'" so there was a string to replace with the proper label
- I followed the advice in [GHA Wiki Tip 4](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and tested locally to make sure it would return the new comments as expected. I never tested it by triggering an actual GHA because this just modifies a string and shouldn't cause a problem with the action. PLEASE let me know if there is another way I should be testing it.

### Screenshots of changed comment message:

<details>
<summary>Comment added before changes</summary>

image

</details>

<details>
<summary>Comment options after changes</summary>

  
image

</details>

P.S. Any feedback on how I wrote this PR would be appreciated (Too much information included, too little information included, etc)

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Availability: Friday 2/17
ETA: Friday 5 pm

**Comment by christinaor** [comment]
Availability: Fri 2/17
ETA: Friday 10 pm

**Review by christinaor — APPROVED** [review]
Really great job on this issue, Chris! I was able to comb through the code and understand each piece and their relation to another. I think the variable names are perfectly descriptive as well. I also did not run this as a GitHub action, but tested locally and can confirm that the strings are being replaced correctly. (Would also love to go through running it as a GitHub action if someone else brings that up as an option!)

**Review by t-will-gillis — APPROVED** [review]
Hey @chrismenke45 - great job on this issue! To answer your last question (in ‘P.S.’): I think that as long as your explanations are well-organized and descriptive, I would rather read more information esp. if you believe it is important in explaining why you did what you did. I think for this particular issue you are providing the right amount of information.

I was able to run this as a GHA on my repo through a kludgy process. Here is what I saw when I was testing this: the automation triggered the comment with the message to remove the `2 weeks inactive` label and add the `Status: Updated` label. (On my repo, the bot itself added and removed the appropriate labels.)  Another thing- currently the `2 weeks inactive` labels keeps triggering when it shouldn’t and preempts the `To Update !` label. Issue #2634 is addressing this particular problem. I was able  to comment out some conditionals in `add-label.js` so that the `To Update !` label would be applied correctly. The `update-instructions-template` file comment changed back correctly to reference this label.

To summarize, I believe your edits are working as intended. Until issue 2634 is complete, from what I can tell the `2 weeks inactive` label and comment are going to continue to be triggered at the wrong times and we won’t see the `To Update !` label or comment.

Great job again!

P.S. As far as testing the GHA, Tung Lin has used nektos/act successfully for testing some GHAs and this may be the route to explore. What I did worked but it involved a.) editing the `add-update-label-weekly.yml` file to run `on: workflow_dispatch` instead of the cron schedule, b.) substituting the id of a local column on my repo for the `IN_PROGRESS_COLUMN_ID` instead of the secret which itself is referencing the id of the column in the HfLA repo, c.) creating sample issues (with labels, a reviewer, and sample comments) to populate the sample Project Board on my repo, d.) then adjusting the number of days on lines 10-12 on `add-label.js` to trigger the bot to add labels and the message you edited in `update-instructions-template.md`, and e.) commenting out the conditionals to allow `To Update !` to trigger.

**Pull request merged**
