### PR TITLE
Updated Leadership in Ops.yml

### LINKED ISSUE #2743: Communities of Practice information updates: Ops
### Overview
We need to add information on the COP page so it is up to date.

### Action Items
- [x] Please make the following changes (Note: Find and add the complete links for GitHub handle and Slack IDs in the Ops.yml file):
```
Remove person(s) and info from CoP file?

NO

If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name:

Add person(s) and info to CoP file?

YES

If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Jason Ebueng
Title: CoLead
GitHub Handle: JasonEb
Slack Member ID: U02CA3CAK7Z

Name: Nicole Dubin
Title: CoLead
GitHub Handle: Neecolaa
Slack Member ID: U02LL2XK486
```
- [x] Make sure the changes are reflected in your repo

### Resources/Instructions
- Webpage where changes should be reflected: [Hackforla COP page](https://www.hackforla.org/communities-of-practice)
- File where changes need to be made: [Ops yml file](https://github.com/hackforla/website/blob/b602137a825371cb5ff28917f892f43b030d7c44/_data/internal/communities/ops.yml)

### PR DESCRIPTION
**Pull request by lindseyindev**
Fixes #2743 

### What changes did you make and why did you make them ?

  - Added data to ops.yml to reflect the current co-leads of the ops team.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before-ops-CoP

Ops section

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after-ops-CoP

Ops section

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1.5 hours
- Review ETA: Tue, Mar 1, 2022

**Comment by tamara-snyder** [comment]
Availability: 2 hours
Review ETA: Tuesday, March 1, 2022

**Comment by SAUMILDHANKAR** [comment]
@lindseyindev Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

**Review by tamara-snyder — APPROVED** [review]
Hi Lindsey, great job on this issue! The new Slack and Github links work, the pictures are displaying as expected, and the formatting matches that of the other COP cards. Really well done.

**Review by JessicaLucindaCheng — APPROVED** [review]
@lindseyindev In my environemnt, I see Jason and Nicole in the Ops section of Communities of Practice page, and the GitHub and Slack links for them work. Good job!

**Pull request merged**
