### PR TITLE
Add new entry to leadership variable

### LINKED ISSUE #5763: Update Project Profile: Expunge Assist (Add Samantha Hyler)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Samantha Hyler
    github-handle: SamHyler
    role:  UX Content, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U025XR6MY6S
      github: https://github.com/SamHyler
    picture: https://avatars.githubusercontent.com/SamHyler
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by liamtirney**
Fixes #5763

### What changes did you make?
  - Added new entry within `_projects/expunge-assist.md` file, under `leadership` variable

### Why did you make the changes (we will use this info to test)?
  - To keep list of active HfLA project team members on the website up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>

after

</details>

### CODE REVIEW

**Comment by mshirk2** [comment]
Review ETA: 10/26/23 at 6pm (PT)
Availability: 10-6 Weekdays

**Review by mshirk2 — APPROVED** [review]
@liamtirney - Well done with this pull request!

- The new branch is merging into the correct branch 'gh-pages'
- Original issue is linked
- PR description is clear and correct
- The specified change has been correctly implemented

**Comment by jaasonw** [comment]
@liamtirney why was this closed?

**Comment by liamtirney** [comment]
@jaasonw that was my bad, I misread the message, thought the PR had been merged, and deleted the branch from my fork. I restored the branch. Is there anything else I can do on my end to help fix this?

**Comment by Chrisklangley** [comment]
Review ETA: 10/26/23 at 6pm PST.
Availability: 6-10pm Weekdays

**Review by Chrisklangley — APPROVED** [review]
Hey @liamtirney 
Visually everything looks really good!

• You correctly created a new branch for your issue and merged that into gh-pages
• You have a link to the issue
• I was able to clearly understand the changes you made in your PR and saw  the correct changes were implemented from lines 34-40 in  _projects/expunge-assist.md

great work!

**Pull request merged**
