### PR TITLE
Update TDM calc project card

### LINKED ISSUE #989: Update the TDM Calc project card
### Overview
We need to update the TDM calc project so that it properly represents the current state of leadership and open roles, etc so that new people coming to the site can join the project or get current status.

### Action Items
- [x] Development
   - [x] See issue https://github.com/hackforla/product-management/issues/37 for update details

### Resources/Instructions
_projects/tdm-calculator.md

### PR DESCRIPTION
**Pull request by akibrhast**
#Fixes #989

##Changes that address the following change
1.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-761925373) 
2.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-772230227)

- [x] Update Title
- [x] Update Blurb
- [x] Update Partner
- [x] Update Technologies
- [x] Update Leadership

### CODE REVIEW

**Comment by akibrhast** [comment]
image

image

**Comment by akibrhast** [comment]
Typo in vivek's role changed from "Product manager" to "Product Manager"

**Review by danyc23 — CHANGES_REQUESTED** [review]
Change Open Roles one entry for designers and researchers.

**Comment by akibrhast** [comment]
Open roles changed to one entry

**Comment by danyc23** [comment]
Changes made as requested.

**Pull request merged**
