### PR TITLE
Added workflow_dispatch: (with colon) for a manual workflow trigger.

### LINKED ISSUE #4392: Add manual trigger to the "Update VRMS data" workflow
### Overview
The `Update VRMS data` workflow is currently being triggered by a cron job that runs each day at 10:00AM UTC. For this issue, we will add an additional trigger so that we can update the meeting data for the hfla website on demand. 

### Action Items
- [x] Add the `workflow_dispatch` trigger to the `Update VRMS data` workflow

### Resources/Instructions
- [vrms-data.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/vrms-data.yml)
- [HFLA GHA Wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [GHA Docs on workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [GHA Docs on using multiple triggers](https://docs.github.com/en/github-ae@latest/actions/using-workflows/triggering-a-workflow#using-multiple-events)

### PR DESCRIPTION
**Pull request by LOSjr4**
Fixes #4392

### What changes did you make and why did you make them ?

  - In website/.github/workflows/vrms-data.yml under "Update VRMS data" I added "workflow_dispatch" as a manual workflow trigger as an option beside the already included automatic scheduled trigger.
  - In order to list multiple triggers, I included a colon after "workflow_dispatch:" "to configure each event separately, including events without configuration". -(https://docs.github.com/en/github-ae@latest/actions/using-workflows/triggering-a-workflow#using-multiple-events)
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Backend only, no visual changes on website. There may be changes as a github action. I followed Matt Pereira's instructions on the comment section of the original issue to try to test changes, but I'm uncertain and as Matt said, "The action is going to fail on your fork because one of the steps uses a token".

### CODE REVIEW

**Comment by janice87** [comment]
Review ETA: 9 PM 4/15/22
Availability: 5-9 PM Fri - Sat

**Review by blulady — APPROVED** [review]
This PR comes from the correct branch and goes to the correct branch. Properly addresses the correctly linked issue by adding a manual trigger in addition to the cron job that was already running.
I was able to test if this worked by pulling the branch into my local, pushing it into my own personal GitHub repository, switching the default branch to LOSjr4's branch, clicking on actions in the second navbar from the top, clicking on Update VRMS Data on the left side navbar, and seeing that there was a Run Workflow button to the right under workflow runs. I didn't make the changes necessary to the file to run it in my local repo but the button was there.
Good Job!!

**Comment by blulady** [comment]
Also, thank you for all the reviews you've been leaving on other folk's PRs. As soon as @janice87 gets a chance to review this, I hope it gets merged.

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. In the vrms-data.yml file I see the workflow dispatch was added. I went into my own GitHub repo, went to your branch and under Actions I see the workflow "Update VRMS data". When I press on the workflow, it says it is disabled by default in forks, but like Matt mentioned this is expected due to the token. From what I can see, it looks like the issue was addressed. Great job on this issue!

**Pull request merged**
