### PR TITLE
Update Project Profile: Guides Team Add Jesus Diaz

### LINKED ISSUE #7584: Update Project Profile: Guides Team Add Jesus Diaz
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Jesus Diaz
    github-handle: JesseTheCleric
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U0725MRMMA9
      github: https://github.com/JesseTheCleric
    picture: https://avatars.githubusercontent.com/JesseTheCleric
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team
[^3]: initiating ER:  #7259

### PR DESCRIPTION
**Pull request by mamypoco**
Fixes #7584 

### What changes did you make?
  
 -  File updated: _projects/guides-team.md
 -  Where:  current project team on https://www.hackforla.org/projects/guides-team
  -  Added the following:
  ```
- name: Jesus Diaz
    github-handle: JesseTheCleric
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U0725MRMMA9
      github: https://github.com/JesseTheCleric
    picture: https://avatars.githubusercontent.com/JesseTheCleric
```
   

### Why did you make the changes (we will use this info to test)?
  
  -  The ticket #7584 requested to add new member.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>

after

</details>

### CODE REVIEW

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@mamypoco Hey, thank you for taking on this issue. 

### Things that went well : 
- The branch name is correct 
- The changes are correct and visible with the before and after screenshots 

### Things that need to change : 

- [x] Updated the pr title to align with the changes addressed similar to the original issue  and remove the issue number.
- [x] Checked off the relevant completed tasks from the original issue.
- [x] Responded to the HackForLABot in the original issue. 
- [x] The description should be more informative and the `changes made` section should be more on where the changes you made and which files you modified. 

Thank you ! If you have any questions feel free to reach out.

**Comment by mamypoco** [comment]
Thank you @codyyjxn, I checked the boxes for your review. This is my very first PR and you covered thoroughly!

**Comment by DrAcula27** [comment]
ETA: 1 November 2024
Availability: weekdays after 2pm

**Review by DrAcula27 — APPROVED** [review]
@mamypoco Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7584 
- The correct file `-projects/guides-team.md` was edited
- No extra edits were made
- Appearance of the website looks good (Chrome and Firefox)
- Great job fixing your PR and re-requesting changes!
Approved! 👍

**Comment by siyunfeng** [comment]
Review ETA: 11/1/2024 Friday
Availability: 7-10 PM Weekdays (EDT)

**Review by siyunfeng — APPROVED** [review]
Nice job working on your good first issue, @mamypoco !

- Availability and ETA are provided in the original issue
- The linked issue is included in your PR
- The change is accurate
- Before-and-after screenshots are helpful to show the change you made

Improvement: 
- Provide specific detail to `Why did you make the changes (we will use this info to test)?`, such as `to ensure the project leadership info is up to date / accurate`

Thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
@mamypoco  Great Job ! Keep it up !

**Pull request merged**
