### PR TITLE
Updating github handle for Naomi Chao

### LINKED ISSUE #6763: Add github-handle for Naomi Chao in civic-tech-structure.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-structure.md` in the IDE
- [x] Replace:
```
- name: Naomi Chao
```
with
```
- name: Naomi Chao
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-structure

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by nssensalo**
Fixes #6763

### What changes did you make?
  -Replaced   "- name: Naomi Chao" with "- name: Naomi Chao  github-handle: "
 
  
  

### Why did you make the changes (we will use this info to test)?
  - The plan is for a single github-handle variable to replace the github and picture variables.
  
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

The Visual was unchanged. I deleted the site and jekyll files and restarted docker as suggested but I still didn't see my changes.
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by moazDev1** [comment]
Availability: Sat - Mon (6PM - 10PM)
ETA: EOD 4/27

**Review by moazDev1 — APPROVED** [review]
Great job @nssensalo  on:

1. Using the correct branch for your pull request.
2. Accurately linking the issue.
3. Making code changes as requested in the issue
4. Ensuring no visual changes across multiple browsers (Safari, Firefox, Chrome) in both desktop and mobile views.
5. Applicable and clean code changes.

Keep going!!

**Comment by t-will-gillis** [comment]
Hey @jenjenkayi, @patelbansi3009, @taylorbeee, @nssensalo, @ShamaaTabassum as a reminder, while you are waiting for your PRs to be reviewed, please consider reviewing each other’s `good first issue` PRs and any other PRs you feel comfortable with. Instructions are here for [How to Review Pull Requests]( https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) . You should aim to review two PRs for every PR you submit, and each PR ideally should have two or more reviewers. Thanks!
#6746, #6767, #6768, #6770, #6772

**Comment by patelbansi3009** [comment]
Availability: Mon-Thu (11PM - 6PM) EST
ETA: EOD 04/29

**Comment by patelbansi3009** [comment]
Excellent Job @nssensalo!

- Correct Branch was used for the issue.
- Accurately linked the issue.
- Code changes are made as requested in the issue.
- There are no visual changes on the website, checked on all multiple viewports (such as mobile or tablet), through the browser's developer mode
- Code changes look clean.

Thank You!

**Review by patelbansi3009 — APPROVED** [review]
Excellent work **@nssensalo!** Keep up the good work.

**Comment by Thinking-Panda** [comment]
@nssensalo Thank you for working on this issue!

**Pull request merged**
