### PR TITLE
updated overview link opens Access The Data-2234

### LINKED ISSUE #2234: Update how 'Overview' link opens for Access The Data
### Overview
As a user, clicking on the 'Overview' link for the Access The Data project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Access The Data's pdf file currently opens](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Access The Data's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/access-the-data) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
[Project Page](https://www.hackforla.org/projects/access-the-data)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

### PR DESCRIPTION
**Pull request by anthonysim**
Fixes #2234 

### What changes did you make and why did you make them ?

- Download a copy of Access The Data's overview pdf and put it in /assets/pdfs
- Change the 'Overview' link for the markdown file to point to the pdf file living under /assets/pdfs
- Ensure that the links in both the project page and the project's dedicated page open the pdf file properly after the change

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>

</details>

### CODE REVIEW

**Comment by anthonysim** [comment]
I am not sure why one of the checks are failing?

`Set PR Labels / generate-labels-artifact (pull_request) `

I will bring this up at Tues meeting and see if I can fix it. 

Edit: NVM, I figured it out, I forgot to update the Fixes: #2234 portion of the PR message above.

**Comment by JessicaLucindaCheng** [comment]
- Availability: Wed, Dec 8, 2021 7am-5pm PST
- Review ETA: Wed, Dec 8, 2021

**Review by JessicaLucindaCheng — DISMISSED** [review]
@anthonysim Under the "Screenshots of Proposed Changes Of The Website" for the pull request comment, if there are no images, please add an explanation for why there are no images. See the example in the bottom of the section [iv. Complete pull request (4): Include images (if available)](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available). Thanks.

Otherwise, good job! The Access the Data PDF was added to the correct folder (assets/pdf) and the url was changed in the access-the-data.md file to open the PDF file in the browser.

**Comment by anthonysim** [comment]
> @anthonysim Under the "Screenshots of Proposed Changes Of The Website" for the pull request comment, if there are no images, please add an explanation for why there are no images. See the example in the bottom of the section [iv. Complete pull request (4): Include images (if available)](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available). Thanks.
> 
> Otherwise, good job! The Access the Data PDF was added to the correct folder (assets/pdf) and the url was changed in the access-the-data.md file to open the PDF file in the browser.

@JessicaLucindaCheng, oops, I just added the missing screenshots!

**Review by JessicaLucindaCheng — APPROVED** [review]
@anthonysim Thanks for adding the screenshots to the pull request comment! Everything looks good now!

**Review by Johnnie007 — APPROVED** [review]
This looks good. Great job Anthony!

**Review by macho-catt — APPROVED** [review]

**Pull request merged**
