### PR TITLE
Remove mention CfA in about.html

### LINKED ISSUE #5408: remove mention of CfA - about.html
### Overview
We need to remove mention of CfA from the Hack for LA homepage, under the heading "Want to know more about Hack for LA?"

### Action Items
- [x] In your local IDE, navigate to `_includes/about.html`
 replace this text:
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA region. Hack for LA is a project of <a href="https://www.codeforamerica.org" rel="noopener" target="_blank">Code for America</a> and is it's 
      official Los Angeles chapter. 
    </p>
```
with
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA region. Hack for LA is a project of <a href="https://www.civictechstructure.org/" rel="noopener" target="_blank">Civic Tech Structure, Inc.</a>
    </p>
```
- [x] Using Docker, view the webpage and confirm that the text under the heading "Want to know more about Hack for LA?" has been updated, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about.html
2. Webpage(s): https://www.hackforla.org/#press

### PR DESCRIPTION
**Pull request by YolandaHaynes**
Fixes #5408 

### What changes did you make?
  - removed the mention of Code of America in the about.html 
  - updated it to mention the Civic Tech Structure Inc.

### Why did you make the changes (we will use this info to test)?
  - to update information about Hack for LA's invovlment from Code for America to Civic Tech Structure Inc. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
Screen Shot 2023-09-17 at 6 25 58 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
Screen Shot 2023-09-17 at 6 26 47 PM

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: 9/18 EOD
Availability: 2-5pm PDT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The requested changes were made and everything looks good in docker. PR also includes description of the changes made and relevant screenshots. Great work!

**Comment by ortegaa32** [comment]
Review ETA: 3:00 PM 19th September 2023
Availability: 1:00 - 3:00 PM everyday

**Comment by ortegaa32** [comment]
- Branches set up correctly and PR linked to correct issue
- Changes correctly reflected in screenshots and don't break the website
- Changes made to the correct file and look clean

Excellent work @YolandaHaynes!

**Review by ortegaa32 — APPROVED** [review]

**Pull request merged**
