### PR TITLE
Updated GHA to include transferred issue types

### LINKED ISSUE #2215: GitHub Actions: Update trigger on add missing labels GHA
### Overview
As a developer, we need to cover edge cases on our code. For this issue, we will update the trigger for our Add missing labels to new issues job under the "[Issue Trigger](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)" GHA.

### Action Items

- [x] Add "transferred" to the GHA trigger noted above (line 4).
```
  issues:
    types: [opened, transferred]
```
- [x] Update the if conditional for the job so it also triggers on issue transfer (line 10).
```
if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'transferred')}}
```
- [x] If possible, test in your local environment that the action works as intended.

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[Issue Trigger](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)

### PR DESCRIPTION
**Pull request by aricforrest**
Fixes #2215

### What changes did you make and why did you make them ?

  - Updated GHA Issue Trigger to include triggering on transferred issues
  - Updated Add-Missing-Labels-To-Issues (job) if conditional to include transferred issues

### CODE REVIEW

**Comment by GRISONRF** [comment]
Availability: 1h
ETA: 09/25/23

**Review by GRISONRF — APPROVED** [review]
Everything looks good, good job!

**Comment by d-perez-8** [comment]
Review ETA: 6:30 PM 9/26/22
Availability: Tuesday-Thursday 9-11 am

**Review by d-perez-8 — APPROVED** [review]
This looks good, @aricforrest! Thank you for taking this issue. 

I saw that Ava wanted line 4 as `types: [opened, transferred]` on the issue, but since we use the "assigned" type later on, I think how you have it is perfect.

**Pull request merged**
