### PR TITLE
Change sdg image's alt text for access the data

### LINKED ISSUE #3093: Change alt text for sdg image in access the data md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the access the data project's sustainability development goal image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/access-the-data.md`, change [line 111](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/access-the-data.md?plain=1#L111) for the alt text:

from
```
sdg-image-alt: peace justice bottom sustainable dev goal
```
to
```
sdg-image-alt: '16: peace, justice and strong institutions'
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/access-the-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/access-the-data.md?plain=1#L111

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #3093 

### What changes did you make and why did you make them ?

  - Updated the alt text of the sdg image for `_projects/access-the-data.md`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Only changed the alt text of an image, which has no visual effect on the website.

### CODE REVIEW

**Comment by blulady** [comment]
ETA:  6/23
Availability: 1 hours

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: 6/23

**Review by blulady — APPROVED** [review]
The branches look good, going into hackforla:gh-pages from your branch. There is a linked issue and it is the correct linked issue. There are no visual changes so there are no pictures. The code itself has been changed from sdg-image-alt: peace justice bottom sustainable dev goal to sdg-image-alt: '16: peace, justice and strong institutions' and looks good when I throw the repo up locally.
Good Job!!

**Review by Sparky-code — APPROVED** [review]
@BeckettOBrien I see that you've accurately updated the alt text for the SDG image on line 110. 
Branches look good, formatting for your PR is good. Great job moving through your prework/first issues!

**Pull request merged**
