### PR TITLE
Added Rachel Ichniowski Profile to Expunge Assist Leadership

### LINKED ISSUE #7702: Update Project Profile: Expunge Assist Add Rachel Ichniowski
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Rachel Ichniowski
    github-handle: raeraeicky
    role: Product Manager, UX Research
    links:
      slack: https://hackforla.slack.com/team/U07LGA7RZ0W
      github: https://github.com/raeraeicky
    picture: https://avatars.githubusercontent.com/raeraeicky
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/expunge-assist
[^3]: initiating ER: https://github.com/hackforla/website/issues/7580#issue-2579554525

### PR DESCRIPTION
**Pull request by nmotamedi**
Fixes #7702

### What changes did you make?
  
  - Added Name / Role / Links / Picture for Rachel Ichniowski to the expunge-assist.md

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
  <summary>Visuals before changes are applied</summary>

 
Screen Shot 2024-11-19 at 10 03 29 PM

</details>

<details>
  <summary>Visuals after changes are applied</summary>

Screen Shot 2024-11-19 at 10 02 46 PM

</details>

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### CODE REVIEW

**Comment by mchait18** [comment]
Review ETA: 12:30 PM 11/20/24
Availability: 9-3 PM  EST M-Th

**Comment by codyjohnsontx** [comment]
Review ETA: 12:00 PM 11/20/24
Availability: On Call Today: 10am-6 PM CST, 9pm-12midnight CST 11/20

**Review by mchait18 — DISMISSED** [review]

**Comment by mchait18** [comment]
Hi @nmotamedi, thanks for taking this issue!

- the PR contains the correct branch
- issue is correctly linked
- changes are verified across browsers (firefox, edge, chrome)
- code changes are accurate and concise
- no other notable issues
Great job!

**Comment by codyjohnsontx** [comment]
Thank you for working on this issue, @nmotamedi  !

You're doing these right:
The branch you made the change on is correct
The linked issue (original issue) number is included
The content required to add is accurate
The before / after screenshot is helpful to display the change


Changes you need to make:
-Address the questions from HackforLABot in the original issue ( comment your Availability and ETA)
-The CodeQL Alerts are checked (check box above)
-Fix the unnecessary changes (double quotation marks(") instead of the original single quotation marks('), and the spacing on some of the lines) and submit your PR again (It could be caused by the formatting tool in your IDE, such as prettier)
-You can re-request me to review your PR once you make the changes. Feel free to reach out if you have any questions.

**Comment by codyjohnsontx** [comment]
Review ETA: 3:00 PM 11/20/24
Availability: On Call Today: 10am-6 PM CST, 9pm-12midnight CST 11/20

**Review by codyjohnsontx — DISMISSED** [review]
Nice Work @nmotamedi!
Excellent job fixing the quotation marks and spacing issues in the file
Proper into and from branches
Clear and simple what and why
Correctly added the team members info

Thanks for the PR!

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@nmotamedi thank you for taking on this issue.
### Some suggestions
- You need to add this question `Why did you make the changes (we will use this info to test)?`
- I believe you have this section twice please remove one `Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)`

**Comment by nmotamedi** [comment]
Thank you, @codyyjxn. I have made the updates requested.

**Comment by belunatic** [comment]
Review ETA: 10 AM 11/22/24
Availability: 4-5 PM Monday

**Review by belunatic — DISMISSED** [review]
@nmotamedi  great job and thank you for fixing the previous issues

- The issue name looks great
- the before and after images a re spot on
- issue number is great

**Suggestions**
- I like that you dded the file name you changed, but it will be great if you also added the folder name i.e: ``_project/expung_assist``, to locate it faster

Besides that keep up the good work!

**Comment by rachelcorawood** [comment]
Review ETA: 7PM 11/21/24
Availability: M-F noon-3pm

**Review by rachelcorawood — DISMISSED** [review]
You linked the issue, understand the linked issues, changes can be viewed, and your code looks clean and efficient with no bugs. Great job!

**Comment by jphamtv** [comment]
Hi @nmotamedi, there's a conflict in `_projects/expunge-assist.md` from a recent merge that needs resolving. Once you resolve it, we'll get this merged in. Check out [How to Resolve Merge Conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts) for help.

**Review by codyyjxn — APPROVED** [review]
Hey @nmotamedi  great job on fixing these issues. 
Keep it up!

**Comment by dvernon5** [comment]
Review ETA: 7:00 PM 11/26/2024
Availability: 9AM - 6PM Tuesday & Wednesday of this week.

**Review by dvernon5 — APPROVED** [review]
Hello @nmotamedi 

Branch name looks good.
The code changes looks suburb.
This issue is linked correctly.
CodeQL alerts are good.
The content added is correct.
Before and After photo look stunning

Your PR is absolutely perfect. Great job!

**Pull request merged**
