### PR TITLE
Added empty alt attribute to hero image within project layout header

### LINKED ISSUE #4670: Add empty alt text attribute for project hero images
### Overview
As developers we need to markup image attributes according to W3C guidelines in order to ensure accessibility.  Each project page features a hero image which does not add meaning that differs from the adjacent H1 header; therefore the hero images should be marked with an empty alt attribute.  

### Action Items
- [x] Read the file `_layouts/project.html` and locate the `` tag located within `<header class='project-hero'>`
- [x] To the `` tag, add the attribute: `alt=''`

### Resources/Instructions

- https://jekyllrb.com/docs/step-by-step/04-layouts/
- [W3C Alt text Decision Tree](https://www.w3.org/WAI/tutorials/images/decision-tree/)

### PR DESCRIPTION
**Pull request by Dprosser4**
Fixes #4670

### What changes did you make and why did you make them ?

-Added empty alt attribute to an img HTML tag.

-Specific Tag Changed: ``

-File: ` _layouts/project.html`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website. (Confirmed with Docker)

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: 10 AM - 2PM
ETA: 5/31/23

**Review by Thinking-Panda — APPROVED** [review]
@Dprosser4 nice work with the issue. Merge branches look good. Code changes are as mentioned in the issue and thank you for deleting the trailing space on line 176. Website works perfect on my local machine. Thank you!

**Comment by roslynwythe** [comment]
Hi @mademarc please advise re: your availability and ETA for this review.  Thank you.

**Comment by graycodesnu** [comment]
Availability: Afternoon of 6/1 
ETA: EOD 6/1

**Review by graycodesnu — APPROVED** [review]

**Comment by graycodesnu** [comment]
@Dprosser4, great job completing this issue! The changes are committed to and from the correct branches, you correctly added the alt attribute to the img tag, and the changes work on my local machine. Keep up the great work!

**Comment by mademarc** [comment]
Review ETA: 6/2/2023
Availability: 7:15PM

**Review by mademarc — APPROVED** [review]
hey @Dprosser4  well done on the img changes by adding the alt element on it  and @roslynwythe this review has been done as well

**Comment by drakenguyen4000** [comment]
Nicely done!

**Pull request merged**
