### PR TITLE
Refactor GHA 'sort-closed-issues.js'

### LINKED ISSUE #7530: Refactor GHA `sort-closed-issues.js` to use `label-directory.json`
### Overview
We want to refactor the GHA workflows to reference each label by a general ID (i.e. a 'labelKey') rather than the label's name so that other HfLA project groups can use these workflows without needing to match the label names used by the Website team.

### Details
Currently, the GHA workflows files that add, remove, and change labels on issues identify each label by its name (i.e. the 'labelName') directly. Instead of hard-coding each label name, we want these files to identify each label by its 'labelKey' and use the `retrieve-label-directory.js` module to look up the corresponding 'labelName' that is needed in order for the REST API to apply labels to issues.

### Action Items
This issue involves the "**_Move Closed Issues_**" GitHub Action, and you must set up your environment for testing GHAs in order to work on this issue. See notes below in "Resources/ Instructions", and ask questions if you need additional help- GHAs can be tricky, and if you get stuck somewhere, someone who has worked on these before might have information that will save you a lot of time.    
- [x] Before making any of the edits following, first create a test branch in your repo and demonstrate the current, correct behavior of the "Move Closed Issues" GHA. Afterwards, create an additional branch for the edits following- this is the branch that will be attached to the PR.

Refer to [sort-closed-issues.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/move-closed-issues/sort-closed-issues.js).
- [x]  A preliminary search found that this file uses the following labels. As you work through this issue, confirm that this list is correct, and note any additions or subtractions as needed:
  - `Feature: Refactor CSS`
  - `Feature: Refactor HTML`
  - `Feature: Refactor JS / Liquid`
  - `Feature: Refactor GHA`
  -  `role: back end/devOps`
  -  `Feature: Analytics`
  -  `role: front end`
 
- [x] Add to `// Import modules`:  
  ```
  const retrieveLabelDirectory = require('../../utils/retrieve-label-directory');
  ```
- [x] Before the current definition of the `hard labels` around line 13, add comment:
  ```
  // Use labelKeys to retrieve current labelNames from directory
  ```
  then for each label, consult [label-directory.json](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/_data/label-directory.json) and replace labelName with the labelKey:
  ```
  const [
    featureRefactorCss,
    featureRefactorHtml,
    featureRefactorJsLiquid,
    featureRefactorGha,
    roleBackEndDevOps,
    featureAnalytics,
    roleFrontEnd
  ] = [
    “featureRefactorCss”,
    “featureRefactorHtml”, 
    “featureRefactorJsLiquid”,
    “featureRefactorGha”,
    “roleBackEndDevOps”,
    “featureAnalytics”,
    “roleFrontEnd”
  ].map(retrieveLabelDirectory);
  ```
- [x] Search  `sort-closed-issues.js` for instances of the original label name and substitute the <labelKey> defined above.
- [x] Prior to submitting the PR, search `sort-closed-issues.js` for for all code comments that reference a specific label name
  - [x] List these instances out in a comment on this issue, with your suggestion for replacement text that generalizes it.
  - [x] When finished, add the label `ready for product` and change status to "Questions / In Review" 
  - [x] Product will review and provide feedback on replacement text for revision or sign-off on changes.
- [x] Perform a test in your own repo that demonstrates that there is no change to the GHA's functionality after making the edits.
### Resources/Instructions
- Refer to [Hack for LA's GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), especially Tips 6, 7, and 8, if you have not already created you personal environment for testing.
- [How to Test GitHub Actions](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA)
- [Additional Notes for GitHub Actions](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)
- This issue is part of the epic #6454

### PR DESCRIPTION
**Pull request by aadilahmed**
Fixes #7530

### What changes did you make?
  
  - Imported 'retrieveLabelDirectory' function into sort-closed-issues.js 
  - Use 'retrieveLabelDirectory' function to replace each labelName variable with the corresponding labelKey
  - Substitute the labelKey variable with each of the original label names in sort-closed-issues.js

### Why did you make the changes (we will use this info to test)?
  
  - To refactor the GHA workflows to reference each label by a general ID (labelKey) so that other HFLA groups can use these workflows without having to match the label names used by the website team
  
<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
No visual changes to website.

Tested workflows:
move-closed-issues.yaml

Screenshot 2024-11-17 at 19-21-29 issue 31 · aadilahmed_website@1b9ea05

### CODE REVIEW

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: Nov 21 EOD

**Comment by t-will-gillis** [comment]
Available: weekdays
ETA: Weds 11/26 eod

**Review by daras-cu — APPROVED** [review]
Hi @aadilahmed, great work on this issue. The changes you made to `sort-closed-issues.js` successfully retrieve the label names from the directory rather than using the hard-coded names, and the functionality is not affected. I tested closing the following issues:
- An issue with a label in `hardLabels` was moved to `Done`
- An issue with a label in `softLabels` was moved to `Done`
- An issue with a label in `overrideSoftLabels` was moved to `QA`
- An issue with none of the listed labels was moved to `QA`

In all cases, the GH Action performed as expected. In addition, your PR explains the changes you made and why, and links to the original issue. Well done!

**Review by codyyjxn — APPROVED** [review]
Hey @aadilahmed great job on this!
- The code is clean and concise. 
- The issue is linked and the sort-closed is refactored very well.

**Review by t-will-gillis — APPROVED** [review]
Hey @aadilahmed Great job! I have tested this and everything appears to be sorting correctly. Looks great

Thanks for taking on this issue!

**Pull request merged**
