### PR TITLE
Removed unused alt hero field

### LINKED ISSUE #3198: Remove unused `alt-hero` field from green-earth-os.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/green-earth-os.md`, remove line 8 for the alt-hero
```
alt-hero: 'Green Background'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/green-earth-os.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/fdecdb49ef86a3cc3bf4617effe055e39efecc13/_projects/green-earth-os.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by abdiaz2018**
Fixes #3198 

### What changes did you make and why did you make them ?

  -Removed unused alt hero field
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
no visual changes

### CODE REVIEW

**Comment by giroz** [comment]
ETA: 9-4-22
Availability: 3 Hours

**Review by giroz — APPROVED** [review]
Good job!  Delete and go.

**Comment by arpitapandya** [comment]
Availability : 6hrs
ETA : EOD 2022-09-05

**Review by arpitapandya — APPROVED** [review]
All the changes are correct! Great job!! @abdiaz2018

**Pull request merged**
