### PR TITLE
Fix font size of getting started page on mobile

### LINKED ISSUE #1335: Adjust styling of Getting Started page
### Overview
We need to adjust the styling of the Getting Started page, especially in mobile, so that it is consistent with other pages on the site and user-friendly

### Action Items
- [ ] Make sure all of these changes below will apply to both versions of the Getting Started page - getting-started.html and getting-started-with-video.html ('with video' version will be brought back as soon as we have self-onboarding added back in)
- [ ] Make ALL of the links on this page open in new tabs
- [ ] Make all of the steps subheadings ("Step 1: Onboard", etc.):
   - [ ]  In desktop: 24px font (instead of 25px) - use rem units
   - [ ] In mobile: 20px font - use rem units
- [ ] mobile: the header paragraph (.header-p) text should be left-aligned
- [ ] In mobile: Make the font of the questions in the accordion ("How do I raise my hand on zoom?" etc.) **18px font** (instead of 20px) - use rem units (but this is ONLY in mobile- in desktop it should stay the same)
   - [ ] This will affect other accordions on the site, which is fine. Double check the [2FA guide](https://www.hackforla.org/guide-pages/2FA) accordion in mobile to make sure it still looks good

### Resources/Instructions
[Getting Started Page
](https://www.hackforla.org/getting-started)
[2FA guide](https://www.hackforla.org/guide-pages/2FA) (to make sure accordion still looks good in mobile when changes apply here)

### PR DESCRIPTION
**Pull request by qaz6209031**
- [x] Make sure all of these changes below will apply to both versions of the Getting Started page - getting-started.html and getting-started-with-video.html ('with video' version will be brought back as soon as we have self-onboarding added back in)
- [x] Make ALL of the links on this page open in new tabs
- [x] Make all of the steps subheadings ("Step 1: Onboard", etc.):

- [x] In desktop: 24px font (instead of 25px) - use rem units

 

- [x] In mobile: 20px font - use rem units

 

- [x] mobile: the header paragraph (.header-p) text should be left-aligned

 

- [x] In mobile: Make the font of the questions in the accordion ("How do I raise my hand on zoom?" etc.) 18px font (instead of 20px) - use rem units (but this is ONLY in mobile- in desktop it should stay the same)

 

- [x] This will affect other accordions on the site, which is fine. Double check the 2FA guide accordion in mobile to make sure it still looks good

Fixes #1335, I didn't make the links on the top of the starting page opened in the new page (Events, Projects, Press, Join Us...etc. But all the other issues are fixed.

### CODE REVIEW

**Comment by erikaBell** [comment]
@qaz6209031 Hi ~ I just left a comment on your last PR, #1470. If you could please checkout my comment and make those adjustments on this PR, that would be great! Feel free to assign me as the reviewer for this.

Also, was there a decision to move forward without opening pages into new tabs, and that is why it wasn't created?

Thanks ~

**Review by daniellex0 — CHANGES_REQUESTED** [review]
The changes look good!

But I think you missed this part:

-  For all of the step subheadings ("Step 1: Onboard", "Step 2", etc.):

   -  In desktop these subheadings should 24px font (instead of 25px) - use rem units. This is to match our design system.

   -  In mobile these subheadings should be 20px font (instead of 25px) - use rem units. This is to match our design system.

Let me know if you have any questions. Thanks!

**Comment by daniellex0** [comment]
> Also, was there a decision to move forward without opening pages into new tabs, and that is why it wasn't created?

@erikaBell I think the links are able to open in new tabs for me?

**Comment by qaz6209031** [comment]
> The changes look good!
> 
> But I think you missed this part:
> 
> * For all of the step subheadings ("Step 1: Onboard", "Step 2", etc.):
>   
>   * In desktop these subheadings should 24px font (instead of 25px) - use rem units. This is to match our design system.
>   * In mobile these subheadings should be 20px font (instead of 25px) - use rem units. This is to match our design system.
> 
> Let me know if you have any questions. Thanks!

Hello @daniellex0, I just checked, but I did made those changes 

web version
Screen Shot 2021-04-27 at 7 53 28 PM

mobile version
Screen Shot 2021-04-27 at 7 52 32 PM

**Comment by daniellex0** [comment]
Ah sorry @qaz6209031 , I wasn't clear- those are actually supposed to stay the same font size in mobile please. 

I had meant these step subheadings:

Screen Shot 2021-04-28 at 12 53 17 AM

Please adjust Step 1-4 in those subheadings to 20px (instead of 25px)- and please revert the header steps back to the sizes they were before.

Thank you!

**Comment by qaz6209031** [comment]
Ohh, I misunderstood the issue. I revert the header steps back and the subheading should be fixed 

web:
Screen Shot 2021-04-28 at 9 35 48 AM

mobile: 
Screen Shot 2021-04-28 at 9 33 03 AM

**Review by erikaBell — APPROVED** [review]
Looks good ~ (-:

**Pull request merged**
