### PR TITLE
Add github-handle variable

### LINKED ISSUE #5504: Add new variable github-handle for member Niven Prasad in 100-automations.md
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Niven Prasad
```
with
```
- name: Niven Prasad
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [x] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by jlevot**
Fixes #5504

### What changes did you make?
Add an empty github handle variable on 100 Automations project for Niven Prasad

### Why did you make the changes (we will use this info to test)?
Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 1/13/2024

**Comment by freaky4wrld** [comment]
@jlevot thanks for taking up the issue, well the changes made by you are good to be merged, but before that I request some minor things
- first please checkoff the box `[ ]` linked in the original issue
- please replace `There is no impacts on the web view, so it's not necessary to provide screenshots before/after` with `No visual changes`
- do remember to put the above line inside the `Screenshot` heading which you might have removed 

Ping me when you are done and I'll approve it

**Comment by jlevot** [comment]
@freaky4wrld Thank you for your review.

I have updated the PR body and checkoff the box linked in the original issue.

**Review by freaky4wrld — APPROVED** [review]
Everything looks to merge, branches are correct, changes made are seen in local environment.... PR approved!!

**Comment by kwangric** [comment]
Availability: Evening 1/15
ETA: EOD 1/15

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The PR is linked to the correct issue and the requested changes to the `100.automations.md` file has been made. Everything still looks good in Docker, and the PR includes why the changes were made. Great work!

**Pull request merged**
