### PR TITLE
updates profile page by removing aletia trepte, case 5806

### LINKED ISSUE #5806: Update Project Profile: Lucky Parking (Remove Aletia Trepte)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Aletia Trepte
    role: Data Scientist/Engineer
    links:
      slack: 'https://hackforla.slack.com/team/U03KAPRML9Y'
      github: 'https://github.com/parcheesime'
    picture: https://avatars.githubusercontent.com/u/38143160
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #5806

### What changes did you make?
  - Removed Aletia Trepte from profile page

### Why did you make the changes (we will use this info to test)?
  - To update Lucky Parking profile page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-09 at 1 44 38 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-09 at 1 45 53 PM

</details>

### CODE REVIEW

**Review by freaky4wrld — CHANGES_REQUESTED** [review]
Hey @sornekian great work the changes specified in the issue are correctly done, just make some changes so that the PR is perfect, 
- In the `reason for changes made` mention `to update the Lucky Parking profile page`, I think this will be apt
- Also if possible can you please add desktop screenshots, they will be little easier for reviewer and your PR can be reviewed
Just change the above mentioned suggestions and I will approve it !!!

**Comment by sornekian** [comment]
> Hey @sornekian great work the changes specified in the issue are correctly done, just make some changes so that the PR is perfect,
> 
> * In the `reason for changes made` mention `to update the Lucky Parking profile page`, I think this will be apt
> * Also if possible can you please add desktop screenshots, they will be little easier for reviewer and your PR can be reviewed
>   Just change the above mentioned suggestions and I will approve it !!!

Hey, I appreciate the comments. For the desktop, I'm not sure how to view the local host on docker aside from opening it within the browser. Any suggestions?

**Review by freaky4wrld — COMMENTED** [review]
Hey @sornekian I was just asking you to provide, full window screenshots, well doesn't matter that much. I'll approve this PR looks fine to me
- Merging branch is correct
- Deletion of file content is done properly
And that's good to go!!  Make sure to check off the underlying dependency on #5806

**Review by freaky4wrld — APPROVED** [review]

**Review by t-will-gillis — APPROVED** [review]
Hey @sornekian great work! 
- Your branches from/to are good
- You're linked to original issue
- You are providing a concise description of what you did and why
- You are providing relevant before and after screenshots
- Your code edits change only what needs to be changed

Thank you for working with @freaky4wrld to address the requested corrections.

**Pull request merged**
