### PR TITLE
 update refactored tools data for public tree #4812

### LINKED ISSUE #4812: Refactor Tools data for public-tree-map.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [public-tree-map.md](https://github.com/hackforla/website/blob/gh-pages/_projects/public-tree-map.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Zeplin
```
to:
```
tools:
  - Zeplin
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by Ris345**
Fixes #4812 

### What changes did you make?
 - Refactored tools data from string to a list 
  - From  `tools: Zeplin` to 
  `tools:
      -Zeplin`

### Why did you make the changes (we will use this info to test)?
  - To revise the filter menu on the [Projects Check page](https://www.hackforla.org/projects-check/) to include a dropdown for "Tools",  to facilitate moving project values between "Tools" and "Technologies. 
  
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No visual changes were required for this issue

### CODE REVIEW

**Comment by DorianDeptuch** [comment]
Availability: 7/31 evening
ETA: 7/31 evening

**Review by DorianDeptuch — APPROVED** [review]
Hi Rishav,

You documented the changes well, the tools in the markdown file are now in a list, and there are no visual updates and the site is running in my local environment. Great work!

**Comment by Ris345** [comment]
Thanks @DorianDeptuch  for the review!

**Comment by kwangric** [comment]
ETA: EOD 8/4
Availability: Most days after 3pm PT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The requested changes were made to the code and everything still looks good in Docker. The pull request also contains a description of what changes were made and why. 

For future pull request where there are no visual changes, you can remove the details tags completely and include a short message saying that there were no visual changes.

Overall, great work completing the issue!

**Comment by Ris345** [comment]
Thank you @kwangric appreciate the merge and review! I will make sure to remove those image tags completely now and in the future.

**Pull request merged**
