### PR TITLE
updated alt text for Mid-city neighborhood council image on line 55

### LINKED ISSUE #3106: Change alt text for Mid-city neighborhood council image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Mid-city neighborhood council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 55](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L55) for the alt text:

from
```
<img class="org-img" src="/assets/images/citizen-engagement/mid_city_neighborhood_council.svg" alt="MINC mid-city neighborhood council logo">
```
to
```
<img class="org-img" src="/assets/images/citizen-engagement/mid_city_neighborhood_council.svg" alt="Mid-City Neighborhood Council">
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L55

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by AzaniaBG**
Fixes #3106

### What changes did you make and why did you make them ?

  - changed line 55 alt text to "Mid-City Neighborhood Council"
  - changes made in citizen engagement html file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to website; only changed alt text for image.

### CODE REVIEW

**Comment by tunglinn** [comment]
ETA: today
Availability: 1hr

**Review by tunglinn — APPROVED** [review]
Merge branches are good. Only changes mentioned in the issue are applied. Website does not break. Good work!

**Comment by mariareeves** [comment]
ETA: 9/23/22
Availability: 4 hrs

**Comment by arpitapandya** [comment]
ETA: EOD 2022-09-21
Availability: 30 minutes

**Review by arpitapandya — APPROVED** [review]
All the changes are correct & doesn't break anything!! Great job! @AzaniaBG 

- Just one note for future PRs where you may be changing multiple lines of code, I would keep the title short for e.g `updated citizen engagement image` or `modified neighborhood council image`. Try not to include lines in the title.

You can always be more specific under ### What changes did you make and why did you make them?

**Pull request merged**
