### PR TITLE
Refactor HTML to resolve linter error

### LINKED ISSUE #5285: Refactor HTML to resolve linter error: _includes/about-page/about-card-donations.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-donations.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about'>
```
to
```
<div class="card-primary page-card-lg page-card--about">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-donations.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by ortegaa32**
Fixes #5285 

### What changes did you make?
  - Switched single quotes to double quotes in HTML div tag

### Why did you make the changes (we will use this info to test)?
  - To resolve the linter error "Value of attribute [class] must be in double quotes"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 No visual changes.

### CODE REVIEW

**Comment by tesiahwang** [comment]
Review ETA: 8/30/2023
Availability: flexible

**Review by tesiahwang — APPROVED** [review]
Great job, @ortegaa32 - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable & clean!

**Comment by celinalou92** [comment]
Review ETA: 8/31/2023
Availability: flexible

**Review by celinalou92 — APPROVED** [review]

**Comment by mademarc** [comment]
Review ETA: 8/31/2023
Availability: 7:08PM

**Review by mademarc — APPROVED** [review]
Hey @ortegaa32  I like how readable your code is on line 1 as the small change was made  also Great job!

**Review by t-will-gillis — APPROVED** [review]
@ortegaa32 - Great job on your first issue! Your branches look good, you are linked to the original issue, you have included descriptions of what you did and why, and your code is clean. Thanks for your work!

**Pull request merged**
