### PR TITLE
Changed alt text for security icon

### LINKED ISSUE #1585: Change Alt Text for Security Icon on Credit page
### Overview
Alt text for Security Icon on Credit Page needs update.

### Action Items
- [x] Change the alt attribute value to 'Security Icon'

```diff
- alt: 'Image of Security'
+ alt: 'Security Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/secutiry.yml#L10

### PR DESCRIPTION
**Pull request by R-Tomas-Gonzalez**
Fixes #1585
### What changes did you make and why did you make them ?
  - Alt text changed in file '_data/internal/credits/security.yml' from 'Image of Security' to 'Security Icon'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screen Shot 2021-09-12 at 10 41 43 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
Screen Shot 2021-09-12 at 10 48 25 PM

</details>

### CODE REVIEW

**Review by macho-catt — APPROVED** [review]
LGTM. Good job on your first issue!

**Comment by R-Tomas-Gonzalez** [comment]
> LGTM. Good job on your first issue!

Thanks Matthew! :)

**Review by Abel-Zambrano — APPROVED** [review]
@R-Tomas-Gonzalez Good Job! Also, kudos for checking off the checkbox in the issue.

**Comment by R-Tomas-Gonzalez** [comment]
> @R-Tomas-Gonzalez Good Job! Also, kudos for checking off the checkbox in the issue.

Thanks Abel! Looking forward to continue contributing :) 

Cheers!

**Pull request merged**
