### PR TITLE
update website project info: added Bitian to leadership 

### LINKED ISSUE #4235: Update Project Profile: Hackforla.org Website- Bitian
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Bitian Zhang
  GitHub Handle: bzzz-coding
  Role: Merge Team
  Slack Member ID: U04H6PYK14N
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by nnr-nnr**
Fixes #4235

### What changes did you make and why did you make them ?

  - Added Bitian's information to the website project `leadership` data, including Bitian's GitHub + Slack links and team assignment (merge team)
  - These changes help keep the website up to date on team information

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Bitian is not in the Current Project Team.

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

Bitian _is_ in the Current Project Team.

image

</details>

### CODE REVIEW

**Comment by arcan9** [comment]
Review ETA: Before 5:30PM, 03/23/23
Availability: 3-8PM, M-F

**Review by arcan9 — APPROVED** [review]
Great job, @nnr-nnr! Correct branch, issue, and screenshots provided. Reason for the change is clear. The change is also reflected correctly in the browser (web, mobile, tablet). 👍

**Comment by mjshelton12** [comment]
Review ETA: Before 6pm 3/23
Availability: Rest of the day

**Review by mjshelton12 — APPROVED** [review]
Excellent work, nrr-nrr! Your basics are perfect: Branches are correct, issue is linked, I can clearly read what you did and why, and the visuals are clear.

Your code is clean and effective. I can view the changes in docker including views for PC, tablets, and phones. The links for slack and github both work as expected. Excellent work, keep it up!

**Pull request merged**
