### PR TITLE
Rename "Update GitHub Data" to "Schedule Daily 1100"

### LINKED ISSUE #2222: GitHub Actions: Rename "Update GitHub Data" to "Schedule Daily 1100"
### Overview
As a member of the backend team, github actions are much more maintainable and easier to understand if they are structured based on triggers and functionality. For this issue, we want to update [github-data.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/github-data.yml) and rename the action to 'Schedule Daily 1100' so all scheduled actions that occur on 11am daily can live in this file.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Rename the file from 'github-data.yml' to 'schedule-daily-1100.yml'
- [x] Rename the name of the action from 'Update GitHub Data' to 'Schedule Daily 1100'
    - [x] The name of the job should still stay the same (line 9)
- [x] Update the location of the [accompanying js file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/get-project-data.js)
    - [x] If not created yet, create a new directory under /[github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)/ called trigger-schedule
    - [x] Create a subdirectory under /github-actions/trigger-schedule called github-data
    - [x] Move the js file [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/get-project-data.js) under /github-actions/trigger-schedule/github-data
    - [x] Update the github action's js requirement to reflect the change in directory
- [ ] If possible, do a test on your local environment and make sure it still works

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Accompanying JS](https://github.com/hackforla/website/tree/gh-pages/github-actions)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

### PR DESCRIPTION
**Pull request by lilyarj**
Fixes #2222

### What changes did you make and why did you make them ?

  - I renamed "update GitHub Data" to "Schedule Daily 1100"
  - updated the location of the accompaning js file
  - I did this to make git hub actions easier to understand and more maintainable
  -
No visual changes

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 2 Hours
ETA: EOD 7/13/22

**Review by BeckettOBrien — DISMISSED** [review]
I can't test the action but all the changes look correct and the site still works, so good job!

**Comment by clayton1111** [comment]
availabilty: 2 hours
eta: end of day

**Review by clayton1111 — DISMISSED** [review]
All of the changes are correct!

**Comment by blulady** [comment]
> I can't test the action but all the changes look correct and the site still works, so good job!

So github actions send an alert to the owner of the repo when they run...

**Comment by blulady** [comment]
Hey Lily,
I might be doing something wrong on my end but I can't get your branch to work in my repo... I'd love to do a screen share if you think the error is on my end.
This is the error I am getting under Generate github-data.json

```
Run node github-actions/trigger-schedule/github-data/get-project-data.js
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/website/website/github-actions/trigger-schedule/github-data/get-project-data.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:[7](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:8)7[8](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:9):27)
    at Module.require (node:internal/modules/cjs/loader:1005:1[9](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:10))
    at require (node:internal/modules/cjs/helpers:[10](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:11)2:18)
    at Object.<anonymous> (/home/runner/work/website/website/github-actions/trigger-schedule/github-data/get-project-data.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:[11](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:12)05:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:[12](https://github.com/blulady/website/runs/7381951446?check_suite_focus=true#step:5:13))
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/website/website/github-actions/trigger-schedule/github-data/get-project-data.js'
  ]
}
Error: Process completed with exit code 1.
```

**Comment by lilyarj** [comment]
Hi, @blulady thats so weird. Sure!

**Comment by BeckettOBrien** [comment]
@lilyarj I think you have to change the working directory on line 22 to match the new location of the JavaScript file so that it installs the dependencies in the correct place. (You might also have to move or copy the `package.json` from the old working directory to the new one)

**Comment by lilyarj** [comment]
> @lilyarj I think you have to change the working directory on line 22 to match the new location of the JavaScript file so that it installs the dependencies in the correct place. (You might also have to move or copy the `package.json` from the old working directory to the new one)

Okay I think I changed it

**Review by BeckettOBrien — CHANGES_REQUESTED** [review]
This should work but you still have to move the `package.json` from the old directory to the new one. You might also be able to delete the old `github-actions/github-data` because the only thing left is an unnecessary `package-lock.json`, but I would double-check with someone else first because the issue didn't specifically say it's okay

**Comment by lilyarj** [comment]
> This should work but you still have to move the `package.json` from the old directory to the new one. You might also be able to delete the old `github-actions/github-data` because the only thing left is an unnecessary `package-lock.json`, but I would double-check with someone else first because the issue didn't specifically say it's okay

Oh okay, thank you so much! How would I move the package.json?

**Comment by BeckettOBrien** [comment]
You can just drag it to the new directory in vscode or use `mv github-actions/github-data/package.json github-actions/trigger-schedule/github-data/`.

**Comment by lilyarj** [comment]
> You can just drag it to the new directory in vscode or use `mv github-actions/github-data/package.json github-actions/trigger-schedule/github-data/`.

Thank you so much! I think I did it, but I'm not completely sure. The first time I tried it, it gave me this error saying I needed to pull before I can push, so I tried that but then it gave me another error, so I restarted and tried again and I think it worked, hopefully lol

**Comment by blulady** [comment]
I am getting a new error so that's progress. @lilyarj  How are you testing to see if the GitHub action is working?

Under `GitHub Action for install npm dependencies`

```
Run bahmutov/npm-install@v1
running npm-install GitHub Action
Error: ENOENT: no such file or directory, open 'github-actions/trigger-schedule/github-data/package-lock.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:[4](https://github.com/blulady/website/runs/7400678871?check_suite_focus=true#step:4:5)[5](https://github.com/blulady/website/runs/7400678871?check_suite_focus=true#step:4:6)3:35)
    at Function.module.exports.hasha.fromFileSync (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:7555:54)
    at Object.installInOneFolder (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:3040:2[6](https://github.com/blulady/website/runs/7400678871?check_suite_focus=true#step:4:7))
    at npmInstallAction (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:3100:21)
    at Object.<anonymous> (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:3130:3)
    at __webpack_require__ (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:43:19)
    at /home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:49:1[8](https://github.com/blulady/website/runs/7400678871?check_suite_focus=true#step:4:9)
    at Object.<anonymous> (/home/runner/work/_actions/bahmutov/npm-install/v1/dist/index.js:52:[10](https://github.com/blulady/website/runs/7400678871?check_suite_focus=true#step:4:11)) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'github-actions/trigger-schedule/github-data/package-lock.json'
}
Error: ENOENT: no such file or directory, open 'github-actions/trigger-schedule/github-data/package-lock.json'
```

**Comment by BeckettOBrien** [comment]
Sorry, I didn't realize that the workflow uses a custom action to install dependencies that needs the `package-lock.json` file. @lilyarj You should be able to fix the error by also moving the `package-lock.json` file the same way you did the `package.json` file. After that, you can probably also delete the old `github-actions/github-data/` directory because it should be empty.

**Comment by blulady** [comment]
> Sorry, I didn't realize that the workflow uses a custom action to install dependencies that needs the `package-lock.json` file. @lilyarj You should be able to fix the error by also moving the `package-lock.json` file the same way you did the `package.json` file. After that, you can probably also delete the old `github-actions/github-data/` directory because it should be empty.

Thanks for the help!!

**Comment by lilyarj** [comment]
> Sorry, I didn't realize that the workflow uses a custom action to install dependencies that needs the `package-lock.json` file. @lilyarj You should be able to fix the error by also moving the `package-lock.json` file the same way you did the `package.json` file. After that, you can probably also delete the old `github-actions/github-data/` directory because it should be empty.

Okay I think I did it. I did not delete the github-actions/github-data/ directory because there was still the contributors-data.js. Thank you so much for you help!

**Review by BeckettOBrien — APPROVED** [review]
The changes look good and I just ran the action on my fork and it worked perfectly! Good job!

**Comment by blulady** [comment]
> The changes look good and I just ran the action on my fork and it worked perfectly! Good job!

Same in my repo too. Good Job!!!

**Comment by blulady** [comment]
@clayton1111  After you check this, we'll merge it. Let me know if you want help running it in your own repo.

**Comment by blulady** [comment]
Hey so it is running in my repo as well, but it says that there is a conflict in the branch. We are so close!!!

**Comment by clayton1111** [comment]
HI everyone! Sorry for getting to this so late. Everythign is running in my repo as well but I see that there is a conflict with the package-lock.json file. Does anyone see what the conflict is? I haven't been able to figure it out

**Pull request merged**
