### PR TITLE
Create Design System page

### LINKED ISSUE #1850: Standardizing the HFLA Design System
### Dependency
- [ ] Post Homepage launch when we recruit a new design team.

### Overview
With the new design system coming up, we need a way to relay to the team on what the intentions are behind the new designs. 

### Detail
While we sometimes have to decide things on an "as-needed" emergency basis, the entire team benefits when we have firmer guidelines on utilizing the new designs because it reduces the amount of back and forth between team members, speeding up production.

See also: 
- #577, 
- #1416, 
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

### Action Items
- [x] Discuss the new design system more in-depth so that there is a group understanding
- [ ] Create an issue for one of the checkboxes in the Components section below
- [ ] Add the link to the issue you made into the Components section (so the issue does not get made twice).
- [ ] As part of the auditing/researching/recommendations issue, include the following as Action Items (you can add additional Action Items as you see fit):
````
    - [ ] Search and find where each component is by looking at the pages that are live on the website and also in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0) for not yet live pages.
    - [ ] Questions to answer/consider when working on this issue:
      - [ ] Where should the component live? In other words, which file should the CSS for the component be in? Does this file need to be created?
      - [ ] What are the differences between the classes that are located on the specific pages? Document those differences 
      - [ ] If they don't appear the same, should we rationalize them and make them the same across the page they show up on? 
      - [ ] Should the class(es) be renamed to be clearer?
  - [ ] If research is necessary, summarize your research
  - [ ] Summarize your recommendations for how to standardize the component and its code
  - [ ] Have a Merge Team member or a Technical Lead to review and sign off on your analysis and recommendations
  - [ ] Have a Product Manager review and sign off on your recommendations
  - [ ] (Optional) Write a new issue for a developer to implement your recommendations.
    - [ ] Here is the [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues) wiki page for how we write issues on the Hack for LA Website Team
    - [ ] Ask a Merge Team member or Technical Lead if you need help with writing an issue. 
    - [ ] Include this in the Action items of your issue
```
 - [ ] Come up with a standard way to implement the CSS side (and, if applicable, HTML) of each component
 - [ ] Implement the CSS side (and, if applicable, HTML) of each component
 - [ ] Create/update a wiki for the design system component
 - [ ] Update the GitHub action that will emphasize the use of the system
```
````
#### Guidance on how to make the issues
- The auditing, researching, and recommendations for how to standardize the component can all be in one issue.
   - The issue for auditing, researching, and recommendations can be either a small or medium issue depending on the number of instances of each component on the webpage. For example, since accordions only show up twice throughout the website, if I were to write an issue for auditing, researching, and recommendations for the accordions, I would label it as a small issue.
     - Note: Some issues have already been written for this epic (they are linked in the Components section)

### Components
- [ ] Accordions standardized
  - [x] Accordions standards discussed (#1407) 
  - [ ] Audit accordions on website and in codebase
  - [ ] Accordions standardized css and html implemented
  - [ ] In the wiki, add a `Components: Accordion` wiki page
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Buttons standardized ([Button Project Board](https://github.com/hackforla/website/projects/7?card_filter_query=complete+refactor%2Fstandardization+of+all+button))
  - [x] Button standards discussed (#1352)
  - [x] Buttons audited (#1921)
  - [x] Button html/CSS implemented
    - #2104
    - #2158
    - #2159
    - #2165
    - #2187
  - [ ] In the wiki, add a `Components: Buttons` wiki page
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Cards css standardized
  - [ ] Cards standards audited (#2061)
  - [ ] Cards html implemented (#2226)
  - [ ] In the wiki, add a `Components: Cards` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [x] Colors css standardized - [Color Standardization Project Board](https://github.com/hackforla/website/projects/7?card_filter_query=design+system+audit%3A+swap+colors)
  - [ ] In the wiki, add a `Components: Colors` wiki page
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase  
- [ ] Dropdowns css standardized
  - [ ] Dropdowns standards discussed
  - [ ] Audit dropdowns on the website and in the codebase
  - [ ] Dropdowns html implemented
  - [ ] In the wiki, add a `Components: Dropdowns` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Filter tags css standardized
  - [ ] Filter tags standards discussed 
  - [ ] Audit filter tags on the website and in the codebase
  - [ ] Filter tags html implemented
  - [ ] In the wiki, add a `Components: Filters` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [x] Header container css standardized(#1898, )
  - [x] Header container standards discussed (#1898, )
  - [x] Header container html implemented (#1898, )
  - [ ] In the wiki, add a `Components: Header Container` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Input fields css standardized
  - [ ] Input fields standards discussed (#1398, )
  - [ ] Audit input fields on the website and in the codebase
  - [ ] Input fields html implemented
  - [ ] In the wiki, add a `Components: Input Fields` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Modals css standardized
  - [ ] Modals standards discussed 
  - [ ] Audit modals on the website and in the codebase
  - [ ] Modals html implemented
  - [ ] In the wiki, add a `Components: Modals` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [ ] Sticky side nav css standardized
  - [ ] Sticky side nav standards audit (#2173)
  - [ ] Sticky side nav html implemented (#2174)
  - [ ] In the wiki, add a `Components: Sticky Side Nav` wiki page 
  - [ ] Audit design system classes/code in Figma to make sure they match the codebase
- [x] Typography css standardized (#1743, )
  - [ ] Fixing all the typography on the website will become it's own epic for devs. A new dev issue will be written as each of the Design Team ["Design System Audit: Text Elements:" issues](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+design%22+Design+System+Audit%3A+Text+Elements+-milestone%3A%22w.+Ongoing+%22+) are completed and added to the new epic in order to track them. 

### Resources/Instructions
- #577
- #1416
- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- Standardized Components wiki page (explains how the standardized components should work in general): https://github.com/hackforla/website/wiki/Standardized-Components

#### Historical information
- [x] ~#1927~
   - Note: We are no longer updating/maintaining the [Design System webpages](https://www.hackforla.org/design-system). Read the decision record on [Maintaining the Design System webpages](https://github.com/hackforla/website/wiki/DR:-Maintaining-the-Design-System-webpages) for more info.

### LINKED ISSUE #1927: Create the design system pages
### Overview

Jumping off of discussion that started in #1850, this will be the issue to discuss the specifics of the Design System webpages that will exist on our website.

Last comment on the [Design System webpages from #1850 ](https://github.com/hackforla/website/issues/1850#issuecomment-877859115).

### Action items

- [x] Decide on goals of the pages
- [x] Decide on design of the architecture
- [x] Create prototype of the design system
- [x] Open a discuss on prototype if needed
- [ ] ~Finalize design system pages~ - this will need to be a new issue (which has as its dependency, the design system team making new mockups for development).  See comment below

### Resources/Instructions
#577
#1416
#1850
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

### PR DESCRIPTION
**Pull request by arghmatey**
Fixes #1927

### What changes did you make and why did you make them ?

  - Created front end of design system page. Not all styling is complete. Design system starts on /design-system page, then when a component is chosen design-system layout is loaded. This is similar to guide-pages from /toolkit page, but the visual layout remains the same. 
  - Created design-system collection to display on front end.

### Action Items
- [x] Complete adding component information from Figma to md files - both for buttons and page cards. This is just copy/paste and will not take long.
- [ ] Style page to match [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=12438%3A96181) file. This includes researching and implementing code block coloring, though this could be turned into a separate issue after MVP is complete.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
August 7, 2021 Progress
August 7, 2021 Progress

### CODE REVIEW

**Comment by arghmatey** [comment]
From your project repository, check out a new branch and test the changes.

```
git checkout -b arghmatey-design-system-webpage gh-pages
git pull https://github.com/arghmatey/website.git design-system-webpage
```
---
August 13, 2021 Progress
Screen Shot 2021-08-13 at 10 46 35 AM

**Comment by Aveline-art** [comment]
@arghmatey Just want to note that if the site is still waiting on some components before it can go live, we can always set `published` to false and that should hide the site for now.

**Comment by arghmatey** [comment]
@Aveline-art Good idea! I've set `published` to false.

**Comment by arghmatey** [comment]
Converted from draft to ready to review. **Margins are off. They are still being finalized by design. Reached out and am waiting for update.**

Discussed moving on with what we have and creating new smaller issues for things we are waiting for. Will update with new issue numbers as they are created.

**Comment by arghmatey** [comment]
Updated with new margins, resolved conflicts, and added a _rough_ mobile view.

**Review by Aveline-art — DISMISSED** [review]
Just took a look at it all, and this is all very impressive work! Everything is so reusable and so easy to add to!

One thing to note: we have recently decided to name the files in the `_includes` directory according to the pages they are used in. The example directory should ideally be further nested in a `design-system-page` directory. After that, I will say this is ready to merge, unless someone else has other thoughts.

You have outdone yourself again @arghmatey ! I feel so honored to review and witness such great work. Thank you!

**Comment by arghmatey** [comment]
@Aveline-art Thanks for your review and kind words. :) I've pushed a new commit to reflect our new naming convention.

**Review by Aveline-art — APPROVED** [review]
Everything looks good! Feel free to make new issues for follow up tasks, or continue working on the issue.

From what I can see, issues can be made for:

- solving the sticky-nav issue
- adding the typography section

Also, it might be prudent to document the architecture of these pages in a new wiki, as well as steps to adding new pages/components.

**Pull request merged**
