### PR TITLE
Added Github-handle for Bonnie Wolfe

### LINKED ISSUE #6717: Add github-handle for Bonnie Wolfe in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jenjenkayi**
Fixes #6717

### What changes did you make?
  - Added github-handle for Bonnie Wolfe in ems-triage-tracker.md.

### Why did you make the changes (we will use this info to test)?
  - Reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - Added github-handle to the file. No visual changes to the website.

### CODE REVIEW

**Comment by del9ra** [comment]
Review ETA: EST 10 PM 5/9/24
Availability: 5-8 PM Friday

**Review by del9ra — APPROVED** [review]
Hi @jenjenkayi, 
* Used the correct branch for pull request
* The issue is properly linked
* Changes were made correctly
* The appearance of the project webpage is unchanged
Thanks for your contribution!

**Comment by DeniseLewis1** [comment]
Review ETA: End of day 5/10
Availability: 5/10 9AM - 2PM

**Review by DeniseLewis1 — APPROVED** [review]
Great job @jenjenkayi!

- The correct branch was used for the pull request
- The issue is linked correctly
- Changes were made correctly
- No visual changes across Firefox and Chrome in desktop, mobile, and tablet views

Thank you for your contribution!

**Pull request merged**
