### PR TITLE
Add new variable github-handle  for member Jason Brown in 100-automations.md 

### LINKED ISSUE #5509: Add new variable github-handle for member Jason Brown in 100-automations.md
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Jason Brown
```
with
```
- name: Jason Brown
  github-handle: 
```
- [ ] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by aramattamara**
Fixes #5509 

### What changes did you make?
  - Add github-handle to 100-automations.md
 

### Why did you make the changes (we will use this info to test)?
  - https://github.com/hackforla/website/issues/5509
 

 Confirmed that the appearance of the project webpage is unchanged at all screen sizes.

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: 6 PM 9/24/23
Availability: 11 AM-6 PM Sunday

**Review by KyleA99 — DISMISSED** [review]
Reviewed and approved.  Looks great @aramattamara

**Comment by KyleA99** [comment]
@ajb176 @roslynwythe @MattChau01  visual issue is not appearing on this page (aramattamara did not pre-fix github variable with "-").  The presence of "-" prefix may cause issues with how these markdown files are being parsed?

@aramattamara fyi we encountered an issue described in comments of #5565 so I wanted to update others as your PR is very similar.

**Comment by roslynwythe** [comment]
@aramattamara @KyleA99 @agutiernc There is an error in the original issue and it will be updated shortly.  In the meantime please do not review or merge.  Thank you.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@aramattamara I apologize for the error in the original issue.  It has been updated along with a new comment.  It looks like you correctly added the `github-handle` variable, however the intention for this `good first issue` was simply to place the variable, and not to populate the variable and replace the previous variables.  Eventually, when the code has been modified, all of those changes will be made but for now I have to ask that you make only the exact change specified in the issue.  Thank you

**Review by KyleA99 — APPROVED** [review]
Looks good to me.  Nice work @aramattamara

**Review by roslynwythe — APPROVED** [review]
Thank you @aramattamara for excellent work on this issue.  Your code is correct and clean and checkes out perfectly in the browser.  The PR is descriptive and the branches are setup correctly.  We appreciate your contributions!

**Pull request merged**
