### PR TITLE
Img Tag Refactor #4398

### LINKED ISSUE #4398: img Tag Refactor: Getting Started page - `step-img-wide technology.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-wide" src="./assets/images/getting-started/technology.png" alt="" />
```
to
```
<img class="step-img-wide" src="./assets/images/getting-started/technology.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by katiehermalik**
Fixes #4398

### What changes did you make and why did you make them ?
- Changed an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.
- Check the page remains the same in mobile, tablet, and desktop views as on the current website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: 1pm PDT
Availability: After 12pm PDT today

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. Pull request includes a summary of changes made and why.
Requested changes have been made and everything looks good on Docker. Great work!

**Comment by StephenTheDev1001** [comment]
ETA: EoD
Availability: M-F 10am-12pm

**Review by StephenTheDev1001 — APPROVED** [review]
Good description of the changes and rationale behind them. The PR comes from the correct branch and the changes to the code is correct. Good job on your first pull request.

**Comment by ghost** [comment]
ETA: 8pm PST
Availability: April 29th, 2023 7:30pm - 11:00pm

**Review by ghost — APPROVED** [review]
Descriptive title with issue number, completed the task as ticket requested. Fantastic job, keep up the good work!

**Review by t-will-gillis — APPROVED** [review]
Hey @katiehermalik Great job! Your branches are correct, your changes address the issue cleanly and concisely, you are referencing the issue correctly, you have specified the changes you made and why, and finally  in Docker everything appears to be functioning as intended.

Congrats on your first issue and thank you!

**Pull request merged**
