### PR TITLE
added github handle for Priyanka Talwar - not Bryanna

### LINKED ISSUE #7248: Add github-handle for Priyanka Talwar in tech-work-experience.md REVISED
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Priyanka Talwar
```
with
```
- name: Priyanka Talwar
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by NolaDodd**
Fixes #7248 

### What changes did you make?
  - Added "github-handle" for Priyanka Talwar in _projects/tech-work-experience.md
  - ***NOTE: The issue title says changes to Add github-handle for Bryanna Lim in tech-work-experience.md #7248 but the actual issue description says Priyanka Talwar.  
 
UPDATE*** Merge Team changed title to reference "Priyanka Talwar"
  
  ### Why did you make the changes (we will use this info to test)?
  - To add a place for Priyanka to add her Github handle. Eventually, the github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

### CODE REVIEW

**Comment by andyphancode** [comment]
Review ETA: 8/30/24 EOD
Availability: throughout week

**Comment by andyphancode** [comment]
Branches look good, correct addition to Priyanka. Good catch on the inconsistency of names. @roslynwythe did they select the proper individual to add github-handle to, or was the issue intended to change for Bryanna Lim? 

For @NolaDodd , please add a "Why did you make the changes (we will use this info to test)?" regularly to pull requests. A good idea would be "Added a github handle label to hold github profile link of person" or whatever you see appropriate.

**Comment by NolaDodd** [comment]
> Branches look good, correct addition to Priyanka. Good catch on the inconsistency of names. @roslynwythe did they select the proper individual to add github-handle to, or was the issue intended to change for Bryanna Lim?
> 
> For @NolaDodd , please add a "Why did you make the changes (we will use this info to test)?" regularly to pull requests. A good idea would be "Added a github handle label to hold github profile link of person" or whatever you see appropriate.

Added the "Why" for the request, thank you!

**Review by andyphancode — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Hi @NolaDodd (and @andyphancode , @roslynwythe ) Thanks for pointing out the mix up. The issue title is now updated to #7248, and also updated the issue and issue title for #7239 to address "Bryanna Lin"

**Comment by 8alpreet** [comment]
**Review ETA:** EOD Sep 4, 2024
**Availability:** 3pm to 7pm weekdays

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @NolaDodd,

What went well:
* Correct lines of code were changed.
* PR title is descriptive and concise.
* Branch is named correctly.
* Related issue is linked.

Changed Needed:
1. Why section:
    * your why section is very similar to your what section because it describes *what* you did not *why* you did it. I know the distinction is blurry on these good first issue, but the *why* is the cause of the changes. Let's say for example, that some elements in the website were having weird sizing issue on mobile devices. You figure out that some CSS in file X is the cause. So your what would be: I changed _____ in file X. Your *why* should explain why it was those lines of code that needed to be changed.
2. Screenshots section:
    * you don't need the quotes around "- No visual changes..."

**Review by k-cardon — APPROVED** [review]
This looks correct, @NolaDodd! You branched correctly, added the correct lines of code, used spaces instead of indent, and I confirmed no visual changes to site. 

Since Balpreet wants a change to the "why" section of the pull request, you could pull text from the issue, which explains why the site is updating the github-handle variable:

"Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file."

**Review by codyyjxn — APPROVED** [review]
@NolaDodd  Nice this looks good! The title is concise and the pr is good !

**Comment by Thinking-Panda** [comment]
@NolaDodd Please make requested changes and re-request a review.

**Review by 8alpreet — APPROVED** [review]
Things look great now, thanks for applying the feedback!

**Pull request merged**
