### PR TITLE
Removed line 8 unused alt-hero field

### LINKED ISSUE #3208: Remove unused `alt-hero` field from open-community-survey.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/open-community-survey.md`, remove line 8 for the alt-hero
```
alt-hero: 'Silhouette of buildings and houses with different colors, shapes and styles.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/open-community-survey.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/_projects/open-community-survey.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by Skydodle**
Fixes #3208

### What changes did you make and why did you make them ?

  - Removed line 8 because the alt-hero field is not used anywhere in the website
 
no visual change on the website

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 11/8/22 2pm
Availability: 11/8/22 Flexible

**Comment by luiderek** [comment]
Review ETA: 10m
Availability: till 10pm pdt

**Review by jyaymie — APPROVED** [review]
Great job, @Skydodle! You took care of the issue's action item appropriately. And I like your branch name - brief yet effective in helping us understand the issue at a glance.

**Review by luiderek — APPROVED** [review]
Nice stuff @Skydodle. The pull request is coming from a properly named forked branch, and you've hit the right file; Just be aware the action items on the issue itself can be checked off when they're finished.

**Pull request merged**
