### PR TITLE
Hack Night updates

### LINKED ISSUE #134: Add card for South LA's Wednesday meetup
### Overview
Create new card on website to represent South LA's Wednesday meetup

### Action Items
Gather these items and attach them to this issue.  Notify @ExperimentsInHonesty when completed

- [ ] 600 x 400 image of sip and sonder
- [ ] Location

### Resources/Instructions
see https://hackforla.org for how the other hack nights look

### PR DESCRIPTION
**Pull request by thekaveman**
* **Finally** adding a card for South LA
* Verbiage around *Onboarding Nights*
* Linking off to Meetup for schedules/locations

The new Hack Nights section:

image

Closes #134

### CODE REVIEW

**Comment by ExperimentsInHonesty** [comment]
I think we need to agree on how we word the titles on the hack nights.  Right now we have a wide variety of titles, which I think will make it difficult for people to figure out what is going on:

Westside Civic Hack Night - Onboarding Night
Westside Civic Hack Night - Ongoing Project Work

DTLA Civic Hack Night - Consolidation Night
DTLA Civic Hack Night - New volunteer onboarding/project showcase

South LA Hack Night

**Comment by thekaveman** [comment]
That should be easy, just rename the existing (repeated) Meetup to include the Onboarding Night right?

**Comment by ExperimentsInHonesty** [comment]
I think it should say "..for the current schedule and locations."

But I can add that after we push this.

**Comment by matikin9** [comment]
Tam & I give 👍  👍

**Comment by thekaveman** [comment]
@ExperimentsInHonesty I added the "... and locations." bit at the end there. Merging!

**Pull request merged**
