### PR TITLE
Img tag refactor getting started page 4418

### LINKED ISSUE #4418: img Tag Refactor: Getting Started page - `step-img-icon-join-slack proj-4.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-join-slack" src="assets/images/getting-started/proj-4.png" alt="" />
```
to
```
<img class="step-img-icon-join-slack" src="assets/images/getting-started/proj-4.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by katherinek123**
Fixes #4418 

### What changes did you make and why did you make them ?

  - removed the slash to refactor the image tags to update the html tags to maintain consistency throughout the codebase.

### CODE REVIEW

**Comment by LOSjr4** [comment]
image
@katherinek123, type the original issue number here. It will automatically make a link to original issue so we all can easily refer back to it.

**Comment by katherinek123** [comment]
> image @katherinek123, type the original issue number here. It will automatically make a link to original issue so we all can easily refer back to it.

thanks for that! your screen shot made it quick to fix!

**Review by matthewmpan — CHANGES_REQUESTED** [review]
Hi @katherinek123 Thanks for taking up this issue! Your branches are set up correctly and the issue is correctly linked. Taking a look at issue #4418, the requested change relates only to line 201, but I noticed that you updated lines 91 & 178 as well. These line updates are probably linked to other issues, so it is best to leave them as is for now. After reverting those two lines, your PR should be good to go.

**Comment by katherinek123** [comment]
> 

thanks for taking a look. I'll add the changes later tonight! Could you let me know how you were able to find that the issue only relates to line 201? Seems like I missed it.

**Comment by 93Belen** [comment]
Availability: Tuesday, Thursday and Sunday from 6am to 6pm
ETA: 5/30/23 by 6pm

**Review by 93Belen — DISMISSED** [review]
Hi! You did the pull request from the correct branch and linked the issue correctly, but I noticed two problems:
- The Issue ask you to change only the image with class step-img-icon-join-slack. Which is the one in line 201
- In the description of you PR you said the reason to change it is "according to the pull request". It would be better if the "why" is more explicative like: "so that the codebase is consistent with how we use img HTML tags."
Once you make that couple of changes everything should be good to go :)

**Comment by 93Belen** [comment]
> thanks for taking a look. I'll add the changes later tonight! Could you let me know how you were able to find that the issue only relates to line 201? Seems like I missed it.

It says to change this specific image: 
There you can see the class :)

**Comment by katherinek123** [comment]
> > thanks for taking a look. I'll add the changes later tonight! Could you let me know how you were able to find that the issue only relates to line 201? Seems like I missed it.
> 
> It says to change this specific image:  There you can see the class :)

Got it! I misread the additional classes that I changed. I thought it was the same class. I will make the changes and edit my pull request.

**Comment by rdhmdhl** [comment]
availability: weekdays 5-9pm; weekends 9-5pm
ETA: 5/31

**Comment by 93Belen** [comment]
Hey @katherinek123! I see you made some changes, remember to change the correct img (double check the class). And click the arrows by the reviewers' names when you are ready for us to re-review your changes ☺️

**Comment by rdhmdhl** [comment]
Good job @katherinek123! I see that you have linked the issue at the top, and you have understood the issue. I have looked at the change you made to the getting-started.html file and viewed the change on desktop and mobile devices. Pull request approved!

**Review by matthewmpan — DISMISSED** [review]
Hi @katherinek123 Just following up on my request for review. I will just piggyback off of the last comment made by @93Belen and mention that the only image that should be updated in this PR is the one with **class="step-img-icon-join-slack"**.

**Comment by mademarc** [comment]
Review ETA: 6/22/2023
Availability: 7:16PM

**Review by mademarc — DISMISSED** [review]
Hey @katherinek123 the format for line 91 img tag change was done very well in order in making  the code look professional.

**Comment by blulady** [comment]
@rdhmdhl if you still intend on reviewing this, please put your eta or remove yourself as a reviewer please.

**Review by rdhmdhl — DISMISSED** [review]
Good job @katherinek123! I see that you have linked the issue at the top, and you have understood the issue. I have looked at the change you made to the getting-started.html file and viewed the change on desktop and mobile devices. Everything looks normal.

If there are no visual changes, it isn't necessary to include the section "Screenshots of Proposed Changes Of The Website" on the pull request description. This is approved!

**Comment by chrismenke45** [comment]
Hi @katherinek123, 
Do you have an ETA on requested changes?

**Comment by katherinek123** [comment]
Just updated the pull request!

**Comment by roslynwythe** [comment]
@katherinek123 if you would like to re-request reviews, please click the highlighted icon which appears in the top right hand corner of this page.  
image

**Comment by 93Belen** [comment]
Availability: Tuesday, Thursday and Sunday from 6am to 6pm
ETA: Sunday by 6pm

**Review by 93Belen — COMMENTED** [review]
I think the previous img tag that you changed has already been changed in another PR and that's why it shows that you are adding the slash to it again. You probably need to update your branch with the new changes in the gh-pages branch.

**Review by rdhmdhl — COMMENTED** [review]
Belen appears to be correct. There are two images edited in your pull request. I would get the recent changes from the gh-pages repo, then ensure that your pull request is only editing one image at a time, like the issue suggests.

**Comment by mademarc** [comment]
Review ETA: 7/13/2023
Availability: 7PM

**Review by mademarc — DISMISSED** [review]
Hey @katherinek123   good move of your in removing the / on the img html tags

**Review by t-will-gillis — APPROVED** [review]
Hey @katherinek123 Great job on your first issue and thanks for explaining everything. As we discussed, I imagine that another dev changed line 91 while your issue was open- but we are good to go now.

Thanks!

**Review by t-will-gillis — APPROVED** [review]
tags are fixed now

**Review by t-will-gillis — APPROVED** [review]
This has been fixed now

**Comment by t-will-gillis** [comment]
Hi @matthewmpan and @93Belen: 
FYI @katherinek123 and I went through the issue and comments during the Tuesday meeting, and the PR now is editing line 201 only.

**Pull request merged**
