### PR TITLE
Updated calendar-time.yml in Credits Page - #2800

### LINKED ISSUE #2800: Edit content field and remove type field from calendar-time.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/calendar-time.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/calendar-time.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/8757cb553d879ef0543c5809be82c91312e4f0ff/_data/internal/credits/calendar-time.yml#L4
https://github.com/hackforla/website/blob/8757cb553d879ef0543c5809be82c91312e4f0ff/_data/internal/credits/calendar-time.yml#L11

### PR DESCRIPTION
**Pull request by oliviaywangn**
Fixes #2800

### What changes did you make and why did you make them ?

  - changed line 4 of calendar-time.yml from content field to content: icon
  - removed line 11 for type field
  - the information was redundant, and using content-type makes it clearer for developers what the content is used for in the future

No visible changes were made to the website.

### CODE REVIEW

**Comment by answebdev** [comment]
Availability: 1 hour
ETA: 6/17/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@oliviaywangn Thank you for submitting your PR. For this issue, in the file `_data/internal/credits/calendar-time.yml`, line 4 needed to be changed from `content: icon` to `content-type: image`, and line 11 needed to be removed, which I can see that you did. Great job!

On a minor note, please add this PR to the Project Board. Thanks!

**Comment by answebdev** [comment]
@oliviaywangn Great job working on this issue. Please add this PR to the Project Board. Thanks.

**Comment by ericvennemeyer** [comment]
Availability: 1 hour
ETA: Monday 6/20/2022 (end of day)

**Review by ericvennemeyer — APPROVED** [review]
@oliviaywangn I see that line 4 in this file has been changed from `content: icon` to `content-type: image`, and line 11 has been deleted, exactly as specified in the original issue. Good work!

**Pull request merged**
