### PR TITLE
Update Project Profile: LA TDM Calculator Remove Ebi Imafidon

### LINKED ISSUE #7650: Update Project Profile: LA TDM Calculator Remove Ebi Imafidon
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
  - name: Ebi Imafidon
    github-handle:
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U031EU2E6LB'
      github: 'https://github.com/Biuwa'
    picture: https://avatars.githubusercontent.com/Biuwa
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by mugdhchauhan**
Fixes #7650 

### What changes did you make?
  
  - Update Project Profile for LA TDM Calculator by removing Ebi Imafidon from the Current Project Team

### Why did you make the changes (we will use this info to test)?
  
  - We need to keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Screenshot Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot After

</details>

### CODE REVIEW

**Comment by trimakichan** [comment]
Review ETA: 3 PM 11/19/2024
Availability: 10-3 PM Monday - Friday

**Review by trimakichan — APPROVED** [review]
Fantastic job, @bmugdhchauhan!

Everything looks great to me.

- The branch name includes the issue number and clearly describes the work you did.
- The issue is linked correctly.
- Before-and-after screenshots are provided to demonstrate the changes.
- The code changes are accurate.
- CodeQL alerts have been checked.

Thank you for your contribution! Keep up the excellent work!

**Comment by mamypoco** [comment]
Review ETA: 6 PM 11/19/2024
Availability: 10-3 PM M-F

**Review by mamypoco — APPROVED** [review]
Great job, @bmugdhchauhan, Everything looks awesome!

- The branch you work on is correct, the branch name is clear.
- The linked issue number is included.
- Availability and ETA are provided.
- The change you made is correct.
- Before-and-after screenshots match the frontend view.
- CodeQL alerts have been checked.

Keep up with the great work!

**Comment by mugdhchauhan** [comment]
Thank you @trimakichan and @mamypoco

**Pull request merged**
