### PR TITLE
Adds Program Areas header image to Credits

### LINKED ISSUE #1507: Add Program Areas page header illustration to Credits page
### Overview
We need to add the vector illustration from the [Program Areas page](https://www.hackforla.org/program-areas) header to the [Credits](https://www.hackforla.org/credits/) page so that we are following the image use requirements

### Action Items
- [ ] View the image credit information in the comment below (scroll down) 
- [ ] Add the credit information to the Credits page

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [credit.md template](https://github.com/hackforla/website/wiki/Template-of-a-credit.md-file-(for-Credits-page))

### PR DESCRIPTION
**Pull request by grhhhh**
Fixes #1507

Adds Program Areas header image and info to the Credits page

Screen Shot 2021-05-06 at 12 57 30 PM

### CODE REVIEW

**Review by averdin2 — CHANGES_REQUESTED** [review]
@grhhhh The artist: Stories should be lower case 'stories'. Other than this, looks good to me.

**Comment by grhhhh** [comment]
Changed "Stories" to "stories" in the latest commit

**Review by qiqicodes — CHANGES_REQUESTED** [review]
The page looks good, the alt text needs to be a little more descriptive. and "Image of" is not necessary.

Hope these resources can help you.
https://cliquestudios.com/alt-text/
https://medium.com/nyc-design/how-to-write-effective-alt-tags-for-images-9f888f36992f

**Comment by grhhhh** [comment]
I agree the alt text should be improved, however the alt text in this pr is in keeping with the convention set forth by the existing images on the credits page, each being 'Image of _____". I suggest we create a new issue to create a new standard for the alt text of the credits page overall.

**Comment by qiqicodes** [comment]
> I agree the alt text should be improved, however the alt text in this pr is in keeping with the convention set forth by the existing images on the credits page, each being 'Image of _____". I suggest we create a new issue to create a new standard for the alt text of the credits page overall.

We've created an issue addressing the alt text for all images on the credit page. #1526

**Comment by grhhhh** [comment]
Allowing for issue #1526 to resolve the question of alt text for this image as well would avoid duplicating the work of creating a methodology for alt text on the credits page. It would also avoid creating two solutions to the alt text question that could possibly be in conflict.

**Comment by akibrhast** [comment]
LGTM

**Pull request merged**
