### PR TITLE
Make "Learn more" link visible on Redesigned Homepage and link it to About Page

### LINKED ISSUE #7689: Make "Learn more" Link Visible on Redesigned Homepage
### Overview
We want the **Learn more** link to the _About Us_ page[^about-page] to be visible on the redesigned homepage so that visitors to the website can read more information about Hack for LA.

<details>
   <summary>Click here to see a screenshot of the <b>Learn more</b> link we want to make visible on the redesigned homepage.</summary>

   Screenshot 2024-11-04 155206

</details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow **Step 1: Create your branch** in _How to work off of a feature branch_ wiki article[^how-to-work-off-of-a-feature-branch].
- [x] For `_includes/home-page/hero.html`[^homepage-hero], find 
   ```
           <!-- Link below to remain inactive until About page is completed and live -->
           <!-- <a href="/about">Learn more</a></p> -->
   ```
   - [x] Delete 
      ```
              <!-- Link below to remain inactive until About page is completed and live -->
      ```
   - [x] Make the **Learn more** link visible by uncommenting it so that this
      ```
              <!-- <a href="/about">Learn more</a></p> -->
      ```
      becomes
      ```
              <a href="/about">Learn more</a></p>
      ```
- [x] To update your topic branch, please follow **Step 2: Update your branch with upstream changes** in _How to work off of a feature branch_ wiki article[^how-to-work-off-of-a-feature-branch].
- [x] The pull request created from this issue will be merged into `feature-homepage-launch` by a Merge Team member. Please follow **Step 3: Create a pull request** in _How to work off of a feature branch_ wiki article[^how-to-work-off-of-a-feature-branch].
### Resources/Instructions
- This issue originated from this comment: https://github.com/hackforla/website/issues/2317#issuecomment-1083703541
[^about-page]: Link to _About Us_ page: https://www.hackforla.org/about/
[^how-to-work-off-of-a-feature-branch]: [How to work off of a feature branch wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[^homepage-hero]: `_includes/home-page/hero.html` on the **feature-homepage-launch** branch: https://github.com/hackforla/website/blob/feature-homepage-launch/_includes/home-page/hero.html

### PR DESCRIPTION
**Pull request by belunatic**
Fixes #7689

### What changes did you make?
  
  - I made changes to the file `_includes/home-page/hero.html`
  - I deleted a comment 
  - I made the **Learn more** link visible by uncommenting it 

### Why did you make the changes (we will use this info to test)?
  
  - Because the author wanted the **Learn more** link to be visible and link to the _About US page_  on the redesigned homepage so that visitors can read more information about  Hack for LA. 

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

FireShot Capture 080 - Hack for LA - localhost

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
FireShot Capture 079 - Hack for LA - localhost

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
@codyyjxn , please provide your Review ETA and Availability when assigning yourself

**Review by codyyjxn — APPROVED** [review]
### Things that went well:
-The file change is correct with uncomment code. 
-The title is concise and the description is also clear.  

### Some suggestions 
- You need to change the  P: HfLA Website: Project Board : `Prioritized backlog` to `In Progress`

**Comment by belunatic** [comment]
@codyyjxn Thank you for that I went ahead and changed the status.

**Comment by minkang3** [comment]
### Eta
Within the hour
### Availability
5-9 pm

**Review by minkang3 — APPROVED** [review]
### What looks good
- What changes you made look good
- Reason for changes look good
- Branch name looks good
- Code changes looks good
- Visual changes looks good

Everything looks good to me.

**Comment by mchait18** [comment]
Review ETA: 12:30 PM 12/10/24
Availability: 9-3 EST

**Review by mchait18 — APPROVED** [review]
Thank you for working on this issue, @belunatic  !
You're doing these right:

The branch you made the change on is correct
The linked issue (original issue) number is included
The content required to be removed is accurate
The CodeQL Alerts are checked (check box above)
The screenshots are clear

Great job!

**Review by DrAcula27 — APPROVED** [review]
@belunatic Great job on your `Small Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7689 
- The correct file `_includes/home-page/hero.html` was edited
- No extra edits were made
- Commit is in the correct feature branch
- Appearance of the website looks good in Chrome and Firefox
Approved! 👍

**Pull request merged**
