### PR TITLE
Added span tag to learning section

### LINKED ISSUE #5367: Refactor HTML: _includes/about-page/about-card-platform.html - Learning
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
                    <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/learning.svg" alt=""></span><span class="sub-head-text color-orange">Learning</div>
```
to
```
                    <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/learning.svg" alt=""></span><span class="sub-head-text color-orange">Learning</span></div>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by soleilherring**
Fixes #5367

### What changes did you make?
  - added span tag to the learning section of the about section
  
### Why did you make the changes (we will use this info to test)?
  - We want to update an HTML tag to resolve the linter error "Tag must be paired; missing </span>"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 - No visual changes to the website.

</details>

### CODE REVIEW

**Review by one2code — COMMENTED** [review]
Excellent job on making the requested changes, and merging into the correct branch on your 1st commit. For future PR submissions, it's ok to remove unused bullet points and skip the visual if no visual changes are made.

**Review by one2code — APPROVED** [review]

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @soleilherring Your PR looks great! Your branches from/to are good, you are linked back to the original issue, you are briefly describing what you did and why, and your edits change only what needs to be changed. As @one2code noted, on the description of what you did and why, could you delete the extra bullet points? Also, for the "Screenshots" section, since there are no visual changes here you can delete the "Visuals before/ after" dropdowns and replace with a note such as "No visual changes to the website". 

Otherwise, this is good to go- thanks for contributing!

**Comment by soleilherring** [comment]
@t-will-gillis  I deleted extra bullet points and removed the screenshot. Thank you!

**Review by t-will-gillis — APPROVED** [review]
Hey @soleilherring Thanks for making the changes- looks perfect.

**Pull request merged**
