### PR TITLE
Add "github-handle" variable for Anousha Shadrach in tdm-calculator.md

### LINKED ISSUE #7174: Add github-handle for Anousha Shadrach in tdm-calculator.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tdm-calculator.md` in the IDE
- [x] Replace:
```
- name: Anousha Shadrach
```
with
```
- name: Anousha Shadrach
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tdm-calculator

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by minkang3**
Fixes #7174

### What changes did you make?
  - Added "github-handle" variable in the LA TDM Calculator project for the member Anousha Shardrach in tdm-calculator.md

### Why did you make the changes (we will use this info to test)?
  - The variables were a bit verbose,`github` and `picture` variables were able to be condensed, reducing the redundancy in the project file.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Comment by Anahisv23** [comment]
Availability: M - F 12pm - 5pm
ETA: EOD

**Review by Anahisv23 — APPROVED** [review]
Hi @minkang3, thanks for working on this ticket. Here's what you did well along with some feedback. Nice job!

What went well
- Into and from branch are correct
- There is a linked issue present
- Modified the appropriate lines of code to add `github-handle` variable

Feedback 
- In your PR it would be helpful to be specific and descriptive about why you did the changes you did or mention what the goal of the ticket was.

**Comment by minkang3** [comment]
@Anahisv23 Thank you for the feedback, I'll keep that in mind for my next contribution.
I was wondering if there is anything left for me to do with the original issue #7174. Should I change the status to "Done" or will the automation take care of it? Thank you again. Also, should I close this pull request?

**Comment by Anahisv23** [comment]
Hi @minkang3, could you please update this PR so its more specific and descriptive about why you did the changes you did or mention what the goal of the ticket was. The merge team will be the ones to close your PR. I think you should wait to update the status to done until the merge team has looked at your PR. Great questions!

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @minkang3, thanks for working on this issue! Your changes look good, there's just a couple small things to adjust.

Here's what looks good:
- Your branches are set up correctly for merging.
- You linked the original issue in the PR.
- The code changes were made as described in the original issue.
- When testing the changes locally, the page displays correctly with no visual changes.

To do:
- As mentioned, the "Why did you make the changes" section should show that you understand the purpose of the changes you made. You can usually find this described in the original issue, in this case the new variable is going to replace two other variables in order to reduce redundancy in the project file, so your answer could be as simple as "To reduce redundancy in the file."
- Since there are no visual changes to the website, you can delete both the details sections with screenshots and just put "No visual changes."

After you make the two changes, let me know in a comment or re-request a review and I'll come back and take another look!

**Review by daras-cu — APPROVED** [review]
Thanks for making the adjustments @minkang3, everything looks good!

**Pull request merged**
