### PR TITLE
Update citizen-engagement-card.yml

### PR DESCRIPTION
**Pull request by rashmeesinha**
Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by macho-catt** [comment]
@rashmeesinha can you please update your PR so it fills out the requirements in the template?
It needs:
- What issue number it fixes
- Changes you made
- Screenshots of change

Thanks

**Comment by adam-abundis** [comment]
@rashmeesinha please refer to our contributing document to complete a pull request

https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-making-a-pull-request

As soon as your pull request initial comment is updated, we can review this pull request properly.

Thank you!

**Comment by adam-abundis** [comment]
Hi @rashmeesinha. I am going to wait until Wednesday (10/27) morning to see if you have updated the initial comment within this pull request. If you have not, I will close this pull request and you will have to submit another pull request to get credit for a Hacktoberfest contribution. Let me know if you have any questions. 

Thank you.

**Comment by adam-abundis** [comment]
@hackforla/website-merge @rashmeesinha I am going to close this PR because the pull request template was not completed correctly. You are free to submit another pull request, but please follow [Part 3: Pull Request within our Contributing document](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests).

Thank you.

**Pull request closed without merging**
