### PR TITLE
Updated Community Survey Project .md to accurately display current Pr…

### LINKED ISSUE #2711: Update Project Profile: Open Community Survey
### Overview
As a product manager of Open Community Survey I want my project's details to be up to date on the HackforLA website

### Project card
Their card URL: https://github.com/hackforla/website/tree/gh-pages/_projects/open-community-survey.md

### Action Items

- [x] Open Community Survey Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [x] Name
         - [x] GitHub hand
         - [x] Role
         - [x] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
         - [ ] Overview
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status

### PR DESCRIPTION
**Pull request by kathrynsilvaconway**
…oject Team leadership.

Fixes #2711

### What changes did you make and why did you make them ?

  -Removed from Current team section on Community Service Project's project page:
        JoAnne Narcisse
        Ebele O.
        Sonu
        Amy Wilkins
        Jasmine Kim
        Shika Zhou
        Kevin
        Bernard
  - Added Kalyani Raman, Tugba Metinyurt & Mary Kate Leibmanto Current team section on Community Service Project's project page.
  - Verified that all other info on project card displays correctly.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
after_2217

<details>
<summary>Visuals before changes are applied</summary>

before_2217

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

after_2217

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Friday, April 8, 2022

**Review by tamara-snyder — DISMISSED** [review]
Hi @kathrynsilvaconway, I think you accidentally linked a closed PR instead of the issue you were working on. Can you please change the link in your PR to the number of the issue you were working on so that we can see the issue description? Thank you!

Edit: I think you just need to change the 2217 to 2711

**Comment by kathrynsilvaconway** [comment]
> Hi @kathrynsilvaconway, I think you accidentally linked a closed PR instead of the issue you were working on. Can you please change the link in your PR to the number of the issue you were working on so that we can see the issue description? Thank you!
> 
> Edit: I think you just need to change the 2217 to 2711

Silly mistake, thank you for pointing it out. I fixed it.

**Comment by ExperimentsInHonesty** [comment]
@tamara-snyder please hold off on reviewing this.  I have asked @kathrynsilvaconway to add one more person to the project

Name: Tugba Metinyurt
GitHub handle: Tugba
Role: Researcher
SLACK ID: U02NF293BRQ

**Comment by kathrynsilvaconway** [comment]
@tamara-snyder @ExperimentsInHonesty 
I added the last name and pushed the changes. Should be reviewable now.

**Comment by blulady** [comment]
Availability: 4 hours
Review ETA: Friday, 4.10.22

**Review by blulady — DISMISSED** [review]
The branches are correct from the private branch to hackforla:gh-pages. The linked issue is also correct. But when I go to look at the visual changes they don't match the changes in the screen shots you have in the PR. I realized this is because of a last minute request from Bonnie to include Tugba Metinyurt and those changes are included in the projects/open-community-survey.md file so I believe you are good to go. Good Job!!

**Comment by SAUMILDHANKAR** [comment]
Review ETA: 4:30 PM 4/11/22
Availability: Now for an hour

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@kathrynsilvaconway Thanks a lot for updating the project team members, however, I just noticed that the one sheet pdf needs to be added as well. Please use the link in the issue to download the pdf and then add it to the following directory: `website/assets/pdfs/`. Make sure the file is named "Open-Community-Survey-One-Sheet.pdf"
Next, please add the following lines in the links section of the open-community-survey.md file:
```
  - name: Overview
    url: '../assets/pdfs/Open-Community-Survey-One-Sheet.pdf'
```
Also, requesting to add the PR to the project board and add relevant screenshots as well. Thank you. Really appreciate your great work.
Please request a re-review once the changes have been made.

**Comment by kathrynsilvaconway** [comment]
@SAUMILDHANKAR 
Changes:
   - Added the open project survey pdf to assets folder
   - added Overview link to open-cummunity-survey.md
   - Updated screenshots above to reflect the last name Bonnie added.
 
Thanks for noticing the items I missed in that comment, nice catch.

**Review by SAUMILDHANKAR — APPROVED** [review]
@kathrynsilvaconway Thanks for making the changes in such a short timeframe. All looks good in my environment. Great job! 
Note: For your future PRs, the screenshots should only be part of collapsible sections. Thanks again.

**Comment by SAUMILDHANKAR** [comment]
Holding off on merging this PR since I need [clarification](https://github.com/hackforla/website/issues/2711#issuecomment-1095791689) on the roles of some of the members being added. Have reached out to Bonnie for confirmation.

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@kathrynsilvaconway Sorry for requesting to make changes after approving the PR earlier. I just heard back from Kalyani and following changes need to be made as well.
- Role for Kalyani Raman should be Product Manager instead of Project Manager.
- GitHub handle for Tugba should be changed to TugbaMet from Tugba.

Again, want to mention that you did a perfect job for this PR and these changes are not because you missed something but because there were errors in the requirements. Thanks for keeping up with multiple last minute requests.

**Comment by kathrynsilvaconway** [comment]
@SAUMILDHANKAR 
New changes to open-community-survey.md:
- Kalyani is now a product Manager, not a Project Manager
- Tugba's Github handle is changed to TugbaMet.

**Review by SAUMILDHANKAR — APPROVED** [review]
@kathrynsilvaconway Thanks all looks good. Great work!

**Pull request merged**
