### PR TITLE
Change alt text for citizen engagement html file

### LINKED ISSUE #3103: Change alt text for Echo Park neighborhood council image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Echo Park neighborhood council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 52](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L52) for the alt text:

from
```
<img class="org-img" src="/assets/images/citizen-engagement/echo_park_neighborhood_council.svg" alt="echo park neighborhood council logo">
```
to
```
<img class="org-img" src="/assets/images/citizen-engagement/echo_park_neighborhood_council.svg" alt="Echo Park Neighborhood Council">
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L52

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by clayton1111**
Fixes #3103

### What changes did you make and why did you make them ?

  - changed line 52: alt text "echo park neighborhood council logo" ----> alt text ""Echo Park Neighborhood Council"
  - This pull request also includes an edit to _data/internal/credits/citizen-engagement.yml. My first good issue (#2811) was approved but I was told to delete the blank line (line 11). I couldn't figure out how to send these pull request separately.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No screenshot

### CODE REVIEW

**Comment by clayton1111** [comment]
Also there are alot of repetitive commits. Is there a way to delete/undo a commit? I was having technical difficulties in VS code trying to change the docker-comose.yml file. I was able to revert in but in the process I created a lot of unnecessary commits that's purpose was to re-do previous work. Is there an easier solution?

**Review by luke-karis — APPROVED** [review]
This looks good to me, thanks for working on this! My only note is that it is a good idea to work on a branch off gh-pages, it should be fine for now but you can find more info about how to create a branch here https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue. If you do your work on separate branches, then you will be able to create multiple PRs

Regarding your concern about all those commits, I wouldn't worry about it. When this is merged in we can squash all your commits into a single commit by doing squash and merge. Also, if you ever want to change the name of a commit before you push it you can do `git commit --amend` (I have made a lot of typos in my commits and this command is a lifesaver)

**Comment by tunglinn** [comment]
Review ETA: 12 PM 6/28/22
Availability: Monday

**Review by tunglinn — APPROVED** [review]
Changes look good and doesn't break the site. Although you're merging from your gh-pages, Luke mentioned this will create the extra commits, but should be ok once merged. Keep it up!

**Comment by kathrynsilvaconway** [comment]
> Also there are alot of repetitive commits. Is there a way to delete/undo a commit? I was having technical difficulties in VS code trying to change the docker-comose.yml file. I was able to revert in but in the process I created a lot of unnecessary commits that's purpose was to re-do previous work. Is there an easier solution?

Hey @ericvennemeyer, do you have a suggestion on this? You probably know the most about it at this point.

**Comment by ericvennemeyer** [comment]
Hey @kathrynsilvaconway that's actually more of a git question than a Docker question, but my understanding is the extra commits won't matter because they'll all get squashed into a single commit before being merged with gh-pages.

Having said that, I opened a PR for the Docker error issue yesterday (at last). Once it's merged, and everyone incorporates the upstream changes to their local repos, we will hopefully never have to deal with this again.

**Pull request merged**
