### PR TITLE
Create new Privacy Policy page and its credit, and edit label

### LINKED ISSUE #2555: Create new privacy policy page
### Dependency
- [x]  ~#2690~

### Overview
Create a new privacy policy page to properly inform users about how the website collects, uses, stores, and protects data from site visitors.

### Details
We're creating a new privacy policy page. The content can be found in the google drive and the design can be found in the figma design under the resources/instructions section.

### Action Items

- [x] Create a credit for privacy policy page header image based on the figma design
  - [x] Add a privacy-policy.yml file to the [/_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) directory
  - [x] Follow the structure of other yml credit files and figma to create same structure
- [x] Create a new privacy-policy.html under the [/pages](https://github.com/hackforla/website/tree/gh-pages/pages) directory
- [x] Create a corresponding _privacy-policy.scss file under [/_sass/components](https://github.com/hackforla/website/tree/gh-pages/_sass/components) directory
- [x] Add the url to this [label description](https://github.com/hackforla/website/labels?q=Privacy+Policy)
- [x] Make sure the page looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)

### Resources/Instructions
[HFLA Figma - Policy Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17845%3A137765)
[Content(Google Doc)](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw)

Issue Creator - [Tomas Gonzalez - Slack DM](https://hackforla.slack.com/team/U02DF1PPQUA)
Lead Designer - [Isaac Cruz - Slack DM](https://hackforla.slack.com/team/U0255408P8Q)
Feature Page Designer - [Anh Hoang - Slack DM](https://hackforla.slack.com/team/U025DUAKAPK)

#### List of scss classes used in the Privacy Policy page (that are not in _privacy-policy.scss) and where they came from
- _sass/elements/_containers.scss
  - .header-container
    - .header-text
      - .sub-p
    - .header-hero-image 
  - .flex-container
- _sass/elements/_cards.scss
  - .page-card
  - .card-primary
  - .page-card-lg
- _sass/elements/_typography.scss
  - .title1
  - .title2
  - .paragraph2
- _sass/layouts/_main.scss
  - .content-section

#### Additional notes
- The mobile and desktop Figma designs are missing the following after the "Effective date" subheading: "This version of the policy is effective November 1, 2021." and the header "Questions", which should be there.

### PR DESCRIPTION
**Pull request by JessicaLucindaCheng**
Fixes #2555 

### What changes did you make and why did you make them ?
- As requested in the issue,
  - I created privacy-policy.yml in _data/internal/credits for the hero image on the Privacy Policy page
  - I created a privacy-policy.html in the pages directory
  - I created a _privacy-policy.scss in _sass/components
  - I added the url to the [label description](https://github.com/hackforla/website/labels?q=Privacy+Policy)
  - I checked the page looks fine on mobile, tablet, and desktop views
- I also used [WCAG 2.0 Compliance Checkers](https://github.com/hackforla/website/wiki/WCAG-2.0-Compliance-Checkers) to check the Privacy Policy page structure (HTML) followed WCAG so that our website is accessible to everyone.

Notes:
- There are differences in content (words, punctuation, contractions, etc) in the Google Doc vs the Figma desktop design vs the Figma mobile design. These differences are commented on in the Google Doc and Figma. The Figma desktop design was followed when there were differences, except for "Email Addresses" header, and the "Effective date" and "Questions" sections.
  - I used "E-mail Addresses" in the header to be consistent with the beginning of the sentence on the next line, which begins with "E-mail addresses".
  - For the "Effective date" and "Questions" sections, the content in the Google Doc was followed.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Visuals before changes are applied: There are no visuals before changes are applied because the Privacy Policy page and its associated credit are new. Thus, they don't currently exist on the website.

<details>
  <summary>Visuals after changes are applied</summary>
  
  **Credit**
  privacy-after-credit

  **Mobile View**
  pp-after-mobile

  **Desktop View**
  privacy-after-desktop

</details>

### CODE REVIEW

**Comment by luke-karis** [comment]
Review:
ETA: 5/4/22
Availability: Wednesday 1-2 hours
Edit: Sorry I couldn't finish by Monday! I will definitely finish Wednesday

**Comment by JessicaLucindaCheng** [comment]
@RyanCahela
When you're assigned as a reviewer for a pr, please write in a comment the following:
- Availability: "How much time will you have this week to review this pr?"
- Review ETA: "When do you expect to complete your review?"

**Comment by RyanCahela** [comment]
Availability: 5 hours Fri, Sat, Sun
Review ETA: 5/2/22

**Comment by Wny-Duong** [comment]
Availability: 4 hours, Thurs, Fri (4/28-4/29)
Review ETA: 4/29/22

**Comment by Wny-Duong** [comment]
Everything looks like how the original issue specified. The mobile and desktop pages I'm getting match all three of the images attached. Content matches what I'm seeing over in the Figma design besides the changes listed in Notes. The privacy-policy.yml file also matches the format of the rest. Good work!

**Review by Wny-Duong — DISMISSED** [review]
Changes approved.

**Review by RyanCahela — DISMISSED** [review]
Hey @JessicaLucindaCheng, I've reviewed the newly created files and everything is in the right place and matches the requirements of the issue, The CSS is scoped to the privacy policy page and the content responds to changes in viewport size. Great job!

**Comment by answebdev** [comment]
Availability: 2 hours
Review ETA: 5/4/2022 (end of day)

**Review by answebdev — COMMENTED** [review]
@JessicaLucindaCheng Thank you for submitting your PR. I reviewed the original issue and the changes you made, and everything looks good according to what was asked in the original issue: you created the "privacy-policy" `.yml`, `.html`, and `.scss`; added the `privacy-policy.jpg` image in the correct location; and added the url to the label description. I checked and the page looks fine on mobile, tablet, and desktop views. Thank you too for adding the notes at the end. I noticed the differences in content, but your notes helped me see what you did and why there were differences. Great job!

On a minor note, I was a little unsure about the spacing in the "Questions" section at the very bottom of the page, so I wanted to ask about it here, specifically the spacing between the sentence and the Code for America address. In the local browser (as well as in your provided screenshot image), there is no space, as you can see in my first screenshot below. I'm wondering if there should be a space here between the sentence and the Code for America address - where the arrow is pointing in my screenshot.

<details>
  <summary>Questions section in the local browser</summary>

questions

</details>

In the Figma design, there _is_ a space between the sentence and address.

<details>
  <summary>Figma design</summary>

questions_figma

</details>

I know the Figma design is not exaclty for this section (though it's similar because of the address) and you were going off the Google Doc for this (which in itself has different spacing - the address lines are actually double-spaced in the Google Doc), but I wanted to check on this since the spacing on your page, the Figma design, and the Google Doc are all different. I'm wondering if it would actually look better with the space, as in the Figma design, or if the intention was to have it with no space, so I wanted to point that out and ask about it. Other than that, everything else looks great!

**Comment by JessicaLucindaCheng** [comment]
@answebdev Good catch! I missed that space. I have updated the code so there is now a space before the address at the bottom of the page. I have also updated the after screenshots for mobile and desktop.

**Review by answebdev — APPROVED** [review]
@JessicaLucindaCheng Thank you for making those changes. I am now able to see the space locally in the browser (as well as the space added in the code) and can see the updated screenshots. As this was the only thing that I noticed, and it has now been addressed, and everything else looked great (as well as looking good to the other reviewers), I'm going to go ahead and merge this.

**Pull request merged**
