### PR TITLE
update alt text for .project-card-mini-image images

### LINKED ISSUE #3876: Program Areas: Update alt text for .project-card-mini-image images to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Program Areas` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `/pages/program-areas.html`:

**From:**
```
<img class="project-card-mini-image" src="{{project.image}}" alt="{{project.image_alt}}" />
```

**To:**
```
<img class="project-card-mini-image" src="{{project.image}}" alt="" />
```

- [x] Ensure that the corresponding `Program Areas` page stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

### Resources/Instructions
- https://www.hackforla.org/program-areas

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `/pages/program-areas.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/075ce5f7d67c7732e258148b0f4a1a9342095e26/pages/program-areas.html#L47

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by janice87**
Fixes #3876 

### What changes did you make and why did you make them ?

  - Updated the img class="project-card-mini-image" alt text from alt="{{project.image_alt}}"  to alt=""
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

program-areas-b4

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
program-areas-after

</details>

### CODE REVIEW

**Comment by janice87** [comment]
Availability for this week: Tuesday or Sunday 
My estimated ETA for completing this issue: Tuesday 3/21/23

**Comment by mjshelton12** [comment]
Review ETA: Finish by EOD today
Availability: All of today

**Review by mjshelton12 — APPROVED** [review]
Nice work on your first issue!

Your branches are done perfectly, the issue is properly attached, the changes can be seen when I pull them and are working correctly when I bring them up in docker, your code is clean, and I am adding my approval!

**Comment by Sebster3** [comment]
Review ETA: Finished by EOD, 3/20
Availability: 2PM-5PM

**Review by Sebster3 — APPROVED** [review]
Good work, Janice! The requested changes are done cleanly, in the correct branch, and render properly in Docker. Approved!

**Pull request merged**
