### PR TITLE
Refactored JavaScript files so that Events page sources meeting data from vrms_data.json

### LINKED ISSUE #6023: Refactor JavaScript so that Events page sources meeting data from vrms_data.json
### Overview
We need to refactor the JavaScript that generates the list of meetings on the Events page, so that it retrieves meeting data from the file `data/external/vrms_data.json`, in order to reduce the latency and improve the reliability of the Events page.  For testing purposes, a new page `events-check` will be created that will maintain the behavior of the current `events` page.

#### Details
The project pages currently sources meeting data from `data/external/vrms_data.json` and so elements of that code can be refactored so that functions can be called from the Events page as well.  

### Action Items
- [x] Copy `events.html` then rename the copy to `events-check.html` and change the permalink to `/events-check`
- [x] Copy `events.js` then rename the copy `events-check.js` and update `events-check.html` to reference the renamed file
- [x] Copy `_includes/events-page/right-col-content.html` then rename the copy to `_includes/events-page/right-col-content-check.html` and update `events-check.html` to reference the renamed file 
- [x] Copy `assets/js/right-col-content.js` then rename the copy `assets/js/right-col-content-check.js` and modify `_includes/events-page/right-col-content-check.html` to reference the renamed file 
- [x] Confirm that the appearance and meeting data on `/events-check` are identical to `/events`
- [x] Open the file `assets/js/project.js` in your IDE and understand the code used to display project meetings.  If there is code that can be shared between the project and events pages, move those elements to a new file `assets/js/utility/vrms-events.js`.  
- [x]  If code was moved to `assets/js/utility/vrms-events.js`, refactor the code in `assets/js/project.js` to reference function(s) in the new file, and perform testing to confirm that functionality on the Project page[^2] is unchanged. 
- [x] Refactor the code in `assets/js/right-col-content.js` and `_includes/events-page/right-col-content.html` to reference the function(s) in `assets/js/utility/vrms-events.js` and perform testing to confirm that functionality on the Event page[^1] is unchanged. 

### Resources/Instructions
[^1]:[Events webpage](https://www.hackforla.org)
[^2]:[Project page - sample](https://www.hackforla.org/projects/311-data)
[^3]:[Project Meetings page](https://www.hackforla.org/project-meetings)

### Merge Team
- [x] Release dependency on #6059, move that issue to New Issue Approval and apply "ready for dev lead" label

### PR DESCRIPTION
**Pull request by irais-valenzuela**
Fixes #6023 

### What changes did you make?
  - Created a new file in assets/js/utility called vrms-events.js to handle data fetching from the vrms_data.json file, vrms data sorting, and vrms data formatting for both project.html and right-col-content.html page.
  - The project.js file no longer has sorting and time formatting functions sortByDate and timeFormat as they were moved to vrms-events.js file and timeFormat was replaced with localeTimeIn12Format. Project.js still uses sortByDate and formatting functions but they're are now coming from vrms-events.js.
  - The right-col-content.js file now has the insertEventSchedule functionality that used to live in api-events.js. As well as other functions that used to be in api-events.js.
  - Api-events.js is no longer being used for right-col-content.js to grab event data so most of that file is commented out.
  - In summary, both project.html and right-col-content.html now share data fetching, sorting, and formatting functionality. 

### Why did you make the changes (we will use this info to test)?
  - Needed to reduce the latency and improve the reliability of the Events page and leverage the vrms_data.json file that already had event data to render meeting times for events page.
  - Both project.html and right-col-content.html had data fetching, sorting, and formatting logic that could be shared by both files.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
No changes to website. 
</details>

<details>
<summary>Visuals after changes are applied</summary>
No changes to website. 

</details>

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA: EOD 5/7/24
Availability: 9-5 PM M-F

**Review by aadilahmed — CHANGES_REQUESTED** [review]
Hi @irais-valenzuela , great job so far, the meeting data on the "events" page matches the live site exactly.

However, the meeting data is blank on the "events-check" page, which I believe is because you commented out the code in api-events.js . To maintain the behavior of the original events page, you should revert api-events.js back to its original code.

**Comment by irais-valenzuela** [comment]
@aadilahmed Thanks for catching that! I just restored the code. Let me know if everything else is good.

**Review by aadilahmed — APPROVED** [review]
Everything works as expected, great job @irais-valenzuela !

**Review by roslynwythe — APPROVED** [review]
Great job @irais-valenzuela on this `Complexity: Large` issue!  
- Code changes are clean, correct and achieve the desired refactoring
- Pull Request is well-formed with proper branching and description of work
   - The description could be improved slightly by replacing both of the "Visual changes" detail-summary blocks with a single line "no visual changes"
- Local testing of `/events-check` shows that event list is consistent with the live `/events` page
- Local testing of `/projects/civic-tech-jobs` shows that event list is consistent with the live `/projects/civic-tech-jobs` page
- Local testing of `/events` shows that event list is consistent with the live `/projects/civic-tech-jobs` page

Unfortunately in the process of checking events, I discovered discrepancies between the events on pages sourcing data from the API calls versus pages sourcing data from the `vrms-data.json` file,  
- Those will be addressed in #6838

Thank you @irais-valenzuela for this contribution to Hack for LA!

**Pull request merged**
