### PR TITLE
Refactor privacy policy page 4527

### LINKED ISSUE #4527: Refactor the Privacy Policy to use markdownify and a yml file
### Overview
We want to refactor the body of the Privacy Policy page to use a yml file for its contents/wording so that it will be easier to edit the contents of the Privacy Policy page in the future.

### Details
- Only the body of the Privacy Policy page will be refactored to use a yml file for its contents/wording.

  <details>
    <summary>Click here to see the body of the Privacy Policy page marked in a red rectangle</summary>

    privacy_-policy-body

  </details>

### Action Items
- [x] Understand how the Letter from the Executive Director is implemented on the About page using a yml file and markdownify. (See the `About Page Files and Links to Get You Started` section in the `Resources/Instructions` section below. You may need to do additional research beyond the links and files provided.)
- [x] In the `_data/internal` directory, create a new file called `privacy-policy.yml` that contains the contents/words of the body of the Privacy Policy page
- [x] Refactor the body of the Privacy Policy page to use the contents in the `privacy-policy.yml` file and markdownify
- [x] Make sure the page looks good in desktop, tablet, and mobile views

#### About Page Files and Links to Get You Started
- About page's Letter from the Executive Director: https://www.hackforla.org/about/#letter
- [_includes/about-page/about-card-executive-letter.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-executive-letter.html)
- [_data/internal/executive_letter.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/executive_letter.yml)
- [_sass/components/_about.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss)

#### Privacy Policy Page Files and Links to Get You Started
- Privacy Policy page: https://www.hackforla.org/privacy-policy
- [pages/privacy-policy.html](https://github.com/hackforla/website/blob/gh-pages/pages/privacy-policy.html)
- [_sass/components/_privacy-policy.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_privacy-policy.scss)
- `Notes from assigned developer` in #2555 
- [HFLA Figma - Policy Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17845%3A137765)
- [Content(Google Doc)](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw)

#### Other Resources
- [_data/internal](https://github.com/hackforla/website/tree/gh-pages/_data/internal)
- [Liquid template language used by Jekyll](https://jekyllrb.com/docs/liquid/)
- [Hack for LA's Site Architecture wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### PR DESCRIPTION
**Pull request by drakenguyen4000**
Fixes #4527 

### What changes did you make and why did you make them ?
  - Added a privacy-policy.yml file that contains the body of the HFLA privacy policy to _data/internal directory.
  - Refactored  body of the Privacy Policy page to use a yml file.
  - Updated SCSS to properly use the new yml html tags
 
We refactored the body of the Privacy Policy page to use a yml file so it would be easier to edit the contents of the Privacy Policy page in the future.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by LOSjr4** [comment]
Availability: weekdays 9AM-1PM
ETA: today 5/9 before 1PM

**Review by LOSjr4 — APPROVED** [review]
@drakenguyen4000 Converting the section of the privacy policy over to yml was completed very well. Everything looks perfect to me on Docker in various sizes. I wished you kept some of the line spacing (after curly braces) in the _privacy-policy.scss file, but that's just personal preference, and it's difficult to find consistency between other scss files, so I'll approve it as is.

**Comment by blulady** [comment]
@Sebster3 if we could get your eta/availability?

**Comment by Sebster3** [comment]
ETA: EOD today 5/11
Availability: 1PM-4PM

**Review by Sebster3 — APPROVED** [review]
Good job on this PR! The changes address the action items and goal of the issue, the PR correctly targets the `gh-pages` branch, and rendering of the Privacy Policy pages appears correct in my local environment. I do echo Luis' observation on the file's formatting, but the inconsistency in other files makes this inconsequential.

Approved!

**Review by t-will-gillis — APPROVED** [review]
Hey @drakenguyen4000 - Great job! You've covered the basics (correct branch, linked to the issue, addressed the issue concisely) and the changes appear correct in Docker on all formats. Thanks for your work

**Pull request merged**
