### PR TITLE
fix size and aspect ratio of not today image

### PR DESCRIPTION
**Pull request by brentjayingram**
I made the aspect ratio 600x400 with white padding on each side.

### CODE REVIEW

**Comment by brentjayingram** [comment]
This is in regards to issue #161

**Comment by sarL3y** [comment]
@bingr001 Hey Brent! Feel free to hop on our Slack if you'd like to chat about the project. Thank you for the help! [hackforla.org/slack](url)

**Comment by ExperimentsInHonesty** [comment]
@bingr001  the language you need to use on github to tie a pull request to an issue is 
fixes issue #161

@Vallsurf are you reviewing this?

**Comment by brentjayingram** [comment]
Thanks @ExperimentsInHonesty 
fixes issue #161

**Review by Vallsurf — APPROVED** [review]
This reaches the intended result of a proper aspect ratio for the not today image, although it looks like there should be more control on the CSS side rather than changing the file size directly.

**Comment by ExperimentsInHonesty** [comment]
I am satisfied that fixing the image is the solution that is appropriate here.

**Pull request merged**
