### PR TITLE
Github action append top comment on Feature Branch

### LINKED ISSUE #1940: GitHub Actions: Automatic response to feature branch issues
### Overview
We need to create a GHA to post a comment on any issue that gets a label `feature: feature branch` with details about what the developer should do.  If the label gets removed, the message should be removed.  This should be a new job that runs in parallel with the other jobs under the "[Issue Trigger](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)" action.

### Action Items
- [x] Trigger: On event `issues`: activity `opened` if the issue has the `feature: feature branch` OR activity `labeled` with the label `feature: feature branch`
    - [x] Add a comment to the issue:
```
Hi @[REPLACE WITH AUTHOR]
Based on the `feature: feature branch` label, this issue should target a feature branch.  Please consult the instructions on [working off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
```
- [x] Trigger: On event `issues`: activity `unlabeled` - if the label `feature: feature branch` is removed
   - [x] Hide (as "outdated") the comment described above

### Checks

- [x] When the `feature: feature branch` label is added during issue creation, the comment is added
- [x] When the `feature: feature branch` label is applied after issue creation, the comment is added
- [x] When a **different label** is added during issue creation, the additional text is **not** added.
- [x] When the `feature: feature branch` label is removed, the comment is hidden
- [x] When a **different label** is removed, the comment is **not** hidden

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)
Bonnie test text to remove
Bonnie second test

### PR DESCRIPTION
**Pull request by arcan9**
Fixes #1940 

### What changes did you make and why did you make them ?

  - Per the instructions of #1940 I added a new job under the "Issue Trigger" GitHub action found in `/.github/workflows/issue-trigger.yml`
  - This job will append new additional text when an issue is created AND labeled "Feature Branch"
  -  Then I created a script ( `./github-actions/trigger-issue/append-top-comment.js` ) that contains the appended text and will only run if certain conditions are met (see the aformentioned `yml` file). 
  - I'm using the API described in this comment: https://github.com/hackforla/website/issues/1940#issuecomment-901350940
  - I created all that's required including the Github Token/Secret (I followed the instructions [here](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board)).
  
**Testing in my own repo:** 

- I created a secret token
- I added that secret to the `yml` and `js` files
- I opened an issue and labeled it `Feature Branch` and `Feature: Feature Branch` to see which one of these would trigger the job
- Unfortunately, nothing happens

I feel like I've done everything I could think of and I don't know what the problem is. Would appreciate help!

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by mjshelton12** [comment]
Updated:

A job interview came up so I don't have the time on a weekday to dedicate to reviewing a large issue that I thought I would. I should still be able to tackle this weekend.

Availability: Sat/Sun sporadically all day
ETA: Sunday 3/30/23 by end of day

**Comment by bootcamp-brian** [comment]
Availability: Weekdays this week after 5pm
ETA: By end of week

**Comment by mjshelton12** [comment]
Reading through this, it looks like you are in need of help/suggestions rather than being done with this issue as the actions you are trying to create aren't working in your repo - is that correct?

If so, perhaps a better way to get help is to close this PR and move your issue into the Questions/In Review column on the project board so Dev Leads can take a look or folks can look at it during a future meeting.

Let me know if I'm reading this wrong and it really looks like you have done excellent work so far!

**Comment by bootcamp-brian** [comment]
@arcan9 I think marking the issue itself with the help wanted label and placing it in the Questions/In Review column like MJ mentioned would give it better visibility on the project board. That being said, it looks like you've got a good start at working out a complicated issue and I'd be interested in trying to help work out the bugs if you'd like. I sent you a message on Slack when you get a chance.

**Comment by arcan9** [comment]
@mjshelton12 @bootcamp-brian Hey, all! Due to personal life stuff, I've decided to close this PR and unassign myself from the issue altogether. I'll be on a break, but I truly appreciate your help. Best regards.

**Comment by t-will-gillis** [comment]
PR is closed without merging. Moving to "IGNORE PRs closed without being merged"

**Pull request closed without merging**
