### PR TITLE
Update codeql.yml to exclude YAML front-matter and Liquid code

### LINKED ISSUE #6548: Update codeql.yml to exclude YAML front-matter and Liquid code
### Overview

Many of our Javascript and HTML code files cannot be scanned by CodeQL as-is because they contain non-JS Liquid code `{% ... %}` or YAML front matter `--- ... ---`, which cause syntax errors. We need to try and resolve these errors without removing all non-JS code.

### Details

The error message "Could not process some files due to syntax errors" indicates that these "syntax errors" may prevent CodeQL from scanning the files below (see issue #5234 for details).

* `hamburger-nav.js`: YAML front-matter with a title
* `toolkit.js`: 1 line of Liquid, empty YAML front-matter
* `wins.js` : 2 lines (Liquid), empty YAML front-matter
* `project.js` : 2 lines (Liquid), empty YAML front-matter
* `about.js`: for loop (Liquid), empty YAML front-matter
* `current-project.js`: 2 lines + for loop (Liquid), empty YAML front-matter
* Separately, we have observed problems with CodeQL scanning of HTML with embedded liquid statements - see #6485

<details>
<summary>Screenshot: CodeQL error message</summary>

CodeQL error message 1

</details>

Simply deleting the Liquid lines would break the site (and CodeQL raised those errors accordingly in testing), so an alternative, holistic solution is required.

### Action Items
- [x] Review the Possible Solutions content under Resources
- [ ] Implement a solution that will exclude YAML front-matter and Liquid code from CodeQL scans on .js and .html files.
- [ ] Thoroughly test your changes and ensure the codeql.yml file runs as expected.  If it does not run as expected, detail your testing in a comment.  

### Testing

- [ ] Test your solution by running the `.codeql-scan-job.yml` workflow. 
- [ ] You'll have to figure out a way to confirm that CodeQL was able to scan the files listed above without scanning the YAML front-matter or Liquid code and without throwing the error.

### Resources/Instructions

- This issue resulted from #6378
- [Hack for LA's GitHub Actions Wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- https://github.com/hackforla/website/issues/5234#issuecomment-1949927685

#### Possible Solutions
**Here are two possible solutions (in order of preference) to this problem.**  Please use your best judgment, these are only recommendations. 

#### Option 1 
This approach is preferred because it is 
- more generic and reusable
- compatible with using a CodeQL for VS Code extension (See [Setting up CodeQL in Visual Studio](https://codeql.github.com/docs/codeql-for-visual-studio-code/setting-up-codeql-in-visual-studio-code/))
<details><summary>Define a new CodeQL query file that excludes Liquid and YAML patterns within JavaScript files.
</summary>
<p>

Create a file named exclude-patterns.ql
  
```
import javascript

from File file
where (file.getExtension() = "js" or file.getExtension() = "html")
  and not file.getCode().matches(".*\\{%.*%\\}.*") // Exclude Liquid code
  and not file.getCode().matches(".*---.*")        // Exclude YAML front matter
select file
```
    
Then modify codeql-scan-job.yml file to use the new query file for analysis. Update the queries section in the Initialize CodeQL step to include the new query file:
    
```
# On codeql-scan-job.yml file:

- name: Initialize CodeQL
     uses: github/codeql-action/init@v3
     with:
       languages: ${{ matrix.language }}
       queries: path/to/exclude-patterns.ql, security-and-quality
```

</p>
</details> 

#### Option 2
<details><summary>Exclude liquid code and YAML front matter patterns from the CodeQL analysis within `codeql-scan-job.yml`</summary>
<p>

```
    # On codeql-scan-job.yml file:
    
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3
          with:
            languages: javascript
            queries: security-and-quality
            # Exclude Liquid and YAML code within JavaScript files
            exclude: |
              path: "**/*.{js,html}"
              patterns:
                - pattern: |
                    // Start of Liquid code
                    {% if variable %}
                    // Liquid code here
                    {% endif %}
                    // End of Liquid code
                - pattern: |
                    // Start of YAML front matter
                    ---
                    # YAML front matter here
                    ---
                    // End of YAML front matter
```

</p>
</details>

### PR DESCRIPTION
**Pull request by luisitocanlas**
Fixes #6548

### What changes did you make?
  - added `./codeql-queries/exclude-patterns.ql` following the suggestion solution option 1, slightly modifying it.
  - added the path of `exclude-patterns.ql` to the queries at line 48 in `./.github/workflows/codeql-scan-job.yml`

### Why did you make the changes (we will use this info to test)?
  - per issue #6548: Javascript and HTML code files cannot be scanned by CodeQL as-is because they contain non-JS Liquid code or YAML front matter, which causes syntax errors.

### Additional info:
  - I tried to figure out a way to see if the CodeQL was able to scan. Below is what I ended up doing:
      - On my forked repository, I run the CodeQL Scan workflow from my branch `update-codeql-6548` with the `exclude-pattern.ql` inside `codeql-scan-job.yml`. The workflow was able to run without throwing any errors.
      - As for verifying if CodeQL was able to scan the files, I did the following steps:
          - Go to the Actions tab and click on the CodeQL Scan workflow.
          - Click on the completed job.
          - Open the Perform CodeQL Analysis log.
          - Look for the search logs and type in the js files that has either Liquid code or YAML front matter (ex. hamburger-nav.js)
          - Confirm if there are no errors associated with the files.
          - Additional step would be to look at the Security tab of the repository and clicking on the `view alerts` on the `Code scanning alerts` and see if there are any alerts thrown by the scan.

### CODE REVIEW

**Comment by dcotelessa** [comment]
Great work!
- Verified the CodeQL scan results to not include the files mentioned (`hamburger-nav.js`)
- No Code scanning alerts related to these changes.
- Addition Info was helpful in testing.

**Review by dcotelessa — DISMISSED** [review]

**Comment by t-will-gillis** [comment]
available 7/7
eta: 7/7 eod

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @luisitocanlas Thanks for taking on this issue, and good work so far. 

- I checked out your branch locally, pushed it to my desktop, and triggered "CodeQL Scan" through a `workflow_dispatch`. Unfortunately, when I ran CodeQL on your branch, it generated nearly the same "Security Alerts" as currently on the HfLA main branch. That is, the code edits do not appear to change the "Security alert" results or prevent the "Syntax error(s)" due to YAML front matter or Liquid code.  [Example alert](https://github.com/t-will-gillis/website/security/code-scanning/10) Let me know if you think I am missing something here.

  <details>
  Screenshot 2024-07-07 215331
  
  </details>  
  <details>
  
  Screenshot 2024-07-07 215452
  
  
  </details>  
- Side note: if this route works, I would like to discuss with the team about where the `exclude-patterns.ql` file is located. I believe it should be in a sub-directory within `github-actions`, possibly `github-actions/code-ql/` (or similar) rather than as current.
 
 Thank you again for working on this, and again if you think I am missing something let me know!

**Comment by luisitocanlas** [comment]
Hi @t-will-gillis,

I rerun the CodeQL workflow on my branch, this time the errors are back under the `Perform CodeQL Analysis` compared to when I first run the workflow.

<details>
<summary>Screenshot of errors</summary>

image
</details>

I'll redo the `exclude-patterns.ql` and try to make it work. If you have any suggestions for this problem, please let me know.

I also agree that the file should be in a sub-directory in `github-actions` instead of its current location. Just let me know where and what should I name the sub-directory.

Thank you!

**Comment by t-will-gillis** [comment]
Hi @luisitocanlas thanks for slogging through this. 

To answer the second question, `github-actions/code-ql/` or similar works for me. To answer your first question, I would say to try the approaches mentioned in the original issue and anything else you might think of, and keep notes. If you do not find a solution, I think it is reasonable to say this and to give a brief summary of what you tried and what results you saw.

**Comment by luisitocanlas** [comment]
Hi @t-will-gillis,

I moved the `exclude-patterns.ql` to `./github-actions/code-ql/`.

I also tried something different using predicates inside `exclude-patterns.ql`. I waited a day before running the CodeQL workflow since last time I ran it right after pushing my updates there were no errors but after a while there were errors again.

So far, I don't see any errors under `Perform CodeQL Analysis`. 

For the `Syntax error` under `Security Alerts`, does it take time for it to be removed or appear there?

The screenshot below says that the error appeared on the branch on Jun 13.
<details>
<summary>Screenshot</summary>

image
</details>

Thank you again!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @luisitocanlas - I copied your branch and made sure that no "Security" alerts were showing, and then I ran "codeql-scan-job" manually. The result is that CodeQL found 16 alerts, including the same 7 "Could not process some files due to syntax errors".
<details>
Screenshot 2024-07-22 154757

</details>

I could be wrong in interpreting this but I believe that CodeQL is still flagging the Liquid syntax as ***new*** errors, that is not just re-stating the errors it found on previous scans. 

Comparing your scan job with the one I ran on my repo, I can see that your job did not find errors but that mine did. I don't know why that would be the case. Have you set up "Security" on your repo? Just curious....

**Comment by t-will-gillis** [comment]
@luisitocanlas Also want to reiterate:
> I think it is reasonable to say that you did not find a solution and to give a brief summary of what you tried and what results you saw.

**Comment by t-will-gillis** [comment]
Hey @luisitocanlas Checking in with you to see your thoughts about this issue- are you still working on it? Last messaging I said that I believe CodeQL is still flagging the Liquid syntax, however if you believe your changes are correct we/you can ask others to review this PR as well.

Please let us know how you would like to proceed-

**Comment by t-will-gillis** [comment]
Hi @luisitocanlas I just noticed that you unassigned from #6548 and left some notes there- thank you. I will discuss this issue with Bonnie and Roslyn to see how we want to proceed, so we may ask for your thoughts too. 

But again, thanks for taking on this likely frustrating issue.

**Pull request closed without merging**
