### PR TITLE
updated CONTRIBUTING.md 2.1

### LINKED ISSUE #6375: Update CONTRIBUTING.md 2.1 Hack for LA contributor expectations
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to update Section 2.1 of CONTRIBUTING.md to accurately describe Hack for LA contributor expectations

### Action Items
- [x] Browse to [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) and open for editing (click the pencil icon with tooltip "Edit this file")
- [x] Locate Section 2.1 and replace
```
In order to join [another project within Hack for LA](https://www.hackforla.org/projects/) or work on a `Complexity: Small`/`Complexity: Medium`/`Complexity: Large` label issue within this repo, you need to complete the following:
```
with
```
In order to work on a `Complexity: Small`/`Complexity: Medium`/`Complexity: Large` label issue within this repo, you need to complete the following:
```
- [x] Content will be added at the end of Section 2.1.  Replace:
```
<sub>[Back to Table of Contents](#table-of-contents)</sub>
```
with 
```
Prior to joining [another project within Hack for LA](https://www.hackforla.org/projects/), developers should gain the following experience:
* Setting up your local environment from a CONTRIBUTING file
* Completing the above series of issues at least up to `Complexity: Large` 
* Resolving Merge Conflicts
* Reviewing other people's Pull Requests
* Create or improve documentation for other developers
* Mentor other developers
* Create new issues

In addition, backend engineers should complete issues that provide experience with the following:
* API requests
* Cron Job Scripting
* CRUD operations

<sub>[Back to Table of Contents](#table-of-contents)</sub>
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

### PR DESCRIPTION
**Pull request by aidanwsimmons**
Fixes #6375

### What changes did you make?
  - added expectations for developers prior to joining another Hack for LA project

### Why did you make the changes (we will use this info to test)?
  - updated CONTRIBUTING.md section 2.1 to accurately describe Hack for LA contributor expectations

  For Reviewers: Do not review changes locally, rather, review changes at 
  https://github.com/aidanwsimmons/website/blob/update-contributing.md-2.1-6375/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
  <summary>Visuals before changes are applied</summary>

   image

</details>

<details>
  <summary>Visuals after changes are applied</summary>

  
  image

  image

</details>

### CODE REVIEW

**Review by elliot-d-kim — APPROVED** [review]
Hey Aidan,
- Branches and naming was done properly
- Issue is linked
- Code looks clean and accurate

Just some feedback for your summary:
- Concisely describe your changes rather than include all the text that was changed (especially when the change is not just one line)
- To demonstrate your changes to CONTRIBUTING in their entirety, I suggest using screenshots instead
- Also, don't forget to mention the initial motivation for these changes!

Here is an example PR that does all these: [link](https://github.com/hackforla/website/pull/2285).

Otherwise, these changes look good to me! Approved ✅

**Review by heejung-hong — COMMENTED** [review]
Hello @aidanwsimmons,
 
Per Elliot's suggestion, can you kindly update your responses to the following sections?

- What changes did you make?
  - Concise sentence to indicate the changes.
- Why did you make the changes?
  - This question was not answered.  Please refer to the Overview section of assigned issue 6375.
- Add Screenshots of Proposed Changes Of The Website?
  - Screenshots will be needed for the reviewer to compare and verify the changes indicated.

I will approve the issue, once the three changes have been made.

Thank you

**Comment by aidanwsimmons** [comment]
@heejung-hong @elliot-d-kim 
Changes made to review comment as requested! Let me know if further changes are required. Thanks!

**Review by heejung-hong — APPROVED** [review]
Great work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, tablet, and mobile view), Firefox, and Safari browser.

**Pull request merged**
