### PR TITLE
Escape visible projects object in current-projects.js to prevent Liquid injections

### LINKED ISSUE #3257: Refactor code in current-projects.js to avoid Liquid injection vulnerability
### Overview

As a developer, I want to keep the sites I work on secure by escaping Liquid injection vulnerabilities so that site remains secure.

### Action Items
- [x] Read this [audit of the HfLA website's Liquid injection vulnerabilities](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#) for a better understanding of the current state of the site's security. The purpose of this issue is to take extra precautions when loading some internal JSON data to prevent scripting problems/attacks from within the organization, like when code is edited.
- [x] In [assets/js/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js):
   - [x] Find the line of Liquid that creates `visible_projects` on line 63.
   - [x] Escape the `visible_projects` object using `JSON.parse(decodeURIComponent())` and assign it to a variable. You can use lines 62 and 64 (the `projects` object) as a reference
   - [x] Make sure that the object is being called correctly in lines 101, 104, 107, and 110. These lines will probably need to change to something like in lines 69-78 for the `projects` object
- [x] Check that there are no errors and that the [Projects page](https://www.hackforla.org/projects/) loads as expected
- [x] Use the code from pages 3 and 4 of the [audit of the HfLA website's Liquid injection vulnerabilities](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#) to test that HTML insertion in a .md file will not affect the website
- [x] Create a pull request for this issue. There should be no visible changes to the site

### Resources/Instructions
[Hack for LA Liquid Injection Vulnerabilities Audit](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#)
Code file to be edited: [assets/js/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
[Liquid guide](https://shopify.github.io/liquid/basics/introduction/)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #3257 

### What changes did you make and why did you make them ?

In `assets/js/current-projects.js`
  - Escaped the `visible_projects` object with `JSON.parse(decodeURIComponent())`
  - Rewrote lines `78-120` to work with the new `visible_projects` object
  - Sanitizing the `visible_projects` object prevents possible Liquid injection attacks as described in the [Hack for LA Liquid Injection Vulnerabilities Audit](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Only changed code to sanitize inputs. No visual changes to the site.

### CODE REVIEW

**Comment by lilyarj** [comment]
Availability: 2hrs
ETA: 6/28 or 6/29

**Review by lilyarj — DISMISSED** [review]
Everything looks good! Website runs as normal

**Comment by blulady** [comment]
Availability: 2 hours
ETA: 6.28.22

**Comment by BeckettOBrien** [comment]
@blulady Hello! Do you still have time to review this pull request today, and if you do, would you be able to provide a new ETA? If not, I can find someone else to review it. Thank you!

**Comment by blulady** [comment]
> @blulady Hello! Do you still have time to review this pull request today, and if you do, would you be able to provide a new ETA? If not, I can find someone else to review it. Thank you!

Thanks for the reminder. Looking at it now.

**Review by blulady — DISMISSED** [review]
The branches are correct. There is a correct linked issue. The object that created the issue looks like it has been escaped on line 65. Lines 101, 104, 107, and 110 have been deleted.  It looks good when I throw it up on my local (links work, card looks good)  but I am unable to test if XSS is still occurring.

**Comment by BeckettOBrien** [comment]
Hmm, I just tried doing an injection earlier on these changes and it didn't work, but I just tried it again and it worked. Would someone else be able to take a look and see if it works for them or not?

**Comment by BeckettOBrien** [comment]
I think I figured it out. I got confused because the data wasn't sanitized on the main projects page and the browser's dev tools showed that it had injected a script tag, but the alert didn't show up so I thought I wasn't testing the right page. The [Hack for LA Liquid Injection Vulnerabilities Audit](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#) used 311 Data's individual page as an example so I thought that I was trying to fix that but it isn't handled in `assets/js/current-projects.js`, so I think this PR is fine.

**Comment by Wny-Duong** [comment]
> I think I figured it out. I got confused because the data wasn't sanitized on the main projects page and the browser's dev tools showed that it had injected a script tag, but the alert didn't show up so I thought I wasn't testing the right page. The [Hack for LA Liquid Injection Vulnerabilities Audit](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#) used 311 Data's individual page as an example so I thought that I was trying to fix that but it isn't handled in `assets/js/current-projects.js`, so I think this PR is fine.

I'm a bit confused here since it looked like the original issue involved making sure that liquid injections in an HTML file wouldn't affect the site. When I was testing just to make sure before merging, it looks like the test injection code I'm copying from the drive link into a project readme (testing with the 311 example case) still causes the injection issue if you try to go on the main project page based on that readme file. What exactly is being fixed regarding the liquid injections through the code refactoring?

I'm seeing stuff like this pop up as a result of the google doc's test code:
image

**Comment by BeckettOBrien** [comment]
Sorry, that's what I was confused about too, but I did a bad job of explaining what I think happened, so I'll try again. This PR is to fix issue #3257, which only requests changes to `assets/js/current-projects.js`, which only has an effect on the main projects page ([hackforla.org/projects](https://hackforla.org/projects) but the [document linked in the issue](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#) shows the vulnerability being tested on 311 Data's specific project page ([hackforla.org/projects/311-data](https://hackforla.org/projects/311-data). The weird thing is that a liquid injection attack only half-works on the main projects page, but fully works on the individual pages. Before this commit, adding the injection code to `_projects/311-data.md` resulted in a script tag successfully being injected into the 311-data card on the main projects page, but it wouldn't run the alert message:
image
After this patch, the injection is escaped on the project card on the main page but not on the project page:
image
I think I could apply this same patch to the individual projects' pages but it would technically be out of scope for this PR. Do you think it would be better to just add another commit to this PR that fixes it or do you think it would be better to make another issue for the individual project pages and fix it in a seperate PR?
(Also, I noticed that just using `JSON.parse(decodeURIComponent())` wasn't enough to escape the HTML characters so I changed it to `JSON.parse(decodeURIComponent().replace(/</g, '&lt;'))` but I forgot to include it in my last commit, so I'll add that now.)

**Review by Wny-Duong — APPROVED** [review]
@BeckettOBrien Got it. Thank you so much for clarifying! Since you have addressed all the action items from the original issue, I'll just approve this PR then. Personally, I feel that the Liquid injection vulnerability still existing in the site through the project-specific pages is kind of a grey area that should be addressed with another issue being opened up at some point in the future.  That aside, good work on the issue!

@tamara-snyder Any thoughts on this by the way?

**Review by blulady — APPROVED** [review]
Thanks for the explanation.

**Comment by ExperimentsInHonesty** [comment]
@BeckettOBrien @Wny-Duong @blulady @lilyarj highly probable that this pr broke the program areas and languages on the home page and projects page.  If you go there, you can see that there is no data in the program area filter and program area and language do not show up on the project cards, although they do show up if you click through to the project pages.  https://www.hackforla.org/projects/

@BeckettOBrien if you are around today, I can show you how to test this.  If not, you can try the following
1. Go to GitHub where the file is located: https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js
2. Click on History on the page (see image)
image
3. Go to the commit prior to yours (see image)
image
4. Click on the _View at this point in history_ icon
image
5. Copy the file contents into your local version in VS Code, then look at it in local host.  Does that solve the problem?  Did the Program Areas come back?  
6. If yes, let us know so that we can revert this commit.

**Comment by blulady** [comment]
@ExperimentsInHonesty I would love to see how to test for this. Let me know if you are going to explain it later on.

**Comment by BeckettOBrien** [comment]
I think the issue is caused because the new commit uses `JSON.parse` to turn the liquid project object directly into a javascript object, whereas the old commit did it manually and ended up renaming the `program-area` property to `programAreas`:
```
{%- if project.program-area -%},
"programAreas": {{ project.program-area | jsonify }}
{%- endif -%}
```

**Comment by BeckettOBrien** [comment]
I assume whoever did it this way did it because JavaScript variables can't have hyphens in them, so the `program-areas` field is the only one that was renamed and we should be able to fix this issue by replacing `projects.programAreas` with `projects['program-areas']`. Another option would be to rename the `program-areas` field to `programAreas` in each project file, but that seems to me like a big restructuring decision beyond the scope of this issue

**Comment by BeckettOBrien** [comment]
@Wny-Duong would you be able to revert this so I can fix the issue and open a new PR? I can reopen the original issue and mark it as in-progress again.

**Pull request merged**
