### PR TITLE
Updated spell checker via cspell.json by adding 'Inclusivity'

### LINKED ISSUE #5686: Update cspell.json with false positive term "Inclusivity"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to update the Code Spell Checker configuration file with false positive terms so that they are no longer marked as errors. 

### Action Items
- [x] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file `cspell.json`
- [x] Replace the line
```
  "words": [
```
with
```
  "words": [
      "Inclusivity",
```
- [x] Save `cspell.json` and then test the change by opening `_includes/about-page/about-card-platform.html` and confirming that no Code Spell Checker errors/messages are displayed.  
- [x] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- This issue was created as part of #5312

### PR DESCRIPTION
**Pull request by colin-macrae**
Fixes #5686

### What changes did you make?
  - Updated spell checker by adding "Inclusivity" to cspell.json

### Why did you make the changes (we will use this info to test)?
  - To keep spell checker up-to-date by adding needed false positive terms, e.g. "Inclusivity" 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No applicable images as there are no visual changes to website

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hi @colin-macrae FYI it looks like you may have added the "Fixes #5686" line after the PR was created because many of the automations did not run. One of the automations copies the labels from the original issue to the PR- since that did not run please copy the labels manually.

Also, there are other, concurrent issues to edit `cspell.json`- one has already gone through which is causing a merge conflict. This just means that the current version of the file is ahead of the version on your branch. You can fix this by selecting "Resolve conflicts", editing the file to include both your edit and the addition of `"Undebate",` (added by 5957), then "Mark as resolved".

**Comment by t-will-gillis** [comment]
Hey @colin-macrae and @naveenmallemala5 I will leave this message on both of your PRs. Since you are both waiting for your PRs to be reviewed- you could consider reviewing each other's in the meantime and then when they are ready one of us will be available to merge them. Your respective PRs are #6006 and #6004.

**Comment by colin-macrae** [comment]
> Hi @colin-macrae FYI it looks like you may have added the "Fixes #5686" line after the PR was created because many of the automations did not run. One of the automations copies the labels from the original issue to the PR- since that did not run please copy the labels manually.
> 
> Also, there are other, concurrent issues to edit `cspell.json`- one has already gone through which is causing a merge conflict. This just means that the current version of the file is ahead of the version on your branch. You can fix this by selecting "Resolve conflicts", editing the file to include both your edit and the addition of `"Undebate",` (added by 5957), then "Mark as resolved".

Thanks @t-will-gillis for explaining that.  Noted for the future.  Exact labels copied & pasted below for easy comparison.  

image

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 12/21

**Comment by freaky4wrld** [comment]
Hey @colin-macrae your PR has merge conflicts as mentioned by @t-will-gillis, please resolve it so that further reviewing can be done, you just have to update your version of `cspell.json` file. One thing you can do is to try pulling from the origin branch i.e. `git pull origin`, then add `Inclusivity` in the array and I guess you are good to go.

Ping me once the changes are made and I'll review it

**Comment by colin-macrae** [comment]
> Hey @colin-macrae your PR has merge conflicts as mentioned by @t-will-gillis, please resolve it so that further reviewing can be done, you just have to update your version of `cspell.json` file. One thing you can do is to try pulling from the origin branch i.e. `git pull origin`, then add `Inclusivity` in the array and I guess you are good to go.
> 
> Ping me once the changes are made and I'll review it

Thank you @freaky4wrld!  I resolved the conflicts per the method the initial reviewer suggested so that I could learn that method of doing so.  Please review at your convennience.

**Comment by freaky4wrld** [comment]
@colin-macrae though you managed to resolve the merge conflicts, I can see that your version of code is adding two elements into the array 'collabathon' and  `Inclusivity` just to let you know that the element 'collabathon' is updated to 'Collabathon'. So can you please remove 'collabathon' and I can approve this PR. Thanks for making changes so quickly. Do ping me once you are done :)

**Comment by colin-macrae** [comment]
> @colin-macrae though you managed to resolve the merge conflicts, I can see that your version of code is adding two elements into the array 'collabathon' and `Inclusivity` just to let you know that the element 'collabathon' is updated to 'Collabathon'. So can you please remove 'collabathon' and I can approve this PR. Thanks for making changes so quickly. Do ping me once you are done :)

Thanks @t-will-gillis .  The requested changes have been made.  This is my first merge conflict so I'd like to make sure I understand for future issues.  When I did the initial merge conflict resolution yesterday, did I commit the file with BOTH `collabathon,` and `Collabathon,` visible to me?  That is, did I simply miss it and not see it on my screen while resolving it in GitHub?  Or did something else happen?

Second question.  Is there a benefit to pulling from main and then updating it locally, instead of updating it on GitHub? 

Many thanks if you're able to educate me a bit here.

**Comment by t-will-gillis** [comment]
Hey @colin-macrae - for the first question, the commit shows both `collabathon` and `Collabathon` so you probably just missed it (it happens!): https://github.com/hackforla/website/pull/6006/commits/2327ea7ed699d39dad4de5e3bce3e21408bb8481

For the second question, if the conflict involved many sections or multiple files it seems that updating locally would be easier and have less of a chance of missing something. Whichever way works better for you.

**Comment by colin-macrae** [comment]
> Hey @colin-macrae - for the first question, the commit shows both `collabathon` and `Collabathon` so you probably just missed it (it happens!): [2327ea7](https://github.com/hackforla/website/commit/2327ea7ed699d39dad4de5e3bce3e21408bb8481)
> 
> For the second question, if the conflict involved many sections or multiple files it seems that updating locally would be easier and have less of a chance of missing something. Whichever way works better for you.

Appreciate the answers, @t-will-gillis.  Are we good now?  I just scrolled up, changed the file in "files changed", accordingly, and committed.

**Review by t-will-gillis — APPROVED** [review]
Hi @colin-macrae Great job and thanks for making the edits, fixing the merge conflict, and working with @freaky4wrld and myself! The from/to branches are good, the issue is linked, you have described what changes were made and why, and the edit is clean.  
Thanks for working on this!

**Review by freaky4wrld — APPROVED** [review]
Great work there @colin-macrae, everything looks great and ready to merge.... kudos to your effort!! PR approved 👌

**Pull request merged**
