### PR TITLE
Update project profile 5809

### LINKED ISSUE #5809: Update Project Profile: Lucky Parking (Add Partner: Atwater Village)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `partner` variable and change the following:

**From:**
```
partner: Department of Neighborhood Empowerment
```
**To:**
```
partner: Department of Neighborhood Empowerment, Atwater Village
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909 and #5098
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by jtw007**
Fixes #5809 

### What changes did you make?
  - updated partners variable to include Atwater Village 

### Why did you make the changes (we will use this info to test)?
  - to keep information up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2024-01-25 at 14 30 51

Screen Shot 2024-01-25 at 14 31 03

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2024-01-25 at 14 31 33
Screen Shot 2024-01-25 at 14 31 41

</details>

### CODE REVIEW

**Comment by iancooperman** [comment]
ETA: EoD 1/25/2024
Availability: 1/25 - After 8pm

**Comment by iancooperman** [comment]
The following check out:
- Correctly linked issue and branch.
- Atwater Village added to partners variable.
- Changes are reflected in the browser and in different viewports.
- No extraneous changes.

Great job, @jtw007! I approve.

**Review by iancooperman — APPROVED** [review]
The following check out:
- Correctly linked issue and branch.
- Atwater Village added to partners variable.
- Changes are reflected in the browser and in different viewports.
- No extraneous changes.

Great job, @jtw007! I approve.

**Review by heejung-hong — APPROVED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in developer mode on Chrome (desktop, iPad, and iPhone view), Firefox, and Safari browser.

**Comment by jphamtv** [comment]
Nice work, @jtw007. Just a reminder to complete the remaining action items in the issue, now that the PR is merged. Thanks!

**Pull request merged**
