### PR TITLE
Update profile image alt text in wins page

### LINKED ISSUE #4112: Enhance wins JavaScript to assign alt text to contributor photo
### Overview

To comply with Web Content Accessibility Guidelines (WCAG), we need to ensure that image alt text on the Wins page is meaningful and appropriate for each image. This issue addresses the need for alt text on the GitHub profile photo in the Wins cards, which are generated using JavaScript.

### Action Items

- [x] Understand the role of these components of the wins page:
  - [x] The main Wins web page: [wins.html](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html), which uses Liquid to include the template for each win card: [wins-card-template.html](https://github.com/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html)
  - [x] The JavaScript code [wins js](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js) running in the Wins web page.pro
- [x]  In [wins-card-template.html](https://github.com/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html), find the img element with class 'wins-card-profile-img', and add an empty alt attribute (alt='').
- [x] In [wins.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js), search for the text '.wins-card-profile-img' in order to locate the line of code which sets the "src" attribute for the GitHub profile photo. Add code to set the "alt" attribute of the image equal to "photo of name" where name is the name of the contributor. For example, the alt text for Mary Smith's photo should be "photograph of Mary Smith".
- [x] View the wins page to test the code at mobile, tablet and full-screen widths. Also also follow the "See More" page to check the alt tag on the modal overlay.

### Resources/Instructions

[Wins webpage](https://hackforla.org/wins/)
[wins.html](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html)
[wins js](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
[wins-card-template.html](https://github.com/hackforla/website/blob/gh-pages/_includes/wins-page/wins-card-template.html)
This issue was created as a follow-up to https://github.com/hackforla/website/issues/2569. See that issue for accessibility resources.

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #4112

### What changes did you make and why did you make them ?

  - Update wins.js to add new alt tag to img element that describes the image in a more meaningful/appropriate way. 
  - In this case, each photo will have the alt tag: "photograph of <insert contributor's name>"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by richardmundyiii** [comment]
Availability: M-F 6am - 8am
ETA: EOD 3/17/2023

**Review by richardmundyiii — APPROVED** [review]
@Jaretzbalba Great work on completing this Medium Complexity issue. Nice work on documenting the issue and what you did to fix said issue. There were no images needed and you noted that as well. Good job!

**Comment by roslynwythe** [comment]
Availability: 10 - midnight 3/19
ETA EOD 3/19

**Review by roslynwythe — APPROVED** [review]
Great work @Jaretzbalba.  The branches are setup correctly, the PR is descriptive, and you have addressed all the of the required code changes to handle both mobile and larger screen sizes, in a clean and effective manner.  The page checks out fine in the browser at all screen sizes.

**Pull request merged**
