### PR TITLE
Create dependabot.yml

### LINKED ISSUE #3843: Create dependabot.yml file for dependabot to create pull requests
### Overview

GH Dependabot has been enabled to issue alerts for vulnerabilities and security. Therefore we need a configuration file, dependabot.yml, to create pull requests so that we maintain up to date security in our repo.

### Action Items

- [x] Read [configure dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [x] Read #3598 to understand HfLA's decision for implementing dependabot
  - [x] See associated [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- [x] Create a dependabot.yml file in the [.github](https://github.com/hackforla/website/tree/gh-pages/.github) and configure the file as per the instructions given in 1st link

### Resources/Instructions

- [Enabling Dependabot Version Updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [Configuration Options for Dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- ER for Decision Record: https://github.com/hackforla/website/issues/3598
- [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- See previous work done here: #4102

### PR DESCRIPTION
**Pull request by one2code**
Fixes #3843

### What changes did you make and why did you make them ?

Created a dependabot configuration file to update out-of-date packages and Github Actions in the HackforLA website repository.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

N/A

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Avail: sunday, monday 6pm-11
ETA: monday 11pm.

**Comment by angieyan** [comment]
Availability: W-F, Sun 9AM - 11AM
ETA: EOD 5/21/23

**Review by steven-positive-tran — CHANGES_REQUESTED** [review]
I've noticed the branch is in the main upstream hackforla git instead of your fork. I'll test the changes to see if it works on my machine once I pull it but this is something to note and fix.

**Comment by steven-positive-tran** [comment]
I'm confused on the intended behavior of this
image

For npm it can't find package.json so it does not evalulate.
For docker it can't find dockerfile so it does not evalulate.
For issues it did create 5 pull request on my fork which is the max and I do have the emails and pr's for it but I'm wondering if it should be able to do npm and docker as well.

**Comment by one2code** [comment]
The npm and docker was part of the testing (Github Actions initially would not fire). I forgot to remove them for the final update. I will push the changes soon. As for the main upstream configuration, that was due to the dependabot config file being unable to operate on the original fork. I attempted to resolve this issue with Sarah, and even contacted the Github Dependabot engineering team for further support. Unfortunately, the only working solution was to create another clone-since website was already forked-and later rename it to website and push the PR via upstream.

**Review by angieyan — COMMENTED** [review]
@one2code as @steven-positive-tran mentioned, it is not in the correct branch. Please change the commit branch from your repo ("one2code:create-dependabot.yml-#3843") into "hackforla:gh-pages".

**Review by blulady — APPROVED** [review]

**Pull request closed without merging**
