### PR TITLE
Removes Pratibha Shivanand from the Lucky Parking project page.

### LINKED ISSUE #4909: ER: Update Project Profile: Lucky Parking
### Dependency (Issues that need to be completed in order to close this ER and complete these [action items](https://github.com/hackforla/website/issues/4909#issuecomment-1793873563))
- [x] #5790 
- [x] #5809
- [x] #5791 
- [x] #5796
- [x] #5797 
- [x] #5798
- [x] #5799 
- [x] #5800
- [x] #5801 
- [x] #5802
- [x] #5803
- [x] #5804  
- [x] #5805
- [x] #5806
- [x] #5807 
- [x] #5808
- [x] #5792 

### Project Name

Lucky Parking

### Project Card URL

lucky-parking.md

### Update the Technologies?

YES

### Technologies

- [x] React, TailwindCSS, Mapbox, Node.js, Express, MongoDB, AWS, Markdown

### Update the Partner(s)?

YES

### Partners

- [x] Atwater Village
  - See https://github.com/hackforla/website/issues/4909#issuecomment-1707100068 and #5098 

### Update the Tools?

YES

### Tools

- [x] pnpm, GitHub, Storybook, Google Colab

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Yuting Chu
- [x] Name: Arpita Pandya
- [x] Name: Diedrich Chavarria
- [x] Name: Jodie Chen
- [x] Name: Sijia Pitts
- [x] Name: Yujin Chang
- [x] Name: Sam Sengupta
- [x] Name: David Lam
- [x] Name: Carlos Olivas
- [x] Name: Pratibha Shivanand
- [x] Name: Aletia Trepte
- [x] Name: Yen Phan
- [x] Name: Yao Guan

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Danny Pham
GitHub Handle: dannycpham
Role: Product Manager Lead
Slack Member ID: U041DP398GH

### LINKED ISSUE #5805: Update Project Profile: Lucky Parking (Remove Pratibha Shivanand)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Pratibha Shivanand
    role: Data Scientist
    links:
      slack: 'https://hackforla.slack.com/team/U03SM1LF9HD'
      github: 'https://github.com/pratibhanagesh'
    picture: https://avatars.githubusercontent.com/u/8139348
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column, add a **ready for dev lead** label to it, and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by Pfulcher26**
Fixes #5805 

### What changes did you make?
  - Removed Pratibha Shivanand from the Lucky Parking project detail page. 

### Why did you make the changes (we will use this info to test)?
  - To keep project team member info up to date, as it appears Pratibha has left the project. 
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
Hi @Pfulcher26, it looks like you may have linked the wrong issue to this PR. Can you update the first line to the correct issue number (`5805`)? Thanks!

**Comment by Pfulcher26** [comment]
@kwangric Hi Richard, sorry about that!  It's updated :)

**Comment by MattChau01** [comment]
Availability: Evenings all throughout the week
ETA: EoD Sunday

**Review by MattChau01 — APPROVED** [review]
Hi @Pfulcher26, Thanks for taking up this issue! Just wanted throw in some tips when working on future issues:

- Please check off the boxes that were provided in the original issue as you work on it (Unless the box explicitly says it is for a merge team member). This way the author and your fellow peers know it was worked on.  (#5805)
- In the future, I would suggest putting the correct issue number in your branch. I saw that you listed `4909` in the branch, when the issue you worked on was `5805`.

Other than that, you:
- pushed code to the proper branch: `gh-pages`. ✅ 
- referenced the correct issue #5805. ✅ 
- removed the correct code as referred to in the original issue. ✅  
- provided great screenshots displaying any visual changes. ✅ 

Great work! When you can, please mark off the boxes on the original issue! :)

**Comment by KyleA99** [comment]
Availability: 11/5/23 12 - 5 PM
ETA 11/5/23 EOD

**Review by KyleA99 — APPROVED** [review]
Hi @Pfulcher26 PR reviewed and approved.  Code is correctly changed and visuals look great.  Thank you for taking on this issue!

**Pull request merged**
