### PR TITLE
Updated Technologies list in Project Overview section in Civic Tech Jobs Project Page

### LINKED ISSUE #7515: Update Project Profile: Civic Tech Jobs Update Technologies
### Dependency
- https://github.com/hackforla/website/issues/7314#issuecomment-2371834851

### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/[Insert filename].md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `technologies` variable and change the following:

**From:**
```
technologies: 
  - Django
  - Django REST Framework
  - React
  - Webpack
  - Babel
  - PostgreSQL
  - Docker
  - GitHub Actions
```
**To:**
```
Technologies: 
  - React
  - Express
  - Node.js
  - Docker
  - PostgreSQL
  - Django
  - Figma
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
[^3]: initiating ER:  #7314

### PR DESCRIPTION
**Pull request by floydferrer**
Fixes #7515 

### What changes did you make?
  
  - Updated list of technologies within Project Overview section on Civic Tech Jobs Project page
 
 - Technologies list before changes: 
    - Django
    - Django REST Framework
    - React
    - Webpack
    - Babel
    - PostgreSQL
    - Docker
    - GitHub Actions
  
  - Technologies list after changes:
    - React
    - Express
    - Node.js
    - Docker
    - PostgreSQL
    - Django
    - Figma

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of technologies up to date

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-09-26 201919

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-09-26 201944

</details>

### CODE REVIEW

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: Sept 30

**Comment by FamousHero** [comment]
Availability: 5pm-9pm Mon-Fri
ETA: EOD 9/28

**Comment by codyyjxn** [comment]
Availability: Mon > Fri
ETA: EOD 9/27

**Review by codyyjxn — CHANGES_REQUESTED** [review]
### Things that are good:
- The branch name is good
- The right file was changed `_projects/civic-tech-jobs.md`
- The screenshots are clear and a good bonus. 


### Few things you need to change:  

- [x] Please update the original issue's status from "Prioritized Backlog" to "Work in Progress" under the labels section.
- [x] Make sure to check the boxes in the original issue, indicating each step you completed, following the prompts as required.
- [x] It would be helpful if the title were more descriptive, reflecting the sections you updated.
- [x] The PR comment should also be detailed, specifying where the changes were made.

**Review by codyyjxn — APPROVED** [review]
Great Job ! @floydferrer Thank you for taking on this issue.

**Review by FamousHero — APPROVED** [review]
Hi @floydferrer, Thanks for taking on this issue!

Things you did well:
- branch name is descriptive & has issue number
- PR correctly links to issue
- Description of changes & why are clear
- Screenshots match desired output
- Issues **Action Items** were followed as instructed

Good Job! No reviews needed!

**Comment by terrencejihoonjung** [comment]
Availability: 5pm-9pm PST, Mon-Fri 
ETA: today, 11:59pm PST

**Review by t-will-gillis — APPROVED** [review]
Hi @floydferrer excellent job on your first PR!
- branches look good
- linked to the original issue
- descriptions for what was changed and why are good- fyi in the future you could go with only the first bullet point under "What changes did you make?", but this is fine
- there are appropriate before and after screenshots
- the code changes are clean
The page appears correct and Docker.

Great job and thanks for your contribution!

**Comment by t-will-gillis** [comment]
Hi @terrencejihoonjung oops- I just noticed you assigned yourself after I merged the PR

**Pull request merged**
