### PR TITLE
Updated Project Profile #5459: Removed Johnny Wu

### LINKED ISSUE #5459: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Johnny Wu
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U043KH4FQ1M'
      github: 'https://github.com/Skydodle'
    picture: https://avatars.githubusercontent.com/Skydodle
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by WayneTsai45**
Fixes #5459 

### What changes did you make?
  - Removed Johnny Wu from [Hackforla.org Website project page](https://www.hackforla.org/projects/website)

### Why did you make the changes (we will use this info to test)?
  - The Hackforla.org Website project page needs to be updated so that the project information is up to date.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not scree
<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-09-14 at 3 32 18 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-09-14 at 3 22 20 PM

</details>

### CODE REVIEW

**Comment by tesiahwang** [comment]
Review ETA: 9/15/2023
Availability: flexible

**Review by tesiahwang — APPROVED** [review]
Great job, @WayneTsai45 - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable! One small note:
- When naming your branch, choose something that relates to your issue e.g. "update-website-profile-5459".

**Comment by agutiernc** [comment]
Review ETA: 9/15/2023
Availability: EOD

**Review by agutiernc — APPROVED** [review]
Thanks for contributing, @WayneTsai45!

The following checks out:
- Correct linked issue
- Contributor no longer shows on hackforla's website project page
- Content is rendered in different views
- Before/After screenshots confirm removal

I also agree with @tesiahwang, about naming a branch that is more descriptive. [2.7.b, of contributing.md, has an example](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue).

Good job, @WayneTsai45.

**Pull request merged**
