### PR TITLE
Update project profile

### LINKED ISSUE #6295: Update Project Profile: Add Nikileshwari Prasadh to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Nikileshwari Prasadh
    github-handle: Thinking-Panda
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U04MJA414LU'
      github: 'https://github.com/Thinking-Panda'
    picture: https://avatars.githubusercontent.com/Thinking-Panda
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by KuanHsienYEH**
Fixes #6295 

### What changes did you make?
  added Nikileshwari Prasadh to Website Team
```html
 - name: Nikileshwari Prasadh
    github-handle: Thinking-Panda
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U04MJA414LU'
      github: 'https://github.com/Thinking-Panda'
    picture: https://avatars.githubusercontent.com/Thinking-Panda
```

### Why did you make the changes (we will use this info to test)?
  To resolve #6295  update the project information to be up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
before:
1708128218279@2x

after:
1708128202220@2x

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  02/17/2024
Availability: 12pm - 4pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @KuanHsienYEH! Great job with this pull request.
The branching was done correctly, you linked the issue, and you made the relevant code changes. I am able to confirm in Docker the changes appear correctly.
Just a couple edits:
- In the 'Why did you make the changes' section, instead of linking the issue, give a brief description of why the changes were made. 
- Also provide a screenshot to show a Visual before changes are applied
Thanks!

**Comment by KuanHsienYEH** [comment]
Hi @robertnjenga  
Thanks for advice. I've made the edits as suggested.

**Review by robertnjenga — DISMISSED** [review]
Hi @KuanHsienYEH 
Thank you for making the changes, everything looks good. Great Job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @KuanHsienYEH - Great job on this issue and thanks for working with @robertnjenga- great communication! Your branches are correct, you are linking the original issue, you are describing what changes were made and why, and you are providing before and after screenshots.

I have one request: even though you did not add in the extra line at what is now line 95, could you please remove this anyway? This is outside of your issue's scope, but it will help clean up the file. 

Thanks for your work!

**Comment by KuanHsienYEH** [comment]
Hi @t-will-gillis 

Thank you for the feedback and for acknowledging our efforts on this issue. It was a pleasure working with you.
I've made the requested change and removed the extra line. This should help clean up the file and maintain consistency.

**Review by t-will-gillis — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Thanks @KuanHsienYEH !

**Pull request merged**
