### PR TITLE
Projects page copy with only technology and language filters

### LINKED ISSUE #2502: Create a copy of the project page with only two filters: technology and language
### Dependency
- ~#2488~

### Overview
We need a copy of the project page with only the technology and language filter to ensure that the page filters properly

### Action Items
- [x] Create a new page based off of the current [project page](https://www.hackforla.org/projects/)
    - [x] The new page's permalink should be set to `/projects-check/`
    - [x] The page should only be reachable via permalink
- [x] For the newly created page, update the dropdown filters so there are only two: technologies filter and language filters
    - [x] The technologies filter should filter based on a specific technology
    - [x] The languages filter should filter based on a specific language
    - [x] You may use the ideas of the current existing code: [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [ ] Ensure the new page works, and it should not affect any existing pages on the website

### Resources/Instructions
- [projects page](https://www.hackforla.org/projects/)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)

### PR DESCRIPTION
**Pull request by Wny-Duong**
Fixes #2502

### What changes did you make and why did you make them ?

  - Created a copy of the projects page that is accessible through a `/projects-check/` permalink and is only accessible through permalink. It can't be reached simply by pressing the project button, only through http://localhost:4000/projects-check/ when checking locally.
  - On projects-check, there are only two filters, technologies and languages. They follow the same behavior as the default projects page filters. 
    - Example 1: Selecting multiple technologies in only the technologies filter will increase the number of projects returned, as cards containing any of the selected technologies are shown. 
    - Example 2: Selecting a technology filter and a language filter will restrict the number of projects returned, as it checks only for projects that contain both the specific technology and language.
    - The separated technologies and languages filter contain the same filter items as the combined technologies/languages filter used in the default projects page.
   - Note: The new files added were based off of the current-projects.html, current-projects.js, and projects-page.html files used to generate the current projects page. The html files are identical with changes to the file names referenced to ensure a separate working projects-check page. The projects page is still accessible through `/projects/` and uses the old filters currently used (program areas, languages/tech, status).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA: End of Day on 8/15
Availability: 4 hours

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-08-11

**Comment by Zak234** [comment]
ETA: Aug. 14

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct and visible!! Great job! @Wny-Duong

**Review by Zak234 — COMMENTED** [review]
I may be wrong but it looks like there are 65 combined languages and technologies in the new page and only 62 in the old page.

**Comment by Wny-Duong** [comment]
> I may be wrong but it looks like there are 65 combined languages and technologies in the new page and only 62 in the old page.

I looked into this and you're right, there are 3 more languages that were added because of my changes:
Makefile
Ruby
Svelte

These languages do show up in the project cards for the old projects page, but aren't included in the original combined languages and technologies filter. I'm not too sure why this is and I don't know if this is something that should be fixed since it technically corrects the problem of those languages not showing up in the filter in the first place.

**Comment by Zak234** [comment]
We could probably bring it up during office hours tomorrow

**Comment by Wny-Duong** [comment]
Sounds good to me. I'll see you there.

**Comment by Wny-Duong** [comment]
@Zak234 From the office hours, it looks like the new languages are fine, but there might be a need to make a new issue addressing the fact that the old Projects filters were missing the Makefile, Ruby, and Svelte language filter options since those languages are listed in some of the project cards currently existing on the Projects page.

Just leaving a note here that the changes made found three new languages that weren't previously included under the Projects page Languages/Technologies filter along with some images in case a new issue needs to be created.

Image from the projects-check language filter:
image

Images from the old projects filter:
image

Project cards using Ruby, Svelte, and Makefile on the old projects page included:
Spare
Write for All
Work for LA
BallotNav

**Review by blulady — APPROVED** [review]
Changes look good. I made an issue requesting documentation for this.

**Comment by kathrynsilvaconway** [comment]
Here is the issue @blulady created to request documentation:
#3487

**Review by kathrynsilvaconway — APPROVED** [review]
@Wny-Duong Great work on this issue. The filters on the new page function as expecteda dn everything looks good. We will have to decide what to do about the items that are missing from the current project filters in a separate issue.

**Pull request merged**
