### PR TITLE
updated hardcoded colors with variables - Green

### LINKED ISSUE #2200: Design System Audit: Swap colors with color variables: Greens
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the greens colors so we can use the color variables.

### Action Items

- [ ] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (greens)
- [ ] Replace all instances of the hard-coded colors with the color variables
  - [ ] Make sure to do this carefully, as some changes might break the website
  - [ ] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [ ] If a color variable is unused, delete it from the files noted above.
- [ ] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L24-L29

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  
</details>

### PR DESCRIPTION
**Pull request by geedtd**
Fixes #2200

### What changes did you make and why did you make them ?

Changed hardcoded colors to variables representing the colors

No images needed, no color changes just having variables instead of the hardcoded color

### CODE REVIEW

**Review by Zak234 — CHANGES_REQUESTED** [review]
It's supposed to be $color-forestgreen not $color-forestgreenb

**Review by Zak234 — APPROVED** [review]
Looks good. Great work!

**Comment by ericvennemeyer** [comment]
`Availability`: Today, 1hr
`ETA`: EOD Today, 8/23

**Review by ericvennemeyer — APPROVED** [review]
Correct branch, changes have been made as requested in issue, and site does not break. Looks good!

**Pull request merged**
