### PR TITLE
Change card-image-alt in lucky-parking.md

### LINKED ISSUE #3096: Change alt text for card image in lucky parking md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the lucky parking project card image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/lucky-parking.md`, change [line 60](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/lucky-parking.md?plain=1#L60) for the alt text:

from
```
card-image-alt: lucky parking project card
```
to
```
card-image-alt: 
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/lucky-parking.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/lucky-parking.md?plain=1#L60

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by tunglinn**
Fixes #3096 

### What changes did you make and why did you make them ?

  - changed card-image-alt to adhere to Web Content Accessibility Guidelines (WCAG) 
  - specifically, removed `lucky parking project card`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Comment by lilyarj** [comment]
Availability: 2hrs
Eta: 6/27

**Review by lilyarj — APPROVED** [review]
Everything looks good, it is linked to the correct issue, and it does what that issue asks (changed line 60 from card-image-alt: lucky parking project card to card-image-alt:). No screenshots of the website were provided since no visual changes were made.

**Comment by clayton1111** [comment]
Review ETA: <hour
Availability: right now

**Review by clayton1111 — APPROVED** [review]
Everything looks great!

**Pull request merged**
