### PR TITLE
Removed Code for America alt text on sponsor icon in the about page

### LINKED ISSUE #5963: Remove mention of Code for America from alt text on About Us page
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove mention of Code for America from the alt text attribute on the "Sponsors" icon, which appears in mobile view on the left side of the Sponsors card when the card is collapsed.  

### Action Items
- [x] In your IDE, navigate to `_includes/about-page/about-card-sponsors.html`
- [x] Locate the img tag with src `/assets/images/about/section-header-elements/sponsors.svg` and change the alt attribute to: 
 ```
alt=""
``` 
- [x] Using Docker, confirm that the alt text has been updated and that otherwise, the appearance and behavior of the page is unchanged in mobile and full screen sizes.  See the Resources section below for screenshot and link.  

### Resources/Instructions
<details><summary>"Sponsors" icon in mobile view</summary>

image

</details> 

- "About Us" webpage: https://www.hackforla.org/about
- This issue was created from #5953

### PR DESCRIPTION
**Pull request by YolandaHaynes**
Fixes #5963 

### What changes did you make?
  - Removed the alt text in the sponsor icon tag

### Why did you make the changes (we will use this info to test)?
  - To keep the about page up to date. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Removed alt attribute to empty string. No visual changes to website.

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: weekday evenings
ETA: EoD 1/3

**Comment by pdimaano** [comment]
ETA: 1/4/24
Availability: Weekday evenings

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5963 was properly referenced. ✅ 
- As mentioned on the original issue, the line of code was properly updated. ✅ 

Great work @YolandaHaynes !

**Review by pdimaano — CHANGES_REQUESTED** [review]
@YolandaHaynes Good start with this pull request, I just have a few suggestions before final approval: the linked pull request states that the appearance and behavior of the webpage should both be unchanged after editing the code. According to the Hack for LA contributing documentation, you should not include any screenshots of the website or code blocks if this is the case. Instead, you just need to write something like "No visual changes to the website."

Please make these edits and I will do another code review, thanks!

**Comment by YolandaHaynes** [comment]
@pdimaano Thank you for your feedback. From my understanding, under the contribution guidelines, it was advised not to show code from an IDE(VSCode).  However, my screenshot demonstrated the website using the inspect tool of the browser to show that I was in mobile mode because that was one of the requests for the changes. So, I thought showing a screenshot demonstrated that I fulfilled that requirement. However, I do understand that it did not make any visual changes to the website. I will update my PR.

**Review by pdimaano — APPROVED** [review]
@YolandaHaynes Thank you for making the requested changes. The branches are correct and the issue is linked. There are no visual or functional changes on my system on desktop or mobile. The correct file was changed and the requested alt text was removed. Well done!

**Pull request merged**
