### PR TITLE
Fixes #2852: Edit people.yml content field to content-type and remove type field

### LINKED ISSUE #2852: Edit content field and remove type field from people.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/people.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/people.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/people.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/people.yml#L11

### PR DESCRIPTION
**Pull request by str-xjua24**
Fixes #2852

### What changes did you make and why did you make them?

  -Edit content field to content-type and changed value from icon to image
  -Removed redundant type field

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Minor changes to people.yml for better code readability and redundant code removed. List is self-explanatory.

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: 12 PM 10/24/22
Availability: 12 - 4 PM Monday

**Review by MattPereira — APPROVED** [review]
Good work @str-xjua24 ! :+1: 

I love how you removed the redundant code from `_data/internal/credits/people.yml` to make it easier to understand!

**Comment by t-will-gillis** [comment]
review ETA: 5 pm 10/24
available: 4-5 pm 10/24

**Review by t-will-gillis — COMMENTED** [review]
Hi @str-xjua24 -

Congrats on your first pull request! This looks correct, great job

**Review by t-will-gillis — APPROVED** [review]
Hi @str-xjua24 -

Congrats on your first pull request! This looks correct, great job

**Pull request merged**
