### PR TITLE
Title Added Github-handle for Faezeh Faezipour

### LINKED ISSUE #6704: Add github-handle for Faezeh Faezipour in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Faezeh Faezipour
```
with
```
- name: Faezeh Faezipour
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by del9ra**
Fixes #6704

### What changes did you make?
  -Replaced "- name: Faezeh Faezipour" with "- name: Faezeh Faezipour
  github-handle:"

### Why did you make the changes (we will use this info to test)?
  - To be able to hold the github handle for each member of the leadership team
  - To avoid redundancy by replacing two variables 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by roslynwythe** [comment]
@del9ra I believe we have resolved the problem causing the failed "Add Pull Request Instructions" check.  I would like to close this PR and have you create a new one with the same branch.  Would you be willing to do that?

**Review by taylorbeee — APPROVED** [review]
Hey @del9ra  thanks for taking up the issue, branch looks good, the issue is linked correctly and spaces were used rather than tabs. Testing on local machine shows desired result. Great job.

Approved!

EDIT** I see this issue is getting re-created to work around "Add Pull Request Instructions" problem. Disregard

**Review by roslynwythe — APPROVED** [review]
Thank you @del9ra for work on this issue
- The branches are setup correctly and you have described your work
- The code change is clean and correct
- It checks out in the browser

Please disregard the error message regarding the failed GitHub check.  Great job!

**Comment by roslynwythe** [comment]
@taylorbeee This PR did not have to be re-created after all.  Part of the reason I thought we should re-create it is so reviewers would have the benefit of the instructions for pulling down the branch, but it appears that you had no problem with that. 
 Thank you for your review and I apologize for the confusion.

**Pull request merged**
