### PR TITLE
Completed CoP info update: 4948.

### LINKED ISSUE #4948: Communities of Practice information updates: Engineering CoP
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the information for the Engineering Community of Practice (COP) so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the _data/internal/communities/engineering.yml file [^1] and make the following change:
  - [x] Under the `leadership` section, remove
    ```
      - name: Fang Yi Liu
        role: Co-Lead
        links:
          slack: https://hackforla.slack.com/team/UCE01B4AX
          github: https://github.com/fyliu
        picture: https://avatars.githubusercontent.com/fyliu
    ```
- [x] Using Docker, verify the changes by checking the Engineering section of the COP page [^2] in mobile, tablet, and desktop views

### Resources/Instructions
- Original request copied into this comment for future reference: https://github.com/hackforla/website/issues/4948#issuecomment-1639479285
[^1]: Directory to find the page once you have it in your IDE: `_data/internal/communities/engineering.yml`
[^2]: COP page: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by MattChau01**
Fixes #4948 

### What changes did you make?
  - Removed the following from `engineering.yml` per issue: #4948 

```
  - name: Fang Yi Liu
    role: Co-Lead
    links:
      slack: https://hackforla.slack.com/team/UCE01B4AX
      github: https://github.com/fyliu
    picture: https://avatars.githubusercontent.com/fyliu
```

### Why did you make the changes (we will use this info to test)?
  - Updating contact information from the engineering community of practice section with the current active members.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image (1)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image (2)
image (3)

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 7/26/23
Availability: Weekday evenings

**Review by pdimaano — APPROVED** [review]
@MattChau01 Great work on this: the correct branch is included and the correct issue is linked. I can see the same visual changes on my system in desktop, mobile and tablet. The requested lines of code were removed from the changed file. Good job!

**Comment by MattChau01** [comment]
Hi @pdimaano , thanks for the review!

**Comment by jnomad21** [comment]
Availability - 7/26 most of the day
Completion - 7/26 EOD

**Comment by nnr-nnr** [comment]
Availability: 7/26 5:30-7PM PT
ETA: EOD 7/26

**Review by jnomad21 — APPROVED** [review]
@MattChau01 Everything looks good from my end.  Branch and linked issue are correct.  You've removed the requested lines of code and provided screenshots.  It looks correct on browser. Nice job.

**Review by nnr-nnr — APPROVED** [review]
Nice job keeping the website updated, @MattChau01 ! This looks good.
A couple of reminders:
- you don't need to include screenshots of the code you edited (as the pull request template says, "please do not screen shot code changes")
- make sure you check off all steps of the issue you're working on as you go; it looks like the last step of your issue was not checked/completed ("Using Docker, verify the changes by checking the Engineering section of the COP page [2](https://github.com/hackforla/website/issues/4948#user-content-fn-2-126dde4955ab058d548108a660274e77) in mobile, tablet, and desktop views")

Keep up the good work!

**Comment by MattChau01** [comment]
Thank you @jnomad21 !

Also thanks for pointing that out @nnr-nnr ! I'll keep that in mind for future PRs!

**Pull request merged**
