### PR TITLE
Update img Tag in Getting-Started Page

### LINKED ISSUE #4416: img Tag Refactor: Getting Started page - `step-img-icon-choose-slack proj-4.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-choose-slack" src="assets/images/getting-started/proj-4.png" alt="" />
```
to
```
<img class="step-img-icon-choose-slack" src="assets/images/getting-started/proj-4.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by whitneywind**
Fixes #4416 

### What changes did you make and why did you make them ?

  - Changed img tag from  to  for codebase consistency

### CODE REVIEW

**Comment by jch1013** [comment]
ETA: End of Day
Availability: Any

**Review by jch1013 — APPROVED** [review]
Changes are being merged from personal branch to gh-pages; changes match the changes requested in the original issue. No visual changes to website in either mobile or desktop views. Nice work!

**Comment by ldietz08** [comment]
ETA:  6/8 5pm
Availability:  M-F 4pm-6pm

**Comment by steven-positive-tran** [comment]
Availability: W-F
ETA: Friday 11pm

**Comment by roslynwythe** [comment]
Hi @ldietz08 If you are interested in reviewing this PR, please update your availability.  We have two other reviewers so if you are not able to review this PR, its no problem, just remove your name from the list.  Thanks!

**Comment by ldietz08** [comment]
Hi Whitney, I see that the pull request was done in the correct branch and you linked to the issue. The trailing slash in the image tag was removed. Great job!

**Review by ldietz08 — APPROVED** [review]
Hi Whitney, I see that the pull request was done in the correct branch and you linked to the issue. The trailing slash in the image tag was removed. Great job!

**Comment by graycodesnu** [comment]
Availability: 6/8
ETA: EOD

**Review by graycodesnu — APPROVED** [review]
Hi @whitneywind, great job working this issue. You committed to and from the correct branches and added the correct changes to the img tag. Changes approved. Thank you for your contribution! :)

**Comment by drakenguyen4000** [comment]
Great job @whitneywind.  The code is updated correctly.

**Pull request merged**
