### PR TITLE
Update alt text

### LINKED ISSUE #3904: Brigade Organizers Playbook: Update alt text for the Brigade Organizers Playbook image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text for the `Brigade Organizers Playbook` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the alt value within `_projects/brigade-organizers-playbook.md`:

**From:**
```
alt: "Brigade Organizer's Playbook Extension Project"
```

**To:**
```
alt: 'Brigade Organizers Playbook'
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Brigade Organizers Playbook Page: https://www.hackforla.org/projects/brigade-organizers-playbook

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/brigade-organizers-playbook.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by drakenguyen4000**
Fixes #3904

### What changes did you make and why did you make them?
- Updated alt text to "Brigade Organizers Playbook"
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
- Modified alt text to an image. No visual changes to the website.

### CODE REVIEW

**Comment by karengcecena** [comment]
Review ETA: 3/19/23
Availability: 6:00 PM

**Review by karengcecena — APPROVED** [review]
Nice work @drakenguyen4000 ! Merge branches are correct, website work good on local machine, and code changes are as mentioned in the issue. The one feedback I have for next time is to be more descriptive with your pull request description (i.e. include "to adhere to the Web Content Accessibility Guidelines (WCAG) to achieve our mission of inclusivity"). Feel free to refer to the pull request guide for more examples. Thank you!

**Comment by perlaroyerc** [comment]
Review ETA: 10 PM 3/20/23
Availability: 11-7 PM ET M-F

**Review by perlaroyerc — APPROVED** [review]
Thank you for taking this issue @drakenguyen4000! The issue is linked, changes look good in the local environment and branches are set up correctly.

I suggest adding the PR to the project board, take a look at the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board) wiki for reference. As Karen mentioned, briefly describe "why" you made a change, this would help team members and collaborators understand how those changes address specific issues. Great job!

**Comment by drakenguyen4000** [comment]
Hi Karen,
Thanks for the tips, I'll be more detailed for my next pull request.  
    On Sunday, March 19, 2023 at 05:47:52 PM PDT, Karen Garcia Cecena ***@***.***> wrote:  
 
 


@karengcecena approved this pull request.

Nice work @drakenguyen4000 ! Merge branches are correct, website work good on local machine, and code changes are as mentioned in the issue. The one feedback I have for next time is to be more descriptive with your pull request description (i.e. include "to adhere to the Web Content Accessibility Guidelines (WCAG) to achieve our mission of inclusivity"). Feel free to refer to the pull request guide for more examples. Thank you!

**Pull request merged**
