### PR TITLE
Add credit for Voting & Representation image

### LINKED ISSUE #3418: Add credit for Voting & Representation image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Voting & Representation credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `voting-and-representation.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Voting & Representation
# The url where you can get direct access to the image on the provider site
title-link: https://unsplash.com/photos/GidItEeb_24
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Phillip Goldsberry
# Name of the image database you found it on
provider: Unsplash
# Please give the general site URL, not the link to the image
provider-link: https://unsplash.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/vote-representation.png
# Alt text for the image on the Credits page
alt: ''
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by attali-david**
Fixes #3418

### What changes did you make and why did you make them ?

  - Added voting-and-representation.yml to _data/internal/credits
  - Added Image data to file.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
Screen Shot 2022-09-03 at 11 05 30 AM

</details>

### CODE REVIEW

**Comment by arpitapandya** [comment]
@attali-david Could you share screenshot of the image or the changes in the comment on the top? please! [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iii-complete-pull-request-3-what-changes-did-you-make)

**Comment by attali-david** [comment]
The image doesn't appear even though the path in source key is correct.

**Comment by arpitapandya** [comment]
> The image doesn't appear even though the path in source key is correct.

Running `docker-compose up` in your branch? and on `localhost:4000` ?

**Comment by attali-david** [comment]
> > The image doesn't appear even though the path in source key is correct.
> 
> Running `docker-compose up` in your branch? and on `localhost:4000` ?

Fixed. I was running on 0.0.0.0/4000

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-09-03

**Review by arpitapandya — APPROVED** [review]
All the changes are correct and doesn't break anything! Great job!! @attali-david

**Pull request merged**
