### PR TITLE
Add separators to links section (#1444)

### LINKED ISSUE #1444: Update Current Projects Page with separators
### Overview
The 'link', 'looking for', and 'technologies' line on the project cards in the Current Projects page ([link](https://www.hackforla.org/#projects)) lacks separators between items, reducing readability.

### Action Items

- [x] Add separators (such as commas) between the items in the 'link', 'looking for' and 'technologies' lines
- [x] Ensure that the addition of separator does not alter presentation of individual project pages ([example](https://www.hackforla.org/projects/website))

### Resources/Instructions

- Possibly relevant website files: [_projects directory](https://github.com/hackforla/website/tree/gh-pages/_projects), [current-projects.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html)
- [HackForLa site architecture documentation](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### PR DESCRIPTION
**Pull request by DGnzl**
Added comma separators to the links section of the Projects page.

### CODE REVIEW

**Comment by DGnzl** [comment]
Screen Shot 2021-04-28 at 8 42 25 AM
Screenshot of separators between links

**Review by erikaBell — CHANGES_REQUESTED** [review]
Hey @DGnzl ~ The commas between the links look great! It appears issue #1444 also asks for comma separators to be added to the "Looking For" and "Technologies" sections of these cards. Could you add those in? 

Also, please re-request review once these changes have been made, so I know to look over it again.

Thanks!

**Comment by DGnzl** [comment]
Screen Shot 2021-04-28 at 3 48 08 PM
Additional separators added.

**Review by erikaBell — APPROVED** [review]
Awesome, looks great @DGnzl

**Pull request merged**
