### PR TITLE
Replaced Broken Terminal Command With Working Terminal Commands in the CONTRIBUTING.md file

### LINKED ISSUE #7378: Section 2.7e of CONTRIBUTING.md has code that will not work in terminal
### Overview
The code block for _incorporating upstream changes_ at [2.7.e Working on an issue (5): Incorporating changes from upstream](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) of `website/CONTRIBUTING.md` utilizes bash comments that may not run successfully on some operating systems or machines when copy-and-pasted. The comments need to be removed from this code block, and rewritten after the code-block for explanation purposes. .

### Action Items
- [x] Open `website/CONTRIBUTING.md` in your IDE
- [x] Go to section "2.7.e Working on an issue (5): Incorporating changes from upstream"
- [x] At each line of code, remove all text after and inclusive of the `#` symbols. These are comments that prevent the code from executing properly. 
- [x] Remove the following
```
```bash
git checkout upstream-gh-pages # Move to the branch you want to merge with.
git pull  # This updates your tracking branch to match the gh-pages branch in this repository
git checkout gh-pages  # Move back to your gh-pages branch
git merge upstream-gh-pages  # Merge to bring your gh-pages current.```
```
- [x] Replace with the below 

~~~
1. Move to the branch you want to merge with.
```bash
git checkout upstream-gh-pages 
```

2. Update your tracking branch with the latest changes from the `gh-pages` branch in this repository
```bash
git pull  
```

3. Move back to your gh-pages branch
```bash
git checkout gh-pages  
```

4. Merge your changes back into your `gh-pages` branch.
```bash
git merge upstream-gh-pages
```
~~~

- [x] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- #6209

### PR DESCRIPTION
**Pull request by dvernon5**
Fixes #7378

### What changes did you make?
  - Updated `website/CONTRIBUTING.md` section "2.7e Working on an issue (5): Incorporating changes form upstream"
  - Replaced broken terminal commands with functional terminal commands, if branch upstream-gh-pages has already been created

### Why did you make the changes (we will use this info to test)?
  - The CONTRIBUTING.md section 2.7e has code formatting errors that need to be fixed.

### For Reviewers:
  - Do not review changes locally, rather, review changes at https://github.com/dvernon5/website/blob/replacing-broken-code-command-7378/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

No visual changes to the website

### CODE REVIEW

**Comment by mchait18** [comment]
Review ETA: 12 PM 11/28/2024
Availability: 9-12 PM EST Thurs

**Review by mchait18 — DISMISSED** [review]
Thank you for working on this issue, @dvernon5  !

You're doing these right:
- The branch you made the change on is correct
- The linked issue (original issue) number is included
- The content required to remove and to add is accurate
- The CodeQL Alerts are checked (check box above)
- The URL to the test page is working

 Great job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @dvernon5 Everything looks good- just a couple comments
- I understand how the instructions for #7378 could be read this way; however, the section "For Reviewers: Do not review..." should be an instruction that occurs after you have answered the question "Why did you make the changes (we will use this info to test)?", and not the answer to the question itself like the instructions seem to say. Please add an answer after "Why did you make the changes..." - something like "The CONTRIBUTING.md section 2.7.e has code formatting errors that need to be fixed".  and move the "For Reviewers..." down. Something like this might work:
  ```  
  ### Why did you make the changes (we will use this info to test)?
  - The CONTRIBUTING.md section 2.7.e has code formatting errors that need to be fixed
  
  ### For Reviewers
  - Do not review changes locally, rather, review changes at https://github.com/dvernon5/website/blob/replacing-broken-code-command-7378/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream  
  ```  
- Please remove the comment on line 707- we are continuously replacing things in this file and if we added this comment each time, we would have dozens of these

Thanks!

FYI- It is a good idea not to assign people to review your issue unless you know the person is available, or if you need a followup to a review that person previously did. I am saying this because one of the people you assigned is no longer active in the project. Else when people look at your issue they will mistakenly believe you have enough reviewers

**Comment by dvernon5** [comment]
Hello @t-will-gillis 

Thank you for your feedback. Re-reading the exercise you are correct, I was supposed to insert the question "For Reviewers" underneath the question "Why did you make the changes" Thank you for the clarification. Also, I made the changes to the initial mistakes on the markdown template, as well as removing the comment on line 707 and re-pushing my local code into the repository. 

Question: After making a pull request, what should I do to get my issue checked followed by merging if all steps are correct? Should I leave a message in the Slack hfla-site channel to let someone know that my issue is ready to be checked?

**Comment by siyunfeng** [comment]
> Hello @t-will-gillis
> 
> Thank you for your feedback. Re-reading the exercise you are correct, I was supposed to insert the question "For Reviewers" underneath the question "Why did you make the changes" Thank you for the clarification. Also, I made the changes to the initial mistakes on the markdown template, as well as removing the comment on line 707 and re-pushing my local code into the repository.
> 
> Question: After making a pull request, what should I do to get my issue checked followed by merging if all steps are correct? Should I leave a message in the Slack hfla-site channel to let someone know that my issue is ready to be checked?

Hi @dvernon5 , developers usually review your PR within 2 to 4 days after your PR is submitted. Sending your PR URL to the hfla-site-pr channel will be a nice reminder for available developers. 

To merge your PR to the gh-pages branch, you will need at least 2 reviewers to approve your PR. You will need to keep an eye on your PR, if someone leaves you a comment asking for a change, please respond and make the change in time. Once you complete the change requests, you can re-request the reviewers to review your PR by clicking the `Re-request review` button in the `Reviewers` section. 

The reviewers will provide their review ETA and availability after they assign themselves. Please don't hesitate to reach out through the Slack channel or leave a comment in your PR if you have any questions or need help. 

Hack for LA will have the annual break for a whole month in December and will be back in January. You can leave a message in the Slack channel and some of us will check the message and try to reply occasionally.

**Review by t-will-gillis — APPROVED** [review]
Hey @dvernon5 Great- thank you for making the changes! 

To add to @siyunfeng 's comments (thanks!) - after you make changes requested by a reviewer, be sure to re-request reviews by clicking on the chasing arrows next to each of the reviewers' names:
Screenshot 2024-11-30 084623

This will alert the reviewers that they should look at the PR again. 

@mchait18 if would you please re-review this?

**Comment by dvernon5** [comment]
@siyunfeng 

Thank you for your response and clarification. I truly appreciate it and understand the PR process.

Thank you!

**Comment by dvernon5** [comment]
@t-will-gillis 

No problem thank you once again for the suggestions. As well thank you for the further explanation and the screenshot. It truly helps. Thank you for all of your help.

**Comment by t-will-gillis** [comment]
Hi again @mchait18 - No need to re-review since you previously Approved this PR

**Pull request merged**
