### PR TITLE
Add automatic retries to "Schedule Daily" GHA

### LINKED ISSUE #7120: Add automatic retries to "Schedule Daily" GHA
### Overview
When reviewing the ["Schedule Daily" workflow logs](https://github.com/hackforla/website/actions/workflows/schedule-daily-1100.yml), it can be seen that many days the workflow fails with the error:
`RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again... ` We need to add code to automatically retry the workflow a set number of times if the workflow does not successfully complete.

### Details
It appears that the `RequestError` occurs in the function `getAllRepos()` in the file `get-project-data.js`. The `RequestError` is due to a secondary rate limit and the message suggests to wait a few minutes before retrying. Therefore we will want to incorporate code that retries the workflow a total of three times: at 2 minutes past the original failure, and if needed after 4 more minutes, and lastly if needed after 8 more minutes. 
### Action Items
- [x] Review one of the recent, failed [workflow logs](https://github.com/hackforla/website/actions/runs/9938251117) and 
- [x] cross-reference with [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml) and [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js). 
- [x] Determine the appropriate location for the retry, for example at `getAllRepos()`. *** 
- [x] Add code for automatically retrying if there is a `RequestError`, and set the intervals of 2, then 4, and finally 8 minutes. 
- [x] Test in your own repo that the retry works as intended. Possible test: recreate a `RequestError` in "Schedule Daily" in your repo to confirm that the retries occur.

*** There may be other appropriate ways to retry the failed workflows, for example: adding a retry step after "Generate github-data.json" in `schedule-daily-1100.yml`. FYI- Do not use a GitHub Marketplace action/automation.
### Resources/Instructions
- Info regarding ["Schedule Daily" and testing](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028)

### PR DESCRIPTION
**Pull request by daras-cu**
Fixes #7120

### What changes did you make?
  - In `get-project-data.js`, added code to the `getAllRepos()` function to retry the original function steps in case of an error.
  - The code will retry up to three times, waiting 2 minutes, 4 minutes, and 8 minutes before each successive retry.
  - If the third retry still is unsuccessful, an error will be thrown and the workflow will exit as before.

### Why did you make the changes (we will use this info to test)?
  - The Schedule Daily workflow periodically fails because of a rate limit related `RequestError` that occurs during a GitHub API request within the `getAllRepos()` function.
  - GitHub documentation indicates the rate limit error should be resolved by waiting and retrying the request, so the changes should enable the request to complete successfully on retry, allowing the workflow to continue.

### Resources for testing:
[Schedule Daily info](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028)

Note: Any type of error you add within the try block should also trigger the retries for testing purposes. I did encounter the rate limit error on one of my tests and the request returned successfully on retry.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes

### CODE REVIEW

**Comment by daras-cu** [comment]
#### Additional info:
This is the workflow run where I encountered the `RequestError` during testing in the first and second retries (note there was also a `ReferenceError` that ultimately caused the final retry to fail, but reaching this second error indicated the request returned successfully on this retry)
[Request Error Run](https://github.com/daras-cu/website/actions/runs/10328569954/job/28595281835)

Also note I added the `Error: retrying in 'x' minutes` messages for confirming the timing of retries was correct in testing, but they are not present in the final code.

**Comment by mrodz** [comment]
**Availability**: Weekdays 8am-8pm, Weekends 9am-5pm
**ETA**: EOD 8/12/24

**Comment by del9ra** [comment]
Review ETA: EST 10 PM 8/16/24
Availability: 1PM-5 PM

**Review by mrodz — CHANGES_REQUESTED** [review]
Hello @daras-cu, amazing work!
- Proper to/from branches
- Linked issue
- Good description
- All of these workflow runs of `Schedule Daily 1100` fail at the exact same point; good on you for catching the error propagating from `getAllRepos`: example [A](https://github.com/hackforla/website/actions/runs/10235693602/job/28316834780), [B](https://github.com/hackforla/website/actions/runs/10227506301/job/28299033575), [C](https://github.com/hackforla/website/actions/runs/10075450968/job/27853753486), [D](https://github.com/hackforla/website/actions/runs/10007022977/job/27660877012), [E](https://github.com/hackforla/website/actions/runs/9906860580/job/27369316703), etc.
Your code appears proper and follows the formatting of the rest of the document. Your solution will get the job done! It creatively uses an async `delay` function.
- I tested the code in a branch off of your branch. After inserting an exception when `tries == 0`, your code waited and then fetched again successfully. Your GHA run shows the same result 👍 
- Good on you for using a geometric sequence to determine the delay! Your code waits 2, 4, and 8 minutes accordingly.
---
I just wanted to let you know that there are some styling discrepancies. Throughout this file, `if/else` blocks are written like this:
```js
if(condition) {
  // code
} else {
  // code
}
```
... while your PR introduces:
```js
if(condition) {
  // code
}
else {
  // code
}
```
Same with the `try/catch` block.

I am going to request changes because I believe the merge team would point this out when they do their review. It shouldn't take more than a few minutes to make sure your changes match the file's style. Ping me once you've got it! :)

**Review by mrodz — APPROVED** [review]
Merge team, see my previous comment for a breakdown. These changes look great! The formatting is superb :)

**Comment by daras-cu** [comment]
Hi @mrodz, thanks for catching the styling issue! I've adjusted both blocks to get rid of the line breaks, let me know if all looks ok.

ETA: You were faster than me leaving this comment, thanks for re-reviewing!

**Comment by t-will-gillis** [comment]
avail: 8/18
eta: 8/18 eod

**Review by t-will-gillis — APPROVED** [review]
Hey @daras-cu Fabulous work! Thank you for working with @mrodz on the formatting, and thanks to both for your detailed notes and logs. I tested in my repo and got similar results. Branches are good, links are good, and your code is clean.

Thanks again!

**Pull request merged**
