### PR TITLE
Update a credit file for composite images

### LINKED ISSUE #4606: Update a credit file for composite images
### Overview
We need to add some info to the credit for an image because it is a composite image. We do this so that we give credit to all the image authors.  

### Details
This will require creating separate credits for each image

#### Details
The three images involved are 
- [Diversity, Equity, Inclusion](https://github.com/hackforla/website/blob/feature-homepage-launch/assets/images/program-areas/diversity-equity-inclusion.png) - composite image
- [Team Hands Middle Photo](https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity) (the main image)
- ["Progress" Pride Flag](https://progress.gay/pages/terms-of-use) (the image we are using in the composite image)

On the redesigned homepage on the feature-homepage-launch branch, the Diversity, Equity, Inclusion image is a composite image.  The original image was altered by removing images from the laptop cover, and then adding the "Progress" pride flag. However, on the Credits page, the credit for Diversity, Equity, Inclusion only provides credit to one image's artist and doesn't provide credit to the other artist.  Here is what It looks like now
<details>
<summary>Current credit</summary>

</details>

<details>
We will be replacing the current credit with these credit files. 

<summary>Proposed future credit files</summary>

1 composite image - filename `diversity-equity-inclusion-composite.yml` 
```
---
title: Diversity, Equity, Inclusion
title-link: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-composite.yml
content-type: image
used-in: Homepage
provider: HfLA composite image
image-url: /assets/images/program-areas/diversity-equity-inclusion.png
provider-link: (Replace with link to this file, so that people can see the comments)
# If an image was altered, please give the name of the HfLA designer that altered the image
compiled-by: Kristine Eudey
# If an image was altered, please give the LinkedIn URL of the HfLA designer that altered the image
compiled-by-link: https://www.linkedin.com/in/kristine-eudey/
alt: '4 people doing Ready Break! over laptop with progress pride flag'
# alteration: 'edited to remove images from the laptop cover, and then add the "Progress" pride flag'
# This image is a composite image.  If this image is used, credit must be provided to the author of each of the images used in the composite as well as the person who altered it.  
# See the following credits: 
#   main image: [Replace with the url to the credits yml file for the main image]
#   secondary image: [Replace with the urls to the credits yml file for the secondary image]
---
```

2 main image - filename '`diversity-equity-inclusion-main.yml`
```
---
title: Team Hands Middle Photo
title-link: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Matthew Henry
provider: Burst
provider-link: https://burst.shopify.com/
image-url: 
alt: '4 people doing Ready Break! over laptop'
---
```

3 secondary image - filename `diversity-equity-inclusion-secondary.yml`
```
---
title: "Progress" Pride Flag
title-link: https://progress.gay/pages/terms-of-use
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Daniel Quasar
provider: Progress.gay
provider-link: https://progress.gay/
image-url: 
alt: '"Progress" Pride Flag'
---
```
</details>

### Action Items
- [x] Work on this issue will be merged into hackforla/feature-homepage-launch.  For information about working on a feature branch, see https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
- [x] Based on "Proposed future credit files" above, create three new credits files in the `_data/internal/credits/` folder, using the specified filenames
- [x] Delete `_data/internal/credits/diversity-equity-inclusion.yml`
- [x] Update `pages/credits.html` to display the new variables `compiled-by` and `compiled-by-link` 
- [x] Obtain the images for the "main" and "secondary" images from the dev lead, and add those to the folder `assets/images/credits`
- [x] Edit `diversity-equity-inclusion-main.yml`, populating the `image-url` field with a relative url to the "main" image
- [x] Edit `diversity-equity-inclusion-secondary.yml`, populating the `image-url` field with a relative url to the "secondary" image 

### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. file on the homepage branch: https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/diversity-equity-inclusion.yml

### PR DESCRIPTION
**Pull request by A-Wu5**
Fixes #4606

### What changes did you make?
  - Replaced `_data/internal/credits/diversity-equity-inclusion.yml` with `diversity-equity-inclusion-main.yml`, `diversity-equity-inclusion-composite.yml`, and `diversity-equity-inclusion-secondary.yml`.
  - Updated `pages/credits.html` to display `compiled-by` and `compiled-by-link` variables
  - Added `ProgressSQsm.jpg` and `team-hands-middle.jpg` to assets/images/credits
### Why did you make the changes (we will use this info to test)?
  - To ensure that credit is fairly given to all image artists.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

image

</details>

### CODE REVIEW

**Comment by jphamtv** [comment]
Availability: Monday-Friday 8–11 PM (PST) 
Estimated ETA: 1/12/24

**Comment by LRenDO** [comment]
Hi @A-Wu5! It looks like you've done a great job adding the files and the complied by variables! It looks like there is also a check box about adding instructions to the wiki on how to write up a credit. "Based on the "Proposed future credit files" above, create or update a page for the wiki that explains how to format credits on composite images. https://github.com/hackforla/website/issues/5895". I couldn't find anything to added to the wiki. If you added it to https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki or somewhere else please direct the reviewers to it in your PR comment. 

Looping in @roslynwythe to clarify a few things:

- It looks like the issue linked in the instructions for the wiki is closed, but the page hasn't been created and it is listed in a task for #4606. I want to be sure I didn't miss the wiki draft on how to create a composite credit somewhere and that it still needs to be created. [This wiki page](https://github.com/hackforla/website/wiki/Credits-page) is the only one I found relating to credits.
- For this issue, should all of the credits added now be appearing in the credits list on http://localhost:4000/credits/ or was this issue simply to make the data files and add the complied by variables? Currently, the main and secondary credits are not appearing.
- Should the URLs in the composite credit file be replaced before merging?
- The `title-link` in diversity-equity-inclusion-composite.yml does not link to the image should it be updated to http://localhost:4000/assets/images/program-areas/diversity-equity-inclusion.png before merging?

**Comment by A-Wu5** [comment]
Hi @LRenDO, thanks for the feedback! Regarding the checkbox for adding instructions to the wiki for writing up a credit that was already checked before I took on the issue. I think the wiki file it might be referring to is [Credit yml file template for icons and images](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery). However, you are correct in that there is no specific wiki page or detail in the above page that mentions composite images.

I created the files with the specified fields as requested, but the main and secondary credits are not shown because the `image-url` fields are empty.  I would also like that to be clarified on what should be in those fields or if they are intentionally empty.

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @A-Wu5, 

Great job on the pull request. The to/from branches are correctly set, and the issue link is properly included. I appreciate how well you've summarized the 'What' and 'Why' behind the changes.

Also, excellent work on replacing the .yml file and updating pages/credits.html. I checked the page locally, and it looks good. The link to the 'Compiled by' link navigates to the person's LinkedIn page correctly.

However, I did notice a couple of areas that need your attention:

- The before/after screenshots don't seem to reflect the page's visuals. Could you update them to show the latest changes? A screenshot of what I see is below.
- When clicking on the 'Name' and 'Provider' links, they go to 404 pages. I think the URLs in `diversity-equity-inclusion-composite.yml` for `title-link:`, `provider-link:`, and the URLs in the comments section, should be prepended with `https://github.com/hackforla/website/blob/gh-pages/`. This adjustment should ensure the links work correctly after the feature-homepage-launch branch is merged with the gh-pages branch.
- I also couldn’t locate a Wiki draft for composite credit. It's possible the issue #5895 might have been closed accidentally, as the checkboxes aren’t marked as done. I wonder if this could be a case of automation mistakenly checking off the action item in your issue when the issue was closed? 

Once you've made these updates, go ahead and re-request a review. Let me know if you have any questions.

Screenshot 2024-01-12 at 11 08 57

**Comment by roslynwythe** [comment]
- Thank you @A-Wu5 for your work on this issue and thank you @LRenDO and @jphamtv for great reviews.  I apologize for the confusion around #5895.  It appears that it was closed accidentally without being completed, so I will reopen it.   I removed mention of #5895 from the current linked issue #4606 because it was confusing. 

I have not been able to locate the image urls.  I will ask Bonnie about it at tonight's dev/PM meeting and ask about using the title-link or provider-link, and I will report back tomorrow so we can approve this PR.

**Comment by roslynwythe** [comment]
@A-Wu5 Please find the images [main image](https://github.com/roslynwythe/website/blob/A-Wu5-feature-homepage-launch/assets/images/credits/team-hands-middle.jpg) and [secondary image](https://github.com/roslynwythe/website/blob/A-Wu5-feature-homepage-launch/assets/images/credits/ProgressSQsm.jpg).  So that we can demonstrate the successful completion of this issue, I need to ask you to update this PR,  to add the images to the respository and to populate `image-url` in the "main" and "secondary" yml files.  I added three new Action Items to the issue which describe these tasks.  
Thank you

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@A-Wu5 Please find the images [main image](https://github.com/roslynwythe/website/blob/A-Wu5-feature-homepage-launch/assets/images/credits/team-hands-middle.jpg) and [secondary image](https://github.com/roslynwythe/website/blob/A-Wu5-feature-homepage-launch/assets/images/credits/ProgressSQsm.jpg). So that we can demonstrate the successful completion of this issue, I need to ask you to update this PR, to add the images to the respository and to populate image-url in the "main" and "secondary" yml files. I added three new Action Items to the issue which detail these tasks.
Thank you

**Comment by A-Wu5** [comment]
Hi @roslynwythe and @jphamtv, 

Thanks for the review! I've added the image files and updated the screenshots to reflect what's shown on the page accurately. 

I've also fixed the links for the credit files. More specifically, I set the links for `title-link` and `provider-link` in [diversity-equity-inclusion-composte.yml](https://github.com/hackforla/website/pull/6026/files#diff-1a161554c77defc3b4ccbffcc4a2abcea2fa5d46213d18f33c8d36686b0d31ca) to `https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/diversity-equity-inclusion-composite.yml`. 

However, the links will lead to a 404 error page until the files in this pull request are merged because they do not exist in the repository yet. I set the links to the `feature-homepage-launch` branch and I'm not sure if it should be that or `gh-pages`. In the future, if the branch gets merged into `gh-pages` the links would not work unless it is `gh-pages`. Which one should it be?

**Comment by roslynwythe** [comment]
Thank you @A-Wu5 - It is possible to use a relative link:
```
title-link: /_data/internal/credits/diversity-equity-inclusion-composite.yml
```
however that is not going to display without some kind of yml viewer.  I will ask Bonnie about this and report back with an answer by EOD 1/21.

**Comment by roslynwythe** [comment]
Great job so far @A-Wu5 and we appreciate your patience as we fill in details on this issue.  I have two minor requests:
- Please set the links for `title-link` and `provider-link` in `diversity-equity-inclusion-composte.yml` to  https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-composite.yml.  You are correct, that the links will not work until merged into gh-pages so PR reviewers should not be concerned with those 404 errors.    
- If possible, please provide a single screenshot that shows credits for the composite, main and secondary images.  
Thank you!

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @A-Wu5 , thanks for updating the screenshots. I was able to verify the compiled, main, and secondary images and credits appear on the credits page on my end using Docker.

Just a few more things:

- The Action item instructs to place the main and secondary images in the folder `assets/images/credits`, but they are currently in `assets/images/project-areas`.  
- On lines 17 and 18 of the `diversity-equity-inclusion-composite.yml` file, it looks like URLs need to be included to link to the 'main' and 'secondary' credit yml files. 

Please let me know once these updates are completed. Thanks for your continued effort on this issue.

**Comment by A-Wu5** [comment]
Hello @roslynwythe,

I've updated the links in `diversity-equity-inclusion-composite.yml` and updated the 'after' screenshot so that it is only one screenshot.

Thank you for the review.

**Comment by A-Wu5** [comment]
Hi @jphamtv,

Good catches! I moved the image files to the credits folder and added the links to `diversity-equity-inclusion-composite.yml`.

Thank you for the review.

**Review by jphamtv — APPROVED** [review]

**Review by LRenDO — APPROVED** [review]
Hi All!

Thanks @roslynwythe for all the clarifications and @jphamtv for a great review!

@A-Wu5, great job with this pull request! And thanks for your patience while we sorted out some of the details!

Some highlights:

- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site. All three images are listed when run locally.
- Relevant images were included to show visual changes
- The PR request states why the changes are being made

I also have a just one non-functional request and a clarification on branching.
- In the what was changed section of the original PR comment, add that image files were added
- I don't think it's an issue with this particular pull request, but in the instructions for working on the feature page, it said to create a branch off the feature branch locally before beginning your work.  Similar to how we branch off of the gh-pages branch. The branching should ideally be an new branch off of your `feature-branch-launch branch`. 

Again, really nice work and thanks for taking the time to contribute to the website!

**Review by roslynwythe — APPROVED** [review]
Thank you @A-Wu5 for your work on this issue.  As Ren pointed out, it is a best practice to make your changes on an issue branch that is based on your local `feature-homepage-launch` branch.  Since your changes were made to your local `feature-homepage-launch` branch, you should delete your local `feature-homepage-launch` branch and start fresh the next time you work on a feature homepage launch branch issue.

**Comment by ExperimentsInHonesty** [comment]
Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

**Pull request merged**
