### PR TITLE
Updated credit link to display only if direct link exist

### LINKED ISSUE #4351: Edit credits.html to only include href if credit has a title-link
### Overview
Some of the credits in [/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) don't have a direct link to their photos. We need to update [credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html) so that it only renders a link to the credit's photo if it has a direct link. 

### Action Items
- [x] See line 39 in credits.html:
https://github.com/hackforla/website/blob/a3c702fc14be53f17f16cf906b54eb6e63d19fd9/pages/credits.html#L39
- [x] Using Liquid, edit the html so that the title only links to photo if the credit has a valid `title-link`
- [x] All credits that do have a valid `title-link` must still have a direct link to their photos
- [x] Ensure this does not break any other page that uses the credits

### Resources/Instructions
- Example of a credit without a valid `title-link`: [cwmoss.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/cwmoss.yml)
- [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll

### PR DESCRIPTION
**Pull request by drakenguyen4000**
Fixes #4351

### What changes did you make and why did you make them ?

  -  Update credits.html so that it only renders a link to the credit's photo if it has a direct link.  Else the title will not display as a link.  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before
</details>

<details>
<summary>Visuals after changes are applied</summary>

After

</details>

### CODE REVIEW

**Review by RyanGehris — APPROVED** [review]
Your code changes worked great in multiple browsers and screen sizes. The changes you  made are very concise and effective. Thank you for completing this issue for HackForLA!

**Comment by KazushiR** [comment]
Review ETA: Today 04/09/23 EOD
Availability: Weekdays and sometimes weekends

**Comment by nnr-nnr** [comment]
Review ETA: EOD 4/10/23
Availability: M-F 3-8pm PST

**Comment by steven-positive-tran** [comment]
Review ETA: EOD 4/10/23
Availability: M-F 7-12pm PST

**Review by steven-positive-tran — APPROVED** [review]
Works on my machine on firefox and edge. 
Commited to correct branch and from your own fork.
Code changes seem appropiate for the issue

Approved and thank you for taking up this issue for hackforla

**Comment by roslynwythe** [comment]
Hi @nnr-nnr this PR has 2 approvals already but if you plan to review this issue, I'll hold off on merging if you would like.  Just let me know your ETA.  Thanks!

**Review by nnr-nnr — APPROVED** [review]
Nice job on this issue! You've fixed the problem of broken links, with this PR passing the ABCs. One thing I noticed was that the live site and this repo show a different order of credit items  on the credit page (though using the inspector shows that there are 79 `credit-items` on both). I can't tell if this difference is caused by the changes in this repo (the code doesn't seem like it should affect the order of credit items on the page), or maybe just because the live site is many merges behind the repo version this code was branched from. The code fixes the issue, hence the approve. If you have any insight into this, though, I'd be curious :). Great work!

Order of credit items on live site:
Screenshot 2023-04-11 at 12 24 14 PM

Vs order of credit items on in this repo:
Screenshot 2023-04-11 at 12 25 11 PM

**Pull request merged**
