### PR TITLE
Removed Aparna et al from Access The Data Project Profile

### LINKED ISSUE #6065: Update Project Profile: Access the Data (Remove Aparna Gopal, Judson Lester, Tony Delgado Willis)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/access-the-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Judson Lester
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U9NFW84QK'
      github: 'https://github.com/nyarly'
    picture: https://avatars.githubusercontent.com/nyarly
  - name: Aparna Gopal
    role: UX Researcher
    links:
      slack: 'https://hackforla.slack.com/team/U0245UJP868'
      github: 'https://github.com/Aparna1Gopal'
    picture: https://avatars.githubusercontent.com/Aparna1Gopal
  - name: Tony Delgado
    github-handle: 
    role: Developer
    links:
      slack: 'https://hackforla.slack.com/team/U05422GPUQ2'
      github: 'https://github.com/TonyDelgadoWillis'
    picture: https://avatars.githubusercontent.com/TonyDelgadoWillis
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Access the Data page [^2]
- [x] Once your pull request is merged, go to #6018 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6018 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6018
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/access-the-data

### PR DESCRIPTION
**Pull request by colin-macrae**
Fixes #6065

### What changes did you make?
  - Removed profiles for: Aparna Gopal, Judson Lester, Tony Delgado Willis 

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>  

image

</details>

### CODE REVIEW

**Comment by YolandaHaynes** [comment]
Review ETA: 10pm 01/21/24
Availability: Sunday 8-10pm.

**Review by YolandaHaynes — DISMISSED** [review]
Great job @colin-macrae! 

- You have the correct branch and the linked issue. 
- Your description was clear and to the point. 
- Your screenshots do show before and after changes, and you edited the code as needed. 
- When I tested locally, I saw the appropriate outcome and changes. 

Thanks for your work!

**Comment by kwangric** [comment]
Hey @Tony-Hsieh! When you get the chance, please leave a comment with your availability and ETA for your review. Thanks!

**Comment by tonyvang** [comment]
Hi, @kwangric @roslynwythe, I think there was a confusion at Sunday's meeting. I think this is a PR I volunteered to review and Tony Hsieh wasn't at the meeting.

ETA: 11pm Thursday 2024/01/25
Availability: Tomorrow evening, Thursday evening

**Review by tonyvang — DISMISSED** [review]
Hi @colin-macrae,

You have the correct issue linked, and are merging into the correct branch from an appropriate and clearly named working branch.

Your code change appropriately removes the Judson Lester, Aparna Gopal, and Tony Delgado blocks from the leadership section in the Access the Data project markdown.

Your description of your changes is direct. Both your screenshots and my local test of your changes show the desired visual change. I'm approving this PR.

Excellent work, Colin. Thanks for contributing!

**Comment by jphamtv** [comment]
Hey @colin-macrae , thanks for working on this issue. It looks like there are conflicts on the branch that need to be resolved before merging. I also have a minor suggestion: to clear the broken image links (see image below) by removing `image` from the “Visuals before/after changes are applied” sections. Thanks! 

Screenshot 2024-01-25 at 18 42 24

**Comment by colin-macrae** [comment]
> Hey @colin-macrae , thanks for working on this issue. It looks like there are conflicts on the branch that need to be resolved before merging. I also have a minor suggestion: to clear the broken image links (see image below) by removing `image` from the “Visuals before/after changes are applied” sections. Thanks!
> 
> Screenshot 2024-01-25 at 18 42 24

Thank you @jphamtv.  I made changes to the img files in my original comment, per your suggestion, and resolved the merge conflict.  It looks like all the names from the list have now been deleted and there is now a placeholder: 

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>  

image

</details>

**Comment by jphamtv** [comment]
> 
> Thank you @jphamtv. I made changes to the img files in my original comment, per your suggestion, and resolved the merge conflict. It looks like all the names from the list have now been deleted and there is now a placeholder:
> 
> image

@colin-macrae - Thanks for resolving the conflict. Since the code changed, you'll need to re-request reviews from the reviewers. You can do that by clicking the icon next to their names. Also, make sure to update the before/after screenshots for accurate representation.

Screenshot 2024-01-26 at 23 07 21

**Comment by colin-macrae** [comment]
> > Thank you @jphamtv. I made changes to the img files in my original comment, per your suggestion, and resolved the merge conflict. It looks like all the names from the list have now been deleted and there is now a placeholder:
> > image
> 
> @colin-macrae - Thanks for resolving the conflict. Since the code changed, you'll need to re-request reviews from the reviewers. You can do that by clicking the icon next to their names. Also, make sure to update the before/after screenshots for accurate representation.
> 
> Screenshot 2024-01-26 at 23 07 21

Thanks @jphamtv.  Done.  Can I assume that for all future merge conflicts and change requests I can re-assign the same reviewers after the changes are made?  

Hi @YolandaHaynes and @tonyvang.  Would you be able to confirm my merge conflict resolution is satisfactory, and if so, re-approve the PR?  (I have re-assigned you per @jphamtv)

**Comment by jphamtv** [comment]
> Thanks @jphamtv. Done. Can I assume that for all future merge conflicts and change requests I can re-assign the same reviewers after the changes are made?
> 

Hey @colin-macrae, yes, you're correct, we need to re-request reviews on our pull requests whenever we update the code. Also, a reminder to update the screenshots in the changes summary to reflect the correct visuals on the page. Thanks!

**Comment by tonyvang** [comment]
Many thanks @jphamtv for catching the merge conflict! Good looking out.

@colin-macrae, thanks for re-requesting! I'll take a second look after tonight's meeting.

**Review by tonyvang — APPROVED** [review]
Hi @colin-macrae, I took a look at your second commit and and tested locally to the same result as your new screenshots.

Thanks for your patience; great work on the issue and resolving this merge conflict! I'm re-approving your PR.

**Review by jphamtv — APPROVED** [review]
@colin-macrae, great work on this issue and for updating the before/after screenshots with the updated visuals after resolving the merge conflicts.

**Pull request merged**
