### PR TITLE
Add github-handle for Jane He in tdm-calculator.md 

### LINKED ISSUE #7170: Add github-handle for Jane He in tdm-calculator.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tdm-calculator.md` in the IDE
- [x] Replace:
```
- name: Jane He
```
with
```
- name: Jane He
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tdm-calculator

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by vorleakyek**
Fixes #7170

### What changes did you make?
  
  - Replace `- name: Jane He` with 
```
- name: Jane He
  github-handle:
```
  

### Why did you make the changes (we will use this info to test)?
  
  - To create a single variable github-handle
  - Eventually github-handle will replace the github and picture variables
  

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
Adding the `github-handle:` in the tdm-calculator.md file. No visual changes to the website.

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Review ETA: End of day Aug 24, 2024
Availability: 12-3PM PT

**Comment by palakkeni5** [comment]
Review ETA:  Aug 24, 2024 6PM EST
Availability: 5PM - 8 PM EST

**Comment by palakkeni5** [comment]
Checklist
 

- [x]  Is the pull request done with the correct branch?  Yes
- [x]  Is there a linked issue? Fixes https://github.com/hackforla/website/issues/7170
- [x]  Understand the linked issue. 
- [x]  View the changes in the browser. 
- [x]  Take a look at files changed tab.
- [x]  Check for anything else.
- [ ]  Approve the pull request.
- [x]  Clean up your working 

Hi @vorleakyek ,

Your PR looks fine to me.

Thanks for working on the issue!

P.S : This is my first PR review in the organization. I do not see options to approve this request as mentioned in the steps.

**Comment by bexux** [comment]
Review ETA: Aug 24, 2024 6PM PST
Availability: 6PM - 8 PM PST

**Review by bexux — APPROVED** [review]
Looks great. You followed all the steps - approved.

**Review by tamara-snyder — APPROVED** [review]
I can see that you added the github-handle line in the right place and that the appearance of the webpage is unchanged. Nice work!

**Pull request merged**
