### PR TITLE
Update Img tag refactor: citizen engagement

### LINKED ISSUE #4449: img Tag Refactor: Citizen Engagement page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/program-area-pages-cards.html`
- [x] Change the following from
```
<img class="sdg-image" src="{{ item.sdg-image-src }}" alt="{{ item.sdg-image-alt }}" />
```
to
```
<img class="sdg-image" src="{{ item.sdg-image-src }}" alt="{{ item.sdg-image-alt }}">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/program-area-pages-cards.html
2. Webpage: https://www.hackforla.org/citizen-engagement
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by oliviazhai**
Fixes #4449 

### What changes did you make and why did you make them ?

  -  Remove the ending slash in the img HTML tag in citizen engagement page

there are no visual changes

### CODE REVIEW

**Review by LOSjr4 — CHANGES_REQUESTED** [review]
@oliviazhai Thank you for addressing the slash in this issue. Your pull request was submitted correctly. However I noticed the original issue also showed the space taken out in addition to the slash.  
image
Please go back into your branch, remove the space, and commit/push again.

Also FYI, I appreciate your effort to include pictures, but regarding this issue, there wasn't any changes to show. It's important that we check Docker to make sure our changes don't break anything, but we don't always supply pictures if changes are not visible to the site.

**Comment by 93Belen** [comment]
Availability: Tuesday, Thursday and Sunday from 6am to 6pm
ETA: 5/30/23 by 6pm

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @oliviazhai, I agree with the points made by @LOSjr4.  Since we are aiming for a consistent formatting of HTML, please remove the extra space at the end of the tag, and also please delete the `<details>` and `<summary>` tags and simply state that there are no visual changes to the website.  But aside from those minor points, the PR looks very good.  Thank you!

**Comment by 93Belen** [comment]
I agree with the changes requested so I am just going to wait for that to be fix before I leave the same review :)

**Comment by oliviazhai** [comment]
> Hi @oliviazhai, I agree with the points made by @LOSjr4. Since we are aiming for a consistent formatting of HTML, please remove the extra space at the end of the tag, and also please delete the `<details>` and `<summary>` tags and simply state that there are no visual changes to the website. But aside from those minor points, the PR looks very good. Thank you!

Hi,

I just did the change can you review again, thanks for the feedback

**Comment by oliviazhai** [comment]
> @oliviazhai Thank you for addressing the slash in this issue. Your pull request was submitted correctly. However I noticed the original issue also showed the space taken out in addition to the slash. image Please go back into your branch, remove the space, and commit/push again.
> 
> Also FYI, I appreciate your effort to include pictures, but regarding this issue, there wasn't any changes to show. It's important that we check Docker to make sure our changes don't break anything, but we don't always supply pictures if changes are not visible to the site.

Hi,

thanks so much for the feedback, i did the change can you review it again

**Review by 93Belen — APPROVED** [review]
Hi! Great job!
You did the PR from the correct branch, linked the issue and explained what you did.
Now the img element is formatted exactly how described in the Issue.
Great job addressing the changes requested.

**Review by LOSjr4 — APPROVED** [review]
Perfect @oliviazhai! Thank you for going back in to remove that space and letting me know to re-review your PR.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @oliviazhai since there are no visual changes to the website, please delete the `<details>` and `<summary>` tags in the PR, along with the images, and simply state that there are no visual changes.

**Comment by oliviazhai** [comment]
> Hi @oliviazhai since there are no visual changes to the website, please delete the `<details>` and `<summary>` tags in the PR, along with the images, and simply state that there are no visual changes.

Hi, @roslynwythe, I just updated the command,thanks

**Review by roslynwythe — APPROVED** [review]
Hi @oliviazhai great job on this issue.  Your code change is clean and correct and it checks out fine in the browser, you setup the branches of the PR correctly and described your work,  Thank you!

**Pull request merged**
