### PR TITLE
Add github-handle for Michael Morgan in design-systems.md #7291

### LINKED ISSUE #7291: Add github-handle for Michael Morgan in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Michael Morgan
```
with
```
- name: Michael Morgan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md?plain=1
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jmarinit**
Fixes #7291

### What changes did you make?
  - Added "github-handle" under "-name: Michael Morgan" 
 
### Why did you make the changes (we will use this info to test)?
  - We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
No visual changes to the website.

### CODE REVIEW

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@jmarinit Thank you for taking this issue. 
### Things you need to change: 

- [x] `Why did you make the changes (we will use this info to test)?` You need to explain why the change was needed. Please read the original issue.
- [x] On the title you need to assign the correct issue you fixed.  The issue don't match the branch name.
- [x] You also need to check why you are getting these unchecked 
"Pull Request Trigger / Check-For-Linked-Issue (pull_request) 
[Details](https://github.com/hackforla/website/actions/runs/10784866159/job/29909163733?pr=7428)
@github-actions
Set PR Labels / generate-labels-artifact (pull_request) F

**Comment by Thinking-Panda** [comment]
@jmarinit - please edit the PR description to properly link to the issue you worked on. Add a # to the front of the issue number.

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
EoD: Thurs Sept 12

**Comment by t-will-gillis** [comment]
Hi @jmarinit Just to clarify, the top of the PR template includes the words:
  ```  
  Fixes #replace_this_text_with_the_issue_number
  ```  
The word "Fixes" is required- this is the reason that the two checks "Set PR Labels" and "Pull Request Trigger" are failing. Please edit your description to:
  ```  
  Fixes #7291
  ```  
Thank you

**Review by ramitaarora — CHANGES_REQUESTED** [review]
Looks good!
- You made a pull request from the correct branch
- You used spaces, not tabs
- The correct changes are showing up in your branch

All it seems you need to do is add "Fixes" to the beginning of your pull request, and then I can approve.

Good work, and thank you for your contribution!

**Comment by jmarinit** [comment]
> Looks good!
> 
> * You made a pull request from the correct branch
> * You used spaces, not tabs
> * The correct changes are showing up in your branch
> 
> All it seems you need to do is add "Fixes" to the beginning of your pull request, and then I can approve.
> 
> Good work, and thank you for your contribution!

Thank you! I made the changes. Is that good now because it's still showing that it's failing the checks.

**Comment by codyyjxn** [comment]
Nice you need to request another review on the reviewers tab.

**Review by codyyjxn — APPROVED** [review]

**Review by ramitaarora — APPROVED** [review]

**Comment by daras-cu** [comment]
@jmarinit well done with this issue! Just a reminder, you do not need to assign yourself to pull requests when you open them, only the original issue.

**Pull request merged**
