### PR TITLE
Replaced 'Github' with 'GitHub' in tech-work-experience.md

### LINKED ISSUE #7414: Replace `Github` with `GitHub` in _projects/tech-work-experience.md
### Overview
We need to replace instances of `Github` and `github` with `GitHub` so that we display the company name correctly, and test the changes to ensure the behavior and appearance of any and all related webpages are unchanged.    

### Details
The instance of "Github" that you are changing seems to relate to the creation of this button on the https://www.hackforla.org/communities-of-practice page 
 
that is created by https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html.

### Action Items
- [x] Open `_projects/tech-work-experience.md` in your IDE
- [x] Change
```
  - name: Github
```
to
```
  - name: GitHub
```
- [x] Find all the files that are connected to this change.  (e.g., if its a yml or md file, what files or scripts use the data stored in that file).  And document briefly how they work together.
- [x] Define where you expect the change to show up on the website (e.g., the footer of the website).  Can be on multiple pages
- [x] Write a test procedure, in a comment, and then use it to test the change.  Include a link to this comment in your PR.
- [x] Add/commit changes then create a PR as usual.  Document the test procedure in the Pull Request.  

### Resources
- This issue resulted from #6161

### Merge Team
- [x] After closing this issue, check off the dependency in #6161.  If all dependencies have been completed, close #6161

### PR DESCRIPTION
**Pull request by pluto-bell**
Fixes #7414

### What changes did you make?
  - Replaced `- name: Github` with `- name: GitHub` in `_projects/tech-work-experience.md`

### Why did you make the changes (we will use this info to test)?
  
  - To fix display issues stemming from `name:` variable 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2024-10-13 at 5 10 56 PM
Screenshot 2024-10-13 at 5 11 07 PM
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-10-13 at 5 10 43 PM
Screenshot 2024-10-13 at 5 11 15 PM
</details>

### Connected Files
The `_projects/tech-work-experience.md` is referenced by `_layouts/project.html` which dynamically creates each project card. 
The `_projects/tech-work-experience.md` file is also referenced by `current-projects.js` which dynamically creates a display card for each project.

### Test Procedure
Follow [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) in order to clone the feature branch
- Compare the Tech Work Experience card between http://localhost:4000/projects and https://www.hackforla.org/projects/. More specifically, compare the link elements.

- Similarly, compare the Tech Work Experience card between http://localhost:4000/projects/tech-work-experience and https://www.hackforla.org/projects/tech-work-experience. More specifically, compare the link elements.

### CODE REVIEW

**Comment by 8alpreet** [comment]
ETA: EOD Oct 16
Availability: 3pm - 7pm, Mon - Fri

**Review by codyyjxn — CHANGES_REQUESTED** [review]
Hi @pluto-bell,
Thank you for taking the time to work on this issue!

### Things that went well:
- The issue was correctly linked.
- The right file was modified.
- You applied the necessary labels.
- Including the before-and-after screenshots was very helpful, making it easy for others to review the changes.


### Areas for improvement:

- The branch name could be updated. There's no need to include "pluto" twice. A better option would be `replace_Github_with_GitHub-7414`.

Please feel free to reach out if you have any questions or need further clarification. Thanks again for your valuable contribution!

**Comment by daras-cu** [comment]
@codyyjxn thanks for your review! The branch name may be a little redundant but there is no way to change it without closing this pull request and opening a new one, and the guidelines about branch names are more suggestions than hard and fast rules. If everything else looks good let's approve this PR as is and @pluto-bell can keep your feedback in mind for future issues.

@k-cardon please leave a comment with your availability and ETA if you are still planning to review this issue.

**Comment by k-cardon** [comment]
ETA: EOD Oct 17
Availability: evenings, weekends

**Comment by pluto-bell** [comment]
@codyyjxn I see, I didn't realize it was configured to automatically add my user name, on my end the branch was just: `pluto/...`

Now I know it'll be taken care of for me (:, thanks for the point out.

**Review by k-cardon — APPROVED** [review]
Everything looks correct here! Code is changed correctly, text shows up properly on the development server on both pages, pull request is detailed yet concise. Thanks!

**Comment by codyyjxn** [comment]
> @codyyjxn I see, I didn't realize it was configured to automatically add my user name, on my end the branch was just: `pluto/...`
> 
> Now I know it'll be taken care of for me (:, thanks for the point out.

No Problem. Please request a review so I can approve this tonight.

**Review by 8alpreet — APPROVED** [review]
Hi @pluto-bell,

Great job on this issue! Tracking down the right files in this project can be difficult but you found the right files that use this variable. I tested your changed locally and it looks good! Both the project card in the projects page and the project specific page now display **GitHub**.

Things you did well:
* PR title is informative and concise
* comment includes "Fixes..."
* What section is answered well
* Screenshots clearly show the change
* You correctly identified the connected files
* You changed only the appropriate line of code

What could be improved:
1. Why section: the why section is not entirely accurate. This change isn't due to display issues, rather it's to unify the presentation of the name "GitHub" across the website. We don't want to display "Github" which is not how the company spells their name.
2. File name mentions: it would be nice to have full path `assets/js/current-projects.js` instead of `current-projects.js`. This is not a big deal, but we have many directories and it can be hard to find files so having the full path makes things easier.
3. The branch naming has already been addressed. However, a small clarification is necessary. Your name is not being added to the branch, your GitHub handle is being displayed as the **source** of the branch. For example, it says "commit into hackforla:gh-pages" to inform us that the commit will be merged into gh-pages which belongs to the "hackforla" organization's GitHub handle.

**Comment by 8alpreet** [comment]
@pluto-bell, @codyyjxn

I would like to mention something which Bonnie mentioned at yesterday's (Oct 15) dev meeting. When someone doesn't name the branch correctly, we don't need to have them rename the branch and make a new PR. We can leave feedback and they can do better next time.

It looks like you too are already on board with this idea, but I thought I would mention it just to be safe.

@pluto-bell, I already re-requested a review form @codyyjxn. However, I think the old "requested changes" needs to be dismissed. I could do it for you, but I thought it best to leave it to you.

**Review by codyyjxn — APPROVED** [review]

**Pull request merged**
