### PR TITLE
Add J Pham to Website Team

### LINKED ISSUE #6112: Update Project Profile: Add J Pham to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: J Pham
    github-handle: jphamtv
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U064FRUF893'
      github: 'https://github.com/jphamtv'
    picture: https://avatars.githubusercontent.com/jphamtv
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by elliot-d-kim**
Fixes #6112 

### What changes did you make?
  - Added J Pham's details to the _projects/website.md as specified in issue

### Why did you make the changes (we will use this info to test)?
  - To keep list of website team members on HfLA website up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by njackman-2344** [comment]
Availability: Tuesday 7pm-10pm 1/23, Wednesday 5pm-10pm 1/24, Friday 5pm -10pm

ETA: Friday 1/25 EOD

**Comment by LRenDO** [comment]
Hi @mademarc! When you have a minute, please add your ETA and Availability. Thanks!

**Review by jphamtv — APPROVED** [review]
Hey @elliot-d-kim , the pull request is done with the correct branch, and the issue is linked correctly. The summaries of changes are clearly communicated, and the provided screenshots are great examples of the changes. I've confirmed the updates on the website via Docker are accurate. Great work on the issue and pull request!

**Comment by mademarc** [comment]
Review ETA: 1/25/2024
Availability: 7:14PM

**Review by mademarc — APPROVED** [review]
Hey @elliot-d-kim  great job in adding the j pham info on the lines 87-93 on this issue and @LRenDO the ETA is there.

**Review by njackman-2344 — APPROVED** [review]
Very Nice @elliot-d-kim 

The code in .md and the branch look good. I see the visuals are changed and reflect @jphamtv 's info.

Awesome!! Thank you.

**Pull request merged**
