### PR TITLE
Sponsorlinks 1167

### LINKED ISSUE #1167: Turn the About Page sponsor icons into links
### Overview
We need to add links to our About page sponsors to give them proper credit 

### Action Items
- [ ] Add a link to each sponsor on the [About page](https://www.hackforla.org/about) sponsors section- these should be exactly the same links as in the [Home page](https://www.hackforla.org/) sponsors section

### Resources/Instructions
[About Us page](https://www.hackforla.org/about) (scroll to bottom for Sponsors)
[Home page](https://www.hackforla.org/) (scroll to bottom for Sponsors) 

Screen Shot 2021-03-06 at 10 00 43 PM

### PR DESCRIPTION
**Pull request by efrenmarin45**
Fixes #1167

### CODE REVIEW

**Review by akibrhast — CHANGES_REQUESTED** [review]
It seems that you have deleted the folder called `website` .
This should not have been deleted in this pull request.
- [ ] Ensure that the pull request has only 1 file changed `about.html`

**Comment by efrenmarin45** [comment]
I didn't delete anything, I only added the fix. The file changed has no value to it it's an empty file from what the commit history shows. Do you have any suggestions on how to fix this if it needs to be changed before merging?

**Comment by akibrhast** [comment]
@drubgrubby @jbubar What is the reason behind the existence of the directory `website` in the root of this repo?
Can it be deleted? Is it ok to merge this pull request?

**Review by akibrhast — APPROVED** [review]
Everything Looks good,
it seems like there is no reason behind the website directory.

**Pull request merged**
