### PR TITLE
my other branch was having a lot of git issues so I made a new branch

### LINKED ISSUE #3843: Create dependabot.yml file for dependabot to create pull requests
### Overview

GH Dependabot has been enabled to issue alerts for vulnerabilities and security. Therefore we need a configuration file, dependabot.yml, to create pull requests so that we maintain up to date security in our repo.

### Action Items

- [x] Read [configure dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [x] Read #3598 to understand HfLA's decision for implementing dependabot
  - [x] See associated [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- [x] Create a dependabot.yml file in the [.github](https://github.com/hackforla/website/tree/gh-pages/.github) and configure the file as per the instructions given in 1st link

### Resources/Instructions

- [Enabling Dependabot Version Updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [Configuration Options for Dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- ER for Decision Record: https://github.com/hackforla/website/issues/3598
- [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- See previous work done here: #4102

### PR DESCRIPTION
**Pull request by kurikurichan**
Fixes #3843 

### What changes did you make and why did you make them ?

- Created a dependencies.yml file, following the instructions for Github Actions that GH provided
- Updated the pull request to make the file in the correct location (.github)
- Added instructions for NPM, Docker, & GH Actions
- I have not tested this yet, we can use an outdated dependency probably to test it 
- There were a lot of git issues with the old branch so I made a new one

### CODE REVIEW

**Comment by blulady** [comment]
ETA: 1/2 hours
availability: today

**Comment by blulady** [comment]
I have switched to kurikurichan-gh-dependabot-3843 branch in my GitHub Repo. I switched the interval to daily. I enabled GitHub Dependabot in the repo. I am currently waiting a day to see if it works. 
ETA: 1/2 hours
availability: Tomorrow

**Comment by kurikurichan** [comment]
@blulady, thanks for reviewing this PR. Do I have to do anything else for now? This is my first issue so I don't know if I'm allowed to assign myself to another issue yet

**Review by blulady — CHANGES_REQUESTED** [review]
@kurikurichan  Hey, so I initially I could not get this to work but after I removed `name: Dependabot pull requests` it started working. So I am requesting that you change that and see if you see anything change locally. And then, of course, modify the pr.

**Comment by blulady** [comment]
Hey so no you can't open a new pr until this one is closed but you can (and should) review other volunteer's PR's while you are waiting/working on this one.

**Comment by blulady** [comment]
> @blulady, thanks for reviewing this PR. Do I have to do anything else for now? This is my first issue so I don't know if I'm allowed to assign myself to another issue yet

@kurikurichan  Hey so no you can't open a new pr until this one is closed but you can (and should) review other volunteer's PR's while you are waiting/working on this one.

**Comment by jdingeman** [comment]
Hello @kurikurichan - please provide us with an update on this pull request. Thanks!

**Comment by blulady** [comment]
> Hello @kurikurichan - please provide us with an update on this pull request. Thanks!

@jdingeman I slacked her last week, no response.

**Comment by ExperimentsInHonesty** [comment]
@kurikurichan, 

@blulady wrote to you on March 8th with changes you needed to make to your PR. You have not made them yet, so we can't accept it. If you don't update the PR or get back to us with questions on it by 2023-03-30 we will close the PR and unassign you from the issue.  Thank you for your understanding.

**Comment by blulady** [comment]
Dev seems to have abandoned PR. Placed back into Backlog

**Pull request closed without merging**
