### PR TITLE
Update Project Profile: Add Srishti Gupta to Expunge Assist Page

### LINKED ISSUE #7703: Update Project Profile: Expunge Assist Add Srishti Gupta
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Srishti Gupta
    github-handle: srishti-gupta-me
    role: Product Manager, UX Content
    links:
      slack: https://hackforla.slack.com/team/U07FF4C4YFQ
      github: https://github.com/srishti-gupta-me
    picture: https://avatars.githubusercontent.com/srishti-gupta-me
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Expunge Assist page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/expunge-assist
[^3]: initiating ER: https://github.com/hackforla/website/issues/7580#issue-2579554525

### PR DESCRIPTION
**Pull request by katiejnete**
Fixes #7703  

### What changes did you make?
  
  - Added project profile Srishti Gupta lines to the leadership variable in expunge-assist markdown file `_projects/expunge-assist.md`

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of current project team members under Expunge Assist up-to-date

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by mugdhchauhan** [comment]
Review ETA: 22 Nov 2024 @ 8 PM (GMT)
Availability: Daily @ 6 PM - 8 PM (GMT)

**Comment by trimakichan** [comment]
Review ETA: Nov 22nd, 6 PM
Availability: 10 AM to 3 PM (M-F, PST)

**Review by mugdhchauhan — CHANGES_REQUESTED** [review]
Hey @katiejnete, thank you for your Pull Request!

### Things that went well
- The Pull Request is done with the correct branch. 
- The issue is linked well in the Pull Request.
- What changes you made and why are clear in the PR post.
- Your Availability and ETA are provided in the issue.
- The information for Srishti Gupta is added in the correct file as provided in the issue.
- Before and after screenshots show these changes. 
- I can see these changes in my local environment. 
- CodeQL alerts have been checked.

###  Things to change

- [x] Comments on the changes in the Pull Request: consider using backticks ``(`)`` to enclose the file path such as `_projects/expunge-assist.md`.

- [x] The correct slack for Srishti Gupta is https://hackforla.slack.com/team/U07FF4C4YFQ. Please update the code with this Slack URL. This also needs to be corrected in the original issue.

- [x] Try using http://localhost:4000 rather than 0.0.0.0:4000 for viewing the changes in your local environment.

- [x] The additional tabs in the provided screenshots are not needed. You can take the screenshot of the page in separate window or the specific visual change of the site.

Thank you for your contribution! Please feel free to ask if you have any questions. After making these changes re-request a review from me.

**Review by trimakichan — DISMISSED** [review]
Great job, @katiejnete!

- The PR is created with the correct branch.
- The branch name accurately describes the work done and includes the issue number.
- The issue is linked correctly.
- The "What" and "Why" sections are clear and concise.
- Before-and-after screenshots are provided to demonstrate the changes.
- CodeQL alerts have been checked.

Thank you for your contribution! Keep up the great work!

**Review by rachelcorawood — COMMENTED** [review]
**Things that went well:**
-Your pull request is done in the correct branch
-The issue is linked correctly
-You clearly understand the issue
-The changes are visible in the browser and images are clear

Things to Update: 

- [x] The correct slack for Srishti Gupta is https://hackforla.slack.com/team/U07FF4C4YFQ. Please update the code with this Slack URL. This also needs to be corrected in the original issue.

**Comment by mugdhchauhan** [comment]
Review ETA: 23 Nov 2024 @ 10 AM (GMT)
Availability: Daily @ 6 PM - 8 PM (GMT)

**Review by mugdhchauhan — APPROVED** [review]
@katiejnete Thank you for making the changes and re-requesting a review from me. Looks good! I approve this PR.

**Comment by t-will-gillis** [comment]
Great job @katiejnete with the PR and working with the reviewers to make the edits.
Kudos to @mugdhchauhan for a thorough review and esp. for noticing and correcting the Slack ID! This is easy to miss.

**Review by trimakichan — APPROVED** [review]
The links are all working.

**Comment by mugdhchauhan** [comment]
Thank you @t-will-gillis

**Comment by codyjohnsontx** [comment]
Review ETA: 24 Nov 2024 @ 12am (CST)
Availability: This week, Monday 9-11am, Tuesday 10-6, Friday 10-6

**Comment by codyjohnsontx** [comment]
Hey @katiejnete, thanks for the Pull Request!

Highlights:

The PR is targeting the correct branch.
The issue is properly linked.
Changes and their reasoning are clearly documented.
Availability and ETA are detailed in the issue.
Information for Srishti Gupta is added to the correct file.
Before/after screenshots effectively showcase the updates.
CodeQL alerts have been reviewed.
All links are working as expected.
Great work! 🎉

**Review by codyjohnsontx — APPROVED** [review]
Hey @katiejnete, thanks for the Pull Request!

Highlights:

The PR is targeting the correct branch.
The issue is properly linked.
Changes and their reasoning are clearly documented.
Availability and ETA are detailed in the issue.
Information for Srishti Gupta is added to the correct file.
Before/after screenshots effectively showcase the updates.
CodeQL alerts have been reviewed.
All links are working as expected.
Great work! 🎉

**Comment by belunatic** [comment]
Review ETA: 25 Nov 2024 
Availability: 4-5 Monday/ Tuesday

**Review by belunatic — APPROVED** [review]
@katiejnete Amazing job, all look good and also thank you for taking care of the changes point out by others.

Keep up the good work!!

**Comment by mchait18** [comment]
Review ETA: 3:15 PM 11/25/2024
Availability: 9-3PM Monday-Thursday EST

**Review by mchait18 — APPROVED** [review]
Thank you for working on this issue, [katiejnete](https://github.com/katiejnete)!

You're doing these right:
- The branch you made the change on is correct
- The linked issue (original issue) number is included
- The content required to add is accurate
- The before / after screenshot is helpful to display the change

Great job!

**Comment by dvernon5** [comment]
Review ETA: 7:00pm PST 11/26/2024
Availability: 9AM - 6PM Tuesday & Wednesday of this week.

**Review by dvernon5 — APPROVED** [review]
Hello @katiejnete
Branch name looks good.
The code changes look perfect.
The issue is linked correctly
CodeQL alerts are good
The content added is correct
Before and After photos look stunning.

Everything looks fantastic. Great job

**Pull request merged**
