### PR TITLE
update alt text for design systems img in md #3986

### LINKED ISSUE #3986: Design Systems: Update alt text for Design Systems image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Design Systems` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/design-systems.md`:

**From:**
```
Hack for LA logo and the title of the project, Design Systems
```

**To:**
```
Design Systems
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/design-systems

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/design-systems.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md
- This issue is part of epic #3866 

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by MicahBear**
Fixes #3986 

### What changes did you make and why did you make them ?

  - changed the image alt property value within _projects/design-systems.md to Designs Systems

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- no visual changes

### CODE REVIEW

**Comment by KazushiR** [comment]
Review ETA: 2/25/23
Availability: Flexible

**Comment by nicolettedmabeza** [comment]
Review ETA: 2/24/23
Availability: 3pm-5pm PST

**Comment by MicahBear** [comment]
@KazushiR and @nicolettedmabeza, I just realized my prettier was on for the new workspace I created.  The line of code needed for review is line 9.
Prettier has been disabled moving forward.

**Comment by bootcamp-brian** [comment]
Review ETA: 12:15pm
Availability: Today until 6pm

**Review by bootcamp-brian — APPROVED** [review]
It looks to me like you made the requested changes to the code and after inspecting the projects page in my browser and comparing it to the live site it looks like the change has been reflected in the html successfully without anything breaking so good job.

And thanks for recognizing what happened with prettier and leaving a comment to clarify things.

**Comment by KazushiR** [comment]
@MicahBear Hello Micah. Apologies on the late reply. I did take a look and everything looks good. I do see however that you did not check off the action-item within the issue that was created. Once you check that off, I will go ahead and approve of the changes. Please let me know if you have anymore questions.

**Comment by MicahBear** [comment]
@KazushiR, I appreciate the call to that action item. No worries. The extra time allowed me to look at my issue again.  Thanks for the review
@bootcamp-brian, I appreciate the feedback.

**Review by KazushiR — APPROVED** [review]
Everything looks good. Congradulations on your review.

**Review by nicolettedmabeza — APPROVED** [review]
Pull request is from the correct branch. Source code is clean and applicable. After inspecting website on my browser, changes are reflected and does not break site. Thanks for clarifying the changes made and checking off the action items on the issues page. Great job!

**Pull request merged**
