### PR TITLE
Update Project Profile: Add Ren Demeis-Ortiz to Website Team

### LINKED ISSUE #4920: Update Project Profile: Add Ren Demeis-Ortiz to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the end of the `leadership` variable
```
  - name: Ren Demeis-Ortiz
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U059K7A1VFB
      github: 'https://github.com/LRenDO'
    picture: https://avatars.githubusercontent.com/LRenDO
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by DeviantSchemist**
Fixes #4920

### What changes did you make?
  - Add new team member's name, role, slack, github, picture links
  - Add above information to the leadership variable in the website.md file in the projects folder
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

HackForLA Issue #4920 Before

</details>

<details>
<summary>Visuals after changes are applied</summary>

HackForLA Issue #4920 After

</details>

### CODE REVIEW

**Comment by whitneywind** [comment]
Review ETA: 7/22
Availability: 5-7pm 7/21

**Comment by adrianang** [comment]
@DeviantSchemist I was just checking PRs and I noticed that you made yourself an assignee on your own pull request, so I went ahead and removed it as doing so is not really needed/accurate (you generally won't review your own PR). You'll still get credited for this pull request once it is merged — thanks in advance! 😄

**Review by whitneywind — APPROVED** [review]
Hey, nice job working on this issue. You committed to and from the correct branches, added the necessary text to the file, and your PR is descriptive. Visually, the changes look the same on my machine as they do in your screenshots (taking into account a merge from this morning that removed someone from the list). 

I noticed that in the issue instructions the slack and github links have single quotes while yours don’t, but looking at the current file it appears that the use of quotes in the file is inconsistent, doesn't make a visual impact, and that your choice is consistent with the most recent entries, so I'm approving. Thanks you for taking up this issue!

**Review by LOSjr4 — APPROVED** [review]
Description of what was done with visuals included are good. The added information is in the correct format. The links go to their intended place. Docker is showing the added member correctly.
Good work and thank you for handling this issue @DeviantSchemist .

**Pull request merged**
