### PR TITLE
Update website.md, remove Mario Anonini, #7459

### LINKED ISSUE #7459: Update Project Profile: remove Mario Antonini from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Mario Antonini
    github-handle: 
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06MTPZ67V3'
      github: 'https://github.com/marioantonini'
    picture: https://avatars.githubusercontent.com/marioantonini
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by codyjohnsontx**
Fixes #7459

### What changes did you make?
  
  - Delete Mario Anonini and relevant data from HackforLA website
  - Current Project Team Page
  

### Why did you make the changes (we will use this info to test)?
  
  - To keep list of Current Project Team members up to date 
 
<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before
remove-Mario-Antonini-(before)-7459

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After
remove-Mario-Antonini-7459
</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
Review ETA: 11/15/2024 Friday
Availability: 6-10 PM Weekdays (EDT)

**Review by siyunfeng — CHANGES_REQUESTED** [review]
Thank you for working on this issue, @codyjohnsontx !

### You're doing these right: 
- The branch you made the change on is correct
- The linked issue (original issue) number is included
- The content required to remove is accurate
- The CodeQL Alerts are checked
- The after screenshot is helpful to display the change

### Changes you need to make: 
- [x] Address the questions from HackforLABot in the original issue (Availability and ETA)
- [ ] Fix the unnecessary changes and submit your PR again (It could be caused by the formatting tool in your IDE, such as prettier)
- [x] Fix the before-and-after screenshots section (The images are not showing)

You can re-request me to review your PR once you make the changes. Feel free to reach out if you have any questions.

**Comment by codyjohnsontx** [comment]
Availability for this week: Friday 4-6, Saturday 10-4, Sunday 10-4

My estimated ETA for completing this issue: 30 minutes to 1 hour

**Review by siyunfeng — APPROVED** [review]
Nice job fixing the quotation marks in the file, @codyjohnsontx .

Things to improve:
- You only need to address your availability and ETA in the original issue (the linked issue you mentioned in your PR https://github.com/hackforla/website/issues/7459)
- Move the before-and-after screenshots to this section `Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)`
- Check the changes requested by the reviewer once you make the changes

Other than these, everything looks good. Thank you for your contribution!

**Comment by DakuwoN** [comment]
Review ETA: 10PM 11/16/24
Availability: Everyday after 10:30AM CST

**Comment by mmcclanahan** [comment]
Nice Work @codyjohnsontx !
Proper into and from branches
Clear and simple what and why
Correctly removed the team members info 

Thanks for the PR!

**Review by mmcclanahan — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Hey @codyjohnsontx FYI- you do not need to assign yourself to your own PRs

**Pull request merged**
