### PR TITLE
alt text for 17 partnerships updated

### LINKED ISSUE #3399: Update alt text for Partnerships image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-sustainability.html`, change the following alt text

From
```
Partnerships for the goals goal logo
```

To
```
17 Partnerships For The Goals
```

- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/about-page/about-card-platform.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a83dd650b664618ff2352b2fb93e8ae4acfb402b/_includes/about-page/about-card-platform.html#L77

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by chrismenke45**
Fixes #3399 

### What changes did you make and why did you make them ?

For the 17 partnerships image:
  -I updated the alt to "17 Partnerships For The Goals"

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes were made to the site.

### CODE REVIEW

**Comment by ghost** [comment]
Review ETA: 12 AM 1/25/23
Availability: Open

**Review by ghost — APPROVED** [review]
Hello Chris, good job working on this issue. 

You have successfully updated the alt text.

**Comment by d-perez-8** [comment]
ETA: 1 hour 
Availability: Weekdays 3-5pm PST

**Review by d-perez-8 — APPROVED** [review]
Thank you @chrismenke45 for working on this issue! You've correctly made the changes and the website doesn't break. Great work 👍

**Pull request merged**
