### PR TITLE
added github handle for Bonnie Wolfe

### LINKED ISSUE #7102: Add github-handle for Bonnie Wolfe in guides-teams.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/guides-team.md` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md?plain=1
Project Webpage: https://www.hackforla.org/projects/guides-team

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by mSharifHub**
Fixes #7102 

### What changes did you make?
  - line 12 added githubHandle

### Why did you make the changes (we will use this info to test)?
  -To reduce redundancy in the project file

### CODE REVIEW

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @mSharifHub great job-
- branches are good
- linked back to the original issue
- the code change is clean and appropriate

Quick comment:
- For "why did you make the changes", this is asking for the reason that the changes needed to be made, not the reason that you made the changes personally. So here a good response would be to look at the original issue and say something like: "To reduce redundancy in the project file" or similar

Thanks for working on this- please make this change and then this will be ready

**Comment by mSharifHub** [comment]
got it.

**Comment by mSharifHub** [comment]
> Hey @mSharifHub great job-
> 
>     * branches are good
> 
>     * linked back to the original issue
> 
>     * the code change is clean and appropriate
> 
> 
> Quick comment:
> 
>     * For "why did you make the changes", this is asking for the reason that the changes needed to be made, not the reason that you made the changes personally. So here a good response would be to look at the original issue and say something like: "To reduce redundancy in the project file" or similar
> 
> 
> Thanks for working on this- please make this change and then this will be ready

how can i link to the original pull request? and I think the original one is closed

**Comment by t-will-gillis** [comment]
@mSharifHub 
> how can i link to the original pull request? and I think the original one is closed

You can link back to the original PR using the number even though it is closed- However, is there a reason why you want to do this?

**Comment by mSharifHub** [comment]
I thought you asked me to do so. Disregard. So is anything else needs to be
done to be approved?

**Comment by t-will-gillis** [comment]
Yes- changing your response under "Why did you make the changes (we will use this info to test)?" from what you have currently to a response that is more appropriate. I suggested that you could change this to:
```  
- To reduce redundancy in the project file
```

**Comment by mSharifHub** [comment]
will do

**Comment by robertnjenga** [comment]
Review ETA:  07/21/2024
Availability: 10am - 12pm

**Review by robertnjenga — APPROVED** [review]
Hi @mSharifHub, Thanks for taking up this issue.
You covered all the basics: branches were done correctly, link to issue, concise description of what you did and why the changes were made.
Good job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
@mSharifHub One remaining item- please add the space between the dash and the text in:
`- To reduce redundancy in the project file`  


Once you do this,  the text will display correctly showing a bullet point

**Comment by jphamtv** [comment]
Hi @mSharifHub - Please make the requested text edit or provide your ETA for completing this task. Let us know if you're no longer able to work on this issue. Thanks!

**Comment by t-will-gillis** [comment]
@mSharifHub We have been waiting several weeks for you to complete this PR and we have not heard from you or gotten a status update, therefore we are closing this PR and returning the issue so that another dev can work on it.

**Comment by mSharifHub** [comment]
@t-will-gillis sounds good. I have been caught up with other things. But I'll start picking up other issues starting tomorrow. Thanks for heads up

**Pull request closed without merging**
