### PR TITLE
Add Allison Profile to 311 Data Page

### LINKED ISSUE #7542: Update Project Profile: 311 Data Add Allison Jeon
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Allison Jeon
    github-handle: allisonjeon
    role: UX Design Lead
    links:
      slack: https://hackforla.slack.com/team/U05JP94R9B7
      github: https://github.com/allisonjeon
    picture: https://avatars.githubusercontent.com/allisonjeon
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data
[^3]: initiating ER:  #7301

### PR DESCRIPTION
**Pull request by trimakichan**
Fixes #7542

### What changes did you make?
  - Added Allison's profile to the 311-data.md file in the _projects folder. 
 
### Why did you make the changes (we will use this info to test)?
  - To keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
  <summary>Visuals before changes are applied</summary>

update_project_profile_7542_before

</details>

<details>
  <summary>Visuals after changes are applied</summary>

update_project_profile_7542_after

</details>

### CODE REVIEW

**Comment by siyunfeng** [comment]
Review ETA: 10/26/2024 Sat
Availability: 6-10 PM Weekdays (EDT)

**Comment by terrencejihoonjung** [comment]
Review ETA: 10/28/2024, 11:59pmPST
Availability: 5pm - 12am PST, Fri-Sun, 5pm - 9pm Mon

**Review by siyunfeng — APPROVED** [review]
Nice job working on this issue, @trimakichan ! 

You provided your availability and ETA in the original issue, created a new branch to make the changes, and included the linked issue in your PR. 

The answers to `What changes did you make?` and `Why did you make the changes (we will use this info to test)?` are clear so our fellow developers would have a better understanding of the issue and your schedule. The changes you made are accurate. I appreciate that you provided the before-and-after screenshots to show the changes you made. 

**Improvement**:
- Name the branch with more specific details, such as `add-allison-jeon-profile-311-data-7542`

Thank you for your contribution!

**Review by codyyjxn — APPROVED** [review]
Hey @trimakichan great job on this issue. 

- The branch name is good with the issue number 
- The issue is linked correctly 
- The changes are displayed correctly 

One thing you need to do is on the original issue you need to tick one of the boxes that says : `Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:`

That will complete this issue. Thank you for your contribution. Keep it up!

**Review by terrencejihoonjung — APPROVED** [review]
Hi @trimakichan,

Looks great! Things you did well:
- branching naming to and from
- changes made and why they were made stated clearly
- visual before and after provided
- code changes are correct

Thank you for your contribution!

**Comment by trimakichan** [comment]
> Nice job working on this issue, @trimakichan !
> 
> You provided your availability and ETA in the original issue, created a new branch to make the changes, and included the linked issue in your PR.
> 
> The answers to `What changes did you make?` and `Why did you make the changes (we will use this info to test)?` are clear so our fellow developers would have a better understanding of the issue and your schedule. The changes you made are accurate. I appreciate that you provided the before-and-after screenshots to show the changes you made.
> 
> **Improvement**:
> 
> * Name the branch with more specific details, such as `add-allison-jeon-profile-311-data-7542`
> 
> Thank you for your contribution!

Thank you so much for taking the time to check this issue! Your advice on naming the branch is helpful. Thanks!

**Comment by trimakichan** [comment]
> Nice job working on this issue, @trimakichan !
> 
> You provided your availability and ETA in the original issue, created a new branch to make the changes, and included the linked issue in your PR.
> 
> The answers to `What changes did you make?` and `Why did you make the changes (we will use this info to test)?` are clear so our fellow developers would have a better understanding of the issue and your schedule. The changes you made are accurate. I appreciate that you provided the before-and-after screenshots to show the changes you made.
> 
> **Improvement**:
> 
> * Name the branch with more specific details, such as `add-allison-jeon-profile-311-data-7542`
> 
> Thank you for your contribution!

Thank you so much for taking the time to check this issue, @siyunfeng! Your advice on naming the branch is helpful. Thanks!

**Comment by trimakichan** [comment]
> Hey @trimakichan great job on this issue.
> 
> * The branch name is good with the issue number
> * The issue is linked correctly
> * The changes are displayed correctly
> 
> One thing you need to do is on the original issue you need to tick one of the boxes that says : `Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:`
> 
> That will complete this issue. Thank you for your contribution. Keep it up!

Thank you for checking, @codyyjxn! I checked the box you mentioned. The next step is just to wait for my pull request to be merged, correct?

**Comment by siyunfeng** [comment]
> > Hey @trimakichan great job on this issue.
> > 
> > * The branch name is good with the issue number
> > * The issue is linked correctly
> > * The changes are displayed correctly
> > 
> > One thing you need to do is on the original issue you need to tick one of the boxes that says : `Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:`
> > That will complete this issue. Thank you for your contribution. Keep it up!
> 
> Thank you for checking, @codyyjxn! I checked the box you mentioned. The next step is just to wait for my pull request to be merged, correct?

Yes, once this PR is merged, please fill out the info in `### 6 - PULL REQUESTS update` and comment on your skills issue.

If this is your first `good first issue`, you can move on to your 2nd `good first issue` after completing the `PULL REQUESTS update`.

**Comment by trimakichan** [comment]
> Hi @trimakichan,
> 
> Looks great! Things you did well:
> 
> * branching naming to and from
> * changes made and why they were made stated clearly
> * visual before and after provided
> * code changes are correct
> 
> Thank you for your contribution!

Thank you for checking! I appreciate you taking the time to do so, @terrencejihoonjung.

**Comment by trimakichan** [comment]
> > > Hey @trimakichan great job on this issue.
> > > 
> > > * The branch name is good with the issue number
> > > * The issue is linked correctly
> > > * The changes are displayed correctly
> > > 
> > > One thing you need to do is on the original issue you need to tick one of the boxes that says : `Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:`
> > > That will complete this issue. Thank you for your contribution. Keep it up!
> > 
> > 
> > Thank you for checking, @codyyjxn! I checked the box you mentioned. The next step is just to wait for my pull request to be merged, correct?
> 
> Yes, once this PR is merged, please fill out the info in `### 6 - PULL REQUESTS update` and comment on your skills issue.
> 
> If this is your first `good first issue`, you can move on to your 2nd `good first issue` after completing the `PULL REQUESTS update`.

Thank you for your quick reply and for describing the next step very clearly, @siyunfeng! I appreciate it.

**Comment by Thinking-Panda** [comment]
@trimakichan Thank you for working on this issue.

**Pull request merged**
