### PR TITLE
Add github handle field 

### LINKED ISSUE #7050: Add github-handle for Tien Yuan in heart.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Tien Yuan
```
with
```
- name: Tien Yuan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jazxbx**
Fixes #7050 
### What changes did you make?
  -Add github-handle: on heart.md file

### Why did you make the changes (we will use this info to test)?
  --This variable will eventually replace github and picture variables to reduce redundancy in the project file.

No visual changes to the website.

### CODE REVIEW

**Comment by andyphancode** [comment]
Availability: Throughout week
ETA: 6/25 EOD

**Review by andyphancode — CHANGES_REQUESTED** [review]
- Changes in code appear correct
- Branching is correct
- PR summary contains necessary info 

Everything looks good! Just wanted to ask for a more specific title for the Pull Request just for more organized book keeping. Maybe something like "Added github-handle to Tien Yuan section".

**Comment by mrodz** [comment]
Availability: every day 9AM-8PM
ETA: 6/25 7:45

**Review by mrodz — CHANGES_REQUESTED** [review]
Good job!

- Good source branch and destination branch
- Linked issue number
- No visual changes
- The new YAML property uses a delimiter of whitespaces

I concord with @andyphancode that the name of the PR should include at least Tien Yuan's name. Once you rename the PR, make sure to re-request our reviews so that we can get your work merged!

Thanks for your time :)

**Comment by LRenDO** [comment]
Closing this as there were two issues for this change #7050 and #6941 and the PR for #6941 was just merged ( #7069 ). @jazxbx, apologies for the duplication of work. Please feel free to grab another first good issue.

**Pull request closed without merging**
