### PR TITLE
removed unused variable in getDayString

### LINKED ISSUE #7013: Resolve CodeQL Alert #114 - Generated by GHA
### Prerequisite

1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the new alert [(114)](https://github.com/hackforla/website/security/code-scanning/114) and either recommend dismissal of the alert or update the code files to resolve the alert.

### Action Items
- [x] The following action item serves to "link" this issue as the "tracking issue" for the CodeQL alert and to provide more details regarding the alert:
- [x] https://github.com/hackforla/website/security/code-scanning/114
- [x] In a comment in this issue, add your analysis and recommendations.  The recommendation can be one of the following: `dismiss as test`, `dismiss as false positive`, `dismiss as won't fix`, or `update code`.  An example of a `false positive` is a report of a JavaScript syntax error that is caused by markdown or liquid symbols such as `---` or `{%`
- [ ] **If the recommendation is to dismiss the alert:**
  - [ ] Apply the label `ready for dev lead` 
  - [ ] Move the issue to `Questions/In Review`
- [x] **If the recommendation is to update code:**
  - [x] Create an issue branch and proceed with the code update
  - [x] Test using docker to ensure that there are no changes to any affected webpage(s)
  - [x] Proceed with pull request in the usual manner

### Resources/Instructions
- [HfLA website: CodeQL scan alert audits - issue 5005](https://docs.google.com/spreadsheets/d/1B3R-fI8OW0LcYuwZICQZ2fB8sjlE3VsfyGIXoReNBIs/edit#gid=193401043)
- [Code scanning results page](https://github.com/hackforla/website/security/code-scanning)
- [CodeQL query help for JavaScript](https://codeql.github.com/codeql-query-help/javascript/)
- [How to manage CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270 )

This issue was automatically generated from the codeql.yml workflow

### PR DESCRIPTION
**Pull request by pluto-bell**
Fixes #7013 

### What changes did you make?
  - Removed an unused variable in function `getDayString` in file `right-col-content.js` 

### Why did you make the changes (we will use this info to test)?
  - To make the code readable, clear and uncluttered.
  - This fix makes the function easier to understand for developers moving forward.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes made

### CODE REVIEW

**Comment by mrodz** [comment]
**Availability**: Weekdays 6:30-9PM, Weekends 9AM-5PM
**ETA**: 13:15 8/17

**Review by mrodz — CHANGES_REQUESTED** [review]
Hi @pluto-bell, your code changes look good!
- Removed unused variable
- Documented changes
- Explained reasoning for changes
- Resolves CodeQL alert
- Correct `to` branch
- Linked issue(s)

However, I believe you misread the instructions on the CodeQL issue:
> Create an issue branch and proceed with the code update

This does not mean creating a new issue on top of the CodeQL issue and merging a PR to close two separate issues. Instead, make one branch associated with #7013 and develop your patch on there.

Can you please apply your changes to a branch associated with #7013, and close the extra issue (#7295)?

---
Here are some examples of merged PRs that fix CodeQL alerts:
- #6824 
- #6822
- #6517

---

Re-request my review once you've got this done.

**Comment by pluto-bell** [comment]
Thanks @mrodz! I did misread the instructions, and that makes way more sense. I've closed out issue #7295 and editing the description of this PR.

Since the branch name is already linked to issue #7013 ("resolve-codeQL-alert#114-issue#7013") I didn't change anything there. If I'm misunderstanding what you're looking for, please let me know.

**Review by mrodz — APPROVED** [review]
I see you closed the extra issue—nice! Thanks for cleaning it up. Everything looks good to me and I think you're in a good state to merge. 

For future issues, you don't need to include the `#` before any issue numbers. Also, you don't need to include the CodeQL alert number as prior PRs do not include it, and its CodeQL number can be obtained from the tracking issue.

_Merge team, see my previous review. I am approving this issue as while the branch name does not explain the fixes, previously-merged CodeQL patches also do not relay changes in the branch name._

**Comment by jphamtv** [comment]
Hey @ihop-56, Could you please provide your estimated time for review and your availability? Thanks!

**Comment by ihop-56** [comment]
Aug 23 9 PM ET

**Review by ihop-56 — APPROVED** [review]
Hi @pluto-bell, I reviewed the changes, and everything looks great. The unused variable in the `getDayString` function was correctly removed. There are no visual changes to the website, and the code is cleaner as a result. Nice job!

**Pull request merged**
