### PR TITLE
issue 2816 content-type

### LINKED ISSUE #2816: Edit content field and remove type field from commofpract.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/commofpract.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/commofpract.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/commofpract.yml#L4
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/commofpract.yml#L11

### PR DESCRIPTION
**Pull request by Mattre7**
Fixes #2816

### What changes did you make and why did you make them ?

  - Changed the content field in the .yml files (those found in _data/internal/credits) to content-type, and removed the type field
  - This was done in order to optimize the code and remove redundancies

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 5 Hours
ETA: EOD 2022-07-26

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-27

**Comment by BeckettOBrien** [comment]
@Mattre7 Could you please link the issue number where it says `Fixes #replace_this_text_with_the_issue_number`, for example: `Fixes #2816`

**Comment by Mattre7** [comment]
> @Mattre7 Could you please link the issue number where it says `Fixes #replace_this_text_with_the_issue_number`, for example: `Fixes #2816`

Done

**Comment by arpitapandya** [comment]
> > @Mattre7 Could you please link the issue number where it says `Fixes #replace_this_text_with_the_issue_number`, for example: `Fixes #2816`
> 
> 
> 
> Done

Thank you

**Review by BeckettOBrien — CHANGES_REQUESTED** [review]
It's very impressive that you fixed the issue for every file in the credits folder, but it looks like the issue only asked you to change `_data/internal/credits/commofpract.yml` and we'd like to make sure that any changes made in a pull request are inside the scope of their issue. Also, line 4 is supposed to be `content-type: image` and not `content-type: icon`. If you could update your branch to only change the one file and change `icon` to `image` on line 4, that would be great. Thank you!

**Comment by Mattre7** [comment]
> It's very impressive that you fixed the issue for every file in the credits folder, but it looks like the issue only asked you to change `_data/internal/credits/commofpract.yml` and we'd like to make sure that any changes made in a pull request are inside the scope of their issue. Also, line 4 is supposed to be `content-type: image` and not `content-type: icon`. If you could update your branch to only change the one file and change `icon` to `image` on line 4, that would be great. Thank you!

Heard. I will definitely be more careful reading the instructions in the future, apologies for that. I just updated that line in my branch, committed and pushed the changes. Will that update this pull request, or will I have to open a new one?

**Comment by BeckettOBrien** [comment]
Unfortunately, some of the changes to other files are causing merge conflicts, so you'll need to get rid of those changes before we can merge this PR. I'm not quite sure what the easiest way of doing that is because the changes are all grouped in one commit, so reverting it would also revert some of your work. If anyone else knows of a good way to fix this, please let me know.

**Comment by arpitapandya** [comment]
> Unfortunately, some of the changes to other files are causing merge conflicts, so you'll need to get rid of those changes before we can merge this PR. I'm not quite sure what the easiest way of doing that is because the changes are all grouped in one commit, so reverting it would also revert some of your work. If anyone else knows of a good way to fix this, please let me know.

I would suggest close this PR and delete the branch first. Also, make sure your gh-pages branch is updated with the latest changes(Go to your repo of website for hackforla & fetch the upstream with latest)then create a new branch and work on the issue and create a new PR by following the contribution guide and the issue you're working on..I think is the easy way🙂

**Comment by arpitapandya** [comment]
@Mattre7 if you need help or you're stuck, DM me on slack please

**Comment by Mattre7** [comment]
Closing this and opening a new one shortly

**Pull request closed without merging**
