### PR TITLE
Make checkbox text clickable

### LINKED ISSUE #1071: Refactor <span> elements on current projects dropdown menus to <label> elements
### Overview 
Currently, the dropdown menus on the "Current Projects" section of the homepage require a user to click directly on the checkbox. If each checkbox input element is wrapped in a label element, a user can also click on the text to select the checkbox.

### Details 
Here's a screenshot of the relevant code:

image

- [x] On line 159, a span element is created to describe the checkbox. This can be changed to a label element. May want to also change the variable name.
- [x] Line 163 can use the textContent node property rather than innerHTML
- [x] Line 193 should be changed if the variable name is changed.
- [ ] Line 192 should append to the new label element instead of the div element variable 'content.'

### Resources  
[Label element on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

> Associating a <label> with an <input> element offers some major advantages:
>  - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> - You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

### LINKED ISSUE #1319: Make Filter Dropdown Text Clickable
### Overview
For accessibility reasons, we want to make sure we can click on the dropdown text to activate the checkbox. We also want to ensure that the cursor pointer appears when hovering over the text.

### Action Items
- [x] Make sure dropdown text is clickable.
- [ ] Make sure pointer shows up when hovering over dropdown checkbox text.

### Resources/Instructions
image
https://www.hackforla.org/wins/?
https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins-filter-template.html

### PR DESCRIPTION
**Pull request by averdin2**
Fixes #1319  Fixes #1071 
- This PR fixes issues on the site where the presence of a span tag instead of a label was keeping users from selecting checkboxes by clicking on text. Both issues linked are related to this issue and are fixed.
- This PR also adds a pointer cursor when hovering over dropdown menus.

See the below gif for all functionality mentioned
<details>
<summary>Checkbox text clickable gif</summary>

label_click
</details>

### CODE REVIEW

**Review by erikaBell — COMMENTED** [review]
Looks good.

It appears some of these changes have created issues for the filter tags upon refresh though. Not sure if that should just be a separate issue.

<details>
<summary>Filter Tag bugs on refresh</summary>

https://user-images.githubusercontent.com/67438372/114466517-716be800-9b9d-11eb-966e-8b82f9232288.mov
</details>

**Comment by averdin2** [comment]
@erikaBell I am actually noticing this on the live site as well, so I don't think that changes I made are an issue. I will try to look into what is causing this though

**Comment by erikaBell** [comment]
> @erikaBell I am actually noticing this on the live site as well, so I don't think that changes I made are an issue. I will try to look into what is causing this though

Here is a video of my live site. Is your live site doing it on _all_ the filter list items? Or just some of them?
<details>
<summary>Live Site Filter Tag Bug</summary>

https://user-images.githubusercontent.com/67438372/114477886-ef39ee80-9bb1-11eb-8f5c-7ae5bb576b9f.mov
</details>

Only asking because Akib and I are aware there are some bugs with the filter tags live site during refresh, mainly for list items that contain: more than two words or have certain symbols such as a "/". Akib showed me it had to do with the URLparams not being set-up correctly. Here is a link that will take you to the part of Akib and I's conversation that relates to what I just mentioned, as well as the issue we created: [Issue # 1201](https://github.com/hackforla/website/issues/1353#issuecomment-814199013)

**Comment by averdin2** [comment]
@erikaBell I see, I'll mess around with the live site and with my local to see if I can figure out the issue you are seeing with my changes.

**Comment by erikaBell** [comment]
Good luck!~

**Comment by averdin2** [comment]
@erikaBell I figured it out. I forgot to remove previousSibling from the line in the screenshot below. Thanks for the catch Erika! I just pushed the changes.

image

**Review by erikaBell — APPROVED** [review]
Nice, looks good to me!

**Comment by erikaBell** [comment]
@averdin2, we are waiting on merging this so you can research your "pointer" question, yeah? Just double checking.

**Comment by averdin2** [comment]
@erikaBell I honestly think it could be merged and the "pointer" issue just be another issue should there be a want to change it. I am really just waiting for Danielle to take a look at the PR since I made changes to how the overall Dropdown works. I just want to make sure that is communicated to the UI/UX team.

**Comment by akibrhast** [comment]
@daniellex0

**Review by daniellex0 — APPROVED** [review]
SO sorry about the delay @averdin2 , crazy week- yes this is approved 👍

**Review by akibrhast — CHANGES_REQUESTED** [review]
@averdin2 Could you please remove the file _includes/currenlty-project.html from this PR . I believe that would resolve the merge conflicts. You should be able to do that by running `git restore _includes`

**Pull request merged**
