### PR TITLE
Add GHA Job to Issue Trigger Workflow that Adds Newly Created Issues to Project Board

### LINKED ISSUE #2306: GitHub Actions: Automatically move a newly created issue into the Project Board
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want newly created issues to automatically be placed in the Project Board.

### Action Items

- [x] Review the notes below to understand the GitHub actions architecture we are currently moving towards
- [x] This should be a new job under the ["Issue Trigger" workflow](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
    - [x] This job triggers when an issue is opened
    - [x] This job should have an if statement that triggers when the event name is "issues" and event action is "opened." 
        - if: ${{ github.event_name == 'issues' && github.event.action == 'opened'}}
    - [x] This job should run in parallel with the other action, ["Add-Missing-Labels-To-Issues"](https://github.com/hackforla/website/blob/f6df44e3200b477a753475264c945ef7d3e1b268/.github/workflows/issue-trigger.yml#L7)
      - [x] Essentially, the action should add the issue onto the Project Board AND run the action "Add-Missing-Labels-To-Issues"
  
### Pseudo-code

- [x] When an issue is opened
    - [x] Add the issue into the Project Board
    - [x] Place the issue into the "New Issue Approval" column (this action runs automatically with another GHA)

### Checks

- [x] Test in your local environment that it works
- [x] If a user creates an issue and does not add the issue to the Project Board, the GitHub action should automatically add the issue to the Project Board in the New Issue Approval Column
- [x] If a user creates an issue and adds it properly to the Project Board, the GitHub action should also move the issue to the New Issue Column in the Project Board if the user did not already do so
- [x] If the column the issue is going to has automation turned on, the GitHub action should still trigger and add the issue to the New Issue Approval column without causing any weird issues / side effects

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by adrianang**
Fixes #2306 

### What changes did you make?
  - Add new GHA job `Add-Issue-To-Project-Board` that moves newly created issues into the Project Board to the Issue Trigger workflow (`.github/workflows/issue-trigger.yml`) in GitHub Actions.

### Why did you make the changes (we will use this info to test)?
  - We want to implement an automation through GitHub Actions that automates adding newly created issues onto the Project Board, in order to organize all created issues in the repository and keep productivity high.
  - To test this pull request, reviewers must test this branch on their own fork of the website repo (high-level steps outlined below in Steps for Testing section) and create a copy of the HfLA Website Project Board (resource linked in step 2 of Steps for Testing section below).

### Steps for Testing

1. Check out this PR's branch on your local development environment.
2. Create a duplicate of the Project Board by following the directions outlined in [step 6 of HfLA's guide to GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board).
3. Create a personal access token that will allow the automation to work on your duplicated project board by following the directions outlined in [step 7 of HfLA's guide to GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board).
4. (While on this PR's branch) On line 83 of `issue-trigger.yml`, replace `secrets.HACKFORLA_BOT_PA_TOKEN` with `secrets.[NAME OF YOUR TOKEN]`. You can find the name of the token you created in step 3 at https://github.com/settings/tokens.
5. Commit this change and push this commit to the branch.
6. Push the branch to your fork of the website repository.
7. On GitHub, in your fork of the website repository (likely `[YOUR USERNAME]/website`), go to "Settings" and change the default branch from `gh-pages` to this PR's branch.
8. While in your fork on the website repository, go to "Issues" and create a new issue (any of the templates can be used).
9. Make sure that this issue **is not assigned** to a Project (in the right-column, the Projects section should be 'None yet'). Submit the new issue.
10. On your newly created issue, the issue should assign itself to the Project Board in the New Issue Approval column after a few seconds.
11. Create another issue (repeat step 8). This time, make sure that this issue **is assigned** to a Project (in the right-column, click the gear icon for the Project section and assign the issue to the Project Board). Submit the new issue.
12. On this newly created issue, the issue should already be assigned to the Project Board in the New Issue Approval column.
13. After testing and confirming that newly created issues are added to the Project Board, go back to the "Settings" on your fork of the website repository and change the default branch back to `gh-pages`.
14. Delete this branch from your fork of the website repository.

### CODE REVIEW

**Review by t-will-gillis — DISMISSED** [review]
Hey @adrianang Fantastic job! I tested this in my repo to confirm that when a new issue is opened, it is automatically added to the Project Board in the "New Issue Approval" column.

Only as a question: what do you think about moving this job/ "Add-Issue-To-Project-Board" as the first job on `issue-trigger.yml` starting on Line 7? This does not affect how the automation runs, but it seems to me that this could/should be the first step...

Great job again and thanks for working on this!

**Comment by adrianang** [comment]
@t-will-gillis Thank you for reviewing my pull request! I agree with you that this job would logically make most sense as the first job in the workflow and initially thought about inserting it on line 7, but I just ended up adding it to the end.

Should I go ahead and make a new commit to move the job up to line 7?

**Comment by t-will-gillis** [comment]
@adrianang 

> Should I go ahead and make a new commit to move the job up to line 7?

Sure, sounds good to me!

**Review by t-will-gillis — APPROVED** [review]
Hey @adrianang Changes look good! (I like that you added the comment also.)

Thanks for addressing this issue!

**Pull request merged**
