### PR TITLE
Update Img Alt Text In Jobs-For-Hope.md

### LINKED ISSUE #4013: Jobs for Hope: Update alt text for Jobs for Hope image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Jobs for Hope` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/jobs-for-hope.md`:

**From:**
```
LA county homelessness initiative logo.
```

**To:**
```
Jobs for Hope
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/jobs-for-hope

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/jobs-for-hope.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/jobs-for-hope.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by richardmundyiii**
Fixes #4013 

### What changes did you make and why did you make them?

  - Changed img alt from 'LA county homelessness initiative logo.' to 'Jobs for Hope'
  - Changed img alt text to adhere to the Web Content Accessibility Guidelines (WCAG)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

Only alt text is changed. No visual changes to the website.

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Availability: Tuesday and Thursday evenings
ETA: EOD 3/15/23

**Review by bzzz-coding — APPROVED** [review]
@richardmundyiii Thanks for working on this issue! I see that you made the PR from and to the right branches and that you changed the alt exactly as instructed in the issue. Good job!

**Comment by mademarc** [comment]
Review ETA: 3/15/23
Availability: 7:35 PM

**Review by mademarc — COMMENTED** [review]
Hey @richardmundyiii Well done on the changes over here.

**Comment by karengcecena** [comment]
Availability: Wednesday
ETA: 9pm 3/15/23

**Review by karengcecena — APPROVED** [review]
Good job @richardmundyiii! You correctly created the pull request with the correct information and the correct to and from branches for this issue, updated the alt text according to WCAG, and it all looks good on my local machine. Way to go!

**Comment by roslynwythe** [comment]
@drubgrubby were you going to review this PR?  If so, please let leave a comment with your Availability and ETA.  Thank you!

**Pull request merged**
