### PR TITLE
Update Home Unite Us Project Card

### LINKED ISSUE #2715: Update Project Profile: Home Unite Us
### Overview
As a product manager of Home Unite Us I want my project's details to be up to date on the HackforLA website

### Project card
https://www.hackforla.org/projects/home-unite-us

### Action Items

- [ ] Home Unite Us Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [ ] title
      - [x] description
      - [ ] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub hand
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [ ] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [ ] Site
      - [ ] technologies
      - [x] partner
      - [ ] tools
      - [x] status

### PR DESCRIPTION
**Pull request by jnmrles**
Fixes #2715 

### What changes did you make and why did you make them ?

  - Updated Project Description, Project Team, Project Tools, and Project site links

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-03-22 at 4 54 33 PM
Screen Shot 2022-03-22 at 4 54 44 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
Screen Shot 2022-03-21 at 10 15 58 PM
Screen Shot 2022-03-21 at 10 16 23 PM

  

</details>

### CODE REVIEW

**Comment by answebdev** [comment]
Review ETA: 3/24/2022 (end of day)
Availability: 3 hours

**Comment by Carlos-A-P** [comment]
Availability: 2 hrs
ETA: 3/23/2022

**Review by answebdev — APPROVED** [review]
@jnmrles Thank you for submitting your PR. For this issue, the listed leadership people were to be added to the Home Unite Us I project's details card, as well as removing the listed person. The description was also to be modified, the tools updated, as well as adding the https://homeunite.us/ URL for the site. I can see that you did all of this, and I was also able to see these changes in the browser, and go to the correct https://homeunite.us/ URL when clicking on the Site card. Great job with everything!

On a minor note, please add this PR to the Project Board. Thank you.

**Review by Carlos-A-P — APPROVED** [review]
@jnmrles Great job working on this issue! Everything looks great; I can see the updated members, tools, description, and links.

**Pull request merged**
