### PR TITLE
Add credit .yml file  to diversity, equity, inclusion image for redesigned homepage

### LINKED ISSUE #3353: Add credit for Diversity, Equity, Inclusion image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the Credits webpage is up to date.

### Details
From the Homepage Redesign Credits in Figma, here is a screenshot of the credit's information for reference:
    <details>
      <summary>Click here to see the screenshot of the Diversity, Equity, Inclusion credit in Figma</summary>
      
    </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `diversity-equity-inclusion.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Diversity, Equity, Inclusion
# The url where you can get direct access to the image on the provider site
title-link: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Matthew Henry
# Name of the image database you found it on
provider: Burst
# Please give the general site URL, not the link to the image
provider-link: https://burst.shopify.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/diversity-equity-inclusion.png
# Alt text for the image on the Credits page
alt: ''
# If an image was altered, please give the name of the HfLA designer that altered the image
altered-by: Kristine Eudey
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please do the following in issue #3130:
    - [x] Move it to the New Issue Approval column
    - [x] Remove the "Dependency" label from it
    - [x] Add a "ready for dev lead" label to it  
  
### Resources/Instructions
- [Credits webpage](https://www.hackforla.org/credits/)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- This issue is tracked in the epic #3130.

### PR DESCRIPTION
**Pull request by str-xjua24**
Fixes #3353 

### What changes did you make and why did you make them ?

  -Add credit in diversity-equity-inclusion.yml file for redesigned homepage

### CODE REVIEW

**Comment by esantiano** [comment]
ETA: 12/10/2022
Availability: 2 Hours

**Review by esantiano — APPROVED** [review]
Hey @str-xjua24 
Good job on the medium issue. Looks like the file you added works on the homepage on desktop as well as the mobile site. Excellent work!

**Comment by MattPereira** [comment]
ETA: 12/11/2022
Availability: 8 - 10 PM

**Review by MattPereira — APPROVED** [review]
Solid work @str-xjua24 ! :+1: 

You created your pull request on the `hackforla:feature-homepage-launch` branch, put the `diversity-equity-inclusion.yml` file in the correct directory, and properly copy/pasted the contents of the file from the issue. 

Looks good on desktop and mobile

<details><summary><strong>See Desktop Screenshot</strong></summary></details>

<details><summary><strong>See Mobile Screenshot</strong></summary></details>

**Pull request merged**
