### PR TITLE
Change 'engineering.yml' to 'coding.yml' and edit the credits

### LINKED ISSUE #3295: Edit credit for Coding image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Coding credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/engineering.yml`,
  - [x] Change the file name from `engineering.yml` to `coding.yml`
  - [x] Change `title: Engineering` to `title: Coding`
  - [x] Change 
    `title-link: https://thenounproject.com/ralfschmitzer/collection/gui-basics/?i=486344`
    to
    `title-link: https://thenounproject.com/search/?q=coding&i=486344`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'Engineering Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by neevliberman**
Fixes #3295

### What changes did you make and why did you make them ?

  - Changed engineering.yml to coding.yml
  - Edited title, title-link, alt, used-in (and added content-type) attributes, and removed the type attribute
  - Credits page updated with new icon & credits, see below

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

(No associated credits were on the page)

</details>

<details>
<summary>Visuals after changes are applied</summary>

2nd row, right column

image

</details>

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-08-17

**Comment by jdingeman** [comment]
Availability: 4 hrs
ETA: EOD 8/15/2022

**Comment by jdingeman** [comment]
Hey @neevliberman. I am having trouble getting this into my local repo. I think your pull request needs to have hackforla:gh-pages, and not hackforla:feature-homepage-launch
image

You may need to do another pull request with the correct branch, though I think @arpitapandya can speak on that with more confidence than I can.

**Comment by neevliberman** [comment]
@jdingeman [The original issue says](https://github.com/hackforla/website/issues/3295): "The pull request created from this issue should be merged into feature-homepage-launch", so I did with that what I could... Not sure though, I could be wrong. Hopefully @arpitapandya can clear this up.

**Comment by arpitapandya** [comment]
> Hey @neevliberman. I am having trouble getting this into my local repo. I think your pull request needs to have hackforla:gh-pages, and not hackforla:feature-homepage-launch image
> 
> You may need to do another pull request with the correct branch, though I think @arpitapandya can speak on that with more confidence than I can.

@jdingeman you may not be able to getting into your local repo because you don't have `feature-homepage-launch` branch locally if you haven't worked on `feature-homepage-launch` or may be deleted.
This PR should be merged to `feature-homepage-launch` and not `gh-pages` as per the [issue](https://github.com/hackforla/website/issues/3295)

Here is how I will review the PR
- create a branch in your local repo `feature-homepage-launch` make sure its updated with the latest changes
- Then follow the commands to review @neevliberman's PR
PS: we have `gh-pages` and `feature-homepage-launch` branches which are separate so when you work on issue or review PR related to `feature-homepage-launch` make sure you have that locally and updated as you do for `gh-pages`.
- Also, I will update branch on my github repo website prior to creating branch or making any changes to avoid the merge conflicts
nocodingyml

**Comment by jdingeman** [comment]
@neevliberman @arpitapandya oops that's embarrassing. Thank you for the correction. 😄  I managed to get it into my local repo and I'll review it.

ETA: EOD 8/17/22

**Review by jdingeman — APPROVED** [review]
Looks good! Changes clearly visible in credits page. 
Thank you so much to @arpitapandya for walking me through the whole thing because I could not figure out what was going wrong on my end. 😄

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct! Great job! @neevliberman

**Pull request merged**
