### PR TITLE
Update getting started webpage 3761

### LINKED ISSUE #3761: Getting Started webpage: Fix Steps 3 and 4 to be consistent
### Overview
On the Getting Started webpage, we want Step 3 to be Adopt Our Standards and Step 4 to be Choose a Role in the header section of the page so that 
- the order of the steps is consistent with the detailed instruction cards in the body of the page and
- we maintain a professional-looking website.

### Details
<details>
  <summary>current state of Getting Started webpage image of the steps in the header section</summary>
  
</details>

<details>
  <summary>future state of Getting Started webpage image of the steps in the header section</summary>
  
</details>

### Action Items
**Developer**
- [x] In the `pages/getting-started.html`, switch Step 3 and Step 4 in the header section so that Step 3 is Adopt Our Standards and Step 4 is Choose a Role
- [x] Using developer tools, make sure your changes look good when you view the page in mobile, tablet, and desktop views

**Product Manager**
- [ ] After the pull request to fix this issue has been merged and passed Quality Assurance, pass this to the Design Lead to write an issue for a designer to update the Getting Started section in the [Current Pages in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0&t=vN6N6qjUVS9lbn3j-0) so that
  - the desktop design for the webpage has the steps in the header be Step 3 is Adopt Our Standards and Step 4 is Choose a Role
  -  the desktop design for the webpage has the detailed, instruction cards on the lower part of the page be Step 3 is Adopt Our Standards and Step 4 is Choose a Role
  - update the site screenshot with the current Getting Started page for desktop view

### Resources/Instructions
- [Getting Started webpage](https://www.hackforla.org/getting-started)
- [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #3761 

### What changes did you make and why did you make them ?

  - Changed Step 3 text to "Adopt Our Standards" & Changed Step 4 text to "Choose a Role"
  - Switched the Images and the class values
  - These changes were made to be consistent with the rest of the webpage. So now Step 3 and Step 4 will match respectively to the rest of webpage.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After

</details>

### CODE REVIEW

**Comment by Adastros** [comment]
Availability (PST): 9:00 - 11PM 24JAN23
Review Estimate: 11PM 24JAN23

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 1/26
Availability: 2 hours

**Review by Adastros — COMMENTED** [review]
Hi @d-perez-8, good job on completing the issue! Steps 3 and 4 were switched as indicated in the issue and the getting started page reflects the changes. 

Before I approve it, I wanted to get the team's thoughts on removing the empty lines after each `img` tag for the getting started header. It shouldn't fall outside the scope of the issue and should help clean up that section of the code. Prior to this pull request, each `img` tag had an empty line right after it except for one. It's possible the intention was to have that section of the code formatted that way, but I think it's better to remove those empty lines while we're working on this issue.

While reviewing the pull request, I also noticed that the naming schemes for the images used in the header section aren't consistent with how the other images are named in the asset folder. It seems like the images should follow a scheme of step-1, step-2, etc. In addition, the names of the images that are associated with each step don't match. For example, step 3 in the header uses an image named `step2.png`. I believe the image names should be fixed to keep it consistent with the steps in the header at least. I don't believe fixing the image names fall within the scope of the issue and can be captured in a new issue. 

[Current getting-started.html file](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)

[Updated getting-started.html file](https://github.com/d-perez-8/website/blob/update-getting-started-3761/pages/getting-started.html)

<details>
<summary>Sample screenshot of image names in the gh-page repository</summary>

img

</details>

**Comment by d-perez-8** [comment]
@Adastros Thank you for the detailed review! I'll bring it up to the team on Sunday's meeting about these concerns and see what they want to do 👍

**Comment by d-perez-8** [comment]
After our Sunday's meeting discussion, I will create a new issue for the name inconsistency and will delete the empty lines of code in my next commit.

**Review by Adastros — APPROVED** [review]
Hi @d-perez-8, thanks for making the changes and creating a new issue regarding the image names! The changes look good to me. Nice job!

**Review by Jaretzbalba — APPROVED** [review]
@d-perez-8 Sorry for the late review! I see that steps 3 and 4 were changed accordingly and everything looks good. Thank you for working on this issue!

**Pull request merged**
