### PR TITLE
replace content field remove type field in process.yml

### LINKED ISSUE #2856: Edit content field and remove type field from process.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/process.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/process.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/process.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/process.yml#L11

### PR DESCRIPTION
**Pull request by luiderek**
Fixes #2856

### What changes did you make and why did you make them
For the file: `_data/internal/credits/process.yml`
- replaced the content field with content-type
- removed the type field

Oops about the bad link. Unsure if it was caused by the initial "Fixes ####", or the commit message. Opted to not include an issue code within the commit to be safe.

### CODE REVIEW

**Comment by gstemmann** [comment]
Availability Wednesday 6-9pm
ETA: November 7, 2022

**Comment by jyaymie** [comment]
Review ETA: 11/2/22 12:30pm
Availability: Now til 12:30pm

**Review by jyaymie — APPROVED** [review]
Nicely done, @luiderek! Thank you for taking the time to create a new PR with the corrected branch name. I had no problem with the issue link.

**Comment by gstemmann** [comment]
@luiderek it looks like you made the proper changes to the .yml file as the issue asked, and you also pushed your branch to the correct repo, but don't forget to reassign yourself as an assignee so you get the credit. [2.4 Claiming an Issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#24-claiming-an-issue)

**Comment by luiderek** [comment]
I believe I'm still listed as an assignee for issue #2856 itself, it's just now linked to both a closed and this pull request now. Bot magic and all.

**Comment by gstemmann** [comment]
> I believe I'm still listed as an assignee for issue #2856 itself, it's just now linked to both a closed and this pull request now. Bot magic and all.

Oh pardon me. Then yes you did a great job!

**Review by gstemmann — APPROVED** [review]
All approved!!

**Pull request merged**
