### PR TITLE
updating wins-feature-1 with changes made on gh-pages

### PR DESCRIPTION
**Pull request by jbubar**
@marcobarrera  made some changes to the wins page on gh-pages, so I thought we should merge those changes into the wins-feature-1 branch.. This will also include all the gh-pages changes up till now. So it is like an update for the wins-feature-1 development branch..

We are going to have to do this eventually.. why not now.. before it gets worse.

### CODE REVIEW

**Comment by jbubar** [comment]
Ok. So I resolved the merge conflicts... if you want to pull it to your machine run these commands.

```
git fetch upstream
git checkout -b gh-pages-1 upstream/gh-pages-1
git merge wins-feature-1
```
I created a branch gh-pages-1 for resolving the merge conflicts. we can delete it after this merge. 

Oh wait.. going to update some things..

**Comment by jbubar** [comment]
Ok. I think it is ready to merge

**Comment by akibrhast** [comment]
Quick question @jbubar . This  looks like it is a merge of gh-pages into wins-feature-1 , is that correct? If it is, may I recommend an alternative to do a rebase instead. What are your thoughts and opinions on this ?

Because:
1. The feature branch will have an extraneous merge commit every time you need to incorporate upstream changes. If main is very active, this can pollute your feature branch’s history quite a bit
2. The major benefit of rebasing is that you get a much cleaner project history. It eliminates the unnecessary merge commits required by git merge.

source:
- https://www.atlassian.com/git/tutorials/merging-vs-rebasing
- https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase
- https://www.atlassian.com/git/tutorials/merging-vs-rebasing#the-golden-rule-of-rebasing

**Review by Aveline-art — APPROVED** [review]
I have examined every page and the code and everything works as intended! Thanks for taking the time for this, Josh. To avoid doing this again, would you like me to make an issue to research methods to concurrently update the wins-feature-1 branch with the gh-pages branch?

Also, what are your thoughts on implementing unittesting for the website project?

**Comment by akibrhast** [comment]
>  issue to research methods to concurrently update the wins-feature-1 branch with the gh-pages branch

Yes to opening an issue to research and discuss about the possibilities, benefits and potential pitfalls

- One side effect to that , of the top of my head is that it is going to create a lot of headache and overheads for anyone working on a feature branch.

**Comment by jbubar** [comment]
@Aveline-art I am so sorry that you had to read through all the files. True MVP!!

I did this because of marco's commit where he added a 'x' closing button to the wins page on gh-pages. I thought it was necessary to have that commit on feature branch. I also thought that it would be a chance to resolve merge conflicts if there were any. 

When the feature is ready we will merge it into gh-pages, I do not imagine that we have to do this again, unless we make changes to the wins page on gh-pages

@akibrhast I do not know about rebase. Lets bring this up in the dev meeting.

**Comment by akibrhast** [comment]
I am going to take my self as a reviewer off of this. Leaving the decisions to @hackforla/website-merge

**Comment by akibrhast** [comment]
@jbubar What exactly do you want us to discuss on our next dev meeting regarding this ?

**Comment by jbubar** [comment]
Only need to look at these two commits
e2f624a

dd908a1

**Review by averdin2 — APPROVED** [review]
@jbubar Everything on the wins page looks good to me. I think this should be ready to merge.

**Pull request merged**
