### PR TITLE
Changed from Content to Content-Type

### LINKED ISSUE #2811: Edit content field and remove type field from citizen-engagement.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/citizen-engagement.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: image
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/citizen-engagement.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/citizen-engagement.yml#L4 
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/citizen-engagement.yml#L11

### PR DESCRIPTION
**Pull request by clayton1111**
Fixes #2811

### What changes did you make and why did you make them ?

  - changed line 4: content ----> content - type
  - removed line 11: type
  - purpose: combine 2 lines to simplify code

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No screenshot, does not change website visuals

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Review ETA: Less than 1 Hour
Availability: 3 Hours

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: EOD 6/24

**Comment by answebdev** [comment]
Availability: 1 hour
ETA: End of day (6/24/2022)

**Review by answebdev — COMMENTED** [review]
@clayton1111 Thank you for submitting your PR. For this issue, line 4 for the content field in `_data/internal/credits/citizen-engagement.yml` needed to be changed from `content: image` to `content-type: image`, and line 11 for the type field needed to be removed, which I can see that you did. Great job!

On a minor note: Please remove the white space in line 11 where the type field was removed. Currently, `_data/internal/credits/citizen-engagement.yml` has 12 lines, with 11 being empty. After removing this white space, you should then have 11 lines with no more white space. Thank you!

**Review by Sparky-code — APPROVED** [review]
Everything looks good, I see you've properly changed the requested lines. As soon as you've addressed the whitespace issue that @answebdev brought up you should be all set!

**Pull request merged**
