### PR TITLE
new icons

### LINKED ISSUE #2528: Add credits for photos and icons for redesigned homepage
### Overview
We need to add credits for all new icons and photographs used in the redesigned version of the homepage so that the Credits page is up to date. 

### Note: Feature Branch
The pull request created from this issue should be pushed into a feature branch called "feature-homepage-launch." Please note this [wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) on how to work off of a feature branch.

### Action Items

- [ ] Add credits to the Credits Page for all the icons and photographs used on the redesigned homepage. All the credit information can be found [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724).

### Resources/Instructions
[HfLA - Credits Page](https://www.hackforla.org/credits/)
[Figma - Homepage Redesign: Credits](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by jqg123**
Fixes #2528

### What changes did you make and why did you make them ?

  -new icons
  -credits
  -figma prototype to feature branch

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image](https://user-images.githubusercontent.com/9208705/153740847-9c72380d-aa04-4306-ac43-febff5dfec7f.png)

Paste_Your_Image_Link_Here_After_Attaching_Files)

</details>
Screenshot (55)
Screenshot (56)
Screenshot (57)
Screenshot (58)

Screenshot (59)
Screenshot (60)
Screenshot (61)

Screenshot (62)

### CODE REVIEW

**Comment by macho-catt** [comment]
Hi @jqg123, could you also add what changes you made in your post, and add the relevant images?

Thanks

**Comment by SAUMILDHANKAR** [comment]
@jqg123 Just following up on the issue. Please share the images after changes are applied. Let me know if you have questions. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@jqg123 Are you still interested in working on this issue? If yes, please let me know by Monday, January 31, 2022. If I do not hear back from you by that date, I will close this pull request and unassign you from this issue.

**Comment by SAUMILDHANKAR** [comment]
@jqg123 Thanks for getting back to me on Slack. Please update your progress here as well. Thank you.

**Comment by jqg123** [comment]
working on this. have not done this issue in a long time.

**Comment by JessicaLucindaCheng** [comment]
Closing this pr because it is a duplicate of pr #2774

**Pull request closed without merging**
