### PR TITLE
Added github-handle var to Benny Van section

### LINKED ISSUE #6124: Add github-handle for Benny Van in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Benny Van
```
with
```
- name: Benny Van
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs.md 

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Cloid**
Fixes [#6124](https://github.com/hackforla/website/issues/6124)

### What changes did you make?
  - Added additional var called `github-handle`

### Why did you make the changes (we will use this info to test)?
  - Changes were already made in the requirements.`github-handle` will eventually be used deprecate redundant variables and have one singular variable to replace them.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by w1ld-r** [comment]
Hey @Cloid Can you add the labels from the issue (#6124) onto this PR? It looks like the workflow that adds those automatically failed. Either something went wrong, or maybe you created the PR in a different way than the workflow expects. Thanks!

**Comment by Cloid** [comment]
> Hey @Cloid Can you add the labels from the issue (#6124) onto this PR? It looks like the workflow that adds those automatically failed. Either something went wrong, or maybe you created the PR in a different way than the workflow expects. Thanks!

@gaylem I added the labels in the original issue. Let me know if I need to add anything else.

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hey @Cloid,

Nice work editing the md file, but you're meant to create a new branch when working on issues. The gh-pages branch should generally be only pulling changes upstream from the HackForLA repository, you shouldn't edit it yourself when working on issues. 

You can find information on creating a branch [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue). To summarize:

- Navigate to your gh-pages branch and pull changes from upstream to make sure it's up to date: `git pull upstream gh-pages` 

- Make a new branch with a descriptive name using: `git checkout -b <name of new branch>`, something like add-github-handle-6124 for this issue would work. 

I would suggest closing this PR and making a new one following the instructions linked above. If anything is confusing or you have any questions, feel free to ask.

**Comment by tony1ee** [comment]
**review aborted**: actions to requested changes pending

**Pull request closed without merging**
