### PR TITLE
removed Cristina Or from _projects/website.md

### LINKED ISSUE #6376: Update Project Profile: remove Christina Or from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Christina Or
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U04J1GBA6QP'
      github: 'https://github.com/christinaor'
    picture: https://avatars.githubusercontent.com/christinaor
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by kmdeakers**
Fixes #6376

### What changes did you make?
  - removed Cristina Or from ```_projects/website.md```

### Why did you make the changes (we will use this info to test)?
  - to remove Cristina Or from website leadership

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
image
Screenshot 2024-03-08 at 10 50 13 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
Screenshot 2024-03-02 at 5 09 37 PM

</details>

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @GRK1998 - I think you meant to put your name down to review this PR? If so, please add your name to the list of reviewers and comment with your ETA and Availability- and either way please remove your name from the list of assignees. 

Also, I see you requested @vraer to review this issue- please remove this request. 
Thanks!

**Comment by ramitaarora** [comment]
ETA: Eod Mar 5
Availability: 9am-2pm Weekdays

**Review by ramitaarora — APPROVED** [review]
Looks good @kmdeakers!
- Christa Or's profile was removed from the _projects/website.md file
- The correct changes are showing on the website projects page

Thank you for contributing to Hack for LA!

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
@kmdeakers The visuals of "before changes" do not match with the published website. Members- Sarah Sangar and Richard Kwong are already removed from the Hack For LA site project. Please make sure your forked repo is up to date with the hackforla website repo.

**Comment by kmdeakers** [comment]
Fixes #6376 

### What changes did you make?
  - removed Christina Or from ```_projects/website.md```

### Why did you make the changes (we will use this info to test)?
  - to remove Cristina Or from website leadership

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)



<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2024-03-08 at 10 50 13 AM

image


</details>

<details>
<summary>Visuals after changes are applied</summary>
Screenshot 2024-03-08 at 10 52 55 AM

image

</details>

**Comment by kmdeakers** [comment]
@Thinking-Panda sorry about the that. Hopefully this resolves the issue.

**Comment by t-will-gillis** [comment]
Hey @kmdeakers - please transfer the changes you made in[ your comment](https://github.com/hackforla/website/pull/6410#issuecomment-1986248400) to the top section of the issue. Then, since you have made the changes requested, you can re-request a review by selecting the chasing arrows next to @Thinking-Panda 's name so that they receive a notification:
<details>
image
</details>

**Review by Thinking-Panda — APPROVED** [review]
@kmdeakers , thank you for making the requested changes. It looks good now. Approved!

**Pull request merged**
