### PR TITLE
issue 5386 done-Melinda Moved

### LINKED ISSUE #5386: Update Project Profile: Civic Tech Jobs (move Melinda Sukosd)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] **_MOVE only_** the entry for Melinda:
```
  - name: Melinda Sukosd
    role: UX Research Lead
    links:
      slack: https://hackforla.slack.com/team/U03T1G9F46P
      github: https://github.com/melkosm
    picture: https://avatars.githubusercontent.com/melkosm
```
 - [x] Move Melinda's profile immediately after any other Lead's profile
 - [x] Confirm on your local that links for the member appear to be correct (for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by sheehanrobb**
Fixes #5386 

### What changes did you make?
  - updated order of people

### Why did you make the changes (we will use this info to test)?
  - to keep leads together on website

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary> 
Screenshot 2023-09-09 at 4 44 18 PM
</details>

<details>
<summary>Visuals after changes are applied</summary>
Screenshot 2023-09-14 at 4 32 44 PM

</details>

### CODE REVIEW

**Comment by LukeLowrey2** [comment]
Working on this review Monday 9/11
Availably: Monday 9/11 930a - 1030a, Tuesday 9/12 10a - 11a
ETA: Tuesday 9/12 EOD

**Comment by ha-bach** [comment]
Reviewing this PR
Availability: any day after 7pm
ETA: Tuesday 9/12

**Comment by ha-bach** [comment]
PR Review

What works:
- Correct branches
- Linked issue is correct
- Required code changes are done correctly
- No other unnecessary code changes are done
- Changes look good on my local machine on computer, phone, and tablet mode
- Links work correctly on my local machine

What I think needs changing:
- Formatting for answer for "What changes did you make?" in the PR description is weird
- Empty bullet points for "What changes did you make?" and "Why did you make the changes (we will use this info to test)?" sections in PR description
- The before image should be moved to the "Visuals before changes are applied"
- The image link in "Visuals before changes are applied" leads to a 404

Overall the code changes are excellent! It's only the PR documentation that could be improved.

**Comment by sheehanrobb** [comment]
Have updated the documentation. Sorry I didn't know you could edit. Hopefully you can see the changes.

**Comment by ha-bach** [comment]
Aside from a leftover ![image] tag after the before picture, the documentation looks great now! :D Thank you for your work!

**Review by ha-bach — DISMISSED** [review]

**Review by LukeLowrey2 — DISMISSED** [review]
Hello @sheehanrobb!
-You are committing into the correct branch 
-You have properly linked the issue to the PR
-You have moved Melinda's info to be included, alphabetically, with other leads

Thank you for being on top of the comment edits!
Great job with the code changes!

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @sheehanrobb, thank you for taking on this issue! 

- The branches are correct
- The requested changes from issue #5386 are correct

I won't be able to merge this pull request due to a merge conflict. Some recent changes were made to the `civic-tech-jobs.md` file that your branch of the file does not contain (a new person was added to the list). To fix this, could you update your fork and branch of the HFLA website repository? Once updated, you can re-implement the changes that issue #5386 is requesting. Reference [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) on how to update your fork and branch. 

Once the changes are implemented, don't forget to update the images in the pull request comment! 

Let me know if you have any questions!

**Comment by sheehanrobb** [comment]
Hi @Adastros, 
Thanks for the review and feedback. I hope I've done this correctly and there are no conflicts.  Let me know if anymore changes need to be made.
- I have incorporated changes into my branch and committed them.

**Comment by t-will-gillis** [comment]
Hello @sheehanrobb -

The merge conflict appears to have ballooned. At this point, it may be easiest for you to close this PR, then make sure your branch is updated, and then redo issue #5386 and open a new PR. When you have a chance, please feel free to reach out to @Adastros or anyone on the merge team (including myself). 

Thanks!

**Comment by sheehanrobb** [comment]
Thank you @t-will-gillis. I have closed this PR. I will redo with an updated branch. At least I'm getting lots of github practice haha

**Pull request closed without merging**
