### PR TITLE
Edited content field and removed type field from business.yml file

### LINKED ISSUE #2798: Edit content field and remove type field from business.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/business.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/business.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/business.yml#L4
https://github.com/hackforla/website/blob/4efd6a62b1d5e625445ddd8f7cb86572e5b9e7a8/_data/internal/credits/business.yml#L11

### PR DESCRIPTION
**Pull request by mchavezm**
Fixes #2798

### What changes did you make and why did you make them ?

  - Edited 'content' field to 'content-type'
  - Removed 'type' field since it contained similar information to 'content' filed 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by trishajjohnson** [comment]
Availability: 1hr
ETA: EOD 6/2/22

**Review by trishajjohnson — APPROVED** [review]
I inspected the PR and found that it is done from/to the appropriate branches, the correct issue number has been provided that PR addresses to fix and, after consulting the original issue, I see that the required tasks were completed to satisfaction.  You changed content: icon to content-type: image on line 4 and removed line 11 type: icon from file _data/internal/credits/business.yml.  No visual changes to the frontend were observed, so screenshots were unnecessary and assignee noted this in PR.

Well done.  You should be good to go.

**Comment by Jaretzbalba** [comment]
Availability: 1hr
ETA: EOD 6/3/22

**Review by Jaretzbalba — APPROVED** [review]
@mchavezm I see that you correctly change the content property to content-type and deleted line 11 with the type property. Good job working on this issue!

**Pull request merged**
