### PR TITLE
Added Sydney Walcoff to the expunge-assist.md File

### LINKED ISSUE #5627: ER: Update Project Profile: Expunge Assist
### Dependency
- [x] #5752 
- [x] #5753 
- [x] #5754 
- [x] #5755 
- [x] #5756 
- [x] #5757
- [x] #5759 
- [x] #5760
- [x] #5761 
- [x] #5762
- [x] #5763 
- [x] #5919 

### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Title

_No response_

### Update the Description?

NO

### Description

_No response_

### Update the Image?

NO

### Image

_No response_

### Update the Technologies?

NO

### Technologies

_No response_

### Update the Partner(s)?

NO

### Partners

_No response_

### Update the Tools?

NO

### Tools

_No response_

### Update GitHub Link?

NO

### GitHub Link

_No response_

### Update Slack Link?

NO

### Slack Link

_No response_

### Update Test Site Link?

NO

### Test Site Link

_No response_

### Update Demo Site Link?

NO

### Demo Site Link

_No response_

### Update Site Link?

NO

### Site link

_No response_

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Thomas Demoner
- [x] Name: Jamie Siu
- [x] Name: Sheron Virani
- [x] Name: James Shin

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Analicia Mejia Mesinas 
GitHub Handle: amejiamesinas
Role: Product Manager, UX Research
Slack Member ID: U04J34E73CG

- [x] Name: Lane Mitchell
GitHub Handle: lmitch10
Role: Product Manager, Development
Slack Member ID: U052LEP0BSN

- [x] Name: Curtis Barber 
GitHub Handle: CBx3000
Role: Product Manager, Content
Slack Member ID: U05RZAETCQ4

- [x] Name: Sydney Walcoff
Github handle: sydneywalcoff
Role: Development, Team Lead
Slack Member ID: U02P0A49XL4

- [x] Name: Anita Morales
Github handle: anitadesigns
Role: UX Design, Team Co-lead
Slack Member ID: U03F43PFR3K

- [x] Name: Justin Yeh
GitHub handle: jyehllow
Role: UX Design, Team Co-lead
Slack Member ID: U03PNBDLXL1

- [x] Name: Samantha Hyler
GitHub handle: SamHyler
Role: UX Content, Team Lead
Slack Member ID: U025XR6MY6S

### Project Status

Active

### LINKED ISSUE #5760: Update Project Profile: Expunge Assist (Add Sydney Walcoff)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Sydney Walcoff
    github-handle: sydneywalcoff
    role: Development, Team Lead
    links:
      slack: https://hackforla.slack.com/team/U02P0A49XL4
      github: https://github.com/sydneywalcoff
    picture: https://avatars.githubusercontent.com/sydneywalcoff
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      
    </details>

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by jleung7158**
Fixes #5760 

### What changes did you make?
  - Found the leadership variable and added the Sydney Walcoff text as a new entry for Expunge Assist project (_projects/expunge-assist.md)

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.
  - Not sure how else to answer this personally besides *cue Patrick Star voice* "Because you told me to!" 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>
image
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
@jleung7158 Thank you for taking up the good first issue! You wrote a nice pull request and you added Sydney info correctly in the `_projects/expunge-assist.md`. And Thank you for attaching before and after.

Only fix I ask is to put correct issue number. You put Fixes 5627 on pull request and branch name but I believe issue number is [5760](https://github.com/hackforla/website/issues/5760#user-content-fn-2-5ed52829e758cd52a150832d276d9241).

**Comment by jleung7158** [comment]
Sorry about that @Tomomi-K1! I have fixed it now, let me know if there is anything else :]

**Comment by jleung7158** [comment]
I'm not too sure if I properly changed the branch name though, as I am checking my git branches and my "update" doesn't appear.

**Comment by jackyuan1** [comment]
Review ETA: 6pm 10/31/23
Availability: 5-6pm 10/31/23

**Comment by jleung7158** [comment]
Apparently I need to delete my old branch, remove this pull request, and make a new one. Is that alright?

**Comment by jackyuan1** [comment]
- The pull request is done within the correct branch.
- The issue is correctly linked
- The provided screenshots captures the changes 
- Upon opening your branch in VSCode, it does not seem that Sydney Walcoff has been added

**Review by jackyuan1 — CHANGES_REQUESTED** [review]
- The pull request is done within the correct branch.
- The issue is correctly linked
- The provided screenshots captures the changes 
- Upon opening your branch in VSCode, it does not seem that Sydney Walcoff has been added

**Comment by Tomomi-K1** [comment]
I forgot to put my availability and ETA.
ETA today.
Availability: 12-5pm weekday.

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @jleung7158!

Great job with this pull request!

- The branching was done correctly. 
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site. Sydney Walcoff's card has been added.
- Relevant images were included to show visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made according to the original issue description

I do have a couple additional requests. When you're done, you can click the circle with the arrows next to my name in the reviewers section and I will approve the changes. Please feel free to ping me if you have any questions.
- [ ] @jackyuan1 noted the inconsistent issue number in the branch name. This can probably be fixed by changing the branch name. See these [instructions for changing branch name](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch). You may have to copy your PR into a new one when you push the branch again. If you have to create a new PR, please link this one and re-add the same reviewers.
- [ ]  Please pull the changes into your local feature branch and push it to your forked repo again. There is currently a merge conflict because Samantha Hyler was added and that PR was merged before yours. This will update this PR with the changes. 
- [ ] Add the labels that are on the original issue to this PR request (usually this happens automatically, but sometimes it doesn't work. It generally fails when the original issue number isn't added when the PR is created.)

Thanks for taking the time to contribute to the website!

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
@jleung7158 , I see you fixed your issue number of this pull request!🙌🏻
- Please kindly follow what @LRenDO mentioned in the review 
- Please make sure to update before and after screenshot. Currently at this moment, [HackForLA website](https://www.hackforla.org/projects/expunge-assist) is showing below members.
image
If you pulled the main branch into your feature branch before you push out, you should see 6 people plus one more. But that could change as the things get merged. But you can always check Live HackForLA site to compare.

- It looks like you deleted Samantha Hyler and Curtis Barber. But you are supposed to add Sydney and not delete other members.
image

If you need any help, please let me know 😊!

**Comment by jleung7158** [comment]
I hope it's alright, I plan on just creating a new PR and linking this one!

**Pull request closed without merging**
