### PR TITLE
Update Language Merging to Support Projects with Multiple Additional Repositories

### LINKED ISSUE #5160: Display languages for projects that have 2 or more repos
### Dependency
- [x] #5231 

### Overview
We need to change the code for displaying the language data so that it can display languages for projects that have 2 or more repositories (repos).

#### Developer
- [x] Understand how the website is currently getting languages data for projects [^1][^2]
- [x] In the _projects/civic-tech-index.md [^3], change `additional-repo-ids` from
  ```
  additional-repo-ids: '275296439'
  ```
  to
  ```
  additional-repo-ids:
    - 275296439
  ```
- [x] With the change you made above to `additional-repo-ids`, change the code to work with the 2 or more repos.
- [x] Check your code meets the Acceptance Criteria below

##### Acceptance Criteria
- [x] Code still works for any projects with only 1 repository (repo). 
    - [x] A project's markdown file that only has a non-empty `identification` field and no `additional-repo-ids` field.
    - [x] A project's markdown file with a non-empty `identification` field and an empty `additional-repo-ids` field.
- [x] Code for any projects with 2 or more repos 
  - [x] Possible scenario: A project has 2 repos, so the project's markdown file has a non-empty `identification` field and the `additional-repo-ids` field has 1 repo listed.
  - [x] Possible scenario: A project has 3 or more repos, so the project's markdown file has a non-empty `identification` field and an `additional-repo-ids` field with 2 or more repos listed.
- [x] When displaying languages for a project, the same languages are not listed multiple times. For example, if a project has HTML as a language in two repos, its list of languages when displayed on the website should only list HTML once.
- [x] On the Projects page [^4],
  - [x] The filters work properly
  - [x] The languages and contents on the cards remain the same as on the live website
- [x] After all the code changes, check the Languages listed for the detailed Civic Tech Index project page matches the one on the live website [^5] 
- [x] Also, check other project's detailed pages to make sure everything looks and works okay
- [x] Nothing is broken on the website due to your code changes

#### Merge Team
- [ ] Once the pull request associated with this issue is merged, go to #6138 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in _Phase 1_ of the _Dependency_ section are checked off, move each of the issues in _Phase 2_ of the _Dependency_ section to the **New Issue Approval** column and apply a **ready for prioritization** label to each of those issues.

### Resources/Instructions
- This issue is tracked in #6138 
[^1]: [Wiki: How languages are added to the `project` variable](https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File#adding-languages)
[^2]: Previous issue #3805 and its pr #5037 that the work for this issue should be built upon. (Note: Due to code changes, please look at the actual files in the codebase for the most current code.) Also, look at #5231 for the refactor of variables and fields. 
[^3]: [_projects/civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md?plain=1)
[^4]: [Projects page](https://www.hackforla.org/projects/)
[^5]: [Civic Tech Index page](https://www.hackforla.org/projects/civic-tech-index)

### PR DESCRIPTION
**Pull request by jphamtv**
Fixes #5160

### What changes did you make?

- _projects/civic-tech-index.md:
  - Updated `additional-repo-ids` format to enable support for multiple additional repositories.
&nbsp;
- _layouts/project.html:
  - Applied  Liquid's `join` filter to convert multiple additional repository IDs from a project's Markdown file into a comma-separated string.
&nbsp;
- assets/js/projects.js:
  - Modified JavaScript logic to enhance the merging of languages from multiple repos associated with a project.
&nbsp;
- assets/js/current-projects.js:
  - Updated JavaScript logic in the `retrieveProjectDataFromCollection` function to merge languages from multiple repos associated with a project more efficiently.
  - Refined code formatting within this function for better readability, maintainability, and consistency.

### Why did you make the changes (we will use this info to test)?
  - These changes upgrade the existing language display feature to accommodate projects with more than two additional repository IDs in the Markdown file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
avail: 2/11
eta: 2/11

**Comment by t-will-gillis** [comment]
New eta: 2/13

**Review by t-will-gillis — APPROVED** [review]
Hey @jphamtv Fantastic work! I am able to confirm that "Civic Tech Index" in Docker  matches the live site, and did not find any discrepancies when checking some of the other projects. The code edits appear to satisfy the other criteria (no `additional-repo-ids,` with the add'l repo but empty, with one add'l repo, and with multiple add'l repos. )

And great job picking up the minor edits (`projectLanguageArr` --> `projectLanguageArray`, semicolons, etc.)- thanks for tackling this issue!

**Comment by jphamtv** [comment]
@t-will-gillis - thanks for the feedback and review!

**Pull request merged**
