### PR TITLE
Toolkit scss consolidation

### PR DESCRIPTION
**Pull request by sena-ji**
Updated Toolkits pages for standardization

### CODE REVIEW

**Comment by erikaBell** [comment]
looks good to me

**Comment by daniellex0** [comment]
@sena-ji Just confirming, is this connected to an issue? Sorry, I'm not quite sure what the context is! Is this a followup to the Tuesday CSS discussion?

**Comment by sena-ji** [comment]
> @sena-ji Just confirming, is this connected to an issue? Sorry, I'm not quite sure what the context is! Is this a followup to the Tuesday CSS discussion?

Nope! I was asked to create a pull request of the standardization we did during the developers meeting.

**Comment by daniellex0** [comment]
Ah ok got it- this removes the link from the resource cards? Could you post a screenshot of how it looks with the changes please? I'll run it by the design team meeting tomorrow first if possible since it's a UX design-related change (Also there's a chance Bonnie might want to weigh in on this, I'll check)

**Comment by akibrhast** [comment]
> Ah ok got it- this removes the link from the resource cards? @daniellex0 
 
No, it does not. Should not.

**Comment by daniellex0** [comment]
@akibrhast Ohh ok sorry just ran this myself now and pulled it up (as I should have in the beginning!)- so this should all just look the same, but with more standard CSS, got it. Ok looks good to me. 

Just to confirm, .not-clickable is removed because it wasn't being used anywhere, right?

Btw (and this is not a critique at all because I did the same thing forever!), but in the future @sena-ji in PR's please list out the changes that you made with quick explanations if possible, thank you! :) (unless it's already all listed out in an attached issue)

**Comment by sena-ji** [comment]
> @akibrhast Ohh ok sorry just ran this myself now and pulled it up (as I should have in the beginning!)- so this should all just look the same, but with more standard CSS, got it. Ok looks good to me.
> 
> Just to confirm, .not-clickable is removed because it wasn't being used anywhere, right?
> 
> Btw (and this is not a critique at all because I did the same thing forever!), but in the future @sena-ji in PR's please list out the changes that you made with quick explanations if possible, thank you! :) (unless it's already all listed out in an attached issue)

Got it Danielle! I will make sure to do that for future PRs. Thank you for the feedback :)

**Review by akibrhast — APPROVED** [review]
LGTM. Am merging

**Pull request merged**
