### PR TITLE
Updated alt text for Sitemap Header Hero image

### LINKED ISSUE #6798: SiteMap Page: Update alt text for SiteMap Header Hero image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the [SiteMap page](https://www.hackforla.org/sitemap/) page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within: pages/sitemap.html

**From:**
```
  <img class="header-hero-image" src="/assets/images/sitemap/sitemap-planning.svg"
        alt="image of a person using a computer and mapping out a website">
```

**To:**
```
  <img class="header-hero-image" src="/assets/images/sitemap/sitemap-planning.svg"
        alt="">
```

- [x] Ensure that the corresponding [SiteMap page](https://www.hackforla.org/sitemap/)  stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3859 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3859 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
[SiteMap page](https://www.hackforla.org/sitemap/)

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: pages/sitemap.html
- Click on the filename below to see the source file code:
[Location in the Code](https://github.com/hackforla/website/blob/gh-pages/pages/sitemap.html)
- This issue is part of epic #3859

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by andyphancode**
Fixes #6798 

### What changes did you make?
  - Removed alt text for header hero image on sitemap.html

### Why did you make the changes (we will use this info to test)?
  - Removed to create space for more clear and descriptive alt text

### Visual Changes
  - No visual changes were made in this code change

### CODE REVIEW

**Comment by terrencejihoonjung** [comment]
Review ETA: 11:59 PM PST, 6/4/24
Availability: 12pm-12am PST Mon-Fri

**Review by terrencejihoonjung — CHANGES_REQUESTED** [review]
Hi @andyphancode 

- branching is correct, issue is listed
- `alt=""` is correctly replacing the previous value
- PR title is clear and concise
- changes made and why they were made are clearly stated

Changes Requested:
- note whether there were visual changes in the PR

Once you've completed these changes, you are good to go! Thank you and good job!

**Review by terrencejihoonjung — APPROVED** [review]
Changes look good! Thanks @andyphancode!

**Comment by jchue** [comment]
**Review ETA:** 6/5 EOD
**Availability:** 6/5, after 5 PM

**Comment by ino-iosdev** [comment]
ETA: EoD

**Review by ino-iosdev — APPROVED** [review]
Hi @andyphancode  , It's such a blessing to have you as part of the team here!
 
- Naming was appropriate
- Direction between branches `from` and `to` are clear
- The changes to `alt=""` and why were clear
- PR issue link was clear
- No visual changes to the website
 
Great job, thank you for contributing!

**Review by ino-iosdev — APPROVED** [review]

**Review by jchue — APPROVED** [review]
I don't think you need my approval anymore, but nice job, @andyphancode.

- Pull request done with correct branch
- Correct issue linked
- `alt` property correctly updated
- Site Map webpage unchanged

**Pull request merged**
