### PR TITLE
Update project profile guides 2888

### LINKED ISSUE #2888: Update Project Profile: Guides Website
### Overview
As a product manager of the Guides Team, I want my project's details to be up to date on the HackforLA website

### Project card
- [guides-team.md](https://github.com/hackforla/website/blob/427c0c8ae104955f91a41e9af0fc4594cce08c22/_projects/guides-team.md?plain=1)
- [Guides Team on Hack For LA Website](https://www.hackforla.org/projects/guides-team)

### Action Items

- We need to update the Current Project Team to remove former team members who are:
      - Thuy Le
      - Carol Zhu

### Resources
- https://github.com/hackforla/website/blob/427c0c8ae104955f91a41e9af0fc4594cce08c22/_projects/guides-team.md?plain=1
- https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by blulady**
Fixes #2888 

### What changes did you make and why did you make them ?

  -I removed former team member
  -Thuy Le
  -Carol Zhu
  -their affiliate links from [guides-team.md](https://github.com/hackforla/website/blob/427c0c8ae104955f91a41e9af0fc4594cce08c22/_projects/guides-team.md?plain=1)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by blulady** [comment]
Is there a way to limit the amount of commit information I am sharing?
Please Advise,
Sarah

**Review by maybleMyers — APPROVED** [review]
Looks good. All issues were fixed. Good Job!

**Comment by harshitasao** [comment]
Review ETA : 21/03/2022
Availability : Flexible

**Review by harshitasao — APPROVED** [review]
@blulady Excellent work! Everything appears to be in order.

**Comment by tamara-snyder** [comment]
@blulady I have the same problem in my PRs since I update my forked gh-pages a lot and I'm honestly not sure how to fix it. Maybe squashing the commits would help, but I need to look into it more.

**Comment by JessicaLucindaCheng** [comment]
@blulady @tamara-snyder I think it is expected that there are a lot of commits in your prs if you are updating your topic branch and also saving your coding work to your forked remote repo in between coding sessions (which I think is a good practice so you don't lose your work if something happens to your files locally).

**Comment by tamara-snyder** [comment]
Good to know, thanks @JessicaLucindaCheng!

**Pull request merged**
