### PR TITLE
Resolved CodeQL Alert 50 by removing unused variable.

### LINKED ISSUE #6621: Resolve CodeQL Alert 50
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers. we need to analyze [CodeQL query alert 50](https://github.com/hackforla/website/security/code-scanning/50) and to either recommend dismissal of the alert or update the code to resolve the alert.    

### Action Items
- [x] DO NOT DISMISS ANY ALERTS.  Dismissal of alerts should be done by dev leads only after review of the recommendation
- [x] Browse to the link in the next Action Item and read the contents.  Click "See More" to view Recommendations, Examples and References.  
- [x] https://github.com/hackforla/website/security/code-scanning/50 
- [x] Note these resources: 
   - [x] See the wiki page "How to manage CodeQL alerts" (see under Resources)
   - [x] To look at the resolution of similar alerts, visit the [code scanning page](https://github.com/hackforla/website/security/code-scanning) and query closed alerts for similar alert type.  To see the resolution of a closed alert, view the alert details and open the tracking issue (outlined in red in the screenshot under Resources)
- [x] In a comment in this issue, provide your recommendation.  The recommendation can be one of the following: `dismiss as test`, `dismiss as false positive`, `dismiss as won't fix`, or `update code`.  An example of a 'false positive' is a report of a JavaScript syntax error that is caused by markdown or liquid symbols such as `---` or `{%`.  
- [x] If the recommendation is to update code:
   - [x] create an issue branch and proceed with the code update
   - [x] Use docker to test locally, ensuring that there are no changes to the appearance or the behavior of any affected webpage(s) or GitHub actions.  If you are not certain how to test a particular code change, ask a merge team member or dev lead.  
   - [x] proceed with pull request in the usual manner 
- [x] If the recommendation is to dismiss, describe your reason for dismissal in the comment, then move the issue to `Questions/In Review` and apply the label `ready for dev lead`.  

### For merge team/dev lead
- [ ] If recommendation to dismiss is approved, dismiss the alert with a comment, then close the issue as completed.
- [ ] When this issue is closed please check off the dependency (under "Issues") in #5159.  If all issues are closed, close #5159 as completed.  
  
### Resources/Instructions
<details><summary>Screenshot of CodeQL alert detail page with tracking issue outlined in red</summary>

CodeQLAlert

</details> 

- [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
- [code scanning page](https://github.com/hackforla/website/security/code-scanning)
- Wiki page "How to resolve CodeQL alerts" (if this page has not been published yet, see the draft at https://github.com/hackforla/website/issues/6463#issuecomment-2002573270)
- This issue is part of #5159

### PR DESCRIPTION
**Pull request by danajeon**
Fixes #6621 

### What changes did you make?
  - Removed unused variable `contactMessage`.

### Why did you make the changes (we will use this info to test)?
  - Change was made because variable is unused, which may lead to performance issues due to wasted computation.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Modified api-actionnetwork.js file. No visual changes made to website.

### CODE REVIEW

**Comment by roslynwythe** [comment]
@danajeon The modified code is used to respond to form submissions on the `/Join` page.  Using the issue branch from this PR, I submitted forms and am attempting to confirm receipt of the email messages.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe The original issue for this is here 
- https://github.com/hackforla/website/issues/316
- We need an ER
   - The forms and the spreadsheet, etc will need to be moved by me, and we should discuss how we test in future, which will inform the setup.
   - the info all should get documented in our wiki.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I checked and we got all the form submissions you did.

**Review by roslynwythe — APPROVED** [review]
Great job @danajeon on this issue:
- The analysis and code change are correct
- The PR is well-formed and descriptive
- The changes were tested by confirming that the forms on the Join Us page result in email messages

**Pull request merged**
