### PR TITLE
Renamed to blank-issue-form-with-dependency.yml

### LINKED ISSUE #3720: Update blank-issue-form.yml file name to blank-issue-form-with-dependency.yml
### Overview

We want to change the file name of `blank-issue-form.yml` to `blank-issue-form-with-dependency.yml` to clarify the purpose of the file. This will also make locating the file easier for future developers.

### Action Items

- [x] In the `.github/ISSUE_TEMPLATE/` folder, change the file name of `blank-issue-form.yml` to `blank-issue-form-with-dependency.yml`

### Testing Instructions
Check if the form works and displays correctly by
1. Pushing the changes to your remote forked repo's topic branch on GitHub
2. In your remote forked repo on GitHub, temporarily change the default branch from `gh-pages` to your topic branch. (See link in the Resources section for official documentation)
3. Check you have issues enabled in your forked repo by going to the `Settings` tab and then select `General` in the left menu. On the right side of your screen, scroll until you see the `Issues` checkbox under the `Features` section. Make sure the checkbox is checked. <details><summary>Click here to see what it looks like when issues are enabled in a repo</summary>
                image</details>
4. Open an issue within your repo to test out the form you just edited by going to the `Issues` tab and clicking the `New issue` button.
5. Select the `Getting Started` button for `Blank Issue Form with Dependency`<details><summary>Click here to see where the Getting Started button is for the Blank Issue with Dependency Form</summary>
Blank Form with Dependency Issue Selection View </details>
6. Test out the form and make sure everything functions as expected.
7. Remember to change your default branch back to `gh-pages` in your remote forked repo on GitHub.

### Resources
- [blank-issue-form.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml)
- [Github's documentation on how to change the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch)

### PR DESCRIPTION
**Pull request by angieyan**
Fixes #3720 

### What changes did you make and why did you make them ?

  - Renamed the file to blank-issue-form-with-dependency.yml
  - The reason for renaming the file is to clarify the purpose of the file and to make locating the file easier for future developers.

### CODE REVIEW

**Comment by Adastros** [comment]
Availability (PST): 9-11 PM 08MAR23
Review ETA (PST): 11PM 08MAR23

**Comment by RyanGehris** [comment]
Availability: 6-8pm
ETA: EOD 03/08/2023

**Review by RyanGehris — APPROVED** [review]
Thank you for completing this issue. I was able to make a topic branch on my local repo, and test that the form was functional, and the files name change was reflected. Great work.

**Review by Adastros — DISMISSED** [review]
@angieyan good job on completing the issue! The file was renamed successfully and issues can be created from the template without any problems. 

Could you update the following:
- in your pull request comment, link the issue you worked on (#3720) instead of pull request #4115. The pull request statement "Fixes" should always reference the issue you worked on.
- check the task in issue #3720. This helps indicate what was and will need be completed for an issue. 
- add a brief statement on why the changes were implemented. This is to get into the habit of good documentation practices

**Comment by angieyan** [comment]
@Adastros 
Thank you for the explanation and guidance.
#3720  issue is the main issue but as I merged to a wrong branch #4115 was created.

**Comment by Adastros** [comment]
@angieyan you are correct, but this pull request should link issue #3720 instead of pull request #4115. This is so we follow standard operating procedures set forth in the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests).

**Comment by roslynwythe** [comment]
Availability 3/11 10-11, 3/12 2-6 pm
ETA: EOD 3/12

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @angieyan, @Adastros is currently out and asked me to complete the review in his stead, so when you have completed the items that he requested in his comment above (https://github.com/hackforla/website/pull/4131#pullrequestreview-1332135120), please click the icon to the right of my name.  Thank you!

**Comment by roslynwythe** [comment]
Hi @angieyan, @Adastros is currently out and asked me to complete the review in his stead, so when you have completed the items that he requested in his comment above (https://github.com/hackforla/website/pull/4131#pullrequestreview-1332135120), please click the re-request icon to the right of my name.  Thank you!

**Comment by angieyan** [comment]
Thank you @roslynwythe 
I fixed it.

**Comment by roslynwythe** [comment]
Hi @angieyan thank you for putting the issue number on the first line of the PR.  Now the issue and PR will be properly linked. 
 
In his comment https://github.com/hackforla/website/pull/4131#pullrequestreview-1332135120 Adastros also requested that you check the box in the Action item of the issue, and add a brief statement in the PR about the reason for the change.  When you have completed those steps, please click the re-review icon to the right of my name.  Thank you.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @angieyan thank you for putting the issue number on the first line of the PR. Now the issue and PR will be properly linked.

In his comment https://github.com/hackforla/website/pull/4131#pullrequestreview-1332135120 Adastros also requested that you check the box in the Action item of the issue, and add a brief statement in the PR about the reason for the change. When you have completed those steps, please click the re-review icon to the right of my name. Thank you.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @angieyan In his comment https://github.com/hackforla/website/pull/4131#pullrequestreview-1332135120 Adastros also requested that you add a brief statement in the PR about the reason for the change. When you have completed that, please click the re-review icon to the right of my name. Thank you for great work on this issue!

**Review by roslynwythe — APPROVED** [review]

**Pull request merged**
