### PR TITLE
Mobile header

### LINKED ISSUE #1596: Standardize Program Areas page header in mobile
### Overview
We need to standardize the Program Areas page header in mobile to make it consistent with other pages and our design system.

### Action Items
- [x] Standardize the Program Areas page header in mobile (see annotated screenshot below)
   - [x] Decrease the margin between heading and top nav bar to 32px (2rem)- this should be done by just removing the margin-top: 2.25rem) - **only in mobile**
   - [x] Increase margin between heading and paragraph to 28px total - **only in mobile**
   - [x] Increase margin between header paragraph and illustration to 36px total - **only in mobile**
   - [x] Decrease the size of the header illustration to max-width 256px - **only in mobile**

### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)

**How header looks now (incorrect)**

Screen Shot 2021-05-20 at 12 54 29 AM

**How header should look (correct):**

Screen Shot 2021-05-20 at 12 54 14 AM

### PR DESCRIPTION
**Pull request by Abel-Zambrano**
Fixes #1596

  - Decreased the margin between heading and top nav bar to 32px (2rem) - only in mobile
  - Increased margin between heading and paragraph to 28px total - only in mobile
  - Increased margin between header paragraph and illustration to 36px total - only in mobile
  - Decreased the size of the header illustration to max-width 256px - only in mobile

<details>
<summary>Visuals before changes are applied</summary>

  Screen Shot 2021-07-10 at 1 24 42 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
Screen Shot 2021-07-10 at 1 25 16 PM
</details>

### CODE REVIEW

**Review by jbubar — COMMENTED** [review]
Hey Abel, this is looking good, but now there are some git mistakes, and it will not prevent it from merging, but it is important for future pull requests...

<details>
    <summary>notice how all of these commits are from previous issues?</summary>

Screen Shot 2021-07-10 at 5 38 35 PM

</details>

Usually, this is because someone is branching off the wrong branch... but in your case I am pretty sure this is because your first few issues were off of the gh-pages branch.. which corrupted that branch.. 

I recommend deleting and recreating the gh-pages branch locally and on your fork

try these commands
```bash
git checkout upstream-gh-pages #switched to other branch
git branch -D gh-pages #deletes gh-pages
git checkout -b gh-pages upstream/gh-pages #creates a new gh-pages branch off of the upstream gh-pages
```

Then you want to go to [your fork](https://github.com/Abel-Zambrano/website/) and delete gh-pages

then do `git push` on the new gh-pages branch

**Comment by jbubar** [comment]
Let me know that you did that, and I will approve this pr. hit me up if you get stuck

**Comment by Abel-Zambrano** [comment]
Hey Josh,

All done, I recreated the gh-pages.

**Review by jbubar — APPROVED** [review]
Good work. glad we got this sorted. sorry about all the complications

**Comment by jbubar** [comment]
@Abel-Zambrano hey.. I just realized that I was checking see that it did not break anything, but it did not check if you solved this issue. my bad.
going to reopen the issue and offer you some guidance

**Comment by jbubar** [comment]
I do not think that we have to revert this merge, because it does solve other margin issues. I reopened issue #1596 and offered some suggestions for next steps

**Pull request merged**
