### PR TITLE
Replaced 'and' with '&' on line 2, 'name' field, to be consistent with that title. 'Diversity, Equity, and Inclusion' changed to 'Diversity, Equity, & Inclusion'

### LINKED ISSUE #4284: Make Program Area Consistent on Program Areas Page
### Overview
We want our website to use terms consistently when referring to program areas. On the [Program Areas](https://www.hackforla.org/program-areas) page, we need to change the title of the `Diversity, Equity, and Inclusion` card to `Diversity, Equity & Inclusion`.

### Action Items
- [x] Change the 'name' field of the[ diversity-equity-inclusion-card.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/diversity-equity-inclusion-card.yml) file to: `Diversity, Equity & Inclusion`.
- [x] Important note: do **not** change the 'program-area' field on the same card. It needs to remain as shown.

### Resources/Instructions
- [Program Areas page](https://www.hackforla.org/program-areas)
- [/pages/program-areas.html](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html)
- [/_data/internal/program-areas/diversity-equity-inclusion-card.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/diversity-equity-inclusion-card.yml)

### PR DESCRIPTION
**Pull request by LOSjr4**
Fixes #4284

### What changes did you make and why did you make them ?

  - Updated 'and' into '&' on line 2 of the 'name' field.
  - This was done so our terms are consistent when referring to program areas.
  - What was 'Diversity, Equity, and Inclusion' will be changed to 'Diversity, Equity, & Inclusion'.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - Before: the yml file affects the title as seen here on the current site.
  
image
  
- After: The title as seen on my docker preview.

image

### CODE REVIEW

**Comment by jch1013** [comment]
Availability: Thursday any time
ETA: 3/28 EOD

**Comment by jch1013** [comment]
Hello! two things caught my eye while reviewing this... First of all, could you make sure all the boxes are checked on the original issue? More importantly, I'm seeing a message that says there is a merge conflict that needs to be resolved. I'm not sure what the issue is, maybe the merge team can help out with that at our meeting tonight? Apart from those things the actual code changes look correct to me, so nice work on that!

**Comment by LOSjr4** [comment]
I believe the merge issue is now cleared. My local branch was not up to date. I also checked the boxes that were complete on the original issue. Thank you Jackson H. for letting me know.

**Comment by hang-justin** [comment]
Review ETA: 3/29/23 5pm pacific time
Availability: 9-5 pm weekdays

**Review by hang-justin — DISMISSED** [review]
@LOSjr4 

Looks golden here! Great job!

Curious as to how you fixed your merge conflict. Would love to learn how you did so.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @LOSjr4 - thanks for working on this issue! Your branches 'from' and 'to' are correct and you have linked back to the original issue. Thanks for addressing @jch1013 's comments and also fixing the merge conflict.

Please note that although these changes are to the yml file (the third item on the 'Resources/Instructions' for issue 4284), the yml file is referenced by an html file (the second item), and therefore this edit does make a visual change to the website (see the first item, which is a link to the website that is affected by this edit: the Program Areas page.) Therefore, in the description section of the PR, please attach the 'before' and 'after' screenshots showing the change to the Program Areas page. (Let one of us know if you need help setting up Docker)

Also, if you look closely at 4284, the 'name' field should change to `Diversity, Equity & Inclusion`. In other words, for consistency with other areas of the website, there should not be a comma after 'Equity'. 

Good work so far and thanks again!

**Comment by LOSjr4** [comment]
I'll share what I remembered, @hang-justin. My mistake was I had checked git fetch upstream, but I skipped the part to pull the changes to my repo. So after my repo was current, VS code showed a merge issue alert. I clicked on the alert and it pointed out the differences and allowed me to fix the discrepancy. Then I just commit and push as before.
@t-will-gillis, thank you for telling me this. I hadn't worked with yml files before so I didn't quite understand how they worked. I will work on before and after pictures now.

**Comment by LOSjr4** [comment]
Added before and after pictures. Removed comma after Equity.
Thank you @t-will-gillis for noticing the comma and teaching me something about yml files.

**Review by t-will-gillis — APPROVED** [review]
Hi @LOSjr4 - Great job! Thanks for making the changes. Yeah, the html referencing the yml is done with [Liquid](https://shopify.github.io/liquid/) and here is a link for using [Liquid in Jekyll](https://jekyllrb.com/docs/liquid/)- I am fairly new to it myself.  

Thanks again for making the changes- will keep this issue open for a little longer to give @hang-justin and @jch1013 a chance to look at it too.

**Review by hang-justin — APPROVED** [review]

**Comment by hang-justin** [comment]
Thanks for sharing that @LOSjr4 . I'm sure that I'll come across that and this info would be helpful.

I pulled down the repo and verified the visual changes on my end. Looks good here. Great, quick work.

Good eye there @t-will-gillis . Thanks for that info on the YML and Jekyll/Liquid. I didn't know YML files could be used like that.

**Comment by blulady** [comment]
Hey @jch1013 if you are able to review this PR again, could you give us an ETA and Availability?

**Comment by jch1013** [comment]
ETA: End of Day
Availability: any day after 3pm

**Review by jch1013 — APPROVED** [review]
Changes look good to me, nice job getting everything fixed!

**Pull request merged**
