### PR TITLE
Update vrms-data.yml to fail when the VRMS API fails to return a valid response 5691

### LINKED ISSUE #5691: Update vrms-data.yml to fail when the VRMS API fails to return a valid response
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview

When the request to the VRMS API fails and returns an error, meeting times are overwritten and replaced with a "503 Service Temporarily Unavailable" HTML file instead of retaining the previous meeting times

### Action Items
- [x] Validate that the github action fails incorrectly
  - [x] Update `.github/workflows/vrms-data.yml` commenting out `if: github.repository == 'hackforla/website'` to allow the github action to run locally on your fork
  - [x] Replace `https://www.vrms.io/api/recurringevents` with `https://httpstat.us/503` to validate that the github action fails incorrectly and push the commit to validate that the github action fails incorrectly and overwrites the json file in `_data/external/vrms_data.json`
  - [x] Undo the changes to `_data/external/vrms_data.json`
- [x] Update `.github/workflows/vrms-data.yml` to retry the request n times if it fails and terminate if it still fails to update. Adding `--retry` and `--fail` to the curl parameters should accomplish this. I've included links to the man pages for both below
- [x] Validate that the changes now no longer overwrite `_data/external/vrms_data.json` and the github action indicates a failed run
- [x] Replace `https://httpstat.us/503` with `https://www.vrms.io/api/recurringevents`
- [x] Verify the github action still runs correctly with the vrms api
- [x] Uncomment the `if: github.repository == 'hackforla/website'` you commented in the earlier step

### Resources/Instructions

1. https://curl.se/docs/manpage.html#-f
2. https://curl.se/docs/manpage.html#--retry
3. https://httpstat.us/ returns HTTP status codes, useful for debugging

relevant issue: https://github.com/hackforla/website/issues/5650

### PR DESCRIPTION
**Pull request by kevin31yu**
Fixes #5691

### What changes did you make?
  - commented out `if: github.repository == 'hackforla/website'` so I can run the action locally
  - set up my access token to run the action
  - replaced url to `https://httpstat.us/503` to test request failure with error code 503
  - undo the change done by the action on the json file
  - added curl parameters `--retry 7` and `--fail` such that the github action will not overwrites the json file
  - vertify that action run properly after reverting the url back to `https://www.vrms.io/api/recurringevents`
  - undo the token and comment back to original

### Why did you make the changes (we will use this info to test)?
  - The github action overwrites the json file after making a 503 bad request, so I have to fix the curl parameter to allow it to retry 7 times and terminate after that. Such that it won't overwrite the json file if failed.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
   - No visual changed for the website.

### CODE REVIEW

**Comment by kevin31yu** [comment]
Below is the verification of action fail incorrectly and overwrites the json file
Screenshot (1)

**Comment by kevin31yu** [comment]
Action result after adding curl parameters with error code 503
Screenshot (2)

**Comment by jphamtv** [comment]
Availability: Monday-Friday 12–2 PM, 8–10 PM (PST) 
Estimated ETA: 12/17/23

**Review by jphamtv — APPROVED** [review]
Great work on this issue, @kevin31yu . The issue is linked correctly, and the from/to branch is accurately set up. Thanks for providing detailed explanations of the changes you made. I tested the error locally and can confirm that the `--retry` and `--fail `parameters you added to the `curl `command effectively prevent overwriting the JSON file when the API returns a 503 error.

**Review by t-will-gillis — APPROVED** [review]
Hey @kevin31yu Excellent work! I agree with @jphamtv 's comments, esp. about your detailed explanations. I also tested locally to confirm this functions as intended.

Thanks for working on this!

**Pull request merged**
