### PR TITLE
Refactor project check page tools 5322

### LINKED ISSUE #4322: Pre-work Checklist: Developer: Justin Tan
### Prerequisite
We are looking forward to having you on our team. Please make sure to attend the general Hack for LA onboarding to get the process started https://meetup.com/hackforla/events.

### Overview
As a new developer on the HfLA website team, fill in the following fields as you complete each onboarding item.

### Special Notes
1. It may take you a few weeks to finish this issue, because part of it is learning how to provide updates on issues that take more than a week to complete.    Please keep this issue open until you have been able to do all the steps.  
2. Usually we don't want to you have more than one issue assigned to you at a time, this issue is the exception, because it is instructions on how to work on other issues.
3. The action items listed below should mostly be worked on in a sequential order. However, you don't have to wait on one if you can proceed with the others, For instance, you don't have to wait for attending a weekly meeting before setting up your dev environment.  

### Action Items

- [x] Add yourself to the #hfla-site and #hfla-site-pr Slack channels
- [x] Share your GitHub handle and Gmail address in the hfla-site-onboarding slack channel so you can be added to the Google Drive (alternative to go to meeting and direct message a merge team member at the [meeting](https://github.com/hackforla/website/wiki/Meetings-and-Agendas
))
  - [x] To find contact information for the merge team members and technical leads, please take a look at our [Meet the Team wiki page](https://github.com/hackforla/website/wiki/Meet-the-Team)
- [ ] Also, confirm with a merge team member or a technical lead that they have added you to the Google Calendar invites for our Zoom meetings
- [ ] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
- [ ] After you have finished adding yourself to the roster, let a merge team member or a technical lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
- [ ] Once added to the website-write team:
  - [ ] Self Assign this issue (gear in right side panel)
  - [ ] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [ ] Add this issue to the Project Board under the Projects section (gear in right side panel)
- [ ] Signup for a [Figma](https://Figma.com) account
- [ ] Attend weekly team meetings:
  - [ ] Developer (front-end/back-end) weekly team meeting, Tuesdays 7-8pm PST
  - [ ] (Optional) Office Hours, Thursdays 7-8pm PST
  - [ ] All team meeting (UX, Development, Product), Sunday 10am-12pm PST
- [ ] Note: There are no meetings on the 1st-7th of every month.
- [ ] Note regarding weekly team meeting requirements: All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis. Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
- [ ] Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-1-setting-up-the-development-environment)
  - [ ] OPTIONAL: If you run into any issues, use [4.1 How do I ask for help within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#41-what-do-i-do-if-i-need-help) as a visual example to get a hold of our [HfLA website leadership team](https://github.com/hackforla/website/projects/7#card-69730135). That way we can help you resolve any set up issues immediately.
- [ ] Read section 2.1 - 2.4 in [Part 2: How the Website team works with GitHub issues within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues)
  - [ ] Follow the steps in section [2.3 Where can I find GitHub issues to work on?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) to assign yourself your first issue under the Project Board's Prioritized Backlog column and use [2.7 Working on a Issue within Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue) to start working on your issue
  - [ ] Read [2.6 What to do when you need to stop mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26-what-to-do-when-you-need-to-stop-mid-issue)
- [ ] Once you take a good first issue, you will provide estimates and progress reports. Also, once you finish providing your "Estimate" action item below, please answer the question in the "Time spent so far" action item (also below).
   - [ ] Estimate: Copy the below and put it in the "good first issue" that you picked.
 Check this box when you have completed this task so that we can identify if you understood the instructions and know what to do on all subsequent issues upon assignment. (Note: Please provide estimates on all the issues that you pick up, going forward.)
    ```
   Availability for this week:
   My estimated ETA for completing this issue:
    ```
   - [ ] Time spent so far: Copy the question below into a new comment below (in this pre-work issue only) and answer it. This is just to get feedback on how long it took you to get to this point on this pre-work. There is no right or wrong answers. There is no judgement. It is ok if you take a long time or if you do it really fast or at any pace.
    ```
    How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
    ```
   - [ ] Progress Reports: Copy the below and put it in the issue once you have been assigned to the issue at least 5 days (we check weekly on Fridays), or sooner if you have something to report.  If you finish this issue before 5 days are reached, Yeah!!, do it on your next issue. **This update should be done every week for every issue that you are assigned to**. The checkbox here is meant for us to see if you understood the instructions when you end up doing your first weekly progress update.
    ```
    Provide Update
    1. Progress
    2. Blockers
    3. Availability
    4. ETA
    ```
- [ ] Read sections 3.1.a - 3.1.c in [3.1 How to make a pull request](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request) to learn more about how to make a pull request (PR) for the issue that you are working on and how to make changes to your PR if changes are requested by the reviewer
- [ ] Additional notes:
   - [ ] Please don't forget to review pull requests whenever you are able to.  The [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests) guide will teach you how to review pull requests.
   - [ ] Please work on only one issue at a time and wait until your pull request is merged before picking up another issue.
- [ ] Read and understand how we progress through issues. Then, you can check this off.
Progress through issues in the [prioritized backlog](https://github.com/hackforla/website/projects/7#column-7198257) only with increasing complexity in the following order:
  - Good first issue (one per person)
  - Good second issue (one per person)
  - Small (one per person, with some exceptions, see below)
  - Medium (you can work on more than one medium issue, but only one at a time)
  - Large (you can work on more than one large issue, but only one at a time)
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
    - You can work on back-to-back small issues if it meets the following criteria:
      - You are learning something new and need to work on an issue of a lesser complexity
      - Special request by a lead or pm
- [ ] Read the [Start Here - Developers](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8583%3A0) in Figma
- [ ] Go familiarize yourself with the [Hack for LA Design System page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)  (where you can see components and their SCSS classes)
- [ ] Once all tasks are completed, close this issue.  This issue will remain open until you get through your first progress report.  Once you have done that, we are confident you know how to keep the momentum going on your issue and keep your team informed.

### What should I do if I have a question about an issue I'm working on, and I haven't gotten a response yet?
- First, you should post the question or blocker as a comment on your assigned issue, so it can be easily referred to in the next bullet points.
- Then, add the label "Status: Help Wanted" so other developers can see it and potentially help answer your question. In addition, you will still need to post a Slack message or bring it up in meeting so we know you need help; see below for how to do that.
- Also, you can post your question on the hfla-site slack channel and link the issue you're working on, so other developers can see and respond.
- Lastly, you can add the issue to the "Development team meeting discussion items" column of the Project Board so that it can be addressed in the next development meeting. Please bring it during the meeting that you need help.

### Resources/Instructions
- [Contributing.md - Hack for LA](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [GitHub Project Board - Hack for LA](https://github.com/hackforla/website/projects/7)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Front End](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22)
- [GitHub Project Board Prioritized Backlog highlighted and sorted by Back End/DevOps](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+back+end%2Fdevops%22)
- [Figma - Hack for LA](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)
- [Google Drive - Hack for LA website team](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT?usp=sharing)
- [Agenda / Notes - Dev Team Tuesday meeting](https://github.com/hackforla/website/issues/2010)
- [Agenda / Notes - All Team meeting](https://github.com/hackforla/website/issues/2027)
- [How to review Pull Requests](https://github.com/hackforla/website/wiki/How-to-review-pull-requests)

### LINKED ISSUE #5322: Refactor Projects-Check page Tools
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For the [Projects-Check](https://www.hackforla.org/projects-check/) page, the code that renders each projects' Tools data has  complexity that is no longer needed. This code should be simplified so that it is consistent with adjacent code.

### Details
While implementing a series of issues for changing our projects' tools data from a string to a list/array structure, there was a brief period of time when the code for the Projects Check page needed to be able to render correctly regardless of the data type. Now that these issues are complete, we are able to simplify this code.

### Action Items

- [x] Refer to [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js), which is the code for rendering each projects' data on the Project Check page.
- [x] Towards the end of the file, within the `projectCardComponent` function, there is code to render the tools data when it exists. 
  - [x] The line which includes `${ project.tools }` should be refactored in a similar fashion as for `project.languages` and `project.technologies`, so that a comma and a space are added between the each entry when joining the tools data into a list string
- [x] Confirm with Docker on your local repo that the Tools data renders as expected (that is, as before) and review and compare the rest of the pages to confirm that no other unexpected changes/ deletions/ etc. have been made. Provide screenshots of 'before' and 'after' to demonstrate.

### Resources/Instructions
[Projects Check](https://www.hackforla.org/projects-check/) page

### PR DESCRIPTION
**Pull request by antho-zng**
Fixes #5322

### What changes did you make?
  - I refactored the projectCardComponent code in assets/js/current-projects-check.js. Specifically, I modified the code parsing the project tools data to make it consistent with the surrounding code

### Why did you make the changes (we will use this info to test)?
  - The code that renders each project's tools data has complexity that's no longer needed, and the code needed to be simplified to be consistent with adjacent code

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Screenshots included to confirm that the refactored code did not produce any visual changes on the page.

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-09-18 at 15 06 18

Screen Shot 2023-09-18 at 15 06 28

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-09-18 at 15 13 11

Screen Shot 2023-09-18 at 15 13 19

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 9/21/23
Availability: Weekday evenings

**Comment by homeroochoa47** [comment]
ETA: Wednesday 9/20 EOD
Availability: Tuesday evening, Wednesday morning

**Review by pdimaano — DISMISSED** [review]
@lateral-neck-stretch Good job: The branches are correct and the issue is linked. The website still works correctly on my system on desktop, mobile and tablet. The correct line of code was refactored in a similar fashion for Languages and Technologies. Also, I see the issue clearly asked for "before" and "after" screenshots to demonstrate no unintended deletions or changes were made to the appropriate page. Well done!

**Review by homeroochoa47 — COMMENTED** [review]
What's up, @lateral-neck-stretch! In terms of functionality, the changes work as expected and are also visually consistent with the previous version prior to the changes. The merging looks good as well.

I did notice one slight formatting difference when comparing to the other mapped functions such as with projects.languages, etc. In those functions, there is a space between the opening HTML tag and the template literal in the callback function. Here is an example from projects.languages:

`<p class='project-card-field-inline'> ${ language }</p>`

In the current case, the code does not have the space following the opening tag:

`<p class='project-card-field-inline'>${ tool }</p>`

I'm not sure what the degree of strictness for formatting consistency is, but perhaps @t-will-gillis can provide some more insight into this? If it's not an issue, I can go ahead and approve. I hope I'm not being too picky LOL 

Thanks!

**Comment by t-will-gillis** [comment]
Hey @homeroochoa47 (and @lateral-neck-stretch) Good eye noticing the subtle difference in formatting. I probably would not have noticed this!- but no, you are not being too picky. Even though the space itself does not affect the visuals, since the other mappings do include a space I feel that for formatting consistency the tools section should as well.   

Thank you for asking the question-this is a great example for why it is helpful to have multiple reviewers.

**Comment by antho-zng** [comment]
Thanks @homeroochoa47 for the catch and @t-will-gillis for the explanation! I just pushed a new commit adding the missing space and confirmed that spacing on the page still looks the same :)

**Review by homeroochoa47 — APPROVED** [review]
Revision looks great! Nice work and thanks for the help @t-will-gillis and update @lateral-neck-stretch

**Comment by t-will-gillis** [comment]
Hey @lateral-neck-stretch and @homeroochoa47 Looks great- thanks for coordinating!

**Pull request merged**
