### PR TITLE
Img Tag Refactor #4383

### LINKED ISSUE #4383: img Tag Refactor: Getting Started page - `step-img-wide solidarity.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-wide" src="./assets/images/getting-started/solidarity.png" alt="" />
```
to
```
<img class="step-img-wide" src="./assets/images/getting-started/solidarity.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by graycodesnu**
Fixes #4383 

### What changes did you make and why did you make them ?

  - Changed an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Comment by graycodesnu** [comment]
Originally from https://github.com/hackforla/website/pull/4521

**Comment by kwangric** [comment]
ETA: EOD 4/17
Availability: After 1pm PDT 4/17

**Comment by steven-positive-tran** [comment]
ETA: EOD 4/17
Availability: 9pm -12am PST 4/16, 4/17

**Comment by Jaretzbalba** [comment]
ETA: EOD 4/17
Availability: 1 hour

**Review by Jaretzbalba — APPROVED** [review]
@graycodesnu I see that the img tag was corrected by removing the ending slash to keep our codebase consistent. Thank you for working on this first good issue!

**Review by kwangric — APPROVED** [review]
Branches were set up correctly. The requested changes were made and everything looks good in Docker. The pull request also states what changes were made and why. Great work!

**Review by steven-positive-tran — APPROVED** [review]
- [X] Branches look good
- [X] PR gave a good summary of the changes
- [X] Looks good on my machine
- [X] Code changes seems in line with the issue 

Approved and thank you for taking up this issue.

**Comment by angieyan** [comment]
ETA: 4/18/23
Availability: 10am-3pm

**Review by angieyan — APPROVED** [review]

**Pull request merged**
