### PR TITLE
Img tag refactor in Getting Started Page  - #4417

### LINKED ISSUE #4417: img Tag Refactor: Getting Started page - `step-img people.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img" src="./assets/images/getting-started/people.png" alt="" />
```
to
```
<img class="step-img" src="./assets/images/getting-started/people.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by kerimedeiros**
Fixes #4417

### What changes did you make and why did you make them ?

  - Removed the trailing slash and extra space from the img tag.
  - Changes made to ensure that the codebase is consistent in how we use HTML tags.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes as this was a refactoring of an img tag.

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: 3pm PDT today
Availability: Today until 5pm PDT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. Pull request includes summary of the changes that were made and why. Requested changes to the img tag are made, and everything looks good in Docker. Great work!

**Comment by StephenTheDev1001** [comment]
ETA: EoD
Availability: M-F 10am-12pm

**Review by StephenTheDev1001 — APPROVED** [review]
It is linked to the correct issue #4417 and has a clear and concise description of the changes and the rationale behind them. The code changes are correct. I have no comments or suggestions for improvement. Well done!

**Review by StephenTheDev1001 — APPROVED** [review]
It is linked to the correct issue and comes from the correct branch. It has a clear and concise description of the changes and the rationale behind them. The code changes are correct. Well done!

**Review by t-will-gillis — APPROVED** [review]
Hi @kerimedeiros - Great job! Your from-to branches are set up correctly, you are linked back to the issue, and you made the clean and concise changes per the issue. Checking in Docker it appears everything is functioning correctly in different modes. Finally, you are describing which changes you made and why. 

Congrats on your first issue, and thanks!

**Pull request merged**
