### PR TITLE
Resolve codeql 6053

### LINKED ISSUE #6053: Resolve CodeQL alert 19 "Potentially unsafe external link"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 19](https://github.com/hackforla/website/security/code-scanning/19) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/19
- [x] Open the file `pages/communities-of-practice.html` in your IDE
- [x] On line 54, replace:
```
<a href='{{ leader.links.linkedin }}' target='_blank' title='Linkedin Profile'>
```
with
```
<a href='{{ leader.links.linkedin }}' target='_blank' title='Linkedin Profile' rel="noopener noreferrer">
```
- [x] Make changes only to this specific href as flagged by CodeQL no. 19. 
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/communities-of-practice
3. This issue is part of #5129

### PR DESCRIPTION
**Pull request by junadkat32**
Fixes #6053 

### What changes did you make?
  Replaced ```<a href='{{ leader.links.linkedin }}' target='_blank' title='Linkedin Profile'>``` 

with 

```<a href='{{ leader.links.linkedin }}' target='_blank' title='Linkedin Profile' rel="noopener noreferrer">```

### Why did you make the changes (we will use this info to test)?

To resolve codeql alert 6053

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
Review ETA:2/13/24

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
@junadkat32 , Thank you for working on this issue. Merge branches are setup correctly. The action item in the issue mentions to add the `rel=` attribute only for the LinkedIn Profile on `line 54`. Please reverse changes made to `line 58`. There will probably be another issue to make that change. Thanks!

**Comment by junadkat32** [comment]
@Thinking-Panda Yes, you are right. There is a separate issue for ```line 58```and it was me who took up that issue and the PR has been approved. Please advise on further steps.

Thank you.

**Comment by Thinking-Panda** [comment]
> @Thinking-Panda Yes, you are right. There is a separate issue for `line 58`and it was me who took up that issue and the PR has been approved. Please advise on further steps.
> 
> Thank you.

@junadkat32 , developers are expected to work on only one issue at a time and wait until the previous issue is merged to pick another issue. We need to check with the merge-team on further steps.

**Comment by roslynwythe** [comment]
@junadkat32 This PR will be closed, because you are assigned to a different open issue.

**Comment by junadkat32** [comment]
Hello @roslynwythe my previous PR was merged and I have reopened this PR.

**Comment by t-will-gillis** [comment]
Hey @junadkat32 - Closing this PR for a couple of reasons: first is that although you were previously, you are not currently assigned to this issue which is required for opening the PR. The other reason is that you have already completed 3 `good first issue`s and, as is noted on the "Pre-work Checklist", you should be advancing to a `Complexity: Small` issue. Thanks!

**Pull request closed without merging**
