### PR TITLE
Updated partner logo for LA homeless initiative

### LINKED ISSUE #3016: Partners: Change the image for Los Angeles County Homeless Initiative
### Overview
As a developer, I want the logos for our partners to be up to date so that 
- we maintain professionalism on our website and 
- are consistent with the current logos the partners use for themselves. 

For this issue, we will replace an old partner logo image with a new one.
 
### Action Items
- [x] Remove `real-help-lasting-change.svg` from `assets/images/partners` directory
- [x] For the new image:
  - [x] Download the new image from https://homeless.lacounty.gov/wp-content/uploads/2018/09/HI_Logo_lasting-change-v3.png
  - [x] Rename the new image to `la-county-homeless-initiative.png`
  - [x] Add the new image to `assets/images/partners` directory
- [x] For `The Los Angeles County Homeless Initiative` in [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml), update the link for the image field so it points to the new image you added to `assets/images/partners` directory
- [x] In the [Partners section on the About Us page](https://www.hackforla.org/about/#partners), check the image looks good on mobile, tablet, and desktop views using developer tools

### Resources/Instructions
- Image to remove: [real-help-lasting-change.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/partners/real-help-lasting-change.svg)
- Link to new image: https://homeless.lacounty.gov/wp-content/uploads/2018/09/HI_Logo_lasting-change-v3.png
- [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
- [Partners section on the About Us page](https://www.hackforla.org/about/#partners)

### PR DESCRIPTION
**Pull request by RyanCahela**
Fixes #3016

### What changes did you make and why did you make them ?

  - removed the old partner logo
  - optimized new logo size using https://tinypng.com/
  - updated image src with new logo.

### Screenshots of Proposed Changes Of The Website

<details>
<summary>Visuals before changes are applied</summary>

before-desktop
before-mobile
before-tablet

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after-desktop
after-mobile
after-tablet
</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Availability: 1 hour.
ETA: By the end of the day on 4/13.

**Comment by Sparky-code** [comment]
ETA: 4/13 EOD
Avail: 1hr

**Comment by kathrynsilvaconway** [comment]
Availability: 1 hour.
ETA: By the end of the day on 4/13

**Review by Jaretzbalba — APPROVED** [review]
@RyanCahela The new image looks good on the desktop and mobile version. Good job on this issue!

**Review by kathrynsilvaconway — APPROVED** [review]
@RyanCahela Nice work updating the partner logo for the LA Homeless Initiative. It looks good on all the mobiles views and I see that you have deleted the old image from the folder.

**Review by Sparky-code — APPROVED** [review]
Nice going - The Image looks good across desktop and a range of mobile devices. The file rename reads more inline with ARIA standards. I see the change both in file reference and assets.

**Pull request merged**
