### PR TITLE
fix project links

### LINKED ISSUE #2175: Project links with spaces are not read properly
### Overview
The project link href tags need to be enclosed in quotes to avoid issues with URLs that may contain spaces.

### Action Items
- [x] In [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) replace 
```javascript
${project.links.map(item => `<a href=${ item.url } rel="noopener" target='_blank'> ${ item.name }</a>`).join(", ")}
```
 with 
```javascript
${project.links.map(item => `<a href="${ item.url }" rel="noopener" target='_blank'> ${ item.name }</a>`).join(", ")}
```
- [x] Ensure that the links still work correctly

### Resources/Instructions
https://github.com/hackforla/website/blob/823a06c316bb621c505f5a8d6b1774d1c42adb9c/assets/js/current-projects.js#L414

The links appear on these pages:
[https://www.hackforla.org](https://www.hackforla.org)
[https://www.hackforla.org/projects/](https://www.hackforla.org/projects/)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2175

### What changes did you make and why did you make them ?

  - added quotes to the href tag to avoid issues with URLs that may contain spaces

### CODE REVIEW

**Review by glenflorendo — COMMENTED** [review]
Hi @amnak1284! Good work! 👍🏽

For my testing, though, what were the breaking links (the urls with spaces) prior to this change? I want to make sure I check those links.

**Comment by macho-catt** [comment]
@glenflorendo there are no breaking links right now, but (if you want to play around and test it) if you update one of the yml file links to point to a url that has a space in it (for example, a pdf file with the name "test pdf file" instead of "test-pd-file") then this fix will automatically encapsulate the name with a double quotes, routing properly. Without the double quotes, you will be led to a 404 page.

**Review by glenflorendo — APPROVED** [review]
@macho-catt Thanks for the clarification!

@amnak1284 LGTM!

**Review by macho-catt — APPROVED** [review]
LGTM! Thanks @amnak1284. Feel free to pick up a new issue.

**Pull request merged**
