### PR TITLE
added donate-card.html file in _includes folder, removed hard coded d…

### LINKED ISSUE #2451: Update donate section on multiple pages to be the same component
### Overview
We need to componentize the donate section on multiple pages to ensure consistent changes and formatting.

### Action Items
- [x] Notice the donate section on the following two links: [HfLA - Donate](https://www.hackforla.org/donate/) and [HfLA - Join](https://www.hackforla.org/join)
- [x] Extract the html file from the donation part of the [HfLA - Join page](https://www.hackforla.org/join) and store the new html file in the [_includes directory](https://github.com/hackforla/website/tree/gh-pages/_includes)
- [x] This html file should be used for both pages using the keyword {% include %} in liquid
- [x] Ensure that both pages look and function the same after the change in desktop, tablet, and mobile views

### Resources/Instructions
[HfLA - Donate](https://www.hackforla.org/donate/)
[HfLA - Join](https://www.hackforla.org/join)
[Join Us html file](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
[Donate html file](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html)
[_includes directory](https://github.com/hackforla/website/tree/gh-pages/_includes)
[Jekyll - using "includes"](https://jekyllrb.com/docs/includes/)
[Intro to Liquid](https://shopify.github.io/liquid/basics/introduction/)

### PR DESCRIPTION
**Pull request by Mattre7**
…onate card on the join-us and donate pages

Fixes #2451

### What changes did you make and why did you make them ?

  - I consolidated the donate cards' html on the join us and donate pages into a single html file "donate-card.html" in the _includes folder
  -   I deleted the hard code on the join us and donate pages and linked the "donate-card.html"
  - The reason why is so that the donate-card can be more easily linked in the future if it's neater, but also to have a cleaner, easier to understand code and less redundancies

### Additional info
  -  Initially got some styling errors on one page or the other when I linked the same donate-card.html
  - This required some tinkering as the donate-card was coded differently (with different classes) on each page, but was ultimately able to use the same donate-card.html in both circumstances after editing a class of a parent div.
  [](url)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>No changes, however I have attached screenshots of the branch running locally on my computer with the correct styling/application with the new consolidated code in desktop and mobile formats</summary>

### Desktop Join-Us Page (ran locally on my issue branch - same styling)
joinus-page-desktop-pic1
joinus-page-desktop-pic2

### Mobile Join-Us Page
joinus-page-mobile-pic1
joinus-page-mobile-pic2

### Desktop Donate Page
donate-page-desktop-pic1
donate-page-desktop-pic2

### Mobile Donate-Page
donate-page-mobile-pic1
=""
donate-page-mobile-pic2

### CODE REVIEW

**Comment by Zak234** [comment]
ETA: Aug. 1 - Aug. 2
Availability: Anytime

**Review by Zak234 — CHANGES_REQUESTED** [review]
There seem to be various errors on the Join Us page. For both desktop and tablet, the amount of grey space underneath the text is different. Additionally, the sizing and white space for the subtitle ```Running Hack for LA costs money``` seem to be off along with the sizing for ```How to help us continue to do impactful work```. The whitespace seems to only be off for ```Running Hack for LA costs money``` on desktop but the sizing for both titles is off for on all screens.

**Comment by Mattre7** [comment]
> There seem to be various errors on the Join Us page. For both desktop and tablet, the amount of grey space underneath the text is different. Additionally, the sizing and white space for the subtitle ```Running Hack for LA costs money``` seem to be off along with the sizing for ```How to help us continue to do impactful work```. The whitespace seems to only be off for ```Running Hack for LA costs money``` on desktop but the sizing for both titles is off for on all screens.

image

Good catch. This is the live version of the donate page currently and it seemingly looks the same as the above, but the donate card on the join us page looks different. Can you see those same errors on the live hackforla/donate page?

image

This is the current donate section on the join-us page. It does look better/cleaner, so I will make some changes in the new consolidated donate-card.html to make both applications look like that version.


Will be available later today to hopefully resolve.

**Comment by Mattre7** [comment]
**Updated donate page on Mobile**

updated-donate-page-card-mobile-pic1
updated-donate-page-card-mobile-pic2

**Updated donate page on Desktop**

updated-donate-page-card-desktop

**Current Live Website donate page on mobile**

live-donate-page-card-mobile



- Fixed the styling on the donate-card that was different/not as polished on the donate page 

- donate-card currently has different styling on both the join us and donate pages on the live website

- The next step would be to consolidate the css as well, because now a div on the donate page uses the class "join-us-card-container" in order to fetch the correct styling, which is not ideal

- I commented out much of the css on the _donate.scss page, because now that code is going unused, and that code was also what was causing the donate page to be styled differently than the version on the join us page. Maybe should have just deleted but seemed safer for the time being

**Review by Zak234 — CHANGES_REQUESTED** [review]
Is your branch up to date? It seems like there are merge conflicts with _donate.scss.

**Review by Zak234 — DISMISSED** [review]
I was able to solve the merge conflict but all the differences noted before still show up on the donate page.

**Comment by Zak234** [comment]
I think that the reason there are styling errors for the donate page is because the original cards for the Join Us and Donate pages were not the same, so I don't think it's a major issue. I would check in at office hours on Thursday just to make sure it is okay.

**Comment by Mattre7** [comment]
> I think that the reason there are styling errors for the donate page is because the original cards for the Join Us and Donate pages were not the same, so I don't think it's a major issue. I would check in at office hours on Thursday just to make sure it is okay.

Yes they were definitely different. In hindsight the changes to donate.scss were not necessary, but a large chunk of that coded is now going unused after changing the class on a parent div in donate.html (so I commented out that unused code). The change/conflict in that donate.html file is what got the cards to present the same way, but a little confusing since I had to use the join-us-card-container class on the donate file. Anyway, good idea, I will be at office hours tomorrow!

**Comment by JessicaLucindaCheng** [comment]
@Mattre7 Since I am transitioning off of the team, I am no longer reviewing pull requests, so I will be removing myself as a reviewer.

Also, I know GitHub suggests reviewers, which is maybe why you selected me to review your pull request, However, a lot of the suggested reviewers may no longer be active on this team. Thus, if I want reviewers for a pull request, I would do one of the following:
- Wait for a team meeting for pull request reviewers to be assigned
- Post a Slack message with a link to the pull request in the hfla-site channel asking for reviewers

**Comment by blulady** [comment]
Hey @Mattre7, we haven't heard from you in almost a month. If you are still available to work on this PR give us an update in the next week or two.

**Comment by Mattre7** [comment]
> Hey @Mattre7, we haven't heard from you in almost a month. If you are still available to work on this PR give us an update in the next week or two.
> 
> Hi, yes I will update this PR, I'm sure it has fallen behind the main repo by now, but besides that I thought I was actually still just waiting on someone to review the changes. I apologize, I need to be better about reaching out to technical leads myself and get clarity on what I potentially need to change before it gets approved.

**Comment by ericvennemeyer** [comment]
`Availability`: Weds 8/31 - Fri 9/2, 1hr
`ETA`: EOD Fri 9/2

**Comment by Mattre7** [comment]
Just made sure that the issue branch is up to date with recent changes to the main website repo. Happy to see that it looks like @ericvennemeyer might be able to review the pull request. I know I have been absent for a little while, I just started in a new line of work at a new company, but excited to be more present in this community once again, and I am here if anyone needs to contact me regarding this issue and those in the future.

**Review by ericvennemeyer — DISMISSED** [review]
Hey @Mattre7 good job turning these multiple chunks of code into a component. I can see the donate section appears correctly and the styling is now standardized across both pages in desktop and mobile. The current styling also matches the original "join us" page styling. (Noted that the original "donate" page section was coded differently and thus does not match, but not a problem.)

Only comment is that, as you mentioned, the scss is now full of unused code. (e.g. the donate card in `join-us.html` is wrapped in a div of class `donate-card-container`, which no longer exists.) Would be nice to clean that up, but because your changes address the original issue and don't break the site, I'm going to approve this PR.

**Review by blulady — CHANGES_REQUESTED** [review]
Hey @Mattre7 the changes look great on the website as well as all the mobile views. In the interest of keeping the code on the website clean I will ask you to delete the commented out code in the components file. If necessary we'll roll back the changes with Git/GitHub. Thank you so much for all your hard work.

**Comment by Mattre7** [comment]
> Hey @Mattre7 the changes look great on the website as well as all the mobile views. In the interest of keeping the code on the website clean I will ask you to delete the commented out code in the components file. If necessary we'll roll back the changes with Git/GitHub. Thank you so much for all your hard work.

@blulady Ok should be done now, thank you for reviewing! Haven't been as active as I would have liked to be this past month, but settling in to my new job and excited to tackle more issues like this one!

**Review by ericvennemeyer — APPROVED** [review]
After deleting unused SCSS, site still runs without breaking and the Donate and Join Us pages look good. Approved.

**Review by blulady — APPROVED** [review]
The code is clean. It looks good in mobile and on desktop. Stoked to be merging it.

**Pull request merged**
