### PR TITLE
Fix event pg hidden item

### PR DESCRIPTION
**Pull request by josiehandeveloper**
Fixed hidden items #1521 

https://user-images.githubusercontent.com/63170710/118379686-085b0400-b591-11eb-93a9-42a4aab7dbc7.mov

The white margins below the location image are showing having a hard time removing it because the height was set to auto so that the white background would be behind the items.

### CODE REVIEW

**Review by erikaBell — CHANGES_REQUESTED** [review]
Referencing the action items on issue #1521, and highlighting that if things can't be worked out in a way that keeps to the Figma design, reach out to @daniellex0 on how it might need to be reconfigured.

> 
> - [ ] refer to [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) design for how the event cards should look (blue rectangle) 
> - [ ] refactor the code to prevent items in the `<div class="mini-projects">` containers from being hidden—both on the "Monday" and "Tuesday" card—, while maintaining the Figma design
>   - if the design needs to be altered to work, reach out to @daniellex0 for direction
> - [ ] ensure that mobile view does not break


Comparison of Live Site vs Branch below

<details>
<summary>Jo's Branch, Desktop View</summary>

JosBranchDesktop

</details>

<details>
<summary>Live Site, Desktop View</summary>

LiveSiteDesktop

</details>

<details>
<summary>Jo's Branch </summary>

JosBranch

</details>

<details>
<summary>Live Site</summary>

LiveSite

</details>

<details>
<summary>Jo's Branch Mobile View</summary>

JosBranchMobile

</details>

<details>
<summary>Live Site Mobile View</summary>

LiveSiteMobile
</details>

**Comment by josiehandeveloper** [comment]
Fixed hidden item, now a scroll #1521 


https://user-images.githubusercontent.com/63170710/118742745-d9999380-b805-11eb-96a1-6211292e41c5.mov

**Comment by josiehandeveloper** [comment]
Screen Shot 2021-05-18 at 7 17 43 PM (2)

**Review by erikaBell — APPROVED** [review]
lgtm. Thanks @josiehandeveloper (-:

**Pull request merged**
