### PR TITLE
add sdg scss color vars and import to main

### LINKED ISSUE #4233: Add SDG color variables: 2-5, 8-11, 13, 16, 17
### Overview
We need to add the SDG (Sustainable Development Goal) colors to our repo so we can use these colors with their corresponding, matching SDG icons.

### Action Items
- [x] In the `_sass/variables`, create a new file: `_colors-sdg.scss`
- [x] In the file you just created, add the following:
```
/**
 * Sustainable Development Goal (SDG) Colors
 *
 * The hex color values for these variables match the SDG color icons provided by the United Nations (UN).
 * These hex values are from the last the page in the SDG Guidelines provided by the UN:
 * https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf
 */

$color-sdg2: #DDA63A;
$color-sdg3: #4C9F38;
$color-sdg4: #C5192D;
$color-sdg5: #FF3A21;
$color-sdg8: #A21942;
$color-sdg9: #FD6925;
$color-sdg10: #DD1367;
$color-sdg11: #FD9D24;
$color-sdg13: #3F7E44;
$color-sdg16: #00689D;
$color-sdg17: #19486A;
``` 
- [x] In the `_sass/main.scss`, under the `General Settings and Utilities` section, add this:
```
@import 'variables/colors-sdg';
```

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues/dependencies listed under the `Dependency` section are closed or checked off. If the dependencies are all closed or checked, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4344 

### Resources/Instructions
- [_sass/variables](https://github.com/hackforla/website/tree/gh-pages/_sass/variables)
- [_sass/main.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/main.scss)
- [SDGs_HEX_Colors tab in HfLA: Projects: SDG and Targets Google Sheet](https://docs.google.com/spreadsheets/d/1lV8d8AMSJ5HOiTWlFE7lzbqiKxqMmh8pHADcJMdp7JE/edit#gid=741671421)
- This issue is tracked in #4153

### PR DESCRIPTION
**Pull request by StephenTheDev1001**
Fixes #4233

### What changes did you make and why did you make them ?

  - create new file _colors-sdg.scss with sdg-color variables
  - import _colors-sdg.scss to _sass/main.scss
  - allows us to use these colors with their corresponding, matching SDG icons.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Added scss background color variables. No visual changes.

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Review ETA: 4/5/23
Availability: 1 hour

**Review by Jaretzbalba — APPROVED** [review]
@StephenTheDev1001 I see that the main.css file was updated and the new file containing the sdg colors was created successfully. Everything looks good to me! Thank you for working on this issue!

**Comment by LOSjr4** [comment]
Availability: tues, fri, mon
ETA: 4/4 4:30PM

**Review by LOSjr4 — APPROVED** [review]
New file in the correct folder, correct info added to file, and added line to main.scss. Yes, yes, and yes. Good work @StephenTheDev1001 !

**Pull request merged**
