### PR TITLE
remove alt-hero field

### LINKED ISSUE #2924: Remove unused `alt-hero` field from civic-tech-index.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/civic-tech-index.md`, remove line 9 for the alt-hero
```
alt-hero: 'Outline of the world map with connectivity dots linking major cities on each continent.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/civic-tech-index.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/civic-tech-index.md?plain=1#L9

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by mariareeves**
Fixes #2924
### What changes did you make and why did you make them ?

  - removed unused 'alt-hero- field 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website

### CODE REVIEW

**Comment by AzaniaBG** [comment]
ETA: 09/19/2022 by 6 PM
Availability: 09/19/2022 4 - 6 PM

**Comment by lilyarj** [comment]
ETA: 6/18
Availability: 2hrs

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Review by blulady — APPROVED** [review]
This comes from the correct branch (mariareeves:remove-alt-hero-field-2924)[mariareeves:remove-alt-hero-field-2924](https://github.com/mariareeves/website/tree/remove-alt-hero-field-2924) and goes to the correct branch [hackforla:gh-pages](https://github.com/hackforla/website). It has a linked issue, the linked issue is addressed by  deleting line 9. The code is clean and there's only one commit. Good Job!

**Review by neevliberman — APPROVED** [review]
Looks great! Does exactly what the issue asked you to.

**Comment by AzaniaBG** [comment]
I removed myself as a reviewer as this has already ben merged.

**Pull request merged**
