### PR TITLE
Update alt text for Los Angeles Criminal Sentencing Project image

### LINKED ISSUE #3952: Los Angeles Criminal Sentencing Project: Update alt text for Los Angeles Criminal Sentencing Project image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Los Angeles Criminal Sentencing Project` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/criminal-sentencing.md`:

**From:**
```
Gavel
```

**To:**
```
Los Angeles Criminal Sentencing Project
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- Los Angeles Criminal Sentencing Project: https://www.hackforla.org/projects/criminal-sentencing

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/criminal-sentencing.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/criminal-sentencing.md
- This issue is part of epic #3866 

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by angieyan**
Fixes #3952

### What changes did you make and why did you make them ?

  - changed the image alt text in _projects/criminal-sentencing.md, making the alt text more clear and descriptive so that we can adhere to WCAG standards

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

no visual changes were made to the website

### CODE REVIEW

**Comment by vanessavun** [comment]
Availability: weekday evenings
ETA: 11:30PM Fri 2/24

**Review by vanessavun — APPROVED** [review]
Thanks for finishing this task. I see that the commit is going to the right branch from your branch and you changed one file for the alt tag from `Gavel ` to `Los Angeles Criminal Sentencing Project`. I'm running the website locally and don't see anything broken. This project is not visible so I can't check it visually. Great job!

**Comment by angieyan** [comment]
Thank you @Vanessavun.

**Comment by MarkWiltberger** [comment]
**Availability:** Daily 10am-6pm ET (7am - 3pm PT)
**ETA:** 02/27/2023 Mon 6pm ET (3pm PT)

**Review by MarkWiltberger — APPROVED** [review]
Great job! I love what you have done, @angieyan ! You have made the change precisely. The pull request is done with the correct branch. The linked issue is to change the alt text in the `_projects/criminal-sentencing.md` file. This change should not result in visible changes in the browser. The code was run in the local dev browser and did not result in any visible changes. The code was inspected and the changes fulfill the _ABC’s_: they are _applicable_, they do not _break_ the main website, and they are _clean_. The changes are approved.

**Comment by angieyan** [comment]
Thank you so much @MarkWiltberger 😊

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @angieyan, good job on completing the issue! Before this gets merged, could you update your pull request comment to follow the template as shown in pull request #4048? It should look similar in structure. If there are no visible changes, you can either remove the section titled "Screenshots of Proposed Changes Of The Website" or state that no visual changes were made to the website as a result your updates. 

Could you also clarify the pull request title (what kind of alt text did we update)? 

The reason for asking this is to ensure we follow good documentation practices for tasks we work on. In the future, it will also help reviewers develop a better understanding of what was implemented when you work on more complex tasks.

**Review by mademarc — COMMENTED** [review]
@angieyan It looks and it is very readable this code  :)

**Comment by mademarc** [comment]
Review ETA:  7:30PM 2/28/23
Availability: 1Hr

**Comment by angieyan** [comment]
> Hi @angieyan, good job on completing the issue! Before this gets merged, could you update your pull request comment to follow the template as shown in pull request #4048? It should look similar in structure. If there are no visible changes, you can either remove the section titled "Screenshots of Proposed Changes Of The Website" or state that no visual changes were made to the website as a result your updates.
> 
> Could you also clarify the pull request title (what kind of alt text did we update)?
> 
> The reason for asking this is to ensure we follow good documentation practices for tasks we work on. In the future, it will also help reviewers develop a better understanding of what was implemented when you work on more complex tasks.

@Adastros thank you for this guide. I have made changes and re-requested you to review. This kind of guide helped me understand minor but important things for the documentation.

**Review by Adastros — APPROVED** [review]
@angieyan thanks for making the changes! Looks good!

**Pull request merged**
