### PR TITLE
Corrected spelling of 'accommodate' in sitemap html file

### LINKED ISSUE #2941: Fix misspelled word on sitemap.html file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items
- [ ] For the file `pages/sitemap.html`,  on line 14, change the spelling from "accomodate" to "accommodate", so

  ```
  to accomodate our fully remote brigade.
  ```
  becomes
  ```
  to accommodate our fully remote brigade.
  ```
- [ ] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/sitemap/
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/sitemap.html
Line of code:
https://github.com/hackforla/website/blob/6c99fa3042ac616ae9e7ab456c157b842be441fb/pages/sitemap.html#L14
sitemap_before
sitemap_after

### PR DESCRIPTION
**Pull request by kathrynsilvaconway**
Fixes #2941

### What changes did you make and why did you make them ?

  -Corrected spelling of the word 'accommodate' in the Site Map html file on line 14. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

sitemap_after

<details>
<summary>Visuals before changes are applied</summary>

sitemap_before
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
sitemap_after
</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Availability: 1 hour
Review ETA: Within the next hour

**Review by Jaretzbalba — APPROVED** [review]
Looks like you fixed the spelling error and everything looks good! Thank you for working on this issue!

**Comment by answebdev** [comment]
Review ETA: 3/25/2022 (end of day)
Availability: 1 hour

**Review by answebdev — APPROVED** [review]
@kathrynsilvaconway Thank you for submitting your PR. For this issue, the spelling on line 14 of `pages/sitemap.html` needed to be changed from "accomodate" to "accommodate", which I can see that you did. I was also able to see this change in the browser. Great job with that!

Also, please add this PR to the Project Board. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@kathrynsilvaconway Thanks a lot for working on this issue. Really good work, just wanted to request you to add the images of the webpage before and after the changes were made. It would really help the QA. Once done, please request a re-review by clicking the icon next to my GitHub handle on top right. Thanks once again for your help.

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@kathrynsilvaconway Thanks a lot for working on this issue. Really good work, just wanted to request you to add the images of the webpage, before and after the changes were made. It would really help the QA. Once done, please request a re-review by clicking the icon next to my GitHub handle on top right. Thanks once again for your help.

**Review by answebdev — APPROVED** [review]
@kathrynsilvaconway Thank you for adding your PR to the Project Board. Everything else looks good. Great job!

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway I saw that you added images to your issue but the images should be added in the "Screenshots of Proposed Changes of the Website" section above in your first pr comment:
Screenshot 2022-03-26 201028

**Review by answebdev — APPROVED** [review]
@kathrynsilvaconway Thank you for adding the screenshots of before and after the changes made. Looks good. Great job with that!

**Review by Jaretzbalba — APPROVED** [review]
@kathrynsilvaconway Thank you for adding the images and fixing the issue! Everything looks good!

**Review by SAUMILDHANKAR — APPROVED** [review]
Thanks for adding the images. Ready to merge.

**Pull request merged**
