### PR TITLE
Changed content field to content-type and removed type field in credits/404 yml file

### LINKED ISSUE #2633: Edit content field and remove type field from 404.yml credits file
### Dependency
- [x] - #2642

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/404.yml`, do the following:

- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
   ```
   type: icon
   ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/404.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/6bb9e8aa9aff0d44a46419ec54ebc342ae073bf0/_data/internal/credits/404.yml#L4
https://github.com/hackforla/website/blob/6bb9e8aa9aff0d44a46419ec54ebc342ae073bf0/_data/internal/credits/404.yml#L11

Availability for this week: 6 hrs
My estimated ETA for completing this issue: 10 minutes

### LINKED ISSUE #2642: Update Credits yml file template
### Overview
As a member of the team, we need to ensure the Wiki is an up to date and accurate resource. For this issue, we will update the [Credits yml file template](https://github.com/hackforla/website/wiki/Credits-yml-file-template).

### Action Items
This will be an issue worked on and discussed during development team meetings.
- [x] Figure out why there are two name values for (content and type) which seem the same
  - [x] You may want to see how (if anywhere) content and type are used in our code 
- [x] Update the [Credits yml file template](https://github.com/hackforla/website/wiki/Credits-yml-file-template)
- [x] Release dependency on https://github.com/hackforla/website/issues/2633
  - [x] Update action items in the dependency issue if needed 

### Resources/Instructions
- [Credits yml file template](https://github.com/hackforla/website/wiki/Credits-yml-file-template)
- [pages/credits.html](https://github.com/hackforla/website/blob/e33b5d42e8c048255b2448ca5567f511c85dc1c2/pages/credits.html)
- This issue might be helpful in figuring out what the difference between content and type are: https://github.com/hackforla/website/issues/571

### PR DESCRIPTION
**Pull request by scorbz9**
Fixes #2633

### What changes did you make and why did you make them ?

  - Updated content field to read content-type: image
  - Deleted type field from file
  - This will make the code easier to understand for other developers and less redundant

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual updates to website

### CODE REVIEW

**Comment by answebdev** [comment]
ETA: 5/18/2022 (end of day)
Availability: 2 hours

**Review by answebdev — APPROVED** [review]
@scorbz9 Thank you for submitting your PR. For this issue, `content: Image` needed to be changed to `content-type: image` (line 4), and `type: icon` needed to be removed (line 11) for the file `_data/internal/credits/404.yml`, which I can see that you did. There is a linked issue, and you have also added the PR to the project board. Great job!

**Comment by harshitasao** [comment]
Availability: 10pm-11pm IST
Review ETA: 19/05/2022 (End of the day)

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Thursday, May 19

**Comment by tamara-snyder** [comment]
Hi @scorbz9, great work on this! I can see that you replaced ```content: Image``` with ```content-type: image``` and removed the redundant ```type: icon``` line. Well done!

**Pull request merged**
