### PR TITLE
Removed hex code abbreviations and replaced with the full hex code to fix issue #3355

### LINKED ISSUE #3355: Replace 3 digit abbreviated hex color codes in _colors.scss
### Overview
We need to replace the 3 digit abbreviated hex color codes in _colors.scss with its equivalent 6 digit hex color codes so that it fits in with the rest of the values on the page which are all 6 digit, which will promote readability.

### Action Items
Open _sass/variables/_colors.scss in VS Code or your IDE, then
- [x]  Change the line `$color-black: #333;` to `$color-black: #333333;`
- [x]  Change the line `$color-mediumgrey: #ccc;` to `$color-mediumgrey: #cccccc;`
- [x]  Change the line `$color-white: #fff;` to `$color-white: #ffffff`

### Resources/Instructions
[_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss)

### PR DESCRIPTION
**Pull request by JohnJBarrett22**
Fixes #3355

### What changes did you make and why did you make them ?

  - Filled in the full hex codes in place of the abbreviations that were there.

### CODE REVIEW

**Comment by tunglinn** [comment]
ETA: today
Availability: 1hr

**Review by tunglinn — APPROVED** [review]
Merge branches look good. All changes mentioned in the issue are implemented. The site looks the same and is not broken. Great job, John!

**Comment by ericvennemeyer** [comment]
`ETA`: EOD (Today, Tuesday 8/16)
`Availability`: 1 hr

**Review by ericvennemeyer — APPROVED** [review]
Branches are correct, requested changes have been made, and site doesn't break. Looks good!

**Pull request merged**
