### PR TITLE
Update project profile civic tech jobs add benny van 5390

### LINKED ISSUE #5390: Update Project Profile: Civic Tech Jobs (add Benny Van)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] Add a new entry for Benny Van:
```
  - name: Benny Van
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U05JP90EHMK
      github: https://github.com/bennyv8
    picture: https://avatars.githubusercontent.com/bennyv8
```
 - [x] Place Benny's profile after the other Developers' profiles
 - [x] Confirm on your local that links for the member appear to be correct (for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by innith**
Fixes #5390 

### What changes did you make?
  - added Benny Van to civic tech jobs project under leadership.

### Why did you make the changes (we will use this info to test)?
  - to keep the website up to date and accurate.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/5/23
Availability: 1-3 PM everyday

**Comment by ortegaa32** [comment]
- Branches set up correctly and PR links to correct issue
- Changes accurately reflected in screenshots and don't appear to break the website
- Changes are clean and done in the correct file
Great job on your first pull request @innith! Approved!

**Review by ortegaa32 — APPROVED** [review]

**Comment by LRenDO** [comment]
Hi @janice87 and @one2code! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hey @innith Great job! Your branches are correct, the original file is linked, you are explaining what changes you made and for what reason, and you provided visuals showing before and after. The edits are clean and look correct on Docker.   

Thanks for your work!

**Pull request merged**
