### PR TITLE
Blaycoder update guide teams 5584

### LINKED ISSUE #5584: Update Project Profile: Guides Team (Remove Shawn Wong)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the project information for Guides Team so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the `_projects/guides-team.md` file and make the following change:
  - [x] Under the `leadership` section, 
    - [x] Remove 
      ```
        - name: Shawn Wong
          role: Product Manager
          links:
            slack: 'https://hackforla.slack.com/team/U04MXRWPQ64'
            github: 'https://github.com/seannwvong'
          picture: https://avatars.githubusercontent.com/seannwvong
      ```
- [x] Verify the changes by viewing the Guides Team page [^1] in your local environment and include before and after screenshots with your pull request

### Resources/Instructions
- This issue was initiated by #5407
[^1]: Project page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by blaycoder**
Fixes #5584 

### What changes did you make?
 I removed the empty line in line 23 as requested from @kwangric  https://github.com/hackforla/website/pull/5648#issue-1923043395

### Why did you make the changes (we will use this info to test)?
To update the project information for Guides Team so that visitors to the website can find accurate and up-to-date information.

### CODE REVIEW

**Comment by kwangric** [comment]
Hey @blaycoder, thanks for making the changes! When you make changes, please update the [original pull request](https://github.com/hackforla/website/pull/5648) so the reviewers can easily review the code again and see the changes made.

**Comment by LukeLowrey2** [comment]
Availability: Tuesday 10/10/23 10am - 12pm
ETA: Tuesday 10/10/23 EOD

**Review by LukeLowrey2 — DISMISSED** [review]
Hello @blaycoder!

- The issue is linked to the pull request
- You are committing into the correct branch
- You have properly removed what was specified in the issue from the guides-team section 

Thank you for working on this issue. Great job!

**Comment by freaky4wrld** [comment]
Availability: Thursday 12th October, Evening
ETA: Friday 13th October, EOD

**Review by freaky4wrld — DISMISSED** [review]
Hey @blaycoder you have 
- Provided the linked PR here
- Removed the specified section and confirmed it by providing the visual changes in the linked PR
- Also the correction is made, i.e **to remove the blank line at line number 23**
- The merging branch is going into correct branch i.e ` gh-pages `

You can now update the changes to the linked PR, so that other reviewers can review it.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @blaycoder Thanks for working on the PR and your efforts to address the comments by @kwangric on the previous PR. Great work so far!

There are some items that need to be addressed before merging and completing this issue/PR: 
- It is OK to open a second PR- just please remember to add a comment on the first one, and in the comment provide the second PR number, and then close the first PR.
- When you make the second PR, all of the original information (i.e. the ‘Fixes: ‘, the what you did and why, the visuals, etc.) needs to copy over to the second PR since it is replacing the first PR.
- Unfortunately, in the time since you started working on this issue, a separate issue (#5672 fixes #5624) added a new profile to the Guides team and this causes a ‘merge conflict’ with your PR. If you have not seen this before, it sounds worse than it is: it just means that your branch does not include the new information from the other PR and git needs direction on which information is correct. There are a couple of ways to address this, but in this case I probably would:
  - Scroll down to the bottom of this PR and select ‘Resolve conflicts’
  - First delete lines 31 through 37, then delete lines 23-24.
  - The six lines for ‘Sarah Levine’ should remain.
  - Scroll back up, select ‘Mark as resolved’  
  
As a final step after copying the relevant info from the original PR to this one and then resolving the merge conflict, select the chasing arrows next to everyone’s name in ‘Reviewers’ so that this can be re-reviewed  
  
If you would like to discuss in person, please contact me or anyone else on the merge team.

**Comment by blaycoder** [comment]
> Hi @blaycoder Thanks for working on the PR and your efforts to address the comments by @kwangric on the previous PR. Great work so far!
> 
> There are some items that need to be addressed before merging and completing this issue/PR:
> 
> * It is OK to open a second PR- just please remember to add a comment on the first one, and in the comment provide the second PR number, and then close the first PR.
> * When you make the second PR, all of the original information (i.e. the ‘Fixes: ‘, the what you did and why, the visuals, etc.) needs to copy over to the second PR since it is replacing the first PR.
> * Unfortunately, in the time since you started working on this issue, a separate issue ([Add pm 5624 #5672](https://github.com/hackforla/website/pull/5672) fixes [Update Project Profile: Guides Team (Add Sarah Levine) #5624](https://github.com/hackforla/website/issues/5624)) added a new profile to the Guides team and this causes a ‘merge conflict’ with your PR. If you have not seen this before, it sounds worse than it is: it just means that your branch does not include the new information from the other PR and git needs direction on which information is correct. There are a couple of ways to address this, but in this case I probably would:
>   
>   * Scroll down to the bottom of this PR and select ‘Resolve conflicts’
>   * First delete lines 31 through 37, then delete lines 23-24.
>   * The six lines for ‘Sarah Levine’ should remain.
>   * Scroll back up, select ‘Mark as resolved’
> 
> As a final step after copying the relevant info from the original PR to this one and then resolving the merge conflict, select the chasing arrows next to everyone’s name in ‘Reviewers’ so that this can be re-reviewed
> 
> If you would like to discuss in person, please contact me or anyone else on the merge team.

How can I contact you?
What should I do to solve this issue and How do I avoid this from happening again when next I am working on another issue?

**Comment by blaycoder** [comment]
> Hi @blaycoder Thanks for working on the PR and your efforts to address the comments by @kwangric on the previous PR. Great work so far!
> 
> There are some items that need to be addressed before merging and completing this issue/PR:
> 
> * It is OK to open a second PR- just please remember to add a comment on the first one, and in the comment provide the second PR number, and then close the first PR.
> * When you make the second PR, all of the original information (i.e. the ‘Fixes: ‘, the what you did and why, the visuals, etc.) needs to copy over to the second PR since it is replacing the first PR.
> * Unfortunately, in the time since you started working on this issue, a separate issue ([Add pm 5624 #5672](https://github.com/hackforla/website/pull/5672) fixes [Update Project Profile: Guides Team (Add Sarah Levine) #5624](https://github.com/hackforla/website/issues/5624)) added a new profile to the Guides team and this causes a ‘merge conflict’ with your PR. If you have not seen this before, it sounds worse than it is: it just means that your branch does not include the new information from the other PR and git needs direction on which information is correct. There are a couple of ways to address this, but in this case I probably would:
>   
>   * Scroll down to the bottom of this PR and select ‘Resolve conflicts’
>   * First delete lines 31 through 37, then delete lines 23-24.
>   * The six lines for ‘Sarah Levine’ should remain.
>   * Scroll back up, select ‘Mark as resolved’
> 
> As a final step after copying the relevant info from the original PR to this one and then resolving the merge conflict, select the chasing arrows next to everyone’s name in ‘Reviewers’ so that this can be re-reviewed
> 
> If you would like to discuss in person, please contact me or anyone else on the merge team.

I have work on the issues you addressed. Thanks for helping out @t-will-gillis

**Review by t-will-gillis — APPROVED** [review]
Hi @blaycoder - Great thanks for fixing the merge conflict and closing the other PR!

**Pull request merged**
