### PR TITLE
removed alejandro gomez info from engineering yml file

### LINKED ISSUE #6074: Update Communities of Practice: Engineering (Remove Alejandro Gomez)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Alejandro Gomez
    role: Co-Lead
    links:
      slack: https://hackforla.slack.com/team/U04HFRQ5Y12
      github: https://github.com/agosmou
    picture: https://avatars.githubusercontent.com/agosmou
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #6060 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6060 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6060
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by jtw007**
Fixes #6074

### What changes did you make?
  - removed Alejandro Gomez information from yml file

### Why did you make the changes (we will use this info to test)?
  - Keeping information up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2024-01-18 at 14 53 34

</details>

<details>
<summary

>Visuals after changes are applied</summary>
  
Screen Shot 2024-01-18 at 14 52 47

</details>

### CODE REVIEW

**Review by jlevot — APPROVED** [review]
@jtw007, branches are set up correctly (don't forget for your next branch to add the issue number in the suffix like the in the [documentation](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)). The correct issue is linked and the requested changes to remove Alejandro Gomez from the list have been made.

Good job 👍 

Just an advice for you next PR, you can improve the clarity of the body:
- Add screenshots before/after of the website view, not of the code. The goal is to have a visual rendering of your work.

Feel free to contact me on slack if you have any questions.

**Review by tonyvang — APPROVED** [review]
Hi jtw007, apologies for reviewing a day after my ETA,

Your pull request merges correctly into hackforla:gh-pages from your working branch. The [H4LA wiki on contributing recommends](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) giving your branch a name that indicates a bit about the issue being addressed and includes the issue number.

You have correctly linked the issue in your pull request. As jlevot mentioned, screenshots of the effect of the change on your local build of the site would be helpful. Nevertheless, your code change looks correct and appropriate to the issue, and tests on my machine to the desired effect. I am approving this request.

Good work jtw007, and thanks for contributing!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @jtw007 Good job and thanks for picking up this issue! Your branches are good (but as @jlevot mentions, adding the issue number in the suffix is helpful), you are linked back to the issue, and you are leaving a brief description of what you did and why. Your code edits are perfect. 

Some comments: as the previous reviewers mentioned, please provide 'before' and 'after' screenshots showing the change to the website. Also, regarding the formatting at "what changes did you make?" and why, please add a space between the dash and the letter at `-removed` and `-keeping`, and then remove the unused dashes- this should fix the formatting. 

Thanks again for your work on this!

**Comment by jtw007** [comment]
> Hi @jtw007 Good job and thanks for picking up this issue! Your branches are good (but as @jlevot mentions, adding the issue number in the suffix is helpful), you are linked back to the issue, and you are leaving a brief description of what you did and why. Your code edits are perfect.
> 
> Some comments: as the previous reviewers mentioned, please provide 'before' and 'after' screenshots showing the change to the website. Also, regarding the formatting at "what changes did you make?" and why, please add a space between the dash and the letter at `-removed` and `-keeping`, and then remove the unused dashes- this should fix the formatting.
> 
> Thanks again for your work on this!

Changes made! There were no visual changes to the website that I saw on my end so there weren't any screenshots I could provide. Thank you for the feedback @t-will-gillis @tonyvang

**Comment by t-will-gillis** [comment]
Hi @jtw007 Thanks for making the changes!
The screenshots are for the changes to the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page, i.e.
<details>
Screenshot 2024-01-17 125947



</details>

**Comment by jtw007** [comment]
> Hi @jtw007 Thanks for making the changes! The screenshots are for the changes to the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page, i.e.

Fixed! Apologies for the delay - initially when I viewed the website on my local docker container I didn't see an update but now I do. Will be following this format going forward, thank you for the feedback and help! @t-will-gillis

**Review by t-will-gillis — APPROVED** [review]
@jtw007 Thanks for adding the screenshots- looks great!

**Pull request merged**
