### PR TITLE
Remove good second issue 5617

### LINKED ISSUE #5617: Remove "good second issue" from CONTRIBUTING.md Section 2.3.c
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove mention of  the "Compleity: Good second issue" label in order to eliminate confusion, since we are no longer ceating issues with the "Complexity: Good second issue" label.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` Section 2.3.c
- [x] Remove this line:
```
* `Prioritized Backlog` column in the [filtered Project Board - **complexity: Good second issues** label](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22complexity%3A+good+second+issue%22+label%3A%22role%3A+back+end%2Fdevops%22)
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4506

### PR DESCRIPTION
**Pull request by tkozek**
Fixes #5617 

### What changes did you make?
  -Removed the following line from CONTRIBUTING.md Section 2.3.c:

`* `Prioritized Backlog` column in the [filtered Project Board - **complexity: Good second issues** label](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22complexity%3A+good+second+issue%22+label%3A%22role%3A+back+end%2Fdevops%22)`

### Why did you make the changes?
  -In order to eliminate confusion, since Hack for LA is no longer creating issues with the "good second issue" label
 -For Reviewers: Do not review changes locally, rather, review changes at:

 https://github.com/tkozek/website/blob/remove-good-second-issue-5617/CONTRIBUTING.md#23c-available-issues-for-returning-members-back-end

### Screenshots of Proposed Changes Of The Website
Before:
image

After:

image

### CODE REVIEW

**Comment by JanineSooThow** [comment]
Availability: Tuesdays NZT
ETA: Before Wednesday 11th October

**Review by JanineSooThow — APPROVED** [review]
Well done @tkozek on the changes. Changes made were applicable :) Good job!

**Comment by robertnjenga** [comment]
Review ETA:  10/10/2023
Availability: 10am - 2pm

**Review by robertnjenga — APPROVED** [review]
Hi @tkozek Great job with the issue!
The branching is set up correctly.
You linked the issue.
Changes appear correctly in the test URL. Well done!

**Pull request merged**
