### PR TITLE
Remove alt-hero field from vrms.md project file

### LINKED ISSUE #3214: Remove unused `alt-hero` field from vrms.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/vrms.md`, remove line 8 for the alt-hero
```
alt-hero: 'City of LA skyline at dusk.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/vrms.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a2c97475e2d1ab5956bf5cbe95c7e251ce8a1033/_projects/vrms.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by DonaldBrower**
Fixes #3214

### What changes did you make and why did you make them ?

  - Removed the `alt-hero` field from `_projects/vrms.md`
    - This field isn't used anywhere in the codebase, since the hero image is a CSS background image.  
    - If the hero image were used in an HTML tag, the `alt=""` properties could be set using information from other fields in this file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Editing this file did not create any visual changes.

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Tuesday, June 7th

**Review by Wny-Duong — APPROVED** [review]
Line 8 containing alt-hero is removed from vrms.md. There shouldn't be visual changes so it looks good to me. Great work.

**Comment by answebdev** [comment]
Availability: 1 hour
Review ETA: 6/10/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@DonaldBrower Thank you for submitting your PR. For this issue, line 8 for the alt-hero in the file `_projects/vrms.md` needed to be removed, which I can see that you did. There also should not be any visual changes, so everything looks good. Great job!

**Pull request merged**
