### PR TITLE
Completed: (Update Project Profile: Lucky Parking (Update Technologies) #5790)

### LINKED ISSUE #5790: Update Project Profile: Lucky Parking (Update Technologies)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `technologies` variable and change the following:

**From:**
```
  - React
  - AWS
  - PostgreSQL
  - Node.js
  - Mapbox
```
**To:**
```
  - React
  - TailwindCSS
  - Mapbox
  - Node.js
  - Express
  - MongoDB
  - AWS
  - Markdown
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by dustinowen**
Fixes #5790 

### What changes did you make?
  - Updated technologies

### Why did you make the changes (we will use this info to test)?
  - Per Update Project Profile: Lucky Parking (Update Technologies) #5790

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Project card (before)
Project Page (before)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Project card (after update)
Project page (after update)

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
Hey @dustinowen! Please edit the first line of your PR so it includes the issue number (e.g. `Fixes #5790`) to properly link the issue to the PR. This will also help reviewers know what changes were requested. Thanks!

**Comment by ajb176** [comment]
ETA: November 4th EOD
Availability: 6-8am, all days

My mistake, ETA 2 hours

**Comment by agutiernc** [comment]
Availability: After 7pm, Nov. 5th
ETA: November 5th EOD

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hey Dustin, 

You're meant to create a new, distinct branch when working on an issue. gh-pages is meant to be the main branch of your fork, and you don't want to have your main branch affected by potentially problematic commits. Ideally your gh-pages only pulls changes approved by the merge team from upstream. 

You can find information on branch creation and naming convention [here.](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) 

The code looks good and the PR is formatted well, but you should probably re-do the PR while following the above guidelines to get a sense of the proper procedure. Once you create a new PR, you can close this one and request a review from me. If you really would rather not re-do it, I'll approve the PR after testing and see if the merge team lets it slide since it shouldn't cause any issues.

**Comment by agutiernc** [comment]
Hi @dustinowen,
I also noticed what @ajb176 mentioned about making a branch that refers to the issue as a title. An example of naming a branch and steps are mentioned in [2.7b, of the contributing doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue).

Other than that, the changes that you made are correct. Whichever choice that you do with what @ajb176 recommended, let us know, so that we can approve or not.

**Comment by dustinowen** [comment]
@agutiernc @ajb176 

Thank you for the feedback/information, I apologize for the oversight. I have submitted a new pull request which I will tag you both in. I have made note of this for issues going forward.

**Pull request closed without merging**
