### PR TITLE
Changed "vertical" to "program area"

### LINKED ISSUE #1554: Change all project.md files to include "Program Area" Instead of "Vertical"
### Overview
We need to replace all mentions of "Vertical" with "Program Area" instead in all project.md files (including the [wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)) because these have been renamed (referring to the social cause of the project)

### Action Items
- [x] Find where the "Vertical" is in the project.md files
- [x] Replace all "Vertical" mentions in all project.md files with "Program Area" instead
- [x] Replace "Vertical" with "Program Area" in the [project.md template wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) as well
- [x] Check if there are any other instances of "Vertical" in the code that need to be updated to Program Area

### Resources/Instructions
[Project.md template wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

### PR DESCRIPTION
**Pull request by Aveline-art**
Fixes #1554 

No images, as changes do not reflect on webpage, as far as I can tell.

Changes to wiki:
[Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
[Compare: Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file/_compare/d81d1c65d0acb9468c6db755f069e6a069e2c9e9...7e4c67ade256da2e4d39953defc503acc318be86)

### CODE REVIEW

**Review by qiqicodes — APPROVED** [review]
lgtm

**Review by akibrhast — APPROVED** [review]
lgtm!

**Comment by qiqicodes** [comment]
Please audit these two files while review this PR, to make sure the "program area" create no change to the site.
1. website/pages/program-areas.html
2. website/_layouts/project.html

The web pages that this change would affect are:
1. https://www.hackforla.org/
2. https://www.hackforla.org/#projects
3. https://www.hackforla.org/projects/100-automations (27 individual projects)

**Comment by Aveline-art** [comment]
@josiehandeveloper Hi! Can you review this PR so that it may be merged? I cannot start another issue with my current one still open.

**Comment by josiehandeveloper** [comment]
Yes! I'll get on it

**Comment by josiehandeveloper** [comment]
Lgtm

**Review by josiehandeveloper — APPROVED** [review]
Good job!

**Pull request merged**
