### PR TITLE
Update HelloGov Slack Link

### LINKED ISSUE #2444: Update HelloGov Slack link
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly and are up to date.

### Action Items
- [x] Change the GitHub link for HelloGov so it resolves to the correct url
    - **Line 33** under `_projects/hellogov.md`

From:
```
url: 'https://hackforla.slack.com/archives/CMER3R1RD'
```
To:
```
url: 'https://hackforla.slack.com/messages/CDA23KHKP'
```
- [x] Ensure that clicking the Slack link from the [projects page](https://www.hackforla.org/projects/) and [HelloGov page](https://www.hackforla.org/projects/hellogov) both resolve to the new address

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/hellogov.md`
- [Projects page](https://www.hackforla.org/projects/)
- [HelloGov page](https://www.hackforla.org/projects/hellogov)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/8b2585f5cd0ac7c5ff568b7d790832f9935a5a01/_projects/hellogov.md#L33

### PR DESCRIPTION
**Pull request by lindseyindev**
Fixes #2444

### What changes did you make and why did you make them ?

  - Updated projects/hellogov slack link to url: 'https://hackforla.slack.com/messages/CDA23KHKP' because the previous link was out of date.

### Screenshots of Proposed Changes Of The Website 
Updated a redirect link, no visual changes.

### CODE REVIEW

**Review by JessicaLucindaCheng — APPROVED** [review]
@lindseydotdev The changes look good. Great job!

**Comment by JessicaLucindaCheng** [comment]
@lindseydotdev Could you add this pull request to the Project Board? Thanks.

**Comment by lindseyindev** [comment]
@JessicaLucindaCheng yes sorry! thank you for letting me know

**Review by macho-catt — APPROVED** [review]
LGTM. Good job on your first issue, and feel free to pick up a 2nd one

**Pull request merged**
