### PR TITLE
Updated Tools and Current Project Team sections for the Design Systems project profile

### LINKED ISSUE #2745: Update Project Profile: Design systems
### Overview
As a product manager of Design systems I want my project's details to be up to date on the HackforLA website

### Project card
_insert url of their card here before sending - their cards can be found in this folder: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md

### Action Items

- [ ] Design systems team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [ ] tools
      - [x] status
 - [x] Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below

### Resources
- https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md

### PR DESCRIPTION
**Pull request by JessicaLucindaCheng**
Fixes #2745 

### What changes did you make and why did you make them?
  - As requested, I added the tools and removed and added members to the Current Project Team section.
  - Also, when I was adding the members, I tried adding the members with the same roles after each other, so that it would display on the page with members with the same roles together to make it look more organized.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

current-design-systems-page

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
updated-design-systems-page

</details>

### CODE REVIEW

**Comment by scarter31191** [comment]
I see that this issue is time-sensitive is it ok if I review it, even though there are already two assigned reviewers?

**Comment by scarter31191** [comment]
Availability for this week: 3/26, 3/27
My estimated ETA for completing this issue: 3/27

**Review by scarter31191 — APPROVED** [review]
"Great job! Everything looks perfect Jessica! I enjoyed how you organized it."

**Review by SAUMILDHANKAR — APPROVED** [review]
@JessicaLucindaCheng Thank you once again for leading the way and working on this issue. Changes look good in my environment.

**Pull request merged**
