### PR TITLE
Remove the ending slash on the img tag

### LINKED ISSUE #4381: img Tag Refactor: Getting Started page - `step-img-icon-attend-git join-2.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-attend-git" src="assets/images/getting-started/join-2.png" alt="" />
```
to
```
<img class="step-img-icon-attend-git" src="assets/images/getting-started/join-2.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by bphan002**
Fixes #4381

### What changes did you make and why did you make them ?
  - Changed the img tag by removing the slash
  - Change was made to keep it consistent with all the other img tags

### Screenshots of Proposed Changes Of The Website  
N/A

### CODE REVIEW

**Comment by pdimaano** [comment]
Availability: Weekday evenings
ETA: 4/24/2023

**Review by pdimaano — DISMISSED** [review]
Nice work on this: the correct linked issue is present, the right feature branch was used and the website visuals are intact when viewed in the browser. Good job!

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM - 3PM
ETA: 4/24/23

**Review by Thinking-Panda — COMMENTED** [review]
Hello @bphan002 , Thank you for working on this issue. The merge branches look good. The changes made are as mentioned in the issue. The code could be made cleaner by removing the space just before the closing tag (alt="" >)

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @bphan002, thank you for working on the issue! Could you:

- remove the space at the end of the img element as shown in issue #4381 and as @Thinking-Panda mentioned. This is mainly to keep the code style consistent across our repository. 
- update your pull request comment to remove the text in the boxed area in the screenshot below. If there aren't any visual changes to the website, no need to have them there. This is mainly to follow HackforLA's  documentation practices. 

image

**Comment by Adastros** [comment]
Hi @Thinking-Panda, thanks for reviewing the pull request and catching the spacing issue! Wasn't sure if you requesting changes for this pull request but if you were, don't forget to submit your comment as "request changes". This is so the pull request doesn't get accidentally merged if there's something we can do to fix/improve the code. Reference the image in [Step 6 ](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-6-approve-the-pull-request) in the How to Review a Pull Request guide on how to request changes.

**Comment by bphan002** [comment]
Thank you for the feedback.  I've made the needed changes.

**Comment by Thinking-Panda** [comment]
> Hi @Thinking-Panda, thanks for reviewing the pull request and catching the spacing issue! Wasn't sure if you requesting changes for this pull request but if you were, don't forget to submit your comment as "request changes". This is so the pull request doesn't get accidentally merged if there's something we can do to fix/improve the code. Reference the image in [Step 6 ](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-6-approve-the-pull-request) in the How to Review a Pull Request guide on how to request changes.

Got it. Next time I will post it as "Request Changes"

**Review by Thinking-Panda — APPROVED** [review]
Hi @bphan002 , thank you for making the changes. Website works perfect on my local machine.

**Review by pdimaano — APPROVED** [review]

**Review by Adastros — APPROVED** [review]
Thanks for implementing the changes @bphan002! Everything looks good.

**Pull request merged**
