### PR TITLE
About refactor

### PR DESCRIPTION
**Pull request by akibrhast**
Refactor about page

- Break down about page to smaller componentized sections
- Redo `about.yml` to `executive_letter.yml` and `accomplishments.yml` as discussed on Sundays meeting

### CODE REVIEW

**Review by jbubar — COMMENTED** [review]
fix the donate gif 
and delete the unused js code for the see more... it might be breaking things

**Comment by averdin2** [comment]
@akibrhast I found a strange issue with the page card resizing that does not seem so to be so extreme in the current site. For some reason, the page cards resize too large when in iPad landscape viewport range. I don't know what is causing this to behave this way. Maybe something to do with @jbubar's comment? I have added some gifs below to show what I mean.

<details>
<summary>Gifs</summary>

1.  First, here is how it is broken in regards to this PR. Notice how the page card resizes too big.
about_page_card_broken

2. Here is how it looks on the current site. You can see that the page card does seem to resize a little bit, but not too big. I'm not sure why it would even resize 😕 ?
about_page_card_fine


</details>

**Comment by akibrhast** [comment]
@averdin2 @jbubar Thank you for your reviews. I have made the changes as requested in the above comments.

**Review by erikaBell — CHANGES_REQUESTED** [review]
Making note that we are waiting for changes to be added to the letter: "Read More" and toggle functionality. 

Also @akibrhast I think you mentioned to me a couple days ago there is a dependency for this PR? Can you let us know what that is.

**Comment by akibrhast** [comment]
Unfortunately I am not going to have time to work on this until after sunday evening . This issue is currently blocking @averdin2 PR
https://github.com/hackforla/website/pull/1430

**Comment by akibrhast** [comment]
Hey Everyone assigned as a reviewer, can you please review it again. 
@erikaBell @jbubar @daniellex0 @averdin2.

**Review by erikaBell — CHANGES_REQUESTED** [review]
Looking stellar ~ My only request, to remove console.logs  (-;


goodwork

**Comment by averdin2** [comment]
Everything mostly looks really good to me. Great job @akibrhast! However, I noticed that there seems to be a problem with how the card's accordion arrows are oriented when the page is resized from desktop to mobile. The accordion arrows seem to point the wrong way, but fix themselves as the accordion is closed and reopened. See the gif below for more details. I think this could be made into its own issue. Otherwise, the changes look good.

<details>
<summary>Gif</summary>

about_page_accordion
</details>

**Review by averdin2 — APPROVED** [review]
Other than the suggestions made in https://github.com/hackforla/website/pull/1424#issuecomment-827999944, I think the changes look good.

**Review by daniellex0 — CHANGES_REQUESTED** [review]
Hmm everything looks ok visually, but the issue is that when you scroll down, the page jumps down between page cards in an annoying way that doesn't let you finish reading, and it didn't used to do that in the old version- that one scrolled smoothly. Any idea what's causing that?

**Comment by akibrhast** [comment]
@daniellex0 Nice catch there, the scroll was indeed janky. I have pushed in a fix. Could you please check if it fixes it.

**Review by daniellex0 — APPROVED** [review]
Great, indeed scrolling smoothly now- approved! 👍

**Review by averdin2 — APPROVED** [review]
Spoke about in dev meeting on Tuesday. Issue was created to address accordion arrow bug https://github.com/hackforla/website/issues/1481. This PR is good to go :shipit:

**Pull request merged**
