### PR TITLE
New citizen page 2180

### LINKED ISSUE #2180: Create a Citizen engagement page layout
### Overview
We need to create a template page for the program area Citizen engagement so that people can find the project related to this program area.

### Action Items
Development
- [x] Develop the Donate page based on the design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4947%3A26584) in the pink rectangle
- [x] Do not link the page to the website yet- this should remain an unlinked page for now, until the new home page is finished
- [x] Add header image to [Credits](https://www.hackforla.org/credits/) page

### Resources/Instructions
[How to Create a new HfLA website page](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website)
[HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)

Design issue for the Citizen Engagement page https://github.com/hackforla/website/issues/1879

### PR DESCRIPTION
**Pull request by R-Tomas-Gonzalez**
Fixes #2180

### What changes did you make and why did you make them ?

  - Addressed @macho-catt comment in pull request #2324. When merged the CSS interfered with other pages on the site. 
  - Added new class names to the components which I have changed and added comments in the SCSS stylesheet to reflect new names.
  - Made sure all other pages were not reflecting css styles.
  - NOTE: Showing the home projects page because this was one of the other pages that was being effected by the citizen-engagement scss file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2021-10-19 at 2 46 30 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2021-10-19 at 2 46 46 PM

</details>

### CODE REVIEW

**Review by macho-catt — APPROVED** [review]
@R-Tomas-Gonzalez this looks good to me. Good job!

Of course as mentioned in your last PR, there are some improvements we can do on this page that we can open separate issues on just so you're not stuck on this page. Let me know if you want to help in creating those issues. 

These are the issues that will need to be created (@abuna1985 if you have more you can think of please let me know).
- Extract JS into a separate file
- Instead of the page statically rendering the data, it should pull data from MD files based on which projects are part of the citizen engagement program area and render those to the page
- Organization images could also be placed in YML files and rendered based on data on that file, instead of statically rendered

I will merge this PR by tonight, unless Adam has any additional inputs.

**Comment by R-Tomas-Gonzalez** [comment]
> @R-Tomas-Gonzalez this looks good to me. Good job!
> 
> Of course as mentioned in your last PR, there are some improvements we can do on this page that we can open separate issues on just so you're not stuck on this page. Let me know if you want to help in creating those issues.
> 
> These are the issues that will need to be created (@abuna1985 if you have more you can think of please let me know).
> 
> * Extract JS into a separate file
> * Instead of the page statically rendering the data, it should pull data from MD files based on which projects are part of the citizen engagement program area and render those to the page
> * Organization images could also be placed in YML files and rendered based on data on that file, instead of statically rendered
> 
> I will merge this PR by tonight, unless Adam has any additional inputs.

Yeah, would love to get with you on creating an issue. And then I can do the other on my own!

**Review by adam-abundis — APPROVED** [review]
Everything looks good. @R-Tomas-Gonzalez go ahead and get with @macho-catt regarding making the issues from this pull request. Thank you for all your work on this.

**Comment by macho-catt** [comment]
Created issues #2474 and #2475. @R-Tomas-Gonzalez will create an issue for extracting the JS portion into a separate file under assets/js

**Pull request merged**
