### PR TITLE
Rename about us page to about

### LINKED ISSUE #864: Rename about-us page to about
### Dependency
~#966 #967 #862~

### Overview
We need to rename the page to from about-us to "about" to maintain consistent naming convention throughout the project.

### Action Items

- [x] There is an _about.scss file.  Figure out if is it still being used for anything, and if it can be renamed, deleted, etc. 
- [x] Rename the about-us page to about
- [x] Rename _about-us.scss to _about.scss (unless the current _about.scss can't be renamed for some reason)
- [x] Rename assets/js/about-us.js to about.js . 

### Resources/Instructions
https://www.hackforla.org/about-us

### PR DESCRIPTION
**Pull request by kevinreber**
fixes #864 

- Renamed `about-us` page and it's assets to `about`
- Renamed `_about.scss` as ` _home.scss`
- Imported `_home.scss` into `main.scss`
- Renamed `_about-us.scss` as `_about.scss`
- Delete `_about-us.scss` and remove from `main.scss`

### CODE REVIEW

**Comment by akibrhast** [comment]
@kevinreber  Can you please explain what these changes in the image below in your pull request mean?

<details>
<summary>Img</summary>

image

</details>

These are the only files that should have been changed in this pull request right? Why are assets and image files within the commit?

> - Renamed `about-us` page and it's assets to `about`
> - Renamed `_about.scss` as ` _home.scss`
> - Imported `_home.scss` into `main.scss`
> - Renamed `_about-us.scss` as `_about.scss`
> - Delete `_about-us.scss` and remove from `main.scss`

**Comment by kevinreber** [comment]
@akibrhast 

I assumed after renaming `assets/js/about-us.js` to `assets/js/about.js` we may want to rename the `assets/images/about-us` directory to `assets/images/about` to avoid any future confusion between the **about page** and the **about section** on the homepage

<details>
<summary>Screenshot</summary>

image

</details>

**Comment by akibrhast** [comment]
@kevinreber owh owh! That's cool! Thanks! I was just asking , cause I didn't understand it. Thanks for your explanation.

**Review by drubgrubby — APPROVED** [review]
@kevinreber - Really nice work!  This seemed like it was going to be a simple change, but it turned out that there were a lot more moving pieces that I suspected.  Looks to me like you caught them all.  This looks ready to merge to me.

**Pull request merged**
