### PR TITLE
Updated leadership role for Matt Pereira

### LINKED ISSUE #4219: Update Project Profile: Hackforla.org Website
### Overview
For this issue, please update the [Hackforla.org Website Project's](https://www.hackforla.org/projects/website) leadership information so that it is up to date.

### Action Items
- [x] Locate the `website.md` file inside of the `_projects/` collection folder
- [x] Find the `leadership` variable and look for `- name: Matt Pereira`
- [x] Change the `role` variable for Matt Pereira from `Technical Lead` to `Merge Team`

### Resources/Instructions
- https://www.hackforla.org/projects/website
- https://github.com/hackforla/website/blob/gh-pages/_projects/website.md
- https://jekyllrb.com/docs/front-matter/

### PR DESCRIPTION
**Pull request by mjshelton12**
Fixes #4219 

### What changes did you make and why did you make them ?

  - Updated Matt Pereira's role on the HfLA.org Website's Project Page to reflect his new leadership role
  - Changed his role from "Technical Lead" to "Merge Team" in the leadership variable of the website.md file
  - Ensured changes could be viewed on docker including with the inspection tool and didn't create unexpected problems elsewhere.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
<br/>
<em>Find Matt Pereira's card in the middle on left-hand side</em>
4219 Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
<br/>
<em>Find Matt Pereira's card in the middle on left-hand side</em>
4219 After

</details>

### CODE REVIEW

**Comment by nnr-nnr** [comment]
Review ETA: 7 PM 3/22/23
Availability: 3-8 PM 3/22/23

**Review by nnr-nnr — APPROVED** [review]
Nice, clean work @mjshelton12 ! This PR passes the ABC's, addressing all points of the original issue without creating any new/unforeseen problems.

**Comment by arcan9** [comment]
ETA: EOD 03/23/23
Availability: 5-8pm, M-F

**Review by arcan9 — APPROVED** [review]
Good job, @mjshelton12! The PR is in the correct branch, addresses the reason for the change, and linked to the correct issue. When viewed in the browser via docker, the change is reflected. 👍

**Pull request merged**
