### PR TITLE
update pull_request_template with onboard notice

### LINKED ISSUE #7722: Update PR Template with adding a notice of completing onboarding before creating a PR
### Overview
We have observed non-members creating PRs. To solve this, we will add a notice to the top of the PR template notifying developers that they must complete onboarding before creating a PR. 

### Action Items
- [x] Open the file `.github/pull_request_template.md` in your IDE
- [x] Add the following text: 

    ```
    Please note: You must be a member of the HFLA website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started. Delete this message if you joined this team via onboarding.
    <!--  Note: Delete the message above if you joined this team via onboarding  -->

    ```
    above 
    ```
    <!--  Important! Add the number of the issue you worked on  --> 
    Fixes #replace_this_text_with_the_issue_number
    ```
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example: `git push --set-upstream origin test-update-labels-1234`
- [x] Save the URL from the push command response, for later use after testing
- [x] Test the updated PR template by following these steps:
    - [x] Change your default branch to the branch you make the changes on in your repo
             <details>
                <summary>Screenshot of Default Branch Setting</summary>
                
             </details> 
    - [x] Navigate to the `Pull Requests` tab in your repo, and click the `New pull request` button
             <details>
                <summary>Screenshot of Pull Requests Tab and New Pull Requests Button</summary>
                
             </details> 
    - [x] Ensure the head repository is your repo and the compare branch is the one you make the changes on, then click the `Create pull request` button
             <details>
                <summary>Screenshot of Creating Pull Request</summary>
                
             </details> 
    - [x] Verify the appearance of the updated PR template, and compare it with [.github/pull_request_template.md](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md?plain=1)
    - [x] Close the Pull Request creation page
- [x] Complete the Pull Request process by visiting the URL from the push command
- [x] Submit PR
- [ ] After PR is merged, be sure to follow the step above to change your default branch back to `gh-pages`

### Resources/Instructions
- For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md?plain=1
- This issue was initiated by #6058

### PR DESCRIPTION
**Pull request by codyjohnsontx**
Fixes #7722 

### What changes did you make?
  
  - Add message at top of pull_request_template.md indicated in issue:

### Why did you make the changes (we will use this info to test)?
  
  - Non-members have been creating PRs.
  - To solve issue, we add a this notice at the top of the PR template to notifiy developers they must complete onboarding prior to PRs
  

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

- No visual changes to the website

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
- No visual changes to the website

</details>

### CODE REVIEW

**Comment by belunatic** [comment]
ETA: 12/17/24
Available: M-T 10-4PM

**Review by DrAcula27 — APPROVED** [review]
@codyjohnsontx Great job on your `Small Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7722 
- The correct file `.github/pull_request_template.md` was edited
- No extra edits were made
- Appearance of the website is unchanged (Chrome and Firefox)
- A minor nitpick: did you mean to include the issue number after this text?
    - `Add message at top of pull_request_template.md indicated in issue:`

Approved! 👍

**Comment by mchait18** [comment]
Review ETA: end of 12/17/2024
Availability: 10-3 EST M-TH

**Review by mchait18 — APPROVED** [review]
Thank you for working on this issue, @codyjohnsontx  !

You're doing these right:

- The branch you made the change on is correct
- The linked issue (original issue) number is included
- The content required to add is accurate
- The CodeQL Alerts are checked (check box above)
Great job!

Things to review:
- Not all items on the original issue are checked

**Review by belunatic — APPROVED** [review]
@codyjohnsontx great job, a fantastic work

- The branch name is on point
- great job and letting us know what changed
- The links works
- Everything is checked on the original issue

Way to end the year with a bang! lol!

Thanks again for you hardwork.

**Pull request merged**
