### PR TITLE
Removed Diedrich Chavarria

### LINKED ISSUE #5798: Update Project Profile: Lucky Parking (Remove Diedrich Chavarria)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Diedrich Chavarria
    role: Full-Stack Developer
    links:
      slack: 'https://hackforla.slack.com/team/U031VEUS0CW'
      github: 'https://github.com/DCH-CH'
    picture: https://avatars.githubusercontent.com/DCH-CH
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by heejung-hong**
Fixes #5798 

### What changes did you make?
  - Removed Diedrich Chavarria from Lucky Parking.

### Why did you make the changes (we will use this info to test)?
  - To keep Hack for LA website updated with correct information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-27 at 10 01 36 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-27 at 10 01 08 AM

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 11/30/23
Availability: Weekday evenings

**Comment by jphamtv** [comment]
Availability for this week: Monday-Friday 12–2 PM, 8–10 PM (PST) 
My estimated ETA for completing this issue: 10 PM 11/28/23

**Review by pdimaano — DISMISSED** [review]
@heejung-hong Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed and the appropriate information was removed. Well done!

**Comment by jphamtv** [comment]
Hi @heejung-hong, the branch has a conflict that needs to be resolved. Please let me know when you've resolved it, and I'll review the updated pull request. Thanks!

**Comment by heejung-hong** [comment]
Hi @jphamtv, I believe this branch conflict has been resolved.  Can you kindly review?

**Comment by heejung-hong** [comment]
Closed pull request to resolve branch conflict.

**Pull request closed without merging**
