### PR TITLE
Updated expunge assist project profile to include Justin Yeh

### LINKED ISSUE #5762: Update Project Profile: Expunge Assist (Add Justin Yeh)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Justin Yeh
    github-handle: jyehllow
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03PNBDLXL1
      github: https://github.com/jyehllow
    picture: https://avatars.githubusercontent.com/jyehllow
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
      <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
      
    </details>

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by Anahisv23**
Fixes #5762

### What changes did you make?
  - I added Justin Yeh's information to update the expunge assist project profile. I added this information on the expunge-assist.md file in the _projects directory under Samantha information.
  - Added Justin's name, github handle, role, picture, and links to slack and github.

### Why did you make the changes (we will use this info to test)?
  - To update the project profile with the most relevant information about expunge assist.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by irais-valenzuela** [comment]
Review ETA: 2PM 11/3/23
Availability: 12-2 PM Friday & Wednesday 12-4pm

**Review by irais-valenzuela — DISMISSED** [review]
Nice job, Anahis! Everything looks good.

**Review by irais-valenzuela — DISMISSED** [review]
Looks good, Anahis!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @Anahisv23 - Great job! 
- The branches from/ to are good
- You are referencing the original issue 
- You are including info for what and why you made the changes
- You are including appropriate 'before' and 'after' screenshots

Some notes:
- In the description section, please remove the line `...r information`
- I can see that you addressed the merge conflict by adding "Curtis Barber" - thanks for doing this! It appears that you inadvertently added an empty line (Line 50) after the "Curtis Barbar" section- please remove this line.
- Some of the automatic comments and checks were not triggered when you created this PR. This might happen if you have not included the info "Fixes # xxxx" when you first create the PR. Since these automations were not triggered, please manually copy the labels from Issue #5762 over to this PR. 

Once you are able to makes the edits and commit, you can select the chasing-arrows next to my name in the "Reviewers" section to re-request a review.

Thanks for working on this!

**Review by t-will-gillis — APPROVED** [review]
Hi @Anahisv23 - looks great- thanks for fixing!

**Pull request merged**
