### PR TITLE
Updated Civic Tech Index project profile 2728

### LINKED ISSUE #2728: Update Project Profile: Civic Tech Index
### Dependency
[Issue tracking this on Civic Tech Index project board](https://github.com/civictechindex/CTI-website-frontend/issues/1062)

### Overview
As a product manager of Civic Tech Index I want my project's details to be up to date on the HackforLA website

### Project card
[Civic Tech Index Card Link](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)

### Action Items

- [ ] Civic Tech Index Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub hand
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [ ] Github
         - [ ] Wiki
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [ ] technologies
      - [x] partner
      - [ ] tools
      - [x] status

### Resources/Instructions
- File where changes need to be made [Civic Tech Index Card Link](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)
- Related issue link to be followed: [CTI project issue](https://github.com/civictechindex/CTI-website-frontend/issues/1062) 
- Link to the CTI project page on our website: [CTI project](https://www.hackforla.org/projects/civic-tech-index)

### PR DESCRIPTION
**Pull request by Wny-Duong**
Fixes #2728

### What changes did you make and why did you make them ?

  - Updated Current Project Team roster 
    - Removed: Levi Adissi, Iffath Sultana, Maria Studnicka, Shipra Prakash, Emily Marinaro)
    - Added: Sean Sada, Dennis Chatkhan, Briana Bennett, Joyce Kim, Adaeze Nwaezeigwe, Ron Fu, Vance Dubberly, Isaiah Ozadhe
    - Note: Nandana Rao was listed as a new addition, but had been added to the roster 10 months ago.
  - Added to technologies and tools as they were written in the comments under the original issue.
    - Tools: Google docs, Figma, Usability Hub
    - Technologies: AWS
  - Updated links to Github and wiki pages
    - Github: https://github.com/civictechindex/CTI-website-frontend
    - Wiki: https://github.com/civictechindex/CTI-website-frontend/wiki

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image

</details>

### CODE REVIEW

**Comment by harshitasao** [comment]
Availability: 6pm-7pm IST
Review ETA: End of the day 09/05/2022

**Review by harshitasao — APPROVED** [review]
@Wny-Duong Good work! The changes look good to me.

**Comment by Sparky-code** [comment]
Avail: 1hr
ETA: 5/10 EOD

**Review by Sparky-code — APPROVED** [review]
@Wny-Duong Looks great! All the links look right and the tools and technologies you added match the referenced issue.

**Pull request merged**
