### PR TITLE
delete the record-clearance-hero.png

### LINKED ISSUE #1519: Remove record-clearance-hero.png from assets folder
### Overview
The name of Record Clearance Project was changed to Expunge Assist. As a result, we also added new images to the project and the old images are no longer needed.

### Action Items
- [x] Remove record-clearance-hero.png file from assets folder
- [x] Run site locally and make sure nothing is broken
- [x] Reference contributing document (see [here](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)) to work on issue and make pull request

### Resources/Instructions
File to be removed: https://github.com/hackforla/website/blob/gh-pages/assets/images/projects/record-clearance-hero.png
Contributing Doc: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by alexeysergeev-cm**
Fixes [#1519](https://github.com/hackforla/website/issues/1519)

Deleted record-clearance-hero.png from assets folder

### CODE REVIEW

**Review by glenflorendo — APPROVED** [review]
Look good to me!

**Comment by akibrhast** [comment]
@alexeysergeev-cm Please add the number issue number that this PR is related to in your original comment using the following format.

`Fixes <issue-number>` -> `Fixes 99999` [Do not put it in code blocks].

The reason for that is because doing that links the issue and the PR together such that merging the PR will close the issue.


Here is a good PR example: https://github.com/hackforla/website/pull/1701

**Comment by alexeysergeev-cm** [comment]
@akibrhast Hi, I added the issue number. Do I have to go over Action Items and check them myself or is it auto? Thank you.

**Review by akibrhast — APPROVED** [review]
nice work!

**Pull request merged**
