### PR TITLE
Refactor "Issue Trigger" for issue created from "Inactive Members"

### LINKED ISSUE #7075: Post PBB migration: Refactor "Issue Trigger"
### Overview
The new Projects Beta is structured a little differently from Projects (classic). During to our recent migration from Projects (classic) to Projects Beta, we scrubbed our workflows and removed all functionality that referenced 'columns' as this term is no longer used. We need to refactor our post migration workflows so that they have similar functionality as previously.

### Details
Prior to the migration to Projects Beta, [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js) contained logic that un-assigned a member and posted a message if the member assigned themselves to an issue in the "New Issue Approval" column,  and if that issue had neither a `Complexity: Prework` nor `Draft` label. This file's logic needs to be rewritten in terms of the 'status' field instead, using GraphQL. 

### Action Items
UPDATE: PR #6969 addresses the following Action Items:

> - [x] This issue involves GithHub Actions and GraphQL. You will need the new Project Board Beta set up in your repo so that you are able to test and demonstrate your solution. Refer to the "Resources/Instructions" section below to get started, and be sure to let us know if you have questions.
> - [x] In the same section below, see the "Previous (pre-migration) issues" that describe the previous functionality which needs to be emulated as closely as possible in the new projects. Additionally, refer to [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js), lines 54-90 +/-: This section is pre-migration code, and may be used as a rough guide for the functionality we want restored.
> - [x] Using GraphQL, refactor this file to restore the previous functionality as noted above and on the previous issues linked below. 
> - [x] Note that the files 'draft-label-reminder.md' and 'unassign-from-NIA.md' already exist.  

This additional step applies to a special case.
- [x] In the pre-migration `issue-trigger.yml` file (see #7053) , line 13, an issue with the phrase "Hack for LA website bot" in its title was sorted to the "Questions/ In Review" column. For the new Projects Beta, if a newly created issue matches this criteria it should be sorted to the "Questions/ In Review" status, which will need to be done in GraphQL
#### Merge Team
- [x] After this issue has been merged, release the dependency, add the label "Ready for Prioritization", and change the Status to "New Issue Approval" for:
  - [x] #7078 
  - [x] #7079 
### Resources/Instructions
- Initial GraphQL queries and results
- [GitHub GraphQL Explorer](https://docs.github.com/en/enterprise-server@3.12/graphql/overview/explorer)
- [GitHub GraphQL API](https://github.com/octokit/octokit.js?tab=readme-ov-file#graphql-api-queries)
- [Hack for LAs GitHub Actions](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335)
- Previous (pre-migration) issues:
  - 
  - PR #6811 fixes #6555 
  - PR #6502 fixes #4821
- This issue initiated by #6993

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #7075 

### What changes did you make?
  - a.) In `issue-trigger.yml`, added `HACKFORLA_GRAPHQL_TOKEN`
  - b.) In `check-labels.js`, added code lines 37-40 to retrieve issue and status field id values, then change issue's status to "Questions / In Review"
  - c.) In `post-labels-comment.js`, added check at line 38 so that if issue title matches "Hack for LA website bot..." the function returns without adding a comment.
  - d.) Added new `status-field-ids.js` 
  - e.) Added new module `mutate-issue-status.js` (thank you @moazDev1 )
  - f.) Added new module `query-issue-info.js` (same!)
  - g.) Throughout, add explicit semi-colons where missing

### Why did you make the changes (we will use this info to test)?
  - a.) When using a GraphQL mutation, we need a token with "Project" scopes enabled
  - b.) This restores the behavior of the workflow before migration to Projects Beta
  - c.) The comment is not needed since all labels are present
  - d.) This file added b/c these values will be needed for other functions, and since these ids do not change it makes more sense to have a simple lookup for the value than performing a GraphQL query each time we need a value
  - e.) This file mutates / changes the status of an issue given the issues id value
  - f.) This file returns an issue's given its issue number. Note that this is done in GraphQL b/c the typical REST API for looking up issues does not seem to return the correct id value
  - g.) Did this to anticipate and avoid Code QL alerts

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes to website

## Notes for Testing
In order to review this PR you will need to have your repo environment set up for testing. 
- See [Hack for LA's GitHub Actions (revised doc)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335).  This document should be mostly up to date still, but if you run into problems let us know
- To find your own id values to use while testing:
  - Go to [GitHub Explorer](https://docs.github.com/en/graphql/overview/explorer) 
  - In the query field on the left, enter:  

  ```  
  query findStatusSubfieldIds ($login: String!, $projNum: Int!, $fieldName: String!   ) {
    user(login: $login) {
      projectV2(number: $projNum) {
        id
        field(name:$fieldName) { 
          ... on ProjectV2SingleSelectField { 	
          id options{ 
              id
              name
              ... on ProjectV2SingleSelectFieldOption {
                id
              }
            } 
          }
        }
      }
    }
  }
  ```  
  and in the 'Variables' section underneath, replace for your GitHub login and project number:  

  ```  
  {
    "login":"<replace with yours>",
    "projNum": <replace with yours>,
    "fieldName": "Status"
  }
  ```  

  - Next, create a new issue and give it the title "The Hack for LA website bot removed me"
  - A successful test will result in the issue receiving five labels including `Complexity: Small`, `Feature: Administrative`, `ready for dev leads`, `role: dev leads`, and `size: 0.25pt`. Additionally, the issue will be moved to the status of "Questions / In Review"
- [Successful run](https://github.com/t-will-gillis/website/actions/runs/10030838061) of "Issue Trigger"
- [Issue created](https://github.com/t-will-gillis/website/issues/846) Yours will not look exactly like this...

### CODE REVIEW

**Comment by moazDev1** [comment]
Availability: Sat - Mon 6 PM - 10 PM
ETA: 8/1

**Review by moazDev1 — COMMENTED** [review]
Hey @t-will-gillis, thanks for working on this issue and making this clear description of what you have done!

I created a couple of issues and everything worked perfectly for me. Issues including the title "Hack for LA Website Bot" automatically added the required labels, and other issues with missing labels triggered a comment asking to add the missing labels.

I just have a question regarding line 40 in `check-labels.js`:
```javascript
mutateIssueStatus(github, context, itemId, newStatusValue);
```
Dones't this function need `await` before it since it's async? I know it works which's surprising but just want to mentioned that. Otherwise, everything looks perfect for me.

**Comment by t-will-gillis** [comment]
Thanks @moazDev1! I added `await` as you suggested

**Review by moazDev1 — APPROVED** [review]
Thank you @t-will-gillis, everything looks perfect for me.

 Keep going!

**Comment by t-will-gillis** [comment]
Thank you for reviewing this, @moazDev1!

**Pull request merged**
