### PR TITLE
Updated alt text for GreenEarthOS image

### LINKED ISSUE #4000: GreenEarthOS: Update alt text for GreenEarthOS image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `GreenEarthOS` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/green-earth-os.md`:

**From:**
```
GreenEarthOS logo with text in green and a globe as a "O"
```

**To:**
```
GreenEarthOS
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3866 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/green-earth-os

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/green-earth-os.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by karengcecena**
Fixes #4000 

### What changes did you make and why did you make them ?

  - Updated alt text for the GreenEarthOS Image to better adhere to WCAG

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - Changing alt text to the image. No visual changes to the website without using inspect tool.

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Availability: 1 hour
ETA: EOD 3/14/23

**Review by Jaretzbalba — APPROVED** [review]
@karengcecena I see that the alt tag was updated correctly as requested in the issue. Everything looks good locally! Good job working on this issue!

**Comment by perlaroyerc** [comment]
ETA: 2PM 3/15/23
Availability: 11-6 PM M-F

**Review by perlaroyerc — APPROVED** [review]
Amazing job @karengcecena! The issue was linked, the changes look good, and you are merging from and to the correct branches.

**Review by mademarc — COMMENTED** [review]
Hey @karengcecena The alt  logo text part of this code was done updated correctly so good done here.

**Comment by mademarc** [comment]
Review ETA:  3/15/23
Availability: 7PM

**Pull request merged**
