### PR TITLE
Update tools on the lucky parking project profile page

### LINKED ISSUE #5791: Update Project Profile: Lucky Parking (Update Tools)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `tools` variable and change the following:

**From:**
```
  - Jupyter Notebooks
  - Google Colab
```
**To:**
```
  - pnpm
  - GitHub
  - Storybook
  - Google Colab
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by Anahisv23**
Fixes #5791

### What changes did you make?
  - Updated the tools on the lucky-parking.md file to show the following
     - pnpm
     - GitHub
     - Storybook
     - Google Colab
 

### Why did you make the changes (we will use this info to test)?
  - To keep the tools up to date on the lucking parking project page and the lucky parking project card on the 
     projects page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image

</details>

### CODE REVIEW

**Comment by irais-valenzuela** [comment]
Review ETA: 4 PM 11/16/23
Availability: 10:30 AM - 4 PM Thursday & 10:30 AM - 1 PM Friday

**Review by irais-valenzuela — APPROVED** [review]
Hi @Anahisv23!

Branches were set up correctly. Your changes successfully update the tools from the issue on the UI and in the code. You gave a clear description of what your PR does, why changes were made, and provided before and after screenshots.

Great job! @Anahisv23 ✨

**Comment by freaky4wrld** [comment]
ETA: EOD 11/18
Availability: Evenings

**Review by freaky4wrld — APPROVED** [review]
Hey @Anahisv23 , I approve the PR
- the to/from branches are correct
- the linked issue is correct
- changes made in the correct file, and the addition/deletion is correctly done
- the visuals are apt and are as specified in the issue

Great work there......

**Comment by drakenguyen4000** [comment]
Nicely done Anahisv23.  Changes were done correctly and showing up a docker.

**Pull request merged**
