### PR TITLE
 Update labels within pre-work-template---ex.md file

### LINKED ISSUE #4484: Update labels: Issue Template: pre-work-template---ux
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/pre-work-template---ux.md`
- [x] Replace the following line
   ```
   labels: 'Feature: Onboarding/Contributing.md, prework, role: user research, size:1pt'
   ```
   with
   ```
   label: ['Feature: Onboarding/Contributing.md','prework','role: user research','size:1pt','Complexity: Missing']
   ```
- [ ] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL] 

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/pre-work-template---ux.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by arfgit**
Fixes #4484

### What changes did you make and why did you make them ?

  - Replace the following line labels: 'Feature: Onboarding/Contributing.md, prework, role: user research, size:1pt' with label: ['Feature: Onboarding/Contributing.md','prework','role: user research','size:1pt','Complexity: Missing']
  - File was located in .github/ISSUE_TEMPLATE/pre-work-template---ux.md
  - Changes were made to kick off my first good issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by kerimedeiros** [comment]
ETA: EOD today
Availability: M-F 9am-5pm

**Review by kerimedeiros — DISMISSED** [review]
Branch is set up correctly and linked issue is accurate. The code changes are correct. No screenshots required here, as change was to a markdown file only (would recommend deleting the visual links in "Visuals before/after changes are applied" sections in initial PR comment for future issues if visuals are not are not needed). Great job!

**Review by rdhmdhl — DISMISSED** [review]
Great job following instructions! I've reviewed these changes to the pre-work-template---ux.md file and the labels match what was proposed in issue #4484

**Review by roslynwythe — DISMISSED** [review]
Hi @arfgit great work on this PR so far.  The branches are setup correctly and the code change appears to be correct.  However I just learned that we may need to test the new template in a test repo on GitHub.  I'm still trying to understand how to do that.  I will try to work on it today 5/15 and tomorrow 5/16.

**Comment by roslynwythe** [comment]
Hi @arfgit I spoke with Bonnie and Justin about this, and we need to test the PR in a test repository.  I will post the test procedure when it is ready.  Thanks.

**Comment by arfgit** [comment]
Okay gotcha thanks for the update

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @arfgit - great job on your first good issue! You are using the correct branches, you linked the issue, your description is clear, and you followed the issue and made the code changes as requested. 

You did what you were instructed to do- thanks!- but  inadvertently the code we said to use has some typos. Instead would you please replace the code on Line 5 with the following- 

`labels: ['Feature: Onboarding/Contributing.md', 'prework', 'role: user research', 'size: 1pt', 'Complexity: Missing']`

As @roslynwythe indicated, this will need to be tested and we will give you instructions for doing so. One minor observation- when you don't have 'before' and 'after' visuals you can delete the 'Visuals before ...' and 'Visuals after ...' and replace with 'No changes to the website' or similar.

Great job again, apologies for our typo, and thank you for your work

**Comment by arfgit** [comment]
No worries, let me know if things are good now!

**Review by t-will-gillis — APPROVED** [review]
Hey @arfgit - thanks for making the change, looks good! I am able to test it and it appears to work as intended. 

For you to test it also: @roslynwythe posted instructions for testing [here](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931). Feel free to message us on Slack if you run into any issues. Thanks again!

PS when you make changes requested by a reviewer, you can select the circling arrows next to their name to re-request a review: 
Screenshot 2023-05-16 195140

**Comment by roslynwythe** [comment]
Hi @arfgit I tested the PR and it checks out fine on the test repository, so I'm going to merge it.  I apologize for the confusion about testing and I want to thank you for a great job on your "first good issue".

**Pull request merged**
