### PR TITLE
SDG 2: Rename and replace image with correct color one

### LINKED ISSUE #4254: SDG 2: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `zero-hunger.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-02.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg2.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the image you just added by changing
  ```
  <img src="/assets/images/sdg/zero-hunger.svg" alt="2 Zero Hunger" />
  ```
  to
  ```
  <img src="/assets/images/sdg/sdg2.svg" alt="2 Zero Hunger" />
  ```
- [x] Using Docker, check the About page's Sustainability section (https://www.hackforla.org/about/#sustainability) to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by cng008**
Fixes #4254

### What changes did you make and why did you make them ?

  - Replaced the Sustainable Development Goals (SDG) images in the repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf) (after image is slightly lighter in color)
    - Deleted `zero-hunger.svg`
    - Added the svg into the `assets/images/sdg` directory

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
Availability: weekdays
ETA: Will look it over by EOD tomorrow 04/08/2023

**Comment by Jaretzbalba** [comment]
Availability: 1 hour
ETA: EOD 4/8

**Review by Jaretzbalba — APPROVED** [review]
@cng008 I see that the old image was deleted and replaced with the new one in accordance with SDG guidelines. Everything looks good to me! Thank you for working on this issue!

**Review by KazushiR — APPROVED** [review]
@cng008 Hello. Apologies on the late reply. After reviewing the PR, everything looks good!

**Pull request merged**
