### PR TITLE
change media query to desktop-up

### LINKED ISSUE #3437: Refactor CSS for Home Page Footer on Smaller Screens for Redesigned Homepage
### Overview
Currently, when you compress the HfLA home page on a computer screen, the CSS for mobile doesn't activate. We need to update the CSS so that the mobile CSS is activated for the compressed Home Page to ensure the intended formatting.

### Action Items
- [x] Feature Branch: You will be working off a feature branch called feature-homepage-launch. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] Review [_footer.scss](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_footer.scss) and [_footer.html](https://github.com/hackforla/website/blob/feature-homepage-launch/_includes/footer.html) to understand how CSS is applied to the footer
- [x] Change the CSS so that the footer displays like the mobile version on compressed screens
- [x] Confirm everything is working as intended
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into feature-homepage-launch. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article

### Resources/Instructions
- Current redesigned Home page
  <details>
    <summary>Click here to see the current redesigned Home page as it is being compressed from 1024 to smaller sizes in developer tools:</summary>

    redesigned-homepage-footer-compression problem

  </details>

- Desired Home page for smaller screens:
intended home page

Files:
- [_footer.scss](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_footer.scss) 
- [_footer.html](https://github.com/hackforla/website/blob/feature-homepage-launch/_includes/footer.html) 
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Homepage Redesign in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #3437 

### What changes did you make and why did you make them ?

  - Updated scss media query to create a more fluid/responsive transition. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2022-12-27 at 11 46 31 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2022-12-27 at 11 42 17 AM

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 6 - 11 pm 12/27, 10 am - 2 pm 12/28

**Review by roslynwythe — COMMENTED** [review]
Hi @Jaretzbalba, the footer looks really nice and smooth as the screen size changes.  Question: Was the footer supposed to be sticky?  That was not clear to me from the Figma design.  I noticed position: sticky on .main-footer, but I'm not sure if that is necessary and if so, it is not clear what effect that style is having.

**Comment by Jaretzbalba** [comment]
@roslynwythe I saw that as well but left it since I was focusing more on the layout than the positioning of the footer itself. That sticky position is not doing anything from what I can tell.

**Review by roslynwythe — APPROVED** [review]
Great job @Jaretzbalba !  Source and destination branches are correct, and after your change to the media query, the footer now looks good at all screen sizes.  I am somewhat concerned because the CSS on the main-footer class seems to indicate the intention to make the footer sticky, but it does not behave in a "sticky" manner.  However, this same situation exists in feature-homepage-launch and this issue mentioned nothing about the sticky behavior, so I assume the sticky situation will be handled in a separate issue.

**Comment by MattPereira** [comment]
Review ETA: EOD Jan 9, 2023
Availability: 15 hours

**Review by MattPereira — APPROVED** [review]
Solid work @Jaretzbalba ! :+1: 

Nice job finding the specific `@media` query that needed to be changed.

I did notice your issue is currently missing :ballot_box_with_check: for most of the action items. I recommend that you click those checkboxes as you complete each task to help pull request reviewers.

**Comment by MattPereira** [comment]
Hey @roslynwythe if you are interested in pursuing your suggestion to re-examine the `position: sticky` property on the `.main-footer` class you do have the option to create an [Emergent Request](https://github.com/hackforla/website/issues/new?assignees=&labels=size%3A+0.25pt&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)

I tracked down the PR that changed the position to sticky but I don't have time to look into it right now:
- https://github.com/hackforla/website/pull/3183

**Comment by roslynwythe** [comment]
Thank you @mattpereira for finding that PR.  Reading it, I learned that the
use of position: sticky was an intentional choice, not to fulfill a
requirement for a sticky footer, but to solve a challenging CSS positioning
problem.  I'd never seen that usage before.

**Pull request merged**
