### PR TITLE
Refactor Tools data for tech-work-experience.md

### LINKED ISSUE #4913: Refactor Tools data for tech-work-experience.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [tech-work-experience.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Miro, Otter.ai, Zoom, Calendly, LinkedIn, 1password, GitHub Wiki, Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar), Google Data Studio
```
to:
```
tools: 
  - Figma
  - Miro
  - Otter.ai
  - Zoom
  - Calendly
  - LinkedIn
  - 1Password
  - GitHub Wiki
  - Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar)
  - Google Data Studio
```
  - [x] Confirm that the tools data on all project pages is rendered correctly

### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by ziniwang**
Fixes #4913 

### What changes did you make?
  - Refactor the tools data in the `tech-work-experience.md` file from a string to a list

### Why did you make the changes (we will use this info to test)?
  - To include a dropdown for 'Tools' for the filter menu on the 'projects-check' page

### CODE REVIEW

**Comment by yujioshiro** [comment]
Review ETA: 8/2/23 EOD
Availability: 8/2 8pm-10pm

**Comment by wongstephen** [comment]
Availability 8/2
ETA EOD

**Comment by wongstephen** [comment]
Hi @ziniwang,

Issue is linked correctly, the naming convention of the branch is easy to follow, changes to the issue are documented and the code fix looks correct I can confirm that the site works and has the correct information on it when it is run in my local environment. Great work!

**Review by wongstephen — APPROVED** [review]
Great job on your first issue pull request!

**Review by yujioshiro — APPROVED** [review]
Great job @ziniwang! 

The branches are set up correctly, the changes reflect what the issue asks for, and the description is accurate.

While there are no visual changes to the site, because the issue asks that you confirm the tools still renders correctly, I think it would be good to upload images of the list being rendered correctly the next time.

I pulled @ziniwang's branch and confirmed that the list renders correctly both on the projects page as well as the Tech Work Experience page.

**Review by adrianang — APPROVED** [review]
Hi @ziniwang — the branching is set up correctly, the corresponding issue is linked, and the requested change of refactoring the Tools data for Tech Work Experience has been made exactly as requested in the linked issue. In testing your branch in my local environment through Docker, the change you made did not visually (except for title-casing 1Password, which seems to be more accurate anyway) or functionally affect the project in its various views (project pages and cards on mobile, tablet, and desktop).

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
