### PR TITLE
Html refactor 2fa #5709

### LINKED ISSUE #5709: Refactor HTML to resolve linter error: _guidepages/2FA.html - line 29
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 29
- [x] Change the line of code
```
<div class='section-container'>
```
to
```
<div class="section-container">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by coding-yost**
Fixes #5709 

### What changes did you make?
  - Change to line 29 of guide-pages/2fa from single quote to double quotes

### Why did you make the changes (we will use this info to test)?
  - support linter for HTML

### visual change
- No visual change.

### CODE REVIEW

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The PR is linked to the corresponding issue and the requested change has been made. Great work!

**Comment by freaky4wrld** [comment]
ETA: EOD 1/9/24

**Comment by freaky4wrld** [comment]
@coding-yost please provide the after/before screenshots as per the templates. Ping me when you are done and I'll approve it.

**Comment by coding-yost** [comment]
> @coding-yost please provide the after/before screenshots as per the templates. Ping me when you are done and I'll approve it.

The changes made did not contribute to any visual changes on the website so I did not think before/after screen shots were required as they ask to not screenshot code.

**Review by freaky4wrld — APPROVED** [review]
The changes are made accordingly, the to/from branch is great,  everything looks great, @coding-yost thanks for mentioning that `no changes needed`... PR approved

**Pull request merged**
