### PR TITLE
Update food-oasis.md

### PR DESCRIPTION
**Pull request by ExperimentsInHonesty**
There is no issue, making a hotfix

### What changes did you make and why did you make them ?
  - added a link to the pdf for the project under the title overview
  - added a pdf to the directory so that it can be accessed.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
There are not screenshots for this even though there should be.  I need this live now, so doing it in the github directly.  Not viewing it on my own machine.  Someone will need to check to see if I have done it correctly by bringing down the code locally and making the missing screenshot.

<details>
<summary>Visuals before changes are applied</summary>

Food Oasis - Projects page
Food Oasis - Project page

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Food Oasis - Projects page after
Food Oasis - Project page after
Food Oasis - Onesheet pdf

</details>

### CODE REVIEW

**Comment by answebdev** [comment]
Review ETA: 4/4/2021
Availability: 1 hour

**Review by answebdev — APPROVED** [review]
@ExperimentsInHonesty I checked this issue and brought it up on my machine locally. On the "projects/food-oasis" page, I am able to see the Overview card, and when I click on it, I can see the PDF. And the path in the URL for the PDF is "assets/pdfs/Food-Oasis-One-Sheet.pdf".

<details>
  <summary>Click here to see the Overview card on the Food Oasis page</summary>

food

</details>

<details>
  <summary>Click here to see the PDF</summary>

food-oasis-pdf

</details>

From the Home Page, when I click on the Food Oasis link on the card, it takes me to the Food Oasis page, where you can see the Overview card (see above).

<details>
  <summary>Click here to see the Home Page</summary>

home

</details>

**Comment by SAUMILDHANKAR** [comment]
Review ETA: 5 PM Pacific time 4/4/22
Availability: Monday 4-5 PM Pacific Time

**Review by SAUMILDHANKAR — APPROVED** [review]
@ExperimentsInHonesty I can see the changes in my environment. All looks good to me. I will add the images as well. Thank you.

**Comment by ExperimentsInHonesty** [comment]
@answebdev @SAUMILDHANKAR Thanks!

**Pull request merged**
