### PR TITLE
Sdg11 replace img 4225

### LINKED ISSUE #4225: SDG 11: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `sustainable-cities.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-11.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg11.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the SVG you just added by changing
  ```
  <img src="/assets/images/sdg/sustainable-cities.svg" alt="11 Sustainable Cities and Communities" />
  ```
  to
  ```
  <img src="/assets/images/sdg/sdg11.svg" alt="11 Sustainable Cities and Communities" />
  ```
- [x] In `_projects/lucky-parking.md`, update the path to the SVG you just added by changing
```
sdg-image-src: /assets/images/sdg/sustainable-cities.svg
```
to
```
sdg-image-src: /assets/images/sdg/sdg11.svg
```
- [x] Using Docker, check the following pages to check that the SDG image shows up on the same spot as on the live webpages
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 
  - [x] About page's Sustainability section (https://www.hackforla.org/about/#sustainability)
  - [x] Citizen Engagement page: https://www.hackforla.org/citizen-engagement
  - [x] Lucky Parking: https://www.hackforla.org/projects/lucky-parking

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4187 
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md?plain=1)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- Lucky Parking: https://www.hackforla.org/projects/lucky-parking
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by StephenTheDev1001**
Fixes #4225

### What changes did you make and why did you make them ?

  - delete sustainable-cities.svg 
  - add E-WEB-Goal-11.svg from [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) , rename it to sdg11.svg
  - update paths from sustainable-cities.svg to sdg11.svg
  - makes our SDG svgs correct color and compliant with UN SDG guidelines

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Comment by StephenTheDev1001** [comment]
should I squash these two commits into one commit?

**Review by arcan9 — APPROVED** [review]
Great job @StephenTheDev1001! You made the changes in the correct branch, linked the correct issue, and your changes were reflected upon viewing the relevant pages inside Chrome dev tools.

**Comment by arcan9** [comment]
> should I squash these two commits into one commit?

Maybe if you were repeating a process multiple time this could be useful to reduce your commits, but you only have two commits so there's no need in my opinion.

**Comment by nnr-nnr** [comment]
Review ETA: EOD 4/10/23
Availability: M-F 3-8pm PST

**Comment by drakenguyen4000** [comment]
Review ETA: 4/9/23
Availability: M-F 3-8pm PST

**Review by drakenguyen4000 — CHANGES_REQUESTED** [review]
Hi @StephenTheDev1001!, I checked and the correct image file was added and renamed.  The paths were revised correctly.  In Docker, the images displayed in on Edge and Chrome browser.  However, the image is not displaying in FireFox Developer edition. 
- Image missing in FF normal window, pixel 5, iphone 6/7/8/12/13SE/XS Max and Galaxy S20 Utlra.

I would advise checking with JessicaLucindaCheng.  It might be just a styling issue.

FireFox Regular Window
FireFox Regular Iphone XS Max

**Comment by StephenTheDev1001** [comment]
Apr 11th Dev Meeting:

I was told that these changes are fine and it'll be merged soon. I think I was told by @roslynwythe.
I'm not sure how to proceed from here.

**Review by nnr-nnr — APPROVED** [review]
Nice work! All applicable changes have been made with no detectable, unwanted side effects. Everything looks good in Chrome, however, in Safari responsive view for the About page for smaller viewport dimensions, the SDG images have variable sizes (see below). This is the case for the live site as well, though. And, as the original issue notes, this will be fixed with another issue down the line. Good job!

Screenshot 2023-04-12 at 11 00 01 AM

**Review by drakenguyen4000 — APPROVED** [review]
Per @StephenTheDev1001, @roslynwythe said changes are fine.  I'll switch to approval.

**Pull request merged**
