### PR TITLE
552 update project team meetings page

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ruben1s — COMMENTED** [review]
Everything looks fine. There is just one issue. The hack4la logo is covering some of the <p>paragraph</p> text about covid.
Screenshot from 2020-06-24 10-04-53

**Comment by ghost** [comment]
That's interesting, your version of it actually looks completely different from what my local server is showing, it should look like below.
Screen Shot 2020-06-21 at 11 37 01 AM


Screen Shot 2020-06-21 at 11 34 23 AM

**Comment by ghost** [comment]
I'm checking to make sure I actually pushed everything to the remote issue branch

**Comment by ghost** [comment]
@ruben1s I did have commits that I'd forgotten to push up to the remote repo, sorry about that! Hopefully, it is looking the same as the screenshots that I sent over in the previous comment now. I have not updated a pull request with additional code before, so I believe that I did it correctly but let me know if you're not seeing the changes.

**Comment by ruben1s** [comment]
Looks good.

**Comment by ruben1s** [comment]
Screenshot from 2020-06-24 11-31-56
I merged it, but the problem persists.

**Pull request merged**
