### PR TITLE
github-handle Bonnie - #6167

### LINKED ISSUE #6167: Add github-handle for Bonnie Wolfe in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-index.md ` in the IDE
- [x] Replace:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Ayrh1**
Fixes #6167 

### What changes did you make?

Replaced:

 ```
- name: Bonnie Wolfe
 ```

with 

```
 - name: Bonnie Wolfe
  github-handle:  

```
On the file _projects/civic-tech-index.md

### Why did you make the changes (we will use this info to test)?

We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by freaky4wrld** [comment]
@Ayrh1 it seems in your PR description, has no link to the issue you are working on the top of your PR says `Fixes #replace_this_text_with_the_issue_number` you have to make it like this `Fixes #1234` where the number is the issue number you are working on. 

Also provide an apt description, so that the reviewer has the ease to review it!!! Make sure the rest of the template is followed correctly, a great PR description increases the chances of getting the PR merged. Feel free to look through the [CONTRIBUTING GUIDE](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests) 

If this is a draft PR, provide an apt heading saying it's a draft and not to review it!!

**Comment by w1ld-r** [comment]
Availability: March 13-15, 3pm - 7pm CST
Review ETA: 3/13 by 10pm CST

**Review by w1ld-r — CHANGES_REQUESTED** [review]
Hi @Ayrh1 — great work on this issue!

* You linked the issue correctly in your PR description
* Your branch is correct
* Everything looks good across mobile and desktop 

I have a couple of recommendations for your PR description. Can you make the following changes? I adjusted the formatting, pulled some info from the issue ticket and added the "Screenshots of Proposed Changes Of The Website" section back in. It will make it more clear to reviewers and the merge team.

Once you update the description I'll approve. Thanks! 😄 

---

### What changes did you make?

Replaced:
```
- name: Bonnie Wolfe
```
with
```
- name: Bonnie Wolfe
  github-handle: 
```
On the file _projects/civic-tech-index.md

### Why did you make the changes (we will use this info to test)?
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

**Review by w1ld-r — APPROVED** [review]
Nicely done -- Approved! 👍

**Review by freaky4wrld — APPROVED** [review]
@Ayrh1 thanks for taking up the issue, the branches looks good, issue linked is correct too. Changes made are apt the description provided is great too.... Thanks @gaylem for providing great suggestions!!!

PR approved!!

**Pull request merged**
