### PR TITLE
Remove Member Anousha Shadrach From LA TDM Calculator

### LINKED ISSUE #7651: Update Project Profile: LA TDM Calculator Remove Anousha Shadrach
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/tdm-calculator.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x]  Find the `leadership` variable and remove the following:
```
- name: Anousha Shadrach
    github-handle:
    role: UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U045EHW8NDA'
      github: 'https://github.com/Noushie'
    picture: https://avatars.githubusercontent.com/Noushie
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] LA TDM Calculator page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/tdm-calculator
[^3]: initiating ER:  #7305

### PR DESCRIPTION
**Pull request by dvernon5**
Fixes #7651 

### What changes did you make?
  - Removed the name Anousha Shadrach from the _projects/tdm-calculator.md path.

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before_Webpage_Changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After_Webpage_Changes

</details>

### CODE REVIEW

**Comment by mchait18** [comment]
Review ETA: 1 PM 11/26/2024
Availability: 9-3 PM EST Mon-Thurs

**Review by mchait18 — CHANGES_REQUESTED** [review]
Thank you for working on this issue, @dvernon5 !

You're doing these right:
- The branch you made the change on is correct
- The linked issue (original issue) number is included
- The content required to remove is accurate
- The before / after screenshot is helpful to display the change

Changes you need to make:
- Address the questions from HackforLABot in the original issue ( comment your Availability and ETA)
- The items on the original issue should be checked off when items are addressed

- You can re-request me to review your PR once you make the changes. Feel free to reach out if you have any questions.

**Review by codyyjxn — APPROVED** [review]
@dvernon5 great job on taking this gfi. 
### Things that went well
- The branch name is correct 
- The issue is linked 
- The before and after photos are great 

### Some suggestions 
- You need to respond to the HackForLA bot in the issue 
- You need to check the boxes from the original issue as well 
- You can also remove the issue number from the title 


Keep it up !

**Comment by dvernon5** [comment]
@mchait18 @codyyjxn 

Thank you for your feedback. I wanted to inform y'all that I made the following changes that y'all suggested. Thank you for your time.

**Review by mchait18 — APPROVED** [review]

**Review by minkang3 — APPROVED** [review]
Code changes are perfect, you did exactly what the issue specified.
Branch name looks good.
For the "Why did you make the changes?" section, don't just say that the issue specified it, say _why_ did the issue specify it.

Overall looks good to me.

**Comment by dvernon5** [comment]
@minkang3 

Thank you for your feedback. I took your advice and re-edit my answer to the given question "Why did you make the changes?". I hope that is a better response. 

Thank you once again.

**Comment by rachelcorawood** [comment]
Review ETA: 2 PM 11/26/2024
Availability: 9am-3 PM PST Mon-Wed and Friday This week

**Review by rachelcorawood — APPROVED** [review]
@dvernon5 great job successfully removing Anousha Shadrach from the LA TCM Calculator. 

Things that went well
-The branch name is correct
-The issue is linked
-The before and after photos are great
-You responded to the bot
-You removed the issue number from the title

**Comment by dvernon5** [comment]
@rachelcorawood 
Thank you for your time and feedback. I am glad everything looks good.

**Comment by codyjohnsontx** [comment]
Review ETA: 4:30pm 11/26/2024
Availability: 10-6 PM CST Mon-Fri

**Review by codyjohnsontx — APPROVED** [review]
Branch name looks good
The code changes look perfect. 
The issue is linked correctly
CodeQL alerts are good
The content removed is corrrect
Before and After photos look great

Good job on the PR @dvernon5 and thank you for your time

**Comment by dvernon5** [comment]
@codyjohnsontx 

Thank you for your feedback and time. I truly appreciate it, and I am glad everything is looking good.

**Pull request merged**
