### PR TITLE
Add github-handle variable to Zuri Smith #6238

### LINKED ISSUE #6238: Add new variable github-handle to member Zuri Smith in ballot-nav.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/ballot-nav.md` in the IDE
- [x] Replace:
```
- name: Zuri Smith
```
with
```
- name: Zuri Smith
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [x] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md
Project Webpage: https://www.hackforla.org/projects/ballot-nav
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by elisetvy**
Fixes #6238 

### What changes did you make?
  - Added github-handle variable under Zuri Smith
  - Used spaces, not tabs, to indent github-handle
  - Using Docker, confirmed that appearance of project webpage is unchanged

### Why did you make the changes (we will use this info to test)?
  - To hold the GitHub handle for a member of the leadership team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Adding new variable. No visual changes to the website.

### CODE REVIEW

**Review by jphamtv — APPROVED** [review]
Hi @elisetvy, 

- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- Your code change correctly uses spaces instead of tabs to indent

Please check off the Action Items when working on issues to indicate you have completed them.

Thanks for your contribution!

**Review by t-will-gillis — COMMENTED** [review]
Hi @elisetvy As requested by J Pham, please check off the Action items that you have completed on issue #6238

**Comment by elisetvy** [comment]
@jphamtv @t-will-gillis thank you for the feedback! I’ve checked off the Action Items 😊

**Review by t-will-gillis — APPROVED** [review]
Thanks @elisetvy!

**Pull request merged**
