### PR TITLE
Changed margin to 32px on mobile Wins page hero

### LINKED ISSUE #1594: Adjust margin in mobile Wins page header
### Overview
We need to make the margin smaller between the heading and button in the Wins page in mobile, to make the header look less distorted.

### Action Items
- [x] Decrease the margin in the [Wins page](https://www.hackforla.org/wins/) header between the heading ("Let's celebrate together!) and button ("Share your wins") to **32px** (instead of 56px)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

How it looks now (incorrect):

Screen Shot 2021-05-19 at 11 57 12 PM

How it should look (correct):

Screen Shot 2021-05-19 at 11 57 26 PM

### PR DESCRIPTION
**Pull request by ghost**
Fixes #1594 

### What changes did you make and why did you make them ?

  - Updated margin for <h1> elements on the hero to 32px within the Wins page
Screen Shot 2021-07-12 at 4 06 42 PM
Screen Shot 2021-07-12 at 4 07 07 PM

  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by arghmatey — CHANGES_REQUESTED** [review]
@MariannaAskova The original issue was to change the margin for only the mobile view. Can you please revert the code changed back to 56px, and then add in h1 styling to the below-mobile media query on line 64. It should end up looking like this:

```
@media #{$bp-below-mobile} {
    .wins-hero{
        img{
            height: 105px;
        }
        h1 {
            margin-bottom: 32px;
        }
        .wins-btn{
            max-width: 134px;
            max-height: 46px;
            font-size: 12px;
            line-height: 14px;
        }
    }
}

**Comment by ghost** [comment]
Fixes #1594

What changes did you make and why did you make them ?
Updated margin for mobile elements on the hero to 32px within the Wins page
Reversed the original margin back to 56

Screen Shot 2021-07-12 at 7 08 44 PM
Screen Shot 2021-07-12 at 7 09 12 PM

**Comment by averdin2** [comment]
@MariannaAskova For this issue, the Pull Request needs to be directed towards the wins-feature-1 branch. I also believe that you made your initial changes based on the gh-pages branch and not the wins-feature-1 branch. I think you might need to redo your changes based on the wins-feature-1 branch and make a new Pull Request. I will link our wiki article on how to work off of a feature branch: https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch. If you are still confused about what to do, we are having a dedicated pull request review meeting tomorrow, Tuesday, July 13 at 4pm PT. If you can make it to that meeting, we can assist you. Otherwise, we can help you during normal meeting hours or you can reach out in the slack channel.

**Comment by ghost** [comment]
Closed this pull request and created a new one #1936

**Pull request closed without merging**
