### PR TITLE
Standardization of the accordion element

### LINKED ISSUE #1407: Accordion Component Standardization
### Overview
As a part of the Dev team's efforts to standardize components throughout the website, we need to standardize the accordion component. The JavaScript code needs to be standardized, and some changes with how the JavaScript manipulates the accordion styles needs to be changed. There are also some style issues with the accordion component that need to be fixed. On the 2FA page on the website, the accordion component in the FAQ section stretches farther than the card in the tablet view range.

### Action Items
- [x] Take JavaScript code for the accordion out of [getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) and [2FA.html](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/2FA.html), and move the JavaScript code into the [elements](https://github.com/hackforla/website/tree/gh-pages/assets/js/elements) folder. The final result should be js code in the following file `/assets/js/elements/accordion.js`
- [x] Once there is an `assets/js/elements/accordion.js`, you need to include it into the `pages/getting-started.html` and `guide-pages/2FA.html` via the script tag like so. `<script src="/assets/js/elements/accordion.js" type="module"></script>`. You will place it where the previous `<script>` containing the accordion logic was.
- [x] Move any accordion related style classes from [_getting-started-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss) and [2FA.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/guide-pages/2FA.scss) into a new file called _accordion.scss in the elements folder.
- [x] Change the JavaScript code so that it adds a style class called "show" when the accordion is opened, and when closed it removes that class, rather than having the JavaScript code add the styles directly.
- [x] ~~As per comment https://github.com/hackforla/website/issues/1619#issuecomment-897769443, the accordion arrows need to be made pink in all viewport ranges.~~

#### Current uses of accordion on website
https://www.hackforla.org/getting-started
https://www.hackforla.org/guide-pages/2FA
#### Relevant files
https://github.com/hackforla/website/blob/gh-pages/_guide-pages/2FA.html
https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html
https://github.com/hackforla/website/blob/gh-pages/_sass/components/guide-pages/2FA.scss
https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss
[Figma Design 2FA (black border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=695%3A0)

Below are screenshots of the behavior of the FAQ section when it's resized above 958 left-right:
image

image

### PR DESCRIPTION
**Pull request by JackRichman**
Fixes #1407   

### What changes did you make and why did you make them ?

  - moved js code from html files to accordion.js
  - moved css styling for accordion from multiple files to _accordion.scss

### CODE REVIEW

**Comment by JackRichman** [comment]
@hackforla/website-merge converted this pull request to draft. Awaiting resolution from this comment: https://github.com/hackforla/website/issues/1407#issuecomment-907718418

**Comment by macho-catt** [comment]
@JackRichman do you have any more questions, and if not can this be undrafted? Thanks :)

**Review by adam-abundis — CHANGES_REQUESTED** [review]
@JackRichman My apologies for the delay. There seem to be merge conflicts that need to be addressed. You can follow the [Check Upstream before you push](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Check-upstream-before-you-push) instructions. If you need any help, please reach out to me on Slack or come to a dev meeting. Thank you.

Also, can you change `care.yml` back to  `give.yml`? You can find it at `_data/internal/credits/care.yml`

**Review by adam-abundis — APPROVED** [review]

**Review by adam-abundis — APPROVED** [review]
@JackRichman Great job solving the merge conflicts. I have pulled the changes and verified the accordion works on the Getting Started page and the Guide Pages 2FA page correctly. Great job. Thank you for your patience with this pull request.

**Review by macho-catt — APPROVED** [review]
LGTM. Good job!

**Pull request merged**
