### PR TITLE
Edit: changed 'content' to 'content-type'; removed 'type' field

### LINKED ISSUE #2795: Edit content field and remove type field from book.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/book.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/book.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/book.yml#L4
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/book.yml#L11

### PR DESCRIPTION
**Pull request by poorvi4**
Fixes #2795 

### What changes did you make and why did you make them ?
- Changed 'content' property in book.yml to 'content-type'  
- Deleted 'type '  property to reduce redundancy after 1st change
- Goal of changes is to optimize book.yml for readability 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
N/A

### CODE REVIEW

**Comment by harshitasao** [comment]
Review ETA : 15/03/2022
Availability : Flexible

**Comment by tamara-snyder** [comment]
Availability: 2 hours
Review ETA: Tuesday, March 15, 2022

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Hi @poorvi4, really great work on this issue! I have one small request, which is to delete the blank lines of code at the end of the file.

Please re-request a review from me when you're ready. Thank you so much!

**Review by harshitasao — APPROVED** [review]
@poorvi4 Hi! Thanks for working on this issue. Changes looks good to me. Great Job!

**Review by tamara-snyder — APPROVED** [review]
Approving this now since there's no urgent need to delete the empty lines at the end. Everything else looks good!

**Pull request merged**
