### PR TITLE
Refactor image tag (program-areas/volunteer icon/mobile)

### LINKED ISSUE #5136: img Tag Refactor: Program Areas Page - volunteer-with-us-icon.svg (class mobile-img)
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/program-areas.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
      <img
        class=""join-us-footer-img mobile-img""
        src=""/assets/images/join-us/volunteer-with-us-icon.svg""
        alt=""""
      />
```
to
```
      <img
        class=""join-us-footer-img mobile-img""
        src=""/assets/images/join-us/volunteer-with-us-icon.svg""
        alt=""""
      >
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  There also may be multiple img tags with the same source image, but with different classes.  Make sure you only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html
2. Webpage(s): https://www.hackforla.org/program-areas
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by evanhesketh**
Fixes #5136 

### What changes did you make?
  - Removed ending slash in img tag

### Why did you make the changes (we will use this info to test)?
  - Make codebase consistent with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

5136-image-tag-refactor-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
5136-image-tag-refactor-after

</details>

### CODE REVIEW

**Comment by davidwiese** [comment]
Review ETA: 4pm PST 8/4/23
Availability: 2-4pm PST 8/4/23

**Review by davidwiese — APPROVED** [review]
Great job! Followed directions well and did everything properly.

**Comment by kwangric** [comment]
ETA: EOD 8/5
Availability: Most days after 3pm PT

**Review by kwangric — APPROVED** [review]
Branches are set up correctly. The requested changes to the code were made, and everything still looks good on the Program Areas page on Docker. Only comment I have is that if there are no visual changes to the site, you don't have to include any screenshots to your PR and just include a message stating that there were no visual changes.

Great work!

**Pull request merged**
