### PR TITLE
Created YML file for SDG 3

### LINKED ISSUE #4451: Creating a yml file for SDG 3
### Overview
We want to create a yml file for a Sustainable Development Goal (SDG) so that information is not repeated in multiple files.

### Action Items
- [x] In `_data/internal/sdg`, add a file called `sdg3.yml`
- [x] In the file you just created, add the following:
```
# The Sustainable Development Goal (SDG) number (e.g. 16)
sdg: 3
# The SCSS color variable that matches the color of the SDG image 
color-variable: $color-sdg3
# The path to the SDG image
image: /assets/images/sdg/sdg3.svg
# The alt text for the SDG image
image-alt: 3 Good Health And Well-being
targets:
    # The SDG target (e.g. 1, 2, or a, b, ...)
  - target: 4
    # The SDG target statement 
    statement: By 2030, reduce premature mortality from non-communicable diseases through prevention and treatment and promote mental health and well-being
```

### Resources/Instructions
- [_data/internal/sdgs](https://github.com/hackforla/website/tree/gh-pages/_data/internal/sdgs)
- This issue is tracked in epic #4153

### PR DESCRIPTION
**Pull request by se7en-illa**
Fixes #4451 

### What changes did you make and why did you make them ?

  - Created YML file for Sustainable Development Goal 3 (SDG3) so that information is not repeated in multiple files

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Comment by StephenTheDev1001** [comment]
Availability: M-F 10am-12pm
Review ETA: EoD Apr 19th

**Review by StephenTheDev1001 — APPROVED** [review]
You created a new file correctly and followed the naming convention. You also did the pull request on the correct branch and wrote a clear and concise description of the changes you made and why they were necessary. Well done!

**Comment by kwangric** [comment]
ETA: EOD 4/20
Availability: Before 2pm PDT today

**Review by kwangric — APPROVED** [review]
Branches were set up correctly. The file was created in the right location with the correct information and the pull request included a description of the changes made. Great work!

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by creating file sdg3.yml in the correct directory. The code is identical to the code in the linked issue. The code looks clean, only one commit and only one file changed. 
Good job!!

**Pull request merged**
