### PR TITLE
Updated html to resolve linter erro

### LINKED ISSUE #5319: Refactor HTML to resolve linter error: _includes/about-page/about-card-news.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-news.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about last-card'>
```
to
```
<div class="card-primary page-card-lg page-card--about last-card">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-partners.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by freaky4wrld**
Fixes #5319 

### What changes did you make?
  - Updated class='....' to class="..."

### Why did you make the changes (we will use this info to test)?
- To remove linter error

### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
- No visual changes to website

### CODE REVIEW

**Review by ajb176 — APPROVED** [review]
-Merges into correct branch
-Edits code in accordance with linked issue #5319 
-No visual changes to website

Nice work, @freaky4wrld!

Two quick side notes:

1. In your original PR post [here](https://github.com/hackforla/website/pull/5664#issue-1927397392), you didn't state why the changes were made, and the Screenshots section links two invalid image links. For the former, you can write something simple like 'To resolve a linter error', and for the latter, you can remove the two image links and write 'No visual changes to website' (if you've tested and confirmed it). I'd suggest you quickly edit that post to get the hang of it, I'll approve your PR once you do that. 

2. I would suggest avoiding review requests unless you have a reason to want a specific person to review your PR (If they asked you to, or if it's something they're best equipped to handle). The people you request may be busy, and your review could be delayed if others see two reviewers assigned to your issue and skip over it. I'm going to remove the other reviewers, if one of them asked you to request them feel free to add them back.

**Review by ajb176 — CHANGES_REQUESTED** [review]
Edit the original post [here](https://github.com/hackforla/website/pull/5664#issue-1927397392) as mentioned in the comment above. 

1. Add the reason why the changes are made (the title of your PR captures it pretty well). 
2. Remove the broken image links. If there are no visual changes to the website, you can just write that instead of posting images. 

If you have any questions, feel free to ask. Once you make the changes you can tag me and I'll approve the PR. Your code is perfect.

**Comment by freaky4wrld** [comment]
@ajb176 thanks for the helpful suggestions, I'll keep that in mind.......... I've made the necessary changes requested by you, if there's anything else do tag me, glad you laid out every piece of advice to help me understand the process of PR reviewing!!

**Comment by MattChau01** [comment]
Availability: Evening, but may contact via Slack on the weekends throughout the day
ETA: By EOD Saturday

**Comment by nikunjgupta609** [comment]
Please please assign me this issue 🥇

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5319 was properly referenced. ✅ 
- The specified line of code was properly updated per the instructions on the original issue. ✅

**Review by ajb176 — APPROVED** [review]
Next time, don't change the headers when you're creating the PR. 'No visual changes' should be written under the header that already exists in the template, you shouldn't change the header to 'No visual changes'. I made a slight edit to your post to illustrate what it's supposed to look like. 

But nice work.

**Review by adrianang — APPROVED** [review]
Hi @freaky4wrld — good job with this issue! The branching is set up correctly, the corresponding issue is linked, the requested change to double-quotes (instead of single-quotes) in the div tag on line 1 has been made, and the change didn't affect the About page on my Docker environment.

Good job taking @ajb176's advice regarding the documentation in your PR — they provided really good insight that would be useful for future PRs you make! I would say that the Why section could be a _bit_ more descriptive by stating something about the linter error itself requiring the code to be in double-quotes, but I think that's more of something to keep in mind for your next PR.

Thank you for taking up and completing this issue! 🙌🏼

**Pull request merged**
