### PR TITLE
Update Food Oasis Project Profile Details

### LINKED ISSUE #3572: Update Project Profile: Food Oasis
### Overview
As a product manager of Food Oasis I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Food Oasis project's description, leadership, partner, and tools.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the `leadership`, `description`, `partner`, and `tools` variables.
- [x] Replace the existing `description` variable with the following: 
```
Food Oasis is focused on supporting individuals seeking food in Los Angeles. We aim to provide an up-to date resource on food pantries and meal services. The team is currently working on updating listings on our website [foodoasis.net](http://foodoasis.net/), improving UI, and establishing new partnerships.
```
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
    - [x] Name: Stacey Rebekah Scott
         Github Handle: staceyrebekahscott 
         Role: Senior Project Manager
         Slack ID: U02U9Q5DUF6
    - [x] Name: Erin Dean
         Github Handle: itserindean
         Role: Senior Product Manager
         Slack ID: U03JSNJ3UKE
- [x] Update the value of the following team member's `role`s
    - [x] Name: Gigi Patel
          Role: Lead UX Researcher 
    - [x] Name: Seiko Igi
           Role: Senior Product Designer
    - [x] Name: John Darragh 
          Role: Lead Developer 
    - [x] Name: Bryan Wu
          Role: UX/UR Lead
    - [x] Name: Hannah Zulueta
           Role: Lead Developer 
 - [x] partner (remove seeking)
 - [x] Add the following `tools`
     - [x] paper prototyping
     - [x] Google forms
     - [x] Google Sheets
     - [x] Google Analytics
     - [x] FigJam
     - [x] SPSS
     - [x] Mplus
     - [x] AtlasTI
     - [x] Usabilityhub.com surveys
 - [x] Update the following `tools`
     - [x] change `pencil and paper` to `whiteboard / paper & pencil`

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- Food Oasis markdown file: https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Related Issues
- Meeting time update submitted by the Food Oasis team to VRMS: https://github.com/hackforla/VRMS/issues/1216

### PR DESCRIPTION
**Pull request by christinaor**
Fixes #3572

### What changes did you make and why did you make them ?

  - Various updates have been applied to keep the Food Oasis description, leadership, partner, and tools details up to date on the HackforLA website.
  - Updated the description.
  - Added 2 new team members to the "leadership" variable, including their name, role, slack, github, and picture.
  - Updated the "role" variable for 5 team members.
  - Removed "seeking" from the "partner" variable so it is now empty.
  - Added 9 tools to the "tools" variable.
  - Updated "pencil and paper" to "whiteboard / paper & pencil" under the "tools" variable.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image
image

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 2/5 6-11 pm, 2/6 10-noon
ETA: 2/6

**Comment by roslynwythe** [comment]
@christinaor @jdingeman Per the 2nd action item, the new Description text includes: our website "[foodoasis.net]"(http://foodoasis.net/).  I don't believe the text in square brackets was intended to be rendered literally.  It looks like the intention was either to create a hyperlink or to just include the URL text in parenthesis.  Also, note that the project site links in the  "Links" and "Resources" sections (https://foodoasis.la) are not consistent with the new URL listed in the Description section (https://foodoasis.net).  Perhaps PMs: @itserindean @staceyrebekahscott can advise.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Good catch on the description changes.  That got by me.  I should have removed the project's attempt to insert a hyperlink into the project description.  

@christinaor the revised description should be
```
Food Oasis is focused on supporting individuals seeking food in Los Angeles. We aim to provide an up-to date resource on food pantries and meal services. The team is currently working on updating listings on our website foodoasis.net, improving UI, and establishing new partnerships.
```

**Comment by christinaor** [comment]
Thanks for catching that Roslyn and for the revision Bonnie! I will push up the change shortly.

**Comment by christinaor** [comment]
Actually @ExperimentsInHonesty , as Roslyn mentioned previously, should the URL be "foodoasis.net", or should it be changed to "https://foodoasis.la/" to stay consistent with the link in the "Links" and "Resources" sections?

**Comment by itserindean** [comment]
Apologies for the delay responding. We'd like it to be http://foodoasis.net/ everywhere for consistency

**Comment by christinaor** [comment]
@roslynwythe @ExperimentsInHonesty Updated the PR with the new description. I'm not sure if you'd prefer to create a new issue for changing the links in the other sections, but let me know if you'd rather I change them in this issue.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty  should I create a follow-up issue for updating the "Links" and "Resources" sections?

**Review by roslynwythe — APPROVED** [review]
Since this is a time-sensitive issue and all the Action items were executed successfully, and the branches are correct, I am approving this PR and will create a new issue to address the inconsistent URLs.

**Comment by roslynwythe** [comment]
New Issue Update Food Oasis Project URL in Profile Links and Resources #3955 addresses the site URL in the Links section.

**Comment by roslynwythe** [comment]
@christinaor Thank you for your great work on this issue!  The changes were implemented cleanly and the description in the PR was perfectly clear.

**Pull request merged**
