### PR TITLE
Restore old dropdown scss to wins page

### LINKED ISSUE #4557: Fix  of display of filters on WINS page
### Overview
We need to restore the original "drop-down" Role and Team filter menus on the WINS page, which have changed due to recent updates to a shared SCSS file.  The original SCSS classes will be restored with new names and  the HTML will be updated accordingly. 

### Action Items
- [x] Checkout the` gh-pages` branch then run `git reset --hard 70288eaed010f0a996132113c96588e27c7ea2fa` in order to restore the original version of the SCSS file in the working directory tree.  
- [x] Make a copy of `_sass/elements/_dropdown_filters.scss` named `_sass/elements/_old_dropdown_filters.scss`
- [x] Restore the current `gh-pages` using `git pull upstream gh-pages` then create an issue branch
- [x] Add an `@import` statement to `_sass/main.scss` so that the new SCSS file is included in the site's CSS
- [x] In `_sass/elements/_old_dropdown_filters.scss`, prepend "old-" to the beginning of each class.  
- [x] Update the HTML in `_includes/ wins-filter-template.html` to reference class names with the "old-" prefix.
- [x] Using Docker, test the WINS page locally to ensure that its appearance matches the screenshots shown below in the Resources section at mobile and desktop screen widths, and that the filters are functional at mobile and desktop screen widths.  Check the Projects and Home Pages as well to ensure that the appearance and functionality of the Project filters has not changed.  

### Resources/Instructions
<details>
<summary>Original appearance of the WINS page (tablet/desktop screen widths)</summary>

image

</details>
<details>
<summary>Original appearance of the WINS page (mobile screen width)</summary>

image

</details>
<details>
<summary>Current appearance of the WINS page on page load (after PR# 4280) tablet/desktop screen widths</summary>

image

</details>
<details>
<summary>Current appearance of the WINS page on page load (after PR# 4280) mobile screen widths</summary>

image

</details>

- SCSS classes for styling the drop down menus are stored in `_sass/elements/_dropdown_filters.scss` 
- HTML markup for the drop down menus is stored in `_includes/wins-page/wins-filter-template.html`
- WINS page [live](http://hackforla.org/wins) [ | on GitHub code repository](https://hackforla.slack.com/archives/C0271FFEV0E/p1682243133731619)
- [Projects page](https://hackforla.org/projects)
- Changes to the original SCSS classes can be found in #4280

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #4557

### What changes did you make and why did you make them ?

  -Created a copy of old dropdown scss file and imported into main.scss
  -Applied old dropdown scss to wins page only

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-05-08 at 4 12 48 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-05-08 at 4 12 25 PM

</details>

### CODE REVIEW

**Comment by mjshelton12** [comment]
Avail: Monday 8pm-10pm, Tuesday 9am-3pm
ETA: Tuesday end of day

**Comment by mjshelton12** [comment]
This is looking really great! The changes are effective and function well in phone, tablet, and desktop views.

I do have one question though: What is the relevance of the change in _sass/components/_projects-page.scss? It looks like a media query was deleted for the projects page. I didn't see this requested in the original issue but also can't see a difference in docker vs live on the projects page. It felt out of scope for this issue, can you expand on why you made this change if I'm missing it?

**Comment by Jaretzbalba** [comment]
@mjshelton12 Of course! I found that the dropdown buttons on tablet/desktop screens weren't being displayed correctly because that media query is for the newer filter display. Since this issue is restoring the old dropdown filter to the wins page only, this media query was actually messing up the layout. I'm not sure as to why the scss file is called projects-page when it is actually for the wins page. You can see that the scss file for the project page is actually just called project.scss. Hopefully, that clears things up!

**Comment by cng008** [comment]
Availability: weekdays after 2pm
ETA: Wednesday EOD

**Review by cng008 — CHANGES_REQUESTED** [review]
I see that the: 
- PR was done on the correct branch
- issue is linked correctly
- new file is imported in `_sass/main.scss`
- class names have been updated in `_includes/wins-filter-template.html` (though you may want to ask if the id attributes also need to be changed)

Great job reverting the changes on `_sass/elements/_old_dropdown_filters.scss`! 

There is an issue with the drop-downs in desktop view in Safari. Anything above mobile formats appears like the below image. It may have something to do with the media query you removed in `_sass/components/_projects-page.scss` bc when I put it back, I'm at least able to use the filtering. Otherwise, looks good on Firefox and Chrome.
desktop-safari

### Things to note:
<details>
<summary>desktop view</summary>

desktop

</details>

- I did notice that the width of the dropdown is off when it's opened on desktop and mobile. This wasn't a part of the original issue but is something to note. Changing the width to 100% on `line 57` & `line 166` in `_sass/elements/_old_dropdown_filters.scss` fixes this.  

<details>

<summary>mobile view</summary>

mobile

</details>

- The dropdown text in mobile could be smaller to account for word-wrapping going on
- The dropdown card could be made scrollable as it currently extends past the height of the screen

@roslynwythe should these styling issues be fixed in a separate issue?

**Comment by Jaretzbalba** [comment]
@mjshelton12 @cng008 Thank you both for the input! I made some changes to the `_wins-page.scss` file to fix the display of the filter on all browsers now and added back the code I removed from the `_projects-page.scss` file.

**Review by mjshelton12 — APPROVED** [review]
Thank you for your timely and effective replies!

This looks great. To review: Your branches look correct, you linked the issue, you explained what you did and why, and you provided visuals. Your code is clean and effective. I checked the code in chrome for phone, tablet, and desktop as well as safari for desktop and all looked as expected for me.

Thanks again for all your hard work and for being so responsive to our notes!

**Review by cng008 — APPROVED** [review]
I can confirm that the desktop view on Safari is now fixed. Great work in meeting the requirements for the issue. Appreciate all the hard work you put into this. Thank you!

**Comment by roslynwythe** [comment]
Hi @Jaretzbalba @cng008 @mjshelton12 @t-will-gillis thank you all for your great work on this PR.  It would be a good idea for someone to write an ER to address the "desktop view" and "mobile view" issues raised by Christien in her excellent [comment](https://github.com/hackforla/website/pull/4608#pullrequestreview-1421349990) If anyone is interested in writing that ER, please let myself or Justin know.

**Review by t-will-gillis — APPROVED** [review]
Hey @Jaretzbalba – Fantastic job on this issue, and awesome communication with @mjshelton and @cng008. Great work!

Christien has some good observations about styling in comments above. These are outside the scope of this issue but would be good to address these in an ER. Thanks for your work!

**Pull request merged**
