### PR TITLE
Remove entire entry of Noor Grewal from leadership variable

### LINKED ISSUE #5377: Update Project Profile: Civic Tech Jobs (remove Noor Grewal)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] **_REMOVE_** the entirety of the entry:
```
   - name: Noor Grewal
    role: Full Stack Developer
    links:
      slack: https://hackforla.slack.com/team/U045Q8PD1B5
      github: https://github.com/gjagnoor
    picture: https://avatars.githubusercontent.com/gjagnoor 
```
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by liamtirney**
Fixes #5377

### What changes did you make?
  - removed entire entry of Noor Grewal from leadership variable

### Why did you make the changes (we will use this info to test)?
  - to keep Civic Tech Jobs current project team up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/14/23
Availability: 1-3 PM everyday

**Review by one2code — DISMISSED** [review]
Upon testing the changes to `civic-tech-jobs.md` in Docker, I noticed no unintended side effects to the Civic Tech Jobs team roster. All requested changes have been successfully made, and the merge is into the correct branch. Excellent job on resolving this issue and making the required pull request.

**Comment by ortegaa32** [comment]
- Branches set up correctly and correct issue linked.
- Changes accurately reflected in screenshots and don't appear to break the website
- Source code looks clean 

Great work @liamtirney! Approving your pull request

**Review by ortegaa32 — DISMISSED** [review]

**Review by t-will-gillis — DISMISSED** [review]
Hey @liamtirney - Great job on your first pull request! Your branches are correct, you are linked to original issue, you are describing what you did and why, you are providing appropriate before and after screenshots, and your code is clean and only changes what needs to be changed. 

Thanks for working on this issue

**Review by t-will-gillis — APPROVED** [review]
Resolved merge conflict

**Pull request merged**
