### PR TITLE
Added github-handle for Muhi-Dean Othman in 100-automations.md

### LINKED ISSUE #5507: Add new variable github-handle for member Muhi-Dean Othman in 100-automations.md
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Muhi-Dean Othman
```
with
```
- name: Muhi-Dean Othman
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by samuelusc**
Fixes #5507 
### What changes did you make?
  - I replace "- name: Muhi-Dean Othman" with "- name: Muhi-Dean Othman github-handle: " in _projects/100-automations.md 

### Why did you make the changes (we will use this info to test)?
  - Add new variable github-handle for member Muhi-Dean Othman in 100-automations.md #5507

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website
  

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 3/14/24
Availability: Weekday evenings

**Comment by ramitaarora** [comment]
ETA: Mar 13 Eod
Availability: 9am-2pm Weekdays

**Review by pdimaano — APPROVED** [review]
@samuelusc Good job: The branches are correct and the issue is linked. The website still appears and works properly on my system on desktop, mobile and tablet. The correct file was updated with the requested information. Well done!

For future pull requests, if there are no visual changes to the website, you can remove the pre-placed text in the "Screenshots" section and instead write a statement such as "No visual changes to the website."

**Comment by samuelusc** [comment]
Hi @pdimaano  
Thank you for your feedback. I've updated pull request based on your comments.

**Review by ramitaarora — APPROVED** [review]
@samuelusc This looks good! No visual changes to site, github handle variable has been added.

Thank you!

**Pull request merged**
