### PR TITLE
Refactor img tag for sdg13 in about-card-sustainability

### LINKED ISSUE #5174: img Tag Refactor: _includes/about-page/about-card-sustainability.html - sdg13.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sustainability.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/sdg/sdg13.svg" alt="13 Climate Action" />
```
to
```
<img src="/assets/images/sdg/sdg13.svg" alt="13 Climate Action">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by AudreyRose-Wooden**
Fixes #5174 

### What changes did you make?
  - removed closing slash in img HTML tag for sdg13

### Why did you make the changes (we will use this info to test)?
  - refactoring img tags to maintain consistency across the codebase

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No Visual Changes

### CODE REVIEW

**Comment by erinzz** [comment]
Availability: 8/18
ETA: 8/18 12PM

**Comment by erinzz** [comment]
Hey Audrey Rose! 

Great work on completing this issue! You've removed the closing slash properly and per instructed, you've also left all the other img tags untouched. You've also navigated the git workflow well by creating a new feature branch so that your origin branch can receive the changes from remote database. Good work on navigating to the about page as well since there wasn't an obvious link from the main website page. I've ran your code on my local computer, tested the about page, and looks like everything works as it should. You've submitted the pull request and included clear screenshots of the webpage. My only minor addition is to notate "No visual changes" in your submission to let your reviewers know there shouldn't be any changes between your before and after image since the issue is a refactoring of the codebase. Otherwise, everything looks great! 

Erin

**Review by erinzz — APPROVED** [review]
Hey Audrey Rose!

Great work on completing this issue! You've removed the closing slash properly and per instructed, you've also left all the other img tags untouched. You've also navigated the git workflow well by creating a new feature branch so that your origin branch can receive the changes from remote database. Good work on navigating to the about page as well since there wasn't an obvious link from the main website page. I've ran your code on my local computer, tested the about page, and looks like everything works as it should. You've submitted the pull request and included clear screenshots of the webpage. My only minor addition is to notate "No visual changes" in your submission to let your reviewers know there shouldn't be any changes between your before and after image since the issue is a refactoring of the codebase. Otherwise, everything looks great!

Erin

**Comment by ldietz08** [comment]
Availability: Mon-Thu 4pm-7pm
ETA: 08/21 EOD

**Review by ronaldpaek — APPROVED** [review]
Perfect, good job!

**Comment by drakenguyen4000** [comment]
Good job @AudreyRose-Wooden on your first issue.

**Pull request merged**
