### PR TITLE
Update blank issue form with dependency

### LINKED ISSUE #2904: Update blank issue form with dependency
### Dependency
- [x] https://github.com/hackforla/website/issues/2954

### Overview
We want to make the title, description, and format of the Blank Issue form clear that it is for issues with dependencies so that it will be easier and quicker to pick an issue template and write an issue. For this issue, we will update the title and description, and move the dependency section to the top of the form.

### Details
The screenshots below were taken by viewing the form on GitHub. (See the last Action Item for detailed instructions on how to do this.)
<details>
  <summary>Click here to see a screenshot of the current form</summary>
  
  current-form
</details>

<details>
  <summary>Click here to see a screenshot of the desired updated form</summary>
  
  desired form
</details>

### Action Items
In `.github/ISSUE_TEMPLATE/blank-issue-form.yml` on your local computer/IDE, 
- [x] Move
  ```
    - type: dropdown
      id: dependency
      attributes:
        label: Is there a dependency?
        options:
          - "Yes"
          - "No"
      validations:
        required: true
    - type: textarea
      id: dependency-explanation
      attributes:
        label: If Yes, please explain
  ```
  to right below `body:`
  ```
  name: 'Blank Issue '
  description: 'Standard HackforLA issue template '
  
  body:
  ```
- [x] Change
  ```
  name: 'Blank Issue '
  description: 'Standard HackforLA issue template'
  ```
  to
  ```
  name: 'Blank Issue Form with Dependency'
  description: 'Standard HackforLA issue form with dependency'
  ```
- [x] To check the form works correctly
  - [x] Push the changes to your remote forked repo's topic branch on GitHub
  - [x] In your remote forked repo on GitHub, 
    - [x] You are going to temporarily change the default branch from `gh-pages` to your topic branch. (See the link in the Resources/Instructions section for more documentation on how to do this.)
    - [x] Then, check you have issues enabled in your forked repo by
      - [x] Going to the `Settings` tab and then select `General` in the left menu.
      - [x] On the right side of your screen, scroll until you see the `Issues` checkbox under the `Features` section. Make sure the checkbox is checked.
          <details>
            <summary>Click here to see what it looks like when issues are enabled in a repo</summary>
            
           </details>
      - [x] You should now see the Issues tab in your forked repo
    - [x] Now, open an issue within your repo to test out the form you just edited by 
      - [x] Going to the `Issues` tab and clicking the `New issue` button.
      - [x] Then select `Getting Started` button for `Blank Issue Form with Dependency`
      - [x] You should now be able to test out the form and make sure everything functions as expected.
- [x] Once you're done, in your remote forked repo on GitHub, remember to change your default branch back to `gh-pages`.
- [x] Do items in [comment below](https://github.com/hackforla/website/issues/2904#issuecomment-1328329813) to finish the issue
 
### Resources/Instructions
- Blank Issue Form: https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml
- Raw view of .github/ISSUE_TEMPLATE/blank-issue-form.yml: https://raw.githubusercontent.com/hackforla/website/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml
- Blob view of .github/ISSUE_TEMPLATE/blank-issue-form.yml: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml
- [GitHub's documentation on how to change the default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch)

### PR DESCRIPTION
**Pull request by Adastros**
Fixes #2904 

### What changes did you make and why did you make them ?

  - Updated the issue form to remove the dropdown question since the answer to the question is 'yes' by default. The form will only be used for issues with dependencies.
  - Added a description for the Dependency section and a tasklist value in the textarea

These updates were made to help improve the layout and use of the form.

### Screenshots of Proposed Changes Of The Website 

<details>
<summary>Visuals before changes are applied</summary>

Image

</details>

<details>
<summary>Visuals after changes are applied</summary>

Image

</details>

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Availability: 12-2 Weds 1/11
ETA: Weds 1/11

**Review by t-will-gillis — APPROVED** [review]
Hi @Adastros 
This looks good. I tested the form locally and it appears to be functioning as intended. I read your comments to Bonnie about using `label: Dependency` and `description: “Add dependencies (ideally by issue #)”`. Those are a great calls and improve upon what was in the original issue. Very nice.

My only other observation is that I feel that it would be cleaner if this file used either single quotes or double quotes, when quotes are used. I am still new-ish to YAML, and I see that sometimes quotes are necessary (for example, lines 9 and 10 both require quotes) and sometimes they are not (lines 16 and 17 seem to function the same with or without quotes). But since a.) it does not appear to affect the functionality and b.) the other YAML files in this directory are inconsistent as well, it may be better to leave this alone. 
Good job again and thanks!

**Comment by blulady** [comment]
Hey @Adastros,
Awesome job. I concur with Will, we should have some standard but looking at the rest of the .yml files in the directory, it kind of already does. If you go to the other .yml files the names/descriptions/titles mostly seem to have single quotes at the top and double quotes for the rest of the labels/values/descriptions below. Looking into all of that is outside the scope of this issue, @hackforla/website-merge could consider creating an issue to look into it & then a bunch of little issues if we decide to implement the change. What I am dying to know is how you have title above the dependency area because when I switch to @Adastros's branch my issue looks slightly different.


Screenshot (338)


 But that matches HackForLA's website  
Screenshot (339)

So I am going to merge it but please explain!

**Comment by Adastros** [comment]
Those are good points @t-will-gillis and @blulady. We can def make it into issues to help standardize the `.yml` files.

Hi @blulady, could you clarify the difference you saw on your branch? Was the table/title that is circled in the images not appearing at the top of the form?

**Pull request merged**
