### PR TITLE
Update project profile for Guides Team

### LINKED ISSUE #3925: Update Project Profile: Guides Team
### Overview
As a product manager of the Guides Team I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Guides Team project's leadership information.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/guides-team.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
    - [x] Name: Sarah Edwards
GitHub Handle: edwardsarah
Role: Product Manager
Slack Member ID: U03KBU16APN
    - [x] Name: Shawn Wong
GitHub Handle: seannwvong
Role: Product Manager
Slack Member ID: U04MXRWPQ64
    - [x] Name: Prakhar Singh
GitHub Handle: designer2209
Role: UI/UX Designer
Slack Member ID: U038R24FU3S
- [x] Verify the changes by viewing the [Guides Team project page](https://www.hackforla.org/projects/guides-team) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [guides-team.md](https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jlu9d2**
Fixes #3925

### What changes did you make and why did you make them ?

  - Updated the Guides Team project's leadership information to be up to date on the HackforLA website.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-03-03 at 8 34 10 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-03-03 at 8 45 37 PM

</details>

### CODE REVIEW

**Comment by jlu9d2** [comment]
Progress Report

Progress: Waiting on approving review.

Blockers: No blockers.

Availability: Monday through friday

ETA: Sunday, March 05, 2023

**Comment by d-perez-8** [comment]
Availability: 4-6 pm on weekdays
ETA: 1 hour

**Review by d-perez-8 — APPROVED** [review]
Great work on this issue, @jlu9d2! You have completed the issue as directed, the links all work, and the code is consistent with the codebase. Once this pull request is merged, you're ready to work on Medium issues 👍

**Review by Suman2795 — APPROVED** [review]
Good job @jlu9d2 . You made changes as per the action items in the issue into the correct  branch , the code looks clean and correct. The proposed changes work well in the browser.

**Review by plang-psm — APPROVED** [review]
Hi @jlu9d2 , great job implementing the action items for this issue! All changes were correctly made and loaded to the site without issue.

**Pull request merged**
