### PR TITLE
added assets/ to cspell.json

### LINKED ISSUE #5842: Add "assets/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "assets/" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by lukewangm**
Fixes #5842 

### What changes did you make?
  - I added "assets/" to the end of the array "ignorePaths" in cspell.json
  
### Why did you make the changes (we will use this info to test)?
  - I completed issue #5842, which prevents the assets/ path from triggering a cspell error.
  
### Screenshots of Proposed Changes Of The Website
No visual changes to the website.

### CODE REVIEW

**Review by aqandrew — DISMISSED** [review]
This works perfectly!

The [Code Spell Checker's demo in VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) shows squiggly lines under a JS variable called `firstVallue`. I tested by declaring this variable in a JS file in `assets/js/`. No squigglies appear when I have this branch checked out 👍🏽

**Comment by w1ld-r** [comment]
Availability: Weekdays 9AM to 8PM CST
Review ETA: EOD Wednesday March 6th

**Review by w1ld-r — DISMISSED** [review]
Hey @lukewangm,

Good work on this issue! Just a couple of minor tweaks and you should be good to go.

1. Can you add the following section back in to your PR description?

> ### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
> No visual changes to the website.

2. Also, for the "Why did you make the changes" section, it's a good idea to describe briefly the rationale for the changes. In this case, it's to prevent the assets/ path from triggering a cspell error. 

Otherwise, you checked all the right boxes -- issue is linked, your branch is correct, and I am not seeing any cspell errors on files in the assets folder on your branch.

Thanks!

**Review by jphamtv — DISMISSED** [review]
Hey @lukewangm,
- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- Your code change is clean and accurate 

Great work, thanks for working on this issue and for addressing the feedback from @gaylem.

**Review by jphamtv — APPROVED** [review]
Resolved conflict as I just merged some PRs before that caused the conflict. Confirmed the feedback from @gaylem has been addressed. PR approved and ready to be merged.

**Pull request merged**
