### PR TITLE
Removed David Lam from Lucky Parking project team

### LINKED ISSUE #5803: Update Project Profile: Lucky Parking (Remove David Lam)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: David Lam
    role: Data Scientist
    links:
      slack: 'https://hackforla.slack.com/team/U02D8CDURF0'
      github: 'https://github.com/davidlamcanada'
    picture: https://avatars.githubusercontent.com/davidlamcanada
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by jphamtv**
Fixes #5803

### What changes did you make?
  - Removed David Lam's info from _projects/lucky-parking.md 

### Why did you make the changes (we will use this info to test)?
  - To keep the current project team up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-12 at 12 02 41

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-12 at 12 02 49

</details>

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: Evenings
ETA: EoD Wednesday 11/15

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD Tuesday 11/14

**Review by freaky4wrld — APPROVED** [review]
Hey @jphamtv nice work there, all the needed changes are done correctly
- from/to branch is correct
- the reason for change is correct and apt
- the visuals look similar when testing on local environment
- no merging conflicts

Keep up the good work...... feel free to check on the dependencies mentioned in the issue #5803

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5803 was properly referenced. ✅ 
- Per the instructions on the original issue, the specified lines of code were properly removed. ✅ 
- Per the provided screenshots, the visual changes are correct. ✅ 

Hey @jphamtv, Don't forget to mark the issue as completed on #4909 after this pull request is merged! Great work!

**Pull request merged**
