### PR TITLE
Removed Code for America logo and references in partners.yml and spon…

### LINKED ISSUE #5960: Remove Code for America logo and references in partners.yml and sponsors.yml
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove references to the Code for America logo from the Partners and Sponsors markdown, and delete the graphic file.  

### Action Items
- [x] In your local IDE, navigate to `_data/internal/partners.yml`
- [x] Remove these lines:
 ```
- name: Code for America
  image: /assets/images/sponsors/code-for-america.svg
  link: https://www.codeforamerica.org/
  program-area:
    - Vote / Representation
``` 
- [x] In your local IDE, navigate to `_data/internal/sponsors.yml`
- [x] Remove these lines:
 ```
- name: Code for America
  link: https://www.codeforamerica.org/
  img_url: /assets/images/sponsors/code-for-america.svg
  position: 
``` 
- [x] Using Docker, confirm that the Code for America logo no longer appears on the "Partners" section of the "About Us" page

### Resources/Instructions
1. "Partners" section of the "About Us" webpage: https://www.hackforla.org/about/#partners
2. This issue was created from #5953`

### PR DESCRIPTION
**Pull request by heejung-hong**
…sors.yml

Fixes #5960

### What changes did you make?
  - Removed Code for America logo from partners.yml and sponsors.yml.

### Why did you make the changes (we will use this info to test)?
  - To update the website with partner and sponsor information.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-01-23 at 8 22 24 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-01-23 at 8 22 49 PM

</details>

### CODE REVIEW

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EoD 1/24/24

**Review by freaky4wrld — APPROVED** [review]
Hey @heejung-hong thanks for taking up the issue, these are my observations: 
- the to/from branch looks good
- the issue linked is correct as well
- the changes made and the reason to make those changes is correctly specified
- the visual changes are provided as well
- on testing the changes in local environment the `partners-section` has no `instance/image` of the removed organization  

PR approved..... keep up the good work

**Comment by pdimaano** [comment]
ETA: 1/27/24
Availability: Weekday evenings

**Review by pdimaano — APPROVED** [review]
@heejung-hong Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct files were changed and the requested lines of code were removed. Well done!

**Comment by jphamtv** [comment]
Great job on this, @heejung-hong. A small request: could you please remove the extra text at the beginning of the PR comment? It's a minor detail, but it contributes to keeping things organized. Going ahead with the merge since it doesn't affect the site's functionality. Thanks!

**Pull request merged**
