### PR TITLE
Resolve CodeQL alert 16 "Potentially unsafe external link"

### LINKED ISSUE #6050: Resolve CodeQL alert 16 "Potentially unsafe external link"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 16](https://github.com/hackforla/website/security/code-scanning/16) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/16
- [x] #6062
- [x] Replace
```
 <a href="{{ community[1].links[0].url }}" class="btn btn-primary btn-md btn--default cop-btn" target="_blank" title="{{community[1].name}} Slack channel">
```
with
```
 <a href="{{ community[1].links[0].url }}" class="btn btn-primary btn-md btn--default cop-btn" target="_blank" title="{{community[1].name}} Slack channel" rel="noopener noreferrer">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/communities-of-practice
3. This issue i

### PR DESCRIPTION
**Pull request by w1ld-r**
Fixes #6050

### What changes did you make?

Add rel='noopener noreferrer' attribute to all links with target='_blank' on communities-of-practice.html 

### Why did you make the changes (we will use this info to test)?

HTML links that open in a new tab or window allow the target page to access the DOM of the origin page using window.opener unless link type noopener or noreferrer is specified. This is a potential security risk.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visible changes were made to the website.

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 2/6/24

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
@gaylem , Thank you for working on this issue. Merge branches look great. The attribute `rel="noopener noreferrer"` is to be added only to `line 73`. All other changes are beyond the scope of this issue. The linked issue does not specify the file to work on. I would request @roslynwythe to confirm that the file to work on is `pages/communities-of-practice.html`.

**Comment by w1ld-r** [comment]
Thanks for the clarification @Thinking-Panda. I saw pages/community-of-practice.html here, so that's why I thought that was the correct page to edit:  [https://github.com/hackforla/website/security/code-scanning/16](https://github.com/hackforla/website/security/code-scanning/16). But I agree, it would be good to have Roslyn confirm. 

One quick question: if it's insecure for one of the links that opens in `target="_blank"` to not have the `rel="noopener noreferrer"` attribute, would there be a reason we wouldn't want to update all of the instances?

**Comment by LRenDO** [comment]
Hi @gaylem, @Thinking-Panda and @roslynwythe! Popping in to clarify a few things for y'all, so that @roslynwythe doesn’t need to chime in. Dev leads generally have a lot to juggle. 

On the topic of the correct file, @gaylem is correct that the community-of-practice.html is the correct page to edit. It is listed in the resources section of the original issue. 

@thinkingpanda is also correct that only the requested changes in the issue (line 73) should be changed. The rest of the changes need to be reverted back before we can merge the PR. 

@gaylem, you're correct that we would want to change all instances. However, we only do one instance at a time for operational reasons. We need to be able to create large number of good first issues for new developers and changes like these are a good fit for that type of issue. Issues for the rest of the instances in the file likely already exist which is why it’s important to stick to changes in the issue. 

Please feel free to ping me here or on Slack if you need any help or clarification. 

Thanks for taking on the issue and for reviewing it!

**Comment by w1ld-r** [comment]
@LRenDO Amazing, thanks so much for clarifying. @Thinking-Panda and thanks to you as well for your patience. I've reverted the changes, please let me know if you need anything else.

**Comment by LRenDO** [comment]
@gaylem, happy to help and thanks for making the updates! You can re-request a review from @Thinking-Panda by clicking the arrow circle next to the right of their name in the Reviewers section.

**Review by Thinking-Panda — APPROVED** [review]
@gaylem , Nice job on this issue. Merge branches look good. Code changes are as mentioned in the issue. Website works well on the local machine. Approved!

@LRenDO Thank you for clarifying. I just wanted to double check. Thank you!

**Comment by Chrisklangley** [comment]
Availability: M-F 6:30pm
ETA:2/9/24 EOD

**Review by Chrisklangley — APPROVED** [review]
Great work on your Pull request.

The issue is correctly linked in your PR and you have clear and detailed documentation on the changes you made and why you made them.

**Pull request merged**
