### PR TITLE
Updated CONTRIBUTING.md 2.7.f 

### LINKED ISSUE #6185: Update CONTRIBUTING.md Section 2.7.f
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [2.7.f Working on an issue (6): Handling SSH authorization errors](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors), we need to clarify the instructions so new contributors with existing SSH keys know to skip the entire section.

### Details
Hack for LA sees many beginner developers join who may have already created SSH keys on previous beginner projects without necessarily learning what SSH keys are and whether new keys are required for new projects or if existing ones suffice. Thus, instructions should be more explicit that those with SSH keys already connected to their GitHub should skip 2.7.f.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
- [x] Replace
```
#### **2.7.f Working on an issue (6): Handling SSH authorization errors**

**IMPORTANT:** If you are a windows user then you have to install git bash, but if you are a Mac user you only need to use your terminal. Download git bash for windows here
[Git Bash](https://git-scm.com/downloads)
```
with
```
#### **2.7.f Working on an issue (6): Handling SSH authorization errors**

If you already have an SSH key that connects your computer with your GitHub account, you can skip this section (2.7.f).

**IMPORTANT:** If you are a Windows user then you have to install git bash, but if you are a Mac user you only need to use your terminal. Download Git Bash for Windows here:
[Git Bash](https://git-scm.com/downloads)
```

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

### PR DESCRIPTION
**Pull request by andyphancode**
Fixes #6185

### What changes did you make?
  - Added a statement to section 2.7.f of CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
  - Clarify instructions for new members
  - For Reviewers: Do not review changes locally, rather, review changes at [https://github.com/andyphancode/website/blob/update-contributing-6185/CONTRIBUTING.md](https://github.com/andyphancode/website/blob/update-contributing-6185/CONTRIBUTING.md)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by iancooperman** [comment]
Review ETA: End of today

**Review by iancooperman — DISMISSED** [review]
Looks good to me.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
@andyphancode Great job! 
- branches look good
- original issue is linked
- there is a concise description of what changes were made and why
- there are visuals for the changes, (which might not be needed, but no harm in this case!)

Everything looks great, however, I have a couple minor requests:
- Would you please remove the extra ticks in "What changes did you make?" and "Why did you make the changes"
- This is outside of the scope of this issue, but if you agree I feel like `git  bash` should be capitalized for consistency, on the line that begins `IMPORTANT: ...`

Thanks for working on this

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
I will make the call. This was shown incorrectly on the original issue, and is an error that needs to be fixed: 

Please capitalize "Git Bash" in line 738,  or provide an argument why you believe this should not be done.

**Comment by andyphancode** [comment]
> I will make the call. This was shown incorrectly on the original issue, and is an error that needs to be fixed:
> 
> Please capitalize "Git Bash" in line 738, or provide an argument why you believe this should not be done.

No disagreement, just believed it was outside the scope of the issue #. Agreed it should be changed. @t-will-gillis

**Review by t-will-gillis — APPROVED** [review]
Hey @andyphancode Great, thanks so much

**Pull request merged**
