### PR TITLE
fix: resolve CodeQL alert

### LINKED ISSUE #6049: Resolve CodeQL alert 15 "Potentially unsafe external link"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 15](https://github.com/hackforla/website/security/code-scanning/15) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/15
- [x] Open the file `pages/communities-of-practice.html` in your IDE
- [x] Replace
```
<a href="{{ community[1].links[1].url }}" class="btn btn-primary btn-md btn--default cop-btn" target="_blank"
```
with
```
<a href="{{ community[1].links[1].url }}" class="btn btn-primary btn-md btn--default cop-btn" target="_blank" rel="noopener noreferrer"
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/communities-of-practice
3. This issue is part of #5129

### PR DESCRIPTION
**Pull request by anthonypz**
Fixes #6049 

### What changes did you make?
  - Added the `rel="noopener noreferrer` attribute to external links

### Why did you make the changes (we will use this info to test)?
  - To resolve the CodeQL [security alert 15](https://github.com/hackforla/website/security/code-scanning/15)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

No visual changes.

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
No visual changes.

</details>

### CODE REVIEW

**Comment by KuanHsienYEH** [comment]
Review ETA: 13 PM 29/2/24
Availability: 11-13 PM Thu

**Review by KuanHsienYEH — APPROVED** [review]
Great job! I love what you have done, Thanks @anthonypz  !

**Comment by jtw007** [comment]
Review ETA Feb 29 2024
Availability: this afternoon

**Review by jtw007 — APPROVED** [review]
Nice job! 
Branches are correct and issue is linked. 
Correct file and information has been changed.

**Pull request merged**
