### PR TITLE
Removed 'good second issue' from CONTRIBUTING.md Section 2.3.b

### LINKED ISSUE #5591: Remove "good second issue" from CONTRIBUTING.md Section 2.3.b
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove references to "good second issue" from CONTRIBUTING.md in order to avoid confusion, since we are no longer creating issues with the label `Complexity: good second issue'.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` and locate Section 2.3.b
- [x] Remove
```
* `Prioritized Backlog` column in the [filtered Project Board - **complexity: Good second issues** label](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22+label%3A%22complexity%3A+good+second+issue%22)
```
- [x] Do not make any changes outside the single instance above in Section 2.3.b
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review locally, rather review changes at [REPLACE WITH TEST URL]
```
### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

- This issue is part of #4506

### PR DESCRIPTION
**Pull request by segbuniwe**
Fixes #5591 
### What changes did you make?
  - Removed section about "Complexity: Good second issue" from section 2.3.b of CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
  - To avoid confusion since issues with "Complexity: Good second issue" will no longer be made
  
For Reviewers: Do not review locally, rather review changes at https://github.com/segbuniwe/website/blob/remove-second-issue-5591/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Screenshot 2023-10-10 at 5 09 05 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
Screenshot 2023-10-10 at 5 19 54 PM

</details>

### CODE REVIEW

**Comment by mademarc** [comment]
Review ETA: 10/12/2023
Availability: 7:13PM

**Review by mademarc — DISMISSED** [review]
Hey @segbuniwe  well done on the removal of this "good second issue" so the developer can get ger the task done.

**Review by k-rewd — CHANGES_REQUESTED** [review]
Hello! I see that the changes you made are correct! However, I do find it odd that 50 lines of code have been changed with your commit, although it seems like its just the spaces at the end that have been removed. I might have missed something but I did message @blulady just in case. In the meantime, please add the labels attached issue 5591 to the PR.
image
Other than that, I think it's good to go! Appreciate your time and effort and thank you for contributing!

**Review by k-rewd — DISMISSED** [review]
Awesome! Labels have been added nicely. Thank you!

**Review by t-will-gillis — DISMISSED** [review]
Hey @segbuniwe - Great job! Branches are correct, you are linked to the original issue, you are briefly explaining what you changed and why, and you are providing relevant before and after screenshots. Your code edits are clean- as @k-rewd noted, it appears your ide deleted whitespace in several areas which is fine here. Otherwise, thanks for working with @k-rewd to add labels (for future reference: it may be that you created the PR before specifying the "Fixes: #" so the bot did not fill in the labels automatically). 

Thanks for your work!

**Review by t-will-gillis — APPROVED** [review]
<Resolved merge conflict due to changes made by related PRs>

**Pull request merged**
