### PR TITLE
Add github-handle for Melinda Sukosd

### LINKED ISSUE #5880: Add new variable github-handle to member Melinda Sukosd in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
  - name: Melinda Sukosd 
```
with
```
  - name: Melinda Sukosd 
    github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [x] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md 
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by Kle012**
Fixes #5880 

### What changes did you make?
  - Add github-handle under Melinda Sukosd

### Why did you make the changes (we will use this info to test)?
  - Good first issue
  - To reduce redundancy in the project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)
  - No visual changes to the website

### CODE REVIEW

**Comment by Chrisklangley** [comment]
availability: M-F 6:30pm -9pm
ETA 04/19/24

**Comment by A-Wu5** [comment]
Availability: 4/17/24 6-7PM
ETA: End of day

**Comment by A-Wu5** [comment]
Hello @Kle012! Great job on your first issue. The changes requested on #5880 have been done correctly. However, in the "Why did you make the changes" section of this pull request description please describe why this change was necessary in regards to the overall website. For instance, you can put something like "To reduce redundancy in the project file" to make that section more clear.

**Review by A-Wu5 — CHANGES_REQUESTED** [review]
Refer to above comment

**Comment by Thinking-Panda** [comment]
@Chrisklangley - Please review the PR whenever possible.

**Comment by Kle012** [comment]
Hi @A-Wu5, thank you for reviewing. I just updated the "Why did you make the changes" section.

**Review by A-Wu5 — APPROVED** [review]

**Review by jphamtv — APPROVED** [review]
Hi @Kle012,

- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- Your code change correctly uses spaces instead of tabs to indent

Thanks for your contribution to this issue!

**Pull request merged**
