### PR TITLE
Update resource card 4659

### LINKED ISSUE #4659: Update Resource Card logic to test resource names using case-insensitive matching
### Overview
As developers, we need to modify the logic that generates project resource cards, in order to create robust code that will display the project resource icons properly even if the name of the GitHub resource is declared with an incorrect case in a project markdown file. 

### Details
The correct string to specify the GitHub resource in the front matter of a project markdown file is 
`- name: GitHub`  

The Resources section below includes a screenshot depicting the error that occurs when the resource name has incorrect case , for example, as 

`- name: Github`

In this issue the logic will be modified so that the icon and heading in the resource card section of each project page will be displayed in a consistent manner regardless of the case of the liquid `name` variable.  

### Action Items
- [x] Open a sample project markdown file, for example the [website project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) and locate the `links` array and the line `- name: GitHub` which assigns the value `GitHub` to the liquid `name` variable.
- [x] Open the file `_includes/resource-card.html` and read the HTML and liquid tags to understand how the liquid variable `name` is used to select the displayed svg icon and display the `GitHub` heading.   
- [x] Change the code so that regardless of case, if `name` matches `github`, the GitHub icon is displayed and the header text is transformed to `GitHub`.  
- [x] The GitHub resource name may have been corrected in all project files by the time this issue is addressed, so for local testing purposes it may be necessary to edit a project markdown file, entering a value of `name` with incorrect case, in order to confirm that the appearance of the resource section of the corresponding project webpage is correct.  Do not add any project file modifications to the commit.  

### For Reviewers/Merge Team
- [x] The GitHub resource name may have been corrected in all project files by the time this issue is addressed, so for local testing purposes it may be necessary to edit a project markdown file, entering a value of `name` with incorrect case, in order to confirm that the appearance of the resource section of the corresponding project webpage is correct.  

### Resources
<details><summary>GitHub resource card on a project page (incorrect icon)</summary>

image

</details> 
<details><summary>GitHub resource card on a project page (correct icon)</summary>

image

</details>

- [sample project markdown file - for the website project ](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [sample project webpage - for the website project](https://www.hackforla.org/projects/website)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Liquid Conditional Tags](https://shopify.dev/docs/api/liquid/tags/conditional-tags)
- This is the code which reads the `links` array and renders the resource cards: [resource-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/resource-card.html)
- This issue was created as a result of #4660

### PR DESCRIPTION
**Pull request by EdASalazar**
Fixes #4659

### What changes did you make and why did you make them?

  - Line 4: Created 'lowercaseName' and added included.name | downcase. 
  -  Line 9: Changed "Github" to lowercase "github".
  - This will change the liquid version of the name to all lowercase.  This combined with the changes to line 9 will make the logo render consistently. So that the logo will match the name every time. 
  -  Line 22 - 29: Created an if/else statement. If the name entered is 'GitHub' in any casing it will switch to lowercase in Line 4. That will be checked by the if statement. If the lowercase version of the word matches 'github' then 'GitHub' will be rendered. 
 - If the lowercaseName doesn't match 'github' then the name will render as entered.

### Screenshots of Proposed Changes Of The Website  

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-06-05 at 7 35 19 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-06-06 at 11 37 01 AM

</details>

### CODE REVIEW

**Comment by 93Belen** [comment]
Availability: Thursday and Sunday all day
ETA: Thursday by 6pm

**Review by 93Belen — CHANGES_REQUESTED** [review]
Hi! Thank you for providing a detailed description, that makes it much easier for reviewers!
You did the the PR from the correct branch and linked the issue in your description. 

The approach that you are taking seems to be the right one, but it needs just a little tweak. I see that you converted the variable to lowercase to be able to render the proper logo regardless what format they wrote it on each project markdown. The problem is that that variable is being used in line 21 to render the name of the resource, and it's being rendered all in lowercase. Plus is breaking other resource's cards that are working with specific cases.
This is what it should look like with `GitHub`
github before changes
And this after your changes with `github`
github after changes
It's breaking the Getting Started Card
Screenshot 2023-05-31 at 4 45 05 PM


Also, since your Issue is only asking to change the GitHub cards, It's better not to change the Slack one because it might be part of other Issue that someone else might be working on.

**Comment by EdASalazar** [comment]
OK. I'll take a look and figure out another solution. 

I'll have time tomorrow. 

2-6pm

**Comment by roslynwythe** [comment]
Hi @mademarc please leave a comment indicating your Availability and ETA for reviewing this PR.  Thank you

**Comment by mademarc** [comment]
Review ETA: 6/2/2023
Availability: 7:06PM

**Review by mademarc — COMMENTED** [review]
Hey @EdASalazar the line 3 adding of  the html element really helps this web site looks better so good job on this also thanks @roslynwythe  for the heads up as well

**Comment by EdASalazar** [comment]
I'll be working on this tomorrow, Monday 6/4. 
I should have 3 hours to work on it. Which will hopefully be enough.

**Comment by EdASalazar** [comment]
Screen Shot 2023-06-05 at 7 52 33 PM

**Review by 93Belen — CHANGES_REQUESTED** [review]
Hey nice job addressing the problem with the Getting Started card!
Now we just need to fix the other 2 problems:

- [x] The card heading still get rendered in the way that was written in the projects files. In the issue they ask to have it rendered the correct way regardless of how is written in the projects files.
Here is what the Issues says about this:

> In this issue the logic will be modified so that the **icon and heading** in the resource card section of each project page **will be displayed in a consistent manner regardless of the case of the liquid name variable.**

- [x] Since your Issues only ask to fix the GitHub card is better not to touch the Slack one, since that might be part of other Issue.

Thank you for your work!

**Comment by EdASalazar** [comment]
OK, I think I have it all sorted now. Here are some screen grabs with the test code I modified to check my work. I'll update the branch now. 

- Slack is not affected by these changes.
-  'GitHub' should render correctly no matter how it was entered. 


Screen Shot 2023-06-06 at 11 37 01 AM
Screen Shot 2023-06-06 at 11 38 57 AM
Screen Shot 2023-06-06 at 11 38 11 AM
Screen Shot 2023-06-06 at 11 38 22 AM

**Review by 93Belen — CHANGES_REQUESTED** [review]
Good job! Everything looks perfect on my end! 
Just update the second bullet point of your description, since you haven't change "Slack".
I was tempted to approve the PR and tell you to update the description as a comment, just because the code looks perfect, but I'll request the changes just to follow guidelines. Once that is updated it should be good to go. ☺️

**Comment by EdASalazar** [comment]
> Good job! Everything looks perfect on my end! Just update the second bullet point of your description, since you haven't change "Slack". I was tempted to approve the PR and tell you to update the description as a comment, just because the code looks perfect, but I'll request the changes just to follow guidelines. Once that is updated it should be good to go. ☺️

I was eating lunch at Shake Shack and remembered that I forgot to update the pull request halfway through my milkshake. LOL  I'll take care of it now. Thank you.

**Comment by EdASalazar** [comment]
I updated the pull request to match the changes and updated the images. I hope that everything is good to go. Thank you for your help and patience.

**Comment by 93Belen** [comment]
> > Good job! Everything looks perfect on my end! Just update the second bullet point of your description, since you haven't change "Slack". I was tempted to approve the PR and tell you to update the description as a comment, just because the code looks perfect, but I'll request the changes just to follow guidelines. Once that is updated it should be good to go. ☺️
> 
> I was eating lunch at Shake Shack and remembered that I forgot to update the pull request halfway through my milkshake. LOL I'll take care of it now. Thank you.

🤣 I know that feeling

**Review by 93Belen — APPROVED** [review]
Perfect! ☺️

**Comment by 93Belen** [comment]
> I updated the pull request to match the changes and updated the images. I hope that everything is good to go. Thank you for your help and patience.

Don't worry at all, in my first PR I had to change things 3 times and when it finally got approved I deleted my branch so I had to do the PR all over again haha

**Comment by chrismenke45** [comment]
@mademarc Please leave a comment with your updated ETA and availability. Thank you

**Review by blulady — APPROVED** [review]
Looks good!! Comes from the correct branch to gh-pages, the linked issue is addressed and only one file is changed. The changes look good, the code looks clean and functions as intended.

**Pull request merged**
