### PR TITLE
Add GitHub handle Ryan Mayott

### LINKED ISSUE #6732: Add github-handle for Ryan Mayott in engage.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/engage.md` in the IDE
- [x] Replace:
```
- name: Ryan Mayott
```
with
```
- name: Ryan Mayott
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/engage

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by santiseccovidal**
Fixes #6732

### What changes did you make?
  - Under "- name: Ryan Mayott" I added "github-handle:"

### Why did you make the changes (we will use this info to test)?
  - To create a single variable <code>github-handle</code> to hold the github handle for Ryan Mayott

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by urvishp13** [comment]
Review ETA: EOD
Availability: 1pm - 4pm 5/14/24

**Comment by urvishp13** [comment]
**Blocker:** it seems like there is a merge happening in the commit history from the `gh-pages` branch. This stood out to me as odd. Is it okay to have this?

**Comment by tony1ee** [comment]
Hi @urvishp13, the merge from `gh-pages` seemed to be the result of **incorporating changes from upstream**, there's no additional file changes from that merge as seen in https://github.com/hackforla/website/pull/6852/files

The merge commit should not be an issue for approval. 

The merge team likely will squash merge this PR so that merge commit won't show up in `gh-pages` branch commit history.

Hope this helps.

**Comment by urvishp13** [comment]
Okay thanks @tony1ee

**Review by urvishp13 — APPROVED** [review]
Hey @santisecco! Great job completing this issue!

- pull request done on the correct branch
- correctly linked issue
- good job making sure to use spaces instead of tabs in the source code
- no visual changes done to the website in desktop, tablet, and mobile views (Firefox, Chrome)

**Comment by DrAcula27** [comment]
Review ETA: 15 May 2024
Availability: weekdays, 2pm – 8pm Pacific Time

**Review by DrAcula27 — APPROVED** [review]
@santisecco Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - https://github.com/hackforla/website/issues/6732
- The correct file `_projects/engage.md` was edited
- No extra edits were made
- Spaces were used instead of tabs for indenting
- Appearance of the website is unchanged (Chrome and Firefox)

**Pull request merged**
