### PR TITLE
changed alt for _projects/writeforall.md

### PR DESCRIPTION
**Pull request by sarthkdobriyal**
Fixes #replace_this_text_with_the_issue_number

### What changes did you make and why did you make them ?

  -
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by bootcamp-brian** [comment]
Review ETA: 12pm
Availability: Today until 6pm

**Review by bootcamp-brian — CHANGES_REQUESTED** [review]
@high-prog It looks like this is your first pull request and it seems that you missed a few steps when submitting it. Please take another look at the CONTRIBUTING.md and follow the steps under "Part 3: Pull Requests" [here](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31-how-to-make-a-pull-request). If you have any questions feel free to reach out.

**Comment by KazushiR** [comment]
Review ETA: 6 PM
Availability: End of day

**Comment by KazushiR** [comment]
@high-prog Hello. Before proceeding, it looks like that you are missing the issue number as well as the types of changes that you made to the original issue. Please ensure that the changes are correctly reflected. I also cannot view any images to the changes you made. Please ensure that the changes are correctly reflected in the images before this PR can be approved.

**Comment by jdingeman** [comment]
Hello, @high-prog, we appreciate you making the proposed changes, however it looks like you are not a member of HackforLA, so we cannot merge your pull request. If you'd like to join the organization then we encourage you to sign up for onboarding. You can review the [Getting Started](https://www.hackforla.org/getting-started) page for more information.

**Pull request closed without merging**
