### PR TITLE
Added Kevin Yu's Profile  to Civic Tech Jobs File

### LINKED ISSUE #7556: Update Project Profile: Civic Tech Jobs Add Kevin Yu
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Kevin Yu
    github-handle: kevin31yu
    role: Developer
    links:
      slack: https://hackforla.slack.com/team/U061GQQ56Q4
      github: https://github.com/kevin31yu
    picture: https://avatars.githubusercontent.com/kevin31yu
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs
[^3]: initiating ER:  #7521

### PR DESCRIPTION
**Pull request by srinipandiyan**
Fixes #7556

### What changes did you make?
  
  - Added a profile card with Kevin Yu's data to the Civic Tech Jobs section of the Projects page.
  -  Updated `civic-tech-jobs.md` file to include Kevin Yu's contact info.

### Why did you make the changes (we will use this info to test)?
  
  - To update the frontend interface for end-clients to reflect the latest profile data within the Civic Tech Jobs section.
### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

Before Screenshot without Kevin Yu's profile info

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After Screenshot with Kevin Yu's profile info

</details>

### CODE REVIEW

**Review by pluto-bell — CHANGES_REQUESTED** [review]
Hi @srinipandiyan thanks for taking this issue on (: I just have a couple of requests so we can move forward with your PR.

1. Please rename your branch to something that is specific to the issue you are handling—it is also generally advised to add the issue number. For example: `add-profile-to-civic-tech-7556`
2. Please re-write the reason for making these changes. While I understand you are taking this issue on as a way to 'go through the steps,' that doesn't clarify what the actual fix is handling. In this case, it appears you are creating a new profile card for Kevin Yu on the Civic Tech Job project so that the website information is up to date. 
3. Please add related label tags to your PR, this can be found on the right hand side. Some examples for this PR are: `good first issue`, `role: front end`, `size: 0.25 pt`. These labels help people filter pull requests and also help them know as to whether or not they currently have permission to review your PR.

**Comment by 8alpreet** [comment]
ETA: EOD Oct 16
Availability: 3pm-7pm, Mon-Fri

**Comment by codyyjxn** [comment]
ETA: EOD 
Availability: M > F

**Review by codyyjxn — CHANGES_REQUESTED** [review]
hey @srinipandiyan 
### Things that need to be changed: 
- The branch name needs to be related to the issue fixed. 
- Also the title of this pr needs to be a bit more descriptive. 
- You also need to add some labels to show what kind of issue this is and also so others know if this is frontend or backend related. The issue labels should match with the original issue. 

### Things that went well : 
- You did make the right changes to the files `_projects/civic-tech-jobs.md`
- You provided visuals changes. 

Keep it up ! if you have any questions feel free to leave any messages.

**Comment by srinipandiyan** [comment]
I've made the required changes to the PR. Thank you for your guidance. @pluto-bell @8alpreet @codyyjxn

**Comment by srinipandiyan** [comment]
Closed current PR and opened new PR here: https://github.com/hackforla/website/pull/7598

**Pull request closed without merging**
