### PR TITLE
Include project links in project page

### LINKED ISSUE #2296: Ensure that all project links are included in the project page
### Overview
We need to make sure the same links are available on both the project card and project page to 

<details>
  <summary>Current project card (100 automation) - 4 links</summary>
  <h3>An example that highlighs links within project card</h3>
  project card example
</details>

<details>
  <summary>Current project page (100 Automation) - 1 link</summary>
  <h3>Notice one link is available in the page instead of 4</h3>
  project page example
</details>

### Action Items

- [x] Review [line 32-55 of _layouts/project.html](https://github.com/hackforla/website/blob/6b3d76fffa1476f2d17a39440da3ada82d4a4c21/_layouts/project.html#L32-L55)
- [x] Refactor the code so that a list of links similar to the project card (comma separated) show up on the project page
- [x] Verify the project card and project page provide a similar list of links (comma separated)
- [x] Create a pull request for final review

### Resources/Instructions
- Projects Page: https://www.hackforla.org/projects/
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/6b3d76fffa1476f2d17a39440da3ada82d4a4c21/_layouts/project.html#L32-L55

#### Backround information about the Jekyll framework (optional reading)
[Liquid docs - iteration (for loops)](https://shopify.github.io/liquid/tags/iteration/)
[Liquid docs - control flow (if/elseif/else)](https://shopify.github.io/liquid/tags/control-flow/)

### PR DESCRIPTION
**Pull request by lopezpedres**
Fixes #2296

### What changes did you make and why did you make them ?

  - Refactor code to include project links on the project page
  - Those links are comma-separated

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by JimGeist — CHANGES_REQUESTED** [review]
Hi Miguel, Please make the following indentation changes:
Line 44: add one more indent to the right. {% if item.name == 'GitHub' or item.name == 'Slack' or item... should not have the same left alignment as line 43 {% for item in page.links %}
Line 46, 50: Please add the spaces before and after item.name so we have {{ item.name }} 
Line 53: Decrease the indent for {% endif %} .
The requested changes are to clear up if/endif heirarchy. The spaces around the variable name in the {{  }} will not affect the rendering of the page - it just increases the code readability for us.
Other than the above, great job!!

**Comment by lopezpedres** [comment]
Hey @JimGeist ! Thank you so much for your feedback! I made the changes that you requested. Please let me know if there is something else missing. Cheers!

**Review by JimGeist — APPROVED** [review]
Hi Miguel, Awesome job on this one. You made a great choice in issues because this one touches every project page on the site! Everything looks great and it is good to go, - Jim

**Review by macho-catt — APPROVED** [review]
LGTM.Good job!

**Pull request merged**
