### PR TITLE
add github handle for Jed Stewart

### LINKED ISSUE #7176: Add github-handle for Jed Stewart in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Jed Stewart
```
with
```
- name: Jed Stewart
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jazxbx**
Fixes #7176 

### What changes did you make?
Added "github-handle:" under Jed Stewart's name in home-unite-us.md 

### Why did you make the changes (we will use this info to test)?
This variable will eventually replace github and picture variables to reduce redundancy in the project file.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
No visual changes to the website"

### CODE REVIEW

**Comment by bexux** [comment]
ETA: this evening, 7-9PM pacific

**Comment by codyyjxn** [comment]
Review ETA: 6 PM Today
Availability: 5am-8pm M > F

**Review by codyyjxn — APPROVED** [review]
@jazxbx Nice job on the title and the branch name.

**Review by bexux — APPROVED** [review]
Looks good! Followed instructions, file is correct, nicely done.

**Review by jphamtv — COMMENTED** [review]
Hi @jazxbx - Great work on this pull request!

- You created the pull request using the correct branch
- The issue is properly linked to the pull request
- Your summary of changes is clear and concise
- Your code change correctly uses spaces instead of tabs

Thanks for your contribution to resolving this issue!

**Pull request merged**
