### PR TITLE
Fixed Typo

### LINKED ISSUE #2942: Fix typo on citizen-engagement-card.html file from "throughout out" to "throughout"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [ ] For the file `pages/citizen-engagement-card.html`, on line 45, change the typo from "throughout out" to "throughout", so

  ```
  throughout out our communities.
  ```
  becomes
  ```
  throughout our communities.
  ```
- [ ] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/citizen-engagement
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html
Line of code:
https://github.com/hackforla/website/blob/6c99fa3042ac616ae9e7ab456c157b842be441fb/pages/citizen-engagement.html#L45

### PR DESCRIPTION
**Pull request by scarter31191**
Fixes #2942

### What changes did you make and why did you make them?

  - Cleaned up a typo so that our reputation for quality is maintained.
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-03-25 at 9 50 02 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-03-25 at 9 59 13 PM

</details>

### CODE REVIEW

**Comment by harshitasao** [comment]
Review ETA: 26/03/2022
Availability: Flexible

**Review by harshitasao — APPROVED** [review]
@scarter31191 , great job. Changes look good to me.

**Review by tamara-snyder — APPROVED** [review]
Hi Steve, well done on completing this issue. The typo is fixed and it shows up on the site when I run it locally.

Please bear in mind for the future that you should progress through issues in order of good first issue, good second issue, small, medium, and large. This is so that you can gain more experience during your time as a volunteer and so that we can save smaller issues like this for new members who are getting their development environments set up. You can read more about the guidelines for issue progression in section 2.1 of [How to Contribute](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations).

**Comment by scarter31191** [comment]
Hey Tamara,

My Apologies, I was on vacation after my first week of joining so I was trying to get back into the groove of things. But I understand what you're saying, thanks for the heads up.

**Comment by tamara-snyder** [comment]
@scarter31191 No worries! The good second issue will be very similar in scope to the good first, so you're in a good place. Also, we are always here for you if you ever need help as you progress into the larger issues.

**Pull request merged**
