### PR TITLE
Add github-handle for Tyler Thome in home-unite-us.md 

### LINKED ISSUE #7175: Add github-handle for Tyler Thome in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Tyler Thome
```
with
```
- name: Tyler Thome
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by ihop-56**
Fixes #7175 

### What changes did you make?
- Added the `github-handle:` field under `name: Tyler Thome` in the `_projects/home-unite-us.md` file. This field was added without a value as per the issue's instructions.

### Why did you make the changes?
- The change was made to prepare the project file for future enhancements, reducing redundancy by standardizing the GitHub handle field.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by iancooperman** [comment]
Review ETA: EoD

**Review by iancooperman — CHANGES_REQUESTED** [review]
This largely looks good, but please add the issue number "7175" to the name of your branch in your fork.

**Comment by 8alpreet** [comment]
- [ ] Step 0: Is the pull request done with the correct branch?
- [ ] Step 1: Is there a linked issue?
- [ ] Step 2: Understand the linked issue.
- [ ] Step 3: View the changes in the browser.
- [ ] Step 4: Take a look at files changed tab.
- [ ] Step 5: Check for anything else.
- [ ] Step 6: Approve the pull request.
- [ ] Step 7: Clean up your working repo.

**Comment by 8alpreet** [comment]
Review ETA: EOD
Availability: Mon to Fri; 3 p.m. to 7 p.m.

- [x] Step 0: Is the pull request done with the correct branch?
- [x] Step 1: Is there a linked issue?
- [x] Step 2: Understand the linked issue.
- [x] Step 3: View the changes in the browser.
- [x] Step 4: Take a look at files changed tab.
- [ ] Step 5: Check for anything else.
- [ ] Step 6: Approve the pull request.
- [ ] Step 7: Clean up your working repo.

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @ihop-56,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- Only relevant lines of code were changed.

### Changes needed:
1. The issue number must be a part of the branch name. It works well as a suffix (in my opinion).
2. The "what changes did you make" section:
    - It has repeated sentences. 
    - It mentions visual changes which has a section of it's own thus does not need to be discussed in this section.
    - It does not provide insight into the changes, rather it points the reader to the issue. Which is not an invalid approach; however, It would be helpful to reiterate the intention of the linked issue in your own words.

**Review by minkang3 — CHANGES_REQUESTED** [review]
File changes look good.

There is a slight formatting error in your PR where your second bullet point is not spaced properly. Add a space after "-" and it should be fixed.

**Comment by codyyjxn** [comment]
Review ETA: 9am - 8pm 8/22/2024
Availability: 5am - 8PM Monday-Friday

**Comment by codyyjxn** [comment]
Hi @ihop-56  

### Things you did correctly:

1. Branch is set up correctly.
2. PR is linked to the correct issue number.
3. Correct file change 

### Things you should change: 

1. In the "What changes did you make?" section, try to keep it concise and avoid repetition.
2. Including the issue number in the branch name is a good practice. It helps others quickly identify the context, especially when viewing the branch for the first time.

**Review by codyyjxn — CHANGES_REQUESTED** [review]
Hi @ihop-56

### Things you did correctly:

1. Branch is set up correctly.
2. PR is linked to the correct issue number.
3. Correct file change

### Things you should change:

1. In the "What changes did you make?" section, try to keep it concise and avoid repetition.
2. Including the issue number in the branch name is a good practice. It helps others quickly identify the context, especially when viewing the branch for the first time.

**Comment by ihop-56** [comment]
Hi @codyyjxn 

I've made the requested changes:

Updated the branch name to include the correct issue number #7175.
Revised the PR description to remove redundancy and clarify the changes made.
Let me know if there's anything else needed.

**Comment by codyyjxn** [comment]
Hi @ihop-56,
I apologize for any confusion earlier. What I meant to convey is that the issue number should be included in the branch name : `ihop-56:add-tyler-thome-github-handle`.

The title was fine before. No need to add the issue number on the title.

**Comment by ihop-56** [comment]
Hi @codyyjxn 

I've updated the branch name to `add-tyler-thome-github-handle-7175` as requested.

Please let me know if there's anything else needed.

Thank you!

**Comment by 8alpreet** [comment]
Hi @ihop-56, I looked it up and it's not possible to rename a branch when a PR is open. Technically, branches are not renamed on Github, they are deleted and replaced. I went onto your account and saw that you have created a new branch containing the issue number but it is not linked to this PR. You will have to open a new PR.

Useful instructions for updating branch name: [LINK](https://stackoverflow.com/questions/30590083/git-how-to-rename-a-branch-both-local-and-remote)

**Comment by bexux** [comment]
Hi @ihop-5 -6  Thank you for updating the branch name.  Since you have created a new PR from that  new branch, you may want to close this one to avoid confusion. I will link the new one here for reference. https://github.com/hackforla/website/pull/7346

**Pull request closed without merging**
