### PR TITLE
Update profile food oasis 3232

### LINKED ISSUE #3232: Update Project Profile: Food Oasis
### Overview
We'd like to update our current team members on this page: https://www.hackforla.org/projects/food-oasis

### Action Items
- [x] Please remove the people currently listed under Current Project Team on https://www.hackforla.org/projects/food-oasis
- [x] In [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1), please update the leadership with the following people:  

Name: John
GitHub handle: @entrotech
Role: Architect and Technology Lead
Slack ID: UFLDX9V19

Name: Bryan Wu
GitHub handle: @fancyham
Role: Design Lead
Slack ID: U01PG6RD0T1

Name: Jieun Ryu
GitHub handle: @ryu-jieun
Role: UX Researcher 
Slack ID: U02LL2DF4HL

Name: Gigi Patel
GitHub handle: @LIlinit
Role: UX Researcher
Slack ID: U02KZ8WSHHV

Name: Virginia Wu
GitHub handle: VirginiaWu11
Role: Full Stack Engineer
Slack ID: U02G7SBKSV7

Name: Seiko Igi
GitHub handle: @sei1122
Role: Product Designer
Slack ID: U02U55MQEQ7

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID: U9SCMTNK0

### Resources/Instructions
- [Food Oasis webpage](https://www.hackforla.org/projects/food-oasis)
- [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1)

### PR DESCRIPTION
**Pull request by lilyarj**
Fixes #3232 

### What changes did you make and why did you make them ?

  - I updated the food oasis profile
  - Deleted the leadership people and changed their names and position to :
  
 Name: John
GitHub handle: @entrotech
Role: Architect and Technology Lead
Slack ID: UFLDX9V19

Name: Bryan Wu
GitHub handle: @fancyham
Role: Design Lead
Slack ID: U01PG6RD0T1

Name: Jieun Ryu
GitHub handle: @ryu-jieun
Role: UX Researcher
Slack ID: U02LL2DF4HL

Name: Gigi Patel
GitHub handle: @LIlinit
Role: UX Researcher
Slack ID: U02KZ8WSHHV

Name: Virginia Wu
GitHub handle: VirginiaWu11
Role: Full Stack Engineer
Slack ID: U02G7SBKSV7

Name: Seiko Igi
GitHub handle: @sei1122
Role: Product Designer
Slack ID: U02U55MQEQ7

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID: U9SCMTNK0 ( I actually used a different slack id, one that I got off slack for Hannah Zulueta because this one did not connect to an account) - This was the one I used (U01G7AH18J3)

- I made these changes so the Food Oasis could have an updated profile with the people who are currently on the leadership team and all of their roles were described accurately.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-06-26 at 10 51 39 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-06-26 at 10 50 44 AM

</details>

### CODE REVIEW

**Comment by lilyarj** [comment]
For some reason it is saying I submitted two commits, when I only submitted the second one. How do I change this?

**Comment by Sparky-code** [comment]
Hi @lilyarj Thank you for making note of the issues you encountered while working through this issue. I am checking in with @raswani2023 as it looks like she is the one responsible for the other commit. I will probably have you rebase this PR (and will write out some directions for that) but would like you to hold on for a bit while I figure out what happened on their side. Thanks for your patience.

**Comment by lilyarj** [comment]
Okay cool thank you so much. Also idk if this is useful information but I did review Riya's PR request right before I started working on this issue.

**Comment by Sparky-code** [comment]
Hey @lilyarj after checking on the issue it looks like you were a reviewer on the issue that the extra file/commit is connected to. 
I believe this ended up as part of your commit here as a result of that. 

Please make sure that when you are adding files to commit that you do so explicitly. Using `git status` will help you see which files will be added when you use `git add` (it is always better to add files individually especially when you are only making changes to a single file). I would also say to make sure that you are pulling the most up to date commits from the website repository before committing your changes. 

For this issue I'm going to ask you to follow [this guide](https://github.com/hackforla/website/wiki/Remove-files-from-your-Pull-Request) to remove the extra file. Let me know if you have any issues.

**Review by Sparky-code — CHANGES_REQUESTED** [review]
Please follow the linked guide to remove the credits/code.yml file as this deals with another issue. Please rerequest a review once this is done and I will check this PR again.

image

**Comment by kathrynsilvaconway** [comment]
ETA: End of day, as soon as requested changes are made.
Availability: 1 hour

@lilyarj Don't forget to request a re-review from me as soon as you finish your changes.

**Comment by lilyarj** [comment]
Hi, @kathrynsilvaconway @Sparky-code I followed the steps in [the guide,](https://github.com/hackforla/website/wiki/Remove-files-from-your-Pull-Request) but I'm unsure what to do after that. Do I re submit another pull request, or is it supposed to auto update? 
`lilyarjomand@Lilys-MacBook-Pro website % git rev-parse upstream/gh-pages
a2883aaf28f5e664faa7cd5efaf4cd7ae64ed8b3

lilyarjomand@Lilys-MacBook-Pro website % git checkout a2883aaf28f5e664faa7cd5efaf4cd7ae64ed8b3 -- _data/internal/credits/code.yml`

**Comment by kathrynsilvaconway** [comment]
> Hi, @kathrynsilvaconway @Sparky-code I followed the steps in [the guide,](https://github.com/hackforla/website/wiki/Remove-files-from-your-Pull-Request) but I'm unsure what to do after that. Do I re submit another pull request, or is it supposed to auto update? `lilyarjomand@Lilys-MacBook-Pro website % git rev-parse upstream/gh-pages [a2883aa](https://github.com/hackforla/website/commit/a2883aaf28f5e664faa7cd5efaf4cd7ae64ed8b3)
> 
> lilyarjomand@Lilys-MacBook-Pro website % git checkout [a2883aa](https://github.com/hackforla/website/commit/a2883aaf28f5e664faa7cd5efaf4cd7ae64ed8b3) -- _data/internal/credits/code.yml`

hI @lilyarj , I am not completely sure if further action is needed or not. I am going to discuss it during office hours this evening.

**Comment by kathrynsilvaconway** [comment]
The commit errors in this PR have prompted us to begin work on a new guide for deleting/preventing these issues. For the immediate issue, we will close this PR and have @lilyarj open a new one.

**Pull request closed without merging**
