### PR TITLE
4799 refactor tools list for brigade

### LINKED ISSUE #4799: Refactor Tools data for brigade-organizers-playbook.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Zoom, Calendly, Otter.ai, Google Docs, HackforLA.org guides
```
to
```
tools:
  - Zoom
  - Calendly
  - Otter.ai
  - Google Docs
  - HackforLA.org guides
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by PoppaRainmaker**
Fixes #4799

### What changes did you make?
  - changed tools list for the brigade organizers playbook
  - 
  -

### Why did you make the changes (we will use this info to test)?
  - tools list needed to be converted to a list for searching/filtering purposes
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>No visual changes expected, only functional changes expected when filter feature is implemented</summary>

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Hi @PoppaRainmaker please update the first line of the PR to read:
```
Fixes #4799
```
Without that information, our GHA scripts are not able to link the PR to an issue, which causes a number of problems with our automation, and also makes it more difficult for PR reviewers who need to refer to the original issue.  Thanks!

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @PoppaRainmaker please update the first line of the PR to read:
```
Fixes #4799
```
Without that information, our GHA scripts are not able to link the PR to an issue, which causes a number of problems with our automation, and also makes it more difficult for PR reviewers who need to refer to the original issue.  Thanks!

**Comment by LRenDO** [comment]
Hi @ronaldpaek and @mademarc! When you have a minute, please add your availability and eta. Thanks!

**Comment by ronaldpaek** [comment]
Hi team I will review this PR on Friday, August 11th before EOD.

**Review by ronaldpaek — APPROVED** [review]
The changes you made look correct to me, I checked file and the local instance no issues there. Thank you for all your hard work as services, great job!

**Comment by mademarc** [comment]
Review ETA: 8/11/2023
Availability: 5:16PM

**Review by mademarc — COMMENTED** [review]
Hey @PoppaRainmaker  the screenshots a 404 error on the image if it is possible to fix that to see what changes that you have done for proper reviewing that said the code changes on line 93 look fine and @LRenDO  the ETA and Availability is done.

**Comment by PoppaRainmaker** [comment]
> Hi @PoppaRainmaker please update the first line of the PR to read:
> 
> ```
> Fixes #4799
> ```
> 
> Without that information, our GHA scripts are not able to link the PR to an issue, which causes a number of problems with our automation, and also makes it more difficult for PR reviewers who need to refer to the original issue. Thanks!

Thanks @roslynwythe - I believe I added the issue id in the description as you requested, please confirm when you get a chance.

**Comment by PoppaRainmaker** [comment]
> Hey @PoppaRainmaker the screenshots a 404 error on the image if it is possible to fix that to see what changes that you have done for proper reviewing that said the code changes on line 93 look fine and @LRenDO the ETA and Availability is done.

Thanks @mademarc - I don’t believe I added a screenshot, unless I’m mistaken there shouldn’t be any difference in terms of the page display after the changes. I can add a before and after though to memorialize this if it’s standard procedure.

**Comment by kwangric** [comment]
Hey @PoppaRainmaker! If you've made the requested changes, you can re-request reviews from the assigned reviewers so they know when to take a look at your PR again.
review-2

Also if nothing changed visually on the website, you can remove the screenshots and just write a message in your PR that there weren't any visual changes.

**Review by roslynwythe — APPROVED** [review]
Thank you @PoppaRainmaker You've made the correct code change, setup the branches correctly, described your work, and linked your PR to the isssue.  The change checks out perfectly in the browser.  Great job on this issue.

**Pull request merged**
