### PR TITLE
Update Project Profile: Lucky Parking (Update Technologies) #5790

### LINKED ISSUE #5790: Update Project Profile: Lucky Parking (Update Technologies)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `technologies` variable and change the following:

**From:**
```
  - React
  - AWS
  - PostgreSQL
  - Node.js
  - Mapbox
```
**To:**
```
  - React
  - TailwindCSS
  - Mapbox
  - Node.js
  - Express
  - MongoDB
  - AWS
  - Markdown
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

### PR DESCRIPTION
**Pull request by dustinowen**
Fixes #5790 

### What changes did you make?
  -Updated technologies

### Why did you make the changes (we will use this info to test)?
  -Per Update Project Profile: Lucky Parking (Update Technologies) https://github.com/hackforla/website/issues/5790

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before-1
before-2

</details>

<details>
<summary>Visuals after changes are applied</summary>

after-1
after -2

</details>

### CODE REVIEW

**Comment by dustinowen** [comment]
@agutiernc @ajb176 

Hello - here is the new PR with the changes in branch name to meet guidelines. My apologies for the oversight. Thank you for the feedback/information, I have made note of this for future issues.

**Review by agutiernc — APPROVED** [review]
The following are correct:
- Linked issue and branch name added
- Technologies variable updated with the latest info
- Lucky Parking card and info page correctly displayed on the website and in different view modes

Great job @dustinowen! And thanks for your contribution and update changes!

**Review by ajb176 — APPROVED** [review]
Yup, everything looks good now. I think your before/after screenshots are swapped but it's no big deal, I'm seeing the proper changes on the docker container. 

Once you navigate back to your local gh-pages branch, make sure to run 'git pull upstream gh-pages' to make sure your local branch is synced to the HFLA branch. The contributing.md file should cover how to do this if you're unsure, but you can also reach out if you have any issues. 

Nice work, and thanks for taking the time to re-do the PR.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @dustinowen, thank you for working on this issue! The branches are correct and the changes to the technologies for the Lucky Parking project match what is required per issue #5790.

Could you switch the before and after screenshots around so that they match the dropdown title? Once implemented, I'll merge the pull request.

**Comment by dustinowen** [comment]
Hi @Adastros - the screenshots have been updated to their proper label.

**Review by Adastros — APPROVED** [review]
Thanks for making the changes @dustinowen! The screenshots look good.

**Pull request merged**
