### PR TITLE
updates projects filter to include tools

### LINKED ISSUE #6196: Add Tools to the Languages/Technologies filter group on the projects page
### Overview
We need to add Tools into `Languages/Technologies` filter on the projects page, revising it to `Languages/Technologies/Tools`, in order to provide users with the ability to filter projects based on Tools.  

### Details
The [projects](https://www.hackforla.org/projects) and [projects-check](https://www.hackforla.org/projects-check) pages share the same js file `/assets/js/current-projects.js` ; based on the value of `window.location.pathname`, the code implements different filters between the pages.   Note that in this issue we do not want to alter the projects-check in any way.  

### Action Items
- [x] Open the file `assets/js/current-projects.js` in your IDE
- [x] Update the code to add `Tools` to the `Languages/Technologies` filter
- [x] Rename the filter `Languages/Technologies/Tools`
- [x] Using docker, confirm the operation of the filters on the `/project` page
- [x] Using docker, confirm that the appearance and behavior of the `/projects-check` page is unchanged.  

### Resources/Instructions
- Projects page: [webpage](https://hackforla.org/projects) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- Projects Check page: [webpage](https://hackforla.org/projects-check) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- This issue was created from #6150

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #6196 

### What changes did you make?
  - Updated the filters for the projects and project-check pages

### Why did you make the changes (we will use this info to test)?
  - To update the projects and project-check pages filters to include the tools filter for more accurate filings

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before
before1

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after
after1

</details>

### CODE REVIEW

**Comment by Anahisv23** [comment]
Review ETA: 4 PM 2/20/24
Availability: 12pm - 5pm Tuesday and Wednesday

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
@sornekian , Thank you for working on this issue. Merge branches are set up correctly. With the current code change, "Tools" is included in the filter title only. The tool items are not added in the `filter-list` For instance, "Figma" is a tool used in a project but not listed on the filter-list.
PR6318

**Comment by roslynwythe** [comment]
ETA to review 2/26 Availability all day

**Comment by sornekian** [comment]
I am unclear as to where the the languages and technologies data is in that filter, for me to add the tools data. Any suggestions?

**Comment by roslynwythe** [comment]
Hi @sornekian this the current line of code that is used to create the array of filter items under "Technologies and Languages", that you can update to include Tools:
          
https://github.com/hackforla/website/blob/8cf71334372ad6a7c5df137b02ff32e8e06bc550/assets/js/current-projects.js#L233

Also just a note about communication: when you create a comment in an issue, it is more likely to be noticed promptly if you "comment mention" the appropriate members.  So in this case you could have started your comment with @roslynwythe @Thinking-Panda

**Comment by sornekian** [comment]
I see the mapping but I can seem to find where the data is stored to add the tools like (1) Calendly (2) FigJam (2) Figma, etc. I'm a bit lost... @roslynwythe @Thinking-Panda

**Comment by elliot-d-kim** [comment]
Availability: Mon-Thu outside of 2-7pm, Fri before 2pm, Sat all day
ETA: Sunday (3/3)

**Comment by Thinking-Panda** [comment]
@sornekian , the tools data list is in `sortedProjectsData` sent as the argument to the function. Including it in `line 233` will add tools to the filter list.

**Pull request closed without merging**
