### PR TITLE
Home Unite Us change alt text #4012

### LINKED ISSUE #4012: Home Unite Us: Update alt text for Home Unite Us image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Home Unite Us` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/home-unite-us.md`:

**From:**
```
Home Unite Us logo, blue circle with white heart in the center, two hands hugging the logo with "Home Unite Us" above the heart.
```

**To:**
```
Home Unite Us
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/home-unite-us

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/home-unite-us.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by erinpattison**
Fixes #4012

### What changes did you make and why did you make them ?

  - I changed the alt text in home-unitu-us.md according to instructions
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by erinpattison** [comment]
Hi! This is my first issue with Hack For LA - the instruction in the contributing doc were kind of difficult to follow along with, but I think I figured it out- if there is anything I did incorrectly please let me know!

**Comment by perlaroyerc** [comment]
Review ETA: 11 AM 3/17/23
Availability: 11-6 PM ET M-F

**Comment by bootcamp-brian** [comment]
Review ETA: 3:45pm
Availability: Today before 6pm

**Review by bootcamp-brian — CHANGES_REQUESTED** [review]
Good job on making the requested changes to the file, but it looks like your pull request isn't coming from the correct branch. An example for pushing your issue branch can be found [here](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch) at 3.1a of the contributing.md.

If you missed the step to setup a new branch when you started working on this issue, you'll want to look at 2.7b [here](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) instead.

Oh and I think you might have to delete this pull request and create a new one in order to get the branches setup right because I don't know of a way to edit that part once a pull request is submitted.

**Review by perlaroyerc — CHANGES_REQUESTED** [review]
Thank you for taking this issue @erinpattison! As Brian mentioned above your changes should always come from a feature branch that you create from your original branch (gh-pages), and should be formatted like this `change-alt-text-4012(issue #)`. Also, make sure to include the PR to the project board, if you need any help you can reference [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board).

The changes were made in the correct document, and the issue was linked correctly. Add a brief explanation of why you made the changes, it's a good habit to get into for keeping your documentation top-notch!

**Comment by ExperimentsInHonesty** [comment]
@erinpattison Are you going to fix the changes in this PR or should we close it?  If we don't hear from you on the PR or the issue by 2023-04-09 we will close it and remove you from the issue.

**Comment by jdingeman** [comment]
Hi @erinpattison, since we have not heard from you and have seen no activity since changes were requested, we are going to close this PR without merge.

**Pull request closed without merging**
