### PR TITLE
Update center.yml

### LINKED ISSUE #2805: Edit content field and remove type field from center.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/center.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/center.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/center.yml#L4
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/center.yml#L11

### PR DESCRIPTION
**Pull request by trz832**
Fixes #2805 

### What changes did you make and why did you make them ?

  - Changed line 4 'content: icon' to 'content-type: image'
  - Removed 'type: icon' from line 11
  -

### CODE REVIEW

**Comment by Olanrewaju-Ak** [comment]
Review ETA: 7 PM 6/20/22
Availability: 2 hrs Monday

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Jun 19, 2022

**Review by tamara-snyder — DISMISSED** [review]
Hi @troywzhu, great work! I can see that you changed content: icon to content-type: image and removed the unnecessary line of code. Thank you!

**Comment by mmogri** [comment]
Availability: 1 hour
Review ETA: Jun 19, 2022

**Comment by mmogri** [comment]
It looks like the pull request has not been done from the correct branch. 

From https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests:
"The commit from must be from the collaborator who opened the pulled request"
As such, the commit should be from "troywzhu:troywzhu-patch-3" (ie, from troywzhu's own account rather than a branch within hackforla).

Instead it looks like both the to and from branches are within hackforla: "[troywzhu](https://github.com/troywzhu) wants to merge 1 commit into [gh-pages](https://github.com/hackforla/website) from [troywzhu-patch-3](https://github.com/hackforla/website/tree/troywzhu-patch-3)"

The "from" branch should be from troywzhu's own account. Please redo the pull request with the correct branch.

**Review by mmogri — CHANGES_REQUESTED** [review]
It looks like the pull request has not been done from the correct branch. 

From https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests:
"The commit from must be from the collaborator who opened the pulled request"
As such, the commit should be from "troywzhu:troywzhu-patch-3" (ie, from troywzhu's own account rather than a branch within hackforla).

Instead it looks like both the to and from branches are within hackforla: "[troywzhu](https://github.com/troywzhu) wants to merge 1 commit into [gh-pages](https://github.com/hackforla/website) from [troywzhu-patch-3](https://github.com/hackforla/website/tree/troywzhu-patch-3)"

The "from" branch should be from troywzhu's own account. Please redo the pull request with the correct branch.

**Review by Olanrewaju-Ak — APPROVED** [review]
@troywzhu good work!!. I see that you changed content: icon to content-type: image and removed the unnecessary line of code.
However, you didn't seem to follow the correct branch naming convention for your issue
Note: 
You are to choose a branch name that:
-relates to the issue (No spaces!)
-includes the issue number
-The format should be such that, the words are a brief description of the issue that will make sense at a glance to someone unfamiliar with the issue.
as opposed to using troywzhu-patch-3.

I hope you can make this correction in your subsequent issues.

**Review by KBWells77 — CHANGES_REQUESTED** [review]
@troywzhu  Good job, you condensed the code so that it now says content-type:image. Like other reviewers said, you did not follow the Branch Naming Procedure, so the branch name is not clear. You need to follow the correct branch to and from naming procedure, as others have listed above.

**Comment by kathrynsilvaconway** [comment]
While the comments above are correct, I don't think it is possible to change the branch name. I am going to merge this request because the work is done correctly, and the author does not appear to be active with Hfla at the moment. 

@troywzhu For your reference, a better branch name would be something like:

    edit-content-and-type-fields-on-center-yml-2805

See: Section 2.7.b of [Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)

**Pull request merged**
