### PR TITLE
Updated Access-The-Data Slack/Overview links

### LINKED ISSUE #1590: Update Project Profile: Access The Data
### Overview
As a product manager of Access The Data I want my project's details to be up to date on the HackforLA website

### Project card
access-the-data.md

### Action Items

- [ ] Access the Data Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
      - [ ] links
         - [x] Github
         - [ ] Slack
         - [ ] Test Site
         - [ ] Demo Site
         - [ ] Site
      - [ ] looking
      - [ ] technologies
      - [ ] location
      - [ ] partner
      - [ ] tools
      - [ ] status

### PR DESCRIPTION
**Pull request by HiThereImCam**
Fixes #1590

### CODE REVIEW

**Comment by arghmatey** [comment]
Hi, @HiThereImCam! Looks good to me! 

Before we merge this, could you please edit your original comment to have "Fixes " before the issue number? This ensures the issue will be closed automatically once your pull request is accepted and merged. Thank you!

**Comment by HiThereImCam** [comment]
> 
> 
> Hi, @HiThereImCam! Looks good to me!
> 
> Before we merge this, could you please edit your original comment to have "Fixes " before the issue number? This ensures the issue will be closed automatically once your pull request is accepted and merged. Thank you!

Completed. Thank you!

**Comment by arghmatey** [comment]
Can you change it around to be in this format?

Screen Shot 2021-06-11 at 11 24 47 AM

**Comment by HiThereImCam** [comment]
> Can you change it around to be in this format?
> 
> Screen Shot 2021-06-11 at 11 24 47 AM

Completed.

**Review by arghmatey — APPROVED** [review]

**Pull request merged**
