### PR TITLE
Updated Criminal-Sentencing md file with Program Area #2276

### LINKED ISSUE #2276: Add Program Area to Project: Criminal Sentencing
### Overview
We need to add program area information to the Criminal Sentencing project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Justice
```

### Resources/Instructions
File location to make the change: _projects/criminal-sentencing.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/criminal-sentencing.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

### PR DESCRIPTION
**Pull request by vmaineng**
Fixes  #2276

### What changes did you make and why did you make them ?

  - Added program-area to criminal-sentencing.md file as requested.

### CODE REVIEW

**Review by arpitapandya — CHANGES_REQUESTED** [review]
@vmaineng Could you link the issue on the top comment? where it says fixes #

**Comment by vmaineng** [comment]
I updated the fix comment with "Add Program Area to Project: Criminal Sentencing #2276"

**Comment by blulady** [comment]
Hey @vmaineng, looks like good work!! 
If you could take a peek at some of the PR's in the que to see how they add the issue number, while the name doesn't hurt it's not exactly the standard. Also because the issue number was not in your pr initially, none of the labels were added. If you could add the labels from the original issue #2276, we'd be able to merge your PR (again, it might be helpful to peek at the other PRs).

**Comment by vmaineng** [comment]
Hey @blulady! I appreciate the update :) I updated the comment to only include the issue number and updated the labels. Please let me know if you have any further questions. Thanks!

**Review by arpitapandya — APPROVED** [review]
Changes looks correct! Thanks for updating @vmaineng

**Pull request merged**
