### PR TITLE
removed 1Password from tools

### LINKED ISSUE #5680: Remove '1Password' From Tools Data in website.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
'1Password' needs to be removed from tools data in website.md since 1Password is not considered as a tool.

### Action Items
- [x] Open `_projects/website.md` in your IDE
- [x] In the `tools` section, remove the line:
```
  - 1Password
```
- [x] Using docker, confirm that on the [Project Check Page](https://www.hackforla.org/projects-check), the Tools menu no longer includes `1password`, and the [Website Project Page](https://www.hackforla.org/projects/website) no longer displays `1Password` under Tools, but that both pages are otherwise unchanged.  

### Resources/Instructions
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)
[Website Project Page](https://www.hackforla.org/projects/website)
- This issue resulted from #5271

### PR DESCRIPTION
**Pull request by dimiprousalis**
Fixes #5680

### What changes did you make?
  - Removed "1Password" from the Tools section in _projects/website.md

### Why did you make the changes (we will use this info to test)?
  - To remove "1Password" from Tools section on [hackforla.org/projects](https://www.hackforla.org/projects/)
  - To remove "1Password" from Tools section on [hackforla.org/projects/website](https://www.hackforla.org/projects/website)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

1pass-before
1pass-before-pt2

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

1pass-after
1pass-after-pt2

</details>

### CODE REVIEW

**Comment by jphamtv** [comment]
Availability for this week: Monday-Friday 12–2 PM, 8–10 PM (PST) 
My estimated ETA for completing this issue: 10 PM 11/22/23

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 11/22/23

**Review by freaky4wrld — COMMENTED** [review]
Hi there , great work there all the work assigned to you in the issue is done correctly
- the to/from branch looks good
- the visual changes are completely applied in the local environment, on both the pages
- the changes specified is done correctly and are apt
- the issue linked is correct too

Great work there, I'll approve this PR, but just a small change to be made can you please `check off the action items` [ ] in the original issue #5680. 
Rest is awesome, specially the links you mentioned in the comment are quite time-saving.

**Review by jphamtv — APPROVED** [review]
Nice work! The pull request was done with the correct branch, and the issue is linked correctly. Changes in the source code are applicable, clean, and everything looks good in the browser.

**Comment by dimiprousalis** [comment]
> Hi there , great work there all the work assigned to you in the issue is done correctly
> 
> * the to/from branch looks good
> * the visual changes are completely applied in the local environment, on both the pages
> * the changes specified is done correctly and are apt
> * the issue linked is correct too
> 
> Great work there, I'll approve this PR, but just a small change to be made can you please `check off the action items` [ ] in the original issue #5680. Rest is awesome, specially the links you mentioned in the comment are quite time-saving.

Thank you! I have checked off the action items in the original issue #5680

**Review by t-will-gillis — APPROVED** [review]
Hey @dimiprousalis - Great job on this issue! Thanks for working with @jphamtv and picking up the comments from @freaky4wrld

**Pull request merged**
