### PR TITLE
Update: Add Rishi Raghu to Civic Tech Jobs

### LINKED ISSUE #7731: Update Project Profile: Civic Tech Jobs Add Rishi Raghu
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile under the other Researchers
```
  - name: Rishi Raghu
    github-handle: rishi222k
    role: UXR Researcher
    links:
      slack: https://hackforla.slack.com/team/U07G0CHGNSD
      github: https://github.com/rishi222k
    picture: https://avatars.githubusercontent.com/rishi222k
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: (https://www.hackforla.org/projects/civic-tech-jobs)
- initiating ER:  #7490

### PR DESCRIPTION
**Pull request by handshek**
Fixes #7731

### What changes did you make?
  - Added Rishi Raghu to the Civic Tech Jobs project file.

### Why did you make the changes (we will use this info to test)?
- We need to keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website
 

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by codyjohnsontx** [comment]
Review ETA: 6 PM 12/9/24
Availability: 4-7 PM Monday

**Review by DrAcula27 — APPROVED** [review]
@buneeIsSlo Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7731 
- The correct file `_projects/civic-tech-jobs.md` was edited
- No extra edits were made
- Appearance of the website is unchanged (Chrome and Firefox)
Approved! 👍

**Comment by codyjohnsontx** [comment]
- Branch name looks good
- PR is linked correctly to the issue
- CodeQL alerts are good
- The content added.
- Links work correctly
- branch ran great on my local machine
- Before and After photos added correctly and show the changes

Good job on the PR @buneeIsSlo and thank you for taking the time to knock this out 🥳

**Comment by codyjohnsontx** [comment]
- Branch name looks good
- PR is linked correctly to the issue
- CodeQL alerts are good
- The content added.
- Links work correctly
- branch ran great on my local machine
- Before and After photos added correctly and show the changes

Good job on the PR @buneeIsSlo and thank you for taking the time to knock this out 🥳

**Review by codyjohnsontx — APPROVED** [review]
- Branch name looks good
- PR is linked correctly to the issue
- CodeQL alerts are good
- The content added.
- Links work correctly
- branch ran great on my local machine
- Before and After photos added correctly and show the changes

Good job on the PR @buneeIsSlo and thank you for taking the time to knock this out 🥳

**Pull request merged**
