### PR TITLE
Update group.yml

### LINKED ISSUE #2833: Edit content field and remove type field from group.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/group.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/group.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L11

### PR DESCRIPTION
**Pull request by JijiTheCreator**
Edited line 4 and removed line for improved code readability and eliminate redundany.

Fixes #2833

### What changes did you make and why did you make them ?

  - Edited line 4 for improved readability
  - removed line 11 to eliminate redundancy
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by arpitapandya — CHANGES_REQUESTED** [review]
@JijiTheCreator Please create a branch from your working repo, It looks like you have created branch on Hack for LA's website repo. Adding a [guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue)

mistake

Also, when you create a Pull request, add linked issue

**Comment by arpitapandya** [comment]
@JijiTheCreator let us know if you need help

**Comment by JijiTheCreator** [comment]
@arpitapandya Hi I do need assistance with the workflow for the first time. I tried attending Sunday meeting but have had some issues. I will be attending the Tuesday meeting to hopefully solidify the workflow process.

**Comment by blulady** [comment]
@JijiTheCreator Just wanted to check in and see if you got the help you needed with this PR....

**Comment by blulady** [comment]
Hope all is well @JijiTheCreator,
If we don't hear back by Monday we're going to assume that you aren't available to work on this issue and return it to the priority backlog.

**Comment by MattPereira** [comment]
@JijiTheCreator I'm closing this PR because you created a new one

**Pull request closed without merging**
