### PR TITLE
updated alt text for home unite us 2093

### PR DESCRIPTION
**Pull request by EdASalazar**
fixes #4465

### What changes did you make and why did you make them ?

Changed the alt text to "Home United Us" as per the ticket. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes on the Website.

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Review ETA: EOD 4/10/23
Availability: M-F 7-12pm PST

**Comment by steven-positive-tran** [comment]
When doing an issue and creating the pull request. Do put Fixes #(issue number) at the top so that the github bot automatically puts in labels.

Edit:
https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-1-is-there-a-linked-issue

**Review by steven-positive-tran — COMMENTED** [review]
You have merged to the correct branch using your fork.
Code changes seems appropiate for the issue.

In my machine I do see the alt img change
Firefox
image
Edge
image

Approved and thank you for taking up this issue. Next time just make sure that the pull request has Fixed #(issue number) at the top.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @EdASalazar your code change looks good, and you setup the PR branches correctly, but I need to request a few changes to the PR:
- The first line of the PR should read: `Fixes #4465`
- Please clean up the blank bullet points
- We do not require a screenshot for issues that modify alt text, so you should delete everything starting with `<details>` up to and including the final `</details>` tag and write "No Visual Changes to the Website".  

Thank you!

**Comment by EdASalazar** [comment]
Updated the pull request. Cleaned up the bullet points and removed the "details" elements. Added "No visual changes...".

**Review by roslynwythe — APPROVED** [review]
Great job @EdASalazar - the code change is correct, the PR is well-formed and tested successfully in the browser.

**Pull request merged**
