### PR TITLE
removed back slash from img tag 4393

### LINKED ISSUE #4393: img Tag Refactor: Getting Started page - `step-img-icon-cop proj-4.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-cop" src="assets/images/getting-started/proj-4.png" alt="" />
```
to
```
<img class="step-img-icon-cop" src="assets/images/getting-started/proj-4.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by EdASalazar**
Fixes #4393 

### What changes did you make and why did you make them ?
As per the ticket I deleted the backslash from the img tag on line #91 of getting-started.

### CODE REVIEW

**Comment by karengcecena** [comment]
ETA: 10:30am on 4/13
Availability: 9:50am - 10:30am

**Comment by karengcecena** [comment]
Hi, [EdASalazar](https://github.com/EdASalazar). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, you removed the slash that was asked for, and the website looks good on my local machine. 

Great job & thanks again for working on this issue!

**Comment by LOSjr4** [comment]
Availability: M,T,TH 9AM-1PM
ETA: today noon

**Review by LOSjr4 — APPROVED** [review]
I saw you removed the unnecessary slash correctly and it doesn't change the website appearance at all, just cleaner code. Good job handling your good first issue!

**Comment by blulady** [comment]
> Hi, [EdASalazar](https://github.com/EdASalazar). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, you removed the slash that was asked for, and the website looks good on my local machine.
> 
> Great job & thanks again for working on this issue!

Excellent review of the PR!! If you could leave this as a review rather than a comment, I'll go ahead and merge the code.

**Review by karengcecena — APPROVED** [review]
Hi, [EdASalazar](https://github.com/EdASalazar). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, you removed the slash that was asked for, and the website looks good on my local machine.

Great job & thanks again for working on this issue!

**Comment by karengcecena** [comment]
> > Hi, [EdASalazar](https://github.com/EdASalazar). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, you removed the slash that was asked for, and the website looks good on my local machine.
> > Great job & thanks again for working on this issue!
> 
> Excellent review of the PR!! If you could leave this as a review rather than a comment, I'll go ahead and merge the code.

Oops, my bad! Just did it

**Pull request merged**
