### PR TITLE
Updated Leadership List for Open Community Survey 

### LINKED ISSUE #3217: Update Project Profile: Open Community Survey
### Overview
As a product manager of Open Community Survey I want my project's details to be up to date on the HackForLA website

### Project card
URL: https://github.com/hackforla/website/tree/gh-pages/_projects/open-community-survey.md

### Action Items

- [ ] Open Community Survey Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links 
         - [x] Github
         - [x] Slack
         - [x] Test Site (Don't exist)
         - [x] Demo Site (Don't exist)
         - [x] Site (Don't exist)
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources

- HackforLA.org, Open Community Survey page: https://www.hackforla.org/projects/open-community-survey
- [OCS Roster](https://docs.google.com/spreadsheets/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit?usp=sharing)

### Prior Closed Issues

- 2021-10-11 https://github.com/hackforla/website/issues/2364#issue-1023261996
- 2022-01-22 https://github.com/hackforla/website/issues/2711

### PR DESCRIPTION
**Pull request by RyanCahela**
Fixes #3217

### What changes did you make and why did you make them ?

  - Added Ambareen Sultana's name to open-community-survey.md along with slack and github profile information

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before_Desktop

Before_mobile

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After_Desktop
After_Mobile

</details>

### CODE REVIEW

**Comment by clayton1111** [comment]
ETA: < 1 hour
Availability: All day

**Review by clayton1111 — APPROVED** [review]
Everything looks good!

**Comment by lilyarj** [comment]
ETA: 7/6
Availability: 2hrs

**Comment by Wny-Duong** [comment]
ETA:  7/9/22, Saturday
Availability: 2 hours

**Review by Wny-Duong — APPROVED** [review]
Changes look good and Open Community Survey's product page has the right new member added to it. Good work.

**Pull request merged**
