### PR TITLE
Communities of practice info update 2758

### LINKED ISSUE #2758: Communities of Practice information updates: [PRODUCT MANAGEMENT Community of Practice]
### Overview
As a member of Hack for LA, I want the information on the website to be accurate and up to date. For this issue, we will update the information for Project/Product Management section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice).

### Action Items
- [ ] In [_data/internal/communities/project-management.yml](https://github.com/hackforla/website/blob/c80ed5135c439c837b2a8e275b29a49af93284ea/_data/internal/communities/project-management.yml), update the information following the request below:

> ### Remove person(s) and info from CoP file?
> 
> YES
> 
> ### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:
> 
> Name: Carol Zhu
> 
> Name: Ebele Oputa
> 
> Name: Olivia Chiong
> 
> ### Add person(s) and info to CoP file?
> 
> NO
> 
> ### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:
> 
> _No response_

### Resources/Instructions
- Project/Product Management section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- [_data/internal/communities/project-management.yml](https://github.com/hackforla/website/blob/c80ed5135c439c837b2a8e275b29a49af93284ea/_data/internal/communities/project-management.yml)

### PR DESCRIPTION
**Pull request by blulady**
Fixes #2758 

### What changes did you make and why did you make them ?

  - Remove person(s) and info from CoP file (project-management.yml)
  - I removed them to update the Project Manager section of the Communities of Practice page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Hi Sarah, your work on this issue looks good! However, I noticed there are changes to CONTRIBUTING.md in this PR which are not related to the issue.

Please remove those changes (looks like lines 317-320 of CONTRIBUTING.md) and re-request a review from me when you're ready.

Thanks!

**Comment by blulady** [comment]
> Hi Sarah, your work on this issue looks good! However, I noticed there are changes to CONTRIBUTING.md in this PR which are not related to the issue.
> 
> Please remove those changes (looks like lines 317-320 of CONTRIBUTING.md) and re-request a review from me when you're ready.
> 
> Thanks!

Good Catch!! Thank you.

**Comment by blulady** [comment]
So I believe that I made the changes you requested.  On the communities-of-practice-info-update-2758 branch on both my local and github repository, I see the lines missing from the original pr are now in the Contributing.MD file but I am not seeing the changes here.
Please Advise,
Sarah

**Review by tamara-snyder — APPROVED** [review]
Hi Sarah, thank you for removing the changes to CONTRIBUTING.md. As before, the rest of your changes look good and they display the updated project-management data as expected on the website. Great work on this issue!

**Comment by poorvi4** [comment]
Hi Sarah,
Sorry for the late response however as per Tamara's comments, everything looks good to go! Good work!

**Review by poorvi4 — COMMENTED** [review]
Great work in implementing the aforementioned suggestions made by Tamara!

**Pull request merged**
