### PR TITLE
Update Project Profile: Expunge Assist

### LINKED ISSUE #3931: Update Project Profile: Expunge Assist
### Overview
As a developer, we need to ensure the Expunge Assist project's details are up to date on the HackforLA website. For this issue, we will update the Expunge Assist project's partners, links, and leadership.

### Action items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [expunge-assist.md](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md) file and find the `partners`, `links`, and `leadership` variable.
- [x] Remove the `partner` variable since there are no current partners for this project
- [x] Remove the "Overview" link by deleting the following lines from the project's `links` variable
```
    - name: Overview
      url: '../assets/pdfs/Expunge-Assist-Project-One-Sheet.pdf'
```
- [x] Remove Valeriya Metla from the `leadership` variable
- [x] Add the following persons to the `leadership` variable
    - [x] Name: Sheron Virani
GitHub Handle: sheronvirani21
Role: Product Manager, Research
Slack Member ID: U041X0628B0
    - [x] Name: James Shin
GitHub Handle: jamesshin27
Role: Product Manager, Design
Slack Member ID: U04BS46F67L
- [x] Check the [Expunge Assist project page](https://www.hackforla.org/projects/expunge-assist) on your local development environment to verify the changes and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [The Expunge Assist markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find a Slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #3931 

### What changes did you make and why did you make them?

  - Removed partner section since there is no longer a partner for this project.
  - Removed the overview section because it include out-of-date information.
  - Removed an old leadership position, and added new leadership to keep leadership up-to-date.

**Note:** I modified adding leadership action items to keep consistent with the rest of the code.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Review ETA: EOD 2/21
Availability: 2 hr

**Review by Jaretzbalba — APPROVED** [review]
@d-perez-8 I see that the partners variable was removed along with the overview link, and the leadership was updated as requested in the issue. Everything also looks good in my local environment! Thank you for working on this issue!

**Comment by RyanGehris** [comment]
Review ETA: EOD 2/22
Availability: 02/21 8-9pm, 02/23 5-8pm

**Comment by RyanGehris** [comment]
Great job making the required changes! The leadership changes, along with the links are working as intended. The partners variable and overview link were also removed correctly. 

You did a great job committing into hackforla:gh-pages. I recommend next time to follow this link to  [create a new branch where you will work on your issue]( https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue ) instead of working on the gh-pages branch.

Thank you for all your hard work!

**Review by RyanGehris — APPROVED** [review]

**Comment by d-perez-8** [comment]
@RyanGehris Sorry for the rookie mistake. I forgot to check which branch I was on. Should I redo the pull request?

**Comment by RyanGehris** [comment]
@d-perez-8 I don't think you do. I was curious about that as well, but when looking at the requirements to accept a pull request, the two major things regarding the [branch](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Step0) is that the commit must be into "hackforla:gh-pages" and from the collaborator who opened the pulled request. I guess that implies that your local branch being named "gh-pages" and not something like "Update-Project-Profile-Expunge-Assist-4020" is fine. 

Let's wait and see what the merge team has to say.

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @d-perez-8, good job on completing the issue! The branch that you've worked on should be named as described in the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue) document. You should be able to create a new branch on your fork of the repository with your updates and change the target branch on the pull request without creating new pull request. 

@RyanGehris thanks for catching the branch name! Reading through the [how to review a pull request wiki](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#step-0-is-the-pull-request-done-with-the-correct-branch) it's not a requirement to check the collaborator's branch name as you have mentioned. This should be updated so that it's consistent with the instructions in the CONTRIBUTING.md. This can be addressed by creating an "emergent request" issue.

**Comment by d-perez-8** [comment]
Deleting the commit from the gh-pages branch caused the pull request to close. Creating a new pull request to the correct branch.

**Pull request closed without merging**
