### PR TITLE
Add surveys/ in cspell.json 5847

### LINKED ISSUE #5847: Add "surveys/ " to "ignorePaths" array in cspell.json
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to `cspell.json`
- [x] Add the path `surveys/` to the end of the array `ignorePaths`
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [ ] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by ShamaaTabassum**
Fixes #5847

### What changes did you make?
  -Added "surveys/ " to "ignorePaths" array in cspell.json

### Why did you make the changes (we will use this info to test)?
  - So that "surveys/ " file should be excluded from spell checking,

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @jenjenkayi, @patelbansi3009, @taylorbeee, @nssensalo, @ShamaaTabassum as a reminder, while you are waiting for your PRs to be reviewed, please consider reviewing each other’s `good first issue` PRs and any other PRs you feel comfortable with. Instructions are here for [How to Review Pull Requests]( https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) . You should aim to review two PRs for every PR you submit, and each PR ideally should have two or more reviewers. Thanks!
#6746, #6767, #6768, #6770, #6772

**Review by Maarimar — APPROVED** [review]
Hello! @ShamaaTabassum, thank you for contributing :)
You used the correct branch to commit your changes and added the path in the correct file and array specified on the issue. GTG.

**Comment by patelbansi3009** [comment]
Availability: Mon-Thu (11PM - 6PM) EST
ETA: EOD 04/29

**Comment by patelbansi3009** [comment]
Great work @ShamaaTabassum!

- Used the correct branch.
- Accurately linked the issue.
- Code changes are made as requested in the issue.
- There are no visual changes on the website.

Keep up the good work!

**Review by patelbansi3009 — APPROVED** [review]
Perfect Execution @ShamaaTabassum! Keep up the good work.

**Comment by t-will-gillis** [comment]
Hey @ShamaaTabassum Looks great, congrats on completing your first pull request! 

As a friendly note for the next time: on the description above, if you add a space between the dash and the text following, the Markdown will render correctly. For example:  


-My text is here
- My text is here

Great work!

**Pull request merged**
