### PR TITLE
img Tag Refactor: Toolkit page

### LINKED ISSUE #4366: img Tag Refactor: Toolkit page
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/toolkit.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="header-hero-image" src="/assets/images/toolkit/toolkit-hero.svg" alt="" />
```
to
```
<img class="header-hero-image" src="/assets/images/toolkit/toolkit-hero.svg" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/toolkit.html](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html)
2. Toolkit page: https://www.hackforla.org/toolkit
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by cng008**
Fixes #4366

### What changes did you make and why did you make them ?

- change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website.

### CODE REVIEW

**Comment by drakenguyen4000** [comment]
Review ETA: 4/3/23
Availability: M-F 4-8PM

**Comment by janice87** [comment]
Review ETA: 4/3/23
Availability: M-W 5-8 PM

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. In the source code, I see the change was made to the  tag to remove the slash at the end. There are no visual changes made. Good job on your first issue, this is approved!

**Review by drakenguyen4000 — APPROVED** [review]

**Comment by drakenguyen4000** [comment]
The tag is fixed, the issue is linked, your pull request description is helpful, changes look good in the local environment, and branches are set up correctly. 

However, I suggest adding why the change was needed.  Per the issue description as to why the change was needed.  
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () **so that the codebase is consistent with how we use img HTML tags.**

Thank you for taking this issue @cng008!  Great job!

**Comment by cng008** [comment]
@drakenguyen4000 I appreciate the feedback! I've taken your advice and made the necessary adjustments. Thank you for your time

**Pull request merged**
