### PR TITLE
commented out broken site links

### LINKED ISSUE #4923: Comment out broken site links for WorkForLA, HelloGOV, Jobs for Hope
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to comment out non-functional site links for the Work for LA, HelloGOV, and Jobs for Hope projects to avoid directing users to dead links on our site.

### Details

Our website contains several dead links on the pages of the mentioned projects, which lead to errors or non-existent pages. This provides a sub-optimal experience for our users.

### Action Items
- [x] Go to each project's project.md file in the GitHub repository under [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects).
- [x]  Locate the lines containing the link to the respective project's site. 
- [x]  Comment out both the line beginning with ` - name: ...` as well as with`   url: ...` so the site link will not be rendered on the live website. In Markdown, this can be done by placing a '#' at the start of each line. If you are using VSCode, you can highlight the line(s) to be commented out, then select 'Ctrl/Cmd' + '/' to automatically insert the '#'s.
- [x] Verify that each link no longer appears on the live site by running the site locally in Docker.

Projects to be fixed under the _projects folder:

- [x] Work for LA
  - [x] Locate file: [work-for-la.md](https://github.com/hackforla/website/blob/gh-pages/_projects/work-for-la.md)
  - [x]  Comment out the site link
- [x]  HelloGOV
  - [x] Locate file: [hellogov.md](https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md)
  - [x]  Comment out the site link
- [x] Jobs for Hope
  - [x] Locate file: [jobs-for-hope.md](https://github.com/hackforla/website/blob/gh-pages/_projects/jobs-for-hope.md)
  - [x]  Comment out the site link

### Resources/Instructions
[WorkForLA](https://www.hackforla.org/projects/work-for-la) project page
[HelloGOV](https://www.hackforla.org/projects/hellogov) project page
[Jobs for Hope](https://www.hackforla.org/projects/jobs-for-hope) project page
Associated ER: https://github.com/hackforla/website/issues/4594

### PR DESCRIPTION
**Pull request by JanineSooThow**
Fixes #4923

### What changes did you make?
  - Commented out site link under file work-for-la.md
  - Commented out site link under file hellogov.md
  - Commented out site link under file jobs-for-hope.md

### Why did you make the changes (we will use this info to test)?
  - The site links for work-for-la.md, hellogov.md and jobs-for-hope.md were not working. 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

image
workforla
hellogov
jobs-for-hope

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
after-hellogov
after-jobsforhope
after-workforla

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/5/23
Availability: 1-3 PM everyday

**Comment by ronaldpaek** [comment]
I plan to review this by Sept 7th.

**Comment by ortegaa32** [comment]
- Pull request contains correct branch and links to correct issue
- Changes accurately reflected in screenshots and don't appear to break the website
- Changes made to the right files and source code looks clean.

Well done @JanineSooThow. Approving you pull request.

**Review by ortegaa32 — DISMISSED** [review]

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @JanineSooThow You have the correct from-to branches, you are linked to the original issue, you are explaining what you did and why, and you are providing before and after screenshots. Great job!   

I have thing that I would like to request that was not specified on the original issue- you followed the issue correctly. This also does not affect the visuals on the website but instead involves the code itself: when commenting out the `- name: ` and `url: ` the code will appear cleaner and easier to read if the hashtags are aligned like so:  

```
  # - name: Site
  #   url: 'https://hellogov.squarespace.com'
```

```
  # - name: Site
  #   url: 'https://jobs-for-hope.herokuapp.com/'
```

```
  # - name: Site
  #   url: 'http://www.workfor.la/'
```

Again, you did the issue correctly! If you would make this change, I think the code will appear cleaner.   

Thank you for working on this issue!

**Comment by JanineSooThow** [comment]
Hello @ortegaa32 thank you so much for reviewing my changes :D

**Comment by JanineSooThow** [comment]
Hello @t-will-gillis thank you so much for the feedback! I really appreciate it! I made the changes on the branch '4923-comment-out-broken-site-links-for-workforla-hellogov-jobs-for-hope'. The changes definitely make the code look cleaner :D. I am not sure if I did the PR correctly , so please let me know if you can see my changes or not.

**Review by t-will-gillis — APPROVED** [review]
Hey @JanineSooThow Thanks so much for making the changes- Everything looks perfect!

**Pull request merged**
