### PR TITLE
Update Project Profile: HackforLA.org Website - Chris Menke added

### LINKED ISSUE #4512: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Chris Menke
  GitHub Handle: chrismenke45
  Role: Merge Team
  Slack Member ID: U04KVG05H3J
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by matthewmpan**
Fixes #4512

### What changes did you make and why did you make them ?

  - Added the name Chris Menke to leadership along with role, Slack/GitHub links, and picture
  - Retained existing trailing blank line at the end of leadership for consistency with the original code

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

BeforeChanges

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
AfterChanges

</details>

### CODE REVIEW

**Review by vanyanv — DISMISSED** [review]
Availability: M-F 10AM - 5PM
ETA 5/10/23

**Review by vanyanv — CHANGES_REQUESTED** [review]
Hi @matthewmpan, Merge branches look good, code changes are as mentioned in the issue. The code needs a little cleaning up, so delete line 87 and line 126. 
Great Job on your first issue!

**Comment by matthewmpan** [comment]
@vanyanv I will go ahead and make those changes now.

**Review by vanyanv — DISMISSED** [review]
Great Job making those changes @matthewmpan. Merge branches look good, code changes are as mentioned in the issue.

**Comment by blulady** [comment]
@amath95 & @mademarc if you guys could through down your availability so we could know when to expect your reviews?

**Comment by amath95** [comment]
Apologies for the delay 
Availability: 5/14 After 6
ETA: 5/14

**Comment by mademarc** [comment]
Review ETA:   5/11/2023
Availability: 7PM

**Review by mademarc — COMMENTED** [review]
Hey @matthewmpan  the adding of the name , role, slack, picture, github links are are added well on the element to make the page looking better so good job

**Comment by matthewmpan** [comment]
@vanyanv @mademarc @amath95 I merged updates from the gh-pages branch and resolved conflicts that arose since the PR was submitted. Can you please re-approve/approve the updates. Thanks.

**Comment by amath95** [comment]
Hey @matthewmpan, 

Just took a look at your issue, merging into the correct branch and properly executed the necessary changes. Code looks good! Overall good job reviewing your first issue! You're on your way keep it up!

**Review by vanyanv — APPROVED** [review]
Great Job fixing the conflict issues @matthewmpan.  I see now that your merge branches look good, code changes are as mentioned in the issue and there are no conflicts.

**Comment by mademarc** [comment]
Review ETA: 4/12/2023
Availability: 7:40PM

**Review by mademarc — APPROVED** [review]
Hey @matthewmpan Good job in  adding of the name , role, slack, picture, github links along with  the adding of the  elements to make the page looking better.

**Review by t-will-gillis — APPROVED** [review]
Hey @matthewmpan - Great job, and congrats on your first issue! The branches are correct, you linked the issue, your description is appropriate and you included before and after screenshots. Thanks for addressing the comment from @vanyanv .

**Comment by matthewmpan** [comment]
Hey @t-will-gillis Thanks for merging my pull request!

**Pull request merged**
