### PR TITLE
Improvements to hack night description; "meetups" in main nav

### PR DESCRIPTION
**Pull request by wesrowe**
I felt "Hack nights" verbiage was too prominent, given our many discussions about the word "hack" being a confusing description of what we do. So...
- I added more description (hopefully more welcoming) to the "Meetups" section at the top of the site
- I replaced "Hack nights" in the section heading for hack night info with "Meetups"
- (I incorrectly stated before that I changed the main nav - that's not in here.)

**Best make sure I edited the right file :)**

### CODE REVIEW

**Comment by ExperimentsInHonesty** [comment]
Let's talk more about this in person.  But in general, we shouldn't change the name of something unless we are changing it everywhere, otherwise there is an inconsistent user experience across our platforms (website, meetup.com, in person, facebook, twitter, etc.).  Let's do a survey of what our marketing message is across all platforms and then talk about what kind of user testing we are going to do on name changes.

**Comment by thekaveman** [comment]
This looks good and is ready for merge.

But we're HOLDing until the Travis + surge preview setup is complete (nearly there)... so we can have a nice simple test case ready to go, to ensure it works as expected.

**Comment by ExperimentsInHonesty** [comment]
This is refers to content that is no longer on the site, and some new pages will be pushed soon that address what it was trying to accomplish.  Thanks!

**Comment by ExperimentsInHonesty** [comment]
Screen Shot 2020-11-08 at 11 15 28 AM

**Pull request closed without merging**
