### PR TITLE
Update project profile5320

### LINKED ISSUE #5320: Update Project Profile: HackforLA.org Website (Josiah Odosu)
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [ ] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [ ] Add the following lines under Bonnie's section in the leadership variable:
```
  - name: Josiah Odosu
    role: Product Team
    links:
      slack: https://hackforla.slack.com/team/U052L9U44LB
      github: https://github.com/Josiah-O
    picture: https://avatars.githubusercontent.com/Josiah-O
```
- [ ] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by ndmoc**
Fixes #5320

### What changes did you make?
  - Updated Project Profile by adding Josiah Odosu
  -
  -

### Why did you make the changes (we will use this info to test)?
  - Task was to add Josiah Odosu's information under Bonnie's section
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/1/23
Availability: 1-3 PM everyday

**Comment by ortegaa32** [comment]
Hey @ndmoc. It appears as though there is no issue linked to this pull request. In the first line: Fixes #replace_this_text_with_the_issue_number, could you please add the issue number that this pull request is addressing. Thanks!

**Comment by ndmoc** [comment]
> Hey @ndmoc. It appears as though there is no issue linked to this pull request. In the first line: Fixes #replace_this_text_with_the_issue_number, could you please add the issue number that this pull request is addressing. Thanks!

Its been completed, thank you!

**Comment by meru-a** [comment]
Availability: In the evening & on weekends
Review ETA: EOD 09/01

**Review by meru-a — CHANGES_REQUESTED** [review]
Hi @ndmoc! Great work on your pull request! 
- The new branch is properly going into the correct branch gh-pages. ✅
- Original issue was properly linked and referenced. ✅
- The specified person is added ✅
- However, a file that is not specified in the issue was deleted `assets/images/join-us/donation-graphic.svg`. Please restore it and commit your changes!
- Another small note I would make about the pull request itself - it would be great if you could remove the empty bullet points from the first 2 sections of the pull request description.

After all the changes, please request the review again, I'll be glad to approve it!

**Comment by ortegaa32** [comment]
- Pull request contains correct branches
- Pull request links correct issue
Hey @ndmoc. Looking good so far! Just a couple of notes:
- I noticed in your screenshots that there were a few people added to the website besides Josiah Odosu. If I remember correctly, MJ Shelton was removed sometime this week. Also, when I try to test the changes on my computer I encounter an error when merging. Maybe you forgot to pull before making changes?
- I noticed you deleted a file that was not specified in this specific issue. Could you restore it and commit please.

After addressing these issues, please request another review and I'll be happy to approve!

**Review by ortegaa32 — CHANGES_REQUESTED** [review]
- Pull request contains correct branches
- Pull request links correct issue
Hey @ndmoc. Looking good so far! Just a couple of notes:
- I noticed in your screenshots that there were a few people added to the website besides Josiah Odosu. If I remember correctly, MJ Shelton was removed sometime this week. Also, when I try to test the changes on my computer I encounter an error when merging. Maybe you forgot to pull before making changes?
- I noticed you deleted a file that was not specified in this specific issue. Could you restore it and commit please.

After addressing these issues, please request another review and I'll be happy to approve!

**Comment by ndmoc** [comment]
> Hi @ndmoc! Great work on your pull request!
> 
> * The new branch is properly going into the correct branch gh-pages. ✅
> * Original issue was properly linked and referenced. ✅
> * The specified person is added ✅
> * However, a file that is not specified in the issue was deleted `assets/images/join-us/donation-graphic.svg`. Please restore it and commit your changes!
> * Another small note I would make about the pull request itself - it would be great if you could remove the empty bullet points from the first 2 sections of the pull request description.
> 
> After all the changes, please request the review again, I'll be glad to approve it!

Hi Meru,

Thank you for the feedback. 

Yeah, I was working on another first issue that asked me to remove the file. I can link it here while its pending review. https://github.com/hackforla/website/pull/5398

Please advise.

Thank you,
Andy

**Comment by adrianang** [comment]
Hey @ndmoc – going through PRs and noticed that you took up this issue while your first issue was awaiting to be merged.

Just a reminder, per [the message from the github-actions bot](https://github.com/hackforla/website/issues/5320#issuecomment-1701694830) from your self-assignment to the issue, developers may not take up another issue while waiting for their initial issue to be closed. Part of this is to ensure that developers take into account the feedback from their first PR code review and learn about our process and standards for merging for their subsequent issues. 

If you would like to contribute while waiting for an issue to get merged, you can help by completing other developers' pull requests! 😄

**Comment by t-will-gillis** [comment]
Hello @ndmoc You already have one open issue #4466. Per the Pre-work Checklist, we ask devs to focus on completing one issue at a time. Thank you.

**Pull request closed without merging**
