### PR TITLE
added site to 100 automations

### LINKED ISSUE #3440: Add 100 automations website to HackForLA.org
### Overview
As a user, I want to be able to find links to our web applications on the Hack for LA website so that I can easily access them. For this issue, let's add 100automations.org to the project card for 100 Automations.

### Action Items

- [x] Open _projects/100-automations.md in VS Code or your IDE, then under `links` add the following:
  ```
    - name: Site
      url: 'https://100automations.org/'
  ```
- [x] Using Docker to view the website locally, check the Site link you just added shows up under both the Links field and the Resources section on the [100 Automations webpage on the Hack for LA website](https://www.hackforla.org/projects/100-automations)

### Resources/Instructions
- [100 Automations webpage on the Hack for LA website](https://www.hackforla.org/projects/100-automations)
- [_projects/100-automations.md](https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md?plain=1)
- https://100automations.org/

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #3440

### What changes did you make and why did you make them ?

  - added link to 100automations.org to the project card for 100 Automations

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

beforesite
linksecbefore
</details>

<details>

<summary>Visuals after changes are applied</summary>

</details>

aftersite
linksection

### CODE REVIEW

**Review by blulady — APPROVED** [review]
The pull request is coming from the correct branch [arpitapandya:add-100-automations-3440](https://github.com/arpitapandya/website/tree/add-100-automations-3440) and going into the correct branch [hackforla:gh-pages](https://github.com/hackforla/website). There is a linked issue, it is the correct issue, and that issue is properly address in the PR by adding 
- name: Site
url: 'https://100automations.org/'

The changes look good when I throw it up in the local repo and the link works.
No other files were changed.
Good Job @arpitapandya!!!
I am going to give it until the end of the day for someone to review and then I'll merge it.

**Review by Zak234 — CHANGES_REQUESTED** [review]
Looks good but on the homepage it still does not display the site
Screen Shot 2022-08-04 at 4 02 30 PM

**Comment by Zak234** [comment]
This is fairly odd. I checked the other program cards that had sites linked and all of them look almost exactly like yours and are showing up correctly.

**Comment by blulady** [comment]
> This is fairly odd. I checked the other program cards that had sites linked and all of them look almost exactly like yours and are showing up correctly.
It says "check the Site link you just added shows up under both the Links field and the Resources section on the [100 Automations webpage on the Hack for LA website](https://www.hackforla.org/projects/100-automations)"
It doesn't mention the homepage in the issue. Maybe that could be a separate issue? I think it is located in a different place...

**Review by Zak234 — APPROVED** [review]
It looks like the error we are seeing is outside the scope of your issue. Everything else looks fine so good work!

**Comment by arpitapandya** [comment]
> It looks like the error we are seeing is outside the scope of your issue. Everything else looks fine so good work!

Yeah, I wonder why it's not showing up! Tried to figure out but can't catch the error. Though, I am unsure if its a separate issue but the changes are correct as per the issue, or may be something different issue because I compared the code with `311 data project card`.

**Comment by Zak234** [comment]
Never mind, checked website after merge and site is appearing fine. Don't know what the problem was when I ran it on Docker but everything seems to be working fine.

**Comment by 7kram** [comment]
@ExperimentsInHonesty  **Onboarding Flow** milestone

**Pull request merged**
