### PR TITLE
Update hfla-donate.gif to match with CodeForAmerica's donation box

### LINKED ISSUE #1824: Create new donation gif
### Overview
We need to update the donation gif on the bottom of both the Join and About pages because the current gif is outdated and no longer consistent with the Code for America donate box, so it may confuse users and discourage them from donating.

<details >
<summary>current gif appearance in Join page (blue)</summary>

Screen Shot 2021-06-23 at 11 47 38 PM
</details>

<details>
<summary>How gif should look from Code for America site (purple)</summary>

Screen Shot 2021-06-23 at 11 47 55 PM

</details>

### Action Items
- [x] Create a new gif following the same exact actions/flow as the current gif on the bottom of the [Join page](https://www.hackforla.org/join)
- [x] Get approval from product/design for the new gif
- [x] Replace the old gif with the new one in bottom of [Join](https://www.hackforla.org/join) and [About](https://www.hackforla.org/about/) pages

### Resources/Instructions
[Join page](https://www.hackforla.org/join)
[About page](https://www.hackforla.org/about/)
[Code for America donate page](https://www.codeforamerica.org/donate/)

### PR DESCRIPTION
**Pull request by Aveline-art**
Fixes #1824

### What changes did you make and why did you make them ?

  - Replaced the outdated [donation gif ](https://www.hackforla.org/assets/images/about/hfla-donate.gif) on the bottom of the [Join](https://www.hackforla.org/join) and [About](https://www.hackforla.org/about/) pages with a new gif.
  - New gif was recorded in Firefox, and contains slightly modified dimensions. (Old gif: 456 x 724 pixels; New gif: 472 x 712 pixels)
  - Let me know if resizing is preferable!
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>New gif</summary>

</details>

<details>
<summary>Before: iphone6/7/8 plus, resolution: 414x736</summary>

</details>

<details>
<summary>After: iphone6/7/8 plus, resolution: 414x736</summary>

</details>

<details>
<summary>Before: laptop, resolution: 1280x950</summary>

</details>

<details>
<summary>After: laptop, resolution: 1280x950</summary>

</details>

### CODE REVIEW

**Review by erikaBell — COMMENTED** [review]
Looks good on the site!

I'm seeing in the code that the new gif was added under ` assets/images/about/hfla-donate.gif` while the gif itself is used on the "/join" page, and that the original donation gif still lives under `assets/images/join-us/` 

Wondering if we should remove the old gif entirely, plus have the new gif live under "/join-us" assests, opposed to "/about" assests?

**Comment by averdin2** [comment]
I agree with @erikaBell that the old donation-form-img.png file in the join-us folder should also be removed since it is not being used. As to where the new gif file should go, I am not quite sure where the file should go. Either the about or join-us folders seem fine, but perhaps the gif should be put in another folder for asset files used across other pages? Are there any other instances of asset files that are on multiple pages that we can go off of?

**Comment by Aveline-art** [comment]
Good catch, @averdin2 and @erikaBell ! I have cleaned up the folder and the classes so that they are a little more intuitive.

About moving to another folder: I am unsure what is the best way to go about this. The asset sub-directories are separated by location, and the donation gif seems to be the only reused item in assets (besides the program logos, and generic outside logos like meetup, GitHub, etc.).

**Comment by averdin2** [comment]
@Aveline-art I made an issue #1900 to deal with possible inconsistent files in the assets folder. Maybe we can leave the file as-is for this PR, and make a comment on that issue to look over if the about folder is the best place for this file?

**Review by averdin2 — APPROVED** [review]
@Aveline-art Like I mentioned earlier, I think we can leave the new hfla-donate.gif in the about folder and we can make a comment on that other issue to decide if it belongs there. Otherwise, everything looks good to me.

**Review by erikaBell — APPROVED** [review]
lgtm ~

**Pull request merged**
