### PR TITLE
Changed alt text for card image in access-the-data.md #3092

### LINKED ISSUE #3092: Change alt text for card image in access the data md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the access the data project card image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/access-the-data.md`, change [line 109](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/access-the-data.md?plain=1#L109) for the alt text:

from
```
card-image-alt: access the data project card
```
to
```
card-image-alt: 
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/access-the-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/access-the-data.md?plain=1#L109

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by lilyarj**
Fixes #3092 

### What changes did you make and why did you make them ?

  - Changed line 109 from card-image-alt: access the data project card  to card-image-alt:
  - I made this change for the sake of simplicity, and to make the file easier to read.
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No changes of the website were made

### CODE REVIEW

**Comment by blulady** [comment]
Availability: 1 hour
ETA: 6/26/22

**Review by Zak234 — APPROVED** [review]
Everything looks good!

**Comment by Zak234** [comment]
Availability: Anytime, missing from Jun. 27th-July 1st

**Comment by clayton1111** [comment]
Availability: 1 hour
ETA: end of day

**Review by clayton1111 — APPROVED** [review]
Looks great!

**Review by blulady — APPROVED** [review]
The branches are good, going from [lilyarj:change-alt-text-3092](https://github.com/lilyarj/website/tree/change-alt-text-3092) to [hackforla:gh-pages](https://github.com/hackforla/website). There is a linked issue and it is the correct issue, line 108 was corrected from `card-image-alt: access the data project card` to `card-image-alt:` and it looks clean in file. There are no visual changes but when I pulled the repo into my local, the website work and everything looked good.

**Comment by blulady** [comment]
> The branches are good, going from [lilyarj:change-alt-text-3092](https://github.com/lilyarj/website/tree/change-alt-text-3092) to [hackforla:gh-pages](https://github.com/hackforla/website). There is a linked issue and it is the correct issue, line 108 was corrected from `card-image-alt: access the data project card` to `card-image-alt:` and it looks clean in file. There are no visual changes but when I pulled the repo into my local, the website work and everything looked good.

https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Step0

**Pull request merged**
