### PR TITLE
Removed unused alt-hero field from new-schools-today.md

### LINKED ISSUE #3206: Remove unused `alt-hero` field from new-schools-today.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`.   

### Action Items
- [x] For the file `_projects/new-schools-today.md`, remove line 8 for the alt-hero
```
alt-hero: 'Team students and teachers working during a meeting.'
```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/new-schools-today.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/_projects/new-schools-today.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by PeterSYoo**
Fixes #3206

### What changes did you make and why did you make them ?

  - Removed `alt-hero` in `_projects/new-schools-today.md`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: 12 PM 10/29/22
Availability: 12 - 2 PM Saturday

**Review by MattPereira — APPROVED** [review]
Nice job @PeterSYoo ! :+1: 

You removed the unused code from the correct file which will allow for faster website loading times and easier to understand code. Keep up the good work!

**Comment by esantiano** [comment]
Review ETA: 10/29/22
Availability: 3 - 5 PM Saturday

**Review by esantiano — APPROVED** [review]
Hey Peter, looks like a simple code change which passes all the checks, follows the ABC's and makes the code more readable. Great job!

**Pull request merged**
