### PR TITLE
Add aria label footer 4303

### LINKED ISSUE #4303: Add aria-label to footer nav element
### Overview

The ARIA specification states that if a page includes more than one navigation landmark, each should have a unique label.  In this issue we will label the footer navigation element to identify it as the secondary navigation, distinguishing it from the primary navigation element in the header.  

### Action Items

- [x] The html for the footer navigation can be found in _includes/footer.html
- [x] Change `<nav class="footer-nav">`
  to:
  `<nav class="footer-nav" aria-label="Secondary">`

### Resources/Instructions

- [Footer Include](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html)
- [ARIA Authoring Practices Guide - Landmark Regions](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/)
- ARIA 1.2 Specification: [navigation landmark](https://www.w3.org/TR/wai-aria-1.2/#navigation)

### PR DESCRIPTION
**Pull request by amath95**
Fixes #4303

### What changes did you make and why did you make them ?

  -Add aria-label to footer nav element

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hi @amath95 - FYI in the PR Description above, your issue is not linking correctly- likely because it is missing the '#'. Could you edit it to say 'Fixes #4303' ? Thanks!

**Comment by amath95** [comment]
Hey @t-will-gillis, I just updated! Thank you for catching that.

**Comment by t-will-gillis** [comment]
Hi @amath95 - I was looking at the original issue #4303. If you notice the screenshot below, this issue is in the 'New Issue Approval' column and not 'Prioritized Backlog.' Please see the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) documents- you should only assign yourself to issues from the 'Prioritized Backlog' column. Then once you select an issue from 'Prioritized Backlog', you will need to move the issue to 'In progress (actively working).'

Screenshot 2023-04-01 205043

Closing this PR since the issue being fixed was still in the 'New Issue Approval' column and not ready to be worked on.

**Comment by amath95** [comment]
Hi @t-will-gillis, thank you for catching that, I did a search for a “good second issue” on the issues tab. I must have missed that it was not in backlog. I will be more attentive. Thank you for your feedback.

**Pull request closed without merging**
