### PR TITLE
Added The School of law logo issue 3025

### LINKED ISSUE #3025: Partners: Change the image for Golden Gate University School of Law
### Overview
As a developer, I want the logos for our partners to be up to date so that 
- we maintain professionalism on our website and 
- are consistent with the current logos the partners use for themselves. 

For this issue, we will replace an old partner logo image with a new one.
 
### Action Items
- [x] Remove `ggu-school-of-law.png` from `assets/images/partners` directory
- [x] For the new image:
  - [x] Download the new image from https://law.ggu.edu/media/shared/images/logos/2021/law-stack.png
  - [x] Rename the new image to `ggu-school-of-law`
  - [x] Add the new image to `assets/images/partners` directory
- [x] For `Golden Gate University School of Law` in [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml), make sure the link for the image field points to the new image you added to `assets/images/partners` directory
- [x] In the [Partners section on the About Us page](https://www.hackforla.org/about/#partners), check the image looks good on mobile, tablet, and desktop views using developer tools

### Resources/Instructions
- Image to remove: [ggu-school-of-law.png](https://github.com/hackforla/website/blob/gh-pages/assets/images/partners/ggu-school-of-law.png)
- Link to new image: https://law.ggu.edu/media/shared/images/logos/2021/law-stack.png
- [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
- [Partners section on the About Us page](https://www.hackforla.org/about/#partners)

### PR DESCRIPTION
**Pull request by KazushiR**
Fixes #3025

### What changes did you make and why did you make them ?

Deleted the GGU-School-of-Law.png file and added the updated Logo in the partners page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
@JessicaLucindaCheng I have created a PR for my issue. Is this PR not correctly linked to the original issue?

**Comment by Carlos-A-P** [comment]
@KazushiR make sure to add your issue number by replacing "Fixes #replace_this_text_with_the_issue_number" with your issue number. For example "Fixes #0000"

**Comment by harshitasao** [comment]
Availability : Flexible
ETA : 08/04/2022

**Comment by Carlos-A-P** [comment]
Availability: 04/09/2022
ETA: 1 hr

**Review by harshitasao — APPROVED** [review]
@KazushiR  Great job! The changes look good to me.

**Comment by answebdev** [comment]
Review ETA: 4/8/2022 (end of day)
Availability: 1 hour

**Comment by KazushiR** [comment]
> @KazushiR  Great job! The changes look good to me.  

Hello. Apologies if I'm not familiar about this but what does it mean by review availability 1 hour?

**Review by answebdev — APPROVED** [review]
@KazushiR Thank you for submitting your PR. I was able to see that you removed the old image from the directory and added the new one. I was also able to see the new image in the Partners section on the About Us page, and it also looks good on mobile, tablet, and desktop views. Great job!

**Pull request merged**
