### PR TITLE
Added logic to check for the specified main HFLA website repository before commencing scheduling workflow.

### LINKED ISSUE #7500: Refactor "Schedule Friday" workflow trigger to run only on HfLA repo
### Overview
Currently, the "Schedule Friday" workflow will run from anyone's repo, which can be a nuisance and cause confusion. We need to edit the workflow so that it only runs from the main HfLA repo.

### Action Items
- [x] In [schedule-fr-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml) add conditional statement similar to `schedule-daily-1100.yml` and `schedule-monthly.yml` to specify that workflow should only run from the main repo. After the line `runs-on: ubuntu-latest` **_insert_** the new line:
  ```  
  if: github.repository == 'hackforla/website'
  ```  

### Resources/Instructions
Although this is an edit to a GHA, testing is not required.

### PR DESCRIPTION
**Pull request by srinipandiyan**
Fixes #7500

### What changes did you make?
  
  - Added an if-conditional statement to `schedule-fri-0700.yml` which commences the workflow after checking for the specified main hackforla/website repository.

### Why did you make the changes (we will use this info to test)?
  
  - Previously the scheduling workflow could be run from any individual user's repository, which could be a nuisance or cause confusion.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
- No visual changes to the website

### CODE REVIEW

**Review by kabszac — COMMENTED** [review]
Hi @srinipandiyan kindly move the status from prioritized backlog to In progress on the issue page.

**Comment by kabszac** [comment]
Availability: 5-7pm, Mon-Fri
ETA: EOD Saturday, Oct 26

**Comment by srinipandiyan** [comment]
@kabszac done!

**Review by codyyjxn — APPROVED** [review]
@srinipandiyan Thank you for taking on this issue. 

- You made the correct changes
- The description is very detailed and concise 
- The issue is linked correctly 

Keep up the good work!

**Comment by siyunfeng** [comment]
Review ETA: 10/25/2024
Availability: 6-10 PM Weekdays (EDT)

**Review by siyunfeng — APPROVED** [review]
Nice job, @srinipandiyan !

- Availability and ETA are posted in the original issue
- Changes are accurate
- Branch is correct, linked issue is included

Thank you for working on this issue!

**Review by kabszac — APPROVED** [review]
@srinipandiyan Great Job! You made the correct changes
Keep up the good work!

**Pull request merged**
