### PR TITLE
Move program-areas directory and refactor program-areas.html

### LINKED ISSUE #6323: Move program-areas directory and refactor program-areas.html
### Overview
We need to move the program-areas directory and refactor program-areas.html so that 
- we can use the contents in the files in the program-areas directory for individual program area pages in the future, and 
- the Program Areas page [^1] doesn't break when the program-areas directory is moved

### Action Items
- [x] Find the `program-areas` directory under `_data/internal`
- [x] Move the `program-areas` directory so it is outside of the `_data` directory
- [x] Rename the `program-areas` directory to `_program-areas`
- [x] In `_config.yml`, find the `collections` variable. For more info on collections, see _Collections_ [^2] in the _Resources/Instructions_ section.
  - [x] Add the following:
    ```
      program-areas:
        output: false
    ```
- [x] In `pages/program-areas.html`, refactor the code so that it works to pull information from the files in the `_program-areas` directory
- [x] Using Docker, check your changes on the Program Areas page [^1] in desktop, tablet, and mobile views against the live page on the website
- [x] Once your pull request is merged, go to #3328 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #3328 to the **New Issue Approval** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Program Areas](https://www.hackforla.org/program-areas)
[^2]: [Collections](https://jekyllrb.com/docs/collections/)

### PR DESCRIPTION
**Pull request by luisitocanlas**
Fixes #6323 

### What changes did you make?
  - Moved `program-areas` directory so it is outside of the `_data` directory
  - Renamed `program-areas` directory to `_program-areas`
  - Added the following in `_config.yml`, under the `collections` variable:
      ```
      program-areas:
          output: false
      ```
  - Refactor code in `pages/program-areas.html` so that it works to pull information from the files in the `_program-areas` directory
     - removed `{% if program_areas[1].size > 0 %}` at line 21 and `{% endif %}` at line 63
     - refactored `program_areas[1]` into `program_areas`

### Why did you make the changes (we will use this info to test)?
  - Per issue:
      - We can use the contents in the files in the program-areas directory for individual program area pages in the future
      - the Program Areas page doesn't break when the program-areas directory is moved
  - `{% if program_areas[1].size > 0 %}` at line 21, `{% endif %}` at line 63, and `program_areas[1]` were giving me this error: 
      ```
      Liquid Exception: 1 is not a symbol nor a string in pages/program-areas.html
      ```
      - Before moving the `program-areas` directory, the code with `program_areas[1]` was working perfectly. Once I moved the `program-areas` directory outside of the `_data` directory, that's when I started encountering the error

### CODE REVIEW

**Comment by Anahisv23** [comment]
Availability: 2/29 - 3/1, 10AM - 5PM
Review ETA: Thursday 2/29 5PM

**Comment by Anahisv23** [comment]
Hey @luisitocanlas thanks for taking up this issue! 

Here's what you did well
• Into and commit branches are correct 
• There is a linked issue 
• Moved the program-areas directory outside of the data directory 
• Renamed the program-areas directory to _program-areas 
• Added the appropriate code to _config.yml file 
• Refactored the pages/program-areas.html code to retrieve data from the _program-areas directory
• The program areas website page shows the correct data 

Overall nice work!

**Review by Anahisv23 — DISMISSED** [review]

**Review by freaky4wrld — DISMISSED** [review]
@luisitocanlas thanks for taking up the issue, the branches looks fine and linked issue is correct too. The changes you made are great as well and docker-testing shows no error.

Thanks for mentioning the error, before merging I would like @t-will-gillis to look into the error, as everything looks fine to me

PR approved

**Comment by t-will-gillis** [comment]
Hey @luisitocanlas - tl;dr Thanks for mentioning the error, and I agree with your changes and with @freaky4wrld and @Anahisv23- looks great!

Otherwise, I am still learning about Jekyll but I believe this is a difference in [Collections vs Data Files](https://gist.github.com/akibrhast/31c7bb723d80e9efe3d28f619ef0798d). 

BTW this is outside of the scope of the issue, but I think it would help clarity by removing the blank lines at lines 60 and 26 and indenting the `for`s and `if`s as shown. Thoughts?  

Screenshot 2024-03-03 114550

**Comment by luisitocanlas** [comment]
Hi @Anahisv23 , @freaky4wrld , @t-will-gillis,

I'm also pretty new to Jekyll and I need to read more about that. I also incorporated the changes you recommended, it will definitely help on clarity.

Thank you for all of your feedback!

**Review by t-will-gillis — APPROVED** [review]
Hey @luisitocanlas - Thanks for making the edits! 

I will go ahead and merge since @Anahisv23 and @freaky4wrld have already approved this

**Pull request merged**
