### PR TITLE
Change Toolkit SCSS (Part 3)

### LINKED ISSUE #960: Standardize Toolkit Page with CSS Fixes
### Overview
We need to standardize the CSS styling of the Toolkit Page so that it will be more consistent with the rest of the HfLA website.

### Action Items
Front-End Development
- [ ] Review the HfLA site architecture
- [ ] Review the CSS fixes on the Toolkit page file on Figma
- [ ] Implement the CSS fixes on the Toolkit page's .scss file 

### Resources/Instructions
[Toolkit page Figma file (edits to the right of the screen in pink rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5892%3A0)

### PR DESCRIPTION
**Pull request by Treidexy**
Fixed #960

### CODE REVIEW

**Comment by jbubar** [comment]
I resolved the conflict and looked over the code.
looks good to me! 
Just noticed one thing...

the figma has the header with the elements in a row and in desktop view.
Screen Shot 2021-02-07 at 12 33 52 AM



I vote that we merge this, and you can create another pr to fix that :))

**Comment by jbubar** [comment]
screencapture-localhost-4000-toolkit-2021-02-07-00_31_25

**Review by daniellex0 — CHANGES_REQUESTED** [review]
Hi @TeddyTelanoff I am SO sorry about my delayed review, it was a hectic week- the page is getting close, thank you for making these edits! 

The header does need work with the alignment before this PR can be merged (since this page is live and attached to our main nav), so FYI I've included more notes in the [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967) on the Toolkit file (to the right of the previous notes) that will hopefully help make the necessary edits. 

After that there might still be a few more adjustments necessary for mobile FYI. 

Let me know if you have any questions! Sorry again about the delay!

**Comment by Treidexy** [comment]
I worked with Josh Bubar on the sccs for the toolkit page; we made a few changes to what was originally planned. We made some design decisions about the margins in the mobile view and we set the breakpoint at 850px instead of 479px.

Please let me know what changes I should make.

**Comment by daniellex0** [comment]
@TeddyTelanoff This page looks fantastic, great job!!! 🙌

_[ I deleted this part - sorry my google chrome was acting up and I thought the mobile version of the header had issues, but I now see it's all good]_

**Review by daniellex0 — APPROVED** [review]

**Pull request merged**
