### PR TITLE
Edited CONTRIBUTING.md file

### LINKED ISSUE #2896: Add weekly meeting requirements to CONTRIBUTING.md
### Overview
As developers, we want to make sure the contributor expectations in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) are clear. For this issue, we will be adding weekly meeting requirements to [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.

### Action Items
- [ ] Review the Table of Contents in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.
- [ ] Analyze which section would be the best to add the following weekly meeting requirements: 
```
All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis.
```
```
Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
```
- [ ] Consider adding the above requirement to [Section 2.1](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) vs making a new section 
- [ ] Add the weekly meeting requirements mentioned above to the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file
- [ ] Make sure you can see the changes in your own repo.

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md): file where changes need to be made

### PR DESCRIPTION
**Pull request by harshitasao**
Fixes #2896
 
### What changes did you make and why did you make them ?

  - In [Section 2.1](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) added weekly meeting requirements.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by blulady** [comment]
Review ETA: 4:30 PM 3/12/22
Availability: 12-6 PM Monday

**Review by blulady — APPROVED** [review]
The pull request is done with the correct branch. The issue is linked with the correct link. The source code has been appropriately changed. The screenshots accurately reflected the code changes.
Good Job!!

**Comment by blulady** [comment]
I am uncertain as to where I would view these changes in browser.
Please Advise

**Comment by scarter31191** [comment]
Availability: 2 hrs
Review ETA: March 16, 2022

**Review by scarter31191 — APPROVED** [review]
good work harshitasao!

**Pull request merged**
