### PR TITLE
updates cspell.json casing

### LINKED ISSUE #5684: Update cspell.json with false positive term "Collabathon"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to update the Code Spell Checker configuration file with false positive terms so that they are no longer marked as errors. 

### Action Items
- [x] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file `cspell.json`
- [x] Replace the line
```
  "words": [
```
with
```
  "words": [
      "Collabathon",
```
- [x] Save `cspell.json` and then test the change by opening `'_includes/about-page/about-card-sustainability.html` and confirming that no Code Spell Checker errors/messages are displayed.  
- [x] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- This issue was created as part of #5312

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #5684

### What changes did you make?
  - Removed a comma after undebate in the cspell.json
  - Used a capital letter for collabathon in the cspell.json

### Why did you make the changes (we will use this info to test)?
  - To update the casing for collabathon to ensure there are no spelling errors in VSC after adding extension Spell Checker

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 - No changes required

### CODE REVIEW

**Comment by sornekian** [comment]
I didn't add screenshots because docker wasn't required

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 12/17

**Comment by raviteja4117** [comment]
Availability:  3-10pm EST
ETA: EOD 12/18

**Review by freaky4wrld — COMMENTED** [review]
Hey @sornekian thanks for taking up the issue, the changes you have made looks fine, the to/from branch looks nice, visual changes are not needed, so you can mention `No changes required`  and remove `Visual changes before/after` the linked issue is mentioned as well. Once you make those changes I'll approve the PR..... 

Just ping me once you make those changes.

**Review by freaky4wrld — APPROVED** [review]
PR approved.....

**Review by raviteja4117 — APPROVED** [review]
Good job @sornekian  on this issue. You setup the branches correctly, made the correct code change, and prepared a well-formed and descriptive pull request.

**Pull request merged**
