### PR TITLE
Removed the alt text for the 311 project card image

### LINKED ISSUE #3090: Change alt text for card image in 311 data md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the 311 data project card image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/311-data.md`, change [line 72](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/311-data.md?plain=1#L72) for the alt text:

from
```
card-image-alt: 311 project card
```
to
```
card-image-alt: 
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/311-data.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/311-data.md?plain=1#L72

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by mchavezm**
Fixes #3090

### What changes did you make and why did you make them ?

  - Removed alt text

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
Alt text highlighted

Sustainable Development Goal

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
O localhost4000citizen-engagement

</details>

### CODE REVIEW

**Comment by blulady** [comment]
Availability: 1 hour
ETA: 6/15

**Comment by alan-zambrano** [comment]
Availability 2 Hours
ETA: 6/16

**Review by alan-zambrano — APPROVED** [review]
Changes look great! I see you've removed the alt text as dictated by the original issue. For future reference, however, I would suggest omitting the attached image since there are no visual changes. I will approve the merge since this does not conflict with the code, but aside from that, great job!

**Comment by answebdev** [comment]
Availability: 1 hour
ETA: 6/15/2022 (end of day)

**Review by answebdev — APPROVED** [review]
@mchavezm Thank you for submitting your PR. For this issue, line 72 for the alt text for the file `_projects/311-data.md` needed to be changed from `card-image-alt: 311 project card` to `card-image-alt: `, which I can see that you did. Great job!

**Pull request merged**
