### PR TITLE
Design System Audit: Swap colors with color variables (RED)

### LINKED ISSUE #2112: Design System Audit: Swap colors with color variables: Reds
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the red colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (reds)
- [x] Identify an instance of the hard-coded color 
   - [x] Check to see what that code impacts on the site.
   - [x] Switch out the hard-coded color with the appropriate variable
   - [x] Check to see if it broke anything. Some changes might break the website
   - [x] If the color doesn't stay the same or you get any other kind of error, you can try using the classes from this file website/_sass/elements/_color-styles.scss
     - [x] Add a comment to this issue with any instances of needing to use the styles instead of colors.scss
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
  - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [ ] Release dependency on #2114, if conditions are met

### Resources/Instructions
- https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L5-L11

<details>
  <summary>Click here to see a visual example of search/replace for color variables within VS code</summary>
  <br>
  Search: hex color<br>
  Replace: color variable<br>
  files to include: ./<br>
  files to exclude: *.svg, _site, _colors.scss<br>
  Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  Click `Ok` to confirm replace
  
</details>

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similiar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)
- Information about color CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/color

### PR DESCRIPTION
**Pull request by clayton1111**
Fixes #2112 

### What changes did you make and why did you make them ?

  - Replaced hard-coded red values in SCSS files with the corresponding color variables.
  - Did not delete any colors since all appear in other files. (firebrick, mediumvioletred, deeppink, and salmon all appear in  [/_sass/elements/_color-styles.scss ](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss)
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

image

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 2 hours
ETA: 7/7

**Comment by BeckettOBrien** [comment]
Availability: 2 Hours
ETA: EOD 7/7/22

**Review by Wny-Duong — APPROVED** [review]
Looked through the 404, about, project-meetings, getting-started, the survey-reporting-dashboard guide, and three different project pages. They look the same before and after changes. Good work.

**Comment by Wny-Duong** [comment]
Just leaving a note though, that there is the issue with multiple unrelated changes showing up in the commit history. This was discussed in previous [pull request.](https://github.com/hackforla/website/pull/3301)

@clayton1111 Have you been updating the topic branch to account for changes from the main hackforla/website gh-pages branch per the [contributing guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream)? I don't think it should be too much of an issue with this PR but I'll check just to make sure. It's just something to keep in mind for the future.

**Review by BeckettOBrien — APPROVED** [review]
All the changes correctly replace all hardcoded values with the correct variables and the site looks the same. Good job!

**Comment by clayton1111** [comment]
@Wny-Duong I have been updating the topic branch so I am confused to why there are other commits. If I notice it is still an issue on my next pull-request, I will try the solution outlined in the previous [pull request](https://github.com/hackforla/website/pull/3301)

**Pull request merged**
