### PR TITLE
edit content field and remove type field from group.yml credits file

### LINKED ISSUE #2833: Edit content field and remove type field from group.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/group.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/group.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L11

### PR DESCRIPTION
**Pull request by vincentdang**
Fixes #2833

I changed line 4 from content: icon to content-type: images and deleted line 11 to remove redundancy.

### CODE REVIEW

**Comment by janice87** [comment]
Review ETA: 9 PM 3/25/22
Availability: 5-8 PM Friday, Saturday

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. It follows the ABCs and the issue is addressed and updated. The change does not affect the physical appearance of the website. The only suggestion I have is to have the title of the PR be more descriptive and related to the issue, otherwise everything looks good!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @vincentdang - great job on this issue! The branches from and to are correct, you linked the issue correctly, and you made the changes requested by the issue. As @janice87 mentioned, it would be helpful if you could edit the title of the issue to be more descriptive of the issue. This helps us when looking through the pull requests, etc. Something simple would work such as 'Update and edit to group.yml' . It also would be helpful to add more to the description. You can usually look at the original issue's Overview section to get an idea, for example '...edited the content field and removed the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.'

Thanks for you work on this!

**Comment by ExperimentsInHonesty** [comment]
@vincentdang Please change the name of the PR to `edit content field and remove type field from group.yml credits file` so we can accept it.

**Comment by vincentdang** [comment]
> @vincentdang Please change the name of the PR to `edit content field and remove type field from group.yml credits file` so we can accept it.

hi thanks for your feedback. I have done what is requested.

**Review by t-will-gillis — APPROVED** [review]
Looks good! Thanks

**Pull request merged**
