### PR TITLE
removed slash from <img../> --> <img..>

### LINKED ISSUE #4419: img Tag Refactor: Getting Started page - `step-img-icon clipboard.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/clipboard.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/clipboard.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by JpadillaCoding**
Fixes #4419 

### What changes did you make and why did you make them ?

  - Removed end slash on img tag  so that the codebase is consistent with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Refrac on code. No visual changes.

### CODE REVIEW

**Comment by ldietz08** [comment]
Availability: 05/28 10am-2pm
ETA: 05/28

**Comment by LOSjr4** [comment]
Availability: weekdays 9AM-1PM
ETA: 5/29 1PM

**Review by ldietz08 — APPROVED** [review]
Hi Jose! I see that the pull request is done in the correct branch and you linked to the issue. The trailing slash in the image tag was removed from the codebase. Well done.

**Review by Mayank2808sharma — APPROVED** [review]
Hello @JpadillaCoding 

I went through the issue and the changes you made. 
LGTM

**Review by LOSjr4 — APPROVED** [review]
@JpadillaCoding removed the correct space and slash from line 207 as described in the issue. He left a fair description of the changes he made and reason why. Good work on this first issue @JpadillaCoding !

**Review by chrismenke45 — APPROVED** [review]
Great work!

**Pull request merged**
