### PR TITLE
Remove alt-hero field from civic-opportunity-project.md #2923

### LINKED ISSUE #2923: Remove unused `alt-hero` field from civic-opportunity-project.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/civic-opportunity-project.md`, remove line 8 for the alt-hero
```
alt-hero: 'Wireframing and designing process for Civic Opportunity Project, there are hands pointing to a tablet and papers of the low fidelity prototyping.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/civic-opportunity-project.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/civic-opportunity-project.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by mmogri**
Fixes #2923

### What changes did you make and why did you make them ?

  - Removed line 8 which was "alt-hero: 'Wireframing and designing process for Civic Opportunity Project, there are hands pointing to a tablet and papers of the low fidelity prototyping.'"
  - alt-hero is the alt text associated with image-hero, but alt-hero is not used anywhere and is therefore being deleted.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes were made, no pictures are needed.

### CODE REVIEW

**Review by blulady — APPROVED** [review]
The pull request is from the correct branch, there is a correct linked issue that this pull request addresses. Namely deleting line 8 with the alt-hero. The pr deletes the appropriate line. There are no changes in browser so no pictures are needed although I know they like to pr's to state that there were no visual changes so no pictures are necessary. New code looks clean.
Good Job! Looks like you are good to go.

**Comment by trishajjohnson** [comment]
ETA: EOD 5/26/22
Availability: 1hr

**Review by trishajjohnson — APPROVED** [review]
Hey @mmogri !  Took a look at your PR.  Everything looks how it should.  It's from the correct branch, you included the correct issue number, since the issue involved code and had no visible changes on the frontend, you were not required to add any images to your PR; however, I tend to agree with @blulady .  For thoroughness, I would recommend, at least in future, mentioning in your PR that there were no visible changes and thus, providing images was not necessary.  That way it doesn't look like you overlooked it or made a mistake and images aren't loading properly for some reason.  Everything seems to appear correct on the frontend, website still working properly.  You fulfilled the requirements of the issue and removed the alt-hero from line 8 in file _projects/civic-opportunity-project.md. I think you're good to go!

**Review by Sparky-code — CHANGES_REQUESTED** [review]
@mmogri Look great! Thank you for including both what you did and why.
Everything looks ready to be committed but for clarity (and as others have mentioned), can you remove the text and images below the visual changes header and replace that with 'no visual changes made'. Thank you!

**Comment by mmogri** [comment]
@Sparky-code text and image in section for screenshots were removed and text was added to clarify that no visual changes were made. Thank you

**Review by Sparky-code — APPROVED** [review]
Thanks for updating the issue comments, looks great!

**Pull request merged**
