### PR TITLE
Deleted the file assets/images/join-us/donation-graphic.svg

### LINKED ISSUE #4466: Delete unused donation circle graphic from join-us image folder
### Dependency

- [x] #4263 
- [x] #4439
- [x] #4544

### Overview
We want to delete the unused `donation-graphic.svg` so that we keep the file system clean and avoid confusion.

### Details
The donation circle graphic previously used on the Join Us page has been replaced with HTML/CSS for improved readability and accessibility.

### Action Items
- [x] Delete the file `assets/images/join-us/donation-graphic.svg`
- [x] Use git to add and commit the change (deletion)
- [x] Use docker to confirm that the Join Us [local page](http://localhost:4000/join) matches the [live webpage](https://hackforla.org)

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- [unused donation graphic](https://github.com/hackforla/website/blob/gh-pages/assets/images/join-us/donation-graphic.svg)
- This issue is part of Epic #4492

### PR DESCRIPTION
**Pull request by ndmoc**
Fixes #4466

### What changes did you make?
  - I removed the donation-graphic.svg file from the assets directory

### Why did you make the changes (we will use this info to test)?
  - Task: Delete the file assets/images/join-us/donation-graphic.svg because it was unused
  - Deleting the file would ensure that there wouldn't be any confusion on unused images and clean up the folder with unnecessary files

### CODE REVIEW

**Comment by antho-zng** [comment]
Availability: M-F 9-5
ETA: 9/1

**Review by antho-zng — APPROVED** [review]
Looks good! Join Us page on local page looks the same as on the live webpage. Thanks!

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @ndmoc — the branching is set up correctly, the corresponding issue was linked, and the requested change of removing the `donation-graphic.svg` file was made without affecting the Join Us page, but I have two small requests for you to edit and update your PR.

- As you had noted within the `<details>` tag, the image was unused and did not result in visual changes; since there are no visual changes, can you delete the entire Screenshots section in your PR? This will help keep our codebase documentation clean and it's a bit more obvious at first glance that there are no visual changes from this PR when this is deleted.
- The Why of your PR could explain the change a bit more thoroughly; looking at the linked issue, the reason the file was to be deleted is because it is unused and deleting it would "keep the file system clean and avoid confusion". Can you update the Why section of your PR with a bit more explanation, closer to the Overview in the linked issue?

Other than those changes, everything is looking good so far!

**Comment by ndmoc** [comment]
> Hi @ndmoc — the branching is set up correctly, the corresponding issue was linked, and the requested change of removing the `donation-graphic.svg` file was made without affecting the Join Us page, but I have two small requests for you to edit and update your PR.
> 
> * As you had noted within the `<details>` tag, the image was unused and did not result in visual changes; since there are no visual changes, can you delete the entire Screenshots section in your PR? This will help keep our codebase documentation clean and it's a bit more obvious at first glance that there are no visual changes from this PR when this is deleted.
> * The Why of your PR could explain the change a bit more thoroughly; looking at the linked issue, the reason the file was to be deleted is because it is unused and deleting it would "keep the file system clean and avoid confusion". Can you update the Why section of your PR with a bit more explanation, closer to the Overview in the linked issue?
> 
> Other than those changes, everything is looking good so far!

Thank you for the feedback Adrian. I removed the screenshot section and added an explanation regarding the issue's overview. I will be more specific moving forward! Thank you

**Review by adrianang — APPROVED** [review]
Thank you for making those changes! The PR looks good to me now; thank you for taking up this issue and contributing to HfLA! 🙌🏼

**Pull request merged**
