### PR TITLE
Create and apply header component 

### LINKED ISSUE #1898: Standardize code for header layout
### Overview
Create standardized header layout component html and css to ensure visual consistency, and to make creating new pages easier and more efficient.

### Action Items
- [x] Determine class names and properties necessary based on Figma file
- [x] Implement CSS and HTML changes to create standard header component to all pages that use this specific component layout 
- [x] Update [How to create a page on the HfLA website](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website) wiki page
- [x] Release dependency on #19 

### Resources/Instructions
Issues with current header layout commented on #1791

### PR DESCRIPTION
**Pull request by arghmatey**
Fixes #1898 

### What changes did you make and why did you make them ?
  - Created and applied class names for a specific header layout that is used across eight pages (About, Communities of Practice, Credits, Join Us, Programs Areas, Project Meetings, Sitemap, Toolkit).
  - Consolidated and refactored css code related to the header section into _containers.scss 
  - Removed any unused css related to the old header. There was a lot of repetitive code spread across different files, so this was a pretty necessary clean up. Tested to make sure no other pages would be affected before removing code. 

  - "About Us" link in header section needed a new class and css to be moved since it is different styling.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

**_Screenshots provided are full page views_**

<details>
<summary>Desktop full length pages before changes were applied</summary>

[About Us Before](https://user-images.githubusercontent.com/40401149/126730475-fb069651-2ded-4437-aa3b-e59f4f08ccd8.png)
[Communities of Practice Before](https://user-images.githubusercontent.com/40401149/126730483-67ebbde2-6bf1-4e5f-a9d4-1511d4350872.png)
[Credits Before](https://user-images.githubusercontent.com/40401149/126730486-ffcdc05f-a5d9-42af-943a-5f4509c787b3.png)
[Join Us Before](https://user-images.githubusercontent.com/40401149/126730490-b91e29af-e0a3-41e7-9e7e-11ac6f9b1ad4.png)
[Program Areas Before](https://user-images.githubusercontent.com/40401149/126730491-1d5795bc-d3d1-4fed-9685-d23c0a69fc5a.png)
[Project Team Meetings Before](https://user-images.githubusercontent.com/40401149/126730496-c0c709c9-414e-4e0c-b788-002e0c645e95.png)
[Sitemap Before](https://user-images.githubusercontent.com/40401149/126730498-cc45c43f-0744-4690-8115-c9d030a8a95a.png)
[Toolkit Before](https://user-images.githubusercontent.com/40401149/126730500-33d93af7-d7f8-419e-867a-27434fa3e2e0.png)

</details>

<details>
<summary>Desktop full length pages after changes were applied</summary>

[About Us Before After](https://user-images.githubusercontent.com/40401149/126730809-a8ee1b85-ce6d-4ffd-a360-676f2ca2c2b6.png)
[Communities of Practice After](https://user-images.githubusercontent.com/40401149/126730819-81c4ece9-e0f7-47fb-9fc7-54f2ffcc90b6.png)
[Credits After](https://user-images.githubusercontent.com/40401149/126730826-18c472e8-d1f2-42f3-bd02-0c2296da3d2d.png)
[Join Us After](https://user-images.githubusercontent.com/40401149/126730827-55ea8872-0997-44cc-8d19-92b35a33bc9e.png)
[Program Areas After](https://user-images.githubusercontent.com/40401149/126730828-eac83057-28b5-4b71-892a-bfff6afd973d.png)
[Project Team Meetings After](https://user-images.githubusercontent.com/40401149/126730833-7b9b1319-b6ff-4cfb-af28-bf0b5c3f1719.png)
[Sitemap After](https://user-images.githubusercontent.com/40401149/126730836-d01bcad3-25cc-444c-bbf0-3a3bf44e081c.png)
[Toolkit After](https://user-images.githubusercontent.com/40401149/126730837-393f28d3-2136-437d-8dcc-98f26eedecfc.png)

</details>

<details>
<summary>Tablet views after changes were applies</summary>

 **Using Toolkit and Project Team Meetings pages as examples**
[Toolkit Tablet After](https://user-images.githubusercontent.com/40401149/126731952-06ebe1ef-bb34-4271-a711-5782d4480c99.png)
[Project Team Meetings After](https://user-images.githubusercontent.com/40401149/126731962-80737989-3a6c-4d1b-91a6-f2b1f7433a29.png)

</details>

<details>
<summary>Mobile views after changes were applies</summary>

 **Using Toolkit and Project Team Meetings pages as examples**
[Toolkit Mobile After](https://user-images.githubusercontent.com/40401149/126732017-fd4440ae-5cd5-48d5-b87d-d9c6e64897f9.png)
[Project Team Meetings Mobile After](https://user-images.githubusercontent.com/40401149/126732045-47fc8072-988f-4040-8aeb-11fb7a726ffd.png)

</details>

### CODE REVIEW

**Review by blakes24 — DISMISSED** [review]
Looks good to me. It removes a lot of duplication, and the headers looked great across all screen sizes when I tested it out.

**Review by Aveline-art — COMMENTED** [review]
I want to say that this is awesome and amazing work, @arghmatey ! There is so much attention to detail on this when comparing the [website as it currently is](https://www.hackforla.org/#), to our [figma ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465), to your changes. A++++ work! I will gladly merge this in a heartbeat, but I want to know your thoughts on some of the spacing:

Comparing it to the Figma designs, some of the margins/padding between the titles and the nav bar is off (most noticeable in the program area and team meetings page). Would you want to change them as part of this PR? Or do you feel it is better to make new issues out of them? I am fine with either, as the spacing is not too off.

**Comment by arghmatey** [comment]
Thank you, @Aveline-art! 

Nice catch on the spacing. Looks like right now the Credits page is off of the Figma file as well. I'll take a deep dive into it tomorrow morning to see what would be the best solution.

**Comment by arghmatey** [comment]
@Aveline-art This is ready for a final review now. Please let me know if you find anything else. Here's what I did: 

- Found the text side of the header should be justified to center of container. This causes the spacing on program areas, project meetings, and credits page because the height of the text is smaller than the image height. 
- I also had to change padding/margin dimensions on the second p tag since the bottom margin was adding to the spacing issues. 

The only issue we are left with is the Sitemap page. Figma shows it should not be justified center like the other pages, but close to the navbar instead. I figure since it is one page against many, a new issue can be created to put it back in the right place.

<details>
<summary>Justified Center Screenshots</summary>

Credits
Program Areas
Project Team Meetings

</details>

<details>
<summary>Sitemap Now & Figma</summary>

Now
Figma
</details>

**Review by Aveline-art — DISMISSED** [review]
This looks awesome @arghmatey ! There is a merge conflict, but once that is dealt with, I can feel free to merge this.

**Comment by arghmatey** [comment]
Thanks, @Aveline-art. Merge conflict resolved!

**Review by Aveline-art — APPROVED** [review]
Looks gorgeous! Thank you for the hard work!

**Pull request merged**
