### PR TITLE
New color variables

### LINKED ISSUE #1378: Consolidate Raw Colors To Standardized Color Variables
### Overview
 Currently there are quite a few places in the code base where raw colors are being used. These needs to be consolidated into variable names as much as possible such that we can have a dictionary of HFLA acceptable color variable names. An effort to do this has already been started by the design team as part of the HFLA [Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) as well as by developers under the following [folder](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss)

### Action Items
<sub>Please ensure to tick of the checkboxes as you complete each task</sub>
- [x] A developer, Make a table of all the raw colors that are currently being used, the pages they are being used in and screenshots of rendered color on the site.
- [x] Post the table as a comment on this issue
- [x] Rope in someone from the design team to discuss naming conventions 
- [x] After the above steps has been completed make a PR that implements the above changes by removing all raw colors as necessary and replacing them with variable names
- [x] Complete the additional changes outline [here](https://github.com/hackforla/website/pull/1917#pullrequestreview-708614012)

### Resources
Parts of this issue had already been previously completed. The remaining steps are outlined above in unchecked action items. To see what has already been done, please see [this pull request](https://github.com/hackforla/website/pull/1917).

### PR DESCRIPTION
**Pull request by Aveline-art**
Partially Fixes #1378

### What changes did you make and why did you make them ?

  - Salvaged the usable code from #1917 
  - Grouped color variables according to Western (?) color sequencing

### TODO after merging

Note: I have decided that the original issue is too large to be considered a medium issue. When testing the code from #1917, the website breaks in many areas (because of the order our scss is being read). To account for this, we must transition to color variables at a slower pace.

- [x] Create new issues pertaining to auditing the website for hard-coded colors, and changing them into one of the variables in this fork.
  - [x] 1 issue for reds and oranges (medium)
  - [x] 1 issue for yellows and greens (medium)
  - [x] 1 issue for blue and purples (medium)
  - [x] 1 issue for the rest (medium)
  - [x] 1 follow-up audit for any remaining hard-coded colors (medium/large) 
  - [x] Note: If any of the variables in this PR is not found elsewhere in our codebase, they should be deleted by the assignee of the above issues.

### CODE REVIEW

**Comment by Aveline-art** [comment]
@hackforla/website-design Please give any feedback on color names. If the team have their own color palette/naming scheme please share them with me! Also, we have a lot of similar colors. Would we want to condense some of them into a single color?

<details>
<summary>Colors as they appear against VSCode's light theme (zoom in to see the colors better)</summary>
<br>

<br>
</details>

**Comment by Aveline-art** [comment]
@daniellex0 has messaged me that everything looks good, so this can be merged after reorganizing some of the misplaced colors, such as midnight-blue.

**Review by macho-catt — COMMENTED** [review]
This looks really good, and I like that you grouped the colors together. It makes looking at the colors much more pleasant to the eye.

I do have one suggestion for one of the color names:

$color-lightergrey: #f6f6f6

Instead of using "lighter grey," I think it would make sense to use something else like "[very light gray](https://www.colorhexa.com/f6f6f6)" or even "[white smoke](https://htmlcolorcodes.com/color-names/)" It just seem like it would conflict / be confusing when used in conjunction with the 'light gray' color variable.

**Review by macho-catt — APPROVED** [review]
Looks good to me. Good job!

**Pull request merged**
