### PR TITLE
Add PM to Website Team Leadership

### LINKED ISSUE #3596: Update Project Profile: HackforLA website team
### Overview
As a product manager of HackForLA website team I want my project's details to be up to date on the HackforLA website

### Project card
URL of my project card: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md

### Action Items

- [x] HackForLA Website team Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

### PR DESCRIPTION
**Pull request by jyaymie**
Fixes #3596

### What changes did you make and why did you make them ?

  - Added Stephanie Samuels (info found in the issue's comment) to the Website Team Leadership so that the project's details are up to date on the HfLA website.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-10-16 at 12 13 16 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screen Shot 2022-10-16 at 12 13 43 PM

</details>

### CODE REVIEW

**Comment by MattPereira** [comment]
Review ETA: 5 PM 10/17/22
Availability: 4 - 5 PM Monday

**Comment by d-perez-8** [comment]
ETA: 6 pm 10/17/2022
Availability: 4:30 to 6 pm 10/17/2022

**Review by MattPereira — APPROVED** [review]
Great job Jamie! I love how you mentioned to look at the issue's comments and your screen captures were excellent!

**Review by d-perez-8 — APPROVED** [review]
This looks good to me. The website does not break, and the links work correctly. 
Great job and thank you for your work!

**Pull request merged**
