### PR TITLE
Update Job Profiles on Civic Tech Jobs : Remove Tin Wei Chung; Add Armon Brown & Carmen MakRemove  # 6639

### LINKED ISSUE #6639: Update Project Profile: Civic Tech Jobs (Remove Tin Wei Chung; Add Armon Brown & Carmen Mak)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/civic-tech-jobs.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and remove the following:
  ```
    - name: Tin Wei Chung
      github-handle:
      role: UX/UI Designer
      links:
        slack: https://hackforla.slack.com/team/U03P6Q6FSQ5
        github: https://github.com/TCUX
      picture: https://avatars.githubusercontent.com/TCUX
  ```
- [x] For the `leadership` variable, add the following profiles. If there are other UX/UI Designers, place Armon Brown's and Carmen Mak's profile after the other UX/UI Designers' profiles
  - [x] Add
    ```
      - name: Armon Brown
        github-handle: stanarmon
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U06J0UCAWHE
          github: https://github.com/stanarmon
        picture: https://avatars.githubusercontent.com/stanarmon
    ```
  - [x] Add
    ```
      - name: Carmen Mak
        github-handle: CarmenMM1
        role: UX/UI Designer
        links:
          slack: https://hackforla.slack.com/team/U06313EMD41
          github: https://github.com/CarmenMM1
        picture: https://avatars.githubusercontent.com/CarmenMM1
    ```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Civic Tech Jobs page [^2]
- [ ] Once your pull request is merged, go to #6583 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6583 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6583
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/civic-tech-jobs

### PR DESCRIPTION
**Pull request by samuelusc**
Fixes #6639

### What changes did you make?
  - Removed previous UX/UI designer

### Why did you make the changes (we will use this info to test)?
  - Add new UX/UI designers

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

conflicts fixed - before

</details>

<details>
<summary>Visuals after changes are applied</summary>

conflicts fixed - after
  

</details>

### CODE REVIEW

**Comment by LRenDO** [comment]
Hi @samuelusc! Thanks for submitting this PR. When you have a moment, please edit the title of the PR to be descriptive of the changes made in the PR. For the future, we also use a descriptive branch name with the issue number included. 

Additionally, I just merged a PR in this same file so there is a now a conflict in your PR. Please update your topic branch and push the changes when you get a chance. For instructions on updating your topic branch, see [Incorporating changes into your topic branch](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-incorporating-changes-into-your-topic-branch). Feel free to ping me here or on Slack if you need help.

**Comment by samuelusc** [comment]
@LRenDO 
Hi LRenDO, 
Thank you for your guidance. I have updated the title of the PR to better reflect the changes made. Additionally, I have resolved the merge conflicts that arose after a recent merge in the same file and have force-pushed the updates to ensure that the  **fix-issue-6639 branch** is now fully aligned with **the latest upstream/gh-pages**. 

Next time I will use more descriptive branch name with the issue number included and appreciate your suggestion. Please let me know if there's anything more to adjust or if further review is needed.

**Comment by A-Wu5** [comment]
Availability: Th & Weekend 8pm-10pm
ETA: Th EOD

**Comment by LRenDO** [comment]
Hi @samuelusc! thank you for taking care of the merge conflict! I went ahead and responded to your message in Slack with some non-functional notes, since it looks like the title change didn't stick and you may have a linter that is removing whitespace automatically.

**Comment by samuelusc** [comment]
@LRenDO 
Thanks for your feedback. I've edited the title as you suggested and turned off the automatic removal of whitespace in my editor. Should I manually add the spaces back according to the diffs shown in the Git commits and push the PR again? Please let me know how you'd like to proceed.

**Review by jphamtv — DISMISSED** [review]
Hi @samuelusc, nice work on this. I tested and confirmed the updates locally and all looks good. I think it's okay to keep the spaces removed and leave it as-is since it doesn't affect anything functionally, but I'll defer to @LRenDO if the opinion is different. Just be mindful of extraneous changes when working on future issues. 

Thanks for your contribution to this issue!

**Comment by samuelusc** [comment]
@jphamtv Thank you, Jpham. I just saw your message. I've updated it accordingly, and I'll be more mindful of extraneous changes in the future. Thanks for your guidance!

**Review by A-Wu5 — APPROVED** [review]
Hi @samuelusc, great job on this issue! The changes have been made accordingly to #6639 and it looks good to me.

**Review by LRenDO — APPROVED** [review]
Hi @samuelusc! This looks great! @jphamtv is correct that spaces in and of themselves were not an issue, just wanted to check about a linter that might make other undesired changed further on in the process.

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site.
- Relevant images were included to show visual changes
- The PR request clearly states what was updated

For the future, along with descriptive branching and limiting the scope of changes to the issue, the why should describe why the development team is making the changes. This is usually found in the "Overview" section of the issue and it's totally okay to copy and paste it.

Again great work on the PR and making updates! Thanks for contributing!

**Pull request merged**
