### PR TITLE
updates co-lead Beck for Abundis

### LINKED ISSUE #6184: Update Communities of Practice: Engineering (Remove Chelsey Beck, Add Adam Abundis)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Chelsey Beck
    role: Co-Lead
    links:
      slack: https://hackforla.slack.com/team/U01J93AQKSS
      github: https://github.com/chelseybeck
    picture: https://avatars.githubusercontent.com/chelseybeck
```
- [x] Then, add the following person to the `leadership` variable as a new entry :
```
  - name: Adam Abundis
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/UJML6CY49
      github: https://github.com/abuna1985
    picture: https://avatars.githubusercontent.com/abuna1985
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #6160 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6160 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6160
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by sornekian**
Fixes #6184 
### What changes did you make?
  - Removed Chelsea Beck
  - Replaced with Adam Abundis
  - Made sure changes reflected on both desktop and mobile

### Why did you make the changes (we will use this info to test)?
  - To update the leadership variable in communities of practice under engineering

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-02-07 at 11 19 37 AM

Screenshot 2024-02-07 at 11 19 53 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-02-07 at 11 18 41 AM

Screenshot 2024-02-07 at 11 18 56 AM

</details>

### CODE REVIEW

**Comment by sornekian** [comment]
Hello, I created another branch and made a new pull request, hopefully this one works. If not, I believe i would need some help.

**Comment by t-will-gillis** [comment]
Hey @sornekian - This looks good! Should be ready to merge. 

If you would, please add a comment on the previous PR and then 'Close with comment' the previous PR. The comment can be something like: "Replaced by #6262" 

Thanks!

**Comment by Chrisklangley** [comment]
Availability: M-F 6:30pm
ETA:2/9/24

**Review by Chrisklangley — APPROVED** [review]
Great work on your Pull request.

The issue is correctly linked in your PR and you have clear and detailed documentation on the changes you made and why you made them. 

 I see that you correctly removed Chelsey from the leadership variable and added adam from lines 28-33 in the _data/internal/communities/engineering.yml file
  
 A quick note: mobile screenshots aren't required

**Review by jphamtv — APPROVED** [review]
Hey @sornekian ,
- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- The before/after screenshots confirm the changes
- Your code change is clean and accurate 
- I was able to verify the changes look good locally through Docker

Great work! As @t-will-gillis mentioned, please ensure to close any pull requests you replace, adding a comment to explain why. This helps to clear the invalid pull requests from the list and prevents other developers from reviewing them when they're not valid.

**Pull request merged**
