### PR TITLE
Img tag refactor 5619

### LINKED ISSUE #5619: img tag refactor in CONTRIBUTING.md Section 4.1
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` Section 4.1
- [x] Replace
```
<img src="https://user-images.githubusercontent.com/21162229/137784791-30871703-48de-4836-91ef-1268d86662a4.jpg" alt="Visual example of how to copy the comment link" />
```
with
```
<img src="https://user-images.githubusercontent.com/21162229/137784791-30871703-48de-4836-91ef-1268d86662a4.jpg" alt="Visual example of how to copy the comment link">
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by tkozek**
Fixes #5619 

What changes did you make?
  -Removed the ending slash in the following img tag in Section 4.1:

`Visual example of how to copy the comment link`

to become: 

`Visual example of how to copy the comment link`

### Why did you make the changes (we will use this info to test)?
  -So that the codebase is consistent with how Hack for LA uses img HTML tags
For Reviewers: Do not review changes locally, rather, review changes at:

 https://github.com/tkozek/website/blob/img-tag-refactor-5619/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website
-There are no visual changes to the site as a result of this issue.

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: EOD 9/7/23
Availability: 12 pm - 5 pm 9/7/23

**Comment by MattChau01** [comment]
Availability: Can be reached via Slack throughout the day
ETA: Will complete by EOD Sunday

**Review by KyleA99 — APPROVED** [review]
Looks good to me.  Nice work @tkozek

**Review by MattChau01 — APPROVED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5619 was properly referenced. ✅ 
- The specified line of code was properly updated per the instructions on the original issue. ✅ 
- You also provided a direct URL to the updated md file for review, which was very helpful! From here, I was able to verify again that the proper code was updated!

Great work @tkozek!

**Pull request merged**
