### PR TITLE
Edit content field and remove type field from security.yml credits file

### LINKED ISSUE #2858: Edit content field and remove type field from security.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/security.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/security.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/security.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/security.yml#L11

### PR DESCRIPTION
**Pull request by Adastros**
Fixes #2858

### What changes did you make and why did you make them ?

  - Updated "content: icon" field to "content-type: image"
  - Removed type field

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updating fields in credits file. No visual changes to the website.

### CODE REVIEW

**Comment by luiderek** [comment]
Availability: 10PM-12PM
ETA: 10min

**Comment by luiderek** [comment]
Nice work @Adastros. It's the right changes to the right file, and your branch / commit naming conventions are clean.

**Review by luiderek — APPROVED** [review]
Learning GitHub is definitely a process. See above.

**Comment by MattPereira** [comment]
Review ETA: End of Day 11/6/22
Availability: 4 - 6 PM

**Comment by Suman2795** [comment]
Review ETA: 9 PM 6/11/2022
Availability : 6 /11/2022

**Review by Suman2795 — APPROVED** [review]
Great job @Adastros ! Your changes look correct.

**Review by MattPereira — APPROVED** [review]
Good work on this one @Adastros ! :+1: 

You linked the issue number properly and removed the redundant code from `secuirty.yml`. Keep up the good work!

**Comment by jyaymie** [comment]
Review ETA: 11/7/22 7:30am
Availability: 11/7/22 Now - 9am

**Review by jyaymie — APPROVED** [review]
You've linked the issue and implemented all its action items. I like to include a rationale for my changes in the body of the PR, but I see it's pretty clear in the issue itself. Great work!

**Pull request merged**
