### PR TITLE
Created Civil Tech Infrastructure credit file

### LINKED ISSUE #3352: Add credit for Civic Tech Infrastructure image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the Credits webpage is up to date.

### Details
From the Homepage Redesign Credits in Figma, here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Civic Tech Infrastructure credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `civic-tech-infrastructure.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Civic Tech Infrastructure
# The url where you can get direct access to the image on the provider site
title-link: https://unsplash.com/photos/unRkg2jH1j0
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Adeolu Eletu
# Name of the image database you found it on
provider: Unsplash
# Please give the general site URL, not the link to the image
provider-link: https://unsplash.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/civic-tech-infrastructure.png
# Alt text for the image on the Credits page
alt: ''
# If an image was altered, please give the name of the HfLA designer that altered the image
altered-by: Kristine Eudey
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please do the following in issue #3130:
    - [ ] Move it to the New Issue Approval column
    - [ ] Remove the "Dependency" label from it
    - [ ] Add a "ready for dev lead" label to it  
  
### Resources/Instructions
- [Credits webpage](https://www.hackforla.org/credits/)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- This issue is tracked in the epic #3130.

### PR DESCRIPTION
**Pull request by kyrakwak**
Fixes #3352

### What changes did you make and why did you make them?
  - Created `_data/internal/credits/civil-tech-infrastructure.yml` file
  - Added content as instructed in linked issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-01-30 at 10 03 07 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
Box added to screenshot to highlight addition, not actually present on site.
Screen Shot 2023-01-30 at 10 01 41 AM

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 2/4
Availability: 2 hours

**Comment by christinaor** [comment]
ETA: 10pm EST 2/2/23
Availability: 10am - 5pm, Mon - Fri

**Comment by christinaor** [comment]
I was able to navigate to the credits page after running docker to confirm the new visual. The name "Civic Tech Infrastructure" correctly links to the image in the thumbnail. The provider correctly links to the general "Unsplash" homepage. The asset is present and the file is correct as well. Great job with this issue!

**Review by christinaor — APPROVED** [review]
I was able to navigate to the credits page after running docker to confirm the new visual. The name "Civic Tech Infrastructure" correctly links to the image in the thumbnail. The provider correctly links to the general "Unsplash" homepage. The asset is present and the file is correct as well. Great job with this issue!

**Review by MattPereira — APPROVED** [review]
Well done @kyrakwak ! :+1: 

I appreciate your high quality screen shots!

**Pull request merged**
