### PR TITLE
updated lucky-parking.md 

### LINKED ISSUE #5807: Update Project Profile: Lucky Parking (Remove Yen Phan)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Yen Phan
    role: User Research
    links:
      slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
      github: 'https://github.com/ymphan'
    picture: https://avatars.githubusercontent.com/ymphan
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking

### PR DESCRIPTION
**Pull request by junadkat32**
Fixes #5807 

### What changes did you make?
  Removed:
  
    - name: Yen Phan
    role: User Research
    links:
      slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
      github: 'https://github.com/ymphan'
    picture: https://avatars.githubusercontent.com/ymphan

### Why did you make the changes (we will use this info to test)?
  
As mentioned in the issue, the task was to remove "Yen Phan" under leadership variable in lucky parking project.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

image

</details>

### CODE REVIEW

**Comment by irais-valenzuela** [comment]
Review ETA: today 1/16/23
Availability: Thursday 10:30 am -2 pm & Friday 10:30 am - 1 pm

**Comment by irais-valenzuela** [comment]
Hi, it seems that the before and after screenshots of your changes are not showing up when I go to look at them. Please be sure to add them.  :)

**Comment by junadkat32** [comment]
Hi @irais-valenzuela , do I have to take a screenshot of the code before and after making the changes?

**Comment by irais-valenzuela** [comment]
> Hi @irais-valenzuela , do I have to take a screenshot of the code before and after making the changes?

Take a screenshot of the UI before and after you've made your changes. Let me know when you've added the pictures or if you need help.

**Comment by junadkat32** [comment]
> > Hi @irais-valenzuela , do I have to take a screenshot of the code before and after making the changes?
> 
> Take a screenshot of the UI before and after you've made your changes. Let me know when you've added the pictures or if you need help.

I have updated the screenshots.

**Review by irais-valenzuela — DISMISSED** [review]
Hi @junadkat32! Thanks for taking up this issue.

Branches were set up correctly. Your changes successfully removed Yen Phan from the lucky parking UI and in the code. PR also included a description of what this PR does and included images to show before and after changes. Next time don't forget to provide a snippet for the "Why did you make the changes (we will use this info to test)?".

Nice job! @junadkat32 ✨

**Comment by junadkat32** [comment]
Hi @irais-valenzuela, will you perform the merging of this pull request? Do I have to do anything from my side?

**Comment by irais-valenzuela** [comment]
Hi, someone from the merge team will. You do have to wait until this PR is
merged for you to move onto another issue but as far as doing anything
after a PR review there’s nothing else.

**Comment by kwangric** [comment]
Hey @Chrisklangley! When you get the chance, can you leave a comment with your availability and ETA for your review? Thanks!

**Comment by Chrisklangley** [comment]
Availability: M-F 6-9pm
ETA: EOD 11/122

**Review by Chrisklangley — DISMISSED** [review]
Hey @junadkat32 

Good work on your PR! 
•your made a new branch with the correct syntax then pushed to hackforLA:gh-pages
you correctly  linked your issue and made  clear documentation on the changes you made
• I see that you removed correctly removed Yen Pan from the leadership Variable in the _project/lucky-parking.md file 

Everything looks good, but please remember to leave a comment under  Why did you make the changes (we will use this info to test)? heading even if the change was small 

Great work!

**Comment by kwangric** [comment]
Hey @junadkat32! Looks like there's a merge conflict after some of the members of Lucky Parking were removed in the last few days. Can you resolve this and then push your branch again? Let me know if you need any help with this.

Also, as @irais-valenzuela and @Chrisklangley have mentioned, please update your PR to include a comment to explain why the changes were made. It doesn't have to be too detailed, just a simple explanation would work.

Thanks!

**Comment by junadkat32** [comment]
Hi @kwangric I am still facing the merge conflict issue. Can you please help me resolve it?

**Comment by kwangric** [comment]
@junadkat32 if you open up the option to "Resolve Conflicts" near the bottom of this PR and delete lines 70, 71, and 78, then  select "Mark as resolved" at the top right of the page, that should fix it. Let me know if you run into any problems.

image

**Comment by junadkat32** [comment]
Okay @kwangric , I have made the necessary changes.

**Review by irais-valenzuela — APPROVED** [review]
Hi @junadkat32, nice job making the changes!

**Review by Chrisklangley — APPROVED** [review]
You made the necessary changes good work!

**Pull request merged**
