### PR TITLE
Update Project Profile: Website

### LINKED ISSUE #4009: Update Project Profile: Hackforla.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Danny Do
GitHub Handle: Adastros
Role: Merge Team
Slack Member ID: U048G8S2YAK
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by bootcamp-brian**
Fixes #4009 

### What changes did you make and why did you make them ?

  - Added Danny Do's info to leadership variable in _projects/website.md
  - Confirmed changes and working links in local environment

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

projects-website-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
projects-website-after

</details>

### CODE REVIEW

**Comment by mademarc** [comment]
Review ETA: 8PM 2/23/23
Availability: 1Hr

**Review by mademarc — COMMENTED** [review]
The code is done well  @bootcamp-brian and it matches the screenshot images

**Comment by vanessavun** [comment]
ETA: 02/23/2023
Availability: weekday evenings

**Review by vanessavun — APPROVED** [review]
Thank you for on working on this ticket to completion. Commit into the right branch from your branch looks good. I viewed the page locally and it appears with the right information without anything broken, and the link opens up and goes to the correct Slack ID. Good job.

**Comment by blulady** [comment]
> The code is done well @bootcamp-brian and it matches the screenshot images

Hey @mademarc , to review a PR click on Files Changed at the top of the PR and then click on Review Changes

Screenshot (346)

**Comment by bootcamp-brian** [comment]
@vanessavun @mademarc Thanks for the feedback!

**Comment by mademarc** [comment]
No Problem @vanessavun and it was my pleasure :)

**Pull request merged**
