### PR TITLE
Refactored tools data in civic-tech-index.md 

### LINKED ISSUE #5341: Refactor Tools data for civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For the Civic Tech Index project, there is a discrepancy in the representation of the name of a tool being used, leading to potential confusion or misrepresentation.

### Action Items

- [x] Locate the Civic Tech Index markdown file in the website/_projects/ folder.
- [x] Locate the section `tools: ...` 
- [x] Replace:
```
  - Google docs
  - Figma
  - Usability Hub
```
with:
```
  - Google Docs
  - Figma
  - UsabilityHub
```
- [x] Provide before and after screenshots of the relevant web pages showing that the change was made successfully with no unintended effects. 

### Resources/Instructions
[civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)
[Civic Tech Index](https://www.hackforla.org/projects/civic-tech-index) project page
[Hack for LA](https://www.hackforla.org/) homepage
[Projects](https://www.hackforla.org/projects/) page
This issue is initiated by ER #5246

### PR DESCRIPTION
**Pull request by A-Wu5**
Fixes #5341 

### What changes did you make?
  - Replaced
    - Google docs
    - Figma
    - Usability Hub
  - with
    - Google Docs
    - Figma
    - UsabilityHub

### Why did you make the changes (we will use this info to test)?
  - To fixed discrepancy in names of tools to prevent confusion.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

#5341Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
#5341After

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: 9/18 EOD
Availability: 2-5pm PDT

**Review by kwangric — DISMISSED** [review]
Branches are set up correctly. The requested changes were made and everything looks good in docker. PR also includes description of the changes made and relevant screenshots. Great work!

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 9/18 EOD

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
@A-Wu5 , merge branches look good, ode changes are as mentioned in the issue, and website looks good on local machine. To keep the code cleaner, please remove the blank `line 135`

**Comment by A-Wu5** [comment]
Hello, thanks for the comments. I have updated the file by removing the empty space.

**Review by kwangric — APPROVED** [review]
Thanks for making the requested changes, everything looks good to me!

**Review by Thinking-Panda — APPROVED** [review]
@A-Wu5 , Thank you !

**Pull request merged**
