### PR TITLE
Edit content field and remove type field from board.yml, credit files

### LINKED ISSUE #2794: Edit content field and remove type field from board.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/board.yml`, do the following:
- [ ] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [ ] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/board.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/board.yml#L4
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/board.yml#L11

### PR DESCRIPTION
**Pull request by Olanrewaju-Ak**
Fixes #2794 

### What changes did you make and why did you make them ?

  -changed  content to content-type on line 4
  -Removed line 11 for the type field
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Edited text fields. No visual changes to the website.

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA: End of the day on 5/23
Availability: 1 hour

**Review by kathrynsilvaconway — COMMENTED** [review]
*Comment removed

**Comment by Jaretzbalba** [comment]
ETA: End of the day on 5/23
Availability: 1 hour

**Comment by Jaretzbalba** [comment]
@kathrynsilvaconway This actually looks to be correct. The issues are very similar due to them being "good first issues". The issue for PR #3168 you mentioned above is for issue #2797 which changes the building.yml file. This PR affects the board.yml file

**Review by Jaretzbalba — APPROVED** [review]
@Olanrewaju-Ak Great job working on this good first issue! I see you were able to change line 4 to "content-type" and remove line 11.

**Comment by kathrynsilvaconway** [comment]
> @kathrynsilvaconway This actually looks to be correct. The issues are very similar due to them being "good first issues". The issue for PR #3168 you mentioned above is for issue #2797 which changes the building.yml file. This PR affects the board.yml file

Aha! Nice catch, as always, @Jaretzbalba. My mistake. I'm going to delete my first review and just write a another one with approval to avoid confusion.

**Review by kathrynsilvaconway — APPROVED** [review]
@Olanrewaju-Ak  Congrats on completing your first issue with Hack for LA. I see that you have changed the content field in line 4 to read 'content-type: image' and you have deleted line 11 from the board yml file. Nice work.

**Pull request merged**
