### PR TITLE
Swap colors with color variables

### LINKED ISSUE #2113: Design System Audit: Swap colors with color variables: black, grey, and white
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the black, grey, and white colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (black, grey and white colors)
  - [x] Also, make sure to check the equivalent hex values
    - [x] For `$color-black`, `#333` is the same as `#333333`
    - [x] For `$color-mediumgrey`, `#ccc` is the same as `#cccccc`
    - [x] For `$color-white`, `#fff` is the same as `#ffffff`
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
  - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L49-L58

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  
</details>

### PR DESCRIPTION
**Pull request by raswani2023**
Fixes #2113

### What changes did you make and why did you make them ?

  - for every white, grey, and black color value, I swapped the hard coded color with the color variable
  - note: the resource given for the current color variables in the issue defined black as 333 and white as fff. I found instances of black being defined as #333333 and white being defined as #FFFFFF, so I swapped those as well

### CODE REVIEW

**Comment by raswani2023** [comment]
I've run into the issue where unwanted commits are in my PR again unfortunately, but I'm not sure why. I am trying to figure it out on my own, but will probably end up needing to attend office hours on Thursday.

**Comment by Wny-Duong** [comment]
ETA: 7/28/22
Availability: 4 hours

**Comment by Wny-Duong** [comment]
Had some time to give this a quick first look before re-reviewing after the merge conflicts get fixed. The changes look good and the site looks the same on the parts matching up with the scss files. 

One thing that's not clear to me though is whether or not you should've changed the color codes for #f7f5f5 and #030d2d to $color-pink and $color-darkblue in addition to the color changes that were more explicitly grey, black, and white.  They're under the Blacks, Greys, and White comment in the original issue so I assumed they should've been changed, but it's possible that that was just a mistake. It's still worth asking the original issue maker if that was intentional though, I think.

On the merge conflict problem, it just looks like there's two separate problems. One conflict is just the _404.scss that should just be overridden with your changes for the color variable. in your IDE assuming you're using VS Code The other issue involves your old commits for previous PRs being included in this one. I'm not too sure how to resolve the second one so that should definitely be brought up during office hours.

Also, I'm not too sure why the gh automation bot isn't added labels to this issue or showing the checkout and pull box but here're the lines if anyone else wants to review this:
```
git checkout -b raswani2023-swap-colors-with-variables-2113 gh-pages
git pull https://github.com/raswani2023/website.git swap-colors-with-variables-2113
```

**Comment by ExperimentsInHonesty** [comment]
@raswani2023 are you able to resolve the conflicts on this pr?

**Comment by raswani2023** [comment]
@Wny-Duong Thanks for looking through it. I am not sure if I was supposed to change the pink and blue colors. I see now that it is under the whites, greys, and blacks section so it is possible that I was supposed to. But I'm not completely sure since the title said only whites, greys, and blacks. I will ask the original issue maker (Ava Li) during Community of Practice tonight for more clarification.

I'm also trying to get help from Satya with the merge conflicts. I'll try to get it solved as soon as possible. Thanks!

**Comment by raswani2023** [comment]
@ExperimentsInHonesty I just heard back from Satya about the merge conflict, so I'm trying to figure it out with him. Hopefully we can find a solution to it. He thinks it might be because my repo wasn't up to date when I opened the PR. Might meet with him on zoom as well.

**Comment by raswani2023** [comment]
@Wny-Duong I checked with Ava and she said that I was supposed to swap the pink and blue colors as well. Just made those changes and pushed them onto my branch. She also helped me with the merge conflict, so I think it might be solved now.  Let me know if it looks fine or if there's anything else I need to fix! Thanks.

**Comment by ExperimentsInHonesty** [comment]
@Zak234 @Wny-Duong are either of you available to review or re-review Riya's pr so that she can finish her Internship on time?

**Comment by ExperimentsInHonesty** [comment]
@raswani2023 did Satya have any advice for what to do once you have done the pr, but the old commits remain?  Do you have to close this one and do another after updating?

**Comment by raswani2023** [comment]
@ExperimentsInHonesty He gave me some advice, but also told me to check with Kathryn tonight and then loop back in with him. But, I did ask Ava yesterday in CoP and she helped me fix the merge conflicts. She thinks it was fixed but maybe there are still some issues. Either way, I will attend office hours tonight to make sure it is all good.

**Comment by Wny-Duong** [comment]
@ExperimentsInHonesty @raswani2023 I'll have this PR re-reviewed by the end of today.

**Review by Wny-Duong — CHANGES_REQUESTED** [review]
I'm getting some error messages when running docker-compose up:
```
hfla_site    |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
hfla_site    |                     Invalid CSS after "...r: $color-black": expected "{", was ";" on line 112
hfla_site    | jekyll 3.9.2 | Error:  Invalid CSS after "...r: $color-black": expected "{", was ";" on line 112
hfla_site    | /usr/gem/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid CSS after "...r: $color-black": expected "{", was ";" on line 112 (Jekyll::Converters::Scss::SyntaxError)
```
and
```
hfla_site    | /srv/jekyll/_sass/components/_404.scss:112: Invalid CSS after "...r: $color-black": expected "{", was ";" (Sass::SyntaxError)
hfla_site    |  from /srv/jekyll/_sass/main.scss:39
```

Looking at the files changed portion, I'm noticing some odd-looking lines here in _404.scss : 
image

and here in github-actions/trigger-issue/add-missing-labels-to-issues:
image

Are you getting a similar error when trying to run docker-compose up?

**Comment by raswani2023** [comment]
@Wny-Duong I did not get any errors when running docker-compose up. Not sure why it is popping up for you but not for me. In regards to the odd-looking files, I am not sure why they are appearing like that. I am attending office hours now to get some help.

**Review by Wny-Duong — APPROVED** [review]
Changes fixed the docker issue I was seeing. Good work! Not too sure about why they're linter errors but they're not giving me any build or site errors from when I was reviewing it.

Note: The error from the linter check comes from the following outputs in the Lint SCSS / Lint SCSS (pull_request) check. These lines of code aren't involved in this issue and were never touched from the changes made.
```
 225:1  ✖  Unexpected duplicate selector ".resource-svg-icons", first used at line 120          no-duplicate-selectors
 230:1  ✖  Unexpected duplicate selector ".toolkit-info-container", first used at line 126      no-duplicate-selectors
 231:5  ✖  Unexpected duplicate selector ".toolkit-info-container h3", first used at line 130   no-duplicate-selectors
```

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-29

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct! Great job!! @raswani2023 
- Also, I am not getting any errors or seeing any as I read in the conversation above and the screenshots, but the linter check fails may be because of the previous 
[commit 85969e7d99663c624ec1480d2c832da25239e394], though it's fixed but you have other commits coming from previous issues in this PR.
noupdateerror
- Experienced: I went through the same problem earlier long time ago, while working on an issue, which in my case I forgot to update my repo with `gh-pages` (before creating branch) and I got other commits and merge conflicts and same linter check errors. But, It was not much lines of code so I closed my PR and opened new. 
- If someone knows how to fix through git command can resolve this.

**Review by Zak234 — APPROVED** [review]
Everything looks good. Great work!

**Pull request merged**
