### PR TITLE
Refactor HTML to Resolve Linter Error

### LINKED ISSUE #5286: Refactor HTML to resolve linter error: _includes/about-page/about-card-metrics.html
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-metrics.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about'>
```
to
```
<div class="card-primary page-card-lg page-card--about">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-metrics.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by efranzener**
Fixes #5286 

### What changes did you make?
- Updated the value of attribute [class] to be in double quotes.

### Why did you make the changes (we will use this info to test)?
- To resolve the linter error "Value of attribute [class] must be in double quotes".

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes to the website.

### CODE REVIEW

**Comment by ronaldpaek** [comment]
I plan to review this issue on Thursday, Sept 7th.

**Review by LRenDO — DISMISSED** [review]
Hi @efranzener!

Great job with this pull request!
- The branching was done correctly
- Issue number was listed
- The quotes were changed correctly
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I do have a few requests. Please make the following changes.
- [x] Delete the `/`after `alt=""` on line 3. It's likely that change was merged after you started working on the issue. 
- [x] Delete line 1 `refactor-html-fix-linter-error-5286`. Only the changes listed in the issue should be made.
- [x] Add the labels that are on the original issue to this PR request (usually this happens automatically, but sometimes it doesn't work. It generally fails when the issue number isn't added the when the PR is created.)

Once you've pushed the changes, you can click the circle with the arrows next to my name in the reviewers section to request a review of changes.

Thanks for taking the time to contribute to the website!

**Review by ronaldpaek — CHANGES_REQUESTED** [review]
Hi good job fixing what the increase says to fix. 

I also agree you should remove the text  refactor-html-fix-linter-error-5286 at the top of the file.

Oh I understand now, we had other issues removing the forward slash on img tag so if you could leave the img tag in it's original please.

Other than that fixing those issues and also adding the labels on the issue like Ren mentioned and you're good to go! :)

**Comment by efranzener** [comment]
Availability for this week: Monday - Friday: 3pm-5pm
My estimated ETA for completing this issue: Tuesday 9/12, by 9pm

**Comment by efranzener** [comment]
Hi @LRenDO  and @ronaldpaek!

Thank you both for your feedbacks.
As per your request, I applied the following changes:

- Deleted the / after alt="" on line 3.
-  Deleted line 1 refactor-html-fix-linter-error-5286
- Added the labels from the original issue to this pull request. 

Please let me know if there is any additional changes to be made.

**Review by ronaldpaek — APPROVED** [review]
Everything looks correct to me. Great job!

**Review by t-will-gillis — APPROVED** [review]
Hey @efranzener Great job- thanks for working with @ronaldpaek and @LRenDO to make the changes to the initial PR- everything looks good!

**Pull request merged**
