### PR TITLE
Separate codql.yml and create new issues workflows

### LINKED ISSUE #6691: Refactor codeql.yml file
### Overview

We need to refactor the `codeql.yml` file by moving the issue creation steps into a separate workflow so that developers don't receive confusing errors when they test CodeQL issues.

### Details 

Since we released the changes in https://github.com/hackforla/website/issues/5059, developers picking up CodeQL issues have encountered errors related to incorrect tokens and rate limiting. Since the three steps added by the changes in said issue aren't needed to test CodeQL issues, we need to refactor to ensure they do not block PR reviews and testing.

We want to refactor for the following reasons:

1. These errors seem to be confusing developers and result in a lot of unnecessary troubleshooting. 
   - One error is "Input required and not supplied: github-token." Right now, our documentation isn't up to speed and many devs don't know how to set up their `HACKFORLA_ADMIN_TOKEN` correctly. 
   - The other error happens when the CodeQL workflow runs and hits the GitHub API rate limit. This requires the dev to wait about an hour and run the workflow again. This is not an ideal situation for testing CodeQL issues, since the steps that hit the rate limit are not required for testing CodeQL issues.
   - Another error occurs because the developer does not have their Issues tab activated in their personal repo.
3. The errors may be preventing the CodeQL scan from running properly locally, which prevents people from testing properly.
4. We need to be able to test properly and confirm that when CodeQL alerts are resolved, they switch from Open to Closed.

### Action Items

- [ ] Separate the last three steps out of the codeql.yml file into a separate issue creation workflow.
- [ ] Modularize the workflows to minimize duplicate code
- [ ] Make the issue creation workflow triggered by a manual run only
- [ ] Test the above and ensure that the codeql.yml workflow scans issues and generates alerts as expected
- [ ] Test the above and ensure that the issue creation workflow generates issues and adds all labels as expected
- [ ] Demonstrate that when CodeQL issues are resolved locally, that their state/status switches from Open to Closed (this can be done using an existing CodeQL issue after the above changes are deployed)

### Resources/Instructions

- https://github.com/hackforla/website/issues/5059
- https://github.com/hackforla/website/pull/6503
- This is an issue where the testing concerns first arose: https://github.com/hackforla/website/pull/6651

### PR DESCRIPTION
**Pull request by w1ld-r**
Fixes #6691

### What changes did you make?

Inside the .github/workflows directory, I created/modified the following files:
  - Created `codeql-create-issues.yml` 
  - Modified `codeql.yml` by moving the bulk of its content to the job below
  - Created `codeql-scan-job.yml` <= This file is called by `codeql.yml` and `codeql-create-issues.yml` 
  - Modified `issue-body.md` to move the alert to its own action item line so that Github will create the association between the alert and the tracking issue

### Why did you make the changes (we will use this info to test)?
  - This will modularize our CodeQL workflows, making them more maintainable. 
  - Now, `codeql.yml` will be run during PR submissions, pull requests, and on a chron job, as it originally did. This will prevent the new issue creation steps from running under most circumstances and prevent unnecessary errors during PR reviews and testing on CodeQL issues.
  - `codeql-create-issues.yml` will only run when manually triggered 

### Screenshots of GHA
Screenshot 2024-04-30 at 6 23 50 PM

Screenshot 2024-04-30 at 6 23 26 PM

Screenshot 2024-04-30 at 6 23 41 PM

### Testing Notes
- [x] Run to CodeQL Scan workflow on your branch to create security alerts.
- [x] Delete some CodeQL issues if you already have some created so they can be recreated as part of the testing (you don't have to delete them all)
- [x] Add the following to the `codeql-create-issues` file to test. You'll need to change it to your branch When you push the changes, it should run automatically. Unfortunately, I think this is necessary because I can't seem to get the run workflow button to show up until the changes are deployed. 
```
on:
  push:
    branches: [ 'YOUR BRANCH' ]
```
- [x] Confirm that the `issue-trigger.yml` workflow runs, adds `missing` labels to the issues, and adds the issues to the project board. 
- [x] After you've tested the create issues workflow, remove `push` from `on` in the `codeql-create-issues.yml` file. Then update the branch to your branch under `push` in the `codeql.yml` file and push those changes to confirm that the create issues workflow DOES NOT run but `codeql.yml` does. This is the desired behavior.
- [x] I suggest we use an open CodeQL alert issue to test if we can see the alert status flip from open to closed when the issue is resolved. I'm not sure we can do this locally. I tried to test it on my personal repo, but the security alerts seem to be hardcoded to `gh-pages`. I can search for alerts on a branch, but I can't do much else. Let me know if you have any ideas.
- [x] I confirmed the unhappy path on this PR by temporarily adding an unused global variable to `fetch-alerts.js`. That triggered a CodeQL alert below. 
Screenshot 2024-04-20 at 2 00 18 PM

### CODE REVIEW

**Comment by w1ld-r** [comment]
Hey @t-will-gillis and @elliot-d-kim, this PR is still in draft only because I haven't gotten approval on the issue yet. Otherwise, it's pretty ready to review when you are. 

One note: For some reason, I am not able to get my issues to create unless I use `GITHUB_TOKEN` on the Create New Issues step of `codeql-create-issues-job.yml`. If I use `HACKFORLA_ADMIN_TOKEN`, I get the `Input required and not supplied: github-token` error. Can you try this out on your end and let me know if you have the same issue?  Also, I think my token issue is causing the `issue-trigger.yml` workflow to not run, so that part also didn't work for me.

Also, if you can't review this then feel free to take your name off. Thanks either way!

**Comment by t-will-gillis** [comment]
Update: have not had a block of time to look at this but hoping later in the week.

**Comment by elliot-d-kim** [comment]
Thanks for putting this together, @gaylem! I'll have more thoughts when I have time to look into this further Wednesday evening.

**Comment by t-will-gillis** [comment]
I have started testing- having the same problem you mentioned with the `GITHUB_TOKEN`. Will keep experimenting. It is weird because the workflow acknowledges that it is evaluating a secret token.

**Comment by w1ld-r** [comment]
Hey @elliot-d-kim, I'm moving this comment over here from the issue (#6691) so I can close out the comments there and get it prioritized. Let me know if you have any questions!

Do you have a `TEAMS` and a `HACKFORLA_PA_BOT` token set up in your personal repo? These are needed for the `issue-trigger.yml` workflow to run. Here are the scopes: 

```
  * to match the `HACKFORLA_BOT_PA_TOKEN` select:
    * public_repo (under 'repo')
    * admin:org_hook 
  * to match the `HACKFORLA_ADMIN_TOKEN` select:
    * public_repo (under 'repo')
    * admin:org_hook 
    * write:org (under 'admin:org')
```

Let me know if that resolves those errors for you.

Regarding the workflow runs, that's a good point. I personally think we should only run the issue creation workflow manually for now. Push isn't really necessary for this use case, and if we set the branch to the `gh-pages` branch, it will still run on private repos since devs have that branch, too. I updated the instructions to reflect this and will push a new commit for it, but let me know if you have any additional thoughts. Thanks for your help!!

**Comment by gaylem** [comment]
Hey @elliot-d-kim and @t-will-gillis I resolved the errors, this should work for you now if you pull down the changes and run the workflows on your personal repos. Let me know if you encounter any issues. Thanks!

**Comment by w1ld-r** [comment]
OK @t-will-gillis and @elliot-d-kim I'm super for real this time, it works. And I managed to refactor it further so it has fewer files and less duplication. Let me know when you test it out. I'm still waiting for the issue to be approved so we'll need to wait to merge until then anyway. Thanks!!

UPDATE: It's been prioritized, so review/approve away!

**Review by t-will-gillis — APPROVED** [review]
Hey @gaylem Fantastic work again! I tested this in my repo and it appears the CodeQL scan is working correctly, as is the separate Create Issues. I had no problems with the token or anything else. 

I noticed that on the issue body, you moved the alert ID to its own line and now the issue is linking up to the alert. I was able to take one of the [generated issues](https://github.com/t-will-gillis/website/issues/711), open and [merge a PR](https://github.com/t-will-gillis/website/pull/724), and have the [alert close](https://github.com/t-will-gillis/website/security/code-scanning/83) as 'Fixed'. 

I think this is ready- let me/us know if there is anything else to look at specifically.

Great job!

**Comment by elliot-d-kim** [comment]
Apologies for being a bit MIA! Was super busy but I'm looking forward to testing these changes sometime this weekend. Will update soon!

**Comment by elliot-d-kim** [comment]
> You'll need to change it to your branch When you push the changes, it should run automatically. Unfortunately, I think this is necessary because I can't seem to get the run workflow button to show up until the changes are deployed.

@gaylem On my end, the 'Run workflow' button shows up under the 'CodeQL Create Issues' workflow. Maybe the problem you ran into has to do with workflow_dispatch only working [if the file is on the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)? I set my test branch as the default branch and modified `codeql.yml` to trigger on pushes to the test branch, and CodeQL jobs worked as expected:
- On push, 'CodeQL Scan' is triggered and completes with no errors. 'CodeQL Create Issues' is not.
- 'CodeQL Create Issues' can be triggered manually and successfully creates issues; no errors.

Like @t-will-gillis, I took one of the [generated issues](https://github.com/elliot-d-kim/hfla-website/issues/54)*, opened and merged a [PR](https://github.com/elliot-d-kim/hfla-website/pull/66), and saw the alert switch from open to closed.

However, I did run into this error with the `move-closed-issue` job. Any thoughts on how to fix this?

<details>
<summary>Error: Parameter token or opts.auth is required</summary>

image

</details>

---

\* In my testing, the issues created in the repo don't link correctly to the corresponding local CodeQL alerts, but rather link to whichever random CodeQL alert in `hackforla/website` that happens to share the alert #. I just manually edited the links to connect them properly. I don't think this will be a problem in practice, since I doubt most contributors will be resolving issues generated locally in their repos. To address CodeQL problems, they can refer directly to the Security tab.

**Comment by w1ld-r** [comment]
> > You'll need to change it to your branch When you push the changes, it should run automatically. Unfortunately, I think this is necessary because I can't seem to get the run workflow button to show up until the changes are deployed.
> 
> @gaylem On my end, the 'Run workflow' button shows up under the 'CodeQL Create Issues' workflow. Maybe the problem you ran into has to do with workflow_dispatch only working [if the file is on the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)? I set my test branch as the default branch and modified `codeql.yml` to trigger on pushes to the test branch, and CodeQL jobs worked as expected:
> 
> * On push, 'CodeQL Scan' is triggered and completes with no errors. 'CodeQL Create Issues' is not.
> * 'CodeQL Create Issues' can be triggered manually and successfully creates issues; no errors.
> 
> Like @t-will-gillis, I took one of the [generated issues](https://github.com/elliot-d-kim/hfla-website/issues/54)*, opened and merged a [PR](https://github.com/elliot-d-kim/hfla-website/pull/66), and saw the alert switch from open to closed.
> 
> However, I did run into this error with the `move-closed-issue` job. Any thoughts on how to fix this?
> 
> Error: Parameter token or opts.auth is required
> * In my testing, the issues created in the repo don't link correctly to the corresponding local CodeQL alerts, but rather link to whichever random CodeQL alert in `hackforla/website` that happens to share the alert #. I just manually edited the links to connect them properly. I don't think this will be a problem in practice, since I doubt most contributors will be resolving issues generated locally in their repos. To address CodeQL problems, they can refer directly to the Security tab.

Hey @elliot-d-kim, thanks for the tip about the `workflow_dispatch`! I just found out about resetting the default branch yesterday so that makes sense. 

Regarding the error, I'm not completely sure what could be causing it. My best guess is that when the CodeQL issue flips from open to close, that triggers the `move closed issue` workflow, which requires the `HACKFORLA_PA_BOT_TOKEN`. Do you have a `HACKFORLA_PA_BOT_TOKEN` set up? The scopes should be as follows: 
    * public_repo (under 'repo')
    * admin:org_hook 

 Let me know if that helps or not.

**Comment by elliot-d-kim** [comment]
Thanks @gaylem, I added `HACKFORLA_BOT_PA_TOKEN` and it resolved the token error!

I ran into another token error in `issue-trigger.yml`. Looks like I need a `TEAMS` token, but I'm not sure what the scopes are.

<details>
<summary>Error in `Add-Missing-Labels-To-Issues`</summary>

image

</details>

The relevant lines in `issue-trigger.yml`:

```yml
#Checks which teams the user is on 
- uses: tspascoal/get-user-teams-membership@v3
  id: checkUserMember
  with:
    username: ${{ github.actor }}
    organization: 'hackforla'
    team: 'website-write'
    GITHUB_TOKEN: ${{ secrets.TEAMS }}
```

@gaylem Could you share the scopes for the `TEAMS` token? Also is there somewhere I can find the scopes myself? (So I don't have to bug you every time I need them!)

**Comment by w1ld-r** [comment]
Hey @elliot-d-kim, the scopes for `TEAMS` are:
- 'read:org' (under 'admin:org')
- 'read:user' (under 'user')

I don't think all of this is in the documentation yet :(

**Review by elliot-d-kim — APPROVED** [review]
Finally, I got everything to work as expected on my end!

- CodeQL runs on push, PRs, and cron without triggering issue creation
- Issue creation is triggered manually with the 'Run workflow' button
- After PR that resolves issue is merged, alert switches from 'open' to 'closed' status
- Once project board (copy from [hackforla/website/projects](https://github.com/hackforla/website/projects/7)) and tokens (`HACKFORLA_ADMIN_TOKEN`, `HACKFORLA_BOT_PA_TOKEN`, `TEAMS`) are set up, issue creation and closing workflows generate issues out of CodeQL alerts and move completed issues to QA, respectively.
- In issue body, corresponding alert is linked (for `hackforla/website`)

Branches and naming look good, issue linked, summary is descriptive and straightforward, website functionality is undisturbed. 

This looks ready for deployment, great work on this @gaylem!

**Comment by t-will-gillis** [comment]
>@gaylem Could you share the scopes for the TEAMS token? Also is there somewhere I can find the scopes myself? (So I don't have to bug you every time I need them!)

@elliot-d-kim @gaylem 

- FYI while we are waiting for the new Wiki, updates to the old one are happening at [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)  
- But more importantly, the latest version of "Hack for LA's GitHub Actions" is linked here:
[Hack for LA's GitHub Actions (most recent)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335) 
- In this document there are notes about ----> which scopes to give tokens <---- 
- See Tip 7 towards the end

**Comment by elliot-d-kim** [comment]
@t-will-gillis Awesome, thanks!

**Pull request merged**
