### PR TITLE
Add github-handle for Nga Do in civic-tech-jobs.md

### LINKED ISSUE #6126: Add github-handle for Nga Do in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Nga Do
```
with
```
- name: Nga Do
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by piecanoe**
Fixes #6126

### What changes did you make?
  - Added a github-handle line for Nga Do in the civic-tech-jobs.md file

### Why did you make the changes (we will use this info to test)?
  - Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by piecanoe** [comment]
Progress: Completed task
Blockers: n/a
Availability: 2 hours
ETA: If this pull request is accepted, the issue should be resolved and completed
Pictures (optional): n/a

**Comment by colin-macrae** [comment]
Availability: 2 hrs tomorrow and 2 hrs Saturday 
ETA: Saturday, 1/20

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @piecanoe,
Nice work on this issue! The PR is correctly done with the appropriate branch, and the issue is correctly linked.

Your summary is clear, and the source code modification is clean, and I confirmed it didn’t alter the visuals on the page. 

Just a few suggestions:

- Remove the extra bullet points in the 'What' and 'Why' summary sections.
- At line 103, there's an edit unrelated to the issue. The change alters how Slack is launched. 'Messages' open Slack in the browser, while 'archives' launch the desktop app with an option for browser use. Please revert this edit. We are encouraged to only make code edits that are specified in the issue's action items.

Once the changes are implemented, please re-request a review (using the arrows icon in the upper-right, next to my name). Thank you!

**Review by colin-macrae — CHANGES_REQUESTED** [review]
Hi @piecanoe, 

Thanks for taking this on!  The changes look great, except for the items @jphamtv mentiond.  So, I'm quoting him below: 

The PR is correctly done with the appropriate branch, and the issue is correctly linked.

Your summary is clear, and the source code modification is clean, and I confirmed it didn’t alter the visuals on the page.

Just a few suggestions:

- Remove the extra bullet points in the 'What' and 'Why' summary sections.

- At line 103, there's an edit unrelated to the issue.  Please revert this edit. 

Once the changes are implemented, please re-request a review (using the arrows icon in the upper-right, next to my name). 

Thank you!

**Comment by piecanoe** [comment]
### What changes did you make?
  - Reverted line 103 (now line 104) url. Link now directs to https://hackforla.slack.com/archives/C02509WHFQQ instead of https://hackforla.slack.com/messages/C02509WHFQQ

### Why did you make the changes (we will use this info to test)?
  - The initial change to line 103 was unintentional

**Review by jphamtv — APPROVED** [review]
@piecanoe thanks for updating the Slack link.

**Review by colin-macrae — APPROVED** [review]
Hi @piecanoe, 

Great job fixing the inadvertent changes.  The changes look correct, clean, and are according to the issue's instructions.  

The to and from branches are also correct.  

Excellent work, and thank you!

**Comment by LRenDO** [comment]
Hi @piecanoe! The request and updates look great! I have one non-functional request that was mentioned before. 

- [ ] Please edit the original pull request comment to remove unused bullet points. You can do this using the drop down menu `...` on the upper right corner of the original comment and clicking the `edit` option. 

<details>
<summary>Image of Dropdown Menu</summary>

image of dropdown

</details>

I am going to go ahead and merge this now since the change is non-functional, but when you have a minute please update the initial comment. Thank you for taking the time to contribute!

**Comment by piecanoe** [comment]
Hi @LRenDO, thanks for merging the pull request. I've edited the original pull request comment to remove unused bullet points.

**Comment by LRenDO** [comment]
Looks great @piecanoe! Thank you!

**Pull request merged**
