### PR TITLE
modified CONTRIBUTING.md

### LINKED ISSUE #5588: Remove "good second issue" from CONTRIBUTING.md Section 2.1
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove references to "good second issue" from CONTRIBUTING.md in order to avoid confusion, since we are no longer creating issues with the label `Complexity: good second issue'.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` and locate Section 2.1
- [x] Replace
```
2. `Complexity: Good second issue`
  *  Self-assign an issue with the `Complexity: Good second issue` label. 
  * Complete steps in [**2.7 Working on an issue**](#27-working-on-an-issue) to create a solution for the issue
  * Complete steps in [**3.1 How to make a pull request**](#31-how-to-make-a-pull-request) to get your solution reviewed by the `website-merge` team
  * Once your pull request is merged, you can work on your next issue.

Progress through issues with increasing complexity in the following order:
  1. Good first issue
  2. Good second issue
  4. Small 
  5. Medium 
  6. Large
```
with
```
2. Repeat #1 with a new `good first issue`

Progress through issues with increasing complexity in the following order:
  1. Good first issue (x2)
  2. Small 
  3. Medium 
  4. Large
  5. Extra Large
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4506

### PR DESCRIPTION
**Pull request by robertnjenga**
Fixes #5588

### What changes did you make?
  - Replaced:
  2. `Complexity: Good second issue`
  *  Self-assign an issue with the `Complexity: Good second issue` label. 
  * Complete steps in [**2.7 Working on an issue**](#27-working-on-an-issue) to create a solution for the issue
  * Complete steps in [**3.1 How to make a pull request**](#31-how-to-make-a-pull-request) to get your solution reviewed by the `website-merge` team
  * Once your pull request is merged, you can work on your next issue.

Progress through issues with increasing complexity in the following order:
  1. Good first issue
  2. Good second issue
  4. Small 
  5. Medium 
  6. Large
  - With:
  2. Repeat #1 with a new `good first issue`

Progress through issues with increasing complexity in the following order:
  1. Good first issue (x2)
  2. Small 
  3. Medium 
  4. Large
  5. Extra Large

### Why did you make the changes (we will use this info to test)?
  - to remove references to "good second issue" from CONTRIBUTING.md in order to avoid confusion, since we are no longer creating issues with the label `Complexity: good second issue'.
  
###  For Reviewers: 
- Do not review changes locally, rather review changes at https://github.com/robertnjenga/website/blob/issue-branch-5588/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes have been made.

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 10/4

**Comment by DorianDeptuch** [comment]
Availability: Weekday afternoons/evenings
ETA: EoD 10/5

**Review by Thinking-Panda — APPROVED** [review]
@robertnjenga nice work on this issue. Branches are setup correctly, code changes are as mentioned in the issue and clean. The changes are reflecting in the test link provided. Thank you!

**Review by DorianDeptuch — APPROVED** [review]
Hi @robertnjenga ,

Thanks for taking up this issue. You correctly stated what changes were mad, why they were made, and you linked to the updated template on your forked repo. It was a little hard to read through the "What" and the "Why" sections at first due to the formatting. The correct changes were made in the template and everything else looks good. Great job!

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @robertnjenga — good job with this issue so far! The branching is set up correctly, the corresponding issue is linked, the change of updating step 2 and the progression outlined in the `CONTRIBUTING.md` document has been made exactly as requested, and this change is reflected in your branch of the document.

Before I can merge this issue, there's just one change that should be made: can you remove the details and summary tags in the Screenshots section of your PR and instead state that no visual changes have been made? Doing this will help keep our documentation clean and easy to use (by indicating at a quick glance that there were no visual changes).

Once the PR has been correctly edited, I can merge this PR to the codebase; everything else is looking good so far!

**Review by adrianang — APPROVED** [review]
Hi @robertnjenga — thank you for making the edit in your PR! It looks good to me and everything else had stayed the same from the last review.

Thank you for taking up and completing this issue! 🙌🏼

**Pull request merged**
