### PR TITLE
aligned events page

### LINKED ISSUE #1393: Evenly align the Events page schedule times and days
### Overview
We need to edit the Events page schedule to match the Figma file and to look more visually aligned

### Action Items
- [ ] View and follow the instructions/notes for editing the Events page schedule in the [Events page figma file, in a purple rectangle](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94)

### Resources/Instructions
[Events Page](https://www.hackforla.org/events)
[Figma- Events Page edit notes](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (find detailed notes in purple rectangle, on bottom right of file)

### PR DESCRIPTION
**Pull request by sanchece**
Closes #1393

Events page schedule matched the Figma file to look more visually aligned

Before
image

After
image

### CODE REVIEW

**Review by akibrhast — DISMISSED** [review]

**Comment by akibrhast** [comment]
@sanchece Please provide a screenshot of what the affected changes look like. Also please link the issue that this PR is supposed to close using keywords such as `closes <ticket-number>`
Here is a guide on how to link issues from a PR
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by erikaBell — APPROVED** [review]
Adding photos of before and after in the future would be really helpful (-:
Seems good to me. Will let Danielle finalize ~

**Review by daniellex0 — DISMISSED** [review]
Look fantastic, approved- thank you @sanchece !

(and agreed with @erikaBell , please add screenshots next time 🙂 )

**Review by averdin2 — COMMENTED** [review]
@daniellex0 @sanchece To work on fixing spacing.

**Comment by daniellex0** [comment]
Hey @sanchece I think the space between the times and meeting names looks good with the .95fr 1.15fr we tried during the meeting-let's go with that. Thanks!

**Comment by sanchece** [comment]
> Hey @sanchece I think the space between the times and meeting names looks good with the .95fr 1.15fr we tried during the meeting-let's go with that. Thanks!

Updates from team review have been implemented. Ready to be merged @daniellex0 @akibrhast

**Review by averdin2 — APPROVED** [review]
@sanchece I don't know why I didn't think about this during the meeting, but I just realized we could have added grid-column-gap instead of changing the fr values 😅 . If @daniellex0 is happy with these changes though, then it looks good to me 👍

**Pull request merged**
