### PR TITLE
Fixes #6559: Update Project Profile: Add Gayle Martin to Merge Team

### LINKED ISSUE #6559: Update Project Profile: Add Gayle Martin to Merge Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Gayle Martin
    github-handle: gaylem
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U06HC3A0DM0'
      github: 'https://github.com/gaylem'
    picture: https://avatars.githubusercontent.com/gaylem
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by Ruizmichael**
Fixes #6559 

### What changes did you make?
  - Updated website.md with new team member's name, github-handle, role, slack link, github link, and picture to the end of the leadership variable

### Why did you make the changes (we will use this info to test)?
  - To update current project team list

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 4/11/23
Availability: Weekday evenings

**Review by pdimaano — APPROVED** [review]
@Ruizmichael Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was updated with the requested information. Well done!

**Review by elliot-d-kim — DISMISSED** [review]
Hey @Ruizmichael, this is looking pretty good!

- Branches and naming was done properly,
- issue is linked,
- screenshots look good,
- code looks clean and accurate!

The summary looks great overall as well and the only thing I'd do differently would be to specifically name the relevant team member, Gayle Martin, in the summary and the title. Checking out [similar issues](https://github.com/hackforla/website/issues?q=label%3A%22good+first+issue%22+is%3Aclosed+label%3A%22P-Feature%3A+Project+Info+and+Page%22) can help you get a good idea of best practices. You might also notice that there are several PRs that update project team members and details about their profiles -- specifying the team member helps us distinguish these PRs from each other.

Please update your PR accordingly, let me know if you have any questions!

**Review by jphamtv — APPROVED** [review]
Hey @Ruizmichael - Great work addressing the feedback from @elliot-d-kim to add the team member's name in the title to distinguish from other similar issues.

One small suggestion for future PRs: Remember to also update the summary with the team member's name, as requested.

Since this is a non-functional change, I'm going to approve and merge this PR. Keep up the great work and just keep that minor point in mind for future issues. Thanks for your contribution!

**Pull request merged**
