### PR TITLE
Make Slack links for Heart project consistent with other projects

### LINKED ISSUE #6512: Project Slack links: Heart
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to edit the Slack link for the project so that we have continuity between project Slack links.

### Action Items
- [x] In `_projects/heart.md`, for the Slack `url` under the `links` section, change 

From:
```
url: 'https://hackforla.slack.com/messages/CDWKEBYBB'
```
To:
```
url: 'https://hackforla.slack.com/archives/CDWKEBYBB'
```
- [x] Ensure that clicking the Slack link resolves to the new address at the following places:
  - [x] On the [Projects page](https://www.hackforla.org/projects/), the Slack link under the `Links` field for the project's card
  - [x] On the [Heart page](https://www.hackforla.org/projects/heart),
    - [x] the Slack link under the `Links` field in the Project Overview section
    - [x] the Slack link in the Resources/Instructions section 
- [x] Once your pull request is merged, go to #4564 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4564 to **Questions / In Review** column and add a **ready for dev lead** label to it

### Resources/Instructions
- Directory to find the page once you have it in your IDE: `_projects/heart.md`
- [Projects page](https://www.hackforla.org/projects/)
- Project page URL: https://www.hackforla.org/projects/heart
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
- This issue is tracked in #4564

### PR DESCRIPTION
**Pull request by Dartis4**
Fixes #6512

### What changes did you make?
  - Updated Slack link in heart.md.
 
### Why did you make the changes (we will use this info to test)?
  - To make the link consistent with the Slack links in other projects.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

N/A

### CODE REVIEW

**Comment by tony1ee** [comment]
**Review ETA**: EOD 04/14/2024
**Availability**: 5-8 PM SUN

**Review by tony1ee — APPROVED** [review]
Thanks for your contribution Dane!

Here's what you did great:
1. using the correct branch for pull request
2. correctly linking the issue
3. changes the slack link in the right file
4. no visual changes on the webpage (as expected), verified on Safari, Firefox and Chrome Desktop, Mobile and Tablet view in developer mode
5. code changes appeared applicable and clean

**Comment by Jperparas** [comment]
**availability:** 4/16
**eta:** eod 4/16

**Comment by LRenDO** [comment]
Hi @Jperparas! Thanks for volunteering to review this issue! When you have a minute, please update your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Comment by Jperparas** [comment]
Sorry @LRenDO! Had a power outage
updated **ETA:** EoD 4/17

**Review by Jperparas — APPROVED** [review]
Good Job @Dartis4 

1. Using correct branch for pull request
2. Proper Issue is linked
3. No visual changes
4. All changes applied correctly

**Pull request merged**
