### PR TITLE
Added 'test/' to ignorePaths array in cspell.json

### LINKED ISSUE #5848: Add "test/" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "test/" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [ ] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by naveenmallemala5**
Fixes #5848 

### What changes did you make?
  - Added 'test/' to ignorePaths array in cspell.json

### Why did you make the changes (we will use this info to test)?
  - To ignore files in the 'test/' path for spell checking.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
Hey @naveenmallemala5! Looks like the PR is currently linked to the wrong issue (it's currently pointing to itself). Can you edit the first line so it references the correct issue number (#5848)?

**Comment by naveenmallemala5** [comment]
Hi @kwangric, I've updated the first line with the correct issue number (#5848), Please review, merge and close the issue. Thank you !

**Comment by t-will-gillis** [comment]
Hey @colin-macrae and @naveenmallemala5 I will leave this message on both of your PRs. Since you are both waiting for your PRs to be reviewed- you could consider reviewing each other's in the meantime and then when they are ready one of us will be available to merge them. Your respective PRs are #6006 and #6004.

**Review by colin-macrae — APPROVED** [review]
@naveenmallemala5, great job. 

- The branch is going into the correct branch gh-pages. ✅
- The original issue [issue with #number] was properly referenced. ✅
- Per the instructions on the original issue, the correct code was added to cspell.json. ✅

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EOD 12/20

**Review by freaky4wrld — APPROVED** [review]
Hey @naveenmallemala5 thanks for taking up the issue, the changes suggested in the linked issue are done correctly, the to/from branch looks great. 

I approve this PR.....

**Pull request merged**
