### PR TITLE
Removed unused donation circle graphic file

### LINKED ISSUE #4456: Remove unused donation circle graphic file from donate images folder
### Dependency

- [x] #4263 
- [x] #4439

### Overview
We want to delete the unused `donation-chart.svg` so that we keep the file system clean and avoid confusion.

### Details
The donation circle graphic previously used on the Donate page has been replaced with HTML/CSS for improved readability and accessibility.

### Action Items
- [x] Delete the file `assets/images/donate/donation-chart.svg`
- [x] Use git to add and commit the change (deletion)
- [x] Using docker, confirm that the Donate [local page](http://localhost:4000/donate) matches the [live webpage](https://hackforla.org/donate) 

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- [unused donation graphic](https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/donation-chart.svg)
- This issue was created as a result of #4407 and is a part of epic #4492

### PR DESCRIPTION
**Pull request by klei0229**
Fixes #4456

### What changes did you make?
  - Deleted the file `assets/images/donate/donation-chart.svg`

### Why did you make the changes (we will use this info to test)?
  - This file was unused and we wanted to keep the file system clean to avoid confusion.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Deleted a file from a directory. No visual changes to the website.

### CODE REVIEW

**Comment by antho-zng** [comment]
Availability: Mon–Fri 9–6 ET
ETA: Sept 4 EOD

**Comment by tesiahwang** [comment]
Review ETA: 9/4/2023
Availability: flexible

**Review by tesiahwang — CHANGES_REQUESTED** [review]
Great job, @klei0229 - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue, and your change is applicable! One small note:
- When no visual changes are made, please remove the `<details>/<summary>` tags to keep your PR clean.

**Comment by LRenDO** [comment]
Hi @lateral-neck-stretch and @tkozek! Thanks for volunteering to review this issue! When you have a minute, please add/update your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Review by roslynwythe — APPROVED** [review]
@klei0229 I agree with the request of @tesiahwang to remove the broken images from the PR, but when that is complete, this PR is good to go.  The branches are setup correctly, the file change is correct, the PR describes the work, and it checks out in the browser.  Thank you!

**Comment by antho-zng** [comment]
@LRenDO @klei0229 Apologies for the delay on my end! Thanks to everyone who reviewed in my place—I'm going to go ahead and remove myself as a reviewer, but happy to revisit if an additional review would be helpful!

**Comment by klei0229** [comment]
@tesiahwang @roslynwythe Sorry for the delay on addressing the issue, I thought this issue had been resolved and closed and only recently saw that it was still open. Thanks for reviewing this. I have made the changes to the PR to remove the broken image tags.

**Review by tesiahwang — APPROVED** [review]
Thank you for making the changes, @klei0229! Everything looks good now!

**Pull request merged**
