### PR TITLE
Fix guide page

### LINKED ISSUE #1081: Wrap guide cards to the left in Toolkit page
### Overview
We need the bottom row of guide cards in the Toolkit page to be wrapped to the left, to bring it back to how it used to look before this page was standardized, and to conform with design standards.

### Action Items
- [x] Try to find a way to wrap the bottom row of guide cards to the left, instead of center, on the Toolkit page

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit)

Bad: 

Screen Shot 2021-02-21 at 9 34 20 AM

Good:

Screen Shot 2021-02-21 at 9 36 38 AM

### PR DESCRIPTION
**Pull request by evancchen**
Fixes #1081

### CODE REVIEW

**Comment by jbubar** [comment]
Hey @evancchen everything looks good with the code, but we (the developers) are curious what is happening with your commits.
Could you explain what you did?

Screen Shot 2021-02-28 at 11 50 16 AM

**Comment by Treidexy** [comment]
@evancchen This looks really good!

**Comment by evancchen** [comment]
I don't know why it's showing multiple commits

**Comment by qiqicodes** [comment]
Everything looks great. Ready to squash and merge.

**Review by qiqicodes — APPROVED** [review]
Ready to squash and merge.

**Pull request merged**
