### PR TITLE
Add multiple labels on "Suggest new feature/content" template.

### LINKED ISSUE #4481: Update labels: Issue Template: suggest-a-feature-or-new-content-for-hackforla-org
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/suggest-a-feature-or-new-content-for-hackforla-org.md`
- [x] Replace the following line
   ```
  labels: enhancement
   ```
   with
   ```
  labels: ['enhancement', 'role missing', 'Feature Missing', 'Complexity: Missing', 'size: missing']  
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  [REPLACE THIS TEXT AND BRACKETS WITH THE URL]

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/suggest-a-feature-or-new-content-for-hackforla-org.md`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by AHP15**
Fixes #4481 

### What changes did you make and why did I make them?

- In the file `.github/ISSUE_TEMPLATE/suggest-a-feature-or-new-content-for-hackforla-org.md`: 
    I replace the following line: `labels: enhancement`, with: `labels: ['enhancement', 'role missing', 'Feature Missing', 'Complexity: Missing', 'size: missing'] `
- I followed the instructions in this [issue](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931)

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process and will be used by reviewers to preview the updated template.
URL of the issue branch on the test Repository:  https://github.com/Abdessittir/website/issues/new?assignees=&labels=enhancement%2Crole+missing%2CFeature+Missing%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=suggest-a-feature-or-new-content-for-hackforla-org.md&title=

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/suggest-a-feature-or-new-content-for-hackforla-org.md`
- This issue is part of epic #4307

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 5/31 10 - midnight
ETA EOD 6/1

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @Abdessittir this PR looks very good.  The branches are setup correctly, the code change is correct and clean, and the template in your test repository displays the correct labels.  My only requests are 
- [x] change the title of PR to reflect the fact that you updated the labels on the "Suggest new feature/content" template.
- [x] copy the URL to the template in your repository, into the PR, replacing this text:   [REPLACE THIS TEXT AND BRACKETS WITH THE URL] which can be found under the heading "Link for Reviewers" above
Thank you!

**Comment by AHP15** [comment]
Thanks, changes implemented

**Review by LRenDO — APPROVED** [review]
Hi @Abdessittir! 

Nice work! As @roslynwythe mentioned, the code looks good and it looks like you have made the changes requested. Some of the highlights are below!

- the PR title has been changed to reflect the update
- template URL from your repo was added
- labels appear correctly in the link and match the HackForLA/website repo
- the issue is linked
- branches are correct

You may already know this, but I just learned that you can also request a re-review by clicking the refresh circle with arrows next to the reviewer. [Shown here in step 3.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)

Thanks for your contribution!

**Review by roslynwythe — APPROVED** [review]
Thank you @Abdessittir for making the request changes.

**Pull request merged**
