### PR TITLE
wins-feature-1 merge with gh-pages

### LINKED ISSUE #2138: Discussion to merge `wins-feature-1` branch
### Overview 
We need to determine whether we merge the `wins-feature-1` branch so that we can stop using feature branch instructions. The wins page is ready to merge now, but we should have a consensus to move forward with merging `wins-feature-1` branch.

### Action Items
- [ ] Discuss `benefits` of merging `wins-feature-1` branch
- [ ] Discuss `setbacks` for merging `wins-feature-1` branch
- [ ] Discuss the topic during a Front-End or Back-end meeting for further feedback
- [ ] Come to a consensus within the dev team about whether to merge the `wins-feature-1` branch

### Resources
#2135

### PR DESCRIPTION
**Pull request by jbubar**
Fixes #2138

### What changes have been made by the team over many months ??

  - adds icons in stead of a list of text
  - changes the styling of the modal and mobile
  - removes table view

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied (mobile: width 700px)</summary>

width-700-before

</details>

<details>
<summary>Visuals after changes are applied (mobile: width 700px)</summary>
  
screencapture-localhost-4000-wins-2021-08-19-23_05_16

</details>

<details>
<summary>Visuals before changes are applied (desktop: width 1000px)</summary>

width-1000-before

</details>

<details>
<summary>Visuals after changes are applied (desktop: width 1000px)</summary>
  
screencapture-localhost-4000-wins-2021-08-19-23_07_11

</details>

### CODE REVIEW

**Comment by jbubar** [comment]
Will have merge conflicts every day. could not figure out how to remove the json files from the pr

**Comment by jbubar** [comment]
This command is the one that I use to update the files
```bash
git checkout upstream/gh-pages -- _data/external/github-data.json _data/external/vrms_data.json
```

**Comment by Aveline-art** [comment]
@jbubar Thanks for following up with this! We will showcase this to the team on Sunday to ensure that it reaches the all-team standard for MVP before merging. Cross your fingers!

**Review by adam-abundis — APPROVED** [review]
@jbubar We went through this pull request during our 8/29 team meeting. Everything looks good. Thank you for all your work. Let's merge this branch. 🔥 🔥 🔥

**Pull request merged**
