### PR TITLE
Add program-area text to Resources section

### LINKED ISSUE #2277: Add Program Area: Curbmap
### Overview
We need to add program area information to the Curbmap project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Citizen Engagement
```

### Resources/Instructions
File location to make the change: _projects/curbmap.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/curbmap.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

### PR DESCRIPTION
**Pull request by answebdev**
Fixes #2277

### What changes did you make and why did you make them ?

The following changes were made to add program area information to the Curbmap project so that it will show up when we add the program areas filter:
- Reviewed the project.md file model in the Resources section
- Added the following text to the file indicated in the Resources section in the _projects/curbmap.md file:

```
program-area:  
    - Citizen Engagement
```

### Screenshots of Proposed Changes Of The Website
- Changes made in _projects/curbmap.md file, so no visual changes to the website.

### CODE REVIEW

**Review by lindseyindev — APPROVED** [review]
Great work this is formatted according to the project file template and in the right place!

I was able to confirm that this PR will update the file linked in the issue for testing by viewing that file on your forked repo of the website at this link: https://github.com/answebdev/website/blob/adding-text-to-resources-section-2277/_projects/curbmap.md
**Basically a note for any reviewers that come after me

**Comment by answebdev** [comment]
@lindseyindev Thank you for reviewing my PR and for confirming.

**Comment by SAUMILDHANKAR** [comment]
Estimated time to finish my review: 8 PM 2/21/22
Availability: Tuesday 7-8 PM Pacific Time

**Review by SAUMILDHANKAR — APPROVED** [review]
@answebdev Thanks for working on this issue. All looks good. Well done!
Just want to remind to add your PR to the project board while working on your next issue. I have added for this one. Thank you.

**Comment by answebdev** [comment]
@SAUMILDHANKAR Thank you, Saumil. And thank you for reminding me to add my PR to the project board. I'll be sure to add it next time.

**Pull request merged**
