### PR TITLE
Delete .github/workflows/schedule-monthly-PREV.yml

### LINKED ISSUE #4788: Fix bug that prevents GHA "Schedule Monthly" from running
### Prerequisites
1. Be a member of Hack for LA. If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need our GitHub Actions to run  as expected on the schedule that we have set so that our workflow is not interrupted. The GHA "Schedule Monthly" has failed on the last two scheduled runs and the error needs to be addressed.

### Details
When reviewing HfLA "Actions" logs on the repo, it can be seen that the GHA "Schedule Monthly" has attempted to run on schedule on the 1st of the month for the last three months. Both attempts have failed on the the job `list-inactive-members` on the step `Get List`.
A successful run of this GHA will result in an issue being generated on the HfLA Project Board similar to the following, as well as a notification comment being added to issue #2607. 

- #4567 

### Action Items
Suggested steps:
- [x] Compare the Action logs for the failed GHA on the HfLA repo with the similar logs on the personal repos for hints as to what might be causing the error(s).
- [x] Refactor the [schedule-monthly-PREV.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly-PREV.yml) and js files and/or any other files or settings (such as the tokens) as needed. >NOTE: the file will be renamed `schedule-monthly-PREV.yml` after #4768 is merged.
- [x] Create a demo Project Board and Personal Access Token for your repo- see [HfLAs GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) doc esp. Tips 6 and 7. 
  - [x] **Important note: be sure to give your secret token a different name than HfLA's token.**
- [x] Create at least one new issue on your Project Board and remember the number.
- [x] Given the different behavior of the GHA running on a personal repo versus the HfLA repo, add a `workflow_dispatch:` to Line 6 of the schedule-monthly.yml so that the action can be triggered immediately on the live site, i.e.:
```
on:
  schedule:
    - cron: "0 8 1 * *"
  workflow_dispatch:
```
- [x] **_Done_**   ~On_ the yml file, change line 11 `- uses: actions/checkout@v2` to `- uses: actions/checkout@v3` per #4735~
- [x] On the three js files, for testing only change any lines referring to `const owner = "hackforla"` to your own repo. (You will revert this before you open the PR.)
- [x] In [comment-issue.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/comment-issue.js) change `let agendaAndNotesIssueNumber = 2607;` to reference the issue you created. (You will revert this before you open the PR.)
- [x] Confirm with a test on your own repo. A successful test will create the 'Inactive Member' issue in your repo, and add the notification comment to the issue you designated.

### Resources/Instructions

- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml)
- [/list-inactive-members/](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/list-inactive-members)
- [workflow logs](https://github.com/hackforla/website/actions/workflows/schedule-monthly.yml)
- Review issues #4158 and PR #4545 

- Note: `schedule-monthly.yml` is intended to identify and remove "Inactive" members from 'website-write' team, which also addresses ER #4541

### LINKED ISSUE #5966: Delete obsolete file `schedule-monthly-PREV`
### Overview
This is a post-PR wrap up- `schedule-monthly-PREV.yml` is slated for deletion after merging PR #5467 

### Action Items

- [x] Delete `schedule-monthly-PREV.yml`. PR #5467 has consolidated its functionality and this file is no longer needed.

### PR DESCRIPTION
**Pull request by t-will-gillis**
Delete obsolete file, functionality incorporated in #5467

Fixes #5966 

### What changes did you make?
  - Delete `schedule-monthly-PREV.yml`

### Why did you make the changes (we will use this info to test)?
  - This GHA's functionality incorporated in to `schedule-monthly.yml` via #5467 fixes #4788

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes

### CODE REVIEW

**Comment by jphamtv** [comment]
Availability: Monday-Friday 12–2 PM, 8–10 PM (PST) 
Estimated ETA: 12/06/23

**Review by jphamtv — APPROVED** [review]
Hey @t-will-gillis,  the from/to branches are correctly set up, and the issue link is properly included. I checked out your branch and confirmed that the `schedule-monthly-PREV.yml` file has been successfully deleted from the `.github/workflows` folder as intended. Everything looks good to me!

**Review by freaky4wrld — APPROVED** [review]
@t-will-gillis it looks the deletion you performed is done correctly and the to/from branch looks good, and there's no visual changes, the file `schedule-monthly-PREV.yml` is done correctly.
Everything looks fine and I approve this!!

**Comment by t-will-gillis** [comment]
Thanks @jphamtv & @freaky4wrld !

**Pull request merged**
