### PR TITLE
Updated UI/UX CoP card

### LINKED ISSUE #3691: Communities of Practice information updates: UI/UX
### Overview
We want to update the information in the UI/UX CoP card so that the information is accurate.

### Action Item
- [x] In _data/internal/communities/ui-ux.yml, update the file to reflect the information written below:

  ### remove person(s)
  
  Name: Felicia Swafford
  Name: Kevin Wang
  
  ### Add person(s) 
  
  Name: Aparna Gopal 
  Title: Co-Lead
  GitHub Handle: Aparna1Gopal
  Slack Member ID: U0245UJP868
  
  Name: Julia Gab
  Title: Co-Lead
  GitHub Handle: juliagab56
  Slack Member ID: U03AS9FBAAU
  
### Resources
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice
- Link to UI/UX CoP card source card: https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml

### PR DESCRIPTION
**Pull request by angelenelm**
Fixes #3691

### What changes did you make and why did you make them?

  - Updated ```_data/internal/communities/ui-ux.yml``` to reflect current UI/UX CoP leadership

### Screenshots of proposed changes of the website (if any; please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

image

</details>

### CODE REVIEW

**Comment by Adastros** [comment]
Review ETA: 11PM 22NOV22
Availability: 9 - 11 PM 22NOV22

**Comment by jyaymie** [comment]
Review ETA: 11/23/22
Availability: 11/23/22 Flexible

**Review by Adastros — APPROVED** [review]
Good job @angelenelm! The UI/UX CoP leadership cards were updated with the correct information! Nice job on including clear screenshots of the changes too!

**Review by jyaymie — COMMENTED** [review]
This looks great, @angelenelm! You even put in the effort to find the information to update the `picture` property for each lead! For some reason, I am not able to see the visual changes on my end, but I'm pretty sure it has to do with me and not you. I'll get some support and hopefully submit my approval as soon as poss!

**Comment by angelenelm** [comment]
> This looks great, @angelenelm! You even put in the effort to find the information to update the `picture` property for each lead! For some reason, I am not able to see the visual changes on my end, but I'm pretty sure it has to do with me and not you. I'll get some support and hopefully submit my approval as soon as poss!

@jyaymie Thanks for reviewing! I ran into this issue as well, I had to follow the instructions in this section of the Contributing wiki (https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-what-if-you-cannot-see-your-changes-locally-within-docker) to get it to work!

**Review by jyaymie — APPROVED** [review]
You are a rockstar, @angelenelm! Thank you for your help!

**Comment by blulady** [comment]
PR goes from the correct branch to the correct branch. Has the correct issue link that is addressed by the PR. Code changes are clean. Communities of Practice page looks good when I deploy it locally. Looks good!! And nice job grabbing the links for the GitHub avatars.

**Pull request merged**
