### PR TITLE
Add aria label nav 4302

### LINKED ISSUE #4302: Add aria-label to header nav element
### Overview

The ARIA specification states that if a page includes more than one navigation landmark, each should have a unique label.  In this issue we will label the header navigation element to identify it as the primary navigation and distinguish it from the footer navigation element.  

### Action Items

- [x] The html for the header navigation can be found in _includes/main-nav.html
- [x] Change `<nav class="header-nav" id="headerNav">`
  to:
  `<nav class="header-nav" id="headerNav" aria-label="Primary">`

### Resources/Instructions
- [Nav Include](https://github.com/hackforla/website/blob/gh-pages/_includes/main-nav.html)
- [ARIA Authoring Practices Guide - Landmark Regions](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/)
- ARIA 1.2 Specification: [navigation landmark](https://www.w3.org/TR/wai-aria-1.2/#navigation)

### PR DESCRIPTION
**Pull request by amath95**
Fixes #4302 

### What changes did you make and why did you make them ?

  -Added the aria-label primary to nav to identify it as the primary navigation and distinguish it from the footer navigation element.

### CODE REVIEW

**Comment by bootcamp-brian** [comment]
Review ETA: 1pm
Availability: Today before 6pm

**Review by bootcamp-brian — CHANGES_REQUESTED** [review]
The issue is linked and the branches are set up so good work there. You made the requested changes from the issue but it also looks like you made additional changes as well. It doesn't look like the issue asked for any changes in the _includes/footer.html file from what I can see.

**Comment by amath95** [comment]
@bootcamp-brian That's weird that's from an issue I had taken up by accident. It wasn't placed in the backlog yet. How can I remove that? Undoing the changes in the file maybe? Please let me know if you have a solution.

**Comment by bootcamp-brian** [comment]
> @bootcamp-brian That's weird that's from an issue I had taken up by accident. It wasn't placed in the backlog yet. How can I remove that? Undoing the changes in the file maybe? Please let me know if you have a solution.

Hm, maybe you didn't sync your local repo with the main repo before you created the new branch for this issue so it still had the changes from the last issue you worked on? I think just undoing the changes in the other file should work but I'm not 100% sure tbh.

**Review by bootcamp-brian — APPROVED** [review]
Looks like that got rid of the changes to the other file so this issue should be good to go. Good work.

**Comment by amath95** [comment]
@bootcamp-brian yeah my branch was out of date I missed that. Nice catch!

**Comment by adevlinb** [comment]
Review ETA: by 4PM/PT today.
Availability: Until 5PM/PT today

**Review by adevlinb — APPROVED** [review]
Excellent work @amath95 

a) The issue is accurately linked.
 b) The pull request is descriptive. 
c) The branches are setup correctly. 
d) The changes are Applicable, do not Break the website, and are Clean.
 e) The changes can be seen in the browser and are as requested. 
f) The changes in the source code are as clean and concise as possible.

**Pull request merged**
