### PR TITLE
Update Team Meeting Data on the Events page to Show Meeting Frequency

### LINKED ISSUE #6920: Update Team Meeting data on the Events page to show meeting frequency
### Overview
Currently the Online Project Team Meeting section of Events page has Day, Start Time, End Time, Name of Project, and Name of Meeting. As some of the meetings do not happen weekly (like Onboarding), we need to mark those meetings and add a message to visit project page for more information.

### Action Items
- [x] Analyze and understand the data in `_data/external/vrms_data.json`
- [x] Update Team Meeting data on the Events page to add asterisk to the end of "Name of Meeting" if it's not weekly.
- [x] Add the following text to the end of the "Online Project Team Meetings" section.
     ```
     *This meeting is not weekly, check project link for more details.
     ```
- [x] Using Docker, check the changes on your local machine 

### Resources/Instructions
- [Event Page](https://www.hackforla.org/events/)
- [JSON Data File](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
- [Js File](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js)
- [HTML File](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html)
- This issue was created from #6320

### PR DESCRIPTION
**Pull request by terrencejihoonjung**
Fixes #6920 

### What changes did you make?
1. Modified `vrms_data.json` to include `"isWeekly": {boolean}` key-value pair based on meeting description's content
2. Conditionally rendering "&#42;", which is the HTML entity for an asterik based on isWeekly property for each event.
3. Mapping the isWeekly property within the `display_object` function to include this property for each event object
4. Added appropriate text at the end of the "Online Project Team Meetings" section

### Why did you make the changes (we will use this info to test)?
1. To utilize the new property for conditional rendering of the asterik.
2. To denote whether an event's meetings are weekly or not. 
3. To include the isWeekly property for each event object.
4. To clarify what the asterik siginifies for users.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

Before
>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After

</details>

### CODE REVIEW

**Comment by santiseccovidal** [comment]
Review ETA: 3 PM 6/26/24
Availability: 1-3 PM Wednesday

**Review by santiseccovidal — COMMENTED** [review]
Hi @terrencejihoonjung I have a question. My knowledge in front-end is limited.
When running the website with the changes I see in the events page the addition of:
"*This meeting is not weekly, check project link for more details."
However, I see no event with the * in the end like your function does when "isWeekly":false
Could you help me understand that?

**Comment by jphamtv** [comment]
Hi @jennisung - please provide your Review ETA and Availability when you have a moment. Thanks!

**Comment by terrencejihoonjung** [comment]
> Hi @terrencejihoonjung I have a question. My knowledge in front-end is limited. When running the website with the changes I see in the events page the addition of: "*This meeting is not weekly, check project link for more details." However, I see no event with the * in the end like your function does when "isWeekly":false Could you help me understand that?

Hi @santisecco,

Sure! The first thing I would do is make sure all my changes exist on your fork. This includes the modified JSON in `vrms_data.json`, checking that I am conditionally rendering "*", a.k.a "&#42",  within the `insertEventSchedule` function (`right-col-content.js`), and including the isWeekly property within the `display_object` function (`right-col-content.js`).

If there's anything about changes made specifically that you want to ask about, I'm happy to explain further!

**Comment by jennisung** [comment]
Review ETA:  By 10 PM 6/29/24
Availability: Saturday all day

**Review by jennisung — APPROVED** [review]
Great job! Everything looks good on my end in Docker, and I see the added text at the end of the Online Project Team Meetings page. I also noticed that you updated the team meeting data to incorporate the asterisk (*) notation for non-weekly meetings per issue #6920.

**Review by santiseccovidal — APPROVED** [review]
@terrencejihoonjung Thanks for the explanation! Yeah my question was more related to the JSON file.
Your explanation is clear, I had kind of understood what you were trying to do with `insertEventSchedule` but when I visualized in docker I couldn't see the "*" added. However, today I can see it displayed.


Screenshot 2024-06-29 100711


Displayed events seem to change on a week by week basis so last week, maybe, I saw all events that were "weekly" only, so no * added, or my data was not updated. If you look at your screenshot Thursday is different, with one more *.

Still I can see that the function works now also in my end. 
Great job, changes to the code are clear and accurate and you provided a clear and concise explanation of the reasons for the changes. You created the pull request with the correct branch.

Thanks for working on this and explaining!

**Comment by t-will-gillis** [comment]
NOTE: opened #7086 to revert this PR

**Pull request merged**
