### PR TITLE
Edit credit for data science image in feature-homepage-launch

### LINKED ISSUE #3331: Edit credit for Data Science image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Data Science credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/data-science.yml`,
  - [x] Change 
    `title-link: https://thenounproject.com/mb.icons/collection/artificial-intelligence-solid/?i=1705416` 
     to
     `title-link: https://thenounproject.com/search/?q=data+science&i=1705416`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'Data Science Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by ericvennemeyer**
Fixes #3331

### What changes did you make and why did you make them ?
Per the issue requirements, I made the following changes to `_data/internal/credits/data-science.yml`:
  - Change
`title-link: https://thenounproject.com/mb.icons/collection/artificial-intelligence-solid/?i=1705416`
to
`title-link: https://thenounproject.com/search/?q=data+science&i=1705416`
  - Change `content: icon` to `content-type: image`
  - Change `used-in: Home` to `used-in: Homepage`
  - Change `alt: 'Data Science Icon'` to `alt: ''`
  - Remove `type: icon`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-08-11 at 12 50 14 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-08-11 at 12 42 33 PM

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
ETA: 8/11/22
Availability: 4 hours

**Review by Wny-Duong — APPROVED** [review]
Changes look good and and the credits page entry for the image is functional. Great work.

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-08-12

**Review by arpitapandya — APPROVED** [review]
All the changes looks correct! Great job! @ericvennemeyer

**Comment by ericvennemeyer** [comment]
Thanks @arpitapandya and @Wny-Duong!

**Pull request merged**
