### PR TITLE
Lucky parking 2916

### LINKED ISSUE #2916: Fix misspelled words on lucky-parking.md file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_projects/lucky-parking.md`,  on line 56, change the spelling from "webapp" to "web app", so

  ```
  solution: Hack for LA’s Lucky Parking project seeks to map the 12.5 million parking citations on a webapp
  ```
  becomes
  ```
  solution: Hack for LA’s Lucky Parking project seeks to map the 12.5 million parking citations on a web app
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/citizen-engagement
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_projects/lucky-parking.md?plain=1#L56

### PR DESCRIPTION
**Pull request by eodero**
Fixes #2916

### What changes did you make and why did you make them ?

  -changed the double quotes around the links back to single quotes per H4LA standards. 
    

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>

<summary>Visuals before changes are applied</summary>

Before

</details>

<details>

<summary>Visuals after changes are applied</summary>

After

</details>

### CODE REVIEW

**Comment by matt-arofin** [comment]
- ETA: End of the day, 05/01/22
- Availability: 6pm - 8pm EST

**Review by matt-arofin — APPROVED** [review]
Hi @eodero,

I see that in addition to updating the spelling to 'web app' as originally requested by this issue you've been able to revert the double quotation marks back to single quotation marks. Great job applying the fix Adolf suggested, your code looks clean and properly formatted!

I did notice that you hadn't checked off the action items on the original issue, and hope you'll note it moving forward since it helps keep us all aware of how you're progressing 😄

**Comment by Carlos-A-P** [comment]
Availability: 1hr
ETA: 5/3/2022 EOD

**Review by Carlos-A-P — CHANGES_REQUESTED** [review]
Hey @eodero, make sure to add "no visual changes" under Screenshots and also move this pr to the project board.

**Comment by eodero** [comment]
> Hi @eodero,
> 
> I see that in addition to updating the spelling to 'web app' as originally requested by this issue you've been able to revert the double quotation marks back to single quotation marks. Great job applying the fix Adolf suggested, your code looks clean and properly formatted!
> 
> I did notice that you hadn't checked off the action items on the original issue, and hope you'll note it moving forward since it helps keep us all aware of how you're progressing 😄

Thank you @matt-arofin

**Comment by eodero** [comment]
> Hey @eodero, before I review this pr make sure to add "no visual changes" under Screenshots and also move this pr to the project board.

@Carlos-A-P , thanks for the pointers.

**Review by luke-karis — DISMISSED** [review]
Great Job working on this issue! The change to typo looks fixed to me. All that needs to be done is to change those double quotes back to single ones. Also, for this issue I think it would be actually be a good idea to include a before and after image because there are technically visible changes even if it is just fixing a typo.

Finally, once you've made these changes, don't forget to click the little circle of arrows next to each reviewers name, this will notify us that you're ready to have your code be re-reviewed!
Screenshot from 2022-05-02 22-22-51

**Comment by Carlos-A-P** [comment]
@eodero, I can see the code changes on my side, and everything looks good, awesome work! I previously said to include no visual changes, but that was my mistake since, for this issue, there are visible changes of the fixed typo, sorry about that. Make sure to include those screen shots under the before and after.

**Comment by Sparky-code** [comment]
Good Morning @eodero! Checking in to see if you're still working on this issue and if you had any questions? Please include an update to your availability and expected ETA for this issue in your reply.

**Comment by SAUMILDHANKAR** [comment]
@eodero Planning to close this PR due to inactivity. Please let us know when your availability changes. Will leave a slack message and email as well. Thanks.

**Comment by alan-zambrano** [comment]
@Carlos-A-P I was prepared to take this issue, but it seems all changes that were requested for the file have already been made? Is this issue only waiting on the screenshots? I can't seem to find the corresponding page to show a before/after, but the github readme has the same "webapp" typo https://github.com/hackforla/lucky-parking/blob/master/README.md

**Comment by Carlos-A-P** [comment]
@alan-zambrano the typo is visible on the following page: https://www.hackforla.org/citizen-engagement. You can take a screenshot of the before image from the hack for la site and an after image from your localhost. 

image

**Comment by alan-zambrano** [comment]
Got it, I've updated the visuals.

**Review by Carlos-A-P — APPROVED** [review]
@alan-zambrano thanks for making those changes and adding the screenshots, great job working on this issue!

**Comment by JessicaLucindaCheng** [comment]
@alan-zambrano I think there has been some confusion. Usually, the PR creator (in this pr @eodero) would be making any requested changes.

If you were looking for a "good first issue" to work on, see [Part 2: How the Website team works with GitHub issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues) in the CONTRIBUTING.md, especially section "2.3 Where can I find GitHub issues to work on?"

**Comment by SAUMILDHANKAR** [comment]
**Update:** Heard back from Erick on slack. Erick is planning to join back and share an update around Wednesday this week.

**Comment by SAUMILDHANKAR** [comment]
**Update:** Heard back from Erick on slack. Erick is planning to join back and share an update around Wednesday this week.

**Comment by eodero** [comment]
Sorry everyone for the the inconvenience, have my PC fixed now, reinstalling some programs and lost some directories which I need to reinstate. 

- availability 3 hrs
- ETA - 6/2/2022

**Comment by Sparky-code** [comment]
@eodero The code changes look good and I do see you included the visual changes (Thank you for highlighting the change!).

**Pull request merged**
