### PR TITLE
change single quotes to double quotes in order to resolve linter error

### LINKED ISSUE #5711: Refactor HTML to resolve linter error: _guidepages/2FA.html - line 46
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 45
- [x] Change the line of code
```
<a class='anchor' id='FAQ'></a>

```
to
```
<a class="anchor" id="FAQ"></a>

```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by aconstas**
Fixes #5711 

### What changes did you make?
  - Changed single quotes to double quotes for `anchor` class and `FAQ` id.

### Why did you make the changes (we will use this info to test)?
  - Per issue: "We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes""

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes made to the site.

### CODE REVIEW

**Review by jtw007 — DISMISSED** [review]
The branches are correct and the issue is linked.
The correct file was changed with the correct information.
I have inspected and confirmed the changes in my local IDE.

Nice job!

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @aconstas, 
- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear and helpful

Please revert the change on line 45, and remove the second bullet point from the "Why did you make changes" section. Although correct, please limit your changes to the scope of the issue. "Good first issues" typically involve single line/item updates to ease into our process. The update for line 45 is covered in another issue (#5710). 

After making the change, please re-request reviews using the circular arrows icon next to the reviewers' names.

Thanks!

**Comment by aconstas** [comment]
@jphamtv My apologies! That's good to know, thank you for the insight. I will update the PR now :)

**Review by jphamtv — APPROVED** [review]
@aconstas - Thanks for the update and great work! PR approved.

Please re-request a review by clicking the circular arrows icon next to the reviewer's name to get the second approval needed for merging.

Screenshot 2024-02-24 at 10 25 57

**Comment by aconstas** [comment]
@jphamtv Done. :)

**Review by jtw007 — APPROVED** [review]

**Comment by drakenguyen4000** [comment]
@aconstas, the issue is updated as requested, the issue is linked properly, and the pull request summary is detailed.  Nice job.

**Pull request merged**
