### PR TITLE
Issue 2600. Creates gradient image.

### LINKED ISSUE #2600: Apply new gradient overlay for Projects pages
### Overview
We need to use a new gradient for the hero-image overlay on Project pages so that it looks smooth, visually pleasing and is applied consistently to Project page hero images.

### Action Items
- [x] Identify where the [gradient image file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891) must be placed in the code repository. 
- [x] Make the code changes so that the gradient is applied on all the Project pages.
- [x] Check if the gradient looks good on each of the Project page and provide screenshots of all of them. 
  - [x] If it does not look good on all of them, identify the ones it does not look good on, and bring them to the team meeting to discuss, or address it directly with design.

### Resources/Instructions
- [Project Page Example: 100 Automations](https://www.hackforla.org/projects/100-automations)
- [HfLA figma, design system page, gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24996%3A285234&t=VH2yEoPVb8SMTAOs-0)
- Related issue #2312
- How to export the image from figma
  - Click on Export on the right side and download from there. 
image

<details>
<summary>Depreciated links - please ingore</summary>

- [Figma - Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11346%3A42)
- Here is the gradient image file: [Final Gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891)
- Location of the gradient in the [Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=7891%3A0) in a box underneath the 'final version' outlined in pink.

</details>

### PR DESCRIPTION
**Pull request by KazushiR**
Fixes #2600

### What changes did you make and why did you make them ?

  - Original issue called for a gradient image to be added. 
  - Added a gradient image to "assets/images/projects/gradient-background.png"
  - overlayed that gradient image to each project page, resulting in a more whiter tone with less color.
  - Changed css code in "_layouts/project.html" to help correctly set up the gradient image.
  - added the image to "_sass/components/_project-page.scss".

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
image
</details>

### CODE REVIEW

**Comment by KazushiR** [comment]
Please note that the images on the before and after images might be a bit long since it was requested that all project changes needs to be added into this PR. You might have to scroll down a bit to look through each change.

**Comment by jdingeman** [comment]
Hey @KazushiR - looks like there is a merge conflict. No worries, though. Try checking out the wiki [How to Resolve Merge Conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts) and see what you can do to resolve it.

**Comment by KazushiR** [comment]
> Hey @KazushiR - looks like there is a merge conflict. No worries, though. Try checking out the wiki [How to Resolve Merge Conflicts](https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts) and see what you can do to resolve it.

I saw the merge conflict and was wondering how to resolve it. I will look into this further. Thank you @jdingeman .

**Comment by KazushiR** [comment]
@patrickohh, @MattPereira, @jyaymie is there an update on the review? Is the PR incorrectly pushed out?

**Comment by jdingeman** [comment]
ETA: EOD 4/4
Availability: between 4pm and 6pm

**Comment by jdingeman** [comment]
Hey Kazushi, nice job on the adding the gradient. I am curious, though, the provided image seems to be making the image heros a bit "washed out" if you know what I mean? It seems like the gradient casts more blue over the image heros than what is currently on the website. I'd like a second opinion on this.

**Comment by bzzz-coding** [comment]
Availability: Wednesday and Thursday evenings
ETA: EOD 4/5/23

**Comment by jefflueck** [comment]
Availability: Wednesday afternoon and Friday afternoon CST
ETA: EOD 4/7/23

**Comment by jefflueck** [comment]
I also see the gradient seems to be applied a little too high on the y-axis. I am wondering if you add some opacity to the application of the gradient being applied might take some of this away to make it not as pronounced as it fades on the y-axis. Thoughts?

**Comment by jefflueck** [comment]
I also see the blue gradient overall seems to be "washing out" the pages in general. I am wondering if we applied some opacity to the gradient that would help dull the blue a little. I think that might help make it look a little more like a natural application of the gradient to the page.

I do like the gradient that you made for this, nice work! The color seems to be a good fit for the theme of the pages.

@KazushiR what are your thoughts on trying something like this?

**Comment by bzzz-coding** [comment]
@KazushiR Good job! I think you did what the issue asked for. 
However, when examining the commit history, I noticed this PR https://github.com/hackforla/website/pull/3664 that was merged and also provided a fix to issue #2600 by adding background gradient to the ::after pseudo element instead of adding a background image. @hackforla/website-merge I would appreciate your input on this. Thanks!

**Comment by MattPereira** [comment]
@bzzz-coding well done figuring out that there was a past PR that was merged to fix issue #2600 

My opinion is that the implementation from PR #3664 with the fancy CSS looks better than using the gradient image file 

We should investigate why issue #2600 was re-opened after a PR that solved the issue was already merged. Maybe there is some information that we are missing?

**Comment by KazushiR** [comment]
> I also see the blue gradient overall seems to be "washing out" the pages in general. I am wondering if we applied some opacity to the gradient that would help dull the blue a little. I think that might help make it look a little more like a natural application of the gradient to the page.
> 
> I do like the gradient that you made for this, nice work! The color seems to be a good fit for the theme of the pages.
> 
> @KazushiR what are your thoughts on trying something like this?

**Comment by KazushiR** [comment]
> @KazushiR Good job! I think you did what the issue asked for. However, when examining the commit history, I noticed this PR #3664 that was merged and also provided a fix to issue #2600 by adding background gradient to the ::after pseudo element instead of adding a background image. @hackforla/website-merge I would appreciate your input on this. Thanks!

@bzzz-coding I did not find that. Good catch on this. I am assuming that this issue does not need to be worked on and the PR and the Issue itself can be closed without any updates going forward. Please correct me if I am wrong @MattPereira.

**Comment by MattPereira** [comment]
@KazushiR 

Feels real bad that you ended up in this situation expending time and effort on a PR that might not be merged. I definitely don't want to keep you stuck on this issue, but I'm not sure if I have the authority to make the final decision

I just communicated this to the dev leads to try and get this sorted as soon as possible

**Review by bzzz-coding — APPROVED** [review]
Approving this PR because @KazushiR followed the instructions from issue #2600. Good job, Kazushi!

**Comment by KazushiR** [comment]
> @KazushiR
> 
> Feels real bad that you ended up in this situation expending time and effort on a PR that might not be merged. I definitely don't want to keep you stuck on this issue, but I'm not sure if I have the authority to make the final decision
> 
> I just communicated this to the dev leads to try and get this sorted as soon as possible

Understood. Thank you for the assistance. I will be in touch with them to see if this issue can be closed out or not

**Comment by KazushiR** [comment]
> I also see the blue gradient overall seems to be "washing out" the pages in general. I am wondering if we applied some opacity to the gradient that would help dull the blue a little. I think that might help make it look a little more like a natural application of the gradient to the page.
> 
> I do like the gradient that you made for this, nice work! The color seems to be a good fit for the theme of the pages.
> 
> @KazushiR what are your thoughts on trying something like this?

@jefflueck I believe the gradient image is something that is handled through the UX Design team and not through us. This issue might be an old issue and this PR along with the issue might be deprecated. I believe we will have to see what the leads say about this particular issue.

**Review by MattPereira — APPROVED** [review]
@KazushiR 

I talked to merge team about the situation and we decided it would be unfair to not give you the merge credits since you worked hard on this issue. Justin will approve and merge soon so that we can let Bonnie make the final decision in the QA column later

Apologies for all the confusion and waiting

**Comment by jefflueck** [comment]
I put myself in the wrong spot, so that's why it is now requesting a review.

I did not realize after seeing the comments from @bzzz-coding and @MattPereira that this was a more complex issue than I originally thought. 

I will also approve the changes.

**Review by jefflueck — APPROVED** [review]
I put myself in the wrong spot, so that's why it is now requesting a review.

I did not realize after seeing the comments from @bzzz-coding and @MattPereira that this was a more complex issue than I originally thought.

I will also approve the changes.

**Comment by KazushiR** [comment]
> @KazushiR
> 
> I talked to merge team about the situation and we decided it would be unfair to not give you the merge credits since you worked hard on this issue. Justin will approve and merge soon so that we can let Bonnie make the final decision in the QA column later
> 
> Apologies for all the confusion and waiting

Alright, thank you for the assistance on this. This was a learning experience so it's all good.

**Comment by KazushiR** [comment]
> I put myself in the wrong spot, so that's why it is now requesting a review.
> 
> I did not realize after seeing the comments from @bzzz-coding and @MattPereira that this was a more complex issue than I originally thought.
> 
> I will also approve the changes.

@jefflueck Thank you for the suggestion on this but this is turning into a more complex issue then expected. I appreciate your quick response on this.

**Review by jdingeman — APPROVED** [review]
Approving for merge. Thank you @KazushiR !

**Pull request merged**
