### PR TITLE
GHAs Remove Merged PRs from Project Board 

### LINKED ISSUE #2592: GitHub Actions: Remove merged PRs from the Project Board
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want the cards of the merged pull requests to automatically be removed from the Project Board.

### Action Items

- [x] Review the notes below to understand the GitHub actions architecture we are currently moving towards
- [x] This should be a new job under the ["PR Trigger" workflow](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/pull-request-trigger.yml)
    - [x] This job should trigger whenever a PR is merged
    - [x] This job should have an if statement that triggers when the event name is "pull_request" and event action is "merged" 
        - if: ${{ github.event_name == 'pull_request' && github.event.action == 'merged'}}
    - [x] This job should run in parallel with other actions that may exist in the trigger file
  
### Pseudo-code

- [x] When a pull request is merged
    - [x] Remove the pull request from the project board.

### Checks

- [x] Test in your local environment that it works
- [x] If a reviewer merges a pr and does not remove the pr from the Project Board, the GitHub action should automatically remove the pr from the Project Board
- [x] If a reviewer merges a pr and moves it to the Project Board, the GitHub action should move it to the correct column in the Project Board and then remove it
- [x] If the column the pr is going to has automation turned on, the GitHub action should still trigger and remove the issue without causing any weird issues / side effects

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes
Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #2592

### What changes did you make and why did you make them ?

  - **PLEASE READ FIRST**: This GitHub Action will **NOT** work with the revised 'Projects'. It will only with 'Project (classic)' i.e. the same as HfLA is using. This Pull Request should only be reviewed / tested by someone who can access 'Projects (classic).'
  
  
  - Edits are to `pull-request-trigger.yml` file. 
    - This file includes two new jobs:  `Move-PR` is intended to find all closed and 'merged' PRs and gather them in a single column immediately prior to the next step. `Delete-Merged-PRs` then deletes all 'merged' PRs from this same column. 
    - (Note that there may be a way to combine these two jobs into a single one.)
  - I was able to create a mockup of the HfLA 'Project Board' but I was only able to partially test this action. However, the `alex-page/github-project-automation-plus` automation does not appear to work with the new 'Projects' (for example, the automation is looking for an object `project` , but for the new 'Projects' it is `projects_v2`, which the automation does not recognize.)
  - This automation is also used in the `move-closed-issues` action, which itself is working once again now that the token/ secrets have been reset. 

 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by jdingeman** [comment]
Availability: Saturday 1/21, M-F after 3pm
ETA: Depends on outcome of demonstration by developer.

**Review by jdingeman — CHANGES_REQUESTED** [review]
Per our discussion, I am requesting changes so that developer can test within his own copy of the Projects (classic) in his own repo. Leaving this in PRs so we can track changes in code if applicable.

**Comment by t-will-gillis** [comment]
Update: The initial testing has been successful: 

- merged PRs are moving to the correct columns and ultimately are deleted from the Project Board. 
- deleting the issue for the merged PR does not affect the changes referenced by the PR itself

Now reviewing to make sure the branch, token, and other references are correct

**Comment by t-will-gillis** [comment]
- I added the step `needs: Move-PR` to the job `Delete-Merged-PRs` to ensure that the move job occurs before the delete job.
- I made many adjustments to the `pull-request-trigger.yml` file for the purposes of testing. These will need to be reverted prior to merging, mainly I added a local:  branch reference, token, and project board name. 
- Need to discuss the similar action `wr-pull-request-trigger.yml`: what is the purpose/ intent for the WR actions? 
- Finally, I believe that this implementation only affects future issues. Do we want/need a `workflow-dispatch` to take care of existing merged prs, or simply delete each manually?

This is not ready to merge yet. @jdingeman do you want to arrange for us to do a live demo?

**Comment by MattPereira** [comment]
Availability: Today 4 - 5 PM
ETA: TBD after meeting at 4 today

**Comment by jdingeman** [comment]
Developer demonstrated workflow and will clean up the branch so we can do a clean test on the HfLA gh-pages.
Notes:
- Workflow only affects PRs that have merged _since_ its implementation -- it will not remove any old PRs from the board
- PRs will remain in the repo, and they are not hard deleted from the repo, they are only removed from the project board as if they were archived (but still working)
- Suggested dev remove 'feature-homepage-launch' from the pr trigger file to prevent feature branch merges from being removed from the board. See comment [here](https://github.com/hackforla/website/issues/2592#issuecomment-1335942513)
  - This can make way for a new issue to move feature branch merges to the correct column instead of being sent to 'test-approved-by-reviewer'

**Comment by t-will-gillis** [comment]
I am closing this PR, then opening a new PR under a clean branch.

**Comment by t-will-gillis** [comment]
Moved this to column 'IGNORE: PRs closed without being merged' since this PR was replaced.

**Pull request closed without merging**
