### PR TITLE
move script to an external javascript file

### LINKED ISSUE #2480: Refactor JavaScript: Move script from citizen-engagement.html to external file
### Overview
JavaScript is much more maintainable and reusable if it exists in an external folder, rather than including it into the html doc. Please make a new file and place all required JS there. 

### Action Items

- [x] Create a new file [here](https://github.com/hackforla/website/tree/gh-pages/assets/js) and name it citizen-engagement.js

- [x] Remove the JavaScript from this [page](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html) and replace it in the citizen-engagement.js file

- [x] Add the JS file to the html page in a script tag

- [x] Adjust changes between the files mentioned in this issue such that the website appears the same visually

- [ ] Release dependency on https://github.com/hackforla/website/issues/2887

### Resources/Instructions
[Here](https://github.com/hackforla/website/issues/2058) is the issue that helped me make this issue. The reference files for that issue is [here(html doc)](https://github.com/hackforla/website/blob/gh-pages/pages/project-meetings.html) and [here(js file)](https://github.com/hackforla/website/blob/gh-pages/assets/js/project-meetings.js).

[How do I include liquid/global variables defined using Jekyll in a Javascript file?](https://stackoverflow.com/questions/58517425/how-do-i-include-liquid-global-variables-defined-using-jekyll-in-a-javascript-fi)

The html doc for this issue is [here](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html).

If you have any questions, feel free to ping me on the HackforLA slack - Tomas Gonzalez. 

**Architecture Notes**
The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our assets/js directory with these specifications:

In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
In the elements sub-directory, the js fjiles should correspond to code needed for our design system elements to function.
In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.
That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

### PR DESCRIPTION
**Pull request by JasonY188**
Fixes #2480

### What changes did you make and why did you make them ?

  -Create a new file citizen-engagement.js
  -Remove the JavaScript from citizen-engagement.html and place it in citizen-engagement.js
   -Add the JS file to the html page in a script tag
   -JavaScript is much more maintainable and reusable if it exists in an external folder, rather than including it into the html doc

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>

There are no visual changes.

<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 3 hours
Review ETA: Friday, Feb 25, 2022

**Review by tamara-snyder — CHANGES_REQUESTED** [review]
Really well done, Jason! I can see that you moved the JavaScript code into its own file and created a script tag to link the new file. The website still functions as normal. 

However, in moving the code to its new file, the formatting got a little wonky.
In [assets/js/citizen-engagement.js](https://github.com/hackforla/website/pull/2882/files#diff-912a49af31271bff744d097387d37a870821e2fbdec822bf3e38d82543bc540d), please do the following:
- [ ] Delete line 1 so that `document.addEventListener('click', (e) => {` is on the first line
- [ ] Select all the text and unindent it once (you can press Shift + Tab to accomplish this)

Once you've done those two things, please re-request a review. Again, great work on the rest of this issue!

**Comment by JasonY188** [comment]
Hi Tamara - Thanks for the feedback.

**Review by tamara-snyder — APPROVED** [review]
Looks great and everything still works! Thanks for the quick fix.

**Comment by usaboo** [comment]
ETA - Feb 28th, Monday
Availability - Sunday, Feb 27th 9PM - 11PM EST

**Review by usaboo — APPROVED** [review]
I see that the required changes have been made, including the creation of a separate citizen-engagement.js file for reusability and also the script tag in the citizen-engagement.html file looks correct. Docker view of the website is the same as before so I'd sayyou've done a good job.

**Pull request merged**
