### PR TITLE
Added github-handle variable to Salima Yacoubi

### LINKED ISSUE #5715: Add new variable github-handle to member Salima Yacoubi in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md ` in your IDE
- [x] Replace:
```
- name: Salima Yacoubi 
```
with
```
- name: Salima Yacoubi 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [ ] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by iancooperman**
Fixes #5715 

### What changes did you make?
  - Added a variable called `github-handle` under Salima Yacoubi's record within the associated file.

### Why did you make the changes (we will use this info to test)?
  - "Eventually `github-handle` will replace the github and picture variables, reducing redundancy in the project file."
  
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by MattChau01** [comment]
ETA: EoD 1/20
Availability: Weekends

**Review by jphamtv — APPROVED** [review]
Hey @iancooperman, thanks for working on this issue. The PR is correctly done with the appropriate branch, and the issue is correctly linked. Your summary is clear, and the source code edit is clean and there were no visual changes to the page. Great work!

**Comment by freaky4wrld** [comment]
ETA: EOD 1/19/24
Availability: Evenings

**Review by freaky4wrld — APPROVED** [review]
@iancooperman thanks for taking up the issue, changes made by you are apt and showed the desired effect to the site hosted locally, the to/from branches looks good and the linked issue is correct as well.... good to go from my side

PR approved!!

**Pull request merged**
