### PR TITLE
Updated contributing.md 3.1.b VI

### LINKED ISSUE #5696: Update CONTRIBUTING.md Section 3.1.b vi
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
### Overview
In [CONTRIBUTING.md "vi.  after pull request is submitted/merged"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#vi-after-pull-request-is-submittedmerged) we need to remove duplicate statements about removing an issue branch following PR merge, in order to avoid confusion. 

### Action Items
- [x] In your local IDE, navigate to CONTRIBUTING.md 3.1.b, under "vi. After pull request is submitted/merged"
- [x] Remove the lines
<pre><code>
Now you can move on to your next issue and create a new branch. (This ensures you don’t accidentally include the changes from your previous branch in your new branch)

From here, once your pull request is approved and merged you can pull the recent merge from the Hack For LA repository and delete your local branch:

```bash
git pull upstream gh-pages
git branch -d update-give-link-2093
```

Managing branches this way will keep the commit logs cleaner on the Hack For LA repository, versus merging your completed feature branches into your local repo.
</pre></code>

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md "vi.  after pull request is submitted/merged"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#vi-after-pull-request-is-submittedmerged)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by james-aguirre**
Fixes #5696

### What changes did you make?
  - Updated text in contributing.md documentation section 3.1.b VI to remove duplicate statements.

### Why did you make the changes (we will use this info to test)?
  - To improve clarity for future readers.
  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/james-aguirre/website/blob/update-contributing-section-31b-5696/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-12-01 at 5 06 00 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-12-01 at 5 05 11 PM

</details>

### CODE REVIEW

**Comment by Tomomi-K1** [comment]
ETA: 12/2 15:00
Availability: Weekday 12-5pm

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
@james-aguirre Thank you for taking up this issue!😆 You correctly put a linked issue in the pull request, you used correct branches and you deleted requested section from CONTRIBUTING.md.🙌🏻

I have one small request, original issue requests you to put comment for reviewer under "Why did you make the changes" section.  Please follow this section and leave a link for a reviewer.
image

**Comment by james-aguirre** [comment]
@Tomomi-K1 Hi Tomomi, PR has been updated to include a link to the test server. Thanks for the review!
Screenshot 2023-12-02 at 6 05 00 PM

**Comment by Tomomi-K1** [comment]
@james-aguirre Thank you for updating a pull request.😊  I might be being too picky about this, but  as the issue instruction said, could you put, "For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]" under "Why did you make changes", not under "What changes did you make?" so that it is obvious for reviewers where to check at one glance. 
Thank you for your help! And After you update, please click button to request re-review as shown below. If you have any questions, let me know I'm on slack with same first name.
image

**Comment by pdimaano** [comment]
ETA: 12/7/23
Availability: Weekday evenings

**Comment by roslynwythe** [comment]
Hi @james-aguirre thank you for including the test URL for the convenience of reviewers.  To avoid confusion, please remove the square brackets surrounding the test URL.  Thanks!

**Review by Tomomi-K1 — COMMENTED** [review]
@james-aguirre Please check @roslynwythe comment and remove [ ]. Thank you for updating it several times!!😊

**Review by Tomomi-K1 — APPROVED** [review]
@james-aguirre Great job! Thank you for updating the pull request several times!!

**Review by t-will-gillis — APPROVED** [review]
Hey @james-aguirre Great job on the PR! You have the correct branches, a link back to the original issue, a succinct description of the changes you made and why, appropriate screenshots, and your code edits address only what needs to change. Thanks for working with @Tomomi-K1 and thanks for improving the `CONTRIBUTING.md` document.

**Pull request merged**
