### PR TITLE
Update project profile 311 data 5856

### LINKED ISSUE #5856: Update Project Profile: 311 Data (Remove Eric Cho & Prasadh Palanichamy, Add Sanju Venugopal & Christopher Cotton)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Eric Cho
    github-handle: 
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U02E95SPK4N'
      github: 'https://github.com/echoproject'
    picture: https://avatars.githubusercontent.com/echoproject
```
- [x] Find the `leadership` variable and remove the following:
```
  - name: Prasadh Palanichamy
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U0143158U80'
      github: 'https://github.com/pras4u'
    picture: https://avatars.githubusercontent.com/pras4u
```
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Sanju Venugopal
    github-handle: sanjumv
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05KFTD3AKA
      github: https://github.com/sanjumv
    picture: https://avatars.githubusercontent.com/sanjumv
```
- [x] If there are other Product Managers, place Sanju Venugopal's profile after the other Product Managers' profiles
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Christopher Cotton
    github-handle: CottonChristopher
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05MQ8CB2S1
      github: https://github.com/CottonChristopher
    picture: https://avatars.githubusercontent.com/CottonChristopher
```
- [x] If there are other Product Managers, place Christopher Cotton's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
- [x] Once your pull request is merged, go to #5786 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5786 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #5786
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data

### PR DESCRIPTION
**Pull request by soleilherring**
Fixes #5856 

### What changes did you make?
-added Saju, Christopher and deleted Eric, Prasadh
### Why did you make the changes (we will use this info to test)?
- update project managers

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-11-06 at 8 53 53 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-11-06 at 9 17 28 PM

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 11/9/23
Availability: Weekday evenings

**Comment by ronaldpaek** [comment]
ETA: 11/7/23
Availability: Will look at it today

**Comment by ronaldpaek** [comment]
@soleilherring I noticed it was giving my merge conflict errors, so I checked out your branch and I am still getting the issue, i'm not why that is happening, but I think you might have to manually resolve the conflict either through your vs code or directly on github.


CleanShot 2023-11-07 at 17 48 52@2x

**Review by ronaldpaek — CHANGES_REQUESTED** [review]
@soleilherring I noticed it was giving my merge conflict errors, so I checked out your branch and I am still getting the issue, i'm not why that is happening, but I think you might have to manually resolve the conflict either through your vs code or directly on github.

image

**Comment by soleilherring** [comment]
@ronaldpaek Thanks for letting me know! I've fixed it. Can you let me know if it's still causing you issues? Thanks for showing the exact error you were receiving :)

**Review by ronaldpaek — APPROVED** [review]
@soleilherring I just pulled in your newest changes I'm not getting merge conflict anymore and I pulled up local instance and the current project team list shows the correct names, excellent work on fixing the merge conflict issue and taking on this issue! :)

**Review by pdimaano — APPROVED** [review]
@soleilherring Thank you for handling the merge conflict. The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed with the appropriate information. Well done!

**Pull request merged**
