### PR TITLE
Update img tag in win-card-template. Issue#5041

### LINKED ISSUE #5041: img Tag Refactor: wins page - wins-card-profile-img
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/wins-page/wins-card-template.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="wins-card-profile-img" alt="" />
```
to
```
<img class="wins-card-profile-img" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: [INSERT LINK TO FILE]
2. Webpage(s): [INSERT LINK TO PAGE ON WEBSITE HERE]
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by locb65**
Fixes #5041 

### What changes did you make?
  -  Removed / from win-card-profile in win-card-template

### Why did you make the changes (we will use this info to test)?
  - To make img tag consistent with other img tag in source code

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No Screenshots

### CODE REVIEW

**Review by one2code — CHANGES_REQUESTED** [review]
@locb65, I can see that you've made the correct change to the `wins-card-profile-img`, and you've merged into the correct branch with a well-named issue branch. I'm going to ask you to take the time to check off the action items on the issue, and be mindful of the markdown formatting in the PR template. As the complexity of the issues you challenge grows, clean formatting and clear communication become in PR's becomes paramount.

**Comment by Tomomi-K1** [comment]
Review ETA: 8/13/2023 4pm
Availability: Mon-Fri 12-8pm

**Review by Tomomi-K1 — CHANGES_REQUESTED** [review]
@locb65, Thank you for taking up this issue.  Your pull request contains correct branch and have a correct linked issue. You have removed slash from the correct image tag.
As [one2code](https://github.com/one2code) mentioned, If you could clean up the pull request, it will be perfect!
you can clean up the PR by :

- removing unused bullet point 
- matching the font size and format of `-To make img tag consistent with other img tag in source code` to `Removed / from win-card-profile in win-card-template`  

After you make an update, please re-request review by clicking re-request button that appears next to reviewers avatar picture. I attached the screen shot below:
image
)

**Review by Tomomi-K1 — APPROVED** [review]
@locb65 Thank you for updating the pull request! 
Using Docker, I also confirmed that the page remains the same in mobile, tablet, and desktop.
Everything looks great!  

One more request, please also request re-review by clicking the `re-request review` button next to one2Code(Travis)? so he can also review your updated PR. 

Thank you again! Have a great week!

**Review by one2code — APPROVED** [review]
Thank you @locb65 for being patient and making all of the requested changes, and congratulations on your first pull request!

**Pull request merged**
