### PR TITLE
Update multiple GHAs about PRs

### LINKED ISSUE #5493: Confirm dependabot version update to pr-instructions.yml
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
Our repo's [dependabot](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) periodically checks the packages/dependencies used in our codebase to see whether a more recent version is available. When it finds an updated version, the dependabot creates a PR specifying which files will be affected if the package/dependency is updated. We need to check each of these files individually to determine whether we should or should not switch to the latest version. 
### Action Items
Refer to the [pr-instructions.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/pr-instructions.yml) file and review the version update(s) recommended by the dependabot.
   
- [ ] Make sure that you have configured your private repo for testing GHAs. See "Details" above.
- [ ] Review the expected activity of the GHA, then create a test branch in your local repo to trigger and record the results of the current action.
- [ ] Create another test branch to trigger and record the results of the action using the updated package version(s). Change all instances of:
```
- uses: actions/checkout@v3
```
to:
```
- uses: actions/checkout@v4
```
- [ ] Compare results to determine whether the update causes breaking changes, or whether the update causes no apparent change in the expected functioning of the action, and "Approve" or "Request changes" as appropriate. 

### Resources/Instructions
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)  
- This issue was initiated by #5443

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #5493 
includes #5496 
includes #5498
includes #5499

### What changes did you make?
  - Updated `actions/checkout@v3` --> `actions/checkout@v4`
    - `pr-instructions.yml`
    - `set-pr-labels.yaml`
    - `wr-pr-instructions.yml`
    - `wr-set-pr-labels.yaml`
  - Tested to confirm the GHA functions as expected with update
  - Testing was successful, see following, OK to update

### Why did you make the changes (we will use this info to test)?
  - Change made to confirm the Dependabot recommended version updates for compatibility with existing automation

### Links to tests
[Test PR](https://github.com/t-will-gillis/website/pull/337) 
[pr-instructions.yml log](https://github.com/t-will-gillis/website/actions/runs/6288083948)
[set-pr-labels.yaml log](https://github.com/t-will-gillis/website/actions/runs/6288083947)
[wr-pr-instructions.yml log](https://github.com/t-will-gillis/website/actions/runs/6288084486)
[wr-set-pr-labels.yaml log](https://github.com/t-will-gillis/website/actions/runs/6288084620)

##
### Note to PR Reviewers

 - The process for testing GHAs is different from procedures described in the `CONTRIBUTING.md` document. You will want to have an environment set up in your local repo and test the GHAs on the desktop. 
 - First, review the following wiki pages [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and follow the "Mini Guide".
   - Pay close attention especially to Steps 6 & 7. 
   - Note in Step 6: When you create your Project Board, be sure to name it (or rename it if needed) "Project Board"
   - Note in Step 7: It is best practice to give your secret an expiration date. 
   - Note in Step 7 also: when you are creating your own token, do not give your token the same name that you see in the yaml file. In other words, do not give your token the same name as HfLA's token, otherwise unexpected behavior may result. Any other name is OK (for example, TEST_TOKEN). 
 - To continue creating your testing environment, go to your local repo on the desktop and create a new branch for testing: 
   - From your "gh-pages" branch, make sure you are synced to HfLA.
   - Select the "gh-pages" button, enter a name for your test branch (such as "test-ghas-for-pr-review"), then select "Create branch". You will make edits and test from here.
   - Next, go to "Settings" on the upper right, scroll down to "Default branch", and select the button with the arrows to switch you default branch to another branch.
   - Find your newly created branch and select it, then "Update", then "I understand, update the default branch".
   - Important- when you are done testing you will want to repeat these steps to reselect "gh-pages" as your default branch.
   - Now, when you make edits to the "website" on your repo you will only affect the new branch.  
   
 - For testing this specific action you will need to make changes to four yml/yaml files:
   - `.github/workflows/pr-instructions.yml`:
     - Line 8: add the name of the branch you are using to test, e.g. `   - 'my-test-branch'`
     - Line 13: switch to ` - uses: actions/checkout@v4`
   - `.github/workflows/set-pr-labels.yaml`:
     - Line 9: add the name of the branch you are using to test, e.g. `   - 'my-test-branch'`
     - Line 19: switch to ` - uses: actions/checkout@v4`
    - `.github/workflows/wr-pr-instructions.yml`:
      - Line 47: switch to ` - uses: actions/checkout@v4`
   - `.github/workflows/wr-set-pr-labels.yaml`:
      - Line 27: switch to ` - uses: actions/checkout@v4`

 - Additional steps needed to successfully test this action:
   - Create an issue:
     - Set up "Labels" if you have not done so already: select "Issues" from your repo, then "New Issue", then choose any issue with "Get Started" on the right, then on the right click on the gear next to "Labels". You will need to add all of the following labels if you have not already: "Complexity: Missing", "Feature Missing", "role missing", "size: missing", "role: front end","role: back end/devOps". From "Labels", click on "Edit labels" , then "New label", and add each label exactly as shown, without the quotes.
     - Now click "Issues" again, then "New issue", then select "Get started" on "Blank Issue Template".
     - On the right, select "Projects" and then your own Project Board- it might be listed under "Recent" or "Repository".
     - Add any title, then "Submit new issue". Take note of the issue # created.
   - Edit your website test branch:
     - Now click on "<> Code" on the upper left. 
     - Select any file- it doesn't matter which. You can use `CONTRIBUTING.md` if you want.
     - Select the pencil icon on the upper right to edit. Make any edit to the file, then select "Commit changes..."
     - Important: select the radio button "Create a new branch for this commit and start a pull request", then "Propose changes"
     - On the next screen, "Create pull request".
     - Be sure to include your new issue number in "Fixes #---" 
     - Make sure that under "Projects" your repo's Project Board is selected.
     - Select "Create pull request".
   - Verify GHAs:
     - If you set up everything correctly, then after a couple of minutes you will see:
       - github-actions bot will add the comment you have seen before "Want to review this pull request? . . . "
       - github-actions bot will transfer/add the labels from your issue to the PR
       - There will be four new logs under "Actions" for each of the GHAs- these should all be green. 
       - If the above is true, then your test was successful.

### CODE REVIEW

**Comment by mshirk2** [comment]
ETA: Fri 9/29, 6pm
Availability: 9/28-9/29, 10-5pm PT

**Comment by mademarc** [comment]
Review ETA: 9/28/2023
Availability: 7PM

**Review by mademarc — APPROVED** [review]
Hey @t-will-gillis  good job on the changes on lines 13, 19, 43 on the yml files on this issue.

**Review by mshirk2 — APPROVED** [review]
Hi @t-will-gillis  — the branching is set up correctly, the corresponding issue is linked, the PR is descriptive, and the change updating the dependabot version from 3 to 4 across 4 files has been done correctly. Well done!

**Pull request merged**
