### PR TITLE
Refactor `add-label.js` to use `label-directory.json`

### LINKED ISSUE #7537: Enhance GHA `add-label.js` to use `label-directory.json`
### Overview
Currently, the GHA workflow files that add, remove, and change labels on issues identify each label by its name (i.e. the 'labelName') directly. Instead of hard-coding each label name, we want these files to identify each label by a general ID (i.e. 'labelId') so that different HfLA project groups will be able to use the GHA workflows without needing to match the label names used by the Website team.

### Action Items
This issue involves the "**_Schedule Friday_**" GitHub Action, and you must set up your environment for testing GHAs in order to work on this issue. See notes below in "Resources/ Instructions", and ask questions if you need additional help- GHAs can be tricky, and if you get stuck somewhere, someone who has worked on these before might have information that will save you a lot of time.    
- [x] Before making any of the edits following, first create a test branch in your repo and demonstrate the current, correct behavior of the "Schedule Friday" GHA. Afterwards, create an additional branch for the edits following- this is the branch that will be attached to the PR.

Refer to [add-label.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js).
- [x]  A preliminary search found that this file uses the following labels. As you work through this issue, confirm that this list is correct, and note any additions or subtractions as needed:
  - `Status: Updated`, 
  - `To Update !`, 
  - `2 weeks inactive`. 
- [x] Add to `// Import modules`:  
  ```
  const retrieveLabelDirectory = require('../../utils/retrieve-label-directory');
  ```
- [x] Add comment:
  ```
  // Use labelIds to retrieve current labelNames from directory
  ```
  then for each label, consult [label-directory.json](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/_data/label-directory.json) and replace labelName with the labelId:
  ```
  const <labelId> = retrieveLabelDirectory('<labelId>');
  ```
- [x] Search the code for instances of the original label name and substitute the <labelId> defined above.
- [x] Search for all code comments referencing a specific label name and replace with a generalized description.
- [x] Perform a test in your own repo that demonstrates that there is no change to the GHA's functionality after making the edits.
### Resources/Instructions
- Refer to [Hack for LA's GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), especially Tips 6, 7, and 8, if you have not already created you personal environment for testing.
- [How to Test GitHub Actions](https://drive.google.com/drive/u/0/folders/1MPY9CKcfKKN7hpDCG46ARrRzRSM8d8OA)
- [Additional Notes for GitHub Actions](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)
- This issue is part of the epic #6454

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #7537 

### What changes did you make?
  
  - Added link to `retrieve-label-directory` module and new variable definitions to use `labelId` - Consolidating to `.map(retrieve-label-directory)`  
  - Searched code for comments that reference the specific label names and replaced with more generic labels
  - Removed redundant console.log() statements
  - Refactored the `retrieve-label-directory.js` module to remove the for loop ~since the labels are iterated using the spread syntax~. Also, reformatted so that `labelData` is generated with the first iteration only.

UPDATE 10/14/24:
  - In `retrieve-label-directory.js`, removed the variadic parameter and refactored for a single parameter
  - Same file, changed the name of `labelRetrieveNames()` --> `retrieveLabelName()` for consistency, and edited plurals to singulars
  
### Why did you make the changes (we will use this info to test)?
  
  - Edits so that the label directory is used instead of label names

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

- No visual changes
- ~["Schedule Friday" log](https://github.com/t-will-gillis/website/actions/runs/11171245853/job/31055612047) showing successful run~
- [Log for revised Schedule Friday](https://github.com/t-will-gillis/website/actions/runs/11334816940/job/31521757730)

## Notes for Testing 
- If you have not set up your local repo for testing, refer to [Hack for LA's GitHub Actions (current revision)](https://github.com/hackforla/website/issues/6537#issuecomment-2041147335), especially Tips 6, 7, and 8. Note! These tips were created for the previous GitHub Projects (classic) and are being updated for the new Projects Beta. Some additional notes:
  - When copying the Project Board, be sure to set yourself as the owner. You can rename the copy to "Project Board" or leave it.
  - After you make the copy, you will see an error message that says something to the effect that some workflows have failed to be created- you can safely ignore this message. 
  - You will likely want to change the View to 'Board' to see that the status column names transferred correctly.
  - To match Hack for LA's Project Board's functionality, you may need to activate workflows by selecting the three dots in the upper right, then "Workflows". Set the "Workflows" as follows:
  
    <details>
  
    Screenshot 2024-10-02 143752
  
    </details>
  - You will want to create the labels in your repo as explained in Tip 8.
- Create a testing branch in your repo. 
- In `add-label.js`, Please comment out Line 182 `  minimizeComments(commentsToBeMinimized);` 
- There are some hard-coded values that are specific to the Hack for LA repo. I don't think that this will affect you when you are testing this. However...
- If you run across any errors that you can not figure out quickly, please send me a message. I might know what the problem is and can save you a lot of time troubleshooting.

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hey @tamara-snyder and @codyyjxn Before you get too far reviewing this issue, I want to provide instructions for reviewing the PR, hopefully in the next day or two. Thanks!

**Comment by codyyjxn** [comment]
Thanks I was going to reach out to you. I definitely need a bit more
information so I can fully understand the issue. Thanks!

**Comment by mrodz** [comment]
Hi @t-will-gillis, I hope you are well. Is it okay if I review this PR too? I can get you a review by EOD Wednesday, 10/2.

**Comment by t-will-gillis** [comment]
Hey @mrodz Yes, definitely! Thank you

**Comment by t-will-gillis** [comment]
Hey @tamara-snyder, @codyyjxn, and @mrodz: I believe this is ready for review now. I added review notes, and I had to make some last-minute edits because I omitted some labels. 

As I said in the review notes, let me know if you run into any problems that you can not figure out quickly- I might know what the problem is and could save you a lot of headaches. Thanks!

**Review by codyyjxn — DISMISSED** [review]
Hey @t-will-gillis Great Job refactoring the labels.
 - After reviewing this the way you refactored the `label-directory.js` it seems like that was a great approach of retrieving the label names. 
 - Also the `add-label.js` is returning the correct labels that you added. You also map through them correctly.  
- The branch is correctly named the issue is linked. 
 
The only thing I recommend is changing the original issue from "New issue approval" to "Working in progress"

Also thank you for the notes on reviewing the issue. It definitely helped me understand how to go about it. 

Keep it up!

**Comment by tamara-snyder** [comment]
Sorry for the delay! Thanks @t-will-gillis for adding some notes. I'll take a look at it today and come to office hours or reach out if I get stuck.
**Review ETA:** Friday, Oct 11
**Availability:** Afternoon Oct 10

**Comment by tamara-snyder** [comment]
Hi again @t-will-gillis, I got my environment set up (I think), but I haven't had time to test the issue yet. I'm travelling for the next few days, so I'm going to unassign myself from reviewing this just so it doesn't get held up. If it still needs a review when I return, I'll come back and look at it more. Thanks!

**Review by mrodz — DISMISSED** [review]
Hi @t-will-gillis! This pull request looks good—your changes look sound, and the updated comments reflect your migration from hardcoded labels to runtime assignment.

The only thing I will note is that it is not super intuitive to have `labelRetrieveNames` be a variadic function if it always expects a single label parameter and does not do bounds checking for zero labels passed to `labelKeys`. But this could be intended behavior and open the door for future implementations—I'd like to hear your thoughts.

Testing looks good! Thanks for including your own test run and steps for others to follow suit.

Please let me know if there is anything else you need from me. I apologize for the delay—work and school have been very consuming. I hope you're having a wonderful day :)

**Comment by t-will-gillis** [comment]
Hi @codyyjxn thank you for your review and comments. I corrected the issue status as you noted

**Comment by t-will-gillis** [comment]
Hey @mrodz Thank you for your review comments. Argh, you are correct about the variadic function- I overlooked this. Since  `.map()` is an iterative method, `labelRetrieveNames()` is never passed variadic arguments. 

Thank you for pointing this out! I have edited the PR to remove the variadic, renamed the function `labelRetrieveNames()` --> `retrieveLabelName()` for consistency, and revised `labelKeys` --> `labelKey`, `labelNames` --> `labelName`, etc.

**Review by codyyjxn — APPROVED** [review]
@t-will-gillis 
The changes look good! 
The code runs on my environment. 
Great job on this!

**Pull request merged**
