### PR TITLE
Removed alt hero tag from _projects/civic-tech-structure.md file

### LINKED ISSUE #2926: Remove unused `alt-hero` field from civic-tech-structure.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [ ] For the file `_projects/civic-tech-structure.md`, remove line 12 for the alt-hero
```
alt-hero: "A network of lines and nodes, and the lines converge to a large dot in the center."
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/civic-tech-structure.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/civic-tech-structure.md?plain=1#L12

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by kathrynsilvaconway**
…leting line 12.

Fixes #2926

### What changes did you make and why did you make them ?

  - Removed alt-hero tag from _projects/civic-tech-structure.md by deleting line 12.
  - This tag is being removed for clarity, since it is not actually used in the codebase.
  - No visual changes to the site, because this was an alt tag that was never used.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: Today, March 27, 2022

**Review by tamara-snyder — APPROVED** [review]
Hi Kathryn, thanks for making this fix. I can see that you've removed line 12 of civic-tech-structure.md and that the site's appearance remains unchanged. Well done!

I should add that in general, we ask that you only take up one issue at a time and wait until your current PR is closed to choose a new issue. This is so that if there are significant changes that need to be made on your open PR, you can focus on making those and leave other issues open to those who are available to work on them. Thank you for understanding.

**Comment by kathrynsilvaconway** [comment]
> I should add that in general, we ask that you only take up one issue at a time and wait until your current PR is closed to choose a new issue. 

Yes, I got a little over-excited and jumped right into the next issue :) I will only self-assign one at a time in the future.

**Comment by scarter31191** [comment]
Availability: 1 hour
Review ETA: Tomorrow, March 28, 2022

**Review by scarter31191 — APPROVED** [review]
Hey Kathryn, this looks great! good job with this fix. You've removed line 12 of civic-tech-structure.md and that the site remains unchanged.

**Pull request merged**
