### PR TITLE
Mobile_responsiveness Template to Github Form

### LINKED ISSUE #2290: Convert Mobile_responsiveness Template to Github Form Issue
### Overview
As an issue creator, we want to implement issue templates for issue creation to streamline and simplify the process. The current issue forms require the person to replace the text, and is less user-friendly compared to GitHub Form issues.

### Action Items

- [x] Create a Mobile_responsiveness.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
- [x] Add the code below to the file
```
name: 'Responsiveness on mobile '
description: 'Standard HackforLA issue template '
title: 'Mobile Responsiveness on [name of the page] : [quick recap of the bug here]'
labels: ['role: design']
# assignees:

body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: |
        We need to check the mobile version of every pages on the website so that we correct any bug that is appearing on mobile.
        1. Explain the bug that you have observed
        2. Put a screenshot of the bug: you can use the following template to create a drop down image
      value: |
        <details>
        <summary>TITLE IMAGE </summary>
        ![image](https://user-images.githubusercontent.com/77212035/134111368-bc5dfa08-0dd3-47be-a0e2-a60c6a362bf7.png)
        </details>
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Action Items"
  - type: checkboxes
    id: action-design
    attributes:
      label: "Design:"
      options:
        - label: "Check the mobile responsiveness of this page (use your mobile to do it ;) )"
        - label: "If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots in the Overview section above. _You have more than one bug? duplicate this issue and create one issue per bug. "
        - label: "List all the changes to implement to correct the bug (eg: resizing..) in the development action items below. (don't hesitate to create 1 checkbox for each changes)"
        - label: "Put the issue(s) in the review column to check the feasibility with the devs. "
  - type: textarea
    id: action-development
    attributes:
      label: Development
      value: |
        - [ ] Implement the following changes : '_list your changes here_ '
        - [ ] Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)
  - type: textarea
    id: resources-instructions
    attributes:
      label: Resources/Instructions
      description: Provide links to the figma file (if there is one), and to the page where the bug is observed.
    validations:
      required: true
```

- [x] Delete Mobile_responsiveness.md

### Resources/Instructions
<details>
  <summary>Before Changes Screenshot</summary>
  
</details>

<details>
  <summary>After Changes Screenshot</summary>
  
</details>

[Github Forms Issue Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Forms Issue Reading Pt 2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
#2128

### PR DESCRIPTION
**Pull request by harshitasao**
Fixes #2290

### What changes did you make and why did you make them ?

  - Created  Mobile_responsiveness.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
  - Deleted Mobile_responsiveness.md file
  - To simplify the process of issue creation from issue template, hence making it more user-friendly.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

beforeChanges

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
afterChanges

</details>

### CODE REVIEW

**Comment by usaboo** [comment]
Availability -> 9PM - 11PM EST(Sunday, March 27th, 2022)
ETA - End of Day -> Sunday(March 27th, 2022)

**Review by usaboo — DISMISSED** [review]
Hi Harshita, good job on your issue -> I see that you have deleted the Mobile_responsiveness.md and created a Mobile_responsiveness.yml in it's place. I checked your code by creating a new github repo on my remote and creating a Responsiveness on mobile issue which seems to be working fine. However I would like to add 2 things -->

1. In the original issue #2290, there are some action items to be checked which you have not checked. I think you should do that.

2. Next in your PR when you are posting screenshots the visual changes to the website there is a part which I do not understand/ see anywhere. I am attaching an annotated image for your reference. Could you please explain this? 

Harshita-issue-annotated

**Comment by kathrynsilvaconway** [comment]
Availability for this week: 8-9am EST on Monday, 3/28.
My estimated ETA for completing this issue: By the end of the day on 3/28

**Review by kathrynsilvaconway — DISMISSED** [review]
Hi @Sihemgourou. Nice work replacing this file. I can see that you have created a new .yml file in ISSUE_TEMPLATE folder and removed the old .md file. The code looks identical to what was requested for this issue, so no problems there.

I do notice that this file has a a typo in line 13, both in the new and the old version:
"We need to check the mobile version of every pages on the website so that we correct any bug that is appearing on mobile."
The word 'pages'  should read 'page:'
" We need to check the mobile version of every page on the website so that we correct any bug that is appearing on mobile."

I can't find an issue for the typo. Not sure if that should be a separate issue, or if it would be better to just correct it here? I'd like a clarification from a team lead @SAUMILDHANKAR  or @tamara-snyder

**Comment by tamara-snyder** [comment]
@kathrynsilvaconway Excellent catch! Feel free to create a new issue to fix the typo. It would probably make a good first issue.

**Comment by SAUMILDHANKAR** [comment]
@kathrynsilvaconway: Thanks for noticing the typo. Creating a new issue would be ideal to fix this, as Tamara mentioned. I would also recommend adding a dependency on this issue.

**Comment by JessicaLucindaCheng** [comment]
@usaboo The table you see is just how GitHub renders the file. To see that table for the before visual changes image:
- Go to https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/Mobile_responsiveness.md
- Then, on the upper right, click on "Display the rendered blob". Here is an image of what the "Display the rendered blob" button looks like:   
    image

**Comment by JessicaLucindaCheng** [comment]
Posting this comment because my comment for dismissing usaboo's review was not posted. The reason for dismissing the review was the requested change to check off the action items in the issue was made.

**Review by JessicaLucindaCheng — APPROVED** [review]
@harshitasao Looks good to me.

**Comment by usaboo** [comment]
Thank you @harshitasao for working on the issue and thank you @JessicaLucindaCheng for clearing my doubt about the display on top! Thanks for closing the issue!

**Pull request merged**
