### PR TITLE
Update Alt Text for Work for LA Project Image

### LINKED ISSUE #4031: Work for LA: Update alt text for the Work for LA image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As a developer, we need to provide clear and descriptive alt text for the Work for LA image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.
### Action Items
- [x] Change the alt value within `_projects/work-for-la.md`:

**From:**
```
alt: 'Los Angeles City Hall building'
```
**To:**
```
alt: 'Work for LA'
```
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
-  Work for LA Page: https://www.hackforla.org/projects/work-for-la

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE:  `_projects/work-for-la.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/work-for-la.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by Sebster3**
Fixes #4031

### What changes did you make and why did you make them ?

  - Changed the alt value within `_projects/work-for-la.md` to provide clearer, more descriptive alt text in order to adhere to the Web Content Accessibility Guidelines (WCAG).

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updated image alt text. No visual changes to the website.

### CODE REVIEW

**Comment by perlaroyerc** [comment]
Review ETA: 11PM 3/14/22 
Availability: 11-6 PM ET M-F

**Review by perlaroyerc — APPROVED** [review]
Great job @Sebster3! The issue was linked, changes were made correctly, and the branches were set up properly. In the future, write down why you made a change in the PR comment. It's a good habit to get into for keeping your documentation top-notch!

**Comment by Sebster3** [comment]
Gotcha, I'll keep that in mind, thanks!

**Comment by mattmalane** [comment]
Review ETA: 5 PM 3/15
Availability: 3-5 PM Wed/Thu/Fri

**Review by mattmalane — APPROVED** [review]
Awesome job @Sebster3! Your PR is formatted correctly with the issue linked, action items listed, and a comment stating why there were no screenshots for this issue.

**Comment by mademarc** [comment]
Review ETA:  3/15/23
Availability: 7:30 PM

**Review by mademarc — COMMENTED** [review]
Hey @Sebster3 Very well done on updating this code here.

**Comment by roslynwythe** [comment]
Hi @Sebster3 this is a very minor point but please edit the PR, under "What changes did you make and why did you make them?", to add a few words about why the change was made.  I believe the original issue should have some text that you could use.  

Great job on this issue, and we'll get it merged as soon as that bit of text is added.

**Comment by Sebster3** [comment]
Done and done, thanks @roslynwythe :)

**Pull request merged**
