### PR TITLE
added github-handle variable for Matt Pereira

### LINKED ISSUE #6111: Add github-handle for Matt Pereira in civic-tech-jobs.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Matt Pereira 
```
with
```
- name: Matt Pereira 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by partapparam**
Fixes #6111 

### What changes did you make?
  - Under 'name: Matt Pereira', I added 'github-handle:' variable
  - I made sure to use spaces instead of tabs

### Why did you make the changes (we will use this info to test)?
  - Good first issue (x2)

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updated variable, no visible changes to the website.

### CODE REVIEW

**Comment by luisitocanlas** [comment]
Review ETA: EOD 2/24/24
Availability: 2/23/24 ~ 2/24/24

**Review by luisitocanlas — APPROVED** [review]
Hi @partapparam, 

- Pull request is done with the correct branch.
- The issue is linked properly.
- Pull request has the proper title and content with a single suggestion. The part where it says "Why did you make the changes?" could be more descriptive. A good guide would be to use or reference the Overview from the linked issue, for this case: "We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file."
- Action items from the linked issue were done properly.
- Everything else looks good!

Thank you!

**Comment by freaky4wrld** [comment]
Review ETA: EOD 2/25/24
Availability: Evenings

**Comment by freaky4wrld** [comment]
@partapparam just a suggestion for future PRs in the section `Why did you make changes` , make sure you mention the correct reason, you can read the issue overview for that.

**Review by freaky4wrld — APPROVED** [review]
@partapparam thanks for taking up the issue, the branches looks good and the issue is linked correctly...... the changes made are apt.

**Pull request merged**
