### PR TITLE
Update alt text on about page 3397

### LINKED ISSUE #3397: Update alt text for Decent Work image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the Radical Inclusivity image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-sustainability.html`, change the following alt text

From
```
Decent Work and Economic Growth goal logo
```

To
```
8 Decent Work and Economic Growth
```

- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_includes/about-page/about-card-platform.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/a83dd650b664618ff2352b2fb93e8ae4acfb402b/_includes/about-page/about-card-platform.html#L77

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by gstemmann**
Fixes #3397

### What changes did you make and why did you make them ?

 -Replaced alt text in the file: _includes/about-page/about-card-sustainability.html
 -Moved text for logo into "8 Decent Work and Economic Growth"
 -Original alt text was too long and to adhere to Web Content Accessibility Guidelines

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No Screenshots applicable

### CODE REVIEW

**Review by MattPereira — APPROVED** [review]
Great work on this one George! you made the alt text more descriptive and succinct! 😎

**Comment by MattPereira** [comment]
Review ETA: 5 minutes prior (I accidentally forgot to post my review ETA and availability)
Availability: 6 hours per week

**Comment by giroz** [comment]
ETA: 10-17-22
Availability: 2 hours

**Review by giroz — APPROVED** [review]
Good job.  Altered line 51 to show new text and delete text

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing line 51's alt text to "8 Decent Work and Economic Growth" from 'Decent Work and Economic Growth goal logo' . The code looks clean and only one file changed. It looks like there was only two commits, the second one to bring the local branch up to date.
Good job!!

**Pull request merged**
