### PR TITLE
Added new team member to UI/UX section in Communities of Practice page

### LINKED ISSUE #4087: Communities of Practice information updates: UI/UX
### Overview
As a co-lead of the UI/UX Community of Practice, I want my project's details to be up to date on the HackforLA website. As developers, we need to update the UI/UX's CoP leadership information.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_data/internal/communities/ui-ux.yml` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Jennifer Nguyen
Title: Co-Lead
GitHub Handle: nguyen-jenn
Slack Member ID: U04K89GRNDS
- [x] Verify the changes by viewing the UI/UX section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [ui-ux.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by arcan9**
Fixes #4087 

### What changes did you make and why did you make them ?

  - Inside the `_data/internal/communities/ui-ux.yml` file, added a new team member, Jennifer Nguyen, with their following info:
    - Name: Jennifer Nguyen
    - Title: Co-Lead
    - GitHub Handle: nguyen-jenn
    - Slack Member ID: U04K89GRNDS

 
This ensures that the leadership info stays up to date with the most current members.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

</details>

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Availability: Tuesday and Thursday evenings
ETA: 6pm 3/14/23

**Comment by Jaretzbalba** [comment]
Availability: 1 hour
ETA: EOD 3/13/23

**Review by Jaretzbalba — APPROVED** [review]
@arcan9 I see that the new team member was added correctly and everything looks good locally. Great job working on this issue!

**Review by bzzz-coding — APPROVED** [review]
Thanks for working on this issue, @arcan9 ! The pull request was made from and to the correct branches, the formatting looks clean and consistent, and all links work. After pulling your branch and running Docker, I can see the desired changes on the communities-of-practice page. Nice job!

**Review by t-will-gillis — APPROVED** [review]
Hi @arcan9 - this looks great! The changes are coming from and going to the correct branches and you addressed all of the requested changes in the linked issue, included screenshots, explained what you did and why, and kept your code clean and concise. The new update appears in Docker correctly. Great job again and thanks for taking this issue!

**Pull request merged**
