### PR TITLE
Update Project Slack Links in Expunge Assist Page #6511

### LINKED ISSUE #6511: Project Slack links: Expunge Assist
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to edit the Slack link for the project so that we have continuity between project Slack links.

### Action Items
- [x] In `_projects/expunge-assist.md`, for the Slack `url` under the `links` section, change 

From:
```
url: 'https://hackforla.slack.com/messages/CN8NXTPK5'
```
To:
```
url: 'https://hackforla.slack.com/archives/CN8NXTPK5'
```
- [x] Ensure that clicking the Slack link resolves to the new address at the following places:
  - [x] On the [Projects page](https://www.hackforla.org/projects/), the Slack link under the `Links` field for the project's card
  - [x] On the [Expunge Assist page](https://www.hackforla.org/projects/expunge-assist),
    - [x] the Slack link under the `Links` field in the Project Overview section
    - [x] the Slack link in the Resources/Instructions section 
- [x] Once your pull request is merged, go to #4564 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4564 to **Questions / In Review** column and add a **ready for dev lead** label to it

### Resources/Instructions
- Directory to find the page once you have it in your IDE: `_projects/expunge-assist.md`
- [Projects page](https://www.hackforla.org/projects/)
- Project page URL: https://www.hackforla.org/projects/expunge-assist
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md?plain=1
- This issue is tracked in #4564

### PR DESCRIPTION
**Pull request by jenjenkayi**
Fixes #6511

### What changes did you make?
  - Updated the Slack url in the links section from messages to archives.
  
### Why did you make the changes (we will use this info to test)?
  - Per instruction.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Updating Slack link. No visual changes to the website.

### CODE REVIEW

**Comment by JackCasica** [comment]
Hi ~ I'll be reviewing this PR tomorrow ~
Availability: (04/10)
ETA: EOD (04/10)

**Comment by Jperparas** [comment]
Hi, I'll be reviewing this soon.
**Availability:** 4/10
**ETA:** EOD 4/10

**Comment by irais-valenzuela** [comment]
Review ETA: 2 PM 4/10/24
Availability: Monday - Thursday

**Review by irais-valenzuela — DISMISSED** [review]
Hi @jenjenkayi, great job on the issue! Your branches are correct, you linked the issue, and successfully updated the project slack link for Expunge Assist on the projects page, expunge assist page in the links section, and the resources section. 

Some improvements for next time are to make sure to check off all the boxes on the issue before opening a PR just to avoid any confusion. In this case I checked and you've completed all the tasks so great job! Just check them off next time. 

Overall, great job!

**Review by Jperparas — CHANGES_REQUESTED** [review]
Hi @jenjenkayi, The branches are correct and you linked the issue, but it looks like you forgot the single quotations ( ' ) around the updated url.
Ill be happy to approve it once that's corrected.

**Review by JackCasica — COMMENTED** [review]
Hi @jenjenkayi ~

In this PR you...
- [x] Updated the Slack link in the Expunge Assist project page ✅
image

I also see that you enclosed the link with `''` per the issue requirements. Good job!

**Review by JackCasica — DISMISSED** [review]

**Comment by jenjenkayi** [comment]
Hi @Jperparas, I have added the quotations around the url. Please approve. Thank you!

**Review by Jperparas — APPROVED** [review]
Hi @jenjenkayi , Thank you for addressing the changes everything looks good now!

**Review by irais-valenzuela — APPROVED** [review]
Great job adding the quotations @jenjenkayi. Thanks @Jperparas for catching that.

**Pull request merged**
