### PR TITLE
Add Project to Website: Tech Work Experience

### LINKED ISSUE #2288: Add new project to website: Tech Work Experience
### Dependency
- https://github.com/hackforla/internship/issues/248

### Overview

We need to add a new project to the hack for la website so that our project list can be current

### Project Details
- Name: Tech Work Experience
- Name of future project.md file: tech-work-experience.md
- Files you will need to upload to the website repository: 
   - tech-work-experience.png
   - tech-work-experience-hero.png
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Take the content listed here and create a new project.md card (skip anything that has strike-through)
- [x] Download the images
- [x] Add both project card and images to appropriate folders
- [x] Once you have it working on your local environment
  - [x] Take screen shots of the project card on the homepage and the projects project page adding them to issue
   - [x] Reach out to the product manager to ask if they are satisfied by adding a comment to [this issue](https://github.com/hackforla/internship/issues/57) with a link to the screenshots on your issue
- [x] Submit pull request
- [ ] Let Product Manager know when its live (by @ messaging them in this issue)
```
@priyatalwar
```

### Resources
[Template for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

#### Content of the project.md card
- [x] A link to the [600 x 400 image]
- [x]  Alt image text - 'Tech Work Experience'
- [x]  A link to the [1500 x 700 hero image] 
- [x]  Name of project: Tech Work Experience
- [x]  A blurb about your project:
```
The Tech Work Experience project is a structured summer internship program for college and high school students to work on open source projects in the fields of software, product development, project management, and UI/UX design at LA’s fastest growing Civic Tech non-profit organization in order to gain confidence, competence and deliverables to support their future career and personal journeys.

```
- [x]  Links:
- GitHub: https://github.com/hackforla/intership
- Slack: [Internship](https://hackforla.slack.com/messages/C01VAUPU788)
- [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
   - Wiki: https://github.com/hackforla/internship/wiki
   - Overview: 
      - future location will be: assets/pdfs/Tech-Work-Experience-One-Sheet.pdf
      - currently location (to copy from): https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf
- [x] leadership: this should be updated right before this issue gets worked on.  The project team keeps this up to date: https://github.com/hackforla/internship/wiki/The-Team#current-team
- [x] Partners (don't list any)
- [x] Location: Remote
- [x] Status: Active
- [x] Program Area: Workforce Development
- [x] Tools: Figma, Miro, Otter.ai, Zoom, Calendly, LinkedIn, 1password, GitHub Wiki, Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar) Google Data Studio

#### Related issue
- https://github.com/hackforla/internship/issues/57

### PR DESCRIPTION
**Pull request by adrianang**
Fixes #2288 

### What changes did you make?
  - Created new markdown file for the Tech Work Experience Project (tech-work-experience.md)
  - Added assets (project card image, project hero image, PDF overview) to their appropriate folders

### Why did you make the changes (we will use this info to test)?
  - To keep list of active HfLA projects on the website up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

localhost_4000_-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
localhost_4000_-after
(Tech Work Experience comes immediately after Open Community Survey)

localhost_4000_projects_tech-work-experience-project-after

</details>

### CODE REVIEW

**Comment by Abrosss** [comment]
Availability: 7/5-6, 
ETA: 7/6

**Review by LOSjr4 — APPROVED** [review]
I see "tech-work-experience.md" was created inside _projects. Content appears correct without typos. Leadership and links appear to be correct. Two new png images are placed in /assets/images/projects. Docker shows the new Tech Work Experience project card on the main page and it links to the main Tech Work Experience page. Both card and page look consistent with our other project pages. Inspecting the card and page in smaller formats also appear consistent.

This looked like a fun issue. Thank you for the good work @adrianang .

**Review by Abrosss — APPROVED** [review]
The pull request is made from the right branch, the tech-work-experience.md file was created in the _projects folder,  and all the assets added to correct folders. I ran the code in my local environment, and I can see that the added project is displayed correctly, and all the links are working. The screenshots of the changes are also attached to the pull request. Nice job @adrianang, thank you for paying attention to all the details!

**Review by chrismenke45 — APPROVED** [review]
@adrianang Great Work! The page looks good, all the links seem to be working properly and all of the files have been added to the appropriate folders

**Pull request merged**
