### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ahdithebomb**
Made additional changes per Bonnie's request to update the Readme by linking the Wiki.

### CODE REVIEW

**Comment by akibrhast** [comment]
@ahdithebomb Any chance you could please add a screenshot of the look of the readme.md after the change has been made?

**Comment by jbubar** [comment]
@ahdithebomb, have you set up your development environment? I know that you are a pm and not a dev. If you want, I can post photos

**Comment by ahdithebomb** [comment]
@akibrhast this is what it would look like if we were to commit this. 

[
Screen Shot 2021-02-17 at 11 35 35 AM
](url)

**Comment by akibrhast** [comment]
@ahdithebomb Yeah I know, those are the lines changed xD
I was asking for a screenshot of the rendered README.md after those lines has been added for posterity's sake 😄 . Have you set up your development environment? I know that you are a pm and not a dev. If you want, I can post photos

**Comment by jbubar** [comment]
As long as @ExperimentsInHonesty  approves it is ready to merge

@akibrhast I don't think it is necessary to show screenshots, because this is a change to the readme

**Pull request closed without merging**
