### PR TITLE
Home unite us project card update

### LINKED ISSUE #953: Update Project Profile: Home Unite Us
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/home-unite-us

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [x] description
- [x] image
- [x] leadership
  - [x] Member Name
  - [x] Role
  - [x] Slack Member ID
  - [x] Github Handle
- [x] links
  - [x] Github
  - [x] Slack
  - [x] Test Site
  - [x] Demo Site
  - [x] Site
- [x] looking
- [x] technologies
- [x] location
- [x] partner
- [x] tools
- [x] status

### PR DESCRIPTION
**Pull request by thatguyish**
fix #953

### CODE REVIEW

**Review by jbubar — APPROVED** [review]
Good work Ish!!
Nice job making it through that convoluted issue.
This pr is ready to merge.
There is just one thing.. 
I know that VRMS is in charge of the meeting times

I think the meeting times need to change to 
Tue 10:00 pm - 11:00 pm (EDT) - this one is correct rn
Sat 3:30 pm - 5:00 pm (EDT) - but this one starts at 3pm EDT on the site currently.

So I want to reach out to the VRMS team before closing the issue

**Comment by thatguyish** [comment]
@jbubar I already put a request in with them I forgot to note it sorry.

**Comment by jbubar** [comment]
Oh no!!!

**Comment by jbubar** [comment]
I just made a new one

**Comment by jbubar** [comment]
LOLOL.. Ill go delete it. then I will squash and merge

**Pull request merged**
