### PR TITLE
refactored imgTag / Westside

### LINKED ISSUE #5266: img Tag Refactor: _includes/events-page/our-locations-content.html - Westside1.png
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/our-locations-content.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="location-image" src="../assets/images/hack-nights/westside1.png" alt="Westside" />
```
to
```
<img class="location-image" src="../assets/images/hack-nights/westside1.png" alt="Westside">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/our-locations-content.html
2. Webpage(s): https://www.hackforla.org/events/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by njackman-2344**
Fixes #5266 

**What changes did you make?**

-   Removed closing "/" in Img Tag with the alt-westside

**Why did you make the changes (we will use this info to test)?**

  - This issue above in order to keep code uniform.

**Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)**

- No Visual change.

### CODE REVIEW

**Review by StephenTheDev1001 — CHANGES_REQUESTED** [review]
File changes are correct. Please fill-out the pull request template.

**Review by StephenTheDev1001 — CHANGES_REQUESTED** [review]
Thanks for the quick response. The purpose of the first pull request is to practice using the standard HackForLA format. Please add the headers similar to this [HfLA member's PR ](https://github.com/hackforla/website/pull/5245)

**Comment by njackman-2344** [comment]
Made similar headers. Thank you for your help!

**Review by StephenTheDev1001 — APPROVED** [review]
Linked to the correct issue. Descriptive branch name. Changes to code correct and works in the browser. Good job on your first PR!

**Comment by christinaor** [comment]
Confirming the template was filled out correctly and the closing "/" was taken out of the img tag of the file. Great job @njackman-2344 !

**Pull request merged**
