### PR TITLE
Add h tags 2952

### LINKED ISSUE #2952: Add h tags to Getting Started page (Steps 1-3)
### Overview
As a developer, I need to replace p tags with h tags on the headings of [Getting Started page](https://www.hackforla.org/getting-started) (Steps 1-3) so it becomes WCAG compliant

### Action Items
- [x] Review [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [x] In line 51, change the p tag to an appropriate h tag: https://github.com/hackforla/website/blob/dadd71fd3db10520b3c69acdce198418863301a3/pages/getting-started.html#L51
- [x] In line 91, change the p tag to an appropriate h tag:
https://github.com/hackforla/website/blob/dadd71fd3db10520b3c69acdce198418863301a3/pages/getting-started.html#L91
- [x] In line 127, change the p tag to an appropriate h tag: https://github.com/hackforla/website/blob/96f02c4a8446f615741c881d823b94619738a708/pages/getting-started.html#L127
- [x] Ensure h tags (h1, h2, h3 etc.) reflect the correct hierarchy of the page for screen readers
- [x] Make sure the [Getting started page](https://www.hackforla.org/getting-started) still looks the same.

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)
- [Getting Started html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html) file
- [Headings in Page Structure Tutorial](https://www.w3.org/WAI/tutorials/page-structure/headings/)
- [WCAG guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/)
- Related issue #2953

### PR DESCRIPTION
**Pull request by riddle015**
Fixes #2952

### What changes did you make and why did you make them ?

  - Updated the p tag on line 51 to an h2 tag
  - Updated the p tag on line 91 to an h2 tag
  - Updated the p tag on line 127 to an h2 tag

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
Changed tags in html. No visual changes to the website.
</details>

### CODE REVIEW

**Comment by Sparky-code** [comment]
ETA: Tuesday 6/14 EOD
Avail: 1hr

**Comment by Carlos-A-P** [comment]
Availability: 1hr
ETA: 6/14 EOD

**Review by Carlos-A-P — APPROVED** [review]
Hey @riddle015, great job working on this issue! I can see the code changes in my local environment. The site looks to have no noticeable changes, which is great. Not too sure why the other step sections don't have a header tag but I see it isn't part of this ticket so I'll approve.

**Review by Sparky-code — APPROVED** [review]
Changes maintain the visual hierarchy that was present before and h2 tags are appropriate for the code structure. Great job!

**Comment by Sparky-code** [comment]
@riddle015 I notice that there are a number of commits from a while ago that look like they predate you taking up this issue. It looks like you've fixed the conflicts there and changed only the relevant file for this issue.

I think @Carlos-A-P makes a good point about the WGCA compliance changes potentially being necessary for other parts of this page - I'm going to note the related issue here for continuity:
https://github.com/hackforla/website/issues/2953

**Pull request merged**
