### PR TITLE
Add github-handle variable in _projects/100-automations.md

### LINKED ISSUE #5505: Add new variable github-handle for member Camila Arias in 100-automations.md
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Camila Arias
```
with
```
- name: Camila Arias
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by KyleA99**
Fixes #5505

### What changes did you make?
  - Added "github-handle" variable to Camila Arias in _projects/100-automations.md

### Why did you make the changes (we will use this info to test)?
  - This change was to help remove redundancy in website codebase.  Redundant variables will be subsequently removed.

### CODE REVIEW

**Comment by MattChau01** [comment]
Availability: Evening Saturday, most of the day Sunday
ETA: End of day Sunday

**Review by MattChau01 — DISMISSED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5505 was properly referenced. ✅ 
- The specified line of code was properly added on line 16. ✅ 

Great work @KyleA99!

**Comment by KyleA99** [comment]
@MattChau01 @roslynwythe Should there be an actual github-handle value declared for this variable?  Reviewing a similar PR right now and noticed that they added a value, whereas, my issue left it blank.  Just wanted to confirm this was intentional.

**Comment by MattChau01** [comment]
Hi @KyleA99 ! Would you mind providing the reference number for the other PR you saw? It could be a different scenario for that other issue. But would like to hear @roslynwythe for advice as well!

**Comment by KyleA99** [comment]
@MattChau01 Here is the issue #5509 

And corresponding PR #5563

**Comment by MattChau01** [comment]
Thanks @KyleA99 . I took a look at the code that was changed in PR #5563 , but I'm not sure where the author received the phrase `superbunker` from. I would advise that you ask the author for clarification on why that was included, since it doesn't appear to be on the original issue (#5509).

**Comment by KyleA99** [comment]
@MattChau01 you're right, I mistakenly thought it was in the original issue.  I'll reach out and update you once I hear back

**Comment by MattChau01** [comment]
@KyleA99 No worries, glad to help out!

**Comment by ajb176** [comment]
I'm seeing some unwanted visual changes, even though Kyle edited the markdown file as suggested. The box containing the person's data seems to split into two. Does this issue occur for anyone else?

<details> <summary> After changes: </summary>
Screenshot 2023-09-25 at 9 19 52 PM
</details>

@tonyvang first noticed this issue [here](https://github.com/hackforla/website/issues/5508#issuecomment-1732235751) in another issue of the same template, and their PR omitted the '-' before '- githhub-handle-' and kept it in line with 'role' and 'links'. Their PR didn't cause any visual changes, but it was slightly different from the instructions in the linked issue.

@roslynwythe could you let me know if you're able to see this issue when reviewing this PR, because if so the original template may need to be slightly changed.

**Comment by KyleA99** [comment]
@ajb176 I can see that unwanted visual change as well.  Somehow missed that when I created the PR.  I will check if this issue is also present in the PR I reviewed.

@MattChau01 @roslynwythe

**Comment by roslynwythe** [comment]
@MattChau01 @KyleA99 @ajb176  There is an error in the original issue and it will be updated shortly.  In the meantime please do not review or merge.  Thank you

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@KyleA99 Please see the updated issue and my comment in the issue.  I apologize for the error and want to thank @ajb176  @MattChau01 for catching the error in the issue.

**Review by roslynwythe — APPROVED** [review]
Thank you @KyleA99 for your work on this issue. The code change is clean and correct and checks out in the browser.  The PR is well-formed and descriptive.  Thank you also for being responsive to the correction in the issue.

**Comment by roslynwythe** [comment]
Special thanks to @ajb176 and @MattChau01 for a superb job testing and reviewing this issue

**Review by MattChau01 — APPROVED** [review]
Code change looks like it was properly adjusted ✅ 

Great work @KyleA99 for actively working on this issue!

**Review by ajb176 — APPROVED** [review]

**Pull request merged**
