### PR TITLE
Replace hex value for redpurple to its color value

### LINKED ISSUE #2205: Design System Audit: Swap colors with color variables: purples,
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the purple colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (purple colors)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, delete it from the files noted above.
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L42-L45

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  
</details>

### PR DESCRIPTION
**Pull request by neevliberman**
Fixes #2205

### What changes did you make and why did you make them ?

  - Changed all hex values associated to purple with their respective color value
  - In this case, only "redpurple" had a matching case to replace.
  - Deleted the other two purple colors from _colors.scss, since they were not found. Please make sure this part was done correctly!!!

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

None

### CODE REVIEW

**Comment by d-perez-8** [comment]
ETA: EOD 8/27/22
Availability:  8/27/22 & 8/29/22

**Review by d-perez-8 — CHANGES_REQUESTED** [review]
Hi @neevliberman! I have checked the colors you have removed, and they are in use using their color value instead of their hex value. I found them under the `_color-styles.scss` and `_about.scss` files.

**Comment by neevliberman** [comment]
Hi @d-perez-8 thank you for taking the time to look this over! I'm a bit confused as to what the issue is asking for, is it not asking for the hex values to be replaced BY the color variables, not the other way around? I may have still missed some but please let me know!

**Comment by neevliberman** [comment]
I'm trying to run docker to see if the changes broke anything and.... looks like it does. I'm getting this error after replacing hex values with variables:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.css':
Undefined variable: "$color-blueviolet". on line 41
```

**Comment by d-perez-8** [comment]
@neevliberman I think they want to change hard coded hex variables into more easily readable color variables. Then delete any unused colors from the [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) file. But some colors are already using color variables, so we want to keep them as is. 

When I was running docker, I tried `docker-compose up` but I got a `exited with code 1` message. I thought it was because the colors that the site was using were deleted.

I'm going to check it again.

**Comment by d-perez-8** [comment]
I put back the colors that were deleted and docker was working fine with me. 

If you are still getting that error, then I think it means that the hexadecimal being used for `$color-blueviolet` was deleted.

**Comment by ericvennemeyer** [comment]
`Availability`: 1hr
`ETA`: EOD Sunday 8/28

**Comment by neevliberman** [comment]
@d-perez-8 I see, thank you for clarifying! I misinterpreted what the issue was requesting. I brought back the color values, please take a look :)

**Review by d-perez-8 — APPROVED** [review]
LGTM, and the changes do not break the website. Good job!

**Review by ericvennemeyer — APPROVED** [review]
Nice job getting this fixed! Branch is correct, changes have been made correctly as requested in the original issue, and the site doesn't break.

**Pull request merged**
