### PR TITLE
Create comm of practice page (new PR)

### LINKED ISSUE #678: Communities of Practice Page
### Overview
We need a homepage for communities of practice which explains what they are and details how to get involved in order to grow our community.

### Action Items
Requirements gathering
- [x] Paragraph about what CoPs are about
- [ ] Instructions for joining the team meetings (join their slack channel and look for the meeting info (usually pinned or in description))
- [x] For each community of practice
   - [x] Name
   - [x] Paragraph that describes them 
   - [x] Meeting times 
   - [x] Leadership Type
     - [ ] Community-led 
     - [x] Specific leader(s)
         - [ ] List leaders - slack member ID, Github picture 
     - [x] Seeking leadership
   - [x] Slack Channel (where they can find the zoom link for the meetings)

UI/UX 
- [ ] [Mockup of the page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627)

Development 
- [ ] Submit collection architecture for approval
   - [ ] Create the cards
   - [ ] Build the page

### Resources/Instructions
See _projects collection
[Working Figma of the page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627)

### PR DESCRIPTION
**Pull request by csseu**
Addressing #678 
Started by @dmcneary and passed on to me.

Notes:
- Cards are a _communities collection processed using Liquid. The template.md won't be shown
- _config.yml updated to include _communities and I couldn't help myself from alphabetizing the entries
- Two media calls used in the header css to deal with the uncanny tablet valley where it just didn't look good as two columns (this wasn't in the Figma so it's ad-libbed)
- The .svg splash files were original but I thought they might be better as smaller jpgs. I didn't delete the .svgs because I wasn't sure, maybe the team would rather use the svgs?

If you're not seeing any card content: In my experience with Jekyll/Docker, occasionally it won't load changes from collections and _config.yml, even when I start with a fresh server. My workaround was to dump _site in the trash and have jekyll serve everything new. (I'm wondering if that was the issue with the Liquid tag for img dir as well).

### CODE REVIEW

**Comment by csseu** [comment]
I think I'm supposed to include screenshots

<details>
<summary>desktop</summary>
<br>

</details>
<details>
<summary>mobile</summary>
<br>

</details>
<details>
<summary>tablet</summary>
<br>

</details>

**Comment by akibrhast** [comment]
- The `projects/<project-name>` page is broken . I believe this is happening due to some changes in `_config.yml` file
<details>
<summary>Broken `projects/project-name` </summary>

image

</details>

- The template.md file is not doing anything, that I can tell. If the purpose of it is to document what a communities.md files should like I recommend moving it to the wiki.
- Having time in a string format in data source really isn't good practice and will cause headaches down the road. Can we get it from VRMS? Have it in a UNIX format -- > `meeting-times: Thursdays 8:00-9:00 pm PT (every week)`

**Review by akibrhast — CHANGES_REQUESTED** [review]
Please ensure that the projects/<project-name> page is not broken .

Also If i am not mistaken this PR should be closing #678. Please link the issue to this PR

**Comment by csseu** [comment]
Thanks for the fast response @akibrhast!

- Yes - found extra lines in _config.yml and removed them. Seems to work for me now.
- Deleted the _template - we'll need to update this according to the date/VRMS issue and place in wiki when done
- VRMS - I don't know how this works yet. I'll dig into it when I have time, or can you/someone advise?

**Review by akibrhast — APPROVED** [review]

**Comment by akibrhast** [comment]
lgtm 👍 . Merging

**Comment by daniellex0** [comment]
Hey @akibrhast should this issue have been closed already? Considering @ruqpyL2 's question above about VRMS... And since this is a brand new page, maybe there should be a chance for a second dev reviewer to take a look just in case. 

The design looks great @ruqpyL2, awesome job- there are some CSS fixes like the gray background instead of beige which I could have asked to fix before this went live, but I can add the notes in a separate issue for someone else. But I just wanted to note there is no need to rush this so much @akibrhast lol, I want to make sure everything is cleared before this can be connected to the site.

**Comment by akibrhast** [comment]
> maybe there should be a chance for a second dev reviewer to take a look just in case.

You are right. I do apologize for that. The reason I merged this is because from what I could tell it seemed like this PR addressed all the necessary changes requested in the issue for the most part. Also, since the page is not linked yet and did not break anything I figured everyone in the team ui/ux,pm,developers would be easily able to access the page without needing to pull it and discover bugs/css changes needed and create new issues regarding this page . https://github.com/hackforla/website/issues/678


> Considering @ruqpyL2 's question above about VRMS

Her question regarding VRMS was in regards to my initial comment regarding vrms. Which I realized was an unnecessary statement to make that had nothing to do with this PR or the issue this PR would be closing.

> there are some CSS fixes like the gray background instead of beige which I could have asked to fix before this went live, 

It's live but not linked yet anyhwere in the page. Just like the about page. Which is live and going through iterative development/fixes . Maybe the css fixes could be iterative and changing the background color could be a good second issue?

> But I just wanted to note there is no need to rush this so much @akibrhast

You are right. I am really sorry about that. Didnt think through when I was merging.

> I want to make sure everything is cleared before this can be connected to the site

It's not connected to the site yet as far as I am aware. Is there somewhere on the site that is linking to hackforla.org/communities-of-practice ?

**Comment by daniellex0** [comment]
@akibrhast Ok got it, no worries- it's true there is the option to let it go live since it is not yet connected to the site, and iterate on that as we have with the About Us page (even though this page is smaller). But in the future if that's the intention, can you please note that before you merge? It takes more work to create more separate issues for the fixes, but that's ok. It's good to have extra issues.

And regarding VRMS, should the meeting times be automated then or not? Do you mean that will need to be on a separate issue?

**Comment by akibrhast** [comment]
Understood.

> And regarding VRMS, should the meeting times be automated then or not? Do you mean that will need to be on a separate issue?

Yes it should. Yes it should be its own issue. Which would highly be dependent on vrms.. and may or may not be addressed any time soon. For now, hardcoding it is the right way to go.

**Comment by daniellex0** [comment]
@akibrhast Got it, thank you for the clarification Akib! Glad we got this all sorted lol

**Pull request merged**
