### PR TITLE
Added Tools Filter to Projects Check Page

### LINKED ISSUE #4427: Add a Tools filter to the projects check page
### Dependency

- [x] #4525
- [x] #4776
- [x] #4798
- [x] #4799
- [x] #4800
- [x] #4801
- [x] #4802
- [x] #4803
- [x] #4804
- [x] #4805 
- [x] #4806
- [x] #4807
- [x] #4808
- [x] #4809
- [x] #4810
- [x] #4811
- [x] #4812
- [x] #4813
- [x] #4814
- [x] #4913 

### Overview
We need to revise the filter dropdown menu to include a dropdown for Tools, so that we can use this page to see where we might need to moved projects values from tools to technologies, and vice versa

### Action Items
- [x] View the current filters dropdown menus on the [projects-check page](https://www.hackforla.org/projects-check/) 
- [x] Make appropriate changes to the following files to create a functional Tools filter dropdown menu
  -  [/_includes/current-projects-check.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html)
  - [/assets/js/current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [x] The style of the dropdown menu should mimic the existing dropdown menus for Technologies and Languages

#### Current Filters on projects-check page
image

#### Example of Tools vs. Languages and Technologies
image

#### For Merge Team/Tech Leads/PMs
- [x] When the PR linked to this issue has been merged, release the dependency on 
   - [x] #3487 
   - [x]  ~#4262~  
   Note: 4262 has dependency on 3487 
   - [x] #4960 

### Resources/Instructions
- [projects-check page](https://www.hackforla.org/projects-check/)
- This issue is part of an epic: #4434

### PR DESCRIPTION
**Pull request by pdimaano**
Fixes #4427

### What changes did you make?
  - Added new filter function for new Tools dropdown menu
  - Updated HTML to properly display cards filtered by Tools

### Why did you make the changes (we will use this info to test)?
  - Allow users to filter though projects based on tools in addition to technologies and languages

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-09-04 at 7 05 26 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-09-04 at 7 06 35 PM

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 9/6/23

**Review by Thinking-Panda — DISMISSED** [review]
@pdimaano , Tools filter is added and works as intended in tablet and desktop viewport. Nice work. Thank you !

**Comment by Thinking-Panda** [comment]
This comment may be out of scope for this issue, but I notice that "AWS" appears twice in "Technologies" and once in "Tools".

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @pdimaano - Great work- you have covered the bases with the branches, linking the issue, the descriptions, and providing the screenshots. Bonus points for correcting the spelling mistakes in the comments!  

But there is something odd happening with the filtering itself and the filter counts- for example, the filter shows "AWS (3)" in "Technologies and "AWS   - " in "Tools". If you would, please track down the source of the problem. 

Otherwise, this is looking good. Thanks for working on this issue

**Comment by t-will-gillis** [comment]
>This comment may be out of scope for this issue, but I notice that "AWS" appears twice in "Technologies" and once in "Tools".

Just noticed your comment @Thinking-Panda

**Comment by pdimaano** [comment]
@t-will-gillis Thank you for the feedback. I see that there is a discrepancy on some of the cards on the projects check page where AWS is in the "Technologies" category in some and the "Tools" category in others. I believe this is causing the multiple AWS options to be dynamically generated in the separate dropdown lists. Is this something that needs to be changed here or is it beyond the scope of this issue like what @Thinking-Panda stated previously?

**Comment by Thinking-Panda** [comment]
The discrepancy is based on how AWS is listed in each of the projects' markdown file in `_projects` folder.

**Comment by t-will-gillis** [comment]
Hi @pdimaano With the current changes to the markdowns in the `_projects/` folder, it looks like the filter should show (4) AWSs in "Technologies" and (3) AWSs in "Tools".

This is something that is in the scope of the issue because the filters are not functioning correctly yet.

**Comment by t-will-gillis** [comment]
Hi @pdimaano Here is something to try: since we know that we will want all "AWS" in "Technologies" in the end, you can check how the filter performs if you move "AWS" to `- technologies: ` for:  
- `home-unite-us.md`  
- `lucky-parking.md`  
- `metro-ontime.md` << you'll need to add in "Technologies: " here  

If that appears to work, then I think it will be fine to add those changes to your PR and call it good...

**Review by t-will-gillis — APPROVED** [review]
Thanks, @pdimaano

**Pull request merged**
