### PR TITLE
Added github-handle for Sanya Nijhawan in home-unite-us.md

### LINKED ISSUE #7181: Add github-handle for Sanya Nijhawan in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Sanya Nijhawan
```
with
```
- name: Sanya Nijhawan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by joooseph2**
Fixes #7181

### What changes did you make?
 Changed variable `name:` in /website/_projects/home-unite-us.md to include variable
`github-handle:` 
- `name: Sanya Nijhawan`

- `name: Sanya Nijhawan
   github-handle:`

### Why did you make the changes (we will use this info to test)?
  - to submit the first pull request. The issue was created to replace the github: and picture: variables with github-handle: to reduce redundancy. 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

- No Visual changes made as only a variable name was added.

### CODE REVIEW

**Comment by daras-cu** [comment]
Availability: Sun/Mon all day, Tues-Fri evenings
ETA: 8/11 EOD

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @joooseph2, thanks for working on this issue!

What looks good:
- You added `github-handle` as described in the issue.
- When I test the website with your changes there are no visual changes and everything displays correctly.
- You are merging from your branch to the correct gh-pages branch.
- You linked the original issue number in the PR.

A couple things to address:
- The name of the branch that you created includes the issue number, but it should be a little more descriptive so someone reading it has a general idea of what issue it addresses. I'm not sure if this can be changed at this point without redoing the PR, so may be something to keep in mind for the next issue you work on.
- Under "Why did you make the changes", your answer should show you understand the purpose of the changes for the website. If you take a look back at the original issue #7181, the `github-handle` variable is going to replace two other variables to reduce redundancy, so your answer here could reference that.
- Under the screenshot section, instead of saying you added a new variable you can just put "No visual changes" so it's more clear for reviewers that the website visuals should not be affected.
- Don't forget to check off the action items in the original issue as you complete them.

A good idea may be to review successfully merged PRs for similar issues to see what they should look like, for example [#7325](https://github.com/hackforla/website/pull/7235).

Once you've made adjustments let me know in a comment or re-request a review and I will take another look!

**Comment by joooseph2** [comment]
@daras-cu Thanks for the feedback! I've done each item. For the next pr I'll make sure to do a better branch name.

**Review by daras-cu — APPROVED** [review]
Looks great, thanks for making the changes!

**Review by pluto-bell — APPROVED** [review]
Great work on this issue and also in handling the changes requested by daras-cu. Everything has been cleaned up and it looks like you now have a better idea of what to do moving forward. 

(:

**Comment by joooseph2** [comment]
@t-will-gillis could I get a merge for this to work on my second skill issue?  Also what is the standard protocol for getting issues reviewed? Do I just have to wait for someone to pick it up or should I just directly ask. I want to keep working on the skills issues but there's a decent delay between approvals and merges.

**Comment by t-will-gillis** [comment]
Hi @joooseph2 - done! As to the protocol for getting things reviewed, yes, unfortunately you have to wait. You can try asking, which might work if you ask someone who also has an open PR pending review. (You did not ask this, but you do not want to assign reviewers even though GitHub suggests people. Often this backfires b/c the suggestions are for people who are no longer active and you will be waiting a very long time.) 

We try to keep the process moving through having the [On call reviewers](https://docs.google.com/spreadsheets/d/1uq65QGwIpbx60JZZpqd7juHwEytDEOJap6e6u1klSVw/edit?gid=0#gid=0) and asking for volunteers during the weekly meetings. 

Finally, while you are waiting for a review it really helps moving things along if you do several PR reviews yourself.

**Comment by t-will-gillis** [comment]
@joooseph2 If you are waiting a long time for a reviewer to complete a review or if all reviews are completed and you just need it merged, definitely feel free to ask like you did.

**Pull request merged**
