### PR TITLE
Update Project Profile: VRMS Add Jack Haeger

### LINKED ISSUE #7473: Update Project Profile: VRMS Add Jack Haeger
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/vrms.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Jack Haeger
    github-handle: JackHaeg
    role: Lead Product Manager
    links:
      slack: https://hackforla.slack.com/team/U059005TN1L
      github: https://github.com/JackHaeg
    picture: https://avatars.githubusercontent.com/JackHaeg
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] VRMS page [^2]
- [x] Once your pull request is merged, go to #7407 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #7407 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #7407
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/vrms

### PR DESCRIPTION
**Pull request by theogguu**
Fixes #7473 

### What changes did you make?
  
  -  Added Jack Haeger to leadership variable in the VRMS .md file
  ```  - name: Jack Haeger
    github-handle: JackHaeg
    role: Lead Product Manager
    links:
      slack: https://hackforla.slack.com/team/U059005TN1L
      github: https://github.com/JackHaeg
    picture: https://avatars.githubusercontent.com/JackHaeg
```
 

### Why did you make the changes (we will use this info to test)?
  
  - To keep project information up to date so that visitors to the website can find accurate information.
 
### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

7473-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
7473-after

</details>

### CODE REVIEW

**Review by pluto-bell — APPROVED** [review]
Great work.

The new profile is added correctly in the code base and the new profile card populates on the VRMS project page like it should.

Provided a good explanation as to why the changes were made and visuals for before and after.

My only suggestion is to be more specific with your git branch naming in the future. In this case, it would allow us to quickly know the profile is being added to the VRMS project specifically.

**Review by DrAcula27 — APPROVED** [review]
@theogguu Great job on your `Good First Issue`! Your code passed the ABC's, including:
- PR is made from the correct branch
- PR links to the correct issue:
  - #7473 
- The correct file `_projects/vrms.md` was edited
- No extra edits were made
- Appearance of the website looks just like your screenshots (Chrome and Firefox)
- I agree with the nitpick from the other reviewer: naming your issue branch so that which project was modified is in the name would be more clear.
Approved! 👍

**Comment by NolaDodd** [comment]
Hey! Your pull request looks good!

- PR is the correct branch and references the correct issue
- The explanation is good
- The correct file and changes were made
- The appearance of the updated website looks correct

Other than a clearer branch name like the others mentioned, everything looks good to me!

**Review by NolaDodd — APPROVED** [review]
Great job!

**Review by codyyjxn — APPROVED** [review]
@theogguu Great job on your Good first issue. 

### Things that went well: 

- The correct branch name 
- The correct file _projects/vrms.md was edited
- You provided screenshots
- Set this up in my end I was able to see what the changes you made. 

Keep it up!

**Comment by Sujay-Anantha** [comment]
Great Job @theogguu, 

- The PR uses the correct naming format.
- The PR is linked to the original issue: #7473.
- The summary of the work done is concise and accurately describes the changes.
- The visual changes on the website match the screenshots provided.

**Review by Sujay-Anantha — APPROVED** [review]

**Comment by daras-cu** [comment]
Thanks for taking on this issue @theogguu, nice work. Don't forget there are a couple more action items to check off on the original issue #7473 now that this is merged.

**Pull request merged**
