### PR TITLE
Capitalize Slack on line 36 of pre-work-template--dev.md

### LINKED ISSUE #7193: Fix Capitalization of "Slack" in Issue Template pre-work-template--dev.md line 37
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/.github/ISSUE_TEMPLATE/pre-work-template--dev.md?plain=1#L37

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template---dev.md` in your code editor
- [x] On Line 37, replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [x] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [x] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  image

  </details> 
- [x] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  image

  </details> 
- [x] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  image

  </details> 

- [x] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [x] Copy the URL of the issue creation page and save for later use.  
- [x] Verify the appearance of the issue template.
- [x] Complete the Pull Request process by visiting the URL saved from the push command.
- [x] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
```
 ### For Reviewers
- Use this URL to check the updated issue template: [INSERT URL of issue creation page]
```
- [x] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template in your fork of the repository
- [x] Submit your pull request with your changes for review
- [x] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### For Merge Team
- [ ] Release the dependency for this issue in #6842. If all the dependencies have been completed, close that issue.

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template---dev.md?plain=1

- This issue is part of Issue Making Issue #6842 and ER #6163.

### PR DESCRIPTION
**Pull request by aadilahmed**
Fixes #7193

### What changes did you make?
  - Capitalized "Slack" on line 36 of the file .github/ISSUE_TEMPLATE/pre-work-template---dev.md

### Why did you make the changes (we will use this info to test)?
  - To make sure that "Slack" is capitalized in the pre-work issue template for developers 
 
### For Reviewers
- Use this URL to check the updated issue template: https://github.com/aadilahmed/website/issues/new?assignees=&labels=Complexity%3A+Prework%2C+Feature%3A+Onboarding%2FContributing.md%2C+role+missing%2C+size%3A+1pt&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-08-17 at 19-14-35 New Issue · aadilahmed_website

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-08-17 at 19-12-59 New Issue · aadilahmed_website

</details>

### CODE REVIEW

**Comment by dcotelessa** [comment]
M-F: Noon-4
ETA: 2hours

**Comment by mrodz** [comment]
**Availability**: Weekdays 5pm-9pm, Weekends 10am-5pm
**ETA**: EOD 8/19

**Review by mrodz — APPROVED** [review]
Hi @aadilahmed, great work!
- Correct to/from branches
- Correct linked issue number
- Fair description of your patch and its justification
- Fixed the issue at hand
- Made testing the patch easy by changing your fork's default branch and providing an easy URL

I checked out your change, and it looks great. Keep up the good work!

**Review by dcotelessa — APPROVED** [review]
- Branches are corrcet
- issue number is correct
- Descriptive explanation of fix and reason
- Tested and works!

Thank you, great job!

**Pull request merged**
