### PR TITLE
SDG 17: Rename and Replace Partnerships for the Goals svg

### LINKED ISSUE #4258: SDG 17: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `partnerships.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-17.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg17.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the image you just added by changing
```
<img src="/assets/images/sdg/partnerships.svg" alt="17 Partnerships For The Goals" />
```
to
```
<img src="/assets/images/sdg/sdg17.svg" alt="17 Partnerships For The Goals" />
```
- [x] Using Docker, check the About page's Sustainability section (https://www.hackforla.org/about/#sustainability) to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by karengcecena**
Fixes #4258

### What changes did you make and why did you make them ?

  - Deleted partnerships.svg from assets/images/sdg
  - Downloaded the new E-WEB-Goal-17.svg and renamed it to sdg17.svg so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf).
  - Added sdg17.svg to assets/images/sdg

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-04-11 at 10 48 24 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2023-04-11 at 10 40 02 AM

</details>

### CODE REVIEW

**Comment by Jaretzbalba** [comment]
Review ETA: EOD 4/11/23
Availability: 1 hour

**Review by Jaretzbalba — APPROVED** [review]
@karengcecena I see that the svg image for the Partnerships for the Goals was replaced correctly and looks good on my local machine. Goob job working on this issue!

**Comment by arcan9** [comment]
Review ETA: EOD 04/12
Availability: afternoon PST, M-F

**Comment by janice87** [comment]
Review ETA: 04/12 EOD
Availability: 4/11 & 4/12 5-9PM

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. I see that the partnerships svg is deleted and sdg17 is added in the correct directory. The visual changes are reflected and shows up in the same spot as the live webpage. Great job on this issue!

**Review by arcan9 — APPROVED** [review]
Nice work @karengcecena!

- You made the changes that were outlined in the issue
- Made in the correct branch
- Linked issue
- Stated reason for the change

**Pull request merged**
