### PR TITLE
Remove unused alt-hero field from ballot-nav.md project file

### LINKED ISSUE #2921: Remove unused `alt-hero` field from ballot-nav.md project file
### Overview
As a developer, I want to make sure unused code is removed from the codebase in project cards so that
- time to load the website is as low as possible,
- it's easier to understand the code, and
- time to review the code is reduced.

### Details
In project md files, `image-hero` is a decorative background image and `alt-hero` is the alt text associated with `image-hero`. However, `alt-hero` text is not used anywhere in our codebase since the `image-hero` is used as an SCSS background image.

Moreover, if the `image-hero` were to be used in an img HTML tag in the future, the alt text for all the `image-hero` images would be `alt=""`, which could be set programmatically for all the alt properties associated with each `image-hero`. 

### Action Items
- [x] For the file `_projects/ballot-nav.md`, remove line 8 for the alt-hero
```
alt-hero: 'Map of the United States with each state and county outlined.'
```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2722 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2722 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #2722 

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/ballot-nav.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/d1f1ce97eb2cff948b0f2bee52158feba417a3ee/_projects/ballot-nav.md?plain=1#L8

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

### PR DESCRIPTION
**Pull request by juliansmith0**
Fixes #2921

### What changes did you make and why did you make them ?

  - Remove Line 8 from ballot-nav.md project file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Update to .md file only—no visual change

### CODE REVIEW

**Comment by harshitasao** [comment]
Availability: 1 hour
Review ETA: 24/05/2022 (end of the day)

**Review by harshitasao — CHANGES_REQUESTED** [review]
Good job @juliansmith0. The changes look good to me. However, please checkout the action item in the original issue.

**Review by blulady — APPROVED** [review]
The pull request is done with the correct branch. There is a linked issue and it is the correct issue. The pr correctly addresses the linked issue, namely deleting the alt-hero from ballot-nav.md. There aren't pictures but this pr doesn't need them and it is properly noted. The website looks great in browser. The source code is clean.
Looks good. Great Job!!

**Comment by juliansmith0** [comment]
> Good job @juliansmith0. The changes look good to me. However, please checkout the action item in the original issue.

Ahah! Apologies I missed that. Done!

**Review by harshitasao — APPROVED** [review]
@juliansmith0 Thanks for working on this issue.

**Comment by Sparky-code** [comment]
@juliansmith0 Looks great! - a reminder to include a sentence about '...and why did you make them?' to the section of your PR on changes made. It helps serve as another check on your process and reinforces documentation over time.

**Pull request merged**
