### PR TITLE
Add GitHub handle in brigade-organizers-playbook.md

### LINKED ISSUE #6156: Add github-handle for Liz Brown in brigade-organizers-playbook.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/brigade-organizers-playbook.md` in the IDE
- [x] Replace:
```
- name: Liz Brown
```
with
```
- name: Liz Brown
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/brigade-organizers-playbook

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by regular-polygon**
Fixes #6156 

### What changes did you make?
  - Add github-handle for Liz Brown in brigade-organizers-playbook.md

### Why did you make the changes (we will use this info to test)?
  - Because we need to create a single variable github-handle to hold the github handle for each member of the leadership team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes.

### CODE REVIEW

**Review by anthonypz — APPROVED** [review]
Hey @regular-polygon, great work!

- the branches are correct
- the correct issue is linked in the pull request
- the correct changes have been made

**Comment by LRenDO** [comment]
Hi @urvishp13! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Comment by urvishp13** [comment]
**Availability:** 11am - 5pm 4/18/24
**ETA:** EOD tomorrow 4/18/24

**Review by urvishp13 — APPROVED** [review]
Hey @regular-polygon, great job finishing this issue!

- PR contains the correct branch
- good job linking the issue in the PR
- good job using spaces instead of tabs to indent the `github-handle` variable
- website hasn't been changed in desktop, tablet, or mobile view, as stated (verified using Firefox)

**Pull request merged**
