### PR TITLE
Added Program-Area

### LINKED ISSUE #2271: Add Program Area: Green Earth OS
### Overview
We need to add program area information to the Green Earth OS project so that it will show up when we add the program areas filter.

### Action Items
- [ ] Review the project.md file model in the Resources section
- [ ] Add the following text to the file indicated in the Resources section
- [ ] See visual changes on the [Projects page's](https://www.hackforla.org/projects/) Green Earth OS card.
  <details>
    <summary>Here is where you will see changes:</summary>
    Green-Earth-OS
  </details>
```
program-area:  
    - Environment
```

### Resources/Instructions
- File location to make the change: _projects/green-earth-os.md

- URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md

- [Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

- Link to [Projects page](https://www.hackforla.org/projects/)

### PR DESCRIPTION
**Pull request by scarter31191**
Fixes #2271

### What changes did you make and why did you make them?

  - Added program area 
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-03-15 at 11 47 15 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-03-15 at 11 47 44 PM

</details>

### CODE REVIEW

**Comment by answebdev** [comment]
Review ETA: 3/16/2022 (end of day)
Availability: 3 hours

**Review by answebdev — APPROVED** [review]
@scarter31191 Thank you for submitting your PR. For this issue, the text needed to be added to `_projects/green-earth-os.md`, which I can see that you did. And the visual changes are seen on the Green Earth OS card on the Projects Page, which I was able to see. Great job!

One minor thing is to please add this PR to the Project Board. Thank you.

**Comment by Carlos-A-P** [comment]
Availability: 1 hr
ETA: 3/17/2022

**Comment by Carlos-A-P** [comment]
@scarter31191 can you add this PR to the project board.

**Comment by scarter31191** [comment]
ok, I think I added it to the board now, sorry about that.

**Review by Carlos-A-P — APPROVED** [review]
@scarter31191 Good job on this issue! I was able to see the code changes and the changes on the website.

**Pull request merged**
