### PR TITLE
Edit content field and remove type field from environmental-impact.yml

### LINKED ISSUE #2830: Edit content field and remove type field from environmental-impact.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/environmental-impact.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: Image
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/environmental-impact.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/environmental-impact.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/environmental-impact.yml#L11

### PR DESCRIPTION
**Pull request by StephenTheDev1001**
Fixes #2830

### What changes did you make and why did you make them ?

  - change content field to content-type: image for clarity of purpose
  - remove type field to remove redundancy with content field
 
### Screenshots of Proposed Changes Of The Website

Moving files to another directory. No visual changes to the website.

### CODE REVIEW

**Comment by perlaroyerc** [comment]
Availability: 11-7 ET M-F
ETA: EOD 3/30

**Comment by LOSjr4** [comment]
availability: mon, tues, thurs 9AM-1PM
eta: 03/30/2023 noon

**Review by LOSjr4 — APPROVED** [review]
Everything looks good Stephen. Although your description says you changed content-type: **icon** instead of **image**, you did make the correct changes in the code.

**Review by perlaroyerc — CHANGES_REQUESTED** [review]
Good job working on your first issue @StephenTheDev1001! The changes look good in the local environment, the issue was linked, and the branches are correct.

I suggest a few minor edits:
- As Luis mentioned above, you should edit the PR description to the correct content-type `image`.
- Add a brief description explaining "why" you made the changes, as it helps ensure the changes align with the project's goals and the HFLA guidelines.
- If no visual changes were made, add an explanation for no images like: `No visual changes made.`

**Review by perlaroyerc — APPROVED** [review]
Great job addressing the requested changes!

**Comment by christinaor** [comment]
Thanks for working on this issue Stephen! I can see the changes made on line 4 and the deletion of line 11.

**Pull request merged**
