### PR TITLE
added github handle variable for olivia chiong

### LINKED ISSUE #5506: Add new variable github-handle for member Olivia Chiong in 100-automations.md
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in your IDE.  
- [x] Replace:
```
- name: Olivia Chiong
```
with
```
- name: Olivia Chiong
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by crystallyyy**
Fixes #5506 

### What changes did you make?
  - under "name: Olivia Chiong", I added "github-handle" variable
  -I made sure not to use tab, and deleted the dash 
  -

### Why did you make the changes (we will use this info to test)?
  -good first issue
  -
  -
### Screenshots of Proposed Changes Of The Website

Screen Shot 2023-10-05 at 4 22 12 PM

### CODE REVIEW

**Comment by Jfong1218** [comment]
ETA: 9/26/23
Availability: Weekday afternoons

**Comment by homeroochoa47** [comment]
ETA: EOD 9/26/23
Availability: Weekday Evenings

**Review by Jfong1218 — COMMENTED** [review]
- The new branch is properly going into the correct branch gh-pages. ✅
- Original issue was properly linked and referenced. ✅
- github-handle has been added into the file per request. ✅

Hey Crystal,

Great job on the edits, My only request is your comment in this pull request seem to have some messed up formatting, as well as the images in before and after change is not showing. If the issue you've fixed have no visual changes you can simply delete that section of the comment. I will check back again when the comment formatting has been fixed and will approve then.

Great job

*Edit:
I've just found out from a different issue where the github handle needs to be added that this addition will separate the div in the website into 2 and will create another card with Olivia's picture and blank name. I am in the process of finding out what the website team wants to do about this. But right now this change will cause the website no not display the correct info.

**Comment by roslynwythe** [comment]
@crystallyyy @Jfong1218 @homeroochoa47 There is an error in this issue.  It will be edited shortly.  In the meantime please do not review or merge.  Thank you

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@crystallyyy Please see the updated issue and my comment in the issue.  I apologize for the error!

**Comment by crystallyyy** [comment]
Hello, I corrected the error the way the issue #5506 specifies and am hoping to get this pull request approved! Let me know if there's anything else I should do! @Jfong1218 @homeroochoa47

**Review by roslynwythe — APPROVED** [review]
Thank you @crystallyyy for updating the PR based on the corrected issue.  The PR has the correct branches and is descriptive and in the browser the 100 automations webpage looks fine.

**Review by Jfong1218 — APPROVED** [review]
Hello Crystal,

Great job! I see no problem with this PR and will be approving it with this review.

Thank you

**Pull request merged**
