### PR TITLE
Add link to project header 3802

### LINKED ISSUE #3802: Citizen Engagement page: Add links to each red project header
### Overview
On the Citizen Engagement webpage [1], we want each red project header to redirect to its project's information webpage when clicked so that visitors to our website can easily get more information about the project they are interested in.

### Details
**Currently on the Citizen Engagement webpage**
<details>
  <summary>Click here to see a couple of examples of red project headers, which I have circled in blue</summary>
  
</details>

**Desired result**
When the red project header is clicked, it should redirect to its project's information webpage.
  - **Note:** When using an anchor tag `<a></a>` around the header, it will automatically underline it. This is expected and is fine.
<details>
  <summary>Click here to see a couple of examples of the desired red project headers</summary>
  Screenshot 2023-02-05 103530
</details>

#### Developer
- [x] Read the `How to Link to a Project's Detailed Info Page` wiki article [2]
  - You will be using `slug` to implement the code for this issue.
- [x] In `_includes/citizen-engagement-cards.html` [3], make it so that when a user clicks on a red project header, they are redirected to the project's detailed information page.
  - For example, when the `Open Community Survey` red header is clicked, it should redirect to https://www.hackforla.org/projects/open-community-survey.
  - **Note:** When using an anchor tag `<a></a>` around the header, it will automatically underline it. This is expected and is fine.
  - [x] On the current webpage, make sure each of the red project headers redirects to its respective project's detailed information page.
  - [x] Make sure that the code you implement is dynamic and will work for any future projects that will be added to the Citizen Engagement page.
- [x] Once your pull request has been merged, 
  - [x] Please update the `Page screenshot (current version)` section in the Citizen Engagement page wiki article [4] with an updated desktop and mobile screenshot from the website, and update the date.
    - [x] Use the GoFullPage Chrome extension [5] to screenshot the whole webpage at once.

#### Product Manager
  - [x] Once the pull request associated with this issue is merged, go to issue #3756 and check if all the issues listed under the `Dependency` section are closed. If they are all closed, move that issue (#3756) into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.

### Resources/Instructions
1. [Citizen Engagement webpage](https://www.hackforla.org/citizen-engagement)
2. [How to Link to a Project's Detailed Info Page](https://github.com/hackforla/website/wiki/How-to-Link-to-a-Project's-Detailed-Info-Page)
3. [_includes/citizen-engagement-cards.html](https://github.com/hackforla/website/blob/gh-pages/_includes/citizen-engagement-cards.html): HTML file that provides the layout/format for each card on the Citizen Engagement page
4. [Citizen Engagement page wiki article](https://github.com/hackforla/website/wiki/Citizen-Engagement-page): Contains additional information about the Citizen Engagement webpage
5. [GoFullPage Chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en) 
6. Issue #3756 is dependent on this issue being completed.

### PR DESCRIPTION
**Pull request by Thinking-Panda**
Fixes #3802
### What changes did you make and why did you make them ?

  - Added link to the project header. The project header appears with an underline and clicking on it take you to the project details page.
  - Link is added dynamically so the code works for any new projects added in future.
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before_changes_to_header

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Link_Added

</details>

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 2/23 4 - 7 pm
ETA 2/24

**Comment by roslynwythe** [comment]
Hi @Thinking-Panda, thank you for working on this issue.   Your branch includes commits to green-earth-os.md which are not relevant to this issue.  I will consult with the merge team to determine how to proceed.

**Comment by Thinking-Panda** [comment]
Thankyou @roslynwythe!

**Review by roslynwythe — APPROVED** [review]
Great work @Thinking-Panda, the branches are setup correctly, the code is correct and clean and checks out fine in the browser.  Thank you for completing this issue!

**Comment by MattPereira** [comment]
**Availability:** 7 - 9 PM Sunday - Thursday
**ETA:** 30 minutes

**Review by MattPereira — APPROVED** [review]
Well done @Thinking-Panda 

Love the variable name `project_relative_path` :+1:

**Comment by Thinking-Panda** [comment]
Thank you for all your help, @MattPereira !

**Pull request merged**
