### PR TITLE
Refractor-HTML-2FA.html-line 45-#5710

### LINKED ISSUE #5710: Refactor HTML to resolve linter error: _guidepages/2FA.html - line 45
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 45
- [x] Change the line of code
```
<div class='section-container'>
```
to
```
<div class="section-container">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

### PR DESCRIPTION
**Pull request by Ayrh1**
Fixes #5710

### What changes did you make?
  Update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"
  Line 45 <div class='section-container'>  -> <div class="section-container">
### Why did you make the changes (we will use this info to test)?
Actions requires and per issue instructions

### CODE REVIEW

**Comment by luisitocanlas** [comment]
Review ETA: EOD 3/8/24
Availability: 3/8/24

**Review by luisitocanlas — APPROVED** [review]
Hi @Ayrh1 ,

- Pull request is done with the correct branch.
- The issue is linked properly.
- Pull request changes and reasoning were provided.
- Everything looks good!

Thank you for working on this issue!

**Comment by marioantonini** [comment]
Review ETA: 3 PM 3/10/24
Availability: 2-6 pm Sunday

**Review by marioantonini — APPROVED** [review]
Hi @Ayrh1 ,

- Pull request is done with the correct branch.
- Issue linked.
- Action items marked.
- Everything looks good!

Thank you for working on this issue!

**Pull request merged**
