### PR TITLE
1255 refactor current data into data external

### LINKED ISSUE #1255: Change Join Us page URL
### Overview
We need to change the [Join Us page](https://www.hackforla.org/join-us) URL from "join-us" to "**join**", to keep it consistent with the [About page](https://www.hackforla.org/about) URL, and the upcoming nav bar

### Action Items
- [ ] Research how to change page URL on the HfLA site
- [ ] Change the Join Us page URL from "join-us" to "join" (from https://www.hackforla.org/join-us to https://www.hackforla.org/join )

### Resources/Instructions
[Join us page](https://www.hackforla.org/join-us)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### LINKED ISSUE #1266: Refactor The Current Data
### Overview
Restructuring site architecture to follow more along the lines as documented in jeklyll docs
https://jekyllrb.com/docs/
 
### Action Items
- [ ] Refactor the current data into data/external (including fixing the GH actions that populate it)

### Resources/Instructions
https://jekyllrb.com/docs/

### PR DESCRIPTION
**Pull request by akibrhast**
Fixes #1266 

 - [x] Refactor the current data into data/external (including fixing the GH actions that populate it)

Please looks at the commit messages for reference to what this pr changes

### CODE REVIEW

**Comment by cnk** [comment]
Looks OK at a glance. Does someone else have time to review it properly?

**Comment by cnk** [comment]
And I think .github/workflows/_wins-data.yml and .github/workflows/wins-data.yml are 2 versions of the same thing. Suspect only one is in use. Could someone check and delete the one that is no longer in use? In this reorg or in a separate PR.

**Comment by akibrhast** [comment]
@cnk They are not the same file one is using curl to pull data, one is using node script to pull data. You are right that currently only one of them is in use. The _wins-data.yml is a work in progress that would eventually be used instead of the current wins-data.yml will be deleted and the _wins-data.yml will be renamed to wins-data.yml

**Comment by jbubar** [comment]
@cnk What would be the best way to review this?
It looks good to me, but I am not sure how to review it because they are github actions

**Comment by cnk** [comment]
@jbubar For testing substantial changes to GitHub actions, I usually change the triggering conditions so I can run them at will - and then run them in my fork.

But for the changes here, simply changing the directory where the data is written, I think it is sufficient to proofread the files to make sure we caught all places that need to be changed to match.

**Review by jbubar — APPROVED** [review]
Looks good. I proof read it very closely, but I did not test it out. I think it should be good

**Comment by jbubar** [comment]
Looked over it a few more times, and merged it

**Pull request merged**
