### PR TITLE
5633-update-prework-issue

### LINKED ISSUE #5633: update prework issue instructions regarding website-write team
### Overview
We need to remove outdated and confusing instructions from the prework issue template

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] replace
```
- [ ] Once added to the website-write team:
  - [ ] Self Assign this issue (gear in right side panel)
  - [ ] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [ ] Add this issue to the Project Board under the Projects section (gear in right side panel)
```
with
```
- [ ] Self Assign this issue (gear in right side panel)
- [ ] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
- [ ] Add this issue to the Project Board under the Projects section (gear in right side panel)
```
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

### PR DESCRIPTION
**Pull request by GRK1998**
Fixes #5633

### What changes did you make?
  - Removed outdated and confusing instructions from the prework issue template

### Why did you make the changes (we will use this info to test)?
  - Outdated, and causing confusion

### For Reviewers
- Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE](https://github.com/GRK1998/website/issues/new?assignees=&labels=Feature%3A+Onboarding%2FContributing.md%2Cprework%2Csize%3A+1pt%2Crole+missing%2CComplexity%3A+Prework&projects=&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D)

### CODE REVIEW

**Review by ajb176 — CHANGES_REQUESTED** [review]
Hi @GRK1998, I think you mistakenly forgot to add the issue number.

The first line of your PR post reads: Fixes #replace_this_text_with_the_issue_number

Edit that in quickly, it's important that the PR has a linked issue. Based on the name of your branch it seems to be addressing #5633

- I can also see that you didn't move issue #5633 to 'in progress' after you assigned it to yourself. It's still on the prioritized backlog. You should do that now, and in the future when you assign yourself to an issue in the prioritized backlog, move it to in-progress immediately. You can find information about this [here.](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#24-claiming-an-issue)

- Unfortunately, the code edit you've made doesn't accurately follow the instructions in issue #5633. You added the correct three lines, but the instructions request you to remove four lines, not three. There is one line that was meant to be removed under the lines you've added. Please take a look at the instructions in the linked issue and take a look at the change you've made, I think you'll spot the issue. 

- Additionally, there are some instructions given in the bottom of the linked issue that re-direct you [here.](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) The instructions direct you to construct a URL containing a link to the new version of the template for reviewing/testing purposes. That URL is meant to replace the 'screenshots' section of the PR. You'll have to follow those directions and add that URL. 

I hope these issues don't discourage you, please comment if you need help with anything!

**Comment by GRK1998** [comment]
Hi @ajb176 I have made the changes as per the requirement above. Could you please check and let me know if there are any additional changes to be made.

**Review by ajb176 — APPROVED** [review]
- Linked issue was added and moved to 'in progress'
- Commit was edited to accurately match instructions in linked issue
- URL was provided for reviewing the edited template, and the template looks good

Nice work @GRK1998, especially with making the changes so quickly

**Comment by mademarc** [comment]
Review ETA: 10/12/2023
Availability: 7:18PM

**Review by mademarc — APPROVED** [review]
Hey @GRK1998 good job in updating the issue by removing the "- [ ] Once added to the website-write team:" line.

**Pull request merged**
