### PR TITLE
add github-handle Aleiya Gafar in brigade-organizers-playbook.md issue -#6154

### LINKED ISSUE #6154: Add github-handle for Aleiya Gafar in brigade-organizers-playbook.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/brigade-organizers-playbook.md` in the IDE
- [x] Replace:
```
- name: Aleiya Gafar
```
with
```
- name: Aleiya Gafar
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/brigade-organizers-playbook

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by Jperparas**
Fixes #6154
### What changes did you make?
  - added github-handle variable to Aleiya Gafar

### Why did you make the changes (we will use this info to test)?
  - reduce redundancy

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 
   -no visual changes

### CODE REVIEW

**Comment by colin-macrae** [comment]
Availability: 3/12-14
ETA: 3/14

**Comment by angela-lee1** [comment]
Review ETA: EOD 3/14
Availability: 3/13 3/14

**Review by angela-lee1 — APPROVED** [review]
@Jperparas Great job! 
- you linked the correct issue, your branch is correct
- a clear description is provided for the reason for making the change
- you gave the reason for not providing screenshots
- the appearance of the project webpage is unchanged at all screen sizes
Thank you!

**Review by colin-macrae — APPROVED** [review]
@Jperparas , great job. 

- The branch is going into the correct branch gh-pages. ✅
- The original issue [issue with #number] was properly referenced. ✅
- Per the instructions on the original issue, the specified lines of code were properly updated. ✅

**Pull request merged**
