### PR TITLE
combined scss files

### LINKED ISSUE #1142: Consolidate all of the scss files currently attached to the home page into the _home.scss file
### Overview
We need to combine all of the contents of the scss files that are currently connected to the homepage into the _home.scss file to keep this consistent with other pages on the site (one scss file per page).

### Action Items
- [ ] Find all of the scss files connected to the homepage
- [ ] Move all of the content from those scss files into the combined _home.scss file (created by @kevinreber )

### Resources/Instructions
[Home page](https://www.hackforla.org/)
Example of one of the scss files connected to the home page - [_contact-us.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_contact-us.scss)

Connected to #864

### PR DESCRIPTION
**Pull request by sanchece**
Fixes #1142

-Moved scss content into _home.scss file
-_home-getting-started.scss is included

### CODE REVIEW

**Comment by jbubar** [comment]
@sanchece could you name all the files that you took from to merge into the home.scss?
And can you delete those files?

**Comment by sanchece** [comment]
image

Into image

**Comment by kceddinger** [comment]
@sanchece Josh is available to help you resolve the merge conflicts or you can come to the meeting on Tuesday. We can't merge it until we resolve the merge conflicts. Apologies for the late review.

**Review by erikaBell — APPROVED** [review]
looks good ~

**Pull request merged**
