### PR TITLE
Added Jason Yung back into Access the Data profiles

### LINKED ISSUE #5332: Update Project Profile Access the Data
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We want the project information on our website to be presented to visitors in a clear, accurate, and intuitive manner. On the Access the Data project page, the arrangement of the team member profiles needs to be rearranged to display team leaders at the top of the page.

### Action Items

- [x] On the [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) markdown page, locate the entry for Jason Yung.
- [x] Move the entry from the current location to one that is just under the entry for AJ Price so that the first team members listed on the Access the Data webpage are  for the Product Manager and the Project Manager.
```
  - name: Jason Yung
    role: Project Manager
    links:
      slack: 'https://hackforla.slack.com/team/U059W9P96C8'
      github: 'https://github.com/merlinsmagic'
    picture: https://avatars.githubusercontent.com/merlinsmagic
```
- [x] Confirm on Docker in your local repo that the webpage displays as intended and that no other, unintended changes have been made.

### Resources/Instructions
[Access the Data](https://www.hackforla.org/projects/access-the-data) project page.
This issue was initiated by #5274

### PR DESCRIPTION
**Pull request by A-Wu5**
Fixes #5332 

### What changes did you make?
  - Added the following into project profiles in access-the-data.md
  
   ```
 - name: Jason Yung
    role: Project Manager
    links:
      slack: 'https://hackforla.slack.com/team/U059W9P96C8'
      github: 'https://github.com/merlinsmagic'
    picture: https://avatars.githubusercontent.com/merlinsmagic
```

### Why did you make the changes (we will use this info to test)?
  - To ensure that the project website page for Access the Data is accurate and up to date to prevent confusion from users.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>
#5332Before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
#5332After

</details>

### CODE REVIEW

**Comment by tesiahwang** [comment]
Review ETA: 9/22/2023
Availability: flexible

**Review by tesiahwang — APPROVED** [review]
Great job, @A-Wu5 - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable & clean!

**Comment by agutiernc** [comment]
Review ETA: 9/23/2023
Availability: Afternoon to evening

**Review by agutiernc — APPROVED** [review]
The following are confirmed:
- Correct branch and linked issue
- Moved collaborator to the correct location in the file
- Displayed correctly and in different views in the browser
- Confirmed before/after screenshots

Great job @A-Wu5! Thanks for contributing.

**Pull request merged**
