### PR TITLE
Update add labels trigger #2939

### LINKED ISSUE #2939: Edit contents of add-labels-template.md file
### Overview
As a developer, I need to edit contents of [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file so that the members who are not part of the website repo would get notified about their inability to add labels

### Action Items
- [x] Review [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) and [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) files
- [x] Add a note for the team members (who do not have write access for the website repo) to ignore the comment about adding labels to the [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file
- [ ] Test if the updated comment gets posted on an issue in your own repo

### Checks
- [ ] For testing in your own repo (after making the necessary code changes)
    - [ ] Create a project board in your own repo
    - [ ] Create a new issue and add it to one of the newly created columns (do not add labels to your issue so that [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file gets triggered)
    - [ ] Make sure the post with updated comment gets posted on your issue
- [ ] Make sure all the functionalities in [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file still work fine

### Resources/Instructions
- File where changes need to be made [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md)
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

### PR DESCRIPTION
**Pull request by poorvi4**
Fixes #2939

### What changes did you make and why did you make them ?
Modified add-labels-template.md to include note to notify users who do not have write access to repository to ignore the 'add labels' section

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
Availability: 1 hour
ETA: By the end of 4/11

**Comment by Sparky-code** [comment]
Availability: 1hr
ETA: 4.11 EOD

**Review by Sparky-code — DISMISSED** [review]
Hey @poorvi4, Everything looks great! Tested the changes locally and it worked as expected, file appears to trigger normally with the additional text.

<details>
<summary>Visuals before changes are applied</summary>

image)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

**Review by kathrynsilvaconway — CHANGES_REQUESTED** [review]
Nice Work adding this clarification to the add labels template. I can see your changes display correctly, no problems there.

For added clarity, it might be better to move the note directly under the step that has to be ignored. If a user is follwing the driections step by step, they might spend time trying to figure out how to add a label before they notice it at the bottom. @SAUMILDHANKAR, do you have a preference?

Otherwise, it looks good.

**Comment by Sparky-code** [comment]
@kathrynsilvaconway Thats a good point, I would agree with you on that. 

Maybe underneath the second line:

```Please don't forget to add the proper labels to this issue. Currently, the labels for the following are missing: ${labels}```
**NOTE: If you do not have 'write' access to this directory, please ignore the adding proper labels comment.**

**Comment by SAUMILDHANKAR** [comment]
@kathrynsilvaconway I wanted to leave the issue action item open ended and let a developer be the best judge of how to implement this but your suggestion is really helpful (would definitely save user's time). Thanks for bringing it up.

**Comment by poorvi4** [comment]
@kathrynsilvaconway that's a great suggestion! I agree with Saumil that it'll ease in readability. Will incorporate those changes

**Comment by kathrynsilvaconway** [comment]
> @kathrynsilvaconway that's a great suggestion! I agree with Saumil that it'll ease in readability. Will incorporate those changes

Don't forget to request a a re-review when you're ready and I will approve it.

**Review by Sparky-code — APPROVED** [review]

**Review by kathrynsilvaconway — APPROVED** [review]
@poorvi4 Nice work adding this this update to the add labels trigger message. Everything looks good!

**Pull request merged**
