### PR TITLE
Accomplishments edit by year 4188

### LINKED ISSUE #4188: Edit Accomplishments in About Page to show different years
### Overview
We want to highlight the accomplishments across HackforLA for the projects across multiple years. Currently, the [About page](https://www.hackforla.org/about/#accomplishments) only shows accomplishments for the year 2022. We need to implement a new format so that a user can see highlights from previous years. 

### Action Items
- [x] We need to add three fields to [_data/internal/accomplishments.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml)
  - [x] `year`
  - [x] `project-file` (example: `project-file: food-oasis.md`)
  - [x] `program-area` (example: `program-area: Social Safety Net`)
- [x] If a project file exists, the program area should be retrieved from the project file, by using Liquid to run through the [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects_) collection and find the program area that matches with the name of the project.  Therefore,  `program-area` should be specified only if no project file exists.  
- [x] See most recent Figma design (in resources below) and zoom into the Accomplishments section
- [x] Navigate to [_includes/about-page/about-card-accomplishments.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html)
- [x] Implement the design so that when a user clicks on any of the years, the section shows accomplishments from that year
- [x] Note: The final layout for the Accomplishments section will slightly differ from the Figma design
   - [x] Rather than list accomplishments by project with the program area above as seen in current design (see below), 
 we want to list the accomplishments by program area. So the program area (e.g. Citizen Engagement) would be like the black header, and the accomplishments for each project in that program area will be listed. This is so the program areas do not get repeated for each project in that program area. 

### Resources/Instructions
- [about.html](https://github.com/hackforla/website/blob/gh-pages/pages/about.html)
- [about.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/about.js)

#### Current design
- About page, accomplishment section: https://www.hackforla.org/about/#accomplishments
- 
  <details>
  <summary>image from current state of website figma</summary>

  image
  </details>

#### Future State of website after this issue is completed
- [Figma, accomplishment section](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22519-129240&t=uYA0fTohWkL30foQ-0)
<details><summary>image from future state of website figma</summary>

**Web View**

**Mobile View**

</details>

### PR DESCRIPTION
**Pull request by Thinking-Panda**
Fixes #4188

### What changes did you make?
  - Added years, program-area or project-file to `accomplishments.yml`
  - added function to `about.js` to retrieve data, sort accomplishments and filter by year
  - added some css to `_about.scss`

### Why did you make the changes (we will use this info to test)?
   - `accomplishments.yml`- added project-file if existed and program-area if project file does not exist
  - `about.js`- added functions to display years for accomplshments, retrieve data from YAML file, handle click events and display accomplishments by year
  - `about.html`- to pass the variable {{accomplishments}} through a `<script>` tag
  - 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before_Change_Mobile
Before_Change_Tablet
Before_Change_Desktop

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
After_Change_Mobile
After_Change_Tablet
After_Change_Desktop

</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
NOTE TO REVIEWERS & MERGE TEAM: I have added sample accomplishments to test for different years. After the PR is reviewed, I can clean up the sample accomplishments before merging.

**Comment by kwangric** [comment]
ETA: 11/28
Availability: 11/26 - 11/28 evenings

**Comment by LRenDO** [comment]
Hi @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Review by kwangric — CHANGES_REQUESTED** [review]
Hey @Thinking-Panda, great job tackling this large issue!

- Year & Program Area/Project Files fields have been added to all the accomplishments.
- Accomplishment section on the About page has been changed to include an option to view accomplishments from different years.
- Accomplishments are listed by program area.

I have a few requested changes. Both these findings don't break the functionality of the new design, but if they can be fixed that would be great!

- When the window is resized from desktop to mobile view, or vice versa, the selected year doesn't stay consistent. For example: if you select "2022" in desktop view, then resize to mobile view, it shows "All" in the dropdown menu even though the 2022 results are still displayed.
- The cursor changes to the text-select icon when hovering over the years. This might be confusing since they are links.

**Comment by Thinking-Panda** [comment]
Thank you @kwangric for the review. I will work on it and push the changes soon.

**Comment by mademarc** [comment]
Review ETA: 11/30/2023
Availability:  7:08PM

**Review by mademarc — DISMISSED** [review]
Hey @Thinking-Panda good call on the yml, js & scss  file changes and @LRenDO the ETA and Availability is there.

**Review by kwangric — DISMISSED** [review]
Thanks for making the changes!
- Selected year stays consistent when switching between desktop and mobile view.
- The cursor now turns into a link icon when hovering over the years.

Great work!

**Comment by Thinking-Panda** [comment]
@kwangric , @mademarc Thank you for your review. After your approval , the sample accomplishments for 2023, 2022, 2021 are removed. Please review again and then it will be ready to be merged. Thanks!

**Review by kwangric — APPROVED** [review]
Everything still looks good!

**Review by t-will-gillis — APPROVED** [review]
Hey @Thinking-Panda Excellent work on this issue and great back and forth with @kwangric addressing comments! In mobile, tablet, and desktop in Docker, the code edits appear to satisfy the requirements of 4188 and the intent shown on Figma with the minor edits to the subheaders for the program areas as noted.

Super work again and thanks for taking on this issue

**Pull request merged**
