### PR TITLE
Update Communities of Practice: UI/UX (Add Peter Gwon) #5874

### LINKED ISSUE #5874: Update Communities of Practice: UI/UX (Add Peter Gwon)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep communities of practice information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_data/internal/communities/ui-ux.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Peter Gwon
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U051F68PG2C
      github: https://github.com/pogwon
    picture: https://avatars.githubusercontent.com/pogwon
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the UI/UX section on the Communities of Practice page [^2]
- [x] Once your pull request is merged, go to #5824 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] Move #5824 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #5824
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

### PR DESCRIPTION
**Pull request by dustinowen**
Fixes #5874

### What changes did you make?
**Add:**
  - name: Peter Gwon
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U051F68PG2C
      github: https://github.com/pogwon
    picture: https://avatars.githubusercontent.com/pogwon

### Why did you make the changes (we will use this info to test)?
  - Per 'Update Communities of Practice: UI/UX (Add Peter Gwon) #5874'

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-11-14 at 1 30 29 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-11-14 at 1 35 28 PM

</details>

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: 6 PM 11/14/23
Availability: 5-8 PM Tuesday

**Review by KyleA99 — APPROVED** [review]
- Your PR is done with the correct branch.
- Yor code is correctly changed.
- Changes look great in the browser.

Reviewed and approved!

Great work @dustinowen

@roslynwythe @JessicaLucindaCheng is GHA supposed to link CONTRIBUTING.md in this PR?  I dont think that pertains to this PR and the CONTRIBUTING.md link has a 404 error.

**Comment by LukeLowrey2** [comment]
Review ETA: Thursday 11/16/23 EOD
Availability: Wednesday 11/15/23 & Thursday 11/16/23 10am - 12am

**Review by LukeLowrey2 — APPROVED** [review]
- You are committing to the correct branch
- The issue is linked to the PR
- Proper code has been added to _data/internal/communities/ui-ux.yml

Great job! PR approved.

**Comment by roslynwythe** [comment]
> @roslynwythe @JessicaLucindaCheng is GHA supposed to link CONTRIBUTING.md in this PR? I dont think that pertains to this PR and the CONTRIBUTING.md link has a 404 error.

@KyleA99 That extra instruction added by the GHA was intended to help reviewers if there was a change to CONTRIBUTING.md.  I apologize for the confusion caused when there is no change to CONTRIBUTING.md.  We're working on updating that GHA so that it will only display the instruction if CONTRIBUTING.md was included in the changed files.

**Pull request merged**
