### PR TITLE
Fixes Misspelled Word on Join Us Page

### LINKED ISSUE #2913: Fix misspelled word on join-us.html file from "commmunity" to "community"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `pages/join-us.html`,  on line 93, change the spelling from "commmunity" to "community", so

  ```
  products to the commmunity.
  ```
  becomes
  ```
  products to the community.
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/join
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/pages/join-us.html#L93

### PR DESCRIPTION
**Pull request by trishajjohnson**
Fixes #2913

### What changes did you make and why did you make them ?

  - Changes spelling of word community on line 93 from "commmunity" to "community"
  - Double checked to see that everything looked right and worked on web and mobile view.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-04-20 at 4 36 03 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2022-04-20 at 4 37 10 PM

</details>

### CODE REVIEW

**Comment by Carlos-A-P** [comment]
Availability: 1 hr
ETA: 4/20/22 EOD

**Review by Carlos-A-P — APPROVED** [review]
@trishajjohnson Great job working on this issue! I can see the code changes in the join-us.html file and everything looks good in my localhost, both on mobile and desktop view.

**Comment by tamara-snyder** [comment]
Availability: 1 hour
Review ETA: 04/21/2022

**Review by tamara-snyder — APPROVED** [review]
Hi @trishajjohnson, great work on this! I love how you highlighted the changed word in your screenshots — super clear. Thank you!

**Pull request merged**
