### PR TITLE
added justice.yml and contents

### LINKED ISSUE #3415: Add credit for Justice image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the Credits webpage is up to date.

### Details
From the Homepage Redesign Credits in Figma, here is a screenshot of the credit's information for reference:

  <details>
    <summary>Click here to see the screenshot of the Justice credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `justice.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Justice
# The url where you can get direct access to the image on the provider site
title-link: https://unsplash.com/photos/bvHcG6334dE
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Sean Lee
# Name of the image database you found it on
provider: Unsplash
# Please give the general site URL, not the link to the image
provider-link: https://unsplash.com/
# Location in our GitHub repo
image-url: /assets/images/program-areas/justice.png
# Alt text for the image on the Credits page
alt: ''
---
```
- **Note:** When you use Docker to view the Justice credit on your computer and click on the `Justice` link in the Name field, that link will lead to `Page not found`. We spoke to Bonnie about this and she said it was okay for that link for Justice to be that way.
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please do the following in issue #3130:
    - [x] Move it to the New Issue Approval column
    - [x] Remove the "Dependency" label from it
    - [x] Add a "ready for dev lead" label to it  
  
### Resources/Instructions
- [Credits webpage](https://www.hackforla.org/credits/)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- This issue is tracked in the epic #3130.

### PR DESCRIPTION
**Pull request by maryjng**
Fixes #3415

### What changes did you make and why did you make them ?
- Added justice.yml file in _data/internal/credits directory with copy pasted content per issue instructions.
- This is to add the Justice item to the credits page on the website

### Visual changes
- Website credits page now has the justice item

Before changes (feature-homepage-launch branch):
image

After changes:
image

### CODE REVIEW

**Review by jch1013 — APPROVED** [review]
The added file looks correct and I can't see any differences in the website, everything looks good!

**Comment by Adastros** [comment]
Availability (PST): 9 - 11 PM 18JAN23
Review ETA: 11PM 18JAN23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @maryjng, good job on creating the `justice.yml` file per the issue! The contents of the file match what's presented in the issue.

I noticed your pull request comment indicates no visual changes were made to the website. In this case, adding the `justice.yml` file will cause the credits page of the feature branch of the website to change. The page will have an item that looks similar to the figma design that's linked in the issue. Could you add screenshots of the credits page before and after adding the `justice.yml` file? 

<details>
<summary>Figma screenshot</summary>

image

</details>

I also think it would be good to add a brief explanation for why the changes were implemented in addition to what was changed per the issue.

**Review by Adastros — APPROVED** [review]
Thanks for updating the pull request! Looks good on my end.

**Pull request merged**
