### PR TITLE
Standardized program areas for mobile

### LINKED ISSUE #1825: Standardize Program Areas page in mobile
### Overview
We need to standardize the **mobile only** ~~header illustration~~ and mini project cards in the [Program Areas page](https://www.hackforla.org/program-areas) to make them look like the original [Figma mobile design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149), so that the page will be ready when the time comes to launch the page. 

### Action Items
- [x] ~~Make the header illustration size **only in mobile** match the size and margins in the Figma mobile design (see [Join Us page](https://www.hackforla.org/join) mobile design as a reference)~~
- [x] Make the mini project cards **in mobile** match the Figma mobile design (should be centered, not left-aligned)

### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)
[Program Areas Figma mockup](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)

<details>
<summary>Current mobile header illustration (too large and off-screen)</summary>
<br>
Screen Shot 2021-06-24 at 12 38 14 AM
</details>

<details>
<summary>Current mobile mini project cards alignment (shouldn't be left-aligned like this, but instead more centered)</summary>
<br>
Screen Shot 2021-06-24 at 12 40 15 AM
</details>

______________________________
Josh's edit: Thanks @Zak234 and @Aveline-art for commenting on this. Part of this issue is a duplicate of another issue. So I went in and crossed out those parts. 
All things crossed out in this issue have been moved to the below issue.
- #1596

### PR DESCRIPTION
**Pull request by Zak234**
Fixes #1825 

### What changes did you make and why did you make them ?

  -Created a media query that centers the mini project cards on mobile
  -Created a empty project card mini spacer class for centering purposes
  -Added 3 spacer class mini project cards to the html file for centering purposes.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Before:
Screen Shot 2021-07-06 at 9 59 35 AM

After:
Screen Shot 2021-07-06 at 10 00 11 AM

### CODE REVIEW

**Comment by jbubar** [comment]
zak's-prgram-areas

can we have @hackforla/website-design team do a visual review? I added a gif to this comment

**Review by jbubar — DISMISSED** [review]
I think it looks good, but I would like design team to do a visual review before merge

**Review by adam-abundis — COMMENTED** [review]
I am wondering why you didn't just apply the elements to justify center in mobile like so?
```
@media #{$bp-below-mobile} {
     justify-content: center;
 }
```

It seems okay and there would be no need for inline padding.

**Comment by Zak234** [comment]
This way doesn't work because if there is an uneven number of mini project cards, justify content centers the last mini project card in the middle of the content section rather than inline with the first mini project card. The inline padding is there to offset the 26px margin that the other project cards have rather than to center the project cards. I believe we discussed this during Sundays meeting.

**Comment by daniellex0** [comment]
Is it possible to do what was in the Toolkit page, where the guide cards are centered but when there is one in the bottom row it's left-aligned? I know this was an issue at first where it was automatically centered too, but they figured out how to make the bottom one left-aligned instead- https://www.hackforla.org/toolkit/

**Comment by Zak234** [comment]
I believe thats what I did?

**Comment by daniellex0** [comment]
@Zak234 just showed me the design live and it looks good in mobile! The situation in the gif where they are off centered in tablet is apparently  carried over from the original development of this page and doesn't relate to this issue or @Zak234 's changes, so I can make a separate issue to fix those. But for this issue, it looks like the requested changes were made well- thanks @Zak234 , good job!

**Review by adam-abundis — APPROVED** [review]
Excellent work @Zak234. Thank you for your patience and understanding during this review.

**Pull request merged**
