### PR TITLE
Add comming-soon guides to toolkit page

### PR DESCRIPTION
**Pull request by KianBadie**
@ExperimentsInHonesty I added the new guides under these files:
- 1password.html
- display-volunteer-experience.html
- figma.html
- responsible-images.html
- team-pages.html
The file names are the url for the pages (something like hackforla.org/guide-pages/1password), but since the pages are not linked anywhere, I figured these temp names could be used now and changed in the future.

In addition, I modified the logic to display the short descriptions of coming soon guides correctly and I removed the `.html` from the url for the 2FA guide. I also added the "short-description" field value to the "description" field value for this reason. Even though there are no links to these pages on the site, someone could enter the correct url to visit these pages since they are part of a collection that renders to pages (at least that's my current theory). In the event that someone does somehow stumble upon one of the urls to a page, I thought it would be nice to still have a description showing instead of a blank field. Unless that messes with how these pages show up on a google search related to these pages in an unintended way, I can remove them.

No typos that I noticed. I deleted some extra spaces. Some additional things I wanted to double check with @ExperimentsInHonesty are:
- Figma description seems to grammatically make sense, but threw me off at first on the first couple reads
- "Getting the Most Out of GitHub Issues", "Create a Kanban Project Board from Our Template", and "Using Kanban Project Boards for Team Effectiveness" all use the same description/short-description. Is that intended for now?
- All coming-soon cards do use the same image. Is that ok?
- Like I mentioned earlier, urls can be entered in manually to visit "coming-soon" pages.

screencapture-localhost-4000-toolkit-2020-10-14-18_26_53

### CODE REVIEW

**Comment by alexandrastubbs** [comment]
@KianBadie we have updated the file names: https://github.com/hackforla/website/issues/751#issuecomment-706934480

We also edited the Figma Short Description.

We also changed the categories for the following guides: 
1. Displaying your Civic Tech - Open Source - Volunteer Experience on LinkedIn
2. How to use Figma effectively on Open Source Volunteer Teams
3. Responsible use of images on HfLA websites

We had to add an extra category for professional development, so this needs to be reflected on the guide page with the other categories. 

We added descriptions for the guides that are already on the Toolkit page: https://github.com/hackforla/website/issues/751#issuecomment-709610467

**Comment by KianBadie** [comment]
@alexandrastubbs 
- I updated the "How to use Figma effectively on Open Source Volunteer Teams" description/short description as per [this](https://github.com/hackforla/website/issues/751#issuecomment-706934480) comment.
- I also changed the categories of "Displaying your Civic Tech - Open Source - Volunteer Experience on LinkedIn", "How to use Figma effectively on Open Source Volunteer Teams", and "Responsible use of images on HfLA websites" as per the same comment. Just a heads up, I do not think the categories for the guide cards have any functional value currently. I still changed them anyways.
- Added the category "Professional Development" to project banner.
- Updated project descriptions for the guides mentioned in [this](https://github.com/hackforla/website/issues/751#issuecomment-709610467) comment.

For the screenshots below, I only added a couple screenshots so I wouldn't flood the feed with images. And when it goes live, you will be able to test freely and we can make changes as needed. Does that sound alright? At times, it looks like the category banner font is small for the current screen size, but I did that so that everything can stay on one line for the biggest window of break points in width (AKA make the font smaller for widths "a through d" rather than change the font on widths "a through b", then "b through c", then "c through d"). My gif might have not captured it's appearances on all widths though so let me know if you want me to show more of what I am talking about.

Also, there is a point in the gif at the very end where the banner displays weird. But that applies for screens thinner than iPhone 5. I thought it's a small edge case to account for so I did not try to account for it. I attached what it looks like on iPhone 5 (what I assumed to be on near the edge on thinnest screen widths to consider).
# Screenshots
## Fullscreen
fullscreen
## Gif of banner
Peek 2020-10-15 17-23
## iPhone 5 Width
iphone5banner

**Comment by ExperimentsInHonesty** [comment]
I think the problems we have visually now, are minor and we can fix them more later.  I am in favor of accepting this if its technically solid.  Maybe @cnk or @drubgrubby could look

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty @cnk - I'm happy to take a look in the morning.

**Pull request merged**
