### PR TITLE
Integrate in kind component join us page #4565

### LINKED ISSUE #4565: Integrate the "In-Kind" component with the Join Us page
### Dependency
- [x] #4457

### Overview
We need to incorporate the new "In-Kind" component with the Join Us page, in order to provide a consistent appearance of donation-related elements across the site.  

### Details

1. The Join Us page currently includes a heading "How to help us continue to do Impactful Work" which appears after the "Donation Circles" and is depicted in Resources under the heading "Current Appearance".   The HTML is contained in `_includes/join-donate-card.html`.  
2. Replace the heading "How to help us continue to do Impactful Work" along with the unordered list beneath it with the heading "Provide In-Kind Software & Services" followed by the "In-Kind" component.  The desired appearance is shown in Resources under the heading "Final Appearance".  
3. Changes to the HTML and CSS layout are required, in order to center the "Donation Circles", the heading "Provide In-Kind Software & Services", and the "In-Kind" components within the entire width of the card.  That is, these elements must be removed from their current div/row placement in the grid, and should be placed in new div/rows that spans both columns of the grid so they are centered in the card.  

### Action Items
- [x] Open the files `_includes/join-donate-card.html` and `_sass\components\_join-us.scss`.  Move the "Donation Circles" (`div.donate-components-items`) into a new div (row), then modify the SCSS so that the "Donation circles" component is centered within the entire width of the card
- [x] Remove the heading ""How to help us continue to do Impactful Work" along with the `<ul>` beneath it.  
- [x] Below the "Donation Circles", add a new div (row), containing the heading "Provide In-Kind Software & Services" (centered) then reference the "In-Kind" component using the liquid tag 
```
{% include 'filename /donation/in-kind.html %}
```
- [x] The "Donation Circles" element, along with the heading "Provide In-Kind Software & Services" and the "In-Kind" component should all be centered within the entire width of the card, however the paragraph text within the In-Kind component should remain left-justified.  If necessary, html elements can be added to the "In-Kind" component and CSS classes specific to the "In-Kind" component can be added to `_sass/components/_donate-components.scss`.  If either the component or component styles are modified, ensure that the appearance of the Donate page is unchanged.  

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Creating/Integrating New Components" then release the dependency on #4455, and move that issue to `New Issue Approval` with `Ready for Prioritization` label

### Resources/Instructions
<details><summary>Current Appearance</summary>

image

</details> 

<details><summary>Final appearance - center the "Donation Circles" and "Provide In-Kind Software & Services" sections within the card sections</summary>

image

</details> 

- HfLA Join Us Page: [webpage](https://hackforla.org/join) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
- "In-Kind" component [HTML](https://github.com/hackforla/website/blob/gh-pages/_includes/donation/in-kind.html)
- The "In-Kind" component was developed in Issue #4457
- [Donate Card - Join Us Page version](https://github.com/hackforla/website/blob/gh-pages/_includes/join-donate-card.html)
- [HfLA Donate Page](https://hackforla.org/donate) 
- This issue is part of the Epic #4492

### PR DESCRIPTION
**Pull request by JpadillaCoding**
Fixes #4565

### What changes did you make?
  - Made the donations circles into their own row in the grid
      - Centered the div by making its own class and specifying the row with CSS grid
  - Deleted the section "How to help us continue to do Impactful Work" along with its content
  - Made the section "Provide In-Kind Software & Services" into its own row
     - added the component "In Kind"
     - Centered the div by making its own class and specifying the row with CSS grid
     - used the previous defined CSS class "title6 page-card--large-icon-header-secondary"for the header text
     - Centered the section header and left aligned the paragraph per instructions

### Why did you make the changes (we will use this info to test)?
  - The donation circles and "Provide In-Kind Software & Services" section had to be their own row to center the content
  - Had to make the donation circle it's own CSS class since the row had to be defined or else the donation card renders before the circles

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

250686638-19e5b90c-8fb1-4397-89ae-9a02454ea6f8

</details>

<details>
<summary>Proposed changes</summary>
  
250823040-4bee40ab-fae8-4fc2-b88d-51addff28a1f

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-07-23 at 12 48 38 AM

</details>

### CODE REVIEW

**Comment by adrianang** [comment]
- Availability: WFSS, 6 PM - 10 PM (PST) (Week of 7/24)
- ETA: I plan on finishing this issue by Wednesday, 7/26 at 10 PM.

**Review by adrianang — CHANGES_REQUESTED** [review]
Hi @JpadillaCoding! I started reviewing your PR and there were a couple of things I noticed while doing so:

- The Annual title for the donation circle lost 8px of bottom margin (was 20px, now 12px), which tightened the space between the donation circles and the in-kind component. Can you add the 8px (maybe even more, after looking at the Final Appearance screenshot in the linked issue again) back? I think adding a margin rule for that to `.join-us-donation-circles` would be easiest, and this would create visual space between the circles and in-kind component.
- The `div` ending and closing tags on lines 19 and 21 aren't needed. I noticed that you had intentionally made this change in commit `8a4f036`, but I think it would be cleaner to add a rule targeting just the 'Provide In-Kind Software & Services' header to center it, rather than putting the header as the sole element in a `div` (since the `div` isn't grouping things) and depending on the `align-items: center` rule on the `.join-us-in-kind` class to center it on the tablet view.
- On that note, the `align-items: center` rule on the `.join-us-in-kind` class is centering the last paragraph of the component on the tablet view. If this is deleted, that paragraph ("Reach out [...]") is left-aligned again (as well as the header in the previous bullet, which should be selected to be centered on tablet view).
- Can you add line breaks between the `.join-us-donation-circles` and `.join-us-in-kind` class rules? I noticed that the other classes have line breaks before and after their sections, so it would be nice if additional lines were added to keep the code style on that SCSS file consistent.

Other than those points, everything's looking good so far — branching is set up correctly, corresponding linked issue is there, and the requested action items were changed! 😄

**Comment by JpadillaCoding** [comment]
Hey, @adrianang. Nice catch on the changes I made!

I addressed the spacing issue between the donation circles and the in-kind component by adding `margin-bottom: 26px` to `.join-us-donation-circles`. I chose 26px since adding 8px just didn't look right (Your prediction was correct) and keeping the consistency with the spacing between the circles and the "Running hack for la cost money" section looks cleaner. 
On that note of the spacing issue you caught, I found that I had a similar issue on mobile view. `margin-bottom: 26px` was added on mobile view to keep consistency. 

You are correct to point out that the In-kind title shouldn't have its own div. This was corrected and centered with its own class.

The `align-item` property was removed from .`join-us-in-kind` to left-align the whole component. Spacing breaks were also added between each CSS class for consistency.

You have a good eye for detail and I learned from you. Thanks!

**Review by adrianang — APPROVED** [review]
@JpadillaCoding I reviewed the changes and they look good to me on my local machine! Good call on matching the margin above the donation circles — it looks really nice! I also like how you reused the existing style classes and Grid/Flex structures. Per my previous review, the branching is still set up correctly, the corresponding issue is still linked, and the requested changes of refactoring the donation circles component and integrating the in-kind component have been made.

Thank you for your thorough documentation throughout this issue and for taking up this issue! 🙌🏼

**Review by roslynwythe — APPROVED** [review]
Thank you @JpadillaCoding for a great job on this issue.  The branches are setup correctly, the PR is well-formed and descriptive, your code changes are clean and the result looks great in the browser at all screen widths.

**Pull request merged**
