### PR TITLE
Removed backlash / in img tag (<img.../>) in CONTRIBUTING.md

### LINKED ISSUE #7098: img tag refactor in CONTRIBUTING.md Sec 2.7.d
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open the file `CONTRIBUTING.md`
- [x] In Section 2.7.d change
```
<img src="https://raw.githubusercontent.com/wiki/hackforla/website/images/how-to-review-pull-requests/step3-sync-demo.gif" />

```
to
```
<img src="https://raw.githubusercontent.com/wiki/hackforla/website/images/how-to-review-pull-requests/step3-sync-demo.gif">

```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  **Do not leave any blank spaces before the closing bracket.** 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL (also store the test URL for use in a later step)
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```

### Merge Team
- [x] After closing this issue, check off the dependency in #6453.  If all dependecies have been completed, close #6453 and check off its dependency in #4362.  If all dependencies have been completed in #4362, close it.  

### Resources/Instructions
1. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. This issue is part of #6453

### PR DESCRIPTION
**Pull request by santiseccovidal**
Fixes #7098 

### What changes did you make?
  - In section 2.7.d of CONTRIBUTING.md removed the backlash / in the img tag () to an img tag without an ending backslash ().

### Why did you make the changes (we will use this info to test)?
  - So that the codebase is consistent with how we use img HTML tags.

For Reviewers: Do not test changes locally, rather test changes at https://github.com/santisecco/website/blob/img-tag-refactor-contributing-7098/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website
- No visual changes were made to the website.

### CODE REVIEW

**Comment by terrencejihoonjung** [comment]
ETA: Thu Aug 15th, 11:59pm PST
Availability: Mon-Fri (all day)

**Comment by handshek** [comment]
Availability: 7 am to 11 am on weekdays
ETA: before 14-AUG-24 e.o.d

**Review by handshek — APPROVED** [review]
Hey @santisecco, Nicely done!

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a clear and concise description of what was done and why
- No changes were made to the website

Thanks for woking on this issue!

**Review by pluto-bell — APPROVED** [review]
Great, everything looks solid on this PR and the file change.

**Review by terrencejihoonjung — APPROVED** [review]
Hi @santisecco,

The changes made look good! 
- branching to and from is correct
- changes made and why they were made are clearly stated
- `img` tag has ending slash removed

Thanks for contributing!

**Pull request merged**
