### PR TITLE
Updated how 'overview' link opens for Home Unite US

### LINKED ISSUE #3220: Update how 'Overview' link opens for Home Unite US
### Overview
As a user, clicking on the 'Overview' link for the Home Unite US project should open a new tab to the pdf file directly. 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Home Unite us pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Home-Unite-Us-One-Sheet.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Home Unite Us's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/home-unite-us) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
[Project Page](https://www.hackforla.org/projects/home-unite-us
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)

### PR DESCRIPTION
**Pull request by alan-zambrano**
Fixes #3220

### What changes did you make and why did you make them ?
This page previously opened a link to the github page with "Home-Unite-Us-One-Sheet.pdf" and now instead opens the file directly in the browser.

When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>

after

</details>

### CODE REVIEW

**Comment by Wny-Duong** [comment]
Availability: 1 hour
Review ETA: Tuesday, June 7th

**Review by Wny-Duong — CHANGES_REQUESTED** [review]
The new url opens a tab to the file correctly on the specific project page for Home Unite Us itself, but the card on the home page seems to redirect to the old link with the Github repo page containing the file instead. This is honestly a bit weird to me because I can see that the old link has been replaced, so I don't have any idea what's causing this.

image

**Comment by alan-zambrano** [comment]
@Wny-Duong You're right, I've been troubleshooting this for a bit and I'm not sure why this is happening either. It seems to be caused by some other file, which may be outside of the scope of this issue.

**Review by Wny-Duong — APPROVED** [review]
Yeah, it looks like the wrongful redirect's been a thing in some of the other pull requests made for overview link editing issues as well. I'll just approve for now because your changes were correct based on the code itself and bring it up during the next website meeting just to make sure it's all good.

**Comment by BeckettOBrien** [comment]
Review ETA: 6/22
Availability: 1 Hour

**Review by BeckettOBrien — APPROVED** [review]
Aside from the issue with the link on the project card, the new link works perfectly and the code changes implement exactly what the issue outlines. Great job!

**Pull request merged**
