### PR TITLE
Added Anita Morales to Expunge Assist Project on the UI

### LINKED ISSUE #5761: Update Project Profile: Expunge Assist (Add Anita Morales)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following as a new entry:
```
  - name: Anita Morales
    github-handle: anitadesigns
    role: UX Design, Team Co-lead
    links:
      slack: https://hackforla.slack.com/team/U03F43PFR3K
      github: https://github.com/anitadesigns
    picture: https://avatars.githubusercontent.com/anitadesigns
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column  and uncheck the **Dependency label**.
    - <details>
         <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
         
    </details>

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by irais-valenzuela**
Fixes #5761 

### What changes did you make?
  - I added Anita Morales's profile information such as their name, GitHub handle, role, social links, and picture to the project team section of Expunge Assist.

### Why did you make the changes (we will use this info to test)?
  - We need to keep project information up to date so that visitors to the website can find accurate information.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before Adding Anita Morales Expunge Assist Team UI

</details>

<details>
<summary>Visuals after changes are applied</summary>

After Adding Anita Morales Expunge Assist UI

</details>

### CODE REVIEW

**Comment by Anahisv23** [comment]
Review ETA: 1 - 2PM 11/3/23
Availability: 11AM - 5PM 11/3/23

**Review by Anahisv23 — DISMISSED** [review]
Nice job Irais! Keep up the good work :)

**Review by Anahisv23 — APPROVED** [review]
Good work Irais!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
HI @irais-valenzuela - Great job on this PR!
- Your from/to branches are correct
- You are linked to the original issue
- You are providing a short description of what you did and why
- You have included 'before' and 'after' screenshots
- Your code edits change only what needs to be changed

Some notes:
- Some of the automations that normally run were not triggered when this PR was created.  This may happen if you don't include the "Fixes # xxxx" line before you first open the PR. In any case, since the automations weren't triggered, please copy the issue labels from #5761 to this PR. 

Once you have added the labels, please re-request a review from me.

Thanks for working on this issue!

**Comment by irais-valenzuela** [comment]
> HI @irais-valenzuela - Great job on this PR!
> 
> * Your from/to branches are correct
> * You are linked to the original issue
> * You are providing a short description of what you did and why
> * You have included 'before' and 'after' screenshots
> * Your code edits change only what needs to be changed
> 
> Some notes:
> 
> * Some of the automations that normally run were not triggered when this PR was created.  This may happen if you don't include the "Fixes # xxxx" line before you first open the PR. In any case, since the automations weren't triggered, please copy the issue labels from [Update Project Profile: Expunge Assist (Add Anita Morales) #5761](https://github.com/hackforla/website/issues/5761) to this PR.
> 
> Once you have added the labels, please re-request a review from me.
> 
> Thanks for working on this issue!

Thanks for the comment! I went ahead and added the labels. Just so I know for next time, do I also need to add issue labels to my next PR or only the Fixes # number?

**Review by t-will-gillis — APPROVED** [review]
@irais-valenzuela Thanks for adding the labels!

Yes, if "Fixes #xxxx" is on the PR, the automation will pull the labels so you won't need to.

**Pull request merged**
