### PR TITLE
Removed the ending slash in the img HTML tag

### LINKED ISSUE #5101: img tag refactor on donate-gif-text include
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/donation/donate-gif-text.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img
  class="donation-gif"
  src="/assets/images/about/hfla-donate.gif"
  alt=""
  />
```
to
```
<img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt=""/>
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/donation/donate-gif-text.html
2. Webpage(s): https://www.hackforla.org/donate, https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by DorianDeptuch**
Fixes #5101 

### What changes did you make?
  - I removed the ending slash in the img HTML tag

### Why did you make the changes (we will use this info to test)?
  - I made the changes so that the codebase is consistent with how we use img HTML tags.

### Screenshots of Proposed Changes Of The Website

- Visuals after changes are applied: /donate page on desktop view

Screen Shot 2023-07-31 at 9 14 17 PM

- Visuals after changes are applied: /join page in mobile view

Screen Shot 2023-07-31 at 9 15 26 PM

### CODE REVIEW

**Comment by ldietz08** [comment]
Availability: Mon-Fri 4pm-7pm
ETA: 08/04 EOD

**Comment by steven-positive-tran** [comment]
Availability: Aug 3 6-12
ETA: 08/03 EOD

**Review by steven-positive-tran — DISMISSED** [review]
Changes seems in line with the issue that needs to be addressed, branches look good and I confirm that the gif in both the donate and join pages are the same. 

Looks good and thanks for doing this.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @DorianDeptuch Great job on your issue! The branches are correct, you are linked back to the original issue, you gave appropriate descriptions of the whats and the whys, and you included screenshots. ( You get bonus points for removing the ending slash and not copying the code shown in the issue!)

One small request- the current image tag spans five lines. Could you please edit this to:
```
<img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
```

Besides this change, everything should be good to go. Thanks!

**Comment by DorianDeptuch** [comment]
Hi, @t-will-gillis,

I went ahead and fixed the changes but I noticed that a modified _projects/access-the-data.md file was also somehow added to the commit. This was a file that I reviewed for someone else and the code is already pushed into the gh-pages branch. I git pulled from the upstream branch before I committed so I'm unsure of how this file snuck it's way into my commit. The small terminal window in vscode sure didn't help me detect it either.

How do you suggest I proceed? Does deleting the file in the 'Files changed' tab delete the file from the repository? Would reverting to a previous commit be a better option?

Thanks,
Dorian

**Comment by t-will-gillis** [comment]
Hi @DorianDeptuch - There are a couple of ways this can be fixed. These changes to "access-the-data.md" were merged earlier today so you would not be changing anything but you still want it clean. The easiest fix would be to delete the file here- that should be safe and not affect the website. In VSCode you should also be able to reset the "access-the-data.md" file if you open the same branch that you pushed the PR and and this will update the branch. 

I'll check it again before merging it. If you have other questions let me know.

**Comment by DorianDeptuch** [comment]
@t-will-gillis,

I'm hoping the file deletion was done correctly. Let me know if there is anything to fix.

**Comment by t-will-gillis** [comment]
Hi @DorianDeptuch please shoot me a message via Slack. I gave you poor advice regarding the file conflict.

**Comment by t-will-gillis** [comment]
Closing this PR, it has been replaced by #5157

**Pull request closed without merging**
