### PR TITLE
Maintenance and adjustment to "Schedule Monthly" workflow

### LINKED ISSUE #7614: Maintenance and adjustments to "Schedule Monthly" workflow
### Overview
This issue is primarily to address two behaviors in the "Schedule Monthly" workflow: 
- 1. the workflow is keeping inactive devs on the Roster longer than desirable. This is partially due to the way that the workflow handles the July and December breaks. We need to adjust the timeline for the `oneMonth` variable in August and January. 
- 2. The workflow needs to close the "Skills Issue" in addition to the "Pre-work checklist" of "Inactive" members.
- 3. For member comments, the workflow currently considers recent updates (like minimizing the issue) to be activity- this needs to change to consider the time of the initial comment only

### Action Items
- [x] In [get-contributors-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/get-contributors-data.js), replace:  
  ```
  // The Feb. 1st and Sept. 1st runs account for skipped months: 'oneMonth' & 'twoMonths' = 2 & 3 months respectively
  let today = new Date();
  let oneMonth = (today.getMonth() === 1 || today.getMonth() === 8) ? 2 : 1;
  let twoMonths = (today.getMonth() === 1 || today.getMonth() === 8) ? 3 : 2;

  let oneMonthAgo = new Date();                              // oneMonthAgo instantiated with date of "today"
  oneMonthAgo.setMonth(oneMonthAgo.getMonth() - oneMonth);   // then set oneMonthAgo from "today"
  ```  
  with:  
  ```  
  // The Feb. 1st and Sept. 1st runs account for skipped months: 'oneMonth' & 'twoMonths' = 1 & 3 months respectively
  let today = new Date();
  let twoMonths = (today.getMonth() === 1 || today.getMonth() === 8) ? 3 : 2;

  let oneMonthAgo = new Date();                                           // oneMonthAgo instantiated with date of "today"
  oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);   // then set oneMonthAgo from "today"
  ```  
- [x] In the same file in the `fetchContributors()` function, replace:
  ```  
          // If timeline is more than two months ago, add to open issues with inactive 
          // comments with flag = true if issue is "Pre-work Checklist", false otherwise
          else if(date === dates[1]){
            if(contributorInfo.title.includes("Pre-work Checklist")){
              inactiveWithOpenIssue[assignee] = [issueNum, true];
  ```  
  with:  
  ```  
          // If timeline is more than two months ago, add to open issues with inactive. Then check if 
          // issue title includes "Pre-work Checklist" or "Skills Issue" and set flag = true, else set false
          else if (date === dates[1]) {
            const regex = /Pre-work Checklist|Skills Issue/i;
            if (regex.test(contributorInfo.title)) {
              inactiveWithOpenIssue[assignee] = [issueNum, true];
  ```  
- [x] In the same file, replace:
  ```  
          // Check for username in `user.login`, but skip `user.login` covered by 3rd API 
        else if(contributorInfo.user  && api != 'GET /repos/{owner}/{repo}/issues'){
  ```  
  with:  
  ```  
          // Check for username in `user.login`, check only comment's `created_at` time, and  skip `user.login` covered by 3rd API 
        else if(contributorInfo.user && contributorInfo.created_at > date && api != 'GET /repos/{owner}/{repo}/issues'){
  ```  

- [x] In [trim-inactive-members.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/trim-inactive-members.js), the function `removeInactiveMembers()` is recalculating `currentTeamMembers`. Refactor to pass this as a parameter to clean up function.
- [x] Search through related files for references to "Pre-work checklist" and change to "Skills Issue" since this will be the term from now on.
- [x] Although this issue involves a GitHub Action, testing is not required.

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #7614 

### What changes did you make?
  
  - main edit 1: made edits to `get-contributors-data.js` so that in the month after HfLA's break, the `oneMonthAgo` variable remains at one month and is not adjusted for the time on break. Note the `twoMonthsAgo` does still account for the break month
  - main edit 2: made edits to several files in workflow to shift focus to the new title of the "Skills Issue", but continue with the legacy "Pre-work checklist" also
  - main edit 3: UPDATED 10/28/24: made edits to workflow to only count the `created_at` date of the member's comment, and exclude `updated_at` date which is typically when a comment is hidden and is typically not performed by the member
  - refactored `trim-inactive-members.js` because the variable `currentTeamMembers` is currently defined/ calculated in two places, unnecessarily. Also, streamlined the `console.log()` for creating separation lines 
### Why did you make the changes (we will use this info to test)?
  
  - for main edit 1, members that should be removed were retained for too long
  - for main edit 2, needed this change so that the workflow accounts for the new template "Skills Issue"
  - for main edit 3, UPDATED 10/28/24 made this change so that comments are considered based on `created_at` date rather than `updated_at` date
  - for last edits, done to remove unneeded code/ clean up

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

- No visual changes to website

## Notes for PR reviewers
- This PR does not require you to test the workflow, but if you would like to do so see the "Test Procedure" in the [Wiki for "Schedule Monthly"](https://github.com/hackforla/website/issues/6399#issuecomment-2118484360)  

UPDATED 10/28/24:
- [Workflow log](https://github.com/t-will-gillis/website/actions/runs/11562966342) showing successful test run
- [Issue created by workflow](https://github.com/t-will-gillis/website/issues/1086)

### CODE REVIEW

**Review by codyyjxn — DISMISSED** [review]
Hey @t-will-gillis this looks great!
- The branch name is correctly 
- The issue is linked as well
- The console.logs are changed to displayed correctly 

This was done very well , great job!

**Comment by santiseccovidal** [comment]
Note edit 10-28-24 - I realized the complexity is greater than I thought at first only looking at the "medium" label.
Review ETA: 2 PM 11/1/24
Availability: 12-3 PM Monday-Friday

**Comment by t-will-gillis** [comment]
Hi @codyyjxn FYI There is a last minute addition (noted by UPDATED 10/28/24 in the description above)- this happens at lines 108-109 in the `get-contributors-data.js`. It is to cover a specific edge case that I found when checking something for Bonnie: when a user's comment gets minimized, the bot thinks that the comment is updated and the workflow counts this as member activity even though it is not. the edits ensure that only the initial user creation is counted.

**Review by santiseccovidal — APPROVED** [review]
Hi Will thanks for working on this. I'm looking at the updates. All the changes look great. I noted down some stuff regarding how the workflow works. 
The changes are great so I'll go ahead and approve them but still I had some questions regarding how the code works not the changes. The annotations made it very clear by the way but I want to be sure I understood it.
Feel free to correct any of the comments bellow.

Noted the change in variable `twoMonthsAgo` for the months of September and February. Following the fact December and July are breaks. The refactoring of console.log() look is better.

Then I also saw the fact we needed to update the code for the new skills issue. That's the reason for the update from "Pre-work" to "Skills issue". Still the code works for "Pre-work checklist".

Looking into the way the code functions. We first get the data of the contributor's activity with `get-contributors-data.js` and then we use that data to remove or notify inactive members using `trim-inactive-member.js`

The APIs return different values. We perform different checks to add the contributor to `allContributorsSince`.

I still have to look at `trim-inactive-member.js` in more detail. So the following might be answered there:
I have a question regarding the checks in ´`get-contributors-data.js`. The "else/if" statements in the `fetchContributors ` function. 
If a user appears as `contributorInfo.author` or `contributorInfo.user` then can their work be outdated? If so how is that checked?
I guess for both of them that is checked since the API call is since at maximum 2 months ago. For  `contributorInfo.user` we check for` contributorInfo.created_at > date` so we are ok there.

**Comment by t-will-gillis** [comment]
Hey @santisecco thanks for the review and comments. For your question:

> I still have to look at `trim-inactive-member.js` in more detail. So the following might be answered there:
> I have a question regarding the checks in `get-contributors-data.js.` The "else/if" statements in the `fetchContributors` function.
> If a user appears as `contributorInfo.author` or `contributorInfo.user` then can their work be outdated? If so how is that checked?
> I guess for both of them that is checked since the API call is since at maximum 2 months ago. For `contributorInfo.user` we check for `contributorInfo.created_at` > date so we are ok there.

The `fetchContributors()` function is a little bit difficult so to try to simplify: The goal is to see which members have contributed within either the last one month and or the last two months and compare this to the team list. But we can't really see what each individual is doing so instead we accumulate all commit, comment, and assignee activity at two months and at one month for the HfLA organization (this is the `since: date` part of the API request). `fetchContributors()` is extracting the user names from all of this data across the organization. `trimContributors()` then is taking the list of current team members and for each person checking if their name is on the list of contributing anything no more than two months ago. If the team member's name was not seen, the member is removed. After this first run through, we generate an updated member list and repeat to see whether the remaining team members have had activity in the last month. If not, these members are notified b/c their activity is between one and two months old. 

To your question then, if an author or a user (or an assignee) name appears on the list, it is because they had activity since the date (one month or two months ago).

I don't know if that helped or not- hope it did. Let me know if you have questions or want to talk about anything else

**Comment by t-will-gillis** [comment]
Hey @codyyjxn I am merging this since you Approved this previously

**Comment by santiseccovidal** [comment]
Thanks @t-will-gillis I'll look at it in more detail and ask you for anything else 👍

**Pull request merged**
