### PR TITLE
added the correct link to Git gui wiki

### LINKED ISSUE #2673: Correct Link to Git Gui Wiki from Contributing.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
The link to the Git Gui Wiki from How to Contribute to Hack for LA needs correction since the current link is broken.

### Action Items
- [ ] Change the **Git Gui Wiki** link (under [2.7.c Working on an issue (3): Prepare your changes to push to your repository](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27c-working-on-an-issue3-prepare-your-changes-to-push-to-your-repository))
From
`https://github.com/hackforla/website/wiki/Using-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code`
To
`https://github.com/hackforla/website/wiki/How-to-Use-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code`

### Resources/Instructions
- The correct link is:
[https://github.com/hackforla/website/wiki/How-to-Use-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code](https://github.com/hackforla/website/wiki/How-to-Use-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code)
- File where changes need to be made: [Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) 
- File location in our codebase: `website/CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by Satenik-Ba**
Fixes #2673

### What changes did you make and why did you make them ?
 
  - added a correct link to Git Gui Wiki from How to Contribute to Hack for LA

<details>
From
https://github.com/hackforla/website/wiki/Using-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code
changed to
https://github.com/hackforla/website/wiki/How-to-Use-Git-GUI-(Graphical-user-Interface)-in-Visual-Studios-Code
</details>

<details>
<summary>no visual changes</summary>
  
</details>

### CODE REVIEW

**Comment by Suman2795** [comment]
ETA:22/11/2022
Availability: 1 hour

**Comment by Adastros** [comment]
Review ETA: 12 AM 22NOV22
Availability: 11:30 PM - 12 AM 21NOV22

**Review by Adastros — APPROVED** [review]
Good job @Satenik-Ba ! You fixed the broken git gui wiki link! 

A couple things of things I want to note:
- I noticed that the statement "no visual changes" is wrapped in a detail tag. It can be captured in a bullet point. It might be confusing to click the arrow and see nothing under it.  
- I also noticed that the commit message is a little unclear about what was changed. It would good practice to give a brief explanation of what was done. I think something similar to the title of this pull request would be good.

**Review by Suman2795 — APPROVED** [review]
You modified the file  to point it to the correct link and now it works well. Good work @Satenik-Ba .
 And I agree with @Adastros, a  commit message with brief description would make it more clear for the future pull requests.

**Review by blulady — APPROVED** [review]
This issue comes from the correct branch and goes to the correct branch. Has a correct linked issue that is addressed by the pull request (pr). The code looks clean, now links to the correct page that is up and running. Great Job!!

**Pull request merged**
