### PR TITLE
Change alt text for CFA logo image in citizen engagement html file Issue#3100

### LINKED ISSUE #3100: Change alt text for CFA logo image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the CFA logo image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 49](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L49) for the alt text:

from
```
<img class="org-img" src="/assets/images/sponsors/logo-cfa.svg" alt="code for america logo"/>
```
to
```
<img class="org-img" src="/assets/images/sponsors/logo-cfa.svg" alt="Code for America"/>
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L49

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by Unity7**
Fixes #3100

### What changes did you make and why did you make them ?

  - in pages/citizen-engagement.html, line 49's alt text img was change from 'code for america logo' to 'Code for America'
  -Alt text was updated in order to be more accurate and web accessible
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
no changes to visuals

### CODE REVIEW

**Review by neevliberman — APPROVED** [review]
This all looks good! You did everything the issue asked you to :)
In the future, you do not have to use images of changes in code on the website for your PR (i.e. if you need to inspect element to see the changes, it's probably not necessary). Really minute detail though! Great Job.

**Comment by giroz** [comment]
ETA:  9/18/22
Availability: 3 hours

**Review by giroz — APPROVED** [review]
Great job! line 49 updated with correct text.

**Comment by arpitapandya** [comment]
Availability: 6hrs
ETA: EOD 2022-09-18

**Review by arpitapandya — CHANGES_REQUESTED** [review]
- @Unity7 Great job on making changes!! The changes are absolutely correct and doesn't break anything. 
- Please, do not attach any screenshot of code as per the upper line above screenshots you attached suggests.
- If the issue doesn't have any visible changes on website then it is perfectly fine not to attach screenshot.  Just like in this issue, after changes there are no visible changes to the website.
- Please, Use docker setup to check website running [guide on how to?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#15-dev-setup-5-set-up-docker), using Live-server through IDE isn't advisable for this project.
- Once you remove the screenshots, I shall be able to merge this PR.

**Comment by Unity7** [comment]
@arpitapandya I have removed the screenshots

**Review by arpitapandya — APPROVED** [review]

**Pull request merged**
