### PR TITLE
added github-handle for Minji Kim

### LINKED ISSUE #7251: Add github-handle for Minji Kim in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [ ] Open the file `_projects/tech-work-experience.md` in the IDE
- [ ] Replace:
```
- name: Minji Kim
```
with
```
- name: Minji Kim
  github-handle:
```
- [ ] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by kgold2018**
Fixes #7251

### What changes did you make?
  - Added 'github-handle' under Minji Kim name list section

### Why did you make the changes (we will use this info to test)?
  - For future replacement of git-hub and picture variables to reduce redundancy.

### Screenshots of Proposed Changes Of The Website (if any, please do not include screenshots of code changes)
- No visual changes

### CODE REVIEW

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @kgold2018 Great job- 
- your 'from' and 'to' branches look good
- your descriptions for what you did and why are corect and concise
- you added the note for no visual changes
- your code edit is clean and only changes what needs to be changed.

On the linked issue, i.e. `Fixes #7251`, I think that you might have added a colon after "Fixes" and this might be tripping up the automation. Would you please remove the colon? Thanks!

FYI I removed the other reviewer you requested b/c they are no longer active. FYI- it is best to avoid asking for specific reviewers, especially when GitHub suggests someone b/c often they are not available. The only exception is when you are asking a specific person for a re-review or if you contacted the person previously and know they are available.

**Comment by kgold2018** [comment]
@t-will-gillis  i have fixed the PR: column(:) was removed and looks like Fixes #7251.Thank you for your input.

**Review by t-will-gillis — APPROVED** [review]
Thanks for making the edit!

**Review by freaky4wrld — APPROVED** [review]
@kgold2018 thanks for making the changes
- branches looks good
- changes made are apt and as specified
- the issue linked is correct

PR approved

**Pull request merged**
