### PR TITLE
Resolve codeql 6051

### LINKED ISSUE #6051: Resolve CodeQL alert 17 "Potentially unsafe external link"
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to resolve the alert "Potentially unsafe external link" which appears in the CodeQL [alert 17](https://github.com/hackforla/website/security/code-scanning/17) by adding the attribute `rel="noopener noreferrer"`

### Action Items
- [x] The following item is required for GitHub to establish tracking between this issue and the alert.  No action is required.  You may simply check the checkbox.  If you do follow the link to learn more about CodeQL alerts, DO NOT DISMISS THE ALERT.  
- [x] https://github.com/hackforla/website/security/code-scanning/17
- [x] Open the file `pages/communities-of-practice.html` in your IDE
- [x] Replace
```
<a href='{{ leader.links.slack }}' target='_blank' title='Slack Direct Message'>
```
with
```
<a href='{{ leader.links.slack }}' target='_blank' title='Slack Direct Message' rel="noopener noreferrer">
```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/communities-of-practice
3. This issue is part of #5129

### PR DESCRIPTION
**Pull request by junadkat32**
Fixes #6051 

### What changes did you make?
 Replaced ```<a href='{{ leader.links.slack }}' target='_blank' title='Slack Direct Message'> ```
with ```a href='{{ leader.links.slack }}' target='_blank' title='Slack Direct Message' rel="noopener noreferrer"```

### Why did you make the changes (we will use this info to test)?
  To resolve codeql alert 6051

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes

### CODE REVIEW

**Comment by Chrisklangley** [comment]
availability: M-F 6:30pm-9pm
ETA: 2/11/24 EOD

**Comment by jphamtv** [comment]
Hey @junadkat32 It seems that the labels didn't automatically transfer when the issue was linked to this pull request, which is unusual since the issue appears to be correctly linked. Could you please manually transfer the labels over? Thank you for your attention to this detail.

**Comment by junadkat32** [comment]
@jphamtv I have added the labels.

**Comment by freaky4wrld** [comment]
@junadkat32 in your description you can put the code instances into code blocks like

````
```html
<a href='{{ leader.links.slack }}' target='_blank' title='Slack Direct Message'>

```html

````

Also in the `Screenshots` you can simply say `No visual changes`, adding description in your PR increases your chances of getting the code merged quickly and help the reviewers as well

Ping me when you are done with the changes

**Comment by freaky4wrld** [comment]
Availability: Evenings
ETA: EoD 2/10/24

**Comment by junadkat32** [comment]
@freaky4wrld I have made the changes.

**Review by freaky4wrld — APPROVED** [review]
@junadkat32 thanks for taking up the issue, the branches and linked issue are correct, changes done as specified in the issue... 

PR approved

**Review by jphamtv — APPROVED** [review]
Great work on this issue, @junadkat32, and thanks for making the requested changes.

**Pull request merged**
