### PR TITLE
SDG 13: Renamed and replaced image with correct color one

### LINKED ISSUE #4257: SDG 13: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `climate-action.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-13.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg13.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the image you just added by changing
```
<img src="/assets/images/sdg/climate-action.svg" alt="13 Climate Action" />
```
to
```
<img src="/assets/images/sdg/sdg13.svg" alt="13 Climate Action" />
```
- [x] Using Docker, check the About page's Sustainability section (https://www.hackforla.org/about/#sustainability) to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- This issue is tracked in #4153
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by nicolettedmabeza**
Fixes #4257 

### What changes did you make and why did you make them ?

  - In the `assets/images/sdg` directory, deleted `climate-action.svg`
  - Downloaded `E-WEB-Goal-13.svg` from website drive and added it to `assets/images/sdg `directory.
  - Renamed svg to `sdg13.svg`
  -  In `_includes/about-page/about-card-sustainability.html`, updated the path to the image 
 - Replaced image so that the SDG 13 svg is the correct color and follows the UN SDG guidelines.
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-04-14 at 11 44 20 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-04-14 at 11 44 27 AM

</details>

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: EOD 5/15
Availability: After 1pm PDT 5/15

**Comment by drakenguyen4000** [comment]
ETA: 4/14/23
Availability: M-F 3:30pm-8pm

**Review by drakenguyen4000 — APPROVED** [review]
Nicely done @nicolettedmabeza.  Your pull request is detailed, explains what changes and why, your PR is linked with the issue, and the PR is moved to Project Board.  All changes met the issue criteria and the image displays correctly on different resolutions on Edge and Chrome.

**Review by kwangric — APPROVED** [review]
Branches were set up correctly and the requested changes were all made. Everything looks good in Docker, great work!

**Pull request merged**
