### PR TITLE
Removed slash at ending tag for step-img-icon-board

### LINKED ISSUE #4382: img Tag Refactor: Getting Started page - `step-img-icon-board board.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-board" src="assets/images/getting-started/board.png" alt="" />
```
to
```
<img class="step-img-icon-board" src="assets/images/getting-started/board.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by agosmou**
Fixes #4382 

### What changes did you make and why did you make them ?

  - Removed a slash at ending tag for step-img-icon-board
  - This was done because  tags don't need a closing slash
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes.

### CODE REVIEW

**Review by cmedina-dev — CHANGES_REQUESTED** [review]
Hi Alejandro! Looks like you got rid of the trailing slash, which is great! I just have a few changes I'd like to suggest:

- Your issue that you're working on needs to be linked by replacing the "#replace_this_text_with_the_issue_number" with the actual number (preceded by a hashtag) of the issue. It looks like you already included the issue in your next section, but you'll want to link the number of the issue up top.
- For your reasoning, you'll want to explain why the change was made. A better way to think of this might be "why was the issue opened in the first place, and what does the code do to resolve it?"
- In your change, it looks like you have an extra space at the end. `alt="" >` should be `alt="">`.

Other than that, everything else looks good to me! You submitted your request from the feature branch, and your PR otherwise looks to be formatted correctly. Great work again!

**Comment by agosmou** [comment]
@cjmedina95 
Items have been addressed! Please review again

**Review by cmedina-dev — APPROVED** [review]
Thanks for adding the requested changes! Just a minor typo in the PR (think you meant to put that \ tags **don't** need slashes), but other than that everything else looks good to me. Great work!

**Comment by agosmou** [comment]
@cjmedina95 fixed the typo! Thanks for reviewing and being thorough. Greatly appreciated .

**Review by jefflueck — APPROVED** [review]
Nice work! Thank you for taking up this issue. Looks good!

**Pull request merged**
