### PR TITLE
Replace label in design system audit page

### LINKED ISSUE #7603: Replace label in design-system-audit--text-elements.md
### Overview
We need to change the ready for label on the design-system-audit--text-elements.md issue template so that the merge team can handle more of the issue reviews.

### Action Items
- [x] Open the files  /.github/ISSUE_TEMPLATE/design-system-audit--text-elements.md
- [x] In the following text, add `ready for merge team` label 
```
 labels: 'Complexity: Missing, Feature Missing, good first issue, role: design, size: 
   0.25pt' 
```
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [x] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [x] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  image

  </details> 
- [x] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  image

  </details> 
- [x] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  image

  </details> 

- [x] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [x] Copy the URL of the issue creation page and save for later use.  
- [x] Verify the appearance of the issue template.
- [x] Complete the Pull Request process by visiting the URL saved from the push command.
- [x] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
```
 ### For Reviewers
- Use this URL to check the updated issue template: [INSERT URL of issue creation page]
```
- [x] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template in your fork of the repository
- [x] Submit your pull request with your changes for review
- [x] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/design-system-audit--text-elements.md?plain=1

- This issue is part of Issue Making Issue #7602

### PR DESCRIPTION
**Pull request by mchait18**
Fixes #7603

### What changes did you make?
  
  - I added the label 'ready for merge team' to the  design-system-audit--text-elements.md file
 
### Why did you make the changes (we will use this info to test)?
  
  - This addition is so that the merge team can handle more of the issue reviews.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### For Reviewers
- Use this URL to check the updated issue template: https://github.com/mchait18/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+Feature+Missing%2C+good+first+issue%2C+role%3A+design%2C+size%3A+0.25pt%2C+ready+for+merge+team&projects=&template=design-system-audit--text-elements.md&title=Design+System+Audit%3A+Text+Elements%3A+%5Breplace+with+page+name%5D+page

- No visual changes to the website

### CODE REVIEW

**Review by codyyjxn — CHANGES_REQUESTED** [review]
@mchait18 Thank you for taking on this issue. 
### Things that went well
- The title and description are great 
- The branch is correct 
- The issue is linked correctly 


### Few things that need to be fixed 
- The url is broken sends me to a 404 page. 
- The screenshots are not showing properly. 

After those are done I am more than happy to take another review on this for approval.

**Comment by mchait18** [comment]
I'm honestly pretty confused about this issue. I followed all the steps but I'm not sure what it was all leading up to. Can you explain what this issue was supposed to fix? I also didn't attach any screenshots, so I'm not sure what those images are.

**Comment by mchait18** [comment]
> @mchait18 Thank you for taking on this issue.
> 
> ### Things that went well
> * The title and description are great
> * The branch is correct
> * The issue is linked correctly
> 
> ### Few things that need to be fixed
> * The url is broken sends me to a 404 page.
> * The screenshots are not showing properly.
> 
> After those are done I am more than happy to take another review on this for approval.

I've corrected the above suggestions and am ready for a re-review. Thanks

**Comment by dcotelessa** [comment]
### Review

- Title and description look good
- Branch correct
- The issue is linked
- URL is fixed
- Do we need to keep screenshots info? (Noted the "no visual changes necessary" under the "Visuals before changes are applied"

**Comment by t-will-gillis** [comment]
Hi @dcotelessa -

> ### Review
> 
> - Title and description look good
> - Branch correct
> - The issue is linked
> - URL is fixed
> - Do we need to keep screenshots info? (Noted the "no visual changes necessary" under the "Visuals before changes are applied"

Please add yourself as a reviewer and submit these comments as a review. Thanks!

**Review by codyyjxn — APPROVED** [review]

**Comment by mchait18** [comment]
> ### Review
> * Title and description look good
> * Branch correct
> * The issue is linked
> * URL is fixed
> * Do we need to keep screenshots info? (Noted the "no visual changes necessary" under the "Visuals before changes are applied"

I removed the screenshot info. Can you please submit as a review so this can be merged? Thanks

**Comment by siyunfeng** [comment]
Review ETA: 11/25/2024 Monday
Availability: 6-10 PM Weekdays (EDT)

**Review by siyunfeng — APPROVED** [review]
Great job working on this issue, @mchait18 !

- Availability and ETA are provided in the original issue
- The branch you made the change on is correct
- The original issue number is linked
- The change you made is accurate, the corresponding labels appear in the updated issue template
- The CodeQL Alerts are checked

**Things to improve**:
- Keep the `Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)` for your corresponding answer `No visual changes to the website`

**Reminder**: 
- Complete the following action item from the original issue: 
    - After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable the `Issues` feature

Thank you for your contribution.

**Comment by mchait18** [comment]
> Great job working on this issue, @mchait18 !
> 
> * Availability and ETA are provided in the original issue
> * The branch you made the change on is correct
> * The original issue number is linked
> * The change you made is accurate, the corresponding labels appear in the updated issue template
> * The CodeQL Alerts are checked
> 
> **Things to improve**:
> 
> * Keep the `Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)` for your corresponding answer `No visual changes to the website`
> 
> **Reminder**:
> 
> * Complete the following action item from the original issue:
>   
>   * After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable the `Issues` feature
> 
> Thank you for your contribution.

This is what it says to do in the Note -

**Comment by mchait18** [comment]
Hey @daras-cu, You mentioned last night that you'd merge this issue. Thanks so much :)

**Pull request merged**
