### PR TITLE
Standardizing buttons on entire HfLA site

### LINKED ISSUE #923: Standardize all buttons across the site
### Overview
We need to standardize the buttons across the entire HfLA site. This is to ensure visual consistency, and to make it easier and more efficient for developers to insert buttons when creating new pages.

### Action Items

UI/UX
- [x] Audit all buttons on site
- [x] Determine standard button features (colors, sizes, etc)

Development
- [x] Determine CSS class names and properties for standardized buttons
- [x] Implement CSS and HTML changes in the code to standardize buttons on site

### Resources/Instructions
[Design System Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Design Audit: Edits Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4272%3A0)
[Standardizing Components Wiki Draft](https://docs.google.com/document/d/1dxY6ieLd445buJg118wRfwFaBk1xfltXV-wTZOXlY9I/edit)

### PR DESCRIPTION
**Pull request by daniellex0**
Fixes #923 

Edited the CSS classes of all buttons on the HfLA site to make them consistent, based on the standards listed out [HERE](https://github.com/hackforla/website/wiki/Standardized-Components).

The standard CSS classes live in `_buttons.scss`, with some guideline comments.

This pull request will be successful if all of the buttons look and function, for the most part, the same as they currently do on the website.

I made some slight size adjustments to some buttons for consistency (the 'XL' button on the home page is now slightly smaller to conform to font and pixel size standards). 

The XL button on the home page is also now responsive (smaller on mobile), and the one on the Wins page is still responsive but with different sizes than the original page.

I also made some style adjustments in the CSS (changing px font sizes to rem, etc.)

Please let me know if there are any questions, because I know this might be a daunting pull request..

### CODE REVIEW

**Review by Oskar-Potratz-Zloch — COMMENTED** [review]
Everything makes sense, and generally looks okay, but let me ask, if You wanted to change rem's proportions (font scales) for all the buttons, how many attributes would You need to update?

**Review by drubgrubby — APPROVED** [review]
Really good work!  These many changes were clearly made carefully and completely and it shows...or, rather, it doesn't show, which was the point.  

There are a few super minor variations from the current look that I noticed: 
- The large button on the main page is a smidge smaller
- The "view on meetup" button on the events page is smaller
- On the toolkit page the external resources cards move down a couple of pixels
(This was all in Firefox, FYI)

The only one of those differences that's really even noticeable is the "view on meetup button".  I'm guessing that was known/intentional.  Please confirm that.

Even thought it's not really part of the pull request, the Standardized Components document is really well done and a great reference.

**Comment by drubgrubby** [comment]
Current: 
Screen Shot 2021-01-19 at 6 20 50 PM

New: 
Screen Shot 2021-01-19 at 6 21 09 PM

**Comment by daniellex0** [comment]
@drubgrubby thank you for going through this huge pull request!

> The large button on the main page is a smidge smaller

Yes that is on purpose- for standardized font size (24px instead of 25px)

> The "view on meetup" button on the events page is smaller

This is on purpose as well, as the 'view on meetup' button veered away from the standard style

> On the toolkit page the external resources cards move down a couple of pixels

Hmm good catch, I didn't notice that.. I'm not sure why that is.. :/ I can look into it..

And thank you so much about the wiki feedback!

**Review by ItsLaszlo — APPROVED** [review]
Nothing is out of place. Everything seems intact and looks the same as the original site excluding some sizing differences in buttons but that is due to the standardizing of buttons. Great job it all looks good!

**Pull request merged**
