### PR TITLE
Update Image Tag in About Page

### LINKED ISSUE #5189: img Tag Refactor: _includes/about-page/about-card-donations.html - donations.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-donations.html - donations.svg`
- [x] Remove the ending slash in the img HTML tag by changing
```
<div class="about-us-section-header" data-hash="donations"><span class="sec-head-img"><img src="/assets/images/about/section-header-elements/donations.svg" alt="" /></span>Make a Donation</div>
```
to
```
<div class="about-us-section-header" data-hash="donations"><span class="sec-head-img"><img src="/assets/images/about/section-header-elements/donations.svg" alt=""></span>Make a Donation</div>
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-donations.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by DomenicScozz**
Fixes #5189 

### What changes did you make?
  - The change involves using a self-closing img tag without a trailing slash.

### Why did you make the changes (we will use this info to test)?
  - I implemented this alteration to enhance the uniformity of the codebase.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
I removed the ending slash from the image tag, but there were no visual changes as a result.

### CODE REVIEW

**Comment by DomenicScozz** [comment]
> Fixes #5189
> 
> ### What changes did you make?
> * The change involves using a self-closing img tag without a trailing slash.
> 
> ### Why did you make the changes (we will use this info to test)?
> * I implemented this alteration to enhance the uniformity of the codebase.
> 
> ### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
> I removed the ending slash from the image tag, but there were no visual changes as a result.



> Fixes #5189
> 
> ### What changes did you make?
> * The change involves using a self-closing img tag without a trailing slash.
> 
> ### Why did you make the changes (we will use this info to test)?
> * I implemented this alteration to enhance the uniformity of the codebase.
> 
> ### Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)
> I removed the ending slash from the image tag, but there were no visual changes as a result.

Note: Although I only edited a single line to remove the trailing slash from the image HTML tag, my IDE, VS Code, is detecting modifications in other lines when I save the file. I've ensured that I don't have any auto-formatting enabled on save or any extensions that might be altering the file format. If you have experience with this issue, I'd greatly appreciate any advice on how to resolve it.

**Review by bphan002 — APPROVED** [review]
Hi Domenic,

Thanks for looking at this issue.  You edited the img tag and removed the closing slash and also removed the white space from the 2 bottom divs.

Everything looks the same after I ran your code in docker.

**Comment by LRenDO** [comment]
Hi @adrianang! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. If for some reason you find that you're unable to review the request, please remove yourself as a reviewer. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hey @DomenicScozz Great job on this issue. Your branches look good, you are linked to the original issue, your description briefly describes what you did and why, and you noted that there are no visual changes. Your code is clean and only edits what is needed. 

>Note: Although I only edited a single line to remove the trailing slash from the image HTML tag, my IDE, VS Code, is detecting modifications in other lines when I save the file. I've ensured that I don't have any auto-formatting enabled on save or any extensions that might be altering the file format. If you have experience with this issue, I'd greatly appreciate any advice on how to resolve it.

I can see that on lines 3 and 5, some whitespace is deleted- I think this might be what your note about is referring to? If so, this is fine.

Thanks for contributing!

**Pull request merged**
