### PR TITLE
img tag refactor in project leadership card

### LINKED ISSUE #5256: img Tag Refactor: _layouts/project.html - item.picture
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_layouts/project.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class='leader-img' src='{{ item.picture }}' />
```
to
```
<img class='leader-img' src='{{ item.picture }}'>
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html
2. Webpage(s): https://www.hackforla.org/projects, https://www.hackforla.org/projects-check/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by erinzz**
Fixes #5256
**What changes did you make?**
	• removed slash from img tag in projects leadership card html file
**Why did you make the changes (we will use this info to test)?**
	• for img tag notation consistency in codebase

**Screenshots of Proposed Changes Of The Website (if any, please do not screen shot code changes)**
No visual changes after code changes applied; see below.

### CODE REVIEW

**Comment by allison-truhlar** [comment]
ETA: EOD Wednesday, Aug 23
Availability: Weds 9-5pm ET

**Comment by LukeLowrey2** [comment]
ETA: Thursday, 8/24
Availability: Thursday 8/24 10am - 12pm, Sunday 8/27 9am - 10am

**Review by allison-truhlar — CHANGES_REQUESTED** [review]
Hi @erinzz! Great work on this pull request. The commit is to and from the correct branches - it is into "hackforla:gh-pages" and from your branch of the code. The pull request contains a correctly formatted linked issue. The changes you made to the code are clean - you only removed the ending slash in the img tag for the leader-img - and the changes did not result in any visual changes on the website, as expected.

I have one small change request - can you please edit your opening comment in the pull request to remove the before and after images, and replace them with a statement that no visual changes occurred. See detailed instructions here: https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available 

After you have done this, please click the circular arrows by my icon under the "reviewers" section on the top right of the pull request to re-request a review.

Thank you and please let me know if you have any questions!

**Comment by LRenDO** [comment]
Hi @mademarc and @k-rewd! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.  Thanks!

**Comment by erinzz** [comment]
Hey @allison-truhlar, thanks for reviewing! I've updated the pull request.

**Review by allison-truhlar — APPROVED** [review]
@erinzz - Thanks for updating the opening comment in the pull request to remove the screenshots! This pull request looks great!

**Review by k-rewd — APPROVED** [review]
Nice. img tag no longer includes a closing '/' as requested by the instructions. Branches are set up correctly and pull request comment has been edited to note that no visual changes are applicable. Well done!

**Review by LukeLowrey2 — APPROVED** [review]
Hello @erinzz! 

- You are committing into the correct branch ‘hackforla:gh-pages’
- The issue has been linked to the PR correctly 
- Clean edit with slash removed from ‘leader-img’ image tag

This looks awesome and thank you for editing the PR comment.

Great job!

**Comment by mademarc** [comment]
Review ETA: 8/24/2023
Availability: 7:14PM

**Review by mademarc — APPROVED** [review]
Hey @erinzz  Good job on the removal of the slash on the hmtl img tag and @LRenDO the  ETA and Availability is done.

**Review by adrianang — APPROVED** [review]
Hi @erinzz — the branching is set up correctly, the corresponding issue is linked, the requested change of removing the ending slash from the image tag on line 151 was made exactly as asked, and it didn't seem to affect any of the project leader cards for the projects I checked on my local environment.

The What and Why sections of your PR are well-written, and the Screenshots section is clear, but it's visually a bit difficult to read as the headings from the PR template were stripped away. The headings are in the PR template for a reason and should be kept in — something to keep in mind for your future PRs.

Thanks for completing this issue!

**Pull request merged**
