### PR TITLE
Edit and additions to Project Profile Card template

### LINKED ISSUE #5857: Edits and additions to "Project Profile Card" template
### Overview
There are some projects at Hack for LA that need to be added to the website. We want to update our `project-profile-card-review-and-update.yml` file to provide options for adding a new project card that will be displayed on the website.

### Action Items
Refer to the `project-card-review-and-update.yml` file. In this file:
- [x] Replace the line:
```
description: "To track project profile card updates"
```
with:
```
description: "To track project profile card updates or add a new project profile card"
```
- [x] Locate the code for the dropdown list labelled "Project Name". At the start of the list near line 18, add:
```
- "---New Project---"
```
- [x] Locate the code for the dropdown list labelled "Project Card URL". At the start of the list near line 62, add:
```
- "---New Project---"
```
- [x] Locate the code for the dropdown labelled "Update the Description?". **_After_** this section, add the following new section. Provide a single line space both above and below:
```
  - type: dropdown
    id: update-hero-image-yes-no
    attributes:
      label: Update the Hero Image?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: hero-image
    attributes:
      label: Hero Image
```
- [x]  Currently, there are three lines after the dropdown labelled "Update the Image?". Change this to a single line for consistency with the rest of the file.
- [x] Locate the code for the dropdown labelled "Update the Image?". After `validations:` `required: true`, replace:
```
  - type: input
```
with:
```
  - type: textarea
```
- [x] Locate the code for the dropdown labelled "Update the Technologies?". Replace the line:
```
      label: Technologies (maximum 26 characters)
```
with:
```
      label: Technologies (maximum 26 characters per technology name)
```
- [x] Change the spacing both after this line and after the dropdown labelled "Update the Partner(s)", each to a single line.

### Resources/Instructions
- [project-card-review-and-update.yml](.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml)

This issue was initiated by ER #4901

### PR DESCRIPTION
**Pull request by roychan1**
Fixes #5857

### What changes did you make?
  - all changes are made within the file "project-profile-card-review-and-update.yml"
  - changed wording in "To track project profile card updates" description and "Update the Technologies?" label
  - added option for new project in "Project Name" and "Project Card URL" drop downs
  - added drop down for Hero Image Update
  - cleaned up line spacings
  - changed "Update the image?" type from input to textarea
  

### Why did you make the changes (we will use this info to test)?
  - need to accommodate for new projects and hero image update
  - style and wording changes are to make the format uniform

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes on website, the modified file is an Issue Form Template.

### CODE REVIEW

**Comment by freaky4wrld** [comment]
Availability: Evenings 
ETA: EOD 11/17

**Review by freaky4wrld — APPROVED** [review]
Hey @roychan1 , great work there..... the to/from branch is correct, the changes made and the reason to change are apt and correct, the linked issue is mentioned correctly. The file has uniform format throughout, the change and addition is correctly done as well ....... Approved!!!

**Comment by Chrisklangley** [comment]
Availability: M-F 6-9pm
ETA: EOD 11/122

**Review by Chrisklangley — APPROVED** [review]
Hey @roychan1 

NIce work on on your pull request!
• you correctly linked your issue and your documentation of the changes you made  are very clear
•you made all the correct updates to the project-profile-card-review-and-update.yml file

Visually everything looks great!
keep up the good work

**Pull request merged**
