### PR TITLE
Mark civic tech structure 3895

### LINKED ISSUE #3895: Mark Civic Tech Structure as Completed and change visibility to False
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the Civic Tech Structure project as `Complete` and make it not visible on the site
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
In `_projects/`, change the following for Civic Tech Structure from
- [x] Status
  ```
  status: Active
  ```
  to
  ```
  status: Complete
  ```
- [x] Visibility
  ```
  visible: true
  ```
  to
  ```
  visible: false
  ```

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/civic-tech-structure.md`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, Civic Tech Structure page](https://www.hackforla.org/projects/civic-tech-structure)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-structure.md?plain=1
- This issue is part of an epic: #3891

### PR DESCRIPTION
**Pull request by RyanGehris**
Fixes #3895

### What changes did you make and why did you make them ?

  - updated status of civic tech structure to complete
  - updated visibility of civic tech structure to false
  - Made these changes to reflect the current status of the project

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-02-02 at 5 12 11 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-02-02 at 5 12 02 PM

</details>

### CODE REVIEW

**Comment by bzzz-coding** [comment]
Availability: Tuesday and Thursday evenings
ETA: By end of day 2/3/23

**Comment by ExperimentsInHonesty** [comment]
@bzzz-coding You asked to review this issue.  But your ETA that you mentioned has passed.  Gentle reminder to either review it or remove yourself as a reviewer

**Comment by bzzz-coding** [comment]
I'm sorry I've been very sick this past week. Here's my updated ETA:
ETA: By end of day 2/6/23

**Review by bzzz-coding — CHANGES_REQUESTED** [review]
@RyanGehris Thanks for working on this issue and asking questions in the comments to clarify the task! 

I noticed that on line 61 you have changed the `status` from `Active` to `Completed`, but in issue #3895, the instruction uses `Complete`. (`status: Complete`)
Could you please make this edit? Thank you!

**Comment by RyanGehris** [comment]
@bzzz-coding Thank you for catching that. I was confused because the other "Completed" projects displayed on the website had a status of "Completed", but the ticket does say to change the status to "Complete". I just made the changes. I hope you feel better soon.

**Comment by bzzz-coding** [comment]
> @bzzz-coding Thank you for catching that. I was confused because the other "Completed" projects displayed on the website had a status of "Completed", but the ticket does say to change the status to "Complete". I just made the changes. I hope you feel better soon.

@RyanGehris Thank you! And thanks for catching that -- I just opened a few files and noticed the same thing. The files below currently have `status: Completed`.
- ems-triage-tracker.md 
- heart.md
- hellogov.md
- metro-ontime.md
- public-tree-map.md
- undebate.md
- work-for-la.md

@hackforla/website Could someone help us clarify the instruction in issue #3895? Should the status be updated to `Complete` or `Completed`? Many thanks!

**Comment by jdingeman** [comment]
Hello @bzzz-coding and @RyanGehris, for the sake of consistency, please use `Completed`

**Comment by RyanGehris** [comment]
Thank you @jdingeman 

@bzzz-coding  I updated the status from "Complete" to "Completed". It is ready for review when you are available.

**Review by bzzz-coding — APPROVED** [review]
@RyanGehris Thanks for working on this issue! Everything looks good! 
Thank you for bringing up consistency concerns in the comments and being so diligent!

**Comment by t-will-gillis** [comment]
availability: 2/9 
eta: 2/9 7 pm

**Review by t-will-gillis — APPROVED** [review]
Hi @RyanGehris - great job on your first issue! You are committing from/to the correct branches, and the changes are clean and complete. But also>>> it is great that you and @bzzz-coding are paying attention to details, and not just following the issue but going beyond to make sure the changes are consistent and make sense. Well done

**Pull request merged**
