### PR TITLE
Changed iframe object to object video player

### LINKED ISSUE #6749: Refactor the Events page header to replace the iframe element
### Overview
We need to refactor the HTML rendering the "Code for America" video within the header of the [Events page](https://www.hackforla.org/events/), with the goal of using an `embed` or `object` element to present the video, in place of the `iframe` element.

### Details
- To understand the history behind this issue and suggested approaches, see #6353

### Action Items
- [x] Open your IDE to `_includes\events-page\header-container-content.html`
- [ ] Refactor the HTML, replacing the `iframe` element with an `embed` or `object` method, modifying the code and styling as needed so that the appearance and behavior of the page is unchanged at all screen sizes. 
- [ ] If possible, perform local testing using docker on both Windows and Mac systems.  

### Resources/Instructions
[Events webpage](https://www.hackforla.org/events/)
[HTML for header of Events page](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html)
<details><summary>embed element</summary>
<p>

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed
```
<div>
  <embed class="video-size" src="https://embed.ted.com/talks/jennifer_pahlka_coding_a_better_government" width="854" height="480" frameborder="0" scrolling="no" allowfullscreen>
</div>
```
</p>
</details> 
<details><summary>object element</summary>
<p>

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object
```
<div>
  <object class="video-size" data="https://embed.ted.com/talks/jennifer_pahlka_coding_a_better_government" width="854" height="480" frameborder="0" scrolling="no" allowfullscreen></object>
</div>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by Cloid**
Fixes [#6749](https://github.com/hackforla/website/issues/6749)

### What changes did you make?
  - Updated iframe to object video player.

### Why did you make the changes (we will use this info to test)?
  - To circumnavigate privacy / video blockers dictated by browsers.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Before Changes</summary>
image
</details>

<details>
<summary>After Changes</summary>
image

</details>

### CODE REVIEW

**Comment by ajb176** [comment]
Hey @Cloid 

Don't hyperlink the issue number, that's done automatically. The first line should just be: Fixes #6749

Just to clarify, your first line currently is: `Fixes [#6749](https://github.com/hackforla/website/issues/6749)` when it should just be `Fixes #6749`

**Comment by ha-bach** [comment]
Reviewing this PR.
Availability: Friday afternoon, Saturday, Sunday morning, Monday.
ETA: by end of Monday.

**Review by ha-bach — CHANGES_REQUESTED** [review]
Hi @Cloid, great work!
What works:

- Original issue is linked
- Appropriate into and from branches
- Good PR description, visual changes are provided
- Object implementation works well on my Linux laptop

Concerns:

- There is a merge conflict with the current version of the website that needs to be resolved before it can be merged (if you need help with this let me know)
- Video does not fit the screen on mobile view (I tested using Galaxy S20 Ultra on Firefox). Googling 'responsive video object' gets several possible fixes for this issue. Changing object's width to a percentage and change height accordingly seems to work on my end.

**Comment by Thinking-Panda** [comment]
@Cloid Please resolve the merge conflict and  add an availability and ETA for the requested changes. Thanks!

**Comment by Cloid** [comment]
Hi there, sorry for the delay. I'll finish this by EOD Thursday, 08/01

**Comment by Cloid** [comment]
@muninnhugin Screen sizing is now fixed for all screen sizes, tested via Firefox/Chrome.

**Comment by ha-bach** [comment]
Reviewing now, should be done by EOD today. Sorry new schedule, I'm really busy during the week now.

**Review by ha-bach — APPROVED** [review]
Both mobile screen size and merge conflicts are fixed. Approving this PR. Thanks for contributing @Cloid!

**Review by roslynwythe — APPROVED** [review]
Great job @Cloid with this challenging issue.
-  code is clean and complete
- Pull Request has well-formed branches, screenshots and descriptive text
- This branch checks out in the browser (Chrome) at all screen sizes
Thank you!

**Pull request merged**
