### PR TITLE
Refactor tag step img intro 4375

### LINKED ISSUE #4375: img Tag Refactor: Getting Started page - `step-img-intro business.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-intro" src="./assets/images/getting-started/business.png" alt="" />
```
to
```
<img class="step-img-intro" src="./assets/images/getting-started/business.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by Maia-Cochran**
Fixes #4375

### What changes did you make and why did you make them ?

  - removes slash in HTML
  - line 16 changes from `````` to `````` per issue indication 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- N/A

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: 10 AM - 3PM
ETA-5/16/23

**Review by Thinking-Panda — CHANGES_REQUESTED** [review]
Hi @Maia-Cochran , merge branches looks good, code is clean and works well on the local machine. But, changes to line 166 seems beyond the scope of this issue. (probably there is another issue written for that change and being worked on by someone else). Please undo the changes on line 166. TIA!

**Comment by roslynwythe** [comment]
Hi @aalieu @kotynskm If you plan to review this PR, please add your Availability and ETA in a comment so we know when we can expect your review.  Thanks!

**Comment by jenny-alexander** [comment]
Availability: 5/22/23 10 AM - 2PM
Availability: 5/22/23 10 AM - 2PM

**Review by jenny-alexander — CHANGES_REQUESTED** [review]
Hi @Maia-Cochran , thank you for doing the work needed to fix issue 4375.
- The branches look good (going into hackforla: ghpages from your branch)
- Linked issue is stated in PR
- Requested change to line 16 is done correctly.

All of this looks great!

**However**, can you please undo changes from line 166 as I don't see this as a requested change in issue #4375 . Once this is done, I can approve the PR.

**Comment by Maia-Cochran** [comment]
Hi all! Changes to line 166 have been reverted to its original state. I apologize for any confusion. Please, let me know if there is anything further you need from me! Thanks! Availability: M-F 9am-6pm MST

**Review by jenny-alexander — APPROVED** [review]
@Maia-Cochran Thank you for reverting back line 166. Approved!

**Review by Thinking-Panda — APPROVED** [review]
@Maia-Cochran , Thank you for changes. LGTM now!

**Review by chrismenke45 — APPROVED** [review]
Great Work @Maia-Cochran . The changes are being merged into the correct branch and look good on the site.

**Pull request merged**
