### PR TITLE
Add github-handle for Natalie Aguilar in tech-work-experience.md #7252

### LINKED ISSUE #7252: Add github-handle for Natalie Aguilar in tech-work-experience.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/tech-work-experience.md` in the IDE
- [x] Replace:
```
- name: Natalie Aguilar
```
with
```
- name: Natalie Aguilar
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
Project Webpage: https://www.hackforla.org/projects/tech-work-experience

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by rachelcorawood**
Fixes #7252

### What changes did you make?

replaced 
- name: Natalie Aguilar
with

- name: Natalie Aguilar
  github-handle:
  

### Why did you make the changes (we will use this info to test)?

 We need to create a single variable github-handle to hold the github handle for each member of the leadership team. Eventually github-handle will replace the github and picture variables, reducing redundancy in the project file.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual changes to the website

### CODE REVIEW

**Comment by daras-cu** [comment]
ETA: 8/18 EOD
Availability: Sun/Mon all day, other weekday evenings

**Review by daras-cu — CHANGES_REQUESTED** [review]
Hi @rachelcorawood, thanks for working on this issue! 

What looks good:
- Your branches are set up correctly
- The original issue number is linked in the pull request
- Good explanation of the changes and note that there should be no visual changes to the site
- When testing, the project page displays correctly with no changes

Issues:
- There are changes to multiple other lines in `tech-work-experience.md` not called for in the issue. It looks like just some white spaces were removed, so I would check if you have some kind of automatic formatting enabled in your editor.
- Just a note, in your pull request if you start a line with "- " it will show up as a bullet point automatically. That's why you're getting a bullet point in front of "name: Natalie Aguilar" in the "What changes did you make" section. If you want code to display without automatic formatting you can use \` to wrap a code snippet or \``` for multi-line code.

For example:
\``` 
\- name: Natalie Aguilar
&nbsp;&nbsp;github-handle:
\```
 will display as:
```
- name: Natalie Aguilar
  github-handle:
```

Overall good job with the issue! Once you've fixed the extra changes to the file, let me know in a comment or re-request a review.

**Comment by 8alpreet** [comment]
Review ETA: EOD Mon Aug 19
Availability: Mon to Fri; 3 p.m. to 7 p.m.

- [x] Step 0: Is the pull request done with the correct branch?
- [x] Step 1: Is there a linked issue?
- [x] Step 2: Understand the linked issue.
- [x] Step 3: View the changes in the browser.
- [ ] Step 4: Take a look at files changed tab.
- [ ] Step 5: Check for anything else.
- [ ] Step 6: Approve the pull request.
- [ ] Step 7: Clean up your working repo.

**Comment by 8alpreet** [comment]
Hi @rachelcorawood,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- the "What..." section clearly outlines the change.
- the "why..." section gives insight into the **why** of the changes

### Changes needed:
1. Extraneous changes
    - As the other reviewer mentioned, there are unnecessary changes likely made by a code linter/formatter you have installed.
2. "What" section
    - Though you clearly mention the change, the styling is not reader-friendly.

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @rachelcorawood ,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- "What.." section clearly outlines the change
- "Why..." section provides insight into why the changes were necessary

### Changes needed:
1. Extraneous changes:
    - There are changes, such as removal of spaces, which are not related to the linked issue. 
    - These changes seem valid, but I'm not sure if they should be a part of this PR.
2. The "What..." section:
    - While you clearly outline the change, the format of the information is not reader-friendly.
3. PR Title
    - Since the issue number is already a part of the branch name and it's at the top of you PR comment. It's not necessary to have it in the PR title. It may even be confusing (happened to me) to read because Github displays the PR number at the end of the title.

**Comment by minkang3** [comment]
ETA: EOD
Availability: 11-5 Weekdays

**Review by minkang3 — CHANGES_REQUESTED** [review]
Hi @rachelcorawood 
Like the other reviewers said:
- Pull request is done with proper branches
- Issue is linked
- Understanding of the issue is shown
- Browser shows no apparent changes on my machine

What went wrong:
- Your code editor is likely adding styling changes to the file when you save, deleting extra spaces in lines outside of the code you edited. I'd recommend to revert the file to before the commit, turn off your styler and add the changes once more. It's good to keep your commits/prs atomic with changes just for the issue addressed.
- The format of the PR could be better. Markdown supports codeblocks which may help with the readability of what you entered. You should surround any code with ```

Everything else looks good, just make the requested changes.

**Review by codyyjxn — CHANGES_REQUESTED** [review]
Your branch is set up correctly

1. The original issue number is linked in the pull request
2. Good explanation of the changes and note that there should be no visual changes to the site
3. When testing, the project page displays correctly with no changes

Things that need change: 
1. There is whitespace that was removed and it making unnecessary changes to the file.

**Comment by Thinking-Panda** [comment]
@rachelcorawood Please make the requested changes and re-request a review. Thanks!

**Comment by jphamtv** [comment]
@rachelcorawood - Closed this PR as #7405 replaces it. For future reference, maintain only one active PR per issue. If you need to open a new PR, please close the existing one first. Thanks!

**Pull request closed without merging**
