### PR TITLE
github-issues (html and scss files) updated to resolve visual issues.

### LINKED ISSUE #794: Getting the Most out of Github Issues Guide
### Dependency
New Issue for figuring out how we can use markdown and then this issue will be restructured. #1085

### Overview 

The 'Getting the most out of Github Issues' guide is complete, but not live due to a problem with how it is showing up visually. We need to fix the visuals so that we can get it live in our toolkit. 

### Action Items 
Development 
- [x] Discuss with Danielle how the CSS should be set up 
    - [ ] If restructuring is recommended, then fix the survey-reporting-dashboard-guide to use new SCSS format and do PR 
    - [x] Update the getting the most out of github guide to use the new SCSS format 
- [x] Add link to the toolkit page and update the card to reflect live status 
- [ ] Create a new Wiki page with a clear explanation on how to execute the responsiveness of the red link indicators and link it to the architecture/ how to create a guide  

### Resources 
[Github Issue Guide](https://www.hackforla.org/guide-pages/github-issues.html)
[Example of guide for what it should look like](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide)
[Toolkit page](https://www.hackforla.org/toolkit)
[Original issue for the guide](https://github.com/hackforla/website/issues/514)
[How to create a guide page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#guide-pages)

Image highlighting the problem: 
Screen Shot 2020-10-23 at 11 47 06 AM

### PR DESCRIPTION
**Pull request by abenipa3**
- Updated github-issues-guide.scss and github-issues.html to resolve visual issues.
- Updated the card to reflect live status.

Fixes #794

UPDATE 4:04 PM 1/11/21: I've just identified a new visual issue after reviewing it in iPad mode. Will update once it's resolved. Thanks.

### CODE REVIEW

**Comment by abenipa3** [comment]
Fixes #794

- Visual issue resolved. Ready for review.

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@alyssabenipayo - Good work on getting the flags to be more stable.  Hopefully at a developers' meeting you can explain your solution.  

Unfortunately, it seems that while the iPad version is now fixed, on the iPhone version the flags are now pushed over the top of the things they are flagging. 

Screen Shot 2021-01-18 at 7 05 23 AM

On the current version that's live on the site the mobile version seems okay.  

Perhaps you can play with the css media query (or something) to make it so both the tablet and mobile versions track correctly.

**Comment by abenipa3** [comment]
@drubgrubby - Thank you for your feedback. 

I might be late in attending tonight's meeting -- going to help my parents out tonight and not sure when I'll be back.

In the meantime, here's a brief explanation of the solution: 
- The @ mixins for the guide arrows in _guide-pages.scss are reusable, which makes it easier to resolve the visual issue as long as we call the correct class.
- In this case, the class "overlay-links-img" is the class we used so that the arrows will connect with the image. 
image
- Initially, we had "screenshot" as the class, which did not work.
image

I'll be more than happy to elaborate either tonight's meeting or on Sunday. Will continue to experiment with the media query. 

Thanks.

**Comment by abenipa3** [comment]
Redesigning guide pages. #1085

**Pull request closed without merging**
