### PR TITLE
556 fix bugs in titles

### LINKED ISSUE #556: Refine HackforLA page titles
### Overview
The pages on the HfLA site should have unique names that make sense for the content that is on them.  This currently does not seem to be the case.

### Action Items
- [ ] Figure out why the titles are not showing up correctly on the following pages (likely different reasons)
   - [ ] Static HTML pages 
      - [ ] https://www.hackforla.org/project-meetings (currently just says "Hack for LA")
      - [ ] https://www.hackforla.org/getting-started (currently just says "Hack for LA")
   - [ ] On all the following redirect pages (currently says "Twitter_Logo_Blue")
      - [ ] https://www.hackforla.org/survey4
      - [ ] https://www.hackforla.org/survey3
      - [ ] https://www.hackforla.org/survey6
      - [ ] https://www.hackforla.org/donate
   - [ ] Check the other redirects
      - [ ] conduct.md
      - [ ] github.md
      - [ ] meetup.md
      - [ ] nationalday.md
     - [ ] slack.md

### Resources/Instructions
I used this site to find these pages: https://www.xml-sitemaps.com/

### PR DESCRIPTION
**Pull request by ye-susan**
Added titles to markdown files and Getting Started and Project Meetings html files to prevent these pages from pulling <title> tags from any other file, in order to have a clean site XML.

### CODE REVIEW

**Comment by cnk** [comment]
The 2 volunteer buttons look good to me. 

But why are you adding titles to the redirect pages? The redirect layout doesn't use that field (_layouts/redirect.html)

**Comment by ye-susan** [comment]
Hi Cynthia, thank you for looking into this.

I added the title front matter to getting-started and project-meetings since they use include\head.html, but I see your point that this wouldn't do anything for the redirect pages. 

Bonnie was seeing 'Twitter_Logo_Blue' as the titles for the redirect pages (and getting-started and project-meetings pages) using https://www.xml-sitemaps.com/. I think removing the <title> from the svg files would prevent this, but do you think it would be better to leave the titles as blanks or include {page.title} in the redirect.html's '< head >'?

**Comment by cnk** [comment]
Given that a title is showing in the sitemap tester, I would add a <title> attribute to the <head> section of the redirect.html layout.

**Comment by ye-susan** [comment]
@cnk, please see the revised <title> tag added to the redirect layout. Thank you!

**Pull request merged**
