### PR TITLE
Update Project Profile: Guides Team (Add Mary Gabrielian) 

### LINKED ISSUE #6509: Update Project Profile: Guides Team (Add Mary Gabrielian)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and add the following:
```
  - name: Mary Gabrielian
    github-handle: marygabrielian
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U06KMNL8ETY
      github: https://github.com/marygabrielian
    picture: https://avatars.githubusercontent.com/marygabrielian
```
- [x] If there are other Product Managers, place Mary Gabrielian's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [x] Once your pull request is merged, go to #6466 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #6466 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6466 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by gdkoo**
Fixes #6509 

### What changes did you make?
  - Added Mary Gabrielian's profile to Guides Team 

### Why did you make the changes (we will use this info to test)?
  - To complete onboarding of new Guides Team leader, to keep Projects up to date with current leadership.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

guides-team-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
guides-team-after

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 3/28/24
Availability: Weekday evenings

**Review by pdimaano — APPROVED** [review]
@gdkoo Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was updated and formatted properly with the requested information. Well done!

**Comment by aidanwsimmons** [comment]
ETA: EOD today
Availability: Weekday afternoons

**Review by Thinking-Panda — APPROVED** [review]
@gdkoo , Thank you for working on this issue. Merge branches are setup correct, code changes are as mentioned in the issue, website works well on my local machine. Well done. Approved!

**Review by aidanwsimmons — APPROVED** [review]
changes look good- issue/ branch linked correctly. Nice job!

**Pull request merged**
