### PR TITLE
completed issue 4961: updating CONTRIBUTING.md.

### LINKED ISSUE #4961: Update CONTRIBUTING.md to reflect updated PR template, part II
### Overview
We need to update CONTRIBUTING.md to reflect the changes in the Pull Request template. This is a continuation of #4870.

### Action Items

- [x] [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md), find Section 3.1b(iii) and replace:
````
##### **iii. Complete pull request (3): What changes did you make**

In bullet point form, notate the changes you made to be in order to complete the action items within your issue. [@adrian-zaragoza](https://github.com/adrian-zaragoza) provided the following summary in PR [Update Care Link in Credits Page - #2131](https://github.com/hackforla/website/pull/2131):

```
### What changes did you make and why did you make them ?

- Updated title and alt to Care.
- Updated artist to Bharat
- Updated filename to care.yml

```
````
with:
````
##### **iii. Complete pull request (3): Explain the changes you made, then explain why these changes were needed**

In bullet point form, explain the changes you made in order to complete the action items within your issue and why. [@adrianang](https://github.com/adrianang) provided the following summary in PR [Add Project to Website: Tech Work Experience #4911](https://github.com/hackforla/website/pull/4911):

```
### What changes did you make?
  - Created new markdown file for the Tech Work Experience Project (tech-work-experience.md)
  - Added assets (project card image, project hero image, PDF overview) to their appropriate folders

### Why did you make the changes (we will use this info to test)?
  - To keep list of active HfLA projects on the website up-to-date

```
````

- [x] At the top of the same file, find the entry for Section 3.1b(iii) and replace:
```
 - [**iii. Complete pull request (3): What changes did you make**](#iii-complete-pull-request-3-what-changes-did-you-make)
```
with:
```
 - [**iii. Complete pull request (3): Explain the changes you made, then explain why these changes were needed**](#iii-complete-pull-request-3-explain-the-changes-you-made-then-explain-why-these-changes-were-needed)   
```
- [x] Confirm in your repo that the changes were made correctly.    

### Resources/Instructions
[Pull Request template](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)

### PR DESCRIPTION
**Pull request by MattChau01**
Fixes #4961

##### Replaced the following code:
````````````````````
##### **iii. Complete pull request (3): What changes did you make**

In bullet point form, notate the changes you made to be in order to complete the action items within your issue. [@adrian-zaragoza](https://github.com/adrian-zaragoza) provided the following summary in PR [Update Care Link in Credits Page - #2131](https://github.com/hackforla/website/pull/2131):

```
### What changes did you make and why did you make them ?

- Updated title and alt to Care.
- Updated artist to Bharat
- Updated filename to care.yml

```
````````````````````
##### with:
````````````````````
##### **iii. Complete pull request (3): Explain the changes you made, then explain why these changes were needed**

In bullet point form, explain the changes you made in order to complete the action items within your issue and why. [@adrianang](https://github.com/adrianang) provided the following summary in PR [Add Project to Website: Tech Work Experience #4911](https://github.com/hackforla/website/pull/4911):

```
### What changes did you make?
  - Created new markdown file for the Tech Work Experience Project (tech-work-experience.md)
  - Added assets (project card image, project hero image, PDF overview) to their appropriate folders

### Why did you make the changes (we will use this info to test)?
  - To keep list of active HfLA projects on the website up-to-date

```
````````````````````
##### Replaced the following code:
````````````````````
 - [**iii. Complete pull request (3): What changes did you make**](#iii-complete-pull-request-3-what-changes-did-you-make)
````````````````````
##### with:
````````````````````
 - [**iii. Complete pull request (3): Explain the changes you made, then explain why these changes were needed**](#iii-complete-pull-request-3-explain-the-changes-you-made-then-explain-why-these-changes-were-needed)   
````````````````````

### Why did you make the changes (we will use this info to test)?
  - The purpose of these changes are to update the CONTRIBUTING.md file to reflect the changes in the Pull Request template. This is a continuation of https://github.com/hackforla/website/issues/4870.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No visual front end changes were made.

### CODE REVIEW

**Comment by allison-truhlar** [comment]
Availability: Tues 3:30-5pm ET
ETA: Tues 5pm ET

**Review by allison-truhlar — APPROVED** [review]
@MattChau01 - good job with this pull request! The branches are set up correctly, and your changes to the code match what was requested and are clean. Nice work!

**Comment by Tomomi-K1** [comment]
Availability: weekday 12-5pm
ETA: Tues 7pm

**Review by Tomomi-K1 — APPROVED** [review]
Hi @MattChau01 Thank you for taking up this issue. It all looks great! You have used correct branches, liked a correct issue, correct changes were made. Great job!

**Review by christinaor — APPROVED** [review]
Good job on this issue @MattChau01 ! Looks like the changes were made correctly in the markdown file. The branch was created correctly, and the issue itself was also descriptive.

**Pull request merged**
