### PR TITLE
Updated spell checker to ignore member's names

### LINKED ISSUE #7010: update spell check config file to ignore members' names
### Overview
We need to update the code spell check configuration file so that the spell checker excludes lines matching `- name: ` from checking, in order to reduce the number of false positives ("unknown word").  

### Action Items
- [x] Open the configuration file `cspell.json` in your IDE
- [x] Find an instance in which an individual's name is flagged as an "unknown word", for example the line `- name: "Saasha Gilkes"` in `_guide-pages/how-to-set-reminders-in-slack.md`
- [x] Using https://cspell.org/configuration/patterns/ as a reference, add a configuration setting so that lines matching `- name: ` are excluded from spell checking
- [x] Save the configuration file and confirm that instances such as `- name: "Saasha Gilkes"` in `_guide-pages/how-to-set-reminders-in-slack.md` are no longer flagged as "unknown word".  
- [x] Add and commit `cspell.json` and prepare a Pull Request in the usual manner.  

### Resources/Instructions
https://cspell.org/configuration/patterns/

- This issue resulted from #7004

### PR DESCRIPTION
**Pull request by vanessasinam**
Fixes #7010

### What changes did you make?
  - Updated the code spell check configuration file so the spell checker excludes lines matching "- name:".

### Why did you make the changes (we will use this info to test)?
  - So that the spell checker can avoid checking lines with " - name:" to reduce the number of false positives ("unknown word") in the spell check.
 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>No visual changes to website</summary>

</details>

### CODE REVIEW

**Review by mSharifHub — DISMISSED** [review]
Just before approving, json does not support comments.  on line 4   // words - list of words to be always considered correct should be removed.

**Comment by vanessasinam** [comment]
> Just before approving, json does not support comments. on line 4 // words - list of words to be always considered correct should be removed.

Hi, the comments on line 4 were not part of my changes.

**Comment by mrodz** [comment]
ETA EOD 7/2/24.
Availability: TWThFSSn (I am camping on Monday and early Tuesday)

**Review by mrodz — APPROVED** [review]
- Correct to/from branches
- Correct PR formatting
- Good description of changes
- The regex you provided looks correct to me—good on you for including the `$` to ensure the pattern ends after the name. 
  > #### Before
  > image
  > 
  > #### After
  > image

---  

Regarding @mSharifHub's observation, the comment has been in the file since its creation (015736e). Many JSON parsers handle comments even though they are not in spec, which is why this is not a problem. Additionally, dealing with this comment is not in the scope of this issue. 

---

Good stuff! Keep up the good work.

**Comment by t-will-gillis** [comment]
available: 7/7
eta: 7/7 eod

**Review by t-will-gillis — APPROVED** [review]
Hey @vanessasinam Great work! All of the basics are in place: branches are good, linked to orig. issue, concise description of what was done and why, and code edits are clean.
 
CSpell is ignoring `- name: <someone>` in all of the .md files per the issue requirements. Thanks for taking care of this issue and eliminating dozens of false positives from the spell checker.

**Pull request merged**
