### PR TITLE
Updated Alt for Donation Chart Image on Donation Card

### LINKED ISSUE #3856: Join Us Page: Update alt text for the donation chart image on the "Help Us Keep the Lights On" card to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Join Us` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_includes/donate-card.html`:

**From:**
```
alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"
```

**To:**
```
alt="Monthly: Hosting, Mailing List services, zoom; Annual: Domain Names; Occasional: Stickers, T-shirts"
```

- [x] Ensure that the corresponding `Join Us` webpage stays the same after the change
- [x] Using developer tools to inspect the image, ensure that the new alt text gets incorporated after the change.
  - **Note:** `alt=""` in code while show up as `alt` when using developer tools to inspect the image's alt text property.

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3858 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- Join Us Webpage: https://www.hackforla.org/join

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_includes/donate-card.html`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html
- This issue is part of epic #3858

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by mjshelton12**
Fixes #3856 

### What changes did you make and why did you make them ?

  - Updated the alt to the donation chart image on the donation card in order to adhere to WCAG
  - Ensured that the update didn't change anything else on the Join Us page
  - Ensured the changes were made in docker

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Only updated image alt, no visual changes to website

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 3/19 10 to noon
ETA 3/19 3 pm

**Review by roslynwythe — APPROVED** [review]
Congrats and thanks @mjshelton12 for a great job on the first issue!  The branches are correct, code is perfect, PR is well formed and informative, and checks out fine in the browser.

**Comment by roslynwythe** [comment]
Availability: 3/19 1 - 3 pm
ETA EOD 3/19

**Review by t-will-gillis — APPROVED** [review]
Hi @mjshelton12 - Great job on your first issue! Your from and to branches are correct, you have linked the issue, your description in the PR is well-written, and your code is clean and matches what the issue asked for. I am curious about the inconsistency in capitalization of the changes- but again, you did exactly what the issue directed you to do so that question is **not** a reflection on your work.

Great job and thanks for your work!

**Pull request merged**
