### PR TITLE
Re Issue 5753: Removed Jamie Siu from Expunge Assist project page leadership section

### LINKED ISSUE #5753: Update Project Profile: Expunge Assist (Remove Jamie Siu)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, remove
```
  - name: Jamie Siu
    role: Product Manager, Design
    links:
      slack: 'https://hackforla.slack.com/team/U036RQHGRRR'
      github: 'https://github.com/jamiesiu'
    picture: 'https://avatars.githubusercontent.com/jamiesiu'
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by tonyvang**
Fixes #5753 

### What changes did you make?
  -    Removed following code from _projects/expunge-assist.md

```
- name: Jamie Siu
    role: Product Manager, Design
    links:
      slack: 'https://hackforla.slack.com/team/U036RQHGRRR'
      github: 'https://github.com/jamiesiu'
    picture: 'https://avatars.githubusercontent.com/jamiesiu'
```

### Why did you make the changes (we will use this info to test)?
  - To remove Jamie Siu from Expunge Assist project page
  - To keep project info up to date and accurate

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot (15)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot (16)

</details>

### CODE REVIEW

**Comment by KyleA99** [comment]
Availability: 10/31 7-9 pm
ETA: 10/31 EOD

**Comment by KyleA99** [comment]
Jamie Siu's profile appears properly changed.  I do receive a merge conflict as Sheron Veroni was removed when PR #5793 was merged

**Review by LRenDO — CHANGES_REQUESTED** [review]
Hi @tonyvang!
Great job with this pull request!

- The branching was done correctly
- Issue number was listed
- The PR title is descriptive of the changes
- Changes were made correctly in the code
- Changes appear correctly on the site. Jamie Siu's card has been removed.
- Relevant images were included to show visual changes
- The PR request clearly states what was updated
- The PR request states why the changes are being made

I have only one request. As @KyleA99 mentioned, there is currently a merge conflict because Sheron Virani was removed and that PR was merged before yours. Please pull the changes into your local feature branch and push it to your forked repo again. This will update this PR with the changes. When you're done, you can click the circle with the arrows next to my name in the reviewers section and I will approve the changes. Please feel free to ping me if you have any questions.

Thanks for taking the time to contribute to the website!

**Comment by LRenDO** [comment]
> Jamie Siu's profile appears properly changed. I do receive a merge conflict as Sheron Veroni was removed when PR #5793 was merged

Hi @KyleA99! Great catch on the merge conflict! When you are submitting a review you can click on the `Files Changed` tab and click the `Review Changes` button.  Be sure to select either the `Approve` or `Request Changes` button according to the circumstance before clicking `Submit Review`.  Clicking the `Request Changes` button allows folks to easily re-request a review for approval once they make changes and `Approve` allows the review to count towards the review requirement to merge. Feel free to ping me if you have any questions!

**Comment by KyleA99** [comment]
@LRenDO thank you, realized I forgot to do that once I saw you did it.  I will also be more descriptive in my review comments!

**Review by KyleA99 — CHANGES_REQUESTED** [review]
Please see merge conflict comments from @LRenDO and myself.  If you have any questions on resolving this conflict, feel free to reach out to me on slack

**Comment by LRenDO** [comment]
@KyleA99 - All good! Thanks for updating and your future descriptive review ambitions!

**Comment by tonyvang** [comment]
Thanks @KyleA99 for the review and catching the merge conflict, and thanks @LRenDO for the review and tip re resolving; think I messed up by updating my feature branch w/ "sync fork" button in browser, overwriting my changes and closing this PR - should I redo PR?

**Comment by jaasonw** [comment]
@tonyvang you don't need to resubmit the pr, just pull in the changes locally, recommit your changes, and push them again

**Review by LRenDO — APPROVED** [review]
Hi @tonyvang! The changes look good to me now. You can click the circle with the arrow next to @KyleA99 in the Reviewers section to re-request a review.

**Comment by KyleA99** [comment]
Availability: 3 - 8 pm 11/2/23
ETA: EOD 11/2/23

**Review by KyleA99 — APPROVED** [review]
Code is properly changed and visuals look correct.  Great work @tonyvang 

PR approved

**Pull request merged**
