### PR TITLE
Added Github-handle for Byron Heart

### LINKED ISSUE #6730: Add github-handle for Bryon Heart in engage.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/engage.md` in the IDE
- [x] Replace:
```
- name: Bryon Heart
```
with
```
- name: Bryon Heart
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/engage

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by ino-iosdev**
Fixes #6730

### What changes did you make?

 - Replacement:

replaced
 
`- name: Bryon Heart` 

with
```
- name: Bryon Heart
  github-handle: 
```
  - maintained YAML front matter

### Why did you make the changes (we will use this info to test)?
  - Bryon Heart in engage.md is missing GitHub-handle

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No website visual change

### CODE REVIEW

**Comment by DrAcula27** [comment]
ETA: 1 June 2024
Availability: weekdays 5pm - 8pm Pacific time

**Comment by del9ra** [comment]
ETA: 10 PM 05/31/2024
Availability: 1-5 PM Friday

**Review by del9ra — CHANGES_REQUESTED** [review]
Hi @ino-iosdev,
- According to this document https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue the format of your branch name should look something like this “update-give-link-2093”. Please put the issue number at the end of the branch name.
- The issue is linked correctly
- Please do not delete “role: Product Manager”. You need to insert “github-handle:” between these two lines: “name: Bryon Heart” and “role: Product Manager”.
- Using Docker http://localhost:4000/projects/engage, you can see that the website is missing “Product Manager” after “Role:”
Please implement the changes and I will be happy to approve!
Thanks for your contribution! Good job!

**Comment by ino-iosdev** [comment]
> Hi @ino-iosdev,
> 
> * According to this document https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue the format of your branch name should look something like this “update-give-link-2093”. Please put the issue number at the end of the branch name.
> * The issue is linked correctly
> * Please do not delete “role: Product Manager”. You need to insert “github-handle:” between these two lines: “name: Bryon Heart” and “role: Product Manager”.
> * Using Docker http://localhost:4000/projects/engage, you can see that the website is missing “Product Manager” after “Role:”
>   Please implement the changes and I will be happy to approve!
>   Thanks for your contribution! Good job!

@del9ra 
Thanks for catching that! Is there anyway I can manually push my fork branch rename to this PR now that it's been already in the "from" and "to"? I renamed the branch on my fork already, just not sure how to link to here, appreciate your assistance here. Thank you.

**Pull request closed without merging**
