### PR TITLE
Change sdg image alt to comply with WCAG

### LINKED ISSUE #3095: Change alt text for sdg image in engage md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the engage project's sustainability development goal image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/engage.md`, change [line 73](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/engage.md?plain=1#L73) for the alt text:

from
```
sdg-image-alt: peace justice bottom sustainable dev goal
```
to
```
sdg-image-alt: '16: peace, justice and strong institutions'
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/engage.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/engage.md?plain=1#L73

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by neevliberman**
Fixes #3095

### What changes did you make and why did you make them?

  - Changed contents of the sdg-image-alt attribute to reduce wordiness

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to the website

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-25

**Review by Zak234 — APPROVED** [review]
Looks good. Great job!

**Comment by lilyarj** [comment]
Availability: 3hrs
ETA: 7-25

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Review by arpitapandya — APPROVED** [review]
The changes looks good! Great job!! @neevliberman

**Review by blulady — APPROVED** [review]
The branch being pushed is the correct branch [neevliberman:change-sdg-image-alt-3095](https://github.com/neevliberman/website/tree/change-sdg-image-alt-3095) and is going to the correct branch [hackforla:gh-pages](https://github.com/hackforla/website). It has a linked issue that is being properly addressed by changing line 73 in the _projects/engage.md file to  '16: peace, justice and strong institutions'.
Good Job!!!

**Pull request merged**
