### PR TITLE
Update Civic Tech Jobs (Sabrina Heasley)

### LINKED ISSUE #5384: Update Project Profile: Civic Tech Jobs (add Sabrina Heasley)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] Add a new entry for Sabrina Heasley:
```
  - name: Sabrina Heasley
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05GDBDPEDR
      github: https://github.com/sabheasley
    picture: https://avatars.githubusercontent.com/sabheasley
```
 - [x] Place Sabrina's profile after any other Product Manager's profile
 - [x] Confirm on your local that links for the member appear to be correct (i.e. for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by kezzaam**
Fixes #5384

### What changes did you make?
  - Added the following to leadership in civic-tech-jobs.md
  - name: Sabrina Heasley
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U05GDBDPEDR
      github: https://github.com/sabheasley
    picture: https://avatars.githubusercontent.com/sabheasley
- placed the entry after any product manager as specified
 

### Why did you make the changes (we will use this info to test)?
  - To update the Current Civic Tech Jobs Project Team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]Screenshot 2023-09-12 at 4 41 58 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image]Screenshot 2023-09-12 at 4 45 51 PM

</details>

### CODE REVIEW

**Review by allison-truhlar — APPROVED** [review]
Hi @kezzaam! Great work with this pull request. The pull request is being made from and into the correct branches, and you've included a correctly formatted issue and descriptions of what you did, why, and resulting visual changes in your post describing the pull request. Your changes to the code are clean, only adding what was requested, and I'm seeing the correct visual changes in my local environment. The only minor change I can suggest is cleaning up the ![image] from in front of your  tags in the before and after visual changes. Excellent job!

**Comment by kezzaam** [comment]
>

**Comment by kezzaam** [comment]
@allison-truhlar Thanks very much for the kind review and your suggestion with the ![image] tags, I will make sure to clean them up on my next issue!

**Comment by kezzaam** [comment]
NB I accidentally closed the issue by hitting the wrong button... I think it's open and where it is meant to be again. Sorry!

**Comment by mademarc** [comment]
Review ETA: 9/14/2023
Availability: 7:02PM

**Review by mademarc — APPROVED** [review]
Hey @kezzaam  i like how you added the lines 21-26 on the md file so good job on this.

**Review by t-will-gillis — APPROVED** [review]
Hey @kezzaam Great job! Your branches are correct, you are linked back to the original issue, your are explaining what you did and why, and you are including before and after screenshots. (FYI for the future when you explain what you did, it will be fine to give a short note e.g. "Added Sabrina Heasley to leadership in civic-tech-jobs.md"- but it's all good here) Also, your code is clean and you have only changed what needed to be changed.

Great job again and thanks for working on this issue

**Pull request merged**
