### PR TITLE
Edit credit for Design image for redesigned homepage

### LINKED ISSUE #3294: Edit credit for Design image for redesigned homepage
### Overview
We need to edit a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Design credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be merged into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] For `_data/internal/credits/ui-ux.yml`,
  - [x] Change the file name from `ui-ux.yml` to `design2.yml`
  - [x] Change `title: UI/UX` to `title: Design`
  - [x] Change `title-link: https://thenounproject.com/eucalyp/collection/digital-transformation-line/?i=3160558` to `title-link: https://thenounproject.com/search/?q=design&i=3160558`
  - [x] Change `content: icon` to `content-type: image`
  - [x] Change `used-in: Home` to `used-in: Homepage`
  - [x] Change `alt: 'UI/UX Icon'` to `alt: ''`
  - [x] Remove `type: icon`
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by clayton1111**
Fixes #3294 
### What changes did you make and why did you make them ?

  -Change the file name from ui-ux.yml to design2.yml
  -Change title: to Design
  -Change title-link: to https://thenounproject.com/search/?q=design&i=3160558
  -Change content: icon to content-type: image
  -Change used-in: to Homepage
  -Change alt: to ''
  -Remove type: icon

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No screenshot

### CODE REVIEW

**Comment by tunglinn** [comment]
ETA: 6/30/2022
Availability: 4 hours

**Review by tunglinn — APPROVED** [review]
Merges into the right branch. All changes are accounted for. Site does not break. Looks good and good job!

**Comment by Wny-Duong** [comment]
ETA: 7/1/2022
Availability: 2 hours

**Review by Wny-Duong — APPROVED** [review]
Changes look good and the action items specified are done. I was kind of curious why the new Design credit isn't showing on the site when I pull up the build, but that might just be because of design.yml still existing. That stuff is out of scope for the issue, I think. So you should be good. Keep up the great work!

**Pull request merged**
