### PR TITLE
Update Civic Tech Jobs Profiles (#5387)

### LINKED ISSUE #5387: Update Project Profile: Civic Tech Jobs (add Leah Ellis)
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We want the information presented on our website to be accurate and up-to-date. The Civic Tech Jobs project page needs to be updated to reflect recent changes in the team.
### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/civic-tech-jobs.md` file and find the `leadership` variable.
 - [x] Add a new entry for Leah Ellis:
```
  - name: Leah Ellis
    role: UX Researcher
    links:
      slack: https://hackforla.slack.com/team/U04GYTXSP9D
      github: https://github.com/Leah0996
    picture: https://avatars.githubusercontent.com/Leah0996
```
 - [x] Place Leah's profile with the other Researcher profiles
 - [x] Confirm on your local that links for the member appear to be correct (for the correct person) and are functioning
 - [x] Confirm on your local repo and provide before and after screenshots showing that the changes have been made on the Civic Tech Jobs project page and that no unexpected changes have occurred.
### Resources/Instructions
  - [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) project page
  - [civic-tech-jobs.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md)  
  - This issue was initiated by #5252

### PR DESCRIPTION
**Pull request by JCameren**
Fixes #5387 

### What changes did you make?
  - added Leah Ellis's social links to the markdown file under `_projects/civic-tech-jobs.md` under leadership
  
### Why did you make the changes (we will use this info to test)?
  - This will render their information on the website along with the rest of the leadership

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

issue-5387ss-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
issue-5387ss-after

</details>

### CODE REVIEW

**Comment by njackman-2344** [comment]
Reviewing this PR

Availability: Sunday 5pm-9pm PST, Thursday 5pm-10pm PST

ETA: Thursday Night PST

**Comment by kezzaam** [comment]
Review ETA: 7 PM 11/09/23
Availability: 1 - 7 PM Monday

**Review by kezzaam — DISMISSED** [review]
Hi @JCameren!

I have reviewed this issue and can confirm that the changes you have made are applicable, do not break anything and are also clean. Well done and happy coding!

**Review by njackman-2344 — DISMISSED** [review]
Follows pr template with for issue #5387 with screenshots before and after. 

Clean code. Great Job @JCameren

**Review by t-will-gillis — DISMISSED** [review]
Hey @JCameren Great job on your first issue! Your branches are correct, you are linked to original issue, you are briefly describing what you did and why, and you are providing appropriate before and after screenshots. Your code looks clean, in that you only made the changes you needed to make. 

It looks like you have a merge conflict because changes have been made to this file since you submitted your PR. FYI- Normally you will need to resolve merge conflicts on your own PRs. However, since there are additional PRs coming through that will continue to change this same file, I will resolve this conflict. 

Thanks for your contribution!

**Review by t-will-gillis — APPROVED** [review]
Merge conflict resolved

**Pull request merged**
