### PR TITLE
Resolve homepage color

### LINKED ISSUE #700: Resolve the incorrect background on the HfLA home page
### Overview
The homepage coloring & layout is not correct. We need to update the page so that it reflects its original design and what exists in the Figma. 

### Action Items

Development 
- [ ] Identify the bug or error that is causing the issue with the homepage background 
- [ ] Update the background on the homepage and compare with Figma 
- [ ] Review with product 

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
[Figma Homepage](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)

### Images 

What the page looks like now: 
Screen Shot 2020-08-23 at 2 59 22 PM

What the page is supposed to look like: 
Screen Shot 2020-08-23 at 2 58 01 PM

### PR DESCRIPTION
**Pull request by sena-ji**
Fixes #700

### CODE REVIEW

**Comment by KianBadie** [comment]
@sena-ji Will remove inline stylings and implement different fix for changing background.

**Review by KianBadie — CHANGES_REQUESTED** [review]
Awaiting changes to remove inline styling and implement solution using a different route. Any update on this @sena-ji? Feel free to reach out for any assistance.

**Review by drubgrubby — APPROVED** [review]
Really good work @sena-ji !  This issue was more complicated than it at first appeared but you seem to have tracked down the correct strategic places to add the background color back in so you could remove it from the full site.

**Comment by sena-ji** [comment]
Fixed the background color for the homepage:
image

After the body color class was deleted, fixed the parts of the toolkit pages that needed the color added again:
image
image
image

**Comment by drubgrubby** [comment]
Just to clarify, the changes made to this issue addressed Kian's requested changes.

**Pull request merged**
