### PR TITLE
fix: resolve CodeQL alert

### LINKED ISSUE #6480: Resolve CodeQL alert 45
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers. we need to analyze [CodeQL query alert 45](https://github.com/hackforla/website/security/code-scanning/45) and either recommend dismissal of the alert or update the code to resolve the alert.    

### Action Items
- [x] DO NOT DISMISS ANY ALERTS.  Dismissal of alerts should be done by dev leads only after review of the recommendation
- [x] Browse to the link in the next Action Item and read the contents.  Click "See More" to view Recommendations, Examples and References.  
- [x] https://github.com/hackforla/website/security/code-scanning/45
- [x] Note that the same problem may exist in several locations within a code file.  Only update the section of code indicated in the alert detail page.  
- [x] Note these resources: 
   - [x] See the wiki page "How to manage CodeQL alerts" (see under Resources)
   - [x] To look at the resolution of similar alerts, visit the [code scanning page](https://github.com/hackforla/website/security/code-scanning) and query closed alerts for similar alert type.  To see the resolution of a closed alert, view the alert details and open the tracking issue (outlined in red in the screenshot under Resources)
- [x] In a comment in this issue, provide your recommendation.  The recommendation can be one of the following: `dismiss as test`, `dismiss as false positive`, `dismiss as won't fix`, or `update code`.  An example of a 'false positive' is a report of a JavaScript syntax error that is caused by markdown or liquid symbols such as `---` or `{%`.  
- [x] If the recommendation is to update code:
   - [x] create an issue branch and proceed with the code update
   - [x] Use docker to test locally, ensuring that there are no changes to any affected webpage(s)
   - [x] proceed with pull request in the usual manner 
- [x] If the recommendation is to dismiss, describe your reason for dismissal in the comment, then move the issue to `Questions/In Review` and apply the label `ready for dev lead`.  

### For merge team/dev lead
- [ ] If recommendation to dismiss is approved, dismiss the alert with a comment, then close the issue as completed.
- [ ] When this issue is closed please check off the dependency (under "Issues") in #5159.  If all issues are closed, close #5159 as completed.  
  
### Resources/Instructions
<details><summary>Screenshot of CodeQL alert detail page with tracking issue outlined in red</summary>

CodeQLAlert

</details> 

- [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
- [code scanning page](https://github.com/hackforla/website/security/code-scanning)
- Wiki page "How to resolve CodeQL alerts" (if this page has not been published yet, see the draft at https://github.com/hackforla/website/issues/6463#issuecomment-2002573270)
- This issue is part of #5159

### PR DESCRIPTION
**Pull request by anthonypz**
Fixes #6480

### What changes did you make?
  - I added the `const` keyword to the `logins` variable

### Why did you make the changes (we will use this info to test)?
  - To resolve the missing variable declaration CodeQL alert
  - Also, I used `const` keyword instead of `let` so that the reference to the array cannot be reassigned to point to a different array, while still allowing the contents of the `logins` array to be modified.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

N/A

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
N/A

</details>

### CODE REVIEW

**Comment by w1ld-r** [comment]
Review ETA: Wednesday, March 27th 7pm CT

**Review by w1ld-r — APPROVED** [review]
Hi @anthonypz — great work on this issue!

* You linked the issue correctly in your PR description
* Your branch is correct
* You clearly described the changes and stated the reasons for making them
* I did not test the site on the frontend since no changes were made there
* This might be overkill given `const` was the only thing added to the `login` array in `add-label.js`, but I managed to run the `schedule-fri-0700.yml` workflow, which uses `add-label.js`, and it completed successfully.

One Note: Instead of changing the "Visual Changes Before/After" drop downs to N/A, you can remove them entirely and just leave a note like "No visible changes made to the website." Not a big deal, but that's what the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests) file says to do. 

Nicely done -- Approved! 👍

**Comment by anthonypz** [comment]
Thanks @gaylem, I appreciate the feedback!

**Review by roslynwythe — APPROVED** [review]
Great job @anthonypz 
- Your code change was clean and correct
- Your PR is well formed with correct branches and link to your issue
- You described your work

It was tested in the fork of my repository.  Approved!

**Pull request merged**
