### PR TITLE
Delete donate.yml file since not needed anymore

### LINKED ISSUE #4578: Remove credit for unused solidarity svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Currently, the website credits have an item for the solidarity-pana.svg in [donate.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/donate.yml), however this image is no longer used anywhere in the site. We need to remove the credit so that we don't have a credit for a file that is not actually used.

### Action Items
- [x] In your local IDE, navigate to `_data/internal/credits`
- [x] Delete `donate.yml`
- [x] Using Docker, check that the Credits page remains the same in mobile, tablet, and desktop views as on the current website 

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4531
- [Credits page](https://www.hackforla.org/credits/)

### PR DESCRIPTION
**Pull request by jenny-alexander**
Fixes #4578

### What changes did you make and why did you make them ?

  - Deleted donate.yml file from _data/internal/credits
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Delete file. No visual changes to the website.

### CODE REVIEW

**Comment by steven-positive-tran** [comment]
Avail: Tue, Thurs 7pm-12
ETA: Tue 11pm

**Review by steven-positive-tran — CHANGES_REQUESTED** [review]
Hey thanks for taking up this issue

1.  Do check off the task list in the action items to help indicate what has been done for the issue.

Other than that it works on my machine with both phone, tablet and pc configuation, Thanks for taking up this issue.

**Comment by jenny-alexander** [comment]
@steven-positive-tran 
Thank you for your feedback! I checked off the tasks on the issue as you requested. I'll ask for another review from you.

**Comment by blulady** [comment]
@se7en-illa & @mademarc if you guys could throw your eta/availability on this PR so we know when to expect it?

**Comment by se7en-illa** [comment]
Avail: M-F 12-8pm EST
ETA: EOD 5/11

**Comment by mademarc** [comment]
Review ETA:  4/11/2023
Availability: 7:15PM

**Review by mademarc — COMMENTED** [review]
Hey @jenny-alexander  Well done in making the changes by deleting the file also @se7en-illa   jump on this when you can that said thanks @blulady once again for the reminder on this matter

**Review by steven-positive-tran — APPROVED** [review]
Thanks for doing that.

**Review by t-will-gillis — APPROVED** [review]
Hey @jenny-alexander - Great job! Your branches are correct, you are linked back to your issue, and you addressed the issue. My only comment for next time is that on your description, you could say why you made the changes also, eg. "Deleted donate.yml file from _data/internal/credits because this file is no longer used." Thanks for your work!

**Pull request merged**
