### PR TITLE
Refactor Img Tag in About Page's News Card

### LINKED ISSUE #5199: img Tag Refactor: _includes/about-page/about-card-news.html - item[1].image
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-news.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="{{item[1].image}}" alt="{{item[1].image_alt}}" />
```
to
```
<img src="{{item[1].image}}" alt="{{item[1].image_alt}}">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5040

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-news.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), and #5040

### PR DESCRIPTION
**Pull request by Jmmcclo2023**
Fixes #5199

### What changes did you make?
  - Removed ending slash from img HTML tag
  - Removed ending whitespace from img HTML tag

### Why did you make the changes (we will use this info to test)?
  - To ensure that codebase is consistent with how we use img HTML tags

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Removing slash and whitespace from an img HTML tag to ensure consistency. No visual changes to the website.

### CODE REVIEW

**Comment by allison-truhlar** [comment]
Review ETA: 5 PM ET 8/22/23
Availability: 9-5 ET M-F

**Review by allison-truhlar — CHANGES_REQUESTED** [review]
Good job with this pull request Jalen! The changes you made in the code are exactly as requested in the issue and they are clean - only the ending slash was removed from the one img tag and nothing else was added. The pull request itself contains the correct branches: the commit is into "hackforla:gh-pages" and it originates from your branch. In addition, the pull request contains a properly formatted linked issue.

To increase the clarity of the pull request, please make these two changes:

- For "why did you make the changes," I would recommend changing your response to match the reason provided for the changes in the original issue. Specifically, "so that the codebase is consistent with how we use img HTML tags."

- Since the removal of the slash in the closing tag makes no visible changes in the browser, please remove the before and after screenshots and instead explain why there were no visual changes. See the contributing guide for details: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available

Thank you! Please let me know if you have any questions!

**Comment by Jmmcclo2023** [comment]
Hi @allison-truhlar, 
Thank you for reviewing the request! In order to make the changes required, would it be best to edit the request in the area above or recreate the pull request entirely and just resubmit it? 
Also, for questions like this, would the best method of communication be adding comments like this or is there a better method?

Thank you for the help, 
Jalen

**Comment by allison-truhlar** [comment]
Hi @Jmmcclo2023 ! I have to admit this is my first pull request review, but based on others I've looked at, I think the path forward is for you to edit the original comment you made and then to leave a new comment here that says you made the changes. Then I'll go back in and approve the pull request. Also, I think you did the right thing by commenting here with your question!

**Comment by DorianDeptuch** [comment]
Availability: Weekday Evenings
ETA: 8/22 EOD

**Review by DorianDeptuch — APPROVED** [review]
Hi @Jmmcclo2023,

You correctly stated the issue to be fixed, what changes were made, and why you made the changes. The ending slash was removed and everything runs well in my local environment. Great job!

**Review by allison-truhlar — APPROVED** [review]
@Jmmcclo2023, thank you for making the requested changes to the opening comment in the pull request! You now have a clear, concise statement for why you made the changes, and a statement that there are no visual changes to the website. Great job on your first issue!

**Comment by MattChau01** [comment]
Availability: In the evening & most of the day on weekends
ETA: Expected to finish review by EOD Friday

**Comment by LRenDO** [comment]
Hi @mademarc! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability. Thanks!

**Comment by mademarc** [comment]
Review ETA: 8/24/2023
Availability: 7:07PM

**Review by mademarc — APPROVED** [review]
Hey @Jmmcclo2023 good job on the html file changes and @LRenDO  the  ETA and Availability is done.

**Review by MattChau01 — APPROVED** [review]
- The new branch is properly going into the correct branch `gh-pages`. ✅ 
- Original issue #5199 was properly linked and referenced. ✅ 
- The specified instance of an `` tag on line 8 was properly adjusted to match the consistency of code. ✅ 

Looks good @Jmmcclo2023 !

**Review by adrianang — APPROVED** [review]
Hi @Jmmcclo2023 — everything looks good to me! The branching and the linked issue is set up correctly, and the requested change of removing the ending slash on the image tag in line 8 was made and doesn't affect the News portion of the About page when I check my local environment.

I appreciate you taking the time to edit the write-up of your PR in a timely manner at the reviewer's request and for being communicative with them; I think the new version of your PR is quite clear and documents your changes nicely. Good job!

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
