### PR TITLE
Update group.yml

### LINKED ISSUE #2833: Edit content field and remove type field from group.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/group.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/group.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L4
https://github.com/hackforla/website/blob/2443b6c47df54ca678a432035beb93f1e2e3b94e/_data/internal/credits/group.yml#L11

### PR DESCRIPTION
**Pull request by JijiTheCreator**
add -type and image on line 4 and remove line 11.

Fixes #2833 

### What changes did you make and why did you make them ?

  - edit line 4 with more complete, less redundant information
  - eliminate line 11 to eliminate redundancy
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by vanessavun** [comment]
Review ETA: 02/13/2023, Monday by 5pm.
Availability: 11am Mon-Fri

**Comment by Jaretzbalba** [comment]
Review ETA: EOD 2/13
Availability: 1 hr

**Review by Jaretzbalba — CHANGES_REQUESTED** [review]
@JijiTheCreator I see that the content type has been updated to content-type and the type field removed as requested in the issue. My only request is that the extra space on line 11 is deleted completely to keep the code clean and consistent. Otherwise, everything looks good and great job on this first issue!

**Review by vanessavun — COMMENTED** [review]
@JijiTheCreator Nice job in submitting this pull request. The commit is into the right repo and it's coming from your matching username and your branch. You also followed directions in changing it from `content: icon` to `content-type: image`. I checked the website locally and it didn't break anything. I also agree with the other review by @Jaretzbalba that to remain consistent with other files, remove the extra space. Once you have this fixed, it'll be good to go.

**Comment by mademarc** [comment]
Review ETA: 8 PM 2/23/23
Availability: 1 Hr.

**Review by mademarc — COMMENTED** [review]
The code is readable and done well @JijiTheCreator

**Comment by vanessavun** [comment]
> @JijiTheCreator I see that the content type has been updated to content-type and the type field removed as requested in the issue. My only request is that the extra space on line 11 is deleted completely to keep the code clean and consistent. Otherwise, everything looks good and great job on this first issue!

@JijiTheCreator reminder to remove the extra space on line 11 so this can be completed.

**Comment by jdingeman** [comment]
Closing this pull request without merging due to PR creator's time constraints.

**Pull request closed without merging**
