### PR TITLE
Update img business.png #4380

### LINKED ISSUE #4380: img Tag Refactor: Getting Started page - `step-img business.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img" src="./assets/images/getting-started/business.png" alt="" />
```
to
```
<img class="step-img" src="./assets/images/getting-started/business.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by one2code**
Fixes #4380 

### What changes did you make and why did you make them ?
Removed the '/' from the step-img business.png img tag

### Screenshots of Proposed Changes Of The Website  

Screenshots N/A for this update. All changes are reflected in the codebase only. Images display 1:1 in Docker with the updated code vs the old code on the live website.

### CODE REVIEW

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @one2code we have created separate issues for removing the '/' from the other img tags and it would create some confusion and unnecessary merge conflicts if your PR fixed all of those.  We really appreciate your initiative but for this good first issue it would be best to push another file with only the requested change.

**Comment by one2code** [comment]
I reviewed the requested changes and performed the necessary updates to make this PR compliant with the request. The new update is currently passing all checks.

**Review by roslynwythe — APPROVED** [review]
Awesome job @one2code on your first good issue.  Your PR is well-formed with correct branches,  correct code change, and a good description of your work.  Thank you also for being professional and responsive to requests for changes.

**Comment by mjshelton12** [comment]
ETA: Today (4/16) by 3pm PST
Availability: Today (4/16) 2pm-6pm

**Review by mjshelton12 — APPROVED** [review]
Great work, one2code!

You did an excellent job on this. The issue is properly linked, you clearly expressed what you did in the code, and your code is clean. Your changes are effective and your activity in this PR is admirable.

For this PR, I think your explanations of what you did were sufficient. Moving forward, you may want to spend a little more time on the "why" of why you did your changes to help reviewers understand why a change was made. In this issue, it's clear enough, but as you move on to bigger issues with more changes to code, it can help reviewers quickly understand your work.

Excellent job! Looking forward to seeing all that you do with HfLA!

**Pull request merged**
