### PR TITLE
Update project profile: HFLA website (remove Chris Menke)

### LINKED ISSUE #5153: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [ ] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [ ] Delete the following lines from the file:
```
  - name: Chris Menke
    role: Merge Team
    links:
      slack: https://hackforla.slack.com/team/U04KVG05H3J
      github: https://github.com/chrismenke45
    picture: https://avatars.githubusercontent.com/chrismenke45
```
- [ ] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by antho-zng**
Fixes #5153

### What changes did you make?
  - Remove entry for Chris Menke on _projects/website.md

### Why did you make the changes (we will use this info to test)?
  - Keep project information up-to-date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2023-08-31 at 15 40 37

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-08-31 at 15 27 18

</details>

### CODE REVIEW

**Comment by ortegaa32** [comment]
Review ETA: 3 PM 9/1/23
Availability: 1-3 PM everyday

**Comment by meru-a** [comment]
Availability: In the evening & on weekends
Review ETA: EOD 09/01

**Comment by ortegaa32** [comment]
- Pull request contains correct branch
- Pull request links to correct issue
- Changes accurately reflected in before and after screenshots
- Website doesn't appear to break
- Changes are in the right file and source code looks good
Good job @lateral-neck-stretch!

**Review by ortegaa32 — APPROVED** [review]

**Comment by pearlescence-m** [comment]
Hi @lateral-neck-stretch! Great work on your pull request - approving it!
- The new branch is properly going into the correct branch gh-pages. ✅
- Original issue was properly linked and referenced. ✅
- Pull request description is clear and correct. ✅
- The specified person is removed from the website is not broken. ✅

**Review by meru-a — APPROVED** [review]
Hi @lateral-neck-stretch! Great work on your pull request - approving it!
- The new branch is properly going into the correct branch gh-pages. ✅
- Original issue was properly linked and referenced. ✅
- Pull request description is clear and correct. ✅
- The specified person is removed from the website is not broken. ✅

**Review by adrianang — APPROVED** [review]
Hi @lateral-neck-stretch — the branching is set up correctly, the corresponding issue is linked, the requested change of removing the previous merge team member's card was made correctly by deleting lines 39 through 44, and doing so didn't seem to affect any other part of the Website project page aside from the expected deletion.

Your PR was done well: the What succinctly describes the change made, the Why explains why the change was made, and I appreciate you correctly adding the screenshots to show the visual change!

Thank you for taking the time to complete this time-sensitive issue; good job! 🙌🏼

**Pull request merged**
