### PR TITLE
Removed api-actionnetwork.js script in default template

### LINKED ISSUE #7092: Remove api-actionnetwork.js script from default template
### Overview
We need to remove the script reference to api-actionnetwork.js from our default template, because the script is no longer required.  

### Action Items
- [x] Open `_layouts/default.html` in your IDE
- [x] Remove the script tag that references `assets/js/api-actionnetwork.js`
- [x] Using Docker, view a sample page (for example `/events`) and confirm that it is unchanged from the production webpage.  

Merge Team:
- [x] When this issue is complete, see the Dependencies section of #6677. If issue #7091  is also complete,  remove the `Dependency` label on #6677 and "Close issue not planned".   

### Resources/Instructions
[Liquid templating language](https://shopify.github.io/liquid/)

### PR DESCRIPTION
**Pull request by maadeshsivakumar**
Fixes #7092

### What changes did you make?
  
  - Removed the script tag that references assets/js/api-actionnetwork.js from default template

### Why did you make the changes (we will use this info to test)?
  
  - The script is no longer required.

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)

  - No visual changes to the website

### CODE REVIEW

**Review by handshek — APPROVED** [review]
Hey @maadeshsivakumar Great work!

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a clear and concise description of what was done and why
- No visual changes are made to the website

**For future reference:** 
- The current branch name is slightly vague and I think something like `remove-actionnetowrkjs-script-7092` would be more appropriate. Apart from that everything looks right.

Thanks for woking on this issue!

**Comment by jphamtv** [comment]
Hey @ramitaarora - Could you please provide your estimated time for review and your availability? Thanks!

**Comment by ramitaarora** [comment]
Availability: Weekday mornings
ETA: Aug 30 EOD

**Comment by vorleakyek** [comment]
Review ETA: 8/30 
Availability: M-F evening

**Review by ramitaarora — APPROVED** [review]
This looks great!
- The pull request is linked and made from the correct branch
- The script tag is no longer in the _layouts/default.html file 

Thank you for your contribution! :)

**Review by vorleakyek — APPROVED** [review]
It looks fine. Thanks for contributing!

**Pull request merged**
