### PR TITLE
Create dependabot file 3843

### LINKED ISSUE #3843: Create dependabot.yml file for dependabot to create pull requests
### Overview

GH Dependabot has been enabled to issue alerts for vulnerabilities and security. Therefore we need a configuration file, dependabot.yml, to create pull requests so that we maintain up to date security in our repo.

### Action Items

- [x] Read [configure dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [x] Read #3598 to understand HfLA's decision for implementing dependabot
  - [x] See associated [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- [x] Create a dependabot.yml file in the [.github](https://github.com/hackforla/website/tree/gh-pages/.github) and configure the file as per the instructions given in 1st link

### Resources/Instructions

- [Enabling Dependabot Version Updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [Configuration Options for Dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- ER for Decision Record: https://github.com/hackforla/website/issues/3598
- [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- See previous work done here: #4102

### PR DESCRIPTION
**Pull request by kurikurichan**
Fixes #3843

### What changes did you make and why did you make them ?

  - I created a dependencies.yml file, following the instructions for Github Actions that GH provided
  - I added instructions for NPM, Docker, & GH Actions
  - I have not tested this, it needs to be tested with an outdated dependency 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Note: There was no dependabot.yml file

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screen Shot 2023-03-01 at 11 42 28 AM

image

</details>

### CODE REVIEW

**Comment by kurikurichan** [comment]
After making this pull request, I made 1 more change to this branch (a critical change, it was in the wrong file location which was causing its deployment to fail). I'm not sure if this pull request reflects that.

It should be in .github and not .github/workflows

**Comment by d-perez-8** [comment]
Availability: 3-6pm
ETA: 3/2/2023

**Comment by d-perez-8** [comment]
Hi @kurikurichan, thank you for doing this issue. Just had a question to better understand this issue. How did you know to add npm, docker, and github-actions to the package-ecosystems?

**Comment by roslynwythe** [comment]
@kurikurichan Thank you for working on this issue.  The file changed by this PR is at .github/workflows/dependabot.yml, and from your comment above it sounds like that is not the correct path.  In that case, please push another commit, after staging and committing the file deletion and addition.  

Also please edit the PR to remove the "Visuals before" and "Visuals after" sections.    If there are no visual changes to the website, we advise to delete the details and summary tags and replace them with an explanation for no images like:

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website

**Comment by kurikurichan** [comment]
> 

Hi Daniel, if there are more package ecosystems, please let me know. The documentation says to at least do github actions, and I noticed that we have package.json and docker files, so I added those too.

**Pull request closed without merging**
