### PR TITLE
Create component and refactor text on Donate page

### LINKED ISSUE #4457: Create Component and Refactor HTML for "In-Kind" text on Donate page
### Dependency

- [x] #3983

### Overview

As developers we need to componentize donation elements which appear on multiple pages in the site, in order to present a consistent appearance and efficiently reuse code.  In this issue, the text on the Donate page below "Provide In-Kind Software & Services" will be componentized.  

### Details

- Please refer to the screenshot under Resources.  The paragraphs depicted in the screenshot appear beneath the header "Provide In-Kind Software & Services" on the Donate page, and the HTML is contained in `_includes/donate-card.html`.   
- To create a reusable component, the paragraphs below the heading (but not the heading) will be moved to a new component 

### Action Items

- [x] Open the current file `_includes/donate-card.html`.  Create a new component file `_includes/donation/in-kind.html` then remove the appropriate `<p>` elements from the current file and add them to the new file.  Note that the heading "Provide In-Kind Software & Services" will not be moved into the new component; instead it should be retained in the existing files.  
- [x] Update `_includes/donate-card.html` to reference the new component file using the liquid `{% include <filename> %}` syntax.  Note that 'filename' is relative to the `_includes` folder.  

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up".

### Resources/Instructions

<details>
 <summary>Screenshot of the new component elements</summary>

image

</details>

- HfLA Donate Page: [webpage](https://hackforla.org/donate) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html)
- [Donate Card - Donate Page version](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)

### PR DESCRIPTION
**Pull request by pdimaano**
Fixes #4457

### What changes did you make and why did you make them ?

  - Created new file and moved paragraph elements from _includes/donate-card.html to _includes/donation/in-kind.html
  - Updated original file to reference new component file

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM- 3PM
ETA- 5/12/23

**Review by Thinking-Panda — APPROVED** [review]
Good work @pdimaano ! Merge branches are perfect, code changes are appropriate, works perfect on local machine and thank you for deleting the trailing spaces.

**Review by Mayank2808sharma — APPROVED** [review]
LGTM

**Comment by Mayank2808sharma** [comment]
Availability: M-F (12 PM- 9PM)IST
ETA- 5/14/23

**Review by t-will-gillis — APPROVED** [review]
Hi @pdimaano - Great job! Your branches are correct, you are linking back to your issue, your description is clear and to the point, and you made clean changes to the code. Everything appears to be loading correctly on Docker in all sizes. Thanks!

**Pull request merged**
