### PR TITLE
Add Section & Link to CONTRIBUTING.MD

### LINKED ISSUE #4352: Add link to CONTRIBUTING.md for VS Code's documentation on Merge Conflicts
### Overview
Merge conflicts are an issue that many developers will face for various reasons. We want to update the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) with a link to VS Code's [documentation on Merge Conflicts](https://code.visualstudio.com/docs/sourcecontrol/overview#_merge-conflicts) so that developers are prepared to deal with merge conflicts.

### Action Items
- [x] Navigate to CONTRIBUTING.md
- [x] Add a new section under 3.1.c
  - [x] Name it "3.1.d Dealing with merge conflicts"
  - [x] Add a link to VS Code's [documentation on Merge Conflicts](https://code.visualstudio.com/docs/sourcecontrol/overview#_merge-conflicts) with a small description
  - [x] Add the link to the section in the [table of contents](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#table-of-contents)
- [x] Check your changes in your remote repository to ensure the style is in line with the rest of the CONTRIBUTING.md

### Resources/Instructions
- Associated ER for this issue: https://github.com/hackforla/website/issues/4231
- [3.1.c Editing a submitted pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31c-editing-a-submitted-pull-request)

### PR DESCRIPTION
**Pull request by se7en-illa**
Fixes #4352 

### What changes did you make and why did you make them ?

  - Added section 3.1.d "Dealing with Merge Conflicts", including a short description of merge conflicts & link to VS Code's documentation
  - Gives contributors a resource in case they run into trouble with a PR 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals after changes are applied</summary>
  
image

image

</details>

### CODE REVIEW

**Comment by vanessavun** [comment]
Availability: weekday evenings
ETA: 04/17/2023

**Review by vanessavun — APPROVED** [review]
Everything looks good! The description and external link are working. You linked the associated issue, created the PR from your feature branch, explained why the change was made, and shared screenshots. Good job!

**Comment by steven-positive-tran** [comment]
ETA: EOD 4/17
Availability: 9pm -12am PST 4/17

**Review by steven-positive-tran — APPROVED** [review]
- [X] Pulled to the correct branch and pulled from your own fork.
- [X] Went to your branch in your fork and the contributrion.md works
- [X] Changes in code seems in line to what the issue is addressing,

Approved and thank you for contributing to hack for la.

**Comment by Adastros** [comment]
Availability (PST): 11 - 11:30 PM 17APR23
Review ETA (PST): 11:20PM 17APR23

**Review by Adastros — CHANGES_REQUESTED** [review]
Hi @se7en-illa, good job on completing the issue! The description is clear and the links are correct. 

Could you update the title of the pull request to remove references to issue #4352? This may cause some confusion when looking at the title since the pull request issue is positioned right next to it. 

Could you also add this pull request to the project board? Reference [this section](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board) in Contributing.md for more info.

**Comment by se7en-illa** [comment]
Thanks for the feedback all! Requested changes have been made.

**Review by Adastros — APPROVED** [review]
Hi @se7en-illa, thanks for implementing the changes! Everything looks good

**Pull request merged**
