### PR TITLE
Update Section2.7.b - making sure devs checkout gh-pages first

### LINKED ISSUE #5698: Update CONTRIBUTING.md Section2.7.b - making sure devs checkout gh-pages first
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In the instructions in  [CONTRIBUTING.md 2.7.b "Working on an issue (2): Create a new branch where you will work on your issue"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue), we need to ensure that the developer has checked out the `gh-pages` branch prior to proceeding to create the issue branch, and that after making files changes, the developers uses caution when using `git add` to prevent inclusion of unwanted files in the subsequent commit.  

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to "Working on an issue (2): Create a new branch where you will work on your issue"
- [x] Replace:
```
The `git checkout` command will create and change to a new branch where you will do the work on your issue.  In git, the checkout command lets you navigate between different branches.  Using the `-b` flag you can create a new branch and immediately switch into it. 

For example,if we creating a new issue branch off [Update ‘Give’ image credit link and information - #2093](https://github.com/hackforla/website/issues/2093):
```
with
```
If you have not already done so, run `git checkout gh-pages` to switch the working directory to the `gh-pages` branch and then update `gh-pages` with upstream changes as described above in Section 2.7.a. 

Using the `-b` flag you can also use the `git checkout` command to create a new branch and immediately switch into it.  

For example,if we creating a new issue branch for [Update ‘Give’ image credit link and information - #2093](https://github.com/hackforla/website/issues/2093):
```
- [x] Replace:
```
When you've finished working on your issue, follow the steps below to prepare your changes to push to your repository.
```
with
```
We urge developers to be cautious using `git add`.  In general it is not advisable to use `git add -all` or `git add .`.  Rather, run `git status`, examine the output carefully, and then add only those files specifically related to the current issue.  This will ensure that no extraneous files are included in the subsequent commit.  

When you've finished working on your issue, follow the steps below to prepare your changes to push to your repository.
```

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
 [CONTRIBUTING.md 2.7.b "Working on an issue (2): Create a new branch where you will work on your issue"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4559

### PR DESCRIPTION
**Pull request by jphamtv**
Fixes #5698

### What changes did you make?
  - Updated the `CONTRIBUTING.md` file

### Why did you make the changes (we will use this info to test)?
  - We need to ensure that the developer has checked out the `gh-pages` branch prior to proceeding to create the issue branch, and that after making files changes, the developers uses caution when using `git add` to prevent inclusion of unwanted files in the subsequent commit.

For Reviewers: Do not review changes locally, rather, review changes at: https://github.com/jphamtv/website/blob/update-contributing-guidelines-5698/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Updated CONTRIBUTING.md file. No visual changes to the website.

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  11/25/2023
Availability: 10am - 5pm

**Review by robertnjenga — APPROVED** [review]
Hi @jphamtv! Great job!
The branching was done correctly, you linked the issue, you gave a description of what you did and why the changes were made, i.e update CONTRIBUTING.md 2.7.b. You also provided the test URL, which confirms the updates. Thank you for taking up this issue.

**Comment by freaky4wrld** [comment]
ETA: EOD 11/27
Availability: Evenings

**Review by freaky4wrld — APPROVED** [review]
Hey there @jphamtv , all the changes mentioned in the linked issue are made and are looking perfect in your branch.  The merge is going in correct branch, I approve it..... great work there

**Comment by t-will-gillis** [comment]
Hey @jphamtv Thank you for working on this issue. I see that you adjusted the language on Line 554 - great work for noticing and then correcting this.

**Pull request merged**
