### PR TITLE
Rename "Update Team Members" action to "Schedule Thursday 1100"

### LINKED ISSUE #2221: GitHub Actions: Rename "Update Team Members" to "Schedule Thursday 1100"
### Overview
As a member of the backend team, github actions are much more maintainable and easier to understand if they are structured based on triggers and functionality. For this issue, we want to update [update-team-members.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-team-members.yml) and rename the action to 'Schedule Thursday 1100' so all scheduled actions that occur on 11am every Thursday can live in this file.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Rename the file from 'update-team-members.yml' to 'schedule-thu-1100.yml'
- [x] Rename the name of the action from 'Update Team Members' to 'Schedule Thursday 1100'
    - [x] The name of the job should still stay the same (line 11)
- [x] Update the location of the [accompanying js file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/contributors-data.js)
    - [x] If not created yet, create a new directory under /[github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)/ called trigger-schedule
    - [x] Create a subdirectory under /github-actions/trigger-schedule called trim-contributors
    - [x] Move the js file [contributor-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/contributors-data.js) under /github-actions/trigger-schedule/trim-contributors
    - [x] Update the github action's js requirement to reflect the change in directory
- [ ] If possible, do a test on your local environment and make sure it still works

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Accompanying JS](https://github.com/hackforla/website/tree/gh-pages/github-actions)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #2221 

### What changes did you make and why did you make them ?

  - Renamed `update-team-members.yml` to `schedule-thu-1100.yml`
  - Renamed the "Update Team Members" action to "Schedule Thursday 1100"
  - Created `/github-actions/trigger-schedule/trim-contributors`
  - Moved `/github-actions/github-data/contributors-data.js` to `/github-actions/trigger-schedule/trim-contributors/`
  - Updated `schedule-thu-1100.yml` to use the new `contributors-data.js` location
  - These changes organize the Update Team Members action according to the new structure outlined in the issue

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Only changed how GitHub actions are organized, so no visible changes to the site.

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Please make sure to double-check the new file paths when reviewing this PR because I couldn't find a good way to test this locally due to it being on the non-default branch. If all the paths are correct then there is no reason this shouldn't work, but if you think you know how to test this locally then please let me know so I can try. Thanks!

**Comment by lilyarj** [comment]
ETA: 7/13
Avalibility: 2hrs

**Comment by Zak234** [comment]
Lopks good but unsure how to test.

**Comment by lilyarj** [comment]
Looks great but I am also still unsure how to test it!

**Comment by tunglinn** [comment]
<details><summary>You can change the default branch through settings in your forked repo. </summary>

image
</details>

And then remember to revert it back to gh-pages once you're done with the review.

However, since this is a timed action, you'll either have to wait until Thursday 1100, or briefly change the code to a time closer to the present.

**Comment by Zak234** [comment]
Thanks!

**Comment by blulady** [comment]
Github actions sends an email to the "owner" of the repo when they complete.

**Comment by luke-karis** [comment]
ETA: 7/16
Availability Friday and Saturday 1 hour

**Review by Zak234 — APPROVED** [review]
From the testing in my repo it seems like it should work fine. I had to get somewhat creative with the testing though so other reviewers should definitely test in their repos to make sure things work the same way for them.

**Comment by luke-karis** [comment]
The changes look good to me but I'm having a little trouble testing this locally. I've set this as my default branch and have been messing with the chron expression and the if statements within the yml file but to no success. The closest I've come to anything happening is setting the chron expression to all * and having GitHub yell at me. @Zak234 would you mind sharing how you manage to get it to work locally?

**Comment by blulady** [comment]
Good Job!!

**Pull request merged**
