### PR TITLE
Expunge Assist: Update alt text for the Expunge Assist image to 'Expu…

### LINKED ISSUE #3998: Expunge Assist: Update alt text for Expunge Assist image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Expunge Assist` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/expunge-assist.md`:

**From:**
```
Image of a criminal record
```

**To:**
```
Expunge Assist
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/expunge-assist

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/expunge-assist.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md
- This issue is part of epic #3866 

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by louiewhitz**
Fixes #3998

### What changes did you make and why did you make them ?

  - Updated alt text for Expunge Assist to adhere to WCAG

### CODE REVIEW

**Comment by one2code** [comment]
**ETA:** 5/30/23

**Review by one2code — APPROVED** [review]
I've reviewed and verified that the correct changes have been made to the alt text for the image. The only suggestion I have, is to include more detail about the specific change being made in future pull requests. For example, "Changed alt text from 'Image of a criminal record' to 'Expunge Assist' to better adhere to  Web Content Accessibility Guidelines (WCAG) and HackForLA's mission of inclusivity." Understanding where changes were made, what changes were made, and why the changes were made, will make your future pull requests easier to review as the complexity increases, and reduce the likelihood of changes being requested.

Good job @louiewhitz on your first pull request!

**Comment by 93Belen** [comment]
Availability: Tuesday, Thursday and Sunday all day
ETA: Tuesday by 6pm

**Review by 93Belen — APPROVED** [review]
Hey good job!
You changed the correct line in the code, made the pull request from the correct branch, and linked the issue in your description. I agree with @one2code that I would personally be more specific in what I have changed when describing my PR, but you can do it in your next Pull Requests ☺️

**Review by chrismenke45 — APPROVED** [review]
Great work!

**Pull request merged**
