### PR TITLE
Fix spelling errors on guide pages and CONTRIBUTING.md

### LINKED ISSUE #3546: Find Linter and Matching VS Code Plugin to Spell Check Site
### Dependency
- #2401 

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained. For this issue, we will find a third party linter and VS Code plugin to spell check all text in pull requests that will appear on the website.

### Action Items

 - [x] Research various third party linters to find one we can use to check pull requests for spelling errors.
 - [x] Verify that the vendor also makes a matching VS Code plugin that our devs can use locally to check their spelling before pushing code. The linter and the plugin must come from the same source.
    - [x] If you do not find a matching set, bring to merge team/dev leads to discuss next best option and present to product.
 - [x] Test the linter/plugin combination in your own repository to be sure they work as expected.
- [x] Once we identify and apply the spell checker go through this [spreadsheet from design team](https://docs.google.com/spreadsheets/d/1qDD7n9XbogIJgDh6mcgdEJAH1x3FMoPnGYNt3pKhhUk/edit#gid=0)
  - [x] Checking off the spelling/grammar errors that have been fixed (don't worry if linter doesn't fix the grammatical errors, we will make a separate issue for another linter if it doesn't fix both)
  - [x] If all spelling errors are corrected then this issue is completed, make a pull request (Merge team may need to install the linter but to verify functionality locally it will be helpful to see the repo it worked in)

### Resources/Instructions
- [Spreadsheet from design team with all the misspellings they found](https://docs.google.com/spreadsheets/d/1qDD7n9XbogIJgDh6mcgdEJAH1x3FMoPnGYNt3pKhhUk/edit?usp=sharing)
- [VS Code Plugins for spelling](https://marketplace.visualstudio.com/search?term=spell&target=VSCode&category=All%20categories&sortBy=Relevance)
- [Web Based Chrome Extension checker](https://chrome.google.com/webstore/detail/spell-check/ofbiibdnnhllfldbglbhmiojndiepejl?u_producttype=chrome-extension-759435&u_country=us&funnel=esign&gclid=CjwKCAjwzt6LBhBeEiwAbPGOgWBYIwbWhghZ-uWgoMQS16y7t8pHC7kKXM0RQjeg27To0YlYVBisdRoCueMQAvD_BwE)
- [Web based external checker](https://www.icwebdesign.co.uk/how-to-spell-check-a-whole-website) - more sensitive than the chrome extension however will only check pages that are linked to main page (not about page, etc.)
- [Figma spell check plug in SPELL](https://www.figma.com/community/plugin/754026612866636376/SPELLL---Spell-Checking-for-Figma-%26-FigJam)
- [Figma spell check plug in Spellchecker](https://www.figma.com/community/plugin/738839069237725273/Spellchecker)
- [Bonnie's Query for spell checkers](https://github.com/marketplace?type=&verification=&query=spell)
   - When going through the query list make sure to check that the spell checker can work in VS Code as well as GitHub CI/CD

### PR DESCRIPTION
**Pull request by christinaor**
Fixes #3546 

### What changes did you make and why did you make them ?

  - Fixed spelling errors on 2 guide pages using Code Spell Checker VS Code extension and manual checking in CONTRIBUTING.md, both in issue #2401 .
  - Researched linters/VS Code extensions and used Code Spell Checker to fix all but one error - does not detect words with less than 4 characters.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

image

image
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

image

image

</details>

### CODE REVIEW

**Comment by vanessavun** [comment]
Availability: weekday evenings
ETA: 10PM 2/17

**Review by vanessavun — DISMISSED** [review]
Thanks for fixing the spelling errors and great work for doing all the requirements. Based on the Google spreadsheet mentioned in the issue (6 misspelled words), I do see the 6 fixed spellings in the 3 total files you edited. I also checked the website in the local environment and all fixes are reflected and there is nothing broken that I can find.

(I'm noticing that the "elipsis" in the image class is misspelled, but it is not part of the fix and it's probably for another issue since it's maybe for styling.)

**Review by t-will-gillis — APPROVED** [review]
Hi @christinaor - great job exploring this topic. I was able to install the Code Spell Checker for VS Code locally to test how it works. I did see that it identifies the misspelled words from the design team’s list so that these may be corrected. It appears that if we went this route we would need to add/ignore common terms like ‘WCAG’ and ‘hackforLA’, as well as terms such as ‘inclusivity’ since these are coming up alongside the misspellings. I also confirmed that the linter is available but I did not install/test that locally because: a.) we still don’t know if this is the spell checker we will ultimately use and b.) I did not want to run this on my machine. If HfLA decides the VS Code Spell Checker is the direction to go, I think at that time the linter can be checked again to confirm it does what we want it to. 

From my understanding, you satisfied the specific items listed in the topic including exploring the options and identifying a workable spell checker plugin/ linter, and you fixed the specific spelling errors from the design team’s list. You have also identified a Plan of Action with several further steps. 

Excellent job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hello again @christinaor -

There is an issue with your `CONTRIBUTING.md` that interestingly enough is not being flagged as a change in the 'Files Changed': The address on line 223 should be: https://github.com/hackforla/website/wiki/Add-local-user-accounts-to-the-docker-users-group-on-Windows-10 : Your copy says `...wiki/Adding-local-users...` and it should be `...wiki/Add-local-users...`

Would you please fix? Thanks!

**Comment by christinaor** [comment]
@t-will-gillis Thanks for catching that! Not sure why the link was different, but the PR has been updated with the correct link.

**Review by t-will-gillis — APPROVED** [review]
My apologies @christinaor - The reason that the link was different between your copy and the HFLA copy of `CONTRIBUTING.md` was b/c of a different PR (3995) submitted **after** you submitted your PR- it was not anything you did! 

Thanks for changing though!

**Pull request merged**
