### PR TITLE
Update Project Profile - Add Aditya Profile to guides-team.md

### LINKED ISSUE #7585: Update Project Profile: Guides Team Add Aditya Soni
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Aditya Soni
    github-handle: Aditya23soni
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U07F766J29M
      github: https://github.com/Aditya23soni
    picture: https://avatars.githubusercontent.com/Aditya23soni
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [ ] Once your pull request is merged, go to the initiating ER [^3]
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team
[^3]: initiating ER:  #7259

### PR DESCRIPTION
**Pull request by trimakichan**
Fixes #7585

### What changes did you make?
  
  - Added Aditya's profile to the guides-team.md file in the _projects folder.

### Why did you make the changes (we will use this info to test)?
  
  - To keep project information up to date so that visitors to the website can find accurate information.

<h3>CodeQL Alerts</h3>

After the PR has been submitted and the resulting GitHub actions/checks have been completed, developers should check the PR for CodeQL alert annotations.

<details><summary>Check the PR's comments. If present on your PR, the CodeQL alert looks similar as shown</summary>
  
Screenshot 2024-10-28 154514

</details>

Please let us know that you have checked for CodeQL alerts. **Please do not dismiss alerts.**
- [x] I have checked this PR for CodeQL alerts and none were found.
- [ ] I found CodeQL alert(s), and (select one):
   - [ ] I have resolved the CodeQL alert(s) as noted
   - [ ] I believe the CodeQL alert(s) is a false positive (Merge Team will evaluate)
   - [ ] I have followed the Instructions below, but I am still stuck (Merge Team will evaluate)

<details><summary>Instructions for resolving CodeQL alerts</summary>

If CodeQL alert/annotations appear, refer to [How to Resolve CodeQL alerts](https://github.com/hackforla/website/issues/6463#issuecomment-2002573270).  

In general, CodeQL alerts should be resolved prior to PR reviews and merging

</details>

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 

<details>
<summary>Visuals before changes are applied</summary>

update_project_profile_7585_before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

update_project_profile_7585_after

</details>

### CODE REVIEW

**Comment by terrencejihoonjung** [comment]
eta: Nov 5th, 2024 11:59pm PST
availability: everyday, 5pm - 9pm PST

**Comment by siyunfeng** [comment]
Review ETA: 11/4/2024 Monday
Availability: 6-9 PM Weekdays (EDT)

**Comment by siyunfeng** [comment]
Great job on your second good first issue, @trimakichan ! 

You have been improving since your first good first issue. 
- Availability and ETA are included in the original issue
- The Linked issue number is included
- The branch you work on is accurate
- The change you made is correct
- CodeQL alerts are checked
- Before-and-after screenshots are listed

Improvements: 
- Name the branch with more specific details, for example, `project name + add/remove + volunteer's name + linked issue number`
- Leave the checkboxes empty, you can check the corresponding checkbox after submitting the comment/PR

Keep it up and thank you for your contribution!

**Review by siyunfeng — DISMISSED** [review]
Great job on your second good first issue, @trimakichan !

You have been improving since your first good first issue.

- Availability and ETA are included in the original issue
- The Linked issue number is included
- The branch you work on is accurate
- The change you made is correct
- CodeQL alerts are checked
- Before-and-after screenshots are listed

Improvements:
- Name the branch with more specific details, for example, project name + add/remove + volunteer's name + linked issue number
- Leave the checkboxes empty, you can check the corresponding checkbox after submitting the comment/PR

Keep it up and thank you for your contribution!

**Comment by maadeshsivakumar** [comment]
Review ETA: 8 AM 11/3/2024
Availability: everyday, 5pm - 9pm EST

**Review by maadeshsivakumar — DISMISSED** [review]
Great job on the pull request, @trimakichan!

- Branches are set up correctly
- Correct issue is linked
- Reason for changes is clear
- Visual changes are clear

**Review by codyyjxn — DISMISSED** [review]
@trimakichan  Great Job on this issue! 
- You made the correct changes
- The description is very detailed and concise
- The issue is linked correctly

Keep it up!

**Review by terrencejihoonjung — DISMISSED** [review]
Hi @trimakichan,

Great job!
- changes made and why they were made are stated clearly
- branch naming is correct
- CodeQL check was done 
- visual changes were shown

Thanks for your contribution!

**Comment by t-will-gillis** [comment]
Hi @trimakichan Please resolve the merge conflict below. 

In case you have not seen this before:  An issue related to yours (#7584) was merged, so now you need to update your branch before your PR can be merged. It is pretty straightforward- you can do it manually by clicking "Resolve conflicts". Let us know if you have any questions. Thanks!

**Comment by trimakichan** [comment]
> Great job on your second good first issue, @trimakichan !
> 
> You have been improving since your first good first issue.
> 
> * Availability and ETA are included in the original issue
> * The Linked issue number is included
> * The branch you work on is accurate
> * The change you made is correct
> * CodeQL alerts are checked
> * Before-and-after screenshots are listed
> 
> Improvements:
> 
> * Name the branch with more specific details, for example, project name + add/remove + volunteer's name + linked issue number
> * Leave the checkboxes empty, you can check the corresponding checkbox after submitting the comment/PR
> 
> Keep it up and thank you for your contribution!

Thank you for reviewing my PR, @siyunfeng! Could you tell me which checkboxes you are referring to? Thanks!

**Comment by trimakichan** [comment]
> Hi @trimakichan Please resolve the merge conflict below.
> 
> In case you have not seen this before: An issue related to yours (#7584) was merged, so now you need to update your branch before your PR can be merged. It is pretty straightforward- you can do it manually by clicking "Resolve conflicts". Let us know if you have any questions. Thanks!

Thank you for letting me know, @t-will-gillis! I just resolved the conflict. Thanks!

**Comment by t-will-gillis** [comment]
Hey @trimakichan Thanks for resolving the merge conflict! 

@terrencejihoonjung @codyyjxn @maadeshsivakumar @siyunfeng Please do a final check and re-Approve now that the merge conflict is resolved. Thank you!

**Comment by siyunfeng** [comment]
> > Great job on your second good first issue, @trimakichan !
> > You have been improving since your first good first issue.
> > 
> > * Availability and ETA are included in the original issue
> > * The Linked issue number is included
> > * The branch you work on is accurate
> > * The change you made is correct
> > * CodeQL alerts are checked
> > * Before-and-after screenshots are listed
> > 
> > Improvements:
> > 
> > * Name the branch with more specific details, for example, project name + add/remove + volunteer's name + linked issue number
> > * Leave the checkboxes empty, you can check the corresponding checkbox after submitting the comment/PR
> > 
> > Keep it up and thank you for your contribution!
> 
> Thank you for reviewing my PR, @siyunfeng! Could you tell me which checkboxes you are referring to? Thanks!

You did well fixing it. 

It was the `I have checked this PR for CodeQL alerts and none were found.` checkbox.

**Review by siyunfeng — APPROVED** [review]
Thank you for working on this issue, @trimakichan !

You did well fixing what I mentioned and everything looks good.

**Review by codyyjxn — APPROVED** [review]
@trimakichan Thank you for taking on this issue. Great job on fixing the merge conflict.

**Pull request merged**
