### PR TITLE
Guides Pages Redesign - Updated (Retry)

### LINKED ISSUE #1630: Work flow for guides to appear on the website
### Dependency
- [x] Waiting for a PM to get assigned to Guides (ask Bonnie or Olivia for status if necessary)
- [x] ~Waiting until PMs have identified all guides that are ready (at least 5 are needed for this test)~

### Overview
As PMs we need guides to be easy and fast to add to the website so that we have our guides appear on the website as soon as possible.

### Action Items
- [x] Define the prototype
   - [x] Document what did not work 
- [ ] Define MVP
- [ ] Define stages post MVP
- [ ] Convert issue to epic with small issues: [Add credits for photos and icons for redesigned homepage #2528](https://github.com/hackforla/website/issues/2528)
- [ ] Once the pull request associated with this issue is approved and merged
  - [ ] Please update and edit issue #1515 by
    - [ ] Checking off the dependency for this issue
    - [ ] If all dependencies are checked off, please move issue #1515 to the New Issue Approval column and remove the Dependency label
  - [ ] Please update and edit issue #3170 by
    - [ ] Checking off the dependency for this issue
    - [ ] If all dependencies are checked off, please move issue #3170 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
Here is what we will post on the a guide issue when we assign an image to it
``` 
Here is the image that will show up when people go to hackforla.org/toolkit and see this guide
[INSERT IMAGE HERE]

Here are the details for the credits page
Name: Meetup (this needs to link to the original image location)
Used in: Toolkit
Artist: _______
Provider: _____
```
- [Guide: How to Write a Guide
](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit#)

- [Template: Guide](https://docs.google.com/document/d/1kV29V-mRPBNRRfIbYHrz05FElC02Dh6egaMANlxaZrM/edit)

- [How to Set Reminders in Slack v4
](https://docs.google.com/document/d/1YxwE3Edz7xXPVZ156wbIaPlQj7UUssIWN-ctTqbBilE/edit)

- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14989%3A95216)

- [Sample Documentation from GitHub as Reference](https://docs.github.com/en/enterprise-server@3.1/admin/all-releases)

- [emojiterra](https://emojiterra.com/)

- [Figma / Type Space Figma Youtube Video](https://www.youtube.com/watch?v=6EuBIwUeF48&list=PLdlnbMNK63vmlbz78zin8X8RmAoBs_D1E&index=8)

- [Tool researched by 100Automations](https://github.com/100Automations/Website/issues/78#issuecomment-745641242) 

- https://github.com/hackforla/guides/issues/10#issuecomment-896934745 

- Guide Pages Design System - https://github.com/hackforla/website/issues/1630#issuecomment-954330264

### PR DESCRIPTION
**Pull request by abenipa3**
Fixes #1630

### What changes did you make and why did you make them?

(Please see Update 9/13/22 below)

This pull request contains files to the Guide Pages Redesign. 

The following files have been added to the respective folders:
- `_guide-pages\how-to-set-reminders-in-slack.md` - New Guide Page called "How to Set Reminders in Slack"
- `_includes\toc.html` - Generates section and subsection titles for the sticky navigation of the Guide Pages.
  - This is the same method used for 100Automations' Guide Pages as seen [[here]](https://github.com/100Automations/Website/blob/gh-pages/_includes/toc.html).
- `_layouts\guides.html` - Layout used for the Guides' MD files.
- `_sass\components\_guides.scss` - Styling for the redesigned Guide Pages.
- `assets\images\guides\how-to-set-reminders-in-slack` - Contains all of the images included in "How to Set Reminders in Slack"
- `assets\images\guides\guide-page-hero.svg` - New hero image for the redesigned Guide Pages.
- `assets\js\guidepages.js` - JS for Guide Pages that enables the functionality of the sticky navigation bar and the _Return to the Top_ Button.
  - _Return to the Top_ Button is only visible on mobile. 
- `pages\guides.html`

The following file has been modified:
- `_sass\main.scss` - Added `@import 'components/guides.scss';` to import styling for the redesigned Guide Pages.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Current Guide Page Design

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

Redesigned Guide Page Design

Note: Please excuse the odd navbar placements. I used an extension to snapshot the entire webpage and the navbar followed the extension as it scanned the page.

image

</details>

Here is also the [Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17202%3A107428) to the Guide Pages Redesign as reference. 

Link to View Locally: http://localhost:4000/guide-pages/how-to-set-reminders-in-slack.html

### Special Notes
~~The following issues need to be completed before the Redesigned Guide Page is ready for public view:
#2978 - Create Guides Markdown Converter (Google Apps Script)~~

Update 6/4/22:
After a [discussion ](https://github.com/hackforla/website/pull/3161#issuecomment-1140494806) with our team, PR will be merged into gh-pages after review. 

Update 8/18/22:
I made the mistake of deleting my head/forked repo. My intent was to pull the latest updates as I was committing my changes to my old PR - https://github.com/hackforla/website/pull/3161 -, but had issues pulling the latest updates, so deleted my fork repo (bad idea). 

Was able to retrieve the old PR, but could no longer update from there; Github needed me to create a new one. My apologies for the inconvenience once again. Please feel free to message me if you have any questions via Slack or email (alymaebenipayo@gmail.com). Thank you. 

Update 9/13/22:
Reopened - we detected visual issues found after merging PR. [[Link to Initial PR]](https://github.com/hackforla/website/pull/3476)

### Links to Related Issues
Some existing issues in this PR may have already been addressed as action items in related issues. If an issue has not been addressed, please feel free to mention it here or in the related issues. Here are the links as references:
https://github.com/hackforla/website/issues/1515 - Create mobile version of the Guide Pages and ensure responsiveness 
https://github.com/hackforla/website/issues/3170 - Guide Pages - Sticky Navigation Fix
https://github.com/hackforla/website/issues/2978 - Create Guides Markdown Converter (Google Apps Script)
https://github.com/hackforla/website/issues/1630#issuecomment-954330264 - Guide Pages Design System Update

### CODE REVIEW

**Comment by abenipa3** [comment]
Hey team! I may need assistance with this. For reference, see below. [[Link]](https://github.com/hackforla/website/pull/3476#issuecomment-1242526998)

> Thank for getting back to me Alyssa. Please forgive me, I misspoke earlier, when I said "re-open" I meant create a PR. We tried to "re-open" the PR, obviously to no avail.
> 
> Below are screenshots I grabbed of the live website when we (foolishly) merged the PR.
> 
> Screenshot (241)
> 
> Screenshot (240)

Here is the output after I checked locally:
image

image

image

I suspect it might be a thing with GH Pages where new changes may take up to 10 minutes if not an hour. (I also realized I've encountered a similar issue in the past and had to wait for about an hour for all the contents to populate properly.) - Here's a doc for reference, too - https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site.

If anything, I'm open to options on how we can approach this. Would very much appreciate it if anyone could double-check again locally just in case. 😄 👍

**Comment by blulady** [comment]
It's entirely possible. This is what that page currently looks like. I am happy to throw it up locally and if it looks good merge it again. We will meet tonight and I'll double check it. If not roll it back again.
Screenshot (242)

**Comment by abenipa3** [comment]
Hey @blulady ! Awesome, sounds a great plan. Thanks so much. I'll look forward to any updates 👍

**Comment by ericvennemeyer** [comment]
Hey @alyssabenipayo @blulady I just tested this out locally, and it looks fine on my end. FWIW it looks like the "_guides.scss" file is not properly connecting after the merge. That seems to be the one that contains all the style info for the cards, margins, sticky nav, etc. I have no idea why this would work locally but not in production, though. :/

**Comment by blulady** [comment]
> Hey @alyssabenipayo @blulady I just tested this out locally, and it looks fine on my end. FWIW it looks like the "_guides.scss" file is not properly connecting after the merge. That seems to be the one that contains all the style info for the cards, margins, sticky nav, etc. I have no idea why this would work locally but not in production, though. :/

@ericvennemeyer That's interesting. How can you tell it's not connecting properly?

**Comment by blulady** [comment]
Hey, so I am uncertain if this is working as intended or if it just looks a little funky because I am inspecting it... But it seems like the Nav Bar is very centered in these mobile views.
Screenshot (243)
Screenshot (245)
Screenshot (246)

**Comment by ericvennemeyer** [comment]
@blulady I'm not 100% it's the `_guides.scss` file, but at a glance it looks like the styles that aren't being applied are the ones contained in that file. 

The sticky nav bar definitely doesn't show up where it's supposed to on mobile views. I mentioned that to @alyssabenipayo  as well and apparently it's being covered in a separate issue.

**Comment by blulady** [comment]
> @blulady I'm not 100% it's the `_guides.scss` file, but at a glance it looks like the styles that aren't being applied are the ones contained in that file.
> 
> The sticky nav bar definitely doesn't show up where it's supposed to on mobile views. I mentioned that to @alyssabenipayo as well and apparently it's being covered in a separate issue.

Ok, if it's getting covered somewhere else, I'll roll it out. I don't suppose you know the issue number?

**Review by blulady — APPROVED** [review]
The sticky nav bar definitely doesn't show up where it's supposed to on mobile views. I mentioned that to @alyssabenipayo as well and apparently it's being covered in a separate issue.

**Comment by abenipa3** [comment]
> Ok, if it's getting covered somewhere else, I'll roll it out. I don't suppose you know the issue number?

Yes, the issue number is here: https://github.com/hackforla/website/issues/1515 !

~~Side comment: I wonder if there's a other steps that needed to be covered so that the scss transfers over? It's also added as `@import guides.scss` (not verbatim 😅 ) in the main.scss. 😮~~

**Comment by abenipa3** [comment]
Just saw it deployed and here's the output! 😮 👀 
image

**Comment by ericvennemeyer** [comment]
@alyssabenipayo Yaay! It looked broken to me, but I realized I had to do a hard browser refresh and now it looks good. As you said, it just took a minute for the changes to take effect. 🙌

**Comment by blulady** [comment]
It looks good!! Thank you for all of your hard work with this.

**Comment by abenipa3** [comment]
Wooo-hooo! I'm glad it works! Thanks so much for working with me on this, @ericvennemeyer and @blulady! 😸 🎉

**Pull request merged**
