### PR TITLE
Update labels in the Mobile_responsiveness.yml file

### LINKED ISSUE #4483: Update labels: Issue Template: Mobile_responsiveness
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/Mobile_responsiveness.yml`
- [x] Replace the following line
   ```
   labels: ['role: design']
   ```
   with
   ```
   labels: ['role: design', 'Feature Missing', 'Complexity: Missing', 'size: missing']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4483#issuecomment-1550766745)

**For Reviewers and Merge Team**
- To review this issue, follow the link below under "Link for Reviewers", then confirm the labels in the issue template match with those specified in the issue.

#### Link for Reviewers 
URL of the issue template on the test repository: https://github.com/rdhmdhl/website/issues/new?assignees=&labels=role%3A+design%2CFeature+Missing%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=Mobile_responsiveness.yml&title=Mobile+Responsiveness+on+%5Bname+of+the+page%5D+%3A+%5Bquick+recap+of+the+bug+here%5D

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/ISSUE_TEMPLATE/Mobile_responsiveness.yml`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by rdhmdhl**
Fixes #4483

### What changes did you make and why did you make them ?

  - Update labels in the Mobile_responsiveness.yml file
  - Made this change to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
 
Link for Reviewers
URL of the issue template on the test repository: https://github.com/rdhmdhl/website/issues/new?assignees=&labels=role%3A+design%2CFeature+Missing%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=Mobile_responsiveness.yml&title=Mobile+Responsiveness+on+%5Bname+of+the+page%5D+%3A+%5Bquick+recap+of+the+bug+here%5D

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by jenny-alexander** [comment]
Review ETA: 05/19/23 10-12pm
Availability: 05/19/23 10-2pm

**Review by roslynwythe — APPROVED** [review]
Hi @rdhmdhl this PR looks great.  You setup the branches correctly, the code change is correct and clean, and you described your work.  Thank you for posting the link so reviewers can view the updated Mobile Responsiveness issue template in your fork on Github.  I confirmed that the issue template includes the correct labels.  I know the testing process for this issue was unusually complex and we really appreciate your pateience and effort to complete the job.

**Review by jenny-alexander — APPROVED** [review]
@rdhmdhl - this looks really good! 
I see you put the linked issue in the PR. 
The 3 additional labels appear in the issue template on the test repository (I checked via the link you provided in the PR).
The Mobile_responsiveness.yml file contains the requested changes to add 3 new labels.

Thank you!

**Review by t-will-gillis — APPROVED** [review]
Hey @rdhmdhl - Great job! Your branches are correct, you're linking the issue, your description says what you did and why, you added the link to the issue creation on your repo and the visuals, and your code is clean and concise. Thanks for working on this

**Pull request merged**
