### PR TITLE
Updated alt text on open community survey md file

### LINKED ISSUE #3098: Change alt text for card image in open community survey md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the open community survey project card image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/open-community-survey.md`, change line 77 for the alt text:

from
```
card-image-alt: open community survey project card
```
to
```
card-image-alt: 
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/open-community-survey.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/open-community-survey.md?plain=1#L99

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by carolemlago**
Fixes #3098

### What changes did you make and why did you make them ?

  - Updated alt text for card image in open community survey md file from "card-image-alt: open community survey project card" to "card-image-alt: "
  - Note: correct line number is 77, not 99 as stated on issue's description.
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Moving files to another directory. No visual changes to the website.

### CODE REVIEW

**Comment by lilyarj** [comment]
Eta: 9/23/22
Availability: 2hrs

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Comment by GRISONRF** [comment]
Availability: Friday till the end of the day.
ETA: 5pm Friday

**Review by GRISONRF — APPROVED** [review]
Looks good, great job!

**Comment by Unity7** [comment]
This looks good. I was able to clearly see that you updated the alt text.

**Review by Unity7 — COMMENTED** [review]
This looks good. I was able to clearly see that you updated the alt text.

**Pull request merged**
