### PR TITLE
Updated Contributing.md

### LINKED ISSUE #5693: Update CONTRIBUTING.md Section 2.7.f i SSH for Mac
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac) we need to clarify the instructions used for setting up an SSH key for Mac in Section 2.7.f i in order to avoid confusion. 

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to Section 2.7.f i "Setting up SSH Keys for Mac"
- [x] Replace
```
4. Next you need to add your ssh key to your ssh agent.
```
with
```
4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

### PR DESCRIPTION
**Pull request by ChrisKildunne**
Fixes #5693

### What changes did you make?
  - Changed 4. Next you need to add your ssh key to your ssh agent. to 4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.

### Why did you make the changes (we will use this info to test)?
  - To help give onboarding hack for la contributors more clear instructions for working on an issue.
  -  For Reviewers: Do not review changes locally, rather, review changes at https://github.com/chriskildunne/website/blob/update-contributing.md-5693/CONTRIBUTING.md

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 11/28

**Review by Thinking-Panda — APPROVED** [review]
@ChrisKildunne , Thank you for working on this issue. Merge branches look good, code changes are as mentioned in the issue, and are displayed in the link provided. Well done!

**Comment by ChrisKildunne** [comment]
Thank you, it took me a few tries.

**Comment by robertnjenga** [comment]
Availability: Mon - Fri 10a-2p
Review ETA: 11/29 - EOD

**Review by robertnjenga — APPROVED** [review]
Hello @ChrisKildunne Thanks for taking up this issue.
The basics are all good -  branches, link to issue, descriptions of what you did, i.e modified CONTRIBUTING.md Section 2.7.f i,  and why the changes were needed. You also provided the test URL which confirms the updates. Great job!

**Pull request merged**
