### PR TITLE
Fixed typo for issue #2911

### LINKED ISSUE #2911: Fix misspelled word on about-card-platform.html file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_includes/about-page/about-card-platform.html`,  on line 76, change the spelling from "definitley" to "definitely", so

  ```
  And last but definitley not least, a true open door policy....
  ```
  becomes
  ```
  And last but definitely not least, a true open door policy....
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/about
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_includes/about-page/about-card-platform.html#L76

### PR DESCRIPTION
**Pull request by RyanCahela**
Fixes #2911

### What changes did you make and why did you make them ?

  - I fixed the spelling of definitely in ~/_includes/about-page/about-card-platform.html
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Before Fix

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Fixed Typo

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
@RyanCahela 

For your before picture, you can take a screenshot of the current website, which should still have the misspelling.

Also, please add your pr to the Project Board.

<details>

  <summary>Click here for more detailed instructions on how to add your pr to the Project Board</summary>
  
  1) On the right, under the "Projects" section
    how-to-add-to-the-project-board1
  
  2) Click on the gear icon
    Add-to-project-board
  
  3) Then click on Project Board to add your pull request to the project board.
    how-to-add-to-the-project-board3

</details>

**Comment by RyanCahela** [comment]
@JessicaLucindaCheng 

I added a before picture and assigned the issue to the project board. 

Let me know if I need to fix anything else.

**Review by Sparky-code — APPROVED** [review]
@RyanCahela Definitely Fixed, Welcome to H4LA!

**Comment by answebdev** [comment]
Review ETA: 3/23/2022 (end of day)
Availability: 3 hours

**Review by answebdev — APPROVED** [review]
@RyanCahela Thank you for submitting your PR. For this issue, the spelling for the file `_includes/about-page/about-card-platform.html` on line 76 needed to be changed from "definitley" to "definitely", which I can see that you did. I also was able to see the changes in the browser. Great job!

**Pull request merged**
