### PR TITLE
Remove type field 2793

### LINKED ISSUE #2793: Edit content field and remove type field from avatar.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/avatar.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label  

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/avatar.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/avatar.yml#L4
https://github.com/hackforla/website/blob/0a6a6e08f231f0fd5ac2c7c9222a6bf6b8da682a/_data/internal/credits/avatar.yml#L11

### PR DESCRIPTION
**Pull request by matt-arofin**
Fixes #2793 

### What changes did you make and why did you make them ?

  - Deleted 'type' field from credits yml file in `_data/internal/credits/avatar.yml` because it is now redundant
  - Changed 'content' field to 'content-type' in `_data/internal/credits/avatar.yml` to make its purpose clearer for devs

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Edited a credits yml file to add clarity to its fields. No visual changes to the website.

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA:  End of the day on 4/24.
Availability: 1 hour.

**Comment by JessicaLucindaCheng** [comment]
@trishajjohnson 
When you're assigned as a reviewer for a pr, please write in a comment the following:
- Availability: "How much time will you have this week to review this pr?"
- Review ETA: "When do you expect to complete your review?"

**Comment by trishajjohnson** [comment]
ETA: end of day 4/24
Availability: 1 hour

**Review by kathrynsilvaconway — APPROVED** [review]
Hi, @matt-arofin. Congratulations on completing your first HFLA issue. I see that your have removed the type field from the avatar.yml file and renamed content field as "content-type." Nice work, everything looks good.

**Review by trishajjohnson — APPROVED** [review]
Hey @matt-arofin.  Just took a look at your PR, everything looks great!  The to and from branches are correct, you provided a linked issue and your explanation of tasks accomplished was clear and to the point.  I pulled your branch and took a look at it and it appears that the page is in working order for all views, nothing broken or out of place, and comparing the files changed, everything seems to be in order.

Great first issue and congrats on completing your first PR!

**Pull request merged**
