### PR TITLE
Refactor tools data for civic-tech-index.md

### LINKED ISSUE #4800: Refactor Tools data for civic-tech-index.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [ ] Refer to the [civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md) file and find the entry for `tools:`
  - [ ] Change the `tools` data from:
```
tools: Google docs, Figma, Usability Hub
```
to
```
tools:
  - Google docs
  - Figma
  - Usability Hub
```
  - [ ] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by yujioshiro**
Fixes #4800

### What changes did you make?
 - Refactored the Tools data for civic-tech-index.md

### Why did you make the changes (we will use this info to test)?
  - The filter menu for the project will include a filter called "Tools" and the refactor ensures the tools are are now individual strings inside a list instead of a single string

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

While there are no visual changes to the website, here is the before and after to show that the tools are rendered correctly for the viewer.

<details>
<summary>Visuals before changes are applied</summary>

Civic Tech

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Civic Tech

</details>

### CODE REVIEW

**Comment by DakuwoN** [comment]
Review ETA: 6 PM 8/2/23
Availability: M-F 3PM - 9PM & Saturday Free

**Review by roslynwythe — APPROVED** [review]
Great job @yujioshiro on this Pull Request.  You setup the branches correctly, your code change is clean and correct, the tools data displays correctly in the browser on both the projects page and the civic tech index webpages, and you provided a description of the changes.  Thank you for contributing to Hack for LA!

**Comment by DakuwoN** [comment]
As I try to preview the change in Docker, I am not seeing the update... I am on the correct branch. 
docker

**Review by DakuwoN — APPROVED** [review]
Excellent job @yujioshiro everything looks clean on this end! Keep up the great work!

**Pull request merged**
