### PR TITLE
Update Lucky Parking tools from string to list

### LINKED ISSUE #4809: Refactor Tools data for lucky-parking.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Jupyter Notebooks, Google Colab, AWS
```
```
tools:
  - Jupyter Notebooks
  - Google Colab
  - AWS
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by mshirk2**
Fixes #4809 

### What changes did you make and why did you make them?
  - Updated tools in lucky-parking.md from a string to a list

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - No visual changes made to the website

### CODE REVIEW

**Comment by kwangric** [comment]
ETA: EOD 7/26
Availability: After 5pm PDT

**Comment by bphan002** [comment]
ETA: Wednesday July 26th EOD

**Review by kwangric — APPROVED** [review]
Branches are set up correctly and the request changes to the code were made. Everything look correct in Docker.

One minor note about the PR is that more details can be added in the description for *why* the changes needed to be made. But other than that, great work!

**Review by bphan002 — APPROVED** [review]
Change was exactly as it should be.  Everything is loading properly and functional. Great work!

**Comment by LRenDO** [comment]
Hi @mademarc! If you still would like to review this request, please add your ETA and Availability when you get a minute.  If not, please remove yourself as a reviewer.  Thanks!

**Comment by mademarc** [comment]
Review ETA: 7/27/2023
Availability: 7:16PM

**Review by mademarc — APPROVED** [review]
Hey @mshirk2  Great job on changes that was required and next time do some screenshots of the work that you have done to show exactly how you did it  and @LRenDO  the ETA and Review is done.

**Review by adrianang — APPROVED** [review]
Hi @mshirk2 — the branching is set up correctly, the corresponding issue is linked, and the requested change of making the tools for Lucky Parking into a list. In testing your branch on my local machine, the project page is still rendering the same (as expected).

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
