### PR TITLE
Add github-handle for Selena Jiang in ems-triage-tracker.md

### LINKED ISSUE #6723: Add github-handle for Selena Jiang in ems-triage-tracker.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/ems-triage-tracker.md` in the IDE
- [x] Replace:
```
- name: Selena Jiang
```
with
```
- name: Selena Jiang
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/ems-triage-tracker

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by dcotelessa**
Fixes #6723

### What changes did you make?
  - On _projects/ems-triage-tracker.md, 
    - added `github-handle:` under `- name: Selena Jiang`

### Why did you make the changes (we will use this info to test)?
  - We need to create a single variable github-handle to hold the github handle for Selena Jiang. 
  - No visual changes, but handle is now in the yaml.

No visual changes to website.

### CODE REVIEW

**Review by mrodz — APPROVED** [review]
Review ETA: 11 AM 5/26/24

This looks great! Besides the formatting issues presented by @t-will-gillis, you followed the items on the checklist and followed the protocol for submitting a PR.

- Branching done correctly
- Issue included
- Used spaces and correctly added the `github-handle` property
- Proper naming of the issue

Congrats on the PR! Thank you for the contribution.

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hey @dcotelessa Congrats on your first HfLA PR-

- Branches 'from' and 'into' are correct
- Original issue is linked
- A brief description of what was done and why is provided
- The code edit is clean

Some notes:
- Under the 'what change' and 'why', please remove the extra lines
- Under 'Screenshots of Proposed Changes..." please remove everything and replace with something to the effect of "No visual changes to website"

Thanks for working on this!

**Comment by t-will-gillis** [comment]
Hi @mrodz 
There is not a specific format that needs to be followed when leaving a [PR review](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Comm), but there are specific items that a good PR review checks for, and it is helpful for everyone when the reviewer leaves specific (and encouraging) reasons for why the PR is being approved or why changes are being requested.  

Here is an example of a well-done review: https://github.com/hackforla/website/pull/6887#pullrequestreview-2075530707 When we look at this, we can see both that the reviewer has done a thorough job checking the PR, and the reviewee has done their job in creating the PR.

**Comment by mrodz** [comment]
> Hi @mrodz There is not a specific format that needs to be followed when leaving a [PR review](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Comm), but there are specific items that a good PR review checks for, and it is helpful for everyone when the reviewer leaves specific (and encouraging) reasons for why the PR is being approved or why changes are being requested.
> 
> Here is an example of a well-done review: [#6887 (review)](https://github.com/hackforla/website/pull/6887#pullrequestreview-2075530707) When we look at this, we can see both that the reviewer has done a thorough job checking the PR, and the reviewee has done their job in creating the PR.

Thank you for the help! I am new to reviewing PR's and I appreciate the feedback. I will use your tips for the next PR's I review.

**Comment by dcotelessa** [comment]
Great feedback. I will keep the format in mind for readability. Thanks!

**Review by t-will-gillis — APPROVED** [review]
Hey @dcotelessa - Perfect, thanks for making the edits. Everything looks great!

**Review by mrodz — APPROVED** [review]
I am re-approving this PR as the formatting was fixed. Good work!

**Pull request merged**
