### PR TITLE
Update cspell.json with docker-compose.yml

### LINKED ISSUE #5849: Add "docker-compose.yml" to "ignorePaths" array in cspell.json
### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to 'cspell.json`
- [x] Add the path "docker-compose.yml" to the end of the array "ignorePaths"
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [ ] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by dimiprousalis**
Fixes #5849

### What changes did you make?
  - Added "docker-compose.yml" to "ignorePaths" array in cspell.json file

### Why did you make the changes (we will use this info to test)?
  - To exclude docker-compose.yml file from spell checking

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
 - No visual changes required

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 12/23/23
Availability: Weekday evenings

**Comment by james-aguirre** [comment]
Availability: Weeknights
ETA: 12/23/23

**Review by pdimaano — APPROVED** [review]
@dimiprousalis Good job: The branches are correct and the issue is linked. The correct file was updated with the requested information and spell checking was omitted from the yml file. There were no visual changes or glitches to the site when run locally on my system. Well done!

**Review by james-aguirre — APPROVED** [review]
@dimiprousalis Thank you for taking up this issue! Your branching looks good, you added the issue # in the description, made the correct changes in csspell.json, gave a descriptive explanation of the changes made, and clarified that there were no visual changes in your PR. Nice work!🙌🏼

**Pull request merged**
