### PR TITLE
Update dependencies action 2065

### LINKED ISSUE #2065: GitHub Actions: Create issue at a timed interval to check for updates to GHA version
### Overview

As a developer who maintains the repository, we need to periodically update our dependencies so that our GitHub actions do not unexpectedly break.

### Psudo-code
- [x] Discuss with the team on how often the interval should be. (Until this discussion happens, you can use a workflow_dispatch trigger to test your code for now).
- [ ] Trigger: when the update interval arrives
  - [x] Post a new issue
    - [ ] The issue is a well formed issue containing:
      - [x] Overview
      - [x] Action items, perhaps something like "Check all GitHub action dependencies for updates" and "create further issues to update the GitHub action as needed"
      - [x] Resources/Instructions
      - [ ] Other notes as needed
    - [x] The issue needs to be well labeled.
    - [x] The issue needs to be moved to the correct column.
    - [x] The issue needs to exist on an external md file so that it can be easily edited by the team as needed.

### Checks

- [ ] None, but the GHA should be run once as a trial, to create an official issue. This issue can then be taken up by a member of the team, and this member can give feedback on the issue's content.

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[About actions](https://docs.github.com/en/actions/creating-actions/about-actions)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

### PR DESCRIPTION
**Pull request by BeckettOBrien**
Fixes #2065 

### What changes did you make and why did you make them ?

  - Created `.github/workflows/update-dependencies-issue.yml`
  - Created `github-actions/update-dependencies-issue/update-issue-template.md`

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Created a new GitHub Actions workflow. No visual changes to the site.

### Notes
There are a few things that might need to change before this PR can actually be merged:
- Right now the action is set to trigger once a week, but that might be too often for creating a fairly large issue
- I'm still pretty new to writing issues so my draft of the template probably needs editing
- We need to decide what column of the project board the issue should go in, and someone needs to create a GitHub secret with its ID

### CODE REVIEW

**Comment by kathrynsilvaconway** [comment]
ETA: End of day 7/27
Availability: 3 Hours

**Comment by blulady** [comment]
ETA: 7.24.22
Availability: 7.25.22

**Comment by blulady** [comment]
ETA: 22-7-24
Availability: 22-7-24, 22-7-25

**Comment by ExperimentsInHonesty** [comment]
@blulady Checking in on your on this PR.  You indicated you were avail on 24 & 25 and the eta was 24.  I don't see a review from you.  Do you need to be unassigned as a reviewer?  If yes, please reach out to @Zak234  and ask him to do a review

**Comment by ExperimentsInHonesty** [comment]
@blulady @kathrynsilvaconway FYI The intern who opened this PR-  last day is Friday, so we need to respond to him in a timely way, so that he can fix anything that comes up before he goes.

**Comment by blulady** [comment]
> @blulady Checking in on your on this PR. You indicated you were avail on 24 & 25 and the eta was 24. I don't see a review from you. Do you need to be unassigned as a reviewer? If yes, please reach out to @Zak234 and ask him to do a review

Hey Bonnie, so after you bailed on the Monday meeting we started talking about how I actually can't test this PR because when I wiped my repo and re-forked, I no longer had access to classic projects. I expected this PR to be closed the way we closed the other PR involving {{ secrets.PRIORITIZED_BACKLOG_COLUMN_ID }} and there is still yet another PR with this issue. Which is why I didn't unassign myself as a reviewer but I am happy to do it now. This issue is experiencing a similar problem. https://github.com/hackforla/website/pull/3426

**Comment by BeckettOBrien** [comment]
If it's too much of a hassle I can just put the column ID directly in the action and not use GitHub Secrets (I think the column id is publicly available information anyway). I just used a secret because I saw that other actions have used secrets for column ids in the past. Also, would we rather put the issue in the new issue approval or the prioritized backlog? I can think of benefits and tradeoffs for both, so just let me know which one you think would work best and I'll add the ID to the action.

**Comment by ExperimentsInHonesty** [comment]
@BeckettOBrien please have it not use GitHub secrets if that information does not need to be secret.

**Comment by ExperimentsInHonesty** [comment]
@blulady 
I'll send Beckett to Office hours tonight to see if this can get resolved.  I don't think I really understand the problem that these two issues are having.  

@hackforla/website-merge  What do you want Beckett to do if he can't finish this issue before internship is over.  Should we have someone take over the PR?

**Comment by BeckettOBrien** [comment]
That should be the only change that prevented the action from being deployed, and everything else (schedule, the contents of the issue posted, etc.) can be changed later and (hopefully) without needing my help.
- To change the issue contents, including the name and labels, edit `github-actions/update-dependencies-issue/update-issue-template.md
- To change the schedule, change line 6 of `.github/workflows/update-dependencies-issue.yml`
- To change the column of the project board the issue gets posted in, change line 23 of `.github/workflows/update-dependencies-issue.yml` (if you click "Copy Link" on a project board column, the ID will be after the dash in the link, ex: `https://github.com/hackforla/website/projects/7#column-7198257` is `7198257`

**Comment by blulady** [comment]
https://github.blog/2022-08-09-dependabot-now-alerts-for-vulnerable-github-actions/#dependabot-alerts-for-github-actions
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by blulady** [comment]
https://github.com/hackforla/website/issues/3598 Please see this issue for details as to why we are closing this issue.

**Pull request closed without merging**
