### PR TITLE
replace verbiage in getting started step 3

### LINKED ISSUE #1488: Adjust Step 4 of Getting Started page
### Overview
We need to adjust Step 4 of the Getting Started page to keep it up to date with current onboarding practices at HfLA

### Action Items
- [x] Review the changes to the Step 4 text in the annotated screenshot below
- [x] Replace "Project Lead" with **"Product Manager"** in # 1, per the screenshot
- [x] Replace "Admin a link to the Team Roster" with **"Product Manager your Github username"** (no link) in # 4, per the screenshot

### Resources/Instructions
[Getting Started Page](https://www.hackforla.org/getting-started)
[Hack for LA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Screen Shot 2021-04-28 at 12 29 40 AM

### PR DESCRIPTION
**Pull request by wendywilhelm10**
fixes #1488 

before 
Before

after
After

Changed verbiage in 1 and 4 in step 3 according to issue.

### CODE REVIEW

**Review by daniellex0 — APPROVED** [review]
Perfect, thanks! 👍

**Review by erikaBell — APPROVED** [review]
Looks good ~

**Review by erikaBell — CHANGES_REQUESTED** [review]
There is a conflict in your branch, if you could fix that up @wendywilhelm10 (-: 

Then we'll be able to merge

**Review by erikaBell — APPROVED** [review]
Great! Thanks for fixing the merge conflicts Wendy (-:

**Pull request merged**
