### PR TITLE
Refactored code using the deprecated Window: Event Property

### LINKED ISSUE #5289: Refactor code using the deprecated Window: Event Property
### Overview

We want to refactor code that uses the deprecated Window: Event Property to avoid JS errors/bugs.

### Action Items

- [x] In your local IDE, navigate to [_assets/js/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [x] Refactor using the following code from:
```
if ((event.key === "Enter" || event.key === "Spacebar" || event.key === " ") && document.activeElement.getAttribute("aria-label")) {
```
to
```
if ((e.key === "Enter" || e.key === "Spacebar" || e.key === " ") && document.activeElement.getAttribute("aria-label")) {
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website. On https://www.hackforla.org/projects and locally on docker (ie https://localhost:4000/projects)  make sure to to test tab index using "Enter" and "Space" to ensure it is working as intended.

### Resources/Instructions

1. Resulted from this  #5264 (example of a refactor on the ER)
2. Documentation on [Window: Event Property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event)

### PR DESCRIPTION
**Pull request by Maarimar**
Fixes #5289 

### What changes did you make?
  - Changed event.key in line 309 to e.key.

### Why did you make the changes (we will use this info to test)?
  - To refactor code that uses the deprecated Window: Event Property to avoid JS errors/bugs.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes made on site.

### CODE REVIEW

**Review by heejung-hong — COMMENTED** [review]
Hi @Maarimar,

I believe you deleted line 310, `document.activeElement.click() `, but the instructions didn't indicate that this line needed to be deleted.

Can you kindly advise why it was deleted?

Thank you

**Comment by Maarimar** [comment]
That was my bad. Working on correcting now.

**Comment by robertnjenga** [comment]
Review ETA:  04/13/2024
Availability: 12pm - 4pm

**Review by robertnjenga — APPROVED** [review]
Hello @Maarimar, Thanks for taking up this issue. 
The basics are covered:
- The pull request is done with the correct branch.
- You linked the issue.
- Code changes were made correctly as stated in the issue i.e refactor code that uses the deprecated Window: Event Property.
- I'm able to confirm that the Tab index is working as intended.
Nice work!

**Comment by t-will-gillis** [comment]
Hi @Maarimar Please don't forget to re-request a review by clicking on the 'chasing arrows' when you make changes based on a reviewer's comments:  

Screenshot 2024-04-14 094202

**Review by robertnjenga — APPROVED** [review]
PR approved in previous comment.

**Review by heejung-hong — APPROVED** [review]
Good work!
- The branches are correct and the issue is linked.
- The correct file was changed with the correct information.
- I have inspected and confirmed there are no visible changes in developer mode on Chrome (desktop, tablet, and mobile view), Firefox, and Safari browser.

Nice effort in the comment section.  Please note the edits I have made.  You might want to check the Preview tab to make sure everything looks good before saving your comment.

**Pull request merged**
