### PR TITLE
Superfluous attribute check and deletion in guidepages2fa 5712

### LINKED ISSUE #5712: attribute appears to be superfluous in `_guidepages/2FA.html`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Determine whether or not an empy class attribute in `_guidepages/2FA.html` is superflous, and if so, remove it.    

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 50, and note the line of code
```
<div class=''>

```
- [x] Determine whether the class attribute is superflous (unnecessary).  
  - [x] If so, remove it, then perform local testing using docker to ensure that the behavior and appearance of the page is unchanged, and then proceed to create a Pull Request
  - [ ] If the HTML should remain as-is, explain in a comment in the issue, then move the issue to Questions/In Review and apply the 'ready for dev lead' label.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA

### PR DESCRIPTION
**Pull request by LukeLowrey2**
Fixes #5712

### What changes did you make?
  - Found the superfluous empty class attribute in _guide-pages/2FA.html at line 50
  - Deleted the empty class attribute 
  - Saw no changes to behavior or appearance when testing locally

### Why did you make the changes (we will use this info to test)?
  - The empty class attribute at line 50 of _guide-pages/2FA.html was not needed 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - There were no visual changes to the website

### CODE REVIEW

**Comment by meru-a** [comment]
Review ETA: EOD 10/29
Availability: weekends

**Comment by robertnjenga** [comment]
Review ETA: EOD 10/29
Availability: Mon - Fri 10a-2p

**Review by robertnjenga — DISMISSED** [review]
Hi @LukeLowrey2! Thanks for taking up this issue.
The branching was done correctly, you linked the issue, you gave a description of what you did and why the changes were made, 
i.e removing the superflous class attribute. There appears to be no behavior or appearance changes on the page. Great Job!

**Review by MattChau01 — CHANGES_REQUESTED** [review]
- The branch is going into the correct branch `gh-pages`. ✅ 
- The original issue #5712 was properly referenced. ✅ 
- Per the instructions on the original issue, the class attribute in `<div class=''>` was properly removed on line 50. ✅ 

@LukeLowrey2 it seems you also made a change on the following file: `pages/join-us.html`, which wasn't referenced on the original issue. Out of curiosity, is there perhaps another issue you were working on with this fix?

Aside from that, the fixes made on `_guide-pages/2FA.html` look great 👍

**Review by meru-a — CHANGES_REQUESTED** [review]
@LukeLowrey2 good job with this PR! The PR description seems is coherent and the branch name is both valid and is going into the correct branch `gh-pages`. Also, the original issue was correctly linked and the class attribute was removed in `_guide-pages/2FA.html` due to being superfluous.

However, similar to @MattChau01, I have concerns about the changes on `pages/join-us.html`. I would be happy to approve your PR after you would comment on or remove these changes. Thanks!

**Comment by LukeLowrey2** [comment]
Thank you, @MattChau01 and @pearlescence-m, for pointing out concerns with the changes to pages/join-us.html. I will update the PR and re-request reviews.

Availability: Friday 11/3/23 9am - 11am, Saturday 11/4/23 9am - 11am, Monday 11/6/23 10am - 12pm
ETA: EOD Monday 11/6/23

**Comment by MattChau01** [comment]
Hi @LukeLowrey2 I saw the new change you made. Did you revert the changes you made on the previous PR? Or was the whole file deleted? Just wanted to clarify since it the `files changed` tab was saying that the `pages/join-us.html` file was deleted.

**Comment by LukeLowrey2** [comment]
Due to an unwanted changed file, I'll need to close this PR and create a new one for the issue https://github.com/hackforla/website/issues/5712.

Thank you @pearlescence-m, @robertnjenga, @MattChau01, and @roslynwythe for the help.

**Comment by LukeLowrey2** [comment]
Due to an unwanted changed file, I'll need to close this PR and create a new one for the issue https://github.com/hackforla/website/issues/5712.

Thank you @pearlescence-m, @robertnjenga, @MattChau01, and @roslynwythe for the help.

**Pull request closed without merging**
