### PR TITLE
Updated donate page image's alt text to adhere to WCAG

### LINKED ISSUE #3630: Update Donate page image's alt text to adhere to WCAG (again)
### Overview
We need to update the donate page image's alt text to provide alt text that adheres to the Web Content Accessibility Guidelines (WCAG).

### Action Items
- [x] make the correction to the file
    - [x] from `alt="join us card image"` to `alt=""`
    - [x] from  `alt="donation chart"` to ` alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"`
    - [x] line 28 from `alt="donation form image"` to `alt=""`
- [x] check that the donate page looks the same
- [x] check that the new alt texts got incorporated after the change by inspecting the web page using developer tools
- [x] Review with product referencing the parent issue https://github.com/hackforla/website/issues/2568 

### Resources/Instructions
- link to the tab on google sheets: [Alt Attribute Review, Donate Page ](https://docs.google.com/spreadsheets/d/1abMlPOX88zHTV29E4BFxAYwahCxgJN28Mn95cXr8jak/edit#gid=14599403)
- To correct this mistake we must make the change in the [_includes/donate-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)

#### Historical Notes (you do not need to read)
- The development team made a mistake in addressing this [issue](https://github.com/hackforla/website/issues/2886).
- The changes recommended are slightly different than this issue #2886
- This issue also replaces #3238.

### PR DESCRIPTION
**Pull request by braguda**
Fixes #3630 

### What changes did you make and why did you make them ?

  -updated alt="join us card image" to alt=""
  -updated alt="donation chart" to alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"
  -updated line 28 from alt="donation form image" to alt=""

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Alt text was changed. No visual changes to website

### CODE REVIEW

**Comment by MattPereira** [comment]
**Review ETA:** 12 PM 10/20/22
**Availability**: 12 - 4 PM Thursday

**Comment by plang-psm** [comment]
Review ETA: 1 PM 10/20/22
Availability: 11 - 5 PM Thursday

**Review by plang-psm — APPROVED** [review]
Good work! All alts requested were changed and the site runs fine.

**Review by MattPereira — APPROVED** [review]
Great work Brian! 👍

You followed the WCAG and made the perfect corrections to the alt text of `includes/donate-card.html` !

**Review by blulady — APPROVED** [review]
Good Job!!!

**Pull request merged**
