### PR TITLE
added _config.docker.yml file to not be spellchecked by cspell

### LINKED ISSUE #5452: Add _config.docker.yml to "ignorePaths" setting in cspell.json
### Dependency
- [x] #5313

### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to `cspell.json`
- [x] Add the path "_config.docker.yml" to the end of the "ignorePaths" array
- [x] Save `cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

### PR DESCRIPTION
**Pull request by Brayheart**
Fixes #5452 

### What changes did you make?
  -added "_config.docker.yml" to cspell.json file 

### Why did you make the changes (we will use this info to test)?
  - "_config.docker.yml" will not be checked for code spell check

No visual changes, no screenshots needed.

### CODE REVIEW

**Comment by lukewangm** [comment]
You need to change [#replace_this_text_with_the_issue_number] to the issue number associated with your fix. In your case I believe it is issue #5452

**Review by lukewangm — CHANGES_REQUESTED** [review]
You need to change [#replace_this_text_with_the_issue_number] to the issue number associated with your fix. In your case I believe it is issue #5452

**Comment by Brayheart** [comment]
@lukewangm, original comment has been updated to include fix number, thanks for catching that.

**Review by lukewangm — DISMISSED** [review]
Good work!

**Review by w1ld-r — CHANGES_REQUESTED** [review]
Hi @Brayheart — great work on this issue! 

- Your branch is correct
- You clearly described the changes and stated the reason for making them
- _config.docker.yml was added to the cspell.json file as requested
- No visible changes made to the website

A couple of notes:
- It looks like you linked to your PR instead of the issue in your PR description. The link should go to #5452. Can you update?
- It looks like there are no labels on your PR. I'm not sure how that happened, but I believe we want the labels on the PR to match those on the ticket. I think it should happen automatically, but can you add them manually?

Once these changes are made, I'll approve. Thanks again for your help! 😄

**Comment by Brayheart** [comment]
@gaylem updated ticket reference from 6432 to 5452 and updated tags.

**Review by w1ld-r — DISMISSED** [review]
@Brayheart Huzzah! Approved 👍

**Comment by w1ld-r** [comment]
Hey @roslynwythe, it looks like there are conflicts and @Brayheart and I aren't sure what the right procedure is. Let us know if we should resolve them before the merge team picks this up.

**Comment by Brayheart** [comment]
I added both lines to the file and merged

**Comment by LRenDO** [comment]
Hi @Brayheart! Great job fixing the merge conflict! It looks like there needs to be an added comma at the end of line 24. Please go ahead and update that and push the changes. Thanks!

**Review by w1ld-r — APPROVED** [review]
Thanks for making the changes @Brayheart! Your issue is properly linked, your PR has the correct labels, and you added a comma to line 24. Approved! 👍

**Review by jphamtv — APPROVED** [review]
Hey @Brayheart - great job addressing the feedback from @gaylem, @LRenDO, and @lukewangm to get this PR merged.

**Pull request merged**
