### PR TITLE
Fix bug and consolidate "Schedule Thursday" into "Schedule Monthly" 4788

### LINKED ISSUE #4788: Fix bug that prevents GHA "Schedule Monthly" from running
### Prerequisites
1. Be a member of Hack for LA. If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need our GitHub Actions to run  as expected on the schedule that we have set so that our workflow is not interrupted. The GHA "Schedule Monthly" has failed on the last two scheduled runs and the error needs to be addressed.

### Details
When reviewing HfLA "Actions" logs on the repo, it can be seen that the GHA "Schedule Monthly" has attempted to run on schedule on the 1st of the month for the last three months. Both attempts have failed on the the job `list-inactive-members` on the step `Get List`.
A successful run of this GHA will result in an issue being generated on the HfLA Project Board similar to the following, as well as a notification comment being added to issue #2607. 

- #4567 

### Action Items
Suggested steps:
- [x] Compare the Action logs for the failed GHA on the HfLA repo with the similar logs on the personal repos for hints as to what might be causing the error(s).
- [x] Refactor the [schedule-monthly-PREV.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly-PREV.yml) and js files and/or any other files or settings (such as the tokens) as needed. >NOTE: the file will be renamed `schedule-monthly-PREV.yml` after #4768 is merged.
- [x] Create a demo Project Board and Personal Access Token for your repo- see [HfLAs GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) doc esp. Tips 6 and 7. 
  - [x] **Important note: be sure to give your secret token a different name than HfLA's token.**
- [x] Create at least one new issue on your Project Board and remember the number.
- [x] Given the different behavior of the GHA running on a personal repo versus the HfLA repo, add a `workflow_dispatch:` to Line 6 of the schedule-monthly.yml so that the action can be triggered immediately on the live site, i.e.:
```
on:
  schedule:
    - cron: "0 8 1 * *"
  workflow_dispatch:
```
- [x] **_Done_**   ~On_ the yml file, change line 11 `- uses: actions/checkout@v2` to `- uses: actions/checkout@v3` per #4735~
- [x] On the three js files, for testing only change any lines referring to `const owner = "hackforla"` to your own repo. (You will revert this before you open the PR.)
- [x] In [comment-issue.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/comment-issue.js) change `let agendaAndNotesIssueNumber = 2607;` to reference the issue you created. (You will revert this before you open the PR.)
- [x] Confirm with a test on your own repo. A successful test will create the 'Inactive Member' issue in your repo, and add the notification comment to the issue you designated.

### Resources/Instructions

- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml)
- [/list-inactive-members/](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/list-inactive-members)
- [workflow logs](https://github.com/hackforla/website/actions/workflows/schedule-monthly.yml)
- Review issues #4158 and PR #4545 

- Note: `schedule-monthly.yml` is intended to identify and remove "Inactive" members from 'website-write' team, which also addresses ER #4541

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #4788 

### Notes to PR Reviewers
  - You will need to have a functioning test environment on your local repo. Here are additional changes that you should make to help with testing. If you do not make these edits, you might delete or mis-edit Hack for LA data, delete team members,  generate false or junk notifications, and/or create junk issues on HfLA's live project board. 
  - In the `schedule-monthly.yml` file:
    - Replace HfLA tokens with a personal token, 4 locations. 
    - Make sure your personal token has a different name than HfLA's token
    - Line 12, redirect to your personal repo.
  - In `contributors-data.js`:
    - Lines 16-21, replace current with:
```
let oneMonthAgo = new Date();                        // oneMonthAgo instantiated with date of "today"
oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 4);   // please make sure that the digit is set to '4'
oneMonthAgo = oneMonthAgo.toISOString();
let twoMonthsAgo = new Date();                        // twoMonthsAgo instantiated with date of "today"
twoMonthsAgo.setMonth(twoMonthsAgo.getMonth() - 5);  // please make sure that the digit is set to '5'
twoMonthsAgo = twoMonthsAgo.toISOString();
```
 - In `create-new-issue.js`:
    - Line 14, change "owner" to your personal repo
    - Lines 36-37, replace current with:
```
  let removedList = removeList.map(x => "@ " + x).join("\n");  // please make sure there is a space after "@  "
  let notifiedList = notifyList.map(x => "@ " + x).join("\n");  // please make sure there is a space after "@  "
```
 - In `comment-issue.js`:
    - Line 12, change the issue number to an issue in your personal repo
    - Line 18, change "owner" to your personal repo

### Background
  - Referring to #4768 also: Previously, both `schedule-monthly.yml` and `schedule-thu-1100.yml` have had bugs and have not run correctly for over a year. Both actions were intended to run once a month, and both involved listing inactive members and then performing some action with the list. For these reasons, we decided that these two should be consolidated into a single action. 
  - 4768 started the consolidation by:
    - renaming the **_then-current_** "monthly" action as a temporary file named `schedule-monthly-PREV.yml`, then 
    - renaming the **_then-current_** "Thursday" action as the refactored `schedule-monthly.yml` (and deleting the now-empty `schedule-thu-1100.yml`)
  - 4788 finishes the consolidation by:
    - incorporating the relevant sections of the "monthly-PREV" action into the refactored `schedule-monthly.yml` and deleting the now-empty temporary file.

### What changes did you make?

  - The original `get-list.ls` from the original "Thursday" / renamed "monthly-PREV" action gathered a list of inactive members. However, its definition of 'inactive' was to mean that the member did not have an open issue at the exact time that the action checked. This is not very helpful information, therefore `get-list.js` is not used/ is deleted. 
  - ~Instead, the definition of 'inactive' from `trim-contributors.js` file in the original "monthly" action is used. This file uses "true-github-contributors" from HfLA's "100 Automations" to search for activity and decide whether the member is active or not.~ _UPDATE 11/12/23: This is incorrect. The original `contributors-data.js` file does import "true-github-contributors" from HfLA's "100 Automations"; however, on further review this automation is not actually used in the file and therefore the import is deleted. See notes from 10/29/23 below._
  - The remaining functionality in `schedule-monthly-PREV.yml` (i.e. other than `get-list.js`) has been integrated into the new, consolidated `schedule-monthly.yml`.
  - Changes included in the refactored `schedule-monthly.yml`:
    - Changed some capitalization and clarified some comments
    - Changed `actions/checkout@v3` to `actions/checkout@v4` per dependabot #5443 
    - Changed the name of the HfLA bot token line 18/19 to match the tokens in the remainder of the file
    - The remainder (lines 39 onward) incorporates the functionality from the original monthly issue by creating a new issue and adding a notification comment to an existing Dev Team issue. 
    - Lines 39 onward are extended as new jobs on the GHA, and "artifacts" are used in order for the two jobs to share data
  - Changes to `contributors-data.js`:
    - Mostly changes to comments and jsDocs until line 250 onward. Here the list of inactive / removed members plus the list of members needing notification are saved to temp file in preparation for artifacting.
  - Changes to `create-new-issue.js`:
    - The main functionality is maintained, but the previous issue has been fleshed out to include "@-ing" the members and making a record of the removed and notified members on an issue.
    - (FUTURE: Optionally- the body of the issue could be pulled out into a markdown file.)
 - Changes to `comment-issue.js`: Besides edits to ensure the automation works, the changes are mainly to comments and formatting.
 
### Why did you make the changes (we will use this info to test)?
  - In order to address the bugs and consolidate both automations into a single, functioning automation.

### Screenshots of Proposed Changes 

<details>
<summary>Diffchecker showing consolidation of `schedule-monthly.yml` functions</summary>

Screenshot 2023-09-12 103836
Screenshot 2023-09-12 103815
Screenshot 2023-09-12 103821

</details>

- [Test run logs](https://github.com/t-will-gillis/website/actions/runs/6128524438) from my repo
- [Test issue created](https://github.com/t-will-gillis/website/issues/326) in my repo
- [Test comment on issue](https://github.com/t-will-gillis/website/issues/317) in my repo
- See also #5163 

## 10/29/23: Additional changes
Per Bonnie's comments [here](https://github.com/hackforla/website/issues/4788#issuecomment-1742152551) and especially  [here](https://github.com/hackforla/website/issues/4788#issuecomment-1774157733):
- in `schedule-monthly.yml` : bump actions/setup-node@v3 --> v4  per #5769
- in `contributors-data.js`: removed reference to ‘trueContributorsMixin’ / ‘true-github-contributors’: This is not actually being used within the function.
- In `create-new-issue.js`: added "thisIssuePredict" and "thisIssueNumber" to identify number of next issue prior to the issue being created
- In `create-new-issue.js`: revised body, labels  of “Review Inactive Members” <-- Major change
- In `create-new-issue.js`: added milestone with correct reference to HfLA 

## 11/22/23: Latest changes
Per Bonnie's comments [here](https://github.com/hackforla/website/issues/4788#issuecomment-1809431319) and discussion with Roslyn and Jessica:
- in `schedule-monthly.yml` : bump actions/github-script@v6 --> v7  per #5899
- in `contributors-data.js`: when octokit.request() is run on "/issues", it returns only users who are "assignee"s. This is to avoid the problem discussed with Bonnie et al about the issue author considered as "active" when someone other than the author updates the issue.
- in `create-new-issue.js`: added instructions to the "Review Inactive Team Members" issue a.) for members to respond with a comment, then reopen the issue and b.) for dev leads to follow a process to reinstall members, etc.
- created a new workflow `wr-schedule-monthly.yml` that only runs if `schedule-monthly.yml` was successful, then automatically finds and closes the issue that was created.
- _See 11/29/23 below_ ~created a new workflow `schedule-monthly-reopen.yml` that is triggered when someone reopens the "Review Inactive Team Members" issue. The workflow moves the reopened issue to the "Questions / In Review" column and applies the `ready for dev leads` label.~
- Finally note that `schedule-monthly-PREV.yml` needs to be deleted immediately after merging this issue.

## 11/23/23: Addendum
Since we will be taking off for the month of December, this monthly check for inactive members should skip the January 1st run and resume on February 1st. Also, the February 1st run should remove members inactive since November 1st (3 months ago) since again, no December. 
- Edits made to `schedule-monthly.yml` and `contributors-data.js` to account for the December holiday.

## 11/29/23: Final Addendum
The remaining edits to this GHA address the problem of how to allow an inactive member (w/o write access) to create an issue to notify dev leads. The prev method was to create a new issue when the member commented; however as discussed this causes the GHA to run every time a comment is made on every issue. The new method is for the member to create a new issue themselves from the comment. Then when the issue is being created, it is picked up by the existing GHAs for issue creation and filtered/labelled appropriately. 
-  Previous workflow `schedule-monthly-reopen.yml` is deleted/removed. It is no longer needed with the revisions.
- Added new info to the "Review Inactive Team Members" issue per `create-new-issue.js`
- Added filter functions to `issue-trigger.yml` to filter and label the new issue.

[New issue created](https://github.com/t-will-gillis/website/issues/397) 
- As before, issue self-closes
- Click on "Watch demo" for a visual demo. 
- See the comment on this issue
[Issue created by member in comment](https://github.com/t-will-gillis/website/issues/406)
- Issue is labelled and sorted to Questions/In Review
- Any member can do this- does not req write access

[Log for revised Schedule Monthly](https://github.com/t-will-gillis/website/actions/runs/7038017797/job/19154050052)
[Log for new WR Schedule Monthly](https://github.com/t-will-gillis/website/actions/runs/7038043608)
[Log for new issue](https://github.com/t-will-gillis/website/actions/runs/7039626872)

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 9/12 noon - 2 pm
ETA: 9/13 EOD

**Comment by roslynwythe** [comment]
Hi @t-will-gillis I have a few questions:
- I don't see any "Review Inactive Members" issues or comments in #2607 referring to such issues.  Were any such issues created in the process of testing ?  When was the last time inactive members were deleted?
- If I make the change suggested in contributors-data.js, to extend the deadlines by 1 month, do you expect any members to be deleted?

**Comment by t-will-gillis** [comment]
Hi @roslynwythe Thanks for reviewing and thanks for the questions:

- For testing, I shifted both the creation and the comment/notification of the issue "Review Inactive Team Members" to my repo. 
  - The [test issue is here- my repo no. 326](https://github.com/t-will-gillis/website/issues/326) and 
  - I shifted the [comment/ notification here- onto my repo no. 317](https://github.com/t-will-gillis/website/issues/317).
  - Whenever I ran a test, the action actually did make real/ permanent changes to HfLA's 'website-write' team, as if this action was already live. At first, I mistakenly believed that tests would not causes any changes since I was running this from my own repo using my own token. 
  - Because the test action does function, this is the reason I shifted the action dates back one month. The last tests I ran caused **_three-month_** inactive members to be removed from 'website-write'. The most recent is from my issue no. 326, September 8. (The GHA when live will remove two-month inactive members.)
- If you extend the deadlines and run a test, there will likely be a few more 'three-month' inactive members- inactive since June 17th- removed from 'website-write'.
- Side note: The member `cnk` was one of the early and productive contributors to the website. They are on the 'website-write' [child team](https://github.com/orgs/hackforla/teams/website-write/members?query=cnk+membership%3Achild-team). 
  - For some reason that I have not been able to identify, when I do test runs, the action cannot make changes to the child team. It might be because the test run is using my token, and since I don't have permission to edit the child team, my test run's token does not have permission either. (Maybe???)
  - After the action is live we will need to see if `cnk` persists in the child team.

**Comment by roslynwythe** [comment]
Thank you @t-will-gillis for a super useful response.  I'm afraid I'm not familar with these "Review of Inactive Member" issues and so I'm puzzled:  For a member who has been removed from website-write, if there has been  mistake or they want to come back, shouldn't they contact a dev lead immediately via Slack to be restored?  I guess I'm unclear on how this "review" issue will work and so I don't understand the reason for the the instructions under "If it ihas been less than 20 days".  Is the idea that the issue will remain open for 20 days to give members a chance to leave their comments, and then after 20 days I close it?  Also I noticed the "ready for product" label.  What is the role of product in this process?

**Comment by t-will-gillis** [comment]
Hi @roslynwythe - The intended function for the first of the two original GHAs was to create and post a list of the inactive members to the Monday Meeting Agenda. (I don't know the original reason- maybe to help with reviewing `2 weeks inactive` issues?) The intended function for the second of the two original GHAs was to find inactive members and cut them from 'website-write'. Neither of the two original issues notified the inactive members.  

For this revised/consolidated GHA, Bonnie wants to notify members when the bot determines that they have been inactive for over one-month, so that they know they're on the list to be cut from the `website-write` team. Then if the members are still inactive after two months the bot will proceed with removing them from 'website-write'.

The -message- of the issue [comes from Bonnie](https://github.com/hackforla/website/issues/4768#issuecomment-1648812159). I believe she intends that **_eventually_** this message will be posted to the individuals' personal, progress-summary issues, when we implement those. So for the future, the bot will write this message as a comment onto an individual's issue, and then the individual can choose to respond or not. (This is how I understand it, but I could also be wrong.)

As I noted above, one of the original GHAs was supposed to post an issue on the board with the list of inactive members. [This new "Review Inactive Team Members" issue](https://github.com/t-will-gillis/website/issues/326) extends the original by not only listing the inactive members but also "@-ing" them so that they are flagged with the message. The new issue also lists the two-month inactive members who were removed.

Regarding the notes for "if it has been less than (/more than) 20 days": My thought is that the "Review Inactive Team Members" issue would remain open for 30 days, until the next month's update. (*** See note below) So although the issue says 20 days, the one-month inactive member has the next 30 days to perform any kind of activity, such as by commenting, by picking up a new issue, or anything else. If they do, then the bot won't list them as 'inactive' the following month. 

If the member is on the list of 'one-month inactive' members this month, and they do nothing, then the following month when the bot runs again the member will be on the 'two-month inactive' list, so they will be cut from `website-write`. Again the message says "over 20 days" but they really have 30 days. If a member has been cut from `website-write` for any reason then the member will need to Slack a dev lead to get added back in. 

Regarding the `Ready for product` label, this is a holdover from the original GHA, but you are right it doesn't need this label. I will remove this label now. 

***Note from above. The unanswered question: what are the reasons for the dev leads and Bonnie to receive this list of inactive members, besides "it-is-always-nice-to-know"? The bot automatically cuts the 'two-month inactive' members from 'website-write', however the issue itself says that "If we don't hear back from you in the upcoming weeks, we will unassign you from any issues you may be working on..." So to me it seems like late in the month, someone would want to take this list and do a quick search to see if these members have any open issues, and if so, manually remove those members and reprioritize their issues. (There probably is a way to have the bot unassign inactive members but to me it seems like this would be better as a manual activity.)

**Comment by allison-truhlar** [comment]
Availability: W, Th, Fr 9am-12pm ET
ETA: Friday EOD

**Comment by roslynwythe** [comment]
I think I see what Bonnie was getting at if this messaging was intended to be posted in a prework issue, but in the context of this review issue, since we are listing inactive members separately from deleted members, we can clarify the messaging by moving the instructions for inactive members directly under the inactive member list, and removing the statements "If it has been less than 20 days" and "if it has been more than 20 days".  But I can discuss that with Bonnie in a Monday meeting, and if she agrees to new wording, I'd be happy to create a new issue.  

Thank you for explaining what I'm supposed to do as dev lead with the review issue, but I don't really want to have to check all these members to see if they have open issues.  Would it be possible to exclude members from automatic removal if they have open issues?  We do check "2 weeks inactive" issues and will eventually unassign members if there are no comments or activity.   I'm not suggesting that we modify this PR, only asking if this makes sense for work in a future issue.

**Comment by allison-truhlar** [comment]
I will need more time to wrap my head around the initial issue, PR, and ongoing conversation. I'm updating my initial time estimate for completing the review to EOD next Friday, 10/6. Next week, I'll be available most weekday afternoons (3-5pm ET) and evenings (8-9pm ET).

**Comment by t-will-gillis** [comment]
@roslynwythe 

> I think I see what Bonnie was getting at if this messaging was intended to be posted in a prework issue, but in the context of this review issue, since we are listing inactive members separately from deleted members, we can clarify the messaging by moving the instructions for inactive members directly under the inactive member list, and removing the statements "If it has been less than 20 days" and "if it has been more than 20 days". But I can discuss that with Bonnie in a Monday meeting, and if she agrees to new wording, I'd be happy to create a new issue.
  
  
You make good points, I agree this could be more clear. For the "Review Inactive Website Team Members" issue, is this [proposed clarification](https://github.com/t-will-gillis/website/issues/339) along the lines of what you were thinking? Please let me know what you think and if there are other things that could be clearer and/or changed.  

> Thank you for explaining what I'm supposed to do as dev lead with the review issue, but I don't really want to have to check all these members to see if they have open issues. Would it be possible to exclude members from automatic removal if they have open issues? We do check "2 weeks inactive" issues and will eventually unassign members if there are no comments or activity. I'm not suggesting that we modify this PR, only asking if this makes sense for work in a future issue.
  
  
Yes, I think it should be straightforward to exclude members who have open issues from automatic removal. Also, it totally makes sense that this action should be making work easier and not adding to someone's (your) work. I think that this check should be part of this PR if possible- I will look at it and reply here.

**Comment by roslynwythe** [comment]
@t-will-gillis @allison-truhlar This issue was discussed in the All Team Planning meeting earlier today.  A "review inactive members" issue had come to her attention because it was missing labels, but a discussion of the messaging and the behavior of the GHA ensued.  Please see her comments https://github.com/hackforla/website/issues/4788#issuecomment-1742155759 and https://github.com/hackforla/website/issues/4788#issuecomment-1742152551.

**Comment by allison-truhlar** [comment]
@roslynwythe @t-will-gillis Based on Rosyln's post and Bonnie's additional comments, am I correct in understanding that there needs to be additional revisions to the GHA back before it can be reviewed?

For the time being, I am going to remove myself as a reviewer from this PR to free myself up for other reviews. At the moment, I think this PR is a little too advanced for me, both in terms of the technical scope and also understanding the membership processes for HfLA. Please feel free to add me back as a reviewer if needed though!

**Comment by bphan002** [comment]
Availability Oct 12 all day
ETA:  Oct 12 Thursday EOD

**Comment by t-will-gillis** [comment]
HI @bphan002 Thanks for volunteering to review this. 

FYI as @allison-truhlar mentioned in the note above, I need to incorporate some comments and requested changes from Bonnie and Roslyn. (I plan to get to these later in the week.) I can let you know when I have made the requested changes. Thanks!

**Comment by t-will-gillis** [comment]
@roslynwythe If you are interested, here is the latest iteration of this PR - hopefully incorporating all of Bonnie's comments where possible.

**Comment by roslynwythe** [comment]
Hi @t-will-gillis was it possible to exclude members who have open issues from automatic removal?  This was discussed above in https://github.com/hackforla/website/pull/5467#issuecomment-1741907010

**Comment by bphan002** [comment]
Hello,

I'll remove myself from this pull request since I think it needs a bit more time to be finalized.

**Comment by elizabethhonest** [comment]
@t-will-gillis I may be missing something but I don't see where we are retrieving information about pull requests or pull request comments so I'm not sure if those count as contributor activity.

**Comment by roslynwythe** [comment]
@t-will-gillis I may be missing something but the queries for GitHub activity in contributors-data.js don't appear to include pull requests, so I'm not sure activity on pull requests would be considered.

**Comment by t-will-gillis** [comment]
Test comment

**Comment by t-will-gillis** [comment]
Hi @roslynwythe I thought that I should run a test to confirm whether `contributors-data.js` is recording activity on PRs:

I added the comment "Test comment" above, then I ran `contributors-data.js` and set the timeframe to be from one hour ago till now to see what activity would be registered. `contributors-data.js` did record activity from your comment, lines 176-219, and also recorded activity for my "Test comment", lines 220-263. [Here is the link](https://github.com/t-will-gillis/website/actions/runs/6856941940/job/18645095455)

Even though `contributors-data.js` does not specify "pull requests", the query to GitHub appears to be reporting those comments.

**Comment by t-will-gillis** [comment]
@roslynwythe BTW the tweaked **_test_** branch file [is here](https://github.com/t-will-gillis/website/blob/fix-sch-monthly-TEST-10-22/github-actions/trigger-schedule/github-data/contributors-data.js) 
Around lines 25-27 is where the one hour timeframe is added
Around lines 72 and 91-92 are the console.log() to report the `contributors.data`

**Comment by t-will-gillis** [comment]
> Hi @t-will-gillis was it possible to exclude members who have open issues from automatic removal? This was discussed above in [#5467 (comment)](https://github.com/hackforla/website/pull/5467#issuecomment-1741907010)

_WG: This should be possible. However, I am wondering if this is needed? For example, "Aveline-art" was removed from the 'website-write' team, but this did not appear to affect one of their issues '1940' ?_

**Comment by ExperimentsInHonesty** [comment]
Will is working on this ... here are note on the issue https://github.com/hackforla/website/issues/4788#issuecomment-1817668197

**Comment by mademarc** [comment]
Review ETA: 11/22/2023
Availability: 7:46PM

**Review by mademarc — DISMISSED** [review]
Hey @t-will-gillis  i like how you made this code readable  along with the proper changes to fix bug in order to make the code work.

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty @roslynwythe 
Final comments at top under "11/29/23 Final Addendum" (fingers crossed)

**Review by roslynwythe — APPROVED** [review]
Thank you @t-will-gillis for completing work on this complex issue.

**Pull request merged**
