### PR TITLE
Updated Project Profiles #3731

### LINKED ISSUE #3731: Update Project Profile: Design Systems
### Overview
As a developer, we must ensure our project's details are up to date on the HackforLA website. We need to update the [Design Systems](https://www.hackforla.org/projects/design-systems) "Project Overview" links and "Current Project Team".

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md) to find the `links` and `leadership` variables. 
- [x] Add a new link to the project's `links` variable. (The one with no indentation)
    - [x] Name: Releases
URL: https://github.com/hackforla/design-systems/releases
- [x] Remove the following persons from the `leadership` variable
    - [x] Eric J Cunningham
    - [x]  Anthony Navarro-Liu
    - [x] Dongchen Hou
    - [x] Joyce Chang
    - [x] Tammy Trinh
    - [x] Kelene Lee
    - [x] Sandra Berjan (The role has changed see the section below)
    - [x] Wataru Inoue (The role has changed see the section below)
- [x] Add the following persons `name`, `role`, `links`, and `picture` to the `leadership` variable (make sure you put the product manager first, then any leads, and then the non lead roles)
   - [x] Name: Yasaman Roostaeian
GitHub Handle: allthatyazz
Role: Product Manager
Slack Member ID: U033GFQ1UQM
    - [x] Name: Rachel Newcomb
GitHub Handle: rachelita2
Role: Lead UX Researcher
Slack Member ID: U03Q5J8SVM3
  - [x] Name: Sandra Berjan
GitHub Handle: sandraberjan
Role: Lead Content Designer
Slack Member ID: U03753VQBSR
  - [x] Name:  Khanh Cao
GitHub Handle: khanhcao17
Role: Co-Lead UX/UI Designer
Slack Member ID: U04A19TDBED
  - [x] Name: Debbie Nyasetia
GitHub Handle: kangina-tech
Role: Co-Lead UX/UI Designer
Slack Member ID: U03FJ3V58FN
  - [x] Name: Wataru Inoue
GitHub Handle: winoue90
Role:  UX Consultant
Slack Member ID: U02SMT4H4LR 
  - [x] Name: Faezeh Faezipour
GitHub Handle: fuzjan81 
Role: UX Researcher
Slack Member ID: U04AT8KU5CY
  - [x] Name: Eva Kwock
GitHub Handle: EvaKw 
Role: UX Researcher
Slack Member ID: U049PSE3ZMZ
  - [x] Name: Zeynep Aslan
GitHub Handle: zeaslan 
Role: UX Researcher
Slack Member ID: U04HDCMD90A
   - [x] Name: Gala Stojnic 
GitHub Handle: GalaStojnic 
Role: UX Researcher
Slack Member ID: U03307LRD2A
  - [x] Name: Eli Marietta 
GitHub Handle: elimarietta 
Role: UX Researcher
Slack Member ID: U03P6Q87BEZ   
  - [x] Name: Asad Haider
GitHub Handle: TobyShanti
Role: UX/UI Designer
Slack Member ID: U04H6Q4K5AS
   - [x] Name: Liz Zheng
GitHub Handle: liz-zheng 
Role: UX/UI Designer
Slack Member ID: U04GYRW4DAT
   - [x] Name: Michael Morgan
GitHub Handle: mklmrgn 
Role: UX/UI Designer
Slack Member ID: U01SPJCC26A
  - [x] Name: Robert Schacht
GitHub Handle: rsschacht
Role: Content Designer
Slack Member ID: U02R5GG3T09

- [x] Test the [Design Systems project page](https://www.hackforla.org/projects/design-systems) on your local development environment to ensure the changes are being displayed properly

### Instructions
- Be sure to use valid YAML syntax and match the existing structure of [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md)
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/
- For the github link, append the team member's github handle to https://github.com/
- For the picture URL, append the team member's github handle to https://avatars.githubusercontent.com/

### Resources
- [Design Systems project page](https://www.hackforla.org/projects/design-systems)
- [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Update your meeting times?
Yes

### If YES on update meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue
- https://github.com/hackforla/VRMS/issues/1248

### PR DESCRIPTION
**Pull request by steven-positive-tran**
Fixes #3731

### What changes did you make and why did you make them ?

Updated Project Details Page in hackforla website so that it remains up to date.

- Added Releases to Links
- Updated Project Profiles
- Removed persons from leadership and updated roles
- Added persons

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by jyaymie** [comment]
Review ETA: 2/7 7pm
Availability: 2/7 til 7pm

**Review by jyaymie — APPROVED** [review]
You were careful to organize the people in leadership based on role. All links worked just fine, and there was no break in the site given your changes. Fantastic work, @steven-positive-tran!

**Comment by jdingeman** [comment]
ETA: 2/8 EOD
Availability: 2 hrs

**Review by jdingeman — APPROVED** [review]
Changes made look good and pushing into the correct branch. Nice job, @steven-positive-tran!

**Pull request merged**
