### PR TITLE
Update project profile vrms 3694

### LINKED ISSUE #3694: Update Project Profile: VRMS
### Overview
As a developer, we need to ensure our project's details are up to date on the HackforLA website. We need to update the VRMS project's leadership to include the current team members and remove some of the old team members.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [vrms.md](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md) file and find the `leadership` variable.
- [x] Remove the following people from the `leadership` variable
    - [x] Alex Anakin
    - [x] Adam Spar
    - [x] Katiuska Alicea de Leon
    - [x] Glen Paul Florendo
    - [x] David Rubinstein
    - [x] Walter Tang
- [x] Add the following people to the `leadership` variable
    - [x] Name: Julia Gab
Github: juliagab56
Role: Lead UX Designer
Slack ID: U03AS9FBAAU
    - [x] Name: Judy Lee
Github: JudyLee533
Role: UX Designer
Slack ID: U03K7Q1FV3P
    - [x] Name: Alex Lee
Github: heyitsalexander
Role: Product Manager
Slack ID: U03PC4KKGAG
    - [x] Name: Amanda Glover
Github: AmandaGlover-PM
Role: Product Manager
Slack ID: U042G8B7RB3
    - [x] Name: Trillium Smith
Github: Spiteless
Role: Developer
Slack ID: U010G9864Q1

- [x] Update the value of Josh Bubar's `role` variable from "Shows up to meetings" to "Developer"
- [x] Check the [VRMS project page](https://www.hackforla.org/projects/vrms) on your local development environment to ensure the "Current Project Team" section is properly displaying the changes you made

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [The VRMS markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find a Slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

### PR DESCRIPTION
**Pull request by RyanGehris**
Fixes #3694

### What changes did you make and why did you make them ?

  - removed 6 members from leadership variable
  - added 5 members to leadership variable
  - updated Josh Bubar's role to "Developer"
  - This was done so that the VRMS Project Team listed on the VRMS project page is up to date

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-02-13 at 8 45 26 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-02-14 at 4 16 16 PM

</details>

### CODE REVIEW

**Comment by chrismenke45** [comment]
Review ETA: 2/15 12pm
Availability: 2/15 8am-12pm

**Review by chrismenke45 — APPROVED** [review]
Good work Ryan! Looks like all the leadership to be removed is gone, all the new leadership has been added, and the existing leadership has the correct changes.

**Comment by MattPereira** [comment]
**Availability:** 7 - 9 PM Sunday - Thursday
**ETA:** 5 minutes

**Review by MattPereira — APPROVED** [review]
Well done @RyanGehris :+1: 

Great attention to detail testing the slack links and good job communicating in the issue comments

**Pull request merged**
