### PR TITLE
Refactored img HTML tag in pages/events.html

### LINKED ISSUE #4445: img Tag Refactor: Events page(s)
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/events.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="" />
```
to
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/events.html
2. Webpage(s): https://www.hackforla.org/events/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by wKategianes**
Fixes #4445

### What changes did you make and why did you make them ?

- I changed an img HTML tag that was ending in a slash () to an img tag without a slash ().
- The file that was worked on was inside pages/events.html and now the img HTML tag is now consistent with the codebase.
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="" />
``` 
to
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="" >
```

### CODE REVIEW

**Comment by karengcecena** [comment]
ETA: 10am on 4/13 
Availability: 9-10 am 4/13

**Review by karengcecena — DISMISSED** [review]
Hi, [wKategianes](https://github.com/wKategianes). Thank you for taking the time to complete this issue. Your pull request is to and from the correct branches, you linked the issue correctly, you removed the slash that was asked for, and the website looks good on my local machine. 

Great job & thanks again for working on this issue!

**Comment by LOSjr4** [comment]
Availability: M,T,TH 9AM-1PM
ETA: today noon

**Review by LOSjr4 — COMMENTED** [review]
Although it doesn't affect anything, the instructions on the original issue had no space after (alt=""> instead of alt="" >). The correct slash was removed which is most important, but also removing the space would be perfection.

**Comment by blulady** [comment]
@wKategianes looks like a very clean first issue, Good Job!! However in the interests of uniformity in the website could you modify the PR as @LOSjr4 suggested and eliminate that extra space. Like he says, it has no real effect but it will drive some of the other Devs bananas.

**Comment by StephenTheDev1001** [comment]
Review ETA: EOD
Availability: 12 - 2pm M-F

**Comment by angieyan** [comment]
Review ETA: 4/18/2023
Availability: 1-3 PM

**Review by angieyan — APPROVED** [review]
Great job, @wKategianes! You have done everything correctly.

**Review by karengcecena — APPROVED** [review]
Hi, [wKategianes](https://github.com/wKategianes). Thank you going back and implementing the feedback [LOSjr4](https://github.com/LOSjr4) left you. Both the slash and space are removed now. 

And like before, your pull request is still to and from the correct branches, the issue is linked correctly and the website looks good on my end.

Great job again!

**Review by LOSjr4 — APPROVED** [review]
I received notification that this is ready for re-review. I see perfection. Thank you @wKategianes for going back and taking out that space.

**Pull request merged**
