### PR TITLE
Converted blank issue template to a form issue!

### LINKED ISSUE #2283: Convert Blank Issue Template to Github Form Issue
### Overview
As an issue creator, we want to implement issue templates for issue creation to streamline and simplify the process. The current issue forms require the person to replace the text, and is less user-friendly compared to GitHub Form issues.

### Action Items

- [ ] Create a blank-issue-form.yml file in this [folder ](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
- [ ] Add the code below to the file.
```
name: 'Blank Issue '
description: 'Standard HackforLA issue template '
title: ''
labels: ''
assignees: ''

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: dependency-explanation
    attributes:
      label: If Yes, please explain
```

- [ ] Rename the current blank-issue-.md file to blank-issue-template.md.

### Resources/Instructions
[Github Issue Forms Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Issue Forms Reading Pt2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
[#2128 ](https://github.com/hackforla/website/issues/2128)

### PR DESCRIPTION
**Pull request by usaboo**
Fixes #2283

### What changes did you make and why did you make them ?

  - Added an issue form blank-issue-form.yml in [website/.github/ISSUE_TEMPLATE/](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
  
#### containing the following code
  ```
name: 'Blank Issue '
description: 'Standard HackforLA issue template '
title: ''
labels: ''
assignees: ''

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: dependency-explanation
    attributes:
      label: If Yes, please explain
```

  - Renamed [blank-issue-.md](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-.md) to blank-issue-template.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
I don't think that there are any visual changes to the website per se but it does affect how we create issues.

### CODE REVIEW

**Comment by answebdev** [comment]
Review ETA: End of Day 3/1/2022
Availability: Monday (3 hours), Tuesday (3 hours)

**Review by answebdev — APPROVED** [review]
@usaboo Thank you for submitting your PR. For this issue, the code from the action item was to be added to a newly created blank-issue-form.yml file, which I can see that you did. Also, the current blank-issue-.md file was to be renamed to blank-issue-template.md, which I can also see that you did. You have also added this PR to the project board. Great job with this!

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1 hour
- Review ETA: Today (Tue, Feb, 28, 2022)

**Review by JessicaLucindaCheng — APPROVED** [review]
@usaboo Looks good to me!

**Pull request merged**
