### PR TITLE
Edit delegate fields 2815

### LINKED ISSUE #2815: Edit content field and remove type field from delegate.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/delegate.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/delegate.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/delegate.yml#L4
https://github.com/hackforla/website/blob/e980b70efb40f63c7c1d54595c0bc3b1ab0d3569/_data/internal/credits/delegate.yml#L11

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #2815

### What changes did you make and why did you make them?

  - The content field and the type field contain similar information, so removing the `type` field will remove the redundancy.
  - Changed the `content` field to `content-type` to have a clearer purpose.
  - Changed line 4 of the content field form from `content: icon` to `content-type: image`.
  - Removed line 11 `type: icon`.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Moving files to another directory. No visual changes to the website.

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 4 Hours
ETA: EOD 2022-07-25

**Comment by d-perez-8** [comment]
Provide Update
1. Progress: Finished, waiting for a review.
2. Blockers: None
3. Availability: Until 3 pm Pacific Time
4. ETA: End of day

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-26

**Review by BeckettOBrien — APPROVED** [review]
The changes look correct and the site looks good. Good job!

**Comment by KBWells77** [comment]
Availability: 2 Hours
ETA: EOD 2022-07-25

**Review by KBWells77 — APPROVED** [review]
Good job, everything looks correct in the code and on the website.

**Review by arpitapandya — APPROVED** [review]
The changes looks good! Great job!! @d-perez-8

**Pull request merged**
