### PR TITLE
Removed '/' from the step-img-icon img tag that wraps id.png

### LINKED ISSUE #4400: img Tag Refactor: Getting Started page - `step-img-icon id.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [ ] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/id.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/id.png" alt="">
```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by one2code**
Fixes #4400 

### What changes did you make and why did you make them ?

Removed the '/' from the step-img-icon img tag that wraps id.png, to maintain more consistent styling throughout the getting-started.html page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
N/A, changes are code only.  The id.png file displays correctly during testing in Docker at all screen sizes.

### CODE REVIEW

**Comment by graycodesnu** [comment]
ETA: EOD 4/17
Availability: 10 AM - 12 PM, 4/17

**Comment by roslynwythe** [comment]
Availability: 8 - 10 pm
ETA: EOD 4/17

**Review by graycodesnu — APPROVED** [review]
Hi @one2code! Great job working this issue. The branches were set up correctly and the correct change was made. You also stated the reason this change was made and provided the necessary info in your pull request. Thank you!

**Review by roslynwythe — APPROVED** [review]
Great job @one2code.  The branches are setup properly, the code change is correct and checks out in the browser and you provided an explanation of your work.  Thank you!

**Pull request merged**
