### PR TITLE
Upload .svg files #2483

### LINKED ISSUE #2483: Upload .svg files for various HfLA technologies into the assets/images directory
### Overview
We need to upload the .svg files for various HfLA technologies used in different projects so we can use them in the future.

### Action Items
- [x] Download the .svg files from the [Google Drive](https://drive.google.com/drive/u/1/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO)
- [x] Create a new directory under [assets/images](https://github.com/hackforla/website/tree/gh-pages/assets/images) called technologies-icons
- [x] Upload the .svg files into the newly created directory

### Resources/Instructions
- Source for this issue: #2130
- [assets/images directory](https://github.com/hackforla/website/tree/gh-pages/assets/images)
- Files location in the [Google Drive](https://drive.google.com/drive/u/1/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO)

### PR DESCRIPTION
**Pull request by lindseyindev**
Fixes #2483

### What changes did you make and why did you make them ?

  -Created a new directory under assets/images called technologies-icons
  -Uploaded .svg files from the Google Drive into that directory
  

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
N/A no visual changes

### CODE REVIEW

**Comment by lindseyindev** [comment]
There were 3 images in the google drive that were not .svg this could be a future issue, I'm not sure if it will affect their sizing and transparent backgrounds when the images are actually displayed on the site in the future.

The images were:
1280px-React-icon.svg.png
nosql-1.jpeg
nosql.png

@SAUMILDHANKAR @R-Tomas-Gonzalez

**Review by JessicaLucindaCheng — DISMISSED** [review]
@lindseyindev I see the technologies-icons has been added and all the images from the Google Drive folder have been added to that folder. Good job!

**Review by lopezpedres — DISMISSED** [review]
All 17 files were included in the right directory. Great job @lindseyindev LGTM!

**Comment by SAUMILDHANKAR** [comment]
@lindseyindev I agree with your comment. This can be a future issue. Let's not keep files with extensions other than svg in this folder. If required, we can add nosql and react svg icons later.

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
Please remove files that do not have svg extension.

**Comment by lindseyindev** [comment]
Merge team and reviewers:

I removed 3 files that were not true .svg from the /assets/images/technologies-icons folder
I added a React.svg I found to both that folder and the google drive folder
 delete mode 100644 assets/images/technologies-icons/1280px-React-icon.svg.png
 create mode 100644 assets/images/technologies-icons/React-icon.svg
 delete mode 100644 assets/images/technologies-icons/nosql-1.jpeg
 delete mode 100644 assets/images/technologies-icons/nosql.png

I could not locate .svgs of the 2 NoSql.png files

**Review by SAUMILDHANKAR — APPROVED** [review]
@lindseyindev Thanks for making the changes. I can see 15 svg files under the technologies folder moved from the google drive. Great job.

**Comment by SAUMILDHANKAR** [comment]
We have skipped moving nosql icon since it was not a svg file. I will bring this up in Sunday meeting and if required create a new issue to add that. Also, should we delete non svg files from that google folder? (needs discussion)

**Pull request merged**
