### PR TITLE
removed Bitian Zhang & Arpita Pandya

### LINKED ISSUE #4473: Update Project Profile: HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
  - [x] Remove Bitian Zhang
  - [x] Remove Arpita Pandya
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by 93Belen**
Fixes #4473

### What changes did you make and why did you make them ?

I removed  Bitian Zhang and Arpita Pandya from the leadership in Hackforla.org Website
This is the second pull request done with the same changes, since the first request was done from the wrong branch.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before changes

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
first isssue

</details>

### CODE REVIEW

**Comment by 93Belen** [comment]
Avail: Wed 2-4pm, Thur 10am-16pm

**Comment by bphan002** [comment]
Hi Belen,

Thank you for creating a new branch. For future reference, they like to have the issue number included in your title
Ex: update-project-profile-4643

I did run into an issue and not sure if its on my end.

Did you pull from the main gh-pages before creating your branch?

After I created a new branch and trying to pull from https://github.com/93Belen/website.git update-project-profile, I'm getting a divergent error and not sure if that is the cause of it or something on my end. 

@steven-positive-tran is that the case?

**Comment by 93Belen** [comment]
I created the branch in my repo so it has the same code as the previus pull request. Thank you for the clarification about the name!

**Comment by bphan002** [comment]
Can you try to pull/synchronize your branch with the main branch? I think that'll do the trick.

**Comment by 93Belen** [comment]
I just did, let me know how it goes :)

**Comment by bphan002** [comment]
I'm running into the same  issue I'll wait for either Steven to look at it or @mademarc since I'm not that experienced with PR reviews.

**Comment by blulady** [comment]
@steven-positive-tran & @mademarc if you guys could throw an eta on this so we could know when to expect a review?

**Review by bphan002 — APPROVED** [review]
The two members are removed on my browser and everything looks great.  I finally got it to work so it was an issue on my end. Sorry for all the confusion.

**Comment by 93Belen** [comment]
Thank you! 😄

**Comment by mademarc** [comment]
Review ETA: 4/12/2023
Availability: 7:45PM

**Review by steven-positive-tran — APPROVED** [review]
Thanks for making a new branch in your fork and placing your changes there.

Looks good on both firefox and edge on my machine and the code changes seem in line with the issue in hand

Thank you for taking up this issue.

**Review by mademarc — COMMENTED** [review]
Hey @93Belen  Good way to go in deleting the unnecessary elements make the UI of the page better and @steven-positive-tran take a look at it as well also thanks @blulady for the heads up.

**Comment by 93Belen** [comment]
Hey! I'm sorry I was trying to fix something and I deleted the repo to fork it again without realizing it would affect this request. What do you recommend me to do? I'm so sorry. I can do the pull request again but I dont want to do it until you guys tell me thats what I should do

**Comment by t-will-gillis** [comment]
This PR was closed and replaced by #4666, therefore moving this to column 'IGNORE: PRs closed without being merged'

**Pull request closed without merging**
