### PR TITLE
Issue #6258: Remove Sarah Sanger from the page projects/website

### LINKED ISSUE #6258: Update Project Profile: remove Sarah Sanger from HackforLA.org Website
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Delete the following lines from the file:
```
  - name: Sarah Sanger
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U02M686LYET'
      github: 'https://github.com/blulady'
    picture: https://avatars.githubusercontent.com/blulady
```
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by jonnyoe**
Fixes #6258 

### What changes did you make?
  - Removed Sarah Sanger from the website team 

### Why did you make the changes (we will use this info to test)?
  - Keeps the list of people on the website team current

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

![image]Screenshot 2024-03-01 at 11 26 47 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
![image]Screenshot 2024-03-01 at 11 27 06 PM

</details>

### CODE REVIEW

**Comment by robertnjenga** [comment]
Review ETA:  03/04/2024
Availability: 10am - 2pm

**Review by robertnjenga — CHANGES_REQUESTED** [review]
Hi @jono4727,
Thanks for making the requested changes, the branching, description of what you did and why, and your code changes are correct,
however the link should be to the original issue, #6258. Re-request my review after making that small edit. Thank You!

**Review by robertnjenga — APPROVED** [review]
@jono4727 
Everything looks good. Thanks for your patience with the edits. Great Job!

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 3/4/24

**Review by Thinking-Panda — APPROVED** [review]
@jono4727 , Thank you for working on this issue. PR description is detailed. Merge branches are setup correctly. Code changes are as mentioned in the issue and website works well on my local machine. Well done! Approved!

**Pull request merged**
