### PR TITLE
 Food oasis .md file refactored

### LINKED ISSUE #4805: Refactor Tools data for food-oasis.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Photoshop, Sketch, whiteboard / paper & pencil, phone calls, paper prototyping, Google forms, Google Sheets, Google Analytics, FigJam, SPSS, Mplus, AtlasTI, Usabilityhub.com surveys

```
to
```
tools:
  - Figma
  - Photoshop
  - Sketch
  - whiteboard / paper & pencil
  - phone calls
  - paper prototyping
  - Google forms
  - Google Sheets
  - Google Analytics
  - FigJam
  - SPSS
  - Mplus
  - AtlasTI
  - Usabilityhub.com surveys
```
  - [ ] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by awellsbiz**
Fixes #4805 

### What changes did you make?
  - Changed tools data for `food-oasis.md `file from a string to list 

### Why did you make the changes (we will use this info to test)?
  - To include a dropdown for 'Tools' for the filter menu on the 'projects-check' page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by evanhesketh** [comment]
Availability: Aug 4, 10am-12pm pst
ETA: 08/04 EOD

**Comment by steven-positive-tran** [comment]
Availability: 6-12pm pst
ETA: 08/03 EOD

**Review by steven-positive-tran — APPROVED** [review]
Branches look from your fork to the main gh-pages, works on my device, and code changes seem in line with the issues that need to be addressed. 

Looks good and thank you for taking up this issue.

**Review by evanhesketh — COMMENTED** [review]
As noted by the previous reviewer, branching is done correctly, issue is linked, the changes appear correctly in the browser, and the changes address the issue. 
Please consider adding before/after screenshots of the website to your pull request to help reviewers visualize the changes you have made. Otherwise, great work!

**Comment by awellsbiz** [comment]
Sounds good! Thanks for the review

**Review by adrianang — APPROVED** [review]
Hi @awellsbiz — the branching is set up correctly, the corresponding issue has been linked to, and the requested change of refactoring the Tools into a list for Food Oasis has been made exactly as asked in the issue. In testing your branch on my local environment through Docker, the views for Food Oasis do not appear to be visually or functionally affected, as expected.

Good job figuring out the workflow from your previous PR; this PR is looking a lot cleaner in the commit history now! One thing that I would say is that your PR submissions should either include a photo if there is a visual change, or not have the image section at all, instead of having broken photo links; something to keep in mind for your next PR(s).

Thank you for taking up this issue! 🙌🏼

**Comment by awellsbiz** [comment]
Hey @adrianang,

Noted.
Thanks,
AW

**Pull request merged**
