### PR TITLE
Updated content field and removed type field in credits/review.yml

### LINKED ISSUE #2860: Edit content field and remove type field from review.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/review.yml`, do the following:
- [x] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [x] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/review.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/review.yml#L4
https://github.com/hackforla/website/blob/7164ec247825adca279d4fd99fa52895335badbb/_data/internal/credits/review.yml#L11

### PR DESCRIPTION
**Pull request by angelenelm**
Fixes #2860
### What changes did you make and why did you make them?
Per the action items:
- Changed line 4 for the content field from
```
content: icon
```
to
```
content-type: image
```
- Removed line 11 for the type field
<strike>

```
type: icon
```

</strike>

### Screenshots of proposed changes of the website (if any, please do not screenshot code changes)
- No visual changes to the website.

### CODE REVIEW

**Comment by d-perez-8** [comment]
ETA: 1 hour
Availability: 3:30 pm to 6 pm weekdays

**Review by d-perez-8 — APPROVED** [review]
Thank you for taking on this issue! You have completed the issue correctly and the website does not break.

Great job!

**Comment by Suman2795** [comment]
Review ETA: 1 hour
Avaialbility: 15/11/2022

**Comment by jyaymie** [comment]
Review ETA: 11/14/22 11pm
Availability: 11/14/22 1 hour

**Review by jyaymie — APPROVED** [review]
You successfully made the changes requested in the linked issue, and your PR was done on the correct branch. Awesome work, @angelenelm!

**Review by Suman2795 — APPROVED** [review]
Your changes are done correctly and to right branch. Good job!

**Review by Skydodle — APPROVED** [review]
Your update to the content field was done correctly and pull request documented well. Great job @angelenelm!

**Pull request merged**
