### PR TITLE
Update Website project profile

### LINKED ISSUE #6294: Update Project Profile: Add Nayan Bhatt to Website Team
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated so that the project information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
- [x] Add the new team members `name`, `github-handle`, `role`, `slack` link, `github` link, and `picture` to the end of the `leadership` variable
```
  - name: Nayan Bhatt
    github-handle: freaky4wrld
    role: Merge Team
    links:
      slack: 'https://hackforla.slack.com/team/U05TZLLJAUV'
      github: 'https://github.com/freaky4wrld'
    picture: https://avatars.githubusercontent.com/freaky4wrld
    
```

- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### PR DESCRIPTION
**Pull request by howdyjessie**
Fixes #6294 

### What changes did you make?
  - Added Nayan Bhatt to website team

### Why Did You Make These Changes?
The Hackforla.org Website project page needs to be updated so that the project information is up to date.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-02-19 at 4 31 14 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2024-02-19 at 4 32 08 PM

</details>

### CODE REVIEW

**Comment by pdimaano** [comment]
ETA: 2/23/24
Availability: Weekday evenings

**Comment by w1ld-r** [comment]
ETA: 2024-02-20
Availability: Weekdays 10AM to 8PM CST

**Review by w1ld-r — APPROVED** [review]
Thanks for working on this, @howdyjessie!

- Your branch is correct
- The issue is correctly linked from your PR
- You made the appropriate changes to the correct lines
- Your PR clearly states the changes you made, and you included before and after images
- I was able to view your changes locally to confirm they are consistent across desktop and mobile devices on chrome and firefox

Approved! Great work and thanks again :)

**Review by SteeRevo — APPROVED** [review]
Hi @howdyjessie ,

Your branch was correct and the issue was linked correctly. I was also able to check on the site locally as well as on the source code and verified that your changes fulfill the criteria given on the issue. I think the only problem is that in your first comment you are missing the Why Did You Make These Changes? section. Otherwise, this is approved!

**Comment by howdyjessie** [comment]
Thanks for taking the time to review this @gaylem @SteeRevo 🙇‍♀️ 

@SteeRevo You're right, I missed that section in my haste. I have just updated my comment to explain the changes.

**Comment by LRenDO** [comment]
Hi @howdyjessie! 

Great work! Thanks for contributing! I am going to go ahead and merge this, but I do have one non- functional request. 

Please update the why section of the PR comment to describe why we as developers are making the changes. When we answer the "Why did you make the changes" section we are looking for the reason why the issue was created to make the changes.  This can usually be found in the `Overview` section of the original issue.  In this case, "The Hackforla.org Website project page needs to be updated so that the project information is up to date." 

Thanks again for contributing!

**Comment by howdyjessie** [comment]
@LRenDO Thank you for merging in my branch. That Overview statement is definitely lot more informative than what I had originally - I've updated my comment with it.

**Comment by LRenDO** [comment]
Perfect! Thank you for updating it @howdyjessie!

**Pull request merged**
