### PR TITLE
Add github handle field

### LINKED ISSUE #6733: Add github-handle for John Darragh in food-oasis.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: John Darragh
```
with
```
- name: John Darragh
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by jazxbx**
Fixes #6733 

### What changes did you make?
  -Add github handle field to John Darragh's entry

### Why did you make the changes (we will use this info to test)?
-This variable will eventually replace github and picture variables to reduce redundancy in the project file.

No visual changes to the website.

### CODE REVIEW

**Comment by terrencejihoonjung** [comment]
Review ETA: 11:59PM (PST) 5/29/24
Availability: 10AM-10PM (Mon-Fri)

**Comment by LRenDO** [comment]
Hi @ino-iosdev! Thanks for volunteering to review this issue! When you have a minute, please add your ETA and Availability.

**Comment by LRenDO** [comment]
Hi @jazxbx! Thanks for working on this issue! With regards to reviewers, unless we have had a conversation with someone and they agree to review a particular PR, we don't generally don't add other people as reviewers. If you had a conversation like that with @93Belen, great! Otherwise, please go ahead and remove them as reviewer. Thanks!

**Comment by ino-iosdev** [comment]
Review ETA: 6 PM 5/29
Availability: Flexible except for Wedn. afternoon till end of June.

**Comment by jazxbx** [comment]
@LRenDO Ahh I see! Thanks so much for clearing that up. I removed Belen!

**Comment by jazxbx** [comment]
> Review ETA: 11:59PM (PST) 5/29/24 Availability: 10AM-10PM (Mon-Fri)

Hi @terrencejihoonjung thanks for your time! Do you want me to be around when doing the review? I didnt see any documentation regarding reviews. I'm available today from 6PM - 10PM. Thanks again

**Review by ino-iosdev — APPROVED** [review]
Hi @jazxbx , It's such a blessing to have you as part of the team here!

- Naming was appropriate 
- Direction between branches "from" and "to" are clear
- The changes and why were clear
- PR issue link was clear
- No visual changes to the website 

Great job, thank you for contributing!

**Review by terrencejihoonjung — CHANGES_REQUESTED** [review]
Hi @jazxbx, great work! 
- the branching was done correctly
- the Issue number was listed/linked
- the "github-handle" variable was properly added
- project webpage remains unchanged at all screen sizes

Changes Requested:
- make sure to state why you made the changes in your PR. This will be important for future PRs that have greater complexity! However, your PR title and statement of changes done are clear and direct.

In regards to your comment https://github.com/hackforla/website/pull/6901#issuecomment-2138226452, you are good! PR reviews are usually done asynchronously at the reviewer's convenience. Once approved, you are good to move on to the next issue~ 

Here are some links for your reference:
- How to Review Pull Requests: https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests#Feedback
- Good Example of a Review/Approval: https://github.com/hackforla/website/pull/6887#pullrequestreview-2075530707
- Making Pull Requests: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests

Thank you!

**Comment by jazxbx** [comment]
> Hi @jazxbx , It's such a blessing to have you as part of the team here!
> 
> * Naming was appropriate
> * Direction between branches "from" and "to" are clear
> * The changes and why were clear
> * PR issue link was clear
> * No visual changes to the website
> 
> Great job, thank you for contributing!

Thanks so much! Excited to work with everyone!🙌

**Comment by jazxbx** [comment]
@terrencejihoonjung Added the requested change! Thanks for the references as well!

**Comment by LRenDO** [comment]
> @LRenDO Ahh I see! Thanks so much for clearing that up. I removed Belen! 
> 
> 

Perfect! Thanks!

**Comment by jphamtv** [comment]
Hey @jazxbx, make sure to re-request reviews from the original reviewer after you have made the requested changes by clicking on the circular arrows icon next to their names. I have done this for you so this is just for future reference. Thanks!
Screenshot 2024-05-30 at 10 59 55

**Comment by del9ra** [comment]
Review ETA: 05/31/2024
Availability: 1-5 PM Friday

**Review by del9ra — CHANGES_REQUESTED** [review]
Hey @jazxbx ,
* The pull request is done with the correct branch
* Can you please remove this issue https://github.com/hackforla/website/issues/6730 from the Development section. This is the correct issue https://github.com/hackforla/website/issues/6733
* Please check off the Action Items when working on issues to indicate you have completed them.
* The PR clearly tells us what changes were made and why
* I will be happy to approve it after the changes are implemented.
Nice work! Well done!

**Comment by jazxbx** [comment]
> Hey @jazxbx, make sure to re-request reviews from the original reviewer after you have made the requested changes by clicking on the circular arrows icon next to their names. I have done this for you so this is just for future reference. Thanks! Screenshot 2024-05-30 at 10 59 55

Thanks so much!

**Comment by jazxbx** [comment]
> Hey @jazxbx ,
> 
> * The pull request is done with the correct branch
> * Can you please remove this issue [Add github-handle for Bryon Heart in engage.md #6730](https://github.com/hackforla/website/issues/6730) from the Development section. This is the correct issue [Add github-handle for John Darragh in food-oasis.md #6733](https://github.com/hackforla/website/issues/6733)
> * Please check off the Action Items when working on issues to indicate you have completed them.
> * The PR clearly tells us what changes were made and why
> * I will be happy to approve it after the changes are implemented.
>   Nice work! Well done!

Done! 🙌

**Comment by del9ra** [comment]
@jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.

**Comment by jazxbx** [comment]
> @jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.

Hey just making sure I'm getting this. Did you want me to check this off? 
Once the pr is approved, this should automatically close the issue.
image

**Review by terrencejihoonjung — APPROVED** [review]
Hey @jazxbx! Thanks, looks great! I also would note that you should check off your finished tasks within the issue #6733. I see that @del9ra has requested this change, so I'll leave the request for that change to theirs! 

Good work!

**Comment by del9ra** [comment]
> > @jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.
> 
> Hey just making sure I'm getting this. Did you want me to check this off? Once the pr is approved, this should automatically close the issue. image

Mark up action items on this page https://github.com/hackforla/website/issues/6733

**Comment by jazxbx** [comment]
> > > @jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.
> > 
> > 
> > Hey just making sure I'm getting this. Did you want me to check this off? Once the pr is approved, this should automatically close the issue. image
> 
> Mark up action items on this page #6733

Ohh thanks for the clarification! Marked as done!

**Comment by ino-iosdev** [comment]
> > > > @jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.
> > > 
> > > 
> > > Hey just making sure I'm getting this. Did you want me to check this off? Once the pr is approved, this should automatically close the issue. image
> > 
> > 
> > Mark up action items on this page #6733
> 
> Ohh thanks for the clarification! Marked as done!

@jazxbx I just moved it back from project board aka undid your action on #6733 because I believe what they are saying is to check off the tasks here:

Screenshot 2024-06-01 at 9 21 00 PM

**Comment by jazxbx** [comment]
> > > > > @jazxbx you forgot to check off the Action Items on the issue page. Please do this, and I'll approve.
> > > > 
> > > > 
> > > > Hey just making sure I'm getting this. Did you want me to check this off? Once the pr is approved, this should automatically close the issue. image
> > > 
> > > 
> > > Mark up action items on this page #6733
> > 
> > 
> > Ohh thanks for the clarification! Marked as done!
> 
> @jazxbx I just moved it back from project board aka undid your action on #6733 because I believe what they are saying is to check off the tasks here:
> 
> Screenshot 2024-06-01 at 9 21 00 PM

Ahhh I see.. Mb ✌️Marked. Thanks for the images 😭

**Review by del9ra — APPROVED** [review]

**Pull request merged**
