### PR TITLE
Update alt text for the Guides Team image

### LINKED ISSUE #4006: Guides Team: Update alt text for Guides Team image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Guides Team` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/guides-team.md`:

**From:**
```
Globe Map made of dots and hackforla logo and text reading Guides Team
```

**To:**
```
Guides Team
```

**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/guides-team

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/guides-team.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by annierm18**
Fixes #4006 

### What changes did you make and why did you make them ?

  - Changed the image alt property value within _projects/guides-team.md to Guides Team, making the alt text more clear and descriptive so that we can adhere to WCAG standards

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visual changes to website.

### CODE REVIEW

**Review by maryjng — APPROVED** [review]
Changes are as requested by the issue. Looks good.

**Comment by steven-positive-tran** [comment]
Review ETA: 10PM 2/26/23
Availability: 1Hr

**Review by steven-positive-tran — APPROVED** [review]
Looks good the alt text has been changed correctly to 'Guides Team' and the correct files is changed.

**Comment by Thinking-Panda** [comment]
Availability: 10 AM - 3PM M-F
ETA: 2/28

**Review by Thinking-Panda — APPROVED** [review]
Hi @annierm18 , changes are made to guides-team.md as mentioned in the issue. Nice work!

**Comment by Adastros** [comment]
Hi @annierm18 good job on completing the issue! Just wanted to note that if the github-actions bot leaves a message on the issue you're working on and adds the `To Update !` label to remove it from the issue (and possibly a linked pull request) once you've provided an update. I went ahead and removed the label so you're good to work on your next issue!

**Pull request merged**
