### PR TITLE
New pages directory and repo clean up

### LINKED ISSUE #1255: Change Join Us page URL
### Overview
We need to change the [Join Us page](https://www.hackforla.org/join-us) URL from "join-us" to "**join**", to keep it consistent with the [About page](https://www.hackforla.org/about) URL, and the upcoming nav bar

### Action Items
- [ ] Research how to change page URL on the HfLA site
- [ ] Change the Join Us page URL from "join-us" to "join" (from https://www.hackforla.org/join-us to https://www.hackforla.org/join )

### Resources/Instructions
[Join us page](https://www.hackforla.org/join-us)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

### PR DESCRIPTION
**Pull request by akibrhast**
Please refer to the commit message in regards to what has been changes

This pull request is a  to test the feasibility of the changes asked in https://github.com/hackforla/website/issues/1138

It also tries to do some clean up work
Please pull this branch for test purposes and try hardest to break it! If possible this should be merged before we start getting in more issues and prs

Closes #1255

### CODE REVIEW

**Review by drubgrubby — COMMENTED** [review]
@akibrhast -> That looks pretty great.  I wasn't able to break it, or really to find anything at all that doesn't look like the current site. 

That said, there's a weird thing going on where there's a second wins directory that's showing all of these files with a .icloud extension.  ????

<details>
<summary>Weird wins directory</summary>
Screen Shot 2021-03-18 at 4 52 02 PM
</details>

I'm guessing this is just on my machine. I tried deleting the branch, restarting everything, and downloading the branch again, and it's still there.  Does anyone else get this?

**Comment by akibrhast** [comment]
> @akibrhast -> That looks pretty great. I wasn't able to break it, or really to find anything at all that doesn't look like the current site.
> 
> That said, there's a weird thing going on where there's a second wins directory that's showing all of these files with a .icloud extension. ????
> 
> Weird wins directory
> Screen Shot 2021-03-18 at 4 52 02 PM
> I'm guessing this is just on my machine. I tried deleting the branch, restarting everything, and downloading the branch again, and it's still there. Does anyone else get this?

It's a mac thing -I believe @drubgrubby >

https://stackoverflow.com/questions/62385234/git-keeps-duplicating-files-and-appending-2-at-end-of-filename
https://stackoverflow.com/questions/59308049/icloud-drive-desktop-sync-vs-git-deleted-files-reappear-and-duplicates-with-n

**Review by cnk — CHANGES_REQUESTED** [review]
The toolkit resources are not data in the way the other items are data. Please move them back out of the data subdirectory - either back to _toolkitResources, or even better to a name that isn't camelCase

**Comment by akibrhast** [comment]
There was a discussion between me and @cnk over slack regarding this issue. For documentation purposes I am going to paste the content of the discussion below. The conclusion of that discussion was

### So make this PR a consistent change to move pages into a subdirectory. Get that approved. Then refactor the current data into data/external (including fixing the GH actions that populate it) Then as a 3rd step a new proposal to reorganize the data-only collections under a data subdirectory

<details>
<summary>Discussion details as copy pasted from slack DM's</summary>

[Discussion.pdf](https://github.com/hackforla/website/files/6173429/Discussion.pdf)



</details>

**Review by cnk — APPROVED** [review]

**Pull request merged**
