### PR TITLE
Created blank issue form with no dependency

### LINKED ISSUE #2954: Create a blank issue form with no dependency
### Overview
As a developer, I want to create a blank issue form for issues with no dependencies as the forms (compared to templates) in some cases, are easier and more intuitive in creating a new issue.

### Action Items
- [x] Review [blank issue form](https://github.com/hackforla/website/blame/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml) yml file as well as the [blank issue form](https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml)
- [x] In a new topic branch of your own repo, create a new file in the directory `website/.github/ISSUE_TEMPLATE` titled "blank-issue-form-with-no-dependency.yml"
- [x] Copy and paste all the code from [blank issue form](https://github.com/hackforla/website/blame/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml) yml file to your newly created yml file except lines 26-38.
- [x] Change the title and description in lines 1 and 2 (in your newly created yml file):

from
```
name: 'Blank Issue '
description: 'Standard HackforLA issue template '
```
to
```
name: 'Blank Issue Form with No Dependency'
description: 'Standard HackforLA issue form with no dependency'
```
- [x] Please add a preview screenshot of the newly created form.
- [x] Push the changes and make a pull request
- [x] Once the pull request associated with this issue is approved and merged, please update and edit issue #2904 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please do the following for issue #2904:
    - [ ] Move it to the New Issue Approval column
    - [ ] Remove the "Dependency" label from it
    - [ ] Add a "ready for dev lead" label to it

### Resources/Instructions
- [Blanks issue form yml file](https://github.com/hackforla/website/blame/gh-pages/.github/ISSUE_TEMPLATE/blank-issue-form.yml)
- [Blank issue form](https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-form.yml)
- Directory where file needs to be created `website/.github/ISSUE_TEMPLATE`

### LINKED ISSUE #3098: Change alt text for card image in open community survey md file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the open community survey project card image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `_projects/open-community-survey.md`, change line 77 for the alt text:

from
```
card-image-alt: open community survey project card
```
to
```
card-image-alt: 
```
- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `_projects/open-community-survey.md`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/_projects/open-community-survey.md?plain=1#L99

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by carolemlago**
Fixes #2954

### What changes did you make and why did you make them ?

  - Reviewed blank issue form yml file and blank issue form.
  - Created a blank issue form with no dependencies by copying from previous file.
  - Modified lines 1 and 2, and deleted lines 26-38.
 
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Screen Shot 2022-09-28 at 5 05 35 PM

### CODE REVIEW

**Comment by jdingeman** [comment]
ETA: EOD 9/28/2022
Availability: 4hrs

**Comment by jdingeman** [comment]
Hi @carolemlago, can you please verify you've linked the correct issue? #3098 [Change alt text for card image in open community survey md file](https://github.com/hackforla/website/issues/3098)

**Review by jdingeman — APPROVED** [review]
Looks good! Double checked the synatx with [YAMLint](http://www.yamllint.com/) and it came out clean. Nice job!

**Comment by carolemlago** [comment]
> #3589



> Hi @carolemlago, can you please verify you've linked the correct issue? #3098 [Change alt text for card image in open community survey md file](https://github.com/hackforla/website/issues/3098)


Just fixed. Thank you @jdingeman

**Review by kathrynsilvaconway — DISMISSED** [review]
@carolemlago Nice work. Everything looks clean. This PR seems to be linked to itself. At the top of the page, please change the link to the number for the issue, not the PR. Be sure to request a re-review after you make this change and I will approve it.

**Comment by arpitapandya** [comment]
ETA: EOD 2022-09-30
Availability: 20 minutes

**Review by arpitapandya — APPROVED** [review]
Thank you for making all the changes and adding a link to the issue. Great job! @carolemlago

**Pull request merged**
