### PR TITLE
add github-handle to member Tan Zhou

### LINKED ISSUE #6192: Add new variable github-handle to member Tan Zhou in civic-opportunity-project.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [ ] Open the file `_projects/civic-opportunity-project.md` in the IDE
- [ ] Replace:
```
- name: Tan Zhou
```
with
```
- name: Tan Zhou
  github-handle: 
```
- [ ] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [ ] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-opportunity-project.md
Project Webpage: https://www.hackforla.org/projects/civic-opportunity-project
- This issue is part of #5441

### PR DESCRIPTION
**Pull request by angela-lee1**
Fixes #6192

### What changes did you make?
  - add GitHub-handle variable for member Tan Zhou
  - made chage in civic-opportunity-project.md
  -

### Why did you make the changes (we will use this info to test)?
  -  creating a single variable github-handle to hold the GitHub handle for each member of the leadership team.
  -  Eventually, github-handle will replace the GitHub and picture variables, reducing redundancy in the project file.
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes to the website.

### CODE REVIEW

**Comment by njackman-2344** [comment]
@awlFCCamp The change in code looks good as I pulled it into docker. 

I see in #6192, spaces instead of tab for .yml

Before I approve review, I see inconsistent comment style under visuals with 404 links. If no visual change, please comment underneath with no visual change under screenshots heading :). Thanks!

**Comment by angela-lee1** [comment]
@njackman-2344 Thank you for reviewing my PR. I have updated my PR, removed<details> and <summary>, and replaced them with an explanation of no visual changes to the website. 
    On Friday, February 2, 2024 at 08:28:53 PM CST, njackman-2344 ***@***.***> wrote:  
 
 


@awlFCCamp The change in code looks good as I pulled it into docker.

I see in #6192, spaces instead of tab for .yml

Before I approve review, I see inconsistent comment style under visuals with 404 links. If no visual change, please comment underneath with no visual change under screenshots heading :). Thanks!

**Comment by elliot-d-kim** [comment]
Hey @awlFCCamp, this is looking pretty good!

- Branches and naming was done properly,
- issue is linked, and
- code looks clean and accurate!

Just a couple of suggestions:

- A little more detail would make your summary great (e.g., the file you made this change in). Also, to answer why the changes were made, consider what problem your changes are solving. I would look at the Overview in the issue to get a better understanding. Refer to this section for an example of a good summary: [3.1.b.iii Complete pull request (3): Explain the changes you made, then explain why these changes were needed](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iii-complete-pull-request-3-explain-the-changes-you-made-then-explain-why-these-changes-were-needed)
- I'm unable to see the before and after screenshots included in this post. Hopefully this section will help with that: [3.1.b.iv Complete pull request (4): Include images (if available)](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#iv-complete-pull-request-4-include-images-if-available)

Let me know if you need clarification!

**Comment by angela-lee1** [comment]
@elliot-d-kim Thank you for reviewing my PR. I added information about the modified file and the reason for the change. There are no visual changes to the website, so I followed the instructions deleted <details> and <summary>, and added the comment of no visual changes to the website. 
    On Friday, February 2, 2024 at 08:59:18 PM CST, elliot-d-kim ***@***.***> wrote:  
 
 


Hey @awlFCCamp, this is looking pretty good!
   
   - Branches and naming was done properly,
   - issue is linked, and
   - code looks clean and accurate!

Just a couple of suggestions:
   
   - A little more detail would make your summary great (e.g., the file you made this change in). Also, to answer why the changes were made, consider what problem your changes are solving. I would look at the Overview in the issue to get a better understanding. Refer to this section for an example of a good summary: 3.1.b.iii Complete pull request (3): Explain the changes you made, then explain why these changes were needed
   - I'm unable to see the before and after screenshots included in this post. Hopefully this section will help with that: 3.1.b.iv Complete pull request (4): Include images (if available)

Let me know if you need clarification!

**Comment by elliot-d-kim** [comment]
I accidentally posted my review as a comment so I deleted it. I see that you've responded to it (I guess it was still available in your email inbox) and I'll formally review the PR properly by the end of the day! Thanks for understanding.

**Review by elliot-d-kim — APPROVED** [review]
Hey @awlFCCamp, this is looking pretty good!

- Branches and naming was done properly,
- issue is linked, and
- code looks clean and accurate!

The summary is in great shape after the adjustments you made: good detail and reasoning. Thanks for also cleaning up the screenshots section!

By the way, no need to keep any empty bullet points. Deleting them would make your PR cleaner -- just something to keep in mind moving forward.

Thanks again and nice work, I'm happy to approve this :)

**Review by njackman-2344 — APPROVED** [review]
Branches and naming looks good and accurate
issue is linked
code great
Thank you for comment consistency with no screenshot changes at bottom
PR Approved

**Pull request merged**
