### PR TITLE
SDG 16: Rename and replace image with correct color one

### LINKED ISSUE #4253: SDG 16: Rename and replace image with correct color one
### Dependency
- #4183 

### Overview
We need to replace the Sustainable Development Goals (SDG) images in our repository so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf). 

### Details
SDG is an acronym for the [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals).

### Action Items
- [x] In the `assets/images/sdg` directory, delete `peace-justice.svg`
- [x] From the HackforLA.org website drive's [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML) folder, download the following svg: `E-WEB-Goal-16.svg`
- [x] Add the svg you just downloaded into the `assets/images/sdg` directory
- [x] Rename that svg so that it becomes `sdg16.svg`
- [x] In `_includes/about-page/about-card-sustainability.html`, update the path to the image you just added by changing
```
<img src="/assets/images/sdg/peace-justice.svg" alt="16 Peace, Justice and Strong Institutions" />
```
to
```
<img src="/assets/images/sdg/sdg16.svg" alt="16 Peace, Justice and Strong Institutions" />
```
- [x] Update the path to the SVG by changing 
  ```
  sdg-image-src: /assets/images/sdg/peace-justice.svg
  ```
  to 
  ```
  sdg-image-src: /assets/images/sdg/sdg16.svg
  ```
  in the following files:
  - [x]  _projects/311-data.md
  - [x]  _projects/access-the-data.md
  - [x]  _projects/engage.md
  - [x]  _projects/open-community-survey.md
- [x] Using Docker, check the following pages to check that the SDG image shows up on the same spot as on the live webpage
  - Note: The size of the image may look different compared to the website. This will be addressed in issue #4229. 
  - [x] About page's Sustainability section: https://www.hackforla.org/about/#sustainability
  - [x] Citizen Engagement page: https://www.hackforla.org/citizen-engagement
  - [x] 311 Data: https://www.hackforla.org/projects/311-data
  - [x] Access the Data: https://www.hackforla.org/projects/access-the-data
  - [x] Engage: https://www.hackforla.org/projects/engage
  - [x] Open Community Survey: https://www.hackforla.org/projects/open-community-survey 

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to each of the following issues and check if all the issues listed under the `Dependency` section are closed. If the dependencies are all closed, move those issues into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.
  - [x] #4187 
  - [x] #4229

### Resources/Instructions
- [assets/images/sdg](https://github.com/hackforla/website/tree/gh-pages/assets/images/sdg) directory
- [HackforLA.org website/SDG/SDG images](https://drive.google.com/drive/folders/1kJdguLXnIRv13IRh_4v4lrYDG7K4FbML)
- [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- [_projects/311-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md?plain=1)
- [_projects/access-the-data.md](https://github.com/hackforla/website/blob/7770fdeaa68f44c6ceb32866a24b903ad52c2019/_projects/access-the-data.md?plain=1)
- [_projects/engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md?plain=1)
- [_projects/open-community-survey.md](https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md?plain=1)
- This issue is tracked in #4153
#### Pages to check
- About page's Sustainability section: https://www.hackforla.org/about/#sustainability
- Citizen Engagement page: https://www.hackforla.org/citizen-engagement
- 311 Data: https://www.hackforla.org/projects/311-data
- Access the Data: https://www.hackforla.org/projects/access-the-data
- Engage: https://www.hackforla.org/projects/engage
- Open Community Survey: https://www.hackforla.org/projects/open-community-survey
#### United Nations' SDG Information
- [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf)
- [United Nations' SDG Communications materials](https://www.un.org/sustainabledevelopment/news/communications-material/)
- [United Nations Development Programme Sustainable Development Goals](https://www.undp.org/sustainable-development-goals)

### PR DESCRIPTION
**Pull request by cng008**
Fixes #4253

### What changes did you make and why did you make them ?

  - Replaced the Sustainable Development Goals (SDG) images so that the SDG svgs are the correct color and follow the [United Nations' SDG guidelines](https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf).
    - Deleted `peace-justice.svg` from the `assets/images/sdg` directory
    - Added `sdg16.svg` to the `assets/images/sdg` directory
  - Updated the path to the SVG in the following files:
    - _includes/about-page/about-card-sustainability.html
    -  _projects/311-data.md
    -  _projects/access-the-data.md
    -  _projects/engage.md
    -  _projects/open-community-survey.md

### Things to note:
 - 311 Data: https://www.hackforla.org/projects/311-data
    - background of color is different now that the SVG image color has changed
 - Access the Data: https://www.hackforla.org/projects/access-the-data
    - image does not exist on this page
 - Engage: https://www.hackforla.org/projects/engage
    - background of color is different now that the SVG image color has changed
 - Open Community Survey: https://www.hackforla.org/projects/open-community-survey
    - background of color is different now that the SVG image color has changed

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

sdg-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
sdg-after

</details>

### CODE REVIEW

**Review by RyanGehris — CHANGES_REQUESTED** [review]
I noticed that there is a merge conflict in your code. Here is a [resource](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) on resolving merge conflicts that might be helpful. Please look into it, and then I will be able to approve your changes. Thank you for all the work you have done so far on this issue!

**Comment by cng008** [comment]
@RyanGehris Thanks for the heads up! I hope I was able to fix the merge conflict. Let me know if there are any issues.

**Review by RyanGehris — CHANGES_REQUESTED** [review]
The merge conflicts look like they were resolved, but now there is no img element for sdg16.svg that is meant to replace peace-justice.svg in the file _includes/about-page/about-card-sustainability.html

Here are screenshots of what I am seeing when viewing https://www.hackforla.org/about/#sustainability on my local computer. 

<details>
<summary>Current About Page</summary>

Screenshot 2023-04-13 at 5 12 15 PM

</details>
<details>
<summary>About Page after your changes</summary>

Screenshot 2023-04-13 at 5 12 24 PM

</details>

The changes you made to these pages are great!
  - [x] Citizen Engagement page: https://www.hackforla.org/citizen-engagement
  - [x] 311 Data: https://www.hackforla.org/projects/311-data
  - [x] Access the Data: https://www.hackforla.org/projects/access-the-data
  - [x] Engage: https://www.hackforla.org/projects/engage
  - [x] Open Community Survey: https://www.hackforla.org/projects/open-community-survey

**Comment by cng008** [comment]
@RyanGehris Good catch! I swear that was there when I merged it. I've added back the SVG, however the empty line at the end of the file was deleted for some reason. If this is an issue, let me know and I can try and fix it.

**Review by RyanGehris — DISMISSED** [review]
Great work! The correct changes are made and the website looks as intended. Thank you for working on this issue!

**Comment by mademarc** [comment]
Review ETA: 4/20/2023
Availability: 7:15PM

**Review by mademarc — DISMISSED** [review]
Hey @cng008  the svg image was added well on the img elements correctly and  it looks good

**Comment by blulady** [comment]
> Great work! The correct changes are made and the website looks as intended. Thank you for working on this issue!

Thanks for thoroughly reviewing this @RyanGehris, I appreciate your time. Do you mind leaving an approval in addition to your comment? Thank you!!!

**Comment by blulady** [comment]
@mademarc can you approve the PR in addition to your comment?

**Comment by LOSjr4** [comment]
Availability: M,T,TH 9AM-1PM
ETA: now

**Review by LOSjr4 — APPROVED** [review]
I see all of the targeted peace-justice.svg where changed to sdg16.svg, and all of the new site pages appear the same as our current site albeit slightly scaled different which was expected.
I saw your note on the image not showing on _projects/access-the-data.md. That is a good observation. It is also true on our current website, so it's acceptable regarding what this issue requested. Good work @cng008 !

**Comment by LOSjr4** [comment]
@cng008 go ahead and click that Re-request review button next to the reviewers who have not left an "approval" yet, so they're alerted that your changes are ready to be re-checked.

**Review by RyanGehris — APPROVED** [review]
Great work! The correct changes are made and the website looks as intended. Thank you for working on this issue!

**Comment by RyanGehris** [comment]
@blulady Thank you for letting me know that I forgot to actually approve the changes. I just did it. Sorry about that.

**Comment by blulady** [comment]
I did not see the sdg16.svg on About page's Sustainability section: https://www.hackforla.org/about/#sustainability
Is it just me?

Screenshot (411)

**Comment by mademarc** [comment]
Availability: 4/20/2023  
ETA: 7:05pm

**Review by mademarc — APPROVED** [review]
Hey @blulady  thank you for the heads up and as i have approved this also once again @cng008     good job on this.

**Comment by RyanGehris** [comment]
@blulady I am seeing the same thing as you when using firefox. I typically check on chrome, safari, and a mobile device so I did not notice that. The changes were successful for Chrome, Safari, and Mobile on my local computer.

**Comment by cng008** [comment]
Thank you @RyanGehris and @mademarc for approving again. It seems this PR
keeps getting merge conflicts as other PRs are getting merged before this
one. @blulady I will be OOO until Tuesday 4/25 and will look at it once
again then.

**Comment by roslynwythe** [comment]
@cng008 It appears that on the live site, there is a problem with the grid in Firefox:
image

 and fixing that problem is not in the scope of this issue, so I'll go ahead and merge and write an ER to address the Firefox issue.

**Comment by roslynwythe** [comment]
@cng008 It appears that on the live site there is a problem with the grid layout:
image

 and resolving that problem is out of the scope of your issue, so we'll create an ER to manage that going forward.

**Pull request merged**
