### PR TITLE
Updated getting-started.html

### LINKED ISSUE #4420: img Tag Refactor: Getting Started page - `step-img-icon-join candidates.png`
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started)  and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-join" src="assets/images/getting-started/candidates.png" alt="" />
```
to
```
<img class="step-img-icon-join" src="assets/images/getting-started/candidates.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by DevRishiJain**
Fixes #4420

### What changes did you make and why did you make them ?

  -Syntax was inconsistent inside the code.
  -Necessary changes has been made.
  -Removal of "/" from img tag.
  -In pages/getting-started.html
  -Line No. 213
 - Checked the page remains the same in mobile, tablet, and desktop views as on the current website.

### CODE REVIEW

**Comment by graycodesnu** [comment]
Availability: 5/17 
ETA: EOD 5/17

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @DevRishiJain I see that issue #4420 specified an update to the `` tag on line 213 but it looks like all the other lines with the closing slash were updated as well.  That may pose a problem, because other issues may have been generated to update the other lines, and this could lead to confusion.  Please revert or edit the file so that the only changed line is 213.  Thank you.

**Review by matthewmpan — CHANGES_REQUESTED** [review]
Hi @DevRishiJain Great job taking on this issue! I will reiterate the changes requested by @roslynwythe about keeping your changes within the scope of issue #4420. Additionally, the trailing space before the closing angle bracket on the `` tag can be deleted for consistency in code formatting. Lastly, be sure to check off the completed action items on issues when you complete them. Thank you.

**Comment by DevRishiJain** [comment]
@roslynwythe the changes you asked for are done. Please re-review them

**Review by one2code — DISMISSED** [review]
I've pulled the code into my repository and see that only line 213's img tag has been changed, which is consistent with the files changed review on the pull request. I've also verified that the changes requested by @roslynwythe have been made. @DevRishiJain, great job on making the requested changes, and congratulations on your 1st pull request!

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @DevRishiJain please check off the Action Items in the issue #4420

**Review by roslynwythe — DISMISSED** [review]
@DevRishiJain  great work on this PR.  The PR is properly formed, it describes the work done, the code is clean and correct and it checks out in the browser.  Thank you!

**Comment by DevRishiJain** [comment]
However all the changes requested by @matthewmpan are done with the original changes as it is within. And I think it is complete now.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
@DevRishiJain your changes are correct but please limit your changes to those specified in the issue, in particular line 213.

**Comment by DevRishiJain** [comment]
I have limit the changes and now I think finally it is ready, sorry for bothering you please have a look at it.

**Review by matthewmpan — APPROVED** [review]
Hi @DevRishiJain Thanks for making the requested changes. Your changes are within scope of issue #4420 and all action items have been checked off. The extra space ' ' was removed and the update looks good. Great work!

**Review by one2code — APPROVED** [review]

**Review by roslynwythe — APPROVED** [review]
@DevRishiJain thank you for your work on this issue and being responsive to the requests for changes during the PR process.  As I mentioned earlier, the branches are formed correctly, the code change is clean and correct and limited to the scope of the item,  you have described your work, and it checks out in the browser.

**Pull request merged**
