### PR TITLE
Update Project Profile: 311 Data Add Joy Truex

### LINKED ISSUE #7541: Update Project Profile: 311 Data Add Joy Truex
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/311-data.md` file.
- [x] Observe the existing syntax of the front matter block [^1] in the file.
- [x] Find the `leadership` variable and add the following profile. 
```
  - name: Joy Truex
    github-handle: Joy-Truex
    role: UX Design Lead
    links:
      slack: https://hackforla.slack.com/team/U03VBPSEH52
      github: https://github.com/Joy-Truex
    picture: https://avatars.githubusercontent.com/Joy-Truex
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] 311 Data page [^2]
- [x] Once your pull request is merged, go to the initiating ER [^3]
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move initiating ER [^3] to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/311-data
[^3]: initiating ER:  #7301

### PR DESCRIPTION
**Pull request by rachelcorawood**
Fixes #7541 

### What changes did you make?
-In the _projects/311-data.md file.

-Found  the leadership variable and add the following profile.

-name: Joy Truex
    github-handle: Joy-Truex
    role: UX Design Lead
    links:
      slack: https://hackforla.slack.com/team/U03VBPSEH52
      github: https://github.com/Joy-Truex
    picture: https://avatars.githubusercontent.com/Joy-Truex

-Verified the changes by viewing the following in your local environment on 311 Data page 

### Why did you make the changes (we will use this info to test)?
-We need to keep project information up to date so that visitors to the website can find accurate information.

### Screenshots of Proposed Changes Of The Website
<details>
  <summary>Visuals before changes are applied</summary>

Screenshot 2024-10-25 at 3 51 31 PM

</details>

<details>
  <summary>Visuals after changes are applied</summary>

Screenshot 2024-10-25 at 3 51 08 PM

</details>

### CODE REVIEW

**Comment by t-will-gillis** [comment]
Hi @rachelcorawood The Pull Request template includes the word "Fixes" before the issue number. This word is required and this is why there are two workflows failing below- please add it back as shown in the PR template instructions. (Adding the word "Fixes" tells GitHub to link your PR with the issue that you are fixing.)

<details><summary>PR template</summary>
Screenshot 2024-10-25 192336

</details>

Also, please note that in Markdown, there needs to be a single space between the dash and the text that follows in a list. Please add the spaces back so that your PR is formatted correctly with bullet points.

Example:
-list1
-list2
-list3  

Versus:
- list1
- list2
- list3

**Comment by rachelcorawood** [comment]
@t-will-gillis Thank you for the feedback. 

I updates the pull request as per your suggestions.

**Comment by siyunfeng** [comment]
Review ETA: 10/29/2024 Tuesday
Availability: 6-10 PM Weekdays (EDT)

**Review by siyunfeng — APPROVED** [review]
Nice job working on this issue, @rachelcorawood !

I appreciate you providing your availability and ETA in the original issue and updating the linked issue to your PR. The branch you made the change in is accurate. The change you made is correct. It's helpful to provide the before-and-after screenshots. 

Improvements: 
- Avoid including your bookmark bar or other personal info in the screenshots
- Leave a space between "-" and the content to list your bullet points, such as `- Found the leadership variable and add the following profile`, or you can type your bullet points, select all of them, and click the `unordered list` button in the editor

Other than these, it looks good. Thank you for your contribution!

**Comment by floydferrer** [comment]
Review ETA: 10/29/2024 Tuesday
Availability: 11AM-2PM Weekdays (PST)

**Comment by Thinking-Panda** [comment]
@rachelcorawood Please resolve the merge conflict and push the branch again. To resolve merge conflict read -(https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts)

**Review by codyyjxn — DISMISSED** [review]
@rachelcorawood Thank you for taking this issue. 

**Things that went well:**

- You made the correct changes
- The description is very detailed and concise
- The issue is linked correctly

**Things that need to be fixed:** 

- [ ] Merge conflict

**Comment by t-will-gillis** [comment]
Hi @rachelcorawood Please see the merge conflict and resolve it so that your issue can be finished. If you need help with it, please let us know. Thanks!

**Review by floydferrer — DISMISSED** [review]
Hi @rachelcorawood thanks for taking this issue!

Things that went well:

- You made the correct changes
- The description is very detailed and concise
- The issue is linked correctly

Things that need to be fixed:

- [ ] Merge conflict

Thank you for your contribution!

**Review by siyunfeng — CHANGES_REQUESTED** [review]
@rachelcorawood , the change you made was accurate. 

You need to update your branch before your PR can be merged because some issues related to yours were being merged. You can click the `Resolve conflicts` button to merge. 

Request changes: 

- [ ] Resolve conflicts (Conflicting files: `_projects/311-data.md`)

Let us know if you have any questions. Thanks!

**Comment by rachelcorawood** [comment]
Thank you all for your comments and suggested edits. I will make these by Wednesday evening. I'm dealing with unexpected event that is taking away my attention from solving this pull request.

**Comment by patelbansi3009** [comment]
ETA: End of the Day
Availability: 9-5 PM 11/08/24

**Review by patelbansi3009 — DISMISSED** [review]
Hi @rachelcorawood, thank you for addressing this issue!

What went well:

- The changes made were correct
- The description is clear and detailed
- The issue has been properly linked

Things to address:
- [x] Resolve the merge conflict

Thanks again for your contribution!

**Comment by rachelcorawood** [comment]
Thank you for your patience. Resolved the Merge Conflict I believe....

**Review by siyunfeng — APPROVED** [review]
Thank you for resolving the merge conflict, @rachelcorawood !

- The branch you made change on is correct
- The linked issue is included
- The change you made is accurate
- Before-and-after screenshots match the website view

Nice job and keep it up!

**Comment by t-will-gillis** [comment]
@rachelcorawood You can let your reviewers know that your PR is ready for a re-review by clicking on the 'chasing arrows' next to your PR reviewer's names: 

<details>

Screenshot 2024-11-09 111123

</details>

**Review by floydferrer — APPROVED** [review]
Hi @rachelcorawood thanks for merging the conflict! This now approved.

Thank you for your contribution!

**Pull request merged**
