### PR TITLE
Guides Pages Redesign - Updated

### LINKED ISSUE #1630: Work flow for guides to appear on the website
### Dependency
- [x] Waiting for a PM to get assigned to Guides (ask Bonnie or Olivia for status if necessary)
- [x] ~Waiting until PMs have identified all guides that are ready (at least 5 are needed for this test)~

### Overview
As PMs we need guides to be easy and fast to add to the website so that we have our guides appear on the website as soon as possible.

### Action Items
- [x] Define the prototype
   - [x] Document what did not work 
- [ ] Define MVP
- [ ] Define stages post MVP
- [ ] Convert issue to epic with small issues: [Add credits for photos and icons for redesigned homepage #2528](https://github.com/hackforla/website/issues/2528)
- [ ] Once the pull request associated with this issue is approved and merged
  - [ ] Please update and edit issue #1515 by
    - [ ] Checking off the dependency for this issue
    - [ ] If all dependencies are checked off, please move issue #1515 to the New Issue Approval column and remove the Dependency label
  - [ ] Please update and edit issue #3170 by
    - [ ] Checking off the dependency for this issue
    - [ ] If all dependencies are checked off, please move issue #3170 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
Here is what we will post on the a guide issue when we assign an image to it
``` 
Here is the image that will show up when people go to hackforla.org/toolkit and see this guide
[INSERT IMAGE HERE]

Here are the details for the credits page
Name: Meetup (this needs to link to the original image location)
Used in: Toolkit
Artist: _______
Provider: _____
```
- [Guide: How to Write a Guide
](https://docs.google.com/document/d/1-8gmeC-wnfM8C8fVvmTP1BLA2WfNjKH_XJrHB1OAV6Q/edit#)

- [Template: Guide](https://docs.google.com/document/d/1kV29V-mRPBNRRfIbYHrz05FElC02Dh6egaMANlxaZrM/edit)

- [How to Set Reminders in Slack v4
](https://docs.google.com/document/d/1YxwE3Edz7xXPVZ156wbIaPlQj7UUssIWN-ctTqbBilE/edit)

- [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14989%3A95216)

- [Sample Documentation from GitHub as Reference](https://docs.github.com/en/enterprise-server@3.1/admin/all-releases)

- [emojiterra](https://emojiterra.com/)

- [Figma / Type Space Figma Youtube Video](https://www.youtube.com/watch?v=6EuBIwUeF48&list=PLdlnbMNK63vmlbz78zin8X8RmAoBs_D1E&index=8)

- [Tool researched by 100Automations](https://github.com/100Automations/Website/issues/78#issuecomment-745641242) 

- https://github.com/hackforla/guides/issues/10#issuecomment-896934745 

- Guide Pages Design System - https://github.com/hackforla/website/issues/1630#issuecomment-954330264

### PR DESCRIPTION
**Pull request by abenipa3**
Fixes #1630

### What changes did you make and why did you make them?

(Please see Update 8/18/22 below)

This pull request contains files to the Guide Pages Redesign. 

The following files have been added to the respective folders:
- `_guide-pages\how-to-set-reminders-in-slack.md` - New Guide Page called "How to Set Reminders in Slack"
- `_includes\toc.html` - Generates section and subsection titles for the sticky navigation of the Guide Pages.
  - This is the same method used for 100Automations' Guide Pages as seen [[here]](https://github.com/100Automations/Website/blob/gh-pages/_includes/toc.html).
- `_layouts\guides.html` - Layout used for the Guides' MD files.
- `_sass\components\_guides.scss` - Styling for the redesigned Guide Pages.
- `assets\images\guides\how-to-set-reminders-in-slack` - Contains all of the images included in "How to Set Reminders in Slack"
- `assets\images\guides\guide-page-hero.svg` - New hero image for the redesigned Guide Pages.
- `assets\js\guidepages.js` - JS for Guide Pages that enables the functionality of the sticky navigation bar and the _Return to the Top_ Button.
  - _Return to the Top_ Button is only visible on mobile. 
- `pages\guides.html`

The following file has been modified:
- `_sass\main.scss` - Added `@import 'components/guides.scss';` to import styling for the redesigned Guide Pages.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Current Guide Page Design

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

Redesigned Guide Page Design

Note: Please excuse the odd navbar placements. I used an extension to snapshot the entire webpage and the navbar followed the extension as it scanned the page.

image

</details>

Here is also the [Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17202%3A107428) to the Guide Pages Redesign as reference. 

Link to View Locally: http://localhost:4000/guide-pages/how-to-set-reminders-in-slack.html

### Special Notes
~~The following issues need to be completed before the Redesigned Guide Page is ready for public view:
#2978 - Create Guides Markdown Converter (Google Apps Script)~~

Update 6/4/22:
After a [discussion ](https://github.com/hackforla/website/pull/3161#issuecomment-1140494806) with our team, PR will be merged into gh-pages after review. 

Update 8/18/22:
I made the mistake of deleting my head/forked repo. My intent was to pull the latest updates as I was committing my changes to my old PR - https://github.com/hackforla/website/pull/3161 -, but had issues pulling the latest updates, so deleted my fork repo (bad idea). 

Was able to retrieve the old PR, but could no longer update from there; Github needed me to create a new one. My apologies for the inconvenience once again. Please feel free to message me if you have any questions via Slack or email (alymaebenipayo@gmail.com). Thank you. 

### Links to Related Issues
Some existing issues in this PR may have already been addressed as action items in related issues. If an issue has not been addressed, please feel free to mention it here or in the related issues. Here are the links as references:
https://github.com/hackforla/website/issues/1515 - Create mobile version of the Guide Pages and ensure responsiveness 
https://github.com/hackforla/website/issues/3170 - Guide Pages - Sticky Navigation Fix
https://github.com/hackforla/website/issues/2978 - Create Guides Markdown Converter (Google Apps Script)
https://github.com/hackforla/website/issues/1630#issuecomment-954330264 - Guide Pages Design System Update

### CODE REVIEW

**Comment by abenipa3** [comment]
Redirecting Feedback and Comment Here:

Feedback:
https://github.com/hackforla/website/pull/3161#pullrequestreview-1069231945

Responses: 
@Wny-Duong Thank you so much again! I greatly appreciate your time in reviewing this large PR and the details in your comments. 😄 Please see below for my responses.

> 1. Clicking on the links on the right side seem to redirect you to the line immediately below the label as opposed to the line corresponding with the link text itself. I'm not too sure if this is intended behavior or not.
Example: Clicking on What is Slack? gets you slightly below the header for What is Slack?

Great catch! (I'm going to circle back to this later and I investigate.) - ~~**Update 8/18/22: Still looking into this. Will update this as soon as it's resolved.**~~ Please see the latest comment for more details.

> 2. From the original Figma, it looks the sections: Who uses reminders and Type of Reminders (line 44 and line 49 in _guide-pages/how-to-set-reminders-in-slack.md should be using the the same header CSS as What is Slack? and When to use Reminders?.

No changes were applied. The font sizes for `Who Uses Reminders` and `Type of Reminders` differ from `What is Slack?` and `When to Use Reminders?` since they are H2. 

<details> <summary> See Here for Font Details </summary>

`What is Slack?` - H1, Font Size: 36px
image

`When to Use Reminders?` - H1, Font Size: 36px
image

`Who Uses Reminders` - H2, Font Size: 24px
image

`Type of Reminders` - H2, Font Size: 24px
image

</details> 

> 3. In When to use Reminders (line 51 of _guide-pages/how-to-set-reminders-in-slack.md) , there's some strange text that goes: **allows you to set up an automatic reminder with a tailored message **
It doesn't look like this text is meant to be bolded according to the Figma page.

Done ✅ That was an oversight on my part when I created the Figma design. The text was supposed to be bolded to match the original document in our Google Docs. I've applied the changes by fixing the bolded text in the `line 51 of _guide-pages/how-to-set-reminders-in-slack.md` file and the Figma Design. Thank you!

image

> 4. There's a numbering issue on the page under option 1 (starting below line 73 to line 99 of _guide-pages/how-to-set-reminders-in-slack.md), as the steps all start with 1. instead of being properly numbered from 1-4.

Done ✅ Added a line break to add a space between the steps and the images, specifically for steps 1, 2, and 4, so that Jekyll can recognize that the steps should be properly numbered from 1-4. 

<details> <summary> Applied Changes - Image Preview </summary>

image

image

image

</details>

> 5. A similar issue is seen in Option 2: by Direct Entry (starting below line 114 to line 123 of _guide-pages/how-to-set-reminders-in-slack.md) where the numbering resets on the step starting with "To Whom"

Done ✅ Applied the changes similar to Option 1. 

<details> <summary> Applied Changes - Image Preview </summary>

image

</details>

> Also on the second step (line 119 to 121 of _guide-pages/how-to-set-reminders-in-slack.md) it looks like there should've been subpoints or some other special formatting for the reminder recipients, "specific person" and "entire channel" since they both appear on the same line instead of separated. The differences are shown below between what's on the current page and the figma design.

Done ✅ I've also updated the font color to the Figma since apparently I didn't add the color the "specific person" and "entire channel" as it appeared on the Google Docs. Applied changes can be seen in the previous comment.

Side note/Commentary: I think ideally (at the time) we wanted to avoid applying CSS (and HTML) to the MD files, but applying CSS was how I could replicate what we had in our design...at least until we find out how to add that to our Automated MD Converter. Other than that, I'm open to suggestions on how to best apply the special formatting to this section. 🙌 

Side-Side Note: Not done updating this PR. Committing changes in the meantime till I come back tomorrow or Friday. Will update you all once it's resolved. Thanks!

**Comment by abenipa3** [comment]
Update: PR not ready for review. Currently working on this:
> Clicking on the links on the right side seem to redirect you to the line immediately below the label as opposed to the line corresponding with the link text itself. I'm not too sure if this is intended behavior or not.
Example: Clicking on What is Slack? gets you slightly below the header for What is Slack?

Blocker: Not feeling well...
ETA: 8/24

**Comment by abenipa3** [comment]
@Wny-Duong Checked the issue again. 
> Clicking on the links on the right side seem to redirect you to the line immediately below the label as opposed to the line corresponding with the link text itself. I'm not too sure if this is intended behavior or not.
Example: Clicking on What is Slack? gets you slightly below the header for What is Slack?

It turns out this was one of the issues I wanted to include in a related issue -  https://github.com/hackforla/website/issues/3170. Thank you for mentioning this. I have just added this as a new action item to the issue's description - https://github.com/hackforla/website/issues/3170.

PR ready for review! Please let me know if you have any further questions or concerns. Thanks!

**Review by Wny-Duong — DISMISSED** [review]
The corrections look great. Thanks for making the changes!

**Comment by abenipa3** [comment]
@Wny-Duong Thank you so much again for taking the time to review this 🎉

**Comment by ericvennemeyer** [comment]
`Availability`: Weds 8/24 - Friday 8/26, 2hrs
`ETA`: EOD Friday 8/26

**Review by ericvennemeyer — CHANGES_REQUESTED** [review]
Hey @alyssabenipayo! This is a complex issue and you've clearly already put a ton of work into it. Since I wasn't part of the design discussions that led to this point, and since @Wny-Duong  has already given it a once over, I'm just going to mention places I've noticed where the final product doesn't seem to match the Figma mockup. These may or may not be actual issues that need addressing:

1. In the sticky nav:
    - The Figma version has two additional sections: "What's in the Guide?" at the top, and "Guide Authors" at the bottom. These are not present in your version. I saw that they were commented out in the code, so maybe this was a deliberate choice?
    - In Figma, section headings are a different weight (700px) than sub-headings (400px). In your version, all appear to be the same weight.
    - When the "How to Set Up Reminders" heading becomes highlighted, the checkbox icon next to it gets bumped to a new line (see screen grabs below)
    
Screen Shot 2022-08-26 at 4 14 27 PM
Screen Shot 2022-08-26 at 4 14 35 PM
    
2. When I tried out the site in responsive design mode to simulate using a smart phone, the sticky nav was still there and blocking a large portion of the screen. (screen grab below.) I'm guessing it's not supposed to do this?
Screen Shot 2022-08-26 at 4 21 12 PM


3. In Figma, there's a margin between each line of text and its example image, but in your version there doesn't seem to be any. (Screen grabs below--Figma, then your version)
Screen Shot 2022-08-26 at 4 17 21 PM
Screen Shot 2022-08-26 at 4 16 10 PM


4. In Figma all images in the "Examples" section are the same width, but in yours the second is much wider than the others (screen grabs-- Figma first, then your version)
Screen Shot 2022-08-26 at 4 22 40 PM
Screen Shot 2022-08-26 at 4 22 31 PM

5. Finally, in the "Help us make this guide better" section at the very bottom, in Figma the "feedback form" text is an active link, but in your version it isn't:
Screen Shot 2022-08-26 at 4 19 30 PM
Screen Shot 2022-08-26 at 4 19 19 PM

**Comment by abenipa3** [comment]
Thanks so much for the review, @ericvennemeyer. Won’t be near a computer very soon to provide proper responses to your feedback since I’m currently (recovering) at the hospital.

In the meantime, ETA: 9/9 or 9/16. I apologize for the inconvenience and thank you.

**Comment by ericvennemeyer** [comment]
@alyssabenipayo of course, no worries at all. I hope you have a good recovery and feel better soon!

**Comment by abenipa3** [comment]
Hi @ericvennemeyer ! I'm back. Thank you again for your detailed feedback! Please see below for my responses:

> 1. In the sticky nav, the Figma version has two additional sections: "What's in the Guide?" at the top, and "Guide Authors" at the bottom. These are not present in your version. I saw that they were commented out in the code, so maybe this was a deliberate choice?

Yes, it was a deliberate choice. The idea was to (re-)include the commented-out code after we find out how to update the sticky nav so that it automatically includes the section title `Guide Authors`, and then omit the code for it in `_layouts\guides.html`. 

<details> <summary> More details </summary>

Commented out code for our reference:

```
<!-- # **Guide Authors**

Peer-created guides are an important part of Hack for LA’s Culture.  They are created by our Volunteer Members based on effective processes developed on our projects.

This guide was created and contributed to by: Maria Studnicka, Katie Jensen, Saasha Gilkes, Oliva Chiong, Alyssa Benipayo, Bukola Ogunleye and Bonnie Wolfe

If you would like to contribute, please see the contribution methods available:

If you are a member of the Hack for LA community you can post any comments directly in the iterative  version of this guide: [How to Set Reminders in Slack](https://www.google.com/)<span style="text-decoration:underline;">.</span>

If you are outside the Hack for LA community, please use this [feedback form](https://www.google.com/) to provide suggestions for improvement or how the guide is useful for you. -->
```
The `Guide Authors` section is included in the Google Docs, but for this PR, I had to delete it after converting it into MD since `_includes\toc.html` doesn't automatically pick up the section title. The codes in `_layouts\guides.html` automatically generates the page cards for "What's in the Guide?" and "Guide Authors" in the meantime.

</details>

As I was working on this, I realized it became a larger issue than I expected, so we decided to spawn a new ticket to cover this part. Here is the link to the issue, which also includes the Action Item to "Update/Fix the sticky nav so that it includes "What's in the Guide?" and "Guide Authors" (as well as possible future sections/subsection titles)": https://github.com/hackforla/website/issues/3170.

> In Figma, section headings are a different weight (700px) than sub-headings (400px). In your version, all appear to be the same weight.

Done ✅ Thanks for pointing this out! Updated the font sizes for headings according to Figma and Guide Page Design System Discussion. I realized this is another case where we'll need to add the style to the MD file. Was hoping to automate this process at the time. Side note: Here is the link to the Guide Page Design System: https://github.com/hackforla/website/issues/1630#issuecomment-954330264

> When the "How to Set Up Reminders" heading becomes highlighted, the checkbox icon next to it gets bumped to a new line (see screen grabs below)

Thanks for pointing this out! We actually do not want to include the images and emojis in the sticky navigation. This is another issue that we addressed in https://github.com/hackforla/website/issues/3170. (I also realized I didn't mention the links to the issues related to this Guide Pages Redesign, so I updated the issue description for our references.)

> 2. When I tried out the site in responsive design mode to simulate using a smart phone, the sticky nav was still there and blocking a large portion of the screen. (screen grab below.) I'm guessing it's not supposed to do this?

Nope, it was not supposed to do this. In mobile, the sticky navigation disappears. This will be covered in a separate issue as well. Here is the link: https://github.com/hackforla/website/issues/1515

> 3. In Figma, there's a margin between each line of text and its example image, but in your version there doesn't seem to be any. (Screen grabs below--Figma, then your version)

Done ✅ Added `#content` next to the link to the image on the MD. Then added `img[src*='#content'] { margin-top: 24px; }`.

> 4. In Figma all images in the "Examples" section are the same width, but in yours the second is much wider than the others (screen grabs-- Figma first, then your version)

Done ✅ I had downloaded the images as it was from the Google Doc, so the sizes varied for each image. (Varied width seen on the Figma as well.) I adjusted the sizes by grabbing the widths of each image and getting the average, which in this case is `588.2 px`. Feel free to let me know your thoughts on this! 🙌 

> 5. Finally, in the "Help us make this guide better" section at the very bottom, in Figma the "feedback form" text is an active link, but in your version it isn't:

Done ✅  Updated `feedback form` as an active link. Placeholder link is currently `https://www.google.com/` since we don't have the official link to the feedback form at this time. (Similar to the "How to Set Reminders in Slack" link under `Help us make this guide better:`.) Please feel free to let me know your thoughts on this as well.

Thank you once again for reviewing this PR and for your patience! PR ready for review! Please let me know if you have any further questions or concerns.

P.S. I noticed this message after I pushed my changes up to my PR:
`[alyssabenipayo](https://github.com/alyssabenipayo) dismissed [Wny-Duong](https://github.com/Wny-Duong)’s [stale review](https://github.com/hackforla/website/pull/3476#pullrequestreview-1079732538) via [60ae430](https://github.com/hackforla/website/commit/60ae43031772847ebf65aaeb9c91fe170fedd0f3)`. I'm not sure how this occurred unless this is automatically done by Github?

**Comment by ericvennemeyer** [comment]
Hey @alyssabenipayo! Welcome back, and I'm glad you were able to get out of the hospital earlier than expected. Hope you're feeling much better!

Thanks for addressing all my notes and including relevant additional issues as context. Almost everything looks good to me. I just have one question about the font weight of section headings in the sticky nav. I see you updated "the font sizes for headings according to Figma and Guide Page Design System Discussion," but I'm not seeing a difference between the headings and the nested list items in the sticky nav. See this screengrab from your version:

Screen Shot 2022-08-30 at 12 35 51 PM

In Figma, "When to use reminders" is bolder than "Who uses reminders?" I inspected the underlying HTML and all the section headings in the sticky nav are anchors, rather than H1, H2, H3, so the additional styles you added in the MD file aren't catching them. See photo:

Screen Shot 2022-08-30 at 12 31 43 PM

**Comment by abenipa3** [comment]
Thanks for the additional feedback, @ericvennemeyer ! I’m happy to be back sooner than expected. Will work in these changes per comment.

ETA: 9/2/22

**Comment by abenipa3** [comment]
Hi @ericvennemeyer, circling back to your feedback right now.

> I just have one question about the font weight of section headings in the sticky nav. I see you updated "the font sizes for headings according to Figma and Guide Page Design System Discussion," but I'm not seeing a difference between the headings and the nested list items in the sticky nav. See this screengrab from your version:

> In Figma, "When to use reminders" is bolder than "Who uses reminders?" I inspected the underlying HTML and all the section headings in the sticky nav are anchors, rather than H1, H2, H3, so the additional styles you added in the MD file aren't catching them. See photo:

Thanks for pointing this out. My bad for overlooking the font-weights for the section titles and subsection titles in the sticky nav from the Figma file. 

It turns out I'm actually going to need help with this.

As of now, the `_includes\toc.html` automatically pulls out all of the content from inside the <h#></h#> and then renders the TOC. The styles that were added in the MD files were meant to be incorporated for the headings in the page cards only.

So for this commit, I changed the `h1` in the MD so that all of the words in the section titles are bolded and that it reflects in the sticky navigation as well. 

The output now looks like this:
image

The part I need help with is how to adjust it so that the first word of each section title (i.e. `What`, `When`, `How`) is bolder/shows that it's bolder in the page cards.

So far I've tried the following:
- Added a div to the first word of the section title only. Then added `font-weight:bolder;` to scss.
  - Output: Shows actual code on the sticky nav. 
- Researched and experimented to see if it's possible to make the text `bolder` than the rest of the title in MD, but none.
- Read topics on the [TOC discussion](https://github.com/allejo/jekyll-toc/discussions) for how to adjust `_includes\toc.html`.

Any feedback on how we could go about this?

**Comment by ericvennemeyer** [comment]
Hey @alyssabenipayo! Thanks for the update. Yeah, this is starting to get tricky, and I have basically zero experience working with Jekyll, liquid or jekyll-toc. I also somehow neglected to notice that the first word of each heading in the Figma is bolder than the rest of the heading. I guess that's why it originally looked that way in the sticky nav--before your last commit, each first word was bold there, too. (Strange that it correctly interpreted the `<strong>` tag, but displays the `<div>` you added as text.)

Anyway, shooting from the hip here, but I took a look at the [jekyll-toc readme](https://github.com/allejo/jekyll-toc), and I found a list of optional parameters. Apologies if you've already tried this, but this one in particular might do the trick:

Screen Shot 2022-09-01 at 4 49 59 PM

If I'm understanding it correctly, it seems like it might allow you to add those additional html tags within the headings without having them automatically carried over to the sticky nav and displayed as text. 

(EDIT: Now I'm actually a little confused. Where DID the `<strong>` tags I saw previously around the first word in each heading in the sticky nav come from?)

**Comment by abenipa3** [comment]
Hi @ericvennemeyer. All good. Unfortunately, the `sanitize` won't work because it strips/removes the HTML applied to the text on MD as seen below.

image

The initial `<strong>` tags appeared when I had bolded the first words like in `**What** is Slack?` as seen below, and then Jekyll converts the MD into an HTML. The current commit is like `**When to use Reminders**`. 
image

image

image

**Comment by ericvennemeyer** [comment]
Hey @alyssabenipayo sorry for the delay. It seems like you're more familiar with this than I am, so I probably can't offer you much. I did try out one last thing, however, and I think it achieves the desired effect. Have a look, anyway.

For the sake of visibility I made the first word in the first heading ("What is slack?") green, and the main headings in the sticky nav blue. But you could just as easily make them bold instead. In the MD file I added a `<span>` with its own style around the first word of the first heading, like so:

`# **<span style="color: green">What</span> is Slack?**`

With the `sanitize=true` parameter added, this new style is not transferred over to the sticky nav. However, as you noted, neither is any of the MD styling. So we have to add it on our own. I added the following to `_guides.scss`:

```
.sticky-nav--guides > ul > li > a {
	color: blue;
}
```

The nested child combinators ensure that only the anchor tags in the main headings, but not the subheadings, receive the specified style. Here's the result on my computer:

Screen Shot 2022-09-06 at 1 00 10 PM
Screen Shot 2022-09-06 at 1 00 32 PM

Again, if you replace the green and blue coloring with `font-weight: bolder` or something along those lines, I think that does the trick?

**Comment by abenipa3** [comment]
hey @ericvennemeyer, all good! thanks so much for the suggestion! it seems to work! :D 

image

image

**Comment by ericvennemeyer** [comment]
Hey @alyssabenipayo awesome! I'm glad that worked. The only thing is, I can't really see a distinction between the bolder first word and the rest of the heading. I know this is a pain in the butt, but since we've come this far . . . could you change the headings to be like this:

`# What <span style="font-weight: 400">is Slack?</span>`

In other words: 

- [x] Remove the double asterisks (they don't seem to be doing anything on top of the basic `<h1>` styling) 
- [x] Move the `<span>` so it wraps the remainder of the title instead of the first word 
- [x] Set the `<span>` font weight to 400 

That will make it match the Figma, or at least close enough as far as I'm concerned. After that, we're all done here.

**Comment by abenipa3** [comment]
Hey @ericvennemeyer ! Got it. Thank you so so much for working with me on this. 😄 Here is the output now:
image

**Review by ericvennemeyer — APPROVED** [review]
@alyssabenipayo This looks great. Congratulations on all your hard work, and happy I could help. Approved!

**Comment by blulady** [comment]
Hey Alyssa, we tried to merge it but there was no margin on the left. Could you please re-open this pull request? I am sorry we should have checked it out in my local repo before merging it.

**Comment by abenipa3** [comment]
Hey Sarah, thanks for catching that. Just want to clarify - when we said there's no margin on the left, are we saying that there's no margin on the left of the page container or the page card (or elsewhere)? Here's what I have in the PR. 

Margin-left on the page container
image

And then we have the padding for the page card
image

Also, it seems like it's been merged so I won't be able to reopen to PR. (Did a bit of research on how and found out through this link: https://stackoverflow.com/questions/12674304/github-reopening-a-merged-pull-request)

I could create a new pull request to push new changes, though. (I also read from the same StackOverflow link that there's a revert merged commit action, which will create a new pull request - https://stackoverflow.com/a/40721461/13090365). Please let me know your thoughts on how we could proceed.

**Comment by blulady** [comment]
Thank for getting back to me Alyssa. Please forgive me, I misspoke earlier, when I said "re-open" I meant create a PR. We tried to "re-open" the PR, obviously to no avail. 


Below are screenshots I grabbed of the live website when we (foolishly) merged the PR.


Screenshot (241)


Screenshot (240)

**Comment by abenipa3** [comment]
Oh no! 😭 Okay, Let me see what I can do to remedy that. All good, Sarah. 😄 Thanks so much for catching this! 👍 

ETA: 9/14/22

**Comment by arpitapandya** [comment]
> Thank for getting back to me Alyssa. Please forgive me, I misspoke earlier, when I said "re-open" I meant create a PR. We tried to "re-open" the PR, obviously to no avail.
> 
> Below are screenshots I grabbed of the live website when we (foolishly) merged the PR.
> 
> Screenshot (241)
> 
> Screenshot (240)

@alyssabenipayo I have reopened the linked issue for you so that you can create new PR, you can also move the issue from `Prioritized Backlog` to `In Progress` under Project Board.

**Comment by abenipa3** [comment]
Thanks @arpitapandya ! Created a new PR here: https://github.com/hackforla/website/pull/3548. I also added a new comment there - I think I have an idea of what happened.

**Pull request merged**
