### PR TITLE
Hide all-time contributors 2605

### LINKED ISSUE #2605: Hide all time contributors - dependent on current project team number
### Overview
If there are less all time contributors than the current project team, hide the div that contains the all time contributors. 

### Action Items
An example of this issue can be found in the [EMS Triage Tracker](https://www.hackforla.org/projects/ems-triage-tracker) page. There are less all time contributors than on the current project team.

- [x] Locate the projects where this issue occurs and their html docs. 
- [x] Locate the JS file `assets/project.js` and the corresponding JavaScript that creates the html elements on line 58.
- [x] Implement an algorithm that counts all of the Current Project Team members and if its less than the All Time Contributors than hide the All Time Contributors and the title

### Resources/Instructions
- https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js - The file where the All Time Contributors gets generated

<details>
<summary>Current H2 Tag for Completed Projects</summary>

</details>

Issue Creator - [Tomas Gonzalez - Slack DM](https://hackforla.slack.com/app_redirect?channel=U02DF1PPQUA)

### PR DESCRIPTION
**Pull request by tamara-snyder**
Fixes #2605

### What changes did you make and why did you make them ?
  - Selected all elements with the class `leader-card` (from line 116 of `_layouts/project.html`) to get an array of the current project team members
  - Added an if statement on line 73 of `assets/js/project.js` to check whether the number of all-time contributors was less than the number of people on the current project team
  - If so, I selected the `h2` as created in line 136 of `_layouts/project.html` and set its style as `display = 'none'` in lines 75-76 of `assets/js/project.js`. Otherwise, the else statement created the contributors list as usual
  - Added a comment on line 74 of `assets/js/project.js` to explain the code I added

Projects worth checking: 
- [ ] [EMS Triage Tracker](https://www.hackforla.org/projects/ems-triage-tracker)
- [ ] [Brigade Organizers Playbook](https://www.hackforla.org/projects/brigade-organizers-playbook)
- [ ] [Civic Tech Structure](https://www.hackforla.org/projects/civic-tech-structure)
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>

image

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 3 hours
- Review ETA: Fri, Mar 18, 2022 (Morning)

**Comment by JasonY188** [comment]
Availability: 3 hours
ETA: 3-18

**Review by JasonY188 — APPROVED** [review]
Hi @tamara-snyder 

I can see you were able to locate the issue in the html.  Your code  checked if the  all-time contributors was less than then  current project team.  If true, the div with All Time Contributors and the title became hidden.   Looks good to me.  Awesome job! 

Project Civic Tech Structure
Before Change
image

After Change
image

**Review by JessicaLucindaCheng — APPROVED** [review]
@tamara-snyder Good job! I see the changes you made using Docker where it doesn't show the All-Time Contributors section if there are less contributors than Project Team leadership members.

**Pull request merged**
