### PR TITLE
remove self onboarding option, css fix

### LINKED ISSUE #1080: Duplicate Getting Started page and remove Self-Onboarding option from new version
### Overview
We need to duplicate the [Getting Started page](https://www.hackforla.org/getting-started), and remove the self-onboarding option from one copy of the page, because the video link doesn't work. However we will eventually have the self-onboarding again, once the slideshow is finished, so we want to save the old version of the page.

### Action Items
- [x] Duplicate the Getting Started page- old version of the page should remain the same and just be renamed "Getting Started with Video." 
   - [x] This page should not be linked to anywhere at the moment - but we are saving it until we have the self-onboarding option again (so that we don't need to change the code back later)
- [x] Name the new duplicate of the page just "Getting Started." 
- [x] Remove the "self-onboarding" section (top left) of the new Getting Started page duplicate 
- [x] Center the Guided Onboarding section of the new Getting Started page duplicate
- [x] Ask Bonnie to remove the Self-Onboarding option language on all of the Meetup onboarding events

### Resources/Instructions
[Getting Started page](https://www.hackforla.org/getting-started)

Screen Shot 2021-02-21 at 9 31 37 AM

### PR DESCRIPTION
**Pull request by matthewlee626**
Fixes #1080 

@ExperimentsInHonesty I believe I'm supposed to ask you to remove any self-onboarding language from Meetup onboarding events!

Removed the self-onboarding language.

image

### CODE REVIEW

**Comment by daniellex0** [comment]
@matthewlee626 Hey Matthew, sorry I just noticed this was already done as I was about to add a screenshot a little late- love how quickly this is done!

Just btw, there are a few adjustments that need to be made- this is what it should look like:

Screen Shot 2021-02-21 at 6 52 27 PM

I believe this can be done by keeping the width of the .project-position-1 class at 50%, but adjusting the margin to: "0px auto"

I'm not sure why all of the vertical margin/padding has disappeared, it should stay the same as before (as you see in the photo- sorry, I should have included this screenshot in the beginning.)

Also, can you also please make the following adjustments:

- Remove "Complete self-onboarding, or attend Guided onboarding..." text on top since the option is no longer relevant
- Add "margin: 5px 0;" to .g-s-list class to make it a little easier to read the lines

So it should look like this:

Screen Shot 2021-02-21 at 6 52 36 PM

And finally (sorry) can you add the [slack self-invite link](https://hackforla-slack.herokuapp.com/) again to the section below (underlined purple words should be the link) because some people are missing it the first time- 

Screen Shot 2021-02-21 at 7 07 53 PM

Thank you!! Sorry about all of the edits! Really appreciate how quickly you've worked on this, since this is probably the top priority issue on the site right now :)

**Comment by matthewlee626** [comment]
@daniellex0 Addressed all your comments. This looks good to go on my end.

image

**Review by akibrhast — COMMENTED** [review]
Everything looks good. All the changes as requested by @daniellex0 seems to have been implemented.

But before I can approve, I had a quick question @matthewlee626 

What is the significance of having two separate pages `getting-started-with-video.html` and ` getting-started.html`  ?

The only difference that I found when I ran a diff against the two files is below(could it not be in the same file?):

```
45a46
>         <p class="getting-started-step-subheader">Complete Self Onboarding, or attend a Guided Onboarding session via Zoom.</p>48a50,59
>                     <h3>Self Onboarding</h3>
>                     <img class="step-img" src="./assets/images/getting-started/onboard-1.png">
>                     <p class="getting-started-onboarding-instructions">Watch our <a
>                             href="https://undebate-cc.herokuapp.com/hackforla-projects">Onboarding Video</a>
>                         where
>                         you will hear a brief introduction to Code for
>                         America and Hack for LA, meet members of our active projects,
>                         and hear about the intended impact and roles these projects seek to fill.</p>
>                 </div>
>                 <div class="project-position-1">
114c125
<                     <li class="g-s-list">Locate and join the project’s <a href="https://hackforla-slack.herokuapp.com/">Slack channel</a>. Post your interest to join the
---
>                     <li class="g-s-list">Locate and join the project’s Slack channel. Post your interest to join the
```

**Comment by daniellex0** [comment]
@akibrhast Bonnie wanted to have a duplicate that still has the self-onboarding option up because we will go back to that version eventually- the details are in the original [issue ](https://github.com/hackforla/website/issues/1080) :)

@matthewlee626 ok that screenshot looks great! Only a tiny edit reversing one thing I said earlier (this is totally my bad, sorry..!) Can you actually remove that extra "slack channel" link on step 4? I wanted to make sure people saw that they can self-invite if they missed the one mentioned above, but this might just be confusing so better to keep it how it was. Sorry!!

So if you just remove that extra slack link (that I had asked you to add) on # 4, it's approved on my end :)

**Comment by matthewlee626** [comment]
@daniellex0 done!

**Comment by akibrhast** [comment]
@daniellex0 ah.. I did not notice that! Thanks for pointing that out  😄

**Review by akibrhast — APPROVED** [review]
Looks Good!

**Review by daniellex0 — APPROVED** [review]

**Pull request merged**
