### PR TITLE
Refactor Tools data for ems-triage-tracker.md

### LINKED ISSUE #4803: Refactor Tools data for ems-triage-tracker.md
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [ems-triage-tracker.md](https://github.com/hackforla/website/blob/gh-pages/_projects/ems-triage-tracker.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, video production
```
to
```
tools:
  - Figma
  - video production
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

### PR DESCRIPTION
**Pull request by ivan20203**
Fixes #4803 

### What changes did you make?
  - refactored the tools data in the .md file from a string to a list.

### Why did you make the changes (we will use this info to test)?
  - This refactoring was necessary to enable the addition of a dropdown filter on the 'Projects Check' page. The new filter will allow us to effectively compare and manage project values between 'tools' and 'technologies'.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2023-07-28 at 16 54 11

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Screenshot 2023-07-28 at 16 54 28

</details>

### CODE REVIEW

**Review by DorianDeptuch — APPROVED** [review]
Hi Ivan,

I tested this in my local environment and the site seems to be working perfectly. Everything looks good to me, great job!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @ivan20203 Good job! Your to/from branches are correct and you are linking to the original issue. Thanks for including the screenshots and the "What changes did you make?" and "Why did you make the changes?" 

For the "What changes" and "Why" section, the intent is that you talk about the specifics of the changes and the reasons for doing so. This does not need to be elaborate and you can usually get an idea of what to write from the original issue. E.g. to answer the first question: "Refactored the tools data on `ems-triage-tracker.md` from a string to a list" and to answer the second: "This was done so that we can add a dropdown filter on the 'Projects Check' page to compare `tools` and `technologies`." 

Thanks for working on this!

**Comment by ivan20203** [comment]
Changed answer for: What changes did you make?
to: refactored the tools data in the .md file from a string to a list.

Changed answer for: Why did you make the changes (we will use this info to test)?
to:This refactoring was necessary to enable the addition of a dropdown filter on the 'Projects Check' page. The new filter will allow us to effectively compare and manage project values between 'tools' and 'technologies'.

**Review by t-will-gillis — APPROVED** [review]

**Comment by t-will-gillis** [comment]
Thanks for making the changes to the description! Everything looks great.

For future reference after you make requested changes, you can re-request reviews by clicking the running arrows next to reviewers names so that the reviewers can approve the new changes:
Screenshot 2023-07-30 114402

**Pull request merged**
