### PR TITLE
Fix citizen engagement logo 4226

### LINKED ISSUE #4226: Logo getting cutoff on smaller screens on Citizen Engagement page
### Overview
On the Citizen Engagement page's Organizations We Work With section, we need to fix the logo so it doesn't get cutoff in tablet and mobile views.

### Details
- Screenshot of problem:
  <details>
    <summary>Click here to see a gif of the logo being cutoff as it the view becomes smaller</summary>
    
  </details> 

- Here are screenshots of the Figma Design of the Organizations We Work With section of the Citizen Engagement page. For dimensions and other specifications, please inspect the Figma Design for the [Citizen Engagement design in the red box titled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625-0&t=xpc1QvW41BRJ0jNW-0) to see how it should look for desktop and mobile views. 

  <details>
    <summary>Click here to see screenshots of the Organizations We Work With section of the Citizen Engagement page in mobile and desktop views</summary>
  
    <b>Desktop</b>
    
  
    <b>Mobile</b>
    
  
  </details>

### Action Items
- [ ] On the Citizen Engagement page's Organizations We Work With section, fix the logo so it resizes as the screen width gets smaller and smaller. (See the Resources/Instructions' Files section for some files to get you started.) 
- [x] Make sure nothing on the website is broken in mobile, tablet, and desktop views

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to issue #3328 and check if all the issues listed under the `Dependency` section are closed. If they are all closed, move that issue (#3328) into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it. 

### Resources/Instructions
- Citizen Engagement page: https://www.hackforla.org/citizen-engagement

#### Files to get you started
- [pages/citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html)
- [_sass/components/_citizen_engagement.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_citizen_engagement.scss)

#### Additional resources
- [Liquid template language](https://shopify.github.io/liquid/)
- [SCSS](https://sass-lang.com/documentation/)
- See the Figma Design [Citizen Engagement design in the red box titled Newest Version](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625-0&t=xpc1QvW41BRJ0jNW-0)

### PR DESCRIPTION
**Pull request by jch1013**
Fixes #4226

### What changes did you make and why did you make them ?

  - Updated image to match image provided in the figma design
  - Removed unnecessary scss styling

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Desktop View

Mobile View

</details>

### CODE REVIEW

**Comment by ronaldpaek** [comment]
Review ETA: 6 PM 6/17/23
Availability: 5-8 PM Saturday

**Comment by Thinking-Panda** [comment]
Availability- M-F 11am - 3 pm
Review ETA- 6/19/23

**Review by bonniewolfe — DISMISSED** [review]
Please update the video of the `Visuals after changes are applied` to include what it will look like in mobile.

Also, this was the first time I got a chance to see the animated gif vs the .mov, and the .gif file loaded much faster.

**Comment by jch1013** [comment]
Added mobile view to pull request and converted .mov to gif

**Review by Thinking-Panda — APPROVED** [review]
@jch1013 Nice work with the issue. Merge branches are good. Code changes are applicable and clean. Website works fine on the local machine. Thank you for the work!

**Review by ronaldpaek — APPROVED** [review]
Everything looks good to me, image updated and works perfectly even on mobile! 👍

**Pull request merged**
