### PR TITLE
Issue 3400

### LINKED ISSUE #3400: Update alt text for peace-justice image on the About Us page to adhere to WCAG
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). In this issue, we will change the alt text for the peace-justice image on the [About Us page](https://www.hackforla.org/about/).

### Details
Designers and PMs identified that some alt texts in the Events page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] In the file `_includes/about-page/about-card-sustainability.html`, change the following alt text

From
```
Peace, Justice and Strong Intitutions goal logo
```

To
```
16 Peace, Justice and Strong Institutions
```

- [x] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3361 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3361 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3361 
- [About Us page](https://www.hackforla.org/about/)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by Mattre7**
Fixes #3400

### What changes did you make and why did you make them ?
  - Changes alt text "Peace, Justice and Strong Institutions goal logo" to "16 Peace, Justice and Strong Institutions"
  - This is for the peace and justice card, found on line 54 in file _includes/about-page/about-card-sustainability.html
  - NOTE: initial issue had a spelling error which I corrected (instructions said "Intitutions")

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
  - This change does not change the appearance of the website

### CODE REVIEW

**Comment by Zak234** [comment]
ETA: Jul 28
Availability: Anytime

**Comment by Wny-Duong** [comment]
Availability: 1 hr
ETA: 7/28/22

**Review by Wny-Duong — APPROVED** [review]
Nice work on catching the typo. Thanks for making the correction!

**Comment by Mattre7** [comment]
> Nice work on catching the typo. Thanks for making the correction!

Of course, thank you for the review!

**Comment by arpitapandya** [comment]
Availability: 6 hrs
ETA: EOD 2022-07-29

**Review by arpitapandya — APPROVED** [review]
Changes looks good, and the typo you fixed it too!! Great job! @Mattre7

**Pull request merged**
