### PR TITLE
Fix misspelled words on citizens engagement card 

### LINKED ISSUE #2909: Fix misspelled words on citizen-engagement-card.yml file from "policymaking" to "policy making"
### Dependency
- [x] https://github.com/hackforla/website/issues/3546

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [ ] For the file `_data/internal/program-areas/citizen-engagement-card.yml`, on line 6, change the spelling from "policymaking" to "policy making", so

  ```
  these projects empower local residents to impact policymaking in their communities.
  ```
  becomes
  ```
  these projects empower local residents to impact policy making in their communities.
  ```
- [ ] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/program-areas
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/citizen-engagement-card.yml
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_data/internal/program-areas/citizen-engagement-card.yml#L6

### PR DESCRIPTION
**Pull request by PMKnight**
Fixes #2909

### What changes did you make and why did you make them ?

  -change spelling from policymaking to policy making
  -
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screen Shot 2022-04-11 at 6 20 18 PM

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by harshitasao** [comment]
Availability : now for an hour.
ETA : 12/04/2022

**Review by harshitasao — CHANGES_REQUESTED** [review]
Hi! @PMKnight  Good job on this issue. The changes that you have made seem good to me. However, in the original issue [#2909](https://github.com/hackforla/website/issues/2909), there were some action items to be checked, which you have not checked. I think you should do that, and I see that you have made changes in [.vscode/settings.json](https://github.com/hackforla/website/blob/gh-pages/.vscode/settings.json), but I think that is not mentioned in the original issue. Can you please explain that?

**Comment by kathrynsilvaconway** [comment]
Availability: 1 hour
ETA: 4/12/2022 End of the Day.

**Comment by PMKnight** [comment]
Thank you @harshitasao, I just checked the items in the original issue. The settings.json changes are an error on my behalf. Is there a way to reject those changes?

**Comment by harshitasao** [comment]
> Thank you @harshitasao, I just checked the items in the original issue. The settings.json changes are an error on my behalf. Is there a way to reject those changes?

Adding a new commit to the branch(in this case fix-misspelled-card-2909) and push the branch. I think this should work.

**Review by kathrynsilvaconway — CHANGES_REQUESTED** [review]
@PMKnight Nice work on this issue. I see that you have fixed the typo in line 6 of the citizens engagement card. The code looks great. 

Please add screenshots of the actual page before and after the changes in the image section above rather than having a screenshot of the code there. Once you add them, request a a re-review from me and I will approve the changes.

**Comment by JessicaLucindaCheng** [comment]
@PMKnight Did you have questions or need clarification?

**Comment by JessicaLucindaCheng** [comment]
@PMKnight

> Thank you @harshitasao, I just checked the items in the original issue. The settings.json changes are an error on my behalf. Is there a way to reject those changes?


You can try doing a git revert on that commit where you made the changes in the json. Then push the changes to your branch fix-misspelled-card-2909

**Comment by SAUMILDHANKAR** [comment]
@PMKnight Planning to close this PR due to inactivity. Please let us know when your availability changes. Will leave a slack message and email as well. Thanks.

**Pull request closed without merging**
