### PR TITLE
Refactor Buttons on Sitemap and Events Pages - #2159

### LINKED ISSUE #2159: Complete refactor/standardization of all buttons within Sitemap/Events Page
## Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

### Action Items
- [x]  Make the 3 recommended edits for the buttons from the spreadsheet below (2 files will be updated)
  

1. - [x] Update **line 43** of `website/pages/sitemap.html` with HTML from the `Reccomendation` column
2. - [x] Update **line 65** of `website/pages/sitemap.html` with HTML from the `Reccomendation` column
3. - [x] Update **line 19** of `website/pages/events/left-col-content.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Home page
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

### PR DESCRIPTION
**Pull request by tamara-snyder**
Fixes #2159

### What changes did you make and why did you make them ?

  - Updated line 43 of website/pages/sitemap.html with HTML from the Recommendation column in the [CSS Standardization](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit#gid=0) spreadsheet
  - Updated line 65 of website/pages/sitemap.html with HTML from the Recommendation column in the [CSS Standardization](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit#gid=0) spreadsheet
  - Updated line 19 of website/pages/events/left-col-content.html with HTML from the Recommendation column in the [CSS Standardization](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit#gid=0) spreadsheet
  - It's not part of the issue, but I also updated the spreadsheet to indicate that these three buttons have now been refactored

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
This was a refactor, so there are no visible changes:

<details>
<summary>Visuals before changes are applied</summary>

2159-before
2159-events-before

</details>

<details>
<summary>Visuals after changes are applied</summary>

2159-after
2159-events-after

</details>

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 2 hours
- ETA: Tue, Feb 22, 2022

**Comment by Carlos-A-P** [comment]
Availability: 4hrs
ETA: Tue, 2/22/2022

**Review by Carlos-A-P — APPROVED** [review]
@tamara-snyder Awesome work! I can see the code changes, and the buttons still function as they should. Don't forget to add this PR to the project board.

**Comment by JessicaLucindaCheng** [comment]
Sorry, I am going to delay my review by one day. I'm not feeling well right now.
- Availability: 2 hours
- Review ETA: Wed, Feb 23, 2022

**Review by JessicaLucindaCheng — APPROVED** [review]
@tamara-snyder Good job! I see the changes in my environment and all the buttons function as expected. Thank you for updating the spreadsheet too.

**Pull request merged**
