### PR TITLE
Made changes to spare.md issue 2437

### LINKED ISSUE #2437: Remove outdated Site link for Spare
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly. If they are outdated or no longer work, they should be removed.

### Action Items
- [ ] Remove the Site link for Spare since it is outdated
    - **Lines 12 - 13** under `_projects/spare.md`

Delete:
```
 - name: Site
   url: 'http://whatcanyouspare.org'
```

- [x] Ensure that the site link is removed from the [projects page](https://www.hackforla.org/projects/) and [Spare page](https://www.hackforla.org/projects/spare)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/spare.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Spare page](https://www.hackforla.org/projects/spare)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/883a983b8f987ad3c0167781de7512c8c06b0d60/_projects/spare.md#L12-L13

### PR DESCRIPTION
**Pull request by KazushiR**
Fixes #2437 

### What changes did you make and why did you make them ?

I have deleted the spare.md within _projects/spare.md. I have deleted the link as described.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

 Deleted the spare.md link

<details> This is what it looked like before teh change per below
<summary>Visuals before changes are applied</summary>

image

</details>
This is what it looks like after deleting the spare.md
<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by SAUMILDHANKAR** [comment]
Review ETA: In an hour
Availability: Tuesday 5-6 PM

**Review by SAUMILDHANKAR — CHANGES_REQUESTED** [review]
@KazushiR Good job in making your first PR. The code changes that you have made look good. However, I would request you to make the following changes before I finish the review:
- Please add this PR to the project board
- Please add the issue number at the top of your initial post.
- Also, please add a description note for what changes you have made

Once you are done with the changes re request a review. Thank you.

**Comment by KazushiR** [comment]
> @KazushiR Good job in making your first PR. The code changes that you have made look good. However, I would request you to make the following changes before I finish the review:
> 
> * Please add this PR to the project board
> * Please add the issue number at the top of your initial post.
> * Also, please add a description note for what changes you have made
> 
> Once you are done with the changes re request a review. Thank you.

@SAUMILDHANKAR  I have updated the above request. Please let me know if the PR can be closed out.

**Comment by SAUMILDHANKAR** [comment]
@KazushiR Thank you for making the changes. Can you please re request a review as well?

**Comment by KazushiR** [comment]
> @KazushiR Thank you for making the changes. Can you please re request a review as well?

@SAUMILDHANKAR I have sent a re request. Please let me know if there are problems with it

**Comment by SAUMILDHANKAR** [comment]
Revised review ETA: End of day 2/16/22
Availability: 1 hour Wednesday

**Review by SAUMILDHANKAR — APPROVED** [review]
@KazushiR: Thank you for making all the changes. Looks good in my environment. Great job!

**Pull request merged**
