### PR TITLE
img Tag Refactor

### LINKED ISSUE #5028: img Tag Refactor: includes/about-page/about-card-accomplishments.html -2
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-accomplishments.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/about/wins-card-desktop.svg" alt="Wins card: contributors' names, teams and roles, and testimonials of their accomplishments." />
```
to
```
<img src="/assets/images/about/wins-card-desktop.svg" alt="Wins card: contributors' names, teams and roles, and testimonials of their accomplishments.">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html
2. Webpage(s): https://www.hackforla.org/about/#accomplishments
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by tkubota31**
Fixes #5028

### What changes did you make?
  - Removed the ending slash of the img tag within the div with class of "wins-card-desktop"
### Why did you make the changes (we will use this info to test)?
  - To standardize and keep the formatting consistent within the codebase.
### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by yujioshiro** [comment]
Hey @tkubota31, it looks like the bot didn't automatically pull the labels from the issue. Could you update the labels on this PR with the labels from the issue?

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @tkubota31 - Great job! Your branches look good and you provided the whats and the whys for making the changes. Some notes: 

As @yujioshiro noted, the labels from the original issue did not transfer to the PR. This might happen if you don't include the "Fixes #----" when the PR is created. Also, the formatting after "What changes did you make?" and "Why did you..." is funky- this can be fixed by editing the description and adding a space between the dash and the reason, e.g.  

```
 - Removed the ending slash...
```
instead of 
```
 -Removed the ending slash...
```
Finally, the extra dashes/bullets can be deleted as can the lines regarding screenshots since this particular issue doesn't require that. 

Otherwise, everything looks great. Thanks for working on this issue!

**Review by yujioshiro — CHANGES_REQUESTED** [review]
Apart from the changes @t-will-gillis suggested, I want to mention the changes of spaces and new lines in your file. I'm not sure if those are changes your text editor or IDE made or if that's something you did, but I think it's best to make sure that doesn't happen in the future. Those changes don't need to be reverted for this PR as it has no effect on the end result, but I can imagine it becoming very distracting and complicated to look at if many more lines were changed.

Once the changes are made, go ahead and click on the "Re-request review" button on the side and we will re-review this PR for you.

image

Other than that, good job on opening up your first PR @tkubota31!

**Review by t-will-gillis — DISMISSED** [review]
Hi @tkubota31 Thanks for making the changes!

**Review by yujioshiro — APPROVED** [review]
All changes look good. Thank you @tkubota31

**Pull request merged**
