### PR TITLE
Update Guides Team Page - #6373

### LINKED ISSUE #6373: Update Project Profile: Guides Team (Remove Sarah Levine, Add Ayma Rahman)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/guides-team.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable and remove the following:
```
  - name: Sarah Levine
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U05RWQJ8YKU'
      github: 'https://github.com/levines2017'
    picture: https://avatars.githubusercontent.com/levines2017
```
- [x] Find the `leadership` variable and add the following:
```
  - name: Ayma Rahman
    github-handle: aymarmsba
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U06C183Q2HL
      github: https://github.com/aymarmsba
    picture: https://avatars.githubusercontent.com/aymarmsba
```
- [x] If there are other Product Managers, place Ayma's profile after the other Product Managers' profiles
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Guides Team page [^2]
- [ ] Once your pull request is merged, go to #6364 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #6364 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        
      </details>

### Resources/Instructions
- This issue was initiated by #6364 
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/guides-team

### PR DESCRIPTION
**Pull request by piecanoe**
Fixes #6373

### What changes did you make?
  - Removed Sarah Levine from Guides Team page
  - Added Ayma Rahman to Guides Team page below other existing Product Managers

### Why did you make the changes (we will use this info to test)?
  - I assume Sarah Levine is no longer a Product Manager on the Guides Team and Ayma Rahman has been added as a Product Manager on the Guides Team

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

6273_before

</details>

<details>
<summary>Visuals after changes are applied</summary>

6273_after

</details>

### CODE REVIEW

**Comment by tonyvang** [comment]
Availability: Friday evening, Sunday evening
ETA: EOD Sunday

**Comment by aidanwsimmons** [comment]
Availability: weekdays afternoon/evening
ETA: EOD Wednesday

**Review by aidanwsimmons — DISMISSED** [review]
Looks Great!

- issue linked correctly
- branch looks good
- screenshots attached
- changes look good on my end
NIce job

**Review by jphamtv — CHANGES_REQUESTED** [review]
Hey @piecanoe - Thanks for working on this issue. I noticed all single quotes have been changed to double quotes. This change wasn't part of the issue's Action Item instructions and is out of scope for this PR. Maybe it was a linter setting that made these changes automatically? Could you please update to reflect only the modifications outlined in the issue's request? Appreciate your understanding and effort!

**Review by tonyvang — CHANGES_REQUESTED** [review]
Your linked issue and branch look correctly done, and your screenshots show the desired visual effect on the website. I do see those quotation changes noted by @jphamtv, as well as deletions of spaces after colons at the ends of lines 36, 44, and 50 of the live code, or 37, 45, and 51 of your changed code which could also be reverted. The shift in line numbers is fine, I think - just occurs because Levine's profile in the live code doesn't have a line for github handle and Rahman's does. I'll wait for your next commit and then give it a proper test and another review!

**Comment by piecanoe** [comment]
Thanks for the feedback @jphamtv and @tonyvang. I reverted the double quotes back to single quotes and added back the spaces at the lines noted by @tonyvang. 

Availability: Saturday afternoon, Sunday evening
ETA: EOD Sunday

**Review by tonyvang — APPROVED** [review]
Hi @piecanoe, your code change looks clean and it tests to the desired effect described in your PR and the linked issue. Approved, fantastic work! Thanks for your contribution and for bearing with.

**Review by jphamtv — APPROVED** [review]
Thanks for making the updates @piecanoe. And great feedback on the additional items @tonyvang. 

- The pull request is done with the correct branch 
- The issue is properly linked
- Your summary of changes is clear
- The before/after screenshots confirm the changes
- Your code update is clean and accurate 

Great work!

**Pull request merged**
