### PR TITLE
Infinity image redesign 3342

### LINKED ISSUE #3342: Add credit for Infinity image for redesigned homepage
### Overview
We need to add a credit for a new image used in the redesigned version of the homepage so that the [Credits page](https://www.hackforla.org/credits/) is up to date.

### Details
From the [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724), here is a screenshot of the credit's information for reference:
  <details>
    <summary>Click here to see the screenshot of the Infinity credit in Figma</summary>
    
  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] In `_data/internal/credits` directory, create a file called `infinity.yml`
- [x] In the file you just created, copy and paste the following:
```
---
# The title from the source provider
title: Infinity
# The url where you can get direct access to the image on the provider site
title-link: https://thenounproject.com/search/?q=infinity&i=686117
# The type of content - image, audio, or video 
content-type: image
# The page it's used on
used-in: Homepage
# Name of the artist
artist: Yeong Rong Kim
# Name of the image database you found it on
provider: Noun Project
# Please give the general site URL, not the link to the image
provider-link: https://thenounproject.com/
# Location in our GitHub repo
image-url: /assets/images/hero/infinite.svg
# Alt text for the image on the Credits page
alt: ''
---
```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3130 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #3130 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
- This issue is tracked in the epic #3130.
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
- [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

### PR DESCRIPTION
**Pull request by arpitapandya**
Fixes #3342

### What changes did you make and why did you make them ?

  - Added Infinity.yml in _data/internal/credits
  - Removed unnecessary lines from _sass/components/_home.scss that's causing errors

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
Capture
Infinity
</details>

### CODE REVIEW

**Comment by BeckettOBrien** [comment]
Availability: 5 Hours
ETA: EOD 7/19/22

**Comment by lilyarj** [comment]
ETA: 7/19
Availability: 3 hrs

**Review by BeckettOBrien — CHANGES_REQUESTED** [review]
The `infinity.yml` file looks good, but I am a little confused as to why the `_home.scss` file changed (I think there might have been a merge conflict because lines 21-25 in your file were removed in a previous commit) and I don't think that `docker-compose.yml` should be added to the gitignore.

**Comment by arpitapandya** [comment]
> The `infinity.yml` file looks good, but I am a little confused as to why the `_home.scss` file changed (I think there might have been a merge conflict because lines 21-25 in your file were removed in a previous commit) and I don't think that `docker-compose.yml` should be added to the gitignore.

I have removed docker-compose.yml from gitignore now. That was just a temporary fix for the linter issue I was having from _home.scss

**Review by BeckettOBrien — CHANGES_REQUESTED** [review]
That looks better but there are still changes to `_sass/components/_home.scss` that undo someone else's work from the feature branch. Is there some way you can restore the correct version of the file?

**Comment by arpitapandya** [comment]
> That looks better but there are still changes to `_sass/components/_home.scss` that undo someone else's work from the feature branch. Is there some way you can restore the correct version of the file?

It is updated now. Though I haven't removed lines 21 to 25, I have seen totally different non CSS lines which I and one of hackforla senior fellow were discussing on which was causing linter issues, not sure why it isn't showing. But Everything is updated now and I think It was after feature branch updated.

Changes made : `infinity.yml`, removed temp `docker-compose.yml` from `gitignore` and restored `_home.scss`(lines 21 to 25 are back but not sure if that's correct because they're not in `feature-homepage-launch` as updated.

**Comment by BeckettOBrien** [comment]
I think those non-css lines were from a merge conflict (if they looked like this: `<<<<<<< HEAD`). The problem is that GitHub is showing that if this PR were merged, [it would add 5 lines and remove 1 line](https://github.com/hackforla/website/pull/3385/files#diff-fc3339adc220b8ed4f977e255974a8116fa1e7315ae63793596c77b4849df163) from [the existing scss file](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_home.scss#L19).

**Comment by arpitapandya** [comment]
> I think those non-css lines were from a merge conflict (if they looked like this: `<<<<<<< HEAD`). The problem is that GitHub is showing that if this PR were merged, [it would add 5 lines and remove 1 line](https://github.com/hackforla/website/pull/3385/files#diff-fc3339adc220b8ed4f977e255974a8116fa1e7315ae63793596c77b4849df163) from [the existing scss file](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_home.scss#L19).

Yes, they were. Let me know if this doesn't work and still have the changes then I can either close this and create new PR or will look for another solution

**Comment by BeckettOBrien** [comment]
I don't think you have to create a new PR (you can if you want to, but it probably isn't necessary) if you just copy the contents of the [current scss file](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_home.scss#L19) into yours or even checkout the file from the feature branch.

**Review by BeckettOBrien — COMMENTED** [review]
For some reason, GitHub still shows changes to `_home.scss` but it looks fine to me. I'm not quite sure if it's an issue or not but everything else looks good to me.

**Review by Zak234 — COMMENTED** [review]
It seems there are some changes in _home.scss that aren't supposed to be there but the changes don't seem to actually affect the file as its a deletion and then addition of a parentheses. The infinity.yml file looks good but I'm not sure that its supposed to have the lines on the top and bottom. I may be wrong but I think you were just supposed to copy the code between the lines.

**Comment by BeckettOBrien** [comment]
@Zak234 I'm pretty sure that the lines are fine because it's [Jekyll front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by arpitapandya** [comment]
@BeckettOBrien So do we have changes? or it's good now to be approved?

**Review by BeckettOBrien — APPROVED** [review]
I think everything is fine. The changes in `_home.scss` doesn't affect the site so it should be okay.

**Review by Zak234 — APPROVED** [review]
Checked everything over again. Everything looks good and seems to be working. Great job!

**Review by lilyarj — APPROVED** [review]
Everything looks good!

**Pull request merged**
