### PR TITLE
Updated alt text for Access The Data image to adhere to WCAG

### LINKED ISSUE #3870: Access The Data: Update alt text for Access The Data image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text for the `Access The Data` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/access-the-data.md`:

**From:**
```
alt: 'description of the card image'
```

**To:**
```
alt: 'Access The Data'
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- Access The Data Page: https://www.hackforla.org/projects/access-the-data

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/access-the-data.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md
- This issue is part of epic #3866 

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by amath95**
Fixes #3870

### What changes did you make and why did you make them ?

- Updated alt text for access the data image to 'Access The Data' to adhere to WCAG

### CODE REVIEW

**Comment by chrismenke45** [comment]
ETA: 3/30 EOD, 
Availability: 10am-12pm

**Review by chrismenke45 — APPROVED** [review]
Looks good! The correct change has been made and its reflected when you run the site and inspect the image.

**Comment by amath95** [comment]
Hey Chris! Should I move this issue to new issue approval board?

**Comment by chrismenke45** [comment]
Hi Amath, I believe it should be in the questions/ in review.

**Comment by KazushiR** [comment]
ETA: 3/30 EOD,
Availability: 1PM-12AM

**Review by KazushiR — APPROVED** [review]
@amath95 Hello Amath. I checked your PR request and looks like it is showing up perfectly fine on my side. Good job!

**Comment by amath95** [comment]
Thank you guys for the feedback 🙏

**Review by blulady — APPROVED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing line 15 to alt: 'Access The Data'. The code looks clean, only one commit and only one file changed. You also mentioned what changes you made in the PR comment and why you made them.
Good job!!

**Pull request merged**
