### PR TITLE
Updated act.yml credits file

### LINKED ISSUE #2791: Edit content field and remove type field from act.yml credits file
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want to edit the content field and remove the type field from a credit's yml file so that redundant code is removed and the code is easier to understand.

### Details
Currently, in each credit's yml file, there is a `content` field and a `type` field, which contains similar information. Since the fields are redundant, we decided to remove the `type` field.  

Also, we changed the `content` field to the `content-type` field to make it clearer what its purpose is. The possible values for `content-type` field are image, video, or audio; other types of content can be added if necessary. In the future, this will allow developers a way to differentiate easily between different types of content in order to show each credit's media file correctly on the website.

### Action Items
For the file `_data/internal/credits/act.yml`, do the following:
- [ ] Change line 4 for the content field from
  ```
  content: icon
  ```
  to
  ```
  content-type: image
  ```
- [ ] Remove line 11 for the type field
  ```
  type: icon
  ```
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #2775 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue #2775 to the New Issue Approval column and remove the Dependency label
  
### Resources/Instructions
-  This issue is tracked in the epic #2775.

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/act.yml`

- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/0797a71debbcad369106a8a1b063b133c7127dde/_data/internal/credits/act.yml#L4
https://github.com/hackforla/website/blob/0797a71debbcad369106a8a1b063b133c7127dde/_data/internal/credits/act.yml#L11

### PR DESCRIPTION
**Pull request by harshitasao**
Fixes #2791

### What changes did you make and why did you make them ?

  - Changed line 4 for the content field from content: icon to content-type: image
  - Removed the type field type: icon
  - I edited it so that it can be better utilized in the [credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html) file in the future

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

  No visual changes to the website.

### CODE REVIEW

**Comment by JessicaLucindaCheng** [comment]
- Availability: 1 hour
- Review ETA: Fri, Feb 25, 2022

**Comment by JessicaLucindaCheng** [comment]
@usaboo If you are interested in reviewing this pr, assign yourself as a reviewer and not an assignee. I went ahead and removed you as an assignee.

**Review by JasonY188 — APPROVED** [review]
Hi harshitasao,

I see that you changed line 4 to content-type: image and removed line 11.
Looks good to me.  Great job!

**Review by JessicaLucindaCheng — APPROVED** [review]
@harshitasao Good job on your first issue! Feel free to pick up a good second issue.

**Comment by harshitasao** [comment]
@JessicaLucindaCheng @JasonY188 Thank you for reviewing and approving my PR.

**Pull request merged**
