### PR TITLE
added github handle to Maxwell Countryman Skewes profile 6180

### LINKED ISSUE #6180: Add github-handle for Maxwell Countryman Skewes in civic-tech-index.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-index.md` in the IDE
- [x] Replace:
```
- name: Maxwell Countryman 
```
with
```
- name: Maxwell Countryman 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-index

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by aswutmaxcy**
Fixes #6180

### What changes did you make?
  - added "github-handle"...

### Why did you make the changes (we will use this info to test)?
  - to allow for a value for a github handle to be added in the future

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

No visual changes, just a place to add a github handle in future

### CODE REVIEW

**Review by heejung-hong — CHANGES_REQUESTED** [review]
Hi @aswutmaxcy ,
"github-handle" is spelled incorrectly.  The pushed code has "githube".
Please make the corrections and push your code again.
Thank you

**Comment by aswutmaxcy** [comment]
@heejung-hong Thank you for the catch! Just edited the line with the correction.

**Review by heejung-hong — APPROVED** [review]
Good work!
The branches are correct and the issue is linked.
The correct file was changed with the correct information.

**Review by marioantonini — APPROVED** [review]
Changes looks good.
Thanks for taking the time to work on this!

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @aswutmaxcy - everything looks great with your issue, and thanks for working with @heejung-hong to resolve the changes requested. 

I have one more request and it involves the formatting for Markdown in the description section: please edit the text for 'what changes were made and why' by adding a space between the dash and the text explanation, and also by removing the extra dash (in two locations). ie replace:
```
-added "github-handle"...
-
```
with:
```
- added "github-handle"...  

```
Thanks! After that, this PR is ready to merge

**Comment by aswutmaxcy** [comment]
@t-will-gillis changed the markdown description to copy your comment

**Review by t-will-gillis — APPROVED** [review]
Looks great, thanks @aswutmaxcy!

**Pull request merged**
