### PR TITLE
Update trophy icon on about page and credit page

### LINKED ISSUE #2043: Update ‘Trophy’ Icon and Credit info
### Overview
We need to replace the Trophy icon in the Wins section of the [About page](https://www.hackforla.org/about/#accomplishments) (under Accomplishments) because the credit link for it isn’t a direct link, and the original icon link can’t be tracked down. 
### Action Items
- [x] Replace the Trophy icon in the Wins section of the [About page](https://www.hackforla.org/about/#accomplishments) (under Accomplishments) with the new one that has now replaced it in the [About page Figma file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)(in pink rectangle- scroll down to Wins section to locate and export new icon. Or just go to the bottom of the credit section in green rectangle, where the new icon and its info has replaced the old one)
- [x] Replace the old icon credit info in the [Credits page](https://www.hackforla.org/credits/) with the new icon’s credit info
  - [x] New icon credit link: https://thenounproject.com/term/trophy/3115497/ 
  - [x] New icon Artist: **iconpixel, ID** 
### Resources/Instructions
[About page](https://www.hackforla.org/about/#accomplishments) 
[About page Figma file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)
[Credits page](https://www.hackforla.org/credits/)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)
New Trophy icon:
128059882-89b873a2-f2e6-45ae-abb4-f5c7018a2964
128059899-ad7e4efb-98fd-40a8-be11-e3ea1a05c49c

### PR DESCRIPTION
**Pull request by Zhu-Joseph**
Fixes #2043 

### What changes did you make and why did you make them?

  -Updated wins-cup.svg file to new trophy icon
  -New trophy icon appears on both [About ](https://www.hackforla.org/about/) page and [Credits ](https://www.hackforla.org/credits/) page
  -Updated trophy icon Artist in  [Credits ](https://www.hackforla.org/credits/) page

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

trophy-before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
trophy-after

</details>

### CODE REVIEW

**Review by macho-catt — CHANGES_REQUESTED** [review]
Hi @Zhu-Joseph, good job overall on the code change! However, you missed one ask from the issue creator.

The title-link in the yml file needs to be updated as well so that it points properly to the site that it came from (i.e. https://thenounproject.com/term/trophy/3115497/)

**Comment by Zhu-Joseph** [comment]
> Hi @Zhu-Joseph, good job overall on the code change! However, you missed one ask from the issue creator.
> 
> The title-link in the yml file needs to be updated as well so that it points properly to the site that it came from (i.e. https://thenounproject.com/term/trophy/3115497/)

Hi @macho-catt thanks for pointing that out, I must of just missed it. I updated the title-link in the yml file. It should be good to go now.

**Review by macho-catt — APPROVED** [review]
Lgtm. Good job!

**Review by blakes24 — APPROVED** [review]
Everything looks good. Nice job.

**Pull request merged**
