### PR TITLE
Fix position of first paragraph on Getting Started

### LINKED ISSUE #3973: Fix Position of First Paragraph on Getting Started Page when the Viewport Width is Below 768px
### Overview

As developers, we want to ensure that there are no visual inconsistencies with the text on the website. We need to reposition the first paragraph on the Getting Started page so that it is visually consistent with the other paragraph on the page.

### Details
<details>
<summary>Current State of the Paragraphs When the Viewport Width is below 768px</summary>

image

</details>

<details>
<summary>Future State of the Paragraphs When the Viewport Width is below 768px</summary>

image

</details>

### Action Items

- [x] Update class `.header-bold-p` in the scss file so that the opening paragraph is positioned similarly to the paragraph below it.
- [x] Test your update by setting the viewport width below 768px and verifying that the two paragraphs under the Getting Started header are positioned uniformly with each other. 
- [x] Test your update at other viewport widths and verify that there are no unintended side effects at those viewport widths

### Resources/Instructions

- [Getting Started Page](https://www.hackforla.org/getting-started)
- [Hack for LA Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465)
- [_getting-started-page.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss)

### PR DESCRIPTION
**Pull request by ronaldpaek**
Fixes #3973

### What changes did you make and why did you make them ?

  - Repositioned the first paragraph on the Getting Started paged so that it is visually consistent with the other paragraphs on the page.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

ezgif com-video-to-gif (7)

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
ezgif com-video-to-gif (8)

</details>

### CODE REVIEW

**Comment by Adastros** [comment]
Availability (PST): 9:45 - 10:30 PM 05MAR23; 9 - 11PM 06MAR23, 07MAR23
Review ETA (PST): 10:30 PM 05MAR23

**Review by Adastros — DISMISSED** [review]
@ronaldpaek good job on implementing a solution for the issue! The paragraphs are visually consistent for various viewport widths. 

I did notice that adding `margin: 0 auto` caused the spacing between the paragraphs to shorten a bit. Looking at the [getting started wire-frame design on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18299%3A128599&t=Bc2dumB4d0Gv9F1k-0), it looks like the intention was to have them spaced 23px apart. With the current commit, the paragraphs are spaced 12px apart. On the current released version of Hack for LA website, the paragraphs are spaced 18px apart. Could you update the spacing to have it match the wire-frame design? I think it should be fine to implement this fix within your pull request. No need to create an emergent request issue to fix this spacing. 

<details>
<summary>Getting Started Wire-frame Screenshot</summary>

image

</details>

In addition, could you add a new line right after line 17 for the `.header-bold-p` class? This is to help with the code formatting. It's minor but I think it's fine to add it.

**Comment by Adastros** [comment]
Not related to this issue and does not affect approval of pull request, but commenting here to document, investigate, and possibly create an emergent request issue to fix the `font-family` css attribute and commented `padding-bottom` css attribute within the `_getting-started-page.scss` file for the following classes so far

- header-bold-p
- header-p
- getting-started-page

The font-family attribute should either have a comma to separate the fonts or removed entirely. Commented `padding-bottom` css attribute should be removed if not needed.

**Comment by ronaldpaek** [comment]
> @ronaldpaek good job on implementing a solution for the issue! The paragraphs are visually consistent for various viewport widths.
> 
> I did notice that adding `margin: 0 auto` caused the spacing between the paragraphs to shorten a bit. Looking at the [getting started wire-frame design on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18299%3A128599&t=Bc2dumB4d0Gv9F1k-0), it looks like the intention was to have them spaced 23px apart. With the current commit, the paragraphs are spaced 12px apart. On the current released version of Hack for LA website, the paragraphs are spaced 18px apart. Could you update the spacing to have it match the wire-frame design? I think it should be fine to implement this fix within your pull request. No need to create an emergent request issue to fix this spacing.
> 
> Getting Started Wire-frame Screenshot
> In addition, could you add a new line right after line 17 for the `.header-bold-p` class? This is to help with the code formatting. It's minor but I think it's fine to add it.

Wow, your level of attention to delay is very good. I also think I missed this cause the container and my CSS changes kind of lag to reflect the change. Thank you for bringing attention to the Figma wireframe; I'm still getting used to working on issues. I made the change for the spacing on the bottom to now be 32px and I added an extra line between selectors.

**Comment by ronaldpaek** [comment]
Availability (PST): 4:00AM - 4:30AM- 03/06/23
ETA (PST): 4:30AM - 03/06/23

**Comment by Adastros** [comment]
Hi @ronaldpaek, thanks for the update and no worries! We're all here to learn. I'm not an expert at Figma and am still familiarizing myself with it. 

Your latest commit fixed the spacing issue when the viewport width is less than 768px but it had an unintended side effect of causing the spacing between the paragraphs to increase at viewport widths greater than or equal to 768px. 

<details>
<summary>Paragraphs When Viewport Width >= 768px - Current Website</summary>

image

</details>

<details>
<summary>Paragraphs When Viewport Width >= 768px - With Latest Changes</summary>

image

</details>

I'm thinking you can keep what you have now but change the bottom margin from 23px to 16px. Then add another line within the `@media #{$bp-below-tablet}` to change the bottom margin to 23px to match the mobile wireframe design. Unfortunately, it doesn't seem like I can figure out the exact spacing between the paragraphs for the desktop wireframe design so I think keeping the bottom margin at 16px like it is on the current version of the website is good.

**Comment by RyanGehris** [comment]
Availability: 6-8pm
ETA: EOD 03/08/2023

**Comment by RyanGehris** [comment]
Update: After reading the conversation above, I agree and will review this PR once the requested changes have been made.

**Comment by ronaldpaek** [comment]
Availability: 6-8 pm 03/10/23
ETA: EOD 03/10/23

So sorry for the delay, I had to help my team set up a project using the newest Next.JS issues, but I will work to resolve and fix this issue by tonight.

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Hi @ronaldpaek @Adastros is away so I will review in his place.  When you have made the change he requested, please click the re-review icon next to my name.  By the way, the animated gif you used for the "before" and "after" was really nice; what utility did you use to create it?

**Comment by ronaldpaek** [comment]
> Hi @ronaldpaek @Adastros is away so I will review in his place. When you have made the change he requested, please click the re-review icon next to my name. By the way, the animated gif you used for the "before" and "after" was really nice; what utility did you use to create it?

@roslynwythe Okay, this week has been a rough week for me, I'm going to work on this issue in the morning now that I was finally able to get a solution working for something I had to finish.

As far as the gif if you use a mac I just press cmd shift and 5 and I record a section of the screen but the file size is usually too big so I usually go to this site to convert the videos to gif. 🙂

 https://ezgif.com/video-to-gif

**Comment by ronaldpaek** [comment]
@roslynwythe sorry took so long, but I fixed the requested changes asked I am also wondering how I should name each fix commit is it okay if it's the same message?

**Review by RyanGehris — APPROVED** [review]
Thank you for working on this issue. After reviewing the before and after on my local machine, your changes successfully fixed the positioning of the paragraphs to be in line, and also maintained the spacing between them. Great work!

**Comment by ronaldpaek** [comment]
@RyanGehris awesome! thank you

**Review by roslynwythe — APPROVED** [review]
@ronaldpaek thank you for your work on this issue.  The branches are setup correctly, the code is clean and the resulting page looks good at all screen sizes.

**Pull request merged**
