### PR TITLE
updated project page filters to show tools

### LINKED ISSUE #6196: Add Tools to the Languages/Technologies filter group on the projects page
### Overview
We need to add Tools into `Languages/Technologies` filter on the projects page, revising it to `Languages/Technologies/Tools`, in order to provide users with the ability to filter projects based on Tools.  

### Details
The [projects](https://www.hackforla.org/projects) and [projects-check](https://www.hackforla.org/projects-check) pages share the same js file `/assets/js/current-projects.js` ; based on the value of `window.location.pathname`, the code implements different filters between the pages.   Note that in this issue we do not want to alter the projects-check in any way.  

### Action Items
- [x] Open the file `assets/js/current-projects.js` in your IDE
- [x] Update the code to add `Tools` to the `Languages/Technologies` filter
- [x] Rename the filter `Languages/Technologies/Tools`
- [x] Using docker, confirm the operation of the filters on the `/project` page
- [x] Using docker, confirm that the appearance and behavior of the `/projects-check` page is unchanged.  

### Resources/Instructions
- Projects page: [webpage](https://hackforla.org/projects) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- Projects Check page: [webpage](https://hackforla.org/projects-check) | [HTML include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- This issue was created from #6150

### PR DESCRIPTION
**Pull request by partapparam**
Fixes #6196 

### What changes did you make?
  - Added `Tools` into `Languages/Technologies` filter on the projects page, revising it to `Languages/Technologies/Tools`
  - Update `projectCardComponent` to include Tools in the file for frequency tracking
  - Refactored `createFilter` function so that Tools is added as a filter
  - Added `tools` into updateProjectCardDisplayState
  - Added `tools` to be tracked with technologies in the `updateCategoryCounter`

### Why did you make the changes (we will use this info to test)?
  - Provide users with the ability to filter projects based on Tools.
  - Ensure that when a Tool is selected as a filter, it displays correctly as `Tool: <tool-name>`
  - Ensure that `projects-check` page does not change

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
Screenshot 2024-03-29 at 5 26 21 PM
Screenshot 2024-04-01 at 7 44 01 PM
Screenshot 2024-04-01 at 7 44 12 PM

image

</details>

### CODE REVIEW

**Comment by aadilahmed** [comment]
Review ETA: EOD 4/2/24
Availability: 9-5 PM Monday - Friday

**Comment by JackCasica** [comment]
Hi ~ I'll be reviewing this PR today ~
Availability: (04/01)
ETA: EOD (04/01)

**Review by JackCasica — CHANGES_REQUESTED** [review]
Hi @partapparam ~ In this PR you...
- [x] Consolidated Filter Category: The technologies filter category now includes languages, technologies, and tools. This consolidates these related items into a single filter, making it easier for users to find what they need. ✅

- [x] Updated Project Card Component: The projectCardComponent function has been updated to include all languages, technologies, and tools in the data-technologies attribute of the project card. This allows the updateFilterFrequency function to accurately calculate and display the frequency of each filter item across the visible project cards. ✅

I did notice that something in the filtering logic on line 233 is preventing "ArcGIS surveys" from showing up in the new consolitated filter list: 
image

Additionally the badge component that shows up when a category is selected is no longer accurate if the changes requested in the issue are implemented.
image
"Technology: ArcGIS surveys" should be "Tool: ArcGIS surveys"

I believe this should be addressed as part of this issue, but you may want to move the the issue to Questions / In Review to get clarification as to whether this piece should be it's own future issue before working on it.

**Review by partapparam — COMMENTED** [review]
@JackCasica thanks for the detailed feedback. It looks like there was a conflicting merge after my submission so I've updated the code to reflect the changes.

**Review by aadilahmed — APPROVED** [review]
Filtering by tools works correctly on the project page, great job!

**Comment by partapparam** [comment]
@JackCasica can you review the updated pull request? I believe I have made the changes you requested, though I'm unsure how to mark your change request as complete.

**Review by JackCasica — APPROVED** [review]

**Comment by JackCasica** [comment]
@partapparam Looking at your changes locally, I see that the 
- [x] `ArcGIS surveys` does in fact show up ✅
- [x] The badge text is accurate ✅
- [x] The projects-check page is unchanged per the issue requirements ✅
image

Nice job with everything! ~

**Pull request merged**
