### PR TITLE
Change alt text for Marvista community council image

### LINKED ISSUE #3107: Change alt text for Marvista community council image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Marvista community council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 56](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L56) for the alt text:

from
```
<img class="org-img" src="/assets/images/citizen-engagement/mar_vista_community_council.svg" alt="Join Us! marvista.org | mar vista community college logo">
```
to
```
<img class="org-img" src="/assets/images/citizen-engagement/mar_vista_community_council.svg" alt="Marvista Community Council">
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L56

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by ericvennemeyer**
Fixes #3107

### What changes did you make and why did you make them ?

  - Changed alt text for Marvista community council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement) from "Join Us! marvista.org | mar vista community college logo" to "Marvista Community Council"
  - This change was made to better conform to Web Content Accessibility Guidelines

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
No visible changes to website.

### CODE REVIEW

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-28

**Review by arpitapandya — APPROVED** [review]
The changes looks good! Great job!! @ericvennemeyer

**Comment by Wny-Duong** [comment]
Availability: 1 Hour
ETA: 7/28

**Review by Wny-Duong — APPROVED** [review]
Changes are good! Keep up the good work.

**Pull request merged**
