### PR TITLE
Fix Program Area for Diversity/Equity/Inclusion

### LINKED ISSUE #4120: Fix Program Areas filter for `Diversity, Equity & Inclusion`
### Dependency
- #4118

### Overview
We need to fix the Program Areas filter on the [projects page](https://www.hackforla.org/projects/) so that website visitors can filter and find the projects with the `Diversity, Equity & Inclusion` program area.

<details>

<summary>Demonstration of the bug</summary>

filter bug

</details>

### Action Items
- [x] In `assets/js/current-projects.js`, fix the Program Areas filter on the [projects page](https://www.hackforla.org/projects/) so that it works for `Diversity, Equity & Inclusion`.

#### Merge Team, Technical Lead, or Product Manager
- [ ] Once the pull request associated with this issue is merged, go to issue #3328 and check if all the issues listed under the `Dependency` section are closed. If they are all closed, move that issue (#3328) into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.

### Resources/Instructions
- [projects page](https://www.hackforla.org/projects/)
- [assets/js/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [pages/projects-page.html](https://github.com/hackforla/website/blob/gh-pages/pages/projects-page.html)
- [_includes/current-projects.html](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html)

### PR DESCRIPTION
**Pull request by t-will-gillis**
Fixes #4120

### What changes did you make and why did you make them ?
  - Fixed the ' Program Areas' dropdown filter on the HfLA Projects page so that visitors can select programs in the area of `Diversity, Equity & Inclusion`. 
  - Note that the fix also addresses the same bug at the same dropdown on the HfLA homepage.
  - Note that the fix also addresses a similar bug on the 'Diversity, Equity, and Inclusion' card on the HfLA Program Areas page.
  - It appears that the script as written is breaking due to both the comma and the ampersand in the program area name - `Diversity, Equity & Inclusion` . Per discussion with Bonnie and Jessica (re: notes in 4120), instead of refactoring the assets/js/current-projects.js script to work with the current program name, we are changing the program name to `Diversity / Equity / Inclusion ` to work with the script. 
  - Also included in this commit are changes to spelling in the comments section (that is, doesn't affect code)
  - Finally, the notes for Issue 4120 ask about potentially changing text for the headers in three pages. These potential changes are not included since they were not in the original scope

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before_projects

before_homepage

program areas
</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after_homepage

after_projects

after_program_areas

</details>

### CODE REVIEW

**Comment by nnr-nnr** [comment]
Review ETA: EOD Mon. 3/27/23
Availability: 12-4 PM 3/26, 3-8 PM 3/27–328/

**Review by nnr-nnr — APPROVED** [review]
Awesome work, @t-will-gillis ! This PR fixes the Diversity, Equity, and Inclusion (DEI) filter on the Projects, Home, and Program Areas pages. The DEI filter works with the other filters (ie, Status, Languages/Technology), as well. It passes the ABCs plus you've addressed some pesky typos, which is great.


One note:
There appears to be a preexisting bug with the Write for All project (one of the two DEI projects) when it's being filtered by Languages/Technology. 

- With this new branch, you can recreate the bug by filtering by DEI then by a Languages/Technology used in the Write for All project (ie, HTML, JavaScript, Svelte, or CSS). The Write for All project will not appear, only the New Schools Today project (the other DEI project)  if you choose JavaScript, HTML, or CSS (see image below). Svelte, the other Languages/Technology used in the Write for All project, doesn't even appear in the filter list for Languages/Technology.
- With this current site/old code, you can see this by trying to filter by Svelte, a Languages/Technology used exclusively by the Write for All project; Svelte doesn't even appear in the filter list for Languages/Technology. Write for All also doesn't appear when JavaScript, HTML, or CSS Languages/Technology filters are used.

It seems like a new Issue could be created for this unless leadership is already aware of it? This bug might be due to the [_projects/writeforall.md](https://github.com/hackforla/website/blob/gh-pages/_projects/writeforall.md) file not having a `technologies` attribute, as some of the other files in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects) have. However, I'm not positive where this Languages/Technology data is being pulled from. Please advise, as I haven't created an issue before. Thank you + nice work on this PR, again!
 
Screenshot 2023-03-26 at 1 32 14 PM
Pictured above: See how there's only (1) project listed under the CSS Languages/Technology filter even though both of the DEI projects have this technology listed.

**Comment by t-will-gillis** [comment]
Hi @nnr-nnr Awesome catch! I did not see that- you're right it is ignoring Write for All's languages completely. I think I unwittingly stumbled across the code that causes this-(`current-projects.js` line 27) but the fix might not be so easy so definitely this calls for a new issue. If you would like to write an issue for this, we would be happy to help you. It's also OK if you don't- just let us know. But in either case, thanks for finding the (new) bug!

**Comment by nnr-nnr** [comment]
Yes, I'd be happy to create a new issue to address this with some guidance. Maybe at Tuesday's dev meeting or Thursday OHs or if there's documentation I can follow? Otherwise, my schedule's pretty flexible, let me know whenever. Thanks!

**Comment by roslynwythe** [comment]
Availability: 3/27 2 - 4pm
ETA: 3/28 EOD

**Review by roslynwythe — APPROVED** [review]
Great work @t-will-gillis !  This PR is well-formed and testing confirms that it resolves issues on the homepage, Projects Page, and Program Areas pages.  Thank you also for fixing the typos.

**Pull request merged**
