### PR TITLE
Added labels to blank issue form with dependency yml file

### LINKED ISSUE #4491: Update labels: Issue Template: blank-issue-form-with-dependency
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
### Overview
As developers, we need to add the labels from the [Missing series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#missing-series) so that we can avoid the GitHub bot taking off the labels when devs add them to issues.
### Action Items
- [x] Navigate to `.github/ISSUE_TEMPLATE/blank-issue-form-with-dependency.yml`
- [x] Add the following line under the description field
   ```
   labels: ['role missing', 'Complexity: Missing', 'Feature Missing', 'size: missing','Draft']
   ```
- [x] Test the updated template using these [instructions](https://github.com/hackforla/website/issues/4307#issuecomment-1549888931).  Copy the contents of that comment into a new comment in this issue, and check off the boxes as you complete the steps.  

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process
URL of the issue branch on the test Repository:  https://github.com/kiwookim/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-dependency.yml
**For PM, Merge Team, or Tech Lead**
- [ ] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `.github/blank-issue-form-with-dependency.yml`
- This issue is part of epic #4307

### PR DESCRIPTION
**Pull request by kiwookim**
Fixes #4491

### What changes did you make and why did you make them ?

  - added labels to blank-issue-form-with-dependency.yml (labels: ['role missing', 'Complexity: Missing', 'Feature Missing', 'size: missing','Draft'])

  

### Screenshots of Proposed Changes Of The Website 

-No Visual Changes

**For PR Reviewers and Merge Team**
To review this issue, click the link below under "Link for reviewers" and verify that the labels match the updated labels string in the issue.

**Link for Reviewers**
This URL will be inserted by the dev during the test process
URL of the issue branch on the test Repository:  https://github.com/kiwookim/website/issues/new?assignees=&labels=role+missing%2CComplexity%3A+Missing%2CFeature+Missing%2Csize%3A+missing%2CDraft&projects=&template=blank-issue-form-with-dependency.yml
**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #4307 by
  - [x] Checking off the dependency for this issue
  - [x] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 1 hr 5/26
ETA 5/27 EOD

**Review by roslynwythe — CHANGES_REQUESTED** [review]
Thank you @kiwookim for great work on this issue.  Your branches are setup correctly, your code change is correct, and you completed the test procedure and copied the test URL into the PR for reviewers to use.  My only tiny request is to make a quick improvement to the description under in the section "What changes did you make.."  You might want to list the labels you added for the convenience of the reviewers.  The second bullet point is not clear so please expand on it or remove.   Thank you.

**Comment by kiwookim** [comment]
> Thank you @kiwookim for great work on this issue. Your branches are setup correctly, your code change is correct, and you completed the test procedure and copied the test URL into the PR for reviewers to use. My only tiny request is to make a quick improvement to the description under in the section "What changes did you make.." You might want to list the labels you added for the convenience of the reviewers. The second bullet point is not clear so please expand on it or remove. Thank you.

Thank you for the review roslyn! I made the changes. Thank you

**Comment by LOSjr4** [comment]
Availability: weekdays 9AM-1PM
ETA: 5/29 1PM

**Review by roslynwythe — APPROVED** [review]

**Review by LOSjr4 — APPROVED** [review]
I saw how we originally didn't have labels on our blank Issue template and @kiwookim added the 5 labels as stated in their description. Ki followed the guide correctly in submitting this PR and leaving a link for reviews to easily see his branch with the additions. Thank you for taking this issue @kiwookim .

**Review by chrismenke45 — APPROVED** [review]
Looks good! The labels show up when using the template!

**Pull request merged**
