### PR TITLE
Update Current Team in Projects Page

### LINKED ISSUE #3840: Update Project Profile: Hackforla.org Website
### Overview
As a developer, we need to ensure our project's details are up to date on the HackforLA website. We need to update the "Current Project Team" for the [Hackforla.org Website Project Page](https://www.hackforla.org/projects/website).

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) file and find the `leadership` variable.
- [x] Add the new team members names, roles, slack links, github links, and picture to the end of the `leadership` variable (just after Justin Dingeman). Order matters here. Note how Bonnie is listed first in markdown and thus appears at the top of the "Current Project Team" section.
    - [x] Name: Matt Pereira
Role: Merge Team
GitHub Handle: MattPereira
Slack Member ID: U045XKKB5DH
    - [x] Name: Phillip Sanchez
Role: Merge Team
GitHub Handle: plang-psm
Slack Member ID: U03UG3VCRK6
- [x] Remove 
   - [x] Name: Stephanie Samuels
   - [x] Name: Vaisali Krishna Kumar
- [x] Check the [Hackforla.org Website Project Page](http://localhost:4000/projects/website) on your local development environment to ensure the "Current Project Team" section is properly displaying the changes you made

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [Hackforla.org Website markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find Slack IDs](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

### PR DESCRIPTION
**Pull request by perlaroyerc**
Fixes #3840 

### What changes did you make, and why did you make them?

- Added two new team members to the "leadership" variable, including their name, role, slack, GitHub, and picture.
- Removed 2 team members.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

<details>
  <summary>Visuals before changes are applied</summary>

Screenshot 2023-02-03 at 4 24 05 PM

</details>

<details>
  <summary>Visuals after changes are applied</summary>

Screenshot 2023-02-03 at 4 24 17 PM

</details>

### CODE REVIEW

**Comment by jdingeman** [comment]
ETA: 2/5 EOD
Availability 2 hrs

**Comment by KazushiR** [comment]
ETA: 2/6 EOD
Availability 3 hrs

**Review by jdingeman — APPROVED** [review]
Nice job! Everything looks correct and in the right format.

**Review by KazushiR — APPROVED** [review]
Everything looks good!

**Comment by MarkWiltberger** [comment]
Review ETA: 6 PM ET 3/7/22
Availability: 10AM - 6PM ET Monday - Friday

**Comment by MarkWiltberger** [comment]
PR has already been approved and branch has already been merged. Issue has been closed. I am unable to sync fork, install branch, and view changes in local browser. Please remove me as reviewer for PR. Thanks! @jdingeman

**Pull request merged**
