### PR TITLE
Alt Text Change for Palms Image

### LINKED ISSUE #3102: Change alt text for Palms neighborhood council image in citizen engagement html file
### Overview
We need to ensure that alt text for images adhere to Web Content Accessibility Guidelines (WCAG). For this issue, we will change the alt text for the Palms neighborhood council image on [citizen engagement page](https://www.hackforla.org/citizen-engagement).

### Details
Designers and PMs identified that some alt texts in the Citizen Engagement page should be changed because they are either inaccurate or too long. Ideally, alt text should be descriptive but short and succinct. According to the WCAG page, an accompanying alt text should be short. Additionally, the Functional Accessibility Evaluator (FAE) recommends for alt text to be no more than 100 characters.

### Action Items
- [x] For the file `pages/citizen-engagement.html`, change [line 51](https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L51) for the alt text:

from
```
<img class="org-img" src="/assets/images/citizen-engagement/palms_neighborhood_council.svg" alt="palms neighborhood council logo">
```
to
```
<img class="org-img" src="/assets/images/citizen-engagement/palms_neighborhood_council.svg" alt="Palms Neighborhood Council">
```
- [ ] **For merge team**: Once the pull request associated with this issue is approved and merged, please update and edit epic #3089 by
  - [ ] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue #3089 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- This issue is part of epic #3089 
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

#### File and code links you will need to work on this issue
- Directory to find the page once you have it in your IDE: `pages/citizen-engagement.html`
- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/f2ce8983e77a9b80d455e3677b1cf323092c4f8d/pages/citizen-engagement.html#L51

#### Information about WCAG
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)

### PR DESCRIPTION
**Pull request by d-perez-8**
Fixes #3102

### What changes did you make and why did you make them ?

  - Changed line 51 from `alt="palms neighborhood council logo"` to `alt="Palms Neighborhood Council"`
  - Change were made to adhere to WCAG to make the alt text shorter

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Changing the alt text. No visual changes to the website.

### CODE REVIEW

**Comment by Zak234** [comment]
ETA: July 28
Availability: Anytime

**Comment by d-perez-8** [comment]
Progress: Finished, but I am wondering why there are 2 commits when the  [edit content field and remove type field](https://github.com/hackforla/website/pull/3441/commits/48c94248c6163bb2636743b10705ed6693ef8bd4) should have been merged already.
Blockers: None
Availability: Today and tomorrow until 2 PST
ETA: End of day

**Comment by arpitapandya** [comment]
Availability: 6 Hours
ETA: EOD 2022-07-30

**Comment by Zak234** [comment]
Looks like you might have commits from previous issues on your branch. I'll check in with the other merge team members and see if you need to revert the previous commit or if we can just merge it.

**Review by Zak234 — APPROVED** [review]
Looks good to me. Great work!

**Review by blulady — APPROVED** [review]
The pull request is from [d-perez-8:alt-text-change-3102](https://github.com/d-perez-8/website/tree/alt-text-change-3102) and it goes into [hackforla:gh-pages](https://github.com/hackforla/website). There is a linked issue, it is correct and addressed in the pull request by changing line 51 to alt="Palms Neighborhood Council". There are no changes in the browser and it looks the same when I throw the repo up locally.
Good Job!!

**Pull request merged**
