### PR TITLE
Add toolkit header image credit

### LINKED ISSUE #1505: Add Toolkit page header illustration to Credits page
### Overview
We need to add the vector illustration from the [Toolkit page](https://www.hackforla.org/toolkit/) header to the [Credits](https://www.hackforla.org/credits/) page so that we are following the image use requirements

### Action Items
- [x] View the image credit information in the comment below (scroll down) 
- [x] Add the credit information to the Credits page

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [credit.md template](https://github.com/hackforla/website/wiki/Template-of-a-credit.md-file-(for-Credits-page))

### PR DESCRIPTION
**Pull request by jamesberke**
fixes #1505 
Added the designer-life.yml file to Credits folder

Copied toolkit-hero.svg into Toolkit folder in assets/images

### CODE REVIEW

**Review by qiqicodes — COMMENTED** [review]
=]

**Review by qiqicodes — CHANGES_REQUESTED** [review]
The page looks good, the alt text needs to be a little more descriptive. and "Image of" is not necessary. 

Hope these resources can help you.
https://cliquestudios.com/alt-text/
https://medium.com/nyc-design/how-to-write-effective-alt-tags-for-images-9f888f36992f

**Comment by jbubar** [comment]
It appears like all of them use 'Image of ' 
https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits
Screen Shot 2021-05-07 at 10 41 28 AM

**Comment by jbubar** [comment]
@qiqi, are you ok if I merge this?

**Comment by jbubar** [comment]
Ok.. Im gunna merge this

**Comment by qiqicodes** [comment]
@jbubar yes, we can merge it. we will audit and rewrite the alt text for the yml files in the same directory.

https://github.com/hackforla/website/issues/1526#issue-878559911

**Pull request merged**
