### PR TITLE
Removed Project Profile From Expunge Assist Team

### LINKED ISSUE #5754: Update Project Profile: Expunge Assist (Remove Sheron Virani)
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/expunge-assist.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Under the `leadership` section, remove
```
  - name: Sheron Virani
    role: Product Manager, Research
    links:
      slack: 'https://hackforla.slack.com/team/U041X0628B0'
      github: 'https://github.com/sheronvirani21'
    picture: 'https://avatars.githubusercontent.com/sheronvirani21'
```
- [x] Verify the changes by viewing the Expunge Assist page [^2] in your local environment and include before and after screenshots with your pull request
- [x] Once your pull request is merged, go to #5627 and
  - [x] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #5627 to **Questions / In Review** column and remove the **Dependency** label from it

### Resources/Instructions
- This issue was initiated by #5627
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project page URL: https://www.hackforla.org/projects/expunge-assist

### PR DESCRIPTION
**Pull request by roychan1**
Fixes #5754

### What changes did you make?
  - Removed Sheron Virani's profile from the Expunge Assist leadership section through editing the _projects/expunge-assist.md file.

### Why did you make the changes (we will use this info to test)?
  - The Expunge Assist Project Profile needs to be updated.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

before

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
after

</details>

### CODE REVIEW

**Comment by KyleA99** [comment]
Review ETA: EOD 10/31
Availability: Mon - Tues 5pm-8pm

**Comment by pdimaano** [comment]
ETA: 11/2/23
Availability: Weekday evenings

**Review by pdimaano — APPROVED** [review]
@roychan1 Good job: The branches are correct and the issue is linked. The changes are visible on my system on desktop, mobile and tablet. The correct file was changed and the requested information was removed. Well done!

**Review by KyleA99 — APPROVED** [review]
Code is correctly changed.  No issues observed with visuals.  Great work @roychan1

**Pull request merged**
