### PR TITLE
Fix Capitalization of "Slack" in CONTRIBUTING.MD

### LINKED ISSUE #6918: Fix Capitalization of "Slack" in CONTRIBUTING.MD
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
- https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/CONTRIBUTING.md?plain=1#L11

### Action Items
- [x] Open the file `CONTRIBUTING.MD` in your code editor
- [x] **On Line 11** replace every `slack` with `Slack` **when it's used to refer to the app and the company**, **do not make changes within URLs**.  Do not change any other lines in the file.
- [x] Changes to CONTRIBUTING.md should not be tested locally, rather they need to be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https\://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Release the dependency for this issue in #6844. If all the dependencies have been completed, close that issue.

### Resources/Instructions
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.MD?plain=1

This issue is part of Issue Making Issue #6844 and ER #6163.

### PR DESCRIPTION
**Pull request by dcotelessa**
Fixes #6918

### What changes did you make?
  - capitalize slack to Slack on line 11 of CONTRIBUTING.md

### Why did you make the changes (we will use this info to test)?
  - For Reviewers: Do not review changes locally, rather, review changes at https://github.com/dcotelessa/website-hackforla/blob/fix-capitalization-slack-6918/CONTRIBUTING.md

No visuals on websites changed.

### CODE REVIEW

**Comment by A-Wu5** [comment]
Availability: Tues/Wed 5-7pm
ETA: EOD

**Review by A-Wu5 — APPROVED** [review]
Great job @dcotelessa on this issue! Everything seems to be linked correctly and the change looks good to me.

**Comment by Anahisv23** [comment]
Availability: M - F 11am - 5pm
ETA: EOD

**Review by Anahisv23 — APPROVED** [review]
Hey @dcotelessa, thanks for working on this issue. Everything looks good. The only constructive feedback I have is to make sure to be more descriptive on your PR on why you made the changes you made. Other than that it looks great!

Here's what you did well
- PR links to correct issue 
- into and from branch look good 
- Changed appropriate lines of code and did not modify the word "slack" in the URLs
- Changed the lowercase "s" to and uppercase "S" in the word "Slack"

**Pull request merged**
