### PR TITLE
changed alt text to heart

### LINKED ISSUE #4007: Heart: Update alt text for Heart image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the `Heart` page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within `_projects/heart.md`:

**From:**
```
Programming code icon that reads helping the homeless with code.
```

**To:**
```
Heart
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- https://www.hackforla.org/projects/heart

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/heart.md`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by ftblmagician**
Fixes #4007

### What changes did you make and why did you make them ?

  - Changed the alt text from 'Programming code icon that reads helping the homeless with code.' to 'Heart'

### CODE REVIEW

**Comment by roslynwythe** [comment]
Availability: 3/1 8:30 - 9:30 pm
ETA EOD 3/1

**Review by roslynwythe — APPROVED** [review]
Thank you @ftblmagician for your work on this issue.  The branches are setup correctly, the code change is perfect and the resulting code works in the browser.

**Comment by d-perez-8** [comment]
Availability: 3-6pm PST
ETA: 2 hours

**Review by d-perez-8 — APPROVED** [review]
Thank you for working on this issue! The changes were made as described in the issue. Some things to add:
1. In your pull request, please describe why you made the changes. I know this is a very small issue, but it's a good habit to build. 
2. Please checkoff the action items checkbox you have completed from the issue you were working on. This helps us track your work on an issue and updates the progress meter on that issue.

Great work on your first good issue 👍

**Review by blulady — CHANGES_REQUESTED** [review]
This branch is coming from the correct branch and going into gh-pages. There is a linked issue, it is correct and addressed in the PR by changing alt line 6 to 'heart'. The code looks clean, only one commit and only one file changed. I do agree with @d-perez-8, you should add the why to the initial PR comment (the ... in the upper right hand corner will allow you to edit). As soon as you do that we'll merge the PR.
Good job!!

**Comment by ftblmagician** [comment]
Okay, I added the why to the initial PR comment. Thank you for your comments!

**Review by blulady — APPROVED** [review]
Hey so I was hoping for something like "we changed alt to `Heart` so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity." But it's a minor point, I'll go ahead an merge your pr.

**Pull request merged**
