### PR TITLE
Refactor img Tag in CONTRIBUTING.md

### LINKED ISSUE #7096: img tag refactor in CONTRIBUTING.md Sec 2.4.a
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open the file `CONTRIBUTING.md`
- [x] In Section 2.4.a change
```
<img src="https://user-images.githubusercontent.com/21162229/137636320-e96ef70d-3c85-405e-90d2-ee7b3bba071f.gif" />

```
to
```
<img src="https://user-images.githubusercontent.com/21162229/137636320-e96ef70d-3c85-405e-90d2-ee7b3bba071f.gif">


```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.** 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL (also store the test URL for use in a later step)
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```

### Merge Team
- [x] After closing this issue, check off the dependency in #6453.  If all dependecies have been completed, close #6453 and check off its dependency in #4362.  If all dependencies have been completed in #4362, close it.  

### Resources/Instructions
1. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. This issue is part of #6453

### PR DESCRIPTION
**Pull request by TheManTheMythTheGameDev**
Fixes #7096 

### What changes did you make?
  - Removed a closing slash from the img tag on line 450

### Why did you make the changes (we will use this info to test)?
  - This change makes the tag more consistent with HackForLA's preferred style

For Reviewers: Do not test changes locally, rather test changes at https://github.com/TheManTheMythTheGameDev/website/blob/img-tag-refactor-7096/CONTRIBUTING.md

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

Stylistic change. No visual changes to the website.

### CODE REVIEW

**Review by handshek — APPROVED** [review]
Hey @TheManTheMythTheGameDev, nicely done!

- The branches *from* and *to* are setup correctly
- Link to the issue is included
- There is a clear and concise description of what was done and why
- `No visual changes` is mentioned

Thanks for woking on this issue!

**Review by daras-cu — APPROVED** [review]
Hi @TheManTheMythTheGameDev! Your changes look good, great job.

- Branch set up correctly
- Linked issue in pull request
- Explanation of reason for changes
- Changes were made in line with original issue instructions

**Review by t-will-gillis — CHANGES_REQUESTED** [review]
Hi @TheManTheMythTheGameDev 
Minor request- please delete the empty / unused bullets in "What changes.." and "Why..."
Thanks!

**Comment by TheManTheMythTheGameDev** [comment]
@t-will-gillis Thank you for the feedback. The requested changes have been made.

**Review by t-will-gillis — APPROVED** [review]
Thanks @TheManTheMythTheGameDev

**Pull request merged**
