### PR TITLE
Delete slash on img tag

### LINKED ISSUE #5173: img Tag Refactor: _includes/about-page/about-card-sustainability.html - sdg16.svg
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash () to an img tag without an ending slash () so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sustainability.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/sdg/sdg16.svg" alt="16 Peace, Justice and Strong Institutions" />
```
to
```
<img src="/assets/images/sdg/sdg16.svg" alt="16 Peace, Justice and Strong Institutions" />
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

### PR DESCRIPTION
**Pull request by shavinski**
Fixes #5173

### What changes did you make?
  - Delete ending img tag slash 

### Why did you make the changes (we will use this info to test)?
  - Made the changes in order to make the codebase consistent with using the '/' in img tags 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

***No need for photos since there were no visual changes***

### CODE REVIEW

**Comment by tesiahwang** [comment]
Review ETA: 8/24/2023
Availability: flexible

**Comment by Tomomi-K1** [comment]
Review ETA: 8/23/2023
Availability: 12-5pm Weekday

**Review by Tomomi-K1 — APPROVED** [review]
You are using correct branch, have a linked issue, slash is removed from an appropriate img tag as instructed in the linked issue and your pull request looks great. I have checked using Docker that the visual of the site remains the same.
You have done a great job!

**Review by tesiahwang — APPROVED** [review]
Great job, @shavinski - you are attempting to merge your commit into the correct base branch, are linking the corresponding issue with the proper PR formatting, and your change is applicable & clean!

**Review by adrianang — APPROVED** [review]
Hi @shavinski — the branching is set up correctly, the corresponding issue has been linked, the requested change of removing the ending slash on the image tag on only line 54 has been made, and doing so didn't seem to affect the SDG icon nor any of the other SDG icons within the card. Your PR describes the What/Why of your change clearly and also removed the excess summary and details tags, making it easy to follow.

Thank you for taking up this issue! 🙌🏼

**Pull request merged**
