### PR TITLE
Wins form css

### PR DESCRIPTION
**Pull request by jbubar**
I am making this pr for a design review.. I started working on the css for this and realized that I was making too many decisions. 

Here is the [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)

<details>
    <summary>1st frame</summary>

    
screencapture-localhost-4000-share-your-wins-2021-03-23-13_14_58

</details>

<details>
    <summary>2nd frame</summary>

    
screencapture-localhost-4000-share-your-wins-2021-03-23-13_15_13

</details>

<details>
    <summary>3rd frame</summary>

    
screencapture-localhost-4000-share-your-wins-2021-03-23-13_15_23

</details>

<details>
    <summary>4th frame</summary>

    
screencapture-localhost-4000-share-your-wins-2021-03-23-13_15_43

</details>

<details>
    <summary>5th frame</summary>

    
screencapture-localhost-4000-share-your-wins-2021-03-23-13_15_56

</details>

Let me know if I am on the right track :))

### CODE REVIEW

**Comment by daniellex0** [comment]
@jbubar so sorry about the delay, I was out of town.. Just to confirm, is this basically moving the survey to the website instead of Google survey?

The styling looks great, I'm just not sure how much styling guidance I am supposed to give- if it's part of the website, we might need to standardize the button / input fields to look more like the buttons / input fields on our site. But if it's not completely part of our site, there may be no need to standardize. Even if it is part of the site, there might be no need since this is only for surveys..?

I'm not sure, basically I think I need a little more context about this to give informed feedback!

Also I would maybe make the input fields for Full name and email address a little less wide- closer to what it looks like on the google form (plus just FYI in the full name field, it says enter "fullname")

**Comment by jbubar** [comment]
Hey. Sorry about letting this hang out for so long. Thanks you @Sihemgourou for reminding me about this.. Not sure how to move forward exactly. Looks good to me, but it would be great if a designer could look over it

**Comment by jbubar** [comment]
@daniellex0 yes, akib made the form because google forms would not let you have a drop down for if you enter your linkedin or github. 
<details>
    <summary>screenshot</summary>

Screen Shot 2021-06-13 at 9 44 26 AM


</details>

It is a part of the site

**Comment by Sihemgourou** [comment]
Hey @jbubar could you give screenshots of the most recent frames?

**Comment by alyssabenipayo** [comment]
@jbubar Hey! Just reviewed your request based on the Figma and screenshots you provided back in March. I do second @Sihemgourou's inquiry - have we made any changes to the styling since then?

A couple of things:
- Have we updated the overview part to *required? I recall during the meeting today that we require people to add an overview.
- Question for @daniellex0 : Do we want to make the background behind the cards beige as we have for our website? Or this a unique case that we leave the blue background for the Wins form?

Other than that, if we based the review on the screenshots from earlier, you're on the right track!

**Comment by abenipa3** [comment]
@jbubar Hey! Just reviewed your request based on the Figma and screenshots you provided back in March. 

Here's what I see when I pulled it up on my computer, assuming these are the latest updates. I've also added comments if needed. (Tagging @Sihemgourou to show what we're seeing.)

Desktop Version:
<details>
    <summary>1st frame</summary>

image

</details>

<details>
    <summary>2nd frame</summary>

I'm able to see the dropdown for LinkedIn. It works when I clicked "Next" after I selected "Yes" and "No."
image
image

<br> 

The dropdown didn't appear for GitHub. It also won't let me click "Next" after I inputted the GitHub link only.
image

</details>

<details>
    <summary>3rd frame</summary>

image

</details>

<details>
    <summary>4th frame</summary>

image


</details>

<details>
    <summary>5th frame</summary>

image


</details>

Mobile Version:

<details>
    <summary>1st frame</summary>

image

</details>

<details>
    <summary>2nd frame</summary>

image
image

Github Dropdrow doesn't work on mobile as well as the "Next" Button.

image

</details>


<details>
    <summary>3rd frame</summary>

Typo: Business is misspelled.

image

</details>

<details>
    <summary>4th frame</summary>

image

</details>

<details>
    <summary>5th frame</summary>

image

</details>

Additional comments:
I recall during today's meeting that we want to require people to add to the overview. I was able to proceed without adding an overview, so we'll need to require people to fill out the Overview part.

Question for @daniellex0 : Do we want to make the background behind the cards beige as we have for our website? Or this a unique case that we leave the blue background for the Wins form?

Other than that, you're on the right track! Great job 🎉

**Review by abenipa3 — CHANGES_REQUESTED** [review]
Looks good! Please view my previous comment.

**Comment by jbubar** [comment]
@alyssabenipayo Great review!!! I fixed the github error checking, and made the overview required. Is there anything I missed?

**Comment by jbubar** [comment]
Also, is the blue underline thing what we want? when a input type text field is focused, I had it underlined blue and with a light gray back ground

**Review by abenipa3 — APPROVED** [review]
Nice job! The dropdown appears under Github and works both when we select either "Yes" or "No" 🎉

**Comment by abenipa3** [comment]
> Also, is the blue underline thing what we want? when a input type text field is focused, I had it underlined blue and with a light gray back ground

That's a good question - so far I don't see a styling requirement for the text field? (Please feel free to correct me if I'm wrong or if you have a suggestion, @daniellex0.) 

image

I also think it looks good unless we want to update the blue underline to a HfLA Pink Color (#FA114F) like this. Any thoughts?
image

**Review by daniellex0 — APPROVED** [review]
Thanks for the screenshots Alyssa, this looks great @jbubar ! I think it's ok to keep the underline blue for now, because the pink tends to look a little bit like red and might make the user think they did something wrong lol. Also the blue background is actually pretty standard for several of our pages (like [Events](https://www.hackforla.org/events/) , [Getting Started](https://www.hackforla.org/getting-started), etc) - we tend to trade off the beige/blue backgrounds depending on the content of the page (sometimes the blue is too stark). But here I think it looks good!

Honestly I think this is good to go for MVP. We can adjust buttons/spacing etc down the line, but those adjustments can be made in separate issues since they're really not urgent or anything, this looks great.

**Comment by daniellex0** [comment]
I will say, maybe let it go live but don't replace the Google form on the wins page with it quite yet- let's test it out a little and make sure everything is good (possibly a few styling edits) before we replace the Google form (if possible).

**Comment by aliibsin** [comment]
merged during dev meeting

**Pull request merged**
