### PR TITLE
Added github-handle for Farah Khan in home-unite-us.md

### LINKED ISSUE #7185: Add github-handle for Farah Khan in home-unite-us.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/home-unite-us.md` in the IDE
- [x] Replace:
```
- name: Farah Khan
```
with
```
- name: Farah Khan
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md?plain=1
Project Webpage: https://www.hackforla.org/projects/home-unite-us.md

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by codyyjxn**
Fixes #7185 

### What changes did you make?
  - I updated the `_projects/home-unite-us.md` file by inserting a new key, 'github-handle,' directly beneath the 'name: Farah Khan' 

### Why did you make the changes (we will use this info to test)?
  - I made this change to streamline the project file by introducing a 'github-handle' key, which replaces the need for separate 'github' and 'picture' entries.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
- No screenshots since adding a variable did not create any new visual change

### CODE REVIEW

**Comment by 8alpreet** [comment]
Review ETA: EOD Tue Aug 20
Availability: Mon to Fri; 3 p.m. to 7 p.m.

**Comment by codyyjxn** [comment]
I have closed the other pr that I first set but now I have created the new pr with the write commits and the issue that I was assigned to do.

**Comment by santiseccovidal** [comment]
Review ETA: 2 PM 8/20/24
Availability: 8-3 PM Tuesday 8/20/24

**Review by santiseccovidal — APPROVED** [review]
Hi @codyyjxn thanks for working on this!

Branches are correct, no visual changes and the code was correctly modified, with the right spacing.

Great job!

**Comment by codyyjxn** [comment]
Thank you! Can I work on another issue ?

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @codyyjxn,

### What went well:
- Into branch is set up correctly.
- PR is linked to the correct issue number.
- Branch is named correctly
- Only relevant lines of code were changed.
- You answered the "What.." section well

### Changes needed:
1. "Why.." section:
    - I am confused by the "Update related logic and documentation" portion of your words. What is the related logic and documentation being updated?
    - The rest of your description regarding use of github handle and project consistency is fine.
    - this section should almost be a short summary of the issue.
    - after reading it, I should quickly know why the issue was created thus why this PR was created.

**Comment by codyyjxn** [comment]
> Hi @codyyjxn,
> 
> ### What went well:
> * Into branch is set up correctly.
> * PR is linked to the correct issue number.
> * Branch is named correctly
> * Only relevant lines of code were changed.
> * You answered the "What.." section well
> 
> ### Changes needed:
> 1. "Why.." section:
>    
>    * I am confused by the "Update related logic and documentation" portion of your words. What is the related logic and documentation being updated?
>    * The rest of your description regarding use of github handle and project consistency is fine.
>    * this section should almost be a short summary of the issue.
>    * after reading it, I should quickly know why the issue was created thus why this PR was created.

Thank you for your feedback. I've implemented the changes as suggested and revised the context accordingly. Please review it and let me know if there are any areas that could be further clarified. I'm open to making adjustments to ensure everything is as clear as possible.

**Comment by codyyjxn** [comment]
@8alpreet 
Thank you for your feedback. I've implemented the changes as suggested and revised the context accordingly. Please review it and let me know if there are any areas that could be further clarified. I'm open to making adjustments to ensure everything is as clear as possible.

**Comment by 8alpreet** [comment]
> Thank you! Can I work on another issue ?

We can only work on one issue at a time. This one must be merged before you can move on.

**Comment by 8alpreet** [comment]
Hi, I appreciate you being open to feedback and making changes! Your updated "Why.." section is more like the "What.." section now because you're describing what you did.

Imagine their is a future issue where users are accidentally clicking delete instead of save. Let's say your solution to the problem, meaning your **what**, is to make the Save button green and to make/keep the Delete button gray. Your reasoning for the change (green is associated with good/save; green draws attention more than grey) would go into the **why** section.

I know the differences in this GFI aren't as obvious and it seems unnecessary to practically restate what the issue itself says.

I encourage you to give it another shot, but you can consult the following PR if you're unsure or stuck: [LINK](https://github.com/hackforla/website/pull/7293).

**Review by santiseccovidal — CHANGES_REQUESTED** [review]
I must say I missed paying attention to the sections "**What changes did you make?**" and "**Why did you make the changes (we will use this info to test)?**".

As @8alpreet mentions the idea behind this questions is to give a brief summary of what was done and the reasons for why the changes were made.

I would add the following, the "**What section**" would be clearer if you stated what was done and omitted "has been successfully" or other further descriptions involving a sort of "examination" of what was done. That would be eventually determined by the reviewer and merge team.

It's better to be more concise I believe. We are all here to learn. Me myself made the mistake of not reading carefully the description of what was done.

But still your code was clear and the change was done correctly.

**Comment by codyyjxn** [comment]
@santisecco 
Thank you for your feedback. I've implemented the changes as suggested and revised the context accordingly. Please review it and let me know if there are any areas that could be further clarified. I'm open to making adjustments to ensure everything is as clear as possible.

**Review by 8alpreet — APPROVED** [review]
Everything looks great now. You did a great job applying the feedback!

**Comment by roslynwythe** [comment]
@santisecco @santisecco please re-review this PR.  Thank you

**Comment by codyyjxn** [comment]
@Satenik-Ba please re-review this PR. Thank you

**Review by santiseccovidal — APPROVED** [review]
Hi @codyyjxn thank you very much!
Your description of the "what" is very precise and clear.
The changes are great

**Comment by codyyjxn** [comment]
Thank you! 👍🏼

**Pull request merged**
