### PR TITLE
Update Citizen engagement page to show missing message

### LINKED ISSUE #3757: Citizen Engagement page: Display a message if missing program area detailed info
### Overview
On the Citizen Engagement webpage [1], we want to display a message on a project's program area card if the project is missing program area detailed information so 
- we make sure the page doesn't break and
- we maintain a professional-looking website.

#### Developer
- [x] Read Citizen Engagement wiki page [2]
- [x] If a project's Markdown file is missing one of the following program area detailed information fields: `problem`, `solution`, `impact`, `sdg`, `card-image-src`, `sdg-image-src`, then change the code in `_includes/citizen-engagement-cards.html` [3] so that the card on the Citizen Engagement webpage should show the project's name and dynamically display the message:
  ```
  We are currently drafting the Problem, Solution and Impact statements for this project.
  ```
  - [x] Make sure the message is displayed for any future projects that are added and are missing program area info.
    - Keep in mind missing program area info can mean `problem`, `solution`, `impact`, `sdg`, `card-image-src`, or `sdg-image-src` fields 
      - a) are **not** in a project's Markdown file at all 
      OR
      - b) the fields exist but are left blank in a project's Markdown file.
  - [x] To style the message, use existing SCSS classes when possible, such as for Typography. See `Design System in Figma` [4] for more info
    - [x] If you need to add SCSS code, add it to `_sass/components/_citizen_engagement.scss` [5]
  - [x] Using developer tools, make sure the message looks good in desktop, tablet, and mobile views
- [ ] For testing your code and getting approval from the Stakeholder Rep,
  - [x] In `adopt-civic-art.md` [6] and `curbmap.md` [7] in the `_projects` directory, you can **temporarily** change `visible: false` to `visible: true` in order to see what the card will look like with the message.
  - [x] Show how the message looks on the card to the Stakeholder Rep and get the Stakeholder Rep's approval. 
    - See the Website Team's project information page [8] for who the Stakeholder Rep is.
  - [x] Before opening a pull request, please make sure to change `visible: true` back to `visible: false` in `adopt-civic-art.md` and `curbmap.md` so that the curbmap and ArtWatcher projects are **not** visible.

#### Merge Team, Technical Lead, or Product Manager
- [x] Once the pull request associated with this issue is merged, go to issue #3756 and check if all the issues listed under the `Dependency` section are closed. If they are all closed, move that issue (#3756) into the `New Issue Approval` column, remove the `Dependency` label on it, and add a `ready for dev lead` label to it.

### Resources/Instructions
- [1] [Citizen Engagement webpage](https://www.hackforla.org/citizen-engagement)
- [2] [Citizen Engagement wiki page](https://github.com/hackforla/website/wiki/Citizen-Engagement-page)
- [3] [_includes/citizen-engagement-cards.html](https://github.com/hackforla/website/blob/gh-pages/_includes/citizen-engagement-cards.html): HTML file that provides the layout/format for each card on the Citizen Engagement page
- [4] [Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3&t=IwD8OB61z2yqo4YR-0)
- [5] [_sass/components/_citizen_engagement.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_citizen_engagement.scss): Current SCSS file for the Citizen Engagement page
- [6] [_projects/adopt-civic-art.md](https://github.com/hackforla/website/blob/gh-pages/_projects/adopt-civic-art.md?plain=1)
- [7] [_projects/curbmap.md](https://github.com/hackforla/website/blob/gh-pages/_projects/curbmap.md?plain=1)
- [8] [Website Team's project information page](https://www.hackforla.org/projects/website)
- Issue #3756 is dependent on this issue being completed

### PR DESCRIPTION
**Pull request by Jaretzbalba**
Fixes #3757 

### What changes did you make and why did you make them ?

  - Updated HTML for citizen engagement page to dynamically show missing info message if conditions are met
  - Added scss code to properly display missing info message 
  - Checked with stakeholder to get new changes approved

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

<details>
<summary>Mobile</summary>

mobile

</details>

<details>
<summary>Tablet</summary>

tablet

</details>

<details>
<summary>Desktop</summary>

desktop

</details>

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
<details>
<summary>Mobile</summary>

mobile-citizen-engagement

</details>

<details>
<summary>Tablet</summary>

tablet-citizen-engagement

</details>

<details>
<summary>Desktop</summary>

desktop-citizen-engagement

</details>
</details>

### CODE REVIEW

**Comment by Thinking-Panda** [comment]
Availability: M-F 10 AM - 3 PM
ETA: 3/1

**Comment by mademarc** [comment]
Review ETA:  7:40PM 2/28/23
Availability: 1Hr

**Review by mademarc — COMMENTED** [review]
@Jaretzbalba The media queries looks well done so it makes the code work :)

**Comment by Suman2795** [comment]
Review ETA: 1 Mar 2023
Availability : 1 hour

**Review by Thinking-Panda — COMMENTED** [review]
Nice work @Jaretzbalba ! The CSS is very effective in all viewports. Just wanted to make sure why the .bash_profile.swp file is added into this pull request.

**Comment by Jaretzbalba** [comment]
@Thinking-Panda Thank you! And I'm not actually quite sure what that file is or how to get rid of it as I can't see it in my own code base.

**Comment by roslynwythe** [comment]
> @Thinking-Panda Thank you! And I'm not actually quite sure what that file is or how to get rid of it as I can't see it in my own code base.

Hi @Jaretzbalba assuming you want to retain the file locally, and you just want to remove it from the branch, you could try 
`git rm --cached .bash_profile.swp `

**Review by Suman2795 — COMMENTED** [review]
Great Job on doing this task @Jaretzbalba ! I have similar question about .bash_profile.swp as @Thinking-Panda but the changes are nicely done as per the action items in the issue.

**Comment by Jaretzbalba** [comment]
@Thinking-Panda @mademarc @Suman2795 I was able to remove the .swp file so everything should be good now. Thank you!

**Review by Thinking-Panda — APPROVED** [review]
@Jaretzbalba ,thank you for making the changes. Website works good on local machine.

**Review by Suman2795 — APPROVED** [review]

**Review by t-will-gillis — APPROVED** [review]
Hi @Jaretzbalba Great job with coordinating the changes with everyone! Only as notes: In Docker I can see that the hrefs at the card titles are functional and that for Open Community Survey, the Impact section has the original message and not 'Dolerem ipsum...' seen in the 'after' screenshots.

Looks good thanks!

**Pull request merged**
