### PR TITLE
Update alt text to adhere to WCAG - Issue 3869

### LINKED ISSUE #3869: 311 Data: Update alt text for 311 Data image to adhere to WCAG
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text for the `311 Data` image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image alt property value within _projects/311-data.md:

**From:**
```
alt: '311 data logo.'
```

**To:**
```
alt: '311 Data'
```

**For PM, Merge Team, or Tech Lead**
- [x] Once the pull request associated with this issue is approved and merged, please update and edit epic #3866 by
  - [x] Checking off the dependency for this issue
  - [ ] If all dependencies are checked off, please move issue  to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- 311 Data Page: https://www.hackforla.org/projects/311-data

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_projects/311-data.md`
- See the source file code on the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md
- This issue is part of epic #3866

#### Background information about the Jekyll framework (optional reading)
- [Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

#### Information about WCAG and alt text (optional reading)
- [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)
- [Web Accessibility Tutorials: Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)
- [WCAG section on alt text](https://www.w3.org/WAI/WCAG21/Techniques/html/H37.html)
- [Alt text decision Tree ](https://www.w3.org/WAI/tutorials/images/decision-tree/)
- [FAE rule 4: alt text should be less than 100 characters](https://fae.disability.illinois.edu/rulesets/IMAGE_4_EN/)

### PR DESCRIPTION
**Pull request by hang-justin**
Fixes #3869 

### What changes did you make and why did you make them ?

  - Updated img alt text
  - Updated to adhere to Web Content Accessibility Guidelines (WCAG)
  - WCAG: Provide clear and descriptive alt text

**Before:**
```
alt: '311 data logo.'
```  
**After:**
```
alt: '311 Data'
```

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)
Updating img alt text. No visual changes to the website.

### CODE REVIEW

**Review by RyanGehris — APPROVED** [review]
Great job fixing the alt text to comply with the current WCAG standards. The changes you made were successful on my local computer. Thank you for working on this issue!

**Comment by janice87** [comment]
Review ETA: 9 PM EST 3/30/22
Availability: 5-9 PM 3/30/22

**Comment by mademarc** [comment]
Review ETA: 3/28/2023
Availability: 7:15PM

**Review by mademarc — APPROVED** [review]
Hey @hang-justin  the logo variable was removed correctly on the alt element so good job.

**Review by janice87 — APPROVED** [review]
The pull request is done in the correct branch and the issue is linked correctly. The alt text was updated to adhere to WCAG and there are no visual changes made. Good job on this issue, it is approved!

**Pull request merged**
