### PR TITLE
Add Github Handle for Gala Stojnic in design-systems.md

### LINKED ISSUE #7287: Add github-handle for Gala Stojnic in design-systems.md
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/design-systems.md` in the IDE
- [x] Replace:
```
- name: Gala Stojnic
```
with
```
- name: Gala Stojnic
  github-handle:
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md?plain=1
Project Webpage: https://www.hackforla.org/projects/design-systems

- This issue is part of #5441.

### PR DESCRIPTION
**Pull request by izma-mujeeb**
Fixes #7287 

### What changes did you make?
  
  - Using spaces, I added a variable called github-handle to hold Gala Stojnic's github handle 

### Why did you make the changes (we will use this info to test)?
  
  - The reason why I needed to add a variable to hold the github-handle was because the github-handle variable is used to replace each member in the leadership team's github and picture variables in the future. By replacing the github and picture variables, I am ensuring that the code is efficient and reducing any redundant code in the project file. 

### Screenshots of Proposed Changes To The Website (if any, please do not include screenshots of code changes)
 
- No visual changes to the website

### CODE REVIEW

**Review by vorleakyek — APPROVED** [review]
It looks good! Approved! 
One minor thing, including the person's name in the branch name for clarity might be good. 
Thanks for contributing!

**Comment by 8alpreet** [comment]
**Review ETA:** EOD Sep 4, 2024
**Availability:** 3pm to 7pm weekdays

**Review by 8alpreet — CHANGES_REQUESTED** [review]
Hi @izma-mujeeb,

What went well:
* PR title is descriptive and concise.
* Branch is named correctly.
* Correct line of code was changed.
* Issue is linked in PR comment.
* What section is answered well.

Changes Needed:
1. Why section:
    * I appreciate the level of detail you provided in this section; however, it is slightly inaccurate. The `github-handle` variable is not used to hold github and picture variables. Rather, that variable will replace both of the variables in the future.

**Review by 8alpreet — APPROVED** [review]
Looks good. Thanks for applying the feedback!

**Review by k-cardon — APPROVED** [review]
Everything looks good to go! Branch is correct, line added correctly with spaces not tab, no visual changes to the site.

**Pull request merged**
